iccDEV: CIccTagCreator Class Reference
CIccTagCreator Class Reference
#include <IccTagFactory.h>
Public Member Functions
~CIccTagCreator ()
Static Public Member Functions
static CIccTag * CreateTag (icTagTypeSignature tagTypeSig)
static icTagSignature GetTagNameSig (const icChar *szName)
static const icChar * GetTagSigName (icTagSignature tagTypeSig)
static icTagTypeSignature GetTagTypeNameSig (const icChar *szName)
static const icChar * GetTagTypeSigName (icTagTypeSignature tagTypeSig)
static IIccTagFactory * PopFactory ()
static void PushFactory (IIccTagFactory *pFactory)
Private Member Functions
CIccTagCreator ()
CIccTag * DoCreateTag (icTagTypeSignature tagTypeSig)
icTagSignature DoGetTagNameSig (const icChar *szName)
const icChar * DoGetTagSigName (icTagSignature tagSig)
icTagTypeSignature DoGetTagTypeNameSig (const icChar *szName)
const icChar * DoGetTagTypeSigName (icTagTypeSignature tagTypeSig)
IIccTagFactory * DoPopFactory (bool bAll=false)
void DoPushFactory (IIccTagFactory *pFactory)
Static Private Member Functions
static CIccTagCreator * GetInstance ()
Private Attributes
CIccTagFactoryList factoryStack
Static Private Attributes
static CIccTagCreatorPtr theTagCreator
Detailed Description
Class: CIccTagCreator
Purpose: CIccTagCreator uses a singleton pattern to provide dynamically upgradeable CIccTag derived object creation based on tag signature.
Constructor & Destructor Documentation
~CIccTagCreator()
CIccTagCreator::~CIccTagCreator ()
{
  IIccTagFactory *pFactory = DoPopFactory(true);
  while (pFactory) {
    delete pFactory;
    pFactory = DoPopFactory(true);
  }
}
References DoPopFactory().
CIccTagCreator()
CIccTagCreator::CIccTagCreator () inline private
Only GetInstance() can create the signleton
{ }
Member Function Documentation
CreateTag()
static CIccTag * CIccTagCreator::CreateTag (icTagTypeSignature tagTypeSig) inline static
Function: CreateTag(tagTypeSig) Create a tag of type tagTypeSig.
Parameter(s): tagTypeSig = signature of the ICC tag type for the tag to be created
Returns a new CIccTag object of the given signature type. Each factory in the factoryStack is used until a factory supports the signature type.
      { return CIccTagCreator::GetInstance()->DoCreateTag(tagTypeSig); }
References DoCreateTag(), and GetInstance().
Referenced by CIccTag::Create(), and CIccTagArray::Read().
DoCreateTag()
CIccTag * CIccTagCreator::DoCreateTag (icTagTypeSignature tagTypeSig) private
{
  CIccTagFactoryList::iterator i;
  CIccTag *rv = NULL;
  for (i=factoryStack.begin(); i!=factoryStack.end(); i++) {
    rv = (*i)->CreateTag(tagTypeSig);
    if (rv)
      break;
  }
  return rv;
}
References IIccTagFactory::CreateTag(), and factoryStack.
Referenced by CreateTag().
DoGetTagNameSig()
icTagSignature CIccTagCreator::DoGetTagNameSig (const icChar * szName) private
{
  CIccTagFactoryList::iterator i;
  icTagSignature rv;
  for (i = factoryStack.begin(); i != factoryStack.end(); i++) {
    rv = (*i)->GetTagNameSig(szName);
    if (rv!=icSigUnknownTag)
      return rv;
  }
  return icSigUnknownTag;
}
References factoryStack, and IIccTagFactory::GetTagNameSig().
Referenced by GetTagNameSig().
DoGetTagSigName()
const icChar * CIccTagCreator::DoGetTagSigName (icTagSignature tagSig) private
{
  CIccTagFactoryList::iterator i;
  const icChar* rv;
  for (i=factoryStack.begin(); i!=factoryStack.end(); i++) {
    rv = (*i)->GetTagSigName(tagSig);
    if (rv)
      return rv;
  }
  return NULL;
}
References factoryStack, and IIccTagFactory::GetTagSigName().
Referenced by GetTagSigName().
DoGetTagTypeNameSig()
icTagTypeSignature CIccTagCreator::DoGetTagTypeNameSig (const icChar * szName) private
{
  CIccTagFactoryList::iterator i;
  icTagTypeSignature rv;
  for (i = factoryStack.begin(); i != factoryStack.end(); i++) {
    rv = (*i)->GetTagTypeNameSig(szName);
    if (rv!=icSigUnknownType)
      return rv;
  }
  return icSigUnknownType;
}
References factoryStack, and IIccTagFactory::GetTagTypeNameSig().
Referenced by GetTagTypeNameSig().
DoGetTagTypeSigName()
const icChar * CIccTagCreator::DoGetTagTypeSigName (icTagTypeSignature tagTypeSig) private
{
  CIccTagFactoryList::iterator i;
  const icChar* rv;
  for (i=factoryStack.begin(); i!=factoryStack.end(); i++) {
    rv = (*i)->GetTagTypeSigName(tagTypeSig);
    if (rv)
      return rv;
  }
  return NULL;
}
References factoryStack, and IIccTagFactory::GetTagTypeSigName().
Referenced by GetTagTypeSigName().
DoPopFactory()
IIccTagFactory * CIccTagCreator::DoPopFactory (bool bAll = false) private
{
//  int nNum = (bAll ? 0 : 1);
  if (factoryStack.size()>0) {
    CIccTagFactoryList::iterator i=factoryStack.begin();
    IIccTagFactory* rv = (*i);
    factoryStack.pop_front();
    return rv;
  }
  return NULL;
}
References factoryStack.
Referenced by ~CIccTagCreator(), and PopFactory().
DoPushFactory()
void CIccTagCreator::DoPushFactory (IIccTagFactory * pFactory) private
{
  factoryStack.push_front(pFactory);
}
References factoryStack.
Referenced by GetInstance(), and PushFactory().
GetInstance()
CIccTagCreator * CIccTagCreator::GetInstance () static private
Function: GetInstance() Private static function to access singleton CiccTagCreator Object.
Parameter(s): None
Returns the singleton CIccTagCreator object. It will allocate a new one and push a single CIccSpecTag Factory object onto the factory stack if the singleton has not been intialized.
{
  if (!theTagCreator.get()) {
    theTagCreator = CIccTagCreatorPtr(new CIccTagCreator);
    theTagCreator->DoPushFactory(new CIccSpecTagFactory);
  }
  return theTagCreator.get();
}
References DoPushFactory(), and theTagCreator.
Referenced by CreateTag(), GetTagNameSig(), GetTagSigName(), GetTagTypeNameSig(), GetTagTypeSigName(), PopFactory(), and PushFactory().
GetTagNameSig()
static icTagSignature CIccTagCreator::GetTagNameSig (const icChar * szName) inline static
Function: GetTagNameSig(szTagName) Get signature from tag display name.
Parameter(s): szTagName = name of tag
Returns tag signature of tag if tag name is recognized by the factory, icSigUnknownTag if the tag name is not recognized.
  {
    return CIccTagCreator::GetInstance()->DoGetTagNameSig(szName);
  }
References DoGetTagNameSig(), and GetInstance().
Referenced by icGetTagNameSig().
GetTagSigName()
static const icChar * CIccTagCreator::GetTagSigName (icTagSignature tagTypeSig) inline static
Function: GetTagSigName(tagSig) Get display name of tagSig.
Parameter(s): tagSig = signature of the ICC tag to get a name for
Returns ptr to string containing name of tag type if it is recognized by any factory, NULL if all factories do not create tagTypeSig tags.
      { return CIccTagCreator::GetInstance()->DoGetTagSigName(tagTypeSig); }
References DoGetTagSigName(), and GetInstance().
Referenced by CIccInfo::GetTagSigName(), and icGetTagSigName().
GetTagTypeNameSig()
static icTagTypeSignature CIccTagCreator::GetTagTypeNameSig (const icChar * szName) inline static
Function: GetTagTypeNameSig(szTypeName) Get signature based on display name of tag type.
Parameter(s): szTypeName = name of the ICC tag type to get a signature for
Returns tag type signature of tag type name if type name is recognized by the factory, icSigUnknownType if the type name is not recognized.
  {
    return CIccTagCreator::GetInstance()->DoGetTagTypeNameSig(szName);
  }
References DoGetTagTypeNameSig(), and GetInstance().
Referenced by icGetTypeNameTagSig().
GetTagTypeSigName()
static const icChar * CIccTagCreator::GetTagTypeSigName (icTagTypeSignature tagTypeSig) inline static
Function: GetTagTypeSigName(tagTypeSig) Get display name of tagTypeSig.
Parameter(s): tagTypeSig = signature of the ICC tag type to get a name for
Returns ptr to string containing name of tag type if it is recognized by any factory, NULL if all factories do not create tagTypeSig tags.
      { return CIccTagCreator::GetInstance()->DoGetTagTypeSigName(tagTypeSig); }
References DoGetTagTypeSigName(), and GetInstance().
Referenced by CIccInfo::GetTagTypeSigName(), and icGetTagSigTypeName().
PopFactory()
static IIccTagFactory * CIccTagCreator::PopFactory () inline static
Function: PopFactory() Remove the top IIccTagFactory from the stack of tag factories tracked by the system.
Parameter(s): None
Returns the top IIccTagFactory from the stack of tag factories tracked by the system. The returned tag factory is no longer owned by the system and needs to be deleted to avoid memory leaks.
Note: The initial CIccSpecTagFactory cannot be popped off the stack.
      { return CIccTagCreator::GetInstance()->DoPopFactory(); }
References DoPopFactory(), and GetInstance().
PushFactory()
static void CIccTagCreator::PushFactory (IIccTagFactory * pFactory) inline static
Function: PushFactory(pFactory) Add an IIccTagFactory to the stack of tag factories tracked by the system.
Parameter(s): pFactory = pointer to an IIccTagFactory object to add to the system. The pFactory must be created with new, and will be owned CIccTagCreator until popped off the stack using PopFactory(). Any factories not popped off will be taken care of properly on application shutdown.
      { CIccTagCreator::GetInstance()->CIccTagCreator::DoPushFactory(pFactory); }
References DoPushFactory(), and GetInstance().
Referenced by main().
Field Documentation
factoryStack
CIccTagFactoryList CIccTagCreator::factoryStack private
Referenced by DoCreateTag(), DoGetTagNameSig(), DoGetTagSigName(), DoGetTagTypeNameSig(), DoGetTagTypeSigName(), DoPopFactory(), and DoPushFactory().
theTagCreator
std::unique_ptr< CIccTagCreator > CIccTagCreator::theTagCreator static private
Referenced by GetInstance().
The documentation for this class was generated from the following files:
IccProfLib/IccTagFactory.h
IccProfLib/IccTagFactory.cpp