iccDEV: IIccArrayFactory Class Reference
IIccArrayFactory Class Reference abstract
#include <IccArrayFactory.h>
Public Member Functions
virtual ~IIccArrayFactory ()
virtual IIccArray * CreateArray (icArraySignature arrayTypeSig, CIccTagArray *pTagArray=NULL)=0
virtual icArraySignature GetArraySig (const icChar *arrayName)=0
virtual bool GetArraySigName (std::string &arrayName, icArraySignature arrayTypeSig, bool bFillUnknown)=0
Detailed Description
Class: IIccArrayFactory
Purpose: IIccArrayFactory is a factory pattern interface for CIccArray creation. This class is pure virtual.
Constructor & Destructor Documentation
~IIccArrayFactory()
virtual IIccArrayFactory::~IIccArrayFactory () inline virtual
{}
Member Function Documentation
CreateArray()
virtual IIccArray * IIccArrayFactory::CreateArray (icArraySignature arrayTypeSig, CIccTagArray * pTagArray = NULL) pure virtual
Function: CreateArray(arrayTypeSig) Create a element of type arrayTypeSig.
Parameter(s): arrayTypeSig = signature of the ICC element type for the element to be created
Returns a new IIArrayObject object of the given signature type. If the element factory doesn't support creation of array handlers of type arrayTypeSig then it should return NULL.
Implemented in CIccBasicArrayFactory.
Referenced by CIccArrayCreator::DoCreateArray().
GetArraySig()
virtual icArraySignature IIccArrayFactory::GetArraySig (const icChar * arrayName) pure virtual
Function: GetArraySig(arrayName) Get signature associate with display name arrayName handler
Parameter(s): arrayName = string to find signature for
Returns true if arraySig is recognized by the factory, false if the factory doesn't create arraySig arrays.
Implemented in CIccBasicArrayFactory.
Referenced by CIccArrayCreator::DoGetArraySig().
GetArraySigName()
virtual bool IIccArrayFactory::GetArraySigName (std::string & arrayName, icArraySignature arrayTypeSig, bool bFillUnknown) pure virtual
Function: GeArraySigName(structTypeSig) Get display name of arrayTypeSig.
Parameter(s): arrayName = string to put struct name into, arrayTypeSig = signature of the ICC struct type to get a name for bFindUnknown = fills arrayName if strutTypeSig is unknown
Returns true if arraySig is recognized by the factory, false if the factory doesn't create arrayTypeSig arrays.
Implemented in CIccBasicArrayFactory.
Referenced by CIccArrayCreator::DoGetArraySigName().
The documentation for this class was generated from the following file:
IccProfLib/IccArrayFactory.h