iccDEV: IIccArray Class Reference
IIccArray Class Reference abstract
#include <IccTagComposite.h>
Public Member Functions
virtual ~IIccArray ()
virtual void Describe (std::string &sDescription, int nVerboseness) const
virtual const icChar * GetClassName () const =0
CIccTagArray * GetTagArray ()
virtual IIccArray * NewCopy (CIccTagArray *pNewTagArray) const =0
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const =0
Protected Attributes
CIccTagArray * m_pTagArray
Detailed Description
Class: IIccArray
Purpose: The interface for Tag Array handler
Constructor & Destructor Documentation
~IIccArray()
virtual IIccArray::~IIccArray () inline virtual
{}
Member Function Documentation
Describe()
virtual void IIccArray::Describe (std::string & sDescription, int nVerboseness) const inline virtual
Reimplemented in CIccArrayUnknown, CIccArrayColorantInfo, and CIccArrayNamedColor.
{ }
GetClassName()
virtual const icChar * IIccArray::GetClassName () const pure virtual
Implemented in CIccArrayUnknown, CIccArrayColorantInfo, and CIccArrayNamedColor.
GetTagArray()
CIccTagArray * IIccArray::GetTagArray () inline
{ return m_pTagArray; }
References m_pTagArray.
NewCopy()
virtual IIccArray * IIccArray::NewCopy (CIccTagArray * pNewTagArray) const pure virtual
Implemented in CIccArrayUnknown, CIccArrayColorantInfo, and CIccArrayNamedColor.
Referenced by CIccTagArray::CIccTagArray(), and CIccTagArray::operator=().
Validate()
virtual icValidateStatus IIccArray::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const pure virtual
Implemented in CIccArrayUnknown, CIccArrayColorantInfo, and CIccArrayNamedColor.
Referenced by CIccTagArray::Validate().
Field Documentation
m_pTagArray
CIccTagArray* IIccArray::m_pTagArray protected
Referenced by GetTagArray().
The documentation for this class was generated from the following file:
IccProfLib/IccTagComposite.h