iccDEV: CDevLinkWriter Class Reference
CDevLinkWriter Class Reference
Public Member Functions
CDevLinkWriter ()
virtual ~CDevLinkWriter ()
virtual bool begin (icColorSpaceSignature srcSpace, icColorSpaceSignature dstSpace)
virtual bool finish ()
virtual void iterate (const CIccXform *pXform)
virtual void setCmm (CIccCmm *pCmm)
virtual bool setFile (const char *szOutputFile)
virtual void setInputRange (icFloatNumber fMinInput, icFloatNumber fMaxInput)
virtual bool setLutSize (icUInt8Number nGridSize)
virtual void setNextNode (icFloatNumber *pPixel)
virtual void setOption (int nOptionValue)
virtual void setTitle (const char *szTitle)
Protected Attributes
bool m_bWriteV5 = true
std::string m_description
std::string m_filename
icFloatNumber m_fMaxInput = 1.0
icFloatNumber m_fMinInput = 0.0
int m_grid = 0
icUInt32Number m_nCountdown = 0
icUInt16Number m_nOutSamples
CIccCmm * m_pCmm = nullptr
const CIccProfile * m_pFirstProfile = nullptr
const CIccProfile * m_pLastProfile = nullptr
icFloatNumber * m_pLutPtr = nullptr
CIccProfile * m_pProfile = nullptr
CIccTagProfileSeqDesc * m_pTagSeq = nullptr
std::string m_title
Detailed Description
Constructor & Destructor Documentation
CDevLinkWriter()
CDevLinkWriter::CDevLinkWriter () inline
{ }
Referenced by main().
~CDevLinkWriter()
virtual CDevLinkWriter::~CDevLinkWriter () inline virtual
  {
    if (m_pProfile)
      delete m_pProfile;
  }
References m_pProfile.
Member Function Documentation
begin()
virtual bool CDevLinkWriter::begin (icColorSpaceSignature srcSpace, icColorSpaceSignature dstSpace) inline virtual
Implements ILinkWriter.
  {
    icUInt16Number nSrcSamples = (icUInt16Number)icGetSpaceSamples(srcSpace);
    icUInt16Number nDstSamples = (icUInt16Number)icGetSpaceSamples(dstSpace);
    m_nOutSamples = nDstSamples;
    if (!nSrcSamples || (!m_bWriteV5 && nSrcSamples > 15) || (m_bWriteV5 && nSrcSamples > 16)) {
      printf("Invalid number of source samples\n");
      return false;
    }
    if (!nDstSamples || (!m_bWriteV5 && nDstSamples > 15)) {
      printf("Invalid number of destination samples\n");
      return false;
    }
    CIccInfo Info;
    if (!Info.IsValidSpace(srcSpace)) {
      printf("Invalid source color space\n");
      return false;
    }
    if (!Info.IsValidSpace(dstSpace)) {
      printf("Invalid destination color space\n");
      return false;
    }
    m_pProfile = new CIccProfile();
    //Initialize profile header
    m_pProfile->InitHeader();
    m_pProfile->m_Header.colorSpace = srcSpace;
    m_pProfile->m_Header.pcs = dstSpace;
    m_pProfile->m_Header.deviceClass = icSigLinkClass;
    //Add description Tag
    CIccTagMultiLocalizedUnicode* pTextTag = new CIccTagMultiLocalizedUnicode();
    if (m_title.size()) {
      pTextTag->SetText(m_title.c_str());
    }
    else {
      pTextTag->SetText("Device link created by iccApplyToLink");
    }
    m_pProfile->AttachTag(icSigProfileDescriptionTag, pTextTag);
    pTextTag = new CIccTagMultiLocalizedUnicode();
    pTextTag->SetText("Copyright ICC");
    m_pProfile->AttachTag(icSigCopyrightTag, pTextTag);
    if (m_bWriteV5) {
      m_pProfile->m_Header.version = icVersionNumberV5;
      //Create A2B0 Tag with LUT
      CIccTagMultiProcessElement* pTag = new CIccTagMultiProcessElement(nSrcSamples, nDstSamples);
      if (!icIsNear(m_fMinInput, 0.0) || !icIsNear(m_fMaxInput, 1.0)) {
        CIccMpeCurveSet* pCurves = new CIccMpeCurveSet(nSrcSamples);
        CIccSingleSampledCurve* pCurve0 = new CIccSingleSampledCurve(m_fMinInput, m_fMaxInput);
        pCurve0->SetSize(2);
        pCurve0->GetSamples()[0] = 0;
        pCurve0->GetSamples()[1] = 1;
        pCurves->SetCurve(0, pCurve0);
        for (icUInt16Number i = 1; i < nSrcSamples; i++) {
          pCurves->SetCurve(1, pCurve0);
        }
        pTag->Attach(pCurves);
      }
      CIccMpeCLUT* pMpeCLUT = new CIccMpeCLUT();
      CIccCLUT* pCLUT = new CIccCLUT((icUInt8Number)nSrcSamples, (icUInt8Number)nDstSamples);
      pCLUT->Init(m_grid);
      m_pLutPtr = pCLUT->GetData(0);
      m_nCountdown = pCLUT->NumPoints();
      pMpeCLUT->SetCLUT(pCLUT);
      pTag->Attach(pMpeCLUT);
      m_pProfile->AttachTag(icSigAToB0Tag, pTag);
    }
    else {
      m_pProfile->m_Header.version = icVersionNumberV4_3;
      m_pFirstProfile = nullptr;
      m_pLastProfile = nullptr;
      m_pTagSeq = new CIccTagProfileSeqDesc();
      if (m_pCmm) {
        m_pCmm->IterateXforms(this);
      }
      if (m_pTagSeq && m_pTagSeq->m_Descriptions && m_pTagSeq->m_Descriptions->size()) {
        m_pProfile->AttachTag(icSigProfileSequenceDescTag, m_pTagSeq);
      }
      else {
        delete m_pTagSeq;
        m_pTagSeq = nullptr;
      }
      if (icIsSpaceCLR(srcSpace) && m_pFirstProfile) {
        if (m_pFirstProfile->m_Header.version < icVersionNumberV5) {
          const CIccTag* pTagColor = m_pFirstProfile->FindTagConst(icSigColorantTableTag);
          if (pTagColor) {
            m_pProfile->AttachTag(icSigColorantTableTag, pTagColor->NewCopy());
          }
        }
        else if (m_pFirstProfile->m_Header.version >= icVersionNumberV5) {
        }
      }
      if (icIsSpaceCLR(dstSpace) && m_pLastProfile) {
        if (m_pLastProfile->m_Header.deviceClass == icSigLinkClass) {
          if (m_pLastProfile->m_Header.version < icVersionNumberV5) {
            const CIccTag* pTagColor = m_pLastProfile->FindTagConst(icSigColorantTableOutTag);
            if (pTagColor) {
              m_pProfile->AttachTag(icSigColorantTableTag, pTagColor->NewCopy());
            }
          }
          else if (m_pLastProfile->m_Header.version >= icVersionNumberV5) {
          }
        }
        else if (m_pLastProfile->m_Header.version < icVersionNumberV5) {
          const CIccTag* pTagColor = m_pLastProfile->FindTagConst(icSigColorantTableTag);
          if (pTagColor) {
            m_pProfile->AttachTag(icSigColorantTableOutTag, pTagColor->NewCopy());
          }
        }
        else if (m_pLastProfile->m_Header.version >= icVersionNumberV5) {
        }
      }
      CIccTagLutAtoB* pTagLut = new CIccTagLutAtoB();
      pTagLut->Init((icUInt8Number)nSrcSamples, (icUInt8Number)nDstSamples);
      LPIccCurve *pCurves = pTagLut->NewCurvesA();
      for (icUInt16Number i = 0; i < nSrcSamples; i++) {
        pCurves[i] = new CIccTagCurve();
      }
      pCurves = pTagLut->NewCurvesB();
      for (icUInt16Number i = 0; i < nDstSamples; i++) {
        pCurves[i] = new CIccTagCurve();
      }
      CIccCLUT* pCLUT = pTagLut->NewCLUT(m_grid);
      m_pLutPtr = pCLUT->GetData(0);
      m_nCountdown = pCLUT->NumPoints();
      m_pProfile->AttachTag(icSigAToB0Tag, pTagLut);
    }
    return true;
  }
References CIccCLUT::CIccCLUT(), CIccMpeCLUT::CIccMpeCLUT(), CIccMpeCurveSet::CIccMpeCurveSet(), CIccSingleSampledCurve::CIccSingleSampledCurve(), CIccTagCurve::CIccTagCurve(), CIccTagLutAtoB::CIccTagLutAtoB(), CIccTagMultiLocalizedUnicode::CIccTagMultiLocalizedUnicode(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagProfileSeqDesc::CIccTagProfileSeqDesc(), CIccTagMultiProcessElement::Attach(), CIccProfile, icHeader::colorSpace, icHeader::deviceClass, CIccCLUT::GetData(), CIccSingleSampledCurve::GetSamples(), icGetSpaceSamples(), icIsNear(), icIsSpaceCLR(), icSigAToB0Tag, icSigColorantTableOutTag, icSigColorantTableTag, icSigCopyrightTag, icSigLinkClass, icSigProfileDescriptionTag, icSigProfileSequenceDescTag, CIccCLUT::Init(), CIccMBB::Init(), CIccInfo::IsValidSpace(), m_bWriteV5, CIccTagProfileSeqDesc::m_Descriptions, m_fMaxInput, m_fMinInput, m_grid, m_nCountdown, m_nOutSamples, m_pCmm, m_pFirstProfile, m_pLastProfile, m_pLutPtr, m_pProfile, m_pTagSeq, m_title, CIccMBB::NewCLUT(), CIccTag::NewCopy(), CIccMBB::NewCurvesA(), CIccMBB::NewCurvesB(), CIccCLUT::NumPoints(), icHeader::pcs, CIccMpeCLUT::SetCLUT(), CIccMpeCurveSet::SetCurve(), CIccSingleSampledCurve::SetSize(), CIccTagMultiLocalizedUnicode::SetText(), and icHeader::version.
finish()
virtual bool CDevLinkWriter::finish () inline virtual
Implements ILinkWriter.
  {
    bool rv = false;
    if (m_pProfile) {
      rv = SaveIccProfile(m_filename.c_str(), m_pProfile);
      delete m_pProfile;
    }
    m_pProfile = nullptr;
    return rv;
  }
References m_filename, m_pProfile, and SaveIccProfile().
iterate()
virtual void CDevLinkWriter::iterate (const CIccXform * pXform) inline virtual
  {
    if (pXform) {
      const CIccProfile* pProfile = pXform->GetProfile();
      if (pProfile) {
        if (!m_pFirstProfile)
          m_pFirstProfile = pProfile;
        m_pLastProfile = pProfile;
        if (!m_bWriteV5 && m_pTagSeq) {
          CIccProfileDescStruct psd;
          psd.m_deviceMfg = pProfile->m_Header.manufacturer;
          psd.m_deviceModel = pProfile->m_Header.model;
          psd.m_attributes = pProfile->m_Header.attributes;
          const CIccTag* pTag = pProfile->FindTagConst(icSigTechnologyTag);
          if (pTag && pTag->GetType() == icSigSignatureType) {
            const CIccTagSignature* pSigTag = (const CIccTagSignature*)pTag;
            psd.m_technology = (icTechnologySignature)pSigTag->GetValue();
          }
          pTag = pProfile->FindTagConst(icSigDeviceMfgDescTag);
          if (pTag) {
            if (pTag->GetType() == icSigTextDescriptionType) {
              const CIccTagTextDescription* pTextTag = (const CIccTagTextDescription*)pTag;
              psd.m_deviceMfgDesc.SetType(icSigTextDescriptionType);
              CIccTagTextDescription* pText = (CIccTagTextDescription*)psd.m_deviceMfgDesc.GetTag();
              if (pText)
                *pText = *pTextTag;
            }
            else if (pTag->GetType() == icSigMultiLocalizedUnicodeType) {
              const CIccTagMultiLocalizedUnicode* pTextTag = (const CIccTagMultiLocalizedUnicode*)pTag;
              psd.m_deviceMfgDesc.SetType(icSigMultiLocalizedUnicodeType);
              CIccTagMultiLocalizedUnicode* pText = (CIccTagMultiLocalizedUnicode*)psd.m_deviceMfgDesc.GetTag();
              if (pText)
                *pText = *pTextTag;
            }
          }
          pTag = pProfile->FindTagConst(icSigDeviceModelDescTag);
          if (pTag) {
            if (pTag->GetType() == icSigTextDescriptionType) {
              const CIccTagTextDescription* pTextTag = (const CIccTagTextDescription*)pTag;
              psd.m_deviceModelDesc.SetType(icSigTextDescriptionType);
              CIccTagTextDescription* pText = (CIccTagTextDescription*)psd.m_deviceMfgDesc.GetTag();
              if (pText)
                *pText = *pTextTag;
            }
            else if (pTag->GetType() == icSigMultiLocalizedUnicodeType) {
              const CIccTagMultiLocalizedUnicode* pTextTag = (const CIccTagMultiLocalizedUnicode*)pTag;
              psd.m_deviceModelDesc.SetType(icSigMultiLocalizedUnicodeType);
              CIccTagMultiLocalizedUnicode* pText = (CIccTagMultiLocalizedUnicode*)psd.m_deviceMfgDesc.GetTag();
              if (pText)
                *pText = *pTextTag;
            }
          }
          m_pTagSeq->m_Descriptions->push_back(psd);
        }
      }
    }
  }
References icHeader::attributes, CIccProfile, CIccProfileDescText::GetTag(), CIccTag::GetType(), CIccTagSignature::GetValue(), icSigDeviceMfgDescTag, icSigDeviceModelDescTag, icSigMultiLocalizedUnicodeType, icSigSignatureType, icSigTechnologyTag, icSigTextDescriptionType, CIccProfileDescStruct::m_attributes, m_bWriteV5, CIccTagProfileSeqDesc::m_Descriptions, CIccProfileDescStruct::m_deviceMfg, CIccProfileDescStruct::m_deviceMfgDesc, CIccProfileDescStruct::m_deviceModel, CIccProfileDescStruct::m_deviceModelDesc, m_pFirstProfile, m_pLastProfile, m_pTagSeq, CIccProfileDescStruct::m_technology, icHeader::manufacturer, icHeader::model, CIccTagMultiLocalizedUnicode::operator=(), CIccTagTextDescription::operator=(), and CIccProfileDescText::SetType().
setCmm()
virtual void CDevLinkWriter::setCmm (CIccCmm * pCmm) inline virtual
Implements ILinkWriter.
  {
    m_pCmm = pCmm;
  }
References m_pCmm.
setFile()
virtual bool CDevLinkWriter::setFile (const char * szOutputFile) inline virtual
Implements ILinkWriter.
  {
    m_filename = szOutputFile;
    return true;
  }
References m_filename.
setInputRange()
virtual void CDevLinkWriter::setInputRange (icFloatNumber fMinInput, icFloatNumber fMaxInput) inline virtual
Implements ILinkWriter.
  {
    m_fMinInput = fMinInput;
    m_fMaxInput = fMaxInput;
  }
References m_fMaxInput, and m_fMinInput.
setLutSize()
virtual bool CDevLinkWriter::setLutSize (icUInt8Number nGridSize) inline virtual
Implements ILinkWriter.
  {
    m_grid = nGridSize;
    return true;
  }
References m_grid.
setNextNode()
virtual void CDevLinkWriter::setNextNode (icFloatNumber * pPixel) inline virtual
Implements ILinkWriter.
  {
    if (m_nCountdown) {
      memcpy(m_pLutPtr, pPixel, m_nOutSamples * sizeof(icFloatNumber));
      m_pLutPtr += m_nOutSamples;
      m_nCountdown--;
    }
  }
References m_nCountdown, m_nOutSamples, and m_pLutPtr.
setOption()
virtual void CDevLinkWriter::setOption (int nOptionValue) inline virtual
Implements ILinkWriter.
  {
    m_bWriteV5 = nOptionValue != 0;
  }
References m_bWriteV5.
setTitle()
virtual void CDevLinkWriter::setTitle (const char * szTitle) inline virtual
Implements ILinkWriter.
  {
    m_title = szTitle;
  }
References m_title.
Field Documentation
m_bWriteV5
bool CDevLinkWriter::m_bWriteV5 = true protected
Referenced by begin(), iterate(), and setOption().
m_description
std::string CDevLinkWriter::m_description protected
m_filename
std::string CDevLinkWriter::m_filename protected
Referenced by finish(), and setFile().
m_fMaxInput
icFloatNumber CDevLinkWriter::m_fMaxInput = 1.0 protected
Referenced by begin(), and setInputRange().
m_fMinInput
icFloatNumber CDevLinkWriter::m_fMinInput = 0.0 protected
Referenced by begin(), and setInputRange().
m_grid
int CDevLinkWriter::m_grid = 0 protected
Referenced by begin(), and setLutSize().
m_nCountdown
icUInt32Number CDevLinkWriter::m_nCountdown = 0 protected
Referenced by begin(), and setNextNode().
m_nOutSamples
icUInt16Number CDevLinkWriter::m_nOutSamples protected
Referenced by begin(), and setNextNode().
m_pCmm
CIccCmm* CDevLinkWriter::m_pCmm = nullptr protected
Referenced by begin(), and setCmm().
m_pFirstProfile
const CIccProfile* CDevLinkWriter::m_pFirstProfile = nullptr protected
Referenced by begin(), and iterate().
m_pLastProfile
const CIccProfile* CDevLinkWriter::m_pLastProfile = nullptr protected
Referenced by begin(), and iterate().
m_pLutPtr
icFloatNumber* CDevLinkWriter::m_pLutPtr = nullptr protected
Referenced by begin(), and setNextNode().
m_pProfile
CIccProfile* CDevLinkWriter::m_pProfile = nullptr protected
Referenced by ~CDevLinkWriter(), begin(), and finish().
m_pTagSeq
CIccTagProfileSeqDesc* CDevLinkWriter::m_pTagSeq = nullptr protected
Referenced by begin(), and iterate().
m_title
std::string CDevLinkWriter::m_title protected
Referenced by begin(), and setTitle().
The documentation for this class was generated from the following file:
Tools/CmdLine/IccApplyToLink/iccApplyToLink.cpp