iccDEV: CIccTagXmlColorantTable Class Reference
CIccTagXmlColorantTable Class Reference
#include <IccTagXml.h>
Public Member Functions
virtual ~CIccTagXmlColorantTable ()
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
virtual const char * GetClassName () const
icColorantTableEntry * GetEntry (icUInt32Number index)
virtual const char * GetExtClassName () const
virtual const char * GetExtDerivedClassName () const
virtual IIccExtensionTag * GetExtension ()
icColorSpaceSignature GetPCS () const
icUInt32Number GetSize () const
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
icColorantTableEntry & operator[] (icUInt32Number index)
virtual bool ParseXml (xmlNode *pNode, std::string &parseStr)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
void SetPCS (icColorSpaceSignature sig)
bool SetSize (icUInt16Number nSize, bool bZeroNew=true)
virtual bool ToXml (std::string &xml, std::string blanks="")
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
Protected Attributes
icUInt32Number m_nCount
icColorSpaceSignature m_PCS
icColorantTableEntry * m_pData
Detailed Description
Constructor & Destructor Documentation
~CIccTagXmlColorantTable()
virtual CIccTagXmlColorantTable::~CIccTagXmlColorantTable () inline virtual
{}
Member Function Documentation
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagColorantTable::Describe (std::string & sDescription, int nVerboseness) virtual inherited
Name: CIccTagColorantTable::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  icChar buf[128];
  icUInt32Number i, nLen, nMaxLen=0;
  icFloatNumber Lab[3] = {0};
  sprintf(buf, "BEGIN_COLORANTS %u\n", m_nCount);
  sDescription += buf;
  for (i=0; i<m_nCount; i++) {
    nLen = (icUInt32Number)strlen(m_pData[i].name);
    if (nLen>nMaxLen)
      nMaxLen =nLen;
  }
  sDescription += "# NAME ";
  if (m_PCS == icSigXYZData) {
    sprintf(buf, "XYZ_X XYZ_Y XYZ_Z\n");
    sDescription += buf;
  }
  else {
    sprintf(buf, "Lab_L Lab_a Lab_b\n");
    sDescription += buf;
  }
  for (i=0; i<m_nCount; i++) {
    sprintf(buf, "%2u \"%s\"", i, m_pData[i].name);
    sDescription += buf;
    memset(buf, ' ', 128);
    buf[nMaxLen + 1 - strlen(m_pData[i].name)] ='\0';
    sDescription += buf;
    if (m_PCS == icSigXYZData) {
      sprintf(buf, "%7.4lf %7.4lf %7.4lf\n", icUSFtoD(m_pData[i].data[0]), icUSFtoD(m_pData[i].data[1]), icUSFtoD(m_pData[i].data[2]));
      sDescription += buf;
    }
    else {
      Lab[0] = icU16toF(m_pData[i].data[0]);
      Lab[1] = icU16toF(m_pData[i].data[1]);
      Lab[2] = icU16toF(m_pData[i].data[2]);
      icLabFromPcs(Lab);
      sprintf(buf, "%7.4lf %8.4lf %8.4lf\n", Lab[0], Lab[1], Lab[2]);
      sDescription += buf;
    }
  }
}
References icColorantTableEntry::data, icLabFromPcs(), icSigXYZData, icU16toF(), icUSFtoD(), CIccTagColorantTable::m_nCount, CIccTagColorantTable::m_PCS, CIccTagColorantTable::m_pData, and icColorantTableEntry::name.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
GetClassName()
virtual const char * CIccTagXmlColorantTable::GetClassName () const inline virtual
Reimplemented from CIccTagColorantTable.
{return "CIccTagXmlColorantTable"; }
GetEntry()
icColorantTableEntry * CIccTagColorantTable::GetEntry (icUInt32Number index) inline inherited
{return &m_pData[index];}
References CIccTagColorantTable::m_pData.
GetExtClassName()
virtual const char * CIccTagXml::GetExtClassName () const inline virtual inherited
Implements IIccExtensionTag.
{ return "CIccTagXml"; }
Referenced by icProfDescToXml(), and icXmlParseProfDesc().
GetExtDerivedClassName()
virtual const char * CIccTagXml::GetExtDerivedClassName () const inline virtual inherited
Implements IIccExtensionTag.
Reimplemented in CIccCurveXml.
{ return ""; }
GetExtension()
virtual IIccExtensionTag * CIccTagXmlColorantTable::GetExtension () inline virtual
Reimplemented from CIccTag.
{return this; }
GetPCS()
icColorSpaceSignature CIccTagColorantTable::GetPCS () const inline inherited
{return m_PCS;};
References CIccTagColorantTable::m_PCS.
GetSize()
icUInt32Number CIccTagColorantTable::GetSize () const inline inherited
{ return m_nCount; }
References CIccTagColorantTable::m_nCount.
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagColorantTable::GetType () const inline virtual inherited
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigColorantTableType; }
References icSigColorantTableType.
Referenced by CIccTagColorantTable::Write().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
virtual CIccTag * CIccTagColorantTable::NewCopy () const inline virtual inherited
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
{return new CIccTagColorantTable(*this);}
References CIccTagColorantTable::CIccTagColorantTable().
operator[]()
icColorantTableEntry & CIccTagColorantTable::operator[] (icUInt32Number index) inline inherited
{return m_pData[index];}
References CIccTagColorantTable::m_pData.
ParseXml()
bool CIccTagXmlColorantTable::ParseXml (xmlNode * pNode, std::string & parseStr) virtual
Implements CIccTagXml.
{
  pNode = icXmlFindNode(pNode, "ColorantTable");
  if (pNode && pNode->children) {
    pNode = pNode->children;
    icUInt16Number n = (icUInt16Number)icXmlNodeCount(pNode, "Colorant");
    if (n) {
      icUInt32Number i;
      SetSize(n);
      for (i=0; pNode; pNode=pNode->next) {
        if (pNode->type == XML_ELEMENT_NODE &&
          !icXmlStrCmp(pNode->name, "Colorant") &&
          i<n) {
            std::string str;
            const icChar *name = icXmlAttrValue(pNode, "Name");
            xmlAttr *L = icXmlFindAttr(pNode, "Channel1");
            xmlAttr *a = icXmlFindAttr(pNode, "Channel2");
            xmlAttr *b = icXmlFindAttr(pNode, "Channel3");
            if (name && L && a && b) {
              strncpy(m_pData[i].name, icUtf8ToAnsi(str, name), sizeof(m_pData[i].name));
              m_pData[i].name[sizeof(m_pData[i].name)-1]=0;
              icFloatNumber lab[3];
              lab[0] = (icFloatNumber)atof(icXmlAttrValue(L));
              lab[1] = (icFloatNumber)atof(icXmlAttrValue(a));
              lab[2] = (icFloatNumber)atof(icXmlAttrValue(b));
              icLabToPcs(lab);
              m_pData[i].data[0] = icFtoU16(lab[0]);
              m_pData[i].data[1] = icFtoU16(lab[1]);
              m_pData[i].data[2] = icFtoU16(lab[2]);
              i++;
            }
            else
              return false;
        }
      }
      return i==n;
    }
    return false;
  }
  return false;
}
References icColorantTableEntry::data, icFtoU16(), icLabToPcs(), icUtf8ToAnsi(), icXmlAttrValue(), icXmlAttrValue(), icXmlFindAttr(), icXmlFindNode(), icXmlNodeCount(), CIccTagColorantTable::m_pData, icColorantTableEntry::name, and CIccTagColorantTable::SetSize().
Read() [1/2]
bool CIccTagColorantTable::Read (icUInt32Number size, CIccIO * pIO) virtual inherited
Name: CIccTagColorantTable::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  icUInt32Number nCount;
  if (sizeof(icTagTypeSignature) +
      sizeof(icUInt32Number) +
      sizeof(icUInt32Number) +
      sizeof(icColorantTableEntry) > size)
    return false;
  if (!pIO) {
    return false;
  }
  if (!pIO->Read32(&sig))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  if (!pIO->Read32(&nCount))
    return false;
  icUInt32Number nNum = (size - 3*sizeof(icUInt32Number))/sizeof(icColorantTableEntry);
  icUInt32Number nNum8 = sizeof(m_pData->name);
  icUInt32Number nNum16 = sizeof(m_pData->data)/sizeof(icUInt16Number);
  if (nNum < nCount || nCount > 0xffff)
    return false;
  if (!SetSize((icUInt16Number)nCount))
    return false;
  for (icUInt32Number i=0; i<nCount; i++) {
    if (pIO->Read8(&m_pData[i].name[0], nNum8) != (icInt32Number)nNum8)
      return false;
    if (pIO->Read16(&m_pData[i].data[0], nNum16) != (icInt32Number)nNum16)
      return false;
  }
  return true;
}
References icColorantTableEntry::data, CIccTag::m_nReserved, CIccTagColorantTable::m_pData, icColorantTableEntry::name, CIccIO::Read16(), CIccIO::Read32(), CIccIO::Read8(), and CIccTagColorantTable::SetSize().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
SetPCS()
void CIccTagColorantTable::SetPCS (icColorSpaceSignature sig) inline inherited
{m_PCS = sig;}
References CIccTagColorantTable::m_PCS.
SetSize()
bool CIccTagColorantTable::SetSize (icUInt16Number nSize, bool bZeroNew = true) inherited
Name: CIccTagColorantTable::SetSize
Purpose: Sets the size of the data array.
Args: nSize - number of entries, bZeroNew - flag to zero newly formed values
{
  if (m_nCount == nSize)
    return true;
  m_pData = (icColorantTableEntry*)icRealloc(m_pData, nSize*sizeof(icColorantTableEntry));
  if (!m_pData) {
    m_nCount = 0;
    return false;
  }
  if (bZeroNew && nSize > m_nCount) {
    memset(&m_pData[m_nCount], 0, (nSize-m_nCount)*sizeof(icColorantTableEntry));
  }
  m_nCount = nSize;
  return true;
}
References icRealloc(), CIccTagColorantTable::m_nCount, and CIccTagColorantTable::m_pData.
Referenced by ParseXml(), and CIccTagColorantTable::Read().
ToXml()
bool CIccTagXmlColorantTable::ToXml (std::string & xml, std::string blanks = "") virtual
Implements CIccTagXml.
{
  char buf[256];
  char fix[256];
  int i;
  std::string str;
  xml += blanks + "<ColorantTable>\n";
  for (i=0; i<(int)m_nCount; i++) {
    icFloatNumber lab[3];
    lab[0] = icU16toF(m_pData[i].data[0]);
    lab[1] = icU16toF(m_pData[i].data[1]);
    lab[2] = icU16toF(m_pData[i].data[2]);
    icLabFromPcs(lab);
    sprintf(buf, "  <Colorant Name=\"%s\" Channel1=\"" icXmlFloatFmt "\" Channel2=\"" icXmlFloatFmt "\" Channel3=\"" icXmlFloatFmt "\"/>\n",
      icFixXml(fix, icAnsiToUtf8(str, m_pData[i].name)), lab[0], lab[1], lab[2]);
    xml += blanks + buf;
  }
  //xml += "\n";
  xml += blanks + "</ColorantTable>\n";
  return true;
}
References icColorantTableEntry::data, icAnsiToUtf8(), icFixXml(), icLabFromPcs(), icU16toF(), CIccTagColorantTable::m_nCount, CIccTagColorantTable::m_pData, and icColorantTableEntry::name.
Validate()
icValidateStatus CIccTagColorantTable::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual inherited
Name: CIccTagColorantTable::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  icSignature sig = icGetFirstSigPathSig(sigPath);
  if (!pProfile) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " - Tag validation incomplete: Pointer to profile unavailable.\n";
    rv = icMaxStatus(rv, icValidateWarning);
    return rv;
  }
  if (sig==icSigColorantTableOutTag) {
    if (pProfile->m_Header.deviceClass!=icSigLinkClass) {
      sReport += icMsgValidateNonCompliant;
      sReport += sSigPathName;
      sReport += " - Use of this tag is allowed only in DeviceLink Profiles.\n";
      rv = icMaxStatus(rv, icValidateNonCompliant);
    }
    if (m_nCount != icGetSpaceSamples(pProfile->m_Header.pcs)) {
      sReport += icMsgValidateNonCompliant;
      sReport += sSigPathName;
      sReport += " - Incorrect number of colorants.\n";
      rv = icMaxStatus(rv, icValidateNonCompliant);
    }
  }
  else {
    if (m_nCount != icGetSpaceSamples(pProfile->m_Header.colorSpace)) {
      sReport += icMsgValidateNonCompliant;
      sReport += sSigPathName;
      sReport += " - Incorrect number of colorants.\n";
      rv = icMaxStatus(rv, icValidateNonCompliant);
    }
  }
  return rv;
}
References icHeader::colorSpace, icHeader::deviceClass, CIccInfo::GetSigPathName(), icGetFirstSigPathSig(), icGetSpaceSamples(), icMaxStatus(), icMsgValidateNonCompliant, icMsgValidateWarning, icSigColorantTableOutTag, icSigLinkClass, icValidateNonCompliant, icValidateWarning, CIccTagColorantTable::m_nCount, icHeader::pcs, and CIccTag::Validate().
Write()
bool CIccTagColorantTable::Write (CIccIO * pIO) virtual inherited
Name: CIccTagColorantTable::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  if (!pIO)
   return false;
  if (!pIO->Write32(&sig))
   return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  if (!pIO->Write32(&m_nCount))
    return false;
  icUInt32Number nNum8 = sizeof(m_pData->name);
  icUInt32Number nNum16 = sizeof(m_pData->data)/sizeof(icUInt16Number);
  for (icUInt32Number i=0; i<m_nCount; i++) {
    if (pIO->Write8(&m_pData[i].name[0],nNum8) != (icInt32Number)nNum8)
      return false;
    if (pIO->Write16(&m_pData[i].data[0],nNum16) != (icInt32Number)nNum16)
      return false;
  }
  return true;
}
References icColorantTableEntry::data, CIccTagColorantTable::GetType(), CIccTagColorantTable::m_nCount, CIccTag::m_nReserved, CIccTagColorantTable::m_pData, icColorantTableEntry::name, CIccIO::Write16(), CIccIO::Write32(), and CIccIO::Write8().
Field Documentation
m_nCount
icUInt32Number CIccTagColorantTable::m_nCount protected inherited
Referenced by CIccTagColorantTable::CIccTagColorantTable(), CIccTagColorantTable::CIccTagColorantTable(), CIccTagColorantTable::Describe(), CIccTagColorantTable::GetSize(), CIccTagColorantTable::operator=(), CIccTagColorantTable::SetSize(), ToXml(), CIccTagColorantTable::Validate(), and CIccTagColorantTable::Write().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_PCS
icColorSpaceSignature CIccTagColorantTable::m_PCS protected inherited
Referenced by CIccTagColorantTable::CIccTagColorantTable(), CIccTagColorantTable::Describe(), CIccTagColorantTable::GetPCS(), CIccTagColorantTable::operator=(), and CIccTagColorantTable::SetPCS().
m_pData
icColorantTableEntry* CIccTagColorantTable::m_pData protected inherited
Referenced by CIccTagColorantTable::CIccTagColorantTable(), CIccTagColorantTable::CIccTagColorantTable(), CIccTagColorantTable::~CIccTagColorantTable(), CIccTagColorantTable::Describe(), CIccTagColorantTable::GetEntry(), CIccTagColorantTable::operator=(), CIccTagColorantTable::operator[](), ParseXml(), CIccTagColorantTable::Read(), CIccTagColorantTable::SetSize(), ToXml(), and CIccTagColorantTable::Write().
The documentation for this class was generated from the following files:
IccXML/IccLibXML/IccTagXml.h
IccXML/IccLibXML/IccTagXml.cpp