iccDEV: CIccIO Class Reference
CIccIO Class Reference
#include <IccIO.h>
Public Member Functions
virtual ~CIccIO ()
bool Align32 ()
Write operation to make sure that filelength is evenly divisible by 4.
virtual void Close ()
virtual icInt32Number GetLength ()
icInt32Number Read16 (void *pBuf16, icInt32Number nNum=1)
icInt32Number Read32 (void *pBuf32, icInt32Number nNum=1)
icInt32Number Read64 (void *pBuf64, icInt32Number nNum=1)
virtual icInt32Number Read8 (void *pBuf8, icInt32Number nNum=1)
icInt32Number ReadFloat16Float (void *pBufFloat, icInt32Number nNum=1)
icInt32Number ReadFloat32Float (void *pBufFloat, icInt32Number nNum=1)
icInt32Number ReadLine (void *pBuf8, icInt32Number nNum=256)
icInt32Number ReadUInt16Float (void *pBufFloat, icInt32Number nNum=1)
icInt32Number ReadUInt8Float (void *pBufFloat, icInt32Number nNum=1)
virtual icInt32Number Seek (icInt32Number nOffset, icSeekVal pos)
bool Sync32 (icUInt32Number nOffset=0)
Operation to make sure read position is evenly divisible by 4.
virtual icInt32Number Tell ()
icInt32Number Write16 (void *pBuf16, icInt32Number nNum=1)
icInt32Number Write32 (void *pBuf32, icInt32Number nNum=1)
icInt32Number Write64 (void *pBuf64, icInt32Number nNum=1)
virtual icInt32Number Write8 (void *pBuf8, icInt32Number nNum=1)
icInt32Number WriteFloat16Float (void *pBuf16, icInt32Number nNum=1)
icInt32Number WriteFloat32Float (void *pBufFloat, icInt32Number nNum=1)
icInt32Number WriteUInt16Float (void *pBuf16, icInt32Number nNum=1)
icInt32Number WriteUInt8Float (void *pBuf16, icInt32Number nNum=1)
Detailed Description
Type: Class
Purpose: This is the base object that handles the IO with an ICC profile.
Constructor & Destructor Documentation
~CIccIO()
virtual CIccIO::~CIccIO () inline virtual
{}
Member Function Documentation
Align32()
bool CIccIO::Align32 ()
Write operation to make sure that filelength is evenly divisible by 4.
{
  int mod = GetLength() % 4;
  if (mod != 0) {
    icUInt8Number buf[4]={0,0,0,0};
    if (Seek(0, icSeekEnd)<0)
      return false;
    if (Write8(buf, 4-mod) != 4-mod)
      return false;
  }
  return true;
}
References GetLength(), icSeekEnd, Seek(), and Write8().
Referenced by CIccMpeCurveSet::Write(), CIccMpeToneMap::Write(), CIccMpeCalculator::Write(), CIccTagSparseMatrixArray::Write(), CIccProfileDescText::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
Close()
virtual void CIccIO::Close () inline virtual
Reimplemented in CIccFileIO, CIccEmbedIO, CIccMemIO, and CIccNullIO.
{}
Referenced by CIccEmbedIO::Close().
GetLength()
virtual icInt32Number CIccIO::GetLength () inline virtual
Reimplemented in CIccFileIO, CIccEmbedIO, CIccMemIO, and CIccNullIO.
{return 0;}
Referenced by Align32(), CalcProfileID(), CIccEmbedIO::GetLength(), icCLutFromXml(), icXmlParseTextString(), CIccTagXmlCurve::ParseXml(), CIccSampledCurveSegmentXml::ParseXml(), CIccSinglSampledeCurveXml::ParseXml(), CIccTagXmlTextDescription::ParseXml(), CIccTagXmlFloatNum< T, A, Tsig >::ParseXml(), CIccTagXmlEmbeddedHeightImage::ParseXml(), CIccTagXmlEmbeddedNormalImage::ParseXml(), CIccEmbedIO::Seek(), CIccTagResponseCurveSet16::Write(), CIccTagStruct::Write(), and CIccTagGamutBoundaryDesc::Write().
Read16()
icInt32Number CIccIO::Read16 (void * pBuf16, icInt32Number nNum = 1)
{
  nNum = Read8(pBuf16, nNum<<1)>>1;
  icSwab16Array(pBuf16, nNum);
  return nNum;
}
References icSwab16Array(), and Read8().
Referenced by icCLutFromXml(), CIccTagXmlCurve::ParseXml(), CIccSampledCurveSegmentXml::ParseXml(), CIccSinglSampledeCurveXml::ParseXml(), CIccTagXmlFloatNum< T, A, Tsig >::ParseXml(), CIccMpeUnknown::Read(), CIccMpeAcs::Read(), CIccFormulaCurveSegment::Read(), CIccSegmentedCurve::Read(), CIccSingleSampledCurve::Read(), CIccSampledCalculatorCurve::Read(), CIccMpeCurveSet::Read(), CIccMpeTintArray::Read(), CIccToneMapFunc::Read(), CIccMpeToneMap::Read(), CIccMpeMatrix::Read(), CIccMpeCLUT::Read(), CIccMpeExtCLUT::Read(), CIccMpeCAM::Read(), CIccMpeCalculator::Read(), CIccMpeSpectralMatrix::Read(), CIccMpeSpectralCLUT::Read(), CIccMpeSpectralObserver::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagChromaticity::Read(), CIccTagSparseMatrixArray::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagDateTime::Read(), CIccTagColorantTable::Read(), CIccResponseCurveStruct::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagDict::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), ReadFloat16Float(), and ReadUInt16Float().
Read32()
icInt32Number CIccIO::Read32 (void * pBuf32, icInt32Number nNum = 1)
{
  nNum = Read8(pBuf32, nNum<<2)>>2;
  icSwab32Array(pBuf32, nNum);
  return nNum;
}
References icSwab32Array(), and Read8().
Referenced by CIccTagStruct::LoadElem(), CIccMpeUnknown::Read(), CIccMpeAcs::Read(), CIccFormulaCurveSegment::Read(), CIccSampledCurveSegment::Read(), CIccSegmentedCurve::Read(), CIccSingleSampledCurve::Read(), CIccSampledCalculatorCurve::Read(), CIccMpeCurveSet::Read(), CIccMpeTintArray::Read(), CIccToneMapFunc::Read(), CIccMpeToneMap::Read(), CIccMpeMatrix::Read(), CIccMpeCLUT::Read(), CIccMpeExtCLUT::Read(), CIccMpeCAM::Read(), CIccCalculatorFunc::Read(), CIccMpeCalculator::Read(), CIccMpeSpectralMatrix::Read(), CIccMpeSpectralCLUT::Read(), CIccMpeSpectralObserver::Read(), CIccTagUnknown::Read(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccProfileDescText::Read(), CIccTagProfileSeqDesc::Read(), CIccResponseCurveStruct::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), and ReadFloat32Float().
Read64()
icInt32Number CIccIO::Read64 (void * pBuf64, icInt32Number nNum = 1)
{
  nNum = Read8(pBuf64, nNum<<3)>>3;
  icSwab64Array(pBuf64, nNum);
  return nNum;
}
References icSwab64Array(), and Read8().
Referenced by CIccTagXmlFloatNum< T, A, Tsig >::ParseXml(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), and CIccTagProfileSeqDesc::Read().
Read8()
virtual icInt32Number CIccIO::Read8 (void * pBuf8, icInt32Number nNum = 1) inline virtual
Reimplemented in CIccFileIO, CIccEmbedIO, CIccMemIO, and CIccNullIO.
{ return 0; }
Referenced by CalcProfileID(), icCLutFromXml(), CIccTagXmlCurve::ParseXml(), CIccSampledCurveSegmentXml::ParseXml(), CIccSinglSampledeCurveXml::ParseXml(), CIccTagXmlFloatNum< T, A, Tsig >::ParseXml(), CIccTagXmlEmbeddedHeightImage::ParseXml(), CIccTagXmlEmbeddedNormalImage::ParseXml(), CIccMpeUnknown::Read(), CIccMpeAcs::Read(), CIccMpeCLUT::Read(), CIccMpeExtCLUT::Read(), CIccMpeSpectralCLUT::Read(), CIccTagUnknown::Read(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagTextDescription::Read(), CIccTagNamedColor2::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagData::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccCLUT::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccProfileIdDesc::Read(), Read16(), Read32(), Read64(), CIccEmbedIO::Read8(), ReadLine(), and ReadUInt8Float().
ReadFloat16Float()
icInt32Number CIccIO::ReadFloat16Float (void * pBufFloat, icInt32Number nNum = 1)
{
  icFloatNumber *ptr = (icFloatNumber*)pBufFloat;
  icFloat16Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    if (Read16(&tmp, 1)!=1)
      break;
    *ptr = icF16toF(tmp);
    ptr++;
  }
  return i;
}
References icF16toF(), and Read16().
Referenced by CIccTagXmlFloatNum< T, A, Tsig >::ParseXml(), CIccSingleSampledCurve::Read(), CIccMpeExtCLUT::Read(), CIccMpeSpectralCLUT::Read(), CIccTagSparseMatrixArray::Read(), and CIccTagFloatNum< T, Tsig >::Read().
ReadFloat32Float()
icInt32Number CIccIO::ReadFloat32Float (void * pBufFloat, icInt32Number nNum = 1)
{
  if (sizeof(icFloat32Number)==sizeof(icFloatNumber))
    return Read32(pBufFloat, nNum);
  icFloatNumber *ptr = (icFloatNumber*)pBufFloat;
  icFloat32Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    if (Read32(&tmp, 1)!=1)
      break;
    *ptr = (icFloatNumber)tmp;
    ptr++;
  }
  return i;
}
References Read32().
Referenced by icCLutFromXml(), CIccTagXmlCurve::ParseXml(), CIccSampledCurveSegmentXml::ParseXml(), CIccSinglSampledeCurveXml::ParseXml(), CIccTagXmlFloatNum< T, A, Tsig >::ParseXml(), CIccFormulaCurveSegment::Read(), CIccSampledCurveSegment::Read(), CIccSegmentedCurve::Read(), CIccSingleSampledCurve::Read(), CIccSampledCalculatorCurve::Read(), CIccToneMapFunc::Read(), CIccMpeMatrix::Read(), CIccMpeCLUT::Read(), CIccMpeExtCLUT::Read(), CIccMpeCAM::Read(), CIccMpeSpectralMatrix::Read(), CIccMpeSpectralCLUT::Read(), CIccMpeSpectralObserver::Read(), CIccTagSparseMatrixArray::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), and CIccTagGamutBoundaryDesc::Read().
ReadLine()
icInt32Number CIccIO::ReadLine (void * pBuf8, icInt32Number nNum = 256)
{
  icInt32Number n=0;
  icInt8Number c, *ptr=(icInt8Number*)pBuf8;
  while(n<nNum) {
    if (!Read8(&c)) {
      break;
    }
    if (c=='\n') {
      break;
    }
    else if (c!='\r') {
      *ptr++ = c;
      n++;
    }
  }
  *ptr = '\0';
  return n;
}
References Read8().
Referenced by icXmlParseTextString(), and CIccTagXmlTextDescription::ParseXml().
ReadUInt16Float()
icInt32Number CIccIO::ReadUInt16Float (void * pBufFloat, icInt32Number nNum = 1)
{
  icFloatNumber *ptr = (icFloatNumber*)pBufFloat;
  icUInt16Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    if (Read16(&tmp, 1)!=1)
      break;
    *ptr = (icFloatNumber)((icFloatNumber)tmp / 65535.0);
    ptr++;
  }
  return i;
}
References Read16().
Referenced by CIccSingleSampledCurve::Read(), CIccMpeExtCLUT::Read(), CIccMpeSpectralCLUT::Read(), CIccTagNamedColor2::Read(), CIccTagSparseMatrixArray::Read(), CIccTagCurve::Read(), CIccTagLut16::Read(), and CIccCLUT::ReadData().
ReadUInt8Float()
icInt32Number CIccIO::ReadUInt8Float (void * pBufFloat, icInt32Number nNum = 1)
{
  icFloatNumber *ptr = (icFloatNumber*)pBufFloat;
  icUInt8Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    if (Read8(&tmp, 1)!=1)
      break;
    *ptr = (icFloatNumber)((icFloatNumber)tmp / 255.0);
    ptr++;
  }
  return i;
}
References Read8().
Referenced by CIccSingleSampledCurve::Read(), CIccMpeExtCLUT::Read(), CIccMpeSpectralCLUT::Read(), CIccTagSparseMatrixArray::Read(), CIccTagLut8::Read(), and CIccCLUT::ReadData().
Seek()
virtual icInt32Number CIccIO::Seek (icInt32Number nOffset, icSeekVal pos) inline virtual
Reimplemented in CIccFileIO, CIccEmbedIO, CIccMemIO, and CIccNullIO.
{return -1;}
Referenced by Align32(), CalcProfileID(), CIccTagStruct::LoadElem(), CIccSegmentedCurve::Read(), CIccMpeCurveSet::Read(), CIccMpeTintArray::Read(), CIccMpeToneMap::Read(), CIccMpeCalculator::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccProfileDescText::Read(), CIccTagResponseCurveSet16::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagLutAtoB::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccEmbedIO::Seek(), Sync32(), CIccMpeCurveSet::Write(), CIccMpeToneMap::Write(), CIccMpeCalculator::Write(), CIccTagResponseCurveSet16::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagLutAtoB::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
Sync32()
bool CIccIO::Sync32 (icUInt32Number nOffset = 0)
Operation to make sure read position is evenly divisible by 4.
{
  nOffset &= 0x3;
  icUInt32Number nPos = ((Tell() - nOffset + 3)>>2)<<2;
  if (Seek(nPos + nOffset, icSeekSet)<0)
    return false;
  return true;
}
References icSeekSet, Seek(), and Tell().
Referenced by CIccProfileDescText::Read(), and CIccTagLutAtoB::Read().
Tell()
virtual icInt32Number CIccIO::Tell () inline virtual
Reimplemented in CIccFileIO, CIccEmbedIO, CIccMemIO, and CIccNullIO.
{return 0;}
Referenced by CIccEmbedIO::Attach(), CalcProfileID(), CIccSegmentedCurve::Read(), CIccMpeCurveSet::Read(), CIccMpeTintArray::Read(), CIccMpeToneMap::Read(), CIccMpeCalculator::Read(), CIccTagTextDescription::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccProfileDescText::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccEmbedIO::Read8(), CIccEmbedIO::Seek(), Sync32(), CIccEmbedIO::Tell(), CIccMpeCurveSet::Write(), CIccMpeToneMap::Write(), CIccMpeCalculator::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagLutAtoB::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
Write16()
icInt32Number CIccIO::Write16 (void * pBuf16, icInt32Number nNum = 1)
{
#ifndef ICC_BYTE_ORDER_LITTLE_ENDIAN
  return Write8(pBuf16, nNum<<1)>>1;
#else
  icUInt16Number *ptr = (icUInt16Number*)pBuf16;
  icUInt16Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    tmp = *ptr;
    icSwab16(tmp);
    if (Write8(&tmp, 2)!=2)
      break;
    ptr++;
  }
  return i;
#endif
}
References Write8().
Referenced by CIccMpeAcs::Write(), CIccFormulaCurveSegment::Write(), CIccSegmentedCurve::Write(), CIccSingleSampledCurve::Write(), CIccSampledCalculatorCurve::Write(), CIccMpeCurveSet::Write(), CIccMpeTintArray::Write(), CIccToneMapFunc::Write(), CIccMpeToneMap::Write(), CIccMpeMatrix::Write(), CIccMpeCLUT::Write(), CIccMpeExtCLUT::Write(), CIccMpeCAM::Write(), CIccMpeCalculator::Write(), CIccMpeSpectralMatrix::Write(), CIccMpeSpectralCLUT::Write(), CIccMpeSpectralObserver::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagChromaticity::Write(), CIccTagSparseMatrixArray::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagDateTime::Write(), CIccTagColorantTable::Write(), CIccResponseCurveStruct::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagDict::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccMpeUnknown::Write(), CIccTagMultiProcessElement::Write(), WriteFloat16Float(), and WriteUInt16Float().
Write32()
icInt32Number CIccIO::Write32 (void * pBuf32, icInt32Number nNum = 1)
{
#ifndef ICC_BYTE_ORDER_LITTLE_ENDIAN
  return Write8(pBuf32, nNum<<2)>>2;
#else
  icUInt32Number *ptr = (icUInt32Number*)pBuf32;
  icUInt32Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    tmp = *ptr;
    icSwab32(tmp);
    if (Write8(&tmp, 4)!=4)
      break;
    ptr++;
  }
  return i;
#endif
}
References Write8().
Referenced by CIccMpeAcs::Write(), CIccFormulaCurveSegment::Write(), CIccSampledCurveSegment::Write(), CIccSegmentedCurve::Write(), CIccSingleSampledCurve::Write(), CIccSampledCalculatorCurve::Write(), CIccMpeCurveSet::Write(), CIccMpeTintArray::Write(), CIccToneMapFunc::Write(), CIccMpeToneMap::Write(), CIccMpeMatrix::Write(), CIccMpeCLUT::Write(), CIccMpeExtCLUT::Write(), CIccMpeCAM::Write(), CIccCalculatorFunc::Write(), CIccMpeCalculator::Write(), CIccMpeSpectralMatrix::Write(), CIccMpeSpectralCLUT::Write(), CIccMpeSpectralObserver::Write(), CIccTagUnknown::Write(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccResponseCurveStruct::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccMpeUnknown::Write(), CIccTagMultiProcessElement::Write(), CIccTagProfileSequenceId::Write(), and WriteFloat32Float().
Write64()
icInt32Number CIccIO::Write64 (void * pBuf64, icInt32Number nNum = 1)
{
#ifndef ICC_BYTE_ORDER_LITTLE_ENDIAN
  return Write8(pBuf64, nNum<<3)>>3;
#else
  icUInt64Number *ptr = (icUInt64Number*)pBuf64;
  icUInt64Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    tmp = *ptr;
    icSwab64(tmp);
    if (Write8(&tmp, 8)!=8)
      break;
    ptr++;
  }
  return i;
#endif
}
References Write8().
Referenced by CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), and CIccTagProfileSeqDesc::Write().
Write8()
virtual icInt32Number CIccIO::Write8 (void * pBuf8, icInt32Number nNum = 1) inline virtual
Reimplemented in CIccFileIO, CIccEmbedIO, CIccMemIO, and CIccNullIO.
{ return 0; }
Referenced by Align32(), CIccMpeAcs::Write(), CIccMpeCLUT::Write(), CIccMpeExtCLUT::Write(), CIccMpeSpectralCLUT::Write(), CIccTagUnknown::Write(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagTextDescription::Write(), CIccTagNamedColor2::Write(), CIccTagCicp::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagData::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagDict::Write(), CIccCLUT::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccMpeUnknown::Write(), CIccProfileIdDesc::Write(), Write16(), Write32(), Write64(), CIccEmbedIO::Write8(), and WriteUInt8Float().
WriteFloat16Float()
icInt32Number CIccIO::WriteFloat16Float (void * pBuf16, icInt32Number nNum = 1)
{
  icFloatNumber *ptr = (icFloatNumber*)pBufFloat;
  icUInt16Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    tmp = icFtoF16(*ptr);
    if (Write16(&tmp, 1)!=1)
      break;
    ptr++;
  }
  return i;
}
References icFtoF16(), and Write16().
Referenced by CIccSingleSampledCurve::Write(), CIccMpeExtCLUT::Write(), CIccMpeSpectralCLUT::Write(), CIccTagSparseMatrixArray::Write(), and CIccTagFloatNum< T, Tsig >::Write().
WriteFloat32Float()
icInt32Number CIccIO::WriteFloat32Float (void * pBufFloat, icInt32Number nNum = 1)
{
  if (sizeof(icFloat32Number)==sizeof(icFloatNumber))
    return Write32(pBufFloat, nNum);
  icFloatNumber *ptr = (icFloatNumber*)pBufFloat;
  icFloat32Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    tmp = (icFloat32Number)*ptr;
    if (Write32(&tmp, 1)!=1)
      break;
    ptr++;
  }
  return i;
}
References Write32().
Referenced by CIccFormulaCurveSegment::Write(), CIccSampledCurveSegment::Write(), CIccSegmentedCurve::Write(), CIccSingleSampledCurve::Write(), CIccSampledCalculatorCurve::Write(), CIccToneMapFunc::Write(), CIccMpeMatrix::Write(), CIccMpeCLUT::Write(), CIccMpeExtCLUT::Write(), CIccMpeCAM::Write(), CIccMpeSpectralMatrix::Write(), CIccMpeSpectralCLUT::Write(), CIccMpeSpectralObserver::Write(), CIccTagSparseMatrixArray::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), and CIccTagGamutBoundaryDesc::Write().
WriteUInt16Float()
icInt32Number CIccIO::WriteUInt16Float (void * pBuf16, icInt32Number nNum = 1)
{
  icFloatNumber *ptr = (icFloatNumber*)pBufFloat;
  icUInt16Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    tmp = (icUInt16Number)(__max(0.0, __min(1.0, *ptr)) * 65535.0 + 0.5);
    if (Write16(&tmp, 1)!=1)
      break;
    ptr++;
  }
  return i;
}
References Write16().
Referenced by CIccSingleSampledCurve::Write(), CIccMpeExtCLUT::Write(), CIccMpeSpectralCLUT::Write(), CIccTagNamedColor2::Write(), CIccTagSparseMatrixArray::Write(), CIccTagCurve::Write(), CIccTagLut16::Write(), and CIccCLUT::WriteData().
WriteUInt8Float()
icInt32Number CIccIO::WriteUInt8Float (void * pBuf16, icInt32Number nNum = 1)
{
  icFloatNumber *ptr = (icFloatNumber*)pBufFloat;
  icUInt8Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    tmp = (icUInt8Number)(__max(0.0, __min(1.0, *ptr)) * 255.0 + 0.5);
    if (Write8(&tmp, 1)!=1)
      break;
    ptr++;
  }
  return i;
}
References Write8().
Referenced by CIccSingleSampledCurve::Write(), CIccMpeExtCLUT::Write(), CIccMpeSpectralCLUT::Write(), CIccTagSparseMatrixArray::Write(), CIccTagLut8::Write(), and CIccCLUT::WriteData().
The documentation for this class was generated from the following files:
IccProfLib/IccIO.h
IccProfLib/IccIO.cpp