iccDEV: CIccIt8Parser Class Reference
CIccIt8Parser Class Reference
Public Member Functions
CIccIt8Parser ()
~CIccIt8Parser ()
bool findTokenLine (std::vector< std::string > &line, const char *szToken)
bool isEOF ()
bool open (const char *szFilename)
bool parseLine (std::vector< std::string > &line)
bool parseNextLine (std::vector< std::string > &line)
Protected Attributes
std::ifstream * m_f
Detailed Description
Constructor & Destructor Documentation
CIccIt8Parser()
CIccIt8Parser::CIccIt8Parser () inline
{ m_f = nullptr; }
References m_f.
~CIccIt8Parser()
CIccIt8Parser::~CIccIt8Parser () inline
{ if (m_f) delete m_f; }
References m_f.
Member Function Documentation
findTokenLine()
bool CIccIt8Parser::findTokenLine (std::vector< std::string > & line, const char * szToken) inline
{
    while (parseNextLine(line)) {
      if (line[0] == szToken)
        break;
    }
    return false;
  }
References parseNextLine().
Referenced by CIccCfgColorData::fromIt8().
isEOF()
bool CIccIt8Parser::isEOF () inline
{ return m_f->eof(); }
References m_f.
Referenced by CIccCfgColorData::fromIt8(), and parseLine().
open()
bool CIccIt8Parser::open (const char * szFilename) inline
{
    if (m_f)
      delete m_f;
    m_f = new std::ifstream(szFilename);
    return m_f != nullptr;
  }
References m_f.
Referenced by CIccCfgColorData::fromIt8().
parseLine()
bool CIccIt8Parser::parseLine (std::vector< std::string > & line) inline
{
    line.clear();
    if (isEOF())
      return false;
    std::string str;
    int c = 0;
    while (!isEOF()) {
      c = m_f->get();
      if (c < 0) {
        if (str.size())
          line.push_back(str);
        if (!line.size())
          return false;
        break;
      }
      else if (c == '\n')
        continue;
      else if (c == '\r') {
        line.push_back(str);
        break;
      }
      else if (c == '\t') {
        line.push_back(str);
        str.clear();
      }
      else {
        str += c;
      }
    }
    return true;
  }
References isEOF(), and m_f.
Referenced by parseNextLine().
parseNextLine()
bool CIccIt8Parser::parseNextLine (std::vector< std::string > & line) inline
{
    while (parseLine(line)) {
      if (line.size())
        return true;
    }
    return false;
  }
References parseLine().
Referenced by findTokenLine(), and CIccCfgColorData::fromIt8().
Field Documentation
m_f
std::ifstream* CIccIt8Parser::m_f protected
Referenced by CIccIt8Parser(), ~CIccIt8Parser(), isEOF(), open(), and parseLine().
The documentation for this class was generated from the following file:
Tools/CmdLine/IccCommon/IccCmmConfig.cpp