iccDEV: CIccTagArray Class Reference
CIccTagArray Class Reference
#include <IccTagComposite.h>
Public Member Functions
CIccTagArray ()
CIccTagArray (const CIccTagArray &lut)
CIccTagArray (icArraySignature sigArrayType)
virtual ~CIccTagArray ()
bool AreAllOfType (icTagTypeSignature sigTagType)
bool AttachTag (icUInt32Number nIndex, CIccTag *pTag)
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
CIccTag * DetachTag (icUInt32Number nIndex, bool bDeleteFlag=false)
IIccArray * GetArrayHandler ()
virtual const icChar * GetClassName () const
virtual IIccExtensionTag * GetExtension ()
CIccTag * GetIndex (icUInt32Number index) const
icUInt32Number GetSize () const
Returns the size of the data array.
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
CIccTagArray & operator= (const CIccTagArray &lut)
CIccTag * operator[] (icUInt32Number index) const
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
bool SetSize (icUInt32Number nSize)
virtual bool SetTagArrayType (icArraySignature sig)
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
static CIccTagArray * ParseMem (icUInt8Number *pMem, icUInt32Number size)
Data Fields
icUInt32Number m_nReserved
Protected Member Functions
void Cleanup ()
Protected Attributes
icUInt32Number m_nSize
IIccArray * m_pArray
icArraySignature m_sigArrayType
IccTagPtr * m_TagVals
Detailed Description
Class: CIccTagArray
Purpose: The Tag Array tag
Constructor & Destructor Documentation
CIccTagArray() [1/3]
CIccTagArray::CIccTagArray ()
Name: CIccTagArray::CIccTagArray
Purpose:
Args:
Return:
{
  m_TagVals = NULL;
  m_nSize = 0;
  m_pArray = NULL;
  m_sigArrayType = icSigUnknownArray;
}
References m_nSize, m_pArray, m_sigArrayType, and m_TagVals.
CIccTagArray() [2/3]
CIccTagArray::CIccTagArray (icArraySignature sigArrayType)
Name: CIccTagArray::CIccTagArray
Purpose:
Args:
Return:
{
  m_TagVals = NULL;
  m_nSize = 0;
  m_pArray = NULL;
  SetTagArrayType(sigArrayType);
}
References m_nSize, m_pArray, m_TagVals, and SetTagArrayType().
CIccTagArray() [3/3]
CIccTagArray::CIccTagArray (const CIccTagArray & tagAry)
Name: CIccTagArray::CIccTagArray
Purpose:
Args:
Return:
{
  if (tagAry.m_nSize) {
    m_TagVals = new IccTagPtr[tagAry.m_nSize];
    icUInt32Number i;
    for (i=0; i<tagAry.m_nSize; i++) {
      if (tagAry.m_TagVals[i].ptr)
        m_TagVals[i].ptr = tagAry.m_TagVals[i].ptr->NewCopy();
      else
        m_TagVals[i].ptr = NULL;
    }
    m_nSize = tagAry.m_nSize;
  }
  m_sigArrayType = tagAry.m_sigArrayType;
  if (tagAry.m_pArray)
    m_pArray = tagAry.m_pArray->NewCopy(this);
  else
    m_pArray = NULL;
}
References m_nSize, m_pArray, m_sigArrayType, m_TagVals, CIccTag::NewCopy(), and IIccArray::NewCopy().
Referenced by NewCopy().
~CIccTagArray()
CIccTagArray::~CIccTagArray () virtual
Name: CIccTagArray::~CIccTagArray
Purpose:
Args:
Return:
{
  Cleanup();
}
References Cleanup().
Member Function Documentation
AreAllOfType()
bool CIccTagArray::AreAllOfType (icTagTypeSignature sigTagType)
Name: CIccTagArray::AreAllOftype
Purpose: checks if all array elements have type signature sigTagType Args: sigTagType Return: true if all elements are of type sigTagType, false otherwise
{
  icUInt32Number i;
  for (i=0; i<m_nSize; i++) {
    CIccTag *pTag = GetIndex(i);
    if (!pTag || pTag->GetType()!=sigTagType)
      return false;
  }
  return true;
}
References GetIndex(), CIccTag::GetType(), and m_nSize.
AttachTag()
bool CIccTagArray::AttachTag (icUInt32Number nIndex, CIccTag * pTag)
Name: CIccTagArray::AttachTag
Purpose: Get a tag entry with a given signature
Args: nIndex - index of tag in array
Return: Pointer to desired tag struct entry, or NULL if not found.
{
  if (nIndex>m_nSize || !pTag) {
    return false;
  }
  if (m_TagVals[nIndex].ptr && m_TagVals[nIndex].ptr != pTag) {
    return false;
  }
  m_TagVals[nIndex].ptr = pTag;
  return true;
}
References m_nSize, and m_TagVals.
Cleanup()
void CIccTagArray::Cleanup () protected
Name: CIccTagArray::Cleanup
Purpose: Detach from a pending IO object
{
  icUInt32Number i, j;
  CIccTag* pTag;
  for (i=0; i<m_nSize; i++) {
    pTag = m_TagVals[i].ptr;
    if (pTag) {
      for (j=i+1; j<m_nSize; j++) {
        if (m_TagVals[i].ptr==pTag)
          m_TagVals[i].ptr = NULL;
      }
      delete pTag;
      m_TagVals[i].ptr = NULL;
    }
  }
  if (m_TagVals)
    free(m_TagVals);
  m_TagVals = nullptr;
  if (m_pArray)
    delete m_pArray;
  m_pArray = NULL;
  m_sigArrayType = icSigUndefinedArray;
}
References icSigUndefinedArray, m_nSize, m_pArray, m_sigArrayType, and m_TagVals.
Referenced by ~CIccTagArray(), operator=(), and Read().
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagArray::Describe (std::string & sDescription, int nVerboseness) virtual
Name: CIccTagArray::Describe
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  std::string name;
  icChar buf[128];
  CIccInfo info;
  IIccArray *pArrayObj = GetArrayHandler();
  CIccArrayCreator::GetArraySigName(name, m_sigArrayType);
  sDescription += "BEGIN TAG_ARRAY \"";
  sDescription += name;
  sDescription += "\"\n\n";
  icUInt32Number i;
  for (i=0; i<m_nSize; i++) {
    if (i)
      sDescription += "\n";
    sprintf(buf, "BEGIN INDEX[%d]\n", i);
    sDescription +=  buf;
    if (m_TagVals[i].ptr) {
      m_TagVals[i].ptr->Describe(sDescription, nVerboseness);
    }
    sprintf(buf, "END INDEX[%d]\n", i);
    sDescription += buf;
  }
  sDescription += "\n";
  sDescription += "END TAG_ARRAY \"";
  sDescription += name;
  sDescription += "\"\n";
}
References CIccTag::Describe(), GetArrayHandler(), CIccArrayCreator::GetArraySigName(), m_nSize, m_sigArrayType, and m_TagVals.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
DetachTag()
CIccTag * CIccTagArray::DetachTag (icUInt32Number nIndex, bool bDeleteFlag = false)
Name: CIccTagArray::DetachTag
Purpose: Detach tag value at given index
Args: nIndex - index of tag in array bDeleteFlag - flag indicating detached tag should be deleted
Return: Pointer to Detached tag struct entry, or NULL if not found or deleted.
{
   if (nIndex>m_nSize)
     return NULL;
   CIccTag *rv = m_TagVals[nIndex].ptr;
   m_TagVals[nIndex].ptr = NULL;
   if (bDeleteFlag) {
     delete rv;
     rv = NULL;
   }
   return rv;
}
References m_nSize, and m_TagVals.
GetArrayHandler()
IIccArray * CIccTagArray::GetArrayHandler ()
Name: CIccTagArray::GetArrayHandler
Purpose: Get Array object handler
Args:
Return: Pointer to an Array object handler for the associated array type
{
  if (!m_pArray) {
    m_pArray = CIccArrayCreator::CreateArray(m_sigArrayType, this);
  }
  return m_pArray;
}
References CIccArrayCreator::CreateArray(), m_pArray, and m_sigArrayType.
Referenced by Describe(), and icGetTagArrayHandler().
GetClassName()
virtual const icChar * CIccTagArray::GetClassName () const inline virtual
Reimplemented from CIccTag.
Reimplemented in CIccTagXmlArray.
{ return "CIccTagArray"; }
GetExtension()
virtual IIccExtensionTag * CIccTag::GetExtension () inline virtual inherited
Reimplemented in CIccTagXmlUnknown, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, CIccTagXmlSignature, CIccTagXmlNamedColor2, CIccTagXmlXYZ, CIccTagXmlChromaticity, CIccTagXmlCicp, CIccTagXmlSparseMatrixArray, CIccTagXmlFixedNum< T, Tsig >, CIccTagXmlNum< T, A, Tsig >, CIccTagXmlFloatNum< T, A, Tsig >, CIccTagXmlMeasurement, CIccTagXmlMultiLocalizedUnicode, CIccTagXmlTagData, CIccTagXmlDateTime, CIccTagXmlColorantOrder, CIccTagXmlColorantTable, CIccTagXmlViewingConditions, CIccTagXmlSpectralDataInfo, CIccTagXmlSpectralViewingConditions, CIccTagXmlProfileSeqDesc, CIccTagXmlResponseCurveSet16, CIccTagXmlCurve, CIccTagXmlParametricCurve, CIccTagXmlSegmentedCurve, CIccTagXmlLutAtoB, CIccTagXmlLutBtoA, CIccTagXmlLut8, CIccTagXmlLut16, CIccTagXmlMultiProcessElement, CIccTagXmlProfileSequenceId, CIccTagXmlDict, CIccTagXmlStruct, CIccTagXmlArray, CIccTagXmlGamutBoundaryDesc, CIccTagXmlEmbeddedHeightImage, CIccTagXmlEmbeddedNormalImage, and CIccTagXmlEmbeddedProfile.
{return NULL;}
Referenced by icCurvesFromXml(), icCurvesToXml(), icProfDescToXml(), icXmlParseProfDesc(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeXmlTintArray::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
GetIndex()
CIccTag * CIccTagArray::GetIndex (icUInt32Number nIndex) const
Name: CIccTagArray::GetIndex
Purpose: Get a tag entry with a given index
Args: nIndex - index of tag in array
Return: Pointer to desired tag entry, or NULL if not found.
{
  if (nIndex>m_nSize)
    return NULL;
  return m_TagVals[nIndex].ptr;
}
References m_nSize, and m_TagVals.
Referenced by AreAllOfType(), CIccArrayNamedColor::Begin(), CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), operator[](), CIccArrayUnknown::Validate(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetSize()
icUInt32Number CIccTagArray::GetSize () const inline
Returns the size of the data array.
{ return m_nSize; }
References m_nSize.
Referenced by CIccArrayNamedColor::Begin(), CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccArrayUnknown::Validate(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetTagArrayType()
virtual icArraySignature CIccTagArray::GetTagArrayType () const inline virtual
Reimplemented from CIccTag.
{ return m_sigArrayType; }
References m_sigArrayType.
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagArray::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigTagArrayType; }
References icSigTagArrayType.
Referenced by Write().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
virtual CIccTag * CIccTagArray::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
{ return new CIccTagArray(*this);}
References CIccTagArray().
operator=()
CIccTagArray & CIccTagArray::operator= (const CIccTagArray & tagAry)
Name: &operator=
Purpose:
Args:
Return:
{
  if (&tagAry == this)
    return *this;
  Cleanup();
  if (tagAry.m_nSize) {
    m_TagVals = new IccTagPtr[tagAry.m_nSize];
    icUInt32Number i;
    for (i=0; i<m_nSize; i++) {
      if (tagAry.m_TagVals[i].ptr)
        m_TagVals[i].ptr = tagAry.m_TagVals[i].ptr->NewCopy();
      else
        m_TagVals[i].ptr = NULL;
    }
    m_nSize = tagAry.m_nSize;
  }
  m_sigArrayType = tagAry.m_sigArrayType;
  if (tagAry.m_pArray)
    m_pArray = tagAry.m_pArray->NewCopy(this);
  else
    m_pArray = NULL;
  return *this;
}
References Cleanup(), m_nSize, m_pArray, m_sigArrayType, m_TagVals, CIccTag::NewCopy(), and IIccArray::NewCopy().
operator[]()
CIccTag * CIccTagArray::operator[] (icUInt32Number index) const inline
{ return GetIndex(index); }
References GetIndex().
ParseMem()
static CIccTagArray * CIccTagArray::ParseMem (icUInt8Number * pMem, icUInt32Number size) static
Read() [1/2]
bool CIccTagArray::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagArray::Read
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  icUInt32Number headerSize = sizeof(icTagTypeSignature) +
    sizeof(icUInt32Number) +
    sizeof(icTagTypeSignature) +
    sizeof(icStructSignature) +
    sizeof(icUInt32Number);
  if (headerSize > size)
    return false;
  if (!pIO) {
    return false;
  }
  Cleanup();
  icUInt32Number nTagStart = pIO->Tell();
  if (!pIO->Read32(&sig))
    return false;
  icArraySignature sigArrayType;
  if (!pIO->Read32(&m_nReserved) ||
      !pIO->Read32(&sigArrayType))
    return false;
  SetTagArrayType(sigArrayType);
  icUInt32Number count, i, j;
  IccTagEntry TagEntry;
  TagEntry.pTag = NULL;
  if (!pIO->Read32(&count))
    return false;
  if (headerSize + count*sizeof(icPositionNumber) > size)
    return false;
  if (count) {
    icPositionNumber *tagPos = new icPositionNumber[count];
    if (!SetSize(count)) {
      delete[] tagPos;
      return false;
    }
    for (i=0; i<count; i++) {
      if (!pIO->Read32(&tagPos[i].offset) ||
          !pIO->Read32(&tagPos[i].size)) {
        delete [] tagPos;
        return false;
      }
    }
    for (i=0; i<count; i++) {
      if (!tagPos[i].offset || !tagPos[i].size) {
        m_TagVals[i].ptr = NULL;
        continue;
      }
      for (j=0; j<i; j++) {
        if (tagPos[i].offset == tagPos[j].offset)
          break;
      }
      if (j<i) {
        m_TagVals[i].ptr = m_TagVals[j].ptr;
      }
      else {
        if (tagPos[i].offset + tagPos[i].size > size) {
          delete [] tagPos;
          return false;
        }
        pIO->Seek(nTagStart + tagPos[i].offset, icSeekSet);
        icTagTypeSignature tagSig;
        pIO->Read32(&tagSig);
        pIO->Seek(nTagStart + tagPos[i].offset, icSeekSet);
        CIccTag *pTag = CIccTagCreator::CreateTag(tagSig);
        if (pTag) {
          if (!pTag->Read(tagPos[i].size, pIO)) {
            delete [] tagPos;
            return false;
          }
          m_TagVals[i].ptr = pTag;
        }
        else {
          delete [] tagPos;
          return false;
        }
      }
    }
    delete [] tagPos;
  }
  return true;
}
References Cleanup(), CIccTagCreator::CreateTag(), icSeekSet, CIccTag::m_nReserved, m_TagVals, icPositionNumber::offset, CIccTag::Read(), CIccIO::Read32(), CIccIO::Seek(), SetSize(), SetTagArrayType(), icPositionNumber::size, and CIccIO::Tell().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
SetSize()
bool CIccTagArray::SetSize (icUInt32Number nSize)
Name: CIccTagArray::SetSize
Purpose: Sets the size of the tag array.
Args: nSize - number of tag entries,
{
  if (!m_nSize) {
    m_TagVals = (IccTagPtr*)calloc(nSize, sizeof(IccTagPtr));
    if (!m_TagVals) {
      m_nSize =0;
      return false;
    }
  }
  else {
    if (nSize<=m_nSize)
      return true;
    m_TagVals = (IccTagPtr*)icRealloc(m_TagVals, nSize*sizeof(IccTagPtr));
    if (!m_TagVals) {
      m_nSize = 0;
      return false;
    }
    memset(&m_TagVals[m_nSize], 0, (nSize-m_nSize)*sizeof(IccTagPtr));
  }
  m_nSize = nSize;
  return true;
}
References icRealloc(), m_nSize, and m_TagVals.
Referenced by CIccTagXmlArray::ParseXml(), and Read().
SetTagArrayType()
bool CIccTagArray::SetTagArrayType (icArraySignature sig) virtual
Name: CIccTagArray::~SetTagArrayType
Purpose: Set the signature of the tag array type. This also sets the m_pArray to allow array type specific handling to be utilized.
Args: sig - signature of array type
Return: true if sig is a recognized array type, false otherwise
{
  if (m_pArray)
    delete m_pArray;
  m_sigArrayType = sig;
  m_pArray = CIccArrayCreator::CreateArray(m_sigArrayType, this);
  return (m_pArray != NULL) || (m_sigArrayType == icSigUtf8TextTypeArray);
}
References CIccArrayCreator::CreateArray(), icSigUtf8TextTypeArray, m_pArray, and m_sigArrayType.
Referenced by CIccTagArray(), CIccTagXmlArray::ParseXml(), and Read().
Validate()
icValidateStatus CIccTagArray::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagArray::Validate
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sigAryPath = sigPath + icGetSigPath(m_sigArrayType);
  if (m_pArray) {  //Should call GetArrayHandler before validate to get
    rv = icMaxStatus(rv, m_pArray->Validate(sigPath, sReport, pProfile));
  }
  else if (m_sigArrayType==icSigUtf8TextTypeArray) { //UTF8 text arrays are known
    //Check # of channels
    if (icGetFirstSigPathSig(sigPath) == icSigMaterialTypeArrayTag &&
        pProfile &&
        m_nSize != icGetMaterialColorSpaceSamples(pProfile->m_Header.mcs)) {
      std::string sSigPathName = Info.GetSigPathName(sigPath);
      sReport += icMsgValidateCriticalError;
      sReport += sSigPathName;
      sReport += " - Number of material channel names does not match MCS in header.\n";
      rv = icMaxStatus(rv, icValidateCriticalError);
    }
    icUInt32Number i;
    for (i=0; i<m_nSize; i++) {
      rv = icMaxStatus(rv, m_TagVals[i].ptr->Validate(sigAryPath, sReport, pProfile));
    }
  }
  else {
    icUInt32Number i;
    sReport += "Unknown tag array type - Validating array sub-tags\n";
    rv = icMaxStatus(rv, icValidateWarning);
    for (i=0; i<m_nSize; i++) {
      rv = icMaxStatus(rv, m_TagVals[i].ptr->Validate(sigAryPath, sReport, pProfile));
    }
  }
  return rv;
}
References CIccInfo::GetSigPathName(), icGetFirstSigPathSig(), icGetMaterialColorSpaceSamples(), icGetSigPath(), icMaxStatus(), icMsgValidateCriticalError, icSigMaterialTypeArrayTag, icSigUtf8TextTypeArray, icValidateCriticalError, icValidateWarning, m_nSize, m_pArray, m_sigArrayType, m_TagVals, icHeader::mcs, CIccTag::Validate(), and IIccArray::Validate().
Write()
bool CIccTagArray::Write (CIccIO * pIO) virtual
Name: CIccTagArray::Write
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  if (!pIO)
    return false;
  icUInt32Number nTagStart = pIO->Tell();
  if (!pIO->Write32(&sig))
    return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  if (!pIO->Write32(&m_sigArrayType))
    return false;
  if (!pIO->Write32(&m_nSize))
    return false;
  if (m_nSize) {
    icUInt32Number i, j;
    icUInt32Number pos = pIO->Tell();
    //Write Unintialized TagPosition block
    icUInt32Number zero = 0;
    for (i=0; i<m_nSize; i++) {
      if (!pIO->Write32(&zero) || !pIO->Write32(&zero))
        return false;
    }
    icPositionNumber *tagPos = new icPositionNumber[m_nSize];
    if (!tagPos)
      return false;
    //Write Tags
    for (i=0; i<m_nSize; i++) {
      if (m_TagVals[i].ptr) {
        for (j=0; j<i; j++) {
          if (m_TagVals[i].ptr==m_TagVals[j].ptr)
            break;
        }
        if (j<i) {
          tagPos[i].offset = tagPos[j].offset;
          tagPos[i].size = tagPos[j].offset;
        }
        else {
          tagPos[i].offset = pIO->Tell() - nTagStart;
          if (!m_TagVals[i].ptr->Write(pIO)) {
            delete [] tagPos;
            return false;
          }
          tagPos[i].size =  pIO->Tell() - nTagStart - tagPos[i].offset;
          pIO->Align32();
        }
      }
      else {
        tagPos[i].offset = 0;
        tagPos[i].size = 0;
      }
    }
    icUInt32Number endPos = pIO->Tell();
    //Update TagPosition block
    pIO->Seek(pos, icSeekSet);
    for (i=0; i<m_nSize; i++) {
      if (!pIO->Write32(&tagPos[i].offset) ||
          !pIO->Write32(&tagPos[i].size)) {
          delete [] tagPos;
          return false;
      }
    }
    delete[] tagPos;
    pIO->Seek(endPos, icSeekSet);
  }
  return true;
}
References CIccIO::Align32(), GetType(), icSeekSet, CIccTag::m_nReserved, m_nSize, m_sigArrayType, m_TagVals, icPositionNumber::offset, CIccIO::Seek(), icPositionNumber::size, CIccIO::Tell(), CIccTag::Write(), and CIccIO::Write32().
Field Documentation
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_nSize
icUInt32Number CIccTagArray::m_nSize protected
Referenced by CIccTagArray(), CIccTagArray(), CIccTagArray(), AreAllOfType(), AttachTag(), Cleanup(), Describe(), DetachTag(), GetIndex(), GetSize(), operator=(), CIccTagXmlArray::ParseXml(), SetSize(), CIccTagXmlArray::ToXml(), Validate(), and Write().
m_pArray
IIccArray* CIccTagArray::m_pArray protected
Referenced by CIccTagArray(), CIccTagArray(), CIccTagArray(), Cleanup(), GetArrayHandler(), operator=(), SetTagArrayType(), and Validate().
m_sigArrayType
icArraySignature CIccTagArray::m_sigArrayType protected
Referenced by CIccTagArray(), CIccTagArray(), Cleanup(), Describe(), GetArrayHandler(), GetTagArrayType(), operator=(), SetTagArrayType(), CIccTagXmlArray::ToXml(), Validate(), and Write().
m_TagVals
IccTagPtr* CIccTagArray::m_TagVals protected
Referenced by CIccTagArray(), CIccTagArray(), CIccTagArray(), AttachTag(), Cleanup(), Describe(), DetachTag(), GetIndex(), operator=(), CIccTagXmlArray::ParseXml(), Read(), SetSize(), CIccTagXmlArray::ToXml(), Validate(), and Write().
The documentation for this class was generated from the following files:
IccProfLib/IccTagComposite.h
IccProfLib/IccTagComposite.cpp