iccDEV: IIccProfileConnectionConditions Class Reference
IIccProfileConnectionConditions Class Reference abstract
#include <IccPcc.h>
Public Member Functions
virtual ~IIccProfileConnectionConditions ()
virtual CIccTagMultiProcessElement * getCustomToStandardPcc ()=0
icFloatNumber * getEmissiveObserver (const icSpectralRange &range, const icFloatNumber *pWhite, icFloatNumber *obsMatrix=NULL)
virtual void getLumIlluminantXYZ (icFloatNumber *pXYZ)=0
virtual bool getMediaWhiteXYZ (icFloatNumber *pXYZ)=0
virtual void getNormIlluminantXYZ (icFloatNumber *pXYZ)=0
icFloatNumber getObserverIlluminantScaleFactor ()
icFloatNumber getObserverWhiteScaleFactor (const icFloatNumber *pWhite, const icSpectralRange &whiteRange)
icFloatNumber getPccCCT ()
icIlluminant getPccIlluminant ()
icStandardObserver getPccObserver ()
virtual const CIccTagSpectralViewingConditions * getPccViewingConditions ()=0
CIccMatrixMath * getReflectanceObserver (const icSpectralRange &rangeRef)
virtual CIccTagMultiProcessElement * getStandardToCustomPcc ()=0
bool hasIlluminantSPD ()
bool isEquivalentPcc (IIccProfileConnectionConditions &IPCC)
bool isStandardPcc ()
Detailed Description
Type: Class
Purpose: Interface for accessing Connection Conditions
Constructor & Destructor Documentation
~IIccProfileConnectionConditions()
virtual IIccProfileConnectionConditions::~IIccProfileConnectionConditions () inline virtual
{}
Member Function Documentation
getCustomToStandardPcc()
virtual CIccTagMultiProcessElement * IIccProfileConnectionConditions::getCustomToStandardPcc () pure virtual
Implemented in CIccCombinedConnectionConditions.
Referenced by CIccCombinedConnectionConditions::getCustomToStandardPcc().
getEmissiveObserver()
icFloatNumber * IIccProfileConnectionConditions::getEmissiveObserver (const icSpectralRange & range, const icFloatNumber * pWhite, icFloatNumber * obsMatrix = NULL)
{
  const CIccTagSpectralViewingConditions *pView = getPccViewingConditions();
  if (!pView || !pWhite)
    return NULL;
  int i, n = range.steps, size = 3*n;
  const icFloatNumber *fptr;
  icFloatNumber *tptr;
  icSpectralRange observerRange;
  const icFloatNumber *observer = pView->getObserver(observerRange);
  if (!obs)
    obs = (icFloatNumber*)malloc(size*sizeof(icFloatNumber));
  if (obs) {
    CIccMatrixMath *mapRange=CIccMatrixMath::rangeMap(observerRange, range);
    //Copy observer while adjusting to range
    if (mapRange) {
        fptr = &observer[0];
        tptr = obs;
        for (i = 0; i < 3; i++) {
            mapRange->VectorMult(tptr, fptr);
            fptr += observerRange.steps;
            tptr += range.steps;
        }
        delete mapRange;
    }
    else {
      memcpy(obs, observer, size*sizeof(icFloatNumber));
    }
    //Calculate scale constant
    icFloatNumber k=0.0f;
    fptr = &obs[range.steps]; //Using second color matching function
    for (i=0; i<(int)range.steps; i++) {
      k += fptr[i]*pWhite[i];
    }
    //Scale observer so application of observer against white results in 1.0.
    for (i=0; i<size; i++) {
      obs[i] = obs[i] / k;
    }
    CIccMatrixMath observerMtx(3,range.steps);
    memcpy(observerMtx.entry(0), obs, size*sizeof(icFloatNumber));
    icFloatNumber xyz[3];
    observerMtx.VectorMult(xyz, pWhite);
  }
  return obs;
}
References CIccMatrixMath::CIccMatrixMath(), CIccMatrixMath::entry(), CIccTagSpectralViewingConditions::getObserver(), getPccViewingConditions(), CIccMatrixMath::rangeMap(), icSpectralRange::steps, and CIccMatrixMath::VectorMult().
Referenced by CIccMpeEmissionMatrix::Begin(), CIccMpeInvEmissionMatrix::Begin(), CIccMpeEmissionCLUT::Begin(), CIccMpeReflectanceCLUT::Begin(), CIccMpeEmissionObserver::Begin(), and CIccMpeReflectanceObserver::Begin().
getLumIlluminantXYZ()
virtual void IIccProfileConnectionConditions::getLumIlluminantXYZ (icFloatNumber * pXYZ) pure virtual
Implemented in CIccCombinedConnectionConditions.
getMediaWhiteXYZ()
virtual bool IIccProfileConnectionConditions::getMediaWhiteXYZ (icFloatNumber * pXYZ) pure virtual
Implemented in CIccCombinedConnectionConditions.
getNormIlluminantXYZ()
virtual void IIccProfileConnectionConditions::getNormIlluminantXYZ (icFloatNumber * pXYZ) pure virtual
Implemented in CIccCombinedConnectionConditions.
Referenced by isEquivalentPcc().
getObserverIlluminantScaleFactor()
icFloatNumber IIccProfileConnectionConditions::getObserverIlluminantScaleFactor ()
{
  const CIccTagSpectralViewingConditions *pView = getPccViewingConditions();
  if (!pView)
    return 1.0;
  icSpectralRange illumRange;
  const icFloatNumber *illum = pView->getIlluminant(illumRange);
  icSpectralRange obsRange;
  const icFloatNumber *obs = pView->getObserver(obsRange);
  int i, n = illumRange.steps;
  CIccMatrixMath *mapRange=CIccMatrixMath::rangeMap(obsRange, illumRange);
  icFloatNumber rv=0;
  if (mapRange) {
    icFloatNumber *Ycmf = new icFloatNumber[illumRange.steps];
    mapRange->VectorMult(Ycmf, &obs[obsRange.steps]);
    delete mapRange;
    for (i=0; i<n; i++) {
      rv += Ycmf[i]*illum[i];
    }
    delete [] Ycmf;
  }
  else {
   const icFloatNumber *Ycmf = &obs[obsRange.steps];
    for (i=0; i<n; i++) {
      rv += Ycmf[i]*illum[i];
    }
  }
  return rv;
}
References CIccTagSpectralViewingConditions::getIlluminant(), CIccTagSpectralViewingConditions::getObserver(), getPccViewingConditions(), CIccMatrixMath::rangeMap(), icSpectralRange::steps, and CIccMatrixMath::VectorMult().
getObserverWhiteScaleFactor()
icFloatNumber IIccProfileConnectionConditions::getObserverWhiteScaleFactor (const icFloatNumber * pWhite, const icSpectralRange & whiteRange)
{
  const CIccTagSpectralViewingConditions *pView = getPccViewingConditions();
  if (!pView)
    return 1.0;
  icSpectralRange obsRange;
  const icFloatNumber *obs = pView->getObserver(obsRange);
  int i, n = whiteRange.steps;
  CIccMatrixMath *mapRange=CIccMatrixMath::rangeMap(obsRange, whiteRange);
  icFloatNumber rv=0;
  if (mapRange) {
    icFloatNumber *Ycmf = new icFloatNumber[whiteRange.steps];
    mapRange->VectorMult(Ycmf, &obs[obsRange.steps]);
    delete mapRange;
    for (i=0; i<n; i++) {
      rv += Ycmf[i]*pWhite[i];
    }
    delete [] Ycmf;
  }
  else {
    const icFloatNumber *Ycmf = &obs[obsRange.steps];
    for (i=0; i<n; i++) {
      rv += Ycmf[i]*pWhite[i];
    }
  }
  return rv;
}
References CIccTagSpectralViewingConditions::getObserver(), getPccViewingConditions(), CIccMatrixMath::rangeMap(), icSpectralRange::steps, and CIccMatrixMath::VectorMult().
getPccCCT()
icFloatNumber IIccProfileConnectionConditions::getPccCCT ()
{
  const CIccTagSpectralViewingConditions *pCond = getPccViewingConditions();
  if (!pCond)
    return 0.0f;
  return pCond->getIlluminantCCT();
}
References CIccTagSpectralViewingConditions::getIlluminantCCT(), and getPccViewingConditions().
Referenced by isEquivalentPcc().
getPccIlluminant()
icIlluminant IIccProfileConnectionConditions::getPccIlluminant ()
{
  const CIccTagSpectralViewingConditions *pCond = getPccViewingConditions();
  if (!pCond)
    return icIlluminantD50;
  return pCond->getStdIllumiant();
}
References getPccViewingConditions(), CIccTagSpectralViewingConditions::getStdIllumiant(), and icIlluminantD50.
Referenced by isEquivalentPcc(), and isStandardPcc().
getPccObserver()
icStandardObserver IIccProfileConnectionConditions::getPccObserver ()
{
 const  CIccTagSpectralViewingConditions *pCond = getPccViewingConditions();
  if (!pCond)
    return icStdObs1931TwoDegrees;
  return pCond->getStdObserver();
}
References getPccViewingConditions(), CIccTagSpectralViewingConditions::getStdObserver(), and icStdObs1931TwoDegrees.
Referenced by isEquivalentPcc(), and isStandardPcc().
getPccViewingConditions()
virtual const CIccTagSpectralViewingConditions * IIccProfileConnectionConditions::getPccViewingConditions () pure virtual
Implemented in CIccCombinedConnectionConditions.
Referenced by CIccCombinedConnectionConditions::CIccCombinedConnectionConditions(), CIccMpeEmissionMatrix::Begin(), CIccMpeInvEmissionMatrix::Begin(), CIccMpeEmissionCLUT::Begin(), CIccMpeReflectanceCLUT::Begin(), CIccMpeEmissionObserver::Begin(), CIccMpeReflectanceObserver::Begin(), getEmissiveObserver(), getObserverIlluminantScaleFactor(), getObserverWhiteScaleFactor(), getPccCCT(), getPccIlluminant(), getPccObserver(), CIccCombinedConnectionConditions::getPccViewingConditions(), getReflectanceObserver(), and hasIlluminantSPD().
getReflectanceObserver()
CIccMatrixMath * IIccProfileConnectionConditions::getReflectanceObserver (const icSpectralRange & rangeRef)
{
  CIccMatrixMath *pAdjust=NULL, *pMtx;
  const CIccTagSpectralViewingConditions *pView = getPccViewingConditions();
  icSpectralRange illumRange;
  const icFloatNumber *illum = pView->getIlluminant(illumRange);
  pMtx = CIccMatrixMath::rangeMap(rangeRef, illumRange);
  if (pMtx)
    pAdjust = pMtx;
  pMtx = pView->getObserverMatrix(illumRange);
  if (pAdjust) {
    pMtx = pAdjust->Mult(pMtx);
    delete pAdjust;
  }
  pAdjust = pMtx;
  pAdjust->VectorScale(illum);
  pAdjust->Scale(1.0f / pAdjust->RowSum(1));
  return pAdjust;
}
References CIccTagSpectralViewingConditions::getIlluminant(), CIccTagSpectralViewingConditions::getObserverMatrix(), getPccViewingConditions(), CIccMatrixMath::Mult(), CIccMatrixMath::rangeMap(), CIccMatrixMath::RowSum(), CIccMatrixMath::Scale(), and CIccMatrixMath::VectorScale().
getStandardToCustomPcc()
virtual CIccTagMultiProcessElement * IIccProfileConnectionConditions::getStandardToCustomPcc () pure virtual
Implemented in CIccCombinedConnectionConditions.
Referenced by CIccCombinedConnectionConditions::getStandardToCustomPcc().
hasIlluminantSPD()
bool IIccProfileConnectionConditions::hasIlluminantSPD ()
{
  const  CIccTagSpectralViewingConditions *pCond = getPccViewingConditions();
  if (!pCond)
    return false;
  icSpectralRange illumRange;
  const icFloatNumber *illum = pCond->getIlluminant(illumRange);
  if (!illumRange.steps || !illum)
    return false;
  return true;
}
References CIccTagSpectralViewingConditions::getIlluminant(), getPccViewingConditions(), and icSpectralRange::steps.
Referenced by isEquivalentPcc().
isEquivalentPcc()
bool IIccProfileConnectionConditions::isEquivalentPcc (IIccProfileConnectionConditions & IPCC)
{
  icIlluminant illum = getPccIlluminant();
  icStandardObserver obs = getPccObserver();
  if (illum!=IPCC.getPccIlluminant() || obs!= IPCC.getPccObserver())
    return false;
  if ((illum==icIlluminantDaylight || illum==icIlluminantBlackBody) && getPccCCT()!=IPCC.getPccCCT())
    return false;
  if (illum==icIlluminantUnknown)
    return false;
  if (obs==icStdObsCustom) {
    if (!hasIlluminantSPD() && !IPCC.hasIlluminantSPD()) {
      icFloatNumber XYZ1[3], XYZ2[3];
      getNormIlluminantXYZ(&XYZ1[0]);
      IPCC.getNormIlluminantXYZ(&XYZ2[0]);
      if (XYZ1[0]!=XYZ2[0] ||
          XYZ1[1]!=XYZ2[1] ||
          XYZ1[2]!=XYZ2[2])
        return false;
    }
    else {
      return false;
    }
  }
  return true;
}
References getNormIlluminantXYZ(), getPccCCT(), getPccIlluminant(), getPccObserver(), hasIlluminantSPD(), icIlluminantBlackBody, icIlluminantDaylight, and icIlluminantUnknown.
isStandardPcc()
bool IIccProfileConnectionConditions::isStandardPcc ()
{
  if (getPccIlluminant()==icIlluminantD50 && getPccObserver()==icStdObs1931TwoDegrees)
    return true;
  return false;
}
References getPccIlluminant(), getPccObserver(), icIlluminantD50, and icStdObs1931TwoDegrees.
The documentation for this class was generated from the following files:
IccProfLib/IccPcc.h
IccProfLib/IccPcc.cpp