iccDEV: CIccSparseMatrixUInt16 Class Reference
CIccSparseMatrixUInt16 Class Reference
#include <IccSparseMatrix.h>
Public Member Functions
CIccSparseMatrixUInt16 ()
virtual icFloatNumber get (int index) const
virtual icUInt8Number * getPtr (int index) const
void init (void *pData)
virtual void set (int index, icFloatNumber value)
virtual icUInt8Number size () const
Protected Attributes
icUInt16Number * m_pData
Detailed Description
Constructor & Destructor Documentation
CIccSparseMatrixUInt16()
CIccSparseMatrixUInt16::CIccSparseMatrixUInt16 () inline
{}
Referenced by CIccSparseMatrix::CIccSparseMatrix(), CIccSparseMatrix::Init(), and CIccSparseMatrix::operator=().
Member Function Documentation
get()
virtual icFloatNumber CIccSparseMatrixUInt16::get (int index) const inline virtual
Implements IIccSparseMatrixEntry.
{return (icFloatNumber)m_pData[index]/65535.0f;}
getPtr()
virtual icUInt8Number * CIccSparseMatrixEntry< icUInt16Number >::getPtr (int index) const inline virtual inherited
Implements IIccSparseMatrixEntry.
{return (icUInt8Number*)(&m_pData[index]); }
init()
void CIccSparseMatrixEntry< icUInt16Number >::init (void * pData) inline virtual inherited
Implements IIccSparseMatrixEntry.
{m_pData = (T*)pData;}
set()
virtual void CIccSparseMatrixUInt16::set (int index, icFloatNumber value) inline virtual
Implements IIccSparseMatrixEntry.
{m_pData[index] = value<0.0 ? 0 : (value > 1.0 ? 65535 : (icUInt8Number)(value*65535.0f+0.5f));}
size()
virtual icUInt8Number CIccSparseMatrixEntry< icUInt16Number >::size () const inline virtual inherited
Implements IIccSparseMatrixEntry.
{ return sizeof(T); }
Field Documentation
m_pData
icUInt16Number * CIccSparseMatrixEntry< icUInt16Number >::m_pData protected inherited
The documentation for this class was generated from the following file:
IccProfLib/IccSparseMatrix.h