iccDEV: IIccCalcDebugger Class Reference
IIccCalcDebugger Class Reference abstract
#include <IccMpeCalc.h>
Public Member Functions
virtual ~IIccCalcDebugger ()
virtual bool AfterOp (SIccCalcOp *op, SIccOpState &os, SIccCalcOp *ops)=0
virtual bool BeforeOp (SIccCalcOp *op, SIccOpState &os, SIccCalcOp *ops)=0
virtual void BeginApply ()=0
virtual void EndApply ()=0
virtual void Error (const char *msg)=0
Static Public Member Functions
static void SetDebugger (IIccCalcDebugger *pDebugger)
Detailed Description
Constructor & Destructor Documentation
~IIccCalcDebugger()
virtual IIccCalcDebugger::~IIccCalcDebugger () inline virtual
{}
Member Function Documentation
AfterOp()
virtual bool IIccCalcDebugger::AfterOp (SIccCalcOp * op, SIccOpState & os, SIccCalcOp * ops) pure virtual
Implemented in CIccConsoleDebugger, and CIccLogDebugger.
Referenced by CIccCalculatorFunc::ApplySequence().
BeforeOp()
virtual bool IIccCalcDebugger::BeforeOp (SIccCalcOp * op, SIccOpState & os, SIccCalcOp * ops) pure virtual
Implemented in CIccConsoleDebugger, and CIccLogDebugger.
Referenced by CIccCalculatorFunc::ApplySequence().
BeginApply()
virtual void IIccCalcDebugger::BeginApply () pure virtual
Implemented in CIccConsoleDebugger, and CIccLogDebugger.
Referenced by CIccMpeCalculator::Apply().
EndApply()
virtual void IIccCalcDebugger::EndApply () pure virtual
Implemented in CIccConsoleDebugger, and CIccLogDebugger.
Referenced by CIccMpeCalculator::Apply().
Error()
virtual void IIccCalcDebugger::Error (const char * msg) pure virtual
Implemented in CIccConsoleDebugger, and CIccLogDebugger.
Referenced by CIccMpeCalculator::Apply(), and CIccOpDefInvalid::Exec().
SetDebugger()
void IIccCalcDebugger::SetDebugger (IIccCalcDebugger * pDebugger) static
{
  if (pDebugger == icCalcDebuggerConsole)
    g_pDebugger = &g_ConsoleDebugger;
  else
    g_pDebugger = pDebugger;
}
References g_ConsoleDebugger, and g_pDebugger.
Referenced by main().
The documentation for this class was generated from the following files:
IccProfLib/IccMpeCalc.h
IccProfLib/IccMpeCalc.cpp