iccDEV: CIccArrayColorantInfo Class Reference
CIccArrayColorantInfo Class Reference
#include <IccArrayBasic.h>
Public Member Functions
CIccArrayColorantInfo (CIccTagArray *pTagArray=NULL)
virtual ~CIccArrayColorantInfo ()
virtual void Describe (std::string &sDescription, int nVerboseness) const
virtual const icChar * GetClassName () const
CIccTagArray * GetTagArray ()
virtual IIccArray * NewCopy (CIccTagArray *pTagArray) const
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
Protected Attributes
CIccTagArray * m_pTag
CIccTagArray * m_pTagArray
icArraySignature m_sig
Detailed Description
Class: CIccArrayColorantInfo
Purpose: The ColorantInfo array handler
Constructor & Destructor Documentation
CIccArrayColorantInfo()
CIccArrayColorantInfo::CIccArrayColorantInfo (CIccTagArray * pTagArray = NULL)
{
  m_pTag = pTagArray;
  m_sig = icSigColorantInfoArray;
}
References icSigColorantInfoArray, CIccArrayUnknown::m_pTag, and CIccArrayUnknown::m_sig.
Referenced by CIccBasicArrayFactory::CreateArray(), and NewCopy().
~CIccArrayColorantInfo()
CIccArrayColorantInfo::~CIccArrayColorantInfo () virtual
{
}
Member Function Documentation
Describe()
void CIccArrayColorantInfo::Describe (std::string & sDescription, int nVerboseness) const virtual
Reimplemented from CIccArrayUnknown.
{
    sDescription += "\nCIccArrayColorantInfo::Describe()\n";
}
GetClassName()
virtual const icChar * CIccArrayColorantInfo::GetClassName () const inline virtual
Reimplemented from CIccArrayUnknown.
{ return "CIccArrayColorantInfo"; }
GetTagArray()
CIccTagArray * IIccArray::GetTagArray () inline inherited
{ return m_pTagArray; }
References IIccArray::m_pTagArray.
NewCopy()
IIccArray * CIccArrayColorantInfo::NewCopy (CIccTagArray * pTagArray) const virtual
Reimplemented from CIccArrayUnknown.
{
  CIccArrayColorantInfo *rv = new CIccArrayColorantInfo(pTagArray);
  return rv;
}
References CIccArrayColorantInfo().
Validate()
icValidateStatus CIccArrayColorantInfo::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Reimplemented from CIccArrayUnknown.
{
  icValidateStatus rv = icValidateOK;
  if (m_pTag) {
    icUInt32Number i;
    for (i = 0; i < m_pTag->GetSize(); i++) {
      CIccTag *pTag = m_pTag->GetIndex(i);
      if (!pTag) {
        rv = icMaxStatus(rv, icValidateWarning);
        char buf[80];
        sprintf(buf, "Tag at index %d is NULL\n", i);
        sReport += buf;
      }
      else {
        if (pTag->GetTagStructType() != icSigColorantInfoStruct) {
          rv = icMaxStatus(rv, icValidateCriticalError);
          char buf[80];
          sprintf(buf, "Tag at index %d is not a colorantInfoStruct\n", i);
          sReport += buf;
        }
        rv = icMaxStatus(rv, pTag->Validate(sigPath + icGetSigPath(pTag->GetType()), sReport, pProfile));
      }
    }
  }
  else {
    sReport += "Array Handler not connected to CIccTagArray object!";
    rv = icValidateWarning;
  }
  return rv;
}
References CIccTagArray::GetIndex(), CIccTagArray::GetSize(), CIccTag::GetTagStructType(), CIccTag::GetType(), icGetSigPath(), icMaxStatus(), icSigColorantInfoStruct, icValidateCriticalError, icValidateOK, icValidateWarning, CIccArrayUnknown::m_pTag, and CIccTag::Validate().
Field Documentation
m_pTag
CIccTagArray* CIccArrayUnknown::m_pTag protected inherited
Referenced by CIccArrayColorantInfo(), CIccArrayNamedColor::CIccArrayNamedColor(), CIccArrayUnknown::CIccArrayUnknown(), CIccArrayNamedColor::Begin(), CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccArrayUnknown::Validate(), Validate(), and CIccArrayNamedColor::Validate().
m_pTagArray
CIccTagArray* IIccArray::m_pTagArray protected inherited
Referenced by IIccArray::GetTagArray().
m_sig
icArraySignature CIccArrayUnknown::m_sig protected inherited
Referenced by CIccArrayColorantInfo(), CIccArrayNamedColor::CIccArrayNamedColor(), and CIccArrayUnknown::CIccArrayUnknown().
The documentation for this class was generated from the following files:
IccProfLib/IccArrayBasic.h
IccProfLib/IccArrayBasic.cpp