iccDEV: CIccBasicMpeFactory Class Reference
CIccBasicMpeFactory Class Reference
#include <IccMpeFactory.h>
Public Member Functions
virtual CIccMultiProcessElement * CreateElement (icElemTypeSignature elementSig)
virtual bool GetElementSigName (std::string &elemName, icElemTypeSignature elemTypeSig)
Detailed Description
Class: CIccBasicMpeFactory
Purpose: CIccBasicMpeFactory provides creation of CIccProcessElement's defined by the ICC profile specification. The CIccMpeCreator always creates a CIccBasicElemFactory.
Member Function Documentation
CreateElement()
CIccMultiProcessElement * CIccBasicMpeFactory::CreateElement (icElemTypeSignature elementSig) virtual
Function: CreateElement(elemTypeSig) Create a element of type elemTypeSig.
Parameter(s): elemTypeSig = signature of the ICC element type for the element to be created
Returns a new CIccProcessElement object of the given signature type. Unrecognized elemTypeSig's will be created as a CIccProcessElementUnknown object.
Implements IIccMpeFactory.
{
  switch(elemTypeSig) {
    case icSigCurveSetElemType:
      return new CIccMpeCurveSet();
    case icSigMatrixElemType:
      return new CIccMpeMatrix();
    case icSigCLutElemType:
      return new CIccMpeCLUT();
    case icSigExtCLutElemType:
      return new CIccMpeExtCLUT();
    case icSigCalculatorElemType:
      return new CIccMpeCalculator();
    case icSigTintArrayElemType:
      return new CIccMpeTintArray();
    case icSigToneMapElemType:
      return new CIccMpeToneMap();
    case icSigJabToXYZElemType:
      return new CIccMpeJabToXYZ();
    case icSigXYZToJabElemType:
      return new CIccMpeXYZToJab();
    case icSigEmissionMatrixElemType:
      return new CIccMpeEmissionMatrix();
    case icSigInvEmissionMatrixElemType:
      return new CIccMpeInvEmissionMatrix();
    case icSigEmissionCLUTElemType:
      return new CIccMpeEmissionCLUT();
    case icSigReflectanceCLUTElemType:
      return new CIccMpeReflectanceCLUT();
    case icSigEmissionObserverElemType:
      return new CIccMpeEmissionObserver();
    case icSigReflectanceObserverElemType:
      return new CIccMpeReflectanceObserver();
    case icSigBAcsElemType:
      return new CIccMpeBAcs();
    case icSigEAcsElemType:
      return new CIccMpeEAcs();
    default:
      return new CIccMpeUnknown();
  }
}
References CIccMpeBAcs::CIccMpeBAcs(), CIccMpeCalculator::CIccMpeCalculator(), CIccMpeCLUT::CIccMpeCLUT(), CIccMpeCurveSet::CIccMpeCurveSet(), CIccMpeEAcs::CIccMpeEAcs(), CIccMpeEmissionCLUT::CIccMpeEmissionCLUT(), CIccMpeEmissionMatrix::CIccMpeEmissionMatrix(), CIccMpeEmissionObserver::CIccMpeEmissionObserver(), CIccMpeExtCLUT::CIccMpeExtCLUT(), CIccMpeInvEmissionMatrix::CIccMpeInvEmissionMatrix(), CIccMpeJabToXYZ::CIccMpeJabToXYZ(), CIccMpeMatrix::CIccMpeMatrix(), CIccMpeReflectanceCLUT::CIccMpeReflectanceCLUT(), CIccMpeReflectanceObserver::CIccMpeReflectanceObserver(), CIccMpeTintArray::CIccMpeTintArray(), CIccMpeToneMap::CIccMpeToneMap(), CIccMpeUnknown::CIccMpeUnknown(), CIccMpeXYZToJab::CIccMpeXYZToJab(), icSigBAcsElemType, icSigCalculatorElemType, icSigCLutElemType, icSigCurveSetElemType, icSigEAcsElemType, icSigEmissionCLUTElemType, icSigEmissionMatrixElemType, icSigEmissionObserverElemType, icSigExtCLutElemType, icSigInvEmissionMatrixElemType, icSigJabToXYZElemType, icSigMatrixElemType, icSigReflectanceCLUTElemType, icSigReflectanceObserverElemType, icSigTintArrayElemType, icSigToneMapElemType, and icSigXYZToJabElemType.
GetElementSigName()
bool CIccBasicMpeFactory::GetElementSigName (std::string & elemName, icElemTypeSignature elemTypeSig) virtual
Function: GetElementSigName(elemTypeSig) Get display name of elemTypeSig.
Parameter(s): elemName = string to put element name into, elemTypeSig = signature of the ICC element type to get a name for
Returns true if element type is recognized by the factory, false if the factory doesn't create elemTypeSig elements.
Implements IIccMpeFactory.
{
  switch(elemTypeSig) {
    case icSigCurveSetElemType:
      elemName = "Curve Set Element";
      break;
    case icSigMatrixElemType:
      elemName = "Matrix Element";
      break;
    case icSigCLutElemType:
      elemName = "CLUT Element";
      break;
    case icSigExtCLutElemType:
      elemName = "Extended CLUT Element";
      break;
    case icSigCalculatorElemType:
      elemName = "Calculator Element";
      break;
    case icSigTintArrayElemType:
      elemName = "Tint Array Element";
      break;
    case icSigToneMapElemType:
      elemName = "Tone Mapping Element";
      break;
    case icSigJabToXYZElemType:
      elemName = "JabToXYZ Element";
      break;
    case icSigXYZToJabElemType:
      elemName = "XYZToJab Element";
      break;
    case icSigEmissionMatrixElemType:
      elemName = "Observer Matrix Element";
      break;
    case icSigInvEmissionMatrixElemType:
      elemName = "Observer Inverse Matrix Element";
      break;
    case icSigEmissionCLUTElemType:
      elemName = "Emission CLUT Element";
      break;
    case icSigReflectanceCLUTElemType:
      elemName = "Reflectance CLUT Element";
      break;
    case icSigEmissionObserverElemType:
      elemName = "Emission Observer Element";
      break;
    case icSigReflectanceObserverElemType:
      elemName = "Reflectance Observer Element";
      break;
    case icSigBAcsElemType:
      elemName = "BACS Element";
      break;
    case icSigEAcsElemType:
      elemName = "EACS Element";
      break;
    default:
      char buf[30], str[100];
      sprintf(str, "Unknown Element Type (%s)", icGetSig(buf, elemTypeSig));
      elemName = str;
      return false;
  }
  return true;
}
References icGetSig(), icSigBAcsElemType, icSigCalculatorElemType, icSigCLutElemType, icSigCurveSetElemType, icSigEAcsElemType, icSigEmissionCLUTElemType, icSigEmissionMatrixElemType, icSigEmissionObserverElemType, icSigExtCLutElemType, icSigInvEmissionMatrixElemType, icSigJabToXYZElemType, icSigMatrixElemType, icSigReflectanceCLUTElemType, icSigReflectanceObserverElemType, icSigTintArrayElemType, icSigToneMapElemType, and icSigXYZToJabElemType.
The documentation for this class was generated from the following files:
IccProfLib/IccMpeFactory.h
IccProfLib/IccMpeFactory.cpp