iccDEV: CIccOpDefSubElement Class Reference
CIccOpDefSubElement Class Reference
Public Member Functions
virtual int ArgsPushed (CIccMpeCalculator *pCalc, SIccCalcOp &op)
virtual int ArgsUsed (CIccMpeCalculator *pCalc, SIccCalcOp &op)
virtual void Describe (SIccCalcOp &op, std::string &desc, int nVerboseness)
virtual bool Exec (SIccCalcOp *op, SIccOpState &os)
virtual bool IsValid (CIccMpeCalculator *pCalc, SIccCalcOp &op)
Detailed Description
Member Function Documentation
ArgsPushed()
virtual int IIccOpDef::ArgsPushed (CIccMpeCalculator * pCalc, SIccCalcOp & op) inline virtual inherited
{ return op.ArgsPushed(pCalc);}
References SIccCalcOp::ArgsPushed().
ArgsUsed()
virtual int IIccOpDef::ArgsUsed (CIccMpeCalculator * pCalc, SIccCalcOp & op) inline virtual inherited
{ return op.ArgsUsed(pCalc);}
References SIccCalcOp::ArgsUsed().
Describe()
virtual void IIccOpDef::Describe (SIccCalcOp & op, std::string & desc, int nVerboseness) inline virtual inherited
{op.Describe(desc, nVerboseness);}
References SIccCalcOp::Describe().
Exec()
virtual bool CIccOpDefSubElement::Exec (SIccCalcOp * op, SIccOpState & os) inline virtual
Reimplemented from IIccOpDef.
  {
    CIccSubCalcApply *pElemApply = os.pApply->GetApply(op->data.select.v1);
    if (!pElemApply)
      return false;
    icUInt16Number nSrc = pElemApply->NumInputChannels();
    icUInt16Number nDst = pElemApply->NumOutputChannels();
    size_t ss = os.pStack->size();
    if (nSrc>ss)
      return false;
    icFloatNumber *s = &(*os.pStack)[ss - nSrc];
    if (os.pScratch->size()<(size_t)nDst)
      os.pScratch->resize(nDst);
    icFloatNumber *d = &(*os.pScratch)[0];
    pElemApply->Apply(d, s);
    int ns = (int)ss + (int)nDst - (int)nSrc;
    if (ns != ss)
      os.pStack->resize(ns);
    s = &(*os.pStack)[ns - nDst];
    memcpy(s, d, nDst*sizeof(icFloatNumber));
    return true;
  }
References CIccSubCalcApply::Apply(), CIccApplyMpeCalculator::GetApply(), CIccSubCalcApply::NumInputChannels(), CIccSubCalcApply::NumOutputChannels(), SIccOpState::pApply, SIccOpState::pScratch, and SIccOpState::pStack.
IsValid()
virtual bool IIccOpDef::IsValid (CIccMpeCalculator * pCalc, SIccCalcOp & op) inline virtual inherited
Reimplemented in CIccOpDefInvalid.
{ return op.IsValidOp(pCalc); }
References SIccCalcOp::IsValidOp().
The documentation for this class was generated from the following file:
IccProfLib/IccMpeCalc.cpp