iccDEV: CIccXmlToneMapFunc Class Reference
CIccXmlToneMapFunc Class Reference
#include <IccMpeXml.h>
Public Member Functions
virtual ~CIccXmlToneMapFunc ()
icFloatNumber Apply (icFloatNumber lumValue, icFloatNumber pixelValue) const
bool Begin ()
void Describe (std::string &sDescription, int nVerboseness=0)
virtual const char * GetClassName () const
virtual icToneFunctionSignature GetType () const
virtual CIccToneMapFunc * NewCopy ()
virtual CIccToneMapFunc * NewCopy () const
virtual bool ParseXml (xmlNode *pNode, std::string &parseStr)
bool Read (icUInt32Number size, CIccIO *pIO)
bool SetFunction (icUInt16Number nFunc, icUInt8Number, icFloatNumber *pParams)
virtual bool ToXml (std::string &xml, std::string blanks="")
icValidateStatus Validate (std::string &sFuncReport, int nVerboseness=0) const
bool Write (CIccIO *pIO)
Protected Member Functions
int NumArgs () const
Protected Attributes
icUInt16Number m_nFunctionType
icUInt8Number m_nParameters
icUInt32Number m_nReserved
icUInt16Number m_nReserved2
icFloatNumber * m_params
Detailed Description
Constructor & Destructor Documentation
~CIccXmlToneMapFunc()
virtual CIccXmlToneMapFunc::~CIccXmlToneMapFunc () inline virtual
{}
Member Function Documentation
Apply()
icFloatNumber CIccToneMapFunc::Apply (icFloatNumber lumValue, icFloatNumber pixelValue) const inherited
{
  if (!m_nFunctionType && m_params) {
    return m_params[0] * lumValue * (pixelValue + m_params[1]) + m_params[2];
  }
  return 0;
}
References CIccToneMapFunc::m_nFunctionType, and CIccToneMapFunc::m_params.
Referenced by CIccMpeToneMap::Apply().
Begin()
bool CIccToneMapFunc::Begin () inherited
{
  if (m_nFunctionType != 0x0000)
    return false;
  if (m_nParameters < NumArgs() || !m_params)
    return false;
  return true;
}
References CIccToneMapFunc::m_nFunctionType, CIccToneMapFunc::m_nParameters, CIccToneMapFunc::m_params, and CIccToneMapFunc::NumArgs().
Referenced by CIccMpeToneMap::Begin().
Describe()
void CIccToneMapFunc::Describe (std::string & sDescription, int nVerboseness = 0) inherited
{
  icChar buf[128];
  sprintf(buf, "ToneFunctionType: %04Xh\n", m_nFunctionType);
  sDescription += buf;
  switch (m_nFunctionType) {
  case 0x0000:
    sprintf(buf, "Y = %.8f * M * ( X + %.8f) + %.8f\n\n", m_params[0], m_params[1], m_params[2]);
    sDescription += buf;
    return;
  default:
    int i;
    sprintf(buf, "Unknown Function with %d parameters:\n\n", m_nParameters);
    sDescription += buf;
    for (i = 0; i < m_nParameters; i++) {
      sprintf(buf, "Param[%d] = %.8lf\n\n", i, m_params[i]);
      sDescription += buf;
    }
  }
}
References CIccToneMapFunc::m_nFunctionType, CIccToneMapFunc::m_nParameters, and CIccToneMapFunc::m_params.
Referenced by CIccMpeToneMap::Describe().
GetClassName()
virtual const char * CIccXmlToneMapFunc::GetClassName () const inline virtual
Reimplemented from CIccToneMapFunc.
{ return "CIccXmlToneMapFunc"; }
GetType()
virtual icToneFunctionSignature CIccToneMapFunc::GetType () const inline virtual inherited
{ return icSigToneMapFunction; }
References icSigToneMapFunction.
Referenced by CIccToneMapFunc::Write().
NewCopy() [1/2]
CIccToneMapFunc * CIccXmlToneMapFunc::NewCopy () virtual
{
  CIccToneMapFunc* rv = new CIccXmlToneMapFunc();
  if (rv)
    *rv = *this;
  return rv;
}
References CIccToneMapFunc::operator=().
NewCopy() [2/2]
CIccToneMapFunc * CIccToneMapFunc::NewCopy () const virtual inherited
{
  CIccToneMapFunc* rv = new CIccToneMapFunc();
  if (rv)
    *rv = *this;
  return rv;
}
References CIccToneMapFunc::CIccToneMapFunc(), and CIccToneMapFunc::operator=().
Referenced by CIccMpeToneMap::CopyToneFuncs().
NumArgs()
int CIccToneMapFunc::NumArgs () const protected inherited
{
  if (m_nFunctionType == 0)
    return 3;
  return 0;
}
References CIccToneMapFunc::m_nFunctionType.
Referenced by CIccToneMapFunc::Begin(), CIccToneMapFunc::SetFunction(), and CIccToneMapFunc::Write().
ParseXml()
bool CIccXmlToneMapFunc::ParseXml (xmlNode * pNode, std::string & parseStr) virtual
{
  xmlAttr* funcType = icXmlFindAttr(pNode, "FunctionType");
  if (!funcType) {
    parseStr += "Bad FunctionType in Tone Map Function\n";
    return false;
  }
  m_nReserved2 = atoi(icXmlAttrValue(pNode, "Reserved2"));
  m_nFunctionType = atoi(icXmlAttrValue(funcType));
  switch (m_nFunctionType) {
  case 0x0000:
    m_nParameters = 3;
    break;
  default:
    parseStr += "Unsupported FunctionType value in Tone Map Function\n";
    return false;
  }
  CIccFloatArray args;
  if (!args.ParseArray(pNode->children))
    return false;
  if (args.GetSize() < m_nParameters)
    return false;
  if (m_params) {
    free(m_params);
  }
  if (m_nParameters) {
    m_params = (icFloatNumber*)malloc(m_nParameters * sizeof(icFloatNumber));
    if (!m_params)
      return false;
    memcpy(m_params, args.GetBuf(), m_nParameters * sizeof(icFloatNumber));
  }
  else
    m_params = NULL;
  return true;
}
References CIccXmlArrayType< T, Tsig >::GetBuf(), CIccXmlArrayType< T, Tsig >::GetSize(), icXmlAttrValue(), icXmlAttrValue(), icXmlFindAttr(), CIccToneMapFunc::m_nFunctionType, CIccToneMapFunc::m_nParameters, CIccToneMapFunc::m_nReserved2, CIccToneMapFunc::m_params, and CIccXmlArrayType< T, Tsig >::ParseArray().
Referenced by CIccMpeXmlToneMap::ParseXml().
Read()
bool CIccToneMapFunc::Read (icUInt32Number size, CIccIO * pIO) inherited
{
  icCurveSegSignature sig;
  icUInt32Number headerSize = sizeof(icTagTypeSignature) +
    sizeof(icUInt32Number) +
    sizeof(icUInt16Number) +
    sizeof(icUInt16Number);
  if (headerSize > size)
    return false;
  if (!pIO) {
    return false;
  }
  if (!pIO->Read32(&sig))
    return false;
  if (sig != icSigToneMapFunction)
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  if (!pIO->Read16(&m_nFunctionType))
    return false;
  if (!pIO->Read16(&m_nReserved2))
    return false;
  if (m_params) {
    free(m_params);
  }
  m_nParameters = (icUInt8Number)((size - headerSize)/sizeof(icFloatNumber));
  if (m_nParameters) {
    m_params = (icFloatNumber*)malloc(m_nParameters * sizeof(icFloatNumber));
    if (!m_params)
      return false;
    if (pIO->ReadFloat32Float(m_params, m_nParameters) != m_nParameters) {
      return false;
    }
  }
  else
    m_params = NULL;
  return true;
}
References icSigToneMapFunction, CIccToneMapFunc::m_nFunctionType, CIccToneMapFunc::m_nParameters, CIccToneMapFunc::m_nReserved, CIccToneMapFunc::m_nReserved2, CIccToneMapFunc::m_params, CIccIO::Read16(), CIccIO::Read32(), and CIccIO::ReadFloat32Float().
Referenced by CIccMpeToneMap::Read().
SetFunction()
bool CIccToneMapFunc::SetFunction (icUInt16Number nFunc, icUInt8Number nParams, icFloatNumber * pParams) inherited
{
  m_nFunctionType = nFunc;
  if (m_params)
    free(m_params);
  int nArgs = NumArgs();
  m_nParameters = (icUInt8Number)icIntMin(nParams, NumArgs());
  if (nArgs && pParams) {
    m_params = (icFloatNumber*)calloc(nArgs, sizeof(icFloatNumber));
    if (m_params)
      memcpy(m_params, pParams, icIntMin(nArgs, nParams) * sizeof(icFloatNumber));
  }
  return nParams == NumArgs();
}
References icIntMin(), CIccToneMapFunc::m_nFunctionType, CIccToneMapFunc::m_nParameters, CIccToneMapFunc::m_params, and CIccToneMapFunc::NumArgs().
ToXml()
bool CIccXmlToneMapFunc::ToXml (std::string & xml, std::string blanks = "") virtual
{
  char line[256];
  sprintf(line, "<ToneMapFunction FunctionType=\"%d\"", m_nFunctionType);
  xml += blanks + line;
  if (m_nReserved) {
    sprintf(line, " Reserved=\"%d\"", m_nReserved);
    xml += line;
  }
  if (m_nReserved2) {
    sprintf(line, " Reserved2=\"%d\"", m_nReserved2);
    xml += line;
  }
  xml += ">\n";
  CIccFloatArray::DumpArray(xml, blanks + "  ", m_params, m_nParameters, icConvertFloat, 8);
  xml += blanks + "</ToneMapFunction>\n";
  return true;
}
References CIccXmlArrayType< T, Tsig >::DumpArray(), icConvertFloat, CIccToneMapFunc::m_nFunctionType, CIccToneMapFunc::m_nParameters, CIccToneMapFunc::m_nReserved, CIccToneMapFunc::m_nReserved2, and CIccToneMapFunc::m_params.
Referenced by CIccMpeXmlToneMap::ToXml().
Validate()
icValidateStatus CIccToneMapFunc::Validate (std::string & sFuncReport, int nVerboseness = 0) const inherited
{
  CIccInfo Info;
  icValidateStatus rv = icValidateOK;
  if (m_nReserved || m_nReserved2) {
    sReport += icMsgValidateWarning;
    sReport += " formula curve has non zero reserved data.\n";
    rv = icMaxStatus(rv, icValidateWarning);
  }
  switch (m_nFunctionType) {
    case 0x0000:
      if (!m_params || m_nParameters < 3) {
        sReport += icMsgValidateCriticalError;
        sReport += " Tone mapping function has invalid parameters.\n";
        rv = icMaxStatus(rv, icValidateCriticalError);
      }
      else if (m_nParameters > 3) {
        sReport += icMsgValidateWarning;
        sReport += " tone mapping function has too many formulaCurveSegment parameters.\n";
        rv = icMaxStatus(rv, icValidateWarning);
      }
      break;
    default:
    {
      icChar buf[128];
      sReport += icMsgValidateCriticalError;
      sprintf(buf, " tone mapping function uses unknown function type %d\n", m_nFunctionType);
      sReport += buf;
      rv = icMaxStatus(rv, icValidateCriticalError);
    }
  }
  return rv;
}
References icMaxStatus(), icMsgValidateCriticalError, icMsgValidateWarning, icValidateCriticalError, icValidateOK, icValidateWarning, CIccToneMapFunc::m_nFunctionType, CIccToneMapFunc::m_nParameters, CIccToneMapFunc::m_nReserved, CIccToneMapFunc::m_nReserved2, and CIccToneMapFunc::m_params.
Referenced by CIccMpeToneMap::Validate().
Write()
bool CIccToneMapFunc::Write (CIccIO * pIO) inherited
{
  icToneFunctionSignature sig = GetType();
  if (!pIO)
    return false;
  if (!pIO->Write32(&sig))
    return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  if (!pIO->Write16(&m_nFunctionType))
    return false;
  if (!pIO->Write16(&m_nReserved2))
    return false;
  if (m_nParameters != NumArgs())
    return false;
  if (m_nParameters) {
    if (pIO->WriteFloat32Float(m_params, m_nParameters) != m_nParameters)
      return false;
  }
  return true;
}
References CIccToneMapFunc::GetType(), CIccToneMapFunc::m_nFunctionType, CIccToneMapFunc::m_nParameters, CIccToneMapFunc::m_nReserved, CIccToneMapFunc::m_nReserved2, CIccToneMapFunc::m_params, CIccToneMapFunc::NumArgs(), CIccIO::Write16(), CIccIO::Write32(), and CIccIO::WriteFloat32Float().
Referenced by CIccMpeToneMap::Write().
Field Documentation
m_nFunctionType
icUInt16Number CIccToneMapFunc::m_nFunctionType protected inherited
Referenced by CIccToneMapFunc::CIccToneMapFunc(), CIccToneMapFunc::Apply(), CIccToneMapFunc::Begin(), CIccToneMapFunc::Describe(), CIccToneMapFunc::NumArgs(), CIccToneMapFunc::operator=(), ParseXml(), CIccToneMapFunc::Read(), CIccToneMapFunc::SetFunction(), ToXml(), CIccToneMapFunc::Validate(), and CIccToneMapFunc::Write().
m_nParameters
icUInt8Number CIccToneMapFunc::m_nParameters protected inherited
Referenced by CIccToneMapFunc::CIccToneMapFunc(), CIccToneMapFunc::Begin(), CIccToneMapFunc::Describe(), CIccToneMapFunc::operator=(), ParseXml(), CIccToneMapFunc::Read(), CIccToneMapFunc::SetFunction(), ToXml(), CIccToneMapFunc::Validate(), and CIccToneMapFunc::Write().
m_nReserved
icUInt32Number CIccToneMapFunc::m_nReserved protected inherited
Referenced by CIccToneMapFunc::CIccToneMapFunc(), CIccToneMapFunc::operator=(), CIccToneMapFunc::Read(), ToXml(), CIccToneMapFunc::Validate(), and CIccToneMapFunc::Write().
m_nReserved2
icUInt16Number CIccToneMapFunc::m_nReserved2 protected inherited
Referenced by CIccToneMapFunc::CIccToneMapFunc(), CIccToneMapFunc::operator=(), ParseXml(), CIccToneMapFunc::Read(), ToXml(), CIccToneMapFunc::Validate(), and CIccToneMapFunc::Write().
m_params
icFloatNumber* CIccToneMapFunc::m_params protected inherited
Referenced by CIccToneMapFunc::CIccToneMapFunc(), CIccToneMapFunc::~CIccToneMapFunc(), CIccToneMapFunc::Apply(), CIccToneMapFunc::Begin(), CIccToneMapFunc::Describe(), CIccToneMapFunc::operator=(), ParseXml(), CIccToneMapFunc::Read(), CIccToneMapFunc::SetFunction(), ToXml(), CIccToneMapFunc::Validate(), and CIccToneMapFunc::Write().
The documentation for this class was generated from the following files:
IccXML/IccLibXML/IccMpeXml.h
IccXML/IccLibXML/IccMpeXml.cpp