iccDEV: CIccArrayNamedColor Class Reference
CIccArrayNamedColor Class Reference
#include <IccArrayBasic.h>
Public Member Functions
CIccArrayNamedColor (CIccTagArray *pTagArray=NULL)
virtual ~CIccArrayNamedColor ()
bool Begin ()
virtual void Describe (std::string &sDescription, int nVerboseness) const
CIccStructNamedColor * FindColor (const icChar *szColor) const
CIccStructNamedColor * FindDeviceColor (const icFloatNumber *pDevColor) const
CIccStructNamedColor * FindPcsColor (const icFloatNumber *pPCS, icFloatNumber dMinDE=1000.0) const
CIccStructNamedColor * FindSpectralColor (const icFloatNumber *pSpec, icFloatNumber dMinRms=1000.0) const
virtual const icChar * GetClassName () const
icUInt32Number GetDeviceSamples ()
bool GetDeviceTint (icFloatNumber *dstColor, const CIccStructNamedColor *pColor, icFloatNumber tint=1.0f, icNamedColorlMemberSignature sig=icSigNmclDeviceDataMbr) const
icUInt32Number GetPcsSamples ()
bool GetPcsTint (icFloatNumber *dstColor, const CIccStructNamedColor *pColor, icFloatNumber tint=1.0f, icNamedColorlMemberSignature sig=icSigNmclPcsDataMbr) const
icUInt32Number GetSpectralSamples ()
bool GetSpectralTint (icFloatNumber *dstColor, const CIccStructNamedColor *pColor, icFloatNumber tint=1.0f, icNamedColorlMemberSignature sig=icSigNmclSpectralDataMbr) const
CIccTagArray * GetTagArray ()
virtual IIccArray * NewCopy (CIccTagArray *pTagArray) const
void SetColorSpaces (icColorSpaceSignature csPcs, icColorSpaceSignature csDevice, icSpectralColorSignature csSpectralPCS=icSigNoSpectralData, const icSpectralRange *pSpectralRange=NULL, const icSpectralRange *pBiSPectralRange=NULL)
icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
Protected Member Functions
bool GetTint (icFloatNumber *dstColor, CIccTagNumArray *pZero, CIccTagNumArray *pData, CIccTagNumArray *pTint, icFloatNumber tint, icUInt32Number nSamples)
Protected Attributes
icSpectralRange m_biSpectralRange
icColorSpaceSignature m_csDevice
icColorSpaceSignature m_csPcs
icSpectralColorSignature m_csSpectralPcs
icNamedColorStructList * m_list
icUInt32Number m_nDeviceSamples
icUInt32Number m_nPcsSamples
icUInt32Number m_nSpectralSamples
CIccTagArray * m_pTag
CIccTagArray * m_pTagArray
CIccStructNamedColor * m_pZeroTint
icArraySignature m_sig
icSpectralRange m_spectralRange
Detailed Description
Class: CIccArrayNamedColor
Purpose: The Named Color array handler
Constructor & Destructor Documentation
CIccArrayNamedColor()
CIccArrayNamedColor::CIccArrayNamedColor (CIccTagArray * pTagArray = NULL)
{
  m_pTag = pTagArray;
  m_sig = icSigNamedColorArray;
  m_list = new icNamedColorStructList;
  m_nDeviceSamples = 0;
  m_nPcsSamples = 0;
  m_nSpectralSamples = 0;
  m_spectralRange = m_biSpectralRange = {};
  m_csDevice = icSigUnknownData;
  m_pZeroTint = NULL;
  m_csSpectralPcs = icSigNoSpectralData;
}
References icSigNamedColorArray, icSigNoSpectralData, m_biSpectralRange, m_csDevice, m_csSpectralPcs, m_list, m_nDeviceSamples, m_nPcsSamples, m_nSpectralSamples, CIccArrayUnknown::m_pTag, m_pZeroTint, CIccArrayUnknown::m_sig, and m_spectralRange.
Referenced by CIccBasicArrayFactory::CreateArray(), and NewCopy().
~CIccArrayNamedColor()
CIccArrayNamedColor::~CIccArrayNamedColor () virtual
{
  delete m_list;
}
References m_list.
Member Function Documentation
Begin()
bool CIccArrayNamedColor::Begin ()
{
  m_pZeroTint = (CIccStructNamedColor*)icGetTagStructHandlerOfType(m_pTag->GetIndex(0), icSigTintZeroStruct);
  m_list->clear();
  int i, n=m_pTag->GetSize();
  for (i=1; i<n; i++) {
    CIccStructNamedColor *pNamedColor = (CIccStructNamedColor*)icGetTagStructHandlerOfType(m_pTag->GetIndex(i), icSigNamedColorStruct);
    if (pNamedColor) {
      std::string name = pNamedColor->getName();
      if (!name.empty())
        (*m_list)[name] = pNamedColor;
    }
  }
  return true;
}
References CIccTagArray::GetIndex(), CIccStructNamedColor::getName(), CIccTagArray::GetSize(), icGetTagStructHandlerOfType(), icSigNamedColorStruct, icSigTintZeroStruct, m_list, CIccArrayUnknown::m_pTag, and m_pZeroTint.
Describe()
void CIccArrayNamedColor::Describe (std::string & sDescription, int nVerboseness) const virtual
Reimplemented from CIccArrayUnknown.
{
    sDescription += "\nCIccArrayNamedColor::Describe()\n";
}
FindColor()
CIccStructNamedColor * CIccArrayNamedColor::FindColor (const icChar * szColor) const
{
  std::string name(szColor);
  icNamedColorStructList::const_iterator i;
  i=m_list->find(name);
  if (i!=m_list->end())
    return i->second;
  return NULL;
}
References m_list.
FindDeviceColor()
CIccStructNamedColor * CIccArrayNamedColor::FindDeviceColor (const icFloatNumber * pDevColor) const
{
  icFloatNumber *temp = new icFloatNumber[m_nDeviceSamples];
  if (!temp)
    return NULL;
  icUInt32Number i, j, n=m_pTag->GetSize();
  for (i=1; i<n; i++) {
    CIccStructNamedColor *pNamedColor = (CIccStructNamedColor*)icGetTagStructHandlerOfType(m_pTag->GetIndex(i), icSigNamedColorStruct);
    if (pNamedColor) {
      CIccTag *pTag = pNamedColor->GetElem(icSigNmclDeviceDataMbr);
      if (pTag && pTag->IsNumArrayType()) {
        CIccTagNumArray *v = (CIccTagNumArray*)pTag;
        icUInt32Number n = v->GetNumValues()/m_nDeviceSamples;
        if (n) {
          v->GetValues(temp, (n-1)*m_nDeviceSamples, m_nDeviceSamples);
          for (j=0; j<m_nDeviceSamples; j++) {
            if (temp[j]!=pDevColor[j])
              break;
          }
          if (n==m_nDeviceSamples) {
            delete [] temp;
            return pNamedColor;
          }
        }
      }
    }
  }
  delete[] temp;
  return NULL;
}
References CIccStructUnknown::GetElem(), CIccTagArray::GetIndex(), CIccTagNumArray::GetNumValues(), CIccTagArray::GetSize(), CIccTagNumArray::GetValues(), icGetTagStructHandlerOfType(), icSigNamedColorStruct, icSigNmclDeviceDataMbr, CIccTag::IsNumArrayType(), m_nDeviceSamples, and CIccArrayUnknown::m_pTag.
FindPcsColor()
CIccStructNamedColor * CIccArrayNamedColor::FindPcsColor (const icFloatNumber * pPCS, icFloatNumber dMinDE = 1000.0) const
{
  icFloatNumber dCalcDE, dLeastDE=dMinDE;
  icFloatNumber pLabIn[3], pLab[3];
  CIccStructNamedColor* leastDEindex = NULL;
  if (m_csPcs != icSigLabData) {
    icXYZtoLab(pLabIn,pPCS);
  }
  else {
    memcpy(pLabIn, pPCS, 3*sizeof(icFloatNumber));
  }
  icUInt32Number i, n=m_pTag->GetSize();
  for (i=1; i<n; i++) {
    CIccStructNamedColor *pNamedColor = (CIccStructNamedColor*)icGetTagStructHandlerOfType(m_pTag->GetIndex(i), icSigNamedColorStruct);
    if (pNamedColor) {
      CIccTag *pTag = pNamedColor->GetElem(icSigNmclDeviceDataMbr);
      if (pTag && pTag->IsNumArrayType()) {
        CIccTagNumArray *v = (CIccTagNumArray*)pTag;
        icUInt32Number n = v->GetNumValues()/m_nDeviceSamples;
        if (n) {
          v->GetValues(pLab, (n-1)*m_nDeviceSamples, 3);
          dCalcDE = icDeltaE(pLabIn, pLab);
          if (dCalcDE<dMinDE && dCalcDE<dLeastDE) {
            dLeastDE = dCalcDE;
            leastDEindex = pNamedColor;
          }
        }
      }
    }
  }
  return leastDEindex;
}
References CIccStructUnknown::GetElem(), CIccTagArray::GetIndex(), CIccTagNumArray::GetNumValues(), CIccTagArray::GetSize(), CIccTagNumArray::GetValues(), icDeltaE(), icGetTagStructHandlerOfType(), icSigLabData, icSigNamedColorStruct, icSigNmclDeviceDataMbr, icXYZtoLab(), CIccTag::IsNumArrayType(), m_csPcs, m_nDeviceSamples, and CIccArrayUnknown::m_pTag.
FindSpectralColor()
CIccStructNamedColor * CIccArrayNamedColor::FindSpectralColor (const icFloatNumber * pSpec, icFloatNumber dMinRms = 1000.0) const
{
  icFloatNumber dCalcRMS, dLeastRMS=dMinRMS;
  CIccStructNamedColor* leastRMSindex = NULL;
  icFloatNumber *temp = new icFloatNumber[m_nSpectralSamples];
  if (!temp)
    return NULL;
  icUInt32Number i, n=m_pTag->GetSize();
  for (i=1; i<n; i++) {
    CIccStructNamedColor *pNamedColor = (CIccStructNamedColor*)icGetTagStructHandlerOfType(m_pTag->GetIndex(i), icSigNamedColorStruct);
    if (pNamedColor) {
      CIccTag *pTag = pNamedColor->GetElem(icSigNmclDeviceDataMbr);
      if (pTag && pTag->IsNumArrayType()) {
        CIccTagNumArray *v = (CIccTagNumArray*)pTag;
        icUInt32Number n = v->GetNumValues()/m_nDeviceSamples;
        if (n) {
          v->GetValues(temp, (n-1)*m_nSpectralSamples, m_nSpectralSamples);
          dCalcRMS = icRmsDif(pSpec, temp, m_nSpectralSamples);
          if (dCalcRMS<dMinRMS && dCalcRMS<dLeastRMS) {
            dLeastRMS = dCalcRMS;
            leastRMSindex = pNamedColor;
          }
        }
      }
    }
  }
  delete[] temp;
  return leastRMSindex;
}
References CIccStructUnknown::GetElem(), CIccTagArray::GetIndex(), CIccTagNumArray::GetNumValues(), CIccTagArray::GetSize(), CIccTagNumArray::GetValues(), icGetTagStructHandlerOfType(), icRmsDif(), icSigNamedColorStruct, icSigNmclDeviceDataMbr, CIccTag::IsNumArrayType(), m_nDeviceSamples, m_nSpectralSamples, and CIccArrayUnknown::m_pTag.
GetClassName()
virtual const icChar * CIccArrayNamedColor::GetClassName () const inline virtual
Reimplemented from CIccArrayUnknown.
{ return "CIccArrayNamedColor"; }
GetDeviceSamples()
icUInt32Number CIccArrayNamedColor::GetDeviceSamples () inline
{ return m_nDeviceSamples; }
References m_nDeviceSamples.
GetDeviceTint()
bool CIccArrayNamedColor::GetDeviceTint (icFloatNumber * dstColor, const CIccStructNamedColor * pColor, icFloatNumber tint = 1.0f, icNamedColorlMemberSignature sig = icSigNmclDeviceDataMbr) const
{
  CIccTagNumArray *pZero;
  if (m_pZeroTint)
    pZero = m_pZeroTint->GetNumArray(sig);
  else
    pZero = NULL;
  if (!pColor)
    return false;
  return pColor->GetTint(dstColor, tint, pZero, sig, m_nDeviceSamples);
}
References CIccStructNamedColor::GetNumArray(), CIccStructNamedColor::GetTint(), m_nDeviceSamples, and m_pZeroTint.
GetPcsSamples()
icUInt32Number CIccArrayNamedColor::GetPcsSamples () inline
{ return m_nPcsSamples; }
References m_nPcsSamples.
GetPcsTint()
bool CIccArrayNamedColor::GetPcsTint (icFloatNumber * dstColor, const CIccStructNamedColor * pColor, icFloatNumber tint = 1.0f, icNamedColorlMemberSignature sig = icSigNmclPcsDataMbr) const
{
  CIccTagNumArray *pZero;
  if (m_pZeroTint)
    pZero = m_pZeroTint->GetNumArray(sig);
  else
    pZero = NULL;
  if (!pColor)
    return false;
  return pColor->GetTint(dstColor, tint, pZero, sig, m_nPcsSamples);
}
References CIccStructNamedColor::GetNumArray(), CIccStructNamedColor::GetTint(), m_nPcsSamples, and m_pZeroTint.
GetSpectralSamples()
icUInt32Number CIccArrayNamedColor::GetSpectralSamples () inline
{ return m_nSpectralSamples; }
References m_nSpectralSamples.
GetSpectralTint()
bool CIccArrayNamedColor::GetSpectralTint (icFloatNumber * dstColor, const CIccStructNamedColor * pColor, icFloatNumber tint = 1.0f, icNamedColorlMemberSignature sig = icSigNmclSpectralDataMbr) const
{
  CIccTagNumArray *pZero;
  if (m_pZeroTint)
    pZero = m_pZeroTint->GetNumArray(sig);
  else
    pZero = NULL;
  if (!pColor)
    return false;
  return pColor->GetTint(dstColor, tint, pZero, sig, m_nSpectralSamples);
}
References CIccStructNamedColor::GetNumArray(), CIccStructNamedColor::GetTint(), m_nSpectralSamples, and m_pZeroTint.
GetTagArray()
CIccTagArray * IIccArray::GetTagArray () inline inherited
{ return m_pTagArray; }
References IIccArray::m_pTagArray.
GetTint()
bool CIccArrayNamedColor::GetTint (icFloatNumber * dstColor, CIccTagNumArray * pZero, CIccTagNumArray * pData, CIccTagNumArray * pTint, icFloatNumber tint, icUInt32Number nSamples) protected
NewCopy()
IIccArray * CIccArrayNamedColor::NewCopy (CIccTagArray * pTagArray) const virtual
Reimplemented from CIccArrayUnknown.
{
  CIccArrayNamedColor *rv = new CIccArrayNamedColor(pTagArray);
  if (rv) {
    rv->m_csPcs = m_csPcs;
    rv->m_csDevice = m_csDevice;
    rv->m_csSpectralPcs = m_csSpectralPcs;
    rv->m_spectralRange = m_spectralRange;
    rv->m_biSpectralRange = m_biSpectralRange;
  }
  return rv;
}
References CIccArrayNamedColor(), m_biSpectralRange, m_csDevice, m_csPcs, m_csSpectralPcs, and m_spectralRange.
SetColorSpaces()
void CIccArrayNamedColor::SetColorSpaces (icColorSpaceSignature csPcs, icColorSpaceSignature csDevice, icSpectralColorSignature csSpectralPCS = icSigNoSpectralData, const icSpectralRange * pSpectralRange = NULL, const icSpectralRange * pBiSPectralRange = NULL)
{
  m_csPcs = csPcs;
  m_csDevice = csDevice;
  m_csSpectralPcs = csSpectralPcs;
  if (pSpectralRange)
    m_spectralRange = *pSpectralRange;
  else
    memset(&m_spectralRange, 0, sizeof(m_spectralRange));
  if (pBiSpectralRange)
    m_biSpectralRange = *pBiSpectralRange;
  else
    memset(&m_biSpectralRange, 0, sizeof(m_biSpectralRange));
  m_nDeviceSamples = icGetSpaceSamples(m_csDevice);
  m_nPcsSamples = icGetSpaceSamples(m_csPcs);
  m_nSpectralSamples = icGetSpaceSamples((icColorSpaceSignature)m_csSpectralPcs);
}
References icGetSpaceSamples(), m_biSpectralRange, m_csDevice, m_csPcs, m_csSpectralPcs, m_nDeviceSamples, m_nPcsSamples, m_nSpectralSamples, and m_spectralRange.
Referenced by CIccProfileXml::ParseTag().
Validate()
icValidateStatus CIccArrayNamedColor::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Reimplemented from CIccArrayUnknown.
{
  icValidateStatus rv = icValidateOK;
  if (m_pTag) {
    icUInt32Number i, n = m_pTag->GetSize();
    CIccTag *pSubTag;
    int nBad = 0;
    if (n<1) {
      sReport += "Named Color array must have at least 1 entry\n";
      rv = icMaxStatus(rv, icValidateCriticalError);
    }
    for (i=0; i<n; i++) {
      pSubTag = m_pTag->GetIndex(i);
      if (pSubTag) {
        icStructSignature sig = pSubTag->GetTagStructType();
        if (!((i && sig==icSigNamedColorStruct) || (!i && sig==icSigTintZeroStruct))) {
          nBad++;
        }
        else {
         CIccTagStruct *pTag = (CIccTagStruct*)pSubTag;
         CIccStructNamedColor *pColor = (CIccStructNamedColor*)pTag->GetStructHandler();
         if (pColor) {
           CIccTagNumArray *pArray, *pTint;
           char str[256];
           pTint = pColor->GetNumArray(icSigNmclTintMbr);
           pArray = pColor->GetNumArray(icSigNmclDeviceDataMbr);
           if (pArray && m_nDeviceSamples) {
             icUInt32Number n = pArray->GetNumValues()/m_nDeviceSamples;
             if (n<1) {
               sprintf(str, "Insufficient device samples in NamedColor[%d]\n", i);
               sReport += str;
               rv = icMaxStatus(rv, icValidateCriticalError);
             }
             else if (pArray->GetNumValues() != n*m_nDeviceSamples) {
               sprintf(str, "Number of Device samples isn't an even multiple of Device samples in NamedColor[%d]!\n", i);
               sReport += str;
               rv = icMaxStatus(rv, icValidateCriticalError);
             }
             if (pTint && pTint->GetNumValues()!=n) {
               sprintf(str, "Number of device samples doesn't match tint values in NamedColor[%d]\n", i);
               sReport += str;
               rv = icMaxStatus(rv, icValidateCriticalError);
             }
           }
           pArray = pColor->GetNumArray(icSigNmclPcsDataMbr);
           if (pArray && m_nPcsSamples) {
             icUInt32Number n = pArray->GetNumValues()/m_nPcsSamples;
             if (n<1) {
               sprintf(str, "Insufficient PCS samples in NamedColor[%d]\n", i);
               sReport += str;
               rv = icMaxStatus(rv, icValidateCriticalError);
             }
             else if (pArray->GetNumValues() != n*m_nPcsSamples) {
               sprintf(str, "Number of PCS samples isn't an even multiple of PCS samples in NamedColor[%d]!\n", i);
               sReport += str;
               rv = icMaxStatus(rv, icValidateCriticalError);
             }
             if (pTint && pTint->GetNumValues()!=n) {
               sprintf(str, "Number of PCS samples doesn't match tint values in NamedColor[%d]\n", i);
               sReport += str;
               rv = icMaxStatus(rv, icValidateCriticalError);
             }
           }
           pArray = pColor->GetNumArray(icSigNmclSpectralDataMbr);
           if (pArray) {
             if (pArray->IsMatrixArray()) {
               CIccTagSparseMatrixArray *pArrayTag = (CIccTagSparseMatrixArray *) pArray;
               if (pArrayTag->GetChannelsPerMatrix()!= m_nSpectralSamples) {
                 sprintf(str, "Incompatible SpectralPcs samples in NamedColor[%d]\n", i);
                 sReport += str;
                 rv = icMaxStatus(rv, icValidateCriticalError);
               }
             }
             else if (m_nSpectralSamples) {
               icUInt32Number n = pArray->GetNumValues()/m_nSpectralSamples;
               if (n<1) {
                 sprintf(str, "Insufficient SpectralPcs samples in NamedColor[%d]\n", i);
                 sReport += str;
                 rv = icMaxStatus(rv, icValidateCriticalError);
               }
               else if (pArray->GetNumValues() != n*m_nSpectralSamples) {
                 sprintf(str, "Number of spectral samples isn't an even multiple of spectral PCS samples in Namedcolor[%d]!\n", i);
                 sReport += str;
                 rv = icMaxStatus(rv, icValidateCriticalError);
               }
               if (pTint && pTint->GetNumValues()!=n) {
                 sprintf(str, "Number of SpectralPCS samples doesn't match tint values in NamedColor[%d]\n", i);
                 sReport += str;
                 rv = icMaxStatus(rv, icValidateCriticalError);
               }
             }
           }
         }
        }
        rv = icMaxStatus(rv, pSubTag->Validate(sigPath, sReport, pProfile));
      }
      else {
        nBad++;
      }
    }
    if (nBad) {
      sReport += "Named Color array has invalid tag struct entries!\n";
      rv = icMaxStatus(rv, icValidateCriticalError);
    }
  }
  return rv;
}
References CIccTagSparseMatrixArray::GetChannelsPerMatrix(), CIccTagArray::GetIndex(), CIccStructNamedColor::GetNumArray(), CIccTagNumArray::GetNumValues(), CIccTagArray::GetSize(), CIccTagStruct::GetStructHandler(), CIccTag::GetTagStructType(), icMaxStatus(), icSigNamedColorStruct, icSigNmclDeviceDataMbr, icSigNmclPcsDataMbr, icSigNmclSpectralDataMbr, icSigNmclTintMbr, icSigTintZeroStruct, icValidateCriticalError, icValidateOK, CIccTagNumArray::IsMatrixArray(), m_nDeviceSamples, m_nPcsSamples, m_nSpectralSamples, CIccArrayUnknown::m_pTag, and CIccTag::Validate().
Field Documentation
m_biSpectralRange
icSpectralRange CIccArrayNamedColor::m_biSpectralRange protected
Referenced by CIccArrayNamedColor(), NewCopy(), and SetColorSpaces().
m_csDevice
icColorSpaceSignature CIccArrayNamedColor::m_csDevice protected
Referenced by CIccArrayNamedColor(), NewCopy(), and SetColorSpaces().
m_csPcs
icColorSpaceSignature CIccArrayNamedColor::m_csPcs protected
Referenced by FindPcsColor(), NewCopy(), and SetColorSpaces().
m_csSpectralPcs
icSpectralColorSignature CIccArrayNamedColor::m_csSpectralPcs protected
Referenced by CIccArrayNamedColor(), NewCopy(), and SetColorSpaces().
m_list
icNamedColorStructList* CIccArrayNamedColor::m_list protected
Referenced by CIccArrayNamedColor(), ~CIccArrayNamedColor(), Begin(), and FindColor().
m_nDeviceSamples
icUInt32Number CIccArrayNamedColor::m_nDeviceSamples protected
Referenced by CIccArrayNamedColor(), FindDeviceColor(), FindPcsColor(), FindSpectralColor(), GetDeviceSamples(), GetDeviceTint(), SetColorSpaces(), and Validate().
m_nPcsSamples
icUInt32Number CIccArrayNamedColor::m_nPcsSamples protected
Referenced by CIccArrayNamedColor(), GetPcsSamples(), GetPcsTint(), SetColorSpaces(), and Validate().
m_nSpectralSamples
icUInt32Number CIccArrayNamedColor::m_nSpectralSamples protected
Referenced by CIccArrayNamedColor(), FindSpectralColor(), GetSpectralSamples(), GetSpectralTint(), SetColorSpaces(), and Validate().
m_pTag
CIccTagArray* CIccArrayUnknown::m_pTag protected inherited
Referenced by CIccArrayColorantInfo::CIccArrayColorantInfo(), CIccArrayNamedColor(), CIccArrayUnknown::CIccArrayUnknown(), Begin(), FindDeviceColor(), FindPcsColor(), FindSpectralColor(), CIccArrayUnknown::Validate(), CIccArrayColorantInfo::Validate(), and Validate().
m_pTagArray
CIccTagArray* IIccArray::m_pTagArray protected inherited
Referenced by IIccArray::GetTagArray().
m_pZeroTint
CIccStructNamedColor* CIccArrayNamedColor::m_pZeroTint protected
Referenced by CIccArrayNamedColor(), Begin(), GetDeviceTint(), GetPcsTint(), and GetSpectralTint().
m_sig
icArraySignature CIccArrayUnknown::m_sig protected inherited
Referenced by CIccArrayColorantInfo::CIccArrayColorantInfo(), CIccArrayNamedColor(), and CIccArrayUnknown::CIccArrayUnknown().
m_spectralRange
icSpectralRange CIccArrayNamedColor::m_spectralRange protected
Referenced by CIccArrayNamedColor(), NewCopy(), and SetColorSpaces().
The documentation for this class was generated from the following files:
IccProfLib/IccArrayBasic.h
IccProfLib/IccArrayBasic.cpp