iccDEV: CTiffImg Class Reference
CTiffImg Class Reference
#include <TiffImg.h>
Public Member Functions
CTiffImg ()
virtual ~CTiffImg ()
void Close ()
bool Create (const char *szFname, unsigned int nWidth, unsigned int nHeight, unsigned int nBPS, unsigned int nPhoto, unsigned int nSamples, float fXRes, float fYRes, bool bCompress=true, bool bSep=false)
unsigned int GetBitsPerSample ()
unsigned int GetBytesPerLine ()
unsigned int GetCompress ()
unsigned int GetExtraSamples ()
unsigned int GetHeight ()
double GetHeightIn ()
bool GetIccProfile (unsigned char *&pProfile, unsigned int &nLen)
unsigned int GetPhoto ()
unsigned int GetPlanar ()
unsigned int GetSamples ()
unsigned int GetWidth ()
double GetWidthIn ()
float GetXRes ()
float GetYRes ()
bool Open (const char *szFname)
bool ReadLine (unsigned char *pBuf)
bool SetIccProfile (unsigned char *pProfile, unsigned int nLen)
bool WriteLine (unsigned char *pBuf)
Protected Attributes
bool m_bRead
float m_fXRes
float m_fYRes
TIFF * m_hTif
icUInt16Number m_nBitsPerSample
unsigned int m_nBytesPerLine
icUInt16Number m_nBytesPerSample
unsigned int m_nBytesPerStripLine
icUInt16Number m_nCompress
unsigned int m_nCurLine
unsigned int m_nCurStrip
icUInt16Number m_nExtraSamples
unsigned int m_nHeight
icUInt16Number m_nPhoto
icUInt16Number m_nPlanar
unsigned int m_nProfileLength
unsigned int m_nRowsPerStrip
icUInt16Number m_nSamples
unsigned int m_nStripSamples
unsigned int m_nStripSize
unsigned int m_nStripsPerSample
unsigned int m_nWidth
unsigned char * m_pProfile
unsigned char * m_pStripBuf
Detailed Description
Constructor & Destructor Documentation
CTiffImg()
CTiffImg::CTiffImg ()
{
  m_nWidth = 0;
  m_nHeight = 0;
  m_nBitsPerSample = 0;
  m_nSamples = 0;
  m_nExtraSamples = 0;
  m_hTif = NULL;
  m_pStripBuf = NULL;
}
References m_hTif, m_nBitsPerSample, m_nExtraSamples, m_nHeight, m_nSamples, m_nWidth, and m_pStripBuf.
~CTiffImg()
CTiffImg::~CTiffImg () virtual
{
  Close();
}
References Close().
Member Function Documentation
Close()
void CTiffImg::Close ()
{
  m_nWidth = 0;
  m_nHeight = 0;
  m_nBitsPerSample = 0;
  m_nSamples = 0;
  m_nExtraSamples = 0;
  if (m_hTif) {
    TIFFClose(m_hTif);
    m_hTif = NULL;
  }
  if (m_pStripBuf) {
    free(m_pStripBuf);
    m_pStripBuf = NULL;
  }
}
References m_hTif, m_nBitsPerSample, m_nExtraSamples, m_nHeight, m_nSamples, m_nWidth, and m_pStripBuf.
Referenced by ~CTiffImg(), Create(), main(), main(), main(), and Open().
Create()
bool CTiffImg::Create (const char * szFname, unsigned int nWidth, unsigned int nHeight, unsigned int nBPS, unsigned int nPhoto, unsigned int nSamples, float fXRes, float fYRes, bool bCompress = true, bool bSep = false)
{
  Close();
  m_bRead = false;
  m_nWidth = nWidth;
  m_nHeight = nHeight;
  m_nBitsPerSample = (icUInt16Number)nBPS;
  m_nSamples = (icUInt16Number)nSamples;
  m_nRowsPerStrip = 1;
  m_fXRes = fXRes;
  m_fYRes = fYRes;
  m_nPlanar = bSep ? PLANARCONFIG_SEPARATE : PLANARCONFIG_CONTIG;
  m_nCompress = bCompress ? COMPRESSION_LZW : COMPRESSION_NONE;
  switch(nPhoto) {
  case PHOTO_MINISBLACK:
    if (m_nSamples==3)
      m_nPhoto = PHOTOMETRIC_RGB;
    else
      m_nPhoto = PHOTOMETRIC_MINISBLACK;
    break;
  case PHOTO_MINISWHITE:
    if (m_nSamples==4)
      m_nPhoto = PHOTOMETRIC_SEPARATED;
    else
      m_nPhoto = PHOTOMETRIC_MINISWHITE;
    break;
  case PHOTO_CIELAB:
    m_nPhoto = PHOTOMETRIC_CIELAB;
    break;
  case PHOTO_ICCLAB:
    m_nPhoto = PHOTOMETRIC_ICCLAB;
    break;
  }
  m_hTif = TIFFOpen(szFname, "w");
  if (!m_hTif) {
    TIFFError(szFname,"Can not open output image");
    return false;
  }
  TIFFSetField(m_hTif, TIFFTAG_IMAGEWIDTH, (uint32) m_nWidth);
  TIFFSetField(m_hTif, TIFFTAG_IMAGELENGTH, (uint32) m_nHeight);
  TIFFSetField(m_hTif, TIFFTAG_PHOTOMETRIC, m_nPhoto);
  TIFFSetField(m_hTif, TIFFTAG_PLANARCONFIG, m_nPlanar);
  TIFFSetField(m_hTif, TIFFTAG_SAMPLESPERPIXEL, m_nSamples);
  TIFFSetField(m_hTif, TIFFTAG_BITSPERSAMPLE, m_nBitsPerSample);
  if (m_nBitsPerSample==32)
    TIFFSetField(m_hTif, TIFFTAG_SAMPLEFORMAT, SAMPLEFORMAT_IEEEFP);
  TIFFSetField(m_hTif, TIFFTAG_ROWSPERSTRIP, m_nRowsPerStrip);
  TIFFSetField(m_hTif, TIFFTAG_COMPRESSION, m_nCompress);
  TIFFSetField(m_hTif, TIFFTAG_ORIENTATION, ORIENTATION_TOPLEFT);
  TIFFSetField(m_hTif, TIFFTAG_XRESOLUTION, fXRes);
  TIFFSetField(m_hTif, TIFFTAG_YRESOLUTION, fYRes);
  if (bCompress) {
    if (m_nBitsPerSample==32) {
      TIFFSetField(m_hTif, TIFFTAG_PREDICTOR, PREDICTOR_FLOATINGPOINT);
    }
    else {
      TIFFSetField(m_hTif, TIFFTAG_PREDICTOR, PREDICTOR_HORIZONTAL);
    }
  }
  m_nCurLine = 0;
  m_nCurStrip = 0;
  if (bSep && m_nSamples>1) {
    m_nStripSamples = m_nSamples;
    if (m_nBitsPerSample % 8) {
      Close();
      return false;
    }
    m_nBytesPerSample = m_nBitsPerSample / 8;
    m_nStripSize = (unsigned int)TIFFStripSize(m_hTif);
    m_nBytesPerStripLine = m_nWidth * m_nBytesPerSample;
    if (m_nStripSize!=m_nBytesPerStripLine) {
      Close();
      return false;
    }
    m_nBytesPerLine = m_nWidth * m_nBytesPerSample * m_nSamples;
    m_pStripBuf = (unsigned char*)malloc(m_nStripSize*m_nStripSamples);
    if (!m_pStripBuf) {
      Close();
      return false;
    }
    m_nStripsPerSample = m_nHeight / m_nRowsPerStrip;
  }
  else {
    m_nBytesPerLine = m_nStripSize = (unsigned int)TIFFStripSize(m_hTif);
    m_nStripSamples = 1;
  }
  return true;
}
References Close(), m_bRead, m_fXRes, m_fYRes, m_hTif, m_nBitsPerSample, m_nBytesPerLine, m_nBytesPerSample, m_nBytesPerStripLine, m_nCompress, m_nCurLine, m_nCurStrip, m_nHeight, m_nPhoto, m_nPlanar, m_nRowsPerStrip, m_nSamples, m_nStripSamples, m_nStripSize, m_nStripsPerSample, m_nWidth, and m_pStripBuf.
Referenced by main(), and main().
GetBitsPerSample()
unsigned int CTiffImg::GetBitsPerSample () inline
{ return m_nBitsPerSample;}
References m_nBitsPerSample.
Referenced by main(), main(), and main().
GetBytesPerLine()
unsigned int CTiffImg::GetBytesPerLine () inline
{ return m_nBytesPerLine; }
References m_nBytesPerLine.
Referenced by main(), main(), and main().
GetCompress()
unsigned int CTiffImg::GetCompress () inline
{ return m_nCompress; }
References m_nCompress.
Referenced by main(), and main().
GetExtraSamples()
unsigned int CTiffImg::GetExtraSamples () inline
{ return m_nExtraSamples; }
References m_nExtraSamples.
Referenced by main().
GetHeight()
unsigned int CTiffImg::GetHeight () inline
{ return m_nHeight;}
References m_nHeight.
Referenced by main(), main(), and main().
GetHeightIn()
double CTiffImg::GetHeightIn () inline
{ return (double)m_nHeight / m_fYRes; }
References m_fYRes, and m_nHeight.
Referenced by main().
GetIccProfile()
bool CTiffImg::GetIccProfile (unsigned char *& pProfile, unsigned int & nLen)
{
  pProfile = NULL;
  nLen = 0;
  TIFFGetField(m_hTif, TIFFTAG_ICCPROFILE, &nLen, &pProfile);
  return pProfile!=NULL && nLen>0;
}
References m_hTif.
Referenced by main(), and main().
GetPhoto()
unsigned int CTiffImg::GetPhoto ()
{
  if (m_nPhoto==PHOTOMETRIC_MINISBLACK ||
      m_nPhoto==PHOTOMETRIC_RGB) {
    return PHOTO_MINISBLACK;
  }
  else if (m_nPhoto==PHOTOMETRIC_MINISWHITE ||
           m_nPhoto==PHOTOMETRIC_SEPARATED) {
    return PHOTO_MINISWHITE;
  }
  else if (m_nPhoto==PHOTOMETRIC_CIELAB)
    return PHOTO_CIELAB;
  else if (m_nPhoto==PHOTOMETRIC_ICCLAB)
    return PHOTO_ICCLAB;
  else
    return PHOTO_MINISWHITE;
}
References m_nPhoto.
Referenced by main(), main(), and main().
GetPlanar()
unsigned int CTiffImg::GetPlanar () inline
{ return m_nPlanar; }
References m_nPlanar.
Referenced by main(), and main().
GetSamples()
unsigned int CTiffImg::GetSamples () inline
{ return m_nSamples;}
References m_nSamples.
Referenced by main(), main(), and main().
GetWidth()
unsigned int CTiffImg::GetWidth () inline
{ return m_nWidth;}
References m_nWidth.
Referenced by main(), main(), and main().
GetWidthIn()
double CTiffImg::GetWidthIn () inline
{ return (double)m_nWidth / m_fXRes; }
References m_fXRes, and m_nWidth.
Referenced by main().
GetXRes()
float CTiffImg::GetXRes () inline
{return m_fXRes;}
References m_fXRes.
Referenced by main(), main(), and main().
GetYRes()
float CTiffImg::GetYRes () inline
{return m_fYRes;}
References m_fYRes.
Referenced by main(), main(), and main().
Open()
bool CTiffImg::Open (const char * szFname)
{
  Close();
  m_bRead = true;
  m_hTif = TIFFOpen(szFname, "r");
  if (!m_hTif) {
    TIFFError(szFname,"Can not open input image");
    return false;
  }
  icUInt16Number nPlanar=PLANARCONFIG_CONTIG;
  icUInt16Number nOrientation=ORIENTATION_TOPLEFT;
  icUInt16Number nSampleFormat=SAMPLEFORMAT_UINT;
  icUInt16Number *nSampleInfo=NULL;
  TIFFGetField(m_hTif, TIFFTAG_IMAGEWIDTH, &m_nWidth);
  TIFFGetField(m_hTif, TIFFTAG_IMAGELENGTH, &m_nHeight);
  TIFFGetField(m_hTif, TIFFTAG_PHOTOMETRIC, &m_nPhoto);
  TIFFGetField(m_hTif, TIFFTAG_PLANARCONFIG, &m_nPlanar);
  TIFFGetField(m_hTif, TIFFTAG_SAMPLESPERPIXEL, &m_nSamples);
  TIFFGetField(m_hTif, TIFFTAG_EXTRASAMPLES, &m_nExtraSamples, &nSampleInfo);
  TIFFGetField(m_hTif, TIFFTAG_BITSPERSAMPLE, &m_nBitsPerSample);
  TIFFGetField(m_hTif, TIFFTAG_SAMPLEFORMAT, &nSampleFormat);
  TIFFGetField(m_hTif, TIFFTAG_ROWSPERSTRIP, &m_nRowsPerStrip);
  TIFFGetField(m_hTif, TIFFTAG_ORIENTATION, &nOrientation);
  TIFFGetField(m_hTif, TIFFTAG_XRESOLUTION, &m_fXRes);
  TIFFGetField(m_hTif, TIFFTAG_YRESOLUTION, &m_fYRes);
  TIFFGetField(m_hTif, TIFFTAG_COMPRESSION, &m_nCompress);
  //Validate what we expect to work with
  if ((m_nBitsPerSample==32 && nSampleFormat!=SAMPLEFORMAT_IEEEFP) ||
      (m_nBitsPerSample!=32 && nSampleFormat!=SAMPLEFORMAT_UINT) ||
       nOrientation != ORIENTATION_TOPLEFT) {
    Close();
    return false;
  }
  m_nCurStrip=(unsigned int)-1;
  m_nCurLine = 0;
  m_nStripSize = (unsigned int)TIFFStripSize(m_hTif);
  if (m_nSamples>1 && m_nPlanar==PLANARCONFIG_SEPARATE) {
    m_nStripSamples = m_nSamples;
    m_nBytesPerLine = (m_nWidth * m_nBitsPerSample * m_nSamples + 7)>>3;
    m_nBytesPerSample = m_nBitsPerSample / 8;
    m_nBytesPerStripLine = m_nWidth * m_nBytesPerSample;
    //Only support bitspersample that fits on byte boundary
    if (m_nBitsPerSample%8) {
      Close();
      return false;
    }
    m_nStripsPerSample = m_nHeight / m_nRowsPerStrip;
    //Only support separations that evenly fit into strips
    if (m_nHeight % m_nRowsPerStrip) {
      Close();
      return false;
    }
  }
  else {
    m_nStripSamples = 1;
    m_nBytesPerLine = (m_nWidth * m_nBitsPerSample * m_nSamples + 7)>>3;
  }
  m_pStripBuf = (unsigned char*)malloc(m_nStripSize*m_nStripSamples);
  if (!m_pStripBuf) {
    Close();
    return false;
  }
  return true;
}
References Close(), m_bRead, m_fXRes, m_fYRes, m_hTif, m_nBitsPerSample, m_nBytesPerLine, m_nBytesPerSample, m_nBytesPerStripLine, m_nCompress, m_nCurLine, m_nCurStrip, m_nExtraSamples, m_nHeight, m_nPhoto, m_nPlanar, m_nRowsPerStrip, m_nSamples, m_nStripSamples, m_nStripSize, m_nStripsPerSample, m_nWidth, and m_pStripBuf.
Referenced by main(), main(), and main().
ReadLine()
bool CTiffImg::ReadLine (unsigned char * pBuf)
{
  if (!m_bRead)
    return false;
  unsigned int nStrip = m_nCurLine / m_nRowsPerStrip;
  unsigned int nRowOffset = m_nCurLine % m_nRowsPerStrip;
  if (nStrip != m_nCurStrip) {
    m_nCurStrip = nStrip;
    if (m_nStripSamples>1) {
      unsigned int s;
      unsigned char *pos = m_pStripBuf;
      unsigned int nStripOffset = 0;
      for (s=0; s<m_nStripSamples; s++) {
        if (TIFFReadEncodedStrip(m_hTif, m_nCurStrip+nStripOffset, pos, m_nStripSize) < 0) {
          return false;
        }
        nStripOffset += m_nStripsPerSample;
        pos += m_nBytesPerStripLine;
      }
    }
    else if (TIFFReadEncodedStrip(m_hTif, m_nCurStrip, m_pStripBuf, m_nStripSize) < 0) {
      return false;
    }
  }
  if (m_nStripSamples>1) { //Sep to contig
    unsigned char *src, *dst;
    src = m_pStripBuf+nRowOffset*m_nBytesPerStripLine;
    dst = pBuf;
    unsigned int w, s;
    for (w=0; w<m_nWidth; w++) {
      unsigned char *pos = src;
      for (s=0; s<m_nSamples; s++) {
        memcpy(dst, pos, m_nBytesPerSample);
        dst += m_nBytesPerSample;
        pos += m_nStripSize;
      }
      src += m_nBytesPerSample;
    }
  }
  else {
    memcpy(pBuf, m_pStripBuf+nRowOffset*m_nBytesPerLine, m_nBytesPerLine);
  }
  m_nCurLine++;
  return true;
}
References m_bRead, m_hTif, m_nBytesPerLine, m_nBytesPerSample, m_nBytesPerStripLine, m_nCurLine, m_nCurStrip, m_nRowsPerStrip, m_nSamples, m_nStripSamples, m_nStripSize, m_nStripsPerSample, m_nWidth, and m_pStripBuf.
Referenced by main(), and main().
SetIccProfile()
bool CTiffImg::SetIccProfile (unsigned char * pProfile, unsigned int nLen)
{
  TIFFSetField(m_hTif, TIFFTAG_ICCPROFILE, nLen, pProfile);
  return true;
}
References m_hTif.
Referenced by main(), and main().
WriteLine()
bool CTiffImg::WriteLine (unsigned char * pBuf)
{
  if (m_bRead)
    return false;
  if (m_nCurStrip < m_nHeight) { //Contig to Sep
    if (m_nStripSamples>1) {
      unsigned char *src, *dst;
      src = pBuf;
      dst = m_pStripBuf;
      unsigned int w, s, offset;
      for (w=0; w<m_nWidth; w++) {
        unsigned char *pos = dst;
        for (s=0; s<m_nSamples; s++) {
          memcpy(pos, src, m_nBytesPerSample);
          src += m_nBytesPerSample;
          pos += m_nStripSize;
        }
        dst += m_nBytesPerSample;
      }
      offset = 0;
      src = m_pStripBuf;
      for (s=0; s<m_nSamples; s++) {
        if (TIFFWriteEncodedStrip(m_hTif, m_nCurStrip+offset, src, m_nStripSize) < 0)
          return false;
        offset += m_nStripsPerSample;
        src += m_nStripSize;
      }
    }
    else if (TIFFWriteEncodedStrip(m_hTif, m_nCurStrip, pBuf, m_nBytesPerLine) < 0)
      return false;
    m_nCurStrip++;
  }
  return true;
}
References m_bRead, m_hTif, m_nBytesPerLine, m_nBytesPerSample, m_nCurStrip, m_nHeight, m_nSamples, m_nStripSamples, m_nStripSize, m_nStripsPerSample, m_nWidth, and m_pStripBuf.
Referenced by main(), and main().
Field Documentation
m_bRead
bool CTiffImg::m_bRead protected
Referenced by Create(), Open(), ReadLine(), and WriteLine().
m_fXRes
float CTiffImg::m_fXRes protected
Referenced by Create(), GetWidthIn(), GetXRes(), and Open().
m_fYRes
float CTiffImg::m_fYRes protected
Referenced by Create(), GetHeightIn(), GetYRes(), and Open().
m_hTif
TIFF* CTiffImg::m_hTif protected
Referenced by CTiffImg(), Close(), Create(), GetIccProfile(), Open(), ReadLine(), SetIccProfile(), and WriteLine().
m_nBitsPerSample
icUInt16Number CTiffImg::m_nBitsPerSample protected
Referenced by CTiffImg(), Close(), Create(), GetBitsPerSample(), and Open().
m_nBytesPerLine
unsigned int CTiffImg::m_nBytesPerLine protected
Referenced by Create(), GetBytesPerLine(), Open(), ReadLine(), and WriteLine().
m_nBytesPerSample
icUInt16Number CTiffImg::m_nBytesPerSample protected
Referenced by Create(), Open(), ReadLine(), and WriteLine().
m_nBytesPerStripLine
unsigned int CTiffImg::m_nBytesPerStripLine protected
Referenced by Create(), Open(), and ReadLine().
m_nCompress
icUInt16Number CTiffImg::m_nCompress protected
Referenced by Create(), GetCompress(), and Open().
m_nCurLine
unsigned int CTiffImg::m_nCurLine protected
Referenced by Create(), Open(), and ReadLine().
m_nCurStrip
unsigned int CTiffImg::m_nCurStrip protected
Referenced by Create(), Open(), ReadLine(), and WriteLine().
m_nExtraSamples
icUInt16Number CTiffImg::m_nExtraSamples protected
Referenced by CTiffImg(), Close(), GetExtraSamples(), and Open().
m_nHeight
unsigned int CTiffImg::m_nHeight protected
Referenced by CTiffImg(), Close(), Create(), GetHeight(), GetHeightIn(), Open(), and WriteLine().
m_nPhoto
icUInt16Number CTiffImg::m_nPhoto protected
Referenced by Create(), GetPhoto(), and Open().
m_nPlanar
icUInt16Number CTiffImg::m_nPlanar protected
Referenced by Create(), GetPlanar(), and Open().
m_nProfileLength
unsigned int CTiffImg::m_nProfileLength protected
m_nRowsPerStrip
unsigned int CTiffImg::m_nRowsPerStrip protected
Referenced by Create(), Open(), and ReadLine().
m_nSamples
icUInt16Number CTiffImg::m_nSamples protected
Referenced by CTiffImg(), Close(), Create(), GetSamples(), Open(), ReadLine(), and WriteLine().
m_nStripSamples
unsigned int CTiffImg::m_nStripSamples protected
Referenced by Create(), Open(), ReadLine(), and WriteLine().
m_nStripSize
unsigned int CTiffImg::m_nStripSize protected
Referenced by Create(), Open(), ReadLine(), and WriteLine().
m_nStripsPerSample
unsigned int CTiffImg::m_nStripsPerSample protected
Referenced by Create(), Open(), ReadLine(), and WriteLine().
m_nWidth
unsigned int CTiffImg::m_nWidth protected
Referenced by CTiffImg(), Close(), Create(), GetWidth(), GetWidthIn(), Open(), ReadLine(), and WriteLine().
m_pProfile
unsigned char* CTiffImg::m_pProfile protected
m_pStripBuf
unsigned char* CTiffImg::m_pStripBuf protected
Referenced by CTiffImg(), Close(), Create(), Open(), ReadLine(), and WriteLine().
The documentation for this class was generated from the following files:
Tools/CmdLine/IccApplyProfiles/TiffImg.h
Tools/CmdLine/IccApplyProfiles/TiffImg.cpp