iccDEV: CIccTagXmlTagData Class Reference
CIccTagXmlTagData Class Reference
#include <IccTagXml.h>
Public Member Functions
virtual ~CIccTagXmlTagData ()
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
virtual const char * GetClassName () const
icUInt8Number * GetData (icUInt32Number index=0)
virtual const char * GetExtClassName () const
virtual const char * GetExtDerivedClassName () const
virtual IIccExtensionTag * GetExtension ()
icUInt32Number GetSize () const
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual bool IsTypeAscii ()
virtual bool IsTypeBinary ()
virtual bool IsTypeCompressed ()
virtual bool IsTypeUtf ()
virtual CIccTag * NewCopy () const
icUInt8Number & operator[] (icUInt32Number index)
virtual bool ParseXml (xmlNode *pNode, std::string &parseStr)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
virtual void SetDataType (icDataBlockType dataType=icAsciiData)
bool SetSize (icUInt32Number nSize, bool bZeroNew=true)
virtual bool ToXml (std::string &xml, std::string blanks="")
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
Protected Attributes
icDataBlockType m_nDataFlag
icUInt32Number m_nSize
icUInt8Number * m_pData
Detailed Description
Constructor & Destructor Documentation
~CIccTagXmlTagData()
virtual CIccTagXmlTagData::~CIccTagXmlTagData () inline virtual
{}
Member Function Documentation
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagData::Describe (std::string & sDescription, int nVerboseness) virtual inherited
Name: CIccTagData::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  icChar buf[128];
  sDescription = "\n";
  if (IsTypeCompressed())
    sDescription += "Compressed ";  // If data is compressed, prepend appropriate text
  if (IsTypeAscii()) {
    sDescription = "Ascii Data:\n";
    for (int i=0; i<(int)m_nSize; i++)
      sDescription += (icChar)m_pData[i];
  }
  else if (IsTypeUtf()) {
    if (m_nSize>2 &&
        ((m_pData[0]==0xff && m_pData[1]==0xfe) ||  //UTF-16LE
         (m_pData[0]==0xfe && m_pData[1]==0xff))) { //UTF-16BE
      sprintf(buf, "UTF-16%s Data:", m_pData[0]==0xff ? "LE" : "BE" );
      sDescription = buf;
      icMemDump(sDescription, m_pData, m_nSize);
    }
    else { //UTF-8
      sDescription = "UTF-8 Data:\n";
      for (int i=0; i<(int)m_nSize; i++)
        sDescription += (icChar)m_pData[i];
    }
  }
  else {
    if (IsTypeBinary()) {
      sDescription = "Binary Data:\n";
    }
    else {
      sDescription = "Other Data:\n";
    }
    icMemDump(sDescription, m_pData, m_nSize);
  }
  sDescription += "\n";
}
References icMemDump(), CIccTagData::IsTypeAscii(), CIccTagData::IsTypeBinary(), CIccTagData::IsTypeCompressed(), CIccTagData::IsTypeUtf(), CIccTagData::m_nSize, and CIccTagData::m_pData.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
GetClassName()
virtual const char * CIccTagXmlTagData::GetClassName () const inline virtual
Reimplemented from CIccTagData.
{return "CIccTagXmlTagData"; }
GetData()
icUInt8Number * CIccTagData::GetData (icUInt32Number index = 0) inline inherited
{ return &m_pData[index];}
References CIccTagData::m_pData.
GetExtClassName()
virtual const char * CIccTagXml::GetExtClassName () const inline virtual inherited
Implements IIccExtensionTag.
{ return "CIccTagXml"; }
Referenced by icProfDescToXml(), and icXmlParseProfDesc().
GetExtDerivedClassName()
virtual const char * CIccTagXml::GetExtDerivedClassName () const inline virtual inherited
Implements IIccExtensionTag.
Reimplemented in CIccCurveXml.
{ return ""; }
GetExtension()
virtual IIccExtensionTag * CIccTagXmlTagData::GetExtension () inline virtual
Reimplemented from CIccTag.
{return this; }
GetSize()
icUInt32Number CIccTagData::GetSize () const inline inherited
{ return m_nSize; }
References CIccTagData::m_nSize.
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagData::GetType () const inline virtual inherited
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigDataType; }
References icSigDataType.
Referenced by CIccTagData::Write().
IsArrayType()
virtual bool CIccTagData::IsArrayType () inline virtual inherited
Reimplemented from CIccTag.
{ return m_nSize > 1; }
References CIccTagData::m_nSize.
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
IsTypeAscii()
virtual bool CIccTagData::IsTypeAscii () inline virtual inherited
{ return (m_nDataFlag&icDataTypeMask) == icAsciiData; }
References icAsciiData, and CIccTagData::m_nDataFlag.
Referenced by CIccTagData::Describe().
IsTypeBinary()
virtual bool CIccTagData::IsTypeBinary () inline virtual inherited
{ return (m_nDataFlag&icDataTypeMask) == icBinaryData; }
References icBinaryData, and CIccTagData::m_nDataFlag.
Referenced by CIccTagData::Describe().
IsTypeCompressed()
virtual bool CIccTagData::IsTypeCompressed () inline virtual inherited
{ return (m_nDataFlag & icCompressedData) != 0; }
References CIccTagData::m_nDataFlag.
Referenced by CIccTagData::Describe(), CIccTagData::Read(), and CIccTagData::Write().
IsTypeUtf()
virtual bool CIccTagData::IsTypeUtf () inline virtual inherited
{ return (m_nDataFlag&icDataTypeMask) == icUtfData; }
References icUtfData, and CIccTagData::m_nDataFlag.
Referenced by CIccTagData::Describe().
NewCopy()
virtual CIccTag * CIccTagData::NewCopy () const inline virtual inherited
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
{return new CIccTagData(*this);}
References CIccTagData::CIccTagData().
operator[]()
icUInt8Number & CIccTagData::operator[] (icUInt32Number index) inline inherited
{ return m_pData[index]; }
References CIccTagData::m_pData.
ParseXml()
bool CIccTagXmlTagData::ParseXml (xmlNode * pNode, std::string & parseStr) virtual
Implements CIccTagXml.
{
  pNode = icXmlFindNode(pNode, "Data");
  if (pNode && pNode->children && pNode->children->content) {
    const icChar *szFlag = icXmlAttrValue(pNode, "Flag");
    m_nDataFlag = icAsciiData;
    if (!strcmp(szFlag,"binary"))
      m_nDataFlag = icBinaryData;
    icUInt32Number nSize = icXmlGetHexDataSize((const char *)pNode->children->content);
    SetSize(nSize, false);
    if (nSize) {
      icXmlGetHexData(m_pData, (const char*)pNode->children->content, nSize);
    }
    return true;
  }
  return false;
}
References icAsciiData, icBinaryData, icXmlAttrValue(), icXmlFindNode(), icXmlGetHexData(), icXmlGetHexDataSize(), CIccTagData::m_nDataFlag, CIccTagData::m_pData, and CIccTagData::SetSize().
Read() [1/2]
bool CIccTagData::Read (icUInt32Number size, CIccIO * pIO) virtual inherited
Name: CIccTagData::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  if (sizeof(icTagTypeSignature) +
      sizeof(icUInt32Number) +
      sizeof(icUInt32Number) +
      sizeof(icUInt8Number) > size)
    return false;
  if (!pIO) {
    return false;
  }
  if (!pIO->Read32(&sig))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  if (!pIO->Read32(&m_nDataFlag))
    return false;
  icUInt32Number nNum = size-3*sizeof(icUInt32Number);
  if (!SetSize(nNum))
    return false;
  if (pIO->Read8(m_pData, nNum) != (icInt32Number)nNum)
    return false;
  if (IsTypeCompressed()) {
    //Uncompress data here
  }
  return true;
}
References CIccTagData::IsTypeCompressed(), CIccTagData::m_nDataFlag, CIccTag::m_nReserved, CIccTagData::m_pData, CIccIO::Read32(), CIccIO::Read8(), and CIccTagData::SetSize().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
SetDataType()
virtual void CIccTagData::SetDataType (icDataBlockType dataType = icAsciiData) inline virtual inherited
{ m_nDataFlag = dataType; }
References CIccTagData::m_nDataFlag.
SetSize()
bool CIccTagData::SetSize (icUInt32Number nSize, bool bZeroNew = true) inherited
Name: CIccTagData::SetSize
Purpose: Sets the size of the data array.
Args: nSize - number of data entries, bZeroNew - flag to zero newly formed values
{
  if (m_nSize == nSize)
    return true;
  m_pData = (icUInt8Number*)icRealloc(m_pData, nSize*sizeof(icUInt8Number));
  if (!m_pData) {
    m_nSize = 0;
    return false;
  }
  if (bZeroNew && nSize > m_nSize) {
    memset(&m_pData[m_nSize], 0, (nSize-m_nSize)*sizeof(icUInt8Number));
  }
  m_nSize = nSize;
  return true;
}
References icRealloc(), CIccTagData::m_nSize, and CIccTagData::m_pData.
Referenced by ParseXml(), and CIccTagData::Read().
ToXml()
bool CIccTagXmlTagData::ToXml (std::string & xml, std::string blanks = "") virtual
Implements CIccTagXml.
{
  icUInt8Number *ptr = m_pData;
  char buf[60];
  std::string szFlag("ASCII");
  if (m_nDataFlag == 1)
    szFlag = "binary";
  sprintf (buf, "<Data Flag=\"%s\">\n", szFlag.c_str());
  xml += blanks + buf;
  icXmlDumpHexData(xml, blanks+" ", m_pData, m_nSize);
  xml += blanks + "</Data>\n";
  return true;
}
References icXmlDumpHexData(), CIccTagData::m_nDataFlag, CIccTagData::m_nSize, and CIccTagData::m_pData.
Validate()
icValidateStatus CIccTagData::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual inherited
Name: CIccTagData::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  // Mask bits to match processing in Describe() so warnings are appropriate
  switch(m_nDataFlag&(icCompressedData|icDataTypeMask)) {
  case icAsciiData:
    for (int i = 0; i < (int)m_nSize; i++) {
      if (m_pData[i] & 0x80) {
        sReport += icMsgValidateWarning;
        sReport += sSigPathName;
        sReport += " - Ascii Data is not just 7-bit data.\n";
        rv = icMaxStatus(rv, icValidateWarning);
        break;
      }
    }
    break;
  case icBinaryData:
  case icUtfData:
  case icCompressedAsciiData:
  case icCompressedBinaryData:
  case icCompressedUtfData:
    break;
  default:
    sReport += icMsgValidateNonCompliant;
    sReport += sSigPathName;
    sReport += " - Invalid data flag encoding.\n";
    rv = icMaxStatus(rv, icValidateNonCompliant);
  }
  if (m_nDataFlag & ~(icCompressedData | icDataTypeMask)) {
      sReport += icMsgValidateNonCompliant;
      sReport += sSigPathName;
      sReport += " - Invalid data flag encoding (reserved high order bits).\n";
      rv = icMaxStatus(rv, icValidateNonCompliant);
  }
  return rv;
}
References CIccInfo::GetSigPathName(), icAsciiData, icBinaryData, icCompressedAsciiData, icCompressedBinaryData, icCompressedUtfData, icMaxStatus(), icMsgValidateNonCompliant, icMsgValidateWarning, icUtfData, icValidateNonCompliant, icValidateWarning, CIccTagData::m_nDataFlag, CIccTagData::m_nSize, CIccTagData::m_pData, and CIccTag::Validate().
Write()
bool CIccTagData::Write (CIccIO * pIO) virtual inherited
Name: CIccTagData::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  if (!pIO)
   return false;
  if (!pIO->Write32(&sig))
   return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  if (!pIO->Write32(&m_nDataFlag))
    return false;
  if (IsTypeCompressed()) {
    icUInt32Number *pData = NULL;
    icInt32Number nSize = 0;
    //Compress data here
    if (pIO->Write8(pData, nSize) != (icInt32Number)nSize)
      return false;
  }
  else {
    if (pIO->Write8(m_pData, m_nSize) != (icInt32Number)m_nSize)
      return false;
  }
  return true;
}
References CIccTagData::GetType(), CIccTagData::IsTypeCompressed(), CIccTagData::m_nDataFlag, CIccTag::m_nReserved, CIccTagData::m_nSize, CIccTagData::m_pData, CIccIO::Write32(), and CIccIO::Write8().
Field Documentation
m_nDataFlag
icDataBlockType CIccTagData::m_nDataFlag protected inherited
Referenced by CIccTagData::CIccTagData(), CIccTagData::IsTypeAscii(), CIccTagData::IsTypeBinary(), CIccTagData::IsTypeCompressed(), CIccTagData::IsTypeUtf(), CIccTagData::operator=(), ParseXml(), CIccTagData::Read(), CIccTagData::SetDataType(), ToXml(), CIccTagData::Validate(), and CIccTagData::Write().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_nSize
icUInt32Number CIccTagData::m_nSize protected inherited
Referenced by CIccTagData::CIccTagData(), CIccTagData::CIccTagData(), CIccTagData::Describe(), CIccTagData::GetSize(), CIccTagData::IsArrayType(), CIccTagData::operator=(), CIccTagData::SetSize(), ToXml(), CIccTagData::Validate(), and CIccTagData::Write().
m_pData
icUInt8Number* CIccTagData::m_pData protected inherited
Referenced by CIccTagData::CIccTagData(), CIccTagData::CIccTagData(), CIccTagData::~CIccTagData(), CIccTagData::Describe(), CIccTagData::GetData(), CIccTagData::operator=(), CIccTagData::operator[](), ParseXml(), CIccTagData::Read(), CIccTagData::SetSize(), ToXml(), CIccTagData::Validate(), and CIccTagData::Write().
The documentation for this class was generated from the following files:
IccXML/IccLibXML/IccTagXml.h
IccXML/IccLibXML/IccTagXml.cpp