iccDEV: CIccXmlArrayType< T, Tsig > Class Template Reference
CIccXmlArrayType< T, Tsig > Class Template Reference
#include <IccUtilXml.h>
Public Member Functions
CIccXmlArrayType ()
~CIccXmlArrayType ()
T * GetBuf ()
icUInt32Number GetSize ()
bool ParseArray (xmlNode *pNode)
bool ParseTextArray (const char *szText)
bool ParseTextArray (xmlNode *pNode)
bool ParseTextArrayNum (const char *szText, icUInt32Number num, std::string &parseStr)
bool SetSize (icUInt32Number nSize)
Static Public Member Functions
static bool DumpArray (std::string &xml, std::string blanks, T *buf, icUInt32Number nBufSize, icConvertType nType, icUInt8Number nColumns)
static bool ParseArray (T *buf, icUInt32Number nBufSize, xmlNode *pNode)
static icUInt32Number ParseText (T *buf, icUInt32Number nBufSize, const char *szText)
static icUInt32Number ParseTextCount (const char *szText)
static icUInt32Number ParseTextCountNum (const char *szText, icUInt32Number num, std::string &parseStr)
Protected Attributes
icUInt32Number m_nSize
T * m_pBuf
Detailed Description
template<class T, icTagTypeSignature Tsig>
class CIccXmlArrayType< T, Tsig >
Constructor & Destructor Documentation
CIccXmlArrayType()
template<class T , icTagTypeSignature Tsig> CIccXmlArrayType< T, Tsig >::CIccXmlArrayType ()
{
  m_pBuf = NULL;
  m_nSize = 0;
}
References CIccXmlArrayType< T, Tsig >::m_nSize, and CIccXmlArrayType< T, Tsig >::m_pBuf.
~CIccXmlArrayType()
template<class T , icTagTypeSignature Tsig> CIccXmlArrayType< T, Tsig >::~CIccXmlArrayType ()
{
  if (m_pBuf) {
    free(m_pBuf);
  }
}
References CIccXmlArrayType< T, Tsig >::m_pBuf.
Member Function Documentation
DumpArray()
template<class T , icTagTypeSignature Tsig> bool CIccXmlArrayType< T, Tsig >::DumpArray (std::string & xml, std::string blanks, T * buf, icUInt32Number nBufSize, icConvertType nType, icUInt8Number nColumns) static
{
  char str[200];
  if (!nColumns) nColumns = 1;
  icUInt32Number i;
  for (i=0; i<nBufSize; i++) {
    if (!(i%nColumns)) {
      xml += blanks;
    }
    else {
      xml += " ";
    }
    switch (Tsig) {
      case icSigUInt8ArrayType:
        switch (nType) {
          case icConvert8Bit:
          default:
            sprintf(str, "%u", (icUInt8Number)buf[i]);
            break;
          case icConvert16Bit:
            sprintf(str, "%u", (icUInt16Number)((icFloatNumber)buf[i] * 65535.0 / 255.0 + 0.5));
            break;
          case icConvertFloat:
            sprintf(str, icXmlFloatFmt, (icFloatNumber)buf[i] / 255.0);
            break;
        }
        break;
      case icSigUInt16ArrayType:
        switch (nType) {
          case icConvert8Bit:
            sprintf(str, "%u", (icUInt16Number)((icFloatNumber)buf[i] * 255.0 / 65535.0 + 0.5));
            break;
          case icConvert16Bit:
          default:
            sprintf(str, "%u", (icUInt16Number)buf[i]);
            break;
          case icConvertFloat:
            sprintf(str, icXmlFloatFmt, (icFloatNumber)buf[i] / 65535.0);
            break;
        }
        break;
      case icSigUInt32ArrayType:
        sprintf(str, "%u", (icUInt32Number)buf[i]);
        break;
      case icSigUInt64ArrayType:
        // unused
        break;
      case icSigFloatArrayType:
      case icSigFloat32ArrayType:
      case icSigFloat64ArrayType:
        switch (nType) {
          case icConvert8Bit:
            sprintf(str, "%u", (icUInt8Number)(buf[i] * 255.0 + 0.5));
            break;
          case icConvert16Bit:
            sprintf(str, "%u", (icUInt16Number)(buf[i] * 65535.0 + 0.5));
            break;
          case icConvertFloat:
          default:
            sprintf(str, icXmlFloatFmt, (icFloatNumber)buf[i]);
        }
        break;
    }
    xml += str;
    if (i%nColumns == nColumns-1) {
      xml += "\n";
    }
  }
  if (i%nColumns) {
    xml += "\n";
  }
  return true;
}
References icConvert16Bit, icConvert8Bit, icConvertFloat, icSigFloat32ArrayType, icSigFloat64ArrayType, icSigUInt16ArrayType, icSigUInt32ArrayType, icSigUInt64ArrayType, and icSigUInt8ArrayType.
Referenced by CIccFormulaCurveSegmentXml::ToXml(), CIccSampledCurveSegmentXml::ToXml(), CIccSinglSampledeCurveXml::ToXml(), CIccXmlToneMapFunc::ToXml(), CIccTagXmlSparseMatrixArray::ToXml(), and CIccTagXmlGamutBoundaryDesc::ToXml().
GetBuf()
template<class T , icTagTypeSignature Tsig> T * CIccXmlArrayType< T, Tsig >::GetBuf () inline
{ return m_pBuf; }
References CIccXmlArrayType< T, Tsig >::m_pBuf.
Referenced by icCLutFromXml(), icXmlParseTextString(), CIccTagXmlCurve::ParseXml(), CIccFormulaCurveSegmentXml::ParseXml(), CIccSampledCurveSegmentXml::ParseXml(), CIccSinglSampledeCurveXml::ParseXml(), CIccXmlToneMapFunc::ParseXml(), CIccTagXmlZipUtf8Text::ParseXml(), CIccTagXmlZipXml::ParseXml(), CIccTagXmlNamedColor2::ParseXml(), CIccTagXmlSparseMatrixArray::ParseXml(), CIccTagXmlFixedNum< T, Tsig >::ParseXml(), CIccTagXmlSpectralViewingConditions::ParseXml(), CIccTagXmlParametricCurve::ParseXml(), and CIccTagXmlGamutBoundaryDesc::ParseXml().
GetSize()
template<class T , icTagTypeSignature Tsig> icUInt32Number CIccXmlArrayType< T, Tsig >::GetSize () inline
{ return m_nSize; }
References CIccXmlArrayType< T, Tsig >::m_nSize.
Referenced by icCLutFromXml(), icXmlParseTextString(), CIccTagXmlCurve::ParseXml(), CIccFormulaCurveSegmentXml::ParseXml(), CIccSampledCurveSegmentXml::ParseXml(), CIccSinglSampledeCurveXml::ParseXml(), CIccXmlToneMapFunc::ParseXml(), CIccTagXmlZipUtf8Text::ParseXml(), CIccTagXmlZipXml::ParseXml(), CIccTagXmlNamedColor2::ParseXml(), CIccTagXmlSparseMatrixArray::ParseXml(), CIccTagXmlFixedNum< T, Tsig >::ParseXml(), CIccTagXmlSpectralViewingConditions::ParseXml(), CIccTagXmlParametricCurve::ParseXml(), and CIccTagXmlGamutBoundaryDesc::ParseXml().
ParseArray() [1/2]
template<class T , icTagTypeSignature Tsig> bool CIccXmlArrayType< T, Tsig >::ParseArray (T * buf, icUInt32Number nBufSize, xmlNode * pNode) static
{
  icUInt32Number n;
  if (Tsig==icSigFloatArrayType) {
    n = icXmlNodeCount(pNode, "f");
    if (!n) {
      if (pNode->type!=XML_TEXT_NODE || !pNode->content)
        return false;
      n = ParseTextCount((const char*)pNode->content);
      if (!n || n>nSize)
        return false;
      ParseText(pBuf, n, (const char*)pNode->content);
    }
    else {
      if (n>nSize)
        return false;
      icUInt32Number i;
      for (i=0; i<nSize && pNode; pNode = pNode->next) {
        if (pNode->type == XML_ELEMENT_NODE &&
          !icXmlStrCmp(pNode->name, "f") &&
          pNode->children &&
          pNode->children->content) {
            float f;
            sscanf((const char *)(pNode->children->content), "%f", &f);
            pBuf[i] = (T)f;
            i++;
        }
      }
    }
  }
  else {
    n = icXmlNodeCount(pNode, "n");
    if (!n) {
      if (pNode->type!=XML_TEXT_NODE || !pNode->content)
        return false;
      n = ParseTextCount((const char *)pNode->content);
      if (!n || n>nSize)
        return false;
      n = ParseText(pBuf, n, (const char *)pNode->content);
    }
    else {
      if (n>nSize)
        return false;
      icUInt32Number i;
      for (i=0; i<nSize && pNode; pNode = pNode->next) {
        if (pNode->type == XML_ELEMENT_NODE &&
          !icXmlStrCmp(pNode->name, "n") &&
          pNode->children &&
          pNode->children->content) {
            pBuf[i] = (T)atol((const char *)(pNode->children->content));
            i++;
        }
      }
    }
  }
  return nSize==n;
}
References icXmlNodeCount(), CIccXmlArrayType< T, Tsig >::ParseText(), and CIccXmlArrayType< T, Tsig >::ParseTextCount().
Referenced by CIccMpeXmlMatrix::ParseXml(), CIccMpeXmlEmissionMatrix::ParseXml(), CIccMpeXmlInvEmissionMatrix::ParseXml(), CIccMpeXmlEmissionCLUT::ParseXml(), CIccMpeXmlReflectanceCLUT::ParseXml(), CIccMpeXmlEmissionObserver::ParseXml(), CIccMpeXmlReflectanceObserver::ParseXml(), and CIccTagXmlColorantOrder::ParseXml().
ParseArray() [2/2]
template<class T , icTagTypeSignature Tsig> bool CIccXmlArrayType< T, Tsig >::ParseArray (xmlNode * pNode)
{
  char scanType[2] = {0};
  scanType[0] = (Tsig == icSigFloatArrayType ? 'f' : 'n');
  scanType[1] = 0;
  icUInt32Number n = icXmlNodeCount(pNode, scanType);
  if (n) {
    if (!SetSize(n))
      return false;
    return ParseArray(m_pBuf, m_nSize, pNode);
  }
  for ( ;pNode && pNode->type!= XML_TEXT_NODE; pNode=pNode->next);
  if (!pNode || !pNode->content)
    return false;
  n = ParseTextCount((const char*)pNode->content);
  if (!n || !SetSize(n))
    return false;
  return ParseArray(m_pBuf, m_nSize, pNode);
}
References icXmlNodeCount(), CIccXmlArrayType< T, Tsig >::m_nSize, CIccXmlArrayType< T, Tsig >::m_pBuf, CIccXmlArrayType< T, Tsig >::ParseTextCount(), and CIccXmlArrayType< T, Tsig >::SetSize().
Referenced by icCLutFromXml(), CIccTagXmlCurve::ParseXml(), CIccFormulaCurveSegmentXml::ParseXml(), CIccSampledCurveSegmentXml::ParseXml(), CIccSinglSampledeCurveXml::ParseXml(), CIccXmlToneMapFunc::ParseXml(), CIccTagXmlNamedColor2::ParseXml(), CIccTagXmlFixedNum< T, Tsig >::ParseXml(), CIccTagXmlParametricCurve::ParseXml(), and CIccTagXmlGamutBoundaryDesc::ParseXml().
ParseText()
template<class T , icTagTypeSignature Tsig> icUInt32Number CIccXmlArrayType< T, Tsig >::ParseText (T * buf, icUInt32Number nBufSize, const char * szText) static
{
  icUInt32Number n = 0, b = 0;
  bool bInNum = false;
  char num[256] = {0};
  while (*szText && n<nSize) {
      if (icIsNumChar(*szText)) {
      if (!bInNum) {
        bInNum = true;
        b=0;
      }
      num[b] = *szText;
      if (b+2<sizeof(num))
        b++;
    }
    else if (bInNum) {
      num[b] = 0;
      if (!strncmp(num, "nan", 3) || !strncmp(num, "-nan", 4)) {
        pBuf[n] = (T)nanf(num);
      }
      else {
        pBuf[n] = (T)atof(num);
      }
      n++;
      bInNum = false;
    }
    szText++;
  }
  if (bInNum) {
    num[b] = 0;
    if (!strncmp(num, "nan", 3) || !strncmp(num, "-nan", 4)) {
      pBuf[n] = (T)nanf(num);
    }
    else {
      pBuf[n] = (T)atof(num);
    }
    n++;
  }
  return n;
}
References icIsNumChar().
Referenced by CIccXmlArrayType< T, Tsig >::ParseArray(), CIccXmlArrayType< T, Tsig >::ParseTextArray(), and CIccXmlArrayType< T, Tsig >::ParseTextArrayNum().
ParseTextArray() [1/2]
template<class T , icTagTypeSignature Tsig> bool CIccXmlArrayType< T, Tsig >::ParseTextArray (const char * szText)
{
  icUInt32Number n = ParseTextCount(szText);
  if (n) {
    if (!SetSize(n))
      return false;
    return ParseText(m_pBuf, m_nSize, szText)==m_nSize;
  }
  return false;
}
References CIccXmlArrayType< T, Tsig >::m_nSize, CIccXmlArrayType< T, Tsig >::m_pBuf, CIccXmlArrayType< T, Tsig >::ParseText(), CIccXmlArrayType< T, Tsig >::ParseTextCount(), and CIccXmlArrayType< T, Tsig >::SetSize().
Referenced by CIccTagXmlSpectralViewingConditions::ParseXml().
ParseTextArray() [2/2]
template<class T , icTagTypeSignature Tsig> bool CIccXmlArrayType< T, Tsig >::ParseTextArray (xmlNode * pNode)
{
  if (pNode->children && pNode->children->type==XML_TEXT_NODE) {
    return ParseTextArray((const char*)pNode->children->content);
  }
  return false;
}
Referenced by CIccTagXmlSparseMatrixArray::ParseXml().
ParseTextArrayNum()
template<class T , icTagTypeSignature Tsig> bool CIccXmlArrayType< T, Tsig >::ParseTextArrayNum (const char * szText, icUInt32Number num, std::string & parseStr)
{
  icUInt32Number n = ParseTextCountNum(szText, num, parseStr);
  if (n) {
    if (!SetSize(n))
      return false;
    return ParseText(m_pBuf, m_nSize, szText)==m_nSize;
  }
  return false;
}
References CIccXmlArrayType< T, Tsig >::m_nSize, CIccXmlArrayType< T, Tsig >::m_pBuf, CIccXmlArrayType< T, Tsig >::ParseText(), CIccXmlArrayType< T, Tsig >::ParseTextCountNum(), and CIccXmlArrayType< T, Tsig >::SetSize().
Referenced by icCLutFromXml(), CIccTagXmlCurve::ParseXml(), CIccSampledCurveSegmentXml::ParseXml(), and CIccSinglSampledeCurveXml::ParseXml().
ParseTextCount()
template<class T , icTagTypeSignature Tsig> icUInt32Number CIccXmlArrayType< T, Tsig >::ParseTextCount (const char * szText) static
{
  icUInt32Number n = 0;
  bool bInNum = false;
  while (*szText) {
    if (icIsNumChar(*szText)) {
      if (!bInNum) {
        bInNum = true;
      }
    }
    else if (bInNum && !strncmp(szText, "#QNAN", 5)) { //Handle 1.#QNAN000 (non a number)
      szText+=4;
    }
    else if (bInNum) {
      n++;
      bInNum = false;
    }
    szText++;
  }
  if (bInNum) {
    n++;
  }
  return n;
}
References icIsNumChar().
Referenced by CIccXmlArrayType< T, Tsig >::ParseArray(), CIccXmlArrayType< T, Tsig >::ParseArray(), and CIccXmlArrayType< T, Tsig >::ParseTextArray().
ParseTextCountNum()
template<class T , icTagTypeSignature Tsig> icUInt32Number CIccXmlArrayType< T, Tsig >::ParseTextCountNum (const char * szText, icUInt32Number num, std::string & parseStr) static
{
  icUInt32Number n = 0;
  bool bInNum = false;
  //icUInt32Number count = 1;
  //while (*szText) {
  for (icUInt32Number i=0; i<num; i++) {
      if (icIsNumChar(*szText)) {
          if (!bInNum) {
              bInNum = true;
          }
      }
    else if (bInNum && !strncmp(szText, "#QNAN", 5)) { //Handle 1.#QNAN000 (non a number)
      i+=4;
      szText+=4;
    }
      // an invalid character is encountered (not digit and not space)
      else if (!isspace(*szText) && i <= num ){
          char line[100];
          sprintf(line, "Data '%c' in position %d is not a number. ", *szText, i);
          parseStr += line;
          return false;
      }
      else if (bInNum) { //char is a space
          n++;
          bInNum = false;
      }
      szText++;
      //count++;
  }
  if (bInNum) {
    n++;
  }
  return n;
}
References icIsNumChar().
Referenced by CIccXmlArrayType< T, Tsig >::ParseTextArrayNum().
SetSize()
template<class T , icTagTypeSignature Tsig> bool CIccXmlArrayType< T, Tsig >::SetSize (icUInt32Number nSize)
{
  if (m_pBuf) {
    free(m_pBuf);
  }
  m_pBuf = (T*)malloc(nSize * sizeof(T));
  if (!m_pBuf) {
    m_nSize = 0;
    return false;
  }
  m_nSize = nSize;
  return true;
}
References CIccXmlArrayType< T, Tsig >::m_nSize, and CIccXmlArrayType< T, Tsig >::m_pBuf.
Referenced by icXmlParseTextString(), CIccXmlArrayType< T, Tsig >::ParseArray(), CIccXmlArrayType< T, Tsig >::ParseTextArray(), CIccXmlArrayType< T, Tsig >::ParseTextArrayNum(), CIccTagXmlZipUtf8Text::ParseXml(), and CIccTagXmlZipXml::ParseXml().
Field Documentation
m_nSize
template<class T , icTagTypeSignature Tsig> icUInt32Number CIccXmlArrayType< T, Tsig >::m_nSize protected
Referenced by CIccXmlArrayType< T, Tsig >::CIccXmlArrayType(), CIccXmlArrayType< T, Tsig >::GetSize(), CIccXmlArrayType< T, Tsig >::ParseArray(), CIccXmlArrayType< T, Tsig >::ParseTextArray(), CIccXmlArrayType< T, Tsig >::ParseTextArrayNum(), and CIccXmlArrayType< T, Tsig >::SetSize().
m_pBuf
template<class T , icTagTypeSignature Tsig> T* CIccXmlArrayType< T, Tsig >::m_pBuf protected
Referenced by CIccXmlArrayType< T, Tsig >::CIccXmlArrayType(), CIccXmlArrayType< T, Tsig >::~CIccXmlArrayType(), CIccXmlArrayType< T, Tsig >::GetBuf(), CIccXmlArrayType< T, Tsig >::ParseArray(), CIccXmlArrayType< T, Tsig >::ParseTextArray(), CIccXmlArrayType< T, Tsig >::ParseTextArrayNum(), and CIccXmlArrayType< T, Tsig >::SetSize().
The documentation for this class was generated from the following files:
IccXML/IccLibXML/IccTagXml.h
IccXML/IccLibXML/IccUtilXml.h
IccXML/IccLibXML/IccUtilXml.cpp