iccDEV: CIccTagChromaticity Class Reference
CIccTagChromaticity Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagChromaticity (const CIccTagChromaticity &ITCh)
CIccTagChromaticity (int nSize=3)
virtual ~CIccTagChromaticity ()
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
virtual const icChar * GetClassName () const
virtual IIccExtensionTag * GetExtension ()
icUInt32Number GetSize () const
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
icChromaticityNumber * Getxy (icUInt32Number index)
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
CIccTagChromaticity & operator= (const CIccTagChromaticity &ChromTag)
icChromaticityNumber & operator[] (icUInt32Number index)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
bool SetSize (icUInt16Number nSize, bool bZeroNew=true)
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt16Number m_nColorantType
icUInt32Number m_nReserved
Protected Attributes
icUInt16Number m_nChannels
icChromaticityNumber * m_xy
Detailed Description
Class: CIccTagChromaticity
Purpose: the chromaticity tag - xy chromaticity values for each channel
Constructor & Destructor Documentation
CIccTagChromaticity() [1/2]
CIccTagChromaticity::CIccTagChromaticity (int nSize = 3)
Name: CIccTagChromaticity::CIccTagChromaticity
Purpose: Constructor
Args: nSize = number of xy entries
{
  m_nChannels = nSize;
  if (m_nChannels <3)
    m_nChannels = 3;
  m_xy = (icChromaticityNumber*)calloc(nSize, sizeof(icChromaticityNumber));
}
References m_nChannels, and m_xy.
CIccTagChromaticity() [2/2]
CIccTagChromaticity::CIccTagChromaticity (const CIccTagChromaticity & ITCh)
Name: CIccTagChromaticity::CIccTagChromaticity
Purpose: Copy Constructor
Args: ITCh = The CIccTagChromaticity object to be copied
{
  m_nChannels = ITCh.m_nChannels;
  m_xy = (icChromaticityNumber*)calloc(m_nChannels, sizeof(icChromaticityNumber));
  memcpy(m_xy, ITCh.m_xy, sizeof(icChromaticityNumber)*m_nChannels);
}
References m_nChannels, and m_xy.
Referenced by NewCopy().
~CIccTagChromaticity()
CIccTagChromaticity::~CIccTagChromaticity () virtual
Name: CIccTagChromaticity::~CIccTagChromaticity
Purpose: Destructor
{
  if (m_xy)
    free(m_xy);
}
References m_xy.
Member Function Documentation
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagChromaticity::Describe (std::string & sDescription, int nVerboseness) virtual
Name: CIccTagChromaticity::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  icChar buf[128];
  CIccInfo Fmt;
  icUInt32Number i;
  //sDescription.reserve(sDescription.size() + m_nChannels*79);
  sprintf(buf, "Number of Channels : %u\n", m_nChannels);
  sDescription += buf;
  sprintf(buf, "Colorant Encoding : %s\n", Fmt.GetColorantEncoding((icColorantEncoding)m_nColorantType));
  sDescription += buf;
  for (i=0; i<m_nChannels; i++) {
    sprintf(buf, "value[%u]: x=%.3lf, y=%.3lf\n", i, icUFtoD(m_xy[i].x), icUFtoD(m_xy[i].y));
    sDescription += buf;
  }
}
References CIccInfo::GetColorantEncoding(), icUFtoD(), m_nChannels, m_nColorantType, m_xy, icChromaticityNumber::x, and icChromaticityNumber::y.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
GetClassName()
virtual const icChar * CIccTagChromaticity::GetClassName () const inline virtual
Reimplemented from CIccTag.
Reimplemented in CIccTagXmlChromaticity.
{ return "CIccTagChromaticity"; }
GetExtension()
virtual IIccExtensionTag * CIccTag::GetExtension () inline virtual inherited
Reimplemented in CIccTagXmlUnknown, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, CIccTagXmlSignature, CIccTagXmlNamedColor2, CIccTagXmlXYZ, CIccTagXmlChromaticity, CIccTagXmlCicp, CIccTagXmlSparseMatrixArray, CIccTagXmlFixedNum< T, Tsig >, CIccTagXmlNum< T, A, Tsig >, CIccTagXmlFloatNum< T, A, Tsig >, CIccTagXmlMeasurement, CIccTagXmlMultiLocalizedUnicode, CIccTagXmlTagData, CIccTagXmlDateTime, CIccTagXmlColorantOrder, CIccTagXmlColorantTable, CIccTagXmlViewingConditions, CIccTagXmlSpectralDataInfo, CIccTagXmlSpectralViewingConditions, CIccTagXmlProfileSeqDesc, CIccTagXmlResponseCurveSet16, CIccTagXmlCurve, CIccTagXmlParametricCurve, CIccTagXmlSegmentedCurve, CIccTagXmlLutAtoB, CIccTagXmlLutBtoA, CIccTagXmlLut8, CIccTagXmlLut16, CIccTagXmlMultiProcessElement, CIccTagXmlProfileSequenceId, CIccTagXmlDict, CIccTagXmlStruct, CIccTagXmlArray, CIccTagXmlGamutBoundaryDesc, CIccTagXmlEmbeddedHeightImage, CIccTagXmlEmbeddedNormalImage, and CIccTagXmlEmbeddedProfile.
{return NULL;}
Referenced by icCurvesFromXml(), icCurvesToXml(), icProfDescToXml(), icXmlParseProfDesc(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeXmlTintArray::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
GetSize()
icUInt32Number CIccTagChromaticity::GetSize () const inline
{ return m_nChannels; }
References m_nChannels.
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagChromaticity::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigChromaticityType; }
References icSigChromaticityType.
Referenced by Write().
Getxy()
icChromaticityNumber * CIccTagChromaticity::Getxy (icUInt32Number index) inline
{return &m_xy[index];}
References m_xy.
IsArrayType()
virtual bool CIccTagChromaticity::IsArrayType () inline virtual
Reimplemented from CIccTag.
{ return m_nChannels > 1; }
References m_nChannels.
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
virtual CIccTag * CIccTagChromaticity::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
{return new CIccTagChromaticity(*this);}
References CIccTagChromaticity().
operator=()
CIccTagChromaticity & CIccTagChromaticity::operator= (const CIccTagChromaticity & ChromTag)
Name: CIccTagChromaticity::operator=
Purpose: Copy Operator
Args: ChromTag = The CIccTagChromaticity object to be copied
{
  if (&ChromTag == this)
    return *this;
  m_nChannels = ChromTag.m_nChannels;
  if (m_xy)
    free(m_xy);
  m_xy = (icChromaticityNumber*)calloc(m_nChannels, sizeof(icChromaticityNumber));
  memcpy(m_xy, ChromTag.m_xy, sizeof(icChromaticityNumber)*m_nChannels);
  return *this;
}
References m_nChannels, and m_xy.
operator[]()
icChromaticityNumber & CIccTagChromaticity::operator[] (icUInt32Number index) inline
{return m_xy[index];}
References m_xy.
Read() [1/2]
bool CIccTagChromaticity::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagChromaticity::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  icUInt16Number nChannels;
  if (sizeof(icTagTypeSignature) +
      sizeof(icUInt32Number) +
      sizeof(icUInt32Number) +
      sizeof(icChromaticityNumber) > size)
    return false;
  if (!pIO) {
    return false;
  }
  if (!pIO->Read32(&sig))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  if (!pIO->Read16(&nChannels) ||
      !pIO->Read16(&m_nColorantType))
    return false;
  icUInt32Number nNum = (size-3*sizeof(icUInt32Number)) / sizeof(icChromaticityNumber);
  icUInt32Number nNum32 = (nNum*sizeof(icChromaticityNumber)) / sizeof(icU16Fixed16Number);
  if (nNum < nChannels)
    return false;
  // SetSize casts from icUInt32Number down to icUInt16Number. Check for overflow
  if (nNum > (icUInt16Number)nNum)
    return false;
  if (!SetSize((icUInt16Number)nNum))
    return false;
  if (pIO->Read32(&m_xy[0], nNum32) != (icInt32Number)nNum32 )
    return false;
  return true;
}
References m_nColorantType, CIccTag::m_nReserved, m_xy, CIccIO::Read16(), CIccIO::Read32(), and SetSize().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
SetSize()
bool CIccTagChromaticity::SetSize (icUInt16Number nSize, bool bZeroNew = true)
Name: CIccTagChromaticity::SetSize
Purpose: Sets the size of the xy chromaticity array.
Args: nSize - number of xy entries, bZeroNew - flag to zero newly formed values
{
  if (m_nChannels == nSize)
    return true;
  m_xy = (icChromaticityNumber*)icRealloc(m_xy, nSize*sizeof(icChromaticityNumber));
  if (!m_xy) {
    m_nChannels = 0;
    return false;
  }
  if (bZeroNew && nSize > m_nChannels) {
    memset(&m_xy[m_nChannels], 0, (nSize - m_nChannels)*sizeof(icChromaticityNumber));
  }
  m_nChannels = nSize;
  return true;
}
References icRealloc(), m_nChannels, and m_xy.
Referenced by CIccTagXmlChromaticity::ParseXml(), and Read().
Validate()
icValidateStatus CIccTagChromaticity::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagChromaticity::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  if (m_nColorantType) {
    if (m_nChannels!=3) {
      sReport += icMsgValidateCriticalError;
      sReport += sSigPathName;
      sReport += " - Number of device channels must be three.\n";
      rv = icMaxStatus(rv, icValidateCriticalError);
    }
    switch(m_nColorantType) {
      case icColorantITU:
        {
          if ( (m_xy[0].x != icDtoUF((icFloatNumber)0.640)) || (m_xy[0].y != icDtoUF((icFloatNumber)0.330)) ||
               (m_xy[1].x != icDtoUF((icFloatNumber)0.300)) || (m_xy[1].y != icDtoUF((icFloatNumber)0.600)) ||
               (m_xy[2].x != icDtoUF((icFloatNumber)0.150)) || (m_xy[2].y != icDtoUF((icFloatNumber)0.060)) ) {
                sReport += icMsgValidateNonCompliant;
                sReport += sSigPathName;
                sReport += " - Chromaticity data does not match specification.\n";
                rv = icMaxStatus(rv, icValidateNonCompliant);
              }
          break;
        }
      case icColorantSMPTE:
        {
          if ( (m_xy[0].x != icDtoUF((icFloatNumber)0.630)) || (m_xy[0].y != icDtoUF((icFloatNumber)0.340)) ||
               (m_xy[1].x != icDtoUF((icFloatNumber)0.310)) || (m_xy[1].y != icDtoUF((icFloatNumber)0.595)) ||
               (m_xy[2].x != icDtoUF((icFloatNumber)0.155)) || (m_xy[2].y != icDtoUF((icFloatNumber)0.070)) ) {
              sReport += icMsgValidateNonCompliant;
              sReport += sSigPathName;
              sReport += " - Chromaticity data does not match specification.\n";
              rv = icMaxStatus(rv, icValidateNonCompliant);
            }
            break;
        }
      case icColorantEBU:
        {
          if ( (m_xy[0].x != icDtoUF((icFloatNumber)0.64)) || (m_xy[0].y != icDtoUF((icFloatNumber)0.33)) ||
               (m_xy[1].x != icDtoUF((icFloatNumber)0.29)) || (m_xy[1].y != icDtoUF((icFloatNumber)0.60)) ||
               (m_xy[2].x != icDtoUF((icFloatNumber)0.15)) || (m_xy[2].y != icDtoUF((icFloatNumber)0.06)) ) {
              sReport += icMsgValidateNonCompliant;
              sReport += sSigPathName;
              sReport += " - Chromaticity data does not match specification.\n";
              rv = icMaxStatus(rv, icValidateNonCompliant);
            }
            break;
        }
      case icColorantP22:
        {
          if ( (m_xy[0].x != icDtoUF((icFloatNumber)0.625)) || (m_xy[0].y != icDtoUF((icFloatNumber)0.340)) ||
               (m_xy[1].x != icDtoUF((icFloatNumber)0.280)) || (m_xy[1].y != icDtoUF((icFloatNumber)0.605)) ||
               (m_xy[2].x != icDtoUF((icFloatNumber)0.155)) || (m_xy[2].y != icDtoUF((icFloatNumber)0.070)) ) {
              sReport += icMsgValidateNonCompliant;
              sReport += sSigPathName;
              sReport += " - Chromaticity data does not match specification.\n";
              rv = icMaxStatus(rv, icValidateNonCompliant);
            }
            break;
        }
      default:
        {
          sReport += icMsgValidateNonCompliant;
          sReport += sSigPathName;
          sReport += " - Invalid colorant type encoding.\n";
          rv = icMaxStatus(rv, icValidateNonCompliant);
        }
    }
  }
  return rv;
}
References CIccInfo::GetSigPathName(), icColorantEBU, icColorantITU, icColorantP22, icColorantSMPTE, icDtoUF(), icMaxStatus(), icMsgValidateCriticalError, icMsgValidateNonCompliant, icValidateCriticalError, icValidateNonCompliant, m_nChannels, m_nColorantType, m_xy, CIccTag::Validate(), icChromaticityNumber::x, and icChromaticityNumber::y.
Write()
bool CIccTagChromaticity::Write (CIccIO * pIO) virtual
Name: CIccTagChromaticity::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  if (!pIO)
   return false;
  if (!pIO->Write32(&sig))
   return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  if (!pIO->Write16(&m_nChannels))
    return false;
  if (!pIO->Write16(&m_nColorantType))
    return false;
  icUInt32Number nNum32 = m_nChannels*sizeof(icChromaticityNumber)/sizeof(icU16Fixed16Number);
  if (pIO->Write32(&m_xy[0], nNum32) != (icInt32Number)nNum32)
    return false;
  return true;
}
References GetType(), m_nChannels, m_nColorantType, CIccTag::m_nReserved, m_xy, CIccIO::Write16(), and CIccIO::Write32().
Field Documentation
m_nChannels
icUInt16Number CIccTagChromaticity::m_nChannels protected
Referenced by CIccTagChromaticity(), CIccTagChromaticity(), Describe(), GetSize(), IsArrayType(), operator=(), SetSize(), CIccTagXmlChromaticity::ToXml(), Validate(), and Write().
m_nColorantType
icUInt16Number CIccTagChromaticity::m_nColorantType
Referenced by Describe(), CIccTagXmlChromaticity::ParseXml(), Read(), CIccTagXmlChromaticity::ToXml(), Validate(), and Write().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_xy
icChromaticityNumber* CIccTagChromaticity::m_xy protected
Referenced by CIccTagChromaticity(), CIccTagChromaticity(), ~CIccTagChromaticity(), Describe(), Getxy(), operator=(), operator[](), CIccTagXmlChromaticity::ParseXml(), Read(), SetSize(), CIccTagXmlChromaticity::ToXml(), Validate(), and Write().
The documentation for this class was generated from the following files:
IccProfLib/IccTagBasic.h
IccProfLib/IccTagBasic.cpp