iccDEV: CIccArrayUnknown Class Reference
CIccArrayUnknown Class Reference
#include <IccArrayBasic.h>
Public Member Functions
CIccArrayUnknown (CIccTagArray *pTagArray=NULL, icArraySignature sigArray=(icArraySignature) 0)
virtual ~CIccArrayUnknown ()
virtual void Describe (std::string &sDescription, int nVerboseness) const
virtual const icChar * GetClassName () const
CIccTagArray * GetTagArray ()
virtual IIccArray * NewCopy (CIccTagArray *pTagArray) const
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
Protected Attributes
CIccTagArray * m_pTag
CIccTagArray * m_pTagArray
icArraySignature m_sig
Detailed Description
Class: CIccArrayUnknown
Purpose: The Unknown array handler
Constructor & Destructor Documentation
CIccArrayUnknown()
CIccArrayUnknown::CIccArrayUnknown (CIccTagArray * pTagArray = NULL, icArraySignature sigArray = (icArraySignature)0)
{
  m_pTag = pTagArray;
  m_sig = sigArray;
}
References m_pTag, and m_sig.
Referenced by CIccBasicArrayFactory::CreateArray(), and NewCopy().
~CIccArrayUnknown()
CIccArrayUnknown::~CIccArrayUnknown () virtual
{
}
Member Function Documentation
Describe()
void CIccArrayUnknown::Describe (std::string & sDescription, int nVerboseness) const virtual
Reimplemented from IIccArray.
Reimplemented in CIccArrayColorantInfo, and CIccArrayNamedColor.
{
    sDescription += "\nCIccArrayUnknown::Describe()\n";
}
GetClassName()
virtual const icChar * CIccArrayUnknown::GetClassName () const inline virtual
Implements IIccArray.
Reimplemented in CIccArrayColorantInfo, and CIccArrayNamedColor.
{ return "CIccArrayUnknown"; }
GetTagArray()
CIccTagArray * IIccArray::GetTagArray () inline inherited
{ return m_pTagArray; }
References IIccArray::m_pTagArray.
NewCopy()
IIccArray * CIccArrayUnknown::NewCopy (CIccTagArray * pTagArray) const virtual
Implements IIccArray.
Reimplemented in CIccArrayColorantInfo, and CIccArrayNamedColor.
{
  CIccArrayUnknown *rv = new CIccArrayUnknown(pTagArray);
  return rv;
}
References CIccArrayUnknown().
Validate()
icValidateStatus CIccArrayUnknown::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Implements IIccArray.
Reimplemented in CIccArrayColorantInfo, and CIccArrayNamedColor.
{
  icValidateStatus rv = icValidateOK;
  if (m_pTag) {
    icUInt32Number i;
    sReport += "Unknown tag array type!\n";
    for (i=0; i<m_pTag->GetSize(); i++) {
      CIccTag *pTag = m_pTag->GetIndex(i);
      if (!pTag) {
        rv = icMaxStatus(rv, icValidateWarning);
        char buf[80];
        sprintf(buf, "Tag at index %d is NULL\n", i);
        sReport += buf;
      }
      else {
        rv = icMaxStatus(rv, pTag->Validate(sigPath+icGetSigPath(pTag->GetType()), sReport, pProfile));
      }
    }
  }
  else {
    sReport += "Array Handler not connected to CIccTagArray object!";
    rv = icValidateWarning;
  }
  return rv;
}
References CIccTagArray::GetIndex(), CIccTagArray::GetSize(), CIccTag::GetType(), icGetSigPath(), icMaxStatus(), icValidateOK, icValidateWarning, m_pTag, and CIccTag::Validate().
Field Documentation
m_pTag
CIccTagArray* CIccArrayUnknown::m_pTag protected
Referenced by CIccArrayColorantInfo::CIccArrayColorantInfo(), CIccArrayNamedColor::CIccArrayNamedColor(), CIccArrayUnknown(), CIccArrayNamedColor::Begin(), CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), Validate(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
m_pTagArray
CIccTagArray* IIccArray::m_pTagArray protected inherited
Referenced by IIccArray::GetTagArray().
m_sig
icArraySignature CIccArrayUnknown::m_sig protected
Referenced by CIccArrayColorantInfo::CIccArrayColorantInfo(), CIccArrayNamedColor::CIccArrayNamedColor(), and CIccArrayUnknown().
The documentation for this class was generated from the following files:
IccProfLib/IccArrayBasic.h
IccProfLib/IccArrayBasic.cpp