iccDEV: CIccTagTextDescription Class Reference
CIccTagTextDescription Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagTextDescription ()
CIccTagTextDescription (const CIccTagTextDescription &ITTD)
virtual ~CIccTagTextDescription ()
icUInt32Number Capacity () const
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
icChar * GetBuffer (icUInt32Number nSize)
virtual const icChar * GetClassName () const
virtual IIccExtensionTag * GetExtension ()
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
const icChar * GetText () const
virtual icTagTypeSignature GetType () const
icUInt16Number * GetUnicodeBuffer (icUInt32Number nSize)
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
CIccTagTextDescription & operator= (const CIccTagTextDescription &TextDescTag)
const icChar * operator= (const icChar *szText)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
void Release ()
void ReleaseUnicode ()
void SetText (const icChar *szText)
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
Protected Attributes
bool m_bInvalidScript
icUInt32Number m_nASCIISize
icUInt16Number m_nScriptCode
icUInt8Number m_nScriptSize
icUInt32Number m_nUnicodeLanguageCode
icUInt32Number m_nUnicodeSize
icUInt8Number m_szScriptText [67]
icChar * m_szText
icUInt16Number * m_uzUnicodeText
Detailed Description
Class: CIccTagTextDescription()
Purpose: The textType ICC tag
Constructor & Destructor Documentation
CIccTagTextDescription() [1/2]
CIccTagTextDescription::CIccTagTextDescription ()
Name: CIccTagTextDescription::CIccTagTextDescription
Purpose: Constructor
{
  m_szText = (icChar*)malloc(1);
  m_szText[0] = '\0';
  m_nASCIISize = 1;
  m_uzUnicodeText = (icUInt16Number*)malloc(sizeof(icUInt16Number));
  m_uzUnicodeText[0] = 0;
  m_nUnicodeSize = 1;
  m_nUnicodeLanguageCode = 0;
  m_nScriptSize = 0;
  m_nScriptCode = 0;
  memset(m_szScriptText, 0, sizeof(m_szScriptText));
  m_bInvalidScript = false;
}
References m_bInvalidScript, m_nASCIISize, m_nScriptCode, m_nScriptSize, m_nUnicodeLanguageCode, m_nUnicodeSize, m_szScriptText, m_szText, and m_uzUnicodeText.
Referenced by CIccTagXmlTextDescription::CIccTagXmlTextDescription().
CIccTagTextDescription() [2/2]
CIccTagTextDescription::CIccTagTextDescription (const CIccTagTextDescription & ITTD)
Name: CIccTagTextDescription::CIccTagTextDescription
Purpose: Copy Constructor
Args: ITTD = The CIccTagTextDescription object to be copied
{
  m_nASCIISize = ITTD.m_nASCIISize;
  m_nUnicodeSize = ITTD.m_nUnicodeSize;
  m_nUnicodeLanguageCode = ITTD.m_nUnicodeLanguageCode;
  m_nScriptSize = ITTD.m_nScriptSize;
  m_nScriptCode = ITTD.m_nScriptCode;
  if (m_nASCIISize) {
    m_szText = (icChar*)malloc(m_nASCIISize * sizeof(icChar));
    memcpy(m_szText, ITTD.m_szText, m_nASCIISize*sizeof(icChar));
  }
  else {
    m_nASCIISize = 1;
    m_szText = (icChar*)calloc(m_nASCIISize, sizeof(icChar));
    m_szText[0] = '\0';
  }
  if (m_nUnicodeSize) {
    m_uzUnicodeText = (icUInt16Number*)malloc((m_nUnicodeSize) * sizeof(icUInt16Number));
    memcpy(m_uzUnicodeText, ITTD.m_uzUnicodeText, m_nUnicodeSize*sizeof(icUInt16Number));
  }
  else {
    m_nUnicodeSize = 1;
    m_uzUnicodeText = (icUInt16Number*)calloc(m_nUnicodeSize, sizeof(icUInt16Number));
    m_uzUnicodeText[0] = 0;
  }
  memcpy(m_szScriptText, ITTD.m_szScriptText, sizeof(m_szScriptText));
  m_bInvalidScript = ITTD.m_bInvalidScript;
}
References m_bInvalidScript, m_nASCIISize, m_nScriptCode, m_nScriptSize, m_nUnicodeLanguageCode, m_nUnicodeSize, m_szScriptText, m_szText, and m_uzUnicodeText.
Referenced by CIccTagXmlTextDescription::CIccTagXmlTextDescription(), and NewCopy().
~CIccTagTextDescription()
CIccTagTextDescription::~CIccTagTextDescription () virtual
Name: CIccTagTextDescription::~CIccTagTextDescription
Purpose: Destructor
{
  free(m_szText);
  free(m_uzUnicodeText);
}
References m_szText, and m_uzUnicodeText.
Member Function Documentation
Capacity()
icUInt32Number CIccTagTextDescription::Capacity () const inline
{ return m_nASCIISize; }
References m_nASCIISize.
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagTextDescription::Describe (std::string & sDescription, int nVerboseness) virtual
Name: CIccTagTextDescription::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  sDescription += "TextDescription Length = ";
  if (m_szText && *m_szText) {
    char buf[40];
    sprintf(buf, "%zu bytes\n", strlen(m_szText));
    sDescription += buf;
  }
  else
    sDescription += "0 (NULL)";
  if (nVerboseness > 25) {
    sDescription += "\"";
    if (m_szText && *m_szText) {
      if ((nVerboseness > 50) || (strlen(m_szText) < BRIEF_STRING_SIZE)) {
        // output entire string if short or doing verbose
         sDescription += m_szText;
      }
      else {
        // copy just first part of string to keep nVerboseness under control
        char buf[BRIEF_STRING_SIZE+1];
        strncpy(buf, m_szText, BRIEF_STRING_SIZE);
        buf[BRIEF_STRING_SIZE] = '\0'; // ensure NULL termination
        sDescription += buf;
        sDescription += "\n... <!truncated!>";
      }
    }
    sDescription += "\"\n";
  }
}
References m_szText.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
GetBuffer()
icChar * CIccTagTextDescription::GetBuffer (icUInt32Number nSize)
Name: CIccTagTextDescription::GetBuffer
Purpose: This function allocates room and returns pointer to data buffer to put string into
Args: nSize = Requested size of data buffer.
Return:
{
  if (m_nASCIISize < nSize) {
    m_szText = (icChar*)icRealloc(m_szText, nSize+1);
    m_szText[nSize] = '\0';
    m_nASCIISize = nSize;
  }
  return m_szText;
}
References icRealloc(), m_nASCIISize, and m_szText.
Referenced by CIccTagXmlTextDescription::ParseXml(), Read(), and SetText().
GetClassName()
virtual const icChar * CIccTagTextDescription::GetClassName () const inline virtual
Reimplemented from CIccTag.
Reimplemented in CIccTagXmlTextDescription.
{ return "CIccTagTextDescription"; }
GetExtension()
virtual IIccExtensionTag * CIccTag::GetExtension () inline virtual inherited
Reimplemented in CIccTagXmlUnknown, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, CIccTagXmlSignature, CIccTagXmlNamedColor2, CIccTagXmlXYZ, CIccTagXmlChromaticity, CIccTagXmlCicp, CIccTagXmlSparseMatrixArray, CIccTagXmlFixedNum< T, Tsig >, CIccTagXmlNum< T, A, Tsig >, CIccTagXmlFloatNum< T, A, Tsig >, CIccTagXmlMeasurement, CIccTagXmlMultiLocalizedUnicode, CIccTagXmlTagData, CIccTagXmlDateTime, CIccTagXmlColorantOrder, CIccTagXmlColorantTable, CIccTagXmlViewingConditions, CIccTagXmlSpectralDataInfo, CIccTagXmlSpectralViewingConditions, CIccTagXmlProfileSeqDesc, CIccTagXmlResponseCurveSet16, CIccTagXmlCurve, CIccTagXmlParametricCurve, CIccTagXmlSegmentedCurve, CIccTagXmlLutAtoB, CIccTagXmlLutBtoA, CIccTagXmlLut8, CIccTagXmlLut16, CIccTagXmlMultiProcessElement, CIccTagXmlProfileSequenceId, CIccTagXmlDict, CIccTagXmlStruct, CIccTagXmlArray, CIccTagXmlGamutBoundaryDesc, CIccTagXmlEmbeddedHeightImage, CIccTagXmlEmbeddedNormalImage, and CIccTagXmlEmbeddedProfile.
{return NULL;}
Referenced by icCurvesFromXml(), icCurvesToXml(), icProfDescToXml(), icXmlParseProfDesc(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeXmlTintArray::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetText()
const icChar * CIccTagTextDescription::GetText () const inline
{ return m_szText; }
References m_szText.
Referenced by CIccProfileIdDesc::CIccProfileIdDesc(), icGetTagText(), and main().
GetType()
virtual icTagTypeSignature CIccTagTextDescription::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigTextDescriptionType; }
References icSigTextDescriptionType.
Referenced by Write().
GetUnicodeBuffer()
icUInt16Number * CIccTagTextDescription::GetUnicodeBuffer (icUInt32Number nSize)
Name: CIccTagTextDescription::GetUnicodeBuffer
Purpose: This function allocates room and returns pointer to data buffer to put string into
Args: nSize = Requested size of data buffer.
Return:
{
  if (m_nUnicodeSize < nSize) {
    m_uzUnicodeText = (icUInt16Number*)icRealloc(m_uzUnicodeText, (nSize+1)*sizeof(icUInt16Number));
    m_uzUnicodeText[nSize] = 0;
    m_nUnicodeSize = nSize;
  }
  return m_uzUnicodeText;
}
References icRealloc(), m_nUnicodeSize, and m_uzUnicodeText.
Referenced by CIccTagXmlTextDescription::ParseXml(), and Read().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
virtual CIccTag * CIccTagTextDescription::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
Reimplemented in CIccTagXmlTextDescription.
{return new CIccTagTextDescription(*this);}
References CIccTagTextDescription().
operator=() [1/2]
CIccTagTextDescription & CIccTagTextDescription::operator= (const CIccTagTextDescription & TextDescTag)
Name: CIccTagTextDescription::operator=
Purpose: Copy Operator
Args: TextDescTag = The CIccTagTextDescription object to be copied
{
  if (&TextDescTag == this)
    return *this;
  m_nASCIISize = TextDescTag.m_nASCIISize;
  m_nUnicodeSize = TextDescTag.m_nUnicodeSize;
  m_nUnicodeLanguageCode = TextDescTag.m_nUnicodeLanguageCode;
  m_nScriptSize = TextDescTag.m_nScriptSize;
  m_nScriptCode = TextDescTag.m_nScriptCode;
  if (m_szText)
    free(m_szText);
  if (m_nASCIISize) {
    m_szText = (icChar*)calloc(m_nASCIISize, sizeof(icChar));
    memcpy(m_szText, TextDescTag.m_szText, m_nASCIISize*sizeof(icChar));
  }
  else {
    m_nASCIISize = 1;
    m_szText = (icChar*)calloc(m_nASCIISize, sizeof(icChar));
    m_szText[0] = '\0';
  }
  if (m_uzUnicodeText)
    free(m_uzUnicodeText);
  if (m_nUnicodeSize) {
    m_uzUnicodeText = (icUInt16Number*)calloc(m_nUnicodeSize, sizeof(icUInt16Number));
    memcpy(m_uzUnicodeText, TextDescTag.m_uzUnicodeText, m_nUnicodeSize*sizeof(icUInt16Number));
  }
  else {
    m_nUnicodeSize = 1;
    m_uzUnicodeText = (icUInt16Number*)calloc(m_nUnicodeSize, sizeof(icUInt16Number));
    m_uzUnicodeText[0] = 0;
  }
  memcpy(m_szScriptText, TextDescTag.m_szScriptText, sizeof(m_szScriptText));
  m_bInvalidScript = TextDescTag.m_bInvalidScript;
  return *this;
}
References m_bInvalidScript, m_nASCIISize, m_nScriptCode, m_nScriptSize, m_nUnicodeLanguageCode, m_nUnicodeSize, m_szScriptText, m_szText, and m_uzUnicodeText.
Referenced by CDevLinkWriter::iterate().
operator=() [2/2]
const icChar * CIccTagTextDescription::operator= (const icChar * szText)
Name: CIccTagTextDescription::operator=
Purpose: Define assignment operator to associate text with tag.
Args: szText - zero terminated string to put in the tag
Return: A pointer to the string assigned to the tag.
{
  SetText(szText);
  return m_szText;
}
References m_szText, and SetText().
Read() [1/2]
bool CIccTagTextDescription::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagTextDescription::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  icUInt32Number nEnd;
  m_szText[0] = '\0';
  nEnd = pIO->Tell() + size;
  if (size<3*sizeof(icUInt32Number) || !pIO)
    return false;
  icUInt32Number nSize;
  if (!pIO->Read32(&sig) ||
      !pIO->Read32(&m_nReserved) ||
      !pIO->Read32(&nSize))
    return false;
  if (3*sizeof(icUInt32Number) + nSize > size)
    return false;
  icChar *pBuf = GetBuffer(nSize);
  if (nSize) {
    if (pIO->Read8(pBuf, nSize) != (icInt32Number)nSize) {
      return false;
    }
  }
  else
    m_szText[0] = '\0';
  Release();
  if (pIO->Tell() + 2 * sizeof(icUInt32Number) > nEnd)
    return false;
  if (!pIO->Read32(&m_nUnicodeLanguageCode) ||
      !pIO->Read32(&nSize))
    return false;
  // Calculations in GetUnicodeBuffer() can cause wrap-around error
  if (nSize == 0xFFFFFFFF)
    return false;
  icUInt16Number *pBuf16 = GetUnicodeBuffer(nSize);
  if (nSize) {
    if (pIO->Read16(pBuf16, nSize) != (icInt32Number)nSize) {
      return false;
    }
  }
  else
    pBuf16[0] = 0;
  ReleaseUnicode();
  if (pIO->Tell()+3 > (icInt32Number)nEnd)
    return false;
  if (!pIO->Read16(&m_nScriptCode) ||
      !pIO->Read8(&m_nScriptSize))
     return false;
  if (pIO->Tell() + m_nScriptSize> (icInt32Number)nEnd ||
      m_nScriptSize > sizeof(m_szScriptText))
    return false;
  int nScriptLen = pIO->Read8(m_szScriptText, 67);
  if (!nScriptLen)
    return false;
  if (nScriptLen<67) {
    memset(&m_szScriptText[0], 0, 67-nScriptLen);
    m_bInvalidScript = true;
  }
  return true;
}
References GetBuffer(), GetUnicodeBuffer(), m_bInvalidScript, CIccTag::m_nReserved, m_nScriptCode, m_nScriptSize, m_nUnicodeLanguageCode, m_szScriptText, m_szText, CIccIO::Read16(), CIccIO::Read32(), CIccIO::Read8(), Release(), ReleaseUnicode(), and CIccIO::Tell().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
Release()
void CIccTagTextDescription::Release ()
Name: CIccTagTextDescription::Release
Purpose: This will resize the buffer to fit the zero terminated string in the buffer.
{
  icUInt32Number nSize = (icUInt32Number)strlen(m_szText);
  if (nSize < m_nASCIISize-1) {
    m_szText=(icChar*)icRealloc(m_szText, nSize+1);
    m_nASCIISize = nSize+1;
  }
}
References icRealloc(), m_nASCIISize, and m_szText.
Referenced by CIccTagXmlTextDescription::ParseXml(), Read(), and SetText().
ReleaseUnicode()
void CIccTagTextDescription::ReleaseUnicode ()
Name: CIccTagTextDescription::ReleaseUnicode
Purpose: This will resize the buffer to fit the zero terminated string in the buffer.
{
  int i;
  for (i=0; m_uzUnicodeText[i]; i++);
  icUInt32Number nSize = i+1;
  if (nSize < m_nUnicodeSize-1) {
    m_uzUnicodeText=(icUInt16Number*)icRealloc(m_uzUnicodeText, (nSize+1)*sizeof(icUInt16Number));
    m_nUnicodeSize = nSize+1;
  }
}
References icRealloc(), m_nUnicodeSize, and m_uzUnicodeText.
Referenced by Read().
SetText()
void CIccTagTextDescription::SetText (const icChar * szText)
Name: CIccTagTextDescription::SetText
Purpose: Allows text data associated with the tag to be set.
Args: szText - zero terminated string to put in tag
{
  m_bInvalidScript = false;
  if (!szText) {
    SetText("");
    return;
  }
  icUInt32Number len=(icUInt32Number)strlen(szText) + 1;
  icChar *szBuf = GetBuffer(len);
  strcpy(szBuf, szText);
  Release();
}
References GetBuffer(), m_bInvalidScript, Release(), and SetText().
Referenced by operator=(), and SetText().
Validate()
icValidateStatus CIccTagTextDescription::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagTextDescription::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  if (m_nScriptSize>67) {
    sReport += icMsgValidateNonCompliant;
    sReport += sSigPathName;
    sReport += " - ScriptCode count must not be greater than 67.\n";
    rv =icMaxStatus(rv, icValidateNonCompliant);
  }
  if (m_bInvalidScript) {
    sReport += icMsgValidateNonCompliant;
    sReport += sSigPathName;
    sReport += " - ScriptCode must contain 67 bytes.\n";
    rv =icMaxStatus(rv, icValidateNonCompliant);
  }
  return rv;
}
References CIccInfo::GetSigPathName(), icMaxStatus(), icMsgValidateNonCompliant, icValidateNonCompliant, m_bInvalidScript, m_nScriptSize, and CIccTag::Validate().
Write()
bool CIccTagTextDescription::Write (CIccIO * pIO) virtual
Name: CIccTagTextDescription::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  icUInt32Number zero = 0;
  if (!pIO)
   return false;
  if (!pIO->Write32(&sig) ||
      !pIO->Write32(&m_nReserved) ||
      !pIO->Write32(&m_nASCIISize))
    return false;
  if (m_nASCIISize) {
    if (pIO->Write8(m_szText, m_nASCIISize) != (icInt32Number)m_nASCIISize)
      return false;
  }
  if (!pIO->Write32(&m_nUnicodeLanguageCode))
    return false;
  if (m_nUnicodeSize > 1) {
    if (!pIO->Write32(&m_nUnicodeSize) ||
        pIO->Write16(m_uzUnicodeText, m_nUnicodeSize) != (icInt32Number)m_nUnicodeSize)
      return false;
  }
  else {
    if (!pIO->Write32(&zero))
      return false;
  }
  if (!pIO->Write16(&m_nScriptCode) ||
      !pIO->Write8(&m_nScriptSize) ||
      pIO->Write8(m_szScriptText, 67)!= 67)
    return false;
  m_bInvalidScript = false;
  return true;
}
References GetType(), m_bInvalidScript, m_nASCIISize, CIccTag::m_nReserved, m_nScriptCode, m_nScriptSize, m_nUnicodeLanguageCode, m_nUnicodeSize, m_szScriptText, m_szText, m_uzUnicodeText, CIccIO::Write16(), CIccIO::Write32(), and CIccIO::Write8().
Field Documentation
m_bInvalidScript
bool CIccTagTextDescription::m_bInvalidScript protected
Referenced by CIccTagTextDescription(), CIccTagTextDescription(), operator=(), Read(), SetText(), Validate(), and Write().
m_nASCIISize
icUInt32Number CIccTagTextDescription::m_nASCIISize protected
Referenced by CIccTagTextDescription(), CIccTagTextDescription(), Capacity(), GetBuffer(), operator=(), CIccTagXmlTextDescription::ParseXml(), Release(), and Write().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_nScriptCode
icUInt16Number CIccTagTextDescription::m_nScriptCode protected
Referenced by CIccTagTextDescription(), CIccTagTextDescription(), operator=(), CIccTagXmlTextDescription::ParseXml(), Read(), CIccTagXmlTextDescription::ToXml(), and Write().
m_nScriptSize
icUInt8Number CIccTagTextDescription::m_nScriptSize protected
Referenced by CIccTagTextDescription(), CIccTagTextDescription(), operator=(), CIccTagXmlTextDescription::ParseXml(), Read(), CIccTagXmlTextDescription::ToXml(), Validate(), and Write().
m_nUnicodeLanguageCode
icUInt32Number CIccTagTextDescription::m_nUnicodeLanguageCode protected
Referenced by CIccTagTextDescription(), CIccTagTextDescription(), operator=(), Read(), CIccTagXmlTextDescription::ToXml(), and Write().
m_nUnicodeSize
icUInt32Number CIccTagTextDescription::m_nUnicodeSize protected
Referenced by CIccTagTextDescription(), CIccTagTextDescription(), GetUnicodeBuffer(), operator=(), CIccTagXmlTextDescription::ParseXml(), ReleaseUnicode(), and Write().
m_szScriptText
icUInt8Number CIccTagTextDescription::m_szScriptText[67] protected
Referenced by CIccTagTextDescription(), CIccTagTextDescription(), operator=(), CIccTagXmlTextDescription::ParseXml(), Read(), CIccTagXmlTextDescription::ToXml(), and Write().
m_szText
icChar* CIccTagTextDescription::m_szText protected
Referenced by CIccTagTextDescription(), CIccTagTextDescription(), ~CIccTagTextDescription(), Describe(), GetBuffer(), GetText(), operator=(), operator=(), CIccTagXmlTextDescription::ParseXml(), Read(), Release(), CIccTagXmlTextDescription::ToXml(), and Write().
m_uzUnicodeText
icUInt16Number* CIccTagTextDescription::m_uzUnicodeText protected
Referenced by CIccTagTextDescription(), CIccTagTextDescription(), ~CIccTagTextDescription(), GetUnicodeBuffer(), operator=(), CIccTagXmlTextDescription::ParseXml(), ReleaseUnicode(), CIccTagXmlTextDescription::ToXml(), and Write().
The documentation for this class was generated from the following files:
IccProfLib/IccTagBasic.h
IccProfLib/IccTagBasic.cpp