iccDEV: Tools/CmdLine/IccTiffDump/iccTiffDump.cpp File Reference
iccTiffDump.cpp File Reference
#include <stdio.h>
#include "IccCmm.h"
#include "IccUtil.h"
#include "IccDefs.h"
#include "IccProfLibVer.h"
#include "IccApplyBPC.h"
#include "TiffImg.h"
Data Structures
struct IdList
Macros
#define UNKNOWNID 0xffffffff
Functions
const char * GetId (unsigned long nId, IdList *pIdList)
int main (int argc, icChar *argv[])
void Usage ()
Variables
IdList compression_types []
IdList photo_types []
IdList planar_types []
Data Structure Documentation
IdList
struct IdList
Data Fields
unsigned long nId
char const *const szName
Macro Definition Documentation
UNKNOWNID
#define UNKNOWNID 0xffffffff
Function Documentation
GetId()
const char * GetId (unsigned long nId, IdList * pIdList)
{
  for (;pIdList->nId != nId && pIdList->nId != UNKNOWNID; pIdList++);
  return pIdList->szName;
}
References IdList::nId, and IdList::szName.
Referenced by main().
main()
int main (int argc, icChar * argv[])
{
  int minargs = 1;
  if (argc <= minargs) {
    Usage();
    return -1;
  }
  CTiffImg SrcImg;
  if (!SrcImg.Open(argv[1])) {
    printf("\nFile [%s] cannot be opened.\n", argv[1]);
    return false;
  }
  printf("-------------------->Tiff Image Dump<---------------------------\n");
  printf("Filename:          %s\n", argv[1]);
  printf("Size:              (%d x %d) pixels, (%.2lf\" x %.2lf\")\n",
    SrcImg.GetWidth(), SrcImg.GetHeight(),
    SrcImg.GetWidthIn(), SrcImg.GetHeightIn());
  printf("Planar:            %s\n", GetId(SrcImg.GetPlanar(), planar_types));
  printf("BitsPerSample:     %d\n", SrcImg.GetBitsPerSample());
  printf("SamplesPerPixel:   %d\n", SrcImg.GetSamples());
  int nExtra = SrcImg.GetExtraSamples();
  if (nExtra)
    printf("ExtraSamples:      %d\n", nExtra);
  printf("Photometric:       %s\n", GetId(SrcImg.GetPhoto(), photo_types));
  printf("BytesPerLine:      %d\n", SrcImg.GetBytesPerLine());
  printf("Resolution:        (%lf x %lf) pixels per/inch\n", SrcImg.GetXRes(), SrcImg.GetYRes());
  printf("Compression:       %s\n", GetId(SrcImg.GetCompress(), compression_types));
  unsigned char *pProfMem = nullptr;
  unsigned int nLen = 0;
  if (SrcImg.GetIccProfile(pProfMem, nLen)) {
    printf("Profile:           Embedded\n");
    // Optional profile export
    if (argc > 2 && pProfMem && nLen > 0) {
      FILE *fp = fopen(argv[2], "wb");
      if (fp) {
        fwrite(pProfMem, 1, nLen, fp);
        fclose(fp);
        printf("ICC profile saved to: %s\n", argv[2]);
      } else {
        fprintf(stderr, "Failed to write ICC profile to %s\n", argv[2]);
      }
    }
    // Profile description and metadata
    CIccProfile *pProfile = OpenIccProfile(pProfMem, nLen);
    if (pProfile) {
      icHeader *pHdr = &pProfile->m_Header;
      CIccInfo Fmt;
      if (pHdr->colorSpace)
        printf(" Color Space:      %s\n", Fmt.GetColorSpaceSigName(pHdr->colorSpace));
      if (pHdr->pcs)
        printf(" Colorimetric PCS: %s\n", Fmt.GetColorSpaceSigName(pHdr->pcs));
      if (pHdr->spectralPCS) {
        printf(" Spectral PCS:     %s\n", Fmt.GetSpectralColorSigName(pHdr->spectralPCS));
        if (pHdr->spectralRange.start || pHdr->spectralRange.end || pHdr->spectralRange.steps) {
          printf(" Spectral Range:   start=%.1fnm, end=%.1fnm, steps=%d\n",
            icF16toF(pHdr->spectralRange.start),
            icF16toF(pHdr->spectralRange.end),
            pHdr->spectralRange.steps);
        }
        if (pHdr->biSpectralRange.start || pHdr->biSpectralRange.end || pHdr->biSpectralRange.steps) {
          printf(" BiSpectral Range: start=%.1fnm, end=%.1fnm, steps=%d\n",
            icF16toF(pHdr->biSpectralRange.start),
            icF16toF(pHdr->biSpectralRange.end),
            pHdr->biSpectralRange.steps);
        }
      }
      CIccTag *pDesc = pProfile->FindTag(icSigProfileDescriptionTag);
      if (pDesc) {
        if (pDesc->GetType() == icSigTextDescriptionType) {
          CIccTagTextDescription *pText = (CIccTagTextDescription*)pDesc;
          printf(" Description:      %s\n", pText->GetText());
        }
        else if (pDesc->GetType() == icSigMultiLocalizedUnicodeType) {
          CIccTagMultiLocalizedUnicode *pStrs = (CIccTagMultiLocalizedUnicode*)pDesc;
          if (pStrs->m_Strings) {
            CIccMultiLocalizedUnicode::iterator text = pStrs->m_Strings->begin();
            if (text != pStrs->m_Strings->end()) {
              std::string line;
              text->GetText(line);
              printf(" Description:      %s\n", line.c_str());
            }
          }
        }
      }
    }
  } else {
    printf("Profile:           None\n");
  }
  SrcImg.Close();
  return 0;
}
References icHeader::biSpectralRange, CIccProfile, CTiffImg::Close(), icHeader::colorSpace, compression_types, icSpectralRange::end, CTiffImg::GetBitsPerSample(), CTiffImg::GetBytesPerLine(), CIccInfo::GetColorSpaceSigName(), CTiffImg::GetCompress(), CTiffImg::GetExtraSamples(), CTiffImg::GetHeight(), CTiffImg::GetHeightIn(), CTiffImg::GetIccProfile(), GetId(), CTiffImg::GetPhoto(), CTiffImg::GetPlanar(), CTiffImg::GetSamples(), CIccInfo::GetSpectralColorSigName(), CIccTagTextDescription::GetText(), CIccLocalizedUnicode::GetText(), CIccTag::GetType(), CTiffImg::GetWidth(), CTiffImg::GetWidthIn(), CTiffImg::GetXRes(), CTiffImg::GetYRes(), icF16toF(), icSigMultiLocalizedUnicodeType, icSigProfileDescriptionTag, icSigTextDescriptionType, CIccTagMultiLocalizedUnicode::m_Strings, CTiffImg::Open(), OpenIccProfile(), icHeader::pcs, photo_types, planar_types, icHeader::spectralPCS, icHeader::spectralRange, icSpectralRange::start, icSpectralRange::steps, and Usage().
Usage()
void Usage ()
{
  printf("iccTiffDump built with IccProfLib version " ICCPROFLIBVER "\n\n");
  printf("Usage: iccTiffDump tiff_file {exported_icc_file}\n\n");
}
Variable Documentation
compression_types
IdList compression_types[]
Initial value:
= {
  {COMPRESSION_NONE,         "None"},
  {COMPRESSION_LZW,          "LZW"},
  {COMPRESSION_JPEG,         "JPEG"},
  {COMPRESSION_DEFLATE,      "Deflate"},
  {COMPRESSION_ADOBE_DEFLATE,"Deflate"},
  {UNKNOWNID,                "Unknown"},
}
{
  {COMPRESSION_NONE,         "None"},
  {COMPRESSION_LZW,          "LZW"},
  {COMPRESSION_JPEG,         "JPEG"},
  {COMPRESSION_DEFLATE,      "Deflate"},
  {COMPRESSION_ADOBE_DEFLATE,"Deflate"},
  {UNKNOWNID,                "Unknown"},
};
Referenced by main().
photo_types
IdList photo_types[]
Initial value:
= {
  {PHOTO_MINISWHITE, "Min Is White"},
  {PHOTO_MINISBLACK, "Min Is Black"},
  {PHOTO_CIELAB,     "CIELab"},
  {PHOTO_ICCLAB,     "IccLab"},
  {UNKNOWNID,        "Unknown"},
}
                       {
  {PHOTO_MINISWHITE, "Min Is White"},
  {PHOTO_MINISBLACK, "Min Is Black"},
  {PHOTO_CIELAB,     "CIELab"},
  {PHOTO_ICCLAB,     "IccLab"},
  {UNKNOWNID,        "Unknown"},
};
Referenced by main().
planar_types
IdList planar_types[]
Initial value:
= {
  {0,  "Interleaved samples"},
  {PLANARCONFIG_CONTIG,  "Interleaved samples"},
  {PLANARCONFIG_SEPARATE, "Samples in separate planes"},
  {UNKNOWNID, "Unknown"},
}
{
  {0,  "Interleaved samples"},
  {PLANARCONFIG_CONTIG,  "Interleaved samples"},
  {PLANARCONFIG_SEPARATE, "Samples in separate planes"},
  {UNKNOWNID, "Unknown"},
};
Referenced by main().