iccDEV: IccXML/IccLibXML/IccIoXml.h File Reference
IccIoXml.h File Reference
#include "IccIO.h"
Data Structures
class CIccStandardFileIO
class IIccOpenFileIO
Functions
CIccIO *ICCPROFLIB_API IccOpenFileIO (const icChar *szFilename, const char *szAttr)
void ICCPROFLIB_API IccSetOpenFileIO (IIccOpenFileIO *pOpenIO)
Detailed Description
File: IccIoXml.h
Contains: Implementation of the IIccOpenFileIO interface.
Version: V1
Copyright: (c) see ICC Software License
Definition in file IccIoXml.h.
Function Documentation
IccOpenFileIO()
CIccIO *ICCPROFLIB_API IccOpenFileIO (const icChar * szFilename, const char * szAttr)
{
  if (g_pIccFileIO) {
    return g_pIccFileIO->OpenFile(szFilename, szAttr);
  }
  return NULL;
}
References g_pIccFileIO, and IIccOpenFileIO::OpenFile().
Referenced by icCLutFromXml(), icXmlParseTextString(), CIccTagXmlCurve::ParseXml(), CIccSampledCurveSegmentXml::ParseXml(), CIccSinglSampledeCurveXml::ParseXml(), CIccTagXmlTextDescription::ParseXml(), CIccTagXmlFloatNum< T, A, Tsig >::ParseXml(), CIccTagXmlEmbeddedHeightImage::ParseXml(), and CIccTagXmlEmbeddedNormalImage::ParseXml().
IccSetOpenFileIO()
void ICCPROFLIB_API IccSetOpenFileIO (IIccOpenFileIO * pOpenIO)
{
  g_pIccFileIO = pOpenIO;
}
References g_pIccFileIO.