iccDEV: IccProfLib/IccWrapper.h File Reference
IccWrapper.h File Reference
#include "IccDefs.h"
#include "IccProfile.h"
#include "IccCmm.h"
Data Structures
struct SIccCmmEnvVars
struct SIccCmmStruct
Typedefs
typedef void CIccApplyHandle
typedef void CIccCmmHandle
typedef void CIccProfileHandle
typedef unsigned char icBoolean
Functions
ICCPROFLIB_API icStatusCMM IccApplyApplyFloat (CIccApplyHandle *pApply, icFloatNumber *pTo, icFloatNumber *pFrom)
ICCPROFLIB_API icStatusCMM IccApplyApplyFloatMulti (CIccApplyHandle *pApply, icFloatNumber *pTo, icFloatNumber *pFrom, icUInt32Number nPixels)
ICCPROFLIB_API void IccApplyFree (CIccApplyHandle *pApply)
ICCPROFLIB_API icStatusCMM IccCmmApplyFloat (CIccCmmHandle *pCmm, icFloatNumber *pTo, icFloatNumber *pFrom)
ICCPROFLIB_API icStatusCMM IccCmmApplyFloatMulti (CIccCmmHandle *pCmm, icFloatNumber *pTo, icFloatNumber *pFrom, icUInt32Number nPixels)
ICCPROFLIB_API icStatusCMM IccCmmAttachProfileFile (CIccCmmHandle *pCmm, const char *szFname, icRenderingIntent nIntent, icXformInterp nInterp, CIccProfileHandle *pPcc, icXformLutType nLutType, icBoolean bUseDtoBTags, icBoolean bUseBPC, SIccCmmEnvVars *pVars)
ICCPROFLIB_API icStatusCMM IccCmmAttachProfileHandle (CIccCmmHandle *pCmm, CIccProfileHandle *pProfile, icRenderingIntent nIntent, icXformInterp nInterp, CIccProfileHandle *pPcc, icXformLutType nLutType, icBoolean bUseDtoBTags, icBoolean bUseBPC, SIccCmmEnvVars *pVars)
ICCPROFLIB_API icStatusCMM IccCmmBegin (CIccCmmHandle *pCmm)
ICCPROFLIB_API CIccCmmHandle * IccCmmCreate (icColorSpaceSignature srcSpace, icColorSpaceSignature dstSpace, icBoolean bFirstIsInput)
ICCPROFLIB_API void IccCmmFree (CIccCmmHandle *pCmm)
ICCPROFLIB_API CIccApplyHandle * IccCmmGetApply (CIccCmmHandle *pCmm)
ICCPROFLIB_API icStatusCMM IccCmmGetInfo (CIccCmmHandle *pCmm, SIccCmmStruct *pCmmInfo)
ICCPROFLIB_API void IccProfileFree (CIccProfileHandle *pProfile)
ICCPROFLIB_API icBoolean IccProfileGetHeader (CIccProfileHandle *pProfile, icHeader *pHeader)
ICCPROFLIB_API CIccProfileHandle * IccProfileOpenHandle (const char *szFname)
ICCPROFLIB_API CIccProfileHandle * IccProfileReadHandle (const char *szFname)
Detailed Description
File: IccWrapper.h
Contains: Header file for C Wrapper interface functions for CIccProfile and CIccCmm classes.
Version: V1
Copyright: (c) see ICC Software License
Definition in file IccWrapper.h.
Data Structure Documentation
SIccCmmEnvVars
struct SIccCmmEnvVars
Data Fields
icUInt32Number nVars
icSigCmmEnvVar * sigs
icFloat32Number * vals
SIccCmmStruct
struct SIccCmmStruct
Data Fields
icUInt16Number dstSamples
icColorSpaceSignature dstSpace
icUInt16Number srcSamples
icColorSpaceSignature srcSpace
Typedef Documentation
CIccApplyHandle
typedef void CIccApplyHandle
CIccCmmHandle
typedef void CIccCmmHandle
CIccProfileHandle
typedef void CIccProfileHandle
icBoolean
typedef unsigned char icBoolean
Function Documentation
IccApplyApplyFloat()
ICCPROFLIB_API icStatusCMM IccApplyApplyFloat (CIccApplyHandle * pApply, icFloatNumber * pTo, icFloatNumber * pFrom)
{
  if (!pApply || !pTo || !pFrom)
    return icCmmStatBad;
  CIccApplyCmm *pApplyPtr = (CIccApplyCmm*)pApply;
  return pApplyPtr->Apply(pTo, pFrom);
}
References icCmmStatBad.
IccApplyApplyFloatMulti()
ICCPROFLIB_API icStatusCMM IccApplyApplyFloatMulti (CIccApplyHandle * pApply, icFloatNumber * pTo, icFloatNumber * pFrom, icUInt32Number nPixels)
{
  if (!pApply || !pTo || !pFrom)
    return icCmmStatBad;
  CIccApplyCmm *pApplyPtr = (CIccApplyCmm*)pApply;
  return pApplyPtr->Apply(pTo, pFrom, nPixels);
}
References icCmmStatBad.
IccApplyFree()
ICCPROFLIB_API void IccApplyFree (CIccApplyHandle * pApply)
{
  if (pApply) {
    CIccApplyCmm *pApplyPtr = (CIccApplyCmm*)pApply;
    delete pApplyPtr;
  }
}
IccCmmApplyFloat()
ICCPROFLIB_API icStatusCMM IccCmmApplyFloat (CIccCmmHandle * pCmm, icFloatNumber * pTo, icFloatNumber * pFrom)
{
  if (!pCmm || !pTo || !pFrom)
    return icCmmStatBad;
  CIccCmm *pCmmPtr = (CIccCmm*)pCmm;
  return pCmmPtr->Apply(pTo, pFrom);
}
References icCmmStatBad.
IccCmmApplyFloatMulti()
ICCPROFLIB_API icStatusCMM IccCmmApplyFloatMulti (CIccCmmHandle * pCmm, icFloatNumber * pTo, icFloatNumber * pFrom, icUInt32Number nPixels)
{
  if (!pCmm || !pTo || !pFrom)
    return icCmmStatBad;
  CIccCmm *pCmmPtr = (CIccCmm*)pCmm;
  return pCmmPtr->Apply(pTo, pFrom, nPixels);
}
References icCmmStatBad.
IccCmmAttachProfileFile()
ICCPROFLIB_API icStatusCMM IccCmmAttachProfileFile (CIccCmmHandle * pCmm, const char * szFname, icRenderingIntent nIntent, icXformInterp nInterp, CIccProfileHandle * pPcc, icXformLutType nLutType, icBoolean bUseDtoBTags, icBoolean bUseBPC, SIccCmmEnvVars * pVars)
{
  if (!pCmm)
    return icCmmStatBad;
  CIccCmm *pCmmPtr = (CIccCmm*)pCmm;
  CIccCreateXformHintManager hint;
  bool bUseHint = false;
  if (bUseBPC) {
    hint.AddHint(new CIccApplyBPCHint());
    bUseHint = true;
  }
  if (pVars) {
    hint.AddHint(new CIccCmmEnvVarWrapperHint(pVars));
    bUseHint = true;
  }
  return pCmmPtr->AddXform(szFname, nIntent, nInterp, (CIccProfile*)pPcc, nLutType, bUseDtoBTags != 0, bUseHint ? &hint : NULL);
}
References CIccCmmEnvVarWrapperHint::CIccCmmEnvVarWrapperHint(), CIccProfile, and icCmmStatBad.
IccCmmAttachProfileHandle()
ICCPROFLIB_API icStatusCMM IccCmmAttachProfileHandle (CIccCmmHandle * pCmm, CIccProfileHandle * pProfile, icRenderingIntent nIntent, icXformInterp nInterp, CIccProfileHandle * pPcc, icXformLutType nLutType, icBoolean bUseDtoBTags, icBoolean bUseBPC, SIccCmmEnvVars * pVars)
{
  if (!pCmm)
    return icCmmStatBad;
  CIccCmm *pCmmPtr = (CIccCmm*)pCmm;
  CIccProfile *pProfilePtr = (CIccProfile*)pProfile;
  CIccCreateXformHintManager hint;
  bool bUseHint = false;
  if (bUseBPC) {
    hint.AddHint(new CIccApplyBPCHint());
    bUseHint = true;
  }
  if (pVars) {
    hint.AddHint(new CIccCmmEnvVarWrapperHint(pVars));
    bUseHint = true;
  }
  return pCmmPtr->AddXform(pProfilePtr, nIntent, nInterp, (CIccProfile*)pPcc, nLutType, bUseDtoBTags != 0, bUseHint ? &hint : NULL);
}
References CIccCmmEnvVarWrapperHint::CIccCmmEnvVarWrapperHint(), CIccProfile, and icCmmStatBad.
IccCmmBegin()
ICCPROFLIB_API icStatusCMM IccCmmBegin (CIccCmmHandle * pCmm)
{
  if (!pCmm)
    return icCmmStatBad;
  CIccCmm *pCmmPtr = (CIccCmm*)pCmm;
  return pCmmPtr->Begin();
}
References icCmmStatBad.
IccCmmCreate()
ICCPROFLIB_API CIccCmmHandle * IccCmmCreate (icColorSpaceSignature srcSpace, icColorSpaceSignature dstSpace, icBoolean bFirstIsInput)
{
  return (CIccCmmHandle*)new CIccCmm(srcSpace, dstSpace, bFirstIsInput != 0);
}
IccCmmFree()
ICCPROFLIB_API void IccCmmFree (CIccCmmHandle * pCmm)
{
  if (pCmm) {
    CIccCmm *pCmmPtr = (CIccCmm*)pCmm;
    delete pCmmPtr;
  }
}
IccCmmGetApply()
ICCPROFLIB_API CIccApplyHandle * IccCmmGetApply (CIccCmmHandle * pCmm)
{
  if (!pCmm)
    return NULL;
  CIccCmm *pCmmPtr = (CIccCmm*)pCmm;
  return (CIccApplyHandle*)pCmmPtr->GetApply();
}
IccCmmGetInfo()
ICCPROFLIB_API icStatusCMM IccCmmGetInfo (CIccCmmHandle * pCmm, SIccCmmStruct * pCmmInfo)
{
  if (!pCmm || !pCmmInfo)
    return icCmmStatBad;
  CIccCmm *pCmmPtr = (CIccCmm*)pCmm;
  pCmmInfo->srcSpace = pCmmPtr->GetSourceSpace();
  pCmmInfo->srcSamples = pCmmPtr->GetSourceSamples();
  pCmmInfo->dstSpace = pCmmPtr->GetDestSpace();
  pCmmInfo->dstSamples = pCmmPtr->GetDestSamples();
  return icCmmStatOk;
}
References SIccCmmStruct::dstSamples, SIccCmmStruct::dstSpace, icCmmStatBad, icCmmStatOk, SIccCmmStruct::srcSamples, and SIccCmmStruct::srcSpace.
IccProfileFree()
ICCPROFLIB_API void IccProfileFree (CIccProfileHandle * pProfile)
{
  if (pProfile) {
    CIccProfileHandle *pProfilePtr = (CIccProfileHandle*)pProfile;
    delete pProfilePtr;
  }
}
IccProfileGetHeader()
ICCPROFLIB_API icBoolean IccProfileGetHeader (CIccProfileHandle * pProfile, icHeader * pHeader)
{
  if (!pProfile || !pHeader)
    return 0;
  CIccProfile *pProfilePtr = (CIccProfile*)pProfile;
  *pHeader = pProfilePtr->m_Header;
  return 1;
}
References CIccProfile.
IccProfileOpenHandle()
ICCPROFLIB_API CIccProfileHandle * IccProfileOpenHandle (const char * szFname)
{
  return (CIccProfileHandle*)OpenIccProfile(szFname);
}
References OpenIccProfile().
IccProfileReadHandle()
ICCPROFLIB_API CIccProfileHandle * IccProfileReadHandle (const char * szFname)
{
  return (CIccProfileHandle*)ReadIccProfile(szFname);
}
References ReadIccProfile().