iccDEV: CIccMpeUnknown Class Reference
CIccMpeUnknown Class Reference
#include <IccTagMPE.h>
Public Member Functions
CIccMpeUnknown ()
CIccMpeUnknown (const CIccMpeUnknown &elem)
virtual ~CIccMpeUnknown ()
virtual void Apply (CIccApplyMpe *pApply, icFloatNumber *pDestPixel, const icFloatNumber *pSrcPixel) const
virtual bool Begin (icElemInterp nIterp=icElemInterpLinear, CIccTagMultiProcessElement *pMPE=NULL)
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual icAcsSignature GetBAcsSig ()
virtual const icChar * GetClassName () const
icUInt8Number * GetData ()
virtual icAcsSignature GetEAcsSig ()
virtual IIccExtensionMpe * GetExtension ()
virtual CIccApplyMpe * GetNewApply ()
virtual CIccApplyMpe * GetNewApply (CIccApplyTagMpe *pApplyTag)
virtual icElemTypeSignature GetType () const
virtual bool IsAcs ()
virtual bool IsLateBinding () const
virtual bool IsLateBindingReflectance () const
virtual bool IsSupported ()
virtual CIccMultiProcessElement * NewCopy () const
virtual icUInt16Number NumInputChannels () const
virtual icUInt16Number NumOutputChannels () const
CIccMpeUnknown & operator= (const CIccMpeUnknown &elem)
virtual bool Read (icUInt32Number nSize, CIccIO *pIO)
void SetChannels (icUInt16Number nInputChannels, icUInt16Number nOutputChannels)
bool SetDataSize (icUInt32Number nSize, bool bZeroData=true)
void SetType (icElemTypeSignature sig)
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccTagMultiProcessElement *pMPE=NULL, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccMultiProcessElement * Create (icElemTypeSignature sig)
Protected Attributes
icUInt16Number m_nInputChannels
icUInt16Number m_nOutputChannels
icUInt32Number m_nReserved
icUInt32Number m_nSize
icUInt8Number * m_pData
icElemTypeSignature m_sig
Detailed Description
Class: CIccMpeUnknown
Purpose: Base Class for Process Elements
Constructor & Destructor Documentation
CIccMpeUnknown() [1/2]
CIccMpeUnknown::CIccMpeUnknown ()
Name: CIccMpeUnknown::CIccMpeUnknown
Purpose:
Args:
Return:
{
   m_sig = icSigUnknownElemType;
   m_nReserved = 0;
   m_nInputChannels = 0;
   m_nOutputChannels = 0;
   m_nSize = 0;
   m_pData = 0;
}
References m_nInputChannels, m_nOutputChannels, m_nReserved, m_nSize, m_pData, and m_sig.
Referenced by CIccBasicMpeFactory::CreateElement().
CIccMpeUnknown() [2/2]
CIccMpeUnknown::CIccMpeUnknown (const CIccMpeUnknown & elem)
Name: CIccMpeUnknown::CIccMpeUnknown
Purpose:
Args:
Return:
{
   m_sig = elem.m_sig;
   m_nReserved = elem.m_nReserved;
   m_nInputChannels = elem.m_nInputChannels;
   m_nOutputChannels = elem.m_nOutputChannels;
   m_nSize = elem.m_nSize;
   if (m_nSize) {
     m_pData = (icUInt8Number*)malloc(m_nSize);
     if (m_pData)
       memcpy(m_pData, elem.m_pData, m_nSize);
   }
   else
     m_pData = NULL;
}
References m_nInputChannels, m_nOutputChannels, m_nReserved, m_nSize, m_pData, and m_sig.
Referenced by NewCopy().
~CIccMpeUnknown()
CIccMpeUnknown::~CIccMpeUnknown () virtual
Name: CIccMpeUnknown::~CIccMpeUnknown
Purpose:
Args:
Return:
{
  if (m_pData)
    free(m_pData);
}
References m_pData.
Member Function Documentation
Apply()
virtual void CIccMpeUnknown::Apply (CIccApplyMpe * pApply, icFloatNumber * pDestPixel, const icFloatNumber * pSrcPixel) const inline virtual
Implements CIccMultiProcessElement.
{}
Begin()
virtual bool CIccMpeUnknown::Begin (icElemInterp nIterp = icElemInterpLinear, CIccTagMultiProcessElement * pMPE = NULL) inline virtual
Implements CIccMultiProcessElement.
{ return false; }
Create()
CIccMultiProcessElement * CIccMultiProcessElement::Create (icElemTypeSignature sig) static inherited
Name: CIccMultiProcessElement::Create
Purpose:
Args:
Return:
{
  return CIccMpeCreator::CreateElement(sig);
}
References CIccMpeCreator::CreateElement().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccSampledCalculatorCurve::Read(), CIccMpeCalculator::Read(), and CIccTagMultiProcessElement::Read().
Describe()
void CIccMpeUnknown::Describe (std::string & sDescription, int nVerboseness) virtual
Name: CIccMpeUnknown::Describe
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
{
  icChar buf[128], sigbuf[40];
  sprintf(buf, "Unknown Element(%s) Type of %u Bytes.",
          icGetSig(sigbuf, m_sig), m_nSize);
  sDescription += buf;
  if (nVerboseness > 50) {
    sDescription += "\n\nData Follows:\n";
    icMemDump(sDescription, m_pData, m_nSize);
  }
}
References icGetSig(), icMemDump(), m_nSize, m_pData, and m_sig.
GetBAcsSig()
virtual icAcsSignature CIccMultiProcessElement::GetBAcsSig () inline virtual inherited
Reimplemented in CIccMpeBAcs.
{ return icSigAcsZero; }
Referenced by CIccMpeAcs::Describe().
GetClassName()
virtual const icChar * CIccMpeUnknown::GetClassName () const inline virtual
Implements CIccMultiProcessElement.
Reimplemented in CIccMpeXmlUnknown.
{ return "CIccMpeUnknown"; }
GetData()
icUInt8Number * CIccMpeUnknown::GetData () inline
{ return m_pData; }
References m_pData.
GetEAcsSig()
virtual icAcsSignature CIccMultiProcessElement::GetEAcsSig () inline virtual inherited
Reimplemented in CIccMpeEAcs.
{ return icSigAcsZero; }
GetExtension()
virtual IIccExtensionMpe * CIccMultiProcessElement::GetExtension () inline virtual inherited
Reimplemented in CIccMpeXmlUnknown, CIccMpeXmlCurveSet, CIccMpeXmlTintArray, CIccMpeXmlToneMap, CIccMpeXmlMatrix, CIccMpeXmlCLUT, CIccMpeXmlExtCLUT, CIccMpeXmlBAcs, CIccMpeXmlEAcs, CIccMpeXmlJabToXYZ, CIccMpeXmlXYZToJab, CIccMpeXmlCalculator, CIccMpeXmlEmissionMatrix, CIccMpeXmlInvEmissionMatrix, CIccMpeXmlEmissionCLUT, CIccMpeXmlReflectanceCLUT, CIccMpeXmlEmissionObserver, and CIccMpeXmlReflectanceObserver.
{ return NULL; }
Referenced by CIccTagXmlMultiProcessElement::ParseElement(), CIccMpeXmlCalculator::ParseImport(), CIccMpeXmlCalculator::ToXml(), and CIccTagXmlMultiProcessElement::ToXml().
GetNewApply() [1/2]
virtual CIccApplyMpe * CIccMpeUnknown::GetNewApply () inline virtual
{ return NULL; }
GetNewApply() [2/2]
CIccApplyMpe * CIccMultiProcessElement::GetNewApply (CIccApplyTagMpe * pApplyTag) virtual inherited
Name: CIccMultiProcessElement::GetNewApply()
Purpose:
Args:
Return:
Reimplemented in CIccMpeCLUT, CIccMpeCalculator, and CIccMpeSpectralCLUT.
{
  return new CIccApplyMpe(this);
}
References CIccApplyMpe::CIccApplyMpe().
Referenced by CIccApplyTagMpe::AppendElem(), and CIccMpeCalculator::GetNewApply().
GetType()
virtual icElemTypeSignature CIccMpeUnknown::GetType () const inline virtual
Implements CIccMultiProcessElement.
{ return m_sig; }
References m_sig.
Referenced by CIccMpeXmlUnknown::ToXml().
IsAcs()
virtual bool CIccMultiProcessElement::IsAcs () inline virtual inherited
Reimplemented in CIccMpeAcs.
{ return false; }
Referenced by CIccTagMultiProcessElement::Apply().
IsLateBinding()
virtual bool CIccMultiProcessElement::IsLateBinding () const inline virtual inherited
Reimplemented in CIccMpeCalculator, CIccMpeSpectralMatrix, CIccMpeSpectralCLUT, and CIccMpeSpectralObserver.
{ return false; }
Referenced by CIccMpeCalculator::IsLateBinding(), and CIccTagMultiProcessElement::IsLateBinding().
IsLateBindingReflectance()
virtual bool CIccMultiProcessElement::IsLateBindingReflectance () const inline virtual inherited
Reimplemented in CIccMpeCalculator, CIccMpeReflectanceCLUT, and CIccMpeReflectanceObserver.
{ return false; }
Referenced by CIccMpeCalculator::IsLateBindingReflectance(), and CIccTagMultiProcessElement::IsLateBindingReflectance().
IsSupported()
virtual bool CIccMpeUnknown::IsSupported () inline virtual
Reimplemented from CIccMultiProcessElement.
{ return false; }
NewCopy()
virtual CIccMultiProcessElement * CIccMpeUnknown::NewCopy () const inline virtual
Implements CIccMultiProcessElement.
{ return new CIccMpeUnknown(*this);}
References CIccMpeUnknown().
NumInputChannels()
virtual icUInt16Number CIccMultiProcessElement::NumInputChannels () const inline virtual inherited
{ return m_nInputChannels; }
References CIccMultiProcessElement::m_nInputChannels.
Referenced by SIccCalcOp::ArgsUsed(), CIccCalculatorFunc::Begin(), CIccTagMultiProcessElement::Begin(), CIccSubCalcApply::NumInputChannels(), CIccMpeXmlUnknown::ToXml(), CIccMpeXmlCurveSet::ToXml(), CIccMpeXmlTintArray::ToXml(), CIccMpeXmlToneMap::ToXml(), CIccMpeXmlMatrix::ToXml(), CIccMpeXmlCLUT::ToXml(), CIccMpeXmlExtCLUT::ToXml(), CIccMpeXmlBAcs::ToXml(), CIccMpeXmlEAcs::ToXml(), CIccMpeXmlJabToXYZ::ToXml(), CIccMpeXmlXYZToJab::ToXml(), CIccMpeXmlCalculator::ToXml(), CIccMpeXmlEmissionMatrix::ToXml(), CIccMpeXmlInvEmissionMatrix::ToXml(), CIccMpeXmlEmissionCLUT::ToXml(), CIccMpeXmlReflectanceCLUT::ToXml(), CIccMpeXmlEmissionObserver::ToXml(), CIccMpeXmlReflectanceObserver::ToXml(), CIccCalculatorFunc::Validate(), and CIccTagMultiProcessElement::Validate().
NumOutputChannels()
virtual icUInt16Number CIccMultiProcessElement::NumOutputChannels () const inline virtual inherited
{ return m_nOutputChannels; }
References CIccMultiProcessElement::m_nOutputChannels.
Referenced by CIccCalculatorFunc::Apply(), SIccCalcOp::ArgsPushed(), CIccCalculatorFunc::Begin(), CIccTagMultiProcessElement::Begin(), CIccSubCalcApply::NumOutputChannels(), CIccMpeXmlUnknown::ToXml(), CIccMpeXmlCurveSet::ToXml(), CIccMpeXmlTintArray::ToXml(), CIccMpeXmlToneMap::ToXml(), CIccMpeXmlMatrix::ToXml(), CIccMpeXmlCLUT::ToXml(), CIccMpeXmlExtCLUT::ToXml(), CIccMpeXmlBAcs::ToXml(), CIccMpeXmlEAcs::ToXml(), CIccMpeXmlJabToXYZ::ToXml(), CIccMpeXmlXYZToJab::ToXml(), CIccMpeXmlCalculator::ToXml(), CIccMpeXmlEmissionMatrix::ToXml(), CIccMpeXmlInvEmissionMatrix::ToXml(), CIccMpeXmlEmissionCLUT::ToXml(), CIccMpeXmlReflectanceCLUT::ToXml(), CIccMpeXmlEmissionObserver::ToXml(), CIccMpeXmlReflectanceObserver::ToXml(), CIccCalculatorFunc::Validate(), and CIccTagMultiProcessElement::Validate().
operator=()
CIccMpeUnknown & CIccMpeUnknown::operator= (const CIccMpeUnknown & elem)
Name: CIccMpeUnknown::operator=
Purpose:
Args:
Return:
{
  if (m_pData)
    free(m_pData);
   m_sig = elem.m_sig;
   m_nReserved = elem.m_nReserved;
   m_nInputChannels = elem.m_nInputChannels;
   m_nOutputChannels = elem.m_nOutputChannels;
   m_nSize = elem.m_nSize;
   if (m_nSize) {
     m_pData = (icUInt8Number*)malloc(m_nSize);
     if (m_pData)
       memcpy(m_pData, elem.m_pData, m_nSize);
   }
   else
     m_pData = NULL;
   return (*this);
}
References m_nInputChannels, m_nOutputChannels, m_nReserved, m_nSize, m_pData, and m_sig.
Read()
bool CIccMpeUnknown::Read (icUInt32Number nSize, CIccIO * pIO) virtual
Name: CIccMpeUnknown::Read
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
{
  icUInt32Number nHeaderSize = sizeof(icTagTypeSignature) +
    sizeof(icUInt32Number) +
    sizeof(icUInt16Number) +
    sizeof(icUInt16Number);
  if (nHeaderSize > nSize)
    return false;
  if (!pIO) {
    return false;
  }
  if (!pIO->Read32(&m_sig))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  if (!pIO->Read16(&m_nInputChannels))
    return false;
  if (!pIO->Read16(&m_nOutputChannels))
    return false;
  icUInt32Number nDataSize = nSize - nHeaderSize;
  if (nDataSize) {
    if (!SetDataSize(nDataSize, false))
      return false;
    if (pIO->Read8(m_pData, nDataSize)!=(icInt32Number)nDataSize)
      return false;
  }
  return true;
}
References m_nInputChannels, m_nOutputChannels, m_nReserved, m_pData, m_sig, CIccIO::Read16(), CIccIO::Read32(), CIccIO::Read8(), and SetDataSize().
SetChannels()
void CIccMpeUnknown::SetChannels (icUInt16Number nInputChannels, icUInt16Number nOutputChannels)
Name: CIccMpeUnknown::Describe
Purpose:
Args:
Return:
{
  m_nInputChannels = nInputChannels;
  m_nOutputChannels = nOutputChannels;
}
References m_nInputChannels, and m_nOutputChannels.
Referenced by CIccMpeXmlUnknown::ParseXml().
SetDataSize()
bool CIccMpeUnknown::SetDataSize (icUInt32Number nSize, bool bZeroData = true)
Name: CIccMpeUnknown::SetDataSize
Purpose:
Args:
Return:
{
  bool rv = true;
  if (m_pData)
    free(m_pData);
  m_nSize = nSize;
  if (m_nSize) {
    m_pData = (icUInt8Number*)malloc(m_nSize);
    if (!m_pData) {
      rv = false;
      m_nSize = 0;
    }
  }
  else
    m_pData = NULL;
  return rv;
}
References m_nSize, and m_pData.
Referenced by CIccMpeXmlUnknown::ParseXml(), and Read().
SetType()
void CIccMpeUnknown::SetType (icElemTypeSignature sig)
Name: CIccMpeUnknown::SetType
Purpose:
Args:
Return:
{
  m_sig = sig;
}
References m_sig.
Referenced by CIccMpeXmlUnknown::ParseXml().
Validate()
icValidateStatus CIccMpeUnknown::Validate (std::string sigPath, std::string & sReport, const CIccTagMultiProcessElement * pMPE = NULL, const CIccProfile * pProfile = NULL) const virtual
Name: CIccMpeUnknown::Validate
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
{
  CIccInfo Info;
  icChar buf[40];
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  sReport += icMsgValidateCriticalError;
  sReport += sSigPathName;
  sReport += " - Contains unknown processing element type (";
  icGetSig(buf, m_sig, true);
  sReport += buf;
  sReport += ").\n";
  return icValidateCriticalError;
}
References CIccInfo::GetSigPathName(), icGetSig(), icMsgValidateCriticalError, icValidateCriticalError, and m_sig.
Write()
bool CIccMpeUnknown::Write (CIccIO * pIO) virtual
Name: CIccMpeUnknown::Write
Purpose:
Args:
Return:
Implements CIccMultiProcessElement.
{
  if (!pIO)
    return false;
  //icUInt32Number elemStart = pIO->Tell();
  if (!pIO->Write32(&m_sig))
    return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  if (!pIO->Write16(&m_nInputChannels))
    return false;
  if (!pIO->Write16(&m_nOutputChannels))
    return false;
  if (m_nSize) {
    if (pIO->Write8(m_pData, m_nSize)!=(icInt32Number)m_nSize)
      return false;
  }
  return true;
}
References m_nInputChannels, m_nOutputChannels, m_nReserved, m_nSize, m_pData, m_sig, CIccIO::Write16(), CIccIO::Write32(), and CIccIO::Write8().
Field Documentation
m_nInputChannels
icUInt16Number CIccMpeUnknown::m_nInputChannels protected
Referenced by CIccMpeUnknown(), CIccMpeUnknown(), operator=(), Read(), SetChannels(), and Write().
m_nOutputChannels
icUInt16Number CIccMpeUnknown::m_nOutputChannels protected
Referenced by CIccMpeUnknown(), CIccMpeUnknown(), operator=(), Read(), SetChannels(), and Write().
m_nReserved
icUInt32Number CIccMpeUnknown::m_nReserved protected
Referenced by CIccMpeUnknown(), CIccMpeUnknown(), operator=(), Read(), CIccMpeXmlUnknown::ToXml(), and Write().
m_nSize
icUInt32Number CIccMpeUnknown::m_nSize protected
Referenced by CIccMpeUnknown(), CIccMpeUnknown(), Describe(), operator=(), SetDataSize(), CIccMpeXmlUnknown::ToXml(), and Write().
m_pData
icUInt8Number* CIccMpeUnknown::m_pData protected
Referenced by CIccMpeUnknown(), CIccMpeUnknown(), ~CIccMpeUnknown(), Describe(), GetData(), operator=(), CIccMpeXmlUnknown::ParseXml(), Read(), SetDataSize(), CIccMpeXmlUnknown::ToXml(), and Write().
m_sig
icElemTypeSignature CIccMpeUnknown::m_sig protected
Referenced by CIccMpeUnknown(), CIccMpeUnknown(), Describe(), GetType(), operator=(), Read(), SetType(), Validate(), and Write().
The documentation for this class was generated from the following files:
IccProfLib/IccTagMPE.h
IccProfLib/IccTagMPE.cpp