iccDEV: CIccApplyMpe Class Reference
CIccApplyMpe Class Reference
#include <IccTagMPE.h>
Public Member Functions
CIccApplyMpe (CIccMultiProcessElement *pElem)
virtual ~CIccApplyMpe ()
void Apply (icFloatNumber *pDestPixel, const icFloatNumber *pSrcPixel)
virtual const icChar * GetClassName () const
CIccMultiProcessElement * GetElem () const
virtual icElemTypeSignature GetType () const
Protected Attributes
CIccApplyTagMpe * m_pApplyTag
CIccMultiProcessElement * m_pElem
Detailed Description
Class: CIccApplyMpe
Purpose: Base Class for Apply storage for Multi Process Elements
Constructor & Destructor Documentation
CIccApplyMpe()
CIccApplyMpe::CIccApplyMpe (CIccMultiProcessElement * pElem)
Name: CIccApplyMpe::CIccApplyMpe
Purpose:
Args:
Return:
{
  m_pElem = pElem;
  m_pApplyTag = NULL;
}
References m_pApplyTag, and m_pElem.
Referenced by CIccApplyMpeCalculator::CIccApplyMpeCalculator(), CIccApplyMpeCLUT::CIccApplyMpeCLUT(), CIccApplyMpeSpectralCLUT::CIccApplyMpeSpectralCLUT(), and CIccMultiProcessElement::GetNewApply().
~CIccApplyMpe()
CIccApplyMpe::~CIccApplyMpe () virtual
Name: CIccApplyMpe::~CIccApplyMpe
Purpose:
Args:
Return:
{
}
Member Function Documentation
Apply()
void CIccApplyMpe::Apply (icFloatNumber * pDestPixel, const icFloatNumber * pSrcPixel) inline
{ m_pElem->Apply(this, pDestPixel, pSrcPixel); }
References CIccMultiProcessElement::Apply(), and m_pElem.
Referenced by CIccTagMultiProcessElement::Apply(), and CIccSubCalcApply::Apply().
GetClassName()
virtual const icChar * CIccApplyMpe::GetClassName () const inline virtual
Reimplemented in CIccApplyMpeCLUT, CIccApplyMpeCalculator, and CIccApplyMpeSpectralCLUT.
{ return "CIccApplyMpe"; }
GetElem()
CIccMultiProcessElement * CIccApplyMpe::GetElem () const inline
{ return m_pElem; }
References m_pElem.
Referenced by CIccTagMultiProcessElement::Apply(), CIccSubCalcApply::NumInputChannels(), and CIccSubCalcApply::NumOutputChannels().
GetType()
virtual icElemTypeSignature CIccApplyMpe::GetType () const inline virtual
Reimplemented in CIccApplyMpeCLUT, CIccApplyMpeCalculator, and CIccApplyMpeSpectralCLUT.
{ return icSigUnknownElemType; }
Field Documentation
m_pApplyTag
CIccApplyTagMpe* CIccApplyMpe::m_pApplyTag protected
Referenced by CIccApplyMpe().
m_pElem
CIccMultiProcessElement* CIccApplyMpe::m_pElem protected
Referenced by CIccApplyMpe(), Apply(), GetElem(), and CIccApplyMpeSpectralCLUT::GetType().
The documentation for this class was generated from the following files:
IccProfLib/IccTagMPE.h
IccProfLib/IccTagMPE.cpp