iccDEV: CIccMpeXml Class Reference
CIccMpeXml Class Reference abstract
#include <IccMpeXml.h>
Public Member Functions
virtual ~CIccMpeXml (void)
virtual const char * GetExtClassName ()
virtual bool ParseXml (xmlNode *pNode, std::string &parseStr)=0
virtual bool ToXml (std::string &xml, std::string blanks="")=0
Detailed Description
Constructor & Destructor Documentation
~CIccMpeXml()
virtual CIccMpeXml::~CIccMpeXml (void) inline virtual
{}
Member Function Documentation
GetExtClassName()
virtual const char * CIccMpeXml::GetExtClassName () inline virtual
Implements IIccExtensionMpe.
{ return "CIccMpeXml"; }
ParseXml()
virtual bool CIccMpeXml::ParseXml (xmlNode * pNode, std::string & parseStr) pure virtual
Implemented in CIccMpeXmlUnknown, CIccMpeXmlCurveSet, CIccMpeXmlTintArray, CIccMpeXmlToneMap, CIccMpeXmlMatrix, CIccMpeXmlCLUT, CIccMpeXmlExtCLUT, CIccMpeXmlBAcs, CIccMpeXmlEAcs, CIccMpeXmlJabToXYZ, CIccMpeXmlXYZToJab, CIccMpeXmlCalculator, CIccMpeXmlEmissionMatrix, CIccMpeXmlInvEmissionMatrix, CIccMpeXmlEmissionCLUT, CIccMpeXmlReflectanceCLUT, CIccMpeXmlEmissionObserver, and CIccMpeXmlReflectanceObserver.
Referenced by CIccTagXmlMultiProcessElement::ParseElement(), and CIccMpeXmlCalculator::ParseImport().
ToXml()
virtual bool CIccMpeXml::ToXml (std::string & xml, std::string blanks = "") pure virtual
Implemented in CIccMpeXmlUnknown, CIccMpeXmlCurveSet, CIccMpeXmlTintArray, CIccMpeXmlToneMap, CIccMpeXmlMatrix, CIccMpeXmlCLUT, CIccMpeXmlExtCLUT, CIccMpeXmlBAcs, CIccMpeXmlEAcs, CIccMpeXmlJabToXYZ, CIccMpeXmlXYZToJab, CIccMpeXmlCalculator, CIccMpeXmlEmissionMatrix, CIccMpeXmlInvEmissionMatrix, CIccMpeXmlEmissionCLUT, CIccMpeXmlReflectanceCLUT, CIccMpeXmlEmissionObserver, and CIccMpeXmlReflectanceObserver.
Referenced by CIccMpeXmlCalculator::ToXml(), and CIccTagXmlMultiProcessElement::ToXml().
The documentation for this class was generated from the following file:
IccXML/IccLibXML/IccMpeXml.h