iccDEV: CIccTagXmlMultiLocalizedUnicode Class Reference
CIccTagXmlMultiLocalizedUnicode Class Reference
#include <IccTagXml.h>
Public Member Functions
CIccTagXmlMultiLocalizedUnicode ()
CIccTagXmlMultiLocalizedUnicode (const CIccTagXmlMultiLocalizedUnicode &ITMLU)
virtual ~CIccTagXmlMultiLocalizedUnicode ()
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
CIccLocalizedUnicode * Find (icLanguageCode nLanguageCode=icLanguageCodeEnglish, icCountryCode nRegionCode=icCountryCodeUSA)
virtual const char * GetClassName () const
virtual const char * GetExtClassName () const
virtual const char * GetExtDerivedClassName () const
virtual IIccExtensionTag * GetExtension ()
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
virtual bool ParseXml (xmlNode *pNode, std::string &parseStr)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
void SetText (const icChar *szText, icLanguageCode nLanguageCode=icLanguageCodeEnglish, icCountryCode nRegionCode=icCountryCodeUSA)
void SetText (const icUInt16Number *sszUnicode16Text, icLanguageCode nLanguageCode=icLanguageCodeEnglish, icCountryCode nRegionCode=icCountryCodeUSA)
void SetText (const icUInt32Number *sszUnicode32Text, icLanguageCode nLanguageCode=icLanguageCodeEnglish, icCountryCode nRegionCode=icCountryCodeUSA)
virtual bool ToXml (std::string &xml, std::string blanks="")
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
CIccMultiLocalizedUnicode * m_Strings
Detailed Description
Constructor & Destructor Documentation
CIccTagXmlMultiLocalizedUnicode() [1/2]
CIccTagXmlMultiLocalizedUnicode::CIccTagXmlMultiLocalizedUnicode () inline
: CIccTagMultiLocalizedUnicode() {}
References CIccTagMultiLocalizedUnicode::CIccTagMultiLocalizedUnicode().
CIccTagXmlMultiLocalizedUnicode() [2/2]
CIccTagXmlMultiLocalizedUnicode::CIccTagXmlMultiLocalizedUnicode (const CIccTagXmlMultiLocalizedUnicode & ITMLU) inline
: CIccTagMultiLocalizedUnicode(ITMLU) {}
References CIccTagMultiLocalizedUnicode::CIccTagMultiLocalizedUnicode().
Referenced by NewCopy().
~CIccTagXmlMultiLocalizedUnicode()
virtual CIccTagXmlMultiLocalizedUnicode::~CIccTagXmlMultiLocalizedUnicode () inline virtual
{}
Member Function Documentation
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagMultiLocalizedUnicode::Describe (std::string & sDescription, int nVerboseness) virtual inherited
Name: CIccTagMultiLocalizedUnicode::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  char szBuf[128];
  std::string utf8;
  int nSize = 127;
  CIccMultiLocalizedUnicode::iterator i;
  for (i=m_Strings->begin(); i!=m_Strings->end(); i++) {
    if (i!=m_Strings->begin())
      sDescription += "\n";
    // Bad ICCs can have unprintables...
    sDescription += "Language = ";
    if (isprint(i->m_nLanguageCode >> 8) && isprint(i->m_nLanguageCode & 0x00FF)) {
        sprintf(szBuf, "'%c%c'", i->m_nLanguageCode >> 8, i->m_nLanguageCode & 0x00FF);
    }
    else {
      sprintf(szBuf, "'\?\?' (0x%04X)", i->m_nLanguageCode);
    }
    sDescription += szBuf;
    if (i->m_nCountryCode) {
        // Region Codes are optional according to ISO
        sDescription += ", Region = ";
        if (isprint(i->m_nCountryCode >> 8) && isprint(i->m_nCountryCode & 0x00FF)) {
          sprintf(szBuf, "'%c%c'", i->m_nCountryCode>>8, i->m_nCountryCode & 0x00FF);
        }
        else {
            sprintf(szBuf, "'\?\?' (0x%04X)", i->m_nCountryCode);
        }
        sDescription += szBuf;
    }
    sDescription += "\n";
    i->GetText(utf8);
    sDescription += "\"";
    sDescription += utf8;
    sDescription += "\"\n";
  }
}
References CIccLocalizedUnicode::GetText(), CIccLocalizedUnicode::m_nCountryCode, CIccLocalizedUnicode::m_nLanguageCode, and CIccTagMultiLocalizedUnicode::m_Strings.
Referenced by CIccDictEntry::Describe(), and CIccProfileIdDesc::Describe().
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
Find()
CIccLocalizedUnicode * CIccTagMultiLocalizedUnicode::Find (icLanguageCode nLanguageCode = icLanguageCodeEnglish, icCountryCode nRegionCode = icCountryCodeUSA) inherited
Name: refIccMAX::CIccTagMultiLocalizedUnicode::Find
Purpose:
Args: nLanguageCode nRegionCode
Return: Pointer to CIccLocalizedUnicode object associated with the nLanguageCode and nRegionCode or NULL if not found
{
  CIccMultiLocalizedUnicode::iterator i;
  for (i=m_Strings->begin(); i!=m_Strings->end(); i++) {
    if (i->m_nLanguageCode == nLanguageCode &&
      i->m_nCountryCode == nRegionCode) {
      return &(*i);
    }
  }
  return NULL;
}
References CIccLocalizedUnicode::m_nCountryCode, CIccLocalizedUnicode::m_nLanguageCode, and CIccTagMultiLocalizedUnicode::m_Strings.
Referenced by icGetTagText(), CIccTagMultiLocalizedUnicode::SetText(), CIccTagMultiLocalizedUnicode::SetText(), and CIccTagMultiLocalizedUnicode::SetText().
GetClassName()
virtual const char * CIccTagXmlMultiLocalizedUnicode::GetClassName () const inline virtual
Reimplemented from CIccTagMultiLocalizedUnicode.
{return "CIccTagXmlMultiLocalizedUnicode"; }
GetExtClassName()
virtual const char * CIccTagXml::GetExtClassName () const inline virtual inherited
Implements IIccExtensionTag.
{ return "CIccTagXml"; }
Referenced by icProfDescToXml(), and icXmlParseProfDesc().
GetExtDerivedClassName()
virtual const char * CIccTagXml::GetExtDerivedClassName () const inline virtual inherited
Implements IIccExtensionTag.
Reimplemented in CIccCurveXml.
{ return ""; }
GetExtension()
virtual IIccExtensionTag * CIccTagXmlMultiLocalizedUnicode::GetExtension () inline virtual
Reimplemented from CIccTag.
{return this; }
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagMultiLocalizedUnicode::GetType () const inline virtual inherited
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigMultiLocalizedUnicodeType; }
References icSigMultiLocalizedUnicodeType.
Referenced by CIccTagMultiLocalizedUnicode::Write().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
virtual CIccTag * CIccTagXmlMultiLocalizedUnicode::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTagMultiLocalizedUnicode.
{return new CIccTagXmlMultiLocalizedUnicode(*this);}
References CIccTagXmlMultiLocalizedUnicode().
ParseXml()
bool CIccTagXmlMultiLocalizedUnicode::ParseXml (xmlNode * pNode, std::string & parseStr) virtual
Implements CIccTagXml.
{
  xmlAttr *langCode;
  int n = 0;
  for (pNode = icXmlFindNode(pNode, "LocalizedText"); pNode; pNode = icXmlFindNode(pNode->next, "LocalizedText")) {
    if ((langCode = icXmlFindAttr(pNode, "LanguageCountry"))) {
      xmlNode *pText;
      for (pText = pNode->children; pText; pText = pText->next) {
        if (pText->type == XML_TEXT_NODE || pText->type == XML_CDATA_SECTION_NODE)
          break;
      }
      if (pText) {
        icUInt32Number lc = icGetSigVal(icXmlAttrValue(langCode));
        CIccUTF16String str((const char*)pText->content);
        SetText(str.c_str(), (icLanguageCode)(lc>>16), (icCountryCode)(lc & 0xffff));
        n++;
      }
      else {
        SetText("");
        n++;
      }
    }
  }
  return n>0;  //We succeed if we parsed at least one string
}
References CIccUTF16String::CIccUTF16String(), CIccUTF16String::c_str(), icGetSigVal(), icXmlAttrValue(), icXmlFindAttr(), icXmlFindNode(), CIccTagMultiLocalizedUnicode::SetText(), and CIccTagMultiLocalizedUnicode::SetText().
Read() [1/2]
bool CIccTagMultiLocalizedUnicode::Read (icUInt32Number size, CIccIO * pIO) virtual inherited
Name: CIccTagMultiLocalizedUnicode::Read
Purpose: Read in the tag contents into a data block
Since MultiLocalizedUnicode tags can be embedded in other tags this function ensures that the current read pointer will be set to the position just after the last name record.
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  icUInt32Number nNumRec, nRecSize;
  icLanguageCode nLanguageCode;
  icCountryCode nRegionCode;
  icUInt32Number nLength, nOffset, nNumChar;
  if (!m_Strings->empty())
    m_Strings->clear();
  if (sizeof(icTagTypeSignature) +
      sizeof(icUInt32Number)*3 > size)
    return false;
  if (!pIO) {
    return false;
  }
  icUInt32Number nTagPos = pIO->Tell();
  if (!pIO->Read32(&sig) ||
      !pIO->Read32(&m_nReserved) ||
      !pIO->Read32(&nNumRec) ||
      !pIO->Read32(&nRecSize))
    return false;
  if (nRecSize!=12) { //Recognized version name records are 12 bytes each
    return false;
  }
  icUInt32Number i;
  CIccLocalizedUnicode Unicode;
  icUInt32Number nLastPos = 0;
  for (i=0; i<nNumRec; i++) {
    if (4*sizeof(icUInt32Number) + (i+1)*12 > size)
      return false;
    pIO->Seek(nTagPos+4*sizeof(icUInt32Number) + i*12, icSeekSet);
    if (!pIO->Read16(&nLanguageCode) ||
        !pIO->Read16(&nRegionCode) ||
        !pIO->Read32(&nLength) ||
        !pIO->Read32(&nOffset))
      return false;
    if (nOffset+nLength > size)
      return false;
    //Find out position of the end of last named record
    if (nOffset+nLength > nLastPos)
      nLastPos = nOffset + nLength;
    nNumChar = nLength / sizeof(icUInt16Number);
    if (!Unicode.SetSize(nNumChar))
      return false;
    Unicode.m_nLanguageCode = nLanguageCode;
    Unicode.m_nCountryCode = nRegionCode;
    pIO->Seek(nTagPos+nOffset, icSeekSet);
    if (pIO->Read16(Unicode.GetBuf(), nNumChar) != (icInt32Number)nNumChar)
      return false;
    m_Strings->push_back(Unicode);
  }
  //Now seek past the last named record
  if (nLastPos > 0)
    pIO->Seek(nTagPos+nLastPos, icSeekSet);
  return true;
}
References CIccLocalizedUnicode::GetBuf(), icSeekSet, CIccLocalizedUnicode::m_nCountryCode, CIccLocalizedUnicode::m_nLanguageCode, CIccTag::m_nReserved, CIccTagMultiLocalizedUnicode::m_Strings, CIccIO::Read16(), CIccIO::Read32(), CIccIO::Seek(), CIccLocalizedUnicode::SetSize(), and CIccIO::Tell().
Referenced by CIccTagDict::Read(), and CIccProfileIdDesc::Read().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
SetText() [1/3]
void CIccTagMultiLocalizedUnicode::SetText (const icChar * szText, icLanguageCode nLanguageCode = icLanguageCodeEnglish, icCountryCode nRegionCode = icCountryCodeUSA) inherited
Name: refIccMAX::CIccTagMultiLocalizedUnicode::SetText
Purpose:
Args: sszUnicodeText nLanguageCode RegionCode
{
   CIccLocalizedUnicode *pText = Find(nLanguageCode, nRegionCode);
   if (!pText) {
     CIccLocalizedUnicode newText;
     newText.SetText(szText, nLanguageCode, nRegionCode);
     m_Strings->push_back(newText);
   }
   else {
     pText->SetText(szText, nLanguageCode, nRegionCode);
   }
}
References CIccTagMultiLocalizedUnicode::Find(), CIccTagMultiLocalizedUnicode::m_Strings, and CIccLocalizedUnicode::SetText().
Referenced by CIccProfileIdDesc::CIccProfileIdDesc(), CDevLinkWriter::begin(), main(), ParseXml(), CIccTagXmlProfileSequenceId::ParseXml(), and CIccTagXmlDict::ParseXml().
SetText() [2/3]
void CIccTagMultiLocalizedUnicode::SetText (const icUInt16Number * sszUnicode16Text, icLanguageCode nLanguageCode = icLanguageCodeEnglish, icCountryCode nRegionCode = icCountryCodeUSA) inherited
Name: refIccMAX::CIccTagMultiLocalizedUnicode::SetText
Purpose:
Args: sszUnicodeText nLanguageCode RegionCode
{
  CIccLocalizedUnicode *pText = Find(nLanguageCode, nRegionCode);
  if (!pText) {
    CIccLocalizedUnicode newText;
    newText.SetText(sszUnicode16Text, nLanguageCode, nRegionCode);
    m_Strings->push_back(newText);
  }
  else {
    pText->SetText(sszUnicode16Text, nLanguageCode, nRegionCode);
  }
}
References CIccTagMultiLocalizedUnicode::Find(), CIccTagMultiLocalizedUnicode::m_Strings, and CIccLocalizedUnicode::SetText().
Referenced by ParseXml(), CIccTagXmlProfileSequenceId::ParseXml(), and CIccTagXmlDict::ParseXml().
SetText() [3/3]
void CIccTagMultiLocalizedUnicode::SetText (const icUInt32Number * sszUnicode32Text, icLanguageCode nLanguageCode = icLanguageCodeEnglish, icCountryCode nRegionCode = icCountryCodeUSA) inherited
Name: refIccMAX::CIccTagMultiLocalizedUnicode::SetText
Purpose:
Args: sszUnicodeText nLanguageCode RegionCode
{
  CIccLocalizedUnicode *pText = Find(nLanguageCode, nRegionCode);
  if (!pText) {
    CIccLocalizedUnicode newText;
    newText.SetText(sszUnicode32Text, nLanguageCode, nRegionCode);
    m_Strings->push_back(newText);
  }
  else {
    pText->SetText(sszUnicode32Text, nLanguageCode, nRegionCode);
  }
}
References CIccTagMultiLocalizedUnicode::Find(), CIccTagMultiLocalizedUnicode::m_Strings, and CIccLocalizedUnicode::SetText().
ToXml()
bool CIccTagXmlMultiLocalizedUnicode::ToXml (std::string & xml, std::string blanks = "") virtual
Implements CIccTagXml.
{
  std::string xmlbuf;
  char data[256];
  std::string bufstr;
  CIccMultiLocalizedUnicode::iterator i;
  if (!m_Strings)
    return false;
  for (i=m_Strings->begin(); i!=m_Strings->end(); i++) {
    xml += blanks + "<LocalizedText LanguageCountry=\"";
    xml += icFixXml(xmlbuf, icGetSigStr(data, (i->m_nLanguageCode<<16) + i->m_nCountryCode));
    xml += "\"><![CDATA[";
    xml += icFixXml(xmlbuf, icUtf16ToUtf8(bufstr, i->GetBuf(), i->GetLength()));
    xml += "]]></LocalizedText>\n";
  }
  return true;
}
References CIccLocalizedUnicode::GetBuf(), CIccLocalizedUnicode::GetLength(), icFixXml(), icGetSigStr(), icUtf16ToUtf8(), CIccLocalizedUnicode::m_nCountryCode, CIccLocalizedUnicode::m_nLanguageCode, and CIccTagMultiLocalizedUnicode::m_Strings.
Validate()
icValidateStatus CIccTagMultiLocalizedUnicode::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual inherited
Name: CIccTagMultiLocalizedUnicode::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  if (!m_Strings->size()) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " - Empty tag!\n";
    rv = icMaxStatus(rv, icValidateWarning);
  }
  CIccMultiLocalizedUnicode::iterator i;
  for (i=m_Strings->begin(); i!=m_Strings->end(); i++) {
    // TODO: Validate ISO-639 Language Codes and and ISO-3166 Country codes.
    // Needs to be done against a full set of codes or many false warnings.
  }
  return rv;
}
References CIccInfo::GetSigPathName(), icMaxStatus(), icMsgValidateWarning, icValidateWarning, CIccTagMultiLocalizedUnicode::m_Strings, and CIccTag::Validate().
Referenced by CIccProfileIdDesc::Validate().
Write()
bool CIccTagMultiLocalizedUnicode::Write (CIccIO * pIO) virtual inherited
Name: CIccTagMultiLocalizedUnicode::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  icUInt32Number nNumRec=(icUInt32Number)m_Strings->size(), nRecSize=12;
  icUInt32Number nLength;
  if (!pIO) {
    return false;
  }
  if (!pIO->Write32(&sig) ||
      !pIO->Write32(&m_nReserved) ||
      !pIO->Write32(&nNumRec) ||
      !pIO->Write32(&nRecSize))
    return false;
  icUInt32Number nPos = 4*sizeof(icUInt32Number) + nNumRec*12;
  CIccMultiLocalizedUnicode::iterator i;
  for (i=m_Strings->begin(); i!=m_Strings->end(); i++) {
    nLength = i->GetLength() * sizeof(icUInt16Number);
    if (!pIO->Write16(&i->m_nLanguageCode) ||
        !pIO->Write16(&i->m_nCountryCode) ||
        !pIO->Write32(&nLength) ||
        !pIO->Write32(&nPos))
      return false;
    nPos += nLength;
  }
  for (i=m_Strings->begin(); i!=m_Strings->end(); i++) {
    nLength = i->GetLength();
    if (nLength) {
      if (pIO->Write16(i->GetBuf(), nLength) != (icInt32Number)nLength)
        return false;
    }
  }
  return true;
}
References CIccLocalizedUnicode::GetBuf(), CIccLocalizedUnicode::GetLength(), CIccTagMultiLocalizedUnicode::GetType(), CIccLocalizedUnicode::m_nCountryCode, CIccLocalizedUnicode::m_nLanguageCode, CIccTag::m_nReserved, CIccTagMultiLocalizedUnicode::m_Strings, CIccIO::Write16(), and CIccIO::Write32().
Referenced by CIccTagDict::Write(), and CIccProfileIdDesc::Write().
Field Documentation
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_Strings
CIccMultiLocalizedUnicode* CIccTagMultiLocalizedUnicode::m_Strings inherited
Referenced by CIccTagMultiLocalizedUnicode::CIccTagMultiLocalizedUnicode(), CIccTagMultiLocalizedUnicode::CIccTagMultiLocalizedUnicode(), CIccTagMultiLocalizedUnicode::~CIccTagMultiLocalizedUnicode(), CIccTagMultiLocalizedUnicode::Describe(), CIccTagMultiLocalizedUnicode::Find(), main(), CIccTagMultiLocalizedUnicode::operator=(), CIccTagMultiLocalizedUnicode::Read(), CIccTagMultiLocalizedUnicode::SetText(), CIccTagMultiLocalizedUnicode::SetText(), CIccTagMultiLocalizedUnicode::SetText(), ToXml(), CIccTagXmlProfileSequenceId::ToXml(), CIccTagXmlDict::ToXml(), CIccTagMultiLocalizedUnicode::Validate(), and CIccTagMultiLocalizedUnicode::Write().
The documentation for this class was generated from the following files:
IccXML/IccLibXML/IccTagXml.h
IccXML/IccLibXML/IccTagXml.cpp