iccDEV: CIccCurveSetCurve Class Reference
CIccCurveSetCurve Class Reference abstract
#include <IccMpeBasic.h>
Public Member Functions
virtual ~CIccCurveSetCurve ()
virtual icFloatNumber Apply (icFloatNumber v) const =0
virtual bool Begin (icElemInterp nInterp, CIccTagMultiProcessElement *pMPE)=0
virtual void Describe (std::string &sDescription, int nVerboseness=100)=0
virtual const icChar * GetClassName () const =0
virtual icCurveElemSignature GetType () const =0
virtual CIccCurveSetCurve * NewCopy () const =0
virtual bool Read (icUInt32Number size, CIccIO *pIO)=0
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccTagMultiProcessElement *pMPE=NULL, const CIccProfile *pProfile=NULL) const =0
virtual bool Write (CIccIO *pIO)=0
Static Public Member Functions
static CIccCurveSetCurve * Create (icCurveElemSignature sig)
Detailed Description
Class: CIccCurveSetCurve
Purpose: Base class for Curve Set Curves
Constructor & Destructor Documentation
~CIccCurveSetCurve()
virtual CIccCurveSetCurve::~CIccCurveSetCurve () inline virtual
{}
Member Function Documentation
Apply()
virtual icFloatNumber CIccCurveSetCurve::Apply (icFloatNumber v) const pure virtual
Implemented in CIccSegmentedCurve, CIccSingleSampledCurve, and CIccSampledCalculatorCurve.
Referenced by CIccMpeCurveSet::Apply(), and CIccMpeToneMap::Apply().
Begin()
virtual bool CIccCurveSetCurve::Begin (icElemInterp nInterp, CIccTagMultiProcessElement * pMPE) pure virtual
Implemented in CIccSegmentedCurve, CIccSingleSampledCurve, and CIccSampledCalculatorCurve.
Referenced by CIccMpeCurveSet::Begin(), and CIccMpeToneMap::Begin().
Create()
CIccCurveSetCurve * CIccCurveSetCurve::Create (icCurveElemSignature sig) static
Name: CIccCurveSetCurve::Create
Purpose:
Args:
Return:
{
  switch (sig) {
  case icSigSegmentedCurve:
    return new CIccSegmentedCurve();
  case icSigSingleSampledCurve:
    return new CIccSingleSampledCurve();
  case icSigSampledCalculatorCurve:
    return new CIccSampledCalculatorCurve();
  default:
    return NULL;
  }
}
References CIccSampledCalculatorCurve::CIccSampledCalculatorCurve(), CIccSegmentedCurve::CIccSegmentedCurve(), CIccSingleSampledCurve::CIccSingleSampledCurve(), icSigSampledCalculatorCurve, icSigSegmentedCurve, and icSigSingleSampledCurve.
Referenced by CIccMpeCurveSet::Read(), and CIccMpeToneMap::Read().
Describe()
virtual void CIccCurveSetCurve::Describe (std::string & sDescription, int nVerboseness = 100) pure virtual
Implemented in CIccSegmentedCurve, CIccSingleSampledCurve, and CIccSampledCalculatorCurve.
Referenced by CIccMpeCurveSet::Describe(), and CIccMpeToneMap::Describe().
GetClassName()
virtual const icChar * CIccCurveSetCurve::GetClassName () const pure virtual
Implemented in CIccSegmentedCurve, CIccSingleSampledCurve, and CIccSampledCalculatorCurve.
GetType()
virtual icCurveElemSignature CIccCurveSetCurve::GetType () const pure virtual
Implemented in CIccSegmentedCurve, CIccSingleSampledCurve, and CIccSampledCalculatorCurve.
Referenced by ToXmlCurve().
NewCopy()
virtual CIccCurveSetCurve * CIccCurveSetCurve::NewCopy () const pure virtual
Implemented in CIccSegmentedCurve, CIccSingleSampledCurve, and CIccSampledCalculatorCurve.
Referenced by CIccMpeCurveSet::CIccMpeCurveSet(), CIccMpeToneMap::CIccMpeToneMap(), CIccMpeCurveSet::operator=(), and CIccMpeToneMap::operator=().
Read()
virtual bool CIccCurveSetCurve::Read (icUInt32Number size, CIccIO * pIO) pure virtual
Implemented in CIccSegmentedCurve, CIccSingleSampledCurve, and CIccSampledCalculatorCurve.
Referenced by CIccMpeCurveSet::Read(), and CIccMpeToneMap::Read().
Validate()
virtual icValidateStatus CIccCurveSetCurve::Validate (std::string sigPath, std::string & sReport, const CIccTagMultiProcessElement * pMPE = NULL, const CIccProfile * pProfile = NULL) const pure virtual
Implemented in CIccSegmentedCurve, CIccSingleSampledCurve, and CIccSampledCalculatorCurve.
Referenced by CIccMpeCurveSet::Validate(), and CIccMpeToneMap::Validate().
Write()
virtual bool CIccCurveSetCurve::Write (CIccIO * pIO) pure virtual
Implemented in CIccSegmentedCurve, CIccSingleSampledCurve, and CIccSampledCalculatorCurve.
Referenced by CIccMpeCurveSet::Write(), and CIccMpeToneMap::Write().
The documentation for this class was generated from the following files:
IccProfLib/IccMpeBasic.h
IccProfLib/IccMpeBasic.cpp