iccDEV: IIccSparseMatrixEntry Class Reference
IIccSparseMatrixEntry Class Reference abstract
#include <IccSparseMatrix.h>
Public Member Functions
virtual ~IIccSparseMatrixEntry ()
virtual icFloatNumber get (int index) const =0
virtual icUInt8Number * getPtr (int index=0) const =0
virtual void init (void *pData)=0
virtual void set (int index, icFloatNumber value)=0
virtual icUInt8Number size () const =0
Detailed Description
Constructor & Destructor Documentation
~IIccSparseMatrixEntry()
virtual IIccSparseMatrixEntry::~IIccSparseMatrixEntry () inline virtual
{}
Member Function Documentation
get()
virtual icFloatNumber IIccSparseMatrixEntry::get (int index) const pure virtual
Implemented in CIccSparseMatrixUInt8, CIccSparseMatrixUInt16, CIccSparseMatrixFloat16, CIccSparseMatrixFloat32, and CIccSparseMatrixFloatNum.
Referenced by CIccSparseMatrix::Copy(), CIccTagSparseMatrixArray::Describe(), CIccSparseMatrix::Interp(), and CIccSparseMatrix::MultiplyVector().
getPtr()
virtual icUInt8Number * IIccSparseMatrixEntry::getPtr (int index = 0) const pure virtual
Implemented in CIccSparseMatrixEntry< T >, CIccSparseMatrixEntry< icFloat16Number >, CIccSparseMatrixEntry< icFloat32Number >, CIccSparseMatrixEntry< icFloatNumber >, CIccSparseMatrixEntry< icUInt16Number >, and CIccSparseMatrixEntry< icUInt8Number >.
Referenced by CIccTagXmlSparseMatrixArray::ParseXml(), CIccTagSparseMatrixArray::Read(), CIccTagXmlSparseMatrixArray::ToXml(), and CIccTagSparseMatrixArray::Write().
init()
virtual void IIccSparseMatrixEntry::init (void * pData) pure virtual
Implemented in CIccSparseMatrixEntry< T >, CIccSparseMatrixEntry< icFloat16Number >, CIccSparseMatrixEntry< icFloat32Number >, CIccSparseMatrixEntry< icFloatNumber >, CIccSparseMatrixEntry< icUInt16Number >, and CIccSparseMatrixEntry< icUInt8Number >.
Referenced by CIccSparseMatrix::Init().
set()
virtual void IIccSparseMatrixEntry::set (int index, icFloatNumber value) pure virtual
Implemented in CIccSparseMatrixUInt8, CIccSparseMatrixUInt16, CIccSparseMatrixFloat16, CIccSparseMatrixFloat32, and CIccSparseMatrixFloatNum.
Referenced by CIccSparseMatrix::Copy(), CIccSparseMatrix::FillFromFullMatrix(), CIccSparseMatrix::Interp(), and CIccSparseMatrix::Union().
size()
virtual icUInt8Number IIccSparseMatrixEntry::size () const pure virtual
Implemented in CIccSparseMatrixEntry< T >, CIccSparseMatrixEntry< icFloat16Number >, CIccSparseMatrixEntry< icFloat32Number >, CIccSparseMatrixEntry< icFloatNumber >, CIccSparseMatrixEntry< icUInt16Number >, and CIccSparseMatrixEntry< icUInt8Number >.
Referenced by CIccSparseMatrix::Init().
The documentation for this class was generated from the following file:
IccProfLib/IccSparseMatrix.h