iccDEV: IIccExtensionMpe Class Reference
IIccExtensionMpe Class Reference abstract
#include <IccTagMPE.h>
Public Member Functions
virtual const char * GetExtClassName ()=0
Detailed Description
Member Function Documentation
GetExtClassName()
virtual const char * IIccExtensionMpe::GetExtClassName () pure virtual
Implemented in CIccMpeXml.
Referenced by CIccTagXmlMultiProcessElement::ParseElement(), CIccMpeXmlCalculator::ParseImport(), CIccMpeXmlCalculator::ToXml(), and CIccTagXmlMultiProcessElement::ToXml().
The documentation for this class was generated from the following file:
IccProfLib/IccTagMPE.h