iccDEV: CIccTagXmlProfileSequenceId Class Reference
CIccTagXmlProfileSequenceId Class Reference
#include <IccTagXml.h>
Public Member Functions
virtual ~CIccTagXmlProfileSequenceId ()
bool AddProfileDescription (CIccProfile &profile)
bool AddProfileDescription (const CIccProfileIdDesc &profileDesc)
CIccProfileIdDescList::iterator begin ()
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
CIccProfileIdDescList::iterator end ()
virtual const char * GetClassName () const
virtual const char * GetExtClassName () const
virtual const char * GetExtDerivedClassName () const
virtual IIccExtensionTag * GetExtension ()
CIccProfileIdDesc * GetFirst ()
CIccProfileIdDesc * GetLast ()
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
virtual bool ParseXml (xmlNode *pNode, std::string &parseStr)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
virtual bool ToXml (std::string &xml, std::string blanks="")
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
static CIccTagProfileSequenceId * ParseMem (icUInt8Number *pMem, icUInt32Number size)
Data Fields
icUInt32Number m_nReserved
Protected Member Functions
void Cleanup ()
Protected Attributes
CIccProfileIdDescList * m_list
Detailed Description
Constructor & Destructor Documentation
~CIccTagXmlProfileSequenceId()
virtual CIccTagXmlProfileSequenceId::~CIccTagXmlProfileSequenceId () inline virtual
{}
Member Function Documentation
AddProfileDescription() [1/2]
bool CIccTagProfileSequenceId::AddProfileDescription (CIccProfile & profile) inline inherited
{ return AddProfileDescription(CIccProfileIdDesc(profile)); }
References CIccProfileIdDesc::CIccProfileIdDesc(), and CIccTagProfileSequenceId::AddProfileDescription().
AddProfileDescription() [2/2]
bool CIccTagProfileSequenceId::AddProfileDescription (const CIccProfileIdDesc & profileDesc) inherited
Name: sampleICC::CIccTagProfileSequenceId::AddProfileDescription
Purpose:
Args: CIccProfileIdDesc &profileDesc
Return: bool
{
  m_list->push_back(profileDesc);
  return true;
}
References CIccTagProfileSequenceId::m_list.
Referenced by CIccTagProfileSequenceId::AddProfileDescription().
begin()
CIccProfileIdDescList::iterator CIccTagProfileSequenceId::begin () inline inherited
{ return m_list->begin(); }
References CIccTagProfileSequenceId::m_list.
Cleanup()
void CIccTagProfileSequenceId::Cleanup () protected inherited
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagProfileSequenceId::Describe (std::string & sDescription, int nVerboseness) virtual inherited
Name: CIccTagProfileSequenceId::Describe
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icChar buf[128];
  sprintf(buf, "BEGIN ProfileSequenceIdentification_TAG\n");
  sDescription += buf;
  sDescription += "\n";
  int i;
  CIccProfileIdDescList::iterator j;
  for (i=0, j=m_list->begin(); j!=m_list->end(); i++, j++) {
    sprintf(buf, "ProfileDescription_%d:\n", i+1);
    sDescription += buf;
    j->Describe(sDescription, nVerboseness);
  }
  sprintf(buf, "END ProfileSequenceIdentification_TAG\n");
  sDescription += buf;
  sDescription += "\n";
}
References CIccProfileIdDesc::Describe(), and CIccTagProfileSequenceId::m_list.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
end()
CIccProfileIdDescList::iterator CIccTagProfileSequenceId::end () inline inherited
{ return m_list->end(); }
References CIccTagProfileSequenceId::m_list.
GetClassName()
virtual const char * CIccTagXmlProfileSequenceId::GetClassName () const inline virtual
Reimplemented from CIccTagProfileSequenceId.
{return "CIccTagXmlProfileSequenceId"; }
GetExtClassName()
virtual const char * CIccTagXml::GetExtClassName () const inline virtual inherited
Implements IIccExtensionTag.
{ return "CIccTagXml"; }
Referenced by icProfDescToXml(), and icXmlParseProfDesc().
GetExtDerivedClassName()
virtual const char * CIccTagXml::GetExtDerivedClassName () const inline virtual inherited
Implements IIccExtensionTag.
Reimplemented in CIccCurveXml.
{ return ""; }
GetExtension()
virtual IIccExtensionTag * CIccTagXmlProfileSequenceId::GetExtension () inline virtual
Reimplemented from CIccTag.
{return this; }
GetFirst()
CIccProfileIdDesc * CIccTagProfileSequenceId::GetFirst () inherited
Name: sampleICC::CIccTagProfileSequenceId::GetFirst
Purpose:
Args:
Return: CIccProfileIdDesc *
{
  if (m_list->size())
    return &(*(m_list->begin()));
  return NULL;
}
References CIccTagProfileSequenceId::m_list.
GetLast()
CIccProfileIdDesc * CIccTagProfileSequenceId::GetLast () inherited
Name: sampleICC::CIccTagProfileSequenceId::GetLast
Purpose:
Args:
Return: CIccProfileIdDesc *
{
  if (m_list->size())
    return &(*(m_list->rbegin()));
  return NULL;
}
References CIccTagProfileSequenceId::m_list.
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagProfileSequenceId::GetType () const inline virtual inherited
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigProfileSequceIdType; }
References icSigProfileSequceIdType.
Referenced by CIccTagProfileSequenceId::Validate(), and CIccTagProfileSequenceId::Write().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
virtual CIccTag * CIccTagProfileSequenceId::NewCopy () const inline virtual inherited
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
{ return new CIccTagProfileSequenceId(*this);}
References CIccTagProfileSequenceId::CIccTagProfileSequenceId().
ParseMem()
CIccTagProfileSequenceId * CIccTagProfileSequenceId::ParseMem (icUInt8Number * pMem, icUInt32Number size) static inherited
Name: CIccTagProfileSequenceId::ParseMem
Purpose:
Args:
Return:
{
  CIccMemIO IO;
  if (!IO.Attach(pMem, size))
    return NULL;
  CIccTagProfileSequenceId *pProSeqId = new CIccTagProfileSequenceId;
  if (!pProSeqId->Read(size, &IO)) {
    delete pProSeqId;
    return NULL;
  }
  return pProSeqId;
}
References CIccMemIO::Attach(), and CIccTagProfileSequenceId::Read().
ParseXml()
bool CIccTagXmlProfileSequenceId::ParseXml (xmlNode * pNode, std::string & parseStr) virtual
Implements CIccTagXml.
{
  pNode = icXmlFindNode(pNode, "ProfileSequenceId");
  if (!pNode)
    return false;
  m_list->clear();
  for (pNode = icXmlFindNode(pNode->children, "ProfileIdDesc"); pNode; pNode = icXmlFindNode(pNode->next, "ProfileIdDesc")) {
    CIccProfileIdDesc desc;
    const icChar *szDesc = icXmlAttrValue(pNode, "id");
    if (szDesc && *szDesc)
      icXmlGetHexData(&desc.m_profileID, szDesc, sizeof(desc.m_profileID));
    xmlAttr *langCode;
    xmlNode* pSubNode;
    for (pSubNode = icXmlFindNode(pNode, "LocalizedText"); pSubNode; pSubNode = icXmlFindNode(pSubNode->next, "LocalizedText")) {
      if ((langCode = icXmlFindAttr(pSubNode, "languageCountry")) &&
        pSubNode->children) {
          xmlNode *pText;
          for (pText = pSubNode->children; pText && pText->type != XML_TEXT_NODE; pText = pText->next);
          if (pText) {
            icUInt32Number lc = icGetSigVal(icXmlAttrValue(langCode));
            CIccUTF16String str((const char*)pText->content);
            desc.m_desc.SetText(str.c_str(), (icLanguageCode)(lc>>16), (icCountryCode)(lc & 0xffff));
          }
          else {
            desc.m_desc.SetText("");
          }
      }
    }
    m_list->push_back(desc);
  }
  return true;
}
References CIccUTF16String::CIccUTF16String(), CIccUTF16String::c_str(), icGetSigVal(), icXmlAttrValue(), icXmlAttrValue(), icXmlFindAttr(), icXmlFindNode(), icXmlGetHexData(), CIccProfileIdDesc::m_desc, CIccTagProfileSequenceId::m_list, CIccProfileIdDesc::m_profileID, CIccTagMultiLocalizedUnicode::SetText(), and CIccTagMultiLocalizedUnicode::SetText().
Read() [1/2]
bool CIccTagProfileSequenceId::Read (icUInt32Number size, CIccIO * pIO) virtual inherited
Name: CIccTagProfileSequenceId::Read
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icUInt32Number headerSize = sizeof(icTagTypeSignature) +
    sizeof(icUInt32Number) +
    sizeof(icUInt32Number);
  if (headerSize > size)
    return false;
  if (!pIO) {
    return false;
  }
  m_list->clear();
  icUInt32Number sig;
  icUInt32Number tagStart = pIO->Tell();
  if (!pIO->Read32(&sig))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  icUInt32Number count, i;
  if (!pIO->Read32(&count))
    return false;
  if (headerSize + (icUInt64Number)count*sizeof(icUInt32Number)*2 > size)
    return false;
  if (!count) {
    return true;
  }
  icPositionNumber *pos = new icPositionNumber[count];
  if (!pos)
    return false;
  //Read TagDir
  for (i=0; i<count; i++) {
    if (!pIO->Read32(&pos[i].offset) ||
        !pIO->Read32(&pos[i].size)) {
      delete [] pos;
      return false;
    }
  }
  CIccProfileIdDesc pid;
  for (i=0; i<count; i++) {
    if (pos[i].offset + pos[i].size > size) {
      delete [] pos;
      return false;
    }
    pIO->Seek(tagStart + pos[i].offset, icSeekSet);
    if (!pid.Read(pos[i].size, pIO)) {
      delete [] pos;
      return false;
    }
    m_list->push_back(pid);
  }
  delete [] pos;
  return true;
}
References icSeekSet, CIccTagProfileSequenceId::m_list, CIccTag::m_nReserved, icPositionNumber::offset, CIccProfileIdDesc::Read(), CIccIO::Read32(), CIccIO::Seek(), icPositionNumber::size, and CIccIO::Tell().
Referenced by CIccTagProfileSequenceId::ParseMem().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
ToXml()
bool CIccTagXmlProfileSequenceId::ToXml (std::string & xml, std::string blanks = "") virtual
Implements CIccTagXml.
{
  std::string info;
  xml += blanks + "<ProfileSequenceId>\n";
  CIccProfileIdDescList::iterator pid;
  for (pid=m_list->begin(); pid!=m_list->end(); pid++) {
    char buf[256];
    char data[256];
    char fix[256];
    std::string bufstr;
    int n;
    for (n=0; n<16; n++) {
      sprintf(buf + n*2, "%02X", pid->m_profileID.ID8[n]);
    }
    buf[n*2]='\0';
    xml += blanks + " <ProfileIdDesc id=\"";
    xml += buf;
    xml += "\">\n";
    if (pid->m_desc.m_Strings) {
      CIccMultiLocalizedUnicode::iterator i;
      for (i=pid->m_desc.m_Strings->begin(); i!=pid->m_desc.m_Strings->end(); i++) {
        sprintf(buf, "<LocalizedText LanguangeCountry=\"%s\"", icFixXml(fix, icGetSigStr(data, (i->m_nLanguageCode<<16) + i->m_nCountryCode)));
        xml += blanks + buf;
        sprintf(buf, ">%s</LocalizedText>\n", icFixXml(fix, icUtf16ToUtf8(bufstr, i->GetBuf(), i->GetLength())));
        xml += buf;
      }
    }
    xml += blanks + " </ProfileIdDesc>\n";
  }
  xml += blanks + "</ProfileSequenceId>\n";
  return true;
}
References CIccLocalizedUnicode::GetBuf(), CIccLocalizedUnicode::GetLength(), icFixXml(), icGetSigStr(), icUtf16ToUtf8(), icProfileID::ID8, CIccProfileIdDesc::m_desc, CIccTagProfileSequenceId::m_list, CIccLocalizedUnicode::m_nCountryCode, CIccLocalizedUnicode::m_nLanguageCode, CIccProfileIdDesc::m_profileID, and CIccTagMultiLocalizedUnicode::m_Strings.
Validate()
icValidateStatus CIccTagProfileSequenceId::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual inherited
Name: CIccTagProfileSequenceId::Validate
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigName = Info.GetSigPathName(sigPath);
  CIccProfileIdDescList::iterator i;
  for (i=m_list->begin(); i!=m_list->end(); i++) {
    rv = icMaxStatus(rv, i->Validate(sigPath+icGetSigPath(GetType()), sReport, pProfile));
  }
  return rv;
}
References CIccInfo::GetSigPathName(), CIccTagProfileSequenceId::GetType(), icGetSigPath(), icMaxStatus(), CIccTagProfileSequenceId::m_list, CIccTag::Validate(), and CIccProfileIdDesc::Validate().
Write()
bool CIccTagProfileSequenceId::Write (CIccIO * pIO) virtual inherited
Name: CIccTagProfileSequenceId::Write
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  if (!pIO)
    return false;
  icUInt32Number tagStart = pIO->Tell();
  if (!pIO->Write32(&sig))
    return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  icUInt32Number i, count = (icUInt32Number)m_list->size();
  pIO->Write32(&count);
  icPositionNumber *pos = new icPositionNumber[count];
  if (!pos)
    return false;
  icUInt32Number dirpos = pIO->Tell();
  //Write Unintialized TagDir
  for (i=0; i<count; i++) {
    pos[i].offset = 0;
    pos[i].size = 0;
    pIO->Write32(&pos[i].offset);
    pIO->Write32(&pos[i].size);
  }
  CIccProfileIdDescList::iterator j;
  //Write Tags
  for (i=0, j=m_list->begin(); j!= m_list->end(); i++, j++) {
    pos[i].offset = pIO->Tell();
    j->Write(pIO);
    pos[i].size = pIO->Tell() - pos[i].offset;
    pos[i].offset -= tagStart;
    pIO->Align32();
  }
  icUInt32Number endpos = pIO->Tell();
  pIO->Seek(dirpos, icSeekSet);
  //Write TagDir with offsets and sizes
  for (i=0; i<count; i++) {
    pIO->Write32(&pos[i].offset);
    pIO->Write32(&pos[i].size);
  }
  pIO->Seek(endpos, icSeekSet);
  return true;
}
References CIccIO::Align32(), CIccTagProfileSequenceId::GetType(), icSeekSet, CIccTagProfileSequenceId::m_list, CIccTag::m_nReserved, icPositionNumber::offset, CIccIO::Seek(), icPositionNumber::size, CIccIO::Tell(), CIccProfileIdDesc::Write(), and CIccIO::Write32().
Field Documentation
m_list
CIccProfileIdDescList* CIccTagProfileSequenceId::m_list protected inherited
Referenced by CIccTagProfileSequenceId::CIccTagProfileSequenceId(), CIccTagProfileSequenceId::CIccTagProfileSequenceId(), CIccTagProfileSequenceId::~CIccTagProfileSequenceId(), CIccTagProfileSequenceId::AddProfileDescription(), CIccTagProfileSequenceId::begin(), CIccTagProfileSequenceId::Describe(), CIccTagProfileSequenceId::end(), CIccTagProfileSequenceId::GetFirst(), CIccTagProfileSequenceId::GetLast(), CIccTagProfileSequenceId::operator=(), ParseXml(), CIccTagProfileSequenceId::Read(), ToXml(), CIccTagProfileSequenceId::Validate(), and CIccTagProfileSequenceId::Write().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
The documentation for this class was generated from the following files:
IccXML/IccLibXML/IccTagXml.h
IccXML/IccLibXML/IccTagXml.cpp