iccDEV: IIccStruct Class Reference
IIccStruct Class Reference abstract
#include <IccTagComposite.h>
Public Member Functions
virtual ~IIccStruct ()
virtual void Describe (std::string &sDescription, int nVerboseness) const
virtual const icChar * GetClassName () const =0
virtual const icChar * GetDisplayName () const =0
virtual std::string GetElemName (icSignature sigElem) const =0
virtual icSignature GetElemSig (const icChar *szElemName) const =0
CIccTagStruct * GetTagStruct ()
virtual IIccStruct * NewCopy (CIccTagStruct *pNewTagStruct) const =0
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const =0
Protected Member Functions
TagEntryList * getTagEntries () const
Protected Attributes
CIccTagStruct * m_pTagStruct
Detailed Description
Class: IIccStruct
Purpose: The interface for Tag Struct handler
Constructor & Destructor Documentation
~IIccStruct()
virtual IIccStruct::~IIccStruct () inline virtual
{}
Member Function Documentation
Describe()
void IIccStruct::Describe (std::string & sDescription, int nVerboseness) const virtual
Reimplemented in CIccStructUnknown.
{
  if (m_pTagStruct) {
    char buf[256];
    CIccInfo info;
    sprintf(buf, "BEGIN UNKNOWN_TAG_STRUCT ");
    sDescription += buf;
    sDescription += info.GetStructSigName(m_pTagStruct->GetTagStructType());
    sDescription += "\n\n";
    TagEntryList::iterator i;
    TagEntryList *pList = m_pTagStruct->GetElemList();
    for (i=pList->begin(); i!=pList->end(); i++) {
      i->pTag->Describe(sDescription, nVerboseness);
    }
    sDescription += "\n";
    sprintf(buf, "END TAG_STRUCT\n");
    sDescription += buf;
    sDescription += "\n";
  }
}
References CIccTag::Describe(), CIccTagStruct::GetElemList(), CIccInfo::GetStructSigName(), CIccTagStruct::GetTagStructType(), and m_pTagStruct.
Referenced by CIccTagStruct::Describe().
GetClassName()
virtual const icChar * IIccStruct::GetClassName () const pure virtual
Implemented in CIccStructUnknown, CIccStructNamedColor, CIccStructBRDF, CIccStructColorEncodingParams, CIccStructColorantInfo, CIccStructMeasurementInfo, CIccStructProfileInfo, and CIccStructTintZero.
GetDisplayName()
virtual const icChar * IIccStruct::GetDisplayName () const pure virtual
Implemented in CIccStructUnknown, CIccStructNamedColor, CIccStructBRDF, CIccStructColorEncodingParams, CIccStructColorantInfo, CIccStructMeasurementInfo, CIccStructProfileInfo, and CIccStructTintZero.
Referenced by CIccTagXmlStruct::ToXml().
GetElemName()
virtual std::string IIccStruct::GetElemName (icSignature sigElem) const pure virtual
Implemented in CIccStructUnknown.
Referenced by CIccTagXmlStruct::ToXml().
GetElemSig()
virtual icSignature IIccStruct::GetElemSig (const icChar * szElemName) const pure virtual
Implemented in CIccStructUnknown.
Referenced by CIccTagXmlStruct::ParseTag().
getTagEntries()
TagEntryList * IIccStruct::getTagEntries () const protected
{
  if (m_pTagStruct)
    return m_pTagStruct->m_ElemEntries;
  return NULL;
}
References CIccTagStruct::m_ElemEntries, and m_pTagStruct.
Referenced by CIccStructUnknown::Validate().
GetTagStruct()
CIccTagStruct * IIccStruct::GetTagStruct () inline
{ return m_pTagStruct; }
References m_pTagStruct.
NewCopy()
virtual IIccStruct * IIccStruct::NewCopy (CIccTagStruct * pNewTagStruct) const pure virtual
Implemented in CIccStructUnknown, CIccStructNamedColor, CIccStructBRDF, CIccStructColorEncodingParams, CIccStructColorantInfo, CIccStructMeasurementInfo, CIccStructProfileInfo, and CIccStructTintZero.
Referenced by CIccTagStruct::CIccTagStruct(), and CIccTagStruct::operator=().
Validate()
virtual icValidateStatus IIccStruct::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const pure virtual
Implemented in CIccStructNamedColor, CIccStructUnknown, CIccStructBRDF, and CIccStructColorantInfo.
Referenced by CIccTagStruct::Validate().
Field Documentation
m_pTagStruct
CIccTagStruct* IIccStruct::m_pTagStruct protected
Referenced by CIccStructBRDF::CIccStructBRDF(), CIccStructColorantInfo::CIccStructColorantInfo(), CIccStructColorEncodingParams::CIccStructColorEncodingParams(), CIccStructMeasurementInfo::CIccStructMeasurementInfo(), CIccStructNamedColor::CIccStructNamedColor(), CIccStructProfileInfo::CIccStructProfileInfo(), CIccStructTintZero::CIccStructTintZero(), CIccStructUnknown::CIccStructUnknown(), CIccStructUnknown::Describe(), Describe(), CIccStructUnknown::GetElem(), CIccStructNamedColor::getName(), getTagEntries(), GetTagStruct(), CIccStructNamedColor::Validate(), CIccStructBRDF::Validate(), and CIccStructColorantInfo::Validate().
The documentation for this class was generated from the following files:
IccProfLib/IccTagComposite.h
IccProfLib/IccTagComposite.cpp