iccDEV: CIccResponseCurveStruct Class Reference
CIccResponseCurveStruct Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccResponseCurveStruct (const CIccResponseCurveStruct &IRCS)
CIccResponseCurveStruct (icMeasurementUnitSig sig, icUInt16Number nChannels=0)
CIccResponseCurveStruct (icUInt16Number nChannels=0)
virtual ~CIccResponseCurveStruct ()
void Describe (std::string &sDescription, int nVerboseness)
icMeasurementUnitSig GetMeasurementType () const
icUInt16Number GetNumChannels () const
CIccResponse16List * GetResponseList (icUInt16Number nChannel)
CIccResponseCurveStruct * GetThis ()
icXYZNumber * GetXYZ (icUInt32Number index)
CIccResponseCurveStruct & operator= (const CIccResponseCurveStruct &RespCurveStruct)
bool Read (icUInt32Number size, CIccIO *pIO)
icValidateStatus Validate (std::string &sReport)
bool Write (CIccIO *pIO)
Protected Attributes
icXYZNumber * m_maxColorantXYZ
icMeasurementUnitSig m_measurementUnitSig
icUInt16Number m_nChannels
CIccResponse16List * m_Response16ListArray
Detailed Description
Data Class: CIccResponseCurveStruct
Purpose: The base class for response curve structure
Constructor & Destructor Documentation
CIccResponseCurveStruct() [1/3]
CIccResponseCurveStruct::CIccResponseCurveStruct (icMeasurementUnitSig sig, icUInt16Number nChannels = 0)
Name: CIccResponseCurveStruct::CIccResponseCurveStruct
Purpose: Constructor
Args: sig = measurement unit signature indicating the type of measurement data, nChannels = number of channels
{
  m_nChannels = nChannels;
  m_measurementUnitSig = sig;
  m_maxColorantXYZ = (icXYZNumber*)calloc(nChannels, sizeof(icXYZNumber));
  m_Response16ListArray = new CIccResponse16List[nChannels];
}
References m_maxColorantXYZ, m_measurementUnitSig, m_nChannels, and m_Response16ListArray.
Referenced by CIccTagResponseCurveSet16::NewResponseCurves(), and CIccTagXmlResponseCurveSet16::ParseXml().
CIccResponseCurveStruct() [2/3]
CIccResponseCurveStruct::CIccResponseCurveStruct (icUInt16Number nChannels = 0)
Name: CIccResponseCurveStruct::CIccResponseCurveStruct
Purpose: Constructor
Args: nChannels = number of channels
{
  m_nChannels = nChannels;
  m_maxColorantXYZ = (icXYZNumber*)calloc(nChannels, sizeof(icXYZNumber));
  m_Response16ListArray = new CIccResponse16List[nChannels];
}
References m_maxColorantXYZ, m_nChannels, and m_Response16ListArray.
Referenced by CIccTagResponseCurveSet16::Read().
CIccResponseCurveStruct() [3/3]
CIccResponseCurveStruct::CIccResponseCurveStruct (const CIccResponseCurveStruct & IRCS)
Name: CIccResponseCurveStruct::CIccResponseCurveStruct
Purpose: Copy Constructor
Args: IRCS = The CIccTagUnknown object to be copied
{
  m_nChannels = IRCS.m_nChannels;
  m_measurementUnitSig = IRCS.m_measurementUnitSig;
  m_maxColorantXYZ = (icXYZNumber*)calloc(m_nChannels, sizeof(icXYZNumber));
  memcpy(m_maxColorantXYZ, IRCS.m_maxColorantXYZ, m_nChannels*sizeof(icXYZNumber));
  m_Response16ListArray = new CIccResponse16List[m_nChannels];
  for (icUInt32Number i=0; i<m_nChannels; i++)
    m_Response16ListArray[i] = IRCS.m_Response16ListArray[i];
}
References m_maxColorantXYZ, m_measurementUnitSig, m_nChannels, and m_Response16ListArray.
~CIccResponseCurveStruct()
CIccResponseCurveStruct::~CIccResponseCurveStruct () virtual
Name: CIccResponseCurveStruct::~CIccResponseCurveStruct
Purpose: Destructor
{
  if (m_maxColorantXYZ)
    free(m_maxColorantXYZ);
  if (m_Response16ListArray)
    delete [] m_Response16ListArray;
}
References m_maxColorantXYZ, and m_Response16ListArray.
Member Function Documentation
Describe()
void CIccResponseCurveStruct::Describe (std::string & sDescription, int nVerboseness)
Name: CIccResponseCurveStruct::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
{
  icChar buf[128];
  CIccInfo Fmt;
  CIccResponse16List nResponseList;
  CIccResponse16List::iterator j;
  sDescription += "Measurement Unit: ";
  sDescription += Fmt.GetMeasurementUnit((icSignature)GetMeasurementType()); sDescription += "\n";
  for (int i=0; i<m_nChannels; i++) {
    nResponseList = m_Response16ListArray[i];
    sDescription += "\n";
    sprintf(buf, "Maximum Colorant XYZ Measurement for Channel-%u : X=%.4lf, Y=%.4lf, Z=%.4lf\n", i+1,
      icFtoD(m_maxColorantXYZ[i].X), icFtoD(m_maxColorantXYZ[i].Y), icFtoD(m_maxColorantXYZ[i].Z));
    sDescription += buf;
    sprintf(buf, "Number of Measurements for Channel-%u : %u\n", i+1, (icUInt32Number)nResponseList.size());
    sDescription += buf;
    sprintf(buf, "Measurement Data for Channel-%u follows:\n", i+1);
    sDescription += buf;
    for (j=nResponseList.begin(); j!=nResponseList.end(); j++) {
      sprintf(buf, "Device Value= %u : Measurement Value= %.4lf\n", j->deviceCode, icFtoD(j->measurementValue));
      sDescription += buf;
    }
  }
}
References icResponse16Number::deviceCode, GetMeasurementType(), CIccInfo::GetMeasurementUnit(), icFtoD(), m_maxColorantXYZ, m_nChannels, m_Response16ListArray, icResponse16Number::measurementValue, icXYZNumber::X, icXYZNumber::Y, and icXYZNumber::Z.
Referenced by CIccTagResponseCurveSet16::Describe().
GetMeasurementType()
icMeasurementUnitSig CIccResponseCurveStruct::GetMeasurementType () const inline
{return m_measurementUnitSig;}
References m_measurementUnitSig.
Referenced by Describe(), CIccTagResponseCurveSet16::GetResponseCurves(), CIccTagXmlResponseCurveSet16::ToXml(), and Write().
GetNumChannels()
icUInt16Number CIccResponseCurveStruct::GetNumChannels () const inline
{return m_nChannels;}
References m_nChannels.
Referenced by CIccTagXmlResponseCurveSet16::ToXml().
GetResponseList()
CIccResponse16List * CIccResponseCurveStruct::GetResponseList (icUInt16Number nChannel) inline
{return &m_Response16ListArray[nChannel];}
References m_Response16ListArray.
Referenced by CIccTagXmlResponseCurveSet16::ParseXml(), and CIccTagXmlResponseCurveSet16::ToXml().
GetThis()
CIccResponseCurveStruct * CIccResponseCurveStruct::GetThis () inline
{return this;}
Referenced by CIccTagResponseCurveSet16::GetFirstCurves(), CIccTagResponseCurveSet16::GetNextCurves(), and CIccTagResponseCurveSet16::GetResponseCurves().
GetXYZ()
icXYZNumber * CIccResponseCurveStruct::GetXYZ (icUInt32Number index) inline
{return &m_maxColorantXYZ[index];}
References m_maxColorantXYZ.
Referenced by CIccTagXmlResponseCurveSet16::ParseXml(), and CIccTagXmlResponseCurveSet16::ToXml().
operator=()
CIccResponseCurveStruct & CIccResponseCurveStruct::operator= (const CIccResponseCurveStruct & RespCurveStruct)
Name: CIccResponseCurveStruct::operator=
Purpose: Copy Operator
Args: RespCurveStruct = The CIccResponseCurveStruct object to be copied
{
  if (&RespCurveStruct == this)
    return *this;
  m_nChannels = RespCurveStruct.m_nChannels;
  m_measurementUnitSig = RespCurveStruct.m_measurementUnitSig;
  if (m_maxColorantXYZ)
    free(m_maxColorantXYZ);
  m_maxColorantXYZ = (icXYZNumber*)calloc(m_nChannels, sizeof(icXYZNumber));
  memcpy(m_maxColorantXYZ, RespCurveStruct.m_maxColorantXYZ, m_nChannels*sizeof(icXYZNumber));
  if (m_Response16ListArray)
    delete [] m_Response16ListArray;
  m_Response16ListArray = new CIccResponse16List[m_nChannels];
  for (icUInt32Number i=0; i<m_nChannels; i++)
    m_Response16ListArray[i] = RespCurveStruct.m_Response16ListArray[i];
  return *this;
}
References m_maxColorantXYZ, m_measurementUnitSig, m_nChannels, and m_Response16ListArray.
Referenced by CIccTagResponseCurveSet16::NewResponseCurves(), and CIccTagResponseCurveSet16::Read().
Read()
bool CIccResponseCurveStruct::Read (icUInt32Number size, CIccIO * pIO)
Name: CIccResponseCurveStruct::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
{
  if (!m_nChannels)
    return false;
  if (sizeof(icTagTypeSignature) +
      m_nChannels * (sizeof(icUInt32Number) +
        sizeof(icXYZNumber) +
        sizeof(icResponse16Number)) > size)
    return false;
  if (!pIO) {
    return false;
  }
  if (!pIO->Read32(&m_measurementUnitSig))
    return false;
  icUInt32Number* nMeasurements = new icUInt32Number[m_nChannels];
  if (pIO->Read32(&nMeasurements[0],m_nChannels) != m_nChannels) {
    delete[] nMeasurements;
    return false;
  }
  icUInt32Number nNum32 = m_nChannels*sizeof(icXYZNumber)/sizeof(icS15Fixed16Number);
  if (pIO->Read32(&m_maxColorantXYZ[0], nNum32) != (icInt32Number)nNum32) {
    delete[] nMeasurements;
    return false;
  }
  icResponse16Number nResponse16 = {};
  CIccResponse16List nResponseList;
  for (int i = 0; i<m_nChannels; i++) {
    if (!nResponseList.empty())
      nResponseList.clear();
    for (int j=0; j<(int)nMeasurements[i]; j++) {
      if (!pIO->Read16(&nResponse16.deviceCode) ||
         !pIO->Read16(&nResponse16.reserved)   ||
         !pIO->Read32(&nResponse16.measurementValue)) {
        delete[] nMeasurements;
        return false;
      }
      nResponseList.push_back(nResponse16);
    }
    m_Response16ListArray[i] = nResponseList;
  }
  delete [] nMeasurements;
  return true;
}
References icResponse16Number::deviceCode, m_maxColorantXYZ, m_measurementUnitSig, m_nChannels, m_Response16ListArray, icResponse16Number::measurementValue, CIccIO::Read16(), CIccIO::Read32(), and icResponse16Number::reserved.
Referenced by CIccTagResponseCurveSet16::Read().
Validate()
icValidateStatus CIccResponseCurveStruct::Validate (std::string & sReport)
Name: CIccResponseCurveStruct::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
{
  icValidateStatus rv = icValidateOK;
  CIccInfo Info;
  std::string sSigName = Info.GetSigName(m_measurementUnitSig);
  switch(m_measurementUnitSig) {
  case icSigStatusA:
  case icSigStatusE:
  case icSigStatusI:
  case icSigStatusT:
  case icSigStatusM:
  case icSigDN:
  case icSigDNP:
  case icSigDNN:
  case icSigDNNP:
    break;
  default:
    sReport += icMsgValidateNonCompliant;
    sReport += sSigName;
    sReport += " - Unknown measurement unit signature.\n";
    rv = icMaxStatus(rv, icValidateNonCompliant);
  }
  if (!m_nChannels) {
    sReport += icMsgValidateNonCompliant;
    sReport += sSigName;
    sReport += " - Incorrect number of channels.\n";
    rv = icMaxStatus(rv, icValidateNonCompliant);
    return rv;
  }
  for (int i=0; i<m_nChannels; i++) {
    rv = icMaxStatus(rv, Info.CheckData(sReport, m_maxColorantXYZ[i], "Max Colorant XYZ"));
  }
  return rv;
}
References CIccInfo::CheckData(), CIccInfo::GetSigName(), icMaxStatus(), icMsgValidateNonCompliant, icSigDN, icSigDNN, icSigDNNP, icSigDNP, icSigStatusA, icSigStatusE, icSigStatusI, icSigStatusM, icSigStatusT, icValidateNonCompliant, icValidateOK, m_maxColorantXYZ, m_measurementUnitSig, and m_nChannels.
Referenced by CIccTagResponseCurveSet16::Validate().
Write()
bool CIccResponseCurveStruct::Write (CIccIO * pIO)
Name: CIccResponseCurveStruct::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
{
  if (!m_nChannels)
    return false;
  icMeasurementUnitSig sig = GetMeasurementType();
  if (!pIO) {
    return false;
  }
  if (!pIO->Write32(&sig))
    return false;
  if (m_nChannels) {
    icUInt32Number* nMeasurements = new icUInt32Number[m_nChannels];
    for (int i=0; i<m_nChannels; i++)
      nMeasurements[i] = (icUInt32Number)m_Response16ListArray[i].size();
    if (pIO->Write32(&nMeasurements[0],m_nChannels) != m_nChannels)
      return false;
    delete [] nMeasurements;
    icUInt32Number nNum32 = m_nChannels*sizeof(icXYZNumber)/sizeof(icS15Fixed16Number);
    if (pIO->Write32(&m_maxColorantXYZ[0], nNum32) != (icInt32Number)nNum32)
      return false;
  }
  else
    return false;
  CIccResponse16List nResponseList;
  CIccResponse16List::iterator j;
  for (int i = 0; i<m_nChannels; i++) {
    nResponseList = m_Response16ListArray[i];
    for (j=nResponseList.begin(); j!=nResponseList.end(); j++) {
      if (!pIO->Write16(&j->deviceCode) ||
         !pIO->Write16(&j->reserved)   ||
         !pIO->Write32(&j->measurementValue))
        return false;
    }
    nResponseList.clear();
  }
  return true;
}
References icResponse16Number::deviceCode, GetMeasurementType(), m_maxColorantXYZ, m_nChannels, m_Response16ListArray, icResponse16Number::measurementValue, icResponse16Number::reserved, CIccIO::Write16(), and CIccIO::Write32().
Referenced by CIccTagResponseCurveSet16::Write().
Field Documentation
m_maxColorantXYZ
icXYZNumber* CIccResponseCurveStruct::m_maxColorantXYZ protected
Referenced by CIccResponseCurveStruct(), CIccResponseCurveStruct(), CIccResponseCurveStruct(), ~CIccResponseCurveStruct(), Describe(), GetXYZ(), operator=(), Read(), Validate(), and Write().
m_measurementUnitSig
icMeasurementUnitSig CIccResponseCurveStruct::m_measurementUnitSig protected
Referenced by CIccResponseCurveStruct(), CIccResponseCurveStruct(), GetMeasurementType(), operator=(), Read(), and Validate().
m_nChannels
icUInt16Number CIccResponseCurveStruct::m_nChannels protected
Referenced by CIccResponseCurveStruct(), CIccResponseCurveStruct(), CIccResponseCurveStruct(), Describe(), GetNumChannels(), operator=(), Read(), Validate(), and Write().
m_Response16ListArray
CIccResponse16List* CIccResponseCurveStruct::m_Response16ListArray protected
Referenced by CIccResponseCurveStruct(), CIccResponseCurveStruct(), CIccResponseCurveStruct(), ~CIccResponseCurveStruct(), Describe(), GetResponseList(), operator=(), Read(), and Write().
The documentation for this class was generated from the following files:
IccProfLib/IccTagBasic.h
IccProfLib/IccTagBasic.cpp