iccDEV: CIccMatrixMath Class Reference
CIccMatrixMath Class Reference
#include <IccMatrixMath.h>
Public Member Functions
CIccMatrixMath (const CIccMatrixMath &mat)
CIccMatrixMath (icUInt16Number nRows, icUInt16Number nCols, bool bInitIdentity=false)
virtual ~CIccMatrixMath ()
virtual void dumpMtx (std::string &str) const
icFloatNumber * entry (icUInt16Number nRow, icUInt16Number nCol=0)
const icFloatNumber * entry (icUInt16Number nRow, icUInt16Number nCol=0) const
virtual icUInt16Number GetCols () const
virtual icUInt16Number GetRows () const
bool Invert ()
virtual bool isIdentityMtx () const
CIccMatrixMath * Mult (const CIccMatrixMath *matrix) const
icFloatNumber RowSum (icUInt16Number nRow) const
void Scale (icFloatNumber v)
bool SetRange (const icSpectralRange &from, const icSpectralRange &to)
virtual void VectorMult (icFloatNumber *pDst, const icFloatNumber *pSrc) const
void VectorScale (const icFloatNumber *vec)
Static Public Member Functions
static CIccMatrixMath * rangeMap (const icSpectralRange &from, const icSpectralRange &to)
Protected Attributes
icUInt16Number m_nCols
icUInt16Number m_nRows
icFloatNumber * m_vals
Detailed Description
Type: Class
Purpose: Object for performing matrix/vector math
Constructor & Destructor Documentation
CIccMatrixMath() [1/2]
CIccMatrixMath::CIccMatrixMath (icUInt16Number nRows, icUInt16Number nCols, bool bInitIdentity = false)
Name: CIccMatrixMath::CIccMatrixMath
Purpose: Constructor
{
  int nTotal = nRows * nCols;
  int nMin = nRows<nCols ? nRows : nCols;
  m_nRows = nRows;
  m_nCols = nCols;
  m_vals = new icFloatNumber[nTotal];
  if (bInitIdentity) {
    memset(m_vals, 0, nTotal * sizeof(icFloatNumber));
    int i;
    for (i=0; i<nMin; i++) {
      icFloatNumber *row = entry(nRows-1-i);
      row[nCols-1-i] = 1.0;
    }
  }
}
References entry(), m_nCols, m_nRows, and m_vals.
Referenced by CIccMpeEmissionMatrix::Begin(), CIccMpeInvEmissionMatrix::Begin(), CIccMpeEmissionCLUT::Begin(), CIccMpeReflectanceCLUT::Begin(), CIccMpeEmissionObserver::Begin(), CIccMpeReflectanceObserver::Begin(), IIccProfileConnectionConditions::getEmissiveObserver(), CIccTagSpectralViewingConditions::getObserverMatrix(), Mult(), and rangeMap().
CIccMatrixMath() [2/2]
CIccMatrixMath::CIccMatrixMath (const CIccMatrixMath & matrix)
Name: CIccMatrixMath::CIccMatrixMath
Purpose: Copy Constructor
{
  int nTotal = matrix.m_nRows * matrix.m_nCols;
  m_nRows = matrix.m_nRows;
  m_nCols = matrix.m_nCols;
  m_vals = new icFloatNumber[nTotal];
  memcpy(m_vals, matrix.m_vals, nTotal*sizeof(icFloatNumber));
}
References m_nCols, m_nRows, and m_vals.
Referenced by CIccMpeReflectanceObserver::Begin().
~CIccMatrixMath()
CIccMatrixMath::~CIccMatrixMath () virtual
Name: CIccMatrixMath::~CIccMatrixMath
Purpose: Destructor
{
  if (m_vals)
    delete[] m_vals;
}
References m_vals.
Member Function Documentation
dumpMtx()
void CIccMatrixMath::dumpMtx (std::string & str) const virtual
Name: CIccMatrixMath::dump
Purpose: dumps the context of the step
{
  char buf[80];
  int i, j;
  const icFloatNumber *row = entry(0);
  for (j=0; j<m_nRows; j++) {
    for (i=0; i<m_nCols; i++) {
      sprintf(buf, ICCMTXSTEPDUMPFMT, row[i]);
      str += buf;
    }
    str += "\n";
    row = &row[m_nCols];
  }
}
References entry(), m_nCols, and m_nRows.
entry() [1/2]
icFloatNumber * CIccMatrixMath::entry (icUInt16Number nRow, icUInt16Number nCol = 0) inline
{ return &m_vals[(int)nRow*m_nCols + nCol]; }
References m_nCols, and m_vals.
Referenced by CIccMatrixMath(), CIccMpeEmissionMatrix::Begin(), CIccMpeInvEmissionMatrix::Begin(), CIccMpeEmissionCLUT::Begin(), CIccMpeReflectanceCLUT::Begin(), CIccMpeEmissionObserver::Begin(), CIccMpeReflectanceObserver::Begin(), IIccProfileConnectionConditions::getEmissiveObserver(), CIccTagSpectralViewingConditions::getObserverMatrix(), Mult(), Scale(), SetRange(), and VectorScale().
entry() [2/2]
const icFloatNumber * CIccMatrixMath::entry (icUInt16Number nRow, icUInt16Number nCol = 0) const inline
{ return &m_vals[(int)nRow*m_nCols + nCol]; }
References m_nCols, and m_vals.
Referenced by dumpMtx(), isIdentityMtx(), Mult(), RowSum(), and VectorMult().
GetCols()
virtual icUInt16Number CIccMatrixMath::GetCols () const inline virtual
{ return m_nCols; }
References m_nCols.
GetRows()
virtual icUInt16Number CIccMatrixMath::GetRows () const inline virtual
{ return m_nRows; }
References m_nRows.
Invert()
bool CIccMatrixMath::Invert ()
Name: CIccMatrixMath::Invert
Purpose: Inverts the matrix
{
  if (m_nRows==3 && m_nCols==3) {
    icMatrixInvert3x3(m_vals);
    return true;
  }
  return false;
}
References icMatrixInvert3x3(), m_nCols, m_nRows, and m_vals.
Referenced by CIccMpeInvEmissionMatrix::Begin().
isIdentityMtx()
bool CIccMatrixMath::isIdentityMtx () const virtual
Name: CIccMatrixMath::isIdentityMtx
Purpose: Determines if applying this step will result in negligible change in data
{
  if (m_nCols!=m_nRows)
    return false;
  int i, j;
  for (j=0; j<m_nRows; j++) {
    for (i=0; i<m_nCols; i++) {
      icFloatNumber v = *(entry(j, i));
      if (i==j) {
        if (v<1.0f-icNearRange || v>1.0f+icNearRange)
          return false;
      }
      else {
        if (v<-icNearRange ||v>icNearRange)
          return false;
      }
    }
  }
  return true;
}
References entry(), m_nCols, and m_nRows.
Mult()
CIccMatrixMath * CIccMatrixMath::Mult (const CIccMatrixMath * matrix) const
Name: CIccMatrixMath::Mult
Purpose: Creates a new CIccMatrixMath that is the result of concatentating another matrix with this matrix. (IE result = matrix * this).
{
  icUInt16Number mCols = matrix->m_nCols;
  icUInt16Number mRows = matrix->m_nRows;
  if (m_nRows != mCols)
    return NULL;
  CIccMatrixMath *pNew = new CIccMatrixMath(mRows, m_nCols);
  int i, j, k;
  for (j=0; j<mRows; j++) {
    const icFloatNumber *row = matrix->entry(j);
    for (i=0; i<m_nCols; i++) {
      icFloatNumber *to = pNew->entry(j, i);
      const icFloatNumber *from = entry(0, i);
      *to = 0.0f;
      for (k=0; k<m_nRows; k++) {
        *to += row[k] * (*from);
        from += m_nCols;
      }
    }
  }
  return pNew;
}
References CIccMatrixMath(), entry(), entry(), m_nCols, and m_nRows.
Referenced by CIccMpeReflectanceCLUT::Begin(), CIccMpeReflectanceObserver::Begin(), and IIccProfileConnectionConditions::getReflectanceObserver().
rangeMap()
CIccMatrixMath * CIccMatrixMath::rangeMap (const icSpectralRange & srcRange, const icSpectralRange & dstRange) static
Name: CIccMatrixMath::rangeMap
Purpose: This helper function generates a matrix math object that can be used to convert spectral vectors from one spectral range to another using linear interpolation.
{
  if (srcRange.steps != dstRange.steps ||
      srcRange.start != dstRange.start ||
      srcRange.end != dstRange.end) {
    CIccMatrixMath *mtx = new CIccMatrixMath(dstRange.steps, srcRange.steps);
    mtx->SetRange(srcRange, dstRange);
    return mtx;
  }
  return NULL;
}
References CIccMatrixMath(), icSpectralRange::end, SetRange(), icSpectralRange::start, and icSpectralRange::steps.
Referenced by CIccTagSpectralViewingConditions::applyRangeToObserver(), CIccMpeReflectanceCLUT::Begin(), CIccMpeReflectanceObserver::Begin(), IIccProfileConnectionConditions::getEmissiveObserver(), IIccProfileConnectionConditions::getObserverIlluminantScaleFactor(), IIccProfileConnectionConditions::getObserverWhiteScaleFactor(), and IIccProfileConnectionConditions::getReflectanceObserver().
RowSum()
icFloatNumber CIccMatrixMath::RowSum (icUInt16Number nRow) const
Name: CIccMatrixMath::RowSum
Purpose: Creates a new CIccMatrixMath step that is the result of multiplying the matrix of this object to the scale of another object.
{
  icFloatNumber rv=0;
  int i;
  const icFloatNumber *row = entry(nRow);
  for (i=0; i<m_nCols; i++) {
    rv += row[i];
  }
  return rv;
}
References entry(), and m_nCols.
Referenced by IIccProfileConnectionConditions::getReflectanceObserver().
Scale()
void CIccMatrixMath::Scale (icFloatNumber v)
Name: CIccMatrixMath::Scale
Purpose: Multiplies all values in matrix by a single scale factor
{
  int i, j;
  for (j=0; j<m_nRows; j++) {
    icFloatNumber *row = entry(j);
    for (i=0; i<m_nCols; i++) {
      row[i] *= v;
    }
  }
}
References entry(), m_nCols, and m_nRows.
Referenced by IIccProfileConnectionConditions::getReflectanceObserver().
SetRange()
bool CIccMatrixMath::SetRange (const icSpectralRange & srcRange, const icSpectralRange & dstRange)
Name: CIccMatrixMath::SetRange
Purpose: Fills a matrix math object that can be used to convert spectral vectors from one spectral range to another using linear interpolation.
{
  if (m_nRows != dstRange.steps || m_nCols != srcRange.steps)
    return false;
  icUInt16Number d;
  icFloatNumber srcStart = icF16toF(srcRange.start);
  icFloatNumber srcEnd = icF16toF(srcRange.end);
  icFloatNumber dstStart = icF16toF(dstRange.start);
  icFloatNumber dstEnd = icF16toF(dstRange.end);
  icFloatNumber srcDiff = srcEnd - srcStart;
  icFloatNumber dstDiff = dstEnd - dstStart;
  icFloatNumber srcScale = (srcEnd - srcStart) / (srcRange.steps-1);
  icFloatNumber dstScale = (dstEnd - dstStart ) / (dstRange.steps - 1);
  icFloatNumber *data=entry(0);
  memset(data, 0, dstRange.steps*srcRange.steps*sizeof(icFloatNumber));
  for (d=0; d<dstRange.steps; d++) {
    icFloatNumber *r = entry(d);
    icFloatNumber w = dstStart + (icFloatNumber)d * dstScale;
    if (w<srcStart) {
      r[0] = 1.0;
    }
    else if (w>=srcEnd) {
      r[srcRange.steps-1] = 1.0;
    }
    else {
      icUInt16Number p = (icUInt16Number)((w - srcStart) / srcScale);
      icFloatNumber p2 = (w - (srcStart + p * srcScale)) / srcScale;
      if (p2<0.00001) {
        r[p] = 1.0f;
      }
      else if (p2>0.99999) {
        r[p+1] = 1.0f;
      }
      else {
        r[p] = 1.0f - p2;
        r[p+1] = p2;
      }
    }
  }
  return true;
}
References icSpectralRange::end, entry(), icF16toF(), m_nCols, m_nRows, icSpectralRange::start, and icSpectralRange::steps.
Referenced by rangeMap().
VectorMult()
void CIccMatrixMath::VectorMult (icFloatNumber * pDst, const icFloatNumber * pSrc) const virtual
Name: CIccMatrixMath::VectorMult
Purpose: Multiplies pSrc vector passed by a matrix resulting in a pDst vector
{
  int i, j;
  const icFloatNumber *row = entry(0);
  for (j=0; j<m_nRows; j++) {
    pDst[j] = 0.0f;
    for (i=0; i<m_nCols; i++) {
      if (row[i]!=0.0)
        pDst[j] += row[i] * pSrc[i];
    }
    row = &row[m_nCols];
  }
}
References entry(), m_nCols, and m_nRows.
Referenced by CIccMpeEmissionMatrix::Apply(), CIccMpeInvEmissionMatrix::Apply(), CIccMpeSpectralObserver::Apply(), CIccTagSpectralViewingConditions::applyRangeToObserver(), CIccMpeEmissionMatrix::Begin(), CIccMpeInvEmissionMatrix::Begin(), CIccMpeEmissionCLUT::Begin(), CIccMpeReflectanceCLUT::Begin(), CIccMpeEmissionObserver::Begin(), CIccMpeReflectanceObserver::Begin(), IIccProfileConnectionConditions::getEmissiveObserver(), IIccProfileConnectionConditions::getObserverIlluminantScaleFactor(), CIccTagSpectralViewingConditions::getObserverMatrix(), and IIccProfileConnectionConditions::getObserverWhiteScaleFactor().
VectorScale()
void CIccMatrixMath::VectorScale (const icFloatNumber * vec)
Name: CIccMatrixMath::VectorScale
Purpose: Multiplies each row by values of vector passed in
{
  int i, j;
  for (j=0; j<m_nRows; j++) {
    icFloatNumber *row = entry(j);
    for (i=0; i<m_nCols; i++) {
      row[i] *= vec[i];
    }
  }
}
References entry(), m_nCols, and m_nRows.
Referenced by IIccProfileConnectionConditions::getReflectanceObserver().
Field Documentation
m_nCols
icUInt16Number CIccMatrixMath::m_nCols protected
Referenced by CIccMatrixMath(), CIccMatrixMath(), dumpMtx(), entry(), entry(), GetCols(), Invert(), isIdentityMtx(), Mult(), RowSum(), Scale(), SetRange(), VectorMult(), and VectorScale().
m_nRows
icUInt16Number CIccMatrixMath::m_nRows protected
Referenced by CIccMatrixMath(), CIccMatrixMath(), dumpMtx(), GetRows(), Invert(), isIdentityMtx(), Mult(), Scale(), SetRange(), VectorMult(), and VectorScale().
m_vals
icFloatNumber* CIccMatrixMath::m_vals protected
Referenced by CIccMatrixMath(), CIccMatrixMath(), ~CIccMatrixMath(), entry(), entry(), and Invert().
The documentation for this class was generated from the following files:
IccProfLib/IccMatrixMath.h
IccProfLib/IccMatrixMath.cpp