iccDEV: CIccCombinedConnectionConditions Class Reference
CIccCombinedConnectionConditions Class Reference
#include <IccPcc.h>
Public Member Functions
CIccCombinedConnectionConditions (CIccProfile *pProfile, IIccProfileConnectionConditions *pAppliedPCC, bool bReflectance=false)
virtual ~CIccCombinedConnectionConditions ()
virtual CIccTagMultiProcessElement * getCustomToStandardPcc ()
icFloatNumber * getEmissiveObserver (const icSpectralRange &range, const icFloatNumber *pWhite, icFloatNumber *obsMatrix=NULL)
virtual void getLumIlluminantXYZ (icFloatNumber *pXYZLum)
virtual bool getMediaWhiteXYZ (icFloatNumber *pXYZ)
virtual void getNormIlluminantXYZ (icFloatNumber *pXYZ)
icFloatNumber getObserverIlluminantScaleFactor ()
icFloatNumber getObserverWhiteScaleFactor (const icFloatNumber *pWhite, const icSpectralRange &whiteRange)
icFloatNumber getPccCCT ()
icIlluminant getPccIlluminant ()
icStandardObserver getPccObserver ()
virtual const CIccTagSpectralViewingConditions * getPccViewingConditions ()
CIccMatrixMath * getReflectanceObserver (const icSpectralRange &rangeRef)
virtual CIccTagMultiProcessElement * getStandardToCustomPcc ()
bool hasIlluminantSPD ()
bool isEquivalentPcc (IIccProfileConnectionConditions &IPCC)
bool isStandardPcc ()
Protected Attributes
bool m_bValidIllumXYZ
bool m_bValidMediaXYZ
icFloatNumber m_illuminantXYZ [3]
icFloatNumber m_illuminantXYZLum [3]
icFloatNumber m_mediaXYZ [3]
IIccProfileConnectionConditions * m_pPCC
CIccTagSpectralViewingConditions * m_pViewingConditions
Detailed Description
Type: Class
Purpose: Class used for defining combined connection conditions where the viewing conditions are the combined result of information from the profile and external connection conditions based on whether reflectance or emission is used.
Constructor & Destructor Documentation
CIccCombinedConnectionConditions()
CIccCombinedConnectionConditions::CIccCombinedConnectionConditions (CIccProfile * pProfile, IIccProfileConnectionConditions * pAppliedPCC, bool bReflectance = false)
{
  if (pAppliedPCC) {
      const CIccTagSpectralViewingConditions *pView = pAppliedPCC->getPccViewingConditions();
      if (bReflectance) {
          m_pPCC = pAppliedPCC;
          m_pViewingConditions = NULL;
          m_illuminantXYZ[0] = pView->m_illuminantXYZ.X / pView->m_illuminantXYZ.Y;
          m_illuminantXYZ[1] = pView->m_illuminantXYZ.Y / pView->m_illuminantXYZ.Y;
          m_illuminantXYZ[2] = pView->m_illuminantXYZ.Z / pView->m_illuminantXYZ.Y;
          m_illuminantXYZLum[0] = pView->m_illuminantXYZ.X;
          m_illuminantXYZLum[1] = pView->m_illuminantXYZ.Y;
          m_illuminantXYZLum[2] = pView->m_illuminantXYZ.Z;
          m_bValidMediaXYZ = pProfile->calcMediaWhiteXYZ(m_mediaXYZ, pAppliedPCC);
      }
      else {
          m_pPCC = pAppliedPCC;
          m_pViewingConditions = (CIccTagSpectralViewingConditions *) pView->NewCopy();
          icSpectralRange illumRange;
          const icFloatNumber *illum = pView->getIlluminant(illumRange);
          m_pViewingConditions->setIlluminant(pView->getStdIllumiant(), illumRange, illum, pView->getIlluminantCCT());
          pProfile->calcNormIlluminantXYZ(m_illuminantXYZ, this);
          pProfile->calcLumIlluminantXYZ(m_illuminantXYZLum, this);
          m_bValidMediaXYZ = pProfile->calcMediaWhiteXYZ(m_mediaXYZ, this);
      }
  }
  else {
    m_pPCC = NULL;
    m_pViewingConditions = NULL;
    m_bValidMediaXYZ = false;
  }
}
References CIccTagSpectralViewingConditions::getIlluminant(), CIccTagSpectralViewingConditions::getIlluminantCCT(), IIccProfileConnectionConditions::getPccViewingConditions(), CIccTagSpectralViewingConditions::getStdIllumiant(), m_bValidMediaXYZ, m_illuminantXYZ, CIccTagSpectralViewingConditions::m_illuminantXYZ, m_illuminantXYZLum, m_mediaXYZ, m_pPCC, m_pViewingConditions, CIccTagSpectralViewingConditions::NewCopy(), CIccTagSpectralViewingConditions::setIlluminant(), icFloatXYZNumber::X, icFloatXYZNumber::Y, and icFloatXYZNumber::Z.
~CIccCombinedConnectionConditions()
CIccCombinedConnectionConditions::~CIccCombinedConnectionConditions () virtual
{
  if (m_pViewingConditions)
    delete m_pViewingConditions;
}
References m_pViewingConditions.
Member Function Documentation
getCustomToStandardPcc()
CIccTagMultiProcessElement * CIccCombinedConnectionConditions::getCustomToStandardPcc () virtual
Implements IIccProfileConnectionConditions.
{
  if (m_pPCC)
    return m_pPCC->getCustomToStandardPcc();
  return NULL;
}
References IIccProfileConnectionConditions::getCustomToStandardPcc(), and m_pPCC.
getEmissiveObserver()
icFloatNumber * IIccProfileConnectionConditions::getEmissiveObserver (const icSpectralRange & range, const icFloatNumber * pWhite, icFloatNumber * obsMatrix = NULL) inherited
{
  const CIccTagSpectralViewingConditions *pView = getPccViewingConditions();
  if (!pView || !pWhite)
    return NULL;
  int i, n = range.steps, size = 3*n;
  const icFloatNumber *fptr;
  icFloatNumber *tptr;
  icSpectralRange observerRange;
  const icFloatNumber *observer = pView->getObserver(observerRange);
  if (!obs)
    obs = (icFloatNumber*)malloc(size*sizeof(icFloatNumber));
  if (obs) {
    CIccMatrixMath *mapRange=CIccMatrixMath::rangeMap(observerRange, range);
    //Copy observer while adjusting to range
    if (mapRange) {
        fptr = &observer[0];
        tptr = obs;
        for (i = 0; i < 3; i++) {
            mapRange->VectorMult(tptr, fptr);
            fptr += observerRange.steps;
            tptr += range.steps;
        }
        delete mapRange;
    }
    else {
      memcpy(obs, observer, size*sizeof(icFloatNumber));
    }
    //Calculate scale constant
    icFloatNumber k=0.0f;
    fptr = &obs[range.steps]; //Using second color matching function
    for (i=0; i<(int)range.steps; i++) {
      k += fptr[i]*pWhite[i];
    }
    //Scale observer so application of observer against white results in 1.0.
    for (i=0; i<size; i++) {
      obs[i] = obs[i] / k;
    }
    CIccMatrixMath observerMtx(3,range.steps);
    memcpy(observerMtx.entry(0), obs, size*sizeof(icFloatNumber));
    icFloatNumber xyz[3];
    observerMtx.VectorMult(xyz, pWhite);
  }
  return obs;
}
References CIccMatrixMath::CIccMatrixMath(), CIccMatrixMath::entry(), CIccTagSpectralViewingConditions::getObserver(), IIccProfileConnectionConditions::getPccViewingConditions(), CIccMatrixMath::rangeMap(), icSpectralRange::steps, and CIccMatrixMath::VectorMult().
Referenced by CIccMpeEmissionMatrix::Begin(), CIccMpeInvEmissionMatrix::Begin(), CIccMpeEmissionCLUT::Begin(), CIccMpeReflectanceCLUT::Begin(), CIccMpeEmissionObserver::Begin(), and CIccMpeReflectanceObserver::Begin().
getLumIlluminantXYZ()
void CIccCombinedConnectionConditions::getLumIlluminantXYZ (icFloatNumber * pXYZLum) virtual
Implements IIccProfileConnectionConditions.
{
  memcpy(pXYZLum, m_illuminantXYZLum, 3 * sizeof(icFloatNumber));
}
References m_illuminantXYZLum.
getMediaWhiteXYZ()
bool CIccCombinedConnectionConditions::getMediaWhiteXYZ (icFloatNumber * pXYZ) virtual
Implements IIccProfileConnectionConditions.
{
  if (m_pPCC || m_pViewingConditions) {
    memcpy(pXYZ, m_mediaXYZ, 3*sizeof(icFloatNumber));
    return m_bValidMediaXYZ;
  }
  return false;
}
References m_bValidMediaXYZ, m_mediaXYZ, m_pPCC, and m_pViewingConditions.
getNormIlluminantXYZ()
void CIccCombinedConnectionConditions::getNormIlluminantXYZ (icFloatNumber * pXYZ) virtual
Implements IIccProfileConnectionConditions.
{
  memcpy(pXYZ, m_illuminantXYZ, 3*sizeof(icFloatNumber));
}
References m_illuminantXYZ.
getObserverIlluminantScaleFactor()
icFloatNumber IIccProfileConnectionConditions::getObserverIlluminantScaleFactor () inherited
{
  const CIccTagSpectralViewingConditions *pView = getPccViewingConditions();
  if (!pView)
    return 1.0;
  icSpectralRange illumRange;
  const icFloatNumber *illum = pView->getIlluminant(illumRange);
  icSpectralRange obsRange;
  const icFloatNumber *obs = pView->getObserver(obsRange);
  int i, n = illumRange.steps;
  CIccMatrixMath *mapRange=CIccMatrixMath::rangeMap(obsRange, illumRange);
  icFloatNumber rv=0;
  if (mapRange) {
    icFloatNumber *Ycmf = new icFloatNumber[illumRange.steps];
    mapRange->VectorMult(Ycmf, &obs[obsRange.steps]);
    delete mapRange;
    for (i=0; i<n; i++) {
      rv += Ycmf[i]*illum[i];
    }
    delete [] Ycmf;
  }
  else {
   const icFloatNumber *Ycmf = &obs[obsRange.steps];
    for (i=0; i<n; i++) {
      rv += Ycmf[i]*illum[i];
    }
  }
  return rv;
}
References CIccTagSpectralViewingConditions::getIlluminant(), CIccTagSpectralViewingConditions::getObserver(), IIccProfileConnectionConditions::getPccViewingConditions(), CIccMatrixMath::rangeMap(), icSpectralRange::steps, and CIccMatrixMath::VectorMult().
getObserverWhiteScaleFactor()
icFloatNumber IIccProfileConnectionConditions::getObserverWhiteScaleFactor (const icFloatNumber * pWhite, const icSpectralRange & whiteRange) inherited
{
  const CIccTagSpectralViewingConditions *pView = getPccViewingConditions();
  if (!pView)
    return 1.0;
  icSpectralRange obsRange;
  const icFloatNumber *obs = pView->getObserver(obsRange);
  int i, n = whiteRange.steps;
  CIccMatrixMath *mapRange=CIccMatrixMath::rangeMap(obsRange, whiteRange);
  icFloatNumber rv=0;
  if (mapRange) {
    icFloatNumber *Ycmf = new icFloatNumber[whiteRange.steps];
    mapRange->VectorMult(Ycmf, &obs[obsRange.steps]);
    delete mapRange;
    for (i=0; i<n; i++) {
      rv += Ycmf[i]*pWhite[i];
    }
    delete [] Ycmf;
  }
  else {
    const icFloatNumber *Ycmf = &obs[obsRange.steps];
    for (i=0; i<n; i++) {
      rv += Ycmf[i]*pWhite[i];
    }
  }
  return rv;
}
References CIccTagSpectralViewingConditions::getObserver(), IIccProfileConnectionConditions::getPccViewingConditions(), CIccMatrixMath::rangeMap(), icSpectralRange::steps, and CIccMatrixMath::VectorMult().
getPccCCT()
icFloatNumber IIccProfileConnectionConditions::getPccCCT () inherited
{
  const CIccTagSpectralViewingConditions *pCond = getPccViewingConditions();
  if (!pCond)
    return 0.0f;
  return pCond->getIlluminantCCT();
}
References CIccTagSpectralViewingConditions::getIlluminantCCT(), and IIccProfileConnectionConditions::getPccViewingConditions().
Referenced by IIccProfileConnectionConditions::isEquivalentPcc().
getPccIlluminant()
icIlluminant IIccProfileConnectionConditions::getPccIlluminant () inherited
{
  const CIccTagSpectralViewingConditions *pCond = getPccViewingConditions();
  if (!pCond)
    return icIlluminantD50;
  return pCond->getStdIllumiant();
}
References IIccProfileConnectionConditions::getPccViewingConditions(), CIccTagSpectralViewingConditions::getStdIllumiant(), and icIlluminantD50.
Referenced by IIccProfileConnectionConditions::isEquivalentPcc(), and IIccProfileConnectionConditions::isStandardPcc().
getPccObserver()
icStandardObserver IIccProfileConnectionConditions::getPccObserver () inherited
{
 const  CIccTagSpectralViewingConditions *pCond = getPccViewingConditions();
  if (!pCond)
    return icStdObs1931TwoDegrees;
  return pCond->getStdObserver();
}
References IIccProfileConnectionConditions::getPccViewingConditions(), CIccTagSpectralViewingConditions::getStdObserver(), and icStdObs1931TwoDegrees.
Referenced by IIccProfileConnectionConditions::isEquivalentPcc(), and IIccProfileConnectionConditions::isStandardPcc().
getPccViewingConditions()
const CIccTagSpectralViewingConditions * CIccCombinedConnectionConditions::getPccViewingConditions () virtual
Implements IIccProfileConnectionConditions.
{
  if (m_pViewingConditions)
    return m_pViewingConditions;
  if (m_pPCC)
    return m_pPCC->getPccViewingConditions();
  return NULL;
}
References IIccProfileConnectionConditions::getPccViewingConditions(), m_pPCC, and m_pViewingConditions.
getReflectanceObserver()
CIccMatrixMath * IIccProfileConnectionConditions::getReflectanceObserver (const icSpectralRange & rangeRef) inherited
{
  CIccMatrixMath *pAdjust=NULL, *pMtx;
  const CIccTagSpectralViewingConditions *pView = getPccViewingConditions();
  icSpectralRange illumRange;
  const icFloatNumber *illum = pView->getIlluminant(illumRange);
  pMtx = CIccMatrixMath::rangeMap(rangeRef, illumRange);
  if (pMtx)
    pAdjust = pMtx;
  pMtx = pView->getObserverMatrix(illumRange);
  if (pAdjust) {
    pMtx = pAdjust->Mult(pMtx);
    delete pAdjust;
  }
  pAdjust = pMtx;
  pAdjust->VectorScale(illum);
  pAdjust->Scale(1.0f / pAdjust->RowSum(1));
  return pAdjust;
}
References CIccTagSpectralViewingConditions::getIlluminant(), CIccTagSpectralViewingConditions::getObserverMatrix(), IIccProfileConnectionConditions::getPccViewingConditions(), CIccMatrixMath::Mult(), CIccMatrixMath::rangeMap(), CIccMatrixMath::RowSum(), CIccMatrixMath::Scale(), and CIccMatrixMath::VectorScale().
getStandardToCustomPcc()
CIccTagMultiProcessElement * CIccCombinedConnectionConditions::getStandardToCustomPcc () virtual
Implements IIccProfileConnectionConditions.
{
  if (m_pPCC)
    return m_pPCC->getStandardToCustomPcc();
  return NULL;
}
References IIccProfileConnectionConditions::getStandardToCustomPcc(), and m_pPCC.
hasIlluminantSPD()
bool IIccProfileConnectionConditions::hasIlluminantSPD () inherited
{
  const  CIccTagSpectralViewingConditions *pCond = getPccViewingConditions();
  if (!pCond)
    return false;
  icSpectralRange illumRange;
  const icFloatNumber *illum = pCond->getIlluminant(illumRange);
  if (!illumRange.steps || !illum)
    return false;
  return true;
}
References CIccTagSpectralViewingConditions::getIlluminant(), IIccProfileConnectionConditions::getPccViewingConditions(), and icSpectralRange::steps.
Referenced by IIccProfileConnectionConditions::isEquivalentPcc().
isEquivalentPcc()
bool IIccProfileConnectionConditions::isEquivalentPcc (IIccProfileConnectionConditions & IPCC) inherited
{
  icIlluminant illum = getPccIlluminant();
  icStandardObserver obs = getPccObserver();
  if (illum!=IPCC.getPccIlluminant() || obs!= IPCC.getPccObserver())
    return false;
  if ((illum==icIlluminantDaylight || illum==icIlluminantBlackBody) && getPccCCT()!=IPCC.getPccCCT())
    return false;
  if (illum==icIlluminantUnknown)
    return false;
  if (obs==icStdObsCustom) {
    if (!hasIlluminantSPD() && !IPCC.hasIlluminantSPD()) {
      icFloatNumber XYZ1[3], XYZ2[3];
      getNormIlluminantXYZ(&XYZ1[0]);
      IPCC.getNormIlluminantXYZ(&XYZ2[0]);
      if (XYZ1[0]!=XYZ2[0] ||
          XYZ1[1]!=XYZ2[1] ||
          XYZ1[2]!=XYZ2[2])
        return false;
    }
    else {
      return false;
    }
  }
  return true;
}
References IIccProfileConnectionConditions::getNormIlluminantXYZ(), IIccProfileConnectionConditions::getPccCCT(), IIccProfileConnectionConditions::getPccIlluminant(), IIccProfileConnectionConditions::getPccObserver(), IIccProfileConnectionConditions::hasIlluminantSPD(), icIlluminantBlackBody, icIlluminantDaylight, and icIlluminantUnknown.
isStandardPcc()
bool IIccProfileConnectionConditions::isStandardPcc () inherited
{
  if (getPccIlluminant()==icIlluminantD50 && getPccObserver()==icStdObs1931TwoDegrees)
    return true;
  return false;
}
References IIccProfileConnectionConditions::getPccIlluminant(), IIccProfileConnectionConditions::getPccObserver(), icIlluminantD50, and icStdObs1931TwoDegrees.
Field Documentation
m_bValidIllumXYZ
bool CIccCombinedConnectionConditions::m_bValidIllumXYZ protected
m_bValidMediaXYZ
bool CIccCombinedConnectionConditions::m_bValidMediaXYZ protected
Referenced by CIccCombinedConnectionConditions(), and getMediaWhiteXYZ().
m_illuminantXYZ
icFloatNumber CIccCombinedConnectionConditions::m_illuminantXYZ[3] protected
Referenced by CIccCombinedConnectionConditions(), and getNormIlluminantXYZ().
m_illuminantXYZLum
icFloatNumber CIccCombinedConnectionConditions::m_illuminantXYZLum[3] protected
Referenced by CIccCombinedConnectionConditions(), and getLumIlluminantXYZ().
m_mediaXYZ
icFloatNumber CIccCombinedConnectionConditions::m_mediaXYZ[3] protected
Referenced by CIccCombinedConnectionConditions(), and getMediaWhiteXYZ().
m_pPCC
IIccProfileConnectionConditions* CIccCombinedConnectionConditions::m_pPCC protected
Referenced by CIccCombinedConnectionConditions(), getCustomToStandardPcc(), getMediaWhiteXYZ(), getPccViewingConditions(), and getStandardToCustomPcc().
m_pViewingConditions
CIccTagSpectralViewingConditions* CIccCombinedConnectionConditions::m_pViewingConditions protected
Referenced by CIccCombinedConnectionConditions(), ~CIccCombinedConnectionConditions(), getMediaWhiteXYZ(), and getPccViewingConditions().
The documentation for this class was generated from the following files:
IccProfLib/IccPcc.h
IccProfLib/IccPcc.cpp