iccDEV: IccProfLib/IccUtil.h File Reference
IccUtil.h File Reference
#include "IccDefs.h"
#include "IccProfLibConf.h"
#include <string>
#include <limits>
Data Structures
class CIccInfo
class CIccPixelBuf
class IIccCmmEnvVarLookup
Macros
#define icDefaultPixelBufSize 100
#define icNegInfinity (-std::numeric_limits<icFloatNumber>::infinity())
#define icNotANumber (std::numeric_limits<icFloatNumber>::quiet_NaN())
#define icNotZero(v) ((v)>1.0e-8 || (v)<-1.0e-8)
#define icPiNum 3.14159265358979323846
#define icPosInfinity (std::numeric_limits<icFloatNumber>::infinity())
#define icSwab16(flt) icSwab16Ptr(&flt)
#define icSwab32(flt) icSwab32Ptr(&flt)
#define icSwab64(flt) icSwab64Ptr(&flt)
#define icUtf8StrCmp(x, y) strcmp((const char*)x, (const char*)y)
Functions
ICCPROFLIB_API icUInt8Number icABtoU8 (icFloatNumber num)
ICCPROFLIB_API void icColorIndexName (icChar *szName, icColorSpaceSignature csSig, int nIndex, int nColors, const icChar *szUnknown)
ICCPROFLIB_API void icColorValue (icChar *szValue, icFloatNumber nValue, icColorSpaceSignature csSig, int nIndex, bool bUseLegacy=false)
ICCPROFLIB_API icFloatNumber icCubeth (icFloatNumber v)
ICCPROFLIB_API icFloatNumber icDeltaE (const icFloatNumber *Lab1, const icFloatNumber *Lab2)
ICCPROFLIB_API void icDeNormXYZ (icFloatNumber *XYZ, icFloatNumber *WhiteXYZ=NULL)
ICCPROFLIB_API icS15Fixed16Number icDtoF (icFloatNumber num)
ICCPROFLIB_API icU8Fixed8Number icDtoUCF (icFloatNumber num)
ICCPROFLIB_API icU16Fixed16Number icDtoUF (icFloatNumber num)
ICCPROFLIB_API icU1Fixed15Number icDtoUSF (icFloatNumber num)
ICCPROFLIB_API icFloat32Number icF16toF (icFloat16Number num)
ICCPROFLIB_API icFloatNumber icFtoD (icS15Fixed16Number num)
ICCPROFLIB_API icFloat16Number icFtoF16 (icFloat32Number num)
ICCPROFLIB_API icUInt16Number icFtoU16 (icFloatNumber num)
ICCPROFLIB_API icUInt8Number icFtoU8 (icFloatNumber num)
ICCPROFLIB_API const icChar * icGet16bitSig (icChar *pBuf, icUInt16Number sig, bool bGetHexVal=true)
ICCPROFLIB_API const icChar * icGetColorSig (icChar *pBuf, icUInt32Number sig, bool bGetHexVal=true)
ICCPROFLIB_API const icChar * icGetColorSigStr (icChar *pBuf, icUInt32Number nSig)
ICCPROFLIB_API icSignature icGetFirstSigPathSig (std::string sigPath)
ICCPROFLIB_API icSignature icGetLastSigPathSig (std::string sigPath)
ICCPROFLIB_API icUInt32Number icGetMaterialColorSpaceSamples (icMaterialColorSignature sig)
ICCPROFLIB_API icSignature icGetSecondSigPathSig (std::string sigPath)
ICCPROFLIB_API const icChar * icGetSig (icChar *pBuf, icUInt32Number sig, bool bGetHexVal=true)
ICCPROFLIB_API std::string icGetSigPath (icUInt32Number sig)
ICCPROFLIB_API const icChar * icGetSigStr (icChar *pBuf, icUInt32Number nSig)
ICCPROFLIB_API icUInt32Number icGetSigVal (const icChar *pBuf)
ICCPROFLIB_API icUInt32Number icGetSpaceSamples (icColorSpaceSignature sig)
ICCPROFLIB_API icUInt32Number icGetSpectralSpaceSamples (const icHeader *pHdr)
ICCPROFLIB_API icUInt8Number icGetStorageTypeBytes (icUInt16Number nStorageType)
ICCPROFLIB_API icFloatNumber icICubeth (icFloatNumber v)
ICCPROFLIB_API icUInt32Number icIntMax (icUInt32Number v1, icUInt32Number v2)
ICCPROFLIB_API icUInt32Number icIntMin (icUInt32Number v1, icUInt32Number v2)
ICCPROFLIB_API bool icIsIllumD50 (icXYZNumber xyz)
ICCPROFLIB_API bool icIsNear (icFloatNumber v1, icFloatNumber v2, icFloatNumber nearRange=1.0e-8)
ICCPROFLIB_API bool icIsSpaceCLR (icColorSpaceSignature sig)
ICCPROFLIB_API void icLab2Lch (icFloatNumber *Lch, icFloatNumber *Lab=NULL)
ICCPROFLIB_API void icLabFromPcs (icFloatNumber *Lab)
Here are some conversion routines to convert to regular Lab encoding.
ICCPROFLIB_API void icLabToPcs (icFloatNumber *Lab)
ICCPROFLIB_API void icLabtoXYZ (icFloatNumber *XYZ, const icFloatNumber *Lab=NULL, const icFloatNumber *WhiteXYZ=NULL)
ICCPROFLIB_API void icLch2Lab (icFloatNumber *Lab, icFloatNumber *Lch=NULL)
ICCPROFLIB_API void icMatrixDump (std::string &sDump, icS15Fixed16Number *pMatrix)
ICCPROFLIB_API bool icMatrixInvert3x3 (icFloatNumber *matrix)
ICCPROFLIB_API void icMatrixMultiply3x3 (icFloatNumber *result, const icFloatNumber *l, const icFloatNumber *r)
ICCPROFLIB_API icFloatNumber icMax (icFloatNumber v1, icFloatNumber v2)
ICCPROFLIB_API icValidateStatus icMaxStatus (icValidateStatus s1, icValidateStatus s2)
ICCPROFLIB_API void icMemDump (std::string &sDump, void *pBuf, icUInt32Number nNum)
ICCPROFLIB_API icFloatNumber icMin (icFloatNumber v1, icFloatNumber v2)
ICCPROFLIB_API void icNormXYZ (icFloatNumber *XYZ, icFloatNumber *WhiteXYZ=NULL)
ICCPROFLIB_API void * icRealloc (void *ptr, size_t size)
ICCPROFLIB_API icFloatNumber icRmsDif (const icFloatNumber *v1, const icFloatNumber *v2, icUInt32Number nSample)
ICCPROFLIB_API double icRoundOffset (double v)
bool ICCPROFLIB_API icSameSpectralRange (const icSpectralRange &rng1, const icSpectralRange &rng2)
void icSwab16Array (void *pVoid, int num)
void icSwab16Ptr (void *pVoid)
void icSwab32Array (void *pVoid, int num)
void icSwab32Ptr (void *pVoid)
void icSwab64Array (void *pVoid, int num)
void icSwab64Ptr (void *pVoid)
ICCPROFLIB_API icFloatNumber icU16toF (icUInt16Number num)
ICCPROFLIB_API icFloatNumber icU8toAB (icUInt8Number num)
ICCPROFLIB_API icFloatNumber icU8toF (icUInt8Number num)
ICCPROFLIB_API icFloatNumber icUCFtoD (icU8Fixed8Number num)
ICCPROFLIB_API icFloatNumber icUFtoD (icU16Fixed16Number num)
ICCPROFLIB_API icFloatNumber icUSFtoD (icU1Fixed15Number num)
ICCPROFLIB_API bool icValidOverlap (const icPositionNumber &pos1, const icPositionNumber &pos2, bool bAllowSame=true)
ICCPROFLIB_API bool icValidTagPos (const icPositionNumber &pos, icUInt32Number nTagHeaderSize, icUInt32Number nTagSize, bool bAllowEmpty=false)
ICCPROFLIB_API void icVectorApplyMatrix3x3 (icFloatNumber *result, const icFloatNumber *m, const icFloatNumber *v)
ICCPROFLIB_API void icXyzFromPcs (icFloatNumber *XYZ)
Here are some conversion routines to convert to regular XYZ encoding.
ICCPROFLIB_API void icXYZtoLab (icFloatNumber *Lab, const icFloatNumber *XYZ=NULL, const icFloatNumber *WhiteXYZ=NULL)
ICCPROFLIB_API void icXyzToPcs (icFloatNumber *XYZ)
Variables
ICCPROFLIB_API icFloatNumber icD50XYZ [3]
ICCPROFLIB_API icFloatNumber icD50XYZxx [3]
ICCPROFLIB_API CIccInfo icInfo
ICCPROFLIB_API const char * icMsgValidateCriticalError
ICCPROFLIB_API const char * icMsgValidateInformation
ICCPROFLIB_API const char * icMsgValidateNonCompliant
ICCPROFLIB_API const char * icMsgValidateWarning
Detailed Description
File: IccUtil.h
Contains: Implementation of utility classes/functions
Version: V1
Copyright: see ICC Software License
Definition in file IccUtil.h.
Macro Definition Documentation
icDefaultPixelBufSize
#define icDefaultPixelBufSize 100
Type: Class
Purpose: This is a utility class which can be for pixel sample storage. It features constant allocation access time when the pixel buffer size is less thatn icDefaultPixelBufSize
icNegInfinity
#define icNegInfinity (-std::numeric_limits<icFloatNumber>::infinity())
icNotANumber
#define icNotANumber (std::numeric_limits<icFloatNumber>::quiet_NaN())
icNotZero
#define icNotZero (v) ((v)>1.0e-8 || (v)<-1.0e-8)
icPiNum
#define icPiNum 3.14159265358979323846
icPosInfinity
#define icPosInfinity (std::numeric_limits<icFloatNumber>::infinity())
icSwab16
#define icSwab16 (flt) icSwab16Ptr(&flt)
icSwab32
#define icSwab32 (flt) icSwab32Ptr(&flt)
icSwab64
#define icSwab64 (flt) icSwab64Ptr(&flt)
icUtf8StrCmp
#define icUtf8StrCmp (x, y) strcmp((const char*)x, (const char*)y)
Function Documentation
icABtoU8()
ICCPROFLIB_API icUInt8Number icABtoU8 (icFloatNumber num)
{
  icFloatNumber v = num + 128.0f;
  if (v<0)
    v=0;
  else if (v>255)
    v=255;
  return (icUInt8Number)(v + 0.5);
}
icColorIndexName()
ICCPROFLIB_API void icColorIndexName (icChar * szName, icColorSpaceSignature csSig, int nIndex, int nColors, const icChar * szUnknown)
{
  icChar szSig[5] = {0};
  int i;
  if (csSig!=icSigUnknownData) {
    szSig[0] = (icChar)(csSig>>24);
    szSig[1] = (icChar)(csSig>>16);
    szSig[2] = (icChar)(csSig>>8);
    szSig[3] = (icChar)(csSig);
    szSig[4] = '\0';
    for (i=3; i>0; i--) {
      if (szSig[i]==' ')
        szSig[i]='\0';
    }
    if (nColors==1) {
      strcpy(szName, szSig);
    }
    else if ((size_t)nColors == strlen(szSig)) {
      sprintf(szName, "%s_%c", szSig, szSig[nIndex]);
    }
    else {
      sprintf(szName, "%s_%d", szSig, nIndex+1);
    }
  }
  else if (nColors==1) {
    strcpy(szName, szUnknown);
  }
  else {
    sprintf(szName, "%s_%d", szUnknown, nIndex+1);
  }
}
Referenced by CIccTagNamedColor2::Describe(), CIccMBB::Describe(), and CIccCLUT::DumpLut().
icColorValue()
ICCPROFLIB_API void icColorValue (icChar * szValue, icFloatNumber nValue, icColorSpaceSignature csSig, int nIndex, bool bUseLegacy = false)
{
  if (csSig==icSigLabData) {
    if (!bUseLegacy) {
      if (!nIndex || nIndex>2)
        sprintf(szValue, "%7.3lf", nValue * 100.0);
      else
        sprintf(szValue, "%8.3lf", nValue * 255.0 - 128.0);
    }
    else {
      if (!nIndex || nIndex>2)
        sprintf(szValue, "%7.3lf", nValue * 100.0 * 65535.0 / 65280.0);
      else
        sprintf(szValue, "%8.3lf", nValue * 255.0 * 65535.0 / 65280.0 - 128.0);
    }
  }
  else if (csSig==icSigUnknownData) {
    sprintf(szValue, "%8.5lf", nValue);
  }
  else {
    sprintf(szValue, "%7.3lf", nValue * 100.0);
  }
}
References icSigLabData.
Referenced by CIccTagNamedColor2::Describe(), CIccTagCurve::Describe(), CIccCLUT::DumpLut(), CIccTagCurve::DumpLut(), and CIccCLUT::Iterate().
icCubeth()
ICCPROFLIB_API icFloatNumber icCubeth (icFloatNumber v)
{
  if (v> 0.008856) {
    return (icFloatNumber)ICC_CBRTF(v);
  }
  else {
    return (icFloatNumber)(7.787037037037037037037037037037*v + 16.0/116.0);
  }
}
Referenced by CIccOpDefToLab::Exec(), and icXYZtoLab().
icDeltaE()
ICCPROFLIB_API icFloatNumber icDeltaE (const icFloatNumber * Lab1, const icFloatNumber * Lab2)
{
  return (icFloatNumber)sqrt(icSq(lab1[0]-lab2[0]) + icSq(lab1[1]-lab2[1]) + icSq(lab1[2]-lab2[2]));
}
References icSq().
Referenced by CIccMinMaxEval::Compare(), CIccPRMG::EvaluateProfile(), CIccTagNamedColor2::FindCachedPCSColor(), and CIccArrayNamedColor::FindPcsColor().
icDeNormXYZ()
ICCPROFLIB_API void icDeNormXYZ (icFloatNumber * XYZ, icFloatNumber * WhiteXYZ = NULL)
icDtoF()
ICCPROFLIB_API icS15Fixed16Number icDtoF (icFloatNumber num)
{
  icS15Fixed16Number rv;
  if (num<-32768.0)
    num = -32768.0;
  else if (num>32767.0)
    num = 32767.0;
  rv = (icS15Fixed16Number)icRoundOffset((double)num*65536.0);
  return rv;
}
References icRoundOffset().
Referenced by CIccTagLut16::CIccTagLut16(), CIccTagLut8::CIccTagLut8(), CIccDefaultEncProfileConverter::ConvertFromParams(), main(), CIccProfileXml::ParseBasic(), CIccTagXmlXYZ::ParseXml(), CIccTagXmlFixedNum< T, Tsig >::ParseXml(), CIccTagXmlMeasurement::ParseXml(), CIccTagXmlViewingConditions::ParseXml(), CIccTagXmlResponseCurveSet16::ParseXml(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), and CIccTagLut16::Write().
icDtoUCF()
ICCPROFLIB_API icU8Fixed8Number icDtoUCF (icFloatNumber num)
{
  icU8Fixed8Number rv;
  if (num<0)
    num = 0;
  else if (num>255.0)
    num = 255.0;
  rv = (icU8Fixed8Number)icRoundOffset(num*256.0);
  return rv;
}
References icRoundOffset().
icDtoUF()
ICCPROFLIB_API icU16Fixed16Number icDtoUF (icFloatNumber num)
{
  icU16Fixed16Number rv;
  if (num<0)
    num = 0;
  else if (num>65535.0)
    num = 65535.0;
  rv = (icU16Fixed16Number)icRoundOffset((double)num*65536.0);
  return rv;
}
References icRoundOffset().
Referenced by CIccTagXmlChromaticity::ParseXml(), CIccTagXmlFixedNum< T, Tsig >::ParseXml(), and CIccTagChromaticity::Validate().
icDtoUSF()
ICCPROFLIB_API icU1Fixed15Number icDtoUSF (icFloatNumber num)
{
  icU1Fixed15Number rv;
  if (num<0)
    num = 0;
  else if (num>65535.0/32768.0)
    num = 65535.0/32768.0;
  rv = (icU1Fixed15Number)icRoundOffset(num*32768.0);
  return rv;
}
References icRoundOffset().
icF16toF()
ICCPROFLIB_API icFloat32Number icF16toF (icFloat16Number num)
{
  icUInt16Number numsgn, numexp, nummnt;
  icUInt32Number rv, rvsgn, rvexp, rvmnt;
  icInt32Number tmpexp;
  icFloatNumber * rvfp, rvf;
  int exp;
  if (!(num & 0x7FFF)) {
    rv = ((icUInt32Number) num) << 16;
  } else {
    numsgn = num & 0x8000;
    numexp = num & 0x7C00;
    nummnt = num & 0x03FF;
    if (!numexp) {
      exp = -1;
      do {
        exp++;
        nummnt <<= 1;
      } while (!(nummnt & 0x0400)); // Shift until leading bit overflows into exponent bit
      rvsgn = ((icUInt32Number) numsgn) << 16;
      tmpexp = ((icUInt32Number) (numexp >> 10)) - 15 + 127 - exp;
      rvexp = (icUInt32Number) (tmpexp << 23);
      rvmnt = ((icUInt32Number) (nummnt & 0x03FFu)) << 13;
      rv = (rvsgn | rvexp | rvmnt);
    } else if (numexp == 0x7C00) {
      if (!nummnt) {
        rv = (((icUInt32Number) numsgn) << 16) | ((icUInt32Number) 0x7F800000);
      } else {
        rv = (icUInt32Number) 0xFFC00000;
      }
    } else {
      rvsgn = ((icUInt32Number) numsgn) << 16;
      tmpexp = ((icUInt32Number) (numexp >> 10)) - 15 + 127;
      rvexp = (icUInt32Number) (tmpexp << 23);
      rvmnt = ((icUInt32Number) nummnt) << 13;
      rv = (rvsgn | rvexp | rvmnt);
    }
  }
  rvfp = (icFloatNumber*)&rv;
  rvf = *rvfp;
  return rvf;
}
Referenced by CIccInfo::CheckData(), CIccMpeSpectralMatrix::Describe(), CIccMpeSpectralObserver::Describe(), CIccTagSpectralDataInfo::Describe(), CIccTagSpectralViewingConditions::Describe(), CIccTagEmbeddedProfile::Describe(), CIccSparseMatrixFloat16::get(), main(), main(), CIccSampledCurveSegmentXml::ParseXml(), CIccSinglSampledeCurveXml::ParseXml(), CIccIO::ReadFloat16Float(), CIccMatrixMath::SetRange(), CIccMpeXmlEmissionMatrix::ToXml(), CIccMpeXmlInvEmissionMatrix::ToXml(), CIccMpeXmlEmissionCLUT::ToXml(), CIccMpeXmlReflectanceCLUT::ToXml(), CIccMpeXmlEmissionObserver::ToXml(), CIccMpeXmlReflectanceObserver::ToXml(), CIccTagXmlSpectralDataInfo::ToXml(), CIccTagXmlSpectralViewingConditions::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
icFtoD()
ICCPROFLIB_API icFloatNumber icFtoD (icS15Fixed16Number num)
{
  icFloatNumber rv = (icFloatNumber)((double)num / 65536.0);
  return rv;
}
Referenced by CIccTagXYZ::Describe(), CIccTagMeasurement::Describe(), CIccTagViewingConditions::Describe(), CIccResponseCurveStruct::Describe(), CIccTagEmbeddedProfile::Describe(), icIsS15Fixed16NumberNear(), icMatrixDump(), main(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), CIccTagXmlXYZ::ToXml(), CIccTagXmlMeasurement::ToXml(), CIccTagXmlViewingConditions::ToXml(), CIccTagXmlResponseCurveSet16::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
icFtoF16()
ICCPROFLIB_API icFloat16Number icFtoF16 (icFloat32Number num)
{
  icUInt16Number rv;
  icUInt16Number rvsgn, rvexp, rvmnt;
  icUInt32Number flt, *fltp, fltsgn, fltexp, fltmnt;
  int exp;
  fltp = (icUInt32Number*)&num;
  flt = *fltp;
  if (!(flt & 0x7FFFFFFF)) {
    rv = (icUInt16Number) (flt >> 16);
  } else {
    fltsgn = flt & 0x80000000;
    fltexp = flt & 0x7F800000;
    fltmnt = flt & 0x007FFFFF;
    if (!fltexp) {
      rv = (icUInt16Number) (fltsgn >> 16);
    } else if (fltexp == 0x7F800000) {
      if (!fltmnt) {
        rv = (icUInt16Number) ((fltsgn >> 16) | 0x7C00); // Signed Inf
      } else {
        rv = (icUInt16Number) 0xFE00; // NaN
      }
    } else { // Normalized number
      rvsgn = (icUInt16Number) (fltsgn >> 16);
      exp = ((int)(fltexp >> 23)) - 127 + 15;
      if (exp >= 0x1F) {  // Overflow
        rv = (icUInt16Number) ((fltsgn >> 16) | 0x7C00); // Signed Inf
      } else if (exp <= 0) {  // Underflow
        if ((14 - exp) > 24) {
          rvmnt = (icUInt16Number) 0;  // Set mantissa to zero
        } else {
          fltmnt |= 0x00800000;  // Include hidden leading bit
          rvmnt = (icUInt16Number) (fltmnt >> (14 - exp));
          if ((fltmnt >> (13 - exp)) & 0x00000001) // Rounding?
            rvmnt += (icUInt16Number) 1;
        }
        rv = (rvsgn | rvmnt);
      } else {
        rvexp = (icUInt16Number) (exp << 10);
        rvmnt = (icUInt16Number) (fltmnt >> 13);
        if (fltmnt & 0x00001000) // Rounding?
          rv = (rvsgn | rvexp | rvmnt) + (icUInt16Number) 1;
        else
          rv = (rvsgn | rvexp | rvmnt);
      }
    }
  }
  return rv;
}
Referenced by CIccProfileXml::ParseBasic(), CIccMpeXmlEmissionMatrix::ParseXml(), CIccMpeXmlInvEmissionMatrix::ParseXml(), CIccMpeXmlEmissionCLUT::ParseXml(), CIccMpeXmlReflectanceCLUT::ParseXml(), CIccMpeXmlEmissionObserver::ParseXml(), CIccMpeXmlReflectanceObserver::ParseXml(), CIccTagXmlSpectralDataInfo::ParseXml(), CIccTagXmlSpectralViewingConditions::ParseXml(), CIccSparseMatrixFloat16::set(), and CIccIO::WriteFloat16Float().
icFtoU16()
ICCPROFLIB_API icUInt16Number icFtoU16 (icFloatNumber num)
{
  icUInt16Number rv;
  if (num<0)
    num = 0;
  else if (num>1.0)
    num = 1.0;
  rv = (icUInt16Number)icRoundOffset(num*65535.0);
  return rv;
}
References icRoundOffset().
Referenced by CIccTagXmlColorantTable::ParseXml().
icFtoU8()
ICCPROFLIB_API icUInt8Number icFtoU8 (icFloatNumber num)
{
  icUInt8Number rv;
  if (num<0)
    num = 0;
  else if (num>1.0)
    num = 1.0;
  rv = (icUInt8Number)icRoundOffset(num*255.0);
  return rv;
}
References icRoundOffset().
icGet16bitSig()
ICCPROFLIB_API const icChar * icGet16bitSig (icChar * pBuf, icUInt16Number sig, bool bGetHexVal = true)
{
    icUInt16Number sig = nSig;
    icUInt8Number c;
    if (!nSig) {
        strcpy(pBuf, "NULL");
        return pBuf;
    }
    pBuf[0] = '\'';
    c = (icUInt8Number)(sig >> 8);
    if (!isprint(c))
        c = '?';
    pBuf[1] = c;
    c = (icUInt8Number)(sig & 0x00FF);
    if (!isprint(c))
        c = '?';
    pBuf[2] = c;
    if (bGetHexVal)
        sprintf(pBuf + 3, "' = %04X", nSig);
    else
        sprintf(pBuf + 3, "'");
    return pBuf;
}
icGetColorSig()
ICCPROFLIB_API const icChar * icGetColorSig (icChar * pBuf, icUInt32Number sig, bool bGetHexVal = true)
{
  icUInt32Number sig=nSig;
  switch (icGetColorSpaceType(nSig)) {
    case icSigNChannelData:
    case icSigReflectanceSpectralData:
    case icSigTransmisionSpectralData:
    case icSigRadiantSpectralData:
    case icSigBiSpectralReflectanceData:
    case icSigSparseMatrixReflectanceData:
      pBuf[0]='\"';
      pBuf[1] = (icUInt8Number)(sig>>24);
      sig<<=8;
      pBuf[2] = (icUInt8Number)(sig>>24);
      sprintf(pBuf+3, "%04X\"", icNumColorSpaceChannels(nSig));
      return pBuf;
    default:
    {
      int i, j=-1;
      icUInt8Number c;
      bool bNeedHexVal = false;
      pBuf[0] = '\'';
      for (i=1; i<5; i++) {
        c=(icUInt8Number)(sig>>24);
        if (!isprint(c)) {
          c = '?';
          bNeedHexVal = true;
        }
        pBuf[i]=c;
        sig <<=8;
      }
      if (bGetHexVal)
        sprintf(pBuf+5, "' = %08X", nSig);
      else if (bNeedHexVal) {
        sprintf(pBuf, "%08Xh", nSig);
      }
      else
        sprintf(pBuf+5, "'");
    }
  }
  return pBuf;
}
References icSigBiSpectralReflectanceData, icSigNChannelData, icSigRadiantSpectralData, icSigReflectanceSpectralData, icSigSparseMatrixReflectanceData, and icSigTransmisionSpectralData.
Referenced by CIccCfgColorData::toLegacy().
icGetColorSigStr()
ICCPROFLIB_API const icChar * icGetColorSigStr (icChar * pBuf, icUInt32Number nSig)
{
  icUInt32Number sig=nSig;
  switch (icGetColorSpaceType(nSig)) {
    case icSigNChannelData:
    case icSigReflectanceSpectralData:
    case icSigTransmisionSpectralData:
    case icSigRadiantSpectralData:
    case icSigBiSpectralReflectanceData:
    case icSigSparseMatrixReflectanceData:
      pBuf[0] = (icUInt8Number)(sig>>24);
      sig<<=8;
      pBuf[1] = (icUInt8Number)(sig>>24);
      sprintf(pBuf+2, "%04X", icNumColorSpaceChannels(nSig));
      return pBuf;
    default:
      {
        int i, j=-1;
        icUInt8Number c;
        bool bGetHexVal = false;
        for (i=0; i<4; i++) {
          c=(icUInt8Number)(sig>>24);
          if (!c) {
            j=i;
          }
          else if (j!=-1) {
            bGetHexVal = true;
          }
          else if (!isprint(c) ||c==':') {
            c='?';
            bGetHexVal = true;
          }
          pBuf[i]=c;
          sig <<=8;
        }
        if (bGetHexVal)
          sprintf(pBuf, "%08Xh", nSig);
        else
          pBuf[4] = '\0';
      }
  }
  return pBuf;
}
References icSigBiSpectralReflectanceData, icSigNChannelData, icSigRadiantSpectralData, icSigReflectanceSpectralData, icSigSparseMatrixReflectanceData, and icSigTransmisionSpectralData.
Referenced by CIccTagSpectralDataInfo::Describe(), CIccCfgDataApply::toJson(), CIccCfgColorData::toJson(), CIccTagXmlSpectralDataInfo::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
icGetFirstSigPathSig()
ICCPROFLIB_API icSignature icGetFirstSigPathSig (std::string sigPath)
{
  icSignature rv = 0;
  const char *ptr = sigPath.c_str();
  while(*ptr==':') {
    std::string sigStr;
    ptr++;
    while(*ptr && *ptr!=':') {
      sigStr += *ptr;
      ptr++;
    }
    rv = icGetSigVal(sigStr.c_str());
    //Skip embedded tag path entry
    if (rv != icSigEmbeddedV5ProfileTag)
      break;
  }
  return rv;
}
References icGetSigVal(), and icSigEmbeddedV5ProfileTag.
Referenced by CIccMBB::Validate(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccTagText::Validate(), CIccTagSignature::Validate(), CIccTagSparseMatrixArray::Validate(), CIccTagNum< T, Tsig >::Validate(), CIccTagFloatNum< T, Tsig >::Validate(), CIccTagColorantTable::Validate(), CIccTagSpectralDataInfo::Validate(), CIccTagArray::Validate(), CIccTagCurve::Validate(), CIccTagParametricCurve::Validate(), CIccMatrix::Validate(), CIccCLUT::Validate(), and CIccTagMultiProcessElement::Validate().
icGetLastSigPathSig()
ICCPROFLIB_API icSignature icGetLastSigPathSig (std::string sigPath)
{
  size_t n = sigPath.length();
  if (!n)
    return icGetSigVal(sigPath.c_str());
  const char *sig = sigPath.c_str();
  for (n = n - 1; n > 0; n--) {
    if (sig[n] == ':') {
      break;
    }
  }
  if (/* n >= 0 && */ sig[n] == ':')
    n++;
  return icGetSigVal(sig+n);
}
References icGetSigVal().
icGetMaterialColorSpaceSamples()
ICCPROFLIB_API icUInt32Number icGetMaterialColorSpaceSamples (icMaterialColorSignature sig)
{
  if (icGetColorSpaceType((icColorSpaceSignature)sig)!=icSigSrcMCSChannelData)
    return 0;
  return icNumColorSpaceChannels(sig);
}
References icSigSrcMCSChannelData.
Referenced by CIccTagNum< T, Tsig >::Validate(), CIccTagFloatNum< T, Tsig >::Validate(), CIccTagArray::Validate(), and CIccTagMultiProcessElement::Validate().
icGetSecondSigPathSig()
ICCPROFLIB_API icSignature icGetSecondSigPathSig (std::string sigPath)
{
  icSignature rv = 0;
  const char *ptr = sigPath.c_str();
  if(*ptr==':') {
    std::string sigStr;
    ptr++;
    ptr = strchr(ptr+1, ':');
    if (ptr) {
      ptr++;
      while(*ptr && *ptr!=':') {
        sigStr += *ptr;
        ptr++;
      }
      rv = icGetSigVal(sigStr.c_str());
    }
  }
  return rv;
}
References icGetSigVal().
Referenced by CIccTagSparseMatrixArray::Validate().
icGetSig()
ICCPROFLIB_API const icChar * icGetSig (icChar * pBuf, icUInt32Number sig, bool bGetHexVal = true)
{
  int i;
  icUInt32Number sig=nSig;
  icUInt8Number c;
  if (!nSig) {
    strcpy(pBuf, "NULL");
    return pBuf;
  }
  pBuf[0] = '\'';
  for (i=1; i<5; i++) {
    c=(icUInt8Number)(sig>>24);
    if (!isprint(c))
      c='?';
    pBuf[i]=c;
    sig <<=8;
  }
  if (bGetHexVal)
    sprintf(pBuf+5, "' = %08X", nSig);
  else
    sprintf(pBuf+5, "'");
  return pBuf;
}
Referenced by SIccCalcOp::Describe(), CIccMpeAcs::Describe(), CIccTagProfileSeqDesc::Describe(), CIccTagEmbeddedProfile::Describe(), CIccMpeUnknown::Describe(), DumpTag(), CIccBasicMpeFactory::GetElementSigName(), CIccInfo::GetUnknownName(), main(), and CIccMpeUnknown::Validate().
icGetSigPath()
ICCPROFLIB_API std::string icGetSigPath (icUInt32Number sig)
{
  char buf[20];
  std::string rv = ":";
  rv += icGetSigStr(buf, nSig);
  return rv;
}
References icGetSigStr().
Referenced by CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccArrayUnknown::Validate(), CIccArrayColorantInfo::Validate(), CIccStructUnknown::Validate(), CIccTagColorantOrder::Validate(), CIccTagProfileSeqDesc::Validate(), CIccTagStruct::Validate(), CIccTagArray::Validate(), CIccTagMultiProcessElement::Validate(), CIccTagProfileSequenceId::Validate(), CIccSegmentedCurve::Validate(), CIccMpeCurveSet::Validate(), CIccMpeTintArray::Validate(), CIccMpeToneMap::Validate(), CIccMpeMatrix::Validate(), CIccMpeCLUT::Validate(), CIccMpeExtCLUT::Validate(), CIccMpeCalculator::Validate(), CIccMpeSpectralMatrix::Validate(), CIccMpeInvEmissionMatrix::Validate(), CIccMpeSpectralCLUT::Validate(), CIccMpeSpectralObserver::Validate(), and CIccMultiProcessElement::Validate().
icGetSigStr()
ICCPROFLIB_API const icChar * icGetSigStr (icChar * pBuf, icUInt32Number nSig)
{
  int i, j=-1;
  icUInt32Number sig=nSig;
  icUInt8Number c;
  bool bGetHexVal = false;
  for (i=0; i<4; i++) {
    c=(icUInt8Number)(sig>>24);
    if (!c) {
      j=i;
    }
    else if (j!=-1) {
      bGetHexVal = true;
    }
    else if (!isprint(c) ||c==':') {
      c='?';
      bGetHexVal = true;
    }
    pBuf[i]=c;
    sig <<=8;
  }
  if (bGetHexVal)
    sprintf(pBuf, "%08Xh", nSig);
  else
    pBuf[4] = '\0';
  return pBuf;
}
Referenced by SIccCalcOp::Describe(), CIccBasicArrayFactory::GetArraySigName(), CIccBasicStructFactory::GetStructSigName(), icGetSigPath(), icProfDescToXml(), jsonFromEnvMap(), CIccMpeXmlUnknown::ToXml(), CIccMpeXmlTintArray::ToXml(), CIccMpeXmlBAcs::ToXml(), CIccMpeXmlEAcs::ToXml(), CIccTagXmlTextDescription::ToXml(), CIccTagXmlSignature::ToXml(), CIccTagXmlMultiLocalizedUnicode::ToXml(), CIccTagXmlProfileSequenceId::ToXml(), CIccTagXmlDict::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
icGetSigVal()
ICCPROFLIB_API icUInt32Number icGetSigVal (const icChar * pBuf)
{
  icUInt32Number v;
  switch(strlen(pBuf)) {
    case 0:
      return 0;
    case 1:
      return (icUInt32Number)((((unsigned long)pBuf[0])<<24) +
                              0x202020);
    case 2:
      return (icUInt32Number)((((unsigned long)pBuf[0])<<24) +
                              (((unsigned long)pBuf[1])<<16) +
                              0x2020);
    case 3:
      return (icUInt32Number)((((unsigned long)pBuf[0])<<24) +
                              (((unsigned long)pBuf[1])<<16) +
                              (((unsigned long)pBuf[2])<<8) +
                              0x20);
    case 4:
    default:
      return (icUInt32Number)((((unsigned long)pBuf[0])<<24) +
                              (((unsigned long)pBuf[1])<<16) +
                              (((unsigned long)pBuf[2])<<8) +
                              (((unsigned long)pBuf[3])));
    case 6:  //Channel based color signatures
      sscanf(pBuf+2, "%x", &v);
      return (icUInt32Number)((((unsigned long)pBuf[0])<<24) +
                              (((unsigned long)pBuf[1])<<16) +
                              v);
    case 8:
    case 9:
      sscanf(pBuf, "%x", &v);
      return v;
  }
}
Referenced by CIccCfgProfileSequence::fromArgs(), CIccCfgColorData::fromLegacy(), CIccInfo::GetSigPathName(), icGetFirstSigPathSig(), icGetLastSigPathSig(), icGetSecondSigPathSig(), icXmlGetChildSigVal(), icXmlStrToSig(), jsonToColorSpace(), jsonToValue(), main(), main(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlUnknown::ParseXml(), CIccTagXmlSignature::ParseXml(), CIccTagXmlMultiLocalizedUnicode::ParseXml(), CIccTagXmlSpectralDataInfo::ParseXml(), CIccTagXmlProfileSequenceId::ParseXml(), CIccTagXmlDict::ParseXml(), CIccTagXmlStruct::ParseXml(), and CIccTagXmlArray::ParseXml().
icGetSpaceSamples()
ICCPROFLIB_API icUInt32Number icGetSpaceSamples (icColorSpaceSignature sig)
{
  switch(sig) {
  case icSigGrayData:
  case icSigGamutData:
    return 1;
  case icSig2colorData:
    return 2;
  case icSigXYZData:
  case icSigLabData:
  case icSigLuvData:
  case icSigYCbCrData:
  case icSigYxyData:
  case icSigRgbData:
  case icSigHsvData:
  case icSigHlsData:
  case icSigCmyData:
  case icSig3colorData:
  case icSigDevLabData:
  case icSigDevXYZData:
    return 3;
  case icSigCmykData:
  case icSig4colorData:
    return 4;
  default:
    switch (icGetColorSpaceType(sig)) {
      case icSigNChannelData:
      case icSigReflectanceSpectralData:
      case icSigTransmisionSpectralData:
      case icSigRadiantSpectralData:
      case icSigBiSpectralReflectanceData:
      case icSigSparseMatrixReflectanceData:
      case icSigSrcMCSChannelData:
        return icNumColorSpaceChannels(sig);
      default:
      {
        icChar szSig[5] = {0};
        szSig[0] = (icChar)(sig>>24);
        szSig[1] = (icChar)(sig>>16);
        szSig[2] = (icChar)(sig>>8);
        szSig[3] = (icChar)(sig);
        szSig[4] = '\0';
        if (!strcmp(szSig+1, "CLR")) {
          int d0 = icHexDigit(szSig[0]);
          if (d0>=0)
            return d0;
        }
        else if (!strncmp(szSig, "MCH", 3)) {  //Litte CMS multi-channel notation (not part of ICC specification)
          int d0 = icHexDigit(szSig[3]);
          if (d0>=0)
            return d0;
        }
      }
      return 0;
    }
  }
}
References icHexDigit(), icSig2colorData, icSig3colorData, icSig4colorData, icSigBiSpectralReflectanceData, icSigCmyData, icSigCmykData, icSigGrayData, icSigHlsData, icSigHsvData, icSigLabData, icSigLuvData, icSigNChannelData, icSigRadiantSpectralData, icSigReflectanceSpectralData, icSigRgbData, icSigSparseMatrixReflectanceData, icSigSrcMCSChannelData, icSigTransmisionSpectralData, icSigXYZData, icSigYCbCrData, and icSigYxyData.
Referenced by CIccCfgColorData::addFields(), CCubeWriter::begin(), CDevLinkWriter::begin(), CIccApplyBPC::calcSrcBlackPoint(), CIccEvalCompare::EvaluateProfile(), CIccCfgColorData::fromLegacy(), CIccInfo::GetColorSpaceSigName(), icGetSpectralSpaceSamples(), IsValidBitmapType(), IsValidColorType(), main(), main(), main(), CIccArrayNamedColor::SetColorSpaces(), CIccCfgColorData::spaceName(), CIccMBB::Validate(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccTagNamedColor2::Validate(), CIccTagSparseMatrixArray::Validate(), CIccTagColorantOrder::Validate(), CIccTagColorantTable::Validate(), CIccTagResponseCurveSet16::Validate(), and CIccTagMultiProcessElement::Validate().
icGetSpectralSpaceSamples()
ICCPROFLIB_API icUInt32Number icGetSpectralSpaceSamples (const icHeader * pHdr)
{
  if (pHdr->spectralPCS)
    return icGetSpaceSamples((icColorSpaceSignature)pHdr->spectralPCS);
  else
    return icGetSpaceSamples(pHdr->pcs);
}
References icGetSpaceSamples(), icHeader::pcs, and icHeader::spectralPCS.
Referenced by CIccTagMultiProcessElement::Validate().
icGetStorageTypeBytes()
ICCPROFLIB_API icUInt8Number icGetStorageTypeBytes (icUInt16Number nStorageType)
{
  switch (nStorageType) {
  case icValueTypeUInt8:
    return 1;
  case icValueTypeUInt16:
  case icValueTypeFloat16:
    return 2;
  case icValueTypeFloat32:
    return 4;
  default:
    return 0;
  }
}
References icValueTypeFloat16, icValueTypeFloat32, icValueTypeUInt16, and icValueTypeUInt8.
Referenced by CIccMpeExtCLUT::Read(), and CIccMpeSpectralCLUT::Read().
icICubeth()
ICCPROFLIB_API icFloatNumber icICubeth (icFloatNumber v)
{
  if (v > 0.20689303448275862068965517241379)
    return v*v*v;
  else
#ifndef SAMPLEICC_NOCLIPLABTOXYZ
  if (v>16.0/116.0)
#endif
    return (icFloatNumber)((v - 16.0 / 116.0) / 7.787037037037037037037037037037);
#ifndef SAMPLEICC_NOCLIPLABTOXYZ
  else
    return 0.0;
#endif
}
Referenced by CIccOpDefFromLab::Exec(), and icLabtoXYZ().
icIntMax()
ICCPROFLIB_API icUInt32Number icIntMax (icUInt32Number v1, icUInt32Number v2)
{
  return( v1 > v2 ? v1 : v2 );
}
Referenced by CIccCalculatorFunc::CheckUnderflowOverflow(), main(), and main().
icIntMin()
ICCPROFLIB_API icUInt32Number icIntMin (icUInt32Number v1, icUInt32Number v2)
{
  return( v1 < v2 ? v1 : v2 );
}
Referenced by CIccCalculatorFunc::CheckUnderflowOverflow(), CIccCalculatorFunc::DescribeSequence(), CIccMpeXmlCalculator::ParseXml(), CIccCalculatorFunc::SequenceNeedTempReset(), and CIccToneMapFunc::SetFunction().
icIsIllumD50()
ICCPROFLIB_API bool icIsIllumD50 (icXYZNumber xyz)
{
  return icIsS15Fixed16NumberNear(xyz.X, 0.9642f) &&
         icIsS15Fixed16NumberNear(xyz.Y, 1.0000f) &&
         icIsS15Fixed16NumberNear(xyz.Z, 0.8249f);
}
References icIsS15Fixed16NumberNear(), icXYZNumber::X, icXYZNumber::Y, and icXYZNumber::Z.
icIsNear()
ICCPROFLIB_API bool icIsNear (icFloatNumber v1, icFloatNumber v2, icFloatNumber nearRange)
Name: icIsNear
Purpose: Checks if two numbers are close to each other in value
Args: v1 - first value v2 - second value range -
Return: true if v1 is near v2 within range
{
  return fabs(v1 - v2) <= nearRange;
}
Referenced by CIccFormulaCurveSegment::Begin(), CCubeWriter::begin(), CDevLinkWriter::begin(), CIccFormulaCurveSegment::Describe(), CubeFile::isCustomInputRange(), and CIccTagSpectralViewingConditions::setIlluminant().
icIsSpaceCLR()
ICCPROFLIB_API bool icIsSpaceCLR (icColorSpaceSignature sig)
{
  icChar szSig[5] = {0};
  szSig[0] = (icChar)(sig>>24);
  szSig[1] = (icChar)(sig>>16);
  szSig[2] = (icChar)(sig>>8);
  szSig[3] = (icChar)(sig);
  szSig[4] = '\0';
  int d0 = icHexDigit(szSig[0]);
  if (szSig[0]=='n' && szSig[1]=='c')
    return true;
  else if (!strcmp(szSig+1, "CLR")) {
    icInt32Number d0 = icHexDigit(szSig[0]);
    if (d0>=1)
      return true;
  }
  else if (!strcmp(szSig+2, "CL")) {
    icInt32Number d0 = icHexDigit(szSig[0]);
    icInt32Number d1 = icHexDigit(szSig[1]);
    if (d0>=0 && d1>=0) {
      icInt32Number n = (d0<<4) + d1;
      if (n>0xf)
        return true;
    }
  }
  return false;
}
References icHexDigit().
Referenced by CDevLinkWriter::begin().
icLab2Lch()
ICCPROFLIB_API void icLab2Lch (icFloatNumber * Lch, icFloatNumber * Lab = NULL)
{
  if (!Lab) {
    Lab = Lch;
  }
  else
    Lch[0] = Lab[0];
  icFloatNumber c = (icFloatNumber)sqrt((double)Lab[1]*Lab[1] + (double)Lab[2]*Lab[2]);
  icFloatNumber h = (icFloatNumber)(atan2(Lab[2], Lab[1]) * 180.0 / PI);
  while (h<0.0)
    h+=360.0;
  Lch[1] = c;
  Lch[2] = h;
}
Referenced by CIccPRMG::InGamut().
icLabFromPcs()
ICCPROFLIB_API void icLabFromPcs (icFloatNumber * Lab)
Here are some conversion routines to convert to regular Lab encoding.
Floating point encoding of Lab in PCS is in range 0.0 to 1.0
{
  Lab[0] *= 100.0;
  Lab[1] = (icFloatNumber)(Lab[1]*255.0 - 128.0);
  Lab[2] = (icFloatNumber)(Lab[2]*255.0 - 128.0);
}
Referenced by CIccTagColorantTable::Describe(), CIccPRMG::EvaluateProfile(), CIccEvalCompare::EvaluateProfile(), CIccTagNamedColor2::FindCachedPCSColor(), CIccTagNamedColor2::InitFindCachedPCSColor(), main(), CIccApplyBPC::pcs2lab(), CIccTagXmlNamedColor2::ToXml(), and CIccTagXmlColorantTable::ToXml().
icLabToPcs()
ICCPROFLIB_API void icLabToPcs (icFloatNumber * Lab)
{
  Lab[0] /= 100.0;
  Lab[1] = (icFloatNumber)((Lab[1] + 128.0) / 255.0);
  Lab[2] = (icFloatNumber)((Lab[2] + 128.0) / 255.0);
}
Referenced by CIccApplyBPC::lab2pcs(), main(), CIccTagXmlNamedColor2::ParseXml(), and CIccTagXmlColorantTable::ParseXml().
icLabtoXYZ()
ICCPROFLIB_API void icLabtoXYZ (icFloatNumber * XYZ, const icFloatNumber * Lab = NULL, const icFloatNumber * WhiteXYZ = NULL)
{
  if (!Lab)
    Lab = XYZ;
  if (!WhiteXYZ)
    WhiteXYZ = icD50XYZ;
  icFloatNumber fy = (icFloatNumber)((Lab[0] + 16.0) / 116.0);
  XYZ[0] = icICubeth((icFloatNumber)(Lab[1]/500.0 + fy)) * WhiteXYZ[0];
  XYZ[1] = icICubeth(fy) * WhiteXYZ[1];
  XYZ[2] = icICubeth((icFloatNumber)(fy - Lab[2]/200.0)) * WhiteXYZ[2];
}
References icD50XYZ, and icICubeth().
Referenced by CIccApplyBPC::calcDstBlackPoint(), CIccApplyBPC::calcSrcBlackPoint(), CIccApplyBPC::lab2pcs(), and main().
icLch2Lab()
ICCPROFLIB_API void icLch2Lab (icFloatNumber * Lab, icFloatNumber * Lch = NULL)
{
  if (!Lch) {
    Lch = Lab;
  }
  else
    Lab[0] = Lch[0];
  icFloatNumber a = (icFloatNumber)(Lch[1] * cos(Lch[2] * PI / 180.0));
  icFloatNumber b = (icFloatNumber)(Lch[1] * sin(Lch[2] * PI / 180.0));
  Lab[1] = a;
  Lab[2] = b;
}
icMatrixDump()
ICCPROFLIB_API void icMatrixDump (std::string & sDump, icS15Fixed16Number * pMatrix)
{
  icChar buf[128];
  sprintf(buf, "%8.4lf %8.4lf %8.4lf\n", icFtoD(pMatrix[0]), icFtoD(pMatrix[1]), icFtoD(pMatrix[2]));
  sDump += buf;
  sprintf(buf, "%8.4lf %8.4lf %8.4lf\n", icFtoD(pMatrix[3]), icFtoD(pMatrix[4]), icFtoD(pMatrix[5]));
  sDump += buf;
  sprintf(buf, "%8.4lf %8.4lf %8.4lf\n", icFtoD(pMatrix[6]), icFtoD(pMatrix[7]), icFtoD(pMatrix[8]));
  sDump += buf;
}
References icFtoD().
Referenced by CIccTagFixedNum< T, Tsig >::Describe().
icMatrixInvert3x3()
ICCPROFLIB_API bool icMatrixInvert3x3 (icFloatNumber * M)
Name: icMatrixInvert3x3
Purpose: Inversion of a 3x3 matrix using the Adjoint Cofactor and the determinant of the 3x3 matrix.
Note: Matrix index positions: 0 1 2 3 4 5 6 7 8
Args: M = matrix to invert.
Return: true = matrix is invertible and stored back into M, false = matrix is not invertible.
{
  const icFloatNumber epsilon = 1e-8f;
  icFloatNumber m48 = M[4]*M[8];
  icFloatNumber m75 = M[7]*M[5];
  icFloatNumber m38 = M[3]*M[8];
  icFloatNumber m65 = M[6]*M[5];
  icFloatNumber m37 = M[3]*M[7];
  icFloatNumber m64 = M[6]*M[4];
  icFloatNumber det = M[0]*(m48 - m75) -
    M[1]*(m38 - m65) +
    M[2]*(m37 - m64);
  if (det>-epsilon && det<epsilon)
    return false;
  icFloatNumber Co[9] = {0};
  Co[0] = +(m48 - m75);
  Co[1] = -(m38 - m65);
  Co[2] = +(m37 - m64);
  Co[3] = -(M[1]*M[8] - M[7]*M[2]);
  Co[4] = +(M[0]*M[8] - M[6]*M[2]);
  Co[5] = -(M[0]*M[7] - M[6]*M[1]);
  Co[6] = +(M[1]*M[5] - M[4]*M[2]);
  Co[7] = -(M[0]*M[5] - M[3]*M[2]);
  Co[8] = +(M[0]*M[4] - M[3]*M[1]);
  M[0] = Co[0] / det;
  M[1] = Co[3] / det;
  M[2] = Co[6] / det;
  M[3] = Co[1] / det;
  M[4] = Co[4] / det;
  M[5] = Co[7] / det;
  M[6] = Co[2] / det;
  M[7] = Co[5] / det;
  M[8] = Co[8] / det;
  return true;
}
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccMatrixMath::Invert(), CIccSimpleMatrixInverter::Invert(), and CIccSimpleMatrixSolver::Solve().
icMatrixMultiply3x3()
ICCPROFLIB_API void icMatrixMultiply3x3 (icFloatNumber * result, const icFloatNumber * l, const icFloatNumber * r)
Name: icMatrixMultiply3x3
Purpose: Multiply two 3x3 matricies resulting in a 3x3 matrix.
Note: Matrix index positions: 0 1 2 3 4 5 6 7 8
Args: result = matrix to recieve result. l = left matrix to multiply (matrix multiplication is order dependent) r = right matrix to multiply (matrix multiplicaiton is order dependent)
{
  const unsigned int e11 = 0;
  const unsigned int e12 = 1;
  const unsigned int e13 = 2;
  const unsigned int e21 = 3;
  const unsigned int e22 = 4;
  const unsigned int e23 = 5;
  const unsigned int e31 = 6;
  const unsigned int e32 = 7;
  const unsigned int e33 = 8;
  result[e11] = l[e11] * r[e11] + l[e12] * r[e21] + l[e13] * r[e31];
  result[e12] = l[e11] * r[e12] + l[e12] * r[e22] + l[e13] * r[e32];
  result[e13] = l[e11] * r[e13] + l[e12] * r[e23] + l[e13] * r[e33];
  result[e21] = l[e21] * r[e11] + l[e22] * r[e21] + l[e23] * r[e31];
  result[e22] = l[e21] * r[e12] + l[e22] * r[e22] + l[e23] * r[e32];
  result[e23] = l[e21] * r[e13] + l[e22] * r[e23] + l[e23] * r[e33];
  result[e31] = l[e31] * r[e11] + l[e32] * r[e21] + l[e33] * r[e31];
  result[e32] = l[e31] * r[e12] + l[e32] * r[e22] + l[e33] * r[e32];
  result[e33] = l[e31] * r[e13] + l[e32] * r[e23] + l[e33] * r[e33];
}
icMax()
ICCPROFLIB_API icFloatNumber icMax (icFloatNumber v1, icFloatNumber v2)
{
  return( v1 > v2 ? v1 : v2 );
}
Referenced by CIccFormulaCurveSegment::Apply(), CIccOpDefMaximum::Exec(), and CIccOpDefVectorMaximum::Exec().
icMaxStatus()
ICCPROFLIB_API icValidateStatus icMaxStatus (icValidateStatus s1, icValidateStatus s2)
Name: icMaxStatus
Purpose: return worst status
Args: s1, s2
Return:
{
  if (s1>s2)
    return s1;
  return s2;
}
Referenced by CIccInfo::CheckData(), CIccInfo::CheckData(), CIccInfo::CheckData(), CIccInfo::CheckData(), main(), CIccToneMapFunc::Validate(), CIccResponseCurveStruct::Validate(), CIccStructNamedColor::Validate(), CIccTagGamutBoundaryDesc::Validate(), CIccMBB::Validate(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccArrayUnknown::Validate(), CIccArrayColorantInfo::Validate(), CIccArrayNamedColor::Validate(), CIccStructUnknown::Validate(), CIccStructBRDF::Validate(), CIccStructColorantInfo::Validate(), CIccTagText::Validate(), CIccTagUtf8Text::Validate(), CIccTagZipUtf8Text::Validate(), CIccTagUtf16Text::Validate(), CIccTagTextDescription::Validate(), CIccTagSignature::Validate(), CIccTagNamedColor2::Validate(), CIccTagXYZ::Validate(), CIccTagChromaticity::Validate(), CIccTagCicp::Validate(), CIccTagSparseMatrixArray::Validate(), CIccTagNum< T, Tsig >::Validate(), CIccTagFloatNum< T, Tsig >::Validate(), CIccTagMeasurement::Validate(), CIccTagMultiLocalizedUnicode::Validate(), CIccTagData::Validate(), CIccTagDateTime::Validate(), CIccTagColorantOrder::Validate(), CIccTagColorantTable::Validate(), CIccTagViewingConditions::Validate(), CIccTagProfileSeqDesc::Validate(), CIccTagResponseCurveSet16::Validate(), CIccTagSpectralDataInfo::Validate(), CIccTagSpectralViewingConditions::Validate(), CIccTagEmbeddedHeightImage::Validate(), CIccTagEmbeddedNormalImage::Validate(), CIccTagStruct::Validate(), CIccTagArray::Validate(), CIccTagDict::Validate(), CIccTagEmbeddedProfile::Validate(), CIccTagCurve::Validate(), CIccTagParametricCurve::Validate(), CIccCLUT::Validate(), CIccTagMultiProcessElement::Validate(), CIccTagProfileSequenceId::Validate(), CIccFormulaCurveSegment::Validate(), CIccSampledCurveSegment::Validate(), CIccSegmentedCurve::Validate(), CIccSingleSampledCurve::Validate(), CIccSampledCalculatorCurve::Validate(), CIccMpeCurveSet::Validate(), CIccMpeToneMap::Validate(), CIccMpeCAM::Validate(), CIccMpeCalculator::Validate(), CIccMpeSpectralMatrix::Validate(), CIccMpeInvEmissionMatrix::Validate(), CIccMpeSpectralCLUT::Validate(), CIccMpeSpectralObserver::Validate(), ValidateIccProfile(), and ValidateIccProfile().
icMemDump()
ICCPROFLIB_API void icMemDump (std::string & sDump, void * pBuf, icUInt32Number nNum)
{
  icUInt8Number *pData = (icUInt8Number *)pBuf;
  icChar buf[80] = {0};
  icChar num[10] = {0};
  icInt32Number i, j;
  icUInt8Number c;
  icInt32Number lines = (nNum + DUMPBYTESPERLINE - 1)/DUMPBYTESPERLINE;
  sDump.reserve(sDump.size() + lines*79);
  for (i=0; i<(icInt32Number)nNum; i++, pData++) {
    j=i%DUMPBYTESPERLINE;
    if (!j) {
      if (i) {
        sDump += (const icChar*)buf;
      }
      memset(buf, ' ', 76);
      buf[76] = ' ';
      buf[77] = '\n';
      buf[78] = '\0';
      sprintf(num, "%08X:", i);
      strncpy(buf, num, 9);
    }
    sprintf(num, "%02X", *pData);
    strncpy(buf+10+j*3, num, 2);
    c=*pData;
    if (!isprint(c))
      c='.';
    buf[10+16*3 + 1 + j] = c;
  }
  sDump += buf;
}
Referenced by MyTagDialog::MyTagDialog(), CIccMpeAcs::Describe(), CIccTagUnknown::Describe(), CIccTagZipUtf8Text::Describe(), CIccTagData::Describe(), and CIccMpeUnknown::Describe().
icMin()
ICCPROFLIB_API icFloatNumber icMin (icFloatNumber v1, icFloatNumber v2)
{
  return( v1 < v2 ? v1 : v2 );
}
Referenced by CIccEvalCompare::EvaluateProfile(), CIccOpDefMinimum::Exec(), and CIccOpDefVectorMinimum::Exec().
icNormXYZ()
ICCPROFLIB_API void icNormXYZ (icFloatNumber * XYZ, icFloatNumber * WhiteXYZ = NULL)
icRealloc()
ICCPROFLIB_API void * icRealloc (void * ptr, size_t size)
Name: icRealloc
Purpose: realloc memory allocated by malloc or calloc freeing old memory on failure.
Args: ptr - memory block to realloc size - new size of memory block
Return: pointer to reallocated memory block or NULL on failure. Old memory is released on error.
{
  void *nptr;
  if (ptr)
    nptr = realloc(ptr, size);
  else
    nptr = malloc(size);
  if (!nptr && ptr)
    free(ptr);
  return nptr;
}
Referenced by CIccTagZipUtf8Text::AllocBuffer(), CIccUTF16String::FromUtf8(), CIccTagText::GetBuffer(), CIccTagUtf8Text::GetBuffer(), CIccTagUtf16Text::GetBuffer(), CIccTagTextDescription::GetBuffer(), CIccTagTextDescription::GetUnicodeBuffer(), CIccUTF16String::operator=(), CIccUTF16String::operator=(), CIccTagDict::Read(), CIccTagText::Release(), CIccTagUtf8Text::Release(), CIccTagUtf16Text::Release(), CIccTagTextDescription::Release(), CIccTagTextDescription::ReleaseUnicode(), CIccTagSparseMatrixArray::Reset(), CIccUTF16String::Resize(), CIccMpeCalculator::SetElem(), CIccTagChromaticity::SetSize(), CIccTagColorantOrder::SetSize(), CIccTagColorantTable::SetSize(), CIccTagArray::SetSize(), CIccTagXYZ::SetSize(), CIccTagData::SetSize(), CIccTagEmbeddedHeightImage::SetSize(), CIccTagEmbeddedNormalImage::SetSize(), CIccTagCurve::SetSize(), and CIccLocalizedUnicode::SetSize().
icRmsDif()
ICCPROFLIB_API icFloatNumber icRmsDif (const icFloatNumber * v1, const icFloatNumber * v2, icUInt32Number nSample)
{
  icFloatNumber sum=0;
  icUInt32Number i;
  for (i=0; i<nSample; i++) {
    sum += icSq(v1[i] - v2[i]);
  }
  if (nSample)
    sum /= nSample;
  return (icFloatNumber)sqrt(sum);
}
References icSq().
Referenced by CIccArrayNamedColor::FindSpectralColor().
icRoundOffset()
ICCPROFLIB_API double icRoundOffset (double v)
Name: icRoundOffset
Purpose: Adds offset to floating point value for purposes of rounding by casting to and integer based value
Args: v - value to offset
Return: v with offset added - suitable for casting to some form of integer
{
  if (v < 0.0)
    return v - 0.5;
  else
    return v + 0.5;
}
Referenced by icDtoF(), icDtoUCF(), icDtoUF(), icDtoUSF(), icFtoU16(), and icFtoU8().
icSameSpectralRange()
bool ICCPROFLIB_API icSameSpectralRange (const icSpectralRange & rng1, const icSpectralRange & rng2)
{
  return (rng1.start == rng2.start &&
          rng1.end == rng2.end &&
          rng1.steps == rng2.steps);
}
References icSpectralRange::end, icSpectralRange::start, and icSpectralRange::steps.
icSwab16Array()
void icSwab16Array (void * pVoid, int num) inline
{
  icUInt8Number *ptr = (icUInt8Number*)pVoid;
  icUInt8Number tmp;
  while (num>0) {
    tmp = ptr[0]; ptr[0] = ptr[1]; ptr[1] = tmp;
    ptr += 2;
    num--;
  }
}
Referenced by CIccIO::Read16().
icSwab16Ptr()
void icSwab16Ptr (void * pVoid) inline
{
  icUInt8Number *ptr = (icUInt8Number*)pVoid;
  icUInt8Number tmp;
  tmp = ptr[0]; ptr[0] = ptr[1]; ptr[1] = tmp;
}
icSwab32Array()
void icSwab32Array (void * pVoid, int num) inline
{
  icUInt8Number *ptr = (icUInt8Number*)pVoid;
  icUInt8Number tmp;
  while (num>0) {
    tmp = ptr[0]; ptr[0] = ptr[3]; ptr[3] = tmp;
    tmp = ptr[1]; ptr[1] = ptr[2]; ptr[2] = tmp;
    ptr += 4;
    num--;
  }
}
Referenced by CIccIO::Read32().
icSwab32Ptr()
void icSwab32Ptr (void * pVoid) inline
{
  icUInt8Number *ptr = (icUInt8Number*)pVoid;
  icUInt8Number tmp;
  tmp = ptr[0]; ptr[0] = ptr[3]; ptr[3] = tmp;
  tmp = ptr[1]; ptr[1] = ptr[2]; ptr[2] = tmp;
}
icSwab64Array()
void icSwab64Array (void * pVoid, int num) inline
{
  icUInt8Number *ptr = (icUInt8Number*)pVoid;
  icUInt8Number tmp;
  while (num>0) {
    tmp = ptr[0]; ptr[0] = ptr[7]; ptr[7] = tmp;
    tmp = ptr[1]; ptr[1] = ptr[6]; ptr[6] = tmp;
    tmp = ptr[2]; ptr[2] = ptr[5]; ptr[5] = tmp;
    tmp = ptr[3]; ptr[3] = ptr[4]; ptr[4] = tmp;
    ptr += 8;
    num--;
  }
}
Referenced by CIccIO::Read64().
icSwab64Ptr()
void icSwab64Ptr (void * pVoid) inline
{
  icUInt8Number *ptr = (icUInt8Number*)pVoid;
  icUInt8Number tmp;
  tmp = ptr[0]; ptr[0] = ptr[7]; ptr[7] = tmp;
  tmp = ptr[1]; ptr[1] = ptr[6]; ptr[6] = tmp;
  tmp = ptr[2]; ptr[2] = ptr[5]; ptr[5] = tmp;
  tmp = ptr[3]; ptr[3] = ptr[4]; ptr[4] = tmp;
}
icU16toF()
ICCPROFLIB_API icFloatNumber icU16toF (icUInt16Number num)
{
  icFloatNumber rv = (icFloatNumber)((icFloatNumber)num / 65535.0);
  return rv;
}
Referenced by CIccTagColorantTable::Describe(), CIccTagNum< T, Tsig >::GetValues(), CIccTagNum< T, Tsig >::Interpolate(), CIccTagXmlColorantTable::ToXml(), and CIccTagNum< T, Tsig >::ValuePos().
icU8toAB()
ICCPROFLIB_API icFloatNumber icU8toAB (icUInt8Number num)
{
  return (icFloatNumber)num - 128.0f;
}
icU8toF()
ICCPROFLIB_API icFloatNumber icU8toF (icUInt8Number num)
{
  icFloatNumber rv = (icFloatNumber)((icFloatNumber)num / 255.0);
  return rv;
}
Referenced by CIccTagNum< T, Tsig >::GetValues(), CIccTagNum< T, Tsig >::Interpolate(), and CIccTagNum< T, Tsig >::ValuePos().
icUCFtoD()
ICCPROFLIB_API icFloatNumber icUCFtoD (icU8Fixed8Number num)
{
  icFloatNumber rv = (icFloatNumber)((icFloatNumber)num / 256.0);
  return rv;
}
icUFtoD()
ICCPROFLIB_API icFloatNumber icUFtoD (icU16Fixed16Number num)
{
  icFloatNumber rv = (icFloatNumber)((double)num / 65536.0);
  return rv;
}
Referenced by CIccTagChromaticity::Describe(), and CIccTagXmlChromaticity::ToXml().
icUSFtoD()
ICCPROFLIB_API icFloatNumber icUSFtoD (icU1Fixed15Number num)
{
  icFloatNumber rv = (icFloatNumber)((icFloatNumber)num / 32768.0);
  return rv;
}
Referenced by CIccTagColorantTable::Describe().
icValidOverlap()
ICCPROFLIB_API bool icValidOverlap (const icPositionNumber & pos1, const icPositionNumber & pos2, bool bAllowSame)
Name: icValidOverlap
Purpose: Checks if pos overlap is acceptable
Args: pos1 - first positionNumber pos2 - second positionNumber bAllowSame - allow to positions to cover the same area
Return: true if v1 is near v2 within range
{
  if ((icUInt64Number)pos1.offset + pos1.size <= (icUInt64Number)pos2.offset ||
      (icUInt64Number)pos1.offset >= (icUInt64Number)pos2.offset + pos2.size)
    return true;
  if (bAllowSame && pos1.offset == pos2.offset || pos1.size == pos2.size)
    return true;
  return false;
}
References icPositionNumber::offset, and icPositionNumber::size.
Referenced by CIccMpeToneMap::Read().
icValidTagPos()
ICCPROFLIB_API bool icValidTagPos (const icPositionNumber & pos, icUInt32Number nTagHeaderSize, icUInt32Number nTagSize, bool bAllowEmpty)
Name: icValidTagPos
Purpose: Checks if pos is valid for data within a tag
Args: pos - first value nTagHeaderSize - size of tag header nTagSize - total size of tag data
Return: true pos is valid
{
  if (bAllowEmpty && !pos.size || !pos.offset)
    return true;
  if (pos.offset < nTagHeaderSize)
    return false;
  if ((icUInt64Number)pos.offset + pos.size > (icUInt64Number)nTagSize)
    return false;
  if (!pos.size && !bAllowEmpty)
    return false;
  return true;
}
References icPositionNumber::offset, and icPositionNumber::size.
Referenced by CIccMpeToneMap::Read().
icVectorApplyMatrix3x3()
ICCPROFLIB_API void icVectorApplyMatrix3x3 (icFloatNumber * result, const icFloatNumber * m, const icFloatNumber * v)
Name: icVectorApplyMatrix3x3
Purpose: Applies a 3x3 matrix to a 3 element column vector.
Note: Matrix index positions: 0 1 2 3 4 5 6 7 8
Note: result = m x v
Args: result = vector to receive result. m = matrix to multiply v = vector to apply matrix to
{
  const unsigned int e11 = 0;
  const unsigned int e12 = 1;
  const unsigned int e13 = 2;
  const unsigned int e21 = 3;
  const unsigned int e22 = 4;
  const unsigned int e23 = 5;
  const unsigned int e31 = 6;
  const unsigned int e32 = 7;
  const unsigned int e33 = 8;
  result[0] = m[e11] * v[0] + m[e12] * v[1] + m[e13] * v[2];
  result[1] = m[e21] * v[0] + m[e22] * v[1] + m[e23] * v[2];
  result[2] = m[e31] * v[0] + m[e32] * v[1] + m[e33] * v[2];
}
Referenced by CIccSimpleMatrixSolver::Solve().
icXyzFromPcs()
ICCPROFLIB_API void icXyzFromPcs (icFloatNumber * XYZ)
Here are some conversion routines to convert to regular XYZ encoding.
Floating point encoding of XYZ in PCS is in range 0.0 to 1.0 (Note: X=1.0 is encoded as about 0.5)
{
  XYZ[0] = (icFloatNumber)(XYZ[0] * 65535.0 / 32768.0);
  XYZ[1] = (icFloatNumber)(XYZ[1] * 65535.0 / 32768.0);
  XYZ[2] = (icFloatNumber)(XYZ[2] * 65535.0 / 32768.0);
}
Referenced by CIccTagNamedColor2::FindCachedPCSColor(), CIccTagNamedColor2::InitFindCachedPCSColor(), main(), CIccApplyBPC::pcs2lab(), and CIccTagXmlNamedColor2::ToXml().
icXYZtoLab()
ICCPROFLIB_API void icXYZtoLab (icFloatNumber * Lab, const icFloatNumber * XYZ = NULL, const icFloatNumber * WhiteXYZ = NULL)
{
  icFloatNumber Xn, Yn, Zn;
  if (!XYZ)
    XYZ = Lab;
  if (!WhiteXYZ)
    WhiteXYZ = icD50XYZ;
  Xn = icCubeth(XYZ[0] / WhiteXYZ[0]);
  Yn = icCubeth(XYZ[1] / WhiteXYZ[1]);
  Zn = icCubeth(XYZ[2] / WhiteXYZ[2]);
  Lab[0] = (icFloatNumber)(116.0 * Yn - 16.0);
  Lab[1] = (icFloatNumber)(500.0 * (Xn - Yn));
  Lab[2] = (icFloatNumber)(200.0 * (Yn - Zn));
}
References icCubeth(), and icD50XYZ.
Referenced by CIccMpeSpectralObserver::Apply(), CIccMpeEmissionCLUT::Begin(), CIccMpeReflectanceCLUT::Begin(), CIccApplyBPC::calcDstBlackPoint(), CIccTagNamedColor2::FindCachedPCSColor(), CIccArrayNamedColor::FindPcsColor(), CIccTagNamedColor2::InitFindCachedPCSColor(), main(), and CIccApplyBPC::pcs2lab().
icXyzToPcs()
ICCPROFLIB_API void icXyzToPcs (icFloatNumber * XYZ)
{
  XYZ[0] = (icFloatNumber)(XYZ[0] * 32768.0 / 65535.0);
  XYZ[1] = (icFloatNumber)(XYZ[1] * 32768.0 / 65535.0);
  XYZ[2] = (icFloatNumber)(XYZ[2] * 32768.0 / 65535.0);
}
Referenced by CIccApplyBPC::CalcFactors(), CIccApplyBPC::lab2pcs(), main(), and CIccTagXmlNamedColor2::ParseXml().
Variable Documentation
icD50XYZ
ICCPROFLIB_API icFloatNumber icD50XYZ[3] extern
{ 0.9642f, 1.0000f, 0.8249f };
Referenced by CIccCamConverter::CIccCamConverter(), CIccDefaultEncProfileConverter::ConvertFromParams(), icDeNormXyz(), icLabtoXYZ(), icNormXyz(), icXYZtoLab(), and CIccTagSpectralViewingConditions::setIlluminant().
icD50XYZxx
ICCPROFLIB_API icFloatNumber icD50XYZxx[3] extern
{ 96.42f, 100.00f, 82.49f };
icInfo
ICCPROFLIB_API CIccInfo icInfo extern
icMsgValidateCriticalError
ICCPROFLIB_API const char* icMsgValidateCriticalError extern
Referenced by CIccToneMapFunc::Validate(), CIccCalculatorFunc::Validate(), CIccMBB::Validate(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccTagChromaticity::Validate(), CIccTagSparseMatrixArray::Validate(), CIccTagNum< T, Tsig >::Validate(), CIccTagFloatNum< T, Tsig >::Validate(), CIccTagSpectralDataInfo::Validate(), CIccTagSpectralViewingConditions::Validate(), CIccTagArray::Validate(), CIccTagEmbeddedProfile::Validate(), CIccTagParametricCurve::Validate(), CIccCLUT::Validate(), CIccTagMultiProcessElement::Validate(), CIccFormulaCurveSegment::Validate(), CIccSampledCurveSegment::Validate(), CIccSegmentedCurve::Validate(), CIccSingleSampledCurve::Validate(), CIccSampledCalculatorCurve::Validate(), CIccMpeCurveSet::Validate(), CIccMpeTintArray::Validate(), CIccMpeToneMap::Validate(), CIccMpeMatrix::Validate(), CIccMpeCLUT::Validate(), CIccMpeExtCLUT::Validate(), CIccMpeCAM::Validate(), CIccMpeCalculator::Validate(), CIccMpeSpectralMatrix::Validate(), CIccMpeInvEmissionMatrix::Validate(), CIccMpeSpectralCLUT::Validate(), CIccMpeSpectralObserver::Validate(), CIccMpeUnknown::Validate(), ValidateIccProfile(), ValidateIccProfile(), and ValidateIccProfile().
icMsgValidateInformation
ICCPROFLIB_API const char* icMsgValidateInformation extern
Referenced by CIccMpeToneMap::Validate().
icMsgValidateNonCompliant
ICCPROFLIB_API const char* icMsgValidateNonCompliant extern
Referenced by CIccInfo::CheckData(), CIccInfo::CheckData(), CIccInfo::CheckData(), main(), CIccResponseCurveStruct::Validate(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTag::Validate(), CIccTagText::Validate(), CIccTagTextDescription::Validate(), CIccTagSignature::Validate(), CIccTagNamedColor2::Validate(), CIccTagChromaticity::Validate(), CIccTagCicp::Validate(), CIccTagSparseMatrixArray::Validate(), CIccTagMeasurement::Validate(), CIccTagData::Validate(), CIccTagColorantOrder::Validate(), CIccTagColorantTable::Validate(), CIccTagProfileSeqDesc::Validate(), CIccTagSpectralViewingConditions::Validate(), CIccTagEmbeddedHeightImage::Validate(), CIccTagEmbeddedNormalImage::Validate(), CIccTagParametricCurve::Validate(), CIccMatrix::Validate(), CIccCLUT::Validate(), and CIccMultiProcessElement::Validate().
icMsgValidateWarning
ICCPROFLIB_API const char* icMsgValidateWarning extern
Referenced by CIccInfo::CheckData(), CIccInfo::CheckLuminance(), main(), CIccToneMapFunc::Validate(), CIccCalculatorFunc::Validate(), CIccStructNamedColor::Validate(), CIccTagGamutBoundaryDesc::Validate(), CIccMBB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccStructBRDF::Validate(), CIccStructColorantInfo::Validate(), CIccTagText::Validate(), CIccTagUtf8Text::Validate(), CIccTagZipUtf8Text::Validate(), CIccTagUtf16Text::Validate(), CIccTagNamedColor2::Validate(), CIccTagXYZ::Validate(), CIccTagSparseMatrixArray::Validate(), CIccTagMultiLocalizedUnicode::Validate(), CIccTagData::Validate(), CIccTagColorantOrder::Validate(), CIccTagColorantTable::Validate(), CIccTagResponseCurveSet16::Validate(), CIccTagStruct::Validate(), CIccTagDict::Validate(), CIccTagEmbeddedProfile::Validate(), CIccTagCurve::Validate(), CIccTagParametricCurve::Validate(), CIccTagMultiProcessElement::Validate(), CIccFormulaCurveSegment::Validate(), CIccSampledCurveSegment::Validate(), CIccSegmentedCurve::Validate(), CIccSingleSampledCurve::Validate(), and CIccSampledCalculatorCurve::Validate().