iccDEV: IIccTagFactory Class Reference
IIccTagFactory Class Reference abstract
#include <IccTagFactory.h>
Public Member Functions
virtual ~IIccTagFactory ()
virtual CIccTag * CreateTag (icTagTypeSignature tagTypeSig)=0
virtual icTagSignature GetTagNameSig (const icChar *szTagName)=0
virtual const icChar * GetTagSigName (icTagSignature tagSig)=0
virtual icTagTypeSignature GetTagTypeNameSig (const icChar *szTypeName)=0
virtual const icChar * GetTagTypeSigName (icTagTypeSignature tagTypeSig)=0
Detailed Description
Class: IIccTagFactory
Purpose: IIccTagFactory is a factory pattern interface for CIccTag creation. This class is pure virtual.
Constructor & Destructor Documentation
~IIccTagFactory()
virtual IIccTagFactory::~IIccTagFactory () inline virtual
{}
Member Function Documentation
CreateTag()
virtual CIccTag * IIccTagFactory::CreateTag (icTagTypeSignature tagTypeSig) pure virtual
Function: CreateTag(tagTypeSig) Create a tag of type tagTypeSig.
Parameter(s): tagTypeSig = signature of the ICC tag type for the tag to be created
Returns a new CIccTag object of the given signature type. If the tag factory doesn't support creation of tags of type tagTypeSig then it should return NULL.
Implemented in CIccSpecTagFactory, and CIccTagXmlFactory.
Referenced by CIccTagCreator::DoCreateTag().
GetTagNameSig()
virtual icTagSignature IIccTagFactory::GetTagNameSig (const icChar * szTagName) pure virtual
Function: GetTagNameSig(szTagName) Get signature from tag display name.
Parameter(s): szTagName = name of tag
Returns tag signature of tag if tag name is recognized by the factory, icSigUnknownTag if the tag name is not recognized.
Implemented in CIccSpecTagFactory, and CIccTagXmlFactory.
Referenced by CIccTagCreator::DoGetTagNameSig().
GetTagSigName()
virtual const icChar * IIccTagFactory::GetTagSigName (icTagSignature tagSig) pure virtual
Function: GetTagSigName(tagSig) Get display name of tagSig.
Parameter(s): tagSig = signature of the ICC tag to get a name for
Returns pointer to string containing name of tag if tag is recognized by the factory, NULL if the factory doesn't create tagSig tags.
Implemented in CIccSpecTagFactory, and CIccTagXmlFactory.
Referenced by CIccTagCreator::DoGetTagSigName().
GetTagTypeNameSig()
virtual icTagTypeSignature IIccTagFactory::GetTagTypeNameSig (const icChar * szTypeName) pure virtual
Function: GetTagTypeNameSig(szTypeName) Get signature based on display name of tag type.
Parameter(s): szTypeName = name of the ICC tag type to get a signature for
Returns tag type signature of tag type name if type name is recognized by the factory, icSigUnknownType if the type name is not recognized.
Implemented in CIccSpecTagFactory, and CIccTagXmlFactory.
Referenced by CIccTagCreator::DoGetTagTypeNameSig().
GetTagTypeSigName()
virtual const icChar * IIccTagFactory::GetTagTypeSigName (icTagTypeSignature tagTypeSig) pure virtual
Function: GetTagTypeSigName(tagTypeSig) Get display name of tagTypeSig.
Parameter(s): tagTypeSig = signature of the ICC tag type to get a name for
Returns pointer to string containing name of tag type if tag is recognized by the factory, NULL if the factory doesn't create tagTypeSig tags.
Implemented in CIccSpecTagFactory, and CIccTagXmlFactory.
Referenced by CIccTagCreator::DoGetTagTypeSigName().
The documentation for this class was generated from the following file:
IccProfLib/IccTagFactory.h