iccDEV: CIccCmmEnvVarHint Class Reference
CIccCmmEnvVarHint Class Reference
#include <IccEnvVar.h>
Inherits CIccCreateCmmEnvVarXformHint.
Public Member Functions
CIccCmmEnvVarHint (icCmmEnvSigMap &map)
virtual ~CIccCmmEnvVarHint ()
virtual IIccCmmEnvVarLookup * GetNewCmmEnvVarLookup () const
Protected Attributes
icCmmEnvSigMap * m_map
Detailed Description
Constructor & Destructor Documentation
CIccCmmEnvVarHint()
CIccCmmEnvVarHint::CIccCmmEnvVarHint (icCmmEnvSigMap & map)
{
  m_map = new icCmmEnvSigMap();
  *m_map = map;
}
References m_map.
Referenced by main(), main(), and main().
~CIccCmmEnvVarHint()
CIccCmmEnvVarHint::~CIccCmmEnvVarHint () virtual
{
  delete m_map;
}
References m_map.
Member Function Documentation
GetNewCmmEnvVarLookup()
virtual IIccCmmEnvVarLookup * CIccCmmEnvVarHint::GetNewCmmEnvVarLookup () const inline virtual
{ return new CIccCmmVarLookup(*m_map);}
References CIccCmmVarLookup::CIccCmmVarLookup(), and m_map.
Field Documentation
m_map
icCmmEnvSigMap* CIccCmmEnvVarHint::m_map protected
Referenced by CIccCmmEnvVarHint(), ~CIccCmmEnvVarHint(), and GetNewCmmEnvVarLookup().
The documentation for this class was generated from the following files:
IccProfLib/IccEnvVar.h
IccProfLib/IccEnvVar.cpp