iccDEV: CIccCurveXml Class Reference
CIccCurveXml Class Reference abstract
#include <IccTagXml.h>
Public Member Functions
virtual ~CIccCurveXml ()
virtual const char * GetExtClassName () const
virtual const char * GetExtDerivedClassName () const
virtual bool ParseXml (xmlNode *pNode, icConvertType nType, std::string &parseStr)=0
virtual bool ParseXml (xmlNode *pNode, std::string &parseStr)=0
virtual bool ToXml (std::string &xml, icConvertType nType, std::string blanks)=0
virtual bool ToXml (std::string &xml, std::string blanks="")=0
Detailed Description
Constructor & Destructor Documentation
~CIccCurveXml()
virtual CIccCurveXml::~CIccCurveXml () inline virtual
{}
Member Function Documentation
GetExtClassName()
virtual const char * CIccTagXml::GetExtClassName () const inline virtual inherited
Implements IIccExtensionTag.
{ return "CIccTagXml"; }
Referenced by icProfDescToXml(), and icXmlParseProfDesc().
GetExtDerivedClassName()
virtual const char * CIccCurveXml::GetExtDerivedClassName () const inline virtual
Reimplemented from CIccTagXml.
{return "CIccCurveXml"; }
ParseXml() [1/2]
virtual bool CIccCurveXml::ParseXml (xmlNode * pNode, icConvertType nType, std::string & parseStr) pure virtual
Implemented in CIccTagXmlCurve, CIccTagXmlParametricCurve, and CIccTagXmlSegmentedCurve.
Referenced by icCurvesFromXml().
ParseXml() [2/2]
virtual bool CIccTagXml::ParseXml (xmlNode * pNode, std::string & parseStr) pure virtual inherited
Implemented in CIccTagXmlUnknown, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, CIccTagXmlSignature, CIccTagXmlNamedColor2, CIccTagXmlXYZ, CIccTagXmlChromaticity, CIccTagXmlCicp, CIccTagXmlSparseMatrixArray, CIccTagXmlFixedNum< T, Tsig >, CIccTagXmlNum< T, A, Tsig >, CIccTagXmlFloatNum< T, A, Tsig >, CIccTagXmlMeasurement, CIccTagXmlMultiLocalizedUnicode, CIccTagXmlTagData, CIccTagXmlDateTime, CIccTagXmlColorantOrder, CIccTagXmlColorantTable, CIccTagXmlViewingConditions, CIccTagXmlSpectralDataInfo, CIccTagXmlSpectralViewingConditions, CIccTagXmlProfileSeqDesc, CIccTagXmlResponseCurveSet16, CIccTagXmlCurve, CIccTagXmlParametricCurve, CIccTagXmlSegmentedCurve, CIccTagXmlLutAtoB, CIccTagXmlLutBtoA, CIccTagXmlLut8, CIccTagXmlLut16, CIccTagXmlMultiProcessElement, CIccTagXmlProfileSequenceId, CIccTagXmlDict, CIccTagXmlStruct, CIccTagXmlArray, CIccTagXmlGamutBoundaryDesc, CIccTagXmlEmbeddedHeightImage, CIccTagXmlEmbeddedNormalImage, and CIccTagXmlEmbeddedProfile.
Referenced by icCurvesFromXml(), icXmlParseProfDesc(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), and CIccTagXmlArray::ParseXml().
ToXml() [1/2]
virtual bool CIccCurveXml::ToXml (std::string & xml, icConvertType nType, std::string blanks) pure virtual
Implemented in CIccTagXmlCurve, CIccTagXmlParametricCurve, and CIccTagXmlSegmentedCurve.
Referenced by icCurvesToXml().
ToXml() [2/2]
virtual bool CIccTagXml::ToXml (std::string & xml, std::string blanks = "") pure virtual inherited
Implemented in CIccTagXmlUnknown, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, CIccTagXmlSignature, CIccTagXmlNamedColor2, CIccTagXmlXYZ, CIccTagXmlChromaticity, CIccTagXmlCicp, CIccTagXmlSparseMatrixArray, CIccTagXmlFixedNum< T, Tsig >, CIccTagXmlNum< T, A, Tsig >, CIccTagXmlFloatNum< T, A, Tsig >, CIccTagXmlMeasurement, CIccTagXmlMultiLocalizedUnicode, CIccTagXmlTagData, CIccTagXmlDateTime, CIccTagXmlColorantOrder, CIccTagXmlColorantTable, CIccTagXmlViewingConditions, CIccTagXmlSpectralDataInfo, CIccTagXmlSpectralViewingConditions, CIccTagXmlProfileSeqDesc, CIccTagXmlResponseCurveSet16, CIccTagXmlCurve, CIccTagXmlParametricCurve, CIccTagXmlSegmentedCurve, CIccTagXmlLutAtoB, CIccTagXmlLutBtoA, CIccTagXmlLut8, CIccTagXmlLut16, CIccTagXmlMultiProcessElement, CIccTagXmlProfileSequenceId, CIccTagXmlDict, CIccTagXmlStruct, CIccTagXmlArray, CIccTagXmlGamutBoundaryDesc, CIccTagXmlEmbeddedHeightImage, CIccTagXmlEmbeddedNormalImage, and CIccTagXmlEmbeddedProfile.
Referenced by icProfDescToXml(), CIccMpeXmlTintArray::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
The documentation for this class was generated from the following file:
IccXML/IccLibXML/IccTagXml.h