iccDEV: CIccStructTintZero Class Reference
CIccStructTintZero Class Reference
#include <IccStructBasic.h>
Public Member Functions
CIccStructTintZero (CIccTagStruct *pTagStruct=NULL)
virtual ~CIccStructTintZero ()
virtual void Describe (std::string &sDescription, int nVerboseness) const
virtual const icChar * GetClassName () const
virtual const icChar * GetDisplayName () const
CIccTag * GetElem (icSignature sigElem) const
virtual std::string GetElemName (icSignature sigElem) const
virtual icSignature GetElemSig (const icChar *szElemName) const
std::string getName () const
CIccTagNumArray * GetNumArray (icSignature sigElem) const
CIccTagStruct * GetTagStruct ()
bool GetTint (icFloatNumber *dstColor, icFloatNumber tint, CIccTagNumArray *pZero, icSignature sigElem, icUInt32Number nSamples) const
virtual IIccStruct * NewCopy (CIccTagStruct *pNewTagStruct) const
icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile) const
Protected Member Functions
TagEntryList * getTagEntries () const
Protected Attributes
SIccElemNameSig * m_pElemNameSigTable
CIccTagStruct * m_pTagStruct
Detailed Description
Class: CIccStructTintZero
Purpose: The Named Color struct handler
Constructor & Destructor Documentation
CIccStructTintZero()
CIccStructTintZero::CIccStructTintZero (CIccTagStruct * pTagStruct = NULL)
{
  m_pTagStruct = pTagStruct;
  m_pElemNameSigTable = g_IccStructTintZeroMbrTable;
}
References g_IccStructTintZeroMbrTable, CIccStructUnknown::m_pElemNameSigTable, and IIccStruct::m_pTagStruct.
Referenced by CIccBasicStructFactory::CreateStruct(), and NewCopy().
~CIccStructTintZero()
CIccStructTintZero::~CIccStructTintZero () virtual
{
}
Member Function Documentation
Describe()
void CIccStructUnknown::Describe (std::string & sDescription, int nVerboseness) const virtual inherited
Reimplemented from IIccStruct.
{
  char buf[256];
  CIccInfo info;
  int n;
  if (m_pTagStruct) {
    TagEntryList *entries = m_pTagStruct->GetElemList();
    TagEntryList::iterator i;
    for (n=0, i=entries->begin(); i!=entries->end(); n++, i++) {
      if (i->pTag) {
        if (n)
          sDescription += "\n";
        sprintf(buf, "Begin SubTag(%s)\n", GetElemName(i->TagInfo.sig).c_str());
        sDescription += buf;
        i->pTag->Describe(sDescription, nVerboseness);
        sprintf(buf, "End SubTag(%s)\n", GetElemName(i->TagInfo.sig).c_str());
        sDescription += buf;
      }
    }
  }
}
References CIccTag::Describe(), CIccTagStruct::GetElemList(), CIccStructUnknown::GetElemName(), IIccStruct::m_pTagStruct, and icTag::sig.
Referenced by CIccTagStruct::Describe().
GetClassName()
virtual const icChar * CIccStructTintZero::GetClassName () const inline virtual
Reimplemented from CIccStructNamedColor.
{ return "CIccStructTintZero"; }
GetDisplayName()
virtual const icChar * CIccStructTintZero::GetDisplayName () const inline virtual
Reimplemented from CIccStructNamedColor.
{ return "tintZeroStructure"; }
GetElem()
CIccTag * CIccStructUnknown::GetElem (icSignature sigElem) const inherited
{
  if (!m_pTagStruct)
    return NULL;
  return m_pTagStruct->FindElem(sigElem);
}
References CIccTagStruct::FindElem(), and IIccStruct::m_pTagStruct.
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccStructBRDF::GetBRDFFunction(), CIccStructBRDF::GetBRDFType(), and CIccStructNamedColor::GetNumArray().
GetElemName()
std::string CIccStructUnknown::GetElemName (icSignature sigElem) const virtual inherited
Implements IIccStruct.
{
  if (m_pElemNameSigTable) {
    int i;
    for (i = 0; m_pElemNameSigTable[i].szName; i++) {
      if (m_pElemNameSigTable[i].nSig == sigElem)
        return m_pElemNameSigTable[i].szName;
    }
  }
  CIccInfo info;
  std::string str;
  str = "PrivateSubTag";
  //str += info.GetSigName(sigElem);
  return str;
}
References CIccStructUnknown::m_pElemNameSigTable, SIccElemNameSig::nSig, and SIccElemNameSig::szName.
Referenced by CIccStructUnknown::Describe().
GetElemSig()
icSignature CIccStructUnknown::GetElemSig (const icChar * szElemName) const virtual inherited
Implements IIccStruct.
{
  if (m_pElemNameSigTable) {
    int i;
    for (i = 0; m_pElemNameSigTable[i].szName; i++) {
      if (!strcmp(m_pElemNameSigTable[i].szName, szElemName))
        return m_pElemNameSigTable[i].nSig;
    }
  }
  return (icSignature)0;
}
References CIccStructUnknown::m_pElemNameSigTable, SIccElemNameSig::nSig, and SIccElemNameSig::szName.
getName()
std::string CIccStructNamedColor::getName () const inherited
{
  CIccTag *pTag = m_pTagStruct->FindElem(icSigNmclNameMbr);
  if (pTag && pTag->GetType()==icSigUtf8TextType) {
    CIccTagUtf8Text *pText = (CIccTagUtf8Text*)pTag;
    return std::string((char*)pText->GetText());
  }
  return "";
}
References CIccTagStruct::FindElem(), CIccTagUtf8Text::GetText(), CIccTag::GetType(), icSigNmclNameMbr, icSigUtf8TextType, and IIccStruct::m_pTagStruct.
Referenced by CIccArrayNamedColor::Begin().
GetNumArray()
CIccTagNumArray * CIccStructNamedColor::GetNumArray (icSignature sigElem) const inherited
{
  CIccTag *pTag = GetElem(sigElem);
  if (pTag && pTag->IsNumArrayType())
    return (CIccTagNumArray*)pTag;
  return NULL;
}
References CIccStructUnknown::GetElem(), and CIccTag::IsNumArrayType().
Referenced by CIccArrayNamedColor::GetDeviceTint(), CIccArrayNamedColor::GetPcsTint(), CIccArrayNamedColor::GetSpectralTint(), CIccStructNamedColor::GetTint(), and CIccArrayNamedColor::Validate().
getTagEntries()
TagEntryList * IIccStruct::getTagEntries () const protected inherited
{
  if (m_pTagStruct)
    return m_pTagStruct->m_ElemEntries;
  return NULL;
}
References CIccTagStruct::m_ElemEntries, and IIccStruct::m_pTagStruct.
Referenced by CIccStructUnknown::Validate().
GetTagStruct()
CIccTagStruct * IIccStruct::GetTagStruct () inline inherited
{ return m_pTagStruct; }
References IIccStruct::m_pTagStruct.
GetTint()
bool CIccStructNamedColor::GetTint (icFloatNumber * dstColor, icFloatNumber tint, CIccTagNumArray * pZero, icSignature sigElem, icUInt32Number nSamples) const inherited
{
  if (tint<0.0f)
    tint = 0.0f;
  else if (tint>1.0f)
    tint = 1.0f;
  CIccTagNumArray *pData;
  CIccTagNumArray *pTint;
  pData = GetNumArray(sigElem);
  pTint = GetNumArray(icSigNmclTintMbr);
  if (!pData || !nSamples)
    return false;
  int nEntries = pData->GetNumValues()/nSamples;
  if (nEntries<1)
    return false;
  bool bNoZero;
  bool bNeedZero;
  icFloatNumber pos;
  if (pTint) {
    if (pTint->GetNumValues()!=nEntries)
      return false;
    if (!pTint->ValuePos(pos, tint, bNoZero))
      return false;
    bNeedZero = (pos<0.0f);
    if (bNoZero)
      pos = (pos + 1.0f)/nEntries;
    else
      pos = pos / (nEntries-1.0f);
  }
  else {
    bNoZero = true;
    bNeedZero = true;
    pos = tint;
  }
  icFloatNumber vals[256];
  icFloatNumber *zeroVals=NULL;
  if (bNoZero) {
    if (!pZero || pZero->GetNumValues()!=nSamples)
      return false;
    if (bNeedZero) {
      if (nSamples<256)
        zeroVals = vals;
      else if (bNeedZero)
        zeroVals = new icFloatNumber[nSamples];
      pZero->GetValues(zeroVals, 0, nSamples);
    }
    else {
      zeroVals = vals;
    }
  }
  bool rv = pData->Interpolate(dstColor, pos, nSamples, zeroVals);
  if (zeroVals && zeroVals!=vals)
    delete [] zeroVals;
  return rv;
}
References CIccStructNamedColor::GetNumArray(), CIccTagNumArray::GetNumValues(), CIccTagNumArray::GetValues(), icSigNmclTintMbr, CIccTagNumArray::Interpolate(), and CIccTagNumArray::ValuePos().
Referenced by CIccArrayNamedColor::GetDeviceTint(), CIccArrayNamedColor::GetPcsTint(), and CIccArrayNamedColor::GetSpectralTint().
NewCopy()
IIccStruct * CIccStructTintZero::NewCopy (CIccTagStruct * pNewTagStruct) const virtual
Reimplemented from CIccStructNamedColor.
{
  CIccStructTintZero *rv = new CIccStructTintZero(pTagStruct);
  return rv;
}
References CIccStructTintZero().
Validate()
icValidateStatus CIccStructNamedColor::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile) const virtual inherited
Reimplemented from CIccStructUnknown.
{
  icValidateStatus rv = icValidateOK;
  if (m_pTagStruct) {
    if (m_pTagStruct->GetTagStructType()==icSigNamedColorStruct && !m_pTagStruct->FindElem(icSigNmclNameMbr)) {
      CIccInfo Info;
      std::string sSigPathName = Info.GetSigPathName(sigPath);
      rv = icValidateCriticalError;
      sReport += icMsgValidateWarning;
      sReport += sSigPathName;
      sReport += " - Missing required struct member(s).\n";
    }
  }
  return icMaxStatus(rv, CIccStructUnknown::Validate(sigPath, sReport, pProfile));
}
References CIccTagStruct::FindElem(), CIccInfo::GetSigPathName(), CIccTagStruct::GetTagStructType(), icMaxStatus(), icMsgValidateWarning, icSigNamedColorStruct, icSigNmclNameMbr, icValidateCriticalError, icValidateOK, IIccStruct::m_pTagStruct, and CIccStructUnknown::Validate().
Field Documentation
m_pElemNameSigTable
SIccElemNameSig* CIccStructUnknown::m_pElemNameSigTable protected inherited
Referenced by CIccStructBRDF::CIccStructBRDF(), CIccStructColorantInfo::CIccStructColorantInfo(), CIccStructColorEncodingParams::CIccStructColorEncodingParams(), CIccStructMeasurementInfo::CIccStructMeasurementInfo(), CIccStructNamedColor::CIccStructNamedColor(), CIccStructProfileInfo::CIccStructProfileInfo(), CIccStructTintZero(), CIccStructUnknown::CIccStructUnknown(), CIccStructUnknown::GetElemName(), and CIccStructUnknown::GetElemSig().
m_pTagStruct
CIccTagStruct* IIccStruct::m_pTagStruct protected inherited
Referenced by CIccStructBRDF::CIccStructBRDF(), CIccStructColorantInfo::CIccStructColorantInfo(), CIccStructColorEncodingParams::CIccStructColorEncodingParams(), CIccStructMeasurementInfo::CIccStructMeasurementInfo(), CIccStructNamedColor::CIccStructNamedColor(), CIccStructProfileInfo::CIccStructProfileInfo(), CIccStructTintZero(), CIccStructUnknown::CIccStructUnknown(), CIccStructUnknown::Describe(), IIccStruct::Describe(), CIccStructUnknown::GetElem(), CIccStructNamedColor::getName(), IIccStruct::getTagEntries(), IIccStruct::GetTagStruct(), CIccStructNamedColor::Validate(), CIccStructBRDF::Validate(), and CIccStructColorantInfo::Validate().
The documentation for this class was generated from the following files:
IccProfLib/IccStructBasic.h
IccProfLib/IccStructBasic.cpp