iccDEV: CIccFuncTokenizer Class Reference
CIccFuncTokenizer Class Reference
#include <IccMpeCalc.h>
Public Member Functions
CIccFuncTokenizer (const char *szText, bool bAllowReferences=false)
virtual ~CIccFuncTokenizer ()
bool GetEnvSig (icSigCmmEnvVar &envSig)
bool GetIndex (icUInt16Number &v1, icUInt16Number &v2, icUInt16Number initV1=0, icUInt16Number initV2=0)
std::string & GetLast ()
std::string GetName () const
bool GetNext (bool bForceNoRefs=false)
const char * GetPos ()
std::string GetReference () const
icSigCalcOp GetSig ()
icFloat32Number GetValue ()
void SetPos (const char *szText)
Protected Member Functions
bool IsComment ()
bool IsWhiteSpace ()
void SkipComment ()
Protected Attributes
bool m_bUseRefs
const char * m_text
std::string * m_token
Detailed Description
Constructor & Destructor Documentation
CIccFuncTokenizer()
CIccFuncTokenizer::CIccFuncTokenizer (const char * szText, bool bAllowReferences = false)
{
  m_token = new std::string();
  m_text = szText;
  m_bUseRefs = bAllowNamedReferences;
}
References m_bUseRefs, m_text, and m_token.
Referenced by CIccMpeXmlCalculator::Flatten(), CIccCalculatorFunc::ParseFuncDef(), CIccMpeXmlCalculator::ParseImport(), CIccMpeXmlCalculator::UpdateLocals(), and CIccMpeXmlCalculator::ValidMacroCalls().
~CIccFuncTokenizer()
CIccFuncTokenizer::~CIccFuncTokenizer () virtual
{
  delete m_token;
}
References m_token.
Member Function Documentation
GetEnvSig()
bool CIccFuncTokenizer::GetEnvSig (icSigCmmEnvVar & envSig)
{
  const char *pos = GetPos();
  if (!GetNext())
    return false;
  const char *szToken = m_token->c_str();
  int l=(int)strlen(szToken);
  if ((*szToken=='[' && szToken[l-1]==']') ||
      (*szToken=='(' && szToken[l-1]==')')) {
    int i;
    icUInt32Number sig = 0;
    if (l==10) {
      sscanf(szToken+1, "%x", &sig);
      envSig = (icSigCmmEnvVar)sig;
      return true;
    }
    for (i=1; i<=4 && i<l-1; i++) {
      sig <<= 8;
      sig |= szToken[i];
    }
    for (;i<=4; i++) {
      sig <<= 8;
      sig |= 0x20;
    }
    envSig = (icSigCmmEnvVar)sig;
  }
  else {
    SetPos(pos); //Undo get token
    envSig = (icSigCmmEnvVar)0;
    return false;
  }
  return true;
}
References GetNext(), GetPos(), m_token, and SetPos().
Referenced by CIccCalculatorFunc::ParseFuncDef().
GetIndex()
bool CIccFuncTokenizer::GetIndex (icUInt16Number & v1, icUInt16Number & v2, icUInt16Number initV1 = 0, icUInt16Number initV2 = 0)
{
  unsigned int iv1, iv2;
  const char *pos = GetPos();
  if (!GetNext(true))
    return false;
  iv1=initV1;
  iv2=initV2;
  const char *szToken = m_token->c_str();
  if (*szToken=='[' || *szToken=='(') {
    if (strchr(szToken, ',')) {
      if (*szToken=='(')
        sscanf(m_token->c_str(), "(%u,%u)", &iv1, &iv2);
      else
        sscanf(m_token->c_str(), "[%u,%u]", &iv1, &iv2);
    }
    else {
      if (*szToken=='(')
        sscanf(m_token->c_str(), "(%u)", &iv1);
      else
        sscanf(m_token->c_str(), "[%u]", &iv1);
    }
  }
  else {
    SetPos(pos); //Undo get token
  }
  v1 = (icUInt16Number)iv1 - initV1;
  v2 = (icUInt16Number)iv2 - initV2;
  return true;
}
References GetNext(), GetPos(), m_token, and SetPos().
Referenced by CIccMpeXmlCalculator::Flatten(), CIccCalculatorFunc::ParseFuncDef(), CIccMpeXmlCalculator::ParseImport(), and CIccMpeXmlCalculator::UpdateLocals().
GetLast()
std::string & CIccFuncTokenizer::GetLast () inline
{ return *m_token; }
References m_token.
Referenced by CIccMpeXmlCalculator::Flatten(), and CIccMpeXmlCalculator::UpdateLocals().
GetName()
std::string CIccFuncTokenizer::GetName () const
{
  std::string rv;
  const char *pos = m_token->c_str();
  while (*pos && *pos != '{' && *pos != '[' && *pos != '(') {
    rv += *pos;
    pos++;
  }
  return rv;
}
References m_token.
Referenced by CIccMpeXmlCalculator::Flatten(), CIccMpeXmlCalculator::ParseImport(), and CIccMpeXmlCalculator::UpdateLocals().
GetNext()
bool CIccFuncTokenizer::GetNext (bool bForceNoRefs = false)
{
  m_token->clear();
try_again:
  while (*m_text && IsWhiteSpace())
    m_text++;
  if (!*m_text) {
    return false;
  }
  if (!m_bUseRefs || bForceNoRefs) {
    if (*m_text == '{') {
      m_text++;
      *m_token = "{";
      return true;
    }
    if (*m_text == '}') {
      m_text++;
      *m_token = "}";
      return true;
    }
    if (*m_text == '[') {
      m_text++;
      *m_token = "[";
      while (*m_text && *m_text != ']') {
        *m_token += *m_text;
        m_text++;
      }
    }
    if (*m_text == '(') {
      m_text++;
      *m_token = "(";
      while (*m_text && *m_text != ')') {
        *m_token += *m_text;
        m_text++;
      }
      if (!*m_text) {
        return false;
      }
    }
  }
  if (!*m_text) {
    return false;
  }
  if (IsComment()) {
    SkipComment();
    goto try_again;
  }
  if (m_bUseRefs && !bForceNoRefs) {
    while (!IsWhiteSpace() && *m_text && !IsComment()) {
      *m_token += *m_text;
      m_text++;
    }
  }
  else {
    while (!IsWhiteSpace() && *m_text && *m_text != '{' && *m_text != '[' &&
           *m_text != '(' &&  *m_text != '}' && !IsComment()) {
      *m_token += *m_text;
      m_text++;
    }
  }
  return true;
}
References IsComment(), IsWhiteSpace(), m_bUseRefs, m_text, m_token, and SkipComment().
Referenced by CIccMpeXmlCalculator::Flatten(), GetEnvSig(), GetIndex(), CIccCalculatorFunc::ParseFuncDef(), CIccMpeXmlCalculator::ParseImport(), CIccMpeXmlCalculator::UpdateLocals(), and CIccMpeXmlCalculator::ValidMacroCalls().
GetPos()
const char * CIccFuncTokenizer::GetPos () inline
{ return m_text; }
References m_text.
Referenced by GetEnvSig(), GetIndex(), and CIccCalculatorFunc::ParseFuncDef().
GetReference()
std::string CIccFuncTokenizer::GetReference () const
{
  const char *pos = strchr(m_token->c_str(), '{');
  if (!m_bUseRefs || !pos)
    return "";
  std::string rv;
  pos++;
  while (*pos && *pos != '}') {
    rv += *pos;
    pos++;
  }
  return rv;
}
References m_bUseRefs, and m_token.
Referenced by CIccMpeXmlCalculator::Flatten(), and CIccMpeXmlCalculator::ValidMacroCalls().
GetSig()
icSigCalcOp CIccFuncTokenizer::GetSig ()
{
  const unsigned char *szToken = (unsigned char*) m_token->c_str();
  int i;
  if ((szToken[0]>='0' && szToken[0]<='9') || szToken[0]=='.' || (szToken[0]=='-' && szToken[1]!='I')) {
    return icSigDataOp;
  }
  if (szToken[0]=='{')
    return icSigBeginBlockOp;
  if (szToken[0]=='}')
    return icSigEndBlockOp;
  if (szToken[0]=='[')
    return icSigBadOp;
  icUInt32Number sig = 0;
  for (i=0; i<4 && szToken[i]; i++) {
    sig <<= 8;
    sig |= szToken[i];
  }
  for (;i<4; i++) {
    sig <<= 8;
    sig |= 0x20;
  }
  return (icSigCalcOp)sig;
}
References icSigDataOp, and m_token.
Referenced by CIccCalculatorFunc::ParseFuncDef().
GetValue()
icFloat32Number CIccFuncTokenizer::GetValue ()
{
  const char * ascii = m_token->c_str();
  char * p = NULL;
  double d = strtod( ascii, &p );
  return (icFloat32Number)d;
}
References m_token.
Referenced by CIccCalculatorFunc::ParseFuncDef().
IsComment()
bool CIccFuncTokenizer::IsComment () protected
{
  if (*m_text=='%' || *m_text==';' || *m_text=='/')
    return true;
  return false;
}
References m_text.
Referenced by GetNext().
IsWhiteSpace()
bool CIccFuncTokenizer::IsWhiteSpace () protected
{
  if (*m_text==' ' || *m_text=='\n' || *m_text=='\r' || *m_text=='\t')
    return true;
  return false;
}
References m_text.
Referenced by GetNext().
SetPos()
void CIccFuncTokenizer::SetPos (const char * szText) inline
{ m_text = szText; }
References m_text.
Referenced by GetEnvSig(), GetIndex(), and CIccCalculatorFunc::ParseFuncDef().
SkipComment()
void CIccFuncTokenizer::SkipComment () protected
{
  while(*m_text && !(*m_text=='\n' || *m_text=='\r')) {
    m_text++;
  }
}
References m_text.
Referenced by GetNext().
Field Documentation
m_bUseRefs
bool CIccFuncTokenizer::m_bUseRefs protected
Referenced by CIccFuncTokenizer(), GetNext(), and GetReference().
m_text
const char* CIccFuncTokenizer::m_text protected
Referenced by CIccFuncTokenizer(), GetNext(), GetPos(), IsComment(), IsWhiteSpace(), SetPos(), and SkipComment().
m_token
std::string* CIccFuncTokenizer::m_token protected
Referenced by CIccFuncTokenizer(), ~CIccFuncTokenizer(), GetEnvSig(), GetIndex(), GetLast(), GetName(), GetNext(), GetReference(), GetSig(), and GetValue().
The documentation for this class was generated from the following files:
IccProfLib/IccMpeCalc.h
IccProfLib/IccMpeCalc.cpp