iccDEV: CIccMBB Class Reference
CIccMBB Class Reference
#include <IccTagLut.h>
Public Member Functions
CIccMBB ()
CIccMBB (const CIccMBB &IMBB)
virtual ~CIccMBB ()
void Cleanup ()
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
virtual const icChar * GetClassName () const
CIccCLUT * GetCLUT () const
icColorSpaceSignature GetCsInput ()
icColorSpaceSignature GetCsOutput ()
LPIccCurve * GetCurvesA () const
LPIccCurve * GetCurvesB () const
LPIccCurve * GetCurvesM () const
virtual IIccExtensionTag * GetExtension ()
CIccMatrix * GetMatrix () const
virtual icUInt8Number GetPrecision ()
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
void Init (icUInt8Number nInputChannels, icUInt8Number nOutputChannels)
icUInt8Number InputChannels () const
virtual bool IsArrayType ()
bool IsInputB ()
virtual bool IsInputMatrix ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
CIccCLUT * NewCLUT (icUInt8Number *pGridPoints, icUInt8Number nPrecision=2)
CIccCLUT * NewCLUT (icUInt8Number nGridPoints, icUInt8Number nPrecision=2)
virtual CIccTag * NewCopy () const
LPIccCurve * NewCurvesA ()
LPIccCurve * NewCurvesB ()
LPIccCurve * NewCurvesM ()
CIccMatrix * NewMatrix ()
CIccMBB & operator= (const CIccMBB &IMBB)
icUInt8Number OutputChannels () const
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
CIccCLUT * SetCLUT (CIccCLUT *clut)
virtual void SetColorSpaces (icColorSpaceSignature csInput, icColorSpaceSignature csOutput)
bool SwapMBCurves ()
virtual bool UseLegacyPCS () const
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL)
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
Protected Attributes
bool m_bInputMatrix
bool m_bUseMCurvesAsBCurves
CIccCLUT * m_CLUT
icColorSpaceSignature m_csInput
icColorSpaceSignature m_csOutput
LPIccCurve * m_CurvesA
LPIccCurve * m_CurvesB
LPIccCurve * m_CurvesM
CIccMatrix * m_Matrix
icUInt8Number m_nInput
icUInt8Number m_nOutput
Detailed Description
Class: CIccMBB
Purpose: The Multi-dimensional Black Box (MBB) base class for lut8, lut16, lutA2B and lutB2A tag types
Constructor & Destructor Documentation
CIccMBB() [1/2]
CIccMBB::CIccMBB ()
Name: CIccMBB::CIccMBB
Purpose: Constructor
{
  m_nInput = 0;
  m_nOutput = 0;
  m_CurvesA = NULL;
  m_CLUT = NULL;
  m_Matrix = NULL;
  m_CurvesM = NULL;
  m_CurvesB = NULL;
  m_csInput  = icSigUnknownData;
  m_csOutput = icSigUnknownData;
  m_bInputMatrix = true;
  m_bUseMCurvesAsBCurves = false;
}
References m_bInputMatrix, m_bUseMCurvesAsBCurves, m_CLUT, m_csInput, m_csOutput, m_CurvesA, m_CurvesB, m_CurvesM, m_Matrix, m_nInput, and m_nOutput.
CIccMBB() [2/2]
CIccMBB::CIccMBB (const CIccMBB & IMBB)
Name: CIccMBB::CIccMBB
Purpose: Copy Constructor
Args: IMBB = The CIccMBB object to be copied
{
 icUInt8Number nCurves;
 int i;
  m_bInputMatrix = IMBB.m_bInputMatrix;
  m_bUseMCurvesAsBCurves = IMBB.m_bUseMCurvesAsBCurves;
  m_nInput = IMBB.m_nInput;
  m_nOutput = IMBB.m_nOutput;
  m_csInput = IMBB.m_csInput;
  m_csOutput = IMBB.m_csOutput;
  if (IMBB.m_CLUT) {
    m_CLUT = new CIccCLUT(*IMBB.m_CLUT);
  }
  else
    m_CLUT = NULL;
  if (IMBB.m_CurvesA) {
    nCurves = !IsInputB() ? m_nInput : m_nOutput;
    m_CurvesA = new LPIccCurve[nCurves];
    for (i=0; i<nCurves; i++)
      m_CurvesA[i] = (CIccTagCurve*)IMBB.m_CurvesA[i]->NewCopy();
  }
  else {
    m_CurvesA = NULL;
  }
  if (IMBB.m_CurvesM) {
    nCurves = IsInputMatrix() ? m_nInput : m_nOutput;
    m_CurvesM = new LPIccCurve[nCurves];
    for (i=0; i<nCurves; i++)
      m_CurvesM[i] = (CIccTagCurve*)IMBB.m_CurvesM[i]->NewCopy();
  }
  else {
    m_CurvesM = NULL;
  }
  if (IMBB.m_CurvesB) {
    nCurves = IsInputB() ? m_nInput : m_nOutput;
    m_CurvesB = new LPIccCurve[nCurves];
    for (i=0; i<nCurves; i++)
      m_CurvesB[i] = (CIccTagCurve*)IMBB.m_CurvesB[i]->NewCopy();
  }
  else {
    m_CurvesB = NULL;
  }
  if (IMBB.m_Matrix) {
    m_Matrix = new CIccMatrix(*IMBB.m_Matrix);
  }
  else {
    m_Matrix = NULL;
  }
}
References CIccCLUT::CIccCLUT(), CIccMatrix::CIccMatrix(), IsInputB(), IsInputMatrix(), m_bInputMatrix, m_bUseMCurvesAsBCurves, m_CLUT, m_csInput, m_csOutput, m_CurvesA, m_CurvesB, m_CurvesM, m_Matrix, m_nInput, m_nOutput, and CIccCurve::NewCopy().
Referenced by CIccTagLut16::CIccTagLut16(), CIccTagLut8::CIccTagLut8(), CIccTagLutAtoB::CIccTagLutAtoB(), and NewCopy().
~CIccMBB()
CIccMBB::~CIccMBB () virtual
Name: CIccMBB::~CIccMBB
Purpose: Destructor
{
  Cleanup();
}
References Cleanup().
Member Function Documentation
Cleanup()
void CIccMBB::Cleanup ()
Name: CIccMBB::Cleanup
Purpose: Frees the memory allocated to the object
{
  int i;
  if (IsInputMatrix()) {
    if (m_CurvesB) {
      for (i=0; i<m_nInput; i++)
        if (m_CurvesB[i])
          delete m_CurvesB[i];
      delete [] m_CurvesB;
      m_CurvesB = NULL;
    }
    if (m_CurvesM) {
      for (i=0; i<m_nInput; i++)
        if (m_CurvesM[i])
          delete m_CurvesM[i];
      delete [] m_CurvesM;
      m_CurvesM = NULL;
    }
    if (m_CurvesA) {
      for (i=0; i<m_nOutput; i++)
        if (m_CurvesA[i])
          delete m_CurvesA[i];
      delete [] m_CurvesA;
      m_CurvesA = NULL;
    }
  }
  else {
    if (m_CurvesA) {
      for (i=0; i<m_nInput; i++)
        if (m_CurvesA[i])
          delete m_CurvesA[i];
      delete [] m_CurvesA;
      m_CurvesA = NULL;
    }
    if (m_CurvesM) {
      for (i=0; i<m_nOutput; i++)
        if (m_CurvesM[i])
          delete m_CurvesM[i];
      delete [] m_CurvesM;
      m_CurvesM = NULL;
    }
    if (m_CurvesB) {
      for (i=0; i<m_nOutput; i++)
        if (m_CurvesB[i])
          delete m_CurvesB[i];
      delete [] m_CurvesB;
      m_CurvesB = NULL;
    }
  }
  if (m_Matrix) {
    delete m_Matrix;
    m_Matrix = NULL;
  }
  if (m_CLUT) {
    delete m_CLUT;
    m_CLUT = NULL;
  }
}
References IsInputMatrix(), m_CLUT, m_CurvesA, m_CurvesB, m_CurvesM, m_Matrix, m_nInput, and m_nOutput.
Referenced by ~CIccMBB(), Init(), and operator=().
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccMBB::Describe (std::string & sDescription, int nVerboseness) virtual
Name: CIccMBB::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  int i;
  icChar buf[128], color[40];
  if (IsInputMatrix()) {
    if (m_CurvesB && !m_bUseMCurvesAsBCurves) {
      for (i=0; i<m_nInput; i++) {
        icColorIndexName(color, m_csInput, i, m_nInput, "");
        sprintf(buf, "B_Curve_%s", color);
        m_CurvesB[i]->DumpLut(sDescription, buf, m_csInput, i, nVerboseness);
      }
    }
    if (m_Matrix)
      m_Matrix->DumpLut(sDescription, "Matrix", nVerboseness);
    if (m_CurvesM) {
      for (i=0; i<m_nInput; i++) {
        icColorIndexName(color, m_csInput, i, m_nInput, "");
        if (!m_bUseMCurvesAsBCurves)
          sprintf(buf, "M_Curve_%s", color);
        else
          sprintf(buf, "B_Curve_%s", color);
        m_CurvesM[i]->DumpLut(sDescription, buf, m_csInput, i, nVerboseness);
      }
    }
    if (m_CLUT)
      m_CLUT->DumpLut(sDescription, "CLUT", m_csInput, m_csOutput, nVerboseness, GetType()==icSigLut16Type);
    if (m_CurvesA) {
      for (i=0; i<m_nOutput; i++) {
        icColorIndexName(color, m_csOutput, i, m_nOutput, "");
        sprintf(buf, "A_Curve_%s", color);
        m_CurvesA[i]->DumpLut(sDescription, buf, m_csOutput, i, nVerboseness);
      }
    }
  }
  else {
    if (m_CurvesA) {
      for (i=0; i<m_nInput; i++) {
        icColorIndexName(color, m_csInput, i, m_nInput, "");
        sprintf(buf, "A_Curve_%s", color);
        m_CurvesA[i]->DumpLut(sDescription, buf, m_csInput, i, nVerboseness);
      }
    }
    if (m_CLUT)
      m_CLUT->DumpLut(sDescription, "CLUT", m_csInput, m_csOutput, nVerboseness);
    if (m_CurvesM && this->GetType()!=icSigLut8Type) {
      for (i=0; i<m_nOutput; i++) {
        icColorIndexName(color, m_csOutput, i, m_nOutput, "");
        sprintf(buf, "M_Curve_%s", color);
        m_CurvesM[i]->DumpLut(sDescription, buf, m_csOutput, i, nVerboseness);
      }
    }
    if (m_Matrix)
      m_Matrix->DumpLut(sDescription, "Matrix", nVerboseness);
    if (m_CurvesB) {
      for (i=0; i<m_nOutput; i++) {
        icColorIndexName(color, m_csOutput, i, m_nOutput, "");
        sprintf(buf, "B_Curve_%s", color);
        m_CurvesB[i]->DumpLut(sDescription, buf, m_csOutput, i, nVerboseness);
      }
    }
  }
}
References CIccCLUT::DumpLut(), CIccCurve::DumpLut(), CIccMatrix::DumpLut(), CIccTag::GetType(), icColorIndexName(), icSigLut16Type, icSigLut8Type, IsInputMatrix(), m_bUseMCurvesAsBCurves, m_CLUT, m_csInput, m_csOutput, m_CurvesA, m_CurvesB, m_CurvesM, m_Matrix, m_nInput, and m_nOutput.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
GetClassName()
virtual const icChar * CIccTag::GetClassName () const inline virtual inherited
Reimplemented in CIccTagUnknown, CIccTagText, CIccTagUtf8Text, CIccTagZipUtf8Text, CIccTagZipXml, CIccTagUtf16Text, CIccTagTextDescription, CIccTagSignature, CIccTagNamedColor2, CIccTagXYZ, CIccTagChromaticity, CIccTagCicp, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, CIccTagMeasurement, CIccTagMultiLocalizedUnicode, CIccTagData, CIccTagDateTime, CIccTagColorantOrder, CIccTagColorantTable, CIccTagViewingConditions, CIccTagProfileSeqDesc, CIccTagResponseCurveSet16, CIccTagSpectralDataInfo, CIccTagSpectralViewingConditions, CIccTagEmbeddedHeightImage, CIccTagEmbeddedNormalImage, CIccTagStruct, CIccTagArray, CIccTagDict, CIccTagEmbeddedProfile, CIccTagCurve, CIccTagParametricCurve, CIccTagSegmentedCurve, CIccTagGamutBoundaryDesc, CIccTagMultiProcessElement, CIccTagProfileSequenceId, CIccTagXmlUnknown, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, CIccTagXmlSignature, CIccTagXmlNamedColor2, CIccTagXmlXYZ, CIccTagXmlChromaticity, CIccTagXmlCicp, CIccTagXmlSparseMatrixArray, CIccTagXmlFixedNum< T, Tsig >, CIccTagXmlNum< T, A, Tsig >, CIccTagXmlFloatNum< T, A, Tsig >, CIccTagXmlMeasurement, CIccTagXmlMultiLocalizedUnicode, CIccTagXmlTagData, CIccTagXmlDateTime, CIccTagXmlColorantOrder, CIccTagXmlColorantTable, CIccTagXmlViewingConditions, CIccTagXmlSpectralDataInfo, CIccTagXmlSpectralViewingConditions, CIccTagXmlProfileSeqDesc, CIccTagXmlResponseCurveSet16, CIccTagXmlCurve, CIccTagXmlParametricCurve, CIccTagXmlSegmentedCurve, CIccTagXmlLutAtoB, CIccTagXmlLutBtoA, CIccTagXmlLut8, CIccTagXmlLut16, CIccTagXmlMultiProcessElement, CIccTagXmlProfileSequenceId, CIccTagXmlDict, CIccTagXmlStruct, and CIccTagXmlArray.
{ return "CIccTag"; }
GetCLUT()
CIccCLUT * CIccMBB::GetCLUT () const inline
{return m_CLUT;}
References m_CLUT.
Referenced by CIccEvalCompare::EvaluateProfile(), icMBBFromXml(), and icMBBToXml().
GetCsInput()
icColorSpaceSignature CIccMBB::GetCsInput () inline
{ return m_csInput; }
References m_csInput.
GetCsOutput()
icColorSpaceSignature CIccMBB::GetCsOutput () inline
{ return m_csOutput; }
References m_csOutput.
GetCurvesA()
LPIccCurve * CIccMBB::GetCurvesA () const inline
{return m_CurvesA;}
References m_CurvesA.
Referenced by icMBBFromXml(), and icMBBToXml().
GetCurvesB()
LPIccCurve * CIccMBB::GetCurvesB () const inline
{return m_CurvesB;}
References m_CurvesB.
Referenced by icMBBFromXml(), and icMBBToXml().
GetCurvesM()
LPIccCurve * CIccMBB::GetCurvesM () const inline
{return m_CurvesM;}
References m_CurvesM.
Referenced by icMBBFromXml(), and icMBBToXml().
GetExtension()
virtual IIccExtensionTag * CIccTag::GetExtension () inline virtual inherited
Reimplemented in CIccTagXmlUnknown, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, CIccTagXmlSignature, CIccTagXmlNamedColor2, CIccTagXmlXYZ, CIccTagXmlChromaticity, CIccTagXmlCicp, CIccTagXmlSparseMatrixArray, CIccTagXmlFixedNum< T, Tsig >, CIccTagXmlNum< T, A, Tsig >, CIccTagXmlFloatNum< T, A, Tsig >, CIccTagXmlMeasurement, CIccTagXmlMultiLocalizedUnicode, CIccTagXmlTagData, CIccTagXmlDateTime, CIccTagXmlColorantOrder, CIccTagXmlColorantTable, CIccTagXmlViewingConditions, CIccTagXmlSpectralDataInfo, CIccTagXmlSpectralViewingConditions, CIccTagXmlProfileSeqDesc, CIccTagXmlResponseCurveSet16, CIccTagXmlCurve, CIccTagXmlParametricCurve, CIccTagXmlSegmentedCurve, CIccTagXmlLutAtoB, CIccTagXmlLutBtoA, CIccTagXmlLut8, CIccTagXmlLut16, CIccTagXmlMultiProcessElement, CIccTagXmlProfileSequenceId, CIccTagXmlDict, CIccTagXmlStruct, CIccTagXmlArray, CIccTagXmlGamutBoundaryDesc, CIccTagXmlEmbeddedHeightImage, CIccTagXmlEmbeddedNormalImage, and CIccTagXmlEmbeddedProfile.
{return NULL;}
Referenced by icCurvesFromXml(), icCurvesToXml(), icProfDescToXml(), icXmlParseProfDesc(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeXmlTintArray::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
GetMatrix()
CIccMatrix * CIccMBB::GetMatrix () const inline
{return m_Matrix; }
References m_Matrix.
Referenced by icMBBFromXml(), and icMBBToXml().
GetPrecision()
virtual icUInt8Number CIccMBB::GetPrecision () inline virtual
Reimplemented in CIccTagLut8.
{ return 2; }
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTag::GetType () const inline virtual inherited
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented in CIccTagUnknown, CIccTagText, CIccTagUtf8Text, CIccTagZipUtf8Text, CIccTagZipXml, CIccTagUtf16Text, CIccTagTextDescription, CIccTagSignature, CIccTagNamedColor2, CIccTagXYZ, CIccTagChromaticity, CIccTagCicp, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, CIccTagMeasurement, CIccTagMultiLocalizedUnicode, CIccTagData, CIccTagDateTime, CIccTagColorantOrder, CIccTagColorantTable, CIccTagViewingConditions, CIccTagProfileSeqDesc, CIccTagResponseCurveSet16, CIccTagSpectralDataInfo, CIccTagSpectralViewingConditions, CIccTagEmbeddedHeightImage, CIccTagEmbeddedNormalImage, CIccTagStruct, CIccTagArray, CIccTagDict, CIccTagEmbeddedProfile, CIccTagCurve, CIccTagParametricCurve, CIccTagSegmentedCurve, CIccTagLutAtoB, CIccTagLutBtoA, CIccTagLut8, CIccTagLut16, CIccTagGamutBoundaryDesc, CIccTagMultiProcessElement, and CIccTagProfileSequenceId.
{ return icMaxEnumType; }
Referenced by CIccProfileIdDesc::CIccProfileIdDesc(), MyTagDialog::MyTagDialog(), CIccTagArray::AreAllOfType(), Describe(), DumpTag(), CIccPRMG::EvaluateProfile(), CIccTagStruct::FindElemOfType(), CIccStructBRDF::GetBRDFFunction(), CIccStructBRDF::GetBRDFType(), CIccStructNamedColor::getName(), CIccProfileDescText::GetType(), icGetTagArrayHandler(), icGetTagStructHandler(), icGetTagText(), icProfDescToXml(), CDevLinkWriter::iterate(), main(), CIccProfileXml::ParseTag(), CIccProfileDescText::SetType(), CIccMpeXmlTintArray::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), CIccProfileXml::ToXmlWithBlanks(), CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccArrayUnknown::Validate(), CIccArrayColorantInfo::Validate(), CIccProfileDescText::Write(), CIccTagLut8::Write(), and CIccTagLut16::Write().
Init()
void CIccMBB::Init (icUInt8Number nInputChannels, icUInt8Number nOutputChannels)
Name: CIccMBB::Init
Purpose: Cleans up any prior memory and Initializes the object.
Args: nInputChannels = number of input channels, nOutputChannels = number of output channels
{
  Cleanup();
  m_nInput = nInputChannels;
  m_nOutput = nOutputChannels;
}
References Cleanup(), m_nInput, and m_nOutput.
Referenced by CDevLinkWriter::begin(), and icMBBFromXml().
InputChannels()
icUInt8Number CIccMBB::InputChannels () const inline
{ return m_nInput; }
References m_nInput.
Referenced by icMBBToXml().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsInputB()
bool CIccMBB::IsInputB () inline
{ return IsInputMatrix(); }
References IsInputMatrix().
Referenced by CIccMBB(), icMBBFromXml(), NewCurvesA(), NewCurvesB(), operator=(), CIccTagLutAtoB::Read(), and CIccTagLutAtoB::Write().
IsInputMatrix()
virtual bool CIccMBB::IsInputMatrix () inline virtual
{ return m_bInputMatrix; } //Is matrix on input side of CLUT?
References m_bInputMatrix.
Referenced by CIccMBB(), Cleanup(), Describe(), icMBBFromXml(), icMBBToXml(), IsInputB(), NewCurvesM(), operator=(), CIccTagLutAtoB::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccTagLutAtoB::Write().
IsMBBType()
virtual bool CIccMBB::IsMBBType () inline virtual
Reimplemented from CIccTag.
{ return true;}
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCLUT() [1/2]
CIccCLUT * CIccMBB::NewCLUT (icUInt8Number * pGridPoints, icUInt8Number nPrecision = 2)
Name: CIccMBB::NewCLUT
Purpose: Allocates memory for a new CLUT and initializes it
Args: pGridPoints = number of grid points in the CLUT
Return: Pointer to the CIccCLUT object
{
  if (m_CLUT)
    return m_CLUT;
  m_CLUT = new CIccCLUT(m_nInput, m_nOutput, nPrecision);
  m_CLUT->Init(pGridPoints);
  return m_CLUT;
}
References CIccCLUT::CIccCLUT(), CIccCLUT::Init(), m_CLUT, m_nInput, and m_nOutput.
NewCLUT() [2/2]
CIccCLUT * CIccMBB::NewCLUT (icUInt8Number nGridPoints, icUInt8Number nPrecision = 2)
Name: CIccMBB::NewCLUT
Purpose: Allocates memory for a new CLUT and initializes it
Args: nGridPoints = number of grid points in the CLUT
Return: Pointer to the CIccCLUT object
{
  if (m_CLUT)
    return m_CLUT;
  m_CLUT = new CIccCLUT(m_nInput, m_nOutput, nPrecision);
  m_CLUT->Init(nGridPoints);
  return m_CLUT;
}
References CIccCLUT::CIccCLUT(), CIccCLUT::Init(), m_CLUT, m_nInput, and m_nOutput.
Referenced by CDevLinkWriter::begin().
NewCopy()
virtual CIccTag * CIccMBB::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
Reimplemented in CIccTagLutAtoB, CIccTagLutBtoA, CIccTagLut8, and CIccTagLut16.
{return new CIccMBB(*this);}
References CIccMBB().
NewCurvesA()
LPIccCurve * CIccMBB::NewCurvesA ()
Name: CIccMBB::NewCurvesA
Purpose: Allocates memory for a new set of A-curves
Return: Pointer to the LPIccCurve object
{
  if (m_CurvesA)
    return m_CurvesA;
  icUInt8Number nCurves = !IsInputB() ? m_nInput : m_nOutput;
  m_CurvesA = new LPIccCurve[nCurves];
  memset(m_CurvesA, 0, nCurves * sizeof(LPIccCurve));
  return m_CurvesA;
}
References IsInputB(), m_CurvesA, m_nInput, and m_nOutput.
Referenced by CDevLinkWriter::begin(), icMBBFromXml(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), and CIccTagLut16::Read().
NewCurvesB()
LPIccCurve * CIccMBB::NewCurvesB ()
Name: CIccMBB::NewCurvesB
Purpose: Allocates memory for a new set of B-curves
Return: Pointer to the LPIccCurve object
{
  if (m_CurvesB)
    return m_CurvesB;
  icUInt8Number nCurves = IsInputB() ? m_nInput : m_nOutput;
  m_CurvesB = new LPIccCurve[nCurves];
  memset(m_CurvesB, 0, nCurves * sizeof(LPIccCurve));
  return m_CurvesB;
}
References IsInputB(), m_CurvesB, m_nInput, and m_nOutput.
Referenced by CDevLinkWriter::begin(), icMBBFromXml(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), and CIccTagLut16::SetColorSpaces().
NewCurvesM()
LPIccCurve * CIccMBB::NewCurvesM ()
Name: CIccMBB::NewCurvesM
Purpose: Allocates memory for a new set of M-curves
Return: Pointer to the LPIccCurve object
{
  if (m_CurvesM)
    return m_CurvesM;
  icUInt8Number nCurves = IsInputMatrix() ? m_nInput : m_nOutput;
  m_CurvesM = new LPIccCurve[nCurves];
  memset(m_CurvesM, 0, nCurves * sizeof(LPIccCurve));
  return m_CurvesM;
}
References IsInputMatrix(), m_CurvesM, m_nInput, and m_nOutput.
Referenced by icMBBFromXml(), and CIccTagLutAtoB::Read().
NewMatrix()
CIccMatrix * CIccMBB::NewMatrix ()
Name: CIccMBB::NewMatrix
Purpose: Allocates memory for a new matrix
Return: Pointer to the CIccMatrix object
{
  if (m_Matrix)
    return m_Matrix;
  m_Matrix = new CIccMatrix;
  return m_Matrix;
}
References m_Matrix.
Referenced by icMBBFromXml(), CIccTagLut8::SetColorSpaces(), and CIccTagLut16::SetColorSpaces().
operator=()
CIccMBB & CIccMBB::operator= (const CIccMBB & IMBB)
Name: CIccMBB::operator=
Purpose: Copy Operator
Args: IMBB = The CIccMBB object to be copied
{
  if (&IMBB == this)
    return *this;
  Cleanup();
  icUInt8Number nCurves;
  int i;
  m_bInputMatrix = IMBB.m_bInputMatrix;
  m_bUseMCurvesAsBCurves = IMBB.m_bUseMCurvesAsBCurves;
  m_nInput = IMBB.m_nInput;
  m_nOutput = IMBB.m_nOutput;
  m_csInput = IMBB.m_csInput;
  m_csOutput = IMBB.m_csOutput;
  if (IMBB.m_CLUT) {
    m_CLUT = new CIccCLUT(*IMBB.m_CLUT);
  }
  else
    m_CLUT = NULL;
  if (IMBB.m_CurvesA) {
    nCurves = !IsInputB() ? m_nInput : m_nOutput;
    m_CurvesA = new LPIccCurve[nCurves];
    for (i=0; i<nCurves; i++)
      m_CurvesA[i] = (CIccTagCurve*)IMBB.m_CurvesA[i]->NewCopy();
  }
  else {
    m_CurvesA = NULL;
  }
  if (IMBB.m_CurvesM) {
    nCurves = IsInputMatrix() ? m_nInput : m_nOutput;
    m_CurvesM = new LPIccCurve[nCurves];
    for (i=0; i<nCurves; i++)
      m_CurvesM[i] = (CIccTagCurve*)IMBB.m_CurvesM[i]->NewCopy();
  }
  else {
    m_CurvesM = NULL;
  }
  if (IMBB.m_CurvesB) {
    nCurves = IsInputB() ? m_nInput : m_nOutput;
    m_CurvesB = new LPIccCurve[nCurves];
    for (i=0; i<nCurves; i++)
      m_CurvesB[i] = (CIccTagCurve*)IMBB.m_CurvesB[i]->NewCopy();
  }
  else {
    m_CurvesB = NULL;
  }
  if (IMBB.m_Matrix) {
    m_Matrix = new CIccMatrix(*IMBB.m_Matrix);
  }
  else {
    m_Matrix = NULL;
  }
  return *this;
}
References CIccCLUT::CIccCLUT(), CIccMatrix::CIccMatrix(), Cleanup(), IsInputB(), IsInputMatrix(), m_bInputMatrix, m_bUseMCurvesAsBCurves, m_CLUT, m_csInput, m_csOutput, m_CurvesA, m_CurvesB, m_CurvesM, m_Matrix, m_nInput, m_nOutput, and CIccCurve::NewCopy().
Referenced by CIccTagLut16::operator=(), CIccTagLut8::operator=(), CIccTagLutAtoB::operator=(), and CIccTagLutBtoA::operator=().
OutputChannels()
icUInt8Number CIccMBB::OutputChannels () const inline
{ return m_nOutput; }
References m_nOutput.
Referenced by icMBBToXml().
Read() [1/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagUnknown, CIccTagText, CIccTagUtf8Text, CIccTagZipUtf8Text, CIccTagUtf16Text, CIccTagTextDescription, CIccTagSignature, CIccTagNamedColor2, CIccTagXYZ, CIccTagChromaticity, CIccTagCicp, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, CIccTagMeasurement, CIccTagMultiLocalizedUnicode, CIccTagData, CIccTagDateTime, CIccTagColorantOrder, CIccTagColorantTable, CIccTagViewingConditions, CIccTagProfileSeqDesc, CIccTagResponseCurveSet16, CIccTagSpectralDataInfo, CIccTagSpectralViewingConditions, CIccTagEmbeddedHeightImage, CIccTagEmbeddedNormalImage, CIccTagStruct, CIccTagArray, CIccTagDict, CIccTagEmbeddedProfile, CIccTagCurve, CIccTagParametricCurve, CIccTagSegmentedCurve, CIccTagLutAtoB, CIccTagLut8, CIccTagLut16, CIccTagGamutBoundaryDesc, CIccTagMultiProcessElement, and CIccTagProfileSequenceId.
{ return false; }
Referenced by CIccTagStruct::LoadElem(), CIccMpeTintArray::Read(), CIccProfileDescText::Read(), CIccTagArray::Read(), CIccTagLutAtoB::Read(), and CIccTag::Read().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
SetCLUT()
CIccCLUT * CIccMBB::SetCLUT (CIccCLUT * clut)
Name: CIccMBB::SetCLUT
Purpose: Assignes CLUT connection to an initialized new CLUT
Args: clut = pointer to a previously allocated CLUT (Onwership is transfered to CIccMBB object).
Return: Pointer to the CIccCLUT object or NULL if clut is incompatible with CIccMBB object. If the clut is incompatible it is deleted.
{
  if (clut->GetInputDim() != m_nInput || clut->GetOutputChannels() != m_nOutput) {
    delete clut;
    return NULL;
  }
  if (m_CLUT) {
    delete m_CLUT;
  }
  m_CLUT = clut;
  return clut;
}
References CIccCLUT::GetInputDim(), CIccCLUT::GetOutputChannels(), m_CLUT, m_nInput, and m_nOutput.
Referenced by icMBBFromXml().
SetColorSpaces()
void CIccMBB::SetColorSpaces (icColorSpaceSignature csInput, icColorSpaceSignature csOutput) virtual
Name: CIccMBB::SetColorSpaces
Purpose: Sets the input and output color spaces
Args: csInput = input color space signature, csOutput = output color space signature
Reimplemented in CIccTagLut8, and CIccTagLut16.
{
   m_csInput = csInput;
   m_csOutput = csOutput;
}
References m_csInput, and m_csOutput.
Referenced by CIccProfileXml::ParseTag(), CIccTagLut8::SetColorSpaces(), and CIccTagLut16::SetColorSpaces().
SwapMBCurves()
bool CIccMBB::SwapMBCurves () inline
{ return m_bUseMCurvesAsBCurves; }
References m_bUseMCurvesAsBCurves.
Referenced by icMBBToXml().
UseLegacyPCS()
virtual bool CIccMBB::UseLegacyPCS () const inline virtual
Reimplemented in CIccTagLut16.
{ return false; } //Treat Lab Encoding differently?
Validate() [1/2]
icValidateStatus CIccMBB::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) virtual
Name: CIccMBB::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented in CIccTagLutAtoB, CIccTagLutBtoA, CIccTagLut8, and CIccTagLut16.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  icSignature sig = icGetFirstSigPathSig(sigPath);
  if (!pProfile) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " - Tag validation incomplete: Pointer to profile unavailable.\n";
    rv = icMaxStatus(rv, icValidateWarning);
    return rv;
  }
  icUInt32Number nInput, nOutput;
  //Check # of channels
  switch(sig) {
  case icSigAToB0Tag:
  case icSigAToB1Tag:
  case icSigAToB2Tag:
  case icSigAToB3Tag:
    {
      nInput = icGetSpaceSamples(pProfile->m_Header.colorSpace);
      if (m_nInput!=nInput) {
        sReport += icMsgValidateCriticalError;
        sReport += sSigPathName;
        sReport += " - Incorrect number of input channels.\n";
        rv = icMaxStatus(rv, icValidateCriticalError);
      }
      nOutput = icGetSpaceSamples(pProfile->m_Header.pcs);
      if (m_nOutput!=nOutput) {
        sReport += icMsgValidateCriticalError;
        sReport += sSigPathName;
        sReport += " - Incorrect number of output channels.\n";
        rv = icMaxStatus(rv, icValidateCriticalError);
      }
      break;
    }
  case icSigBToA0Tag:
  case icSigBToA1Tag:
  case icSigBToA2Tag:
  case icSigBToA3Tag:
    {
      nInput = icGetSpaceSamples(pProfile->m_Header.pcs);
      if (m_nInput!=nInput) {
        sReport += icMsgValidateCriticalError;
        sReport += sSigPathName;
        sReport += " - Incorrect number of input channels.\n";
        rv = icMaxStatus(rv, icValidateCriticalError);
      }
      nOutput = icGetSpaceSamples(pProfile->m_Header.colorSpace);
      if (m_nOutput!=nOutput) {
        sReport += icMsgValidateCriticalError;
        sReport += sSigPathName;
        sReport += " - Incorrect number of output channels.\n";
        rv = icMaxStatus(rv, icValidateCriticalError);
      }
      break;
    }
  case icSigHToS0Tag:
  case icSigHToS1Tag:
  case icSigHToS2Tag:
  case icSigHToS3Tag:
  {
    nInput = icGetSpaceSamples(pProfile->m_Header.pcs);
    if (m_nInput != nInput) {
      sReport += icMsgValidateCriticalError;
      sReport += sSigPathName;
      sReport += " - Incorrect number of input channels.\n";
      rv = icMaxStatus(rv, icValidateCriticalError);
    }
    nOutput = icGetSpaceSamples(pProfile->m_Header.pcs);
    if (m_nOutput != nOutput) {
      sReport += icMsgValidateCriticalError;
      sReport += sSigPathName;
      sReport += " - Incorrect number of output channels.\n";
      rv = icMaxStatus(rv, icValidateCriticalError);
    }
    break;
  }
  case icSigGamutTag:
    {
      nInput = 1;
      if (m_nInput!=nInput) {
        sReport += icMsgValidateCriticalError;
        sReport += sSigPathName;
        sReport += " - Incorrect number of input channels.\n";
        rv = icMaxStatus(rv, icValidateCriticalError);
      }
      nOutput = icGetSpaceSamples(pProfile->m_Header.colorSpace);
      if (m_nOutput!=nOutput) {
        sReport += icMsgValidateCriticalError;
        sReport += sSigPathName;
        sReport += " - Incorrect number of output channels.\n";
        rv = icMaxStatus(rv, icValidateCriticalError);
      }
      break;
    }
  default:
    {
      nInput = m_nInput;
      nOutput = m_nOutput;
    }
  }
  //CLUT check
  if (nInput!=nOutput) {
    if (!m_CLUT) {
      sReport += icMsgValidateCriticalError;
      sReport += sSigPathName;
      sReport += " - CLUT must be present.\n";
      rv = icMaxStatus(rv, icValidateCriticalError);
    }
  }
  if (m_CLUT) {
    rv = icMaxStatus(rv, m_CLUT->Validate(sigPath, sReport, pProfile));
  }
  return rv;
}
References icHeader::colorSpace, CIccInfo::GetSigPathName(), icGetFirstSigPathSig(), icGetSpaceSamples(), icMaxStatus(), icMsgValidateCriticalError, icMsgValidateWarning, icSigAToB0Tag, icSigAToB1Tag, icSigAToB2Tag, icSigAToB3Tag, icSigBToA0Tag, icSigBToA1Tag, icSigBToA2Tag, icSigBToA3Tag, icSigGamutTag, icSigHToS0Tag, icSigHToS1Tag, icSigHToS2Tag, icSigHToS3Tag, icValidateCriticalError, icValidateWarning, m_CLUT, m_nInput, m_nOutput, icHeader::pcs, CIccTag::Validate(), and CIccCLUT::Validate().
Referenced by CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLut8::Validate(), and CIccTagLut16::Validate().
Validate() [2/2]
icValidateStatus CIccTag::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual inherited
Function: Validate Each derived tag will implement it's own IsValid() function
Parameter(s): sig - signature of tag being validated, sDescription - A string to put tag validation report.
Name: CIccTag::Validate
Purpose: Check tag data validity. In base class we only look at the tag's reserved data value
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented in CIccTagGamutBoundaryDesc, CIccTagText, CIccTagUtf8Text, CIccTagZipUtf8Text, CIccTagUtf16Text, CIccTagTextDescription, CIccTagSignature, CIccTagNamedColor2, CIccTagXYZ, CIccTagChromaticity, CIccTagCicp, CIccTagSparseMatrixArray, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, CIccTagMeasurement, CIccTagMultiLocalizedUnicode, CIccTagData, CIccTagDateTime, CIccTagColorantOrder, CIccTagColorantTable, CIccTagViewingConditions, CIccTagProfileSeqDesc, CIccTagResponseCurveSet16, CIccTagSpectralDataInfo, CIccTagSpectralViewingConditions, CIccTagEmbeddedHeightImage, CIccTagEmbeddedNormalImage, CIccTagStruct, CIccTagArray, CIccTagDict, CIccTagEmbeddedProfile, CIccTagCurve, CIccTagParametricCurve, CIccTagSegmentedCurve, CIccTagMultiProcessElement, and CIccTagProfileSequenceId.
{
  icValidateStatus rv = icValidateOK;
  if (m_nReserved != 0) {
    CIccInfo Info;
    sReport += icMsgValidateNonCompliant;
    sReport += Info.GetSigPathName(sigPath);
    sReport += " - Reserved Value must be zero.\n";
    rv = icValidateNonCompliant;
  }
  return rv;
}
References CIccInfo::GetSigPathName(), icMsgValidateNonCompliant, icValidateNonCompliant, icValidateOK, and CIccTag::m_nReserved.
Referenced by CIccTagGamutBoundaryDesc::Validate(), Validate(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccArrayUnknown::Validate(), CIccArrayColorantInfo::Validate(), CIccArrayNamedColor::Validate(), CIccStructUnknown::Validate(), CIccTagText::Validate(), CIccTagUtf8Text::Validate(), CIccTagZipUtf8Text::Validate(), CIccTagUtf16Text::Validate(), CIccTagTextDescription::Validate(), CIccTagSignature::Validate(), CIccTagNamedColor2::Validate(), CIccTagXYZ::Validate(), CIccTagChromaticity::Validate(), CIccTagCicp::Validate(), CIccTagNum< T, Tsig >::Validate(), CIccTagFloatNum< T, Tsig >::Validate(), CIccTagMeasurement::Validate(), CIccTagMultiLocalizedUnicode::Validate(), CIccTagData::Validate(), CIccTagDateTime::Validate(), CIccTagColorantOrder::Validate(), CIccTagColorantTable::Validate(), CIccTagViewingConditions::Validate(), CIccTagProfileSeqDesc::Validate(), CIccTagResponseCurveSet16::Validate(), CIccTagSpectralDataInfo::Validate(), CIccTagSpectralViewingConditions::Validate(), CIccTagEmbeddedHeightImage::Validate(), CIccTagEmbeddedNormalImage::Validate(), CIccTagStruct::Validate(), CIccTagArray::Validate(), CIccTagDict::Validate(), CIccTagEmbeddedProfile::Validate(), CIccTagCurve::Validate(), CIccTagParametricCurve::Validate(), and CIccTagProfileSequenceId::Validate().
Write()
virtual bool CIccTag::Write (CIccIO * pIO) inline virtual inherited
Function: Write(pIO) Each derived tag will implement it's own Write() function.
Parameter(s): pIO - IO object used to write a tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Write is successful.
Reimplemented in CIccTagUnknown, CIccTagText, CIccTagUtf8Text, CIccTagZipUtf8Text, CIccTagUtf16Text, CIccTagTextDescription, CIccTagSignature, CIccTagNamedColor2, CIccTagXYZ, CIccTagChromaticity, CIccTagCicp, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, CIccTagMeasurement, CIccTagMultiLocalizedUnicode, CIccTagData, CIccTagDateTime, CIccTagColorantOrder, CIccTagColorantTable, CIccTagViewingConditions, CIccTagProfileSeqDesc, CIccTagResponseCurveSet16, CIccTagSpectralDataInfo, CIccTagSpectralViewingConditions, CIccTagEmbeddedHeightImage, CIccTagEmbeddedNormalImage, CIccTagStruct, CIccTagArray, CIccTagDict, CIccTagEmbeddedProfile, CIccTagCurve, CIccTagParametricCurve, CIccTagSegmentedCurve, CIccTagLutAtoB, CIccTagLut8, CIccTagLut16, CIccTagGamutBoundaryDesc, CIccTagMultiProcessElement, and CIccTagProfileSequenceId.
{ return false; }
Referenced by CIccMpeTintArray::Write(), CIccProfileDescText::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), and CIccTagLutAtoB::Write().
Field Documentation
m_bInputMatrix
bool CIccMBB::m_bInputMatrix protected
Referenced by CIccMBB(), CIccMBB(), CIccTagLutAtoB::CIccTagLutAtoB(), CIccTagLutBtoA::CIccTagLutBtoA(), IsInputMatrix(), and operator=().
m_bUseMCurvesAsBCurves
bool CIccMBB::m_bUseMCurvesAsBCurves protected
Referenced by CIccMBB(), CIccMBB(), Describe(), operator=(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), SwapMBCurves(), CIccTagLut8::Write(), and CIccTagLut16::Write().
m_CLUT
CIccCLUT* CIccMBB::m_CLUT protected
Referenced by CIccMBB(), CIccMBB(), Cleanup(), Describe(), GetCLUT(), NewCLUT(), NewCLUT(), operator=(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), SetCLUT(), Validate(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), and CIccTagLut16::Write().
m_csInput
icColorSpaceSignature CIccMBB::m_csInput protected
Referenced by CIccMBB(), CIccMBB(), Describe(), GetCsInput(), operator=(), and SetColorSpaces().
m_csOutput
icColorSpaceSignature CIccMBB::m_csOutput protected
Referenced by CIccMBB(), CIccMBB(), Describe(), GetCsOutput(), operator=(), and SetColorSpaces().
m_CurvesA
LPIccCurve* CIccMBB::m_CurvesA protected
Referenced by CIccMBB(), CIccMBB(), Cleanup(), Describe(), GetCurvesA(), NewCurvesA(), operator=(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), and CIccTagLut16::Write().
m_CurvesB
LPIccCurve* CIccMBB::m_CurvesB protected
Referenced by CIccMBB(), CIccMBB(), Cleanup(), Describe(), GetCurvesB(), NewCurvesB(), operator=(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), and CIccTagLut16::Write().
m_CurvesM
LPIccCurve* CIccMBB::m_CurvesM protected
Referenced by CIccMBB(), CIccMBB(), Cleanup(), Describe(), GetCurvesM(), NewCurvesM(), operator=(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), and CIccTagLut16::Write().
m_Matrix
CIccMatrix* CIccMBB::m_Matrix protected
Referenced by CIccMBB(), CIccMBB(), Cleanup(), Describe(), GetMatrix(), NewMatrix(), operator=(), CIccTagLutAtoB::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), and CIccTagLut16::Write().
m_nInput
icUInt8Number CIccMBB::m_nInput protected
Referenced by CIccMBB(), CIccMBB(), Cleanup(), Describe(), Init(), InputChannels(), NewCLUT(), NewCLUT(), NewCurvesA(), NewCurvesB(), NewCurvesM(), operator=(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), SetCLUT(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), Validate(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), and CIccTagLut16::Write().
m_nOutput
icUInt8Number CIccMBB::m_nOutput protected
Referenced by CIccMBB(), CIccMBB(), Cleanup(), Describe(), Init(), NewCLUT(), NewCLUT(), NewCurvesA(), NewCurvesB(), NewCurvesM(), operator=(), OutputChannels(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), SetCLUT(), Validate(), CIccTagLutBtoA::Validate(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), and CIccTagLut16::Write().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
The documentation for this class was generated from the following files:
IccProfLib/IccTagLut.h
IccProfLib/IccTagLut.cpp