iccDEV: Tools/CmdLine/IccCommon/IccJsonUtil.h File Reference
IccJsonUtil.h File Reference
#include <list>
#include <string>
#include <vector>
#include <nlohmann/json.hpp>
#include "../../../IccProfLib/IccDefs.h"
Typedefs
using json = nlohmann::json
Functions
template<typename T >
std::string arrayToJson (T *a, int nCount)
std::string fixJsonString (const char *v)
bool jsonToArray (const json &v, std::vector< std::string > &vals)
template<typename T >
bool jsonToArray (const json &v, std::vector< T > &vals)
template<typename T >
bool jsonToArray (const json &v, T *vals, int n)
bool jsonToColorSpace (const json &j, icColorSpaceSignature &sig)
bool jsonToCStr (const json &j, char *str, int nSize)
bool jsonToList (const json &v, std::list< std::string > &vals)
bool jsonToString (const json &j, std::string &value)
template<>
bool jsonToValue (const json &j, bool &nValue)
template<>
bool jsonToValue (const json &j, std::string &nValue)
template<typename T >
bool jsonToValue (const json &j, T &nValue)
template bool jsonToValue< bool > (const json &, bool &)
template bool jsonToValue< int > (const json &, int &)
template bool jsonToValue< std::string > (const json &, std::string &)
bool loadJsonFrom (json &j, const char *szFname)
bool saveJsonAs (const json &j, const char *szFname, int indent=1)
template<>
std::string valueToJson (const char *name, char *v)
template<>
std::string valueToJson (const char *name, const char *v)
std::string valueToJson (const char *name, const char *v, bool &bPreviousLine)
template<>
std::string valueToJson (const char *name, const std::string &v)
template<>
std::string valueToJson (const char *name, double v)
template<>
std::string valueToJson (const char *name, float v)
template<typename T >
std::string valueToJson (const char *name, T v)
std::string valueToJsonUuid (const char *name, const char *v, bool bBinary=false)
Typedef Documentation
json
using json = nlohmann::json
Function Documentation
arrayToJson()
template<typename T > std::string arrayToJson (T * a, int nCount)
{
  std::string str, num;
  str += "[ ";
  for (int i = 0; i < nCount; i++) {
    if (i)
      str += ", ";
    num = std::to_string(a[i]);
    str += num;
  }
  str += " ]";
  return str;
}
fixJsonString()
std::string fixJsonString (const char * v)
{
  std::string rv;
  for (; *v; v++) {
    if (*v == '\\')
      rv += "\\\\";
    else
      rv += *v;
  }
  return rv;
}
Referenced by valueToJson(), valueToJson(), and valueToJson().
jsonToArray() [1/3]
bool jsonToArray (const json & v, std::vector< std::string > & vals)
{
  if (v.is_array()) {
    size_t nSize = v.size();
    int nValid = 0;
    vals.resize(nSize);
    auto e = v.begin();
    for (int i = 0; e != v.end(); e++, i++) {
      if (e->is_string()) {
        vals[i] = e->get<std::string>();
        nValid++;
      }
      else {
        vals[i] = "";
      }
    }
    return nValid == nSize;
  }
  return false;
}
jsonToArray() [2/3]
template<typename T > bool jsonToArray (const json & v, std::vector< T > & vals)
{
  if (v.is_array()) {
    size_t nSize = v.size();
    int nValid = 0;
    a.resize(nSize);
    auto e = v.begin();
    for (int i = 0; e != v.end(); e++, i++) {
      if (e->is_number()) {
        a[i] = e->get<T>();
        nValid++;
      }
      else {
        a[i] = 0;
      }
    }
    return nValid == v.size();
  }
  return false;
}
Referenced by CIccCfgDataEntry::fromJson().
jsonToArray() [3/3]
template<typename T > bool jsonToArray (const json & v, T * vals, int n)
{
  if (v.is_array()) {
    int nValid = 0;
    auto e = v.begin();
    for (int i = 0; e != v.end() && i < n; e++, i++) {
      if (e->is_number()) {
        vals[i] = e->get<T>();
        nValid++;
      }
    }
    return nValid == v.size();
  }
  return false;
}
jsonToColorSpace()
bool jsonToColorSpace (const json & j, icColorSpaceSignature & sig)
{
  std::string str;
  if (jsonToValue(j, str)) {
    if (str.size())
      sig = (icColorSpaceSignature)icGetSigVal(str.c_str());
    else
      sig = icSigUnknownData;
    return true;
  }
  return false;
}
References icGetSigVal(), and jsonToValue().
Referenced by CIccCfgDataApply::fromJson(), and CIccCfgColorData::fromJson().
jsonToCStr()
bool jsonToCStr (const json & j, char * str, int nSize)
{
  if (j.is_string() && nSize>0) {
    std::string val = j.get<std::string>();
    strncpy(str, val.c_str(), nSize);
    str[nSize - 1] = 0;
    return true;
  }
  return false;
}
jsonToList()
bool jsonToList (const json & v, std::list< std::string > & vals)
{
  if (v.is_array()) {
    size_t nSize = v.size();
    int nValid = 0;
    auto e = v.begin();
    for (int i = 0; e != v.end(); e++, i++) {
      if (e->is_string()) {
        vals.push_back(e->get<std::string>());
        nValid++;
      }
    }
    return nValid == nSize;
  }
  return false;
}
Referenced by CIccCfgDataEntry::fromJson().
jsonToString()
bool jsonToString (const json & j, std::string & value)
{
  if (j.is_string()) {
    value = j.get<std::string>();
    return true;
  }
  return false;
}
Referenced by jsonToValue().
jsonToValue() [1/3]
template<> bool jsonToValue (const json & j, bool & nValue)
{
  if (j.is_boolean()) {
    value = j.get<bool>();
    return true;
  }
  else if (j.is_number_float()) {
    // don't want to check for 0 due to floating point messiness. If the value is greater than 0.5, then
    // it's definitely not 0.
    value = j.get<float>() > 0.5;
    return true;
  }
  else if (j.is_number_integer()) {
    value = j.get<int>() != 0;
    return true;
  }
  else if (j.is_number_unsigned()) {
    value = j.get<unsigned>() != 0;
    return true;
  }
  return false;
}
jsonToValue() [2/3]
template<> bool jsonToValue (const json & j, std::string & nValue)
{
  return jsonToString(j, value);
}
References jsonToString().
jsonToValue() [3/3]
template<typename T > bool jsonToValue (const json & j, T & nValue)
{
  if (j.is_number()) {
    nValue = j.get<T>();
    return true;
  }
  return false;
}
Referenced by CIccCfgDataApply::fromJson(), CIccCfgImageApply::fromJson(), CIccCfgCreateLink::fromJson(), CIccCfgProfile::fromJson(), CIccCfgDataEntry::fromJson(), CIccCfgColorData::fromJson(), jsonToColorSpace(), jsonToValue(), jsonToValue(), and jsonToValue().
jsonToValue< bool >()
template bool jsonToValue< bool > (const json & , bool &) extern
jsonToValue< int >()
template bool jsonToValue< int > (const json & , int &) extern
jsonToValue< std::string >()
template bool jsonToValue< std::string > (const json & , std::string &) extern
loadJsonFrom()
bool loadJsonFrom (json & j, const char * szFname)
{
  bool rv = false;
  j.clear();
  FILE* f = fopen(szFname, "rb");
  if (f) {
    fseek(f, 0, SEEK_END);
    unsigned long flen = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* buf = (char*)malloc(flen+1);
    if (buf) {
      buf[flen] = 0;
      if (fread(buf, 1, flen, f) == flen) {
        try {
          j = json::parse(buf);
          rv = true;
        }
        catch (...) {
        }
      }
      free(buf);
    }
    fclose(f);
  }
  return rv;
}
Referenced by main(), and main().
saveJsonAs()
bool saveJsonAs (const json & j, const char * szFname, int indent = 1)
{
  if (!j.is_object())
    return false;
  bool rv = false;
  FILE* f;
  if (szFname && szFname[0])
    f = fopen(szFname, "wb");
  else
    f = stdout;
  if (f) {
    std::string str = j.dump(indent);
    if (fwrite((void*)(str.c_str()), 1, (unsigned long)str.size(), f) == (long)str.size())
      rv = true;
    if (f!=stdout)
      fclose(f);
  }
  return rv;
}
Referenced by main().
valueToJson() [1/7]
template<> std::string valueToJson (const char * name, char * v)
{
  if (!name) {
    throw std::invalid_argument("name cannot be null");
  }
  if (!v) {
    return "\"" + std::string(name) + "\": null";
  }
  return "\"" + std::string(name) + "\": \"" + fixJsonString(v) + "\"";
}
References fixJsonString().
valueToJson() [2/7]
template<> std::string valueToJson (const char * name, const char * v)
{
  if (!name) {
    throw std::invalid_argument("name cannot be null");
  }
  if (!v) {
    return "\"" + std::string(name) + "\": null";
  }
  return "\"" + std::string(name) + "\": \"" + fixJsonString(v) + "\"";
}
References fixJsonString().
valueToJson() [3/7]
std::string valueToJson (const char * name, const char * v, bool & bPreviousLine)
{
  if (!name) {
    throw std::invalid_argument("name cannot be null");
  }
  if (v && *v) {
    std::string str = valueToJson(name, v);
    if (bPreviousLine) {
      return ", " + str;
    }
    bPreviousLine = true;
    return str;
  }
  return {};
}
References valueToJson().
valueToJson() [4/7]
template<> std::string valueToJson (const char * name, const std::string & v)
{
  if (!name) {
    throw std::invalid_argument("name cannot be null");
  }
  return "\"" + std::string(name) + "\": \"" + fixJsonString(v.c_str()) + "\"";
}
References fixJsonString().
valueToJson() [5/7]
template<> std::string valueToJson (const char * name, double v)
valueToJson() [6/7]
template<> std::string valueToJson (const char * name, float v)
valueToJson() [7/7]
template<typename T > std::string valueToJson (const char * name, T v)
{
  // Safeguard for nullptr name
  if (!name) {
    throw std::invalid_argument("name cannot be null");
  }
  return std::string("\"") + name + "\": " + std::to_string(v);
}
Referenced by valueToJson().
valueToJsonUuid()
std::string valueToJsonUuid (const char * name, const char * v, bool bBinary = false)