iccDEV: CIccProfileIdDesc Class Reference
CIccProfileIdDesc Class Reference
#include <IccTagProfSeqId.h>
Public Member Functions
CIccProfileIdDesc ()
CIccProfileIdDesc (CIccProfile &profile)
CIccProfileIdDesc (const CIccProfileIdDesc &pid)
CIccProfileIdDesc (icProfileID id, CIccTagMultiLocalizedUnicode desc)
void Describe (std::string &sDescription, int nVerboseness)
CIccProfileIdDesc & operator= (const CIccProfileIdDesc &pid)
bool Read (icUInt32Number size, CIccIO *pIO)
icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
bool Write (CIccIO *pIO)
Data Fields
CIccTagMultiLocalizedUnicode m_desc
icProfileID m_profileID
Detailed Description
Constructor & Destructor Documentation
CIccProfileIdDesc() [1/4]
CIccProfileIdDesc::CIccProfileIdDesc ()
Name: sampleICC::CIccProfileIdDesc::CIccProfileIdDesc
Purpose:
Args:
Return:
{
  memset(&m_profileID, 0, sizeof(m_profileID));
}
References m_profileID.
CIccProfileIdDesc() [2/4]
CIccProfileIdDesc::CIccProfileIdDesc (CIccProfile & profile)
Name: sampleICC::CIccProfileIdDesc::CIccProfileIdDesc
Purpose:
Args: CIccProfile &profile
Return:
{
  m_profileID = profile.m_Header.profileID;
  CIccTag *pTag = profile.FindTag(icSigProfileDescriptionTag);
  if (pTag) {
    switch (pTag->GetType()) {
      case icSigMultiLocalizedUnicodeType:
      {
        m_desc = *((CIccTagMultiLocalizedUnicode*)pTag);
      }
      break;
      case icSigTextDescriptionType:
      {
        CIccTagTextDescription *pText = (CIccTagTextDescription*)pTag;
        m_desc.SetText(pText->GetText());
      }
      break;
      case icSigTextType:
      {
        CIccTagText *pText = (CIccTagText*)pTag;
        m_desc.SetText(pText->GetText());
      }
      break;
      default:
        break;
    }
  }
}
References CIccTagText::GetText(), CIccTagTextDescription::GetText(), CIccTag::GetType(), icSigMultiLocalizedUnicodeType, icSigProfileDescriptionTag, icSigTextDescriptionType, icSigTextType, m_desc, m_profileID, CIccTagMultiLocalizedUnicode::operator=(), icHeader::profileID, and CIccTagMultiLocalizedUnicode::SetText().
Referenced by CIccTagProfileSequenceId::AddProfileDescription().
CIccProfileIdDesc() [3/4]
CIccProfileIdDesc::CIccProfileIdDesc (icProfileID id, CIccTagMultiLocalizedUnicode desc)
Name: sampleICC::CIccProfileIdDesc::CIccProfileIdDesc
Purpose:
Args: icProfileID id CIccMultiLocalizedUnicode desc
Return:
{
  m_profileID = id;
  m_desc = desc;
}
References m_desc, m_profileID, and CIccTagMultiLocalizedUnicode::operator=().
CIccProfileIdDesc() [4/4]
CIccProfileIdDesc::CIccProfileIdDesc (const CIccProfileIdDesc & pid)
Name: sampleICC::CIccProfileIdDesc::CIccProfileIdDesc
Purpose:
Args: const CIccProfileIdDesc &pid
Return:
{
  m_profileID = pid.m_profileID;
  m_desc = pid.m_desc;
}
References m_desc, m_profileID, and CIccTagMultiLocalizedUnicode::operator=().
Member Function Documentation
Describe()
void CIccProfileIdDesc::Describe (std::string & sDescription, int nVerboseness)
Name: sampleICC::CIccProfileIdDesc::Describe
Purpose:
Args: std::string &sDescription
Return: void
{
  std::string Dump;
  sDescription += "ProfileID:\n";
  size_t i;
  char buf[20];
  for (i=0; i<sizeof(icProfileID); i++) {
    if (i && i%4==0)
      sDescription += " ";
    sprintf(buf, "%02x", m_profileID.ID8[i]);
    sDescription += buf;
  }
  sDescription += "\n";
  sDescription += "Description:\n";
  m_desc.Describe(sDescription, nVerboseness);
  sDescription += "\n";
}
References CIccTagMultiLocalizedUnicode::Describe(), icProfileID::ID8, m_desc, and m_profileID.
Referenced by CIccTagProfileSequenceId::Describe().
operator=()
CIccProfileIdDesc & CIccProfileIdDesc::operator= (const CIccProfileIdDesc & pid)
Name: sampleICC::CIccProfileIdDesc::operator=
Purpose:
Args: const CIccProfileIdDesc &pid
Return: CIccProfileIdDesc &
{
  if (&pid == this)
    return *this;
  m_profileID = pid.m_profileID;
  m_desc = pid.m_desc;
  return *this;
}
References m_desc, m_profileID, and CIccTagMultiLocalizedUnicode::operator=().
Read()
bool CIccProfileIdDesc::Read (icUInt32Number size, CIccIO * pIO)
Name: sampleICC::CIccProfileIdDesc::Read
Purpose:
Args: icUInt32Number size CIccIO *pIO
Return: bool
{
  if (sizeof (icProfileID) > size)
    return false;
  if (pIO->Read8(&m_profileID, sizeof(icProfileID))!=sizeof(icProfileID))
    return false;
  if (!m_desc.Read(size - sizeof(icProfileID), pIO))
    return false;
  return true;
}
References m_desc, m_profileID, CIccTagMultiLocalizedUnicode::Read(), and CIccIO::Read8().
Referenced by CIccTagProfileSequenceId::Read().
Validate()
icValidateStatus CIccProfileIdDesc::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const
Name: CIccProfileIdDesc::Validate
Purpose:
Args: std::string &sReport
Return: icValidateStatus
{
  return m_desc.Validate(sigPath, sReport, pProfile);
}
References m_desc, and CIccTagMultiLocalizedUnicode::Validate().
Referenced by CIccTagProfileSequenceId::Validate().
Write()
bool CIccProfileIdDesc::Write (CIccIO * pIO)
Name: sampleICC::CIccProfileIdDesc::Write
Purpose:
Args: CIccIO *pIO
Return: bool
{
  pIO->Write8(&m_profileID, sizeof(icProfileID));
  m_desc.Write(pIO);
  return true;
}
References m_desc, m_profileID, CIccTagMultiLocalizedUnicode::Write(), and CIccIO::Write8().
Referenced by CIccTagProfileSequenceId::Write().
Field Documentation
m_desc
CIccTagMultiLocalizedUnicode CIccProfileIdDesc::m_desc
Referenced by CIccProfileIdDesc(), CIccProfileIdDesc(), CIccProfileIdDesc(), Describe(), operator=(), CIccTagXmlProfileSequenceId::ParseXml(), Read(), CIccTagXmlProfileSequenceId::ToXml(), Validate(), and Write().
m_profileID
icProfileID CIccProfileIdDesc::m_profileID
Referenced by CIccProfileIdDesc(), CIccProfileIdDesc(), CIccProfileIdDesc(), CIccProfileIdDesc(), Describe(), operator=(), CIccTagXmlProfileSequenceId::ParseXml(), Read(), CIccTagXmlProfileSequenceId::ToXml(), and Write().
The documentation for this class was generated from the following files:
IccProfLib/IccTagProfSeqId.h
IccProfLib/IccTagProfSeqId.cpp