iccDEV: CIccLogDebugger Class Reference
CIccLogDebugger Class Reference
Public Member Functions
virtual ~CIccLogDebugger ()
virtual bool AfterOp (SIccCalcOp *op, SIccOpState &os, SIccCalcOp *ops)
virtual bool BeforeOp (SIccCalcOp *op, SIccOpState &os, SIccCalcOp *ops)
virtual void BeginApply ()
virtual void EndApply ()
virtual void Error (const char *szMsg)
void reset ()
Static Public Member Functions
static void SetDebugger (IIccCalcDebugger *pDebugger)
Data Fields
std::list< std::string > m_log
Detailed Description
Constructor & Destructor Documentation
~CIccLogDebugger()
virtual CIccLogDebugger::~CIccLogDebugger () inline virtual
{}
Member Function Documentation
AfterOp()
virtual bool CIccLogDebugger::AfterOp (SIccCalcOp * op, SIccOpState & os, SIccCalcOp * ops) inline virtual
Implements IIccCalcDebugger.
  {
    std::string str;
    char buf[200];
    if (op->sig == icSigDataOp) {
      sprintf(buf, "%13s    ", "data");
      str = buf;
    }
    else {
      bool bEnd = false;
      if (op->sig == icSigIfOp || op->sig == icSigSelectOp) {
        str += "End:  ";
        bEnd = true;
      }
      std::string opDesc;
      op->Describe(opDesc, 100);
      if (bEnd)
        sprintf(buf, "%7s    ", opDesc.c_str());
      else
        sprintf(buf, "%13s    ", opDesc.c_str());
      str += buf;
    }
    for (int j = 0; j < (int)os.pStack->size(); j++) {
      sprintf(buf, " %.4f", (*os.pStack)[j]);
      str += buf;
    }
    m_log.push_back(str);
    if (op->sig == icSigIfOp || op->sig == icSigSelectOp)
      m_log.push_back("");
    return false;
  }
References SIccCalcOp::Describe(), icSigDataOp, icSigIfOp, icSigSelectOp, m_log, SIccOpState::pStack, and SIccCalcOp::sig.
BeforeOp()
virtual bool CIccLogDebugger::BeforeOp (SIccCalcOp * op, SIccOpState & os, SIccCalcOp * ops) inline virtual
Implements IIccCalcDebugger.
  {
    if (op->sig == icSigIfOp || op->sig == icSigSelectOp) {
      std::string str = "Start:";
      std::string opDesc;
      op->Describe(opDesc, 100);
      char buf[200];
      sprintf(buf, "%7s    ", opDesc.c_str());
      str += buf;
      for (int j = 0; j < (int)os.pStack->size(); j++) {
        sprintf(buf, " %.4f", (*os.pStack)[j]);
        str += buf;
      }
      m_log.push_back(str);
    }
    return false;
  }
References SIccCalcOp::Describe(), icSigIfOp, icSigSelectOp, m_log, SIccOpState::pStack, and SIccCalcOp::sig.
BeginApply()
virtual void CIccLogDebugger::BeginApply () inline virtual
Implements IIccCalcDebugger.
  {
    m_log.push_back("Begin Calc Apply");
  }
References m_log.
EndApply()
virtual void CIccLogDebugger::EndApply () inline virtual
Implements IIccCalcDebugger.
  {
    m_log.push_back("End Calculator Apply");
    m_log.push_back("");
  }
References m_log.
Error()
virtual void CIccLogDebugger::Error (const char * szMsg) inline virtual
Implements IIccCalcDebugger.
  {
    m_log.push_back(szMsg);
  }
References m_log.
reset()
void CIccLogDebugger::reset () inline
  {
    m_log.clear();
  }
References m_log.
Referenced by main().
SetDebugger()
void IIccCalcDebugger::SetDebugger (IIccCalcDebugger * pDebugger) static inherited
{
  if (pDebugger == icCalcDebuggerConsole)
    g_pDebugger = &g_ConsoleDebugger;
  else
    g_pDebugger = pDebugger;
}
References g_ConsoleDebugger, and g_pDebugger.
Referenced by main().
Field Documentation
m_log
std::list<std::string> CIccLogDebugger::m_log
Referenced by AfterOp(), BeforeOp(), BeginApply(), EndApply(), Error(), main(), and reset().
The documentation for this class was generated from the following file:
Tools/CmdLine/IccApplyNamedCmm/iccApplyNamedCmm.cpp