iccDEV: Tools/CmdLine/IccRoundTrip/iccRoundTrip.cpp File Reference
iccRoundTrip.cpp File Reference
#include <stdio.h>
#include <math.h>
#include "IccUtil.h"
#include "IccEval.h"
#include "IccPrmg.h"
#include "IccProfLibVer.h"
Data Structures
class CIccMinMaxEval
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
{
  if (argc<=1) {
    printf("Usage: iccRoundTrip profile {rendering_intent=1 {use_mpe=0}}\n");
    printf("Built with IccProfLib version " ICCPROFLIBVER "\n");
    printf("  where rendering_intent is (0=perceptual, 1=relative, 2=saturation, 3=absolute)\n");
    return -1;
  }
  icRenderingIntent nIntent = icRelativeColorimetric;
  int nUseMPE = 0;
  if (argc>2) {
    nIntent = (icRenderingIntent)atoi(argv[2]);
    if (argc>3) {
      nUseMPE = atoi(argv[3]);
    }
  }
  CIccMinMaxEval eval;
  icStatusCMM stat = eval.EvaluateProfile(argv[1], 0, nIntent, icInterpLinear, (nUseMPE!=0));
  if (stat!=icCmmStatOk) {
    printf("Unable to perform round trip on '%s'\n", argv[1]);
    return -1;
  }
  CIccPRMG prmg;
  stat = prmg.EvaluateProfile(argv[1], nIntent, icInterpLinear, (nUseMPE!=0));
  if (stat!=icCmmStatOk) {
    printf("Unable to perform PRMG analysis on '%s'\n", argv[1]);
    return -1;
  }
  CIccInfo info;
  printf("Profile:          '%s'\n", argv[1]);
  printf("Rendering Intent: %s\n", info.GetRenderingIntentName(nIntent));
  printf("Specified Gamut:  %s\n", prmg.m_bPrmgImplied ? "Perceptual Reference Medium Gamut" : "Not Specified");
  printf("\nRound Trip 1\n");
  printf(  "------------\n");
  printf("Min DeltaE:    %8.2" ICFLOATSFX "\n", eval.minDE1);
  printf("Mean DeltaE:   %8.2" ICFLOATSFX "\n", eval.GetMean1());
  printf("Max DeltaE:    %8.2" ICFLOATSFX "\n\n", eval.maxDE1);
  printf("Max L, a, b:   " ICFLOATFMT ", " ICFLOATFMT ", " ICFLOATFMT "\n", eval.maxLab1[0], eval.maxLab1[1], eval.maxLab1[2]);
  printf("\nRound Trip 2\n");
  printf(  "------------\n");
  printf("Min DeltaE:    %8.2" ICFLOATSFX "\n", eval.minDE2);
  printf("Mean DeltaE:   %8.2" ICFLOATSFX "\n", eval.GetMean2());
  printf("Max DeltaE:    %8.2" ICFLOATSFX "\n\n", eval.maxDE2);
  printf("Max L, a, b:   " ICFLOATFMT ", " ICFLOATFMT ", " ICFLOATFMT "\n", eval.maxLab2[0], eval.maxLab2[1], eval.maxLab2[2]);
  if (prmg.m_nTotal) {
    printf("\nPRMG Interoperability - Round Trip Results\n");
    printf(  "------------------------------------------------------\n");
    printf("DE <= 1.0 (%8u): %5.1f%%\n", prmg.m_nDE1, (float)prmg.m_nDE1/(float)prmg.m_nTotal*100.0);
    printf("DE <= 2.0 (%8u): %5.1f%%\n", prmg.m_nDE2, (float)prmg.m_nDE2/(float)prmg.m_nTotal*100.0);
    printf("DE <= 3.0 (%8u): %5.1f%%\n", prmg.m_nDE3, (float)prmg.m_nDE3/(float)prmg.m_nTotal*100.0);
    printf("DE <= 5.0 (%8u): %5.1f%%\n", prmg.m_nDE5, (float)prmg.m_nDE5/(float)prmg.m_nTotal*100.0);
    printf("DE <=10.0 (%8u): %5.1f%%\n", prmg.m_nDE10, (float)prmg.m_nDE10/(float)prmg.m_nTotal*100.0);
    printf("Total     (%8u)\n", prmg.m_nTotal);
  }
  return 0;
}
References CIccPRMG::EvaluateProfile(), CIccEvalCompare::EvaluateProfile(), CIccMinMaxEval::GetMean1(), CIccMinMaxEval::GetMean2(), CIccInfo::GetRenderingIntentName(), icCmmStatOk, icInterpLinear, icRelativeColorimetric, CIccPRMG::m_bPrmgImplied, CIccPRMG::m_nDE1, CIccPRMG::m_nDE10, CIccPRMG::m_nDE2, CIccPRMG::m_nDE3, CIccPRMG::m_nDE5, CIccPRMG::m_nTotal, CIccMinMaxEval::maxDE1, CIccMinMaxEval::maxDE2, CIccMinMaxEval::maxLab1, CIccMinMaxEval::maxLab2, CIccMinMaxEval::minDE1, and CIccMinMaxEval::minDE2.