iccDEV: CIccTagXmlParametricCurve Class Reference
CIccTagXmlParametricCurve Class Reference
#include <IccTagXml.h>
Public Member Functions
virtual ~CIccTagXmlParametricCurve ()
virtual icFloatNumber Apply (icFloatNumber v) const
virtual void Begin ()
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
virtual void DumpLut (std::string &sDescription, const icChar *szName, icColorSpaceSignature csSig, int nIndex, int nVerboseness)
icFloatNumber Find (icFloatNumber v)
virtual const char * GetClassName () const
virtual const char * GetExtClassName () const
virtual const char * GetExtDerivedClassName () const
virtual IIccExtensionTag * GetExtension ()
icUInt16Number GetFunctionType () const
icUInt16Number GetNumParam () const
icFloatNumber * GetParams () const
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsIdentity ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
icFloatNumber & operator[] (int index)
icFloatNumber Param (int index) const
virtual bool ParseXml (xmlNode *pNode, icConvertType nType, std::string &parseStr)
virtual bool ParseXml (xmlNode *pNode, std::string &parseStr)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
bool SetFunctionType (icUInt16Number nFunctionType)
virtual bool ToXml (std::string &xml, icConvertType nType, std::string blanks="")
virtual bool ToXml (std::string &xml, std::string blanks="")
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
icUInt16Number m_nReserved2
Protected Member Functions
icFloatNumber Find (icFloatNumber v, icFloatNumber p0, icFloatNumber v0, icFloatNumber p1, icFloatNumber v1)
Protected Attributes
icFloatNumber * m_dParam
icUInt16Number m_nFunctionType
icUInt16Number m_nNumParam
Detailed Description
Constructor & Destructor Documentation
~CIccTagXmlParametricCurve()
virtual CIccTagXmlParametricCurve::~CIccTagXmlParametricCurve () inline virtual
{}
Member Function Documentation
Apply()
icFloatNumber CIccTagParametricCurve::Apply (icFloatNumber X) const virtual inherited
Name: CIccTagParametricCurve::Apply
Purpose: Applies the curve to the value passed.
Args: x = value to be passed through the curve.
Return: The value modified by the curve.
Reimplemented from CIccCurve.
{
  double a, b;
  switch(m_nFunctionType) {
    case 0x0000:
      return (icFloatNumber)pow(X, m_dParam[0]);
    case 0x0001:
      a=m_dParam[1];
      b=m_dParam[2];
      if (X >= -b/a) {
        return (icFloatNumber)pow((double)a*X + b, (double)m_dParam[0]);
      }
      else {
        return 0;
      }
    case 0x0002:
      a=m_dParam[1];
      b=m_dParam[2];
      if (X >= -b/a) {
        return (icFloatNumber)pow((double)a*X + b, (double)m_dParam[0]) + m_dParam[3];
      }
      else {
        return m_dParam[3];
      }
    case 0x0003:
      if (X >= m_dParam[4]) {
        return (icFloatNumber)pow((double)m_dParam[1]*X + m_dParam[2], (double)m_dParam[0]);
      }
      else {
        return m_dParam[3]*X;
      }
    case 0x0004:
      if (X >= m_dParam[4]) {
        return (icFloatNumber)pow((double)m_dParam[1]*X + m_dParam[2], (double)m_dParam[0]) + m_dParam[5];
      }
      else {
        return m_dParam[3]*X + m_dParam[6];
      }
    default:
      return X;
  }
}
References CIccTagParametricCurve::m_dParam, and CIccTagParametricCurve::m_nFunctionType.
Referenced by CIccTagParametricCurve::Validate().
Begin()
virtual void CIccCurve::Begin () inline virtual inherited
Reimplemented in CIccTagCurve, and CIccTagSegmentedCurve.
{}
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagParametricCurve::Describe (std::string & sDescription, int nVerboseness) virtual inherited
Name: CIccTagParametricCurve::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  icChar buf[128];
  sprintf(buf, "FunctionType: %04Xh\n", m_nFunctionType);
  sDescription += buf;
  switch(m_nFunctionType) {
case 0x0000:
  sprintf(buf, "Y = X ^ %.4lf\n", m_dParam[0]);
  sDescription += buf;
  return;
case 0x0001:
  sprintf(buf, "Y = 0 when (X < %.4lf / %.4lf)\n",
    -m_dParam[2], m_dParam[1]);
  sDescription += buf;
  sprintf(buf, "Y = (%.4lf * X + %.4lf) ^ %.4lf   when (X >= %.4lf / %.4lf)\n",
    m_dParam[1], m_dParam[2], m_dParam[0],
    m_dParam[2], m_dParam[1]);
  sDescription += buf;
  return;
case 0x0002:
  sprintf(buf, "Y = %.4lf   when (X < %.4lf / %.4lf)\n", m_dParam[3],
    -m_dParam[2], m_dParam[1]);
  sDescription += buf;
  sprintf(buf, "Y = (%.4lf * X + %.4lf) ^ %.4lf + %.4lf   when (X >= %.4lf / %.4lf)\n",
    m_dParam[1], m_dParam[2], m_dParam[0],
    m_dParam[3],
    -m_dParam[2], m_dParam[1]);
  sDescription += buf;
  return;
case 0x0003:
  sprintf(buf, "Y = %lf * X   when (X < %.4lf)\n",
    m_dParam[3], m_dParam[4]);
  sDescription += buf;
  sprintf(buf, "Y = (%.4lf * X + %.4lf) ^ %.4lf   when (X >= %.4lf)\n",
    m_dParam[1], m_dParam[2], m_dParam[0],
    m_dParam[4]);
  sDescription += buf;
  return;
case 0x0004:
  sprintf(buf, "Y = %lf * X + %.4lf  when (X < %.4lf)\n",
    m_dParam[3], m_dParam[6], m_dParam[4]);
  sDescription += buf;
  sprintf(buf, "Y = (%.4lf * X + %.4lf) ^ %.4lf + %.4lf  when (X >= %.4lf)\n",
    m_dParam[1], m_dParam[2], m_dParam[0],
    m_dParam[5], m_dParam[4]);
  sDescription += buf;
  return;
default:
  int i;
  sprintf(buf, "Unknown Function with %d parameters:\n", m_nNumParam);
  sDescription += buf;
  for (i=0; i<m_nNumParam; i++) {
    sprintf(buf, "Param[%d] = %.4lf\n", i, m_dParam[i]);
    sDescription += buf;
  }
  }
}
References CIccTagParametricCurve::m_dParam, CIccTagParametricCurve::m_nFunctionType, and CIccTagParametricCurve::m_nNumParam.
Referenced by CIccTagParametricCurve::DumpLut().
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
DumpLut()
void CIccTagParametricCurve::DumpLut (std::string & sDescription, const icChar * szName, icColorSpaceSignature csSig, int nIndex, int nVerboseness) virtual inherited
Name: CIccTagParametricCurve::DumpLut
Purpose: Dump data associated with the tag to a string. Basically has the same function as Describe()
Args: sDescription = string to concatenate tag dump to, szName = name of the curve to be printed, csSig = color space signature of the curve data, nIndex = the channel number of color space
Reimplemented from CIccCurve.
{
  icChar buf[128];
  sprintf(buf, "BEGIN_CURVE %s\n", szName);
  sDescription += buf;
  Describe(sDescription, nVerboseness);
}
References CIccTagParametricCurve::Describe().
Find() [1/2]
icFloatNumber CIccCurve::Find (icFloatNumber v) inline inherited
{ return Find(v, 0, Apply(0), 1.0, Apply(1.0)); }
References CIccCurve::Apply(), and CIccCurve::Find().
Find() [2/2]
icFloatNumber CIccCurve::Find (icFloatNumber v, icFloatNumber p0, icFloatNumber v0, icFloatNumber p1, icFloatNumber v1) protected inherited
Name: CIccCurve::Find
Purpose: Read in the tag contents into a data block
Args: v = index to be searched, v0 = index less than/equal to v, p0 = the value at index v0, v1 = index greater than/equal to v, p1 = value at index v1
Return: The value at the requested index
{
  if (v<=v0)
    return p0;
  if (v>=v1)
    return p1;
  if (p1-p0 <= 0.00001) {
    icFloatNumber d0 = (icFloatNumber)fabs(v-v0);
    icFloatNumber d1 = (icFloatNumber)fabs(v1-v);
    if (d0<d1)
      return p0;
    return p1;
  }
  icFloatNumber np = (icFloatNumber)((p0 + p1)/2.0);
  icFloatNumber nv = Apply(np);
  if (v<=nv) {
    return Find(v, p0, v0, np, nv);
  }
  return Find(v, np, nv, p1, v1);
}
References CIccCurve::Apply(), and CIccCurve::Find().
Referenced by CIccCurve::Find(), and CIccCurve::Find().
GetClassName()
virtual const char * CIccTagXmlParametricCurve::GetClassName () const inline virtual
Reimplemented from CIccTagParametricCurve.
{return "CIccTagXmlParametricCurve"; }
GetExtClassName()
virtual const char * CIccTagXml::GetExtClassName () const inline virtual inherited
Implements IIccExtensionTag.
{ return "CIccTagXml"; }
Referenced by icProfDescToXml(), and icXmlParseProfDesc().
GetExtDerivedClassName()
virtual const char * CIccCurveXml::GetExtDerivedClassName () const inline virtual inherited
Reimplemented from CIccTagXml.
{return "CIccCurveXml"; }
GetExtension()
virtual IIccExtensionTag * CIccTagXmlParametricCurve::GetExtension () inline virtual
Reimplemented from CIccTag.
{return this; }
GetFunctionType()
icUInt16Number CIccTagParametricCurve::GetFunctionType () const inline inherited
{return m_nFunctionType; }
References CIccTagParametricCurve::m_nFunctionType.
GetNumParam()
icUInt16Number CIccTagParametricCurve::GetNumParam () const inline inherited
{ return m_nNumParam; }
References CIccTagParametricCurve::m_nNumParam.
Referenced by ParseXml().
GetParams()
icFloatNumber * CIccTagParametricCurve::GetParams () const inline inherited
{ return m_dParam; }
References CIccTagParametricCurve::m_dParam.
Referenced by ParseXml().
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagParametricCurve::GetType () const inline virtual inherited
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigParametricCurveType; }
References icSigParametricCurveType.
Referenced by CIccTagParametricCurve::Write().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsIdentity()
bool CIccTagParametricCurve::IsIdentity () virtual inherited
Name: CIccTagParametricCurve::IsIdentity
Purpose: Checks if this is an identity curve.
Return: true if the curve is an identity
Reimplemented from CIccCurve.
{
  switch(m_nFunctionType) {
    case 0x0000:
      return IsUnity(m_dParam[0]);
    case 0x0001:
    case 0x0002:
    case 0x0003:
    case 0x0004:
      return false;
    default:
      return true;
  }
}
References IsUnity(), CIccTagParametricCurve::m_dParam, and CIccTagParametricCurve::m_nFunctionType.
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
virtual CIccTag * CIccTagParametricCurve::NewCopy () const inline virtual inherited
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccCurve.
{ return new CIccTagParametricCurve(*this);}
References CIccTagParametricCurve::CIccTagParametricCurve().
operator[]()
icFloatNumber & CIccTagParametricCurve::operator[] (int index) inline inherited
{ return m_dParam[index]; }
References CIccTagParametricCurve::m_dParam.
Param()
icFloatNumber CIccTagParametricCurve::Param (int index) const inline inherited
{ return m_dParam[index]; }
References CIccTagParametricCurve::m_dParam.
ParseXml() [1/2]
bool CIccTagXmlParametricCurve::ParseXml (xmlNode * pNode, icConvertType nType, std::string & parseStr) virtual
Implements CIccCurveXml.
{
  return ParseXml (pNode, parseStr);
}
References ParseXml().
ParseXml() [2/2]
bool CIccTagXmlParametricCurve::ParseXml (xmlNode * pNode, std::string & parseStr) virtual
Implements CIccTagXml.
{
  xmlNode *pCurveNode = icXmlFindNode(pNode->children, "ParametricCurve");
  for (pCurveNode = pNode; pCurveNode; pCurveNode=pCurveNode->next) {
    if (pCurveNode->type==XML_ELEMENT_NODE) {
      if (!icXmlStrCmp(pCurveNode->name, "ParametricCurve")) {
        const char *functionType = icXmlAttrValue(pCurveNode, "FunctionType");
        if (!functionType)
          return false;
        if (!SetFunctionType(atoi(functionType))){
          return false;
        }
        CIccFloatArray data;
        if (!data.ParseArray(pCurveNode->children)){
          return false;
        }
        if (data.GetSize()!=GetNumParam()){
          return false;
        }
        icUInt32Number j;
        icFloatNumber *dParams = GetParams();
        icFloatNumber *dataBuf = data.GetBuf();
        for (j=0; j<data.GetSize(); j++) {
          dParams[j] = dataBuf[j];
        }
        xmlAttr *reserved2 = icXmlFindAttr(pCurveNode, "Reserved");
        if (reserved2) {
          m_nReserved2 = (icUInt16Number)atoi(icXmlAttrValue(reserved2));
        }
        return true;
      }
    }
  }
  return false;
}
References CIccXmlArrayType< T, Tsig >::GetBuf(), CIccTagParametricCurve::GetNumParam(), CIccTagParametricCurve::GetParams(), CIccXmlArrayType< T, Tsig >::GetSize(), icXmlAttrValue(), icXmlAttrValue(), icXmlFindAttr(), icXmlFindNode(), CIccTagParametricCurve::m_nReserved2, CIccXmlArrayType< T, Tsig >::ParseArray(), and CIccTagParametricCurve::SetFunctionType().
Referenced by ParseXml().
Read() [1/2]
bool CIccTagParametricCurve::Read (icUInt32Number size, CIccIO * pIO) virtual inherited
Name: CIccTagParametricCurve::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  icUInt16Number nFunctionType;
  icUInt32Number nHdrSize = sizeof(icTagTypeSignature) +
    sizeof(icUInt32Number) +
    2*sizeof(icUInt16Number);
  if ( nHdrSize > size)
    return false;
  if (!pIO) {
    return false;
  }
  if (!pIO->Read32(&sig) ||
    !pIO->Read32(&m_nReserved) ||
    !pIO->Read16(&nFunctionType) ||
    !pIO->Read16(&m_nReserved2))
    return false;
  SetFunctionType(nFunctionType);
  if (!m_nNumParam) {
    m_nNumParam = (icUInt16Number)((size-nHdrSize) / sizeof(icS15Fixed16Number));
    m_dParam = new icFloatNumber[m_nNumParam];
  }
  if (m_nNumParam) {
    int i;
    if (nHdrSize + m_nNumParam*sizeof(icS15Fixed16Number) > size)
      return false;
    for (i=0; i<m_nNumParam; i++) {
      icS15Fixed16Number num;
      if (!pIO->Read32(&num, 1))
        return false;
      m_dParam[i]=icFtoD(num);
    }
  }
  return true;
}
References icFtoD(), CIccTagParametricCurve::m_dParam, CIccTagParametricCurve::m_nNumParam, CIccTag::m_nReserved, CIccTagParametricCurve::m_nReserved2, CIccIO::Read16(), CIccIO::Read32(), and CIccTagParametricCurve::SetFunctionType().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
SetFunctionType()
bool CIccTagParametricCurve::SetFunctionType (icUInt16Number nFunctionType) inherited
Name: CIccTagParametricCurve::SetFunctionType
Purpose: Sets the type of the function the Parametric curve represents
Args: nFunctionType = the type of the function encoded as 0-4
Return: always true!!
{
  icUInt16Number nNumParam;
  switch(nFunctionType) {
    case 0x0000:
      nNumParam = 1;
      break;
    case 0x0001:
      nNumParam = 3;
      break;
    case 0x0002:
      nNumParam = 4;
      break;
    case 0x0003:
      nNumParam = 5;
      break;
    case 0x0004:
      nNumParam = 7;
      break;
    default:
      nNumParam = 0;
  }
  if (m_dParam)
    delete m_dParam;
  m_nNumParam = nNumParam;
  m_nFunctionType = nFunctionType;
  if (m_nNumParam)
    m_dParam = new icFloatNumber[m_nNumParam];
  else
    m_dParam = NULL;
  return true;
}
References CIccTagParametricCurve::m_dParam, CIccTagParametricCurve::m_nFunctionType, and CIccTagParametricCurve::m_nNumParam.
Referenced by ParseXml(), and CIccTagParametricCurve::Read().
ToXml() [1/2]
bool CIccTagXmlParametricCurve::ToXml (std::string & xml, icConvertType nType, std::string blanks = "") virtual
Implements CIccCurveXml.
{
  return ToXml(xml, blanks);
}
References ToXml().
ToXml() [2/2]
bool CIccTagXmlParametricCurve::ToXml (std::string & xml, std::string blanks = "") virtual
Implements CIccTagXml.
{
  char buf[80];
  int i;
  sprintf(buf, "<ParametricCurve FunctionType=\"%d\"", m_nFunctionType);
  xml += blanks + buf;
  if (m_nReserved2) {
    sprintf(buf, " Reserved=\"%d\"", m_nReserved2);
    xml += buf;
  }
  xml += ">\n";
  xml += blanks + " ";
  for (i=0; i<(int)m_nNumParam; i++) {
    sprintf(buf, " " icXmlFloatFmt, m_dParam[i]);
    xml += buf;
  }
  xml += "\n";
  sprintf(buf, "</ParametricCurve>\n");
  xml += blanks + buf;
  return true;
}
References CIccTagParametricCurve::m_dParam, CIccTagParametricCurve::m_nFunctionType, CIccTagParametricCurve::m_nNumParam, and CIccTagParametricCurve::m_nReserved2.
Referenced by ToXml().
Validate()
icValidateStatus CIccTagParametricCurve::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual inherited
Name: CIccTagParametricCurve::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  icSignature sig = icGetFirstSigPathSig(sigPath);
  if (m_nReserved2!=0) {
    sReport += icMsgValidateNonCompliant;
    sReport += sSigPathName;
    sReport += " - Reserved Value must be zero.\n";
    rv = icMaxStatus(rv, icValidateNonCompliant);
  }
  switch(m_nFunctionType) {
case 0x0000:
  if (m_nNumParam!=1) {
    sReport += icMsgValidateCriticalError;
    sReport += sSigPathName;
    sReport += " - Number of parameters inconsistent with function type.\n";
    rv = icMaxStatus(rv, icValidateCriticalError);
  }
  break;
case 0x0001:
  if (m_nNumParam!=3) {
    sReport += icMsgValidateCriticalError;
    sReport += sSigPathName;
    sReport += " - Number of parameters inconsistent with function type.\n";
    rv = icMaxStatus(rv, icValidateCriticalError);
  }
  break;
case 0x0002:
  if (m_nNumParam!=4) {
    sReport += icMsgValidateCriticalError;
    sReport += sSigPathName;
    sReport += " - Number of parameters inconsistent with function type.\n";
    rv = icMaxStatus(rv, icValidateCriticalError);
  }
  break;
case 0x0003:
  if (m_nNumParam!=5) {
    sReport += icMsgValidateCriticalError;
    sReport += sSigPathName;
    sReport += " - Number of parameters inconsistent with function type.\n";
    rv = icMaxStatus(rv, icValidateCriticalError);
  }
  break;
case 0x0004:
  if (m_nNumParam!=7) {
    sReport += icMsgValidateCriticalError;
    sReport += sSigPathName;
    sReport += " - Number of parameters inconsistent with function type.\n";
    rv = icMaxStatus(rv, icValidateCriticalError);
  }
  break;
default:
  sReport += icMsgValidateCriticalError;
  sReport += sSigPathName;
  sReport += " - Unknown function type.\n";
  rv = icMaxStatus(rv, icValidateCriticalError);
  }
  if (sig==icSigBlueTRCTag || sig==icSigRedTRCTag || sig==icSigGreenTRCTag || sig==icSigGrayTRCTag) {
    icFloatNumber lval = Apply(0.0);
    icFloatNumber uval = Apply(1.0);
    if (lval>0.0 || uval<1.0) {
      sReport += icMsgValidateWarning;
      sReport += sSigPathName;
      sReport += " - Curve cannot be accurately inverted.\n";
      rv = icMaxStatus(rv, icValidateWarning);
    }
  }
  return rv;
}
References CIccTagParametricCurve::Apply(), CIccInfo::GetSigPathName(), icGetFirstSigPathSig(), icMaxStatus(), icMsgValidateCriticalError, icMsgValidateNonCompliant, icMsgValidateWarning, icSigBlueTRCTag, icSigGrayTRCTag, icSigGreenTRCTag, icSigRedTRCTag, icValidateCriticalError, icValidateNonCompliant, icValidateWarning, CIccTagParametricCurve::m_nFunctionType, CIccTagParametricCurve::m_nNumParam, CIccTagParametricCurve::m_nReserved2, and CIccTag::Validate().
Write()
bool CIccTagParametricCurve::Write (CIccIO * pIO) virtual inherited
Name: CIccTagParametricCurve::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  if (!pIO) {
    return false;
  }
  sig = GetType();
  if (!pIO->Write32(&sig) ||
    !pIO->Write32(&m_nReserved) ||
    !pIO->Write16(&m_nFunctionType) ||
    !pIO->Write16(&m_nReserved2))
    return false;
  if (m_nNumParam) {
    int i;
    for (i=0; i<m_nNumParam; i++) {
      icS15Fixed16Number num = icDtoF(m_dParam[i]);
      if (!pIO->Write32(&num, 1))
        return false;
    }
  }
  if (!pIO->Align32())
    return false;
  return true;
}
References CIccIO::Align32(), CIccTagParametricCurve::GetType(), icDtoF(), CIccTagParametricCurve::m_dParam, CIccTagParametricCurve::m_nFunctionType, CIccTagParametricCurve::m_nNumParam, CIccTag::m_nReserved, CIccTagParametricCurve::m_nReserved2, CIccIO::Write16(), and CIccIO::Write32().
Field Documentation
m_dParam
icFloatNumber* CIccTagParametricCurve::m_dParam protected inherited
Referenced by CIccTagParametricCurve::CIccTagParametricCurve(), CIccTagParametricCurve::CIccTagParametricCurve(), CIccTagParametricCurve::~CIccTagParametricCurve(), CIccTagParametricCurve::Apply(), CIccTagParametricCurve::Describe(), CIccTagParametricCurve::GetParams(), CIccTagParametricCurve::IsIdentity(), CIccTagParametricCurve::operator=(), CIccTagParametricCurve::operator[](), CIccTagParametricCurve::Param(), CIccTagParametricCurve::Read(), CIccTagParametricCurve::SetFunctionType(), ToXml(), and CIccTagParametricCurve::Write().
m_nFunctionType
icUInt16Number CIccTagParametricCurve::m_nFunctionType protected inherited
Referenced by CIccTagParametricCurve::CIccTagParametricCurve(), CIccTagParametricCurve::CIccTagParametricCurve(), CIccTagParametricCurve::Apply(), CIccTagParametricCurve::Describe(), CIccTagParametricCurve::GetFunctionType(), CIccTagParametricCurve::IsIdentity(), CIccTagParametricCurve::operator=(), CIccTagParametricCurve::SetFunctionType(), ToXml(), CIccTagParametricCurve::Validate(), and CIccTagParametricCurve::Write().
m_nNumParam
icUInt16Number CIccTagParametricCurve::m_nNumParam protected inherited
Referenced by CIccTagParametricCurve::CIccTagParametricCurve(), CIccTagParametricCurve::CIccTagParametricCurve(), CIccTagParametricCurve::Describe(), CIccTagParametricCurve::GetNumParam(), CIccTagParametricCurve::operator=(), CIccTagParametricCurve::Read(), CIccTagParametricCurve::SetFunctionType(), ToXml(), CIccTagParametricCurve::Validate(), and CIccTagParametricCurve::Write().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_nReserved2
icUInt16Number CIccTagParametricCurve::m_nReserved2 inherited
Referenced by CIccTagParametricCurve::CIccTagParametricCurve(), CIccTagParametricCurve::CIccTagParametricCurve(), ParseXml(), CIccTagParametricCurve::Read(), ToXml(), CIccTagParametricCurve::Validate(), and CIccTagParametricCurve::Write().
The documentation for this class was generated from the following files:
IccXML/IccLibXML/IccTagXml.h
IccXML/IccLibXML/IccTagXml.cpp