iccDEV: CIccTagXmlMultiProcessElement Class Reference
CIccTagXmlMultiProcessElement Class Reference
#include <IccTagXml.h>
Public Member Functions
virtual ~CIccTagXmlMultiProcessElement ()
virtual void Apply (CIccApplyTagMpe *pApply, icFloatNumber *pDestPixel, const icFloatNumber *pSrcPixel) const
virtual void Attach (CIccMultiProcessElement *pElement)
virtual bool Begin (icElemInterp nInterp=icElemInterpLinear, IIccProfileConnectionConditions *pProfilePCC=NULL, IIccProfileConnectionConditions *pAppliedPCC=NULL, IIccCmmEnvVarLookup *pCmmEnvVarLookup=NULL)
void DeleteElement (int nIndex)
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
IIccProfileConnectionConditions * GetAppliedPCC ()
virtual const char * GetClassName () const
IIccCmmEnvVarLookup * GetCmmEnvLookup ()
CIccMultiProcessElement * GetElement (int nIndex)
virtual const char * GetExtClassName () const
virtual const char * GetExtDerivedClassName () const
virtual IIccExtensionTag * GetExtension ()
virtual CIccApplyTagMpe * GetNewApply ()
IIccProfileConnectionConditions * GetProfilePCC ()
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual void Insert (CIccMultiProcessElement *pElement)
virtual bool IsArrayType ()
bool IsLateBinding () const
bool IsLateBindingReflectance () const
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
icUInt32Number NumElements () const
icUInt16Number NumInputChannels () const
icUInt16Number NumOutputChannels () const
virtual bool ParseXml (xmlNode *pNode, std::string &parseStr)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
void SetChannels (icUInt16Number nInputChannels, icUInt16Number nOutputChannels)
virtual bool ToXml (std::string &xml, std::string blanks="")
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
static CIccMultiProcessElement * CreateElement (const icChar *szElementNodeName)
Data Fields
icUInt32Number m_nReserved
Protected Member Functions
virtual void Clean ()
virtual icInt32Number ElementIndex (CIccMultiProcessElement *pElem)
virtual CIccMultiProcessElementList::iterator GetFirstElem ()
virtual CIccMultiProcessElementList::iterator GetLastElem ()
virtual void GetNextElemIterator (CIccMultiProcessElementList::iterator &itr)
bool ParseElement (xmlNode *pNode, std::string &parseStr)
Protected Attributes
CIccMultiProcessElementList * m_list
icUInt16Number m_nBufChannels
icUInt16Number m_nInputChannels
icUInt16Number m_nOutputChannels
icUInt32Number m_nProcElements
IIccProfileConnectionConditions * m_pAppliedPCC
IIccCmmEnvVarLookup * m_pCmmEnvVarLookup
icPositionNumber * m_position
IIccProfileConnectionConditions * m_pProfilePCC
Detailed Description
Constructor & Destructor Documentation
~CIccTagXmlMultiProcessElement()
virtual CIccTagXmlMultiProcessElement::~CIccTagXmlMultiProcessElement () inline virtual
{}
Member Function Documentation
Apply()
void CIccTagMultiProcessElement::Apply (CIccApplyTagMpe * pApply, icFloatNumber * pDestPixel, const icFloatNumber * pSrcPixel) const virtual inherited
Name: CIccTagMultiProcessElement::Apply
Purpose:
Args:
Return:
{
  if (!pApply || !pApply->GetList() || !pApply->GetList()->size()) {
    memcpy(pDestPixel, pSrcPixel, m_nInputChannels*sizeof(icFloatNumber));
    return;
  }
#ifdef DEBUG_MPE_APPLY
  int nCount = 0;
  printf("Start of MPE APPLY\n");
  DumpMpeApplyPixe(nCount++, pSrcPixel, m_nInputChannels);
#endif
  CIccDblPixelBuffer *pApplyBuf = pApply->GetBuf();
  CIccApplyMpeIter i = pApply->begin();
  CIccApplyMpeIter next;
  next = i;
  next++;
  if (next==pApply->end()) {
    //Elements rely on pDestPixel != pSrcPixel
    if (pSrcPixel==pDestPixel) {
      i->ptr->Apply(pApplyBuf->GetDstBuf(), pSrcPixel);
      memcpy(pDestPixel, pApplyBuf->GetDstBuf(), m_nOutputChannels*sizeof(icFloatNumber));
    }
    else {
      i->ptr->Apply(pDestPixel, pSrcPixel);
    }
#ifdef DEBUG_MPE_APPLY
    DumpMpeApplyPixe(nCount++, pSrcPixel, m_nInputChannels);
#endif
  }
  else {
    i->ptr->Apply(pApplyBuf->GetDstBuf(), pSrcPixel);
#ifdef DEBUG_MPE_APPLY
    DumpMpeApplyPixe(nCount++, pApplyBuf->GetDstBuf(), m_nInputChannels);
#endif
    i++;
    next++;
    pApplyBuf->Switch();
    while (next != pApply->end()) {
      CIccMultiProcessElement *pElem = i->ptr->GetElem();
      if (!pElem->IsAcs()) {
        i->ptr->Apply(pApplyBuf->GetDstBuf(), pApplyBuf->GetSrcBuf());
#ifdef DEBUG_MPE_APPLY
        DumpMpeApplyPixe(nCount++, pApplyBuf->GetDstBuf(), m_nInputChannels);
#endif
        pApplyBuf->Switch();
      }
      i++;
      next++;
    }
    i->ptr->Apply(pDestPixel, pApplyBuf->GetSrcBuf());
#ifdef DEBUG_MPE_APPLY
    DumpMpeApplyPixe(nCount++, pDestPixel, m_nInputChannels);
#endif
  }
#ifdef DEBUG_MPE_APPLY
  printf("End MPE Apply\n\n");
#endif
}
References CIccApplyMpe::Apply(), CIccApplyTagMpe::begin(), CIccApplyTagMpe::end(), CIccApplyTagMpe::GetBuf(), CIccDblPixelBuffer::GetDstBuf(), CIccApplyMpe::GetElem(), CIccApplyTagMpe::GetList(), CIccDblPixelBuffer::GetSrcBuf(), CIccMultiProcessElement::IsAcs(), CIccTagMultiProcessElement::m_nInputChannels, CIccTagMultiProcessElement::m_nOutputChannels, CIccApplyMpePtr::ptr, and CIccDblPixelBuffer::Switch().
Referenced by main().
Attach()
void CIccTagMultiProcessElement::Attach (CIccMultiProcessElement * pElement) virtual inherited
Name: CIccTagMultiProcessElement::Attach
Purpose:
Args:
Return:
{
  if (!m_list) {
    m_list = new CIccMultiProcessElementList();
  }
  CIccMultiProcessElementPtr ptr;
  ptr.ptr = pElement;
  m_list->push_back(ptr);
}
References CIccTagMultiProcessElement::m_list, and CIccMultiProcessElementPtr::ptr.
Referenced by CDevLinkWriter::begin(), CIccDefaultEncProfileConverter::ConvertFromParams(), and main().
Begin()
bool CIccTagMultiProcessElement::Begin (icElemInterp nInterp = icElemInterpLinear, IIccProfileConnectionConditions * pProfilePCC = NULL, IIccProfileConnectionConditions * pAppliedPCC = NULL, IIccCmmEnvVarLookup * pCmmEnvVarLookup = NULL) virtual inherited
Name: CIccTagMultiProcessElement::Begin
Purpose: Initialize for application of processing element
Args: nInterp defines interpolation to use for N-Dimensional LUTs pPCC provides Profile Connection Conditions (only expected to be valid during call to Begin)
Return: true if initialization successful, false if not
{
  if (!m_list || !m_list->size()) {
    if (m_nInputChannels != m_nOutputChannels)
      return false;
    else
      return true;
  }
  m_pProfilePCC = pProfilePCC;
  m_pAppliedPCC = pAppliedPCC;
  m_pCmmEnvVarLookup = pCmmEnvVarLookup;
  CIccMultiProcessElementList::iterator i;
  m_nBufChannels=0;
  //Now we initialize each processing element checking channel matching as we go
  CIccMultiProcessElement *last=NULL;
  i = m_list->begin();
  if (i->ptr->NumInputChannels() != m_nInputChannels)
    return false;
  for (; i!= m_list->end(); i++) {
    if (last) {
      if (i->ptr->NumInputChannels() != last->NumOutputChannels())
        return false;
    }
    last = i->ptr;
    if (last) {
      if (m_nBufChannels < last->NumOutputChannels())
        m_nBufChannels = last->NumOutputChannels();
      if (!last->Begin(nInterp, this))
        return false;
    }
  }
  //The output channels must match
  if (last && last->NumOutputChannels() != m_nOutputChannels)
    return false;
  m_pAppliedPCC = NULL;
  m_pProfilePCC = NULL;
  return true;
}
References CIccMultiProcessElement::Begin(), CIccTagMultiProcessElement::m_list, CIccTagMultiProcessElement::m_nBufChannels, CIccTagMultiProcessElement::m_nInputChannels, CIccTagMultiProcessElement::m_nOutputChannels, CIccTagMultiProcessElement::m_pAppliedPCC, CIccTagMultiProcessElement::m_pCmmEnvVarLookup, CIccTagMultiProcessElement::m_pProfilePCC, CIccMultiProcessElement::NumInputChannels(), CIccMultiProcessElement::NumOutputChannels(), and CIccMultiProcessElementPtr::ptr.
Referenced by main().
Clean()
void CIccTagMultiProcessElement::Clean () protected virtual inherited
Name: CIccTagMultiProcessElement::Clean
Purpose:
Args:
Return:
{
  if (m_list) {
    CIccLutPtrMap map;
    CIccMultiProcessElementList::iterator i;
    for (i=m_list->begin(); i!=m_list->end(); i++) {
      if (!map[i->ptr].offset) {
        map[i->ptr].offset = 1;
        delete i->ptr;
      }
    }
    delete m_list;
    m_list = NULL;
  }
  if (m_position) {
    free(m_position);
    m_position = NULL;
  }
  m_nProcElements = 0;
}
References CIccTagMultiProcessElement::m_list, CIccTagMultiProcessElement::m_nProcElements, CIccTagMultiProcessElement::m_position, icPositionNumber::offset, and CIccMultiProcessElementPtr::ptr.
Referenced by CIccTagMultiProcessElement::~CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), and CIccTagMultiProcessElement::Read().
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
CreateElement()
CIccMultiProcessElement * CIccTagXmlMultiProcessElement::CreateElement (const icChar * szElementNodeName) static
{
  if (!strcmp(szElementNodeName, "CurveSetElement")) {
    return new CIccMpeXmlCurveSet;
  }
  if (!strcmp(szElementNodeName, "MatrixElement")) {
    return new CIccMpeXmlMatrix;
  }
  if (!strcmp(szElementNodeName, "CLutElement")) {
    return new CIccMpeXmlCLUT;
  }
  if (!strcmp(szElementNodeName, "ExtCLutElement")) {
    return new CIccMpeXmlExtCLUT;
  }
  if (!strcmp(szElementNodeName, "CalculatorElement")) {
    return new CIccMpeXmlCalculator;
  }
  if (!strcmp(szElementNodeName, "TintArrayElement")) {
    return new CIccMpeXmlTintArray;
  }
  if (!strcmp(szElementNodeName, "ToneMapElement")) {
    return new CIccMpeXmlToneMap;
  }
  if (!strcmp(szElementNodeName, "JabToXYZElement")) {
    return new CIccMpeXmlJabToXYZ;
  }
  if (!strcmp(szElementNodeName, "UnknownElement")) {
    return new CIccMpeXmlUnknown;
  }
  if (!strcmp(szElementNodeName, "XYZToJabElement")) {
    return new CIccMpeXmlXYZToJab;
  }
  if (!strcmp(szElementNodeName, "EmissionMatrixElement")) {
    return new CIccMpeXmlEmissionMatrix;
  }
  if (!strcmp(szElementNodeName, "InvEmissionMatrixElement")) {
    return new CIccMpeXmlInvEmissionMatrix;
  }
  if (!strcmp(szElementNodeName, "EmissionCLutElement")) {
    return new CIccMpeXmlEmissionCLUT;
  }
  if (!strcmp(szElementNodeName, "ReflectanceCLutElement")) {
    return new CIccMpeXmlReflectanceCLUT;
  }
  if (!strcmp(szElementNodeName, "EmissionObserverElement")) {
    return new CIccMpeXmlEmissionObserver;
  }
  if (!strcmp(szElementNodeName, "ReflectanceObserverElement")) {
    return new CIccMpeXmlReflectanceObserver;
  }
  if (!strcmp(szElementNodeName, "BAcsElement")) {
    return new CIccMpeXmlBAcs;
  }
  if (!strcmp(szElementNodeName, "EAcsElement")) {
    return new CIccMpeXmlEAcs;
  }
  return NULL;
}
Referenced by ParseElement(), and CIccMpeXmlCalculator::ParseImport().
DeleteElement()
void CIccTagMultiProcessElement::DeleteElement (int nIndex) inherited
Describe()
void CIccTagMultiProcessElement::Describe (std::string & sDescription, int nVerboseness) virtual inherited
Name: CIccTagMultiProcessElement::Describe
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icChar buf[128];
  sprintf(buf, "BEGIN MULTI_PROCESS_ELEMENT_TAG %d %d\n", m_nInputChannels, m_nOutputChannels);
  sDescription += buf;
  sDescription += "\n";
  CIccMultiProcessElementList::iterator i;
  int j;
  for (j=0, i=m_list->begin(); i!=m_list->end(); j++, i++) {
    sprintf(buf, "PROCESS_ELEMENT #%d\n", j+1);
    sDescription += buf;
    i->ptr->Describe(sDescription, nVerboseness);
    sDescription += "\n";
  }
  sDescription += "END MULTI_PROCESS_ELEMENT_TAG\n";
}
References CIccMultiProcessElement::Describe(), CIccTagMultiProcessElement::m_list, CIccTagMultiProcessElement::m_nInputChannels, CIccTagMultiProcessElement::m_nOutputChannels, and CIccMultiProcessElementPtr::ptr.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
ElementIndex()
icInt32Number CIccTagMultiProcessElement::ElementIndex (CIccMultiProcessElement * pElem) protected virtual inherited
Name: CIccTagMultiProcessElement::ElementIndex
Purpose:
Args:
Return:
{
  CIccMultiProcessElementList::iterator i;
  icInt32Number n;
  for (n=0, i=m_list->begin(); i!= m_list->end(); i++, n++) {
    if (i->ptr == pElem)
      break;
  }
  if (i==m_list->end())
    n=-1;
  return n;
}
References CIccTagMultiProcessElement::m_list, and CIccMultiProcessElementPtr::ptr.
GetAppliedPCC()
IIccProfileConnectionConditions * CIccTagMultiProcessElement::GetAppliedPCC () inline inherited
{ return m_pAppliedPCC; }
References CIccTagMultiProcessElement::m_pAppliedPCC.
Referenced by CIccMpeEmissionMatrix::Begin(), CIccMpeInvEmissionMatrix::Begin(), CIccMpeEmissionCLUT::Begin(), CIccMpeReflectanceCLUT::Begin(), CIccMpeEmissionObserver::Begin(), and CIccMpeReflectanceObserver::Begin().
GetClassName()
virtual const char * CIccTagXmlMultiProcessElement::GetClassName () const inline virtual
Reimplemented from CIccTagMultiProcessElement.
{return "CIccTagXmlMultiProcessElement"; }
GetCmmEnvLookup()
IIccCmmEnvVarLookup * CIccTagMultiProcessElement::GetCmmEnvLookup () inline inherited
{ return m_pCmmEnvVarLookup; }
References CIccTagMultiProcessElement::m_pCmmEnvVarLookup.
Referenced by CIccMpeCalculator::Begin().
GetElement()
CIccMultiProcessElement * CIccTagMultiProcessElement::GetElement (int nIndex) inherited
Name: CIccTagMultiProcessElement::GetElement
Purpose:
Args:
Return:
{
  if (!m_list)
    return NULL;
  CIccMultiProcessElementList::iterator i;
  int j;
  for(i=m_list->begin(), j=0; j<nIndex && i!=m_list->end(); i++, j++);
  if (i!=m_list->end())
    return i->ptr;
  return NULL;
}
References CIccTagMultiProcessElement::m_list, and CIccMultiProcessElementPtr::ptr.
Referenced by main().
GetExtClassName()
virtual const char * CIccTagXml::GetExtClassName () const inline virtual inherited
Implements IIccExtensionTag.
{ return "CIccTagXml"; }
Referenced by icProfDescToXml(), and icXmlParseProfDesc().
GetExtDerivedClassName()
virtual const char * CIccTagXml::GetExtDerivedClassName () const inline virtual inherited
Implements IIccExtensionTag.
Reimplemented in CIccCurveXml.
{ return ""; }
GetExtension()
virtual IIccExtensionTag * CIccTagXmlMultiProcessElement::GetExtension () inline virtual
Reimplemented from CIccTag.
{return this; }
GetFirstElem()
CIccMultiProcessElementList::iterator CIccTagMultiProcessElement::GetFirstElem () protected virtual inherited
{
  return m_list->begin();
}
References CIccTagMultiProcessElement::m_list.
Referenced by CIccTagMultiProcessElement::GetNewApply().
GetLastElem()
CIccMultiProcessElementList::iterator CIccTagMultiProcessElement::GetLastElem () protected virtual inherited
{
  return m_list->end();
}
References CIccTagMultiProcessElement::m_list.
Referenced by CIccTagMultiProcessElement::GetNewApply().
GetNewApply()
CIccApplyTagMpe * CIccTagMultiProcessElement::GetNewApply () virtual inherited
Name: CIccTagMultiProcessElement::GetNewApply
Purpose:
Args:
Return:
{
  CIccApplyTagMpe *pApply = new CIccApplyTagMpe(this);
  if (!pApply)
    return NULL;
  CIccDblPixelBuffer *pApplyBuf = pApply->GetBuf();
  pApplyBuf->UpdateChannels(m_nBufChannels);
  if (!pApplyBuf->Begin()) {
    delete pApply;
    return NULL;
  }
  if (!m_list || !m_list->size())
    return pApply;
  CIccMultiProcessElementList::iterator i, last;
  last = GetLastElem();
  for (i=GetFirstElem(); i!=last;) {
    pApply->AppendElem(i->ptr);
    GetNextElemIterator(i);
  }
  return pApply;
}
References CIccApplyTagMpe::CIccApplyTagMpe(), CIccApplyTagMpe::AppendElem(), CIccDblPixelBuffer::Begin(), CIccApplyTagMpe::GetBuf(), CIccTagMultiProcessElement::GetFirstElem(), CIccTagMultiProcessElement::GetLastElem(), CIccTagMultiProcessElement::GetNextElemIterator(), CIccTagMultiProcessElement::m_list, CIccTagMultiProcessElement::m_nBufChannels, CIccMultiProcessElementPtr::ptr, and CIccDblPixelBuffer::UpdateChannels().
Referenced by main().
GetNextElemIterator()
void CIccTagMultiProcessElement::GetNextElemIterator (CIccMultiProcessElementList::iterator & itr) protected virtual inherited
Name: CIccTagMultiProcessElement::GetNextElemIterator
Purpose:
Args:
Return:
{
  itr++;
}
Referenced by CIccTagMultiProcessElement::GetNewApply().
GetProfilePCC()
IIccProfileConnectionConditions * CIccTagMultiProcessElement::GetProfilePCC () inline inherited
{ return m_pProfilePCC; }
References CIccTagMultiProcessElement::m_pProfilePCC.
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagMultiProcessElement::GetType () const inline virtual inherited
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigMultiProcessElementType; }
References icSigMultiProcessElementType.
Referenced by CIccTagMultiProcessElement::Validate(), and CIccTagMultiProcessElement::Write().
Insert()
void CIccTagMultiProcessElement::Insert (CIccMultiProcessElement * pElement) virtual inherited
Name: CIccTagMultiProcessElement::Insert
Purpose:
Args:
Return:
{
  if (!m_list) {
    m_list = new CIccMultiProcessElementList();
  }
  CIccMultiProcessElementPtr ptr;
  ptr.ptr = pElement;
  m_list->push_front(ptr);
}
References CIccTagMultiProcessElement::m_list, and CIccMultiProcessElementPtr::ptr.
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsLateBinding()
bool CIccTagMultiProcessElement::IsLateBinding () const inherited
Name: CIccTagMultiProcessElement::IsLateBinding
Purpose:
Args:
Return:
{
  if (!m_list)
    return false;
  CIccMultiProcessElementList::const_iterator i;
  for (i = m_list->begin(); i!= m_list->end(); i++) {
    if (i->ptr->IsLateBinding()) {
      return true;
    }
  }
  return false;
}
References CIccMultiProcessElement::IsLateBinding(), CIccTagMultiProcessElement::m_list, and CIccMultiProcessElementPtr::ptr.
IsLateBindingReflectance()
bool CIccTagMultiProcessElement::IsLateBindingReflectance () const inherited
Name: CIccTagMultiProcessElement::IsLateBindingReflectance
Purpose:
Args:
Return:
{
  if (!m_list)
    return false;
  CIccMultiProcessElementList::const_iterator i;
  for (i = m_list->begin(); i!= m_list->end(); i++) {
    if (i->ptr->IsLateBindingReflectance()) {
      return true;
    }
  }
  return false;
}
References CIccMultiProcessElement::IsLateBindingReflectance(), CIccTagMultiProcessElement::m_list, and CIccMultiProcessElementPtr::ptr.
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
bool CIccTagMultiProcessElement::IsSupported () virtual inherited
Name: CIccTagMultiProcessElement::IsSupported
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  if (m_list) {
    CIccMultiProcessElementList::iterator i;
    for (i=m_list->begin(); i!=m_list->end(); i++) {
      if (!i->ptr->IsSupported())
        return false;
    }
  }
  return true;
}
References CIccMultiProcessElement::IsSupported(), CIccTagMultiProcessElement::m_list, and CIccMultiProcessElementPtr::ptr.
NewCopy()
virtual CIccTag * CIccTagMultiProcessElement::NewCopy () const inline virtual inherited
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
{ return new CIccTagMultiProcessElement(*this);}
References CIccTagMultiProcessElement::CIccTagMultiProcessElement().
NumElements()
icUInt32Number CIccTagMultiProcessElement::NumElements () const inline inherited
{ return m_list ? (icUInt32Number)(m_list->size()) : 0; }
References CIccTagMultiProcessElement::m_list.
Referenced by main().
NumInputChannels()
icUInt16Number CIccTagMultiProcessElement::NumInputChannels () const inline inherited
{ return m_nInputChannels; }
References CIccTagMultiProcessElement::m_nInputChannels.
Referenced by main(), and ToXml().
NumOutputChannels()
icUInt16Number CIccTagMultiProcessElement::NumOutputChannels () const inline inherited
{ return m_nOutputChannels; }
References CIccTagMultiProcessElement::m_nOutputChannels.
Referenced by main(), and ToXml().
ParseElement()
bool CIccTagXmlMultiProcessElement::ParseElement (xmlNode * pNode, std::string & parseStr) protected
{
  xmlAttr *attr;
  if (pNode->type != XML_ELEMENT_NODE) {
    return false;
  }
  CIccMultiProcessElement *pMpe = CreateElement((const icChar*)pNode->name);
  if (!pMpe) {
    parseStr += std::string("Unknown Element Type (") + (const icChar*)pNode->name + ")\n";
    return false;
  }
  CIccMultiProcessElementPtr ptr;
  IIccExtensionMpe *pExt = pMpe->GetExtension();
  if (pExt) {
    if (!strcmp(pExt->GetExtClassName(), "CIccMpeXml")) {
      CIccMpeXml* pXmlMpe = (CIccMpeXml*)pExt;
      if (pXmlMpe->ParseXml(pNode, parseStr)) {
        if ((attr=icXmlFindAttr(pNode, "Reserved"))) {
          sscanf(icXmlAttrValue(attr), "%u", &pMpe->m_nReserved);
        }
        ptr.ptr = pMpe;
        m_list->push_back(ptr);
      }
      else {
        parseStr += std::string("Unable to parse element of type ") + pMpe->GetClassName() + "\n";
        delete pMpe;
        return false;
      }
    }
    else {
      parseStr += std::string("Element ") + pMpe->GetClassName() + "isn't of type CIccMpeXml\n";
      delete pMpe;
      return false;
    }
  }
  else {
    parseStr += std::string("Element ") + pMpe->GetClassName() + "isn't of type CIccMpeXml\n";
    delete pMpe;
    return false;
  }
  return true;
}
References CreateElement(), CIccMultiProcessElement::GetClassName(), IIccExtensionMpe::GetExtClassName(), CIccMultiProcessElement::GetExtension(), icXmlAttrValue(), icXmlFindAttr(), CIccTagMultiProcessElement::m_list, CIccMultiProcessElement::m_nReserved, CIccMpeXml::ParseXml(), and CIccMultiProcessElementPtr::ptr.
Referenced by ParseXml().
ParseXml()
bool CIccTagXmlMultiProcessElement::ParseXml (xmlNode * pNode, std::string & parseStr) virtual
Implements CIccTagXml.
{
  pNode = icXmlFindNode(pNode, "MultiProcessElements");
  if (!pNode) {
    parseStr += "Cannot Find MultiProcessElements\n";
    return false;
  }
  xmlAttr *pInputChannels = icXmlFindAttr(pNode, "InputChannels");
  xmlAttr *pOutputChannels = icXmlFindAttr(pNode, "OutputChannels");
  if (!pInputChannels || !pOutputChannels) {
    parseStr += "Invalid channels in MultiProcessElements\n";
    return false;
  }
  m_nInputChannels = atoi(icXmlAttrValue(pInputChannels));
  m_nOutputChannels = atoi(icXmlAttrValue(pOutputChannels));
  if (!m_list) {
    m_list = new CIccMultiProcessElementList();
  }
  else {
    m_list->clear();
  }
  xmlNode *elemNode;
  for (elemNode = pNode->children; elemNode; elemNode = elemNode->next) {
    if (elemNode->type == XML_ELEMENT_NODE) {
      if (!ParseElement(elemNode, parseStr)) {
        char str[100];
        parseStr += "Unable to parse element (";
        parseStr += (char*)elemNode->name;
        sprintf(str, ") starting on line %d\n", elemNode->line);
        parseStr += str;
        return false;
      }
    }
  }
  return true;
}
References icXmlAttrValue(), icXmlFindAttr(), icXmlFindNode(), CIccTagMultiProcessElement::m_list, CIccTagMultiProcessElement::m_nInputChannels, CIccTagMultiProcessElement::m_nOutputChannels, and ParseElement().
Read() [1/2]
bool CIccTagMultiProcessElement::Read (icUInt32Number size, CIccIO * pIO) virtual inherited
Name: CIccTagMultiProcessElement::Read
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  icUInt32Number headerSize = sizeof(icTagTypeSignature) +
    sizeof(icUInt32Number) +
    sizeof(icUInt8Number) +
    sizeof(icUInt8Number) +
    sizeof(icUInt16Number);
  if (headerSize > size)
    return false;
  if (!pIO) {
    return false;
  }
  Clean();
  icUInt32Number tagStart = pIO->Tell();
  if (!pIO->Read32(&sig))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  if (!pIO->Read16(&m_nInputChannels))
    return false;
  if (!pIO->Read16(&m_nOutputChannels))
    return false;
  if (!pIO->Read32(&m_nProcElements))
    return false;
  if (headerSize + (icUInt64Number)m_nProcElements*sizeof(icUInt32Number) > size)
    return false;
  m_list = new CIccMultiProcessElementList();
  if (!m_list)
    return false;
  icUInt32Number i;
  m_position = (icPositionNumber*)calloc(m_nProcElements, sizeof(icPositionNumber));
  if (!m_position)
    return false;
  CIccLutOffsetMap loadedElements;
  for (i=0; i<m_nProcElements; i++) {
    if (!pIO->Read32(&m_position[i].offset))
      return false;
    if (!pIO->Read32(&m_position[i].size))
      return false;
  }
  CIccMultiProcessElementPtr ptr;
  icElemTypeSignature sigElem;
  for (i=0; i<m_nProcElements; i++) {
    if (m_position[i].offset+m_position[i].size > size) {
      return false;
    }
    //Use hash to cache offset duplication
    CIccMultiProcessElement *element = loadedElements[m_position[i].offset];
    if (!element) {
      icUInt32Number pos = tagStart + m_position[i].offset;
      if (pIO->Seek(pos, icSeekSet)!=(icInt32Number)pos) {
        return false;
      }
      if (!pIO->Read32(&sigElem)) {
        return false;
      }
      if (pIO->Seek(pos, icSeekSet)!=(icInt32Number)pos) {
        return false;
      }
      element = CIccMultiProcessElement::Create(sigElem);
      if (!element) {
        return false;
      }
      if (!element->Read(m_position[i].size, pIO)) {
        delete element;
        return false;
      }
      loadedElements[m_position[i].offset] = element;
    }
    ptr.ptr = element;
    m_list->push_back(ptr);
  }
  return true;
}
References CIccTagMultiProcessElement::Clean(), CIccMultiProcessElement::Create(), icSeekSet, CIccTagMultiProcessElement::m_list, CIccTagMultiProcessElement::m_nInputChannels, CIccTagMultiProcessElement::m_nOutputChannels, CIccTagMultiProcessElement::m_nProcElements, CIccTag::m_nReserved, CIccTagMultiProcessElement::m_position, icPositionNumber::offset, CIccMultiProcessElementPtr::ptr, CIccMultiProcessElement::Read(), CIccIO::Read16(), CIccIO::Read32(), CIccIO::Seek(), icPositionNumber::size, and CIccIO::Tell().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
SetChannels()
void CIccTagMultiProcessElement::SetChannels (icUInt16Number nInputChannels, icUInt16Number nOutputChannels) inline inherited
{m_nInputChannels = nInputChannels; m_nOutputChannels = nOutputChannels;}
References CIccTagMultiProcessElement::m_nInputChannels, and CIccTagMultiProcessElement::m_nOutputChannels.
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams().
ToXml()
bool CIccTagXmlMultiProcessElement::ToXml (std::string & xml, std::string blanks = "") virtual
Implements CIccTagXml.
{
  std::string info;
  char line[256];
  CIccMultiProcessElementList::iterator i;
  sprintf(line, "<MultiProcessElements InputChannels=\"%d\" OutputChannels=\"%d\">\n", NumInputChannels(), NumOutputChannels());
  xml += blanks + line;
  for (i=m_list->begin(); i!=m_list->end(); i++) {
    if (i->ptr) {
      CIccMultiProcessElement *pMpe = i->ptr;
      IIccExtensionMpe *pMpeExt = pMpe->GetExtension();
      if (pMpeExt) {
        if (!strcmp(pMpeExt->GetExtClassName(), "CIccMpeXml")) {
          CIccMpeXml *pMpeXml = (CIccMpeXml*)pMpeExt;
          pMpeXml->ToXml(xml, blanks + "  ");
        }
        else {
          return false;
        }
      }
      else {
        return false;
      }
    }
  }
  xml += blanks + "</MultiProcessElements>\n";
  return true;
}
References IIccExtensionMpe::GetExtClassName(), CIccMultiProcessElement::GetExtension(), CIccTagMultiProcessElement::m_list, CIccTagMultiProcessElement::NumInputChannels(), CIccTagMultiProcessElement::NumOutputChannels(), CIccMultiProcessElementPtr::ptr, and CIccMpeXml::ToXml().
Validate()
icValidateStatus CIccTagMultiProcessElement::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual inherited
Name: CIccTagMultiProcessElement::Validate
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icValidateStatus rv = icValidateOK;
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  bool bMatchChannels = true;
  if (!m_list || !m_list->size()) {
    if (m_nInputChannels != m_nOutputChannels) {
      sReport += icMsgValidateCriticalError;
      sReport += sSigPathName;
      sReport += " No processing elements and input and output channels do not match!\n";
      rv = icMaxStatus(rv, icValidateCriticalError);
    }
    else {
      sReport += icMsgValidateWarning;
      sReport += sSigPathName;
      sReport += " No processing elements.\n";
      rv = icMaxStatus(rv, icValidateWarning);
    }
  }
  if (!pProfile) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " - Tag validation incomplete: Pointer to profile unavailable.\n";
    rv = icMaxStatus(rv, icValidateWarning);
    return rv;
  }
  icUInt32Number nInput, nOutput;
  //Check # of channels
  switch(icGetFirstSigPathSig(sigPath)) {
    case icSigAToB0Tag:
    case icSigAToB1Tag:
    case icSigAToB2Tag:
    case icSigAToB3Tag:
      {
        nInput = icGetSpaceSamples(pProfile->m_Header.colorSpace);
        if (m_nInputChannels != nInput) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of input channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        nOutput = icGetSpaceSamples(pProfile->m_Header.pcs);
        if (m_nOutputChannels != nOutput) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of output channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        break;
      }
    case icSigBToA0Tag:
    case icSigBToA1Tag:
    case icSigBToA2Tag:
    case icSigBToA3Tag:
      {
        nInput = icGetSpaceSamples(pProfile->m_Header.pcs);
        if (m_nInputChannels!=nInput) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of input channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        nOutput = icGetSpaceSamples(pProfile->m_Header.colorSpace);
        if (m_nOutputChannels!=nOutput) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of output channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        break;
      }
    case icSigDToB0Tag:
    case icSigDToB1Tag:
    case icSigDToB2Tag:
    case icSigDToB3Tag:
      {
        nInput = icGetSpaceSamples(pProfile->m_Header.colorSpace);
        if (m_nInputChannels != nInput) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of input channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        nOutput = icGetSpectralSpaceSamples(&pProfile->m_Header);
        if (m_nOutputChannels != nOutput) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of output channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        break;
      }
    case icSigBToD0Tag:
    case icSigBToD1Tag:
    case icSigBToD2Tag:
    case icSigBToD3Tag:
      {
        nInput = icGetSpectralSpaceSamples(&pProfile->m_Header);
        if (m_nInputChannels!=nInput) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of input channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        nOutput = icGetSpaceSamples(pProfile->m_Header.colorSpace);
        if (m_nOutputChannels!=nOutput) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of output channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        break;
      }
    case icSigHToS0Tag:
    case icSigHToS1Tag:
    case icSigHToS2Tag:
    case icSigHToS3Tag:
      {
        nInput = icGetSpaceSamples(pProfile->m_Header.pcs);
        if (m_nInputChannels != nInput) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of input channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        nOutput = icGetSpaceSamples(pProfile->m_Header.pcs);
        if (m_nOutputChannels != nOutput) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of output channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        break;
      }
    case icSigCustomToStandardPccTag:
    case icSigStandardToCustomPccTag:
      {
        if (m_nInputChannels != 3) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of input channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        if (m_nOutputChannels != 3) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of output channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        break;
      }
    case icSigBRDFAToB0Tag:
    case icSigBRDFAToB1Tag:
    case icSigBRDFAToB2Tag:
    case icSigBRDFAToB3Tag:
      {
        switch(icGetFirstSigPathSig(sigPath)) {
          case icSigBrdfTransformMbr:
            //TODO: Initialize input and output
            nInput = nOutput = 0;
            break;
          case icSigBrdfLightTransformMbr:
            //TODO: Initialize input and output
            nInput = nOutput = 0;
            break;
          case icSigBrdfOutputTransformMbr:
            //TODO: Initialize input and output
            nInput = nOutput = 0;
            break;
          default:
            break;
        }
        break;
      }
    case icSigBRDFDToB0Tag:
    case icSigBRDFDToB1Tag:
    case icSigBRDFDToB2Tag:
    case icSigBRDFDToB3Tag:
      {
        switch(icGetFirstSigPathSig(sigPath)) {
          case icSigBrdfTransformMbr:
            //TODO: Initialize input and output
            nInput = nOutput = 0;
            break;
          case icSigBrdfLightTransformMbr:
            //TODO: Initialize input and output
            nInput = nOutput = 0;
            break;
          case icSigBrdfOutputTransformMbr:
            //TODO: Initialize input and output
            nInput = nOutput = 0;
            break;
          default:
            break;
        }
        break;
      }
    case icSigMToA0Tag:
      {
        nInput = icGetMaterialColorSpaceSamples(pProfile->m_Header.mcs);
        if (m_nInputChannels != nInput) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of input channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        nOutput = icGetSpaceSamples(pProfile->m_Header.colorSpace);
        if (m_nOutputChannels != nOutput) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of output channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        break;
      }
    case icSigAToM0Tag:
      {
        nInput = icGetSpaceSamples(pProfile->m_Header.colorSpace);
        if (m_nInputChannels != nInput) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of input channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        nOutput = icGetMaterialColorSpaceSamples(pProfile->m_Header.mcs);
        if (m_nOutputChannels != nOutput) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of output channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        break;
      }
    case icSigMToB0Tag:
    case icSigMToB1Tag:
    case icSigMToB2Tag:
    case icSigMToB3Tag:
    {
        nInput = icGetMaterialColorSpaceSamples(pProfile->m_Header.mcs);
        if (m_nInputChannels != nInput) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of input channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        nOutput = icGetSpaceSamples(pProfile->m_Header.pcs);
        if (m_nOutputChannels != nOutput) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of output channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        break;
      }
    case icSigMToS0Tag:
    case icSigMToS1Tag:
    case icSigMToS2Tag:
    case icSigMToS3Tag:
    {
        nInput = icGetMaterialColorSpaceSamples(pProfile->m_Header.mcs);
        if (m_nInputChannels != nInput) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of input channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        nOutput = icGetSpectralSpaceSamples(&pProfile->m_Header);
        if (m_nOutputChannels != nOutput) {
          sReport += icMsgValidateCriticalError;
          sReport += sSigPathName;
          sReport += " - Incorrect number of output channels.\n";
          rv = icMaxStatus(rv, icValidateCriticalError);
        }
        break;
      }
    default:
      sReport += icMsgValidateWarning;
      sReport += sSigPathName;
      sReport += " - Unknown tag - Cannot validate input and output channels!\n";
      rv = icMaxStatus(rv, icValidateWarning);
      bMatchChannels = false;
      break;
  }
  if (!m_list || !m_list->size()) {
    return rv;
  }
  CIccMultiProcessElementList::iterator i = m_list->begin();
  CIccMultiProcessElement *last=NULL;
  if (bMatchChannels && i->ptr->NumInputChannels() != m_nInputChannels) {
    sReport += icMsgValidateCriticalError;
    sReport += sSigPathName;
    sReport += "Mis-matching number of input channels in first process element!\n";
    return icValidateCriticalError;
  }
  for (; i!= m_list->end(); i++) {
    if (last) {
      if (i->ptr->NumInputChannels() != last->NumOutputChannels()) {
        sReport += icMsgValidateCriticalError;
        sReport += sSigPathName;
        sReport += "(";
        sReport += last->GetClassName();
        sReport += "->";
        sReport += i->ptr->GetClassName();
        sReport += " Mis-matching number of channels in last process element!\n";
        return icValidateCriticalError;
      }
    }
    last = i->ptr;
    if (last)
        rv = icMaxStatus(rv, last->Validate(sigPath+icGetSigPath(GetType()), sReport, this));
  }
  if (bMatchChannels && last && last->NumOutputChannels() != m_nOutputChannels) {
    sReport += icMsgValidateCriticalError;
    sReport += sSigPathName;
    sReport += " Mis-matching number of output channels!\n";
    return icValidateCriticalError;
  }
  return rv;
}
References icHeader::colorSpace, CIccMultiProcessElement::GetClassName(), CIccInfo::GetSigPathName(), CIccTagMultiProcessElement::GetType(), icGetFirstSigPathSig(), icGetMaterialColorSpaceSamples(), icGetSigPath(), icGetSpaceSamples(), icGetSpectralSpaceSamples(), icMaxStatus(), icMsgValidateCriticalError, icMsgValidateWarning, icSigAToB0Tag, icSigAToB1Tag, icSigAToB2Tag, icSigAToB3Tag, icSigAToM0Tag, icSigBRDFAToB0Tag, icSigBRDFAToB1Tag, icSigBRDFAToB2Tag, icSigBRDFAToB3Tag, icSigBRDFDToB0Tag, icSigBRDFDToB1Tag, icSigBRDFDToB2Tag, icSigBRDFDToB3Tag, icSigBrdfLightTransformMbr, icSigBrdfOutputTransformMbr, icSigBrdfTransformMbr, icSigBToA0Tag, icSigBToA1Tag, icSigBToA2Tag, icSigBToA3Tag, icSigBToD0Tag, icSigBToD1Tag, icSigBToD2Tag, icSigBToD3Tag, icSigCustomToStandardPccTag, icSigDToB0Tag, icSigDToB1Tag, icSigDToB2Tag, icSigDToB3Tag, icSigHToS0Tag, icSigHToS1Tag, icSigHToS2Tag, icSigHToS3Tag, icSigMToA0Tag, icSigMToB0Tag, icSigMToB1Tag, icSigMToB2Tag, icSigMToB3Tag, icSigMToS0Tag, icSigMToS1Tag, icSigMToS2Tag, icSigMToS3Tag, icSigStandardToCustomPccTag, icValidateCriticalError, icValidateOK, icValidateWarning, CIccTagMultiProcessElement::m_list, CIccTagMultiProcessElement::m_nInputChannels, CIccTagMultiProcessElement::m_nOutputChannels, icHeader::mcs, CIccMultiProcessElement::NumInputChannels(), CIccMultiProcessElement::NumOutputChannels(), icHeader::pcs, CIccMultiProcessElementPtr::ptr, and CIccMultiProcessElement::Validate().
Write()
bool CIccTagMultiProcessElement::Write (CIccIO * pIO) virtual inherited
Name: CIccTagMultiProcessElement::Write
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  if (!pIO)
    return false;
  icUInt32Number tagStart = pIO->Tell();
  if (!pIO->Write32(&sig))
    return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  if (!pIO->Write16(&m_nInputChannels))
    return false;
  if (!pIO->Write16(&m_nOutputChannels))
    return false;
  if (m_list) {
    m_nProcElements = (icUInt32Number)m_list->size();
  }
  else {
    m_nProcElements = 0;
  }
  if (!pIO->Write32(&m_nProcElements))
    return false;
  if (m_nProcElements) {
    icUInt32Number offsetPos = pIO->Tell();
    if (m_position) {
      free(m_position);
    }
    m_position = (icPositionNumber*)calloc(m_nProcElements, sizeof(icPositionNumber));
    if (!m_position)
      return false;
    //Write an empty position table
    icUInt32Number j, zeros[2] = { 0, 0 };
    for (j=0; j<m_nProcElements; j++) {
      if (pIO->Write32(zeros, 2)!=2)
        return false;
    }
    CIccLutPtrMap map;
    CIccMultiProcessElementList::iterator i;
    icUInt32Number start, end;
    icPositionNumber position;
    //Write out each process element
    for (j=0, i=m_list->begin(); i!=m_list->end(); i++, j++) {
      if (map.find(i->ptr)==map.end()) {
        start = pIO->Tell();
        if (!i->ptr->Write(pIO))
          return false;
        end = pIO->Tell();
        if (!pIO->Align32())
          return false;
        position.offset = start - tagStart;
        position.size = end - start;
        map[i->ptr] = position;
      }
      m_position[j] = map[i->ptr];
    }
    icUInt32Number endPos = pIO->Tell();
    if (pIO->Seek(offsetPos, icSeekSet)<0)
      return false;
    for (j=0; j<m_nProcElements; j++) {
      if (!pIO->Write32(&m_position[j].offset))
        return false;
      if (!pIO->Write32(&m_position[j].size))
        return false;
    }
    if (pIO->Seek(endPos, icSeekSet)<0)
      return false;
  }
  return true;
}
References CIccIO::Align32(), CIccTagMultiProcessElement::GetType(), icSeekSet, CIccTagMultiProcessElement::m_list, CIccTagMultiProcessElement::m_nInputChannels, CIccTagMultiProcessElement::m_nOutputChannels, CIccTagMultiProcessElement::m_nProcElements, CIccTag::m_nReserved, CIccTagMultiProcessElement::m_position, icPositionNumber::offset, CIccMultiProcessElementPtr::ptr, CIccIO::Seek(), icPositionNumber::size, CIccIO::Tell(), CIccMultiProcessElement::Write(), CIccIO::Write16(), and CIccIO::Write32().
Field Documentation
m_list
CIccMultiProcessElementList* CIccTagMultiProcessElement::m_list protected inherited
Referenced by CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::Attach(), CIccTagMultiProcessElement::Begin(), CIccTagMultiProcessElement::Clean(), CIccTagMultiProcessElement::Describe(), CIccTagMultiProcessElement::ElementIndex(), CIccTagMultiProcessElement::GetElement(), CIccTagMultiProcessElement::GetFirstElem(), CIccTagMultiProcessElement::GetLastElem(), CIccTagMultiProcessElement::GetNewApply(), CIccTagMultiProcessElement::Insert(), CIccTagMultiProcessElement::IsLateBinding(), CIccTagMultiProcessElement::IsLateBindingReflectance(), CIccTagMultiProcessElement::IsSupported(), CIccTagMultiProcessElement::NumElements(), CIccTagMultiProcessElement::operator=(), ParseElement(), ParseXml(), CIccTagMultiProcessElement::Read(), ToXml(), CIccTagMultiProcessElement::Validate(), and CIccTagMultiProcessElement::Write().
m_nBufChannels
icUInt16Number CIccTagMultiProcessElement::m_nBufChannels protected inherited
Referenced by CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::Begin(), and CIccTagMultiProcessElement::GetNewApply().
m_nInputChannels
icUInt16Number CIccTagMultiProcessElement::m_nInputChannels protected inherited
Referenced by CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::Apply(), CIccTagMultiProcessElement::Begin(), CIccTagMultiProcessElement::Describe(), CIccTagMultiProcessElement::NumInputChannels(), CIccTagMultiProcessElement::operator=(), ParseXml(), CIccTagMultiProcessElement::Read(), CIccTagMultiProcessElement::SetChannels(), CIccTagMultiProcessElement::Validate(), and CIccTagMultiProcessElement::Write().
m_nOutputChannels
icUInt16Number CIccTagMultiProcessElement::m_nOutputChannels protected inherited
Referenced by CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::Apply(), CIccTagMultiProcessElement::Begin(), CIccTagMultiProcessElement::Describe(), CIccTagMultiProcessElement::NumOutputChannels(), CIccTagMultiProcessElement::operator=(), ParseXml(), CIccTagMultiProcessElement::Read(), CIccTagMultiProcessElement::SetChannels(), CIccTagMultiProcessElement::Validate(), and CIccTagMultiProcessElement::Write().
m_nProcElements
icUInt32Number CIccTagMultiProcessElement::m_nProcElements protected inherited
Referenced by CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::Clean(), CIccTagMultiProcessElement::operator=(), CIccTagMultiProcessElement::Read(), and CIccTagMultiProcessElement::Write().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_pAppliedPCC
IIccProfileConnectionConditions* CIccTagMultiProcessElement::m_pAppliedPCC protected inherited
Referenced by CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::Begin(), CIccTagMultiProcessElement::GetAppliedPCC(), and CIccTagMultiProcessElement::operator=().
m_pCmmEnvVarLookup
IIccCmmEnvVarLookup* CIccTagMultiProcessElement::m_pCmmEnvVarLookup protected inherited
Referenced by CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::Begin(), CIccTagMultiProcessElement::GetCmmEnvLookup(), and CIccTagMultiProcessElement::operator=().
m_position
icPositionNumber* CIccTagMultiProcessElement::m_position protected inherited
Referenced by CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::Clean(), CIccTagMultiProcessElement::operator=(), CIccTagMultiProcessElement::Read(), and CIccTagMultiProcessElement::Write().
m_pProfilePCC
IIccProfileConnectionConditions* CIccTagMultiProcessElement::m_pProfilePCC protected inherited
Referenced by CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::Begin(), CIccTagMultiProcessElement::GetProfilePCC(), and CIccTagMultiProcessElement::operator=().
The documentation for this class was generated from the following files:
IccXML/IccLibXML/IccTagXml.h
IccXML/IccLibXML/IccTagXml.cpp