iccDEV: CubeFile Class Reference
CubeFile Class Reference
Public Member Functions
CubeFile (const char *szFilename)
~CubeFile ()
void close ()
std::string getCopyright ()
std::string getDescription ()
icFloatNumber * getMaxInput ()
icFloatNumber * getMinInput ()
bool isCustomInputRange ()
bool parse3DTable (icFloatNumber *toLut, icUInt32Number nSizeLut)
bool parseHeader ()
int sizeLut3D ()
Protected Member Functions
const char * getNext (const char *str)
std::string getNextLine ()
std::string getTitle (const char *str)
bool isEOF ()
bool open ()
std::string toEnd (const char *str)
Protected Attributes
bool m_bLutInVideoRange = false
bool m_bLutOutVideoRange = false
std::string m_comments
FILE * m_f =nullptr
icFloatNumber m_fMaxInput [3] = { 1.0f, 1.0f, 1.0f }
icFloatNumber m_fMinInput [3] = { 0.0f, 0.0f, 0.0f }
std::string m_sFilename
int m_sizeLut3D = 0
std::string m_title
Detailed Description
Constructor & Destructor Documentation
CubeFile()
CubeFile::CubeFile (const char * szFilename) inline
  {
    m_sFilename = szFilename;
  }
References m_sFilename.
Referenced by main().
~CubeFile()
CubeFile::~CubeFile () inline
{ close(); }
References close().
Member Function Documentation
close()
void CubeFile::close () inline
  {
    if (m_f)
      fclose(m_f);
    m_f = nullptr;
  }
References m_f.
Referenced by ~CubeFile(), and main().
getCopyright()
std::string CubeFile::getCopyright () inline
{ return m_comments; }
References m_comments.
Referenced by main().
getDescription()
std::string CubeFile::getDescription () inline
{ return m_title; }
References m_title.
Referenced by main().
getMaxInput()
icFloatNumber * CubeFile::getMaxInput () inline
{ return m_fMaxInput; }
References m_fMaxInput.
Referenced by main().
getMinInput()
icFloatNumber * CubeFile::getMinInput () inline
{ return m_fMinInput; }
References m_fMinInput.
Referenced by main().
getNext()
const char * CubeFile::getNext (const char * str) inline protected
  {
    while (*str && *str == ' ') str++;
    while (*str && *str != ' ') str++;
    while (*str && *str == ' ') str++;
    return str;
  }
Referenced by parse3DTable(), and parseHeader().
getNextLine()
std::string CubeFile::getNextLine () inline protected
  {
    std::string rv;
    for (int n=0; n<MAX_LINE_LEN && !isEOF(); n++) {
      char c = fgetc(m_f);
      if ((c < 0 && feof(m_f)) || c == '\n')
        break;
      if (c == '\r') //skip unsupported carriage returns
        continue;
      rv += (unsigned char)c;
    }
    return rv;
  }
References isEOF(), and m_f.
Referenced by parse3DTable(), and parseHeader().
getTitle()
std::string CubeFile::getTitle (const char * str) inline protected
  {
    std::string rv;
    bool bNeedQuote = false;
    if (*str == '\"') {
      bNeedQuote = true;
      str++;
    }
    while (*str && (!bNeedQuote || *str != '\"')) {
      rv += *str++;
    }
    return rv;
  }
Referenced by parseHeader().
isCustomInputRange()
bool CubeFile::isCustomInputRange () inline
  {
    if (!icIsNear(m_fMinInput[0], 0.0) || !icIsNear(m_fMinInput[1], 0.0) || !icIsNear(m_fMinInput[2], 0.0) ||
        !icIsNear(m_fMaxInput[0], 1.0) || !icIsNear(m_fMaxInput[1], 1.0) || !icIsNear(m_fMaxInput[2], 1.0))
      return true;
    return false;
  }
References icIsNear(), m_fMaxInput, and m_fMinInput.
Referenced by main().
isEOF()
bool CubeFile::isEOF () inline protected
{ return m_f ? feof(m_f)!=0 : true; }
References m_f.
Referenced by getNextLine(), parse3DTable(), and parseHeader().
open()
bool CubeFile::open () inline protected
  {
    if (!m_f) {
      m_f = fopen(m_sFilename.c_str(), "rb");
    }
    else {
      fseek(m_f, 0, SEEK_SET);
    }
    return m_f != nullptr;
  }
References m_f, and m_sFilename.
Referenced by parseHeader().
parse3DTable()
bool CubeFile::parse3DTable (icFloatNumber * toLut, icUInt32Number nSizeLut) inline
  {
    icUInt32Number num = m_sizeLut3D * m_sizeLut3D * m_sizeLut3D;
    //
    if (!m_sizeLut3D || nSizeLut != num*3)
      return false;
    const char* next;
    for (auto n = 0u; n < num && !isEOF();) {
      std::string line = getNextLine();
      //Skip empty and commented lines
      if (line[0] == '#' || line.size() == 0)
        continue;
      *toLut++ = (icFloatNumber)atof(line.c_str());
      next = getNext(line.c_str());
      if (!next) {
        printf("Invalid 3DLUT entry\n");
        return false;
      }
      *toLut++ = (icFloatNumber)atof(next);
      next = getNext(next);
      if (!next) {
        printf("Invalid 3DLUT entry\n");
        return false;
      }
      *toLut++ = (icFloatNumber)atof(next);
      n++;
    }
    return true;
  }
References getNext(), getNextLine(), isEOF(), and m_sizeLut3D.
Referenced by main().
parseHeader()
bool CubeFile::parseHeader () inline
  {
    if (!open())
      return false;
    m_title.clear();
    m_comments.clear();
    m_sizeLut3D = 0;
    m_fMinInput[0] = m_fMinInput[1] = m_fMinInput[2] = 0.0f;
    m_fMaxInput[0] = m_fMaxInput[1] = m_fMaxInput[2] = 1.0f;
    bool bAddBlankLine = false;
    while (!isEOF()) {
      long pos = ftell(m_f);
      std::string line = getNextLine();
      if (line[0] == '-' || line[0] == '.' || (line[0] >= '0' && line[0] <= '9')) {
        //undo getNextLine so it can be 3D table can be parsed
        fseek(m_f, pos, SEEK_SET);
        break;
      }
      if (!line.size()) {
        if (m_comments.size()) {
          bAddBlankLine = true;
        }
      }
      else if (line.substr(0, 6) == "TITLE ") {
        if (m_title.size()) {
          m_title += "\n";
        }
        m_title += getTitle(line.c_str() + 6);
      }
      else if (line[0] == '#') {
        if (bAddBlankLine) {
          m_comments += "\n";
        }
        if (line[1]==' ')
          m_comments += line.c_str() + 2;
        else
          m_comments += line.c_str() + 1;
        m_comments += '\n';
        bAddBlankLine = false;
      }
      else if (line.substr(0, 12) == "LUT_1D_SiZE ") {
        printf("1DLUTs are not supported\n");
        return false;
      }
      else if (line.substr(0, 12) == "LUT_3D_SIZE ") {
        m_sizeLut3D = atoi(line.c_str() + 12);
      }
      else if (line.substr(0, 19) == "LUT_3D_INPUT_RANGE ") {
        m_fMinInput[0] = m_fMinInput[1] = m_fMinInput[2] = (icFloatNumber)atof(line.c_str() + 19);
        const char* next = getNext(line.c_str() + 19);
        if (next) {
          m_fMaxInput[0] = m_fMaxInput[1] = m_fMaxInput[2] = (icFloatNumber)atof(next);
        }
      }
      else if (line.substr(0, 11) == "DOMAIN_MIN ") {
        m_fMinInput[0] = (icFloatNumber)atof(line.c_str() + 11);
        const char* next = getNext(line.c_str());
        if (next) {
          m_fMinInput[1] = (icFloatNumber)atof(next);
          next = getNext(next);
          if (next) {
            m_fMinInput[2] = (icFloatNumber)atof(next);
          }
          else
            m_fMinInput[2] = m_fMinInput[1];
        }
        else {
          m_fMinInput[1] = m_fMinInput[2] = m_fMinInput[0];
        }
      }
      else if (line.substr(0, 11) == "DOMAIN_MAX ") {
        m_fMaxInput[0] = (icFloatNumber)atof(line.c_str() + 11);
        const char* next = getNext(line.c_str());
        if (next) {
          m_fMaxInput[1] = (icFloatNumber)atof(next);
          next = getNext(next);
          if (next) {
            m_fMaxInput[2] = (icFloatNumber)atof(next);
          }
          else
            m_fMaxInput[2] = m_fMaxInput[1];
        }
        else {
          m_fMaxInput[1] = m_fMaxInput[2] = m_fMaxInput[0];
        }
      }
      else if (line.substr(0, 18) == "LUT_IN_VIDEO_RANGE")
        m_bLutInVideoRange = true;
      else if (line.substr(0, 19) == "LUT_OUT_VIDEO_RANGE")
        m_bLutOutVideoRange = true;
      else {
        printf("Unknown keyword '%s'\n", line.c_str());
        return false;
      }
    }
    return !isEOF();
  }
References getNext(), getNextLine(), getTitle(), isEOF(), m_bLutInVideoRange, m_bLutOutVideoRange, m_comments, m_f, m_fMaxInput, m_fMinInput, m_sizeLut3D, m_title, and open().
Referenced by main().
sizeLut3D()
int CubeFile::sizeLut3D () inline
{ return m_sizeLut3D; }
References m_sizeLut3D.
Referenced by main().
toEnd()
std::string CubeFile::toEnd (const char * str) inline protected
  {
    std::string rv;
    while (*str && *str != '\"') {
      rv += *str++;
    }
    return rv;
  }
Field Documentation
m_bLutInVideoRange
bool CubeFile::m_bLutInVideoRange = false protected
Referenced by parseHeader().
m_bLutOutVideoRange
bool CubeFile::m_bLutOutVideoRange = false protected
Referenced by parseHeader().
m_comments
std::string CubeFile::m_comments protected
Referenced by getCopyright(), and parseHeader().
m_f
FILE* CubeFile::m_f =nullptr protected
Referenced by close(), getNextLine(), isEOF(), open(), and parseHeader().
m_fMaxInput
icFloatNumber CubeFile::m_fMaxInput[3] = { 1.0f, 1.0f, 1.0f } protected
{ 1.0f, 1.0f, 1.0f };
Referenced by getMaxInput(), isCustomInputRange(), and parseHeader().
m_fMinInput
icFloatNumber CubeFile::m_fMinInput[3] = { 0.0f, 0.0f, 0.0f } protected
{ 0.0f, 0.0f, 0.0f };
Referenced by getMinInput(), isCustomInputRange(), and parseHeader().
m_sFilename
std::string CubeFile::m_sFilename protected
Referenced by CubeFile(), and open().
m_sizeLut3D
int CubeFile::m_sizeLut3D = 0 protected
Referenced by parse3DTable(), parseHeader(), and sizeLut3D().
m_title
std::string CubeFile::m_title protected
Referenced by getDescription(), and parseHeader().
The documentation for this class was generated from the following file:
Tools/CmdLine/IccFromCube/iccFromCube.cpp