iccDEV: CIccTagData Class Reference
CIccTagData Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagData (const CIccTagData &ITD)
CIccTagData (int nSize=1)
virtual ~CIccTagData ()
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
virtual const icChar * GetClassName () const
icUInt8Number * GetData (icUInt32Number index=0)
virtual IIccExtensionTag * GetExtension ()
icUInt32Number GetSize () const
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual bool IsTypeAscii ()
virtual bool IsTypeBinary ()
virtual bool IsTypeCompressed ()
virtual bool IsTypeUtf ()
virtual CIccTag * NewCopy () const
CIccTagData & operator= (const CIccTagData &DataTag)
icUInt8Number & operator[] (icUInt32Number index)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
virtual void SetDataType (icDataBlockType dataType=icAsciiData)
bool SetSize (icUInt32Number nSize, bool bZeroNew=true)
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
Protected Attributes
icDataBlockType m_nDataFlag
icUInt32Number m_nSize
icUInt8Number * m_pData
Detailed Description
Class: CIccTagData
Purpose: The data type tag
Constructor & Destructor Documentation
CIccTagData() [1/2]
CIccTagData::CIccTagData (int nSize = 1)
Name: CIccTagData::CIccTagData
Purpose: Constructor
Args: nSize = number of data entries
{
  m_nSize = nSize;
  if (m_nSize <1)
    m_nSize = 1;
  m_pData = (icUInt8Number*)calloc(nSize, sizeof(icUInt8Number));
}
References m_nSize, and m_pData.
CIccTagData() [2/2]
CIccTagData::CIccTagData (const CIccTagData & ITD)
Name: CIccTagData::CIccTagData
Purpose: Copy Constructor
Args: ITD = The CIccTagData object to be copied
{
  m_nDataFlag = ITD.m_nDataFlag;
  m_nSize = ITD.m_nSize;
  m_pData = (icUInt8Number*)calloc(m_nSize, sizeof(icUInt8Number));
  memcpy(m_pData, ITD.m_pData, sizeof(icUInt8Number)*m_nSize);
}
References m_nDataFlag, m_nSize, and m_pData.
Referenced by NewCopy().
~CIccTagData()
CIccTagData::~CIccTagData () virtual
Name: CIccTagData::~CIccTagData
Purpose: Destructor
{
  if (m_pData)
    free(m_pData);
}
References m_pData.
Member Function Documentation
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagData::Describe (std::string & sDescription, int nVerboseness) virtual
Name: CIccTagData::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  icChar buf[128];
  sDescription = "\n";
  if (IsTypeCompressed())
    sDescription += "Compressed ";  // If data is compressed, prepend appropriate text
  if (IsTypeAscii()) {
    sDescription = "Ascii Data:\n";
    for (int i=0; i<(int)m_nSize; i++)
      sDescription += (icChar)m_pData[i];
  }
  else if (IsTypeUtf()) {
    if (m_nSize>2 &&
        ((m_pData[0]==0xff && m_pData[1]==0xfe) ||  //UTF-16LE
         (m_pData[0]==0xfe && m_pData[1]==0xff))) { //UTF-16BE
      sprintf(buf, "UTF-16%s Data:", m_pData[0]==0xff ? "LE" : "BE" );
      sDescription = buf;
      icMemDump(sDescription, m_pData, m_nSize);
    }
    else { //UTF-8
      sDescription = "UTF-8 Data:\n";
      for (int i=0; i<(int)m_nSize; i++)
        sDescription += (icChar)m_pData[i];
    }
  }
  else {
    if (IsTypeBinary()) {
      sDescription = "Binary Data:\n";
    }
    else {
      sDescription = "Other Data:\n";
    }
    icMemDump(sDescription, m_pData, m_nSize);
  }
  sDescription += "\n";
}
References icMemDump(), IsTypeAscii(), IsTypeBinary(), IsTypeCompressed(), IsTypeUtf(), m_nSize, and m_pData.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
GetClassName()
virtual const icChar * CIccTagData::GetClassName () const inline virtual
Reimplemented from CIccTag.
Reimplemented in CIccTagXmlTagData.
{ return "CIccTagData"; }
GetData()
icUInt8Number * CIccTagData::GetData (icUInt32Number index = 0) inline
{ return &m_pData[index];}
References m_pData.
GetExtension()
virtual IIccExtensionTag * CIccTag::GetExtension () inline virtual inherited
Reimplemented in CIccTagXmlUnknown, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, CIccTagXmlSignature, CIccTagXmlNamedColor2, CIccTagXmlXYZ, CIccTagXmlChromaticity, CIccTagXmlCicp, CIccTagXmlSparseMatrixArray, CIccTagXmlFixedNum< T, Tsig >, CIccTagXmlNum< T, A, Tsig >, CIccTagXmlFloatNum< T, A, Tsig >, CIccTagXmlMeasurement, CIccTagXmlMultiLocalizedUnicode, CIccTagXmlTagData, CIccTagXmlDateTime, CIccTagXmlColorantOrder, CIccTagXmlColorantTable, CIccTagXmlViewingConditions, CIccTagXmlSpectralDataInfo, CIccTagXmlSpectralViewingConditions, CIccTagXmlProfileSeqDesc, CIccTagXmlResponseCurveSet16, CIccTagXmlCurve, CIccTagXmlParametricCurve, CIccTagXmlSegmentedCurve, CIccTagXmlLutAtoB, CIccTagXmlLutBtoA, CIccTagXmlLut8, CIccTagXmlLut16, CIccTagXmlMultiProcessElement, CIccTagXmlProfileSequenceId, CIccTagXmlDict, CIccTagXmlStruct, CIccTagXmlArray, CIccTagXmlGamutBoundaryDesc, CIccTagXmlEmbeddedHeightImage, CIccTagXmlEmbeddedNormalImage, and CIccTagXmlEmbeddedProfile.
{return NULL;}
Referenced by icCurvesFromXml(), icCurvesToXml(), icProfDescToXml(), icXmlParseProfDesc(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeXmlTintArray::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
GetSize()
icUInt32Number CIccTagData::GetSize () const inline
{ return m_nSize; }
References m_nSize.
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagData::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigDataType; }
References icSigDataType.
Referenced by Write().
IsArrayType()
virtual bool CIccTagData::IsArrayType () inline virtual
Reimplemented from CIccTag.
{ return m_nSize > 1; }
References m_nSize.
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
IsTypeAscii()
virtual bool CIccTagData::IsTypeAscii () inline virtual
{ return (m_nDataFlag&icDataTypeMask) == icAsciiData; }
References icAsciiData, and m_nDataFlag.
Referenced by Describe().
IsTypeBinary()
virtual bool CIccTagData::IsTypeBinary () inline virtual
{ return (m_nDataFlag&icDataTypeMask) == icBinaryData; }
References icBinaryData, and m_nDataFlag.
Referenced by Describe().
IsTypeCompressed()
virtual bool CIccTagData::IsTypeCompressed () inline virtual
{ return (m_nDataFlag & icCompressedData) != 0; }
References m_nDataFlag.
Referenced by Describe(), Read(), and Write().
IsTypeUtf()
virtual bool CIccTagData::IsTypeUtf () inline virtual
{ return (m_nDataFlag&icDataTypeMask) == icUtfData; }
References icUtfData, and m_nDataFlag.
Referenced by Describe().
NewCopy()
virtual CIccTag * CIccTagData::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
{return new CIccTagData(*this);}
References CIccTagData().
operator=()
CIccTagData & CIccTagData::operator= (const CIccTagData & DataTag)
Name: CIccTagData::operator=
Purpose: Copy Operator
Args: DataTag = The CIccTagData object to be copied
{
  if (&DataTag == this)
    return *this;
  m_nDataFlag = DataTag.m_nDataFlag;
  m_nSize = DataTag.m_nSize;
  if (m_pData)
    free(m_pData);
  m_pData = (icUInt8Number*)calloc(m_nSize, sizeof(icUInt8Number));
  memcpy(m_pData, DataTag.m_pData, sizeof(icUInt8Number)*m_nSize);
  return *this;
}
References m_nDataFlag, m_nSize, and m_pData.
operator[]()
icUInt8Number & CIccTagData::operator[] (icUInt32Number index) inline
{ return m_pData[index]; }
References m_pData.
Read() [1/2]
bool CIccTagData::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagData::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  if (sizeof(icTagTypeSignature) +
      sizeof(icUInt32Number) +
      sizeof(icUInt32Number) +
      sizeof(icUInt8Number) > size)
    return false;
  if (!pIO) {
    return false;
  }
  if (!pIO->Read32(&sig))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  if (!pIO->Read32(&m_nDataFlag))
    return false;
  icUInt32Number nNum = size-3*sizeof(icUInt32Number);
  if (!SetSize(nNum))
    return false;
  if (pIO->Read8(m_pData, nNum) != (icInt32Number)nNum)
    return false;
  if (IsTypeCompressed()) {
    //Uncompress data here
  }
  return true;
}
References IsTypeCompressed(), m_nDataFlag, CIccTag::m_nReserved, m_pData, CIccIO::Read32(), CIccIO::Read8(), and SetSize().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
SetDataType()
virtual void CIccTagData::SetDataType (icDataBlockType dataType = icAsciiData) inline virtual
{ m_nDataFlag = dataType; }
References m_nDataFlag.
SetSize()
bool CIccTagData::SetSize (icUInt32Number nSize, bool bZeroNew = true)
Name: CIccTagData::SetSize
Purpose: Sets the size of the data array.
Args: nSize - number of data entries, bZeroNew - flag to zero newly formed values
{
  if (m_nSize == nSize)
    return true;
  m_pData = (icUInt8Number*)icRealloc(m_pData, nSize*sizeof(icUInt8Number));
  if (!m_pData) {
    m_nSize = 0;
    return false;
  }
  if (bZeroNew && nSize > m_nSize) {
    memset(&m_pData[m_nSize], 0, (nSize-m_nSize)*sizeof(icUInt8Number));
  }
  m_nSize = nSize;
  return true;
}
References icRealloc(), m_nSize, and m_pData.
Referenced by CIccTagXmlTagData::ParseXml(), and Read().
Validate()
icValidateStatus CIccTagData::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagData::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  // Mask bits to match processing in Describe() so warnings are appropriate
  switch(m_nDataFlag&(icCompressedData|icDataTypeMask)) {
  case icAsciiData:
    for (int i = 0; i < (int)m_nSize; i++) {
      if (m_pData[i] & 0x80) {
        sReport += icMsgValidateWarning;
        sReport += sSigPathName;
        sReport += " - Ascii Data is not just 7-bit data.\n";
        rv = icMaxStatus(rv, icValidateWarning);
        break;
      }
    }
    break;
  case icBinaryData:
  case icUtfData:
  case icCompressedAsciiData:
  case icCompressedBinaryData:
  case icCompressedUtfData:
    break;
  default:
    sReport += icMsgValidateNonCompliant;
    sReport += sSigPathName;
    sReport += " - Invalid data flag encoding.\n";
    rv = icMaxStatus(rv, icValidateNonCompliant);
  }
  if (m_nDataFlag & ~(icCompressedData | icDataTypeMask)) {
      sReport += icMsgValidateNonCompliant;
      sReport += sSigPathName;
      sReport += " - Invalid data flag encoding (reserved high order bits).\n";
      rv = icMaxStatus(rv, icValidateNonCompliant);
  }
  return rv;
}
References CIccInfo::GetSigPathName(), icAsciiData, icBinaryData, icCompressedAsciiData, icCompressedBinaryData, icCompressedUtfData, icMaxStatus(), icMsgValidateNonCompliant, icMsgValidateWarning, icUtfData, icValidateNonCompliant, icValidateWarning, m_nDataFlag, m_nSize, m_pData, and CIccTag::Validate().
Write()
bool CIccTagData::Write (CIccIO * pIO) virtual
Name: CIccTagData::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  if (!pIO)
   return false;
  if (!pIO->Write32(&sig))
   return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  if (!pIO->Write32(&m_nDataFlag))
    return false;
  if (IsTypeCompressed()) {
    icUInt32Number *pData = NULL;
    icInt32Number nSize = 0;
    //Compress data here
    if (pIO->Write8(pData, nSize) != (icInt32Number)nSize)
      return false;
  }
  else {
    if (pIO->Write8(m_pData, m_nSize) != (icInt32Number)m_nSize)
      return false;
  }
  return true;
}
References GetType(), IsTypeCompressed(), m_nDataFlag, CIccTag::m_nReserved, m_nSize, m_pData, CIccIO::Write32(), and CIccIO::Write8().
Field Documentation
m_nDataFlag
icDataBlockType CIccTagData::m_nDataFlag protected
Referenced by CIccTagData(), IsTypeAscii(), IsTypeBinary(), IsTypeCompressed(), IsTypeUtf(), operator=(), CIccTagXmlTagData::ParseXml(), Read(), SetDataType(), CIccTagXmlTagData::ToXml(), Validate(), and Write().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_nSize
icUInt32Number CIccTagData::m_nSize protected
Referenced by CIccTagData(), CIccTagData(), Describe(), GetSize(), IsArrayType(), operator=(), SetSize(), CIccTagXmlTagData::ToXml(), Validate(), and Write().
m_pData
icUInt8Number* CIccTagData::m_pData protected
Referenced by CIccTagData(), CIccTagData(), ~CIccTagData(), Describe(), GetData(), operator=(), operator[](), CIccTagXmlTagData::ParseXml(), Read(), SetSize(), CIccTagXmlTagData::ToXml(), Validate(), and Write().
The documentation for this class was generated from the following files:
IccProfLib/IccTagBasic.h
IccProfLib/IccTagBasic.cpp