iccDEV: ILinkWriter Class Reference
ILinkWriter Class Reference abstract
Public Member Functions
ILinkWriter ()
virtual ~ILinkWriter ()
virtual bool begin (icColorSpaceSignature srcSpace, icColorSpaceSignature dstSpace)=0
virtual bool finish ()=0
virtual void setCmm (CIccCmm *pCmm)=0
virtual bool setFile (const char *szOutputFile)=0
virtual void setInputRange (icFloatNumber fMinInput, icFloatNumber fMaxInput)=0
virtual bool setLutSize (icUInt8Number nGridSize)=0
virtual void setNextNode (icFloatNumber *pPixel)=0
virtual void setOption (int nOptionValue)=0
virtual void setTitle (const char *szTitle)=0
Detailed Description
Constructor & Destructor Documentation
ILinkWriter()
ILinkWriter::ILinkWriter () inline
{}
~ILinkWriter()
virtual ILinkWriter::~ILinkWriter () inline virtual
{};
Member Function Documentation
begin()
virtual bool ILinkWriter::begin (icColorSpaceSignature srcSpace, icColorSpaceSignature dstSpace) pure virtual
Implemented in CCubeWriter, and CDevLinkWriter.
Referenced by main().
finish()
virtual bool ILinkWriter::finish () pure virtual
Implemented in CCubeWriter, and CDevLinkWriter.
Referenced by main().
setCmm()
virtual void ILinkWriter::setCmm (CIccCmm * pCmm) pure virtual
Implemented in CCubeWriter, and CDevLinkWriter.
Referenced by main().
setFile()
virtual bool ILinkWriter::setFile (const char * szOutputFile) pure virtual
Implemented in CCubeWriter, and CDevLinkWriter.
Referenced by main().
setInputRange()
virtual void ILinkWriter::setInputRange (icFloatNumber fMinInput, icFloatNumber fMaxInput) pure virtual
Implemented in CCubeWriter, and CDevLinkWriter.
Referenced by main().
setLutSize()
virtual bool ILinkWriter::setLutSize (icUInt8Number nGridSize) pure virtual
Implemented in CCubeWriter, and CDevLinkWriter.
Referenced by main().
setNextNode()
virtual void ILinkWriter::setNextNode (icFloatNumber * pPixel) pure virtual
Implemented in CCubeWriter, and CDevLinkWriter.
Referenced by main().
setOption()
virtual void ILinkWriter::setOption (int nOptionValue) pure virtual
Implemented in CCubeWriter, and CDevLinkWriter.
Referenced by main().
setTitle()
virtual void ILinkWriter::setTitle (const char * szTitle) pure virtual
Implemented in CCubeWriter, and CDevLinkWriter.
Referenced by main().
The documentation for this class was generated from the following file:
Tools/CmdLine/IccApplyToLink/iccApplyToLink.cpp