iccDEV: CIccTagEmbeddedProfile Class Reference
CIccTagEmbeddedProfile Class Reference
#include <IccTagEmbedIcc.h>
Public Member Functions
CIccTagEmbeddedProfile ()
CIccTagEmbeddedProfile (const CIccTagEmbeddedProfile &ITU)
virtual ~CIccTagEmbeddedProfile ()
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
virtual const icChar * GetClassName () const
virtual IIccExtensionTag * GetExtension ()
virtual CIccProfile * GetProfile () const
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
CIccTagEmbeddedProfile & operator= (const CIccTagEmbeddedProfile &UnknownTag)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
CIccProfile * m_pProfile
Detailed Description
Class: IccTagEmbeddedProfile
Purpose: This "private" tag is used to embed a profile within a profile allowing for v5 profiles to be embedded in v2/v4 profiles
Constructor & Destructor Documentation
CIccTagEmbeddedProfile() [1/2]
CIccTagEmbeddedProfile::CIccTagEmbeddedProfile ()
Name: CIccTagEmbedProfile::CIccTagEmbedProfile
Purpose: Constructor
{
  m_pProfile = NULL;
}
References m_pProfile.
CIccTagEmbeddedProfile() [2/2]
CIccTagEmbeddedProfile::CIccTagEmbeddedProfile (const CIccTagEmbeddedProfile & ITEP)
Name: CIccTagEmbedProfile::CIccTagEmbedProfile
Purpose: Copy Constructor
Args: ITU = The CIccTagEmbedProfile object to be copied
{
  if (ITEP.m_pProfile) {
    m_pProfile = ITEP.m_pProfile->NewCopy();
  }
  else
    m_pProfile = NULL;
}
References m_pProfile.
Referenced by NewCopy().
~CIccTagEmbeddedProfile()
CIccTagEmbeddedProfile::~CIccTagEmbeddedProfile () virtual
Name: CIccTagEmbedProfile::~CIccTagEmbedProfile
Purpose: Destructor
{
  if (m_pProfile)
    delete m_pProfile;
}
References m_pProfile.
Member Function Documentation
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagEmbeddedProfile::Describe (std::string & sDescription, int nVerboseness) virtual
Name: CIccTagEmbedProfile::Describe
Purpose: Dump data associated with unknown tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  if (m_pProfile) {
    sDescription += "Embedded profile in Tag\n";
    // Code below is copied from iccDumpProfile.cpp
    icHeader* pHdr = &m_pProfile->m_Header;
    CIccInfo Fmt;
    char buf[180];
    if (Fmt.IsProfileIDCalculated(&pHdr->profileID)) {
        sDescription += "Profile ID:         %s\n";
        sDescription += Fmt.GetProfileID(&pHdr->profileID);
    }
    else
        sDescription += "Profile ID:         Profile ID not calculated.\n";
    sDescription += "Size:               ";
    sprintf(buf, "%d(0x%x) bytes\n", pHdr->size, pHdr->size);
    sDescription += buf;
    sDescription += "\nHeader\n";
    sDescription += "------\n";
    sprintf(buf, "Attributes:         %s\n", Fmt.GetDeviceAttrName(pHdr->attributes));
    sDescription += buf;
    sprintf(buf, "Cmm:                %s\n", Fmt.GetCmmSigName((icCmmSignature)(pHdr->cmmId)));
    sDescription += buf;
    sprintf(buf, "Creation Date:      %d/%d/%d  %02u:%02u:%02u\n",
        pHdr->date.month, pHdr->date.day, pHdr->date.year,
        pHdr->date.hours, pHdr->date.minutes, pHdr->date.seconds);
    sDescription += buf;
    sprintf(buf, "Creator:            %s\n", icGetSig(buf, pHdr->creator));
    sDescription += buf;
    sprintf(buf, "Data Color Space:   %s\n", Fmt.GetColorSpaceSigName(pHdr->colorSpace));
    sDescription += buf;
    sprintf(buf, "Flags               %s\n", Fmt.GetProfileFlagsName(pHdr->flags));
    sDescription += buf;
    sprintf(buf, "PCS Color Space:    %s\n", Fmt.GetColorSpaceSigName(pHdr->pcs));
    sDescription += buf;
    sprintf(buf, "Platform:           %s\n", Fmt.GetPlatformSigName(pHdr->platform));
    sDescription += buf;
    sprintf(buf, "Rendering Intent:   %s\n", Fmt.GetRenderingIntentName((icRenderingIntent)(pHdr->renderingIntent)));
    sDescription += buf;
    sprintf(buf, "Profile Class:      %s\n", Fmt.GetProfileClassSigName(pHdr->deviceClass));
    sDescription += buf;
    if (pHdr->deviceSubClass) {
        sprintf(buf, "Profile SubClass:   %s\n", icGetSig(buf, pHdr->deviceSubClass));
        sDescription += buf;
    }
    else
        sDescription += "Profile SubClass:   Not Defined\n";
    sprintf(buf, "Version:            %s\n", Fmt.GetVersionName(pHdr->version));
    sDescription += buf;
    if (pHdr->version >= icVersionNumberV5 && pHdr->deviceSubClass) {
       sprintf(buf, "SubClass Version:   %s\n", Fmt.GetSubClassVersionName(pHdr->version));
       sDescription += buf;
    }
    sprintf(buf, "Illuminant:         X=%.4lf, Y=%.4lf, Z=%.4lf\n",
      icFtoD(pHdr->illuminant.X),
      icFtoD(pHdr->illuminant.Y),
      icFtoD(pHdr->illuminant.Z));
    sDescription += buf;
    sprintf(buf, "Spectral PCS:       %s\n", Fmt.GetSpectralColorSigName(pHdr->spectralPCS));
    sDescription += buf;
    if (pHdr->spectralRange.start || pHdr->spectralRange.end || pHdr->spectralRange.steps) {
      sprintf(buf, "Spectral PCS Range: start=%.1fnm, end=%.1fnm, steps=%d\n",
         icF16toF(pHdr->spectralRange.start),
         icF16toF(pHdr->spectralRange.end),
         pHdr->spectralRange.steps);
      sDescription += buf;
    }
    else {
      sDescription += "Spectral PCS Range: Not Defined\n";
    }
    if (pHdr->biSpectralRange.start || pHdr->biSpectralRange.end || pHdr->biSpectralRange.steps) {
      sprintf(buf, "BiSpectral Range:     start=%.1fnm, end=%.1fnm, steps=%d\n",
            icF16toF(pHdr->biSpectralRange.start),
            icF16toF(pHdr->biSpectralRange.end),
            pHdr->biSpectralRange.steps);
      sDescription += buf;
    }
    else {
      sDescription += "BiSpectral Range:   Not Defined\n";
    }
    if (pHdr->mcs) {
      sprintf(buf, "MCS Color Space:    %s\n", Fmt.GetColorSpaceSigName((icColorSpaceSignature)pHdr->mcs));
      sDescription += buf;
    }
    else {
      sDescription += "MCS Color Space:    Not Defined\n";
    }
    sDescription += "\nProfile Tags\n";
    sDescription += "------------\n";
    sprintf(buf, "%28s    ID    %8s\t%8s\t%8s\n", "Tag", "Offset", "Size", "Pad");
    sDescription += buf;
    sprintf(buf, "%28s  ------  %8s\t%8s\t%8s\n", "----", "------", "----", "---");
    sDescription += buf;
    int n, closest, pad;
    TagEntryList::iterator i, j;
    // n is number of Tags in Tag Table
    for (n = 0, i = m_pProfile->m_Tags->begin(); i != m_pProfile->m_Tags->end(); i++, n++) {
        // Find closest tag after this tag, by scanning all offsets of other tags
        closest = pHdr->size;
        for (j = m_pProfile->m_Tags->begin(); j != m_pProfile->m_Tags->end(); j++) {
            if ((i != j) && (j->TagInfo.offset >= i->TagInfo.offset + i->TagInfo.size) && ((int)j->TagInfo.offset <= closest)) {
                closest = j->TagInfo.offset;
            }
        }
        // Number of actual padding bytes between this tag and closest neighbour (or EOF)
        // Should be 0-3 if compliant. Negative number if tags overlap!
        pad = closest - i->TagInfo.offset - i->TagInfo.size;
        sprintf(buf, "%28s  %s  %8d\t%8d\t%8d\n", Fmt.GetTagSigName(i->TagInfo.sig),
            icGetSig(buf, i->TagInfo.sig, false), i->TagInfo.offset, i->TagInfo.size, pad);
        sDescription += buf;
    }
  }
  else {
    sDescription += "No profile embedded in Tag\n";
  }
}
References icHeader::attributes, icHeader::biSpectralRange, icHeader::cmmId, icHeader::colorSpace, icHeader::creator, icHeader::date, icDateTimeNumber::day, icHeader::deviceClass, icHeader::deviceSubClass, icSpectralRange::end, icHeader::flags, CIccInfo::GetCmmSigName(), CIccInfo::GetColorSpaceSigName(), CIccInfo::GetDeviceAttrName(), CIccInfo::GetPlatformSigName(), CIccInfo::GetProfileClassSigName(), CIccInfo::GetProfileFlagsName(), CIccInfo::GetProfileID(), CIccInfo::GetRenderingIntentName(), CIccInfo::GetSpectralColorSigName(), CIccInfo::GetSubClassVersionName(), CIccInfo::GetTagSigName(), CIccInfo::GetVersionName(), icDateTimeNumber::hours, icF16toF(), icFtoD(), icGetSig(), icHeader::illuminant, CIccInfo::IsProfileIDCalculated(), m_pProfile, icHeader::mcs, icDateTimeNumber::minutes, icDateTimeNumber::month, icTag::offset, icHeader::pcs, icHeader::platform, icHeader::profileID, icHeader::renderingIntent, icDateTimeNumber::seconds, icTag::sig, icTag::size, icHeader::size, icHeader::spectralPCS, icHeader::spectralRange, icSpectralRange::start, icSpectralRange::steps, icHeader::version, icXYZNumber::X, icXYZNumber::Y, icDateTimeNumber::year, and icXYZNumber::Z.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
GetClassName()
virtual const icChar * CIccTagEmbeddedProfile::GetClassName () const inline virtual
Reimplemented from CIccTag.
{ return "CIccTagEmbeddedProfile"; }
GetExtension()
virtual IIccExtensionTag * CIccTag::GetExtension () inline virtual inherited
Reimplemented in CIccTagXmlUnknown, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, CIccTagXmlSignature, CIccTagXmlNamedColor2, CIccTagXmlXYZ, CIccTagXmlChromaticity, CIccTagXmlCicp, CIccTagXmlSparseMatrixArray, CIccTagXmlFixedNum< T, Tsig >, CIccTagXmlNum< T, A, Tsig >, CIccTagXmlFloatNum< T, A, Tsig >, CIccTagXmlMeasurement, CIccTagXmlMultiLocalizedUnicode, CIccTagXmlTagData, CIccTagXmlDateTime, CIccTagXmlColorantOrder, CIccTagXmlColorantTable, CIccTagXmlViewingConditions, CIccTagXmlSpectralDataInfo, CIccTagXmlSpectralViewingConditions, CIccTagXmlProfileSeqDesc, CIccTagXmlResponseCurveSet16, CIccTagXmlCurve, CIccTagXmlParametricCurve, CIccTagXmlSegmentedCurve, CIccTagXmlLutAtoB, CIccTagXmlLutBtoA, CIccTagXmlLut8, CIccTagXmlLut16, CIccTagXmlMultiProcessElement, CIccTagXmlProfileSequenceId, CIccTagXmlDict, CIccTagXmlStruct, CIccTagXmlArray, CIccTagXmlGamutBoundaryDesc, CIccTagXmlEmbeddedHeightImage, CIccTagXmlEmbeddedNormalImage, and CIccTagXmlEmbeddedProfile.
{return NULL;}
Referenced by icCurvesFromXml(), icCurvesToXml(), icProfDescToXml(), icXmlParseProfDesc(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeXmlTintArray::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
GetProfile()
virtual CIccProfile * CIccTagEmbeddedProfile::GetProfile () const inline virtual
{ return m_pProfile; }
References m_pProfile.
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagEmbeddedProfile::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigEmbeddedProfileType; }
References icSigEmbeddedProfileType.
Referenced by Read(), and Write().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTagEmbeddedProfile::IsSupported () inline virtual
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented from CIccTag.
{ return true; }
NewCopy()
virtual CIccTag * CIccTagEmbeddedProfile::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
{ return new CIccTagEmbeddedProfile(*this); }
References CIccTagEmbeddedProfile().
operator=()
CIccTagEmbeddedProfile & CIccTagEmbeddedProfile::operator= (const CIccTagEmbeddedProfile & ITEP)
Name: CIccTagEmbedProfile::operator=
Purpose: Copy Operator
Args: UnknownTag = The CIccTagEmbedProfile object to be copied
{
  if (&ITEP == this)
    return *this;
  if (m_pProfile)
    delete m_pProfile;
  if (ITEP.m_pProfile)
    m_pProfile = ITEP.m_pProfile->NewCopy();
  else
    m_pProfile = NULL;
  return *this;
}
References m_pProfile.
Read() [1/2]
virtual bool CIccTagEmbeddedProfile::Read (icUInt32Number size, CIccIO * pIO) inline virtual
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented from CIccTag.
{ return Read(size, pIO, NULL); }
References Read().
Read() [2/2]
bool CIccTagEmbeddedProfile::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) virtual
Name: CIccTagEmbedProfile::Read
Purpose: Read in an unknown tag type into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from pProfile - pProfile object calling read
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  if (size<sizeof(icTagTypeSignature) || !pIO) {
    return false;
  }
  icTagTypeSignature nType;
  if (!pIO->Read32(&nType))
    return false;
  if (nType != GetType())
    return false;
  size = size - sizeof(icTagTypeSignature);
  if (size < sizeof(m_nReserved))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  size = size - sizeof(m_nReserved);
  CIccEmbedIO *pEmbedIO = new CIccEmbedIO();
  if (!pEmbedIO->Attach(pIO, size)) {
    delete pEmbedIO;
    return false;
  }
  if (m_pProfile)
    delete m_pProfile;
  m_pProfile = pProfile ? pProfile->NewProfile() : new CIccProfile();
  if (pProfile && pProfile->HasIO()) {
    if (!m_pProfile->Attach(pEmbedIO)) {
      delete pEmbedIO;
      delete m_pProfile;
      m_pProfile = NULL;
      return false;
    }
  }
  else {
    bool stat = m_pProfile->Read(pEmbedIO);
    delete pEmbedIO;
    if (!stat) {
      delete m_pProfile;
      m_pProfile = NULL;
      return false;
    }
    return stat;
  }
  return true;
}
References CIccEmbedIO::CIccEmbedIO(), CIccEmbedIO::Attach(), CIccProfile, GetType(), CIccTag::m_nReserved, m_pProfile, and CIccIO::Read32().
Referenced by Read().
ReadAll()
bool CIccTagEmbeddedProfile::ReadAll () virtual
Name: CIccTagEmbedProfile::ReadAll
Purpose: Read all tags associated with the embedded profile
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  if (!m_pProfile)
    return true;
  return m_pProfile->ReadTags(m_pProfile);
}
References m_pProfile.
Validate()
icValidateStatus CIccTagEmbeddedProfile::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagEmbedProfile::Validate
Purpose: Check tag data validity. In base class we only look at the tag's reserved data value
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  if (!m_pProfile) {
    sReport += icMsgValidateWarning;
    sReport += Info.GetSigPathName(sigPath);
    sReport += " - No Profile defined for embedded profile tag.\n";
    rv = icMaxStatus(rv, icValidateWarning);
    return rv;
  }
  rv = icMaxStatus(rv, m_pProfile->Validate(sReport, sigPath));
  if (pProfile) {
    if (m_pProfile->m_Header.colorSpace != pProfile->m_Header.colorSpace) {
      sReport += icMsgValidateCriticalError;
      sReport += Info.GetSigPathName(sigPath);
      sReport += " - color space does not match for embedded profile.\n";
      rv = icMaxStatus(rv, icValidateCriticalError);
    }
    if (m_pProfile->m_Header.deviceClass != pProfile->m_Header.deviceClass) {
      sReport += icMsgValidateCriticalError;
      sReport += Info.GetSigPathName(sigPath);
      sReport += " - device class does not match for embedded profile.\n";
      rv = icMaxStatus(rv, icValidateCriticalError);
    }
  }
  return rv;
}
References icHeader::colorSpace, icHeader::deviceClass, CIccInfo::GetSigPathName(), icMaxStatus(), icMsgValidateCriticalError, icMsgValidateWarning, icValidateCriticalError, icValidateWarning, m_pProfile, and CIccTag::Validate().
Write()
bool CIccTagEmbeddedProfile::Write (CIccIO * pIO) virtual
Name: CIccTagEmbedProfile::Write
Purpose: Write an unknown tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  if (!pIO)
    return false;
  icTagTypeSignature nType = GetType();
  if (!pIO->Write32(&nType))
    return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  if (m_pProfile) {
    CIccEmbedIO embedIO;
    if (!embedIO.Attach(pIO))
      return false;
    icProfileIDSaveMethod bWriteId = (m_pProfile->m_Header.profileID.ID32[0] ||
                                      m_pProfile->m_Header.profileID.ID32[1] ||
                                      m_pProfile->m_Header.profileID.ID32[2] ||
                                      m_pProfile->m_Header.profileID.ID32[3]) ? icAlwaysWriteID : icVersionBasedID;
    bool rv = m_pProfile->Write(&embedIO, bWriteId);
    return rv;
  }
  return true;
}
References CIccEmbedIO::Attach(), GetType(), icProfileID::ID32, CIccTag::m_nReserved, m_pProfile, icHeader::profileID, and CIccIO::Write32().
Field Documentation
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_pProfile
CIccProfile* CIccTagEmbeddedProfile::m_pProfile
Referenced by CIccTagEmbeddedProfile(), CIccTagEmbeddedProfile(), ~CIccTagEmbeddedProfile(), Describe(), GetProfile(), operator=(), CIccTagXmlEmbeddedProfile::ParseXml(), Read(), ReadAll(), CIccTagXmlEmbeddedProfile::ToXml(), Validate(), and Write().
The documentation for this class was generated from the following files:
IccProfLib/IccTagEmbedIcc.h
IccProfLib/IccTagEmbedIcc.cpp