iccDEV: CIccSegmentedCurveXml Class Reference
CIccSegmentedCurveXml Class Reference
#include <IccMpeXml.h>
Public Member Functions
virtual icFloatNumber Apply (icFloatNumber v) const
virtual bool Begin (icElemInterp nInterp, CIccTagMultiProcessElement *pMPE)
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual const icChar * GetClassName () const
virtual icCurveElemSignature GetType () const
bool Insert (CIccCurveSegment *pCurveSegment)
virtual CIccCurveSetCurve * NewCopy () const
bool ParseXml (xmlNode *pNode, std::string &parseStr)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
void Reset ()
bool ToXml (std::string &xml, std::string blanks)
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccTagMultiProcessElement *pMPE=NULL, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccCurveSetCurve * Create (icCurveElemSignature sig)
Protected Attributes
CIccCurveSegmentList * m_list
icUInt32Number m_nReserved1
icUInt32Number m_nReserved2
Detailed Description
Member Function Documentation
Apply()
icFloatNumber CIccSegmentedCurve::Apply (icFloatNumber v) const virtual inherited
Name: CIccSegmentedCurve::Apply
Purpose:
Args:
Return:
Implements CIccCurveSetCurve.
{
 CIccCurveSegmentList::iterator i;
  for (i=m_list->begin(); i!=m_list->end(); i++) {
    if (v <= (*i)->EndPoint())
      return (*i)->Apply(v);
  }
  return v;
}
References CIccCurveSegment::Apply(), CIccCurveSegment::EndPoint(), and CIccSegmentedCurve::m_list.
Referenced by CIccTagSegmentedCurve::Apply().
Begin()
bool CIccSegmentedCurve::Begin (icElemInterp nInterp, CIccTagMultiProcessElement * pMPE) virtual inherited
Name: CIccSegmentedCurve::Begin
Purpose:
Args:
Return:
Implements CIccCurveSetCurve.
{
  if (m_list->size()==0)
    return false;
 CIccCurveSegmentList::iterator i;
 CIccCurveSegment *pLast = NULL;
  for (i=m_list->begin(); i!=m_list->end(); i++) {
    if (!(*i)->Begin(pLast))
      return false;
    pLast = *i;
  }
  return true;
}
References CIccCurveSegment::Begin(), and CIccSegmentedCurve::m_list.
Referenced by CIccTagSegmentedCurve::Begin().
Create()
CIccCurveSetCurve * CIccCurveSetCurve::Create (icCurveElemSignature sig) static inherited
Name: CIccCurveSetCurve::Create
Purpose:
Args:
Return:
{
  switch (sig) {
  case icSigSegmentedCurve:
    return new CIccSegmentedCurve();
  case icSigSingleSampledCurve:
    return new CIccSingleSampledCurve();
  case icSigSampledCalculatorCurve:
    return new CIccSampledCalculatorCurve();
  default:
    return NULL;
  }
}
References CIccSampledCalculatorCurve::CIccSampledCalculatorCurve(), CIccSegmentedCurve::CIccSegmentedCurve(), CIccSingleSampledCurve::CIccSingleSampledCurve(), icSigSampledCalculatorCurve, icSigSegmentedCurve, and icSigSingleSampledCurve.
Referenced by CIccMpeCurveSet::Read(), and CIccMpeToneMap::Read().
Describe()
void CIccSegmentedCurve::Describe (std::string & sDescription, int nVerboseness) virtual inherited
Name: CIccSegmentedCurve::Describe
Purpose:
Args:
Return:
Implements CIccCurveSetCurve.
{
  CIccCurveSegmentList::iterator i;
  sDescription += "BEGIN_CURVE\n";
  for (i=m_list->begin(); i!=m_list->end(); i++) {
    (*i)->Describe(sDescription, nVerboseness);
  }
}
References CIccCurveSegment::Describe(), and CIccSegmentedCurve::m_list.
Referenced by CIccTagSegmentedCurve::Describe().
GetClassName()
virtual const icChar * CIccSegmentedCurve::GetClassName () const inline virtual inherited
Implements CIccCurveSetCurve.
{ return "CIccSegmentedCurve"; }
GetType()
virtual icCurveElemSignature CIccSegmentedCurve::GetType () const inline virtual inherited
Implements CIccCurveSetCurve.
{ return icSigSegmentedCurve; }
References icSigSegmentedCurve.
Referenced by CIccSegmentedCurve::Read(), CIccSegmentedCurve::Validate(), and CIccSegmentedCurve::Write().
Insert()
bool CIccSegmentedCurve::Insert (CIccCurveSegment * pCurveSegment) inherited
Name: CIccSegmentedCurve::Insert
Purpose:
Args:
Return:
{
  CIccCurveSegmentList::reverse_iterator last = m_list->rbegin();
  if (last!=m_list->rend()) {
    if (pCurveSegment->StartPoint() == (*last)->EndPoint()) {
      m_list->push_back(pCurveSegment);
      return true;
    }
  }
  else {
    m_list->push_back(pCurveSegment);
    return true;
  }
  return false;
}
References CIccCurveSegment::EndPoint(), CIccSegmentedCurve::m_list, and CIccCurveSegment::StartPoint().
NewCopy()
virtual CIccCurveSetCurve * CIccSegmentedCurve::NewCopy () const inline virtual inherited
Implements CIccCurveSetCurve.
{ return new CIccSegmentedCurve(*this);}
References CIccSegmentedCurve::CIccSegmentedCurve().
Referenced by CIccTagSegmentedCurve::CIccTagSegmentedCurve(), CIccDefaultEncProfileConverter::ConvertFromParams(), and CIccTagSegmentedCurve::operator=().
ParseXml()
bool CIccSegmentedCurveXml::ParseXml (xmlNode * pNode, std::string & parseStr)
{
  m_list->clear();
  for (pNode=pNode->children; pNode; pNode=pNode->next) {
    if (pNode->type == XML_ELEMENT_NODE) {
      icFloatNumber start = icGetSegPos(icXmlAttrValue(pNode, "Start"));
      icFloatNumber end = icGetSegPos(icXmlAttrValue(pNode, "End"));
      if (!icXmlStrCmp(pNode->name, "FormulaSegment")) {
        CIccFormulaCurveSegmentXml *pSegXml = new CIccFormulaCurveSegmentXml(start, end);
        if (!pSegXml->ParseXml(pNode, parseStr)) {
          parseStr += "Unable to parse FormulaSegment\n";
          delete pSegXml;
          return false;
        }
        m_list->push_back(pSegXml);
      }
      else if (!icXmlStrCmp(pNode->name, "SampledSegment")) {
        CIccSampledCurveSegmentXml *pSegXml = new CIccSampledCurveSegmentXml(start, end);
        if (!pSegXml->ParseXml(pNode, parseStr)) {
          parseStr += "Unable to parse SampledSegment\n";
          delete pSegXml;
          return false;
        }
        m_list->push_back(pSegXml);
      }
      else {
        parseStr += "Bad Segment Type\n";
        return false;
      }
    }
  }
  return true;
}
References CIccFormulaCurveSegmentXml::CIccFormulaCurveSegmentXml(), CIccSampledCurveSegmentXml::CIccSampledCurveSegmentXml(), icGetSegPos(), icXmlAttrValue(), CIccSegmentedCurve::m_list, CIccFormulaCurveSegmentXml::ParseXml(), and CIccSampledCurveSegmentXml::ParseXml().
Referenced by CIccTagXmlSegmentedCurve::ParseXml(), and ParseXmlCurve().
Read()
bool CIccSegmentedCurve::Read (icUInt32Number size, CIccIO * pIO) virtual inherited
Name: CIccSegmentedCurve::Read
Purpose:
Args:
Return:
Implements CIccCurveSetCurve.
{
  icCurveElemSignature sig;
  icUInt32Number startPos = pIO->Tell();
  icUInt32Number headerSize = sizeof(icCurveElemSignature) +
    sizeof(icUInt32Number) +
    sizeof(icUInt16Number) +
    sizeof(icUInt16Number);
  if (headerSize > size)
    return false;
  if (!pIO) {
    return false;
  }
  if (!pIO->Read32(&sig))
    return false;
  if (sig!=GetType())
    return false;
  if (!pIO->Read32(&m_nReserved1))
    return false;
  icUInt16Number nSegments;
  if (!pIO->Read16(&nSegments))
    return false;
  if (!pIO->Read16(&m_nReserved2))
    return false;
  Reset();
  icUInt32Number pos = pIO->Tell();
  icCurveSegSignature segSig;
  CIccCurveSegment *pSeg;
  if (nSegments==1) {
    if (sizeof(segSig) > size - headerSize)
      return false;
    if (!pIO->Read32(&segSig))
      return false;
    pSeg = CIccCurveSegment::Create(segSig, icMinFloat32Number, icMaxFloat32Number);
    if (!pSeg)
      return false;
    pIO->Seek(pos, icSeekSet);
    if (!pSeg->Read(size-(pos-startPos), pIO)) {
      delete pSeg;
      return false;
    }
    m_list->push_back(pSeg);
  }
  else if (nSegments) {
    if (nSegments > size - headerSize)
      return false;
    icFloatNumber *breakpoints=(icFloatNumber*)calloc(nSegments-1, sizeof(icFloatNumber));
    if (!breakpoints)
      return false;
    if (pIO->ReadFloat32Float(breakpoints, nSegments-1)!=nSegments-1) {
      free(breakpoints);
      return false;
    }
    int i;
    for (i=0; i<nSegments; i++) {
      pos = pIO->Tell();
      if (!pIO->Read32(&segSig)) {
        free(breakpoints);
        return false;
      }
      if (pIO->Seek(pos, icSeekSet)!=(icInt32Number)pos)
        return false;;
      if (!i)
        pSeg = CIccCurveSegment::Create(segSig, icMinFloat32Number, breakpoints[i]);
      else if (i==nSegments-1)
        pSeg = CIccCurveSegment::Create(segSig, breakpoints[i-1], icMaxFloat32Number);
      else
        pSeg = CIccCurveSegment::Create(segSig, breakpoints[i-1], breakpoints[i]);
      if (!pSeg) {
        free(breakpoints);
        return false;
      }
      if (!pSeg->Read(size-(pos-startPos), pIO)) {
        delete pSeg;
        free(breakpoints);
        return false;
      }
      m_list->push_back(pSeg);
    }
    free(breakpoints);
  }
  return true;
}
References CIccCurveSegment::Create(), CIccSegmentedCurve::GetType(), icSeekSet, CIccSegmentedCurve::m_list, CIccSegmentedCurve::m_nReserved1, CIccSegmentedCurve::m_nReserved2, CIccCurveSegment::Read(), CIccIO::Read16(), CIccIO::Read32(), CIccIO::ReadFloat32Float(), CIccSegmentedCurve::Reset(), CIccIO::Seek(), and CIccIO::Tell().
Referenced by CIccTagSegmentedCurve::Read().
Reset()
void CIccSegmentedCurve::Reset () inherited
Name: CIccSegmentedCurve::Reset
Purpose:
Args:
Return:
{
  CIccCurveSegmentList::iterator i;
  for (i=m_list->begin(); i!=m_list->end(); i++) {
    delete (*i);
  }
  m_list->clear();
}
References CIccSegmentedCurve::m_list.
Referenced by CIccSegmentedCurve::~CIccSegmentedCurve(), CIccSegmentedCurve::operator=(), and CIccSegmentedCurve::Read().
ToXml()
bool CIccSegmentedCurveXml::ToXml (std::string & xml, std::string blanks)
{
  CIccCurveSegmentList::iterator seg;
  xml += blanks + "<SegmentedCurve>\n";
  for (seg = m_list->begin(); seg!=m_list->end(); seg++) {
    CIccCurveSegment* pSeg = *seg;
    if (pSeg && pSeg->GetType() == icSigFormulaCurveSeg) {
      if (!((CIccFormulaCurveSegmentXml*)pSeg)->ToXml(xml, blanks+"  "))
        return false;
    }
    else if (pSeg && pSeg->GetType() == icSigSampledCurveSeg) {
      if (!((CIccSampledCurveSegmentXml*)pSeg)->ToXml(xml, blanks+"  "))
        return false;
    }
    else
      return false;
  }
  xml += blanks + "</SegmentedCurve>\n";
  return true;
}
References CIccCurveSegment::GetType(), icSigFormulaCurveSeg, icSigSampledCurveSeg, CIccSegmentedCurve::m_list, CIccFormulaCurveSegmentXml::ToXml(), and CIccSampledCurveSegmentXml::ToXml().
Referenced by CIccTagXmlSegmentedCurve::ToXml(), and ToXmlCurve().
Validate()
icValidateStatus CIccSegmentedCurve::Validate (std::string sigPath, std::string & sReport, const CIccTagMultiProcessElement * pMPE = NULL, const CIccProfile * pProfile = NULL) const virtual inherited
Name: CIccSegmentedCurve::Validate
Purpose:
Args:
Return:
Implements CIccCurveSetCurve.
{
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  icValidateStatus rv = icValidateOK;
  if (m_nReserved1 || m_nReserved2) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " Segmented curve has non zero reserved data.\n";
    rv = icValidateWarning;
  }
  if (m_list->size()==0) {
    sReport += icMsgValidateCriticalError;
    sReport += sSigPathName;
    sReport += " Has Empty CurveSegment!\n";
    return icMaxStatus(rv, icValidateCriticalError);
  }
  CIccCurveSegmentList::iterator i;
  for (i=m_list->begin(); i!=m_list->end(); i++) {
    rv = icMaxStatus(rv, (*i)->Validate(sigPath+icGetSigPath(GetType()), sReport, pMPE, pProfile));
  }
  return rv;
}
References CIccInfo::GetSigPathName(), CIccSegmentedCurve::GetType(), icGetSigPath(), icMaxStatus(), icMsgValidateCriticalError, icMsgValidateWarning, icValidateCriticalError, icValidateOK, icValidateWarning, CIccSegmentedCurve::m_list, CIccSegmentedCurve::m_nReserved1, CIccSegmentedCurve::m_nReserved2, and CIccCurveSegment::Validate().
Referenced by CIccTagSegmentedCurve::Validate().
Write()
bool CIccSegmentedCurve::Write (CIccIO * pIO) virtual inherited
Name: CIccSegmentedCurve::Write
Purpose:
Args:
Return:
Implements CIccCurveSetCurve.
{
  icCurveElemSignature sig = GetType();
  if (!pIO)
    return false;
  if (!pIO->Write32(&sig))
    return false;
  if (!pIO->Write32(&m_nReserved1))
    return false;
  icUInt16Number nSegments = (icUInt16Number)m_list->size();
  if (!pIO->Write16(&nSegments))
    return false;
  if (!pIO->Write16(&m_nReserved2))
    return false;
  CIccCurveSegmentList::iterator i;
  if (nSegments>1) {
    icFloatNumber breakpoint;
    i=m_list->begin();
    for (i++; i!=m_list->end(); i++) {
      breakpoint = (*i)->StartPoint();
      if (!pIO->WriteFloat32Float(&breakpoint))
        return false;
    }
  }
  for (i=m_list->begin(); i!=m_list->end(); i++) {
    if (!(*i)->Write(pIO))
      return false;
  }
  return true;
}
References CIccSegmentedCurve::GetType(), CIccSegmentedCurve::m_list, CIccSegmentedCurve::m_nReserved1, CIccSegmentedCurve::m_nReserved2, CIccCurveSegment::StartPoint(), CIccCurveSegment::Write(), CIccIO::Write16(), CIccIO::Write32(), and CIccIO::WriteFloat32Float().
Referenced by CIccTagSegmentedCurve::Write().
Field Documentation
m_list
CIccCurveSegmentList* CIccSegmentedCurve::m_list protected inherited
Referenced by CIccSegmentedCurve::CIccSegmentedCurve(), CIccSegmentedCurve::CIccSegmentedCurve(), CIccSegmentedCurve::~CIccSegmentedCurve(), CIccSegmentedCurve::Apply(), CIccSegmentedCurve::Begin(), CIccSegmentedCurve::Describe(), CIccSegmentedCurve::Insert(), CIccSegmentedCurve::operator=(), ParseXml(), CIccSegmentedCurve::Read(), CIccSegmentedCurve::Reset(), ToXml(), CIccSegmentedCurve::Validate(), and CIccSegmentedCurve::Write().
m_nReserved1
icUInt32Number CIccSegmentedCurve::m_nReserved1 protected inherited
Referenced by CIccSegmentedCurve::CIccSegmentedCurve(), CIccSegmentedCurve::CIccSegmentedCurve(), CIccSegmentedCurve::operator=(), CIccSegmentedCurve::Read(), CIccSegmentedCurve::Validate(), and CIccSegmentedCurve::Write().
m_nReserved2
icUInt32Number CIccSegmentedCurve::m_nReserved2 protected inherited
Referenced by CIccSegmentedCurve::CIccSegmentedCurve(), CIccSegmentedCurve::CIccSegmentedCurve(), CIccSegmentedCurve::operator=(), CIccSegmentedCurve::Read(), CIccSegmentedCurve::Validate(), and CIccSegmentedCurve::Write().
The documentation for this class was generated from the following files:
IccXML/IccLibXML/IccMpeXml.h
IccXML/IccLibXML/IccMpeXml.cpp