iccDEV: CIccInfo Class Reference
CIccInfo Class Reference
#include <IccUtil.h>
Public Member Functions
CIccInfo ()
virtual ~CIccInfo ()
icValidateStatus CheckData (std::string &sReport, const icDateTimeNumber &dateTime, std::string sDesc="")
icValidateStatus CheckData (std::string &sReport, const icFloatXYZNumber &XYZ, std::string sDesc="")
icValidateStatus CheckData (std::string &sReport, const icSpectralRange &range, std::string sDesc="")
icValidateStatus CheckData (std::string &sReport, const icXYZNumber &XYZ, std::string sDesc="")
icValidateStatus CheckLuminance (std::string &sReport, const icFloatXYZNumber &XYZ, std::string sDesc="")
const icChar * GetArraySigName (icArraySignature sig)
const icChar * GetCmmSigName (icCmmSignature sig)
const icChar * GetColorantEncoding (icColorantEncoding colorant)
const icChar * GetColorimetricIntentImageStateName (icColorimetricIntentImageStateSignature sig)
const icChar * GetColorSpaceSigName (icColorSpaceSignature sig)
const icChar * GetDeviceAttrName (icUInt64Number val)
const icChar * GetElementTypeSigName (icElemTypeSignature sig)
const icChar * GetIlluminantName (icIlluminant val)
const icChar * GetMeasurementFlareName (icMeasurementFlare val)
const icChar * GetMeasurementGeometryName (icMeasurementGeometry val)
const icChar * GetMeasurementUnit (icSignature sig)
const icChar * GetPathEntrySigName (icUInt32Number val)
const icChar * GetPlatformSigName (icPlatformSignature sig)
const icChar * GetProfileClassSigName (icProfileClassSignature sig)
const icChar * GetProfileFlagsName (icUInt32Number val, bool bCheckMCS=false)
const icChar * GetProfileID (icProfileID *profileID)
const icChar * GetReferenceMediumGamutSigNameName (icReferenceMediumGamutSignature sig)
const icChar * GetRenderingIntentName (icRenderingIntent val, bool bIsV5=false)
const icChar * GetSigName (icUInt32Number val)
std::string GetSigPathName (std::string sigPath)
const icChar * GetSpectralColorSigName (icSpectralColorSignature sig)
const icChar * GetSpotShapeName (icSpotShape val)
const icChar * GetStandardObserverName (icStandardObserver val)
const icChar * GetStructSigName (icStructSignature sig)
const icChar * GetSubClassVersionName (icUInt32Number val)
const icChar * GetTagSigName (icTagSignature sig)
const icChar * GetTagTypeSigName (icTagTypeSignature sig)
const icChar * GetTechnologySigName (icTechnologySignature sig)
const icChar * GetUnknownName (icUInt32Number val)
const icChar * GetVersionName (icUInt32Number val)
bool IsProfileIDCalculated (icProfileID *profileID)
bool IsValidSpace (icColorSpaceSignature sig)
bool IsValidSpectralSpace (icColorSpaceSignature sig)
Protected Attributes
std::string * m_str
icChar m_szSigStr [128]
icChar m_szStr [128]
Detailed Description
Type: Class
Purpose: This is a utility class which can be used to get profile info for printing. The member functions are used to convert signatures and other enum values to character strings for printing.
Constructor & Destructor Documentation
CIccInfo()
CIccInfo::CIccInfo ()
                   : m_szStr{}, m_szSigStr{}
{
  m_str = new std::string;
}
References m_szStr.
~CIccInfo()
CIccInfo::~CIccInfo () virtual
{
  delete m_str;
}
References m_str.
Member Function Documentation
CheckData() [1/4]
icValidateStatus CIccInfo::CheckData (std::string & sReport, const icDateTimeNumber & dateTime, std::string sDesc = "")
{
  icValidateStatus rv = icValidateOK;
  struct tm *newtime;
  time_t long_time;
  time( &long_time );                /* Get time as long integer. */
  newtime = localtime( &long_time );
  icChar buf[128];
  if (dateTime.year<1992) {
    sReport += icMsgValidateWarning;
    sReport += sDesc;
    sprintf(buf," - %u: Invalid year!\n",dateTime.year);
    sReport += buf;
    rv = icValidateWarning;
  }
  int year = newtime->tm_year+1900;
  if (newtime->tm_mon==11 && newtime->tm_mday==31) {
    if (dateTime.year>(year+1)) {
      sReport += icMsgValidateWarning;
      sReport += sDesc;
      sprintf(buf," - %u: Invalid year!\n",dateTime.year);
      sReport += buf;
      rv = icMaxStatus(rv, icValidateWarning);
    }
  }
  else {
    if (dateTime.year>year) {
      sReport += icMsgValidateWarning;
      sReport += sDesc;
      sprintf(buf," - %u: Invalid year!\n",dateTime.year);
      sReport += buf;
      rv = icMaxStatus(rv, icValidateWarning);
    }
  }
  if (dateTime.month<1 || dateTime.month>12) {
    sReport += icMsgValidateWarning;
    sReport += sDesc;
    sprintf(buf," - %u: Invalid month!\n",dateTime.month);
    sReport += buf;
    rv = icMaxStatus(rv, icValidateWarning);
  }
  if (dateTime.day<1 || dateTime.day>31) {
    sReport += icMsgValidateWarning;
    sReport += sDesc;
    sprintf(buf," - %u: Invalid day!\n",dateTime.day);
    sReport += buf;
    rv = icMaxStatus(rv, icValidateWarning);
  }
  if (dateTime.month==2) {
    if (dateTime.day>29) {
      sReport += icMsgValidateWarning;
      sReport += sDesc;
      sprintf(buf," - %u: Invalid day for February!\n",dateTime.day);
      sReport += buf;
      rv = icMaxStatus(rv, icValidateWarning);
    }
    if (dateTime.day==29) {
      if ((dateTime.year%4)!=0) {
        sReport += icMsgValidateWarning;
        sReport += sDesc;
        sprintf(buf," - %u: Invalid day for February, year is not a leap year(%u)!\n",dateTime.day, dateTime.year);
        sReport += buf;
        rv = icMaxStatus(rv, icValidateWarning);
      }
    }
  }
  if (dateTime.hours>23) {
    sReport += icMsgValidateWarning;
    sReport += sDesc;
    sprintf(buf," - %u: Invalid hour!\n",dateTime.hours);
    sReport += buf;
    rv = icMaxStatus(rv, icValidateWarning);
  }
  if (dateTime.minutes>59) {
    sReport += icMsgValidateWarning;
    sReport += sDesc;
    sprintf(buf," - %u: Invalid minutes!\n",dateTime.minutes);
    sReport += buf;
    rv = icMaxStatus(rv, icValidateWarning);
  }
  if (dateTime.seconds>59) {
    sReport += icMsgValidateWarning;
    sReport += sDesc;
    sprintf(buf," - %u: Invalid seconds!\n",dateTime.hours);
    sReport += buf;
    rv = icMaxStatus(rv, icValidateWarning);
  }
  return rv;
}
References icDateTimeNumber::day, icDateTimeNumber::hours, icMaxStatus(), icMsgValidateWarning, icValidateOK, icValidateWarning, icDateTimeNumber::minutes, icDateTimeNumber::month, icDateTimeNumber::seconds, and icDateTimeNumber::year.
Referenced by CIccTagDateTime::Validate().
CheckData() [2/4]
icValidateStatus CIccInfo::CheckData (std::string & sReport, const icFloatXYZNumber & XYZ, std::string sDesc = "")
{
  icValidateStatus rv = icValidateOK;
  if (XYZ.X < 0) {
    sReport += icMsgValidateNonCompliant;
    sReport += sDesc;
    sReport += " - FloatXYZNumber: Negative X value!\n";
    rv = icValidateNonCompliant;
  }
  if (XYZ.Y < 0) {
    sReport += icMsgValidateNonCompliant;
    sReport += sDesc;
    sReport += " - FloatXYZNumber: Negative Y value!\n";
    rv = icMaxStatus(rv, icValidateNonCompliant);
  }
  if (XYZ.Z < 0) {
    sReport += icMsgValidateNonCompliant;
    sReport += sDesc;
    sReport += " - FloatXYZNumber: Negative Z value!\n";
    rv = icMaxStatus(rv, icValidateNonCompliant);
  }
  return rv;
}
References icMaxStatus(), icMsgValidateNonCompliant, icValidateNonCompliant, icValidateOK, icFloatXYZNumber::X, icFloatXYZNumber::Y, and icFloatXYZNumber::Z.
Referenced by CIccTagSpectralViewingConditions::Validate().
CheckData() [3/4]
icValidateStatus CIccInfo::CheckData (std::string & sReport, const icSpectralRange & range, std::string sDesc = "")
{
  icValidateStatus rv = icValidateOK;
  if (icF16toF(range.end)<=icF16toF(range.start)) {
    sReport += icMsgValidateNonCompliant;
    sReport += sDesc;
    sReport += " - spectralRange: end wavelength must be greater than start wavelength!\n";
    rv = icValidateNonCompliant;
  }
  if (range.steps<2) {
    sReport += icMsgValidateNonCompliant;
    sReport += sDesc;
    sReport += " - spectralRange: wavelength range must have at least two steps!\n";
    rv = icMaxStatus(rv, icValidateNonCompliant);
  }
  return rv;
}
References icSpectralRange::end, icF16toF(), icMaxStatus(), icMsgValidateNonCompliant, icValidateNonCompliant, icValidateOK, icSpectralRange::start, and icSpectralRange::steps.
Referenced by CIccTagSpectralDataInfo::Validate(), and CIccTagSpectralViewingConditions::Validate().
CheckData() [4/4]
icValidateStatus CIccInfo::CheckData (std::string & sReport, const icXYZNumber & XYZ, std::string sDesc = "")
{
  icValidateStatus rv = icValidateOK;
  if (XYZ.X < 0) {
    sReport += icMsgValidateNonCompliant;
    sReport += sDesc;
    sReport += " - XYZNumber: Negative X value!\n";
    rv = icValidateNonCompliant;
  }
  if (XYZ.Y < 0) {
    sReport += icMsgValidateNonCompliant;
    sReport += sDesc;
    sReport += " - XYZNumber: Negative Y value!\n";
    rv = icMaxStatus(rv, icValidateNonCompliant);
  }
  if (XYZ.Z < 0) {
    sReport += icMsgValidateNonCompliant;
    sReport += sDesc;
    sReport += " - XYZNumber: Negative Z value!\n";
    rv = icMaxStatus(rv, icValidateNonCompliant);
  }
  return rv;
}
References icMaxStatus(), icMsgValidateNonCompliant, icValidateNonCompliant, icValidateOK, icXYZNumber::X, icXYZNumber::Y, and icXYZNumber::Z.
Referenced by CIccResponseCurveStruct::Validate(), CIccTagXYZ::Validate(), and CIccTagViewingConditions::Validate().
CheckLuminance()
icValidateStatus CIccInfo::CheckLuminance (std::string & sReport, const icFloatXYZNumber & XYZ, std::string sDesc = "")
{
  icValidateStatus rv = icValidateOK;
  if (fabs(XYZ.Y - 1.0) < 0.01) {
    sReport += icMsgValidateWarning;
    sReport += sDesc;
    sReport += " - XYZNumber appears to be normalized! Y value should reflect absolute luminance.\n";
    rv = icValidateWarning;
  }
  return rv;
}
References icMsgValidateWarning, icValidateOK, icValidateWarning, and icFloatXYZNumber::Y.
Referenced by CIccTagSpectralViewingConditions::Validate().
GetArraySigName()
const icChar * CIccInfo::GetArraySigName (icArraySignature sig)
{
  if (CIccArrayCreator::GetArraySigName(*m_str, sig)) {
    return m_str->c_str();
  }
  return GetUnknownName(sig);
}
References CIccArrayCreator::GetArraySigName(), GetUnknownName(), and m_str.
GetCmmSigName()
const icChar * CIccInfo::GetCmmSigName (icCmmSignature sig)
{
  switch (sig) {
  case icSigAdobe:
    return "Adobe";
  case icSigAgfa:
    return "Agfa";
  case icSigApple:
    return "Apple";
  case icSigColorGear:
    return "ColorGear";
  case icSigColorGearLite:
    return "ColorGear Lite";
  case icSigColorGearC:
    return "ColorGear C";
  case icSigEFI:
    return "EFI";
  case icSigExactScan:
    return "ExactScan";
  case icSigFujiFilm:
    return "Fuji Film";
  case icSigHarlequinRIP:
    return "Harlequin RIP";
  case icSigArgyllCMS:
    return "Argyll CMS";
  case icSigLogoSync:
    return "LogoSync";
  case icSigHeidelberg:
    return "Heidelberg";
  case icSigLittleCMS:
    return "Little CMS";
  case icSigKodak:
    return "Kodak";
  case icSigKonicaMinolta:
    return "Konica Minolta";
  case icSigMutoh:
    return "Mutoh";
  case icSigRefIccMAX:
    return "RefIccMAX";
  case icSigDemoIccMAX:
    return "DemoIccMAX";
  case icSigRolfGierling:
    return "Rolf Gierling Multitools";
  case icSigSampleICC:
    return "SampleIcc";
  case icSigToshiba:
    return "Toshiba";
  case icSigTheImagingFactory:
    return "the imaging factory";
  case icSigVivo:
    return "Vivo";
  case icSigWareToGo:
    return "Ware To Go";
  case icSigMicrosoft:
    return "Windows Color System";
  case icSigZoran:
    return "Zoran";
  default:
    return GetUnknownName(sig);
  }
}
References GetUnknownName(), icSigAdobe, icSigAgfa, icSigApple, icSigArgyllCMS, icSigColorGear, icSigColorGearC, icSigColorGearLite, icSigDemoIccMAX, icSigEFI, icSigExactScan, icSigFujiFilm, icSigHarlequinRIP, icSigHeidelberg, icSigKodak, icSigKonicaMinolta, icSigLittleCMS, icSigLogoSync, icSigMicrosoft, icSigMutoh, icSigRefIccMAX, icSigRolfGierling, icSigSampleICC, icSigTheImagingFactory, icSigToshiba, icSigVivo, icSigWareToGo, and icSigZoran.
Referenced by CIccTagEmbeddedProfile::Describe(), and main().
GetColorantEncoding()
const icChar * CIccInfo::GetColorantEncoding (icColorantEncoding colorant)
{
  switch(colorant) {
    case icColorantITU:
      return "ITU-R BT.709";
    case icColorantSMPTE:
      return "SMPTE RP145-1994";
    case icColorantEBU:
      return "EBU Tech.3213-E";
    case icColorantP22:
      return "P22";
    default:
      return "Customized Encoding";
  }
}
References icColorantEBU, icColorantITU, icColorantP22, and icColorantSMPTE.
Referenced by CIccTagChromaticity::Describe(), and CIccTagXmlChromaticity::ToXml().
GetColorimetricIntentImageStateName()
const icChar * CIccInfo::GetColorimetricIntentImageStateName (icColorimetricIntentImageStateSignature sig)
{
  switch (sig) {
  case icSigSceneColorimetryEstimates:
    return "Scene Colorimetry Estimates";
  case icSigSceneAppearanceEstimates:
    return "Scene Appearance Estimates";
  case icSigFocalPlaneColorimetryEstimates:
    return "Focal Plane Colorimetry Estimates";
  case icSigReflectionHardcopyOriginalColorimetry:
    return "Reflection Hardcopy Original Colorimetry";
  case icSigReflectionPrintOutputColorimetry:
    return "Reflection Print Output Colorimetry";
  default:
    return GetUnknownName(sig);
  }
}
References GetUnknownName(), icSigFocalPlaneColorimetryEstimates, icSigReflectionHardcopyOriginalColorimetry, icSigReflectionPrintOutputColorimetry, icSigSceneAppearanceEstimates, and icSigSceneColorimetryEstimates.
Referenced by GetSigName().
GetColorSpaceSigName()
const icChar * CIccInfo::GetColorSpaceSigName (icColorSpaceSignature sig)
{
  switch (sig) {
  case icSigNoColorData:
    return "NoData";
  case icSigXYZData:
  case icSigDevXYZData:
    return "XYZData";
  case icSigLabData:
  case icSigDevLabData:
    return "LabData";
  case icSigLuvData:
    return "LuvData";
  case icSigYCbCrData:
    return "YCbCrData";
  case icSigYxyData:
    return "YxyData";
  case icSigRgbData:
    return "RgbData";
  case icSigGrayData:
    return "GrayData";
  case icSigHsvData:
    return "HsvData";
  case icSigHlsData:
    return "HlsData";
  case icSigCmykData:
    return "CmykData";
  case icSigCmyData:
    return "CmyData";
  case icSigMCH1Data:
    return "MCH1Data/1ColorData";
  case icSigMCH2Data:
    return "MCH2Data/2ColorData";
  case icSigMCH3Data:
    return "MCH3Data/3ColorData";
  case icSigMCH4Data:
    return "MCH4Data/4ColorData";
  case icSigMCH5Data:
    return "MCH5Data/5ColorData";
  case icSigMCH6Data:
    return "MCH6Data/6ColorData";
  case icSigMCH7Data:
    return "MCH7Data/7ColorData";
  case icSigMCH8Data:
    return "MCH8Data/8ColorData";
  case icSigMCH9Data:
    return "MCH9Data/9ColorData";
  case icSigMCHAData:
    return "MCHAData/10ColorData";
  case icSigMCHBData:
    return "MCHBData/11ColorData";
  case icSigMCHCData:
    return "MCHCData/12ColorData";
  case icSigMCHDData:
    return "MCHDData/13ColorData";
  case icSigMCHEData:
    return "MCHEData/14ColorData";
  case icSigMCHFData:
    return "MCHFData/15ColorData";
  case icSigGamutData:
    return "GamutData";
  case icSigNamedData:
    return "NamedData";
  default:
    switch(icGetColorSpaceType(sig)) {
    case icSigNChannelData:
      sprintf(m_szStr, "0x%04XChannelData", icNumColorSpaceChannels(sig));
      return m_szStr;
    case icSigReflectanceSpectralData:
      sprintf(m_szStr, "0x%04XChannelReflectanceData", icNumColorSpaceChannels(sig));
      return m_szStr;
    case icSigTransmisionSpectralData:
      sprintf(m_szStr, "0x%04XChannelTransmissionData", icNumColorSpaceChannels(sig));
      return m_szStr;
    case icSigRadiantSpectralData:
      sprintf(m_szStr, "0x%04XChannelRadiantData", icNumColorSpaceChannels(sig));
      return m_szStr;
    case icSigBiSpectralReflectanceData:
      sprintf(m_szStr, "0x%04XChannelBiDirReflectanceData", icNumColorSpaceChannels(sig));
      return m_szStr;
    case icSigSparseMatrixReflectanceData:
      sprintf(m_szStr, "0x%04XChannelSparseMatrixReflectanceData", icNumColorSpaceChannels(sig));
      return m_szStr;
    default:
      icUInt32Number nChan = icGetSpaceSamples(sig);
      if (nChan>0) {
        sprintf(m_szStr, "0x%XColorData", nChan);
        return m_szStr;
      }
      return GetUnknownName(sig);
    }
  }
}
References GetUnknownName(), icGetSpaceSamples(), icSigBiSpectralReflectanceData, icSigCmyData, icSigCmykData, icSigGrayData, icSigHlsData, icSigHsvData, icSigLabData, icSigLuvData, icSigMCH1Data, icSigMCH2Data, icSigMCH3Data, icSigMCH4Data, icSigMCH5Data, icSigMCH6Data, icSigMCH7Data, icSigMCH8Data, icSigMCH9Data, icSigMCHAData, icSigMCHBData, icSigMCHCData, icSigMCHDData, icSigMCHEData, icSigMCHFData, icSigNamedData, icSigNChannelData, icSigNoColorData, icSigRadiantSpectralData, icSigReflectanceSpectralData, icSigRgbData, icSigSparseMatrixReflectanceData, icSigTransmisionSpectralData, icSigXYZData, icSigYCbCrData, icSigYxyData, and m_szStr.
Referenced by CIccTagEmbeddedProfile::Describe(), GetSigName(), main(), main(), and PrintIccProfileInfo().
GetDeviceAttrName()
const icChar * CIccInfo::GetDeviceAttrName (icUInt64Number val)
{
  if (val & icTransparency)
    strcpy(m_szStr, "Transparency");
  else
    strcpy(m_szStr, "Reflective");
  int l=(int)strlen(m_szStr);
  if (val & icMatte)
    strcpy(m_szStr+l, " | Matte");
  else
    strcpy(m_szStr+l, " | Glossy");
  return m_szStr;
}
References m_szStr.
Referenced by CIccTagEmbeddedProfile::Describe(), and main().
GetElementTypeSigName()
const icChar * CIccInfo::GetElementTypeSigName (icElemTypeSignature sig)
{
  if (CIccMpeCreator::GetElementSigName(*m_str, sig)) {
    return m_str->c_str();
  }
  return GetUnknownName(sig);
}
References CIccMpeCreator::GetElementSigName(), GetUnknownName(), and m_str.
Referenced by GetPathEntrySigName().
GetIlluminantName()
const icChar * CIccInfo::GetIlluminantName (icIlluminant val)
{
  switch (val) {
  case icIlluminantUnknown:
    return "Illuminant Unknown";
  case icIlluminantD50:
    return "Illuminant D50";
  case icIlluminantD65:
    return "Illuminant D65";
  case icIlluminantD93:
    return "Illuminant D93";
  case icIlluminantF2:
    return "Illuminant F2";
  case icIlluminantD55:
    return "Illuminant D55";
  case icIlluminantA:
    return "Illuminant A";
  case icIlluminantEquiPowerE:
    return "Illuminant EquiPowerE";
  case icIlluminantF8:
    return "Illuminant F8";
  case icIlluminantBlackBody:
    return "Illuminant Black Body";
  case icIlluminantDaylight:
    return "Illuminant Daylight";
  case icIlluminantB:
    return "Illuminant B";
  case icIlluminantC:
    return "Illuminant C";
  case icIlluminantF1:
    return "Illuminant F1";
  case icIlluminantF3:
    return "Illuminant F3";
  case icIlluminantF4:
    return "Illuminant F4";
  case icIlluminantF5:
    return "Illuminant F5";
  case icIlluminantF6:
    return "Illuminant F6";
  case icIlluminantF7:
    return "Illuminant F7";
  case icIlluminantF9:
    return "Illuminant F9";
  case icIlluminantF10:
    return "Illuminant F10";
  case icIlluminantF11:
    return "Illuminant F11";
  case icIlluminantF12:
    return "Illuminant F12";
  default:
    sprintf(m_szStr, "Unknown Illuminant '%d", val);
    return m_szStr;
  }
}
References icIlluminantA, icIlluminantB, icIlluminantBlackBody, icIlluminantC, icIlluminantD50, icIlluminantD55, icIlluminantD65, icIlluminantD93, icIlluminantDaylight, icIlluminantEquiPowerE, icIlluminantF1, icIlluminantF10, icIlluminantF11, icIlluminantF12, icIlluminantF2, icIlluminantF3, icIlluminantF4, icIlluminantF5, icIlluminantF6, icIlluminantF7, icIlluminantF8, icIlluminantF9, icIlluminantUnknown, and m_szStr.
Referenced by CIccTagMeasurement::Describe(), CIccTagViewingConditions::Describe(), CIccTagSpectralViewingConditions::Describe(), CIccTagXmlMeasurement::ToXml(), CIccTagXmlViewingConditions::ToXml(), and CIccTagXmlSpectralViewingConditions::ToXml().
GetMeasurementFlareName()
const icChar * CIccInfo::GetMeasurementFlareName (icMeasurementFlare val)
{
  switch (val) { // Directly switch on the enum without casting to int
  case icFlare0:
    return "Flare 0"; // Properly handle the 0% flare
  case icFlare100:
    return "Flare 100"; // Properly handle the 100% flare
  default:
    // Handle icMaxEnumFlare explicitly here if needed
    if (val == icMaxEnumFlare) {
      return "Max Flare"; // Special handling for the max sentinel value
    }
    // General default case for truly unexpected values
          std::snprintf(m_szStr, sizeof(m_szStr), "Unknown Flare '%d'", (int)val);
    return m_szStr;
  }
}
References icFlare0, icFlare100, and m_szStr.
Referenced by CIccTagMeasurement::Describe(), and CIccTagXmlMeasurement::ToXml().
GetMeasurementGeometryName()
const icChar * CIccInfo::GetMeasurementGeometryName (icMeasurementGeometry val)
{
  switch (val) {  // Directly use enum type, casting is not needed
  case icGeometryUnknown:
    return "Geometry Unknown";
  case icGeometry045or450:
    return "Geometry 0-45 or 45-0";
  case icGeometry0dord0:
    return "Geometry 0-d or d-0";
  default:
          std::snprintf(m_szStr, sizeof(m_szStr), "Unknown Geometry '%d'", (int)val);
    return m_szStr;
  }
}
References icGeometry045or450, icGeometry0dord0, icGeometryUnknown, and m_szStr.
Referenced by CIccTagMeasurement::Describe(), and CIccTagXmlMeasurement::ToXml().
GetMeasurementUnit()
const icChar * CIccInfo::GetMeasurementUnit (icSignature sig)
{
  switch (sig) {
    case icSigStatusA:
      return "Status A";
    case icSigStatusE:
      return "Status E";
    case icSigStatusI:
      return "Status I";
    case icSigStatusT:
      return "Status T";
    case icSigStatusM:
      return "Status M";
    case icSigDN:
      return "DIN with no polarizing filter";
    case icSigDNP:
      return "DIN with polarizing filter";
    case icSigDNN:
      return "Narrow band DIN with no polarizing filter";
    case icSigDNNP:
      return "Narrow band DIN with polarizing filter";
    default:
    {
      char buf[10] = {0};
      buf[0] = (char)(sig>>24);
      buf[1] = (char)(sig>>16);
      buf[2] = (char)(sig>>8);
      buf[3] = (char)(sig);
      buf[4] = '\0';
      sprintf(m_szStr, "Unknown Measurement Type '%s'", buf);
      return m_szStr;
    }
  }
}
References icSigDN, icSigDNN, icSigDNNP, icSigDNP, icSigStatusA, icSigStatusE, icSigStatusI, icSigStatusM, icSigStatusT, and m_szStr.
Referenced by CIccResponseCurveStruct::Describe(), and CIccTagXmlResponseCurveSet16::ToXml().
GetPathEntrySigName()
const icChar * CIccInfo::GetPathEntrySigName (icUInt32Number val)
{
  const icChar *rv;
  rv = GetTagSigName((icTagSignature)sig);
  if (rv != m_szStr)
    return rv;
  rv = GetTagTypeSigName((icTagTypeSignature)sig);
  if (rv != m_szStr)
    return rv;
  rv = GetElementTypeSigName((icElemTypeSignature)sig);
  if (rv != m_szStr)
    return rv;
  return GetUnknownName(sig);
}
References GetElementTypeSigName(), GetTagSigName(), GetTagTypeSigName(), GetUnknownName(), and m_szStr.
Referenced by GetSigPathName().
GetPlatformSigName()
const icChar * CIccInfo::GetPlatformSigName (icPlatformSignature sig)
{
  switch (sig) {
  case icSigMacintosh:
    return "Macintosh";
  case icSigMicrosoft:
    return "Microsoft";
  case icSigSolaris:
    return "Solaris";
  case icSigSGI:
    return "SGI";
  case icSigTaligent:
    return "Taligent";
  case icSigUnknownPlatform:
    return "Unknown";
  default:
    return GetUnknownName(sig);
  }
}
References GetUnknownName(), icSigMacintosh, icSigMicrosoft, icSigSGI, icSigSolaris, icSigTaligent, and icSigUnknownPlatform.
Referenced by CIccTagEmbeddedProfile::Describe(), GetSigName(), and main().
GetProfileClassSigName()
const icChar * CIccInfo::GetProfileClassSigName (icProfileClassSignature sig)
{
  switch (sig) {
  case icSigInputClass:
    return "InputClass";
  case icSigDisplayClass:
    return "DisplayClass";
  case icSigOutputClass:
    return "OutputClass";
  case icSigLinkClass:
    return "LinkClass";
  case icSigAbstractClass:
    return "AbstractClass";
  case icSigColorSpaceClass:
    return "ColorSpaceClass";
  case icSigNamedColorClass:
    return "NamedColorClass";
  case icSigColorEncodingClass:
    return "ColorEncodingClass";
  case icSigMaterialIdentificationClass:
    return "MaterialIdentificationClass";
  case icSigMaterialVisualizationClass:
    return "MaterialVisualizationClass";
  case icSigMaterialLinkClass:
    return "MaterialLinkClass";
  default:
    return GetUnknownName(sig);
  }
}
References GetUnknownName(), icSigAbstractClass, icSigColorEncodingClass, icSigColorSpaceClass, icSigDisplayClass, icSigInputClass, icSigLinkClass, icSigMaterialIdentificationClass, icSigMaterialLinkClass, icSigMaterialVisualizationClass, icSigNamedColorClass, and icSigOutputClass.
Referenced by CIccTagEmbeddedProfile::Describe(), GetSigName(), and main().
GetProfileFlagsName()
const icChar * CIccInfo::GetProfileFlagsName (icUInt32Number val, bool bCheckMCS = false)
{
  if (val & icEmbeddedProfileTrue)
    strcpy(m_szStr, "EmbeddedProfileTrue");
  else
    strcpy(m_szStr, "EmbeddedProfileFalse");
  int l=(int)strlen(m_szStr);
  if (val & icUseWithEmbeddedDataOnly)
    strcpy(m_szStr+l, " | UseWithEmbeddedDataOnly");
  else
    strcpy(m_szStr+l, " | UseAnywhere");
  if (bCheckMCS) {
    l=(int)strlen(m_szStr);
    if (val & icMCSNeedsSubsetTrue)
      strcpy(m_szStr+l, " | MCSNeedsSubset");
    else
      strcpy(m_szStr+l, " | MCSConnectAny");
  }
  if (val & icExtendedRangePCS)
    strcpy(m_szStr + l, " | ExtendedRangePCS");
  return m_szStr;
}
References m_szStr.
Referenced by CIccTagEmbeddedProfile::Describe(), and main().
GetProfileID()
const icChar * CIccInfo::GetProfileID (icProfileID * profileID)
{
  char *ptr = m_szStr;
  int i;
  for (i=0; i<16; i++, ptr+=2) {
    sprintf(ptr, "%02x", profileID->ID8[i]);
  }
  return m_szStr;
}
References icProfileID::ID8, and m_szStr.
Referenced by CIccTagEmbeddedProfile::Describe(), and main().
GetReferenceMediumGamutSigNameName()
const icChar * CIccInfo::GetReferenceMediumGamutSigNameName (icReferenceMediumGamutSignature sig)
{
  switch (sig) {
  case icSigPerceptualReferenceMediumGamut:
    return "perceptualReferenceMediumGamut";
  default:
    return GetUnknownName(sig);
  }
}
References GetUnknownName(), and icSigPerceptualReferenceMediumGamut.
Referenced by GetSigName().
GetRenderingIntentName()
const icChar * CIccInfo::GetRenderingIntentName (icRenderingIntent val, bool bIsV5 = false)
{
  switch (val) {
  case icPerceptual:
    return "Perceptual";
  case icRelativeColorimetric:
    if (bIsV5)
      return "Relative";
    else
      return "Relative Colorimetric";
  case icSaturation:
    return "Saturation";
  case icAbsoluteColorimetric:
    if (bIsV5)
      return "Absolute";
    else
      return "Absolute Colorimetric";
  default:
    sprintf(m_szStr, "Unknown Intent '%d", val);
    return m_szStr;
  }
}
References icAbsoluteColorimetric, icPerceptual, icRelativeColorimetric, icSaturation, and m_szStr.
Referenced by CIccTagEmbeddedProfile::Describe(), main(), and CIccProfileXml::ToXmlWithBlanks().
GetSigName()
const icChar * CIccInfo::GetSigName (icUInt32Number val)
{
  const icChar *rv;
  rv = GetTagSigName((icTagSignature)sig);
  if (rv != m_szStr)
    return rv;
  rv = GetTechnologySigName((icTechnologySignature)sig);
  if (rv != m_szStr)
    return rv;
  rv = GetTagTypeSigName((icTagTypeSignature)sig);
  if (rv != m_szStr)
    return rv;
  rv = GetColorSpaceSigName((icColorSpaceSignature)sig);
  if (rv != m_szStr)
    return rv;
  rv = GetProfileClassSigName((icProfileClassSignature)sig);
  if (rv != m_szStr)
    return rv;
  rv = GetPlatformSigName((icPlatformSignature)sig);
  if (rv != m_szStr)
    return rv;
  rv = GetReferenceMediumGamutSigNameName((icReferenceMediumGamutSignature)sig);
  if (rv != m_szStr)
    return rv;
  return GetColorimetricIntentImageStateName((icColorimetricIntentImageStateSignature)sig);
}
References GetColorimetricIntentImageStateName(), GetColorSpaceSigName(), GetPlatformSigName(), GetProfileClassSigName(), GetReferenceMediumGamutSigNameName(), GetTagSigName(), GetTagTypeSigName(), GetTechnologySigName(), and m_szStr.
Referenced by CIccTagSignature::Describe(), CIccResponseCurveStruct::Validate(), CIccTagSignature::Validate(), and CIccTagProfileSeqDesc::Validate().
GetSigPathName()
std::string CIccInfo::GetSigPathName (std::string sigPath)
{
  std::string rv;
  const char *ptr = sigPath.c_str();
  int n =0;
  while(*ptr==':') {
    std::string sigStr;
    ptr++;
    while(*ptr && *ptr!=':') {
      sigStr += *ptr;
      ptr++;
    }
    icSignature sig = icGetSigVal(sigStr.c_str());
    if (n!=0) {
      rv += ">";
    }
    rv += GetPathEntrySigName(sig);
    n++;
  }
  if (n > 0)
    rv += ":";
  return rv;
}
References GetPathEntrySigName(), and icGetSigVal().
Referenced by CIccCalculatorFunc::Validate(), CIccStructNamedColor::Validate(), CIccTagGamutBoundaryDesc::Validate(), CIccMBB::Validate(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccStructBRDF::Validate(), CIccStructColorantInfo::Validate(), CIccTag::Validate(), CIccTagText::Validate(), CIccTagUtf8Text::Validate(), CIccTagZipUtf8Text::Validate(), CIccTagUtf16Text::Validate(), CIccTagTextDescription::Validate(), CIccTagSignature::Validate(), CIccTagNamedColor2::Validate(), CIccTagXYZ::Validate(), CIccTagChromaticity::Validate(), CIccTagCicp::Validate(), CIccTagSparseMatrixArray::Validate(), CIccTagNum< T, Tsig >::Validate(), CIccTagFloatNum< T, Tsig >::Validate(), CIccTagMeasurement::Validate(), CIccTagMultiLocalizedUnicode::Validate(), CIccTagData::Validate(), CIccTagColorantOrder::Validate(), CIccTagColorantTable::Validate(), CIccTagViewingConditions::Validate(), CIccTagProfileSeqDesc::Validate(), CIccTagResponseCurveSet16::Validate(), CIccTagSpectralDataInfo::Validate(), CIccTagSpectralViewingConditions::Validate(), CIccTagEmbeddedHeightImage::Validate(), CIccTagEmbeddedNormalImage::Validate(), CIccTagStruct::Validate(), CIccTagArray::Validate(), CIccTagDict::Validate(), CIccTagEmbeddedProfile::Validate(), CIccTagCurve::Validate(), CIccTagParametricCurve::Validate(), CIccMatrix::Validate(), CIccCLUT::Validate(), CIccTagMultiProcessElement::Validate(), CIccTagProfileSequenceId::Validate(), CIccFormulaCurveSegment::Validate(), CIccSampledCurveSegment::Validate(), CIccSegmentedCurve::Validate(), CIccSingleSampledCurve::Validate(), CIccSampledCalculatorCurve::Validate(), CIccMpeCurveSet::Validate(), CIccMpeTintArray::Validate(), CIccMpeToneMap::Validate(), CIccMpeMatrix::Validate(), CIccMpeCLUT::Validate(), CIccMpeExtCLUT::Validate(), CIccMpeCalculator::Validate(), CIccMpeSpectralMatrix::Validate(), CIccMpeInvEmissionMatrix::Validate(), CIccMpeSpectralCLUT::Validate(), CIccMpeSpectralObserver::Validate(), CIccMpeUnknown::Validate(), and CIccMultiProcessElement::Validate().
GetSpectralColorSigName()
const icChar * CIccInfo::GetSpectralColorSigName (icSpectralColorSignature sig)
{
  switch(icGetColorSpaceType(sig)) {
  case icSigNoSpectralData:
    return "NoSpectralData";
   case icSigNChannelData:
     sprintf(m_szStr, "0x%04XChannelData", icNumColorSpaceChannels(sig));
     return m_szStr;
   case icSigReflectanceSpectralData:
     sprintf(m_szStr, "0x%04XChannelReflectanceData", icNumColorSpaceChannels(sig));
     return m_szStr;
   case icSigTransmisionSpectralData:
     sprintf(m_szStr, "0x%04XChannelTransmissionData", icNumColorSpaceChannels(sig));
     return m_szStr;
   case icSigRadiantSpectralData:
     sprintf(m_szStr, "0x%04XChannelRadiantData", icNumColorSpaceChannels(sig));
     return m_szStr;
   case icSigBiSpectralReflectanceData:
     sprintf(m_szStr, "0x%04XChannelBiSpectralReflectanceData", icNumColorSpaceChannels(sig));
     return m_szStr;
   case icSigSparseMatrixReflectanceData:
     sprintf(m_szStr, "0x%04XChannelSparseMatrixReflectanceData", icNumColorSpaceChannels(sig));
     return m_szStr;
  default:
    return GetUnknownName(sig);
  }
}
References GetUnknownName(), icSigBiSpectralReflectanceData, icSigNChannelData, icSigNoSpectralData, icSigRadiantSpectralData, icSigReflectanceSpectralData, icSigSparseMatrixReflectanceData, icSigTransmisionSpectralData, and m_szStr.
Referenced by CIccTagEmbeddedProfile::Describe(), main(), and main().
GetSpotShapeName()
const icChar * CIccInfo::GetSpotShapeName (icSpotShape val)
{
  switch (val) {
  case icSpotShapeUnknown:
    return "Spot Shape Unknown";
  case icSpotShapePrinterDefault:
    return "Spot Shape Printer Default";
  case icSpotShapeRound:
    return "Spot Shape Round";
  case icSpotShapeDiamond:
    return "Spot Shape Diamond";
  case icSpotShapeEllipse:
    return "Spot Shape Ellipse";
  case icSpotShapeLine:
    return "Spot Shape Line";
  case icSpotShapeSquare:
    return "Spot Shape Square";
  case icSpotShapeCross:
    return "Spot Shape Cross";
  default:
    sprintf(m_szStr, "Unknown Spot Shape '%d", val);
    return m_szStr;
  }
}
References icSpotShapeCross, icSpotShapeDiamond, icSpotShapeEllipse, icSpotShapeLine, icSpotShapePrinterDefault, icSpotShapeRound, icSpotShapeSquare, icSpotShapeUnknown, and m_szStr.
GetStandardObserverName()
const icChar * CIccInfo::GetStandardObserverName (icStandardObserver val)
{
  switch (val) {
  case icStdObsUnknown:
    return "Unknown observer";
  case icStdObs1931TwoDegrees:
    return "CIE 1931 (two degree) standard observer";
  case icStdObs1964TenDegrees:
    return "CIE 1964 (ten degree) standard observer";
  default:
    sprintf(m_szStr, "Unknown Observer '%d", val);
    return m_szStr;
  }
}
References icStdObs1931TwoDegrees, icStdObs1964TenDegrees, icStdObsUnknown, and m_szStr.
Referenced by CIccTagMeasurement::Describe(), CIccTagSpectralViewingConditions::Describe(), and CIccTagXmlSpectralViewingConditions::ToXml().
GetStructSigName()
const icChar * CIccInfo::GetStructSigName (icStructSignature sig)
{
  if (CIccStructCreator::GetStructSigName(*m_str, sig)) {
    return m_str->c_str();
  }
  return GetUnknownName(sig);
}
References CIccStructCreator::GetStructSigName(), GetUnknownName(), and m_str.
Referenced by IIccStruct::Describe().
GetSubClassVersionName()
const icChar * CIccInfo::GetSubClassVersionName (icUInt32Number val)
{
  icFloatNumber ver = (icFloatNumber)(((val >> 12) & 0xf)*10.0 + ((val >> 8) & 0xf) +
    ((val >> 4) & 0xf) / 10.0 + (val & 0xf) / 100.0);
  sprintf(m_szStr, "%.2lf", ver);
  return m_szStr;
}
References m_szStr.
Referenced by CIccTagEmbeddedProfile::Describe(), main(), and CIccProfileXml::ToXmlWithBlanks().
GetTagSigName()
const icChar * CIccInfo::GetTagSigName (icTagSignature sig)
{
  const icChar *rv = CIccTagCreator::GetTagSigName(sig);
  if (rv) {
    return rv;
  }
  return GetUnknownName(sig);
}
References CIccTagCreator::GetTagSigName(), and GetUnknownName().
Referenced by CIccTagEmbeddedProfile::Describe(), DumpTag(), GetPathEntrySigName(), GetSigName(), main(), and CIccProfileXml::ToXmlWithBlanks().
GetTagTypeSigName()
const icChar * CIccInfo::GetTagTypeSigName (icTagTypeSignature sig)
{
  const icChar *rv = CIccTagCreator::GetTagTypeSigName(sig);
  if (rv) {
    return rv;
  }
  return GetUnknownName(sig);
}
References CIccTagCreator::GetTagTypeSigName(), and GetUnknownName().
Referenced by MyTagDialog::MyTagDialog(), DumpTag(), GetPathEntrySigName(), GetSigName(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), and CIccMpeXmlTintArray::ParseXml().
GetTechnologySigName()
const icChar * CIccInfo::GetTechnologySigName (icTechnologySignature sig)
{
  switch(sig) {
  case icSigDigitalCamera:
    return "DigitalCamera";
  case icSigFilmScanner:
    return "FilmScanner";
  case icSigReflectiveScanner:
    return "ReflectiveScanner";
  case icSigInkJetPrinter:
    return "InkJetPrinter";
  case icSigThermalWaxPrinter:
    return "ThermalWaxPrinter";
  case icSigElectrophotographicPrinter:
    return "ElectrophotographicPrinter";
  case icSigElectrostaticPrinter:
    return "ElectrostaticPrinter";
  case icSigDyeSublimationPrinter:
    return "DyeSublimationPrinter";
  case icSigPhotographicPaperPrinter:
    return "PhotographicPaperPrinter";
  case icSigFilmWriter:
    return "FilmWriter";
  case icSigVideoMonitor:
    return "VideoMonitor";
  case icSigVideoCamera:
    return "VideoCamera";
  case icSigProjectionTelevision:
    return "ProjectionTelevision";
  case icSigCRTDisplay:
    return "CRTDisplay";
  case icSigPMDisplay:
    return "PMDisplay";
  case icSigAMDisplay:
    return "AMDisplay";
  case icSigPhotoCD:
    return "PhotoCD";
  case icSigPhotoImageSetter:
    return "PhotoImageSetter";
  case icSigGravure:
    return "Gravure";
  case icSigOffsetLithography:
    return "OffsetLithography";
  case icSigSilkscreen:
    return "Silkscreen";
  case icSigFlexography:
    return "Flexography";
  default:
    return GetUnknownName(sig);
  }
}
References GetUnknownName(), icSigAMDisplay, icSigCRTDisplay, icSigDigitalCamera, icSigDyeSublimationPrinter, icSigElectrophotographicPrinter, icSigElectrostaticPrinter, icSigFilmScanner, icSigFilmWriter, icSigFlexography, icSigGravure, icSigInkJetPrinter, icSigOffsetLithography, icSigPhotoCD, icSigPhotographicPaperPrinter, icSigPhotoImageSetter, icSigPMDisplay, icSigProjectionTelevision, icSigReflectiveScanner, icSigSilkscreen, icSigThermalWaxPrinter, icSigVideoCamera, and icSigVideoMonitor.
Referenced by GetSigName().
GetUnknownName()
const icChar * CIccInfo::GetUnknownName (icUInt32Number val)
{
  icChar buf[24];
  // icGetSig() will print 'NULL' if val is 0x00000000 which is easier to post-process
  // if (!val)
  //  return "Unknown";
  sprintf(m_szStr, "Unknown %s", icGetSig(buf, val));
  return m_szStr;
}
References icGetSig(), and m_szStr.
Referenced by GetArraySigName(), GetCmmSigName(), GetColorimetricIntentImageStateName(), GetColorSpaceSigName(), GetElementTypeSigName(), GetPathEntrySigName(), GetPlatformSigName(), GetProfileClassSigName(), GetReferenceMediumGamutSigNameName(), GetSpectralColorSigName(), GetStructSigName(), GetTagSigName(), GetTagTypeSigName(), and GetTechnologySigName().
GetVersionName()
const icChar * CIccInfo::GetVersionName (icUInt32Number val)
{
  icFloatNumber ver = (icFloatNumber)(((val>>28)&0xf)*10.0 + ((val>>24)&0xf) +
                                      ((val>>20)&0xf)/10.0 + ((val>>16)&0xf)/100.0);
  sprintf(m_szStr, "%.2lf", ver);
  return m_szStr;
}
References m_szStr.
Referenced by CIccTagEmbeddedProfile::Describe(), main(), and CIccProfileXml::ToXmlWithBlanks().
IsProfileIDCalculated()
bool CIccInfo::IsProfileIDCalculated (icProfileID * profileID)
{
  int i;
  for (i=0; i<16; i++) {
    if (profileID->ID8[i])
      break;
  }
  return i<16;
}
References icProfileID::ID8.
Referenced by CIccTagEmbeddedProfile::Describe(), and main().
IsValidSpace()
bool CIccInfo::IsValidSpace (icColorSpaceSignature sig)
{
  bool rv = true;
  switch(sig) {
  case icSigXYZData:
  case icSigLabData:
  case icSigLuvData:
  case icSigYCbCrData:
  case icSigYxyData:
  case icSigRgbData:
  case icSigGrayData:
  case icSigHsvData:
  case icSigHlsData:
  case icSigCmykData:
  case icSigCmyData:
  case icSigMCH1Data:
  case icSigNamedData:
  case icSigGamutData:
  case icSig2colorData:
  case icSig3colorData:
  case icSig4colorData:
  case icSig5colorData:
  case icSig6colorData:
  case icSig7colorData:
  case icSig8colorData:
  case icSig9colorData:
  case icSig10colorData:
  case icSig11colorData:
  case icSig12colorData:
  case icSig13colorData:
  case icSig14colorData:
  case icSig15colorData:
    break;
  default:
    switch(icGetColorSpaceType(sig)) {
    case icSigNChannelData:
      break;
    default:
      rv = false;
    }
  }
  return rv;
}
References icSig10colorData, icSig11colorData, icSig12colorData, icSig13colorData, icSig14colorData, icSig15colorData, icSig2colorData, icSig3colorData, icSig4colorData, icSig5colorData, icSig6colorData, icSig7colorData, icSig8colorData, icSig9colorData, icSigCmyData, icSigCmykData, icSigGrayData, icSigHlsData, icSigHsvData, icSigLabData, icSigLuvData, icSigMCH1Data, icSigNamedData, icSigNChannelData, icSigRgbData, icSigXYZData, icSigYCbCrData, and icSigYxyData.
Referenced by CDevLinkWriter::begin().
IsValidSpectralSpace()
bool CIccInfo::IsValidSpectralSpace (icColorSpaceSignature sig)
{
  bool rv = true;
  switch (icGetColorSpaceType(sig)) {
    case (icSpectralColorSignature)icSigReflectanceSpectralData:
    case (icSpectralColorSignature)icSigTransmisionSpectralData:
    case (icSpectralColorSignature)icSigRadiantSpectralData:
    case (icSpectralColorSignature)icSigBiSpectralReflectanceData:
    case (icSpectralColorSignature)icSigSparseMatrixReflectanceData:
      break;
    default:
      rv = false;
  }
  return rv;
}
References icSigBiSpectralReflectanceData, icSigRadiantSpectralData, icSigReflectanceSpectralData, icSigSparseMatrixReflectanceData, and icSigTransmisionSpectralData.
Field Documentation
m_str
std::string* CIccInfo::m_str protected
Referenced by ~CIccInfo(), GetArraySigName(), GetElementTypeSigName(), and GetStructSigName().
m_szSigStr
icChar CIccInfo::m_szSigStr[128] protected
m_szStr
icChar CIccInfo::m_szStr[128] protected
Referenced by CIccInfo(), GetColorSpaceSigName(), GetDeviceAttrName(), GetIlluminantName(), GetMeasurementFlareName(), GetMeasurementGeometryName(), GetMeasurementUnit(), GetPathEntrySigName(), GetProfileFlagsName(), GetProfileID(), GetRenderingIntentName(), GetSigName(), GetSpectralColorSigName(), GetSpotShapeName(), GetStandardObserverName(), GetSubClassVersionName(), GetUnknownName(), and GetVersionName().
The documentation for this class was generated from the following files:
IccProfLib/IccUtil.h
IccProfLib/IccUtil.cpp