iccDEV: CIccBasicArrayFactory Class Reference
CIccBasicArrayFactory Class Reference
#include <IccArrayFactory.h>
Public Member Functions
virtual IIccArray * CreateArray (icArraySignature arrayTypeSig, CIccTagArray *pTagArray=NULL)
virtual icArraySignature GetArraySig (const icChar *arrayName)
virtual bool GetArraySigName (std::string &arrayName, icArraySignature arrayTypeSig, bool bFindUnknown=true)
Detailed Description
Class: CIccBasicArrayFactory
Purpose: CIccBasicArrayFactory provides creation of CIccArray handlers defined by the ICC profile specification. The CIccArrayCreator always creates a CIccBasicElemFactory.
Member Function Documentation
CreateArray()
IIccArray * CIccBasicArrayFactory::CreateArray (icArraySignature arrayTypeSig, CIccTagArray * pTagArray = NULL) virtual
Function: CreateArray(arrayTypeSig) Create an array object handler of type arrayTypeSig.
Parameter(s): arrayTypeSig = signature of the ICC array type for the array handler to be created pTagArray = pointer to tag array to associate with the handerl
Returns a new CIccArray handler of the given signature type. Unrecognized structTypeSig's will be created as a CIccArrayUnknown object.
Implements IIccArrayFactory.
{
  switch(arrayTypeSig) {
    case icSigNamedColorArray:
      return new CIccArrayNamedColor(pTagArray);
    case icSigColorantInfoArray:
      return new CIccArrayColorantInfo(pTagArray);
    default:
      return new CIccArrayUnknown(pTagArray, arrayTypeSig);
  }
}
References CIccArrayColorantInfo::CIccArrayColorantInfo(), CIccArrayNamedColor::CIccArrayNamedColor(), CIccArrayUnknown::CIccArrayUnknown(), icSigColorantInfoArray, and icSigNamedColorArray.
GetArraySig()
icArraySignature CIccBasicArrayFactory::GetArraySig (const icChar * arrayName) virtual
Function: GetArraySig(arrayName) Get signature associate with display name arrayName handler
Parameter(s): arrayName = string to find signature for
Returns true if arraySig is recognized by the factory, false if the factory doesn't create arraySig arrays.
Implements IIccArrayFactory.
{
  int i;
  for (i = 0; g_icArrayNames[i].sig; i++) {
    if (!strcmp(g_icArrayNames[i].szArrayName, szArrayName)) {
      return g_icArrayNames[i].sig;
    }
  }
  return (icArraySignature)0;
}
GetArraySigName()
bool CIccBasicArrayFactory::GetArraySigName (std::string & arrayName, icArraySignature arrayTypeSig, bool bFindUnknown = true) virtual
Function: GetArraySigName(arrayName, arrayTypeSig, bFindUnknown) Get display name of arrayTypeSig.
Parameter(s): arrayName = string to put struct name into, arrayTypeSig = signature of the ICC struct type to get a name for bFindUnknown = fills arrayName if strutTypeSig is unknown
Returns true if arraySig is recognized by the factory, false if the factory doesn't create arraySig arrays.
Implements IIccArrayFactory.
{
  int i;
  for (i = 0; g_icArrayNames[i].sig; i++) {
    if (g_icArrayNames[i].sig == arrayTypeSig) {
      arrayName = g_icArrayNames[i].szArrayName;
      return true;
    }
  }
  if (!bFindUnknown) {
    char sig[20];
    arrayName = "UnknownStruct_";
    icGetSigStr(sig, arrayTypeSig);
    arrayName += sig;
  }
  else {
    arrayName = "";
  }
  return false;
}
References icGetSigStr().
The documentation for this class was generated from the following files:
IccProfLib/IccArrayFactory.h
IccProfLib/IccArrayFactory.cpp