iccDEV: CIccCfgProfileSequence Class Reference
CIccCfgProfileSequence Class Reference
#include <IccCmmConfig.h>
Public Member Functions
CIccCfgProfileSequence ()
virtual ~CIccCfgProfileSequence ()
int fromArgs (const char **args, int nArg, bool bReset=false)
bool fromJson (json obj, bool bReset=false)
void reset ()
void toJson (json &obj) const
Data Fields
CIccCfgProfileArray m_profiles
Detailed Description
Constructor & Destructor Documentation
CIccCfgProfileSequence()
CIccCfgProfileSequence::CIccCfgProfileSequence ()
{
}
~CIccCfgProfileSequence()
virtual CIccCfgProfileSequence::~CIccCfgProfileSequence () inline virtual
{}
Member Function Documentation
fromArgs()
int CIccCfgProfileSequence::fromArgs (const char ** args, int nArg, bool bReset = false)
{
  int nUsed = 0;
  if (bReset)
    reset();
  icXformInterp interpolation = icInterpTetrahedral;
  if (nArg > 1) {
    interpolation = (icXformInterp)atoi(args[0]);
    args++;
    nArg--;
    nUsed++;
  }
  bool bFirst = true;
  while (nArg >= 2) {
    CIccCfgProfilePtr pProf = CIccCfgProfilePtr(new CIccCfgProfile());
    while (nArg >= 2 && !strnicmp(args[0], "-ENV:", 5)) {  //check for -ENV: to allow for Cmm Environment variables to be defined for next transform
      icSignature sig = icGetSigVal(args[0] + 5);
      icFloatNumber val = (icFloatNumber)atof(args[1]);
      args += 2;
      nArg -= 2;
      nUsed += 2;
      pProf->m_iccEnvVars[sig] = val;
    }
    if (nArg >= 2) {
      pProf->m_iccFile = args[0];
      if (bFirst) {
        if (!stricmp(args[0], "-embedded")) {
          pProf->m_iccFile.clear();
        }
        bFirst = false;
      }
      int nType;
      int nIntent = atoi(args[1]);
      pProf->m_useD2BxB2Dx = true;
      pProf->m_useHToS = (nIntent / 100000) != 0;
      pProf->m_useV5SubProfile = (nIntent / 10000) != 0;
      nIntent = nIntent % 10000;
      pProf->m_adjustPcsLuminance = nIntent / 1000 != 0;
      nIntent = nIntent % 1000;
      nType = abs(nIntent) / 10;
      nIntent = nIntent % 10;
      if (nType == 1) {
        pProf->m_useD2BxB2Dx = false;
        nType = icXformLutColor;
      }
      else if (nType == 4) {
        pProf->m_useBPC = true;
        nType = icXformLutColor;
      }
      pProf->m_intent = (icRenderingIntent)nIntent;
      pProf->m_transform = (icXformLutType)nType;
      pProf->m_interpolation = interpolation;
      args += 2;
      nArg -= 2;
      nUsed += 2;
    }
    if (nArg >= 2 && !stricmp(args[0], "-PCC")) {
      pProf->m_pccFile = args[1];
      args += 2;
      nArg -= 2;
      nUsed += 2;
    }
    m_profiles.push_back(pProf);
  }
  return m_profiles.size()>0 ? nUsed : 0;
}
References CIccCfgProfile::CIccCfgProfile(), icGetSigVal(), icInterpTetrahedral, icXformLutColor, CIccCfgProfile::m_adjustPcsLuminance, CIccCfgProfile::m_iccEnvVars, CIccCfgProfile::m_iccFile, CIccCfgProfile::m_intent, CIccCfgProfile::m_interpolation, CIccCfgProfile::m_pccFile, m_profiles, CIccCfgProfile::m_transform, CIccCfgProfile::m_useBPC, CIccCfgProfile::m_useD2BxB2Dx, CIccCfgProfile::m_useHToS, CIccCfgProfile::m_useV5SubProfile, and reset().
Referenced by main(), and main().
fromJson()
bool CIccCfgProfileSequence::fromJson (json obj, bool bReset = false)
{
  if (!j.is_array())
    return false;
  if (bReset)
    reset();
  for (auto p = j.begin(); p != j.end(); p++) {
    if (p->is_object()) {
      CIccCfgProfilePtr pProf(new CIccCfgProfile);
      if (pProf->fromJson(*p)) {
        m_profiles.push_back(pProf);
      }
      else {
        pProf.reset();
      }
    }
  }
  return true;
}
References CIccCfgProfile::fromJson(), m_profiles, and reset().
Referenced by main(), and main().
reset()
void CIccCfgProfileSequence::reset ()
{
  m_profiles.clear();
}
References m_profiles.
Referenced by fromArgs(), and fromJson().
toJson()
void CIccCfgProfileSequence::toJson (json & obj) const
{
  for (auto p = m_profiles.begin(); p != m_profiles.end(); p++) {
    CIccCfgProfile* pProf = p->get();
    if (!pProf)
      continue;
    json prof;
    pProf->toJson(prof);
    obj.push_back(prof);
  }
}
References m_profiles, and CIccCfgProfile::toJson().
Referenced by main().
Field Documentation
m_profiles
CIccCfgProfileArray CIccCfgProfileSequence::m_profiles
Referenced by fromArgs(), fromJson(), main(), main(), reset(), toJson(), and CIccCfgColorData::toLegacy().
The documentation for this class was generated from the following files:
Tools/CmdLine/IccCommon/IccCmmConfig.h
Tools/CmdLine/IccCommon/IccCmmConfig.cpp