iccDEV: CIccTagXmlMeasurement Class Reference
CIccTagXmlMeasurement Class Reference
#include <IccTagXml.h>
Public Member Functions
virtual ~CIccTagXmlMeasurement ()
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
virtual const char * GetClassName () const
virtual const char * GetExtClassName () const
virtual const char * GetExtDerivedClassName () const
virtual IIccExtensionTag * GetExtension ()
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
virtual bool ParseXml (xmlNode *pNode, std::string &parseStr)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
virtual bool ToXml (std::string &xml, std::string blanks="")
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icMeasurement m_Data
icUInt32Number m_nReserved
Detailed Description
Constructor & Destructor Documentation
~CIccTagXmlMeasurement()
virtual CIccTagXmlMeasurement::~CIccTagXmlMeasurement () inline virtual
{}
Member Function Documentation
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagMeasurement::Describe (std::string & sDescription, int nVerboseness) virtual inherited
Name: CIccTagMeasurement::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  CIccInfo Fmt;
  icChar buf[128];
   sDescription += Fmt.GetStandardObserverName(m_Data.stdObserver); sDescription += "\n";
   sprintf(buf, "Backing measurement: X=%.4lf, Y=%.4lf, Z=%.4lf\n",
           icFtoD(m_Data.backing.X),
           icFtoD(m_Data.backing.Y),
           icFtoD(m_Data.backing.Z));
   sDescription += buf;
   sDescription += Fmt.GetMeasurementGeometryName(m_Data.geometry); sDescription += "\n";
   sDescription += Fmt.GetMeasurementFlareName(m_Data.flare); sDescription += "\n";
   sDescription += Fmt.GetIlluminantName(m_Data.illuminant); sDescription += "\n";
}
References icMeasurement::backing, icMeasurement::flare, icMeasurement::geometry, CIccInfo::GetIlluminantName(), CIccInfo::GetMeasurementFlareName(), CIccInfo::GetMeasurementGeometryName(), CIccInfo::GetStandardObserverName(), icFtoD(), icMeasurement::illuminant, CIccTagMeasurement::m_Data, icMeasurement::stdObserver, icXYZNumber::X, icXYZNumber::Y, and icXYZNumber::Z.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
GetClassName()
virtual const char * CIccTagXmlMeasurement::GetClassName () const inline virtual
Reimplemented from CIccTagMeasurement.
{return "CIccTagXmlMeasurement"; }
GetExtClassName()
virtual const char * CIccTagXml::GetExtClassName () const inline virtual inherited
Implements IIccExtensionTag.
{ return "CIccTagXml"; }
Referenced by icProfDescToXml(), and icXmlParseProfDesc().
GetExtDerivedClassName()
virtual const char * CIccTagXml::GetExtDerivedClassName () const inline virtual inherited
Implements IIccExtensionTag.
Reimplemented in CIccCurveXml.
{ return ""; }
GetExtension()
virtual IIccExtensionTag * CIccTagXmlMeasurement::GetExtension () inline virtual
Reimplemented from CIccTag.
{return this; }
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagMeasurement::GetType () const inline virtual inherited
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigMeasurementType; }
References icSigMeasurementType.
Referenced by CIccTagMeasurement::Write().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
virtual CIccTag * CIccTagMeasurement::NewCopy () const inline virtual inherited
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
{return new CIccTagMeasurement(*this);}
References CIccTagMeasurement::CIccTagMeasurement().
ParseXml()
bool CIccTagXmlMeasurement::ParseXml (xmlNode * pNode, std::string & parseStr) virtual
Implements CIccTagXml.
{
  memset(&m_Data, 0, sizeof(m_Data));
  pNode = icXmlFindNode(pNode, "StandardObserver");
  if (pNode) {
    m_Data.stdObserver = icGetNamedStandardObserverValue(pNode->children ? (icChar*)pNode->children->content: "");
  }
  pNode = icXmlFindNode(pNode, "MeasurementBacking");
  if (pNode){
    xmlAttr *attr;
    attr = icXmlFindAttr(pNode, "X");
    if (attr) {
      m_Data.backing.X = icDtoF((icFloatNumber)atof(icXmlAttrValue(attr)));
    }
    attr = icXmlFindAttr(pNode, "Y");
    if (attr) {
      m_Data.backing.Y = icDtoF((icFloatNumber)atof(icXmlAttrValue(attr)));
    }
    attr = icXmlFindAttr(pNode, "Z");
    if (attr) {
      m_Data.backing.Z = icDtoF((icFloatNumber)atof(icXmlAttrValue(attr)));
    }
  }
  pNode = icXmlFindNode(pNode, "Geometry");
  if (pNode){
    m_Data.geometry = icGeNamedtMeasurementGeometryValue(pNode->children ? (icChar*)pNode->children->content : "");
  }
  pNode = icXmlFindNode(pNode, "Flare");
  if (pNode){
    m_Data.flare = icGetNamedMeasurementFlareValue(pNode->children ? (icChar*)pNode->children->content : "");
  }
  pNode = icXmlFindNode(pNode, "StandardIlluminant");
  if (pNode){
    m_Data.illuminant = icGetIlluminantValue(pNode->children ? (icChar*)pNode->children->content : "");
  }
  return true;
}
References icMeasurement::backing, icMeasurement::flare, icMeasurement::geometry, icDtoF(), icGeNamedtMeasurementGeometryValue(), icGetIlluminantValue(), icGetNamedMeasurementFlareValue(), icGetNamedStandardObserverValue(), icXmlAttrValue(), icXmlFindAttr(), icXmlFindNode(), icMeasurement::illuminant, CIccTagMeasurement::m_Data, icMeasurement::stdObserver, icXYZNumber::X, icXYZNumber::Y, and icXYZNumber::Z.
Read() [1/2]
bool CIccTagMeasurement::Read (icUInt32Number size, CIccIO * pIO) virtual inherited
Name: CIccTagMeasurement::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  if (sizeof(icTagTypeSignature) +
      sizeof(icUInt32Number) +
      sizeof(m_Data) > size)
    return false;
  if (!pIO) {
    return false;
  }
  if (!pIO->Read32(&sig))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  icUInt32Number nSize=sizeof(m_Data)/sizeof(icUInt32Number);
  if (pIO->Read32(&m_Data,nSize) != (icInt32Number)nSize)
    return false;
  return true;
}
References CIccTagMeasurement::m_Data, CIccTag::m_nReserved, and CIccIO::Read32().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
ToXml()
bool CIccTagXmlMeasurement::ToXml (std::string & xml, std::string blanks = "") virtual
Implements CIccTagXml.
{
  char buf[256];
  CIccInfo info;
  sprintf(buf,"<StandardObserver>%s</StandardObserver>\n",icGetStandardObserverName(m_Data.stdObserver));
  xml += blanks + buf;
  sprintf(buf, "<MeasurementBacking X=\"" icXmlFloatFmt "\" Y=\"" icXmlFloatFmt "\" Z=\"" icXmlFloatFmt "\"/>\n", icFtoD(m_Data.backing.X),
    icFtoD(m_Data.backing.Y), icFtoD(m_Data.backing.Z));
  xml += blanks + buf;
  sprintf(buf,"<Geometry>%s</Geometry>\n",info.GetMeasurementGeometryName(m_Data.geometry));
  xml += blanks + buf;
  sprintf(buf,"<Flare>%s</Flare>\n",info.GetMeasurementFlareName(m_Data.flare));
  xml += blanks + buf;
  sprintf(buf,"<StandardIlluminant>%s</StandardIlluminant>\n",info.GetIlluminantName(m_Data.illuminant));
  xml += blanks + buf;
  return true;
}
References icMeasurement::backing, icMeasurement::flare, icMeasurement::geometry, CIccInfo::GetIlluminantName(), CIccInfo::GetMeasurementFlareName(), CIccInfo::GetMeasurementGeometryName(), icFtoD(), icGetStandardObserverName(), icMeasurement::illuminant, CIccTagMeasurement::m_Data, icMeasurement::stdObserver, icXYZNumber::X, icXYZNumber::Y, and icXYZNumber::Z.
Validate()
icValidateStatus CIccTagMeasurement::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual inherited
Name: CIccTagMeasurement::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  switch(m_Data.stdObserver) {
  case icStdObsUnknown:
  case icStdObs1931TwoDegrees:
  case icStdObs1964TenDegrees:
    break;
  default:
    sReport += icMsgValidateNonCompliant;
    sReport += sSigPathName;
    sReport += " - Invalid standard observer encoding.\n";
    rv = icMaxStatus(rv, icValidateNonCompliant);
  }
  switch(m_Data.geometry) {
  case icGeometryUnknown:
  case icGeometry045or450:
  case icGeometry0dord0:
    break;
  default:
    sReport += icMsgValidateNonCompliant;
    sReport += sSigPathName;
    sReport += " - Invalid measurement geometry encoding.\n";
    rv = icMaxStatus(rv, icValidateNonCompliant);
  }
  switch(m_Data.illuminant) {
  case icIlluminantUnknown:
  case icIlluminantD50:
  case icIlluminantD65:
  case icIlluminantD93:
  case icIlluminantF2:
  case icIlluminantD55:
  case icIlluminantA:
  case icIlluminantEquiPowerE:
  case icIlluminantF8:
    break;
  default:
    sReport += icMsgValidateNonCompliant;
    sReport += sSigPathName;
    sReport += " - Invalid standard illuminant encoding.\n";
    rv = icMaxStatus(rv, icValidateNonCompliant);
  }
  return rv;
}
References icMeasurement::geometry, CIccInfo::GetSigPathName(), icGeometry045or450, icGeometry0dord0, icGeometryUnknown, icIlluminantA, icIlluminantD50, icIlluminantD55, icIlluminantD65, icIlluminantD93, icIlluminantEquiPowerE, icIlluminantF2, icIlluminantF8, icIlluminantUnknown, icMaxStatus(), icMsgValidateNonCompliant, icStdObs1931TwoDegrees, icStdObs1964TenDegrees, icStdObsUnknown, icValidateNonCompliant, icMeasurement::illuminant, CIccTagMeasurement::m_Data, icMeasurement::stdObserver, and CIccTag::Validate().
Write()
bool CIccTagMeasurement::Write (CIccIO * pIO) virtual inherited
Name: CIccTagMeasurement::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  if (!pIO)
   return false;
  if (!pIO->Write32(&sig))
   return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  icUInt32Number nSize=sizeof(m_Data)/sizeof(icUInt32Number);
  if (pIO->Write32(&m_Data,nSize) != (icInt32Number)nSize)
    return false;
  return true;
}
References CIccTagMeasurement::GetType(), CIccTagMeasurement::m_Data, CIccTag::m_nReserved, and CIccIO::Write32().
Field Documentation
m_Data
icMeasurement CIccTagMeasurement::m_Data inherited
Referenced by CIccTagMeasurement::CIccTagMeasurement(), CIccTagMeasurement::CIccTagMeasurement(), CIccTagMeasurement::Describe(), CIccTagMeasurement::operator=(), ParseXml(), CIccTagMeasurement::Read(), ToXml(), CIccTagMeasurement::Validate(), and CIccTagMeasurement::Write().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
The documentation for this class was generated from the following files:
IccXML/IccLibXML/IccTagXml.h
IccXML/IccLibXML/IccTagXml.cpp