iccDEV: Tools/CmdLine/IccCommon/IccJsonUtil.cpp File Reference
IccJsonUtil.cpp File Reference
#include "IccJsonUtil.h"
#include "IccUtil.h"
#include <stdio.h>
#include <string>
#include <sstream>
Functions
template<typename T >
std::string arrayToJson (T *a, int nCount)
template std::string arrayToJson< icInt16Number > (icInt16Number *, int)
template std::string arrayToJson< icInt32Number > (icInt32Number *, int)
template std::string arrayToJson< icInt64Number > (icInt64Number *, int)
template std::string arrayToJson< icInt8Number > (icInt8Number *, int)
template std::string arrayToJson< icUInt16Number > (icUInt16Number *, int)
template std::string arrayToJson< icUInt32Number > (icUInt32Number *, int)
template std::string arrayToJson< icUInt64Number > (icUInt64Number *, int)
template std::string arrayToJson< icUInt8Number > (icUInt8Number *, int)
std::string fixJsonString (const char *v)
bool jsonToArray (const json &v, std::vector< std::string > &vals)
template<typename T >
bool jsonToArray (const json &v, std::vector< T > &a)
template<typename T >
bool jsonToArray (const json &v, T *vals, int n)
template bool jsonToArray< double > (const json &, double *, int)
template bool jsonToArray< double > (const json &, std::vector< double > &)
template bool jsonToArray< float > (const json &, float *, int)
template bool jsonToArray< float > (const json &, std::vector< float > &)
template bool jsonToArray< icInt16Number > (const json &, icInt16Number *, int)
template bool jsonToArray< icInt16Number > (const json &, std::vector< icInt16Number > &)
template bool jsonToArray< icInt32Number > (const json &, icInt32Number *, int)
template bool jsonToArray< icInt32Number > (const json &, std::vector< icInt32Number > &)
template bool jsonToArray< icInt64Number > (const json &, icInt64Number *, int)
template bool jsonToArray< icInt64Number > (const json &, std::vector< icInt64Number > &)
template bool jsonToArray< icInt8Number > (const json &, icInt8Number *, int)
template bool jsonToArray< icInt8Number > (const json &, std::vector< icInt8Number > &)
template bool jsonToArray< icUInt16Number > (const json &, icUInt16Number *, int)
template bool jsonToArray< icUInt16Number > (const json &, std::vector< icUInt16Number > &)
template bool jsonToArray< icUInt32Number > (const json &, icUInt32Number *, int)
template bool jsonToArray< icUInt32Number > (const json &, std::vector< icUInt32Number > &)
template bool jsonToArray< icUInt64Number > (const json &, icUInt64Number *, int)
template bool jsonToArray< icUInt64Number > (const json &, std::vector< icUInt64Number > &)
template bool jsonToArray< icUInt8Number > (const json &, icUInt8Number *, int)
template bool jsonToArray< icUInt8Number > (const json &, std::vector< icUInt8Number > &)
bool jsonToColorSpace (const json &j, icColorSpaceSignature &sig)
bool jsonToCStr (const json &j, char *str, int nSize)
bool jsonToList (const json &v, std::list< std::string > &vals)
bool jsonToString (const json &j, std::string &value)
template<>
bool jsonToValue (const json &j, bool &value)
template<>
bool jsonToValue (const json &j, std::string &value)
template<typename T >
bool jsonToValue (const json &j, T &nValue)
template bool jsonToValue< double > (const json &, double &)
template bool jsonToValue< float > (const json &, float &)
template bool jsonToValue< icInt16Number > (const json &, icInt16Number &)
template bool jsonToValue< icInt64Number > (const json &, icInt64Number &)
template bool jsonToValue< icInt8Number > (const json &, icInt8Number &)
template bool jsonToValue< icUInt16Number > (const json &, icUInt16Number &)
template bool jsonToValue< icUInt32Number > (const json &, icUInt32Number &)
template bool jsonToValue< icUInt64Number > (const json &, icUInt64Number &)
template bool jsonToValue< icUInt8Number > (const json &, icUInt8Number &)
template bool jsonToValue< int > (const json &, int &)
bool loadJsonFrom (json &j, const char *szFname)
bool saveJsonAs (const json &j, const char *szFname, int indent)
template<>
std::string valueToJson (const char *name, char *v)
template<>
std::string valueToJson (const char *name, const char *v)
std::string valueToJson (const char *name, const char *v, bool &bPreviousLine)
template<>
std::string valueToJson (const char *name, const std::string &v)
template<typename T >
std::string valueToJson (const char *name, T v)
template std::string valueToJson< double > (const char *, double)
template std::string valueToJson< float > (const char *, float)
template std::string valueToJson< icInt16Number > (const char *, icInt16Number)
template std::string valueToJson< icInt32Number > (const char *, icInt32Number)
template std::string valueToJson< icInt64Number > (const char *, icInt64Number)
template std::string valueToJson< icInt8Number > (const char *, icInt8Number)
template std::string valueToJson< icUInt16Number > (const char *, icUInt16Number)
template std::string valueToJson< icUInt32Number > (const char *, icUInt32Number)
template std::string valueToJson< icUInt64Number > (const char *, icUInt64Number)
template std::string valueToJson< icUInt8Number > (const char *, icUInt8Number)
Function Documentation
arrayToJson()
template<typename T > std::string arrayToJson (T * a, int nCount)
{
  std::string str, num;
  str += "[ ";
  for (int i = 0; i < nCount; i++) {
    if (i)
      str += ", ";
    num = std::to_string(a[i]);
    str += num;
  }
  str += " ]";
  return str;
}
arrayToJson< icInt16Number >()
template std::string arrayToJson< icInt16Number > (icInt16Number * , int)
arrayToJson< icInt32Number >()
template std::string arrayToJson< icInt32Number > (icInt32Number * , int)
arrayToJson< icInt64Number >()
template std::string arrayToJson< icInt64Number > (icInt64Number * , int)
arrayToJson< icInt8Number >()
template std::string arrayToJson< icInt8Number > (icInt8Number * , int)
arrayToJson< icUInt16Number >()
template std::string arrayToJson< icUInt16Number > (icUInt16Number * , int)
arrayToJson< icUInt32Number >()
template std::string arrayToJson< icUInt32Number > (icUInt32Number * , int)
arrayToJson< icUInt64Number >()
template std::string arrayToJson< icUInt64Number > (icUInt64Number * , int)
arrayToJson< icUInt8Number >()
template std::string arrayToJson< icUInt8Number > (icUInt8Number * , int)
fixJsonString()
std::string fixJsonString (const char * v)
{
  std::string rv;
  for (; *v; v++) {
    if (*v == '\\')
      rv += "\\\\";
    else
      rv += *v;
  }
  return rv;
}
Referenced by valueToJson(), valueToJson(), and valueToJson().
jsonToArray() [1/3]
bool jsonToArray (const json & v, std::vector< std::string > & vals)
{
  if (v.is_array()) {
    size_t nSize = v.size();
    int nValid = 0;
    vals.resize(nSize);
    auto e = v.begin();
    for (int i = 0; e != v.end(); e++, i++) {
      if (e->is_string()) {
        vals[i] = e->get<std::string>();
        nValid++;
      }
      else {
        vals[i] = "";
      }
    }
    return nValid == nSize;
  }
  return false;
}
jsonToArray() [2/3]
template<typename T > bool jsonToArray (const json & v, std::vector< T > & a)
{
  if (v.is_array()) {
    size_t nSize = v.size();
    int nValid = 0;
    a.resize(nSize);
    auto e = v.begin();
    for (int i = 0; e != v.end(); e++, i++) {
      if (e->is_number()) {
        a[i] = e->get<T>();
        nValid++;
      }
      else {
        a[i] = 0;
      }
    }
    return nValid == v.size();
  }
  return false;
}
Referenced by CIccCfgDataEntry::fromJson().
jsonToArray() [3/3]
template<typename T > bool jsonToArray (const json & v, T * vals, int n)
{
  if (v.is_array()) {
    int nValid = 0;
    auto e = v.begin();
    for (int i = 0; e != v.end() && i < n; e++, i++) {
      if (e->is_number()) {
        vals[i] = e->get<T>();
        nValid++;
      }
    }
    return nValid == v.size();
  }
  return false;
}
jsonToArray< double >() [1/2]
template bool jsonToArray< double > (const json & , double * , int)
jsonToArray< double >() [2/2]
template bool jsonToArray< double > (const json & , std::vector< double > &)
jsonToArray< float >() [1/2]
template bool jsonToArray< float > (const json & , float * , int)
jsonToArray< float >() [2/2]
template bool jsonToArray< float > (const json & , std::vector< float > &)
jsonToArray< icInt16Number >() [1/2]
template bool jsonToArray< icInt16Number > (const json & , icInt16Number * , int)
jsonToArray< icInt16Number >() [2/2]
template bool jsonToArray< icInt16Number > (const json & , std::vector< icInt16Number > &)
jsonToArray< icInt32Number >() [1/2]
template bool jsonToArray< icInt32Number > (const json & , icInt32Number * , int)
jsonToArray< icInt32Number >() [2/2]
template bool jsonToArray< icInt32Number > (const json & , std::vector< icInt32Number > &)
jsonToArray< icInt64Number >() [1/2]
template bool jsonToArray< icInt64Number > (const json & , icInt64Number * , int)
jsonToArray< icInt64Number >() [2/2]
template bool jsonToArray< icInt64Number > (const json & , std::vector< icInt64Number > &)
jsonToArray< icInt8Number >() [1/2]
template bool jsonToArray< icInt8Number > (const json & , icInt8Number * , int)
jsonToArray< icInt8Number >() [2/2]
template bool jsonToArray< icInt8Number > (const json & , std::vector< icInt8Number > &)
jsonToArray< icUInt16Number >() [1/2]
template bool jsonToArray< icUInt16Number > (const json & , icUInt16Number * , int)
jsonToArray< icUInt16Number >() [2/2]
template bool jsonToArray< icUInt16Number > (const json & , std::vector< icUInt16Number > &)
jsonToArray< icUInt32Number >() [1/2]
template bool jsonToArray< icUInt32Number > (const json & , icUInt32Number * , int)
jsonToArray< icUInt32Number >() [2/2]
template bool jsonToArray< icUInt32Number > (const json & , std::vector< icUInt32Number > &)
jsonToArray< icUInt64Number >() [1/2]
template bool jsonToArray< icUInt64Number > (const json & , icUInt64Number * , int)
jsonToArray< icUInt64Number >() [2/2]
template bool jsonToArray< icUInt64Number > (const json & , std::vector< icUInt64Number > &)
jsonToArray< icUInt8Number >() [1/2]
template bool jsonToArray< icUInt8Number > (const json & , icUInt8Number * , int)
jsonToArray< icUInt8Number >() [2/2]
template bool jsonToArray< icUInt8Number > (const json & , std::vector< icUInt8Number > &)
jsonToColorSpace()
bool jsonToColorSpace (const json & j, icColorSpaceSignature & sig)
{
  std::string str;
  if (jsonToValue(j, str)) {
    if (str.size())
      sig = (icColorSpaceSignature)icGetSigVal(str.c_str());
    else
      sig = icSigUnknownData;
    return true;
  }
  return false;
}
References icGetSigVal(), and jsonToValue().
Referenced by CIccCfgDataApply::fromJson(), and CIccCfgColorData::fromJson().
jsonToCStr()
bool jsonToCStr (const json & j, char * str, int nSize)
{
  if (j.is_string() && nSize>0) {
    std::string val = j.get<std::string>();
    strncpy(str, val.c_str(), nSize);
    str[nSize - 1] = 0;
    return true;
  }
  return false;
}
jsonToList()
bool jsonToList (const json & v, std::list< std::string > & vals)
{
  if (v.is_array()) {
    size_t nSize = v.size();
    int nValid = 0;
    auto e = v.begin();
    for (int i = 0; e != v.end(); e++, i++) {
      if (e->is_string()) {
        vals.push_back(e->get<std::string>());
        nValid++;
      }
    }
    return nValid == nSize;
  }
  return false;
}
Referenced by CIccCfgDataEntry::fromJson().
jsonToString()
bool jsonToString (const json & j, std::string & value)
{
  if (j.is_string()) {
    value = j.get<std::string>();
    return true;
  }
  return false;
}
Referenced by jsonToValue().
jsonToValue() [1/3]
template<> bool jsonToValue (const json & j, bool & value)
{
  if (j.is_boolean()) {
    value = j.get<bool>();
    return true;
  }
  else if (j.is_number_float()) {
    // don't want to check for 0 due to floating point messiness. If the value is greater than 0.5, then
    // it's definitely not 0.
    value = j.get<float>() > 0.5;
    return true;
  }
  else if (j.is_number_integer()) {
    value = j.get<int>() != 0;
    return true;
  }
  else if (j.is_number_unsigned()) {
    value = j.get<unsigned>() != 0;
    return true;
  }
  return false;
}
jsonToValue() [2/3]
template<> bool jsonToValue (const json & j, std::string & value)
{
  return jsonToString(j, value);
}
References jsonToString().
jsonToValue() [3/3]
template<typename T > bool jsonToValue (const json & j, T & nValue)
{
  if (j.is_number()) {
    nValue = j.get<T>();
    return true;
  }
  return false;
}
Referenced by CIccCfgDataApply::fromJson(), CIccCfgImageApply::fromJson(), CIccCfgCreateLink::fromJson(), CIccCfgProfile::fromJson(), CIccCfgDataEntry::fromJson(), CIccCfgColorData::fromJson(), jsonToColorSpace(), jsonToValue(), jsonToValue(), and jsonToValue().
jsonToValue< double >()
template bool jsonToValue< double > (const json & , double &)
jsonToValue< float >()
template bool jsonToValue< float > (const json & , float &)
jsonToValue< icInt16Number >()
template bool jsonToValue< icInt16Number > (const json & , icInt16Number &)
jsonToValue< icInt64Number >()
template bool jsonToValue< icInt64Number > (const json & , icInt64Number &)
jsonToValue< icInt8Number >()
template bool jsonToValue< icInt8Number > (const json & , icInt8Number &)
jsonToValue< icUInt16Number >()
template bool jsonToValue< icUInt16Number > (const json & , icUInt16Number &)
jsonToValue< icUInt32Number >()
template bool jsonToValue< icUInt32Number > (const json & , icUInt32Number &)
jsonToValue< icUInt64Number >()
template bool jsonToValue< icUInt64Number > (const json & , icUInt64Number &)
jsonToValue< icUInt8Number >()
template bool jsonToValue< icUInt8Number > (const json & , icUInt8Number &)
jsonToValue< int >()
template bool jsonToValue< int > (const json & , int &)
loadJsonFrom()
bool loadJsonFrom (json & j, const char * szFname)
{
  bool rv = false;
  j.clear();
  FILE* f = fopen(szFname, "rb");
  if (f) {
    fseek(f, 0, SEEK_END);
    unsigned long flen = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* buf = (char*)malloc(flen+1);
    if (buf) {
      buf[flen] = 0;
      if (fread(buf, 1, flen, f) == flen) {
        try {
          j = json::parse(buf);
          rv = true;
        }
        catch (...) {
        }
      }
      free(buf);
    }
    fclose(f);
  }
  return rv;
}
Referenced by main(), and main().
saveJsonAs()
bool saveJsonAs (const json & j, const char * szFname, int indent)
{
  if (!j.is_object())
    return false;
  bool rv = false;
  FILE* f;
  if (szFname && szFname[0])
    f = fopen(szFname, "wb");
  else
    f = stdout;
  if (f) {
    std::string str = j.dump(indent);
    if (fwrite((void*)(str.c_str()), 1, (unsigned long)str.size(), f) == (long)str.size())
      rv = true;
    if (f!=stdout)
      fclose(f);
  }
  return rv;
}
Referenced by main().
valueToJson() [1/5]
template<> std::string valueToJson (const char * name, char * v)
{
  if (!name) {
    throw std::invalid_argument("name cannot be null");
  }
  if (!v) {
    return "\"" + std::string(name) + "\": null";
  }
  return "\"" + std::string(name) + "\": \"" + fixJsonString(v) + "\"";
}
References fixJsonString().
valueToJson() [2/5]
template<> std::string valueToJson (const char * name, const char * v)
{
  if (!name) {
    throw std::invalid_argument("name cannot be null");
  }
  if (!v) {
    return "\"" + std::string(name) + "\": null";
  }
  return "\"" + std::string(name) + "\": \"" + fixJsonString(v) + "\"";
}
References fixJsonString().
valueToJson() [3/5]
std::string valueToJson (const char * name, const char * v, bool & bPreviousLine)
{
  if (!name) {
    throw std::invalid_argument("name cannot be null");
  }
  if (v && *v) {
    std::string str = valueToJson(name, v);
    if (bPreviousLine) {
      return ", " + str;
    }
    bPreviousLine = true;
    return str;
  }
  return {};
}
References valueToJson().
valueToJson() [4/5]
template<> std::string valueToJson (const char * name, const std::string & v)
{
  if (!name) {
    throw std::invalid_argument("name cannot be null");
  }
  return "\"" + std::string(name) + "\": \"" + fixJsonString(v.c_str()) + "\"";
}
References fixJsonString().
valueToJson() [5/5]
template<typename T > std::string valueToJson (const char * name, T v)
{
  // Safeguard for nullptr name
  if (!name) {
    throw std::invalid_argument("name cannot be null");
  }
  return std::string("\"") + name + "\": " + std::to_string(v);
}
Referenced by valueToJson().
valueToJson< double >()
template std::string valueToJson< double > (const char * , double)
valueToJson< float >()
template std::string valueToJson< float > (const char * , float)
valueToJson< icInt16Number >()
template std::string valueToJson< icInt16Number > (const char * , icInt16Number)
valueToJson< icInt32Number >()
template std::string valueToJson< icInt32Number > (const char * , icInt32Number)
valueToJson< icInt64Number >()
template std::string valueToJson< icInt64Number > (const char * , icInt64Number)
valueToJson< icInt8Number >()
template std::string valueToJson< icInt8Number > (const char * , icInt8Number)
valueToJson< icUInt16Number >()
template std::string valueToJson< icUInt16Number > (const char * , icUInt16Number)
valueToJson< icUInt32Number >()
template std::string valueToJson< icUInt32Number > (const char * , icUInt32Number)
valueToJson< icUInt64Number >()
template std::string valueToJson< icUInt64Number > (const char * , icUInt64Number)
valueToJson< icUInt8Number >()
template std::string valueToJson< icUInt8Number > (const char * , icUInt8Number)