iccDEV: CIccStructBRDF Class Reference
CIccStructBRDF Class Reference
#include <IccStructBasic.h>
Public Member Functions
CIccStructBRDF (CIccTagStruct *pTagStruct=NULL)
virtual ~CIccStructBRDF ()
virtual void Describe (std::string &sDescription, int nVerboseness) const
virtual icSigBRDFFunction GetBRDFFunction () const
virtual icSigBRDFType GetBRDFType () const
virtual const icChar * GetClassName () const
virtual const icChar * GetDisplayName () const
CIccTag * GetElem (icSignature sigElem) const
virtual std::string GetElemName (icSignature sigElem) const
virtual icSignature GetElemSig (const icChar *szElemName) const
CIccTagStruct * GetTagStruct ()
virtual IIccStruct * NewCopy (CIccTagStruct *pNewTagStruct) const
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
Protected Member Functions
TagEntryList * getTagEntries () const
Protected Attributes
SIccElemNameSig * m_pElemNameSigTable
CIccTagStruct * m_pTagStruct
Detailed Description
Class: CIccStructBRDF
Purpose: The BRDF struct handler
Constructor & Destructor Documentation
CIccStructBRDF()
CIccStructBRDF::CIccStructBRDF (CIccTagStruct * pTagStruct = NULL)
{
  m_pTagStruct = pTagStruct;
  m_pElemNameSigTable = g_IccStructBRDFMbrTable;
}
References g_IccStructBRDFMbrTable, CIccStructUnknown::m_pElemNameSigTable, and IIccStruct::m_pTagStruct.
Referenced by CIccBasicStructFactory::CreateStruct(), and NewCopy().
~CIccStructBRDF()
CIccStructBRDF::~CIccStructBRDF () virtual
{
}
Member Function Documentation
Describe()
void CIccStructUnknown::Describe (std::string & sDescription, int nVerboseness) const virtual inherited
Reimplemented from IIccStruct.
{
  char buf[256];
  CIccInfo info;
  int n;
  if (m_pTagStruct) {
    TagEntryList *entries = m_pTagStruct->GetElemList();
    TagEntryList::iterator i;
    for (n=0, i=entries->begin(); i!=entries->end(); n++, i++) {
      if (i->pTag) {
        if (n)
          sDescription += "\n";
        sprintf(buf, "Begin SubTag(%s)\n", GetElemName(i->TagInfo.sig).c_str());
        sDescription += buf;
        i->pTag->Describe(sDescription, nVerboseness);
        sprintf(buf, "End SubTag(%s)\n", GetElemName(i->TagInfo.sig).c_str());
        sDescription += buf;
      }
    }
  }
}
References CIccTag::Describe(), CIccTagStruct::GetElemList(), CIccStructUnknown::GetElemName(), IIccStruct::m_pTagStruct, and icTag::sig.
Referenced by CIccTagStruct::Describe().
GetBRDFFunction()
icSigBRDFFunction CIccStructBRDF::GetBRDFFunction () const virtual
{
  CIccTag* pTag = GetElem(icSigBrdfFunctionMbr);
  if (pTag)
  {
    if (pTag->GetType() == icSigSignatureType)
    {
      CIccTagSignature* pTagSig = dynamic_cast<CIccTagSignature*>(pTag);
      if (pTagSig)
        return  (icSigBRDFFunction)pTagSig->GetValue();
    }
  }
  return (icSigBRDFFunction)icSigUnknownType;
}
References CIccStructUnknown::GetElem(), CIccTag::GetType(), CIccTagSignature::GetValue(), icSigBrdfFunctionMbr, and icSigSignatureType.
GetBRDFType()
icSigBRDFType CIccStructBRDF::GetBRDFType () const virtual
{
  CIccTag* pTag = GetElem(icSigBrdfTypeMbr);
  if (pTag)
  {
    if (pTag->GetType() == icSigSignatureType)
    {
      CIccTagSignature* pTagSig = dynamic_cast<CIccTagSignature*>(pTag);
      if (pTagSig)
        return  (icSigBRDFType)pTagSig->GetValue();
    }
  }
  return (icSigBRDFType)icSigUnknownType;
}
References CIccStructUnknown::GetElem(), CIccTag::GetType(), CIccTagSignature::GetValue(), icSigBrdfTypeMbr, and icSigSignatureType.
GetClassName()
virtual const icChar * CIccStructBRDF::GetClassName () const inline virtual
Reimplemented from CIccStructUnknown.
{ return "CIccStructBRDF"; }
GetDisplayName()
virtual const icChar * CIccStructBRDF::GetDisplayName () const inline virtual
Reimplemented from CIccStructUnknown.
{ return "brdfTransformStructure"; }
GetElem()
CIccTag * CIccStructUnknown::GetElem (icSignature sigElem) const inherited
{
  if (!m_pTagStruct)
    return NULL;
  return m_pTagStruct->FindElem(sigElem);
}
References CIccTagStruct::FindElem(), and IIccStruct::m_pTagStruct.
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), GetBRDFFunction(), GetBRDFType(), and CIccStructNamedColor::GetNumArray().
GetElemName()
std::string CIccStructUnknown::GetElemName (icSignature sigElem) const virtual inherited
Implements IIccStruct.
{
  if (m_pElemNameSigTable) {
    int i;
    for (i = 0; m_pElemNameSigTable[i].szName; i++) {
      if (m_pElemNameSigTable[i].nSig == sigElem)
        return m_pElemNameSigTable[i].szName;
    }
  }
  CIccInfo info;
  std::string str;
  str = "PrivateSubTag";
  //str += info.GetSigName(sigElem);
  return str;
}
References CIccStructUnknown::m_pElemNameSigTable, SIccElemNameSig::nSig, and SIccElemNameSig::szName.
Referenced by CIccStructUnknown::Describe().
GetElemSig()
icSignature CIccStructUnknown::GetElemSig (const icChar * szElemName) const virtual inherited
Implements IIccStruct.
{
  if (m_pElemNameSigTable) {
    int i;
    for (i = 0; m_pElemNameSigTable[i].szName; i++) {
      if (!strcmp(m_pElemNameSigTable[i].szName, szElemName))
        return m_pElemNameSigTable[i].nSig;
    }
  }
  return (icSignature)0;
}
References CIccStructUnknown::m_pElemNameSigTable, SIccElemNameSig::nSig, and SIccElemNameSig::szName.
getTagEntries()
TagEntryList * IIccStruct::getTagEntries () const protected inherited
{
  if (m_pTagStruct)
    return m_pTagStruct->m_ElemEntries;
  return NULL;
}
References CIccTagStruct::m_ElemEntries, and IIccStruct::m_pTagStruct.
Referenced by CIccStructUnknown::Validate().
GetTagStruct()
CIccTagStruct * IIccStruct::GetTagStruct () inline inherited
{ return m_pTagStruct; }
References IIccStruct::m_pTagStruct.
NewCopy()
IIccStruct * CIccStructBRDF::NewCopy (CIccTagStruct * pNewTagStruct) const virtual
Reimplemented from CIccStructUnknown.
{
  CIccStructBRDF *rv = new CIccStructBRDF(pTagStruct);
  return rv;
}
References CIccStructBRDF().
Validate()
icValidateStatus CIccStructBRDF::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Reimplemented from CIccStructUnknown.
{
  icValidateStatus rv = icValidateOK;
  if (m_pTagStruct) {
    if (!m_pTagStruct->FindElem(icSigBrdfTypeMbr) || !m_pTagStruct->FindElem(icSigBrdfFunctionMbr) ||
        !m_pTagStruct->FindElem(icSigBrdfParamsPerChannelMbr) || !m_pTagStruct->FindElem(icSigBrdfTransformMbr)) {
      CIccInfo Info;
      std::string sSigPathName = Info.GetSigPathName(sigPath);
      rv = icValidateCriticalError;
      sReport += icMsgValidateWarning;
      sReport += sSigPathName;
      sReport += " - Missing required struct member(s).\n";
    }
  }
  return icMaxStatus(rv, CIccStructUnknown::Validate(sigPath, sReport, pProfile));
}
References CIccTagStruct::FindElem(), CIccInfo::GetSigPathName(), icMaxStatus(), icMsgValidateWarning, icSigBrdfFunctionMbr, icSigBrdfParamsPerChannelMbr, icSigBrdfTransformMbr, icSigBrdfTypeMbr, icValidateCriticalError, icValidateOK, IIccStruct::m_pTagStruct, and CIccStructUnknown::Validate().
Field Documentation
m_pElemNameSigTable
SIccElemNameSig* CIccStructUnknown::m_pElemNameSigTable protected inherited
Referenced by CIccStructBRDF(), CIccStructColorantInfo::CIccStructColorantInfo(), CIccStructColorEncodingParams::CIccStructColorEncodingParams(), CIccStructMeasurementInfo::CIccStructMeasurementInfo(), CIccStructNamedColor::CIccStructNamedColor(), CIccStructProfileInfo::CIccStructProfileInfo(), CIccStructTintZero::CIccStructTintZero(), CIccStructUnknown::CIccStructUnknown(), CIccStructUnknown::GetElemName(), and CIccStructUnknown::GetElemSig().
m_pTagStruct
CIccTagStruct* IIccStruct::m_pTagStruct protected inherited
Referenced by CIccStructBRDF(), CIccStructColorantInfo::CIccStructColorantInfo(), CIccStructColorEncodingParams::CIccStructColorEncodingParams(), CIccStructMeasurementInfo::CIccStructMeasurementInfo(), CIccStructNamedColor::CIccStructNamedColor(), CIccStructProfileInfo::CIccStructProfileInfo(), CIccStructTintZero::CIccStructTintZero(), CIccStructUnknown::CIccStructUnknown(), CIccStructUnknown::Describe(), IIccStruct::Describe(), CIccStructUnknown::GetElem(), CIccStructNamedColor::getName(), IIccStruct::getTagEntries(), IIccStruct::GetTagStruct(), CIccStructNamedColor::Validate(), Validate(), and CIccStructColorantInfo::Validate().
The documentation for this class was generated from the following files:
IccProfLib/IccStructBasic.h
IccProfLib/IccStructBasic.cpp