iccDEV: CIccApplyMpeSpectralCLUT Class Reference
CIccApplyMpeSpectralCLUT Class Reference
#include <IccMpeSpectral.h>
Public Member Functions
virtual ~CIccApplyMpeSpectralCLUT ()
void Apply (icFloatNumber *pDestPixel, const icFloatNumber *pSrcPixel)
virtual const icChar * GetClassName () const
CIccMultiProcessElement * GetElem () const
virtual icElemTypeSignature GetType () const
Protected Member Functions
CIccApplyMpeSpectralCLUT (CIccMultiProcessElement *pElem, CIccApplyCLUT *pApply)
Protected Attributes
CIccApplyCLUT * m_pApply
CIccApplyTagMpe * m_pApplyTag
CIccMultiProcessElement * m_pElem
Detailed Description
Class: CIccApplyMpeSpectralCLUT
Purpose : The SpectralCLUT element apply data
Constructor & Destructor Documentation
~CIccApplyMpeSpectralCLUT()
CIccApplyMpeSpectralCLUT::~CIccApplyMpeSpectralCLUT () virtual
Name: CIccApplyMpeSpectralCLUT::~CIccApplyMpeSpectralCLUT
Purpose: Destructor
{
  if (m_pApply)
    delete m_pApply;
}
References m_pApply.
CIccApplyMpeSpectralCLUT()
CIccApplyMpeSpectralCLUT::CIccApplyMpeSpectralCLUT (CIccMultiProcessElement * pElem, CIccApplyCLUT * pApply) protected
Name: CIccApplyMpeSpectralCLUT::CIccApplyMpeSpectralCLUT
Purpose: Constructor
                                                                                                        : CIccApplyMpe(pElem)
{
  m_pApply = pApply;
}
References CIccApplyMpe::CIccApplyMpe(), and m_pApply.
Referenced by CIccMpeSpectralCLUT::GetNewApply().
Member Function Documentation
Apply()
void CIccApplyMpe::Apply (icFloatNumber * pDestPixel, const icFloatNumber * pSrcPixel) inline inherited
{ m_pElem->Apply(this, pDestPixel, pSrcPixel); }
References CIccMultiProcessElement::Apply(), and CIccApplyMpe::m_pElem.
Referenced by CIccTagMultiProcessElement::Apply(), and CIccSubCalcApply::Apply().
GetClassName()
virtual const icChar * CIccApplyMpeSpectralCLUT::GetClassName () const inline virtual
Reimplemented from CIccApplyMpe.
{ return "CIccApplyMpeSpectralCLUT"; }
GetElem()
CIccMultiProcessElement * CIccApplyMpe::GetElem () const inline inherited
{ return m_pElem; }
References CIccApplyMpe::m_pElem.
Referenced by CIccTagMultiProcessElement::Apply(), CIccSubCalcApply::NumInputChannels(), and CIccSubCalcApply::NumOutputChannels().
GetType()
virtual icElemTypeSignature CIccApplyMpeSpectralCLUT::GetType () const inline virtual
Reimplemented from CIccApplyMpe.
{ return m_pElem->GetType(); }
References CIccMultiProcessElement::GetType(), and CIccApplyMpe::m_pElem.
Field Documentation
m_pApply
CIccApplyCLUT* CIccApplyMpeSpectralCLUT::m_pApply protected
Referenced by CIccApplyMpeSpectralCLUT(), ~CIccApplyMpeSpectralCLUT(), and CIccMpeSpectralCLUT::Apply().
m_pApplyTag
CIccApplyTagMpe* CIccApplyMpe::m_pApplyTag protected inherited
Referenced by CIccApplyMpe::CIccApplyMpe().
m_pElem
CIccMultiProcessElement* CIccApplyMpe::m_pElem protected inherited
Referenced by CIccApplyMpe::CIccApplyMpe(), CIccApplyMpe::Apply(), CIccApplyMpe::GetElem(), and GetType().
The documentation for this class was generated from the following files:
IccProfLib/IccMpeSpectral.h
IccProfLib/IccMpeSpectral.cpp