iccDEV: CIccOpDefEnvVar Class Reference
CIccOpDefEnvVar Class Reference
Public Member Functions
virtual int ArgsPushed (CIccMpeCalculator *pCalc, SIccCalcOp &op)
virtual int ArgsUsed (CIccMpeCalculator *pCalc, SIccCalcOp &op)
virtual void Describe (SIccCalcOp &op, std::string &desc, int nVerboseness)
virtual bool Exec (SIccCalcOp *op, SIccOpState &os)
virtual bool IsValid (CIccMpeCalculator *pCalc, SIccCalcOp &op)
Detailed Description
Member Function Documentation
ArgsPushed()
virtual int IIccOpDef::ArgsPushed (CIccMpeCalculator * pCalc, SIccCalcOp & op) inline virtual inherited
{ return op.ArgsPushed(pCalc);}
References SIccCalcOp::ArgsPushed().
ArgsUsed()
virtual int IIccOpDef::ArgsUsed (CIccMpeCalculator * pCalc, SIccCalcOp & op) inline virtual inherited
{ return op.ArgsUsed(pCalc);}
References SIccCalcOp::ArgsUsed().
Describe()
virtual void IIccOpDef::Describe (SIccCalcOp & op, std::string & desc, int nVerboseness) inline virtual inherited
{op.Describe(desc, nVerboseness);}
References SIccCalcOp::Describe().
Exec()
virtual bool CIccOpDefEnvVar::Exec (SIccCalcOp * op, SIccOpState & os) inline virtual
Reimplemented from IIccOpDef.
  {
    icSigCmmEnvVar sig = (icSigCmmEnvVar) op->data.size;
    icFloatNumber val=0.0;
    if (sig==icSigTrueVar) {
      OsPushArg((icFloatNumber)1.0);
      OsPushArg((icFloatNumber)1.0);
    }
    else if (sig==icSigNotDefVar) {
      OsPushArg((icFloatNumber)0.0);
      OsPushArg((icFloatNumber)0.0);
    }
    else if (os.pApply->GetEnvVar(sig, val)) {
      OsPushArg((icFloatNumber)val);
      OsPushArg((icFloatNumber)1.0);
    }
    else {
      OsPushArg((icFloatNumber)0.0);
      OsPushArg((icFloatNumber)0.0);
    }
    return true;
  }
References CIccApplyMpeCalculator::GetEnvVar(), icSigNotDefVar, icSigTrueVar, and SIccOpState::pApply.
IsValid()
virtual bool IIccOpDef::IsValid (CIccMpeCalculator * pCalc, SIccCalcOp & op) inline virtual inherited
Reimplemented in CIccOpDefInvalid.
{ return op.IsValidOp(pCalc); }
References SIccCalcOp::IsValidOp().
The documentation for this class was generated from the following file:
IccProfLib/IccMpeCalc.cpp