iccDEV: CIccCmmPccEnvVarHint Class Reference
CIccCmmPccEnvVarHint Class Reference
#include <IccEnvVar.h>
Inherits CIccCreateCmmPccEnvVarXformHint.
Public Member Functions
CIccCmmPccEnvVarHint (icCmmEnvSigMap &map)
virtual ~CIccCmmPccEnvVarHint ()
virtual IIccCmmEnvVarLookup * GetNewCmmEnvVarLookup () const
Protected Attributes
icCmmEnvSigMap * m_map
Detailed Description
Constructor & Destructor Documentation
CIccCmmPccEnvVarHint()
CIccCmmPccEnvVarHint::CIccCmmPccEnvVarHint (icCmmEnvSigMap & map)
{
  m_map = new icCmmEnvSigMap();
  *m_map = map;
}
References m_map.
Referenced by main(), and main().
~CIccCmmPccEnvVarHint()
CIccCmmPccEnvVarHint::~CIccCmmPccEnvVarHint () virtual
{
  delete m_map;
}
References m_map.
Member Function Documentation
GetNewCmmEnvVarLookup()
virtual IIccCmmEnvVarLookup * CIccCmmPccEnvVarHint::GetNewCmmEnvVarLookup () const inline virtual
{ return new CIccCmmVarLookup(*m_map); }
References CIccCmmVarLookup::CIccCmmVarLookup(), and m_map.
Field Documentation
m_map
icCmmEnvSigMap* CIccCmmPccEnvVarHint::m_map protected
Referenced by CIccCmmPccEnvVarHint(), ~CIccCmmPccEnvVarHint(), and GetNewCmmEnvVarLookup().
The documentation for this class was generated from the following files:
IccProfLib/IccEnvVar.h
IccProfLib/IccEnvVar.cpp