iccDEV: CIccTagXmlArray Class Reference
CIccTagXmlArray Class Reference
#include <IccTagXml.h>
Public Member Functions
virtual ~CIccTagXmlArray ()
bool AreAllOfType (icTagTypeSignature sigTagType)
bool AttachTag (icUInt32Number nIndex, CIccTag *pTag)
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
CIccTag * DetachTag (icUInt32Number nIndex, bool bDeleteFlag=false)
IIccArray * GetArrayHandler ()
virtual const char * GetClassName () const
virtual const char * GetExtClassName () const
virtual const char * GetExtDerivedClassName () const
virtual IIccExtensionTag * GetExtension ()
CIccTag * GetIndex (icUInt32Number index) const
icUInt32Number GetSize () const
Returns the size of the data array.
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
CIccTag * operator[] (icUInt32Number index) const
virtual bool ParseXml (xmlNode *pNode, std::string &parseStr)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
bool SetSize (icUInt32Number nSize)
virtual bool SetTagArrayType (icArraySignature sig)
virtual bool ToXml (std::string &xml, std::string blanks="")
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
static CIccTagArray * ParseMem (icUInt8Number *pMem, icUInt32Number size)
Data Fields
icUInt32Number m_nReserved
Protected Member Functions
void Cleanup ()
Protected Attributes
icUInt32Number m_nSize
IIccArray * m_pArray
icArraySignature m_sigArrayType
IccTagPtr * m_TagVals
Detailed Description
Constructor & Destructor Documentation
~CIccTagXmlArray()
virtual CIccTagXmlArray::~CIccTagXmlArray () inline virtual
{}
Member Function Documentation
AreAllOfType()
bool CIccTagArray::AreAllOfType (icTagTypeSignature sigTagType) inherited
Name: CIccTagArray::AreAllOftype
Purpose: checks if all array elements have type signature sigTagType Args: sigTagType Return: true if all elements are of type sigTagType, false otherwise
{
  icUInt32Number i;
  for (i=0; i<m_nSize; i++) {
    CIccTag *pTag = GetIndex(i);
    if (!pTag || pTag->GetType()!=sigTagType)
      return false;
  }
  return true;
}
References CIccTagArray::GetIndex(), CIccTag::GetType(), and CIccTagArray::m_nSize.
AttachTag()
bool CIccTagArray::AttachTag (icUInt32Number nIndex, CIccTag * pTag) inherited
Name: CIccTagArray::AttachTag
Purpose: Get a tag entry with a given signature
Args: nIndex - index of tag in array
Return: Pointer to desired tag struct entry, or NULL if not found.
{
  if (nIndex>m_nSize || !pTag) {
    return false;
  }
  if (m_TagVals[nIndex].ptr && m_TagVals[nIndex].ptr != pTag) {
    return false;
  }
  m_TagVals[nIndex].ptr = pTag;
  return true;
}
References CIccTagArray::m_nSize, and CIccTagArray::m_TagVals.
Cleanup()
void CIccTagArray::Cleanup () protected inherited
Name: CIccTagArray::Cleanup
Purpose: Detach from a pending IO object
{
  icUInt32Number i, j;
  CIccTag* pTag;
  for (i=0; i<m_nSize; i++) {
    pTag = m_TagVals[i].ptr;
    if (pTag) {
      for (j=i+1; j<m_nSize; j++) {
        if (m_TagVals[i].ptr==pTag)
          m_TagVals[i].ptr = NULL;
      }
      delete pTag;
      m_TagVals[i].ptr = NULL;
    }
  }
  if (m_TagVals)
    free(m_TagVals);
  m_TagVals = nullptr;
  if (m_pArray)
    delete m_pArray;
  m_pArray = NULL;
  m_sigArrayType = icSigUndefinedArray;
}
References icSigUndefinedArray, CIccTagArray::m_nSize, CIccTagArray::m_pArray, CIccTagArray::m_sigArrayType, and CIccTagArray::m_TagVals.
Referenced by CIccTagArray::~CIccTagArray(), CIccTagArray::operator=(), and CIccTagArray::Read().
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagArray::Describe (std::string & sDescription, int nVerboseness) virtual inherited
Name: CIccTagArray::Describe
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  std::string name;
  icChar buf[128];
  CIccInfo info;
  IIccArray *pArrayObj = GetArrayHandler();
  CIccArrayCreator::GetArraySigName(name, m_sigArrayType);
  sDescription += "BEGIN TAG_ARRAY \"";
  sDescription += name;
  sDescription += "\"\n\n";
  icUInt32Number i;
  for (i=0; i<m_nSize; i++) {
    if (i)
      sDescription += "\n";
    sprintf(buf, "BEGIN INDEX[%d]\n", i);
    sDescription +=  buf;
    if (m_TagVals[i].ptr) {
      m_TagVals[i].ptr->Describe(sDescription, nVerboseness);
    }
    sprintf(buf, "END INDEX[%d]\n", i);
    sDescription += buf;
  }
  sDescription += "\n";
  sDescription += "END TAG_ARRAY \"";
  sDescription += name;
  sDescription += "\"\n";
}
References CIccTag::Describe(), CIccTagArray::GetArrayHandler(), CIccArrayCreator::GetArraySigName(), CIccTagArray::m_nSize, CIccTagArray::m_sigArrayType, and CIccTagArray::m_TagVals.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
DetachTag()
CIccTag * CIccTagArray::DetachTag (icUInt32Number nIndex, bool bDeleteFlag = false) inherited
Name: CIccTagArray::DetachTag
Purpose: Detach tag value at given index
Args: nIndex - index of tag in array bDeleteFlag - flag indicating detached tag should be deleted
Return: Pointer to Detached tag struct entry, or NULL if not found or deleted.
{
   if (nIndex>m_nSize)
     return NULL;
   CIccTag *rv = m_TagVals[nIndex].ptr;
   m_TagVals[nIndex].ptr = NULL;
   if (bDeleteFlag) {
     delete rv;
     rv = NULL;
   }
   return rv;
}
References CIccTagArray::m_nSize, and CIccTagArray::m_TagVals.
GetArrayHandler()
IIccArray * CIccTagArray::GetArrayHandler () inherited
Name: CIccTagArray::GetArrayHandler
Purpose: Get Array object handler
Args:
Return: Pointer to an Array object handler for the associated array type
{
  if (!m_pArray) {
    m_pArray = CIccArrayCreator::CreateArray(m_sigArrayType, this);
  }
  return m_pArray;
}
References CIccArrayCreator::CreateArray(), CIccTagArray::m_pArray, and CIccTagArray::m_sigArrayType.
Referenced by CIccTagArray::Describe(), and icGetTagArrayHandler().
GetClassName()
virtual const char * CIccTagXmlArray::GetClassName () const inline virtual
Reimplemented from CIccTagArray.
{return "CIccTagXmlArray"; }
GetExtClassName()
virtual const char * CIccTagXml::GetExtClassName () const inline virtual inherited
Implements IIccExtensionTag.
{ return "CIccTagXml"; }
Referenced by icProfDescToXml(), and icXmlParseProfDesc().
GetExtDerivedClassName()
virtual const char * CIccTagXml::GetExtDerivedClassName () const inline virtual inherited
Implements IIccExtensionTag.
Reimplemented in CIccCurveXml.
{ return ""; }
GetExtension()
virtual IIccExtensionTag * CIccTagXmlArray::GetExtension () inline virtual
Reimplemented from CIccTag.
{return this; }
GetIndex()
CIccTag * CIccTagArray::GetIndex (icUInt32Number nIndex) const inherited
Name: CIccTagArray::GetIndex
Purpose: Get a tag entry with a given index
Args: nIndex - index of tag in array
Return: Pointer to desired tag entry, or NULL if not found.
{
  if (nIndex>m_nSize)
    return NULL;
  return m_TagVals[nIndex].ptr;
}
References CIccTagArray::m_nSize, and CIccTagArray::m_TagVals.
Referenced by CIccTagArray::AreAllOfType(), CIccArrayNamedColor::Begin(), CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagArray::operator[](), CIccArrayUnknown::Validate(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetSize()
icUInt32Number CIccTagArray::GetSize () const inline inherited
Returns the size of the data array.
{ return m_nSize; }
References CIccTagArray::m_nSize.
Referenced by CIccArrayNamedColor::Begin(), CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccArrayUnknown::Validate(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetTagArrayType()
virtual icArraySignature CIccTagArray::GetTagArrayType () const inline virtual inherited
Reimplemented from CIccTag.
{ return m_sigArrayType; }
References CIccTagArray::m_sigArrayType.
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagArray::GetType () const inline virtual inherited
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigTagArrayType; }
References icSigTagArrayType.
Referenced by CIccTagArray::Write().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
virtual CIccTag * CIccTagArray::NewCopy () const inline virtual inherited
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
{ return new CIccTagArray(*this);}
References CIccTagArray::CIccTagArray().
operator[]()
CIccTag * CIccTagArray::operator[] (icUInt32Number index) const inline inherited
{ return GetIndex(index); }
References CIccTagArray::GetIndex().
ParseMem()
static CIccTagArray * CIccTagArray::ParseMem (icUInt8Number * pMem, icUInt32Number size) static inherited
ParseXml()
bool CIccTagXmlArray::ParseXml (xmlNode * pNode, std::string & parseStr) virtual
Implements CIccTagXml.
{
  // parse each tag
  xmlNode *tagNode, *indexNode, *firstNode = pNode;;
  xmlAttr *attr;
  for (; pNode; pNode = pNode->next) {
    if (pNode->type == XML_ELEMENT_NODE)
      break;
  }
  if (!pNode) {
    parseStr += "Invalid Tag Array: ";
    if (firstNode)
      parseStr += (const char*)firstNode->name;
    else
      parseStr += ":";
    parseStr += "\n";
    return false;
  }
  std::string nodeName = (icChar*)pNode->name;
  icArraySignature sigArray = CIccArrayCreator::GetArraySig(nodeName.c_str());
  if (sigArray) {
    SetTagArrayType(sigArray);
    pNode = pNode->children;
  }
  else {
    tagNode = icXmlFindNode(firstNode, "ArraySignature");
    if (!tagNode) {
      parseStr += "Unable to find ArraySignature\n";
      return false;
    }
    if (tagNode->type == XML_ELEMENT_NODE && tagNode->children && tagNode->children->content) {
      sigArray = (icArraySignature)icGetSigVal(tagNode->children ? (const icChar*)tagNode->children->content : "");
      SetTagArrayType(sigArray);
    }
    else {
      parseStr += "Invalid XNode type for ArraySignature\n";
      return false;
    }
  }
  indexNode = icXmlFindNode(pNode, "ArrayTags");
  if (!indexNode)
    return false;
  int nMaxIndex = 0, n=0;
  for (tagNode = indexNode->children; tagNode; tagNode = tagNode->next) {
    if (tagNode->type == XML_ELEMENT_NODE) {
      nMaxIndex++;
    }
  }
  if (!SetSize(nMaxIndex))
    return false;
  n=0;
  for (tagNode = indexNode->children; tagNode; tagNode = tagNode->next) {
    if (tagNode->type == XML_ELEMENT_NODE) {
      CIccTag *pTag = NULL;
      icSignature sigTag = (icSignature)0;
      // get the tag signature
      icTagTypeSignature sigType = icGetTypeNameTagSig ((icChar*) tagNode->name);
      if (sigType==icSigUnknownType){
        xmlAttr *attr = icXmlFindAttr(pNode, "type");
        sigType = (icTagTypeSignature)icGetSigVal((icChar*) icXmlAttrValue(attr));
      }
      CIccInfo info;
      // create a tag based on the signature
      pTag = CIccTag::Create(sigType);
      IIccExtensionTag *pExt;
      if (pTag && (pExt = pTag->GetExtension()) && !strcmp(pExt->GetExtClassName(), "CIccTagXml")) {
        CIccTagXml* pXmlTag = (CIccTagXml*)pExt;
        if (pXmlTag->ParseXml(tagNode->children, parseStr)) {
          if ((attr=icXmlFindAttr(pNode, "reserved"))) {
            sscanf(icXmlAttrValue(attr), "%u", &pTag->m_nReserved);
          }
          if (!m_TagVals[n].ptr)
            m_TagVals[n].ptr = pTag;
          else {
            parseStr += "Tag Array Index ";
            parseStr += n;
            parseStr += " already filled!\n";
            return false;
          }
        }
        else {
          parseStr += "Unable to Parse xml node named  \"";
          parseStr += (icChar*)tagNode->name;
          parseStr += "\"\n";
          return false;
        }
      }
      n++;
    }
  }
  for (n=0; n<(int)m_nSize; n++) {
    if (!m_TagVals[n].ptr) {
      parseStr += "Undefined Array Tag at index ";
      parseStr += n;
      parseStr += "\n";
      return false;
    }
  }
  return true;
}
References CIccTag::Create(), CIccArrayCreator::GetArraySig(), IIccExtensionTag::GetExtClassName(), CIccTag::GetExtension(), icGetSigVal(), icGetTypeNameTagSig(), icXmlAttrValue(), icXmlFindAttr(), icXmlFindNode(), CIccTag::m_nReserved, CIccTagArray::m_nSize, CIccTagArray::m_TagVals, CIccTagXml::ParseXml(), CIccTagArray::SetSize(), and CIccTagArray::SetTagArrayType().
Read() [1/2]
bool CIccTagArray::Read (icUInt32Number size, CIccIO * pIO) virtual inherited
Name: CIccTagArray::Read
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  icUInt32Number headerSize = sizeof(icTagTypeSignature) +
    sizeof(icUInt32Number) +
    sizeof(icTagTypeSignature) +
    sizeof(icStructSignature) +
    sizeof(icUInt32Number);
  if (headerSize > size)
    return false;
  if (!pIO) {
    return false;
  }
  Cleanup();
  icUInt32Number nTagStart = pIO->Tell();
  if (!pIO->Read32(&sig))
    return false;
  icArraySignature sigArrayType;
  if (!pIO->Read32(&m_nReserved) ||
      !pIO->Read32(&sigArrayType))
    return false;
  SetTagArrayType(sigArrayType);
  icUInt32Number count, i, j;
  IccTagEntry TagEntry;
  TagEntry.pTag = NULL;
  if (!pIO->Read32(&count))
    return false;
  if (headerSize + count*sizeof(icPositionNumber) > size)
    return false;
  if (count) {
    icPositionNumber *tagPos = new icPositionNumber[count];
    if (!SetSize(count)) {
      delete[] tagPos;
      return false;
    }
    for (i=0; i<count; i++) {
      if (!pIO->Read32(&tagPos[i].offset) ||
          !pIO->Read32(&tagPos[i].size)) {
        delete [] tagPos;
        return false;
      }
    }
    for (i=0; i<count; i++) {
      if (!tagPos[i].offset || !tagPos[i].size) {
        m_TagVals[i].ptr = NULL;
        continue;
      }
      for (j=0; j<i; j++) {
        if (tagPos[i].offset == tagPos[j].offset)
          break;
      }
      if (j<i) {
        m_TagVals[i].ptr = m_TagVals[j].ptr;
      }
      else {
        if (tagPos[i].offset + tagPos[i].size > size) {
          delete [] tagPos;
          return false;
        }
        pIO->Seek(nTagStart + tagPos[i].offset, icSeekSet);
        icTagTypeSignature tagSig;
        pIO->Read32(&tagSig);
        pIO->Seek(nTagStart + tagPos[i].offset, icSeekSet);
        CIccTag *pTag = CIccTagCreator::CreateTag(tagSig);
        if (pTag) {
          if (!pTag->Read(tagPos[i].size, pIO)) {
            delete [] tagPos;
            return false;
          }
          m_TagVals[i].ptr = pTag;
        }
        else {
          delete [] tagPos;
          return false;
        }
      }
    }
    delete [] tagPos;
  }
  return true;
}
References CIccTagArray::Cleanup(), CIccTagCreator::CreateTag(), icSeekSet, CIccTag::m_nReserved, CIccTagArray::m_TagVals, icPositionNumber::offset, CIccTag::Read(), CIccIO::Read32(), CIccIO::Seek(), CIccTagArray::SetSize(), CIccTagArray::SetTagArrayType(), icPositionNumber::size, and CIccIO::Tell().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
SetSize()
bool CIccTagArray::SetSize (icUInt32Number nSize) inherited
Name: CIccTagArray::SetSize
Purpose: Sets the size of the tag array.
Args: nSize - number of tag entries,
{
  if (!m_nSize) {
    m_TagVals = (IccTagPtr*)calloc(nSize, sizeof(IccTagPtr));
    if (!m_TagVals) {
      m_nSize =0;
      return false;
    }
  }
  else {
    if (nSize<=m_nSize)
      return true;
    m_TagVals = (IccTagPtr*)icRealloc(m_TagVals, nSize*sizeof(IccTagPtr));
    if (!m_TagVals) {
      m_nSize = 0;
      return false;
    }
    memset(&m_TagVals[m_nSize], 0, (nSize-m_nSize)*sizeof(IccTagPtr));
  }
  m_nSize = nSize;
  return true;
}
References icRealloc(), CIccTagArray::m_nSize, and CIccTagArray::m_TagVals.
Referenced by ParseXml(), and CIccTagArray::Read().
SetTagArrayType()
bool CIccTagArray::SetTagArrayType (icArraySignature sig) virtual inherited
Name: CIccTagArray::~SetTagArrayType
Purpose: Set the signature of the tag array type. This also sets the m_pArray to allow array type specific handling to be utilized.
Args: sig - signature of array type
Return: true if sig is a recognized array type, false otherwise
{
  if (m_pArray)
    delete m_pArray;
  m_sigArrayType = sig;
  m_pArray = CIccArrayCreator::CreateArray(m_sigArrayType, this);
  return (m_pArray != NULL) || (m_sigArrayType == icSigUtf8TextTypeArray);
}
References CIccArrayCreator::CreateArray(), icSigUtf8TextTypeArray, CIccTagArray::m_pArray, and CIccTagArray::m_sigArrayType.
Referenced by CIccTagArray::CIccTagArray(), ParseXml(), and CIccTagArray::Read().
ToXml()
bool CIccTagXmlArray::ToXml (std::string & xml, std::string blanks = "") virtual
Implements CIccTagXml.
{
  std::string info;
  char buf[256], fix[256], line[256];
  std::string arrayName;
  std::string arrayBlanks = "";
  bool found = CIccArrayCreator::GetArraySigName(arrayName, m_sigArrayType, false);
  if (found) {
    sprintf(line, "<%s> ", arrayName.c_str());
    arrayBlanks = "  ";
  }
  else {
    // print out the struct signature
    sprintf(line, "<privateArray StructSignature=\"%s\"/> ", icFixXml(fix, icGetSigStr(buf, m_sigArrayType)));
    arrayName = "privateArray";
  }
  xml += blanks + line + "<ArrayTags>\n";
  int i;
  for (i=0; i<(int)m_nSize; i++) {
    CIccTag* pTag = m_TagVals[i].ptr;
    if (pTag) {
      CIccTagXml *pTagXml = (CIccTagXml*)(pTag->GetExtension());
      if (pTagXml) {
        const icChar* tagSig = icGetTagSigTypeName(pTag->GetType());
        // PrivateType - a type that does not belong to the list in the icc specs - custom for vendor.
        if ( !strcmp("PrivateType", tagSig) )
          sprintf(line, " <PrivateType type=\"%s\">\n",  icFixXml(fix, icGetSigStr(buf, pTag->GetType())));
        else
          sprintf(line, " <%s>\n", tagSig); //parent node is the tag type
        xml += blanks + arrayBlanks + line;
        //convert the rest of the tag to xml
        if (!pTagXml->ToXml(xml, blanks + arrayBlanks + " ")) {
          printf("Unable to output tag with type %s\n", icGetSigStr(buf, pTag->GetType()));
          return false;
        }
        sprintf(line, " </%s>\n\n",  tagSig);
        xml += blanks + arrayBlanks + line;
      }
      else {
        printf("Non XML tag in list with type %s!\n", icGetSigStr(buf, pTag->GetType()));
        return false;
      }
    }
  }
  xml += blanks + "</ArrayTags> </" + arrayName + ">\n";
  return true;
}
References CIccArrayCreator::GetArraySigName(), CIccTag::GetExtension(), CIccTag::GetType(), icFixXml(), icGetSigStr(), icGetTagSigTypeName(), CIccTagArray::m_nSize, CIccTagArray::m_sigArrayType, CIccTagArray::m_TagVals, and CIccTagXml::ToXml().
Validate()
icValidateStatus CIccTagArray::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual inherited
Name: CIccTagArray::Validate
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sigAryPath = sigPath + icGetSigPath(m_sigArrayType);
  if (m_pArray) {  //Should call GetArrayHandler before validate to get
    rv = icMaxStatus(rv, m_pArray->Validate(sigPath, sReport, pProfile));
  }
  else if (m_sigArrayType==icSigUtf8TextTypeArray) { //UTF8 text arrays are known
    //Check # of channels
    if (icGetFirstSigPathSig(sigPath) == icSigMaterialTypeArrayTag &&
        pProfile &&
        m_nSize != icGetMaterialColorSpaceSamples(pProfile->m_Header.mcs)) {
      std::string sSigPathName = Info.GetSigPathName(sigPath);
      sReport += icMsgValidateCriticalError;
      sReport += sSigPathName;
      sReport += " - Number of material channel names does not match MCS in header.\n";
      rv = icMaxStatus(rv, icValidateCriticalError);
    }
    icUInt32Number i;
    for (i=0; i<m_nSize; i++) {
      rv = icMaxStatus(rv, m_TagVals[i].ptr->Validate(sigAryPath, sReport, pProfile));
    }
  }
  else {
    icUInt32Number i;
    sReport += "Unknown tag array type - Validating array sub-tags\n";
    rv = icMaxStatus(rv, icValidateWarning);
    for (i=0; i<m_nSize; i++) {
      rv = icMaxStatus(rv, m_TagVals[i].ptr->Validate(sigAryPath, sReport, pProfile));
    }
  }
  return rv;
}
References CIccInfo::GetSigPathName(), icGetFirstSigPathSig(), icGetMaterialColorSpaceSamples(), icGetSigPath(), icMaxStatus(), icMsgValidateCriticalError, icSigMaterialTypeArrayTag, icSigUtf8TextTypeArray, icValidateCriticalError, icValidateWarning, CIccTagArray::m_nSize, CIccTagArray::m_pArray, CIccTagArray::m_sigArrayType, CIccTagArray::m_TagVals, icHeader::mcs, CIccTag::Validate(), and IIccArray::Validate().
Write()
bool CIccTagArray::Write (CIccIO * pIO) virtual inherited
Name: CIccTagArray::Write
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  if (!pIO)
    return false;
  icUInt32Number nTagStart = pIO->Tell();
  if (!pIO->Write32(&sig))
    return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  if (!pIO->Write32(&m_sigArrayType))
    return false;
  if (!pIO->Write32(&m_nSize))
    return false;
  if (m_nSize) {
    icUInt32Number i, j;
    icUInt32Number pos = pIO->Tell();
    //Write Unintialized TagPosition block
    icUInt32Number zero = 0;
    for (i=0; i<m_nSize; i++) {
      if (!pIO->Write32(&zero) || !pIO->Write32(&zero))
        return false;
    }
    icPositionNumber *tagPos = new icPositionNumber[m_nSize];
    if (!tagPos)
      return false;
    //Write Tags
    for (i=0; i<m_nSize; i++) {
      if (m_TagVals[i].ptr) {
        for (j=0; j<i; j++) {
          if (m_TagVals[i].ptr==m_TagVals[j].ptr)
            break;
        }
        if (j<i) {
          tagPos[i].offset = tagPos[j].offset;
          tagPos[i].size = tagPos[j].offset;
        }
        else {
          tagPos[i].offset = pIO->Tell() - nTagStart;
          if (!m_TagVals[i].ptr->Write(pIO)) {
            delete [] tagPos;
            return false;
          }
          tagPos[i].size =  pIO->Tell() - nTagStart - tagPos[i].offset;
          pIO->Align32();
        }
      }
      else {
        tagPos[i].offset = 0;
        tagPos[i].size = 0;
      }
    }
    icUInt32Number endPos = pIO->Tell();
    //Update TagPosition block
    pIO->Seek(pos, icSeekSet);
    for (i=0; i<m_nSize; i++) {
      if (!pIO->Write32(&tagPos[i].offset) ||
          !pIO->Write32(&tagPos[i].size)) {
          delete [] tagPos;
          return false;
      }
    }
    delete[] tagPos;
    pIO->Seek(endPos, icSeekSet);
  }
  return true;
}
References CIccIO::Align32(), CIccTagArray::GetType(), icSeekSet, CIccTag::m_nReserved, CIccTagArray::m_nSize, CIccTagArray::m_sigArrayType, CIccTagArray::m_TagVals, icPositionNumber::offset, CIccIO::Seek(), icPositionNumber::size, CIccIO::Tell(), CIccTag::Write(), and CIccIO::Write32().
Field Documentation
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_nSize
icUInt32Number CIccTagArray::m_nSize protected inherited
Referenced by CIccTagArray::CIccTagArray(), CIccTagArray::CIccTagArray(), CIccTagArray::CIccTagArray(), CIccTagArray::AreAllOfType(), CIccTagArray::AttachTag(), CIccTagArray::Cleanup(), CIccTagArray::Describe(), CIccTagArray::DetachTag(), CIccTagArray::GetIndex(), CIccTagArray::GetSize(), CIccTagArray::operator=(), ParseXml(), CIccTagArray::SetSize(), ToXml(), CIccTagArray::Validate(), and CIccTagArray::Write().
m_pArray
IIccArray* CIccTagArray::m_pArray protected inherited
Referenced by CIccTagArray::CIccTagArray(), CIccTagArray::CIccTagArray(), CIccTagArray::CIccTagArray(), CIccTagArray::Cleanup(), CIccTagArray::GetArrayHandler(), CIccTagArray::operator=(), CIccTagArray::SetTagArrayType(), and CIccTagArray::Validate().
m_sigArrayType
icArraySignature CIccTagArray::m_sigArrayType protected inherited
Referenced by CIccTagArray::CIccTagArray(), CIccTagArray::CIccTagArray(), CIccTagArray::Cleanup(), CIccTagArray::Describe(), CIccTagArray::GetArrayHandler(), CIccTagArray::GetTagArrayType(), CIccTagArray::operator=(), CIccTagArray::SetTagArrayType(), ToXml(), CIccTagArray::Validate(), and CIccTagArray::Write().
m_TagVals
IccTagPtr* CIccTagArray::m_TagVals protected inherited
Referenced by CIccTagArray::CIccTagArray(), CIccTagArray::CIccTagArray(), CIccTagArray::CIccTagArray(), CIccTagArray::AttachTag(), CIccTagArray::Cleanup(), CIccTagArray::Describe(), CIccTagArray::DetachTag(), CIccTagArray::GetIndex(), CIccTagArray::operator=(), ParseXml(), CIccTagArray::Read(), CIccTagArray::SetSize(), ToXml(), CIccTagArray::Validate(), and CIccTagArray::Write().
The documentation for this class was generated from the following files:
IccXML/IccLibXML/IccTagXml.h
IccXML/IccLibXML/IccTagXml.cpp