iccDEV: IIccStructFactory Class Reference
IIccStructFactory Class Reference abstract
#include <IccStructFactory.h>
Public Member Functions
virtual ~IIccStructFactory ()
virtual IIccStruct * CreateStruct (icStructSignature structTypeSig, CIccTagStruct *pTagStruct=NULL)=0
virtual icStructSignature GetStructSig (const icChar *structName)=0
virtual bool GetStructSigName (std::string &structName, icStructSignature structTypeSig, bool bFindUnknown)=0
Detailed Description
Class: IIccStructFactory
Purpose: IIccStructFactory is a factory pattern interface for CIccProcessStruct creation. This class is pure virtual.
Constructor & Destructor Documentation
~IIccStructFactory()
virtual IIccStructFactory::~IIccStructFactory () inline virtual
{}
Member Function Documentation
CreateStruct()
virtual IIccStruct * IIccStructFactory::CreateStruct (icStructSignature structTypeSig, CIccTagStruct * pTagStruct = NULL) pure virtual
Function: CreateStruct(structTypeSig) Create a element of type structTypeSig.
Parameter(s): structTypeSig = signature of the ICC element type for the element to be created
Returns a new IIStructObject object of the given signature type. If the element factory doesn't support creation of structs of type structTypeSig then it should return NULL.
Implemented in CIccBasicStructFactory.
Referenced by CIccStructCreator::DoCreateStruct().
GetStructSig()
virtual icStructSignature IIccStructFactory::GetStructSig (const icChar * structName) pure virtual
Function: GetStructSig(structName) Get signature of structure from display name.
Parameter(s): structName = struct display name
Returns signature of structure if it is recognized by the factory, 0 if the factory doesn't create structures with such a display name.
Implemented in CIccBasicStructFactory.
Referenced by CIccStructCreator::DoGetStructSig().
GetStructSigName()
virtual bool IIccStructFactory::GetStructSigName (std::string & structName, icStructSignature structTypeSig, bool bFindUnknown) pure virtual
Function: GeStructSigName(structTypeSig) Get display name of structTypeSig.
Parameter(s): structName = string to put element name into, structTypeSig = signature of the ICC element type to get a name for bFindUnknown = flag to indicate structName should be filled with unknown_sig name, (empty if false)
Returns true if struct type is recognized by the factory, false if the factory doesn't create structTypeSig elements.
Implemented in CIccBasicStructFactory.
Referenced by CIccStructCreator::DoGetStructSigName().
The documentation for this class was generated from the following file:
IccProfLib/IccStructFactory.h