iccDEV: IIccEncProfileConverter Class Reference
IIccEncProfileConverter Class Reference abstract
#include <IccEncoding.h>
Public Member Functions
virtual ~IIccEncProfileConverter ()
virtual icStatusEncConvert ConvertFromParams (CIccProfilePtr &newIcc, CIccTagStruct *pParams, icHeader *pHeader)=0
Static Public Member Functions
static IIccEncProfileConverter * GetHandler ()
static void SetEncProfileConverter (IIccEncProfileConverter *pConverter)
Detailed Description
Constructor & Destructor Documentation
~IIccEncProfileConverter()
virtual IIccEncProfileConverter::~IIccEncProfileConverter () inline virtual
{}
Member Function Documentation
ConvertFromParams()
virtual icStatusEncConvert IIccEncProfileConverter::ConvertFromParams (CIccProfilePtr & newIcc, CIccTagStruct * pParams, icHeader * pHeader) pure virtual
Implemented in CIccDefaultEncProfileConverter.
Referenced by icConvertEncodingProfile().
GetHandler()
IIccEncProfileConverter * IIccEncProfileConverter::GetHandler () static
{
  if (!g_pEncProfileConverter) {
    g_pEncProfileConverter = new CIccDefaultEncProfileConverter();
  }
  return g_pEncProfileConverter;
}
References CIccDefaultEncProfileConverter::CIccDefaultEncProfileConverter(), and g_pEncProfileConverter.
Referenced by icConvertEncodingProfile().
SetEncProfileConverter()
void IIccEncProfileConverter::SetEncProfileConverter (IIccEncProfileConverter * pConverter) static
{
  if (pConverter) {
    if (g_pEncProfileConverter) {
      delete g_pEncProfileConverter;
    }
    g_pEncProfileConverter = pConverter;
  }
}
References g_pEncProfileConverter.
The documentation for this class was generated from the following files:
IccProfLib/IccEncoding.h
IccProfLib/IccEncoding.cpp