iccDEV: CIccTagUtf8Text Class Reference
CIccTagUtf8Text Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagUtf8Text ()
CIccTagUtf8Text (const CIccTagUtf8Text &ITT)
virtual ~CIccTagUtf8Text ()
icUInt32Number Capacity () const
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
icUChar * GetBuffer (icUInt32Number nSize)
virtual const icChar * GetClassName () const
virtual IIccExtensionTag * GetExtension ()
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
const icUChar * GetText () const
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
CIccTagUtf8Text & operator= (const CIccTagUtf8Text &TextTag)
const icChar * operator= (const icChar *szText)
const icUChar * operator= (const icUChar *szText)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
void Release ()
void SetText (const icChar *szText)
void SetText (const icUChar *szText)
void SetText (const icUChar16 *szText)
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
Protected Attributes
icUInt32Number m_nBufSize
icUChar * m_szText
Detailed Description
Class: CIccTagUtf8Text()
Purpose: The utf8TextType ICC tag
Constructor & Destructor Documentation
CIccTagUtf8Text() [1/2]
CIccTagUtf8Text::CIccTagUtf8Text ()
Name: CIccTagUtf8Text::CIccTagUtf8Text
Purpose: Constructor
{
  m_szText = (icUChar*)malloc(1);
  m_szText[0] = '\0';
  m_nBufSize = 1;
}
References m_nBufSize, and m_szText.
Referenced by CIccTagXmlUtf8Text::CIccTagXmlUtf8Text().
CIccTagUtf8Text() [2/2]
CIccTagUtf8Text::CIccTagUtf8Text (const CIccTagUtf8Text & ITT)
Name: CIccTagUtf8Text::CIccTagUtf8Text
Purpose: Copy Constructor
Args: ITT = The CIccTagText object to be copied
{
  m_szText = (icUChar*)malloc(1);
  m_szText[0] = '\0';
  m_nBufSize = 1;
  SetText(ITT.m_szText);
}
References m_nBufSize, m_szText, and SetText().
Referenced by CIccTagXmlUtf8Text::CIccTagXmlUtf8Text(), and NewCopy().
~CIccTagUtf8Text()
CIccTagUtf8Text::~CIccTagUtf8Text () virtual
Name: CIccTagUtf8Text::~CIccTagUtf8Text
Purpose: Destructor
{
  free(m_szText);
}
References m_szText.
Member Function Documentation
Capacity()
icUInt32Number CIccTagUtf8Text::Capacity () const inline
{ return m_nBufSize; }
References m_nBufSize.
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagUtf8Text::Describe (std::string & sDescription, int nVerboseness) virtual
Name: CIccTagUtf8Text::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  sDescription += "UTF8 Length = ";
  if (m_szText && *m_szText) {
    char buf[40];
    sprintf(buf, "%d bytes\n", m_nBufSize);
    sDescription += buf;
  }
  else
    sDescription += "0 (NULL)";
  if (nVerboseness > 25) {
    sDescription += "\"";
    if (m_szText && *m_szText) {
      if ((nVerboseness > 50) || (m_nBufSize < BRIEF_STRING_SIZE)) {
        // output entire string if short or doing verbose output
        sDescription += (icChar*)m_szText;
      }
      else {
         // copy just first part of string to keep nVerboseness under control
         char buf[BRIEF_STRING_SIZE + 1];
         strncpy(buf, (icChar*)m_szText, BRIEF_STRING_SIZE);
         buf[BRIEF_STRING_SIZE] = '\0'; // ensure NULL termination
         sDescription += buf;
         sDescription += "\n... <!truncated!>";
      }
    }
    sDescription += "\"\n";
  }
}
References m_nBufSize, and m_szText.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
GetBuffer()
icUChar * CIccTagUtf8Text::GetBuffer (icUInt32Number nSize)
Name: CIccTagUtf8Text::GetBuffer
Purpose: This function allocates room and returns pointer to data buffer to put string into
Args: nSize = Requested size of data buffer.
Return: The character buffer array
{
  if (m_nBufSize < nSize) {
    m_szText = (icUChar*)icRealloc(m_szText, nSize+1);
    if (m_szText) {
      m_szText[nSize] = '\0';
      m_nBufSize = nSize;
    }
    else {
      m_nBufSize = 0;
    }
  }
  return m_szText;
}
References icRealloc(), m_nBufSize, and m_szText.
Referenced by Read(), and SetText().
GetClassName()
virtual const icChar * CIccTagUtf8Text::GetClassName () const inline virtual
Reimplemented from CIccTag.
Reimplemented in CIccTagXmlUtf8Text.
{ return "CIccUtf8TagText"; }
GetExtension()
virtual IIccExtensionTag * CIccTag::GetExtension () inline virtual inherited
Reimplemented in CIccTagXmlUnknown, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, CIccTagXmlSignature, CIccTagXmlNamedColor2, CIccTagXmlXYZ, CIccTagXmlChromaticity, CIccTagXmlCicp, CIccTagXmlSparseMatrixArray, CIccTagXmlFixedNum< T, Tsig >, CIccTagXmlNum< T, A, Tsig >, CIccTagXmlFloatNum< T, A, Tsig >, CIccTagXmlMeasurement, CIccTagXmlMultiLocalizedUnicode, CIccTagXmlTagData, CIccTagXmlDateTime, CIccTagXmlColorantOrder, CIccTagXmlColorantTable, CIccTagXmlViewingConditions, CIccTagXmlSpectralDataInfo, CIccTagXmlSpectralViewingConditions, CIccTagXmlProfileSeqDesc, CIccTagXmlResponseCurveSet16, CIccTagXmlCurve, CIccTagXmlParametricCurve, CIccTagXmlSegmentedCurve, CIccTagXmlLutAtoB, CIccTagXmlLutBtoA, CIccTagXmlLut8, CIccTagXmlLut16, CIccTagXmlMultiProcessElement, CIccTagXmlProfileSequenceId, CIccTagXmlDict, CIccTagXmlStruct, CIccTagXmlArray, CIccTagXmlGamutBoundaryDesc, CIccTagXmlEmbeddedHeightImage, CIccTagXmlEmbeddedNormalImage, and CIccTagXmlEmbeddedProfile.
{return NULL;}
Referenced by icCurvesFromXml(), icCurvesToXml(), icProfDescToXml(), icXmlParseProfDesc(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeXmlTintArray::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetText()
const icUChar * CIccTagUtf8Text::GetText () const inline
{ return m_szText; }
References m_szText.
Referenced by CIccStructNamedColor::getName(), icConvertEncodingProfile(), and icGetTagText().
GetType()
virtual icTagTypeSignature CIccTagUtf8Text::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigUtf8TextType; }
References icSigUtf8TextType.
Referenced by Write().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
virtual CIccTag * CIccTagUtf8Text::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
Reimplemented in CIccTagXmlUtf8Text.
{return new CIccTagUtf8Text(*this);}
References CIccTagUtf8Text().
operator=() [1/3]
CIccTagUtf8Text & CIccTagUtf8Text::operator= (const CIccTagUtf8Text & TextTag)
Name: CIccTagUtf8Text::operator=
Purpose: Copy Operator
Args: TextTag = The CIccTagText object to be copied
{
  if (&TextTag == this)
    return *this;
  m_szText = (icUChar*)malloc(1);
  m_szText[0] = '\0';
  m_nBufSize = 1;
  SetText(TextTag.m_szText);
  return *this;
}
References m_nBufSize, m_szText, and SetText().
operator=() [2/3]
const icChar * CIccTagUtf8Text::operator= (const icChar * szText) inline
{ return (const icChar*)operator=((icUChar*)szText); }
References operator=().
operator=() [3/3]
const icUChar * CIccTagUtf8Text::operator= (const icUChar * szText)
Name: *CIccTagUtf8Textoperator=
Purpose: Define assignment operator to associate text with tag.
Args: szText - zero terminated string to put in the tag
Return: A pointer to the string assigned to the tag.
{
  SetText(szText);
  return (icUChar*)m_szText;
}
References m_szText, and SetText().
Referenced by operator=().
Read() [1/2]
bool CIccTagUtf8Text::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagUtf8Text::Read
Purpose: Read in a text type tag into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  if (size<sizeof(icTagTypeSignature) || !pIO) {
    m_szText[0] = '\0';
    return false;
  }
  if (!pIO->Read32(&sig))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  if (size < sizeof(icTagTypeSignature) + sizeof(icUInt32Number))
    return false;
  icUInt32Number nSize = size - sizeof(icTagTypeSignature) - sizeof(icUInt32Number);
  icUChar *pBuf = GetBuffer(nSize);
  if (nSize) {
    if (pIO->Read8(pBuf, nSize) != (icInt32Number)nSize) {
      return false;
    }
  }
  Release();
  return true;
}
References GetBuffer(), CIccTag::m_nReserved, m_szText, CIccIO::Read32(), CIccIO::Read8(), and Release().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
Release()
void CIccTagUtf8Text::Release ()
Name: CIccTagUtf8Text::Release
Purpose: This will resize the buffer to fit the zero terminated string in the buffer.
{
  icUInt32Number nSize = (icUInt32Number)strlen((icChar*)m_szText)+1;
  if (nSize < m_nBufSize-1) {
    m_szText=(icUChar*)icRealloc(m_szText, nSize+1);
    m_nBufSize = nSize+1;
  }
}
References icRealloc(), m_nBufSize, and m_szText.
Referenced by Read(), and SetText().
SetText() [1/3]
void CIccTagUtf8Text::SetText (const icChar * szText) inline
{ SetText((icUChar*)szText); }
References SetText().
Referenced by CIccTagXmlUtf8Text::ParseXml(), SetText(), and SetText().
SetText() [2/3]
void CIccTagUtf8Text::SetText (const icUChar * szText)
Name: CIccTagUtf8Text::SetText
Purpose: Allows text data associated with the tag to be set.
Args: szText - zero terminated string to put in tag
{
  if (!szText) {
    SetText("");
    return;
  }
  icUInt32Number len=(icUInt32Number)strlen((icChar*)szText) + 1;
  icUChar *szBuf = GetBuffer(len);
  strcpy((icChar*)szBuf, (icChar*)szText);
  Release();
}
References GetBuffer(), Release(), and SetText().
Referenced by CIccTagUtf8Text(), operator=(), operator=(), SetText(), and SetText().
SetText() [3/3]
void CIccTagUtf8Text::SetText (const icUChar16 * szText)
Name: CIccTagUtf8Text::SetText
Purpose: Allows text data associated with the tag to be set.
Args: szText - zero terminated string to put in tag
{
  if (!szText) {
    SetText("");
    return;
  }
  icUtf8Vector text;
  icUInt32Number len;
  for (len=0; szText[len]; len++);
  icConvertUTF16toUTF8(szText, &szText[len], text, lenientConversion);
  SetText((const icUChar*)&text[0]);
}
References icConvertUTF16toUTF8(), lenientConversion, SetText(), and SetText().
Validate()
icValidateStatus CIccTagUtf8Text::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagUtf8Text::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  if (!m_nBufSize) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " - Empty Tag.\n";
    rv = icMaxStatus(rv, icValidateWarning);
  }
  return rv;
}
References CIccInfo::GetSigPathName(), icMaxStatus(), icMsgValidateWarning, icValidateWarning, m_nBufSize, and CIccTag::Validate().
Write()
bool CIccTagUtf8Text::Write (CIccIO * pIO) virtual
Name: CIccTagUtf8Text::Write
Purpose: Write a text type tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  if (!pIO)
   return false;
  if (!pIO->Write32(&sig))
   return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  if (!m_szText)
    return false;
  icUInt32Number nSize = (icUInt32Number)strlen((icChar*)m_szText)+1;
  if (pIO->Write8(m_szText, nSize) != (icInt32Number)nSize)
    return false;
  return true;
}
References GetType(), CIccTag::m_nReserved, m_szText, CIccIO::Write32(), and CIccIO::Write8().
Field Documentation
m_nBufSize
icUInt32Number CIccTagUtf8Text::m_nBufSize protected
Referenced by CIccTagUtf8Text(), CIccTagUtf8Text(), Capacity(), Describe(), GetBuffer(), operator=(), Release(), and Validate().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_szText
icUChar* CIccTagUtf8Text::m_szText protected
Referenced by CIccTagUtf8Text(), CIccTagUtf8Text(), ~CIccTagUtf8Text(), Describe(), GetBuffer(), GetText(), operator=(), operator=(), Read(), Release(), CIccTagXmlUtf8Text::ToXml(), and Write().
The documentation for this class was generated from the following files:
IccProfLib/IccTagBasic.h
IccProfLib/IccTagBasic.cpp