iccDEV: Tools/CmdLine/IccFromCube/iccFromCube.cpp File Reference
iccFromCube.cpp File Reference
#include <stdio.h>
#include <string>
#include "IccProfile.h"
#include "IccTagBasic.h"
#include "IccTagMPE.h"
#include "IccMpeBasic.h"
#include "IccProfLibVer.h"
#include "IccUtil.h"
Data Structures
class CubeFile
Macros
#define MAX_LINE_LEN 255
Functions
int main (int argc, char *argv[])
Macro Definition Documentation
MAX_LINE_LEN
#define MAX_LINE_LEN 255
Function Documentation
main()
int main (int argc, char * argv[])
{
  int nArg = 1;
  long int verbosity = 100; // default is maximum verbosity (old behaviour)
  if (argc <= 2) {
    printf("Usage: iccFromCube cube_file output_icc_file\n");
    printf("Built with IccProfLib version " ICCPROFLIBVER "\n");
    return -1;
  }
  CubeFile cube(argv[1]);
  if (!cube.parseHeader()) {
    printf("Unable to parse '%s'\n", argv[1]);
    return -2;
  }
  if (!cube.sizeLut3D()) {
    printf("3DLUT not found in '%s'\n", argv[1]);
    return -3;
  }
  CIccProfile profile;
  //Initialize profile header
  profile.InitHeader();
  profile.m_Header.version = icVersionNumberV5;
  profile.m_Header.colorSpace = icSigRgbData;
  profile.m_Header.pcs = icSigRgbData;
  profile.m_Header.deviceClass = icSigLinkClass;
  //Create A2B0 Tag with LUT
  CIccTagMultiProcessElement* pTag = new CIccTagMultiProcessElement(3, 3);
  if (cube.isCustomInputRange()) {
    icFloatNumber* minVal = cube.getMinInput();
    icFloatNumber* maxVal = cube.getMaxInput();
    CIccMpeCurveSet* pCurves = new CIccMpeCurveSet(3);
    CIccSingleSampledCurve* pCurve0 = new CIccSingleSampledCurve(minVal[0], maxVal[0]);
    pCurve0->SetSize(2);
    pCurve0->GetSamples()[0] = 0;
    pCurve0->GetSamples()[1] = 1;
    pCurves->SetCurve(0, pCurve0);
    CIccSingleSampledCurve* pCurve1 = pCurve0;
    if (minVal[1] != minVal[0] || maxVal[1] != maxVal[0]) {
      pCurve1 = new CIccSingleSampledCurve(minVal[1], maxVal[1]);
      pCurve1->SetSize(2);
      pCurve1->GetSamples()[0] = 0;
      pCurve1->GetSamples()[1] = 1;
    }
    pCurves->SetCurve(1, pCurve1);
    CIccSingleSampledCurve* pCurve2 = pCurve0;
    if (minVal[2] != minVal[0] || maxVal[2] != maxVal[0]) {
      if (minVal[2] == minVal[1] && maxVal[2] == maxVal[1])
        pCurve2 = pCurve1;
      else {
        pCurve2 = new CIccSingleSampledCurve(minVal[2], maxVal[2]);
        pCurve2->SetSize(2);
        pCurve2->GetSamples()[0] = 0;
        pCurve2->GetSamples()[1] = 1;
      }
    }
    pCurves->SetCurve(2, pCurve2);
    pTag->Attach(pCurves);
  }
  CIccMpeCLUT* pMpeCLUT = new CIccMpeCLUT();
  CIccCLUT* pCLUT = new CIccCLUT(3, 3);
  pCLUT->Init(cube.sizeLut3D());
  bool bSuccess = cube.parse3DTable(pCLUT->GetData(0), pCLUT->NumPoints()*3);
  pMpeCLUT->SetCLUT(pCLUT);
  pTag->Attach(pMpeCLUT);
  profile.AttachTag(icSigAToB0Tag, pTag);
  cube.close();
  if (!bSuccess) {
    printf("Unable to parse LUT from '%s'\n", argv[1]);
    return (-4);
  }
  //Add description Tag
  CIccTagMultiLocalizedUnicode* pTextTag = new CIccTagMultiLocalizedUnicode();
  std::string desc = cube.getDescription();
  if (desc.size()) {
    pTextTag->SetText(desc.c_str());
  }
  else {
    pTextTag->SetText((std::string("Device link created from ") + argv[1]).c_str());
  }
  profile.AttachTag(icSigProfileDescriptionTag, pTextTag);
  //Add copyright Tag
  if (cube.getCopyright().size()) {
    pTextTag = new CIccTagMultiLocalizedUnicode();
    pTextTag->SetText(cube.getCopyright().c_str());
    profile.AttachTag(icSigCopyrightTag, pTextTag);
  }
  if (SaveIccProfile(argv[2], &profile)) {
    printf("'%s' successfully created\n", argv[2]);
  }
  else {
    printf("Unable to save profile '%s'\n", argv[2]);
    return -5;
  }
  return 0;
}
References CIccCLUT::CIccCLUT(), CIccMpeCLUT::CIccMpeCLUT(), CIccMpeCurveSet::CIccMpeCurveSet(), CIccSingleSampledCurve::CIccSingleSampledCurve(), CIccTagMultiLocalizedUnicode::CIccTagMultiLocalizedUnicode(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CubeFile::CubeFile(), CIccTagMultiProcessElement::Attach(), CIccProfile, CubeFile::close(), icHeader::colorSpace, icHeader::deviceClass, CubeFile::getCopyright(), CIccCLUT::GetData(), CubeFile::getDescription(), CubeFile::getMaxInput(), CubeFile::getMinInput(), CIccSingleSampledCurve::GetSamples(), icSigAToB0Tag, icSigCopyrightTag, icSigLinkClass, icSigProfileDescriptionTag, icSigRgbData, CIccCLUT::Init(), CubeFile::isCustomInputRange(), CIccCLUT::NumPoints(), CubeFile::parse3DTable(), CubeFile::parseHeader(), icHeader::pcs, SaveIccProfile(), CIccMpeCLUT::SetCLUT(), CIccMpeCurveSet::SetCurve(), CIccSingleSampledCurve::SetSize(), CIccTagMultiLocalizedUnicode::SetText(), CubeFile::sizeLut3D(), and icHeader::version.