iccDEV: CIccApplyMpeCalculator Class Reference
CIccApplyMpeCalculator Class Reference
#include <IccMpeCalc.h>
Public Member Functions
virtual ~CIccApplyMpeCalculator ()
void Apply (icFloatNumber *pDestPixel, const icFloatNumber *pSrcPixel)
CIccSubCalcApply * GetApply (icUInt16Number index)
virtual const icChar * GetClassName () const
CIccMultiProcessElement * GetElem () const
bool GetEnvVar (icSigCmmEnvVar sigEnv, icFloatNumber &val)
const icFloatNumber * GetInput ()
icFloatNumber * GetOutput ()
CIccFloatVector * GetScratch ()
CIccFloatVector * GetStack ()
icFloatNumber * GetTemp ()
virtual icElemTypeSignature GetType () const
Protected Member Functions
CIccApplyMpeCalculator (CIccMultiProcessElement *pElem)
Protected Attributes
const icFloatNumber * m_input
icUInt32Number m_nSubElem
icFloatNumber * m_output
CIccApplyTagMpe * m_pApplyTag
IIccCmmEnvVarLookup * m_pCmmEnvVarLookup
CIccMultiProcessElement * m_pElem
CIccFloatVector * m_scratch
CIccFloatVector * m_stack
CIccSubCalcApply ** m_SubElem
icFloatNumber * m_temp
Detailed Description
Class: CIccApplyMpeCalculator
Purpose: The Calculator process element apply data
Constructor & Destructor Documentation
~CIccApplyMpeCalculator()
CIccApplyMpeCalculator::~CIccApplyMpeCalculator () virtual
Name: CIccMpeCalculator::~CIccApplyMpeCalculator
Purpose:
Args:
Return:
{
  if (m_stack) {
    delete m_stack;
  }
  if (m_scratch) {
    delete m_scratch;
  }
  if (m_temp) {
    free(m_temp);
  }
  icUInt32Number i;
  if (m_SubElem) {
    for (i=0; i<m_nSubElem; i++) {
      if (m_SubElem[i])
        delete m_SubElem[i];
    }
  }
}
References m_nSubElem, m_scratch, m_stack, m_SubElem, and m_temp.
CIccApplyMpeCalculator()
CIccApplyMpeCalculator::CIccApplyMpeCalculator (CIccMultiProcessElement * pElem) protected
Name: CIccMpeCalculator::CIccApplyMpeCalculator
Purpose:
Args:
Return:
                                                                             : CIccApplyMpe(pElem)
{
  m_temp = NULL;
  m_input = NULL;
  m_output = NULL;
  m_stack = NULL;
  m_scratch = NULL;
  m_nSubElem = 0;
  m_SubElem = NULL;
}
References CIccApplyMpe::CIccApplyMpe(), m_input, m_nSubElem, m_output, m_scratch, m_stack, m_SubElem, and m_temp.
Referenced by CIccMpeCalculator::GetNewApply().
Member Function Documentation
Apply()
void CIccApplyMpe::Apply (icFloatNumber * pDestPixel, const icFloatNumber * pSrcPixel) inline inherited
{ m_pElem->Apply(this, pDestPixel, pSrcPixel); }
References CIccMultiProcessElement::Apply(), and CIccApplyMpe::m_pElem.
Referenced by CIccTagMultiProcessElement::Apply(), and CIccSubCalcApply::Apply().
GetApply()
CIccSubCalcApply * CIccApplyMpeCalculator::GetApply (icUInt16Number index)
Name: CIccApplyMpeCalculator::GetSubApply
Purpose:
Args:
Return:
{
  if (m_SubElem && index<m_nSubElem)
    return m_SubElem[index];
  return NULL;
}
References m_nSubElem, and m_SubElem.
Referenced by CIccOpDefSubElement::Exec().
GetClassName()
virtual const icChar * CIccApplyMpeCalculator::GetClassName () const inline virtual
Reimplemented from CIccApplyMpe.
{ return "CIccApplyMpeCalculator"; }
GetElem()
CIccMultiProcessElement * CIccApplyMpe::GetElem () const inline inherited
{ return m_pElem; }
References CIccApplyMpe::m_pElem.
Referenced by CIccTagMultiProcessElement::Apply(), CIccSubCalcApply::NumInputChannels(), and CIccSubCalcApply::NumOutputChannels().
GetEnvVar()
bool CIccApplyMpeCalculator::GetEnvVar (icSigCmmEnvVar sigEnv, icFloatNumber & val)
Name: CIccApplyMpeCalculator::GetSubApply
Purpose:
Args:
Return:
{
  if (!m_pCmmEnvVarLookup) {
    val = 0;
    return false;
  }
  return m_pCmmEnvVarLookup->GetEnvVar(sigEnv, val);
}
References IIccCmmEnvVarLookup::GetEnvVar(), and m_pCmmEnvVarLookup.
Referenced by CIccOpDefEnvVar::Exec().
GetInput()
const icFloatNumber * CIccApplyMpeCalculator::GetInput () inline
{ return m_input; }
References m_input.
Referenced by CIccCalculatorFunc::ApplySequence().
GetOutput()
icFloatNumber * CIccApplyMpeCalculator::GetOutput () inline
{ return m_output; }
References m_output.
Referenced by CIccCalculatorFunc::Apply(), and CIccCalculatorFunc::ApplySequence().
GetScratch()
CIccFloatVector * CIccApplyMpeCalculator::GetScratch () inline
{ return m_scratch; }
References m_scratch.
Referenced by CIccCalculatorFunc::ApplySequence().
GetStack()
CIccFloatVector * CIccApplyMpeCalculator::GetStack () inline
{ return m_stack; }
References m_stack.
Referenced by CIccCalculatorFunc::Apply(), and CIccCalculatorFunc::ApplySequence().
GetTemp()
icFloatNumber * CIccApplyMpeCalculator::GetTemp () inline
{ return m_temp; }
References m_temp.
Referenced by CIccCalculatorFunc::ApplySequence().
GetType()
virtual icElemTypeSignature CIccApplyMpeCalculator::GetType () const inline virtual
Reimplemented from CIccApplyMpe.
{ return icSigCalculatorElemType; }
References icSigCalculatorElemType.
Field Documentation
m_input
const icFloatNumber* CIccApplyMpeCalculator::m_input protected
Referenced by CIccApplyMpeCalculator(), CIccMpeCalculator::Apply(), and GetInput().
m_nSubElem
icUInt32Number CIccApplyMpeCalculator::m_nSubElem protected
Referenced by CIccApplyMpeCalculator(), ~CIccApplyMpeCalculator(), GetApply(), and CIccMpeCalculator::GetNewApply().
m_output
icFloatNumber* CIccApplyMpeCalculator::m_output protected
Referenced by CIccApplyMpeCalculator(), CIccMpeCalculator::Apply(), and GetOutput().
m_pApplyTag
CIccApplyTagMpe* CIccApplyMpe::m_pApplyTag protected inherited
Referenced by CIccApplyMpe::CIccApplyMpe().
m_pCmmEnvVarLookup
IIccCmmEnvVarLookup* CIccApplyMpeCalculator::m_pCmmEnvVarLookup protected
Referenced by GetEnvVar(), and CIccMpeCalculator::GetNewApply().
m_pElem
CIccMultiProcessElement* CIccApplyMpe::m_pElem protected inherited
Referenced by CIccApplyMpe::CIccApplyMpe(), CIccApplyMpe::Apply(), CIccApplyMpe::GetElem(), and CIccApplyMpeSpectralCLUT::GetType().
m_scratch
CIccFloatVector* CIccApplyMpeCalculator::m_scratch protected
Referenced by CIccApplyMpeCalculator(), ~CIccApplyMpeCalculator(), CIccMpeCalculator::GetNewApply(), and GetScratch().
m_stack
CIccFloatVector* CIccApplyMpeCalculator::m_stack protected
Referenced by CIccApplyMpeCalculator(), ~CIccApplyMpeCalculator(), CIccMpeCalculator::GetNewApply(), and GetStack().
m_SubElem
CIccSubCalcApply** CIccApplyMpeCalculator::m_SubElem protected
Referenced by CIccApplyMpeCalculator(), ~CIccApplyMpeCalculator(), GetApply(), and CIccMpeCalculator::GetNewApply().
m_temp
icFloatNumber* CIccApplyMpeCalculator::m_temp protected
Referenced by CIccApplyMpeCalculator(), ~CIccApplyMpeCalculator(), CIccMpeCalculator::Apply(), CIccMpeCalculator::GetNewApply(), and GetTemp().
The documentation for this class was generated from the following files:
IccProfLib/IccMpeCalc.h
IccProfLib/IccMpeCalc.cpp