iccDEV: CIccTagLut8 Class Reference
CIccTagLut8 Class Reference
#include <IccTagLut.h>
Public Member Functions
CIccTagLut8 ()
CIccTagLut8 (const CIccTagLut8 &ITL)
virtual ~CIccTagLut8 ()
void Cleanup ()
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
virtual const icChar * GetClassName () const
CIccCLUT * GetCLUT () const
icColorSpaceSignature GetCsInput ()
icColorSpaceSignature GetCsOutput ()
LPIccCurve * GetCurvesA () const
LPIccCurve * GetCurvesB () const
LPIccCurve * GetCurvesM () const
virtual IIccExtensionTag * GetExtension ()
CIccMatrix * GetMatrix () const
virtual icUInt8Number GetPrecision ()
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
void Init (icUInt8Number nInputChannels, icUInt8Number nOutputChannels)
icUInt8Number InputChannels () const
virtual bool IsArrayType ()
bool IsInputB ()
virtual bool IsInputMatrix ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
CIccCLUT * NewCLUT (icUInt8Number *pGridPoints, icUInt8Number nPrecision=2)
CIccCLUT * NewCLUT (icUInt8Number nGridPoints, icUInt8Number nPrecision=2)
virtual CIccTag * NewCopy () const
LPIccCurve * NewCurvesA ()
LPIccCurve * NewCurvesB ()
LPIccCurve * NewCurvesM ()
CIccMatrix * NewMatrix ()
CIccTagLut8 & operator= (const CIccTagLut8 &ITL)
icUInt8Number OutputChannels () const
bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
CIccCLUT * SetCLUT (CIccCLUT *clut)
virtual void SetColorSpaces (icColorSpaceSignature csInput, icColorSpaceSignature csOutput)
bool SwapMBCurves ()
virtual bool UseLegacyPCS () const
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL)
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
Protected Attributes
bool m_bInputMatrix
bool m_bUseMCurvesAsBCurves
CIccCLUT * m_CLUT
icColorSpaceSignature m_csInput
icColorSpaceSignature m_csOutput
LPIccCurve * m_CurvesA
LPIccCurve * m_CurvesB
LPIccCurve * m_CurvesM
CIccMatrix * m_Matrix
icUInt8Number m_nInput
icUInt8Number m_nOutput
icUInt8Number m_nReservedByte
icS15Fixed16Number m_XYZMatrix [9]
Detailed Description
Class: CIccTagLut8
Purpose: The Lut8 tag type
Constructor & Destructor Documentation
CIccTagLut8() [1/2]
CIccTagLut8::CIccTagLut8 ()
Name: CIccTagLut8::CIccTagLut8
Purpose: Constructor
{
  memset(m_XYZMatrix, 0, sizeof(m_XYZMatrix));
  m_XYZMatrix[0] = m_XYZMatrix[4] = m_XYZMatrix[8] = icDtoF(1.0);
  m_nReservedByte = 0;
}
References icDtoF(), m_nReservedByte, and m_XYZMatrix.
CIccTagLut8() [2/2]
CIccTagLut8::CIccTagLut8 (const CIccTagLut8 & ITL)
Name: CIccTagLut8::CIccTagLut8
Purpose: Copy Constructor
Args: ITL = The CIccTagLut8 object to be copied
                                               : CIccMBB(ITL)
{
  memcpy(&m_XYZMatrix, &ITL.m_XYZMatrix, sizeof(m_XYZMatrix));
  m_nReservedByte = 0;
}
References CIccMBB::CIccMBB(), m_nReservedByte, and m_XYZMatrix.
Referenced by NewCopy().
~CIccTagLut8()
CIccTagLut8::~CIccTagLut8 () virtual
Name: CIccTagLut8::~CIccTagLut8
Purpose: Destructor
{
}
Member Function Documentation
Cleanup()
void CIccMBB::Cleanup () inherited
Name: CIccMBB::Cleanup
Purpose: Frees the memory allocated to the object
{
  int i;
  if (IsInputMatrix()) {
    if (m_CurvesB) {
      for (i=0; i<m_nInput; i++)
        if (m_CurvesB[i])
          delete m_CurvesB[i];
      delete [] m_CurvesB;
      m_CurvesB = NULL;
    }
    if (m_CurvesM) {
      for (i=0; i<m_nInput; i++)
        if (m_CurvesM[i])
          delete m_CurvesM[i];
      delete [] m_CurvesM;
      m_CurvesM = NULL;
    }
    if (m_CurvesA) {
      for (i=0; i<m_nOutput; i++)
        if (m_CurvesA[i])
          delete m_CurvesA[i];
      delete [] m_CurvesA;
      m_CurvesA = NULL;
    }
  }
  else {
    if (m_CurvesA) {
      for (i=0; i<m_nInput; i++)
        if (m_CurvesA[i])
          delete m_CurvesA[i];
      delete [] m_CurvesA;
      m_CurvesA = NULL;
    }
    if (m_CurvesM) {
      for (i=0; i<m_nOutput; i++)
        if (m_CurvesM[i])
          delete m_CurvesM[i];
      delete [] m_CurvesM;
      m_CurvesM = NULL;
    }
    if (m_CurvesB) {
      for (i=0; i<m_nOutput; i++)
        if (m_CurvesB[i])
          delete m_CurvesB[i];
      delete [] m_CurvesB;
      m_CurvesB = NULL;
    }
  }
  if (m_Matrix) {
    delete m_Matrix;
    m_Matrix = NULL;
  }
  if (m_CLUT) {
    delete m_CLUT;
    m_CLUT = NULL;
  }
}
References CIccMBB::IsInputMatrix(), CIccMBB::m_CLUT, CIccMBB::m_CurvesA, CIccMBB::m_CurvesB, CIccMBB::m_CurvesM, CIccMBB::m_Matrix, CIccMBB::m_nInput, and CIccMBB::m_nOutput.
Referenced by CIccMBB::~CIccMBB(), CIccMBB::Init(), and CIccMBB::operator=().
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), Read(), CIccTagLut16::Read(), SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccMBB::Describe (std::string & sDescription, int nVerboseness) virtual inherited
Name: CIccMBB::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  int i;
  icChar buf[128], color[40];
  if (IsInputMatrix()) {
    if (m_CurvesB && !m_bUseMCurvesAsBCurves) {
      for (i=0; i<m_nInput; i++) {
        icColorIndexName(color, m_csInput, i, m_nInput, "");
        sprintf(buf, "B_Curve_%s", color);
        m_CurvesB[i]->DumpLut(sDescription, buf, m_csInput, i, nVerboseness);
      }
    }
    if (m_Matrix)
      m_Matrix->DumpLut(sDescription, "Matrix", nVerboseness);
    if (m_CurvesM) {
      for (i=0; i<m_nInput; i++) {
        icColorIndexName(color, m_csInput, i, m_nInput, "");
        if (!m_bUseMCurvesAsBCurves)
          sprintf(buf, "M_Curve_%s", color);
        else
          sprintf(buf, "B_Curve_%s", color);
        m_CurvesM[i]->DumpLut(sDescription, buf, m_csInput, i, nVerboseness);
      }
    }
    if (m_CLUT)
      m_CLUT->DumpLut(sDescription, "CLUT", m_csInput, m_csOutput, nVerboseness, GetType()==icSigLut16Type);
    if (m_CurvesA) {
      for (i=0; i<m_nOutput; i++) {
        icColorIndexName(color, m_csOutput, i, m_nOutput, "");
        sprintf(buf, "A_Curve_%s", color);
        m_CurvesA[i]->DumpLut(sDescription, buf, m_csOutput, i, nVerboseness);
      }
    }
  }
  else {
    if (m_CurvesA) {
      for (i=0; i<m_nInput; i++) {
        icColorIndexName(color, m_csInput, i, m_nInput, "");
        sprintf(buf, "A_Curve_%s", color);
        m_CurvesA[i]->DumpLut(sDescription, buf, m_csInput, i, nVerboseness);
      }
    }
    if (m_CLUT)
      m_CLUT->DumpLut(sDescription, "CLUT", m_csInput, m_csOutput, nVerboseness);
    if (m_CurvesM && this->GetType()!=icSigLut8Type) {
      for (i=0; i<m_nOutput; i++) {
        icColorIndexName(color, m_csOutput, i, m_nOutput, "");
        sprintf(buf, "M_Curve_%s", color);
        m_CurvesM[i]->DumpLut(sDescription, buf, m_csOutput, i, nVerboseness);
      }
    }
    if (m_Matrix)
      m_Matrix->DumpLut(sDescription, "Matrix", nVerboseness);
    if (m_CurvesB) {
      for (i=0; i<m_nOutput; i++) {
        icColorIndexName(color, m_csOutput, i, m_nOutput, "");
        sprintf(buf, "B_Curve_%s", color);
        m_CurvesB[i]->DumpLut(sDescription, buf, m_csOutput, i, nVerboseness);
      }
    }
  }
}
References CIccCLUT::DumpLut(), CIccCurve::DumpLut(), CIccMatrix::DumpLut(), CIccTag::GetType(), icColorIndexName(), icSigLut16Type, icSigLut8Type, CIccMBB::IsInputMatrix(), CIccMBB::m_bUseMCurvesAsBCurves, CIccMBB::m_CLUT, CIccMBB::m_csInput, CIccMBB::m_csOutput, CIccMBB::m_CurvesA, CIccMBB::m_CurvesB, CIccMBB::m_CurvesM, CIccMBB::m_Matrix, CIccMBB::m_nInput, and CIccMBB::m_nOutput.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
GetClassName()
virtual const icChar * CIccTag::GetClassName () const inline virtual inherited
Reimplemented in CIccTagUnknown, CIccTagText, CIccTagUtf8Text, CIccTagZipUtf8Text, CIccTagZipXml, CIccTagUtf16Text, CIccTagTextDescription, CIccTagSignature, CIccTagNamedColor2, CIccTagXYZ, CIccTagChromaticity, CIccTagCicp, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, CIccTagMeasurement, CIccTagMultiLocalizedUnicode, CIccTagData, CIccTagDateTime, CIccTagColorantOrder, CIccTagColorantTable, CIccTagViewingConditions, CIccTagProfileSeqDesc, CIccTagResponseCurveSet16, CIccTagSpectralDataInfo, CIccTagSpectralViewingConditions, CIccTagEmbeddedHeightImage, CIccTagEmbeddedNormalImage, CIccTagStruct, CIccTagArray, CIccTagDict, CIccTagEmbeddedProfile, CIccTagCurve, CIccTagParametricCurve, CIccTagSegmentedCurve, CIccTagGamutBoundaryDesc, CIccTagMultiProcessElement, CIccTagProfileSequenceId, CIccTagXmlUnknown, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, CIccTagXmlSignature, CIccTagXmlNamedColor2, CIccTagXmlXYZ, CIccTagXmlChromaticity, CIccTagXmlCicp, CIccTagXmlSparseMatrixArray, CIccTagXmlFixedNum< T, Tsig >, CIccTagXmlNum< T, A, Tsig >, CIccTagXmlFloatNum< T, A, Tsig >, CIccTagXmlMeasurement, CIccTagXmlMultiLocalizedUnicode, CIccTagXmlTagData, CIccTagXmlDateTime, CIccTagXmlColorantOrder, CIccTagXmlColorantTable, CIccTagXmlViewingConditions, CIccTagXmlSpectralDataInfo, CIccTagXmlSpectralViewingConditions, CIccTagXmlProfileSeqDesc, CIccTagXmlResponseCurveSet16, CIccTagXmlCurve, CIccTagXmlParametricCurve, CIccTagXmlSegmentedCurve, CIccTagXmlLutAtoB, CIccTagXmlLutBtoA, CIccTagXmlLut8, CIccTagXmlLut16, CIccTagXmlMultiProcessElement, CIccTagXmlProfileSequenceId, CIccTagXmlDict, CIccTagXmlStruct, and CIccTagXmlArray.
{ return "CIccTag"; }
GetCLUT()
CIccCLUT * CIccMBB::GetCLUT () const inline inherited
{return m_CLUT;}
References CIccMBB::m_CLUT.
Referenced by CIccEvalCompare::EvaluateProfile(), icMBBFromXml(), and icMBBToXml().
GetCsInput()
icColorSpaceSignature CIccMBB::GetCsInput () inline inherited
{ return m_csInput; }
References CIccMBB::m_csInput.
GetCsOutput()
icColorSpaceSignature CIccMBB::GetCsOutput () inline inherited
{ return m_csOutput; }
References CIccMBB::m_csOutput.
GetCurvesA()
LPIccCurve * CIccMBB::GetCurvesA () const inline inherited
{return m_CurvesA;}
References CIccMBB::m_CurvesA.
Referenced by icMBBFromXml(), and icMBBToXml().
GetCurvesB()
LPIccCurve * CIccMBB::GetCurvesB () const inline inherited
{return m_CurvesB;}
References CIccMBB::m_CurvesB.
Referenced by icMBBFromXml(), and icMBBToXml().
GetCurvesM()
LPIccCurve * CIccMBB::GetCurvesM () const inline inherited
{return m_CurvesM;}
References CIccMBB::m_CurvesM.
Referenced by icMBBFromXml(), and icMBBToXml().
GetExtension()
virtual IIccExtensionTag * CIccTag::GetExtension () inline virtual inherited
Reimplemented in CIccTagXmlUnknown, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, CIccTagXmlSignature, CIccTagXmlNamedColor2, CIccTagXmlXYZ, CIccTagXmlChromaticity, CIccTagXmlCicp, CIccTagXmlSparseMatrixArray, CIccTagXmlFixedNum< T, Tsig >, CIccTagXmlNum< T, A, Tsig >, CIccTagXmlFloatNum< T, A, Tsig >, CIccTagXmlMeasurement, CIccTagXmlMultiLocalizedUnicode, CIccTagXmlTagData, CIccTagXmlDateTime, CIccTagXmlColorantOrder, CIccTagXmlColorantTable, CIccTagXmlViewingConditions, CIccTagXmlSpectralDataInfo, CIccTagXmlSpectralViewingConditions, CIccTagXmlProfileSeqDesc, CIccTagXmlResponseCurveSet16, CIccTagXmlCurve, CIccTagXmlParametricCurve, CIccTagXmlSegmentedCurve, CIccTagXmlLutAtoB, CIccTagXmlLutBtoA, CIccTagXmlLut8, CIccTagXmlLut16, CIccTagXmlMultiProcessElement, CIccTagXmlProfileSequenceId, CIccTagXmlDict, CIccTagXmlStruct, CIccTagXmlArray, CIccTagXmlGamutBoundaryDesc, CIccTagXmlEmbeddedHeightImage, CIccTagXmlEmbeddedNormalImage, and CIccTagXmlEmbeddedProfile.
{return NULL;}
Referenced by icCurvesFromXml(), icCurvesToXml(), icProfDescToXml(), icXmlParseProfDesc(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeXmlTintArray::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
GetMatrix()
CIccMatrix * CIccMBB::GetMatrix () const inline inherited
{return m_Matrix; }
References CIccMBB::m_Matrix.
Referenced by icMBBFromXml(), and icMBBToXml().
GetPrecision()
virtual icUInt8Number CIccTagLut8::GetPrecision () inline virtual
Reimplemented from CIccMBB.
{ return 1; }
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagLut8::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigLut8Type; }
References icSigLut8Type.
Referenced by Read(), Validate(), and Write().
Init()
void CIccMBB::Init (icUInt8Number nInputChannels, icUInt8Number nOutputChannels) inherited
Name: CIccMBB::Init
Purpose: Cleans up any prior memory and Initializes the object.
Args: nInputChannels = number of input channels, nOutputChannels = number of output channels
{
  Cleanup();
  m_nInput = nInputChannels;
  m_nOutput = nOutputChannels;
}
References CIccMBB::Cleanup(), CIccMBB::m_nInput, and CIccMBB::m_nOutput.
Referenced by CDevLinkWriter::begin(), and icMBBFromXml().
InputChannels()
icUInt8Number CIccMBB::InputChannels () const inline inherited
{ return m_nInput; }
References CIccMBB::m_nInput.
Referenced by icMBBToXml().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsInputB()
bool CIccMBB::IsInputB () inline inherited
{ return IsInputMatrix(); }
References CIccMBB::IsInputMatrix().
Referenced by CIccMBB::CIccMBB(), icMBBFromXml(), CIccMBB::NewCurvesA(), CIccMBB::NewCurvesB(), CIccMBB::operator=(), CIccTagLutAtoB::Read(), and CIccTagLutAtoB::Write().
IsInputMatrix()
virtual bool CIccMBB::IsInputMatrix () inline virtual inherited
{ return m_bInputMatrix; } //Is matrix on input side of CLUT?
References CIccMBB::m_bInputMatrix.
Referenced by CIccMBB::CIccMBB(), CIccMBB::Cleanup(), CIccMBB::Describe(), icMBBFromXml(), icMBBToXml(), CIccMBB::IsInputB(), CIccMBB::NewCurvesM(), CIccMBB::operator=(), CIccTagLutAtoB::Read(), SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccTagLutAtoB::Write().
IsMBBType()
virtual bool CIccMBB::IsMBBType () inline virtual inherited
Reimplemented from CIccTag.
{ return true;}
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCLUT() [1/2]
CIccCLUT * CIccMBB::NewCLUT (icUInt8Number * pGridPoints, icUInt8Number nPrecision = 2) inherited
Name: CIccMBB::NewCLUT
Purpose: Allocates memory for a new CLUT and initializes it
Args: pGridPoints = number of grid points in the CLUT
Return: Pointer to the CIccCLUT object
{
  if (m_CLUT)
    return m_CLUT;
  m_CLUT = new CIccCLUT(m_nInput, m_nOutput, nPrecision);
  m_CLUT->Init(pGridPoints);
  return m_CLUT;
}
References CIccCLUT::CIccCLUT(), CIccCLUT::Init(), CIccMBB::m_CLUT, CIccMBB::m_nInput, and CIccMBB::m_nOutput.
NewCLUT() [2/2]
CIccCLUT * CIccMBB::NewCLUT (icUInt8Number nGridPoints, icUInt8Number nPrecision = 2) inherited
Name: CIccMBB::NewCLUT
Purpose: Allocates memory for a new CLUT and initializes it
Args: nGridPoints = number of grid points in the CLUT
Return: Pointer to the CIccCLUT object
{
  if (m_CLUT)
    return m_CLUT;
  m_CLUT = new CIccCLUT(m_nInput, m_nOutput, nPrecision);
  m_CLUT->Init(nGridPoints);
  return m_CLUT;
}
References CIccCLUT::CIccCLUT(), CIccCLUT::Init(), CIccMBB::m_CLUT, CIccMBB::m_nInput, and CIccMBB::m_nOutput.
Referenced by CDevLinkWriter::begin().
NewCopy()
virtual CIccTag * CIccTagLut8::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccMBB.
{return new CIccTagLut8(*this);}
References CIccTagLut8().
NewCurvesA()
LPIccCurve * CIccMBB::NewCurvesA () inherited
Name: CIccMBB::NewCurvesA
Purpose: Allocates memory for a new set of A-curves
Return: Pointer to the LPIccCurve object
{
  if (m_CurvesA)
    return m_CurvesA;
  icUInt8Number nCurves = !IsInputB() ? m_nInput : m_nOutput;
  m_CurvesA = new LPIccCurve[nCurves];
  memset(m_CurvesA, 0, nCurves * sizeof(LPIccCurve));
  return m_CurvesA;
}
References CIccMBB::IsInputB(), CIccMBB::m_CurvesA, CIccMBB::m_nInput, and CIccMBB::m_nOutput.
Referenced by CDevLinkWriter::begin(), icMBBFromXml(), CIccTagLutAtoB::Read(), Read(), and CIccTagLut16::Read().
NewCurvesB()
LPIccCurve * CIccMBB::NewCurvesB () inherited
Name: CIccMBB::NewCurvesB
Purpose: Allocates memory for a new set of B-curves
Return: Pointer to the LPIccCurve object
{
  if (m_CurvesB)
    return m_CurvesB;
  icUInt8Number nCurves = IsInputB() ? m_nInput : m_nOutput;
  m_CurvesB = new LPIccCurve[nCurves];
  memset(m_CurvesB, 0, nCurves * sizeof(LPIccCurve));
  return m_CurvesB;
}
References CIccMBB::IsInputB(), CIccMBB::m_CurvesB, CIccMBB::m_nInput, and CIccMBB::m_nOutput.
Referenced by CDevLinkWriter::begin(), icMBBFromXml(), CIccTagLutAtoB::Read(), Read(), CIccTagLut16::Read(), SetColorSpaces(), and CIccTagLut16::SetColorSpaces().
NewCurvesM()
LPIccCurve * CIccMBB::NewCurvesM () inherited
Name: CIccMBB::NewCurvesM
Purpose: Allocates memory for a new set of M-curves
Return: Pointer to the LPIccCurve object
{
  if (m_CurvesM)
    return m_CurvesM;
  icUInt8Number nCurves = IsInputMatrix() ? m_nInput : m_nOutput;
  m_CurvesM = new LPIccCurve[nCurves];
  memset(m_CurvesM, 0, nCurves * sizeof(LPIccCurve));
  return m_CurvesM;
}
References CIccMBB::IsInputMatrix(), CIccMBB::m_CurvesM, CIccMBB::m_nInput, and CIccMBB::m_nOutput.
Referenced by icMBBFromXml(), and CIccTagLutAtoB::Read().
NewMatrix()
CIccMatrix * CIccMBB::NewMatrix () inherited
Name: CIccMBB::NewMatrix
Purpose: Allocates memory for a new matrix
Return: Pointer to the CIccMatrix object
{
  if (m_Matrix)
    return m_Matrix;
  m_Matrix = new CIccMatrix;
  return m_Matrix;
}
References CIccMBB::m_Matrix.
Referenced by icMBBFromXml(), SetColorSpaces(), and CIccTagLut16::SetColorSpaces().
operator=()
CIccTagLut8 & CIccTagLut8::operator= (const CIccTagLut8 & ITL)
Name: CIccTagLut8::operator=
Purpose: Copy Operator
Args: ITL = The CIccTagLut8 object to be copied
{
  if (&ITL==this)
    return *this;
  CIccMBB::operator=(ITL);
  memcpy(&m_XYZMatrix, &ITL.m_XYZMatrix, sizeof(m_XYZMatrix));
  return *this;
}
References m_XYZMatrix, and CIccMBB::operator=().
OutputChannels()
icUInt8Number CIccMBB::OutputChannels () const inline inherited
{ return m_nOutput; }
References CIccMBB::m_nOutput.
Referenced by icMBBToXml().
Read() [1/2]
bool CIccTagLut8::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagLut8::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  icUInt32Number nStart, nEnd;
  icUInt8Number i, nGrid;
  LPIccCurve *pCurves;
  CIccTagCurve *pCurve;
  if (size<13*sizeof(icUInt32Number) || !pIO) {
    return false;
  }
  nStart = pIO->Tell();
  nEnd = nStart + size;
  if (!pIO->Read32(&sig) ||
      !pIO->Read32(&m_nReserved) ||
      !pIO->Read8(&m_nInput) ||
      !pIO->Read8(&m_nOutput) ||
      !pIO->Read8(&nGrid) ||
      !pIO->Read8(&m_nReservedByte) ||
      pIO->Read32(m_XYZMatrix, 9) != 9)
    return false;
  if (sig!=GetType())
    return false;
  //B Curves
  pCurves = NewCurvesB();
  for (i=0; i<m_nInput; i++) {
    if (256 > nEnd - pIO->Tell())
      return false;
    pCurves[i] = pCurve = (CIccTagCurve*)CIccTag::Create(icSigCurveType);
    if (!pCurve->SetSize(256))
      return false;
    if (pIO->ReadUInt8Float(&(*pCurve)[0], 256) != 256)
      return false;
  }
  //CLUT
  m_CLUT = new CIccCLUT(m_nInput, m_nOutput);
  if (m_CLUT == NULL)
    return false;
  if (!m_CLUT->Init(nGrid, nEnd - pIO->Tell(), 1))
    return false;
  if (!m_CLUT->ReadData(nEnd - pIO->Tell(), pIO, 1))
    return false;
  //A Curves
  pCurves = NewCurvesA();
  if (pCurves == NULL)
    return false;
  for (i=0; i<m_nOutput; i++) {
    if (256 > nEnd - pIO->Tell())
      return false;
    pCurves[i] = pCurve = (CIccTagCurve*)CIccTag::Create(icSigCurveType);
    if (!pCurve->SetSize(256))
      return false;
    if (pIO->ReadUInt8Float(&(*pCurve)[0], 256) != 256)
      return false;
  }
  return true;
}
References CIccCLUT::CIccCLUT(), CIccTag::Create(), GetType(), icSigCurveType, CIccCLUT::Init(), CIccMBB::m_CLUT, CIccMBB::m_nInput, CIccMBB::m_nOutput, CIccTag::m_nReserved, m_nReservedByte, m_XYZMatrix, CIccMBB::NewCurvesA(), CIccMBB::NewCurvesB(), CIccTagCurve::operator[](), CIccIO::Read32(), CIccIO::Read8(), CIccCLUT::ReadData(), CIccIO::ReadUInt8Float(), CIccTagCurve::SetSize(), and CIccIO::Tell().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
SetCLUT()
CIccCLUT * CIccMBB::SetCLUT (CIccCLUT * clut) inherited
Name: CIccMBB::SetCLUT
Purpose: Assignes CLUT connection to an initialized new CLUT
Args: clut = pointer to a previously allocated CLUT (Onwership is transfered to CIccMBB object).
Return: Pointer to the CIccCLUT object or NULL if clut is incompatible with CIccMBB object. If the clut is incompatible it is deleted.
{
  if (clut->GetInputDim() != m_nInput || clut->GetOutputChannels() != m_nOutput) {
    delete clut;
    return NULL;
  }
  if (m_CLUT) {
    delete m_CLUT;
  }
  m_CLUT = clut;
  return clut;
}
References CIccCLUT::GetInputDim(), CIccCLUT::GetOutputChannels(), CIccMBB::m_CLUT, CIccMBB::m_nInput, and CIccMBB::m_nOutput.
Referenced by icMBBFromXml().
SetColorSpaces()
void CIccTagLut8::SetColorSpaces (icColorSpaceSignature csInput, icColorSpaceSignature csOutput) virtual
Name: CIccTagLut8::SetColorSpaces
Purpose: Sets the input and output color spaces
Args: csInput = input color space signature, csOutput = output color space signature
Reimplemented from CIccMBB.
{
  if (csInput==icSigXYZData) {
    int i;
    if (!m_CurvesM && IsInputMatrix()) { //Transfer ownership of curves
      m_CurvesM = m_CurvesB;
      m_CurvesB = NULL;
      LPIccCurve *pCurves = NewCurvesB();
      CIccTagCurve *pCurve;
      for (i=0; i<m_nInput; i++) {
        pCurves[i] = pCurve = (CIccTagCurve*)CIccTag::Create(icSigCurveType);
        pCurve->SetSize(0);
      }
      m_bUseMCurvesAsBCurves = true;
    }
    if (!m_Matrix) {
      CIccMatrix *pMatrix = NewMatrix();
      for (i=0; i<9; i++) {
        pMatrix->m_e[i] = icFtoD(m_XYZMatrix[i]);
      }
      pMatrix->m_bUseConstants=false;
    }
  }
  else {
    m_XYZMatrix[0] = m_XYZMatrix[4] = m_XYZMatrix[8] = icDtoF(1.0);
    m_XYZMatrix[1] = m_XYZMatrix[2] = m_XYZMatrix[3] =
    m_XYZMatrix[5] = m_XYZMatrix[6] = m_XYZMatrix[7] = 0;
  }
  CIccMBB::SetColorSpaces(csInput, csOutput);
}
References CIccTag::Create(), icDtoF(), icFtoD(), icSigCurveType, icSigXYZData, CIccMBB::IsInputMatrix(), CIccMatrix::m_bUseConstants, CIccMBB::m_bUseMCurvesAsBCurves, CIccMBB::m_CurvesB, CIccMBB::m_CurvesM, CIccMatrix::m_e, CIccMBB::m_Matrix, CIccMBB::m_nInput, m_XYZMatrix, CIccMBB::NewCurvesB(), CIccMBB::NewMatrix(), CIccMBB::SetColorSpaces(), and CIccTagCurve::SetSize().
SwapMBCurves()
bool CIccMBB::SwapMBCurves () inline inherited
{ return m_bUseMCurvesAsBCurves; }
References CIccMBB::m_bUseMCurvesAsBCurves.
Referenced by icMBBToXml().
UseLegacyPCS()
virtual bool CIccMBB::UseLegacyPCS () const inline virtual inherited
Reimplemented in CIccTagLut16.
{ return false; } //Treat Lab Encoding differently?
Validate() [1/2]
icValidateStatus CIccTagLut8::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) virtual
Name: CIccTagLut8::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccMBB.
{
  icValidateStatus rv = CIccMBB::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  icSignature sig = icGetFirstSigPathSig(sigPath);
  if (!pProfile) {
    return rv;
  }
  switch(sig) {
  case icSigAToB0Tag:
  case icSigAToB1Tag:
  case icSigAToB2Tag:
  case icSigBToA0Tag:
  case icSigBToA1Tag:
  case icSigBToA2Tag:
  case icSigGamutTag:
    {
      icUInt32Number nInput, nOutput;
      if (sig==icSigAToB0Tag || sig==icSigAToB1Tag || sig==icSigAToB2Tag || sig==icSigGamutTag) {
        nInput = icGetSpaceSamples(pProfile->m_Header.pcs);
        nOutput = icGetSpaceSamples(pProfile->m_Header.colorSpace);
      }
      else {
        nInput = icGetSpaceSamples(pProfile->m_Header.colorSpace);
        nOutput = icGetSpaceSamples(pProfile->m_Header.pcs);
      }
      if (sig==icSigGamutTag) {
        nOutput = 1;
      }
      icUInt8Number i;
      if (m_CurvesB) {
        for (i=0; i<nInput; i++) {
          if (m_CurvesB[i]) {
            rv = icMaxStatus(rv, m_CurvesB[i]->Validate(sigPath+icGetSigPath(GetType()), sReport, pProfile));
            if (m_CurvesB[i]->GetType()==icSigCurveType) {
              CIccTagCurve *pTagCurve = (CIccTagCurve*)m_CurvesB[i];
              if (pTagCurve->GetSize()==1) {
                sReport += icMsgValidateCriticalError;
                sReport += sSigPathName;
                sReport += " - lut8Tags do not support single entry gamma curves.\n";
                rv = icMaxStatus(rv, icValidateCriticalError);
              }
            }
          }
          else {
            sReport += icMsgValidateCriticalError;
            sReport += sSigPathName;
            sReport += " - Incorrect number of B-curves.\n";
            rv = icMaxStatus(rv, icValidateCriticalError);
          }
        }
      }
      if (m_Matrix) {
        rv = icMaxStatus(rv, m_Matrix->Validate(sigPath + icGetSigPath(GetType()), sReport, pProfile));
      }
      else {
        int sum=0;
        for (int i=0; i<9; i++) {
          sum += m_XYZMatrix[i];
        }
        if (m_XYZMatrix[0]!=1.0 || m_XYZMatrix[4]!=1.0 || m_XYZMatrix[8]!=1.0 || sum!=3.0) {
          sReport += icMsgValidateWarning;
          sReport += sSigPathName;
          sReport += " - Matrix must be identity.\n";
          rv = icMaxStatus(rv, icValidateWarning);
        }
      }
      if (m_CurvesA) {
        for (i=0; i<nOutput; i++) {
          if (m_CurvesA[i]) {
            rv = icMaxStatus(rv, m_CurvesA[i]->Validate(sigPath+icGetSigPath(GetType()), sReport, pProfile));
            if (m_CurvesA[i]->GetType()==icSigCurveType) {
              CIccTagCurve *pTagCurve = (CIccTagCurve*)m_CurvesA[i];
              if (pTagCurve->GetSize()==1) {
                sReport += icMsgValidateCriticalError;
                sReport += sSigPathName;
                sReport += " - lut8Tags do not support single entry gamma curves.\n";
                rv = icMaxStatus(rv, icValidateCriticalError);
              }
            }
          }
          else {
            sReport += icMsgValidateCriticalError;
            sReport += sSigPathName;
            sReport += " - Incorrect number of A-curves.\n";
            rv = icMaxStatus(rv, icValidateCriticalError);
          }
        }
      }
      break;
    }
  default:
    {
    }
  }
  return rv;
}
References icHeader::colorSpace, CIccInfo::GetSigPathName(), CIccTagCurve::GetSize(), CIccTag::GetType(), GetType(), icGetFirstSigPathSig(), icGetSigPath(), icGetSpaceSamples(), icMaxStatus(), icMsgValidateCriticalError, icMsgValidateWarning, icSigAToB0Tag, icSigAToB1Tag, icSigAToB2Tag, icSigBToA0Tag, icSigBToA1Tag, icSigBToA2Tag, icSigCurveType, icSigGamutTag, icValidateCriticalError, icValidateWarning, CIccMBB::m_CurvesA, CIccMBB::m_CurvesB, CIccMBB::m_Matrix, m_XYZMatrix, icHeader::pcs, CIccMBB::Validate(), CIccTag::Validate(), and CIccMatrix::Validate().
Validate() [2/2]
icValidateStatus CIccTag::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual inherited
Function: Validate Each derived tag will implement it's own IsValid() function
Parameter(s): sig - signature of tag being validated, sDescription - A string to put tag validation report.
Name: CIccTag::Validate
Purpose: Check tag data validity. In base class we only look at the tag's reserved data value
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented in CIccTagGamutBoundaryDesc, CIccTagText, CIccTagUtf8Text, CIccTagZipUtf8Text, CIccTagUtf16Text, CIccTagTextDescription, CIccTagSignature, CIccTagNamedColor2, CIccTagXYZ, CIccTagChromaticity, CIccTagCicp, CIccTagSparseMatrixArray, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, CIccTagMeasurement, CIccTagMultiLocalizedUnicode, CIccTagData, CIccTagDateTime, CIccTagColorantOrder, CIccTagColorantTable, CIccTagViewingConditions, CIccTagProfileSeqDesc, CIccTagResponseCurveSet16, CIccTagSpectralDataInfo, CIccTagSpectralViewingConditions, CIccTagEmbeddedHeightImage, CIccTagEmbeddedNormalImage, CIccTagStruct, CIccTagArray, CIccTagDict, CIccTagEmbeddedProfile, CIccTagCurve, CIccTagParametricCurve, CIccTagSegmentedCurve, CIccTagMultiProcessElement, and CIccTagProfileSequenceId.
{
  icValidateStatus rv = icValidateOK;
  if (m_nReserved != 0) {
    CIccInfo Info;
    sReport += icMsgValidateNonCompliant;
    sReport += Info.GetSigPathName(sigPath);
    sReport += " - Reserved Value must be zero.\n";
    rv = icValidateNonCompliant;
  }
  return rv;
}
References CIccInfo::GetSigPathName(), icMsgValidateNonCompliant, icValidateNonCompliant, icValidateOK, and CIccTag::m_nReserved.
Referenced by CIccTagGamutBoundaryDesc::Validate(), CIccMBB::Validate(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), Validate(), CIccTagLut16::Validate(), CIccArrayUnknown::Validate(), CIccArrayColorantInfo::Validate(), CIccArrayNamedColor::Validate(), CIccStructUnknown::Validate(), CIccTagText::Validate(), CIccTagUtf8Text::Validate(), CIccTagZipUtf8Text::Validate(), CIccTagUtf16Text::Validate(), CIccTagTextDescription::Validate(), CIccTagSignature::Validate(), CIccTagNamedColor2::Validate(), CIccTagXYZ::Validate(), CIccTagChromaticity::Validate(), CIccTagCicp::Validate(), CIccTagNum< T, Tsig >::Validate(), CIccTagFloatNum< T, Tsig >::Validate(), CIccTagMeasurement::Validate(), CIccTagMultiLocalizedUnicode::Validate(), CIccTagData::Validate(), CIccTagDateTime::Validate(), CIccTagColorantOrder::Validate(), CIccTagColorantTable::Validate(), CIccTagViewingConditions::Validate(), CIccTagProfileSeqDesc::Validate(), CIccTagResponseCurveSet16::Validate(), CIccTagSpectralDataInfo::Validate(), CIccTagSpectralViewingConditions::Validate(), CIccTagEmbeddedHeightImage::Validate(), CIccTagEmbeddedNormalImage::Validate(), CIccTagStruct::Validate(), CIccTagArray::Validate(), CIccTagDict::Validate(), CIccTagEmbeddedProfile::Validate(), CIccTagCurve::Validate(), CIccTagParametricCurve::Validate(), and CIccTagProfileSequenceId::Validate().
Write()
bool CIccTagLut8::Write (CIccIO * pIO) virtual
Name: CIccTagLut8::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  icUInt8Number i, nGrid;
  icS15Fixed16Number XYZMatrix[9];
  icUInt16Number nInputEntries, nOutputEntries;
  LPIccCurve *pCurves;
  CIccTagCurve *pCurve;
  icFloat32Number v;
  if (m_Matrix) {
    for (i=0; i<9; i++)
      XYZMatrix[i] = icDtoF(m_Matrix->m_e[i]);
  }
  else {
    memset(XYZMatrix, 0, 9*sizeof(icS15Fixed16Number));
    XYZMatrix[0] = XYZMatrix[4] = XYZMatrix[8] = icDtoF(1.0);
  }
  if (m_bUseMCurvesAsBCurves) {
    pCurves = m_CurvesM;
  }
  else {
    pCurves = m_CurvesB;
  }
  if (!pCurves || !m_CurvesA || !m_CLUT)
    return false;
  nGrid = m_CLUT->GridPoints();
  nInputEntries = (icUInt16Number)(((CIccTagCurve*)pCurves[0])->GetSize());
  nOutputEntries = (icUInt16Number)(((CIccTagCurve*)m_CurvesA[0])->GetSize());
  if (!pIO->Write32(&sig) ||
      !pIO->Write32(&m_nReserved) ||
      !pIO->Write8(&m_nInput) ||
      !pIO->Write8(&m_nOutput) ||
      !pIO->Write8(&nGrid) ||
      !pIO->Write8(&m_nReservedByte) ||
      pIO->Write32(XYZMatrix, 9) != 9)
    return false;
  //B Curves
  for (i=0; i<m_nInput; i++) {
    if (pCurves[i]->GetType()!=icSigCurveType)
      return false;
    pCurve = (CIccTagCurve*)pCurves[i];
    if (!pCurve)
      return false;
    if (pCurve->GetSize()!=256) {
      icUInt32Number j;
      for (j=0; j<256; j++) {
        v = pCurve->Apply((icFloat32Number)j / 255.0F);
        if (!pIO->WriteUInt8Float(&v, 1))
          return false;
      }
    }
    else {
      if (pIO->WriteUInt8Float(&(*pCurve)[0], 256)!=256)
        return false;
    }
  }
  //CLUT
  if (!m_CLUT->WriteData(pIO, 1))
    return false;
  //A Curves
  pCurves = m_CurvesA;
  for (i=0; i<m_nOutput; i++) {
    if (pCurves[i]->GetType()!=icSigCurveType)
      return false;
    pCurve = (CIccTagCurve*)pCurves[i];
    if (!pCurve)
      return false;
    if (pCurve->GetSize()!=256) {
      icUInt32Number j;
      for (j=0; j<256; j++) {
        v = pCurve->Apply((icFloat32Number)j / 255.0F);
        if (!pIO->WriteUInt8Float(&v, 1))
          return false;
      }
    }
    else {
      if (pIO->WriteUInt8Float(&(*pCurve)[0], 256)!=256)
        return false;
    }
  }
  return true;
}
References CIccTagCurve::Apply(), CIccTagCurve::GetSize(), CIccTag::GetType(), GetType(), CIccCLUT::GridPoints(), icDtoF(), icSigCurveType, CIccMBB::m_bUseMCurvesAsBCurves, CIccMBB::m_CLUT, CIccMBB::m_CurvesA, CIccMBB::m_CurvesB, CIccMBB::m_CurvesM, CIccMatrix::m_e, CIccMBB::m_Matrix, CIccMBB::m_nInput, CIccMBB::m_nOutput, CIccTag::m_nReserved, m_nReservedByte, CIccTagCurve::operator[](), CIccIO::Write32(), CIccIO::Write8(), CIccCLUT::WriteData(), and CIccIO::WriteUInt8Float().
Field Documentation
m_bInputMatrix
bool CIccMBB::m_bInputMatrix protected inherited
Referenced by CIccMBB::CIccMBB(), CIccMBB::CIccMBB(), CIccTagLutAtoB::CIccTagLutAtoB(), CIccTagLutBtoA::CIccTagLutBtoA(), CIccMBB::IsInputMatrix(), and CIccMBB::operator=().
m_bUseMCurvesAsBCurves
bool CIccMBB::m_bUseMCurvesAsBCurves protected inherited
Referenced by CIccMBB::CIccMBB(), CIccMBB::CIccMBB(), CIccMBB::Describe(), CIccMBB::operator=(), SetColorSpaces(), CIccTagLut16::SetColorSpaces(), CIccMBB::SwapMBCurves(), Write(), and CIccTagLut16::Write().
m_CLUT
CIccCLUT* CIccMBB::m_CLUT protected inherited
Referenced by CIccMBB::CIccMBB(), CIccMBB::CIccMBB(), CIccMBB::Cleanup(), CIccMBB::Describe(), CIccMBB::GetCLUT(), CIccMBB::NewCLUT(), CIccMBB::NewCLUT(), CIccMBB::operator=(), CIccTagLutAtoB::Read(), Read(), CIccTagLut16::Read(), CIccMBB::SetCLUT(), CIccMBB::Validate(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLutAtoB::Write(), Write(), and CIccTagLut16::Write().
m_csInput
icColorSpaceSignature CIccMBB::m_csInput protected inherited
Referenced by CIccMBB::CIccMBB(), CIccMBB::CIccMBB(), CIccMBB::Describe(), CIccMBB::GetCsInput(), CIccMBB::operator=(), and CIccMBB::SetColorSpaces().
m_csOutput
icColorSpaceSignature CIccMBB::m_csOutput protected inherited
Referenced by CIccMBB::CIccMBB(), CIccMBB::CIccMBB(), CIccMBB::Describe(), CIccMBB::GetCsOutput(), CIccMBB::operator=(), and CIccMBB::SetColorSpaces().
m_CurvesA
LPIccCurve* CIccMBB::m_CurvesA protected inherited
Referenced by CIccMBB::CIccMBB(), CIccMBB::CIccMBB(), CIccMBB::Cleanup(), CIccMBB::Describe(), CIccMBB::GetCurvesA(), CIccMBB::NewCurvesA(), CIccMBB::operator=(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), Validate(), CIccTagLut16::Validate(), CIccTagLutAtoB::Write(), Write(), and CIccTagLut16::Write().
m_CurvesB
LPIccCurve* CIccMBB::m_CurvesB protected inherited
Referenced by CIccMBB::CIccMBB(), CIccMBB::CIccMBB(), CIccMBB::Cleanup(), CIccMBB::Describe(), CIccMBB::GetCurvesB(), CIccMBB::NewCurvesB(), CIccMBB::operator=(), SetColorSpaces(), CIccTagLut16::SetColorSpaces(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), Validate(), CIccTagLut16::Validate(), CIccTagLutAtoB::Write(), Write(), and CIccTagLut16::Write().
m_CurvesM
LPIccCurve* CIccMBB::m_CurvesM protected inherited
Referenced by CIccMBB::CIccMBB(), CIccMBB::CIccMBB(), CIccMBB::Cleanup(), CIccMBB::Describe(), CIccMBB::GetCurvesM(), CIccMBB::NewCurvesM(), CIccMBB::operator=(), SetColorSpaces(), CIccTagLut16::SetColorSpaces(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLutAtoB::Write(), Write(), and CIccTagLut16::Write().
m_Matrix
CIccMatrix* CIccMBB::m_Matrix protected inherited
Referenced by CIccMBB::CIccMBB(), CIccMBB::CIccMBB(), CIccMBB::Cleanup(), CIccMBB::Describe(), CIccMBB::GetMatrix(), CIccMBB::NewMatrix(), CIccMBB::operator=(), CIccTagLutAtoB::Read(), SetColorSpaces(), CIccTagLut16::SetColorSpaces(), Validate(), CIccTagLut16::Validate(), CIccTagLutAtoB::Write(), Write(), and CIccTagLut16::Write().
m_nInput
icUInt8Number CIccMBB::m_nInput protected inherited
Referenced by CIccMBB::CIccMBB(), CIccMBB::CIccMBB(), CIccMBB::Cleanup(), CIccMBB::Describe(), CIccMBB::Init(), CIccMBB::InputChannels(), CIccMBB::NewCLUT(), CIccMBB::NewCLUT(), CIccMBB::NewCurvesA(), CIccMBB::NewCurvesB(), CIccMBB::NewCurvesM(), CIccMBB::operator=(), CIccTagLutAtoB::Read(), Read(), CIccTagLut16::Read(), CIccMBB::SetCLUT(), SetColorSpaces(), CIccTagLut16::SetColorSpaces(), CIccMBB::Validate(), CIccTagLutAtoB::Write(), Write(), and CIccTagLut16::Write().
m_nOutput
icUInt8Number CIccMBB::m_nOutput protected inherited
Referenced by CIccMBB::CIccMBB(), CIccMBB::CIccMBB(), CIccMBB::Cleanup(), CIccMBB::Describe(), CIccMBB::Init(), CIccMBB::NewCLUT(), CIccMBB::NewCLUT(), CIccMBB::NewCurvesA(), CIccMBB::NewCurvesB(), CIccMBB::NewCurvesM(), CIccMBB::operator=(), CIccMBB::OutputChannels(), CIccTagLutAtoB::Read(), Read(), CIccTagLut16::Read(), CIccMBB::SetCLUT(), CIccMBB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLutAtoB::Write(), Write(), and CIccTagLut16::Write().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_nReservedByte
icUInt8Number CIccTagLut8::m_nReservedByte protected
Referenced by CIccTagLut8(), CIccTagLut8(), Read(), and Write().
m_XYZMatrix
icS15Fixed16Number CIccTagLut8::m_XYZMatrix[9] protected
Referenced by CIccTagLut8(), CIccTagLut8(), operator=(), Read(), SetColorSpaces(), and Validate().
The documentation for this class was generated from the following files:
IccProfLib/IccTagLut.h
IccProfLib/IccTagLut.cpp