iccDEV: CIccProfileDescText Class Reference
CIccProfileDescText Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccProfileDescText ()
CIccProfileDescText (const CIccProfileDescText &IPDC)
virtual ~CIccProfileDescText ()
virtual void Describe (std::string &sDescription, int nVerboseness)
CIccTag * GetTag () const
virtual icTagTypeSignature GetType () const
CIccProfileDescText & operator= (const CIccProfileDescText &ProfDescText)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
bool SetType (icTagTypeSignature nType)
virtual bool Write (CIccIO *pIO)
Data Fields
bool m_bNeedsPading
Protected Attributes
CIccTag * m_pTag
Detailed Description
Data Class: CIccProfileDescText
Purpose: Private text class for CIccProfileDescStruct. Text can be either a CIccTagTextDescription or a CIccTagMultiLocalizedUnicode so this class provides a single interface to both.
Constructor & Destructor Documentation
CIccProfileDescText() [1/2]
CIccProfileDescText::CIccProfileDescText ()
Name: CIccProfileDescText::CIccProfileDescText
Purpose: Constructor
{
  m_pTag = NULL;
  m_bNeedsPading = false;
}
References m_bNeedsPading, and m_pTag.
CIccProfileDescText() [2/2]
CIccProfileDescText::CIccProfileDescText (const CIccProfileDescText & IPDC)
Name: CIccProfileDescText::CIccProfileDescText
Purpose: Copy Constructor
Args: IPDC = The CIccTagUnknown object to be copied
{
  if (IPDC.m_pTag) {
    m_pTag = IPDC.m_pTag->NewCopy();
    m_bNeedsPading = IPDC.m_bNeedsPading;
  }
  else {
    m_pTag = NULL;
    m_bNeedsPading = false;
  }
}
References m_bNeedsPading, m_pTag, and CIccTag::NewCopy().
~CIccProfileDescText()
CIccProfileDescText::~CIccProfileDescText () virtual
Name: CIccProfileDescText::~CIccProfileDescText
Purpose: Destructor
{
  if (m_pTag)
    delete m_pTag;
}
References m_pTag.
Member Function Documentation
Describe()
void CIccProfileDescText::Describe (std::string & sDescription, int nVerboseness) virtual
Name: CIccProfileDescText::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
{
  if (m_pTag)
    m_pTag->Describe(sDescription, nVerboseness);
}
References CIccTag::Describe(), and m_pTag.
Referenced by CIccTagProfileSeqDesc::Describe().
GetTag()
CIccTag * CIccProfileDescText::GetTag () const inline
{ return m_pTag; }
References m_pTag.
Referenced by icProfDescToXml(), icXmlParseProfDesc(), CDevLinkWriter::iterate(), and CIccTagProfileSeqDesc::Validate().
GetType()
icTagTypeSignature CIccProfileDescText::GetType () const virtual
Name: CIccProfileDescText::SetType
Purpose: Gets the type of the profile description text. Could be either a MultiLocalizedUnicodeType or a TextDescriptionType.
{
  if (m_pTag)
    return m_pTag->GetType();
  return icSigUnknownType;
}
References CIccTag::GetType(), and m_pTag.
operator=()
CIccProfileDescText & CIccProfileDescText::operator= (const CIccProfileDescText & ProfDescText)
Name: CIccProfileDescText::operator=
Purpose: Copy Operator
Args: ProfDescText = The CIccProfileDescText object to be copied
{
  if (&ProfDescText == this)
    return *this;
  if (m_pTag)
    delete m_pTag;
  if (ProfDescText.m_pTag) {
    m_pTag = ProfDescText.m_pTag->NewCopy();
    m_bNeedsPading = ProfDescText.m_bNeedsPading;
  }
  else {
    m_pTag = NULL;
    m_bNeedsPading = false;
  }
  return *this;
}
References m_bNeedsPading, m_pTag, and CIccTag::NewCopy().
Referenced by CIccProfileDescStruct::CIccProfileDescStruct(), and CIccProfileDescStruct::operator=().
Read()
bool CIccProfileDescText::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccProfileDescText::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
{
  icTagTypeSignature sig;
  icUInt32Number nPos;
  //Check for description tag type signature
  nPos = pIO->Tell();
  if ((nPos&0x03) != 0)
    m_bNeedsPading = true;
  if (!pIO->Read32(&sig))
    return false;
  pIO->Seek(nPos, icSeekSet);
  if (sig==icSigTextDescriptionType)
    m_bNeedsPading = false;
  if (!SetType(sig)) {
    //We couldn't find it, but we may be looking in the wrong place
    //Re-Sync to a 4 byte boundary
    pIO->Sync32();
    nPos = pIO->Tell();
    if (!pIO->Read32(&sig))
      return false;
    pIO->Seek(nPos, icSeekSet);
    if (!SetType(sig)) {
      return false;
    }
  }
  if (m_pTag) {
    return m_pTag->Read(size, pIO);
  }
  return false;
}
References icSeekSet, icSigTextDescriptionType, m_bNeedsPading, m_pTag, CIccTag::Read(), CIccIO::Read32(), CIccIO::Seek(), SetType(), CIccIO::Sync32(), and CIccIO::Tell().
Referenced by CIccTagProfileSeqDesc::Read().
SetType()
bool CIccProfileDescText::SetType (icTagTypeSignature nType)
Name: CIccProfileDescText::SetType
Purpose: Sets the type of the profile description text. Could be either a MultiLocalizedUnicodeType or a TextDescriptionType.
Args: nType = the tag type signature
Return: true = successful, false = failure
{
  if (m_pTag) {
    if (m_pTag->GetType() == nType)
      return true;
    delete m_pTag;
  }
  if (nType == icSigMultiLocalizedUnicodeType ||
      nType == icSigTextDescriptionType)
    m_pTag = CIccTag::Create(nType);
  else
    m_pTag = NULL;
  return(m_pTag != NULL);
}
References CIccTag::Create(), CIccTag::GetType(), icSigMultiLocalizedUnicodeType, icSigTextDescriptionType, and m_pTag.
Referenced by icXmlParseProfDesc(), CDevLinkWriter::iterate(), and Read().
Write()
bool CIccProfileDescText::Write (CIccIO * pIO) virtual
Name: CIccProfileDescText::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
{
  if (!m_pTag)
    return false;
  if (m_pTag->Write(pIO)) {
    if (m_pTag->GetType() != icSigTextDescriptionType)
      return pIO->Align32();
    else
      return true;
  }
  return false;
}
References CIccIO::Align32(), CIccTag::GetType(), icSigTextDescriptionType, m_pTag, and CIccTag::Write().
Referenced by CIccTagProfileSeqDesc::Write().
Field Documentation
m_bNeedsPading
bool CIccProfileDescText::m_bNeedsPading
Referenced by CIccProfileDescText(), CIccProfileDescText(), operator=(), Read(), and CIccTagProfileSeqDesc::Validate().
m_pTag
CIccTag* CIccProfileDescText::m_pTag protected
Referenced by CIccProfileDescText(), CIccProfileDescText(), ~CIccProfileDescText(), Describe(), GetTag(), GetType(), operator=(), Read(), SetType(), and Write().
The documentation for this class was generated from the following files:
IccProfLib/IccTagBasic.h
IccProfLib/IccTagBasic.cpp