iccDEV: CIccEmbedIO Class Reference
CIccEmbedIO Class Reference
#include <IccIO.h>
Public Member Functions
CIccEmbedIO ()
virtual ~CIccEmbedIO ()
bool Align32 ()
Write operation to make sure that filelength is evenly divisible by 4.
bool Attach (CIccIO *pIO, icInt32Number nSize=0, bool bOwnIO=false)
virtual void Close ()
virtual icInt32Number GetLength ()
icInt32Number Read16 (void *pBuf16, icInt32Number nNum=1)
icInt32Number Read32 (void *pBuf32, icInt32Number nNum=1)
icInt32Number Read64 (void *pBuf64, icInt32Number nNum=1)
virtual icInt32Number Read8 (void *pBuf, icInt32Number nNum=1)
icInt32Number ReadFloat16Float (void *pBufFloat, icInt32Number nNum=1)
icInt32Number ReadFloat32Float (void *pBufFloat, icInt32Number nNum=1)
icInt32Number ReadLine (void *pBuf8, icInt32Number nNum=256)
icInt32Number ReadUInt16Float (void *pBufFloat, icInt32Number nNum=1)
icInt32Number ReadUInt8Float (void *pBufFloat, icInt32Number nNum=1)
virtual icInt32Number Seek (icInt32Number nOffset, icSeekVal pos)
bool Sync32 (icUInt32Number nOffset=0)
Operation to make sure read position is evenly divisible by 4.
virtual icInt32Number Tell ()
icInt32Number Write16 (void *pBuf16, icInt32Number nNum=1)
icInt32Number Write32 (void *pBuf32, icInt32Number nNum=1)
icInt32Number Write64 (void *pBuf64, icInt32Number nNum=1)
virtual icInt32Number Write8 (void *pBuf, icInt32Number nNum=1)
icInt32Number WriteFloat16Float (void *pBuf16, icInt32Number nNum=1)
icInt32Number WriteFloat32Float (void *pBufFloat, icInt32Number nNum=1)
icInt32Number WriteUInt16Float (void *pBuf16, icInt32Number nNum=1)
icInt32Number WriteUInt8Float (void *pBuf16, icInt32Number nNum=1)
Protected Attributes
bool m_bOwnIO
icInt32Number m_nSize
icInt32Number m_nStartPos
CIccIO * m_pIO
Detailed Description
Type: Class
Purpose: Handles embedding a file within a file
Constructor & Destructor Documentation
CIccEmbedIO()
CIccEmbedIO::CIccEmbedIO ()
                         : CIccIO()
{
  m_pIO = NULL;
  m_nStartPos = 0;
  m_nSize = -1;
  m_bOwnIO = false;
}
References m_bOwnIO, m_nSize, m_nStartPos, and m_pIO.
Referenced by CIccTagEmbeddedProfile::Read().
~CIccEmbedIO()
CIccEmbedIO::~CIccEmbedIO () virtual
{
  Close();
}
References Close().
Member Function Documentation
Align32()
bool CIccIO::Align32 () inherited
Write operation to make sure that filelength is evenly divisible by 4.
{
  int mod = GetLength() % 4;
  if (mod != 0) {
    icUInt8Number buf[4]={0,0,0,0};
    if (Seek(0, icSeekEnd)<0)
      return false;
    if (Write8(buf, 4-mod) != 4-mod)
      return false;
  }
  return true;
}
References CIccIO::GetLength(), icSeekEnd, CIccIO::Seek(), and CIccIO::Write8().
Referenced by CIccMpeCurveSet::Write(), CIccMpeToneMap::Write(), CIccMpeCalculator::Write(), CIccTagSparseMatrixArray::Write(), CIccProfileDescText::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
Attach()
bool CIccEmbedIO::Attach (CIccIO * pIO, icInt32Number nSize = 0, bool bOwnIO = false)
{
  if (!pIO)
    return false;
  m_nStartPos = pIO->Tell();
  m_nSize = nSize;
  m_bOwnIO = bOwnIO;
  m_pIO = pIO;
  if (m_nStartPos < 0)
    return false;
  return true;
}
References m_bOwnIO, m_nSize, m_nStartPos, m_pIO, and CIccIO::Tell().
Referenced by CIccTagEmbeddedProfile::Read(), and CIccTagEmbeddedProfile::Write().
Close()
void CIccEmbedIO::Close () virtual
Reimplemented from CIccIO.
{
  if (m_pIO && m_bOwnIO) {
    m_pIO->Close();
    delete m_pIO;
    m_pIO = NULL;
  }
}
References CIccIO::Close(), m_bOwnIO, and m_pIO.
Referenced by ~CIccEmbedIO().
GetLength()
icInt32Number CIccEmbedIO::GetLength () virtual
Reimplemented from CIccIO.
{
  if (!m_pIO)
    return 0;
  if (m_nSize)
    return m_nSize;
  return m_pIO->GetLength() - m_nStartPos;
}
References CIccIO::GetLength(), m_nSize, m_nStartPos, and m_pIO.
Read16()
icInt32Number CIccIO::Read16 (void * pBuf16, icInt32Number nNum = 1) inherited
{
  nNum = Read8(pBuf16, nNum<<1)>>1;
  icSwab16Array(pBuf16, nNum);
  return nNum;
}
References icSwab16Array(), and CIccIO::Read8().
Referenced by icCLutFromXml(), CIccTagXmlCurve::ParseXml(), CIccSampledCurveSegmentXml::ParseXml(), CIccSinglSampledeCurveXml::ParseXml(), CIccTagXmlFloatNum< T, A, Tsig >::ParseXml(), CIccMpeUnknown::Read(), CIccMpeAcs::Read(), CIccFormulaCurveSegment::Read(), CIccSegmentedCurve::Read(), CIccSingleSampledCurve::Read(), CIccSampledCalculatorCurve::Read(), CIccMpeCurveSet::Read(), CIccMpeTintArray::Read(), CIccToneMapFunc::Read(), CIccMpeToneMap::Read(), CIccMpeMatrix::Read(), CIccMpeCLUT::Read(), CIccMpeExtCLUT::Read(), CIccMpeCAM::Read(), CIccMpeCalculator::Read(), CIccMpeSpectralMatrix::Read(), CIccMpeSpectralCLUT::Read(), CIccMpeSpectralObserver::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagChromaticity::Read(), CIccTagSparseMatrixArray::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagDateTime::Read(), CIccTagColorantTable::Read(), CIccResponseCurveStruct::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagDict::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccIO::ReadFloat16Float(), and CIccIO::ReadUInt16Float().
Read32()
icInt32Number CIccIO::Read32 (void * pBuf32, icInt32Number nNum = 1) inherited
{
  nNum = Read8(pBuf32, nNum<<2)>>2;
  icSwab32Array(pBuf32, nNum);
  return nNum;
}
References icSwab32Array(), and CIccIO::Read8().
Referenced by CIccTagStruct::LoadElem(), CIccMpeUnknown::Read(), CIccMpeAcs::Read(), CIccFormulaCurveSegment::Read(), CIccSampledCurveSegment::Read(), CIccSegmentedCurve::Read(), CIccSingleSampledCurve::Read(), CIccSampledCalculatorCurve::Read(), CIccMpeCurveSet::Read(), CIccMpeTintArray::Read(), CIccToneMapFunc::Read(), CIccMpeToneMap::Read(), CIccMpeMatrix::Read(), CIccMpeCLUT::Read(), CIccMpeExtCLUT::Read(), CIccMpeCAM::Read(), CIccCalculatorFunc::Read(), CIccMpeCalculator::Read(), CIccMpeSpectralMatrix::Read(), CIccMpeSpectralCLUT::Read(), CIccMpeSpectralObserver::Read(), CIccTagUnknown::Read(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccProfileDescText::Read(), CIccTagProfileSeqDesc::Read(), CIccResponseCurveStruct::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), and CIccIO::ReadFloat32Float().
Read64()
icInt32Number CIccIO::Read64 (void * pBuf64, icInt32Number nNum = 1) inherited
{
  nNum = Read8(pBuf64, nNum<<3)>>3;
  icSwab64Array(pBuf64, nNum);
  return nNum;
}
References icSwab64Array(), and CIccIO::Read8().
Referenced by CIccTagXmlFloatNum< T, A, Tsig >::ParseXml(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), and CIccTagProfileSeqDesc::Read().
Read8()
icInt32Number CIccEmbedIO::Read8 (void * pBuf, icInt32Number nNum = 1) virtual
Reimplemented from CIccIO.
{
  if (!m_pIO)
    return 0;
  if (m_nSize > 0) {
    icUInt32Number nPos = m_pIO->Tell();
    icUInt32Number nOffset = nPos - m_nStartPos;
    if (nOffset + nNum > (icUInt64Number)m_nSize)
      nNum = m_nSize - nOffset;
  }
  return m_pIO->Read8(pBuf, nNum);
}
References m_nSize, m_nStartPos, m_pIO, CIccIO::Read8(), and CIccIO::Tell().
ReadFloat16Float()
icInt32Number CIccIO::ReadFloat16Float (void * pBufFloat, icInt32Number nNum = 1) inherited
{
  icFloatNumber *ptr = (icFloatNumber*)pBufFloat;
  icFloat16Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    if (Read16(&tmp, 1)!=1)
      break;
    *ptr = icF16toF(tmp);
    ptr++;
  }
  return i;
}
References icF16toF(), and CIccIO::Read16().
Referenced by CIccTagXmlFloatNum< T, A, Tsig >::ParseXml(), CIccSingleSampledCurve::Read(), CIccMpeExtCLUT::Read(), CIccMpeSpectralCLUT::Read(), CIccTagSparseMatrixArray::Read(), and CIccTagFloatNum< T, Tsig >::Read().
ReadFloat32Float()
icInt32Number CIccIO::ReadFloat32Float (void * pBufFloat, icInt32Number nNum = 1) inherited
{
  if (sizeof(icFloat32Number)==sizeof(icFloatNumber))
    return Read32(pBufFloat, nNum);
  icFloatNumber *ptr = (icFloatNumber*)pBufFloat;
  icFloat32Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    if (Read32(&tmp, 1)!=1)
      break;
    *ptr = (icFloatNumber)tmp;
    ptr++;
  }
  return i;
}
References CIccIO::Read32().
Referenced by icCLutFromXml(), CIccTagXmlCurve::ParseXml(), CIccSampledCurveSegmentXml::ParseXml(), CIccSinglSampledeCurveXml::ParseXml(), CIccTagXmlFloatNum< T, A, Tsig >::ParseXml(), CIccFormulaCurveSegment::Read(), CIccSampledCurveSegment::Read(), CIccSegmentedCurve::Read(), CIccSingleSampledCurve::Read(), CIccSampledCalculatorCurve::Read(), CIccToneMapFunc::Read(), CIccMpeMatrix::Read(), CIccMpeCLUT::Read(), CIccMpeExtCLUT::Read(), CIccMpeCAM::Read(), CIccMpeSpectralMatrix::Read(), CIccMpeSpectralCLUT::Read(), CIccMpeSpectralObserver::Read(), CIccTagSparseMatrixArray::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), and CIccTagGamutBoundaryDesc::Read().
ReadLine()
icInt32Number CIccIO::ReadLine (void * pBuf8, icInt32Number nNum = 256) inherited
{
  icInt32Number n=0;
  icInt8Number c, *ptr=(icInt8Number*)pBuf8;
  while(n<nNum) {
    if (!Read8(&c)) {
      break;
    }
    if (c=='\n') {
      break;
    }
    else if (c!='\r') {
      *ptr++ = c;
      n++;
    }
  }
  *ptr = '\0';
  return n;
}
References CIccIO::Read8().
Referenced by icXmlParseTextString(), and CIccTagXmlTextDescription::ParseXml().
ReadUInt16Float()
icInt32Number CIccIO::ReadUInt16Float (void * pBufFloat, icInt32Number nNum = 1) inherited
{
  icFloatNumber *ptr = (icFloatNumber*)pBufFloat;
  icUInt16Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    if (Read16(&tmp, 1)!=1)
      break;
    *ptr = (icFloatNumber)((icFloatNumber)tmp / 65535.0);
    ptr++;
  }
  return i;
}
References CIccIO::Read16().
Referenced by CIccSingleSampledCurve::Read(), CIccMpeExtCLUT::Read(), CIccMpeSpectralCLUT::Read(), CIccTagNamedColor2::Read(), CIccTagSparseMatrixArray::Read(), CIccTagCurve::Read(), CIccTagLut16::Read(), and CIccCLUT::ReadData().
ReadUInt8Float()
icInt32Number CIccIO::ReadUInt8Float (void * pBufFloat, icInt32Number nNum = 1) inherited
{
  icFloatNumber *ptr = (icFloatNumber*)pBufFloat;
  icUInt8Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    if (Read8(&tmp, 1)!=1)
      break;
    *ptr = (icFloatNumber)((icFloatNumber)tmp / 255.0);
    ptr++;
  }
  return i;
}
References CIccIO::Read8().
Referenced by CIccSingleSampledCurve::Read(), CIccMpeExtCLUT::Read(), CIccMpeSpectralCLUT::Read(), CIccTagSparseMatrixArray::Read(), CIccTagLut8::Read(), and CIccCLUT::ReadData().
Seek()
icInt32Number CIccEmbedIO::Seek (icInt32Number nOffset, icSeekVal pos) virtual
Reimplemented from CIccIO.
{
  icInt32Number nPos;
  if (!m_pIO)
    return -1;
  if (pos == icSeekSet) {
    if (m_nSize > 0 && nOffset > m_nSize)
      nOffset = m_nSize;
    else if (nOffset < 0)
      nOffset = m_nStartPos;
   nPos = m_pIO->Seek(nOffset + m_nStartPos, icSeekSet);
  }
  else if (pos == icSeekEnd) {
    if (m_nSize > 0) {
      nOffset = m_nSize + nOffset;
    }
    else {
      nOffset = nOffset + m_pIO->GetLength() - m_nStartPos;
    }
    if (nOffset < 0)
      nOffset = 0;
    nOffset += m_nStartPos;
    nPos = m_pIO->Seek(nOffset, icSeekSet);
  }
  else {//pos == icSeekCur
    nOffset = m_pIO->Tell() + nOffset;
    if (m_nSize && nOffset - m_nStartPos > m_nSize)
      nOffset = m_nStartPos + m_nSize;
    else if (nOffset < m_nStartPos)
      nOffset = m_nStartPos;
    nPos = m_pIO->Seek(nOffset, icSeekSet);
  }
  if (nPos >= m_nStartPos)
    return nPos - m_nStartPos;
  return nPos;
}
References CIccIO::GetLength(), icSeekEnd, icSeekSet, m_nSize, m_nStartPos, m_pIO, CIccIO::Seek(), and CIccIO::Tell().
Sync32()
bool CIccIO::Sync32 (icUInt32Number nOffset = 0) inherited
Operation to make sure read position is evenly divisible by 4.
{
  nOffset &= 0x3;
  icUInt32Number nPos = ((Tell() - nOffset + 3)>>2)<<2;
  if (Seek(nPos + nOffset, icSeekSet)<0)
    return false;
  return true;
}
References icSeekSet, CIccIO::Seek(), and CIccIO::Tell().
Referenced by CIccProfileDescText::Read(), and CIccTagLutAtoB::Read().
Tell()
icInt32Number CIccEmbedIO::Tell () virtual
Reimplemented from CIccIO.
{
  if (!m_pIO)
    return -1;
  icUInt32Number nPos = m_pIO->Tell();
  if ((icInt32Number)nPos >= m_nStartPos)
    return nPos - m_nStartPos;
  return nPos;
}
References m_nStartPos, m_pIO, and CIccIO::Tell().
Write16()
icInt32Number CIccIO::Write16 (void * pBuf16, icInt32Number nNum = 1) inherited
{
#ifndef ICC_BYTE_ORDER_LITTLE_ENDIAN
  return Write8(pBuf16, nNum<<1)>>1;
#else
  icUInt16Number *ptr = (icUInt16Number*)pBuf16;
  icUInt16Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    tmp = *ptr;
    icSwab16(tmp);
    if (Write8(&tmp, 2)!=2)
      break;
    ptr++;
  }
  return i;
#endif
}
References CIccIO::Write8().
Referenced by CIccMpeAcs::Write(), CIccFormulaCurveSegment::Write(), CIccSegmentedCurve::Write(), CIccSingleSampledCurve::Write(), CIccSampledCalculatorCurve::Write(), CIccMpeCurveSet::Write(), CIccMpeTintArray::Write(), CIccToneMapFunc::Write(), CIccMpeToneMap::Write(), CIccMpeMatrix::Write(), CIccMpeCLUT::Write(), CIccMpeExtCLUT::Write(), CIccMpeCAM::Write(), CIccMpeCalculator::Write(), CIccMpeSpectralMatrix::Write(), CIccMpeSpectralCLUT::Write(), CIccMpeSpectralObserver::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagChromaticity::Write(), CIccTagSparseMatrixArray::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagDateTime::Write(), CIccTagColorantTable::Write(), CIccResponseCurveStruct::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagDict::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccMpeUnknown::Write(), CIccTagMultiProcessElement::Write(), CIccIO::WriteFloat16Float(), and CIccIO::WriteUInt16Float().
Write32()
icInt32Number CIccIO::Write32 (void * pBuf32, icInt32Number nNum = 1) inherited
{
#ifndef ICC_BYTE_ORDER_LITTLE_ENDIAN
  return Write8(pBuf32, nNum<<2)>>2;
#else
  icUInt32Number *ptr = (icUInt32Number*)pBuf32;
  icUInt32Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    tmp = *ptr;
    icSwab32(tmp);
    if (Write8(&tmp, 4)!=4)
      break;
    ptr++;
  }
  return i;
#endif
}
References CIccIO::Write8().
Referenced by CIccMpeAcs::Write(), CIccFormulaCurveSegment::Write(), CIccSampledCurveSegment::Write(), CIccSegmentedCurve::Write(), CIccSingleSampledCurve::Write(), CIccSampledCalculatorCurve::Write(), CIccMpeCurveSet::Write(), CIccMpeTintArray::Write(), CIccToneMapFunc::Write(), CIccMpeToneMap::Write(), CIccMpeMatrix::Write(), CIccMpeCLUT::Write(), CIccMpeExtCLUT::Write(), CIccMpeCAM::Write(), CIccCalculatorFunc::Write(), CIccMpeCalculator::Write(), CIccMpeSpectralMatrix::Write(), CIccMpeSpectralCLUT::Write(), CIccMpeSpectralObserver::Write(), CIccTagUnknown::Write(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccResponseCurveStruct::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccMpeUnknown::Write(), CIccTagMultiProcessElement::Write(), CIccTagProfileSequenceId::Write(), and CIccIO::WriteFloat32Float().
Write64()
icInt32Number CIccIO::Write64 (void * pBuf64, icInt32Number nNum = 1) inherited
{
#ifndef ICC_BYTE_ORDER_LITTLE_ENDIAN
  return Write8(pBuf64, nNum<<3)>>3;
#else
  icUInt64Number *ptr = (icUInt64Number*)pBuf64;
  icUInt64Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    tmp = *ptr;
    icSwab64(tmp);
    if (Write8(&tmp, 8)!=8)
      break;
    ptr++;
  }
  return i;
#endif
}
References CIccIO::Write8().
Referenced by CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), and CIccTagProfileSeqDesc::Write().
Write8()
icInt32Number CIccEmbedIO::Write8 (void * pBuf, icInt32Number nNum = 1) virtual
Reimplemented from CIccIO.
{
  if (!m_pIO)
    return 0;
  return m_pIO->Write8(pBuf, nNum);
}
References m_pIO, and CIccIO::Write8().
WriteFloat16Float()
icInt32Number CIccIO::WriteFloat16Float (void * pBuf16, icInt32Number nNum = 1) inherited
{
  icFloatNumber *ptr = (icFloatNumber*)pBufFloat;
  icUInt16Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    tmp = icFtoF16(*ptr);
    if (Write16(&tmp, 1)!=1)
      break;
    ptr++;
  }
  return i;
}
References icFtoF16(), and CIccIO::Write16().
Referenced by CIccSingleSampledCurve::Write(), CIccMpeExtCLUT::Write(), CIccMpeSpectralCLUT::Write(), CIccTagSparseMatrixArray::Write(), and CIccTagFloatNum< T, Tsig >::Write().
WriteFloat32Float()
icInt32Number CIccIO::WriteFloat32Float (void * pBufFloat, icInt32Number nNum = 1) inherited
{
  if (sizeof(icFloat32Number)==sizeof(icFloatNumber))
    return Write32(pBufFloat, nNum);
  icFloatNumber *ptr = (icFloatNumber*)pBufFloat;
  icFloat32Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    tmp = (icFloat32Number)*ptr;
    if (Write32(&tmp, 1)!=1)
      break;
    ptr++;
  }
  return i;
}
References CIccIO::Write32().
Referenced by CIccFormulaCurveSegment::Write(), CIccSampledCurveSegment::Write(), CIccSegmentedCurve::Write(), CIccSingleSampledCurve::Write(), CIccSampledCalculatorCurve::Write(), CIccToneMapFunc::Write(), CIccMpeMatrix::Write(), CIccMpeCLUT::Write(), CIccMpeExtCLUT::Write(), CIccMpeCAM::Write(), CIccMpeSpectralMatrix::Write(), CIccMpeSpectralCLUT::Write(), CIccMpeSpectralObserver::Write(), CIccTagSparseMatrixArray::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), and CIccTagGamutBoundaryDesc::Write().
WriteUInt16Float()
icInt32Number CIccIO::WriteUInt16Float (void * pBuf16, icInt32Number nNum = 1) inherited
{
  icFloatNumber *ptr = (icFloatNumber*)pBufFloat;
  icUInt16Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    tmp = (icUInt16Number)(__max(0.0, __min(1.0, *ptr)) * 65535.0 + 0.5);
    if (Write16(&tmp, 1)!=1)
      break;
    ptr++;
  }
  return i;
}
References CIccIO::Write16().
Referenced by CIccSingleSampledCurve::Write(), CIccMpeExtCLUT::Write(), CIccMpeSpectralCLUT::Write(), CIccTagNamedColor2::Write(), CIccTagSparseMatrixArray::Write(), CIccTagCurve::Write(), CIccTagLut16::Write(), and CIccCLUT::WriteData().
WriteUInt8Float()
icInt32Number CIccIO::WriteUInt8Float (void * pBuf16, icInt32Number nNum = 1) inherited
{
  icFloatNumber *ptr = (icFloatNumber*)pBufFloat;
  icUInt8Number tmp;
  icInt32Number i;
  for (i=0; i<nNum; i++) {
    tmp = (icUInt8Number)(__max(0.0, __min(1.0, *ptr)) * 255.0 + 0.5);
    if (Write8(&tmp, 1)!=1)
      break;
    ptr++;
  }
  return i;
}
References CIccIO::Write8().
Referenced by CIccSingleSampledCurve::Write(), CIccMpeExtCLUT::Write(), CIccMpeSpectralCLUT::Write(), CIccTagSparseMatrixArray::Write(), CIccTagLut8::Write(), and CIccCLUT::WriteData().
Field Documentation
m_bOwnIO
bool CIccEmbedIO::m_bOwnIO protected
Referenced by CIccEmbedIO(), Attach(), and Close().
m_nSize
icInt32Number CIccEmbedIO::m_nSize protected
Referenced by CIccEmbedIO(), Attach(), GetLength(), Read8(), and Seek().
m_nStartPos
icInt32Number CIccEmbedIO::m_nStartPos protected
Referenced by CIccEmbedIO(), Attach(), GetLength(), Read8(), Seek(), and Tell().
m_pIO
CIccIO* CIccEmbedIO::m_pIO protected
Referenced by CIccEmbedIO(), Attach(), Close(), GetLength(), Read8(), Seek(), Tell(), and Write8().
The documentation for this class was generated from the following files:
IccProfLib/IccIO.h
IccProfLib/IccIO.cpp