iccDEV: IccProfLib/IccTagComposite.h File Reference
IccTagComposite.h File Reference
#include "IccProfile.h"
#include "IccTag.h"
#include "IccDefs.h"
#include <memory>
#include <list>
Data Structures
class CIccTagArray
class CIccTagStruct
class IIccArray
class IIccStruct
Functions
ICCPROFLIB_API IIccArray * icGetTagArrayHandler (CIccTag *pTag)
ICCPROFLIB_API IIccArray * icGetTagArrayHandlerOfType (CIccTag *pTag, icStructSignature sig)
ICCPROFLIB_API IIccStruct * icGetTagStructHandler (CIccTag *pTag)
ICCPROFLIB_API IIccStruct * icGetTagStructHandlerOfType (CIccTag *pTag, icStructSignature sig)
Detailed Description
File: IccTagComposite.h
Contains: Header for implementation of CIccTagStruct and CIccTagArray and supporting classes
Version: V1
Copyright: (c) see ICC Software License
Definition in file IccTagComposite.h.
Function Documentation
icGetTagArrayHandler()
ICCPROFLIB_API IIccArray * icGetTagArrayHandler (CIccTag * pTag)
{
  if (!pTag)
    return NULL;
  if (pTag->GetType()!=icSigTagArrayType)
    return NULL;
  CIccTagArray *pArray = (CIccTagArray*)pTag;
  return pArray->GetArrayHandler();
}
References CIccTagArray::GetArrayHandler(), CIccTag::GetType(), and icSigTagArrayType.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
icGetTagArrayHandlerOfType()
ICCPROFLIB_API IIccArray * icGetTagArrayHandlerOfType (CIccTag * pTag, icStructSignature sig)
icGetTagStructHandler()
ICCPROFLIB_API IIccStruct * icGetTagStructHandler (CIccTag * pTag)
{
  if (!pTag)
    return NULL;
  if (pTag->GetType()!=icSigTagStructType)
    return NULL;
  CIccTagStruct *pStruct = (CIccTagStruct*)pTag;
  return pStruct->GetStructHandler();
}
References CIccTagStruct::GetStructHandler(), CIccTag::GetType(), and icSigTagStructType.
Referenced by icGetTagStructHandlerOfType().
icGetTagStructHandlerOfType()
ICCPROFLIB_API IIccStruct * icGetTagStructHandlerOfType (CIccTag * pTag, icStructSignature sig)
{
  if (pTag->GetTagStructType()==sig)
    return icGetTagStructHandler(pTag);
  return NULL;
}
References CIccTag::GetTagStructType(), and icGetTagStructHandler().
Referenced by CIccArrayNamedColor::Begin(), CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), and CIccArrayNamedColor::FindSpectralColor().