iccDEV: CIccTagXmlSegmentedCurve Class Reference
CIccTagXmlSegmentedCurve Class Reference
#include <IccTagXml.h>
Public Member Functions
virtual ~CIccTagXmlSegmentedCurve ()
virtual icFloatNumber Apply (icFloatNumber v) const
virtual void Begin ()
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
virtual void DumpLut (std::string &sDescription, const icChar *szName, icColorSpaceSignature csSig, int nIndex, int nVerboseness)
icFloatNumber Find (icFloatNumber v)
virtual const char * GetClassName () const
CIccSegmentedCurve * GetCurve ()
virtual const char * GetExtClassName () const
virtual const char * GetExtDerivedClassName () const
virtual IIccExtensionTag * GetExtension ()
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsIdentity ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
virtual bool ParseXml (xmlNode *pNode, icConvertType nType, std::string &parseStr)
virtual bool ParseXml (xmlNode *pNode, std::string &parseStr)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
void SetCurve (CIccSegmentedCurve *pCurve)
virtual bool ToXml (std::string &xml, icConvertType nType, std::string blanks="")
virtual bool ToXml (std::string &xml, std::string blanks="")
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
Protected Member Functions
icFloatNumber Find (icFloatNumber v, icFloatNumber p0, icFloatNumber v0, icFloatNumber p1, icFloatNumber v1)
Protected Attributes
CIccSegmentedCurve * m_pCurve
Detailed Description
Constructor & Destructor Documentation
~CIccTagXmlSegmentedCurve()
virtual CIccTagXmlSegmentedCurve::~CIccTagXmlSegmentedCurve () inline virtual
{}
Member Function Documentation
Apply()
icFloatNumber CIccTagSegmentedCurve::Apply (icFloatNumber v) const virtual inherited
Name: CIccTagSegmentedCurve::Apply
Purpose: convert input to output values using segmented curve
Reimplemented from CIccCurve.
{
  if (m_pCurve)
    return m_pCurve->Apply(v);
  return v;
}
References CIccSegmentedCurve::Apply(), and CIccTagSegmentedCurve::m_pCurve.
Begin()
void CIccTagSegmentedCurve::Begin () virtual inherited
Name: CIccTagSegmentedCurve::Begin
Purpose: Get ready to call apply
Reimplemented from CIccCurve.
{
  if (m_pCurve)
    m_pCurve->Begin(icElemInterpLinear, NULL);
}
References CIccSegmentedCurve::Begin(), icElemInterpLinear, and CIccTagSegmentedCurve::m_pCurve.
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagSegmentedCurve::Describe (std::string & sDescription, int nVerboseness) virtual inherited
Name: CIccTagSegmentedCurve::Describe
Purpose: gets information about the segmented curve
Reimplemented from CIccTag.
{
  if (m_pCurve) {
    m_pCurve->Describe(sDescription, nVerboseness);
  }
  else {
    sDescription += "TagSegmentedCurve is undefined\n";
  }
}
References CIccSegmentedCurve::Describe(), and CIccTagSegmentedCurve::m_pCurve.
Referenced by CIccTagSegmentedCurve::DumpLut().
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
DumpLut()
void CIccTagSegmentedCurve::DumpLut (std::string & sDescription, const icChar * szName, icColorSpaceSignature csSig, int nIndex, int nVerboseness) virtual inherited
Name: CIccTagSegmentedCurve::DumpLut
Purpose: gets information about segmented curve
Reimplemented from CIccCurve.
{
  icChar buf[128];
  sprintf(buf, "BEGIN_SEGMENTED_CURVE %s\n", szName);
  sDescription += buf;
  Describe(sDescription, nVerboseness);
}
References CIccTagSegmentedCurve::Describe().
Find() [1/2]
icFloatNumber CIccCurve::Find (icFloatNumber v) inline inherited
{ return Find(v, 0, Apply(0), 1.0, Apply(1.0)); }
References CIccCurve::Apply(), and CIccCurve::Find().
Find() [2/2]
icFloatNumber CIccCurve::Find (icFloatNumber v, icFloatNumber p0, icFloatNumber v0, icFloatNumber p1, icFloatNumber v1) protected inherited
Name: CIccCurve::Find
Purpose: Read in the tag contents into a data block
Args: v = index to be searched, v0 = index less than/equal to v, p0 = the value at index v0, v1 = index greater than/equal to v, p1 = value at index v1
Return: The value at the requested index
{
  if (v<=v0)
    return p0;
  if (v>=v1)
    return p1;
  if (p1-p0 <= 0.00001) {
    icFloatNumber d0 = (icFloatNumber)fabs(v-v0);
    icFloatNumber d1 = (icFloatNumber)fabs(v1-v);
    if (d0<d1)
      return p0;
    return p1;
  }
  icFloatNumber np = (icFloatNumber)((p0 + p1)/2.0);
  icFloatNumber nv = Apply(np);
  if (v<=nv) {
    return Find(v, p0, v0, np, nv);
  }
  return Find(v, np, nv, p1, v1);
}
References CIccCurve::Apply(), and CIccCurve::Find().
Referenced by CIccCurve::Find(), and CIccCurve::Find().
GetClassName()
virtual const char * CIccTagXmlSegmentedCurve::GetClassName () const inline virtual
Reimplemented from CIccTagSegmentedCurve.
{return "CIccTagXmlSegmentedCurve"; }
GetCurve()
CIccSegmentedCurve * CIccTagSegmentedCurve::GetCurve () inline inherited
{ return m_pCurve; }
References CIccTagSegmentedCurve::m_pCurve.
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams().
GetExtClassName()
virtual const char * CIccTagXml::GetExtClassName () const inline virtual inherited
Implements IIccExtensionTag.
{ return "CIccTagXml"; }
Referenced by icProfDescToXml(), and icXmlParseProfDesc().
GetExtDerivedClassName()
virtual const char * CIccCurveXml::GetExtDerivedClassName () const inline virtual inherited
Reimplemented from CIccTagXml.
{return "CIccCurveXml"; }
GetExtension()
virtual IIccExtensionTag * CIccTagXmlSegmentedCurve::GetExtension () inline virtual
Reimplemented from CIccTag.
{return this; }
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagSegmentedCurve::GetType () const inline virtual inherited
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigSegmentedCurveType; }
References icSigSegmentedCurveType.
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsIdentity()
bool CIccTagSegmentedCurve::IsIdentity () virtual inherited
Name: CIccTagSegmentedCurve::IsIdentity
Purpose: Constructor
Reimplemented from CIccCurve.
{
  if (!m_pCurve)
    return true;
  return false;
}
References CIccTagSegmentedCurve::m_pCurve.
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
virtual CIccTag * CIccTagSegmentedCurve::NewCopy () const inline virtual inherited
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccCurve.
{ return new CIccTagSegmentedCurve(*this);}
References CIccTagSegmentedCurve::CIccTagSegmentedCurve().
ParseXml() [1/2]
bool CIccTagXmlSegmentedCurve::ParseXml (xmlNode * pNode, icConvertType nType, std::string & parseStr) virtual
Implements CIccCurveXml.
{
  return ParseXml(pNode, parseStr);
}
References ParseXml().
ParseXml() [2/2]
bool CIccTagXmlSegmentedCurve::ParseXml (xmlNode * pNode, std::string & parseStr) virtual
Implements CIccTagXml.
{
  xmlNode *pCurveNode = icXmlFindNode(pNode, "SegmentedCurve");
  if (pCurveNode) {
    CIccSegmentedCurveXml *pCurve = new CIccSegmentedCurveXml();
    if (pCurve) {
      if (pCurve->ParseXml(pCurveNode, parseStr)) {
        SetCurve(pCurve);
        return true;
      }
      else {
        delete pCurve;
        return false;
      }
    }
    parseStr += "Unable to allocate Segmented Curve\n";
    return false;
  }
  parseStr += "Unable to find Segmented Curve\n";
  return false;
}
References icXmlFindNode(), CIccSegmentedCurveXml::ParseXml(), and CIccTagSegmentedCurve::SetCurve().
Referenced by ParseXml().
Read() [1/2]
bool CIccTagSegmentedCurve::Read (icUInt32Number size, CIccIO * pIO) virtual inherited
Name: CIccTagSegmentedCurve::Read
Purpose: read segmented curve from file
Reimplemented from CIccTag.
{
   CIccSegmentedCurve *pCurve = new CIccSegmentedCurve();
   if (pCurve->Read(size, pIO)) {
     SetCurve(pCurve);
     return true;
   }
   return false;
}
References CIccSegmentedCurve::CIccSegmentedCurve(), CIccSegmentedCurve::Read(), and CIccTagSegmentedCurve::SetCurve().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
SetCurve()
void CIccTagSegmentedCurve::SetCurve (CIccSegmentedCurve * pCurve) inherited
Name: CIccTagSegmentedCurve::SetCurve
Purpose: set the current curve object
{
  if (m_pCurve)
    delete m_pCurve;
  m_pCurve = pCurve;
}
References CIccTagSegmentedCurve::m_pCurve.
Referenced by ParseXml(), and CIccTagSegmentedCurve::Read().
ToXml() [1/2]
bool CIccTagXmlSegmentedCurve::ToXml (std::string & xml, icConvertType nType, std::string blanks = "") virtual
Implements CIccCurveXml.
{
  return ToXml(xml, blanks);
}
References ToXml().
ToXml() [2/2]
bool CIccTagXmlSegmentedCurve::ToXml (std::string & xml, std::string blanks = "") virtual
Implements CIccTagXml.
{
  if (m_pCurve)
    return ((CIccSegmentedCurveXml*)m_pCurve)->ToXml(xml, blanks);
  return true;
}
References CIccTagSegmentedCurve::m_pCurve, and CIccSegmentedCurveXml::ToXml().
Referenced by ToXml().
Validate()
icValidateStatus CIccTagSegmentedCurve::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual inherited
Name: CIccTagSegmentedCurve::Validate
Purpose: Constructor
Reimplemented from CIccTag.
{
  if (!m_pCurve) {
    sReport += "Invalid Segmented Curve Data!\n";
    return icValidateCriticalError;
  }
  return m_pCurve->Validate(sigPath, sReport, NULL);
}
References icValidateCriticalError, CIccTagSegmentedCurve::m_pCurve, and CIccSegmentedCurve::Validate().
Write()
bool CIccTagSegmentedCurve::Write (CIccIO * pIO) virtual inherited
Name: CIccTagSegmentedCurve::Write
Purpose: write segmented curve to file
Reimplemented from CIccTag.
{
  if (!m_pCurve)
    return false;
  return m_pCurve->Write(pIO);
}
References CIccTagSegmentedCurve::m_pCurve, and CIccSegmentedCurve::Write().
Field Documentation
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_pCurve
CIccSegmentedCurve* CIccTagSegmentedCurve::m_pCurve protected inherited
Referenced by CIccTagSegmentedCurve::CIccTagSegmentedCurve(), CIccTagSegmentedCurve::CIccTagSegmentedCurve(), CIccTagSegmentedCurve::~CIccTagSegmentedCurve(), CIccTagSegmentedCurve::Apply(), CIccTagSegmentedCurve::Begin(), CIccTagSegmentedCurve::Describe(), CIccTagSegmentedCurve::GetCurve(), CIccTagSegmentedCurve::IsIdentity(), CIccTagSegmentedCurve::operator=(), CIccTagSegmentedCurve::SetCurve(), ToXml(), CIccTagSegmentedCurve::Validate(), and CIccTagSegmentedCurve::Write().
The documentation for this class was generated from the following files:
IccXML/IccLibXML/IccTagXml.h
IccXML/IccLibXML/IccTagXml.cpp