iccDEV: IccProfLib/IccWrapper.cpp File Reference
IccWrapper.cpp File Reference
#include "IccWrapper.h"
#include "IccApplyBPC.h"
Data Structures
class CIccCmmEnvVarsWrapper
class CIccCmmEnvVarWrapperHint
Functions
icStatusCMM IccApplyApplyFloat (CIccApplyHandle *pApply, icFloatNumber *pTo, icFloatNumber *pFrom)
icStatusCMM IccApplyApplyFloatMulti (CIccApplyHandle *pApply, icFloatNumber *pTo, icFloatNumber *pFrom, icUInt32Number nPixels)
void IccApplyFree (CIccApplyHandle *pApply)
icStatusCMM IccCmmApplyFloat (CIccCmmHandle *pCmm, icFloatNumber *pTo, icFloatNumber *pFrom)
icStatusCMM IccCmmApplyFloatMulti (CIccCmmHandle *pCmm, icFloatNumber *pTo, icFloatNumber *pFrom, icUInt32Number nPixels)
icStatusCMM ICCPROFLIB_API IccCmmAttachProfileFile (CIccCmmHandle *pCmm, const char *szFname, icRenderingIntent nIntent, icXformInterp nInterp, CIccProfileHandle *pPcc, icXformLutType nLutType, unsigned char bUseDtoBTags, unsigned char bUseBPC, SIccCmmEnvVars *pVars)
icStatusCMM IccCmmAttachProfileHandle (CIccCmmHandle *pCmm, CIccProfileHandle *pProfile, icRenderingIntent nIntent, icXformInterp nInterp, CIccProfileHandle *pPcc, icXformLutType nLutType, unsigned char bUseDtoBTags, unsigned char bUseBPC, SIccCmmEnvVars *pVars)
icStatusCMM IccCmmBegin (CIccCmmHandle *pCmm)
CIccCmmHandle * IccCmmCreate (icColorSpaceSignature srcSpace, icColorSpaceSignature dstSpace, unsigned char bFirstIsInput)
void IccCmmFree (CIccCmmHandle *pCmm)
CIccApplyHandle * IccCmmGetApply (CIccCmmHandle *pCmm)
icStatusCMM IccCmmGetInfo (CIccCmmHandle *pCmm, SIccCmmStruct *pCmmInfo)
void IccProfileFree (CIccProfileHandle *pProfile)
icBoolean IccProfileGetHeader (CIccProfileHandle *pProfile, icHeader *pHeader)
CIccProfileHandle * IccProfileOpenHandle (const char *szFname)
CIccProfileHandle * IccProfileReadHandle (const char *szFname)
Detailed Description
File: IccWrapper.h
Contains: Header file for C Wrapper interface functions for CIccProfile and CIccCmm classes.
Version: V1
Copyright: (c) see ICC Software License
Definition in file IccWrapper.cpp.
Function Documentation
IccApplyApplyFloat()
icStatusCMM IccApplyApplyFloat (CIccApplyHandle * pApply, icFloatNumber * pTo, icFloatNumber * pFrom)
{
  if (!pApply || !pTo || !pFrom)
    return icCmmStatBad;
  CIccApplyCmm *pApplyPtr = (CIccApplyCmm*)pApply;
  return pApplyPtr->Apply(pTo, pFrom);
}
References icCmmStatBad.
IccApplyApplyFloatMulti()
icStatusCMM IccApplyApplyFloatMulti (CIccApplyHandle * pApply, icFloatNumber * pTo, icFloatNumber * pFrom, icUInt32Number nPixels)
{
  if (!pApply || !pTo || !pFrom)
    return icCmmStatBad;
  CIccApplyCmm *pApplyPtr = (CIccApplyCmm*)pApply;
  return pApplyPtr->Apply(pTo, pFrom, nPixels);
}
References icCmmStatBad.
IccApplyFree()
void IccApplyFree (CIccApplyHandle * pApply)
{
  if (pApply) {
    CIccApplyCmm *pApplyPtr = (CIccApplyCmm*)pApply;
    delete pApplyPtr;
  }
}
IccCmmApplyFloat()
icStatusCMM IccCmmApplyFloat (CIccCmmHandle * pCmm, icFloatNumber * pTo, icFloatNumber * pFrom)
{
  if (!pCmm || !pTo || !pFrom)
    return icCmmStatBad;
  CIccCmm *pCmmPtr = (CIccCmm*)pCmm;
  return pCmmPtr->Apply(pTo, pFrom);
}
References icCmmStatBad.
IccCmmApplyFloatMulti()
icStatusCMM IccCmmApplyFloatMulti (CIccCmmHandle * pCmm, icFloatNumber * pTo, icFloatNumber * pFrom, icUInt32Number nPixels)
{
  if (!pCmm || !pTo || !pFrom)
    return icCmmStatBad;
  CIccCmm *pCmmPtr = (CIccCmm*)pCmm;
  return pCmmPtr->Apply(pTo, pFrom, nPixels);
}
References icCmmStatBad.
IccCmmAttachProfileFile()
icStatusCMM ICCPROFLIB_API IccCmmAttachProfileFile (CIccCmmHandle * pCmm, const char * szFname, icRenderingIntent nIntent, icXformInterp nInterp, CIccProfileHandle * pPcc, icXformLutType nLutType, unsigned char bUseDtoBTags, unsigned char bUseBPC, SIccCmmEnvVars * pVars)
{
  if (!pCmm)
    return icCmmStatBad;
  CIccCmm *pCmmPtr = (CIccCmm*)pCmm;
  CIccCreateXformHintManager hint;
  bool bUseHint = false;
  if (bUseBPC) {
    hint.AddHint(new CIccApplyBPCHint());
    bUseHint = true;
  }
  if (pVars) {
    hint.AddHint(new CIccCmmEnvVarWrapperHint(pVars));
    bUseHint = true;
  }
  return pCmmPtr->AddXform(szFname, nIntent, nInterp, (CIccProfile*)pPcc, nLutType, bUseDtoBTags != 0, bUseHint ? &hint : NULL);
}
References CIccCmmEnvVarWrapperHint::CIccCmmEnvVarWrapperHint(), CIccProfile, and icCmmStatBad.
IccCmmAttachProfileHandle()
icStatusCMM IccCmmAttachProfileHandle (CIccCmmHandle * pCmm, CIccProfileHandle * pProfile, icRenderingIntent nIntent, icXformInterp nInterp, CIccProfileHandle * pPcc, icXformLutType nLutType, unsigned char bUseDtoBTags, unsigned char bUseBPC, SIccCmmEnvVars * pVars)
{
  if (!pCmm)
    return icCmmStatBad;
  CIccCmm *pCmmPtr = (CIccCmm*)pCmm;
  CIccProfile *pProfilePtr = (CIccProfile*)pProfile;
  CIccCreateXformHintManager hint;
  bool bUseHint = false;
  if (bUseBPC) {
    hint.AddHint(new CIccApplyBPCHint());
    bUseHint = true;
  }
  if (pVars) {
    hint.AddHint(new CIccCmmEnvVarWrapperHint(pVars));
    bUseHint = true;
  }
  return pCmmPtr->AddXform(pProfilePtr, nIntent, nInterp, (CIccProfile*)pPcc, nLutType, bUseDtoBTags != 0, bUseHint ? &hint : NULL);
}
References CIccCmmEnvVarWrapperHint::CIccCmmEnvVarWrapperHint(), CIccProfile, and icCmmStatBad.
IccCmmBegin()
icStatusCMM IccCmmBegin (CIccCmmHandle * pCmm)
{
  if (!pCmm)
    return icCmmStatBad;
  CIccCmm *pCmmPtr = (CIccCmm*)pCmm;
  return pCmmPtr->Begin();
}
References icCmmStatBad.
IccCmmCreate()
CIccCmmHandle * IccCmmCreate (icColorSpaceSignature srcSpace, icColorSpaceSignature dstSpace, unsigned char bFirstIsInput)
{
  return (CIccCmmHandle*)new CIccCmm(srcSpace, dstSpace, bFirstIsInput != 0);
}
IccCmmFree()
void IccCmmFree (CIccCmmHandle * pCmm)
{
  if (pCmm) {
    CIccCmm *pCmmPtr = (CIccCmm*)pCmm;
    delete pCmmPtr;
  }
}
IccCmmGetApply()
CIccApplyHandle * IccCmmGetApply (CIccCmmHandle * pCmm)
{
  if (!pCmm)
    return NULL;
  CIccCmm *pCmmPtr = (CIccCmm*)pCmm;
  return (CIccApplyHandle*)pCmmPtr->GetApply();
}
IccCmmGetInfo()
icStatusCMM IccCmmGetInfo (CIccCmmHandle * pCmm, SIccCmmStruct * pCmmInfo)
{
  if (!pCmm || !pCmmInfo)
    return icCmmStatBad;
  CIccCmm *pCmmPtr = (CIccCmm*)pCmm;
  pCmmInfo->srcSpace = pCmmPtr->GetSourceSpace();
  pCmmInfo->srcSamples = pCmmPtr->GetSourceSamples();
  pCmmInfo->dstSpace = pCmmPtr->GetDestSpace();
  pCmmInfo->dstSamples = pCmmPtr->GetDestSamples();
  return icCmmStatOk;
}
References SIccCmmStruct::dstSamples, SIccCmmStruct::dstSpace, icCmmStatBad, icCmmStatOk, SIccCmmStruct::srcSamples, and SIccCmmStruct::srcSpace.
IccProfileFree()
void IccProfileFree (CIccProfileHandle * pProfile)
{
  if (pProfile) {
    CIccProfileHandle *pProfilePtr = (CIccProfileHandle*)pProfile;
    delete pProfilePtr;
  }
}
IccProfileGetHeader()
icBoolean IccProfileGetHeader (CIccProfileHandle * pProfile, icHeader * pHeader)
{
  if (!pProfile || !pHeader)
    return 0;
  CIccProfile *pProfilePtr = (CIccProfile*)pProfile;
  *pHeader = pProfilePtr->m_Header;
  return 1;
}
References CIccProfile.
IccProfileOpenHandle()
CIccProfileHandle * IccProfileOpenHandle (const char * szFname)
{
  return (CIccProfileHandle*)OpenIccProfile(szFname);
}
References OpenIccProfile().
IccProfileReadHandle()
CIccProfileHandle * IccProfileReadHandle (const char * szFname)
{
  return (CIccProfileHandle*)ReadIccProfile(szFname);
}
References ReadIccProfile().