iccDEV: CIccDictEntry Class Reference
CIccDictEntry Class Reference
#include <IccTagDict.h>
Public Member Functions
CIccDictEntry ()
CIccDictEntry (const CIccDictEntry &IDE)
virtual ~CIccDictEntry ()
void Describe (std::string &sDescription, int nVerboseness)
std::wstring & GetName ()
CIccTagMultiLocalizedUnicode * GetNameLocalized ()
std::wstring GetValue ()
CIccTagMultiLocalizedUnicode * GetValueLocalized ()
bool IsValueSet ()
CIccDictEntry & operator= (const CIccDictEntry &IDE)
icUInt32Number PosRecSize ()
bool SetNameLocalized (CIccTagMultiLocalizedUnicode *pNameLocalized)
bool SetValue (std::wstring sValue)
bool SetValueLocalized (CIccTagMultiLocalizedUnicode *pValueLocalized)
void UnsetValue ()
std::wstring::const_iterator ValueBegin ()
std::wstring::const_iterator ValueEnd ()
Protected Attributes
bool m_bValueSet
CIccTagMultiLocalizedUnicode * m_pNameLocalized
CIccTagMultiLocalizedUnicode * m_pValueLocalized
std::wstring * m_sName
std::wstring * m_sValue
Detailed Description
Data Class: CIccDictEntry
Purpose: Implementation of a dictionary entry with optional localization of name and value
Constructor & Destructor Documentation
CIccDictEntry() [1/2]
CIccDictEntry::CIccDictEntry ()
Name: CIccDictEntry::CIccDictEntry
Purpose:
Args:
Return:
{
  m_sName = new std::wstring();
  m_sValue = new std::wstring();
  m_pNameLocalized = NULL;
  m_pValueLocalized = NULL;
  m_bValueSet = false;
}
References m_bValueSet, m_pNameLocalized, m_pValueLocalized, m_sName, and m_sValue.
Referenced by CIccTagXmlDict::ParseXml(), and CIccTagDict::Read().
CIccDictEntry() [2/2]
CIccDictEntry::CIccDictEntry (const CIccDictEntry & IDE)
Name: CIccDictEntry::CIccDictEntry
Purpose:
Args:
Return:
{
  m_sName = new std::wstring();
  m_sValue = new std::wstring();
  *m_sName = *IDE.m_sName;
  m_bValueSet = IDE.m_bValueSet;
  *m_sValue = *IDE.m_sValue;
  if (IDE.m_pNameLocalized) {
    m_pNameLocalized = (CIccTagMultiLocalizedUnicode*)IDE.m_pNameLocalized->NewCopy();
  }
  else
    m_pNameLocalized = NULL;
  if (IDE.m_pValueLocalized) {
    m_pValueLocalized = (CIccTagMultiLocalizedUnicode*)IDE.m_pValueLocalized->NewCopy();
  }
  else
    m_pValueLocalized = NULL;
}
References m_bValueSet, m_pNameLocalized, m_pValueLocalized, m_sName, m_sValue, and CIccTagMultiLocalizedUnicode::NewCopy().
Referenced by CIccTagDict::CIccTagDict(), and CIccTagDict::operator=().
~CIccDictEntry()
CIccDictEntry::~CIccDictEntry () virtual
Name: CIccDictEntry::~CIccDictEntry
Purpose:
Args:
Return:
{
  delete m_sName;
  delete m_sValue;
  delete m_pNameLocalized;
  delete m_pValueLocalized;
}
References m_pNameLocalized, m_pValueLocalized, m_sName, and m_sValue.
Member Function Documentation
Describe()
void CIccDictEntry::Describe (std::string & sDescription, int nVerboseness)
Name: CIccDictEntry::Describe
Purpose:
Args:
Return:
{
  std::wstring ws;
  //setup converter
  std::wstring_convert<convert_type, wchar_t> converter;
  sDescription += "BEGIN DICT_ENTRY\nName=";
  ws.assign(m_sName->begin(), m_sName->end());
  sDescription += converter.to_bytes(ws);
  sDescription += "\nValue=";
  ws.assign(m_sValue->begin(), m_sValue->end());
  sDescription += converter.to_bytes(ws);
  sDescription += "\n";
  if (m_pNameLocalized) {
    sDescription += "BEGIN NAME_LOCALIZATION\n";
    m_pNameLocalized->Describe(sDescription, nVerboseness);
    sDescription += "END NAME_LOCALIZATION\n";
  }
  if (m_pValueLocalized) {
    sDescription += "BEGIN VALUE_LOCALIZATION\n";
    m_pValueLocalized->Describe(sDescription, nVerboseness);
    sDescription += "END VALUE_LOCALIZATION\n";
  }
  sDescription += "END DICT_ENTRY\n";
}
References CIccTagMultiLocalizedUnicode::Describe(), m_pNameLocalized, m_pValueLocalized, m_sName, and m_sValue.
Referenced by CIccTagDict::Describe().
GetName()
std::wstring & CIccDictEntry::GetName () inline
{ return *m_sName; }
References m_sName.
Referenced by CIccTagDict::AreNamesNonzero(), CIccTagDict::AreNamesUnique(), CIccTagDict::Get(), CIccTagXmlDict::ParseXml(), CIccTagDict::Read(), CIccTagDict::Remove(), CIccTagDict::Set(), CIccTagDict::SetNameLocalized(), CIccTagDict::SetValueLocalized(), CIccTagXmlDict::ToXml(), and CIccTagDict::Write().
GetNameLocalized()
CIccTagMultiLocalizedUnicode * CIccDictEntry::GetNameLocalized () inline
{ return m_pNameLocalized; }
References m_pNameLocalized.
Referenced by CIccTagDict::GetNameLocalized(), CIccTagXmlDict::ParseXml(), CIccTagXmlDict::ToXml(), and CIccTagDict::Write().
GetValue()
std::wstring CIccDictEntry::GetValue () inline
{ return *m_sValue; }
References m_sValue.
Referenced by CIccTagDict::GetValue(), CIccTagDict::Set(), and CIccTagXmlDict::ToXml().
GetValueLocalized()
CIccTagMultiLocalizedUnicode * CIccDictEntry::GetValueLocalized () inline
{ return m_pValueLocalized; }
References m_pValueLocalized.
Referenced by CIccTagDict::GetValueLocalized(), CIccTagXmlDict::ParseXml(), CIccTagXmlDict::ToXml(), and CIccTagDict::Write().
IsValueSet()
bool CIccDictEntry::IsValueSet () inline
{ return m_bValueSet; }
References m_bValueSet.
Referenced by CIccTagDict::GetValue(), CIccTagDict::Set(), CIccTagXmlDict::ToXml(), and CIccTagDict::Write().
operator=()
CIccDictEntry & CIccDictEntry::operator= (const CIccDictEntry & IDE)
Name: CIccDictEntry::operator=
Purpose:
Args:
Return:
{
  if (&IDE == this)
    return *this;
  if (m_pNameLocalized)
    delete m_pNameLocalized;
  if (m_pValueLocalized)
    delete m_pValueLocalized;
  *m_sName = *IDE.m_sName;
  m_bValueSet = IDE.m_bValueSet;
  *m_sValue = *IDE.m_sValue;
  if (IDE.m_pNameLocalized) {
    m_pNameLocalized = (CIccTagMultiLocalizedUnicode*)IDE.m_pNameLocalized->NewCopy();
  }
  else
    m_pNameLocalized = NULL;
  if (IDE.m_pValueLocalized) {
    m_pValueLocalized = (CIccTagMultiLocalizedUnicode*)IDE.m_pValueLocalized->NewCopy();
  }
  else
    m_pValueLocalized = NULL;
  return *this;
}
References m_bValueSet, m_pNameLocalized, m_pValueLocalized, m_sName, m_sValue, and CIccTagMultiLocalizedUnicode::NewCopy().
PosRecSize()
icUInt32Number CIccDictEntry::PosRecSize ()
Name: CIccDictEntry::PosRecSize
Purpose:
Args:
Return:
{
  if (m_pValueLocalized)
    return 32;
  if (m_pNameLocalized)
    return 24;
  return 16;
}
References m_pNameLocalized, and m_pValueLocalized.
Referenced by CIccTagDict::MaxPosRecSize().
SetNameLocalized()
bool CIccDictEntry::SetNameLocalized (CIccTagMultiLocalizedUnicode * pNameLocalized)
Name: CIccDictEntry::SetNameLocalized
Purpose:
Args:
Return:
{
  bool rv;
  if (m_pNameLocalized) {
    delete m_pNameLocalized;
    rv = true;
  }
  else
    rv = false;
  m_pNameLocalized = pNameLocalized;
  return rv;
}
References m_pNameLocalized.
Referenced by CIccTagXmlDict::ParseXml(), CIccTagDict::Read(), and CIccTagDict::SetNameLocalized().
SetValue()
bool CIccDictEntry::SetValue (std::wstring sValue)
{
  bool rv = m_bValueSet && !m_sValue->empty();
  *m_sValue = sValue;
  m_bValueSet = true;
  return rv;
}
References m_bValueSet, and m_sValue.
Referenced by CIccTagXmlDict::ParseXml(), CIccTagDict::Read(), and CIccTagDict::Set().
SetValueLocalized()
bool CIccDictEntry::SetValueLocalized (CIccTagMultiLocalizedUnicode * pValueLocalized)
Name: CIccDictEntry::SetValueLocalized
Purpose:
Args:
Return:
{
  bool rv;
  if (m_pValueLocalized) {
    delete m_pValueLocalized;
    rv = true;
  }
  else
    rv = false;
  m_pValueLocalized = pValueLocalized;
  return rv;
}
References m_pValueLocalized.
Referenced by CIccTagXmlDict::ParseXml(), CIccTagDict::Read(), and CIccTagDict::SetValueLocalized().
UnsetValue()
void CIccDictEntry::UnsetValue () inline
{ m_sValue->clear(); m_bValueSet = false; }
References m_bValueSet, and m_sValue.
Referenced by CIccTagDict::Set().
ValueBegin()
std::wstring::const_iterator CIccDictEntry::ValueBegin () inline
{return m_sValue->begin();}
References m_sValue.
Referenced by CIccTagDict::Write().
ValueEnd()
std::wstring::const_iterator CIccDictEntry::ValueEnd () inline
{return m_sValue->end();}
References m_sValue.
Referenced by CIccTagDict::Write().
Field Documentation
m_bValueSet
bool CIccDictEntry::m_bValueSet protected
Referenced by CIccDictEntry(), CIccDictEntry(), IsValueSet(), operator=(), SetValue(), and UnsetValue().
m_pNameLocalized
CIccTagMultiLocalizedUnicode* CIccDictEntry::m_pNameLocalized protected
Referenced by CIccDictEntry(), CIccDictEntry(), ~CIccDictEntry(), Describe(), GetNameLocalized(), operator=(), PosRecSize(), and SetNameLocalized().
m_pValueLocalized
CIccTagMultiLocalizedUnicode* CIccDictEntry::m_pValueLocalized protected
Referenced by CIccDictEntry(), CIccDictEntry(), ~CIccDictEntry(), Describe(), GetValueLocalized(), operator=(), PosRecSize(), and SetValueLocalized().
m_sName
std::wstring* CIccDictEntry::m_sName protected
Referenced by CIccDictEntry(), CIccDictEntry(), ~CIccDictEntry(), Describe(), GetName(), and operator=().
m_sValue
std::wstring* CIccDictEntry::m_sValue protected
Referenced by CIccDictEntry(), CIccDictEntry(), ~CIccDictEntry(), Describe(), GetValue(), operator=(), SetValue(), UnsetValue(), ValueBegin(), and ValueEnd().
The documentation for this class was generated from the following files:
IccProfLib/IccTagDict.h
IccProfLib/IccTagDict.cpp