iccDEV: CIccStructCreator Class Reference
CIccStructCreator Class Reference
#include <IccStructFactory.h>
Public Member Functions
~CIccStructCreator ()
Static Public Member Functions
static IIccStruct * CreateStruct (icStructSignature structTypeSig, CIccTagStruct *pTagStruct)
static icStructSignature GetStructSig (const icChar *structName)
static bool GetStructSigName (std::string &structName, icStructSignature structTypeSig, bool bFillUnknown=true)
static IIccStructFactory * PopFactory ()
static void PushFactory (IIccStructFactory *pFactory)
Private Member Functions
CIccStructCreator ()
IIccStruct * DoCreateStruct (icStructSignature structTypeSig, CIccTagStruct *pTagStruct=NULL)
icStructSignature DoGetStructSig (const char *structName)
bool DoGetStructSigName (std::string &structName, icStructSignature structTypeSig, bool bFillUnknown=true)
IIccStructFactory * DoPopFactory (bool bAll=false)
void DoPushFactory (IIccStructFactory *pFactory)
Static Private Member Functions
static CIccStructCreator * GetInstance ()
Private Attributes
CIccStructFactoryList factoryStack
Static Private Attributes
static CIccStructCreatorPtr theStructCreator
Detailed Description
Class: CIccStructCreator
Purpose: CIccStructCreator uses a singleton pattern to provide dynamically upgradeable IIccStructObject derived object creation based on element signature.
Constructor & Destructor Documentation
~CIccStructCreator()
CIccStructCreator::~CIccStructCreator ()
{
  IIccStructFactory *pFactory = DoPopFactory(true);
  while (pFactory) {
    delete pFactory;
    pFactory = DoPopFactory(true);
  }
}
References DoPopFactory().
CIccStructCreator()
CIccStructCreator::CIccStructCreator () inline private
Only GetInstance() can create the singleton
{ }
Member Function Documentation
CreateStruct()
static IIccStruct * CIccStructCreator::CreateStruct (icStructSignature structTypeSig, CIccTagStruct * pTagStruct) inline static
Function: CreateStruct(structTypeSig) Create a element of type structTypeSig.
Parameter(s): structTypeSig = signature of the ICC element type for the element to be created
Returns a new CIccProcessStruct object of the given signature type. Each factory in the factoryStack is used until a factory supports the signature type.
      { return CIccStructCreator::GetInstance()->DoCreateStruct(structTypeSig, pTagStruct); }
References DoCreateStruct(), and GetInstance().
Referenced by CIccTagStruct::Describe(), CIccTagStruct::GetStructHandler(), and CIccTagStruct::SetTagStructType().
DoCreateStruct()
IIccStruct * CIccStructCreator::DoCreateStruct (icStructSignature structTypeSig, CIccTagStruct * pTagStruct = NULL) private
{
  CIccStructFactoryList::iterator i;
  IIccStruct *rv = NULL;
  for (i=factoryStack.begin(); i!=factoryStack.end(); i++) {
    rv = (*i)->CreateStruct(structTypeSig, pTagStruct);
    if (rv)
      break;
  }
  return rv;
}
References IIccStructFactory::CreateStruct(), and factoryStack.
Referenced by CreateStruct().
DoGetStructSig()
icStructSignature CIccStructCreator::DoGetStructSig (const char * structName) private
{
  CIccStructFactoryList::iterator i;
  for (i = factoryStack.begin(); i != factoryStack.end(); i++) {
    icStructSignature rv = (*i)->GetStructSig(structName);
    if (rv)
      return rv;
  }
  return (icStructSignature)0;
}
References factoryStack, and IIccStructFactory::GetStructSig().
Referenced by GetStructSig().
DoGetStructSigName()
bool CIccStructCreator::DoGetStructSigName (std::string & structName, icStructSignature structTypeSig, bool bFillUnknown = true) private
{
  CIccStructFactoryList::iterator i;
  for (i=factoryStack.begin(); i!=factoryStack.end(); i++) {
    if ((*i)->GetStructSigName(structName, structTypeSig, bFillUnknown))
      return true;
  }
  return false;
}
References factoryStack, and IIccStructFactory::GetStructSigName().
Referenced by GetStructSigName().
DoPopFactory()
IIccStructFactory * CIccStructCreator::DoPopFactory (bool bAll = false) private
{
  if (factoryStack.size()>0) {
    CIccStructFactoryList::iterator i=factoryStack.begin();
    IIccStructFactory* rv = (*i);
    factoryStack.pop_front();
    return rv;
  }
  return NULL;
}
References factoryStack.
Referenced by ~CIccStructCreator(), and PopFactory().
DoPushFactory()
void CIccStructCreator::DoPushFactory (IIccStructFactory * pFactory) private
{
  factoryStack.push_front(pFactory);
}
References factoryStack.
Referenced by GetInstance(), and PushFactory().
GetInstance()
CIccStructCreator * CIccStructCreator::GetInstance () static private
Function: GetInstance() Private static function to access singleton CiccStructCreator Object.
Parameter(s): None
Returns the singleton CIccStructCreator object. It will allocate a new one and push a single CIccSpecStruct Factory object onto the factory stack if the singleton has not been intialized.
{
  if (!theStructCreator.get()) {
    theStructCreator = CIccStructCreatorPtr(new CIccStructCreator);
    theStructCreator->DoPushFactory(new CIccBasicStructFactory);
  }
  return theStructCreator.get();
}
References DoPushFactory(), and theStructCreator.
Referenced by CreateStruct(), GetStructSig(), GetStructSigName(), PopFactory(), and PushFactory().
GetStructSig()
static icStructSignature CIccStructCreator::GetStructSig (const icChar * structName) inline static
Function: GetStructSig(structName) Get signature of structure from display name.
Parameter(s): structName = struct display name
Returns signature of structure if it is recognized by any factory, 0 if the all the factories don't create a structure with such a display name.
  {
    return CIccStructCreator::GetInstance()->DoGetStructSig(structName);
  }
References DoGetStructSig(), and GetInstance().
Referenced by CIccTagXmlStruct::ParseXml().
GetStructSigName()
static bool CIccStructCreator::GetStructSigName (std::string & structName, icStructSignature structTypeSig, bool bFillUnknown = true) inline static
Function: GetStructSigName(structTypeSig) Get display name of structTypeSig.
Parameter(s): structName = string to put struct name into structTypeSig = signature of the ICC struct type to get a name for bFillUnknown = flag to indicate structName is filled if not found
Returns true if struct type is recognized by any factory, false if all factories do not create structTypeSig structs. If struct type is not recognized by any factories a suitable display name will be placed in structName if bFillUknown is true.
      { return CIccStructCreator::GetInstance()->DoGetStructSigName(structName, structTypeSig, bFillUnknown); }
References DoGetStructSigName(), and GetInstance().
Referenced by CIccTagStruct::Describe(), and CIccInfo::GetStructSigName().
PopFactory()
static IIccStructFactory * CIccStructCreator::PopFactory () inline static
Function: PopFactory() Remove the top IIccStructFactory from the stack of element factories tracked by the system.
Parameter(s): None
Returns the top IIccStructFactory from the stack of element factories tracked by the system. The returned element factory is no longer owned by the system and needs to be deleted to avoid memory leaks.
Note: The initial CIccBasicElemFactory cannot be popped off the stack.
      { return CIccStructCreator::GetInstance()->DoPopFactory(); }
References DoPopFactory(), and GetInstance().
PushFactory()
static void CIccStructCreator::PushFactory (IIccStructFactory * pFactory) inline static
Function: PushFactory(pFactory) Add an IIccStructFactory to the stack of element factories tracked by the system.
Parameter(s): pFactory = pointer to an IIccStructFactory object to add to the system. The pFactory must be created with new, and will be owned CIccStructCreator until popped off the stack using PopFactory(). Any factories not popped off will be taken care of properly on application shutdown.
      { CIccStructCreator::GetInstance()->CIccStructCreator::DoPushFactory(pFactory); }
References DoPushFactory(), and GetInstance().
Field Documentation
factoryStack
CIccStructFactoryList CIccStructCreator::factoryStack private
Referenced by DoCreateStruct(), DoGetStructSig(), DoGetStructSigName(), DoPopFactory(), and DoPushFactory().
theStructCreator
std::unique_ptr< CIccStructCreator > CIccStructCreator::theStructCreator static private
Referenced by GetInstance().
The documentation for this class was generated from the following files:
IccProfLib/IccStructFactory.h
IccProfLib/IccStructFactory.cpp