iccDEV: CIccBasicStructFactory Class Reference
CIccBasicStructFactory Class Reference
#include <IccStructFactory.h>
Public Member Functions
virtual IIccStruct * CreateStruct (icStructSignature structSig, CIccTagStruct *pTagStruct=NULL)
virtual icStructSignature GetStructSig (const icChar *structName)
virtual bool GetStructSigName (std::string &structName, icStructSignature structTypeSig, bool bFindUnknown=false)
Detailed Description
Class: CIccBasicStructFactory
Purpose: CIccBasicStructFactory provides creation of CIccProcessStruct's defined by the ICC profile specification. The CIccStructCreator always creates a CIccBasicElemFactory.
Member Function Documentation
CreateStruct()
IIccStruct * CIccBasicStructFactory::CreateStruct (icStructSignature structSig, CIccTagStruct * pTagStruct = NULL) virtual
Function: CreateStruct(structTypeSig) Create a struct object of type structTypeSig.
Parameter(s): structTypeSig = signature of the ICC struct type for the struct to be created
Returns a new CIccProcessStruct object of the given signature type. Unrecognized structTypeSig's will be created as a CIccStructUnknown object.
Implements IIccStructFactory.
{
  switch(structTypeSig) {
    case icSigBRDFStruct:
      return new CIccStructBRDF(pTagStruct);
    case icSigColorantInfoStruct:
      return new CIccStructColorantInfo(pTagStruct);
    case icSigColorEncodingParamsSruct:
      return new CIccStructColorEncodingParams(pTagStruct);
    case icSigMeasurementInfoStruct:
      return new CIccStructMeasurementInfo(pTagStruct);
    case icSigNamedColorStruct:
      return new CIccStructNamedColor(pTagStruct);
    case icSigProfileInfoStruct:
      return new CIccStructProfileInfo(pTagStruct);
    case icSigTintZeroStruct:
      return new CIccStructTintZero(pTagStruct);
    default:
      return new CIccStructUnknown(pTagStruct);
  }
}
References CIccStructBRDF::CIccStructBRDF(), CIccStructColorantInfo::CIccStructColorantInfo(), CIccStructColorEncodingParams::CIccStructColorEncodingParams(), CIccStructMeasurementInfo::CIccStructMeasurementInfo(), CIccStructNamedColor::CIccStructNamedColor(), CIccStructProfileInfo::CIccStructProfileInfo(), CIccStructTintZero::CIccStructTintZero(), CIccStructUnknown::CIccStructUnknown(), icSigBRDFStruct, icSigColorantInfoStruct, icSigColorEncodingParamsSruct, icSigMeasurementInfoStruct, icSigNamedColorStruct, icSigProfileInfoStruct, and icSigTintZeroStruct.
GetStructSig()
icStructSignature CIccBasicStructFactory::GetStructSig (const icChar * structName) virtual
Function: GetStructSig(structName) Get signature of structure from display name.
Parameter(s): structName = struct display name
Returns signature of structure if it is recognized by the factory, 0 if the factory doesn't create structures with such a display name.
Implements IIccStructFactory.
{
  int i;
  for (i = 0; g_icStructNames[i].sig; i++) {
    if (!strcmp(g_icStructNames[i].szStructName, szStructName)) {
      return g_icStructNames[i].sig;
    }
  }
  return (icStructSignature)0;
}
GetStructSigName()
bool CIccBasicStructFactory::GetStructSigName (std::string & structName, icStructSignature structTypeSig, bool bFindUnknown = false) virtual
Function: GetStructSigName(structTypeSig) Get display name of structTypeSig.
Parameter(s): structName = string to put struct name into, structTypeSig = signature of the ICC struct type to get a name for
Returns true if struct type is recognized by the factory, false if the factory doesn't create structTypeSig structs.
Implements IIccStructFactory.
{
  int i;
  for (i = 0; g_icStructNames[i].sig; i++) {
    if (g_icStructNames[i].sig == structTypeSig) {
      structName = g_icStructNames[i].szStructName;
      return true;
    }
  }
  if (!bFindUnknown) {
    char sig[20];
    structName = "UnknownStruct_";
    icGetSigStr(sig, structTypeSig);
    structName += sig;
  }
  else {
    structName = "";
  }
  return false;
}
References icGetSigStr().
The documentation for this class was generated from the following files:
IccProfLib/IccStructFactory.h
IccProfLib/IccStructFactory.cpp