iccDEV: CIccTagSparseMatrixArray Class Reference
CIccTagSparseMatrixArray Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagSparseMatrixArray (const CIccTagSparseMatrixArray &ITSMA)
CIccTagSparseMatrixArray (int nNumMatrices=1, int nChannelsPerMatrix=4)
virtual ~CIccTagSparseMatrixArray ()
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
icUInt32Number GetBytesPerMatrix () const
icUInt32Number GetChannelsPerMatrix () const
virtual const icChar * GetClassName () const
virtual IIccExtensionTag * GetExtension ()
icSparseMatrixType GetMatrixType () const
icUInt32Number GetNumMatrices () const
Returns the number of matrices in the array.
virtual icUInt32Number GetNumValues () const
bool GetSparseMatrix (CIccSparseMatrix &mtx, int nIndex, bool bInitFromData=true)
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual bool GetValues (icFloatNumber *DstVector, icUInt32Number nStart=0, icUInt32Number nVectorSize=1) const
virtual bool Interpolate (icFloatNumber *DstVector, icFloatNumber val, icUInt32Number nVectorSize=1, icFloatNumber *zeroVals=NULL) const
virtual bool IsArrayType ()
virtual bool IsMatrixArray () const
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy ()
virtual CIccTag * NewCopy () const
CIccTagSparseMatrixArray & operator= (const CIccTagSparseMatrixArray &ITSMA)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
bool Reset (icUInt32Number nNumMatrices, icUInt16Number nChannelsPerMatrix)
void SetMatrixType (icSparseMatrixType nType)
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool ValuePos (icFloatNumber &DstPos, icFloatNumber val, bool &bNoZero) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
Protected Attributes
bool m_bNonZeroPadding
icUInt16Number m_nChannelsPerMatrix
icSparseMatrixType m_nMatrixType
icUInt32Number m_nSize
icUInt8Number * m_RawData
Detailed Description
Class: CIccTagSparseMatrixArray
Purpose: A template class for arrays of Fixed point numbers
Derived Tags: CIccTagS15Fixed16 and CIccTagU16Fixed16
Constructor & Destructor Documentation
CIccTagSparseMatrixArray() [1/2]
CIccTagSparseMatrixArray::CIccTagSparseMatrixArray (int nNumMatrices = 1, int nChannelsPerMatrix = 4)
Name: CIccTagSparseMatrixArray::CIccTagSparseMatrixArray
Purpose: CIccTagSparseMatrixArray Constructor
Args: nSize = number of data entries
{
  m_nSize =  nNumMatrices;
  m_nChannelsPerMatrix = nChannelsPerMatrix;
  m_nMatrixType = icSparseMatrixFloat32;
  if (m_nSize <1)
    m_nSize = 1;
  if (nChannelsPerMatrix<4)
    m_nChannelsPerMatrix = 4;
  m_RawData = (icUInt8Number*)calloc(m_nSize, GetBytesPerMatrix());
  m_bNonZeroPadding = false;
}
References GetBytesPerMatrix(), icSparseMatrixFloat32, m_bNonZeroPadding, m_nChannelsPerMatrix, m_nMatrixType, m_nSize, and m_RawData.
CIccTagSparseMatrixArray() [2/2]
CIccTagSparseMatrixArray::CIccTagSparseMatrixArray (const CIccTagSparseMatrixArray & ITSMA)
Name: CIccTagSparseMatrixArray::CIccTagSparseMatrixArray
Purpose: Copy Constructor
Args: ITFN = The CIccTagFixedNum object to be copied
{
  m_nSize = ITSMA.m_nSize;
  m_nChannelsPerMatrix = ITSMA.m_nChannelsPerMatrix;
  m_nMatrixType = ITSMA.m_nMatrixType;
  m_RawData = (icUInt8Number*)calloc(m_nSize, GetBytesPerMatrix());
  memcpy(m_RawData, ITSMA.m_RawData, m_nSize*GetBytesPerMatrix());
  m_bNonZeroPadding = ITSMA.m_bNonZeroPadding;
}
References GetBytesPerMatrix(), m_bNonZeroPadding, m_nChannelsPerMatrix, m_nMatrixType, m_nSize, and m_RawData.
Referenced by NewCopy().
~CIccTagSparseMatrixArray()
CIccTagSparseMatrixArray::~CIccTagSparseMatrixArray () virtual
Name: CIccTagSparseMatrixArray::~CIccTagSparseMatrixArray
Purpose: Destructor
{
  if (m_RawData)
    free(m_RawData);
}
References m_RawData.
Member Function Documentation
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagSparseMatrixArray::Describe (std::string & sDescription, int nVerboseness) virtual
Name: CIccTagSparseMatrixArray::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  icChar buf[128];
  sDescription += "Begin_SparseMatrix_Array\n";
  sprintf(buf, "OutputChannels = %d\n", m_nChannelsPerMatrix);
  sDescription += buf;
  sprintf(buf, "MatrixType = %d\n", m_nMatrixType);
  sDescription += buf;
  int i, r, c;
  icUInt32Number nBytesPerMatrix = m_nChannelsPerMatrix * sizeof(icFloatNumber);
  for (i=0; i<(int)m_nSize; i++) {
    CIccSparseMatrix mtx(&m_RawData[i*nBytesPerMatrix], nBytesPerMatrix, icSparseMatrixFloatNum, true);
    sprintf(buf, "\nBegin_Matrix_%d\n", i);
    sDescription += buf;
    icUInt16Number *start = mtx.GetRowStart();
    icUInt16Number *cols = mtx.GetColumnsForRow(0);
    for (r=0; r<mtx.Rows(); r++) {
      icUInt16Number rs = start[r];
      icUInt16Number re = start[r+1];
      sprintf(buf, "Row%d:", r);
      sDescription += buf;
      for (c=rs; c<re; c++) {
        sprintf(buf, " (%d, %.4lf)", cols[c], mtx.GetData()->get(c));
        sDescription += buf;
      }
    }
    sprintf(buf, "End_Matrix_%d\n", i);
    sDescription += buf;
  }
  sDescription += "\nEnd_SparseMatrix_Array\n";
}
References CIccSparseMatrix::CIccSparseMatrix(), IIccSparseMatrixEntry::get(), CIccSparseMatrix::GetColumnsForRow(), CIccSparseMatrix::GetData(), CIccSparseMatrix::GetRowStart(), m_nChannelsPerMatrix, m_nMatrixType, m_nSize, m_RawData, and CIccSparseMatrix::Rows().
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
GetBytesPerMatrix()
icUInt32Number CIccTagSparseMatrixArray::GetBytesPerMatrix () const inline
{ return m_nChannelsPerMatrix*sizeof(icFloatNumber); }
References m_nChannelsPerMatrix.
Referenced by CIccTagSparseMatrixArray(), CIccTagSparseMatrixArray(), GetSparseMatrix(), GetValues(), Interpolate(), operator=(), CIccTagXmlSparseMatrixArray::ParseXml(), Read(), Reset(), and CIccTagXmlSparseMatrixArray::ToXml().
GetChannelsPerMatrix()
icUInt32Number CIccTagSparseMatrixArray::GetChannelsPerMatrix () const inline
{ return m_nChannelsPerMatrix; }
References m_nChannelsPerMatrix.
Referenced by CIccArrayNamedColor::Validate().
GetClassName()
virtual const icChar * CIccTagSparseMatrixArray::GetClassName () const inline virtual
Reimplemented from CIccTag.
Reimplemented in CIccTagXmlSparseMatrixArray.
{ return "CIccTagChromaticity"; }
GetExtension()
virtual IIccExtensionTag * CIccTag::GetExtension () inline virtual inherited
Reimplemented in CIccTagXmlUnknown, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, CIccTagXmlSignature, CIccTagXmlNamedColor2, CIccTagXmlXYZ, CIccTagXmlChromaticity, CIccTagXmlCicp, CIccTagXmlSparseMatrixArray, CIccTagXmlFixedNum< T, Tsig >, CIccTagXmlNum< T, A, Tsig >, CIccTagXmlFloatNum< T, A, Tsig >, CIccTagXmlMeasurement, CIccTagXmlMultiLocalizedUnicode, CIccTagXmlTagData, CIccTagXmlDateTime, CIccTagXmlColorantOrder, CIccTagXmlColorantTable, CIccTagXmlViewingConditions, CIccTagXmlSpectralDataInfo, CIccTagXmlSpectralViewingConditions, CIccTagXmlProfileSeqDesc, CIccTagXmlResponseCurveSet16, CIccTagXmlCurve, CIccTagXmlParametricCurve, CIccTagXmlSegmentedCurve, CIccTagXmlLutAtoB, CIccTagXmlLutBtoA, CIccTagXmlLut8, CIccTagXmlLut16, CIccTagXmlMultiProcessElement, CIccTagXmlProfileSequenceId, CIccTagXmlDict, CIccTagXmlStruct, CIccTagXmlArray, CIccTagXmlGamutBoundaryDesc, CIccTagXmlEmbeddedHeightImage, CIccTagXmlEmbeddedNormalImage, and CIccTagXmlEmbeddedProfile.
{return NULL;}
Referenced by icCurvesFromXml(), icCurvesToXml(), icProfDescToXml(), icXmlParseProfDesc(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeXmlTintArray::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
GetMatrixType()
icSparseMatrixType CIccTagSparseMatrixArray::GetMatrixType () const inline
{ return m_nMatrixType; }
References m_nMatrixType.
GetNumMatrices()
icUInt32Number CIccTagSparseMatrixArray::GetNumMatrices () const inline
Returns the number of matrices in the array.
{ return m_nSize; }
References m_nSize.
Referenced by GetNumValues().
GetNumValues()
virtual icUInt32Number CIccTagSparseMatrixArray::GetNumValues () const inline virtual
Implements CIccTagNumArray.
{ return GetNumMatrices(); }
References GetNumMatrices().
GetSparseMatrix()
bool CIccTagSparseMatrixArray::GetSparseMatrix (CIccSparseMatrix & mtx, int nIndex, bool bInitFromData = true)
Name: CIccTagSparseMatrixArray::GetValues
Purpose: Gets values from the num array tag as floating point numbers
Args: nSize - number of data entries, bZeroNew - flag to zero newly formed values
{
  if (nIndex<0 || nIndex>(int)m_nSize) {
    mtx.Reset(NULL, 0, icSparseMatrixFloatNum, false);
    return false;
  }
  icUInt32Number nBytesPerMatrix = GetBytesPerMatrix();
  mtx.Reset(m_RawData+nIndex*GetBytesPerMatrix(), nBytesPerMatrix, icSparseMatrixFloatNum, bInitFromData);
  return true;
}
References GetBytesPerMatrix(), m_nSize, m_RawData, and CIccSparseMatrix::Reset().
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagSparseMatrixArray::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigSparseMatrixArrayType; }
References icSigSparseMatrixArrayType.
Referenced by Write().
GetValues()
bool CIccTagSparseMatrixArray::GetValues (icFloatNumber * DstVector, icUInt32Number nStart = 0, icUInt32Number nVectorSize = 1) const virtual
Implements CIccTagNumArray.
{
  icUInt32Number nBytesPerMatrix = GetBytesPerMatrix();
  if (nVectorSize!=nBytesPerMatrix)
    return false;
  if (nStart % nBytesPerMatrix != 0)
    return false;
  if (nStart / nBytesPerMatrix > m_nSize)
    return false;
  memcpy(DstVector, m_RawData+nStart, nVectorSize);
  return true;
}
References GetBytesPerMatrix(), m_nSize, and m_RawData.
Interpolate()
bool CIccTagSparseMatrixArray::Interpolate (icFloatNumber * DstVector, icFloatNumber pos, icUInt32Number nVectorSize = 1, icFloatNumber * zeroVals = NULL) const virtual
Name: CIccTagSparseMatrixArray::Interpolate
Purpose: Gets values from the num array tag as floating point numbers
Args: nSize - number of data entries, bZeroNew - flag to zero newly formed values
Implements CIccTagNumArray.
{
  icUInt32Number nMatrix = m_nSize;
  if (!nMatrix || nVectorSize != GetBytesPerMatrix())
    return false;
  if (zeroVals)
    nMatrix ++;
  else if (nMatrix<=1)
    return false;
  if (pos<0.0)
    pos=0.0;
  if (pos>1.0)
    pos=1.0;
  icFloatNumber fpos = (icFloatNumber)(nMatrix-1) * pos;
  icUInt32Number iPos = (icUInt32Number)fpos;
  icFloatNumber x = fpos - iPos;
  if (iPos == nMatrix-1) {
    iPos--;
    x = (icFloatNumber)1.0;
  }
  icUInt8Number *lo, *hi;
  if (zeroVals) {
    if (!iPos) {
      lo = (icUInt8Number*)zeroVals;
      hi = m_RawData;
    }
    else {
      lo = &m_RawData[(iPos-1)*nVectorSize];
      hi = &lo[nVectorSize];
    }
  }
  else {
    lo = &m_RawData[iPos*nVectorSize];
    hi = &lo[nVectorSize];
  }
  CIccSparseMatrix mlo(lo, nVectorSize, icSparseMatrixFloatNum, true);
  CIccSparseMatrix mhi(hi, nVectorSize, icSparseMatrixFloatNum, true);
  CIccSparseMatrix dst((icUInt8Number*)DstVector, nVectorSize, icSparseMatrixFloatNum, false);
  if (mlo.Rows()!=mhi.Rows() || mlo.Cols()!=mhi.Cols())
    return false;
  if (!dst.Interp(1.0f-x, mlo, x, mhi))
    return false;
  return true;
}
References CIccSparseMatrix::CIccSparseMatrix(), CIccSparseMatrix::Cols(), GetBytesPerMatrix(), CIccSparseMatrix::Interp(), m_nSize, m_RawData, and CIccSparseMatrix::Rows().
IsArrayType()
virtual bool CIccTagSparseMatrixArray::IsArrayType () inline virtual
Reimplemented from CIccTag.
{ return m_nSize > 1; }
References m_nSize.
IsMatrixArray()
virtual bool CIccTagSparseMatrixArray::IsMatrixArray () const inline virtual
Implements CIccTagNumArray.
{ return true; }
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTagSparseMatrixArray::IsNumArrayType () const inline virtual
Reimplemented from CIccTag.
{ return true; }
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy() [1/2]
virtual CIccTag * CIccTagSparseMatrixArray::NewCopy () inline virtual
{ return new CIccTagSparseMatrixArray(*this); }
References CIccTagSparseMatrixArray().
NewCopy() [2/2]
virtual CIccTag * CIccTag::NewCopy () const inline virtual inherited
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented in CIccTagUnknown, CIccTagText, CIccTagUtf8Text, CIccTagZipUtf8Text, CIccTagZipXml, CIccTagUtf16Text, CIccTagTextDescription, CIccTagSignature, CIccTagNamedColor2, CIccTagXYZ, CIccTagChromaticity, CIccTagCicp, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, CIccTagMeasurement, CIccTagMultiLocalizedUnicode, CIccTagData, CIccTagDateTime, CIccTagColorantOrder, CIccTagColorantTable, CIccTagViewingConditions, CIccTagProfileSeqDesc, CIccTagResponseCurveSet16, CIccTagSpectralDataInfo, CIccTagSpectralViewingConditions, CIccTagEmbeddedHeightImage, CIccTagEmbeddedNormalImage, CIccTagStruct, CIccTagArray, CIccTagDict, CIccTagEmbeddedProfile, CIccCurve, CIccTagCurve, CIccTagParametricCurve, CIccTagSegmentedCurve, CIccMBB, CIccTagLutAtoB, CIccTagLutBtoA, CIccTagLut8, CIccTagLut16, CIccTagGamutBoundaryDesc, CIccTagMultiProcessElement, CIccTagProfileSequenceId, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, and CIccTagXmlMultiLocalizedUnicode.
{return new CIccTag;}
Referenced by CIccMpeTintArray::CIccMpeTintArray(), CIccProfileDescText::CIccProfileDescText(), CIccTagArray::CIccTagArray(), CIccTagStruct::CIccTagStruct(), CDevLinkWriter::begin(), icConvertEncodingProfile(), CIccMpeTintArray::operator=(), CIccProfileDescText::operator=(), CIccTagArray::operator=(), and CIccTagStruct::operator=().
operator=()
CIccTagSparseMatrixArray & CIccTagSparseMatrixArray::operator= (const CIccTagSparseMatrixArray & ITSMA)
Name: CIccTagSparseMatrixArray::operator=
Purpose: Copy Operator
Args: ITFN = The CIccTagSparseMatrixArray object to be copied
{
  if (&ITSMA == this)
    return *this;
  m_nSize = ITSMA.m_nSize;
  m_nChannelsPerMatrix = ITSMA.m_nChannelsPerMatrix;
  if (m_RawData)
    free(m_RawData);
  m_RawData = (icUInt8Number*)calloc(m_nSize, m_nChannelsPerMatrix);
  memcpy(m_RawData, ITSMA.m_RawData, m_nSize*GetBytesPerMatrix());
  m_bNonZeroPadding = ITSMA.m_bNonZeroPadding;
  return *this;
}
References GetBytesPerMatrix(), m_bNonZeroPadding, m_nChannelsPerMatrix, m_nSize, and m_RawData.
Read() [1/2]
bool CIccTagSparseMatrixArray::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagSparseMatrixArray::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  icUInt16Number nChannels;
  icUInt16Number nMatrixType;
  icUInt32Number nBytesPerMatrix;
  icUInt32Number nNumMatrices;
  icUInt32Number nHdrSize = sizeof(icTagTypeSignature) +
    sizeof(icUInt32Number) +
    2*sizeof(icUInt16Number) +
    sizeof(icUInt32Number);
  if (nHdrSize +sizeof(icUInt16Number) > size)
    return false;
  if (!pIO) {
    return false;
  }
  if (!pIO->Read32(&sig) ||
      !pIO->Read32(&m_nReserved) ||
      !pIO->Read16(&nChannels) ||
      !pIO->Read16(&nMatrixType) ||
      !pIO->Read32(&nNumMatrices))
    return false;
  m_nMatrixType = (icSparseMatrixType)nMatrixType;
  icUInt32Number nSizeLeft = size - nHdrSize;
  Reset(nNumMatrices, nChannels);
  nBytesPerMatrix = GetBytesPerMatrix();
  if (m_nSize) {
    icUInt32Number pos;
    icUInt16Number nRows;
    int i, j;
    icUInt32Number n, nAligned;
    CIccSparseMatrix mtx;
    m_bNonZeroPadding = false;
    pos = nHdrSize;
    for (i=0; i<(int)m_nSize; i++) {
      icUInt8Number *pMatrix = m_RawData + i*nBytesPerMatrix;
      n=2*sizeof(icUInt16Number);
      if (nSizeLeft<n)
        return false;
      if (pIO->Read16(pMatrix, 2)!=2) {
        return false;
      }
      nSizeLeft -= n;
      pos += n;
      nRows = *((icUInt16Number*)pMatrix);
      n=(nRows+1)*sizeof(icUInt16Number);
      if (nSizeLeft<n)
        return false;
      if (pIO->Read16(pMatrix+2*sizeof(icUInt16Number), nRows+1)!=nRows+1) {
        return false;
      }
      nSizeLeft -= n;
      pos += n;
      mtx.Reset(pMatrix, nBytesPerMatrix, icSparseMatrixFloatNum, true);
      if (mtx.GetNumEntries()>mtx.MaxEntries(nChannels*sizeof(icFloatNumber), mtx.Rows(), sizeof(icFloatNumber)))
        return false;
      n=mtx.GetNumEntries()*sizeof(icUInt16Number);
      if (nSizeLeft<n)
        return false;
      if (pIO->Read16(mtx.GetColumnsForRow(0), mtx.GetNumEntries())!=mtx.GetNumEntries())
        return false;
      nSizeLeft -= n;
      pos += n;
      nAligned = ((pos+3)/4)*4;
      if (nAligned != pos) {
        n = nAligned - pos;
        if (nSizeLeft < n)
          return false;
        char zbuf[3] = { 0 };
        if (pIO->Read8(&zbuf[0], n)!=n)
          return false;
        for (j=0; j<(int)n; j++) {
          if (zbuf[j])
            m_bNonZeroPadding = true;
        }
        nSizeLeft -= n;
        pos += n;
      }
      switch(m_nMatrixType) {
        case icSparseMatrixUInt8:
          n=mtx.GetNumEntries()*sizeof(icUInt8Number);
          if (nSizeLeft<n)
            return false;
          if (pIO->ReadUInt8Float(mtx.GetData()->getPtr(0), mtx.GetNumEntries())!=mtx.GetNumEntries())
            return false;
          break;
        case icSparseMatrixUInt16:
          n=mtx.GetNumEntries()*sizeof(icUInt16Number);
          if (nSizeLeft<n)
            return false;
          if (pIO->ReadUInt16Float(mtx.GetData()->getPtr(0), mtx.GetNumEntries())!=mtx.GetNumEntries())
            return false;
          break;
        case icSparseMatrixFloat16:
          n=mtx.GetNumEntries()*sizeof(icFloat16Number);
          if (nSizeLeft<n)
            return false;
          if (pIO->ReadFloat16Float(mtx.GetData()->getPtr(0), mtx.GetNumEntries())!=mtx.GetNumEntries())
            return false;
          break;
        case icSparseMatrixFloat32:
          n=mtx.GetNumEntries()*sizeof(icFloat32Number);
          if (nSizeLeft<n)
            return false;
          if (pIO->ReadFloat32Float(mtx.GetData()->getPtr(0), mtx.GetNumEntries())!=mtx.GetNumEntries())
            return false;
          break;
        default:
          return false;
      }
      nSizeLeft -= n;
      pos += n;
      nAligned = ((pos+3)/4)*4;
      if (nAligned != pos) {
        n = nAligned - pos;
        if (nSizeLeft < n)
          return false;
        icUInt8Number zbuf[3] = { 0 };
        if (pIO->Read8(&zbuf[0], n)!=n)
          return false;
        for (j=0; j<(int)n; j++) {
          if (zbuf[j])
            m_bNonZeroPadding = true;
        }
        nSizeLeft -= n;
        pos += n;
      }
    }
    if (nSizeLeft) {
      icUInt8Number b;
      for (i=0; i<(int)nSizeLeft; i++) {
        if (!pIO->Read8(&b))
          return false;
        if (b)
          m_bNonZeroPadding = true;
      }
    }
  }
  return true;
}
References GetBytesPerMatrix(), CIccSparseMatrix::GetColumnsForRow(), CIccSparseMatrix::GetData(), CIccSparseMatrix::GetNumEntries(), IIccSparseMatrixEntry::getPtr(), icSparseMatrixFloat16, icSparseMatrixFloat32, icSparseMatrixUInt16, icSparseMatrixUInt8, m_bNonZeroPadding, m_nMatrixType, CIccTag::m_nReserved, m_nSize, m_RawData, CIccSparseMatrix::MaxEntries(), CIccIO::Read16(), CIccIO::Read32(), CIccIO::Read8(), CIccIO::ReadFloat16Float(), CIccIO::ReadFloat32Float(), CIccIO::ReadUInt16Float(), CIccIO::ReadUInt8Float(), Reset(), CIccSparseMatrix::Reset(), and CIccSparseMatrix::Rows().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
Reset()
bool CIccTagSparseMatrixArray::Reset (icUInt32Number nNumMatrices, icUInt16Number nChannelsPerMatrix)
Name: CIccTagSparseMatrixArray::Reset
Purpose: Sets the size of the data array erasing all previous values
Args: nNumMatrices - number of matrices numChannelsPerMatrix - Equivalent number of output channels that determines the fixed block size for each matrix
{
  if (nNumMatrices==m_nSize && nChannelsPerMatrix==m_nChannelsPerMatrix)
    return true;
  m_nSize = nNumMatrices;
  m_nChannelsPerMatrix = nChannelsPerMatrix;
  icUInt32Number nSize = m_nSize * GetBytesPerMatrix();
  m_RawData = (icUInt8Number *)icRealloc(m_RawData, nSize);
  if (!m_RawData) {
    m_nSize = 0;
    return false;
  }
  memset(m_RawData, 0, nSize);
  return true;
}
References GetBytesPerMatrix(), icRealloc(), m_nChannelsPerMatrix, m_nSize, and m_RawData.
Referenced by CIccTagXmlSparseMatrixArray::ParseXml(), and Read().
SetMatrixType()
void CIccTagSparseMatrixArray::SetMatrixType (icSparseMatrixType nType) inline
{ m_nMatrixType = nType; }
References m_nMatrixType.
Validate()
icValidateStatus CIccTagSparseMatrixArray::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagSparseMatrixArray::Validate
Purpose: Validates tag data
Args: sigPath - signature path of tag in profile to validate sReport - string to put validation report results profile - pointer to profile that contains the tag
Reimplemented from CIccTag.
{
  icValidateStatus rv = icValidateOK;
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  switch(m_nMatrixType) {
    case icSparseMatrixUInt8:
    case icSparseMatrixUInt16:
    case icSparseMatrixFloat16:
    case icSparseMatrixFloat32:
      break;
    default:
      sReport += icMsgValidateCriticalError;
      sReport += sSigPathName;
      sReport += " - Invalid Sparse Matrix Type.\n";
      rv = icMaxStatus(rv, icValidateCriticalError);
  }
  bool bCheckPCS=false;
  icSignature sig1 = icGetFirstSigPathSig(sigPath);
  icSignature sig2 = icGetSecondSigPathSig(sigPath);
  if (sig1==icSigSpectralWhitePointTag) {
    bCheckPCS = true;
  }
  if (bCheckPCS && pProfile) {
    if (!icIsSameColorSpaceType(pProfile->m_Header.spectralPCS, icSigSparseMatrixReflectanceData)) {
      sReport += icMsgValidateCriticalError;
      sReport += sSigPathName;
      sReport += " - SparseMatrix data incompatible with spectral PCS.\n";
      rv = icMaxStatus(rv, icValidateCriticalError);
    }
    else if (icGetSpaceSamples((icColorSpaceSignature)pProfile->m_Header.spectralPCS)!=m_nChannelsPerMatrix) {
      sReport += icMsgValidateCriticalError;
      sReport += sSigPathName;
      sReport += " - SparseMatrix Output channels doesn't match spectral PCS channels.\n";
      rv = icMaxStatus(rv, icValidateCriticalError);
    }
  }
  if (m_bNonZeroPadding) {
    sReport += icMsgValidateNonCompliant;
    sReport += sSigPathName;
    sReport += " - Non zero padding in matrices used.\n";
    rv = icMaxStatus(rv, icValidateNonCompliant);
  }
  if (!m_nSize) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " - No Matrices Defined.\n";
    rv = icMaxStatus(rv, icValidateWarning);
    return rv;
  }
  if (!m_RawData) {
    sReport += icMsgValidateCriticalError;
    sReport += sSigPathName;
    sReport += " - Data dont defined for matrices\n";
    rv = icMaxStatus(rv, icValidateCriticalError);
    return rv;
  }
  icUInt16Number nRows, nCols;
  CIccSparseMatrix mtx;
  int i;
  icUInt16Number nBytesPerMatrix = m_nChannelsPerMatrix * sizeof(icFloatNumber);
  mtx.Reset(m_RawData, nBytesPerMatrix, icSparseMatrixFloatNum, true);
  nRows = mtx.Rows();
  nCols = mtx.Cols();
  icUInt32Number nMaxElements = CIccSparseMatrix::MaxEntries(nBytesPerMatrix, nRows, sizeof(icFloatNumber));
  char buf[128];
  icUInt8Number *temp = new icUInt8Number[nBytesPerMatrix];
  for (i=0; i<(int)m_nSize; i++) {
    mtx.Reset(m_RawData+i*nBytesPerMatrix, nBytesPerMatrix, icSparseMatrixFloatNum, true);
    if (mtx.Rows() != nRows || mtx.Cols() != nCols) {
      sReport += icMsgValidateCriticalError;
      sReport += sSigPathName;
      sprintf(buf, " - Matrix[%d] doesn't have matching rows and columns.\n", i);
      sReport += buf;
      rv = icMaxStatus(rv, icValidateCriticalError);
    }
    if (mtx.GetNumEntries()>nMaxElements) {
      sReport += icMsgValidateCriticalError;
      sReport += sSigPathName;
      sprintf(buf, " - Matrix[%d] entries exceeds number supported by Output channels.\n", i);
        sReport += buf;
      rv = icMaxStatus(rv, icValidateCriticalError);
    }
    if (!mtx.IsValid()) {
      sReport += icMsgValidateCriticalError;
      sReport += sSigPathName;
      sprintf(buf, " - Matrix[%d] has an invalid matrix structure.\n", i);
        sReport += buf;
      rv = icMaxStatus(rv, icValidateCriticalError);
    }
    if (i<(int)(m_nSize-1)) {
      CIccSparseMatrix umtx(temp, nBytesPerMatrix, icSparseMatrixFloatNum, false);
      CIccSparseMatrix mtx2(m_RawData+(i+1)*nBytesPerMatrix, nBytesPerMatrix, icSparseMatrixFloatNum, true);
      umtx.Init(nRows, nCols);
      if (!umtx.Union(mtx, mtx2)) {
        sReport += icMsgValidateCriticalError;
        sReport += sSigPathName;
        sprintf(buf, " - Interpolation from Matrix[%d] exceeds number of supported Output channels.\n", i);
        sReport += buf;
        rv = icMaxStatus(rv, icValidateCriticalError);
      }
    }
  }
  delete [] temp;
  return rv;
}
References CIccSparseMatrix::CIccSparseMatrix(), CIccSparseMatrix::Cols(), CIccSparseMatrix::GetNumEntries(), CIccInfo::GetSigPathName(), icGetFirstSigPathSig(), icGetSecondSigPathSig(), icGetSpaceSamples(), icMaxStatus(), icMsgValidateCriticalError, icMsgValidateNonCompliant, icMsgValidateWarning, icSigSparseMatrixReflectanceData, icSigSpectralWhitePointTag, icSparseMatrixFloat16, icSparseMatrixFloat32, icSparseMatrixUInt16, icSparseMatrixUInt8, icValidateCriticalError, icValidateNonCompliant, icValidateOK, icValidateWarning, CIccSparseMatrix::Init(), CIccSparseMatrix::IsValid(), m_bNonZeroPadding, m_nChannelsPerMatrix, m_nMatrixType, m_nSize, m_RawData, CIccSparseMatrix::MaxEntries(), CIccSparseMatrix::Reset(), CIccSparseMatrix::Rows(), icHeader::spectralPCS, and CIccSparseMatrix::Union().
ValuePos()
bool CIccTagSparseMatrixArray::ValuePos (icFloatNumber & DstPos, icFloatNumber val, bool & bNoZero) const virtual
Name: CIccTagSparseMatrixArray::ValuePos
Purpose: Gets position of a value int the num array tag
Args: DstPos - position of val in array val - value to look for in array. bNoZero - flag indicating whether first entry is zero
Implements CIccTagNumArray.
{
  //ValuePos not supported for Sparse Matrices
  return false;
}
Write()
bool CIccTagSparseMatrixArray::Write (CIccIO * pIO) virtual
Name: CIccTagSparseMatrixArray::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  icUInt16Number nTemp = m_nMatrixType;
  if (!pIO)
   return false;
  if (!pIO->Write32(&sig) ||
      !pIO->Write32(&m_nReserved) ||
      !pIO->Write16(&m_nChannelsPerMatrix) ||
      !pIO->Write16(&nTemp) ||
      !pIO->Write32(&m_nSize))
      return false;
  icUInt32Number nBytesPerMatrix = m_nChannelsPerMatrix * sizeof(icFloatNumber);
  CIccSparseMatrix mtx;
  icUInt16Number nRows;
  int i, n;
  for (i=0; i<(int)m_nSize; i++) {
    icUInt8Number *pMatrix = m_RawData + i*nBytesPerMatrix;
    mtx.Reset(pMatrix, nBytesPerMatrix, icSparseMatrixFloatNum, true);
    nRows = mtx.Rows();
    n=(nRows+3)*sizeof(icUInt16Number);
    if (pIO->Write16(pMatrix, nRows+3)!=nRows+3 ||
        pIO->Write16(mtx.GetColumnsForRow(0), mtx.GetNumEntries())!=mtx.GetNumEntries()) {
      return false;
    }
    if (!pIO->Align32())
      return false;
    switch(m_nMatrixType) {
      case icSparseMatrixUInt8:
        if (pIO->WriteUInt8Float(mtx.GetData()->getPtr(), mtx.GetNumEntries())!=mtx.GetNumEntries()) {
          return false;
        }
        break;
      case icSparseMatrixUInt16:
        if (pIO->WriteUInt16Float(mtx.GetData()->getPtr(), mtx.GetNumEntries())!=mtx.GetNumEntries()) {
          return false;
        }
        break;
      case icSparseMatrixFloat16:
        if (pIO->WriteFloat16Float(mtx.GetData()->getPtr(), mtx.GetNumEntries())!=mtx.GetNumEntries()) {
          return false;
        }
        break;
      case icSparseMatrixFloat32:
        if (pIO->WriteFloat32Float(mtx.GetData()->getPtr(), mtx.GetNumEntries())!=mtx.GetNumEntries()) {
          return false;
        }
        break;
      default:
        return false;
    }
    if (!pIO->Align32())
      return false;
  }
  return true;
}
References CIccIO::Align32(), CIccSparseMatrix::GetColumnsForRow(), CIccSparseMatrix::GetData(), CIccSparseMatrix::GetNumEntries(), IIccSparseMatrixEntry::getPtr(), GetType(), icSparseMatrixFloat16, icSparseMatrixFloat32, icSparseMatrixUInt16, icSparseMatrixUInt8, m_nChannelsPerMatrix, m_nMatrixType, CIccTag::m_nReserved, m_nSize, m_RawData, CIccSparseMatrix::Reset(), CIccSparseMatrix::Rows(), CIccIO::Write16(), CIccIO::Write32(), CIccIO::WriteFloat16Float(), CIccIO::WriteFloat32Float(), CIccIO::WriteUInt16Float(), and CIccIO::WriteUInt8Float().
Field Documentation
m_bNonZeroPadding
bool CIccTagSparseMatrixArray::m_bNonZeroPadding protected
Referenced by CIccTagSparseMatrixArray(), CIccTagSparseMatrixArray(), operator=(), Read(), and Validate().
m_nChannelsPerMatrix
icUInt16Number CIccTagSparseMatrixArray::m_nChannelsPerMatrix protected
Referenced by CIccTagSparseMatrixArray(), CIccTagSparseMatrixArray(), Describe(), GetBytesPerMatrix(), GetChannelsPerMatrix(), operator=(), Reset(), CIccTagXmlSparseMatrixArray::ToXml(), Validate(), and Write().
m_nMatrixType
icSparseMatrixType CIccTagSparseMatrixArray::m_nMatrixType protected
Referenced by CIccTagSparseMatrixArray(), CIccTagSparseMatrixArray(), Describe(), GetMatrixType(), CIccTagXmlSparseMatrixArray::ParseXml(), Read(), SetMatrixType(), CIccTagXmlSparseMatrixArray::ToXml(), Validate(), and Write().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_nSize
icUInt32Number CIccTagSparseMatrixArray::m_nSize protected
Referenced by CIccTagSparseMatrixArray(), CIccTagSparseMatrixArray(), Describe(), GetNumMatrices(), GetSparseMatrix(), GetValues(), Interpolate(), IsArrayType(), operator=(), Read(), Reset(), CIccTagXmlSparseMatrixArray::ToXml(), Validate(), and Write().
m_RawData
icUInt8Number* CIccTagSparseMatrixArray::m_RawData protected
Referenced by CIccTagSparseMatrixArray(), CIccTagSparseMatrixArray(), ~CIccTagSparseMatrixArray(), Describe(), GetSparseMatrix(), GetValues(), Interpolate(), operator=(), CIccTagXmlSparseMatrixArray::ParseXml(), Read(), Reset(), CIccTagXmlSparseMatrixArray::ToXml(), Validate(), and Write().
The documentation for this class was generated from the following files:
IccProfLib/IccTagBasic.h
IccProfLib/IccTagBasic.cpp