iccDEV: CIccTagXmlCurve Class Reference
CIccTagXmlCurve Class Reference
#include <IccTagXml.h>
Public Member Functions
virtual ~CIccTagXmlCurve ()
virtual icFloatNumber Apply (icFloatNumber v) const
virtual void Begin ()
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
virtual void DumpLut (std::string &sDescription, const icChar *szName, icColorSpaceSignature csSig, int nIndex, int nVerboseness)
icFloatNumber Find (icFloatNumber v)
virtual const char * GetClassName () const
icFloatNumber * GetData (icUInt32Number index)
virtual const char * GetExtClassName () const
virtual const char * GetExtDerivedClassName () const
virtual IIccExtensionTag * GetExtension ()
icUInt32Number GetSize () const
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsIdentity ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
icFloatNumber & operator[] (icUInt32Number index)
virtual bool ParseXml (xmlNode *pNode, icConvertType nType, std::string &parseStr)
virtual bool ParseXml (xmlNode *pNode, std::string &parseStr)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
bool SetGamma (icFloatNumber gamma)
bool SetSize (icUInt32Number nSize, icTagCurveSizeInit nSizeOpt=icInitZero)
virtual bool ToXml (std::string &xml, icConvertType nType, std::string blanks="")
virtual bool ToXml (std::string &xml, std::string blanks="")
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
Protected Member Functions
icFloatNumber Find (icFloatNumber v, icFloatNumber p0, icFloatNumber v0, icFloatNumber p1, icFloatNumber v1)
Protected Attributes
icFloatNumber * m_Curve
icUInt16Number m_nMaxIndex
icUInt32Number m_nSize
Detailed Description
Constructor & Destructor Documentation
~CIccTagXmlCurve()
virtual CIccTagXmlCurve::~CIccTagXmlCurve () inline virtual
{}
Member Function Documentation
Apply()
icFloatNumber CIccTagCurve::Apply (icFloatNumber v) const virtual inherited
Name: CIccTagCurve::Apply
Purpose: Applies the curve to the value passed.
Args: v = value to be passed through the curve.
Return: The value modified by the curve.
Reimplemented from CIccCurve.
{
  if(v<0.0) v = 0.0;
  else if(v>1.0) v = 1.0;
  icUInt32Number nIndex = (icUInt32Number)(v * m_nMaxIndex);
  if (!m_nSize) {
    return v;
  }
  if (m_nSize==1) {
    //Convert 0.0 to 1.0 float to 16bit and then convert from u8Fixed8Number
    icFloatNumber dGamma = (icFloatNumber)(m_Curve[0] * 65535.0 / 256.0);
    return (icFloatNumber)pow(v, dGamma);
  }
  if (nIndex == m_nMaxIndex) {
    return m_Curve[nIndex];
  }
  else {
    icFloatNumber nDif = v*m_nMaxIndex - nIndex;
    icFloatNumber p0 = m_Curve[nIndex];
    icFloatNumber rv = p0 + (m_Curve[nIndex+1]-p0)*nDif;
    if (rv>1.0)
      rv=1.0;
    return rv;
  }
}
References CIccTagCurve::m_Curve, CIccTagCurve::m_nMaxIndex, and CIccTagCurve::m_nSize.
Referenced by CIccTagLut8::Write().
Begin()
virtual void CIccTagCurve::Begin () inline virtual inherited
Reimplemented from CIccCurve.
{m_nMaxIndex = (icUInt16Number)m_nSize - 1;}
References CIccTagCurve::m_nMaxIndex, and CIccTagCurve::m_nSize.
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagCurve::Describe (std::string & sDescription, int nVerboseness) virtual inherited
Name: CIccTagCurve::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  icChar buf[128], *ptr;
  if (!m_nSize) {
    sprintf(buf, "BEGIN_CURVE In_Out\n");
    sDescription += buf;
    sDescription += "Y = X\n";
  }
  else if (m_nSize==1) {
    icFloatNumber dGamma = (icFloatNumber)(m_Curve[0] * 256.0);
    sprintf(buf, "BEGIN_CURVE In_Out\n");
    sDescription += buf;
    sprintf(buf, "Y = X ^ %.4lf\n", dGamma);
    sDescription += buf;
  }
  else {
    int i;
    sprintf(buf, "BEGIN_LUT In_Out 1 1\n");
    sDescription += buf;
    if (nVerboseness > 75) {
      sDescription += "IN OUT\n";
      for (i=0; i<(int)m_nSize; i++) {
        ptr = buf;
        icColorValue(buf, (icFloatNumber)i/(m_nSize-1), icSigMCH1Data, 1);
        ptr += strlen(buf);
        strcpy(ptr, " ");
        ptr ++;
        icColorValue(ptr, m_Curve[i], icSigMCH1Data, 1);
        ptr += strlen(ptr);
        strcpy(ptr, "\n");
       sDescription += buf;
      }
    }
  }
}
References icColorValue(), icSigMCH1Data, CIccTagCurve::m_Curve, and CIccTagCurve::m_nSize.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
DumpLut()
void CIccTagCurve::DumpLut (std::string & sDescription, const icChar * szName, icColorSpaceSignature csSig, int nIndex, int nVerboseness) virtual inherited
Name: CIccTagCurve::DumpLut
Purpose: Dump data associated with the tag to a string. Basically has the same function as Describe()
Args: sDescription = string to concatenate tag dump to, szName = name of the curve to be printed, csSig = color space signature of the LUT data, nIndex = the channel number of color space
Reimplemented from CIccCurve.
{
  icChar buf[128], *ptr;
  if (!m_nSize) {
    sprintf(buf, "BEGIN_CURVE %s\n", szName);
    sDescription += buf;
    sDescription += "Y = X\n";
  }
  else if (m_nSize==1) {
    icFloatNumber dGamma = (icFloatNumber)(m_Curve[0] * 256.0);
    sprintf(buf, "BEGIN_CURVE %s\n", szName);
    sDescription += buf;
    sprintf(buf, "Y = X ^ %.4lf\n", dGamma);
    sDescription += buf;
  }
  else {
    int i;
    sprintf(buf, "BEGIN_LUT %s 1 1\n", szName);
    if (nVerboseness > 75) {
      sDescription += buf;
      sDescription += "IN OUT\n";
      sDescription.reserve(sDescription.size() + m_nSize * 20);
      for (i=0; i<(int)m_nSize; i++) {
        ptr = buf;
        icColorValue(buf, (icFloatNumber)i/(m_nSize-1), csSig, nIndex);
        ptr += strlen(buf);
        strcpy(ptr, " ");
        ptr ++;
        icColorValue(ptr, m_Curve[i], csSig, nIndex);
        ptr += strlen(ptr);
        strcpy(ptr, "\n");
        sDescription += buf;
      }
    }
  }
}
References icColorValue(), CIccTagCurve::m_Curve, and CIccTagCurve::m_nSize.
Find() [1/2]
icFloatNumber CIccCurve::Find (icFloatNumber v) inline inherited
{ return Find(v, 0, Apply(0), 1.0, Apply(1.0)); }
References CIccCurve::Apply(), and CIccCurve::Find().
Find() [2/2]
icFloatNumber CIccCurve::Find (icFloatNumber v, icFloatNumber p0, icFloatNumber v0, icFloatNumber p1, icFloatNumber v1) protected inherited
Name: CIccCurve::Find
Purpose: Read in the tag contents into a data block
Args: v = index to be searched, v0 = index less than/equal to v, p0 = the value at index v0, v1 = index greater than/equal to v, p1 = value at index v1
Return: The value at the requested index
{
  if (v<=v0)
    return p0;
  if (v>=v1)
    return p1;
  if (p1-p0 <= 0.00001) {
    icFloatNumber d0 = (icFloatNumber)fabs(v-v0);
    icFloatNumber d1 = (icFloatNumber)fabs(v1-v);
    if (d0<d1)
      return p0;
    return p1;
  }
  icFloatNumber np = (icFloatNumber)((p0 + p1)/2.0);
  icFloatNumber nv = Apply(np);
  if (v<=nv) {
    return Find(v, p0, v0, np, nv);
  }
  return Find(v, np, nv, p1, v1);
}
References CIccCurve::Apply(), and CIccCurve::Find().
Referenced by CIccCurve::Find(), and CIccCurve::Find().
GetClassName()
virtual const char * CIccTagXmlCurve::GetClassName () const inline virtual
Reimplemented from CIccTagCurve.
{return "CIccTagXmlCurve"; }
GetData()
icFloatNumber * CIccTagCurve::GetData (icUInt32Number index) inline inherited
{return &m_Curve[index];}
References CIccTagCurve::m_Curve.
Referenced by ParseXml().
GetExtClassName()
virtual const char * CIccTagXml::GetExtClassName () const inline virtual inherited
Implements IIccExtensionTag.
{ return "CIccTagXml"; }
Referenced by icProfDescToXml(), and icXmlParseProfDesc().
GetExtDerivedClassName()
virtual const char * CIccCurveXml::GetExtDerivedClassName () const inline virtual inherited
Reimplemented from CIccTagXml.
{return "CIccCurveXml"; }
GetExtension()
virtual IIccExtensionTag * CIccTagXmlCurve::GetExtension () inline virtual
Reimplemented from CIccTag.
{return this; }
GetSize()
icUInt32Number CIccTagCurve::GetSize () const inline inherited
{ return m_nSize; }
References CIccTagCurve::m_nSize.
Referenced by CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccTagLut8::Write(), and CIccTagLut16::Write().
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagCurve::GetType () const inline virtual inherited
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigCurveType; }
References icSigCurveType.
Referenced by CIccTagCurve::Write().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsIdentity()
bool CIccTagCurve::IsIdentity () virtual inherited
Name: CIccTagCurve::IsIdentity
Purpose: Checks if this is an identity curve.
Return: true if the curve is an identity
Reimplemented from CIccCurve.
{
  if (!m_nSize) {
    return true;
  }
  if (m_nSize==1) {
    return  IsUnity(icFloatNumber(m_Curve[0]*65535.0/256.0));
  }
  icUInt32Number i;
  for (i=0; i<m_nSize; i++) {
    if (fabs(m_Curve[i]-((icFloatNumber)i/(icFloatNumber)m_nMaxIndex))>VERYSMALLNUM) {
      return false;
    }
  }
  return true;
}
References IsUnity(), CIccTagCurve::m_Curve, CIccTagCurve::m_nMaxIndex, CIccTagCurve::m_nSize, and VERYSMALLNUM.
Referenced by ToXml().
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
virtual CIccTag * CIccTagCurve::NewCopy () const inline virtual inherited
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccCurve.
{ return new CIccTagCurve(*this);}
References CIccTagCurve::CIccTagCurve().
operator[]()
icFloatNumber & CIccTagCurve::operator[] (icUInt32Number index) inline inherited
{return m_Curve[index];}
References CIccTagCurve::m_Curve.
Referenced by main(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::Write(), and CIccTagLut16::Write().
ParseXml() [1/2]
bool CIccTagXmlCurve::ParseXml (xmlNode * pNode, icConvertType nType, std::string & parseStr) virtual
Implements CIccCurveXml.
{
  xmlNode *pCurveNode;
  pCurveNode = icXmlFindNode(pNode, "Curve");
  if(pCurveNode){
    const char *filename = icXmlAttrValue(pCurveNode, "File");
    // file exists
    if (filename[0]) {
      CIccIO *file = IccOpenFileIO(filename, "rb");
      if (!file){
        parseStr += "Error! - File '";
        parseStr += filename;
        parseStr +="' not found.\n";
        delete file;
        return false;
      }
      const char *format = icXmlAttrValue(pCurveNode, "Format");
      // format is text
      if (!strcmp(format, "text")) {
        icUInt32Number num = file->GetLength();
        char *buf = (char *) new char[num];
        if (!buf) {
          perror("Memory Error");
          parseStr += "'";
          parseStr += filename;
          parseStr += "' may not be a valid text file.\n";
          delete [] buf;
          delete file;
          return false;
        }
        if (file->Read8(buf, num) !=num) {
          perror("Read-File Error");
          parseStr += "'";
          parseStr += filename;
          parseStr += "' may not be a valid text file.\n";
          delete [] buf;
          delete file;
          return false;
        }
        // lut8type
        if (nType == icConvert8Bit) {
          CIccUInt8Array data;
          //if (!data.ParseTextArray(buf)) {
          if (!data.ParseTextArrayNum(buf, num, parseStr)){
            parseStr += "File '";
            parseStr += filename;
            parseStr += "' is not a valid text file.\n";
            SetSize(0);
            delete [] buf;
            delete file;
            return false;
          }
          else {
            SetSize(data.GetSize());
            icUInt8Number *src = data.GetBuf();
            icFloatNumber *dst = GetData(0);
            icUInt32Number i;
            for (i=0; i<data.GetSize(); i++) {
              *dst = (icFloatNumber)(*src) / 255.0f;
              dst++;
              src++;
            }
            //if (i!=256) {
            //printf("Error! - Input/Output table does not have 256 entries.\n");
            //SetSize(0);
            //return false;
            //}
            delete[] buf;
            delete file;
            return true;
          }
        }
        //lut16type
        else if (nType == icConvert16Bit || nType == icConvertVariable) {
          CIccUInt16Array data;
          //if (!data.ParseTextArray(buf)) {
          if (!data.ParseTextArrayNum(buf, num, parseStr)){
            parseStr += "File '";
            parseStr += filename;
            parseStr += "' is not a valid text file.\n";
            SetSize(0);
            delete[] buf;
            delete file;
            return false;
          }
          else {
            SetSize(data.GetSize());
            icUInt16Number *src = data.GetBuf();
            icFloatNumber *dst = GetData(0);
            icUInt32Number i;
            for (i=0; i<data.GetSize(); i++) {
              *dst = (icFloatNumber)(*src) / 65535.0f;
              dst++;
              src++;
            }
          }
          delete[] buf;
          delete file;
          return true;
        }
        //float type
        else if (nType == icConvertFloat){
          CIccFloatArray data;
          //if (!data.ParseTextArray(buf)) {
          if (!data.ParseTextArrayNum(buf, num, parseStr)){
            parseStr += "File '";
            parseStr += filename;
            parseStr += "' is not a valid text file.\n";
            SetSize(0);
            delete[] buf;
            delete file;
            return false;
          }
          else {
            SetSize(data.GetSize());
            icFloatNumber *src = data.GetBuf();
            icFloatNumber *dst = GetData(0);
            icUInt32Number i;
            for (i=0; i<data.GetSize(); i++) {
              *dst = *src;
              dst++;
              src++;
            }
          }
          delete[] buf;
          delete file;
          return true;
        }
        else {
          delete[] buf;
          delete file;
          return false;
        }
      }
      // format is binary
      else if (!strcmp(format, "binary")) {
        const char *order = icXmlAttrValue(pCurveNode, "Endian");
        bool little_endian = !strcmp(order, "little");
        if (nType == icConvert8Bit){
          icUInt32Number num = file->GetLength();
          icUInt8Number value;
          SetSize(num);
          icFloatNumber *dst =  GetData(0);
          icUInt32Number i;
          for (i=0; i<num; i++) {
            if (!file->Read8(&value)) {
              perror("Read-File Error");
              parseStr += "'";
              parseStr += filename;
              parseStr += "' may not be a valid binary file.\n";
              delete file;
              return false;
            }
            *dst++ = (icFloatNumber)value / 255.0f;
          }
          delete file;
          return true;
        }
        else if (nType == icConvert16Bit || nType == icConvertVariable){
          icUInt32Number num = file->GetLength() / sizeof(icUInt16Number);
          icUInt16Number value;
          icUInt8Number *ptr = (icUInt8Number*)&value;
          SetSize(num);
          icFloatNumber *dst = GetData(0);
          icUInt32Number i;
          for (i=0; i<num; i++) {
            if (!file->Read16(&value)) {  //this assumes data is big endian
              perror("Read-File Error");
              parseStr += "'";
              parseStr += filename;
              parseStr += "' may not be a valid binary file.\n";
              delete file;
              return false;
            }
#ifdef ICC_BYTE_ORDER_LITTLE_ENDIAN
            if (little_endian) {
#else
            if (!little_endian) {
#endif
              icUInt8Number t = ptr[0];
              ptr[0] = ptr[1];
              ptr[1] = t;
            }
            *dst++ = (icFloatNumber)value / 65535.0f;
          }
          delete file;
          return true;
        }
        else if (nType == icConvertFloat) {
          icUInt32Number num = file->GetLength()/sizeof(icFloat32Number);
          icFloat32Number value;
          icUInt8Number *ptr = (icUInt8Number*)&value;
          SetSize(num);
          icFloatNumber *dst = GetData(0);
          icUInt32Number i;
          for (i=0; i<num; i++) {
            if (!file->ReadFloat32Float(&value)) { //assumes data is big endian
              perror("Read-File Error");
              parseStr += "'";
              parseStr += filename;
              parseStr += "' may not be a valid binary file.\n";
              delete file;
              return false;
            }
#ifdef ICC_BYTE_ORDER_LITTLE_ENDIAN
            if (little_endian) {
#else
            if (!little_endian) {
#endif
              icUInt8Number tmp;
              tmp = ptr[0]; ptr[0] = ptr[3]; ptr[3] = tmp;
              tmp = ptr[1]; ptr[1] = ptr[2]; ptr[2] = tmp;
            }
            *dst++ = value;
          }
          delete file;
          return true;
        }
        else { //not 8bit/16bit/float
          delete file;
          return false;
        }
      }
      else {//not text/binary
        delete file;
        return false;
      }
    }
    // no file
    else{
      if (nType == icConvert8Bit){
        CIccUInt8Array data;
        if (!data.ParseArray(pCurveNode->children)) {
          const char *szSize = icXmlAttrValue(pCurveNode, "IdentitySize");
          if (szSize && *szSize) {
            icUInt32Number nSize = (icUInt32Number)atol(szSize);
            SetSize(nSize);
            if (m_nSize == nSize) {
              icUInt32Number j;
              icFloatNumber *dst = GetData(0);
              for (j=0; j<nSize; j++) {
                *dst = (icFloatNumber)(j) / (icFloatNumber)(nSize-1);
                dst++;
              }
            }
            else
              return false;
          }
          else { //Identity curve with size=0
            SetSize(0);
          }
        }
        else {
          SetSize(data.GetSize());
          icUInt32Number j;
          icUInt8Number *src = data.GetBuf();
          icFloatNumber *dst = GetData(0);
          for (j=0; j<data.GetSize(); j++) {
            *dst = (icFloatNumber)(*src) / 255.0f;
            dst++;
            src++;
          }
          //if (j!=256) {
          //printf("Error! - Input/Output table does not have 256 entries.\n");
          //SetSize(0);
          //return false;
          //}
        }
        return true;
      }
      else if (nType == icConvert16Bit || nType == icConvertVariable){
        CIccUInt16Array data;
        if (!data.ParseArray(pCurveNode->children)) {
          const char *szSize = icXmlAttrValue(pCurveNode, "IdentitySize");
          if (szSize && *szSize) {
            icUInt32Number nSize = (icUInt32Number)atol(szSize);
            SetSize(nSize);
            if (m_nSize == nSize) {
              icUInt32Number j;
              icFloatNumber *dst = GetData(0);
              for (j=0; j<nSize; j++) {
                *dst = (icFloatNumber)(j) / (icFloatNumber)(nSize-1);
                dst++;
              }
            }
            else
              return false;
          }
          else { //Identity curve with size=0
            SetSize(0);
          }
        }
        else {
          SetSize(data.GetSize());
          icUInt32Number j;
          icUInt16Number *src = data.GetBuf();
          icFloatNumber *dst = GetData(0);
          for (j=0; j<data.GetSize(); j++) {
            *dst = (icFloatNumber)(*src) / 65535.0f;
            dst++;
            src++;
          }
        }
        return true;
      }
      else if (nType == icConvertFloat){
        CIccFloatArray data;
        if (!data.ParseArray(pCurveNode->children)) {
          const char *szSize = icXmlAttrValue(pCurveNode, "IdentitySize");
          if (szSize && *szSize) {
            icUInt32Number nSize = (icUInt32Number)atol(szSize);
            SetSize(nSize);
            if (m_nSize == nSize) {
              icUInt32Number j;
              icFloatNumber *dst = GetData(0);
              for (j=0; j<nSize; j++) {
                *dst = (icFloatNumber)(j) / (icFloatNumber)(nSize-1);
                dst++;
              }
            }
            else
              return false;
          }
          else { //Identity curve with size=0
            SetSize(0);
          }
        }
        else {
          SetSize(data.GetSize());
          icUInt32Number j;
          icFloatNumber *src = data.GetBuf();
          icFloatNumber *dst = GetData(0);
          for (j=0; j<data.GetSize(); j++) {
            *dst = *src;
            dst++;
            src++;
          }
        }
        return true;
      }
      // unsupported encoding
      else
        return false;
    }
  }
  return false;
}
References CIccXmlArrayType< T, Tsig >::GetBuf(), CIccTagCurve::GetData(), CIccIO::GetLength(), CIccXmlArrayType< T, Tsig >::GetSize(), icConvert16Bit, icConvert8Bit, icConvertFloat, icConvertVariable, IccOpenFileIO(), icXmlAttrValue(), icXmlFindNode(), CIccTagCurve::m_nSize, CIccXmlArrayType< T, Tsig >::ParseArray(), CIccXmlArrayType< T, Tsig >::ParseTextArrayNum(), CIccIO::Read16(), CIccIO::Read8(), CIccIO::ReadFloat32Float(), and CIccTagCurve::SetSize().
Referenced by ParseXml().
ParseXml() [2/2]
bool CIccTagXmlCurve::ParseXml (xmlNode * pNode, std::string & parseStr) virtual
Implements CIccTagXml.
{
  return ParseXml(pNode, icConvert16Bit, parseStr);
}
References icConvert16Bit, and ParseXml().
Read() [1/2]
bool CIccTagCurve::Read (icUInt32Number size, CIccIO * pIO) virtual inherited
Name: CIccTagCurve::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  icUInt32Number headerSize = sizeof(icTagTypeSignature) +
                              sizeof(icUInt32Number) +
                              sizeof(icUInt32Number);
  if (headerSize > size)
    return false;
  if (!pIO) {
    return false;
  }
  if (!pIO->Read32(&sig))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  icUInt32Number nSize;
  if (!pIO->Read32(&nSize))
    return false;
  if (headerSize + (icUInt64Number)nSize * sizeof(icUInt16Number) > size)
    return false;
  if (!SetSize(nSize, icInitNone))
    return false;
  if (m_nSize) {
    if (pIO->ReadUInt16Float(m_Curve, m_nSize)!=(icInt32Number)m_nSize)
      return false;
  }
  return true;
}
References icInitNone, CIccTagCurve::m_Curve, CIccTag::m_nReserved, CIccTagCurve::m_nSize, CIccIO::Read32(), CIccIO::ReadUInt16Float(), and CIccTagCurve::SetSize().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
SetGamma()
bool CIccTagCurve::SetGamma (icFloatNumber gamma) inherited
Name: refIccMAX::CIccTagCurve::SetGamma
Purpose: Set the curve with a single gamma value.
Args: gamma - gamma value to use
{
  if (!SetSize(1, icInitNone))
    return false;
  icInt16Number whole = (icInt16Number)gamma;
  icFloatNumber frac = gamma - (icFloatNumber)whole;
  m_Curve[0] = (icFloatNumber)((whole * 256) + (frac*256.0)) / (icFloatNumber)65535.0;
  return true;
}
References icInitNone, CIccTagCurve::m_Curve, and CIccTagCurve::SetSize().
SetSize()
bool CIccTagCurve::SetSize (icUInt32Number nSize, icTagCurveSizeInit nSizeOpt = icInitZero) inherited
Name: CIccTagCurve::SetSize
Purpose: Sets the size of the curve array.
Args: nSize - number of entries in the curve, nSizeOpt - flag to zero newly formed values
{
  if (nSize==m_nSize)
    return true;
  if (!nSize && m_Curve) {
    free(m_Curve);
    m_Curve = NULL;
  }
  else {
    if (!m_Curve)
      m_Curve = (icFloatNumber*)malloc(nSize*sizeof(icFloatNumber));
    else
      m_Curve = (icFloatNumber*)icRealloc(m_Curve, nSize*sizeof(icFloatNumber));
    if (!m_Curve) {
      m_nSize = 0;
      return false;
    }
    switch (nSizeOpt) {
    case icInitNone:
    default:
      break;
    case icInitZero:
      if (m_nSize < nSize) {
        memset(&m_Curve[m_nSize], 0, (nSize-m_nSize)*sizeof(icFloatNumber));
      }
      break;
    case icInitIdentity:
      if (nSize>1) {
        icUInt32Number i;
        icFloatNumber last = (icFloatNumber)(nSize-1);
        for (i=0; i<nSize; i++) {
          m_Curve[i] = (icFloatNumber)i/last;
        }
      }
      else if (nSize==1) {
        //Encode a gamma 1.0 u8Fixed8Number converted to 16 bit as a 0.0 to 1.0 float
        m_Curve[0] = (icFloatNumber)(0x0100) / (icFloatNumber)65535.0;
      }
      break;
    }
  }
  m_nSize = nSize;
  m_nMaxIndex = (icUInt16Number)(nSize - 1);
  return true;
}
References icInitIdentity, icInitNone, icInitZero, icRealloc(), CIccTagCurve::m_Curve, CIccTagCurve::m_nMaxIndex, and CIccTagCurve::m_nSize.
Referenced by ParseXml(), CIccTagCurve::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccTagCurve::SetGamma().
ToXml() [1/2]
bool CIccTagXmlCurve::ToXml (std::string & xml, icConvertType nType, std::string blanks = "") virtual
Implements CIccCurveXml.
{
  char buf[40];
  int i;
  if (!m_nSize) {
    xml += blanks + "<Curve/>\n";
  }
  else if (IsIdentity()) {
    xml += blanks + "<Curve IdentitySize=\"";
    sprintf(buf, "%d", m_nSize);
    xml += buf;
    xml += "\"/>\n";
  }
  else if (nType==icConvert8Bit) {
    xml += blanks + "<Curve>\n" + blanks;
    for (i=0; i<(int)m_nSize; i++) {
      if ( i && !(i%16)) {
        xml += "\n";
        xml += blanks;
      }
      sprintf(buf, " %3u", (int)(m_Curve[i] * 255.0 + 0.5));
      xml += buf;
    }
    xml += "\n";
    xml += blanks + "</Curve>\n";
  }
  else if (nType==icConvert16Bit || nType==icConvertVariable) {
    xml += blanks + "<Curve>\n" + blanks;
    for (i=0; i<(int)m_nSize; i++) {
      if (i && !(i%16)) {
        xml += "\n";
        xml += blanks + " ";
      }
      sprintf(buf, " %5u", (int)(m_Curve[i] * 65535.0 + 0.5));
      xml += buf;
    }
    xml += "\n";
    xml += blanks + "</Curve>\n";
  }
  else if (nType==icConvertFloat) {
    xml += blanks + "<Curve>\n" + blanks + "  ";
    for (i=0; i<(int)m_nSize; i++) {
      if (i && !(i%16)) {
        xml += "\n";
        xml += blanks + " ";
      }
      sprintf(buf, " %13.8f", m_Curve[i]);
      xml += buf;
    }
    xml += "\n";
    xml += blanks + "</Curve>\n";
  }
  else
    return false;
  return true;
}
References icConvert16Bit, icConvert8Bit, icConvertFloat, icConvertVariable, CIccTagCurve::IsIdentity(), CIccTagCurve::m_Curve, and CIccTagCurve::m_nSize.
Referenced by ToXml().
ToXml() [2/2]
bool CIccTagXmlCurve::ToXml (std::string & xml, std::string blanks = "") virtual
Implements CIccTagXml.
{
  return ToXml(xml, icConvert16Bit, blanks);
}
References icConvert16Bit, and ToXml().
Validate()
icValidateStatus CIccTagCurve::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual inherited
Name: CIccTagCurve::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  icSignature sig = icGetFirstSigPathSig(sigPath);
  if (sig==icSigBlueTRCTag || sig==icSigRedTRCTag || sig==icSigGreenTRCTag || sig==icSigGrayTRCTag) {
    if (m_nSize>1) {
      if (m_Curve) {
        if (m_Curve[0]>0.0 || m_Curve[m_nSize-1]<1.0) {
          sReport += icMsgValidateWarning;
          sReport += sSigPathName;
          sReport += " - Curve cannot be accurately inverted.\n";
          rv = icMaxStatus(rv, icValidateWarning);
        }
      }
    }
  }
  return rv;
}
References CIccInfo::GetSigPathName(), icGetFirstSigPathSig(), icMaxStatus(), icMsgValidateWarning, icSigBlueTRCTag, icSigGrayTRCTag, icSigGreenTRCTag, icSigRedTRCTag, icValidateWarning, CIccTagCurve::m_Curve, CIccTagCurve::m_nSize, and CIccTag::Validate().
Write()
bool CIccTagCurve::Write (CIccIO * pIO) virtual inherited
Name: CIccTagCurve::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  if (!pIO)
    return false;
  if (!pIO->Write32(&sig))
    return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  if (!pIO->Write32(&m_nSize))
    return false;
  if (m_nSize)
    if (pIO->WriteUInt16Float(m_Curve, m_nSize)!=(icInt32Number)m_nSize)
      return false;
  pIO->Align32();
  return true;
}
References CIccIO::Align32(), CIccTagCurve::GetType(), CIccTagCurve::m_Curve, CIccTag::m_nReserved, CIccTagCurve::m_nSize, CIccIO::Write32(), and CIccIO::WriteUInt16Float().
Field Documentation
m_Curve
icFloatNumber* CIccTagCurve::m_Curve protected inherited
Referenced by CIccTagCurve::CIccTagCurve(), CIccTagCurve::CIccTagCurve(), CIccTagCurve::~CIccTagCurve(), CIccTagCurve::Apply(), CIccTagCurve::Describe(), CIccTagCurve::DumpLut(), CIccTagCurve::GetData(), CIccTagCurve::IsIdentity(), CIccTagCurve::operator=(), CIccTagCurve::operator[](), CIccTagCurve::Read(), CIccTagCurve::SetGamma(), CIccTagCurve::SetSize(), ToXml(), CIccTagCurve::Validate(), and CIccTagCurve::Write().
m_nMaxIndex
icUInt16Number CIccTagCurve::m_nMaxIndex protected inherited
Referenced by CIccTagCurve::CIccTagCurve(), CIccTagCurve::Apply(), CIccTagCurve::Begin(), CIccTagCurve::IsIdentity(), CIccTagCurve::operator=(), and CIccTagCurve::SetSize().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_nSize
icUInt32Number CIccTagCurve::m_nSize protected inherited
Referenced by CIccTagCurve::CIccTagCurve(), CIccTagCurve::CIccTagCurve(), CIccTagCurve::Apply(), CIccTagCurve::Begin(), CIccTagCurve::Describe(), CIccTagCurve::DumpLut(), CIccTagCurve::GetSize(), CIccTagCurve::IsIdentity(), CIccTagCurve::operator=(), ParseXml(), CIccTagCurve::Read(), CIccTagCurve::SetSize(), ToXml(), CIccTagCurve::Validate(), and CIccTagCurve::Write().
The documentation for this class was generated from the following files:
IccXML/IccLibXML/IccTagXml.h
IccXML/IccLibXML/IccTagXml.cpp