iccDEV: CIccTagZipXml Class Reference
CIccTagZipXml Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagZipXml ()
CIccTagZipXml (const CIccTagZipXml &ITT)
virtual ~CIccTagZipXml ()
icUChar * AllocBuffer (icUInt32Number nSize)
icUInt32Number BufferSize () const
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
icUChar * GetBuffer () const
virtual const icChar * GetClassName () const
virtual IIccExtensionTag * GetExtension ()
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual bool GetText (std::string &str) const
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
CIccTagZipXml & operator= (const CIccTagZipXml &TextTag)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
bool SetText (const icChar *szText)
virtual bool SetText (const icUChar *szText)
bool SetText (const icUChar16 *szText)
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
Protected Attributes
icUInt32Number m_nBufSize
icUChar * m_pZipBuf
Detailed Description
Class: CIccTagZipXml()
Purpose: The zipXMLType ICC tag
Constructor & Destructor Documentation
CIccTagZipXml() [1/2]
CIccTagZipXml::CIccTagZipXml () inline
: CIccTagZipUtf8Text() {}
References CIccTagZipUtf8Text::CIccTagZipUtf8Text().
Referenced by CIccTagXmlZipXml::CIccTagXmlZipXml().
~CIccTagZipXml()
virtual CIccTagZipXml::~CIccTagZipXml () inline virtual
{}
CIccTagZipXml() [2/2]
CIccTagZipXml::CIccTagZipXml (const CIccTagZipXml & ITT) inline
: CIccTagZipUtf8Text(ITT) {}
References CIccTagZipUtf8Text::CIccTagZipUtf8Text().
Referenced by CIccTagXmlZipXml::CIccTagXmlZipXml(), and NewCopy().
Member Function Documentation
AllocBuffer()
icUChar * CIccTagZipUtf8Text::AllocBuffer (icUInt32Number nSize) inherited
Name: CIccTagZipUtf8Text::AllocBuffer
Purpose: This function allocates room and returns pointer to data buffer to put string into
Args: nSize = Requested size of data buffer.
Return: The character buffer array
{
  if (m_nBufSize != nSize) {
    if (!nSize) {
      if (m_pZipBuf) {
        free(m_pZipBuf);
        m_pZipBuf = NULL;
      }
      m_nBufSize = nSize;
      return NULL;
    }
    if (!m_nBufSize)
      m_pZipBuf = (icUChar*)malloc(nSize);
    else
      m_pZipBuf = (icUChar*)icRealloc(m_pZipBuf, nSize);
    m_nBufSize = nSize;
  }
  return m_pZipBuf;
}
References icRealloc(), CIccTagZipUtf8Text::m_nBufSize, and CIccTagZipUtf8Text::m_pZipBuf.
Referenced by CIccTagZipUtf8Text::CIccTagZipUtf8Text(), CIccTagZipUtf8Text::operator=(), CIccTagXmlZipUtf8Text::ParseXml(), CIccTagXmlZipXml::ParseXml(), and CIccTagZipUtf8Text::Read().
BufferSize()
icUInt32Number CIccTagZipUtf8Text::BufferSize () const inline inherited
{ return m_nBufSize; }
References CIccTagZipUtf8Text::m_nBufSize.
Referenced by CIccTagZipUtf8Text::CIccTagZipUtf8Text(), and CIccTagZipUtf8Text::operator=().
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagZipUtf8Text::Describe (std::string & sDescription, int nVerboseness) virtual inherited
Name: CIccTagZipUtf8Text::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  std::string str;
#ifdef ICC_USE_ZLIB
  if (!GetText(str)) {
    sDescription += "Error! - Unable to decompress text data.\n";
  }
  else if (m_nBufSize > 4 && !memcmp(m_pZipBuf, icFaultyXmlZipData, 4)) {
    sDescription += "Warning! - Correcting for improperly encoded ";
    sDescription += CIccTagCreator::GetTagTypeSigName(GetType());
    sDescription += " tag.\n\n";
  }
  sDescription += "ZLib Compressed String=\"";
  sDescription += str;
  sDescription += "\"\n";
#else
  char size[30];
  sprintf(size, "%d", m_nBufSize);
  sDescription += "BEGIN_COMPESSED_DATA[\"";
  sDescription += size;
  sDescription += "]\n";
  if (m_nBufSize) {
    icMemDump(str, m_pZipBuf, m_nBufSize);
    sDescription += str;
    sDescription += "\n";
  }
  sDescription += "END_COMPRESSED_DATA\n";
#endif
}
References icMemDump(), CIccTagZipUtf8Text::m_nBufSize, and CIccTagZipUtf8Text::m_pZipBuf.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
GetBuffer()
icUChar * CIccTagZipUtf8Text::GetBuffer () const inline inherited
{ return m_pZipBuf; }
References CIccTagZipUtf8Text::m_pZipBuf.
Referenced by CIccTagZipUtf8Text::CIccTagZipUtf8Text(), and CIccTagZipUtf8Text::operator=().
GetClassName()
virtual const icChar * CIccTagZipXml::GetClassName () const inline virtual
Reimplemented from CIccTagZipUtf8Text.
Reimplemented in CIccTagXmlZipXml.
{ return "CIccZipXML"; }
GetExtension()
virtual IIccExtensionTag * CIccTag::GetExtension () inline virtual inherited
Reimplemented in CIccTagXmlUnknown, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, CIccTagXmlSignature, CIccTagXmlNamedColor2, CIccTagXmlXYZ, CIccTagXmlChromaticity, CIccTagXmlCicp, CIccTagXmlSparseMatrixArray, CIccTagXmlFixedNum< T, Tsig >, CIccTagXmlNum< T, A, Tsig >, CIccTagXmlFloatNum< T, A, Tsig >, CIccTagXmlMeasurement, CIccTagXmlMultiLocalizedUnicode, CIccTagXmlTagData, CIccTagXmlDateTime, CIccTagXmlColorantOrder, CIccTagXmlColorantTable, CIccTagXmlViewingConditions, CIccTagXmlSpectralDataInfo, CIccTagXmlSpectralViewingConditions, CIccTagXmlProfileSeqDesc, CIccTagXmlResponseCurveSet16, CIccTagXmlCurve, CIccTagXmlParametricCurve, CIccTagXmlSegmentedCurve, CIccTagXmlLutAtoB, CIccTagXmlLutBtoA, CIccTagXmlLut8, CIccTagXmlLut16, CIccTagXmlMultiProcessElement, CIccTagXmlProfileSequenceId, CIccTagXmlDict, CIccTagXmlStruct, CIccTagXmlArray, CIccTagXmlGamutBoundaryDesc, CIccTagXmlEmbeddedHeightImage, CIccTagXmlEmbeddedNormalImage, and CIccTagXmlEmbeddedProfile.
{return NULL;}
Referenced by icCurvesFromXml(), icCurvesToXml(), icProfDescToXml(), icXmlParseProfDesc(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeXmlTintArray::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetText()
bool CIccTagZipUtf8Text::GetText (std::string & str) const virtual inherited
Name: CIccTagZipUtf8Text::GetText
Purpose: Allows text data associated with the tag to be set.
Args: text - string to put uncompressed text into
{
#ifndef ICC_USE_ZLIB
  str="";
  return false;
#else
  int zstat;
  z_stream zstr;
  memset(&zstr, 0, sizeof(zstr));
  unsigned char buf[32767] = { 0 };
  zstat = inflateInit(&zstr);
  if (zstat != Z_OK) {
    return false;
  }
  zstat = inflateReset(&zstr);
  if (zstat != Z_OK) {
    return false;
  }
  if (m_nBufSize > 4 && !memcmp(m_pZipBuf, icFaultyXmlZipData, 4)) {
    //xrite creates invalid zipXMLType tags
    zstr.next_in = m_pZipBuf+4;
    zstr.avail_in = m_nBufSize-4;
  }
  else {
    zstr.next_in = m_pZipBuf;
    zstr.avail_in = m_nBufSize;
  }
  do {
    unsigned int i, n;
    zstr.next_out = buf;
    zstr.avail_out = sizeof(buf);
    zstat = inflate(&zstr, Z_SYNC_FLUSH);
    if (zstat != Z_OK && zstat != Z_STREAM_END) {
      inflateEnd(&zstr);
      return false;
    }
    n = sizeof(buf) - zstr.avail_out;
    for (i = 0; i < n; i++) {
      str += buf[i];
    }
  } while (zstat != Z_STREAM_END);
  inflateEnd(&zstr);
  return true;
#endif
}
Referenced by icGetTagText().
GetType()
virtual icTagTypeSignature CIccTagZipXml::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTagZipUtf8Text.
{ return icSigZipXmlType; }
References icSigZipXmlType.
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
virtual CIccTag * CIccTagZipXml::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTagZipUtf8Text.
Reimplemented in CIccTagXmlZipXml.
{return new CIccTagZipXml(*this);}
References CIccTagZipXml().
operator=()
CIccTagZipXml & CIccTagZipXml::operator= (const CIccTagZipXml & TextTag) inline
{CIccTagZipUtf8Text::operator=(TextTag); return *this;}
References CIccTagZipUtf8Text::operator=().
Read() [1/2]
bool CIccTagZipUtf8Text::Read (icUInt32Number size, CIccIO * pIO) virtual inherited
Name: CIccTagZipUtf8Text::Read
Purpose: Read in a text type tag into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  if (size<sizeof(icTagTypeSignature) || !pIO) {
    AllocBuffer(0);
    return false;
  }
  if (!pIO->Read32(&sig))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  icUInt32Number nSize = size - sizeof(icTagTypeSignature) - sizeof(icUInt32Number);
  icUChar *pBuf = AllocBuffer(nSize);
  if (m_nBufSize && pBuf) {
    if (pIO->Read8(pBuf, m_nBufSize) != (icInt32Number)m_nBufSize) {
      return false;
    }
  }
  return true;
}
References CIccTagZipUtf8Text::AllocBuffer(), CIccTagZipUtf8Text::m_nBufSize, CIccTag::m_nReserved, CIccIO::Read32(), and CIccIO::Read8().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
SetText() [1/3]
bool CIccTagZipUtf8Text::SetText (const icChar * szText) inline inherited
{ return SetText((icUChar*)szText); }
References CIccTagZipUtf8Text::SetText().
Referenced by CIccTagXmlZipUtf8Text::ParseXml(), CIccTagXmlZipXml::ParseXml(), and CIccTagZipUtf8Text::SetText().
SetText() [2/3]
bool CIccTagZipUtf8Text::SetText (const icUChar * szText) virtual inherited
Name: CIccTagZipUtf8Text::SetText
Purpose: Allows text data associated with the tag to be set.
Args: szText - zero terminated string to put in tag
{
#ifndef ICC_USE_ZLIB
  return false;
#else
  if (!szText)
    szText = (const icUChar*)"";
  icUInt32Number nSize = (icUInt32Number)strlen((const char*)szText) + 1;
  icUtf8Vector compress;
  int i;
  int zstat;
  z_stream zstr;
  unsigned char buf[32767];
  memset(&zstr, 0, sizeof(zstr));
  zstat = deflateInit(&zstr, Z_DEFAULT_COMPRESSION);
  if (zstat != Z_OK) {
    return false;
  }
  zstat = deflateReset(&zstr);
  zstr.next_in = (Bytef*)szText;
  zstr.avail_in = nSize;
  if (zstat != Z_OK) {
    return false;
  }
  do {
    int n;
    zstr.next_out = buf;
    zstr.avail_out = sizeof(buf);
    zstat = deflate(&zstr, Z_FINISH);
    if (zstat != Z_OK && zstat != Z_STREAM_END) {
      deflateEnd(&zstr);
      return false;
    }
    n = sizeof(buf) - zstr.avail_out;
    for (i = 0; i < n; i++) {
      compress.push_back(buf[i]);
    }
  } while (zstat != Z_STREAM_END);
  deflateEnd(&zstr);
  icUChar *pBuf = AllocBuffer((icUInt32Number)compress.size());
  if (pBuf) {
    for (i = 0; i < (int)m_nBufSize; i++) {
      pBuf[i] = compress[i];
}
  }
  return true;
#endif
}
Referenced by CIccTagZipUtf8Text::SetText(), and CIccTagZipUtf8Text::SetText().
SetText() [3/3]
bool CIccTagZipUtf8Text::SetText (const icUChar16 * szText) inherited
Name: CIccTagZipUtf8Text::SetText
Purpose: Allows text data associated with the tag to be set.
Args: szText - zero terminated string to put in tag
{
  if (!szText) {
    return SetText("");
  }
  icUtf8Vector text;
  icUInt32Number len;
  for (len=0; szText[len]; len++);
  icConvertUTF16toUTF8(szText, &szText[len], text, lenientConversion);
  return SetText((const icUChar*)&text[0]);
}
References icConvertUTF16toUTF8(), lenientConversion, CIccTagZipUtf8Text::SetText(), and CIccTagZipUtf8Text::SetText().
Validate()
icValidateStatus CIccTagZipUtf8Text::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual inherited
Name: CIccTagZipUtf8Text::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  if (!m_nBufSize) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " - Empty Tag.\n";
    rv = icMaxStatus(rv, icValidateWarning);
  }
  else {
#ifdef ICC_USE_ZLIB
    std::string sText;
    if (!GetText(sText)) {
      sReport += icMsgValidateNonCompliant;
      sReport += sSigPathName;
      sReport += " - Unable to get text for tag (possibly corrupt compressed data).\n";
      rv = icMaxStatus(rv, icValidateNonCompliant);
    }
    else if (m_nBufSize > 4 && !memcmp(m_pZipBuf, icFaultyXmlZipData, 4)) {
      sReport += icMsgValidateNonCompliant;
      sReport += sSigPathName;
      sReport += " - Improperly encoded ";
      sReport += CIccTagCreator::GetTagTypeSigName(GetType());
      sReport += " tag.\n";
      rv = icMaxStatus(rv, icValidateNonCompliant);
    }
#else
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " - Zip compression not supported by CMM - unable to validate text compression.\n";
    rv = icMaxStatus(rv, icValidateWarning);
#endif
  }
  return rv;
}
References CIccInfo::GetSigPathName(), icMaxStatus(), icMsgValidateWarning, icValidateWarning, CIccTagZipUtf8Text::m_nBufSize, and CIccTag::Validate().
Write()
bool CIccTagZipUtf8Text::Write (CIccIO * pIO) virtual inherited
Name: CIccTagZipUtf8Text::Write
Purpose: Write a text type tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  if (!pIO)
   return false;
  if (!pIO->Write32(&sig))
   return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  if (m_pZipBuf) {
    if (pIO->Write8(m_pZipBuf, m_nBufSize) != (icInt32Number)m_nBufSize)
      return false;
  }
  return true;
}
References CIccTagZipUtf8Text::GetType(), CIccTagZipUtf8Text::m_nBufSize, CIccTag::m_nReserved, CIccTagZipUtf8Text::m_pZipBuf, CIccIO::Write32(), and CIccIO::Write8().
Field Documentation
m_nBufSize
icUInt32Number CIccTagZipUtf8Text::m_nBufSize protected inherited
Referenced by CIccTagZipUtf8Text::CIccTagZipUtf8Text(), CIccTagZipUtf8Text::CIccTagZipUtf8Text(), CIccTagZipUtf8Text::AllocBuffer(), CIccTagZipUtf8Text::BufferSize(), CIccTagZipUtf8Text::Describe(), CIccTagZipUtf8Text::operator=(), CIccTagXmlZipUtf8Text::ParseXml(), CIccTagXmlZipXml::ParseXml(), CIccTagZipUtf8Text::Read(), CIccTagXmlZipUtf8Text::ToXml(), CIccTagXmlZipXml::ToXml(), CIccTagZipUtf8Text::Validate(), and CIccTagZipUtf8Text::Write().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_pZipBuf
icUChar* CIccTagZipUtf8Text::m_pZipBuf protected inherited
Referenced by CIccTagZipUtf8Text::CIccTagZipUtf8Text(), CIccTagZipUtf8Text::CIccTagZipUtf8Text(), CIccTagZipUtf8Text::~CIccTagZipUtf8Text(), CIccTagZipUtf8Text::AllocBuffer(), CIccTagZipUtf8Text::Describe(), CIccTagZipUtf8Text::GetBuffer(), CIccTagZipUtf8Text::operator=(), CIccTagXmlZipUtf8Text::ParseXml(), CIccTagXmlZipXml::ParseXml(), CIccTagXmlZipUtf8Text::ToXml(), CIccTagXmlZipXml::ToXml(), and CIccTagZipUtf8Text::Write().
The documentation for this class was generated from the following file:
IccProfLib/IccTagBasic.h