iccDEV: CIccTagColorantOrder Class Reference
CIccTagColorantOrder Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagColorantOrder (const CIccTagColorantOrder &ITCO)
CIccTagColorantOrder (int nsize=1)
virtual ~CIccTagColorantOrder ()
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
virtual const icChar * GetClassName () const
icUInt8Number * GetData (int index)
virtual IIccExtensionTag * GetExtension ()
icUInt32Number GetSize () const
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
CIccTagColorantOrder & operator= (const CIccTagColorantOrder &ColorantOrderTag)
icUInt8Number & operator[] (int index)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
bool SetSize (icUInt16Number nsize, bool bZeronew=true)
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
Protected Attributes
icUInt32Number m_nCount
icUInt8Number * m_pData
Detailed Description
Class: CIccTagColorantOrder
Purpose: Colorant Order Tag
Constructor & Destructor Documentation
CIccTagColorantOrder() [1/2]
CIccTagColorantOrder::CIccTagColorantOrder (int nsize = 1)
Name: CIccTagColorantOrder::CIccTagColorantOrder
Purpose: Constructor
Args: nSize = number of channels
{
  m_nCount = nsize;
  if (m_nCount <1)
    m_nCount = 1;
  m_pData = (icUInt8Number*)calloc(nsize, sizeof(icUInt8Number));
}
References m_nCount, and m_pData.
CIccTagColorantOrder() [2/2]
CIccTagColorantOrder::CIccTagColorantOrder (const CIccTagColorantOrder & ITCO)
Name: CIccTagColorantOrder::CIccTagColorantOrder
Purpose: Copy Constructor
Args: ITCO = The CIccTagColorantOrder object to be copied
{
  m_nCount = ITCO.m_nCount;
  m_pData = (icUInt8Number*)calloc(m_nCount, sizeof(icUInt8Number));
  memcpy(m_pData, ITCO.m_pData, sizeof(icUInt8Number)*m_nCount);
}
References m_nCount, and m_pData.
Referenced by NewCopy().
~CIccTagColorantOrder()
CIccTagColorantOrder::~CIccTagColorantOrder () virtual
Name: CIccTagColorantOrder::~CIccTagColorantOrder
Purpose: Destructor
{
  if (m_pData)
    free(m_pData);
}
References m_pData.
Member Function Documentation
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagColorantOrder::Describe (std::string & sDescription, int nVerboseness) virtual
Name: CIccTagColorantOrder::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  icChar buf[128];
  sprintf(buf, "Colorant Count : %u\n", m_nCount);
  sDescription += buf;
  sDescription += "Order of Colorants:\n";
  for (int i=0; i<(int)m_nCount; i++) {
    sprintf(buf, "%u\n", m_pData[i]);
    sDescription += buf;
  }
}
References m_nCount, and m_pData.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
GetClassName()
virtual const icChar * CIccTagColorantOrder::GetClassName () const inline virtual
Reimplemented from CIccTag.
Reimplemented in CIccTagXmlColorantOrder.
{ return "CIccTagColorantOrder"; }
GetData()
icUInt8Number * CIccTagColorantOrder::GetData (int index) inline
{ return &m_pData[index]; }
References m_pData.
GetExtension()
virtual IIccExtensionTag * CIccTag::GetExtension () inline virtual inherited
Reimplemented in CIccTagXmlUnknown, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, CIccTagXmlSignature, CIccTagXmlNamedColor2, CIccTagXmlXYZ, CIccTagXmlChromaticity, CIccTagXmlCicp, CIccTagXmlSparseMatrixArray, CIccTagXmlFixedNum< T, Tsig >, CIccTagXmlNum< T, A, Tsig >, CIccTagXmlFloatNum< T, A, Tsig >, CIccTagXmlMeasurement, CIccTagXmlMultiLocalizedUnicode, CIccTagXmlTagData, CIccTagXmlDateTime, CIccTagXmlColorantOrder, CIccTagXmlColorantTable, CIccTagXmlViewingConditions, CIccTagXmlSpectralDataInfo, CIccTagXmlSpectralViewingConditions, CIccTagXmlProfileSeqDesc, CIccTagXmlResponseCurveSet16, CIccTagXmlCurve, CIccTagXmlParametricCurve, CIccTagXmlSegmentedCurve, CIccTagXmlLutAtoB, CIccTagXmlLutBtoA, CIccTagXmlLut8, CIccTagXmlLut16, CIccTagXmlMultiProcessElement, CIccTagXmlProfileSequenceId, CIccTagXmlDict, CIccTagXmlStruct, CIccTagXmlArray, CIccTagXmlGamutBoundaryDesc, CIccTagXmlEmbeddedHeightImage, CIccTagXmlEmbeddedNormalImage, and CIccTagXmlEmbeddedProfile.
{return NULL;}
Referenced by icCurvesFromXml(), icCurvesToXml(), icProfDescToXml(), icXmlParseProfDesc(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeXmlTintArray::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
GetSize()
icUInt32Number CIccTagColorantOrder::GetSize () const inline
{return m_nCount;}
References m_nCount.
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagColorantOrder::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigColorantOrderType; }
References icSigColorantOrderType.
Referenced by Write().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
virtual CIccTag * CIccTagColorantOrder::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
{return new CIccTagColorantOrder(*this);}
References CIccTagColorantOrder().
operator=()
CIccTagColorantOrder & CIccTagColorantOrder::operator= (const CIccTagColorantOrder & ColorantOrderTag)
Name: CIccTagColorantOrder::operator=
Purpose: Copy Operator
Args: ColorantOrderTag = The CIccTagColorantOrder object to be copied
{
  if (&ColorantOrderTag == this)
    return *this;
  m_nCount = ColorantOrderTag.m_nCount;
  if (m_pData)
    free(m_pData);
  m_pData = (icUInt8Number*)calloc(m_nCount, sizeof(icUInt8Number));
  memcpy(m_pData, ColorantOrderTag.m_pData, sizeof(icUInt8Number)*m_nCount);
  return *this;
}
References m_nCount, and m_pData.
operator[]()
icUInt8Number & CIccTagColorantOrder::operator[] (int index) inline
{ return m_pData[index]; }
References m_pData.
Read() [1/2]
bool CIccTagColorantOrder::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagColorantOrder::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  icUInt32Number nCount;
  if (sizeof(icTagTypeSignature) +
      sizeof(icUInt32Number) +
      sizeof(icUInt32Number) > size)
    return false;
  if (!pIO) {
    return false;
  }
  if (!pIO->Read32(&sig))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  if (!pIO->Read32(&nCount))
    return false;
  icUInt32Number nNum = (size - 3*sizeof(icUInt32Number))/sizeof(icUInt8Number);
  if (nNum < nCount)
    return false;
  if (!SetSize((icUInt16Number)nCount))
    return false;
  if (pIO->Read8(&m_pData[0], m_nCount) != (icInt32Number)m_nCount)
    return false;
  return true;
}
References m_nCount, CIccTag::m_nReserved, m_pData, CIccIO::Read32(), CIccIO::Read8(), and SetSize().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
SetSize()
bool CIccTagColorantOrder::SetSize (icUInt16Number nSize, bool bZeroNew = true)
Name: CIccTagColorantOrder::SetSize
Purpose: Sets the size of the data array.
Args: nSize - number of channels, bZeroNew - flag to zero newly formed values
{
  if (m_nCount == nSize)
    return true;
  m_pData = (icUInt8Number*)icRealloc(m_pData, nSize*sizeof(icUInt8Number));
  if (!m_pData) {
    m_nCount = 0;
    return false;
  }
  if (bZeroNew && nSize > m_nCount) {
    memset(&m_pData[m_nCount], 0, (nSize - m_nCount)*sizeof(icUInt8Number));
  }
  m_nCount = nSize;
  return true;
}
References icRealloc(), m_nCount, and m_pData.
Referenced by CIccTagXmlColorantOrder::ParseXml(), and Read().
Validate()
icValidateStatus CIccTagColorantOrder::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagColorantOrder::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  if (!pProfile) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " - Tag validation incomplete: Pointer to profile unavailable.\n";
    rv = icMaxStatus(rv, icValidateWarning);
    return rv;
  }
  if (sigPath==icGetSigPath(icSigColorantTableTag)) {
    if (m_nCount != icGetSpaceSamples(pProfile->m_Header.colorSpace)) {
      sReport += icMsgValidateNonCompliant;
      sReport += sSigPathName;
      sReport += " - Incorrect number of colorants.\n";
      rv = icMaxStatus(rv, icValidateNonCompliant);
    }
  }
  else if (sigPath==icGetSigPath(icSigColorantTableOutTag)) {
    if (m_nCount != icGetSpaceSamples(pProfile->m_Header.pcs)) {
      sReport += icMsgValidateNonCompliant;
      sReport += sSigPathName;
      sReport += " - Incorrect number of colorants.\n";
      rv = icMaxStatus(rv, icValidateNonCompliant);
    }
  }
  else {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " - Unknown number of required colorants.\n";
    rv = icMaxStatus(rv, icValidateWarning);
  }
  return rv;
}
References icHeader::colorSpace, CIccInfo::GetSigPathName(), icGetSigPath(), icGetSpaceSamples(), icMaxStatus(), icMsgValidateNonCompliant, icMsgValidateWarning, icSigColorantTableOutTag, icSigColorantTableTag, icValidateNonCompliant, icValidateWarning, m_nCount, icHeader::pcs, and CIccTag::Validate().
Write()
bool CIccTagColorantOrder::Write (CIccIO * pIO) virtual
Name: CIccTagColorantOrder::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  if (!pIO)
   return false;
  if (!pIO->Write32(&sig))
   return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  if (!pIO->Write32(&m_nCount))
    return false;
  if (pIO->Write8(&m_pData[0], m_nCount) != (icInt32Number)m_nCount)
    return false;
  return true;
}
References GetType(), m_nCount, CIccTag::m_nReserved, m_pData, CIccIO::Write32(), and CIccIO::Write8().
Field Documentation
m_nCount
icUInt32Number CIccTagColorantOrder::m_nCount protected
Referenced by CIccTagColorantOrder(), CIccTagColorantOrder(), Describe(), GetSize(), operator=(), Read(), SetSize(), CIccTagXmlColorantOrder::ToXml(), Validate(), and Write().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_pData
icUInt8Number* CIccTagColorantOrder::m_pData protected
Referenced by CIccTagColorantOrder(), CIccTagColorantOrder(), ~CIccTagColorantOrder(), Describe(), GetData(), operator=(), operator[](), CIccTagXmlColorantOrder::ParseXml(), Read(), SetSize(), CIccTagXmlColorantOrder::ToXml(), and Write().
The documentation for this class was generated from the following files:
IccProfLib/IccTagBasic.h
IccProfLib/IccTagBasic.cpp