iccDEV: SIccCalcOp Struct Reference
SIccCalcOp Struct Reference
#include <IccMpeCalc.h>
Public Member Functions
icUInt16Number ArgsPushed (CIccMpeCalculator *pCalc)
icUInt16Number ArgsUsed (CIccMpeCalculator *pCalc)
void Describe (std::string &desc, int nVerboseness=100)
bool IsValidOp (CIccMpeCalculator *pCalc)
Static Public Member Functions
static bool IsValidOp (icSigCalcOp sig)
Data Fields
union {
icFloat32Number num
struct {
icUInt16Number v1
icUInt16Number v2
} select
icUInt32Number size
} data
IIccOpDef * def
unsigned long extra
icSigCalcOp sig
Detailed Description
Structure: SIccCalcOp
Purpose: A structure to keep track of channel operations
Member Function Documentation
ArgsPushed()
icUInt16Number SIccCalcOp::ArgsPushed (CIccMpeCalculator * pCalc)
Name: SIccCalcOp::ArgsPushed
Purpose:
Args:
Return:
{
  switch (sig) {
    case icSigOutputChanOp:
    case icSigTempPutChanOp:
    case icSigPopOp:
    case icSigIfOp:
    case icSigSelectOp:
      /*case icSigElseOp:*/     //This is only valid after an icSigIfOp is parsed
      /*case icSigCaseOp:*/     //This is only valid after an icSigSelectOp is parsed
      /*case icSigDefaultOp:*/  //This is only valid after an icSigSelectOp is parsed
      return 0;
    case icSigDataOp:
    case icSigPiOp:
    case icSigPosInfinityOp:
    case icSigNegInfinityOp:
    case icSigNotaNumberOp:
      return 1;
    case icSigEnvVarOp:
      return 2;
    case icSigInputChanOp:
    case icSigTempGetChanOp:
    case icSigTempSaveChanOp:
      return data.select.v2+1;
    case icSigApplyCurvesOp:
    case icSigApplyMatrixOp:
    case icSigApplyCLutOp:
    case icSigApplyTintOp:
    case icSigApplyToJabOp:
    case icSigApplyFromJabOp:
    case icSigApplyCalcOp:
    case icSigApplyElemOp:
      {
        CIccMultiProcessElement *pMpe = pCalc->GetElem(sig, data.select.v1);
        return (pMpe ? pMpe->NumOutputChannels() : 0);
      }
    case icSigCopyOp:
      return (data.select.v1+1)*(data.select.v2+2);
    case icSigRotateLeftOp:
    case icSigRotateRightOp:
      return (data.select.v1+1);
    case icSigFlipOp:
      return (data.select.v1+2);
    case icSigPositionDupOp:
      return data.select.v1+2+data.select.v2;
    case icSigSolveOp:
      return (data.select.v2+1) + 1;
    case icSigTransposeOp:
      return (data.select.v1+1)*(data.select.v2+1);
    case icSigSumOp:
    case icSigProductOp:
    case icSigMinimumOp:
    case icSigMaximumOp:
    case icSigAndOp:
    case icSigOrOp:
      return 1;
    case icSigAddOp:
    case icSigSubtractOp:
    case icSigMultiplyOp:
    case icSigDivideOp:
    case icSigModulusOp:
    case icSigPowOp:
    case icSigGammaOp:
    case icSigScalarAddOp:
    case icSigScalarSubtractOp:
    case icSigScalarMultiplyOp:
    case icSigScalarDivideOp:
    case icSigSquareOp:
    case icSigSquareRootOp:
    case icSigCubeOp:
    case icSigCubeRootOp:
    case icSigSignOp:
    case icSigAbsoluteValOp:
    case icSigTruncateOp:
    case icSigFloorOp:
    case icSigCeilingOp:
    case icSigRoundOp:
    case icSigRealNumberOp:
    case icSigNegOp:
    case icSigExpOp:
    case icSigLogrithmOp:
    case icSigNaturalLogOp:
    case icSigSineOp:
    case icSigCosineOp:
    case icSigTangentOp:
    case icSigArcSineOp:
    case icSigArcCosineOp:
    case icSigArcTangentOp:
    case icSigArcTan2Op:
    case icSigLessThanOp:
    case icSigLessThanEqualOp:
    case icSigEqualOp:
    case icSigNotEqualOp:
    case icSigNearOp:
    case icSigGreaterThanEqualOp:
    case icSigGreaterThanOp:
    case icSigNotOp:
    case icSigVectorMinimumOp:
    case icSigVectorMaximumOp:
    case icSigVectorAndOp:
    case icSigVectorOrOp:
      return data.select.v1+1;
    case icSigCartesianToPolarOp:
    case icSigPolarToCartesianOp:
      return (data.select.v1+1)*2;
    case icSigToLabOp:
    case icSigToXYZOp:
      return (data.select.v1+1)*3;
    default:
      return 0;
  }
}
References CIccMpeCalculator::GetElem(), icSigAbsoluteValOp, icSigAddOp, icSigAndOp, icSigApplyCalcOp, icSigApplyCLutOp, icSigApplyCurvesOp, icSigApplyElemOp, icSigApplyFromJabOp, icSigApplyMatrixOp, icSigApplyTintOp, icSigApplyToJabOp, icSigArcCosineOp, icSigArcSineOp, icSigArcTan2Op, icSigArcTangentOp, icSigCartesianToPolarOp, icSigCeilingOp, icSigCopyOp, icSigCosineOp, icSigCubeOp, icSigCubeRootOp, icSigDataOp, icSigDivideOp, icSigEnvVarOp, icSigEqualOp, icSigExpOp, icSigFlipOp, icSigFloorOp, icSigGammaOp, icSigGreaterThanEqualOp, icSigGreaterThanOp, icSigIfOp, icSigInputChanOp, icSigLessThanEqualOp, icSigLessThanOp, icSigLogrithmOp, icSigMaximumOp, icSigMinimumOp, icSigModulusOp, icSigMultiplyOp, icSigNaturalLogOp, icSigNearOp, icSigNegInfinityOp, icSigNegOp, icSigNotaNumberOp, icSigNotEqualOp, icSigNotOp, icSigOrOp, icSigOutputChanOp, icSigPiOp, icSigPolarToCartesianOp, icSigPopOp, icSigPosInfinityOp, icSigPositionDupOp, icSigPowOp, icSigProductOp, icSigRealNumberOp, icSigRotateLeftOp, icSigRotateRightOp, icSigRoundOp, icSigScalarAddOp, icSigScalarDivideOp, icSigScalarMultiplyOp, icSigScalarSubtractOp, icSigSelectOp, icSigSignOp, icSigSineOp, icSigSolveOp, icSigSquareOp, icSigSquareRootOp, icSigSubtractOp, icSigSumOp, icSigTangentOp, icSigTempGetChanOp, icSigTempPutChanOp, icSigTempSaveChanOp, icSigToLabOp, icSigToXYZOp, icSigTransposeOp, icSigTruncateOp, icSigVectorAndOp, icSigVectorMaximumOp, icSigVectorMinimumOp, icSigVectorOrOp, CIccMultiProcessElement::NumOutputChannels(), and sig.
Referenced by IIccOpDef::ArgsPushed(), and CIccCalculatorFunc::CheckUnderflowOverflow().
ArgsUsed()
icUInt16Number SIccCalcOp::ArgsUsed (CIccMpeCalculator * pCalc)
Name: SIccCalcOp::ArgsUsed
Purpose:
Args:
Return:
{
  switch (sig) {
    case icSigDataOp:
    case icSigPiOp:
    case icSigPosInfinityOp:
    case icSigNegInfinityOp:
    case icSigNotaNumberOp:
    case icSigInputChanOp:
    case icSigTempGetChanOp:
    case icSigEnvVarOp:
      return 0;
    case icSigApplyCurvesOp:
    case icSigApplyMatrixOp:
    case icSigApplyCLutOp:
    case icSigApplyTintOp:
    case icSigApplyToJabOp:
    case icSigApplyFromJabOp:
    case icSigApplyCalcOp:
    case icSigApplyElemOp:
      {
        CIccMultiProcessElement *pMpe = pCalc->GetElem(sig, data.select.v1);
        return (pMpe ? pMpe->NumInputChannels() : 0);
      }
    case icSigOutputChanOp:
    case icSigTempPutChanOp:
    case icSigTempSaveChanOp:
      return data.select.v2+1;
    case icSigCopyOp:
    case icSigRotateLeftOp:
    case icSigRotateRightOp:
    case icSigPositionDupOp:
    case icSigPopOp:
      return data.select.v1+1;
    case icSigSolveOp:
      return (data.select.v1+1)*(data.select.v2+1) + (data.select.v1+1);
    case icSigTransposeOp:
      return (data.select.v1+1)*(data.select.v2+1);
    case icSigFlipOp:
      return data.select.v1+2;
    case icSigSumOp:
    case icSigProductOp:
    case icSigMinimumOp:
    case icSigMaximumOp:
    case icSigAndOp:
    case icSigOrOp:
      return data.select.v1+2;
    case icSigGammaOp:
    case icSigScalarAddOp:
    case icSigScalarSubtractOp:
    case icSigScalarMultiplyOp:
    case icSigScalarDivideOp:
      return data.select.v1+2;
    case icSigAddOp:
    case icSigSubtractOp:
    case icSigMultiplyOp:
    case icSigDivideOp:
    case icSigModulusOp:
    case icSigPowOp:
    case icSigArcTan2Op:
    case icSigLessThanOp:
    case icSigLessThanEqualOp:
    case icSigEqualOp:
    case icSigNotEqualOp:
    case icSigNearOp:
    case icSigGreaterThanEqualOp:
    case icSigGreaterThanOp:
    case icSigCartesianToPolarOp:
    case icSigPolarToCartesianOp:
    case icSigVectorMinimumOp:
    case icSigVectorMaximumOp:
    case icSigVectorAndOp:
    case icSigVectorOrOp:
      return (data.select.v1+1)*2;
    case icSigSquareOp:
    case icSigSquareRootOp:
    case icSigCubeOp:
    case icSigCubeRootOp:
    case icSigSignOp:
    case icSigAbsoluteValOp:
    case icSigTruncateOp:
    case icSigFloorOp:
    case icSigCeilingOp:
    case icSigRoundOp:
    case icSigRealNumberOp:
    case icSigNegOp:
    case icSigExpOp:
    case icSigLogrithmOp:
    case icSigNaturalLogOp:
    case icSigSineOp:
    case icSigCosineOp:
    case icSigTangentOp:
    case icSigArcSineOp:
    case icSigArcCosineOp:
    case icSigArcTangentOp:
    case icSigNotOp:
      return data.select.v1+1;
    case icSigToLabOp:
    case icSigToXYZOp:
      return (data.select.v1+1)*3;
    case icSigIfOp:
    case icSigSelectOp:
      return 1;
    default:
      return 0;
  }
}
References CIccMpeCalculator::GetElem(), icSigAbsoluteValOp, icSigAddOp, icSigAndOp, icSigApplyCalcOp, icSigApplyCLutOp, icSigApplyCurvesOp, icSigApplyElemOp, icSigApplyFromJabOp, icSigApplyMatrixOp, icSigApplyTintOp, icSigApplyToJabOp, icSigArcCosineOp, icSigArcSineOp, icSigArcTan2Op, icSigArcTangentOp, icSigCartesianToPolarOp, icSigCeilingOp, icSigCopyOp, icSigCosineOp, icSigCubeOp, icSigCubeRootOp, icSigDataOp, icSigDivideOp, icSigEnvVarOp, icSigEqualOp, icSigExpOp, icSigFlipOp, icSigFloorOp, icSigGammaOp, icSigGreaterThanEqualOp, icSigGreaterThanOp, icSigIfOp, icSigInputChanOp, icSigLessThanEqualOp, icSigLessThanOp, icSigLogrithmOp, icSigMaximumOp, icSigMinimumOp, icSigModulusOp, icSigMultiplyOp, icSigNaturalLogOp, icSigNearOp, icSigNegInfinityOp, icSigNegOp, icSigNotaNumberOp, icSigNotEqualOp, icSigNotOp, icSigOrOp, icSigOutputChanOp, icSigPiOp, icSigPolarToCartesianOp, icSigPopOp, icSigPosInfinityOp, icSigPositionDupOp, icSigPowOp, icSigProductOp, icSigRealNumberOp, icSigRotateLeftOp, icSigRotateRightOp, icSigRoundOp, icSigScalarAddOp, icSigScalarDivideOp, icSigScalarMultiplyOp, icSigScalarSubtractOp, icSigSelectOp, icSigSignOp, icSigSineOp, icSigSolveOp, icSigSquareOp, icSigSquareRootOp, icSigSubtractOp, icSigSumOp, icSigTangentOp, icSigTempGetChanOp, icSigTempPutChanOp, icSigTempSaveChanOp, icSigToLabOp, icSigToXYZOp, icSigTransposeOp, icSigTruncateOp, icSigVectorAndOp, icSigVectorMaximumOp, icSigVectorMinimumOp, icSigVectorOrOp, CIccMultiProcessElement::NumInputChannels(), and sig.
Referenced by IIccOpDef::ArgsUsed(), and CIccCalculatorFunc::CheckUnderflowOverflow().
Describe()
void SIccCalcOp::Describe (std::string & desc, int nVerboseness = 100)
Name: SIccCalcOp::Describe
Purpose:
Args:
Return:
{
  char buf[300];
  if (sig==icSigDataOp) {
    sprintf(buf, "%.8g", data.num);
    desc = buf;
    return;
  }
  char name[10];
  int i;
  icGetSig(name, sig, false);
  name[5]=0;
  for (i=4; i>0; i--)
    if (name[i]==' ')
      name[i] = 0;
  if (!name[1])
    name[1] = '?';
  desc = &name[1];
  switch (sig) {
    case icSigInputChanOp:
    case icSigOutputChanOp:
    case icSigTempGetChanOp:
    case icSigTempPutChanOp:
    case icSigTempSaveChanOp:
      if (!data.select.v2)
        sprintf(buf, "[%d]", data.select.v1);
      else
        sprintf(buf, "[%d,%d]", data.select.v1, data.select.v2+1);
      desc += buf;
      break;
    case icSigEnvVarOp:
      {
        char varName[10];
        icGetSigStr(varName, (icSignature)data.size);
        int l=(int)strlen(varName);
        if (l==9) { //Remove h at end
          varName[8]=0;
        }
        else {
          for (l--; l>0; l--) {
            if (varName[l]!=' ')
              break;
            varName[l]=0;
          }
        }
        sprintf(buf, "(%s)", varName);
        desc += buf;
      }
      break;
    case icSigApplyCurvesOp:
    case icSigApplyMatrixOp:
    case icSigApplyCLutOp:
    case icSigApplyTintOp:
    case icSigApplyToJabOp:
    case icSigApplyFromJabOp:
    case icSigApplyCalcOp:
    case icSigApplyElemOp:
      sprintf(buf, "(%d)", data.select.v1);
      desc += buf;
      break;
    case icSigPopOp:
      sprintf(buf, "(%d)", data.select.v1+1);
      desc += buf;
      break;
    case icSigSolveOp:
    case icSigTransposeOp:
      sprintf(buf, "(%d,%d)", data.select.v1+1, data.select.v2+1);
      desc += buf;
      break;
    case icSigRotateLeftOp:
    case icSigRotateRightOp:
      sprintf(buf, "(%d,%d)", data.select.v1, data.select.v2);
      break;
    case icSigCopyOp:
    case icSigPositionDupOp:
      if (!data.select.v2) {
        if (data.select.v1) {
          sprintf(buf, "(%d)", data.select.v1+1);
          desc += buf;
        }
      }
      else {
        sprintf(buf, "(%d,%d)", data.select.v1+1, data.select.v2+1);
        desc += buf;
      }
      break;
    case icSigFlipOp:
    case icSigSumOp:
    case icSigProductOp:
    case icSigMinimumOp:
    case icSigMaximumOp:
    case icSigAndOp:
    case icSigOrOp:
      if (data.select.v1) {
        sprintf(buf, "(%d)", data.select.v1+2);
        desc += buf;
      }
      break;
    case icSigGammaOp:
    case icSigScalarAddOp:
    case icSigScalarSubtractOp:
    case icSigScalarMultiplyOp:
    case icSigScalarDivideOp:
    case icSigAddOp:
    case icSigSubtractOp:
    case icSigMultiplyOp:
    case icSigDivideOp:
    case icSigModulusOp:
    case icSigPowOp:
    case icSigArcTan2Op:
    case icSigLessThanOp:
    case icSigLessThanEqualOp:
    case icSigEqualOp:
    case icSigNotEqualOp:
    case icSigNearOp:
    case icSigGreaterThanEqualOp:
    case icSigGreaterThanOp:
    case icSigSquareOp:
    case icSigSquareRootOp:
    case icSigCubeOp:
    case icSigCubeRootOp:
    case icSigSignOp:
    case icSigAbsoluteValOp:
    case icSigTruncateOp:
    case icSigFloorOp:
    case icSigCeilingOp:
    case icSigRoundOp:
    case icSigRealNumberOp:
    case icSigNegOp:
    case icSigExpOp:
    case icSigLogrithmOp:
    case icSigNaturalLogOp:
    case icSigSineOp:
    case icSigCosineOp:
    case icSigTangentOp:
    case icSigArcSineOp:
    case icSigArcCosineOp:
    case icSigArcTangentOp:
    case icSigCartesianToPolarOp:
    case icSigPolarToCartesianOp:
    case icSigNotOp:
    case icSigToLabOp:
    case icSigToXYZOp:
    case icSigVectorMinimumOp:
    case icSigVectorMaximumOp:
    case icSigVectorAndOp:
    case icSigVectorOrOp:
      if (data.select.v1) {
        sprintf(buf, "[%d]", data.select.v1+1);
        desc += buf;
      }
      break;
  }
}
References icGetSig(), icGetSigStr(), icSigAbsoluteValOp, icSigAddOp, icSigAndOp, icSigApplyCalcOp, icSigApplyCLutOp, icSigApplyCurvesOp, icSigApplyElemOp, icSigApplyFromJabOp, icSigApplyMatrixOp, icSigApplyTintOp, icSigApplyToJabOp, icSigArcCosineOp, icSigArcSineOp, icSigArcTan2Op, icSigArcTangentOp, icSigCartesianToPolarOp, icSigCeilingOp, icSigCopyOp, icSigCosineOp, icSigCubeOp, icSigCubeRootOp, icSigDataOp, icSigDivideOp, icSigEnvVarOp, icSigEqualOp, icSigExpOp, icSigFlipOp, icSigFloorOp, icSigGammaOp, icSigGreaterThanEqualOp, icSigGreaterThanOp, icSigInputChanOp, icSigLessThanEqualOp, icSigLessThanOp, icSigLogrithmOp, icSigMaximumOp, icSigMinimumOp, icSigModulusOp, icSigMultiplyOp, icSigNaturalLogOp, icSigNearOp, icSigNegOp, icSigNotEqualOp, icSigNotOp, icSigOrOp, icSigOutputChanOp, icSigPolarToCartesianOp, icSigPopOp, icSigPositionDupOp, icSigPowOp, icSigProductOp, icSigRealNumberOp, icSigRotateLeftOp, icSigRotateRightOp, icSigRoundOp, icSigScalarAddOp, icSigScalarDivideOp, icSigScalarMultiplyOp, icSigScalarSubtractOp, icSigSignOp, icSigSineOp, icSigSolveOp, icSigSquareOp, icSigSquareRootOp, icSigSubtractOp, icSigSumOp, icSigTangentOp, icSigTempGetChanOp, icSigTempPutChanOp, icSigTempSaveChanOp, icSigToLabOp, icSigToXYZOp, icSigTransposeOp, icSigTruncateOp, icSigVectorAndOp, icSigVectorMaximumOp, icSigVectorMinimumOp, icSigVectorOrOp, and sig.
Referenced by CIccConsoleDebugger::AfterOp(), CIccLogDebugger::AfterOp(), CIccConsoleDebugger::BeforeOp(), CIccLogDebugger::BeforeOp(), CIccCalculatorFunc::CheckUnderflowOverflow(), IIccOpDef::Describe(), CIccCalculatorFunc::DescribeSequence(), CIccOpDefInvalid::Exec(), CIccCalculatorFunc::HasUnsupportedOperations(), CIccCalculatorFunc::HasValidOperations(), and CIccCalculatorFunc::ParseFuncDef().
IsValidOp() [1/2]
bool SIccCalcOp::IsValidOp (CIccMpeCalculator * pCalc)
{
  switch(sig) {
    case icSigApplyCurvesOp:
    case icSigApplyMatrixOp:
    case icSigApplyCLutOp:
    case icSigApplyTintOp:
    case icSigApplyToJabOp:
    case icSigApplyFromJabOp:
    case icSigApplyCalcOp:
    case icSigApplyElemOp:
      {
        CIccMultiProcessElement *pMpe = pCalc->GetElem(sig, data.select.v1);
        return pMpe != NULL;
      }
    default:
      return IsValidOp(sig);
  }
}
References CIccMpeCalculator::GetElem(), icSigApplyCalcOp, icSigApplyCLutOp, icSigApplyCurvesOp, icSigApplyElemOp, icSigApplyFromJabOp, icSigApplyMatrixOp, icSigApplyTintOp, icSigApplyToJabOp, IsValidOp(), and sig.
Referenced by CIccCalculatorFunc::HasValidOperations(), and IIccOpDef::IsValid().
IsValidOp() [2/2]
bool SIccCalcOp::IsValidOp (icSigCalcOp sig) static
Name: SIccCalcOp::IsValidOp
Purpose:
Args:
Return:
{
  switch (sig) {
    case icSigDataOp:
    case icSigInputChanOp:
    case icSigOutputChanOp:
    case icSigTempGetChanOp:
    case icSigTempPutChanOp:
    case icSigTempSaveChanOp:
    case icSigEnvVarOp:
    case icSigApplyCurvesOp:
    case icSigApplyMatrixOp:
    case icSigApplyCLutOp:
    case icSigApplyTintOp:
    case icSigApplyToJabOp:
    case icSigApplyFromJabOp:
    case icSigApplyCalcOp:
    case icSigApplyElemOp:
    case icSigCopyOp:
    case icSigRotateLeftOp:
    case icSigRotateRightOp:
    case icSigPositionDupOp:
    case icSigFlipOp:
    case icSigPopOp:
    case icSigSolveOp:
    case icSigTransposeOp:
    case icSigPiOp:
    case icSigPosInfinityOp:
    case icSigNegInfinityOp:
    case icSigNotaNumberOp:
    case icSigSumOp:
    case icSigProductOp:
    case icSigAddOp:
    case icSigSubtractOp:
    case icSigMultiplyOp:
    case icSigDivideOp:
    case icSigModulusOp:
    case icSigPowOp:
    case icSigGammaOp:
    case icSigScalarAddOp:
    case icSigScalarSubtractOp:
    case icSigScalarMultiplyOp:
    case icSigScalarDivideOp:
    case icSigSquareOp:
    case icSigSquareRootOp:
    case icSigCubeOp:
    case icSigCubeRootOp:
    case icSigSignOp:
    case icSigAbsoluteValOp:
    case icSigTruncateOp:
    case icSigFloorOp:
    case icSigCeilingOp:
    case icSigRoundOp:
    case icSigNegOp:
    case icSigExpOp:
    case icSigLogrithmOp:
    case icSigNaturalLogOp:
    case icSigSineOp:
    case icSigCosineOp:
    case icSigTangentOp:
    case icSigArcSineOp:
    case icSigArcCosineOp:
    case icSigArcTangentOp:
    case icSigArcTan2Op:
    case icSigCartesianToPolarOp:
    case icSigPolarToCartesianOp:
    case icSigVectorMinimumOp:
    case icSigVectorMaximumOp:
    case icSigVectorAndOp:
    case icSigVectorOrOp:
    case icSigMinimumOp:
    case icSigMaximumOp:
    case icSigRealNumberOp:
    case icSigLessThanOp:
    case icSigLessThanEqualOp:
    case icSigEqualOp:
    case icSigNotEqualOp:
    case icSigNearOp:
    case icSigGreaterThanEqualOp:
    case icSigGreaterThanOp:
    case icSigAndOp:
    case icSigOrOp:
    case icSigNotOp:
    case icSigToLabOp:
    case icSigToXYZOp:
    case icSigIfOp:
    case icSigElseOp:
    case icSigSelectOp:
    case icSigCaseOp:
    case icSigDefaultOp:
      return true;
    default:
      return false;
  }
}
References icSigAbsoluteValOp, icSigAddOp, icSigAndOp, icSigApplyCalcOp, icSigApplyCLutOp, icSigApplyCurvesOp, icSigApplyElemOp, icSigApplyFromJabOp, icSigApplyMatrixOp, icSigApplyTintOp, icSigApplyToJabOp, icSigArcCosineOp, icSigArcSineOp, icSigArcTan2Op, icSigArcTangentOp, icSigCartesianToPolarOp, icSigCaseOp, icSigCeilingOp, icSigCopyOp, icSigCosineOp, icSigCubeOp, icSigCubeRootOp, icSigDataOp, icSigDefaultOp, icSigDivideOp, icSigElseOp, icSigEnvVarOp, icSigEqualOp, icSigExpOp, icSigFlipOp, icSigFloorOp, icSigGammaOp, icSigGreaterThanEqualOp, icSigGreaterThanOp, icSigIfOp, icSigInputChanOp, icSigLessThanEqualOp, icSigLessThanOp, icSigLogrithmOp, icSigMaximumOp, icSigMinimumOp, icSigModulusOp, icSigMultiplyOp, icSigNaturalLogOp, icSigNearOp, icSigNegInfinityOp, icSigNegOp, icSigNotaNumberOp, icSigNotEqualOp, icSigNotOp, icSigOrOp, icSigOutputChanOp, icSigPiOp, icSigPolarToCartesianOp, icSigPopOp, icSigPosInfinityOp, icSigPositionDupOp, icSigPowOp, icSigProductOp, icSigRealNumberOp, icSigRotateLeftOp, icSigRotateRightOp, icSigRoundOp, icSigScalarAddOp, icSigScalarDivideOp, icSigScalarMultiplyOp, icSigScalarSubtractOp, icSigSelectOp, icSigSignOp, icSigSineOp, icSigSolveOp, icSigSquareOp, icSigSquareRootOp, icSigSubtractOp, icSigSumOp, icSigTangentOp, icSigTempGetChanOp, icSigTempPutChanOp, icSigTempSaveChanOp, icSigToLabOp, icSigToXYZOp, icSigTransposeOp, icSigTruncateOp, icSigVectorAndOp, icSigVectorMaximumOp, icSigVectorMinimumOp, and icSigVectorOrOp.
Referenced by IsValidOp(), and CIccCalculatorFunc::ParseFuncDef().
Field Documentation
[union]
union { ... } SIccCalcOp::data
def
IIccOpDef* SIccCalcOp::def
Referenced by CIccCalculatorFunc::ApplySequence(), CIccCalculatorFunc::ParseFuncDef(), and CIccCalculatorFunc::SetOpDefs().
extra
unsigned long SIccCalcOp::extra
Referenced by CIccCalculatorFunc::ApplySequence(), CIccOpDefData::Exec(), CIccCalculatorFunc::InitSelectOp(), and CIccCalculatorFunc::ParseFuncDef().
sig
icSigCalcOp SIccCalcOp::sig
Referenced by CIccConsoleDebugger::AfterOp(), CIccLogDebugger::AfterOp(), CIccCalculatorFunc::ApplySequence(), ArgsPushed(), ArgsUsed(), CIccConsoleDebugger::BeforeOp(), CIccLogDebugger::BeforeOp(), CIccCalculatorFunc::CheckUnderflowOverflow(), Describe(), CIccCalculatorFunc::DescribeSequence(), CIccCalculatorFunc::DoesOverflowInput(), CIccCalculatorFunc::DoesOverflowOutput(), CIccOpDefData::Exec(), CIccCalculatorFunc::GetMaxTemp(), CIccCalculatorFunc::HasUnsupportedOperations(), CIccCalculatorFunc::HasValidOperations(), CIccCalculatorFunc::InitSelectOp(), CIccCalculatorFunc::InitSelectOps(), IsValidOp(), CIccCalculatorFunc::ParseFuncDef(), CIccCalculatorFunc::Read(), CIccCalculatorFunc::SequenceNeedTempReset(), CIccCalculatorFunc::SetOpDefs(), and CIccCalculatorFunc::Write().
The documentation for this struct was generated from the following files:
IccProfLib/IccMpeCalc.h
IccProfLib/IccMpeCalc.cpp