iccDEV: CIccCalcOpMgr Class Reference
CIccCalcOpMgr Class Reference
Static Public Member Functions
static CIccCalcOpMgr * GetInstance ()
static IIccOpDef * getOpDef (icSigCalcOp opSig)
Protected Attributes
CIccOpDefInvalid m_invalid
icCalcOpMap m_map
Private Member Functions
CIccCalcOpMgr ()
Static Private Attributes
static CIccCalcOpMgr * m_inst = NULL
Detailed Description
Constructor & Destructor Documentation
CIccCalcOpMgr()
CIccCalcOpMgr::CIccCalcOpMgr () private
{
  m_map[icSigDataOp] = new CIccOpDefData();
  m_map[icSigInputChanOp] = new CIccOpDefInputChan();
  m_map[icSigOutputChanOp] = new CIccOpDefOutputChan();
  m_map[icSigTempGetChanOp] = new CIccOpDefTempGetChan();
  m_map[icSigTempPutChanOp] = new CIccOpDefTempPutChan();
  m_map[icSigTempSaveChanOp] = new CIccOpDefTempSaveChan();
  m_map[icSigEnvVarOp] = new CIccOpDefEnvVar();
  m_map[icSigApplyCurvesOp] = new CIccOpDefSubElement();
  m_map[icSigApplyMatrixOp] = new CIccOpDefSubElement();
  m_map[icSigApplyCLutOp] = new CIccOpDefSubElement();
  m_map[icSigApplyTintOp] = new CIccOpDefSubElement();
  m_map[icSigApplyToJabOp] = new CIccOpDefSubElement();
  m_map[icSigApplyFromJabOp] = new CIccOpDefSubElement();
  m_map[icSigApplyCalcOp] = new CIccOpDefSubElement();
  m_map[icSigApplyElemOp] = new CIccOpDefSubElement();
  m_map[icSigCopyOp] = new CIccOpDefCopy();
  m_map[icSigRotateLeftOp] = new CIccOpDefRotateLeft();
  m_map[icSigRotateRightOp] = new CIccOpDefRotateRight();
  m_map[icSigPositionDupOp] = new CIccOpDefPositionDup();
  m_map[icSigFlipOp] = new CIccOpDefFlip();
  m_map[icSigPopOp] = new CIccOpDefPop();
  m_map[icSigSolveOp] = new CIccOpDefSolve();
  m_map[icSigTransposeOp] = new CIccOpDefTranspose();
  m_map[icSigPiOp] = new CIccOpDefPi();
  m_map[icSigPosInfinityOp] = new CIccOpDefPosInfinity();
  m_map[icSigNegInfinityOp] = new CIccOpDefNegInfinity();
  m_map[icSigNotaNumberOp] = new CIccOpDefNotANumber();
  m_map[icSigSumOp] = new CIccOpDefSum();
  m_map[icSigProductOp] = new CIccOpDefProduct();
  m_map[icSigAddOp] = new CIccOpDefAdd();
  m_map[icSigSubtractOp] = new CIccOpDefSubtract();
  m_map[icSigMultiplyOp] = new CIccOpDefMultiply();
  m_map[icSigDivideOp] = new CIccOpDefDivide();
  m_map[icSigModulusOp] = new CIccOpDefModulus();
  m_map[icSigPowOp] = new CIccOpDefPow();
  m_map[icSigGammaOp] = new CIccOpDefGamma();
  m_map[icSigScalarAddOp] = new CIccOpDefScalarAdd();
  m_map[icSigScalarSubtractOp] = new CIccOpDefScalarSubtract();
  m_map[icSigScalarMultiplyOp] = new CIccOpDefScalarMultiply();
  m_map[icSigScalarDivideOp] = new CIccOpDefScalarDivide();
  m_map[icSigSquareOp] = new CIccOpDefSquare();
  m_map[icSigSquareRootOp] = new CIccOpDefSquareRoot();
  m_map[icSigCubeOp] = new CIccOpDefCube();
  m_map[icSigCubeRootOp] = new CIccOpDefCubeRoot();
  m_map[icSigSignOp] = new CIccOpDefSign();
  m_map[icSigAbsoluteValOp] = new CIccOpDefAbsoluteVal();
  m_map[icSigTruncateOp] = new CIccOpDefTruncate();
  m_map[icSigFloorOp] = new CIccOpDefFloor();
  m_map[icSigCeilingOp] = new CIccOpDefCeiling();
  m_map[icSigRoundOp] = new CIccOpDefRound();
  m_map[icSigNegOp] = new CIccOpDefNeg();
  m_map[icSigExpOp] = new CIccOpDefExp();
  m_map[icSigLogrithmOp] = new CIccOpDefLogrithm();
  m_map[icSigNaturalLogOp] = new CIccOpDefNaturalLog();
  m_map[icSigSineOp] = new CIccOpDefSine();
  m_map[icSigCosineOp] = new CIccOpDefCosine();
  m_map[icSigTangentOp] = new CIccOpDefTangent();
  m_map[icSigArcSineOp] = new CIccOpDefArcSine();
  m_map[icSigArcCosineOp] = new CIccOpDefArcCosine();
  m_map[icSigArcTangentOp] = new CIccOpDefArcTangent();
  m_map[icSigArcTan2Op] = new CIccOpDefArcTan2();
  m_map[icSigCartesianToPolarOp] = new CIccOpDefCartesianToPolar();
  m_map[icSigPolarToCartesianOp] = new CIccOpDefPolarToCartesian();
  m_map[icSigVectorMinimumOp] = new CIccOpDefVectorMinimum();
  m_map[icSigVectorMaximumOp] = new CIccOpDefVectorMaximum();
  m_map[icSigVectorAndOp] = new CIccOpDefVectorAnd();
  m_map[icSigVectorOrOp] = new CIccOpDefVectorOr();
  m_map[icSigMinimumOp] = new CIccOpDefMinimum();
  m_map[icSigMaximumOp] = new CIccOpDefMaximum();
  m_map[icSigRealNumberOp] = new CIccOpDefRealNumber();
  m_map[icSigLessThanOp] = new CIccOpDefLessThan();
  m_map[icSigLessThanEqualOp] = new CIccOpDefLessThanEqual();
  m_map[icSigEqualOp] = new CIccOpDefEqual();
  m_map[icSigNotEqualOp] = new CIccOpDefNotEqual();
  m_map[icSigNearOp] = new CIccOpDefNear();
  m_map[icSigGreaterThanEqualOp] = new CIccOpDefGreaterThanEqual();
  m_map[icSigGreaterThanOp] = new CIccOpDefGreaterThan();
  m_map[icSigAndOp] = new CIccOpDefAnd();
  m_map[icSigOrOp] = new CIccOpDefOr();
  m_map[icSigNotOp] = new CIccOpDefNot();
  m_map[icSigToLabOp] = new CIccOpDefToLab();
  m_map[icSigToXYZOp] = new CIccOpDefFromLab();
}
References icSigAbsoluteValOp, icSigAddOp, icSigAndOp, icSigApplyCalcOp, icSigApplyCLutOp, icSigApplyCurvesOp, icSigApplyElemOp, icSigApplyFromJabOp, icSigApplyMatrixOp, icSigApplyTintOp, icSigApplyToJabOp, icSigArcCosineOp, icSigArcSineOp, icSigArcTan2Op, icSigArcTangentOp, icSigCartesianToPolarOp, icSigCeilingOp, icSigCopyOp, icSigCosineOp, icSigCubeOp, icSigCubeRootOp, icSigDataOp, icSigDivideOp, icSigEnvVarOp, icSigEqualOp, icSigExpOp, icSigFlipOp, icSigFloorOp, icSigGammaOp, icSigGreaterThanEqualOp, icSigGreaterThanOp, icSigInputChanOp, icSigLessThanEqualOp, icSigLessThanOp, icSigLogrithmOp, icSigMaximumOp, icSigMinimumOp, icSigModulusOp, icSigMultiplyOp, icSigNaturalLogOp, icSigNearOp, icSigNegInfinityOp, icSigNegOp, icSigNotaNumberOp, icSigNotEqualOp, icSigNotOp, icSigOrOp, icSigOutputChanOp, icSigPiOp, icSigPolarToCartesianOp, icSigPopOp, icSigPosInfinityOp, icSigPositionDupOp, icSigPowOp, icSigProductOp, icSigRealNumberOp, icSigRotateLeftOp, icSigRotateRightOp, icSigRoundOp, icSigScalarAddOp, icSigScalarDivideOp, icSigScalarMultiplyOp, icSigScalarSubtractOp, icSigSignOp, icSigSineOp, icSigSolveOp, icSigSquareOp, icSigSquareRootOp, icSigSubtractOp, icSigSumOp, icSigTangentOp, icSigTempGetChanOp, icSigTempPutChanOp, icSigTempSaveChanOp, icSigToLabOp, icSigToXYZOp, icSigTransposeOp, icSigTruncateOp, icSigVectorAndOp, icSigVectorMaximumOp, icSigVectorMinimumOp, icSigVectorOrOp, and m_map.
Referenced by GetInstance().
Member Function Documentation
GetInstance()
CIccCalcOpMgr * CIccCalcOpMgr::GetInstance () static
{
  if (!m_inst)
    m_inst = new CIccCalcOpMgr();
  return m_inst;
}
References CIccCalcOpMgr(), and m_inst.
Referenced by getOpDef().
getOpDef()
IIccOpDef * CIccCalcOpMgr::getOpDef (icSigCalcOp opSig) static
{
  icCalcOpMap::iterator pos;
  CIccCalcOpMgr *inst = GetInstance();
  pos = inst->m_map.find(opSig);
  if (pos==inst->m_map.end())
    return &inst->m_invalid;
  return pos->second;
}
References GetInstance(), m_invalid, and m_map.
Referenced by CIccCalculatorFunc::SetOpDefs().
Field Documentation
m_inst
CIccCalcOpMgr * CIccCalcOpMgr::m_inst = NULL static private
Referenced by GetInstance().
m_invalid
CIccOpDefInvalid CIccCalcOpMgr::m_invalid protected
Referenced by getOpDef().
m_map
icCalcOpMap CIccCalcOpMgr::m_map protected
Referenced by CIccCalcOpMgr(), and getOpDef().
The documentation for this class was generated from the following file:
IccProfLib/IccMpeCalc.cpp