iccDEV: CIccTagXmlUtf16Text Class Reference
CIccTagXmlUtf16Text Class Reference
#include <IccTagXml.h>
Public Member Functions
CIccTagXmlUtf16Text ()
CIccTagXmlUtf16Text (const CIccTagXmlUtf16Text &ITT)
virtual ~CIccTagXmlUtf16Text ()
icUInt32Number Capacity () const
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
icUChar16 * GetBuffer (icUInt32Number nSize)
virtual const char * GetClassName () const
virtual const char * GetExtClassName () const
virtual const char * GetExtDerivedClassName () const
virtual IIccExtensionTag * GetExtension ()
icUInt32Number GetLength () const
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
const icUChar16 * GetText () const
const icChar * GetText (std::string &bufStr) const
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
virtual bool ParseXml (xmlNode *pNode, std::string &parseStr)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
void Release ()
void SetText (const icChar *szText)
void SetText (const icUChar *szText)
void SetText (const icUChar16 *szText)
virtual bool ToXml (std::string &xml, std::string blanks="")
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
Protected Attributes
icUInt32Number m_nBufSize
icUChar16 * m_szText
Detailed Description
Constructor & Destructor Documentation
CIccTagXmlUtf16Text() [1/2]
CIccTagXmlUtf16Text::CIccTagXmlUtf16Text () inline
: CIccTagUtf16Text() {}
References CIccTagUtf16Text::CIccTagUtf16Text().
CIccTagXmlUtf16Text() [2/2]
CIccTagXmlUtf16Text::CIccTagXmlUtf16Text (const CIccTagXmlUtf16Text & ITT) inline
: CIccTagUtf16Text(ITT) {}
References CIccTagUtf16Text::CIccTagUtf16Text().
Referenced by NewCopy().
~CIccTagXmlUtf16Text()
virtual CIccTagXmlUtf16Text::~CIccTagXmlUtf16Text () inline virtual
{}
Member Function Documentation
Capacity()
icUInt32Number CIccTagUtf16Text::Capacity () const inline inherited
{ return m_nBufSize; }
References CIccTagUtf16Text::m_nBufSize.
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagUtf16Text::Describe (std::string & sDescription, int nVerboseness) virtual inherited
Name: CIccTagUtf16Text::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
    sDescription += "UTF16 Length = ";
    if (m_szText && *m_szText) {
        char buf[40];
        sprintf(buf, "%d bytes\n", m_nBufSize);
        sDescription += buf;
    }
    else
        sDescription += "0 (NULL)";
    if (nVerboseness > 25) {
        sDescription += "\"";
        if (m_szText && *m_szText) {
            std::string   s;
            if ((nVerboseness > 50) || (m_nBufSize < BRIEF_STRING_SIZE)) {
                // output entire string if short or doing verbose
                sDescription += GetText(s);
            }
            else {
                // copy just first part of string to keep nVerboseness under control
                char buf[BRIEF_STRING_SIZE + 1];
                strncpy(buf, GetText(s), BRIEF_STRING_SIZE);
                buf[BRIEF_STRING_SIZE] = '\0'; // ensure NULL termination
                sDescription += buf;
                sDescription += "\n... <!truncated!>";
            }
        }
        sDescription += "\"\n";
    }
}
References CIccTagUtf16Text::GetText(), CIccTagUtf16Text::m_nBufSize, and CIccTagUtf16Text::m_szText.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
GetBuffer()
icUChar16 * CIccTagUtf16Text::GetBuffer (icUInt32Number nSize) inherited
Name: CIccTagUtf16Text::GetBuffer
Purpose: This function allocates room and returns pointer to data buffer to put string into
Args: nSize = Requested size of data buffer.
Return: The utf16 character buffer array
{
  if (m_nBufSize < nSize) {
    m_szText = (icUChar16*)icRealloc(m_szText, (nSize+1)*sizeof(icUChar16));
    m_szText[nSize] = 0;
    m_nBufSize = nSize;
  }
  return m_szText;
}
References icRealloc(), CIccTagUtf16Text::m_nBufSize, and CIccTagUtf16Text::m_szText.
Referenced by CIccTagUtf16Text::Read(), CIccTagUtf16Text::SetText(), and CIccTagUtf16Text::SetText().
GetClassName()
virtual const char * CIccTagXmlUtf16Text::GetClassName () const inline virtual
Reimplemented from CIccTagUtf16Text.
{return "CIccTagXmlUtf16Text"; }
GetExtClassName()
virtual const char * CIccTagXml::GetExtClassName () const inline virtual inherited
Implements IIccExtensionTag.
{ return "CIccTagXml"; }
Referenced by icProfDescToXml(), and icXmlParseProfDesc().
GetExtDerivedClassName()
virtual const char * CIccTagXml::GetExtDerivedClassName () const inline virtual inherited
Implements IIccExtensionTag.
Reimplemented in CIccCurveXml.
{ return ""; }
GetExtension()
virtual IIccExtensionTag * CIccTagXmlUtf16Text::GetExtension () inline virtual
Reimplemented from CIccTag.
{return this; }
GetLength()
icUInt32Number CIccTagUtf16Text::GetLength () const inherited
Name: CIccTagUtf16Text::GetLength
Purpose: Get length of utf16 string
{
  icUInt32Number n;
  if (!m_szText || !m_nBufSize)
    return 0;
  for (n=0; n<m_nBufSize && m_szText[n]; n++);
  return n;
}
References CIccTagUtf16Text::m_nBufSize, and CIccTagUtf16Text::m_szText.
Referenced by CIccTagUtf16Text::GetText(), CIccTagUtf16Text::Release(), and CIccTagUtf16Text::Write().
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetText() [1/2]
const icUChar16 * CIccTagUtf16Text::GetText () const inline inherited
{ return m_szText; }
References CIccTagUtf16Text::m_szText.
GetText() [2/2]
const icChar * CIccTagUtf16Text::GetText (std::string & buf) const inherited
Name: CIccTagUtf16Text::GetText
Purpose: Allows text data associated with the tag to be fetched.
Args: buf - buffer to put tag data into. Returns: buf.c_str()
{
  icUtf8Vector str;
  icConvertUTF16toUTF8(m_szText, &m_szText[GetLength()], str, lenientConversion);
  buf.clear();
  icUtf8Vector::iterator c;
  c=str.begin();
  if (str.size()>2 && (str[0]==0xff && str[1]==0xfe)) {
    c++; c++;
  }
  for (; c!=str.end(); c++)
    buf.push_back(*c);
  return buf.c_str();
}
References CIccTagUtf16Text::GetLength(), icConvertUTF16toUTF8(), lenientConversion, and CIccTagUtf16Text::m_szText.
Referenced by CIccTagUtf16Text::Describe(), icGetTagText(), and ToXml().
GetType()
virtual icTagTypeSignature CIccTagUtf16Text::GetType () const inline virtual inherited
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigUtf16TextType; }
References icSigUtf16TextType.
Referenced by CIccTagUtf16Text::Write().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
virtual CIccTag * CIccTagXmlUtf16Text::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTagUtf16Text.
{return new CIccTagXmlUtf16Text(*this);}
References CIccTagXmlUtf16Text().
ParseXml()
bool CIccTagXmlUtf16Text::ParseXml (xmlNode * pNode, std::string & parseStr) virtual
Implements CIccTagXml.
{
  std::string str = icXmlParseTextString(pNode, parseStr, false);
  if (!str.empty()){
    SetText(str.c_str());
    return true;
  }
  return false;
}
References icXmlParseTextString(), and CIccTagUtf16Text::SetText().
Read() [1/2]
bool CIccTagUtf16Text::Read (icUInt32Number size, CIccIO * pIO) virtual inherited
Name: CIccTagUtf16Text::Read
Purpose: Read in a text type tag into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  if (size<sizeof(icTagTypeSignature) || !pIO) {
    m_szText[0] = '\0';
    return false;
  }
  if (!pIO->Read32(&sig))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  icUInt32Number nSize = (size - sizeof(icTagTypeSignature) - sizeof(icUInt32Number))/sizeof(icUChar16);
  icUChar16 *pBuf = GetBuffer(nSize);
  if (nSize) {
    if (pIO->Read16(pBuf, nSize) != (icInt32Number)nSize) {
      return false;
    }
  }
  Release();
  return true;
}
References CIccTagUtf16Text::GetBuffer(), CIccTag::m_nReserved, CIccTagUtf16Text::m_szText, CIccIO::Read16(), CIccIO::Read32(), and CIccTagUtf16Text::Release().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
Release()
void CIccTagUtf16Text::Release () inherited
Name: CIccTagUtf16Text::Release
Purpose: This will resize the buffer to fit the zero terminated string in the buffer.
{
  icUInt32Number nSize = GetLength()+1;
  if (nSize < m_nBufSize-1) {
    m_szText=(icUChar16*)icRealloc(m_szText, (nSize+1)*sizeof(icUChar16));
    m_nBufSize = nSize+1;
  }
}
References CIccTagUtf16Text::GetLength(), icRealloc(), CIccTagUtf16Text::m_nBufSize, and CIccTagUtf16Text::m_szText.
Referenced by CIccTagUtf16Text::Read(), CIccTagUtf16Text::SetText(), and CIccTagUtf16Text::SetText().
SetText() [1/3]
void CIccTagUtf16Text::SetText (const icChar * szText) inline inherited
{ SetText((icUChar*)szText); }
References CIccTagUtf16Text::SetText().
Referenced by ParseXml().
SetText() [2/3]
void CIccTagUtf16Text::SetText (const icUChar * szText) inherited
Name: CIccTagUtf16Text::SetText
Purpose: Allows text data associated with the tag to be set.
Args: szText - zero terminated string to put in tag
{
  if (!szText) {
    icUChar16 c=0;
    SetText(&c);
    return;
  }
  icUtf16Vector str;
  icConvertUTF8toUTF16(szText, szText+strlen((icChar*)szText)+1, str, lenientConversion);
  int pos = 0;
  if (str[0]==0xfeff) {
    pos = 1;
  }
  icUInt32Number nSize = (icUInt32Number)(str.size()-pos);
  icUChar16 *szBuf = GetBuffer(nSize);
  if (nSize)
    memcpy(m_szText, &str[pos], nSize*sizeof(icUChar));
  Release();
}
References CIccTagUtf16Text::GetBuffer(), icConvertUTF8toUTF16(), lenientConversion, CIccTagUtf16Text::m_szText, CIccTagUtf16Text::Release(), and CIccTagUtf16Text::SetText().
Referenced by CIccTagUtf16Text::SetText().
SetText() [3/3]
void CIccTagUtf16Text::SetText (const icUChar16 * szText) inherited
Name: CIccTagUtf16Text::SetText
Purpose: Allows text data associated with the tag to be set.
Args: szText - zero terminated string to put in tag
{
  if (!szText) {
    icUChar16 c=0;
    SetText(&c);
    return;
  }
  icUInt32Number n;
  for (n=0; szText[n]; n++);
  icUInt32Number len=n + 1;
  icUChar16 *szBuf = GetBuffer(len);
  memcpy(szBuf, szText, len*sizeof(icUChar16));
  Release();
}
References CIccTagUtf16Text::GetBuffer(), CIccTagUtf16Text::Release(), and CIccTagUtf16Text::SetText().
Referenced by CIccTagUtf16Text::CIccTagUtf16Text(), CIccTagUtf16Text::operator=(), CIccTagUtf16Text::operator=(), CIccTagUtf16Text::SetText(), and CIccTagUtf16Text::SetText().
ToXml()
bool CIccTagXmlUtf16Text::ToXml (std::string & xml, std::string blanks = "") virtual
Implements CIccTagXml.
{
  std::string buf;
  return icXmlDumpTextData(xml, blanks, GetText(buf), false);
}
References CIccTagUtf16Text::GetText(), and icXmlDumpTextData().
Validate()
icValidateStatus CIccTagUtf16Text::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual inherited
Name: CIccTagUtf16Text::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  if (!m_nBufSize) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " - Empty Tag.\n";
    rv = icMaxStatus(rv, icValidateWarning);
  }
  return rv;
}
References CIccInfo::GetSigPathName(), icMaxStatus(), icMsgValidateWarning, icValidateWarning, CIccTagUtf16Text::m_nBufSize, and CIccTag::Validate().
Write()
bool CIccTagUtf16Text::Write (CIccIO * pIO) virtual inherited
Name: CIccTagUtf16Text::Write
Purpose: Write a text type tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  if (!pIO)
   return false;
  if (!pIO->Write32(&sig))
   return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  if (!m_szText)
    return false;
  icUInt32Number nSize = GetLength();
  if (nSize) {
    if (pIO->Write16(m_szText, nSize) != (icInt32Number)nSize)
      return false;
  }
  return true;
}
References CIccTagUtf16Text::GetLength(), CIccTagUtf16Text::GetType(), CIccTag::m_nReserved, CIccTagUtf16Text::m_szText, CIccIO::Write16(), and CIccIO::Write32().
Field Documentation
m_nBufSize
icUInt32Number CIccTagUtf16Text::m_nBufSize protected inherited
Referenced by CIccTagUtf16Text::CIccTagUtf16Text(), CIccTagUtf16Text::CIccTagUtf16Text(), CIccTagUtf16Text::Capacity(), CIccTagUtf16Text::Describe(), CIccTagUtf16Text::GetBuffer(), CIccTagUtf16Text::GetLength(), CIccTagUtf16Text::operator=(), CIccTagUtf16Text::Release(), and CIccTagUtf16Text::Validate().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_szText
icUChar16* CIccTagUtf16Text::m_szText protected inherited
Referenced by CIccTagUtf16Text::CIccTagUtf16Text(), CIccTagUtf16Text::CIccTagUtf16Text(), CIccTagUtf16Text::~CIccTagUtf16Text(), CIccTagUtf16Text::Describe(), CIccTagUtf16Text::GetBuffer(), CIccTagUtf16Text::GetLength(), CIccTagUtf16Text::GetText(), CIccTagUtf16Text::GetText(), CIccTagUtf16Text::operator=(), CIccTagUtf16Text::operator=(), CIccTagUtf16Text::Read(), CIccTagUtf16Text::Release(), CIccTagUtf16Text::SetText(), and CIccTagUtf16Text::Write().
The documentation for this class was generated from the following files:
IccXML/IccLibXML/IccTagXml.h
IccXML/IccLibXML/IccTagXml.cpp