iccDEV: CIccTagXmlResponseCurveSet16 Class Reference
CIccTagXmlResponseCurveSet16 Class Reference
#include <IccTagXml.h>
Public Member Functions
virtual ~CIccTagXmlResponseCurveSet16 ()
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
virtual const char * GetClassName () const
virtual const char * GetExtClassName () const
virtual const char * GetExtDerivedClassName () const
virtual IIccExtensionTag * GetExtension ()
CIccResponseCurveStruct * GetFirstCurves ()
CIccResponseCurveStruct * GetNextCurves ()
icUInt16Number GetNumChannels () const
icUInt16Number GetNumResponseCurveTypes () const
CIccResponseCurveStruct * GetResponseCurves (icMeasurementUnitSig sig)
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
CIccResponseCurveStruct * NewResponseCurves (icMeasurementUnitSig sig)
virtual bool ParseXml (xmlNode *pNode, std::string &parseStr)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
void SetNumChannels (icUInt16Number nChannels)
virtual bool ToXml (std::string &xml, std::string blanks="")
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
Protected Attributes
CIccResponseCurveSetIter * m_Curve
icUInt16Number m_nChannels
CIccResponseCurveSet * m_ResponseCurves
Detailed Description
Constructor & Destructor Documentation
~CIccTagXmlResponseCurveSet16()
virtual CIccTagXmlResponseCurveSet16::~CIccTagXmlResponseCurveSet16 () inline virtual
{}
Member Function Documentation
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagResponseCurveSet16::Describe (std::string & sDescription, int nVerboseness) virtual inherited
Name: CIccTagResponseCurveSet16::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  CIccResponseCurveSet::iterator i;
  icChar buf[128];
  sprintf(buf, "Number of Channels: %u\n", m_nChannels);
  sDescription += buf;
  sprintf(buf, "Number of Measurement Types used: %u\n", (icUInt32Number)m_ResponseCurves->size());
  sDescription += buf;
  int count = 0;
  for (i=m_ResponseCurves->begin(); i!=m_ResponseCurves->end(); i++, count++) {
     sDescription += "\n";
    sprintf(buf, "Response Curve for measurement type [%u] follows:\n", count+1);
    sDescription += buf;
    i->Describe(sDescription, nVerboseness);
  }
}
References CIccResponseCurveStruct::Describe(), CIccTagResponseCurveSet16::m_nChannels, and CIccTagResponseCurveSet16::m_ResponseCurves.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
GetClassName()
virtual const char * CIccTagXmlResponseCurveSet16::GetClassName () const inline virtual
Reimplemented from CIccTagResponseCurveSet16.
{return "CIccTagXmlResponseCurveSet16"; }
GetExtClassName()
virtual const char * CIccTagXml::GetExtClassName () const inline virtual inherited
Implements IIccExtensionTag.
{ return "CIccTagXml"; }
Referenced by icProfDescToXml(), and icXmlParseProfDesc().
GetExtDerivedClassName()
virtual const char * CIccTagXml::GetExtDerivedClassName () const inline virtual inherited
Implements IIccExtensionTag.
Reimplemented in CIccCurveXml.
{ return ""; }
GetExtension()
virtual IIccExtensionTag * CIccTagXmlResponseCurveSet16::GetExtension () inline virtual
Reimplemented from CIccTag.
{return this; }
GetFirstCurves()
CIccResponseCurveStruct * CIccTagResponseCurveSet16::GetFirstCurves () inherited
Name: CIccTagResponseCurveSet16::GetFirstCurves
Purpose: Returns pointer to the first set of response curves in the list.
{
  if (!m_Curve)
    return NULL;
  m_Curve->item = m_ResponseCurves->begin();
  if (m_Curve->item == m_ResponseCurves->end()) {
    m_Curve->inited = false;
    return NULL;
  }
  m_Curve->inited = true;
  return m_Curve->item->GetThis();
}
References CIccResponseCurveStruct::GetThis(), CIccResponseCurveSetIter::inited, CIccResponseCurveSetIter::item, CIccTagResponseCurveSet16::m_Curve, and CIccTagResponseCurveSet16::m_ResponseCurves.
Referenced by ToXml().
GetNextCurves()
CIccResponseCurveStruct * CIccTagResponseCurveSet16::GetNextCurves () inherited
Name: CIccTagResponseCurveSet16::GetNextCurves
Purpose: Serves as an iterator for the list containing response curves. GetFirstCurves() must be called before calling this function.
{
  if (!m_Curve || !m_Curve->inited)
    return NULL;
  m_Curve->item++;
  if (m_Curve->item==m_ResponseCurves->end()) {
    m_Curve->inited = false;
    return NULL;
  }
  return m_Curve->item->GetThis();
}
References CIccResponseCurveStruct::GetThis(), CIccResponseCurveSetIter::inited, CIccResponseCurveSetIter::item, CIccTagResponseCurveSet16::m_Curve, and CIccTagResponseCurveSet16::m_ResponseCurves.
Referenced by ToXml().
GetNumChannels()
icUInt16Number CIccTagResponseCurveSet16::GetNumChannels () const inline inherited
{return m_nChannels;}
References CIccTagResponseCurveSet16::m_nChannels.
GetNumResponseCurveTypes()
icUInt16Number CIccTagResponseCurveSet16::GetNumResponseCurveTypes () const inherited
Name: CIccTagResponseCurveSet16::GetNumResponseCurveTypes
Purpose: Get the number of response curve types.
{
  return(icUInt16Number) m_ResponseCurves->size();
}
References CIccTagResponseCurveSet16::m_ResponseCurves.
Referenced by CIccTagResponseCurveSet16::Validate().
GetResponseCurves()
CIccResponseCurveStruct * CIccTagResponseCurveSet16::GetResponseCurves (icMeasurementUnitSig sig) inherited
Name: CIccTagResponseCurveSet16::GetResponseCurves
Purpose: Returns pointer to the requested set of response curves
Args: sig = measurement unit signature of the response curve set desired
{
  if (!m_nChannels)
    return NULL;
  CIccResponseCurveSet::iterator i;
  for (i=m_ResponseCurves->begin(); i!=m_ResponseCurves->end(); i++) {
    if (i->GetMeasurementType() == sig)
      return (i->GetThis());
  }
  return NULL;
}
References CIccResponseCurveStruct::GetMeasurementType(), CIccResponseCurveStruct::GetThis(), CIccTagResponseCurveSet16::m_nChannels, and CIccTagResponseCurveSet16::m_ResponseCurves.
Referenced by CIccTagResponseCurveSet16::NewResponseCurves().
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagResponseCurveSet16::GetType () const inline virtual inherited
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigResponseCurveSet16Type; }
References icSigResponseCurveSet16Type.
Referenced by CIccTagResponseCurveSet16::Write().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
virtual CIccTag * CIccTagResponseCurveSet16::NewCopy () const inline virtual inherited
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
{return new CIccTagResponseCurveSet16(*this);}
References CIccTagResponseCurveSet16::CIccTagResponseCurveSet16().
NewResponseCurves()
CIccResponseCurveStruct * CIccTagResponseCurveSet16::NewResponseCurves (icMeasurementUnitSig sig) inherited
Name: CIccTagResponseCurveSet16::NewResponseCurves
Purpose: Creates and adds a new set of response curves to the list. SetNumChannels() must be called before calling this function.
Args: sig = measurement unit signature
{
  if (!m_nChannels)
    return NULL;
  CIccResponseCurveStruct *pResponseCurveStruct;
  pResponseCurveStruct = GetResponseCurves(sig);
  if (pResponseCurveStruct)
    return pResponseCurveStruct;
  CIccResponseCurveStruct entry;
  entry = CIccResponseCurveStruct(sig, m_nChannels);
  m_ResponseCurves->push_back(entry);
  m_Curve->inited = false;
  return GetResponseCurves(sig);
}
References CIccResponseCurveStruct::CIccResponseCurveStruct(), CIccTagResponseCurveSet16::GetResponseCurves(), CIccResponseCurveSetIter::inited, CIccTagResponseCurveSet16::m_Curve, CIccTagResponseCurveSet16::m_nChannels, CIccTagResponseCurveSet16::m_ResponseCurves, and CIccResponseCurveStruct::operator=().
ParseXml()
bool CIccTagXmlResponseCurveSet16::ParseXml (xmlNode * pNode, std::string & parseStr) virtual
Implements CIccTagXml.
{
  pNode = icXmlFindNode(pNode, "CountOfChannels");
  if(!pNode)
    return false;
  int nChannels = atoi((const char*)pNode->children->content);
  SetNumChannels(nChannels);
  if (!m_ResponseCurves)
    return false;
  if (!m_ResponseCurves->empty())
    m_ResponseCurves->clear();
  for (pNode = pNode->next; pNode; pNode = pNode->next) {
    if (pNode->type==XML_ELEMENT_NODE && !icXmlStrCmp(pNode->name, "ResponseCurve")) {
      const icChar *szMeasurmentType = icXmlAttrValue(pNode, "MeasUnitSignature");
      if (nChannels != icXmlNodeCount(pNode->children, "ChannelResponses"))
        return false;
      CIccResponseCurveStruct curves(icGetMeasurementValue(szMeasurmentType), nChannels);
      xmlNode *pChild, *pMeasurement;
      int i;
      for (i=0, pChild = pNode->children; pChild; pChild = pChild->next) {
        if (pChild->type == XML_ELEMENT_NODE && !icXmlStrCmp(pChild->name, "ChannelResponses")) {
          CIccResponse16List *pResponseList = curves.GetResponseList(i);
          icXYZNumber *pXYZ = curves.GetXYZ(i);
          icResponse16Number response;
          const icChar *szX = icXmlAttrValue(pChild, "X");
          const icChar *szY = icXmlAttrValue(pChild, "Y");
          const icChar *szZ = icXmlAttrValue(pChild, "Z");
          if (!szX || !szY || !szZ || !*szX || !*szY || !*szZ)
            return false;
          pXYZ->X = icDtoF((icFloatNumber)atof(szX));
          pXYZ->Y = icDtoF((icFloatNumber)atof(szY));
          pXYZ->Z = icDtoF((icFloatNumber)atof(szZ));
          for (pMeasurement = pChild->children; pMeasurement; pMeasurement = pMeasurement->next) {
            if (pMeasurement->type == XML_ELEMENT_NODE && !icXmlStrCmp(pMeasurement->name, "Measurement")) {
              const icChar *szDeviceCode = icXmlAttrValue(pMeasurement, "DeviceCode");
              const icChar *szValue = icXmlAttrValue(pMeasurement, "MeasValue");
              const icChar *szReserved = icXmlAttrValue(pMeasurement, "Reserved");
              if (!szDeviceCode || !szValue || !*szDeviceCode || !*szValue)
                return false;
              response.deviceCode = (icUInt16Number)atoi(szDeviceCode);
              response.measurementValue = icDtoF((icFloatNumber)atof(szValue));
              if (szReserved && *szReserved)
                response.reserved = atoi(szReserved);
              pResponseList->push_back(response);
            }
          }
          i++;
        }
      }
      m_ResponseCurves->push_back(curves);
    }
  }
  return true;
}
References CIccResponseCurveStruct::CIccResponseCurveStruct(), icResponse16Number::deviceCode, CIccResponseCurveStruct::GetResponseList(), CIccResponseCurveStruct::GetXYZ(), icDtoF(), icGetMeasurementValue(), icXmlAttrValue(), icXmlFindNode(), icXmlNodeCount(), CIccTagResponseCurveSet16::m_ResponseCurves, icResponse16Number::measurementValue, icResponse16Number::reserved, CIccTagResponseCurveSet16::SetNumChannels(), icXYZNumber::X, icXYZNumber::Y, and icXYZNumber::Z.
Read() [1/2]
bool CIccTagResponseCurveSet16::Read (icUInt32Number size, CIccIO * pIO) virtual inherited
Name: CIccTagResponseCurveSet16::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  icUInt32Number startPos = pIO->Tell();
  unsigned long headerSize = sizeof(icTagTypeSignature) +
                             sizeof(icUInt32Number) +
                             sizeof(icUInt16Number) * 2;
  if (headerSize > size)
    return false;
  if (!pIO) {
    return false;
  }
  if (!pIO->Read32(&sig) ||
      !pIO->Read32(&m_nReserved))
    return false;
  icUInt16Number nCountMeasmntTypes;
  if (!pIO->Read16(&m_nChannels) ||
      !pIO->Read16(&nCountMeasmntTypes))
    return false;
  if ((icUInt32Number)nCountMeasmntTypes * sizeof(icUInt32Number) > size - headerSize)
    return false;
  icUInt32Number* nOffset = new icUInt32Number[nCountMeasmntTypes];
  if (pIO->Read32(&nOffset[0], nCountMeasmntTypes) != nCountMeasmntTypes) {
    delete[] nOffset;
    return false;
  }
  CIccResponseCurveStruct entry;
  for (icUInt16Number i=0; i<nCountMeasmntTypes; i++) {
    if (nOffset[i] + 4 > size) {
      delete[] nOffset;
      return false;
    }
    pIO->Seek(startPos + nOffset[i], icSeekSet);
    entry = CIccResponseCurveStruct(m_nChannels);
    if (!entry.Read(size-nOffset[i], pIO)) {
      delete[] nOffset;
      return false;
    }
    m_ResponseCurves->push_back(entry);
  }
  delete[] nOffset;
  m_Curve->inited = false;
  return true;
}
References CIccResponseCurveStruct::CIccResponseCurveStruct(), icSeekSet, CIccResponseCurveSetIter::inited, CIccTagResponseCurveSet16::m_Curve, CIccTagResponseCurveSet16::m_nChannels, CIccTag::m_nReserved, CIccTagResponseCurveSet16::m_ResponseCurves, CIccResponseCurveStruct::operator=(), CIccResponseCurveStruct::Read(), CIccIO::Read16(), CIccIO::Read32(), CIccIO::Seek(), and CIccIO::Tell().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
SetNumChannels()
void CIccTagResponseCurveSet16::SetNumChannels (icUInt16Number nChannels) inherited
Name: CIccTagResponseCurveSet16::SetNumChannels
Purpose: Sets the number of channels. This will delete any prior Response curves from the set.
Args: nChannels = number of channels
{
  m_nChannels = nChannels;
  if (!m_ResponseCurves->empty())
    m_ResponseCurves->clear();
}
References CIccTagResponseCurveSet16::m_nChannels, and CIccTagResponseCurveSet16::m_ResponseCurves.
Referenced by ParseXml().
ToXml()
bool CIccTagXmlResponseCurveSet16::ToXml (std::string & xml, std::string blanks = "") virtual
Implements CIccTagXml.
{
  char line[80];
  int i;
  CIccInfo info;
  sprintf(line, "<CountOfChannels>%d</CountOfChannels>\n", m_nChannels);
  xml += blanks + line;
  CIccResponseCurveStruct *pCurves=GetFirstCurves();
  while (pCurves) {
    sprintf(line, "<ResponseCurve MeasUnitSignature=\"%s\">\n", info.GetMeasurementUnit(pCurves->GetMeasurementType()));
    xml += blanks + line;
    for (i=0; i<pCurves->GetNumChannels(); i++) {
      CIccResponse16List *pResponseList = pCurves->GetResponseList(i);
      icXYZNumber *pXYZ = pCurves->GetXYZ(i);
      sprintf(line, "    <ChannelResponses X=\"" icXmlFloatFmt "\" Y=\"" icXmlFloatFmt "\" Z=\"" icXmlFloatFmt "\" >\n", icFtoD(pXYZ->X), icFtoD(pXYZ->Y), icFtoD(pXYZ->Z));
      xml += blanks + line;
      CIccResponse16List::iterator j;
      for (j=pResponseList->begin(); j!=pResponseList->end(); j++) {
        sprintf(line, "      <Measurement DeviceCode=\"%d\" MeasValue=\"" icXmlFloatFmt "\"", j->deviceCode, icFtoD(j->measurementValue));
        xml += blanks + line;
        if (j->reserved) {
          sprintf(line, " Reserved=\"%d\"", j->reserved);
          xml += line;
        }
        xml += "/>\n";
      }
      xml += blanks + "    </ChannelResponses>\n";
    }
    xml += blanks + "  </ResponseCurve>\n";
    pCurves = GetNextCurves();
  }
  return true;
}
References icResponse16Number::deviceCode, CIccTagResponseCurveSet16::GetFirstCurves(), CIccResponseCurveStruct::GetMeasurementType(), CIccInfo::GetMeasurementUnit(), CIccTagResponseCurveSet16::GetNextCurves(), CIccResponseCurveStruct::GetNumChannels(), CIccResponseCurveStruct::GetResponseList(), CIccResponseCurveStruct::GetXYZ(), icFtoD(), CIccTagResponseCurveSet16::m_nChannels, icResponse16Number::measurementValue, icResponse16Number::reserved, icXYZNumber::X, icXYZNumber::Y, and icXYZNumber::Z.
Validate()
icValidateStatus CIccTagResponseCurveSet16::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual inherited
Name: CIccTagResponseCurveSet16::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  if (!pProfile) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " - Tag validation incomplete: Pointer to profile unavailable.\n";
    rv = icMaxStatus(rv, icValidateWarning);
    return rv;
  }
  if (m_nChannels!=icGetSpaceSamples(pProfile->m_Header.colorSpace)) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " - Incorrect number of channels.\n";
  }
  if (!GetNumResponseCurveTypes()) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " - Empty Tag!.\n";
    rv = icMaxStatus(rv, icValidateWarning);
  }
  else {
    CIccResponseCurveSet::iterator i;
    for (i=m_ResponseCurves->begin(); i!=m_ResponseCurves->end(); i++) {
      rv = icMaxStatus(rv, i->Validate(sReport));
    }
  }
  return rv;
}
References icHeader::colorSpace, CIccTagResponseCurveSet16::GetNumResponseCurveTypes(), CIccInfo::GetSigPathName(), icGetSpaceSamples(), icMaxStatus(), icMsgValidateWarning, icValidateWarning, CIccTagResponseCurveSet16::m_nChannels, CIccTagResponseCurveSet16::m_ResponseCurves, CIccResponseCurveStruct::Validate(), and CIccTag::Validate().
Write()
bool CIccTagResponseCurveSet16::Write (CIccIO * pIO) virtual inherited
Name: CIccTagResponseCurveSet16::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  icUInt16Number nCountMeasmntTypes = (icUInt16Number)m_ResponseCurves->size();
  if (!pIO) {
    return false;
  }
  icUInt32Number startPos = pIO->GetLength();
  if (!pIO->Write32(&sig) ||
      !pIO->Write32(&m_nReserved))
    return false;
  if (!pIO->Write16(&m_nChannels) ||
      !pIO->Write16(&nCountMeasmntTypes))
    return false;
  icUInt32Number offsetPos = pIO->GetLength();
  icUInt32Number* nOffset = new icUInt32Number[nCountMeasmntTypes];
  int j;
  for (j=0; j<nCountMeasmntTypes; j++) {
    nOffset[j] = 0;
    if (!pIO->Write32(&nOffset[j]))
      return false;
  }
  CIccResponseCurveSet::iterator i;
  for (i=m_ResponseCurves->begin(), j=0; i!=m_ResponseCurves->end(); i++, j++) {
    nOffset[j] = pIO->GetLength() - startPos;
    if (!i->Write(pIO))
      return false;
  }
  icUInt32Number curPOs = pIO->GetLength();
  pIO->Seek(offsetPos,icSeekSet);
  for (j=0; j<nCountMeasmntTypes; j++) {
    if (!pIO->Write32(&nOffset[j]))
      return false;
  }
  pIO->Seek(curPOs,icSeekSet);
  delete [] nOffset;
  return true;
}
References CIccIO::GetLength(), CIccTagResponseCurveSet16::GetType(), icSeekSet, CIccTagResponseCurveSet16::m_nChannels, CIccTag::m_nReserved, CIccTagResponseCurveSet16::m_ResponseCurves, CIccIO::Seek(), CIccResponseCurveStruct::Write(), CIccIO::Write16(), and CIccIO::Write32().
Field Documentation
m_Curve
CIccResponseCurveSetIter* CIccTagResponseCurveSet16::m_Curve protected inherited
Referenced by CIccTagResponseCurveSet16::CIccTagResponseCurveSet16(), CIccTagResponseCurveSet16::CIccTagResponseCurveSet16(), CIccTagResponseCurveSet16::~CIccTagResponseCurveSet16(), CIccTagResponseCurveSet16::GetFirstCurves(), CIccTagResponseCurveSet16::GetNextCurves(), CIccTagResponseCurveSet16::NewResponseCurves(), CIccTagResponseCurveSet16::operator=(), and CIccTagResponseCurveSet16::Read().
m_nChannels
icUInt16Number CIccTagResponseCurveSet16::m_nChannels protected inherited
Referenced by CIccTagResponseCurveSet16::CIccTagResponseCurveSet16(), CIccTagResponseCurveSet16::CIccTagResponseCurveSet16(), CIccTagResponseCurveSet16::Describe(), CIccTagResponseCurveSet16::GetNumChannels(), CIccTagResponseCurveSet16::GetResponseCurves(), CIccTagResponseCurveSet16::NewResponseCurves(), CIccTagResponseCurveSet16::operator=(), CIccTagResponseCurveSet16::Read(), CIccTagResponseCurveSet16::SetNumChannels(), ToXml(), CIccTagResponseCurveSet16::Validate(), and CIccTagResponseCurveSet16::Write().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_ResponseCurves
CIccResponseCurveSet* CIccTagResponseCurveSet16::m_ResponseCurves protected inherited
Referenced by CIccTagResponseCurveSet16::CIccTagResponseCurveSet16(), CIccTagResponseCurveSet16::CIccTagResponseCurveSet16(), CIccTagResponseCurveSet16::~CIccTagResponseCurveSet16(), CIccTagResponseCurveSet16::Describe(), CIccTagResponseCurveSet16::GetFirstCurves(), CIccTagResponseCurveSet16::GetNextCurves(), CIccTagResponseCurveSet16::GetNumResponseCurveTypes(), CIccTagResponseCurveSet16::GetResponseCurves(), CIccTagResponseCurveSet16::NewResponseCurves(), CIccTagResponseCurveSet16::operator=(), ParseXml(), CIccTagResponseCurveSet16::Read(), CIccTagResponseCurveSet16::SetNumChannels(), CIccTagResponseCurveSet16::Validate(), and CIccTagResponseCurveSet16::Write().
The documentation for this class was generated from the following files:
IccXML/IccLibXML/IccTagXml.h
IccXML/IccLibXML/IccTagXml.cpp