iccDEV: CIccApplyTagMpe Class Reference
CIccApplyTagMpe Class Reference
#include <IccTagMPE.h>
Public Member Functions
CIccApplyTagMpe (CIccTagMultiProcessElement *pTag)
virtual ~CIccApplyTagMpe ()
virtual bool AppendElem (CIccMultiProcessElement *pElem)
CIccApplyMpeIter begin ()
CIccApplyMpeIter end ()
CIccDblPixelBuffer * GetBuf ()
CIccApplyMpeList * GetList ()
CIccTagMultiProcessElement * GetTag ()
Protected Attributes
CIccDblPixelBuffer m_applyBuf
CIccApplyMpeList * m_list
CIccTagMultiProcessElement * m_pTag
Detailed Description
Class: CIccTagMultiProcessElement
Purpose: Apply storage for MPE general purpose processing tags
Constructor & Destructor Documentation
CIccApplyTagMpe()
CIccApplyTagMpe::CIccApplyTagMpe (CIccTagMultiProcessElement * pTag)
Name: CIccApplyTagMpe::CIccApplyTagMpe
Purpose:
Args:
Return:
{
  m_pTag = pTag;
  m_list = NULL;
}
References m_list, and m_pTag.
Referenced by CIccTagMultiProcessElement::GetNewApply().
~CIccApplyTagMpe()
CIccApplyTagMpe::~CIccApplyTagMpe () virtual
Name: CIccApplyTagMpe::~CIccApplyTagMpe
Purpose:
Args:
Return:
{
  if (m_list) {
    CIccApplyMpeList::iterator i;
    for (i=m_list->begin(); i!=m_list->end(); i++) {
      delete i->ptr;
    }
    delete m_list;
  }
}
References m_list, and CIccApplyMpePtr::ptr.
Member Function Documentation
AppendElem()
bool CIccApplyTagMpe::AppendElem (CIccMultiProcessElement * pElem) virtual
Name: CIccApplyTagMpe::CIccApplyTagMpe
Purpose:
Args:
Return:
{
  if (!m_list)
    m_list = new CIccApplyMpeList();
  if (!m_list)
    return false;
  CIccApplyMpe *pApply = pElem->GetNewApply(this);
  if (!pApply)
    return false;
  CIccApplyMpePtr ptr;
  ptr.ptr = pApply;
  m_list->push_back(ptr);
  return true;
}
References CIccMultiProcessElement::GetNewApply(), m_list, and CIccApplyMpePtr::ptr.
Referenced by CIccTagMultiProcessElement::GetNewApply().
begin()
CIccApplyMpeIter CIccApplyTagMpe::begin () inline
{ return m_list->begin(); }
References m_list.
Referenced by CIccTagMultiProcessElement::Apply().
end()
CIccApplyMpeIter CIccApplyTagMpe::end () inline
{ return m_list->end(); }
References m_list.
Referenced by CIccTagMultiProcessElement::Apply().
GetBuf()
CIccDblPixelBuffer * CIccApplyTagMpe::GetBuf () inline
{ return &m_applyBuf; }
References m_applyBuf.
Referenced by CIccTagMultiProcessElement::Apply(), and CIccTagMultiProcessElement::GetNewApply().
GetList()
CIccApplyMpeList * CIccApplyTagMpe::GetList () inline
{ return m_list; }
References m_list.
Referenced by CIccTagMultiProcessElement::Apply(), and main().
GetTag()
CIccTagMultiProcessElement * CIccApplyTagMpe::GetTag () inline
{ return m_pTag; }
References m_pTag.
Field Documentation
m_applyBuf
CIccDblPixelBuffer CIccApplyTagMpe::m_applyBuf protected
Referenced by GetBuf().
m_list
CIccApplyMpeList* CIccApplyTagMpe::m_list protected
Referenced by CIccApplyTagMpe(), ~CIccApplyTagMpe(), AppendElem(), begin(), end(), and GetList().
m_pTag
CIccTagMultiProcessElement* CIccApplyTagMpe::m_pTag protected
Referenced by CIccApplyTagMpe(), and GetTag().
The documentation for this class was generated from the following files:
IccProfLib/IccTagMPE.h
IccProfLib/IccTagMPE.cpp