iccDEV: CIccXformCreator Class Reference
CIccXformCreator Class Reference
#include <IccXformFactory.h>
Public Member Functions
~CIccXformCreator ()
Static Public Member Functions
static CIccXform * CreateXform (icXformType xformType, CIccTag *pTag=NULL, CIccCreateXformHintManager *pHintManager=NULL)
static IIccXformFactory * PopFactory ()
static void PushFactory (IIccXformFactory *pFactory)
Private Member Functions
CIccXformCreator ()
CIccXform * DoCreateXform (icXformType xformType, CIccTag *pTag=NULL, CIccCreateXformHintManager *pHintManager=NULL)
IIccXformFactory * DoPopFactory (bool bAll=false)
void DoPushFactory (IIccXformFactory *pFactory)
Static Private Member Functions
static CIccXformCreator * GetInstance ()
Private Attributes
CIccXformFactoryList factoryStack
Static Private Attributes
static CIccXformCreatorPtr theXformCreator
Detailed Description
Class: CIccXformCreator
Purpose: CIccXformCreator uses a singleton pattern to provide dynamically upgradeable CIccXform derived object creation based on xform type.
Constructor & Destructor Documentation
~CIccXformCreator()
CIccXformCreator::~CIccXformCreator ()
{
  IIccXformFactory *pFactory = DoPopFactory(true);
  while (pFactory) {
    delete pFactory;
    pFactory = DoPopFactory(true);
  }
}
References DoPopFactory().
CIccXformCreator()
CIccXformCreator::CIccXformCreator () inline private
Only GetInstance() can create the signleton
{ }
Member Function Documentation
CreateXform()
static CIccXform * CIccXformCreator::CreateXform (icXformType xformType, CIccTag * pTag = NULL, CIccCreateXformHintManager * pHintManager = NULL) inline static
Function: CreateXform(xformTypeSig) Create a xform of type xformTypeSig.
Parameter(s): xformType = signature of the ICC xform type for the xform to be created pTag = tag information for created xform pHintManager = contains additional information used to create xform
Returns a new CIccXform object of the given xform type. Each factory in the factoryStack is used until a factory supports the signature type.
      { return CIccXformCreator::GetInstance()->DoCreateXform(xformType, pTag, pHintManager); }
References DoCreateXform(), and GetInstance().
DoCreateXform()
CIccXform * CIccXformCreator::DoCreateXform (icXformType xformType, CIccTag * pTag = NULL, CIccCreateXformHintManager * pHintManager = NULL) private
{
  CIccXformFactoryList::iterator i;
  CIccXform *rv = NULL;
  for (i=factoryStack.begin(); i!=factoryStack.end(); i++) {
    rv = (*i)->CreateXform(xformTypeSig, pTag, pHintManager);
    if (rv)
      break;
  }
  return rv;
}
References IIccXformFactory::CreateXform(), and factoryStack.
Referenced by CreateXform().
DoPopFactory()
IIccXformFactory * CIccXformCreator::DoPopFactory (bool bAll = false) private
{
  //int nNum = (bAll ? 0 : 1);
  if (factoryStack.size()>0) {
    CIccXformFactoryList::iterator i=factoryStack.begin();
    IIccXformFactory* rv = (*i);
    factoryStack.pop_front();
    return rv;
  }
  return NULL;
}
References factoryStack.
Referenced by ~CIccXformCreator(), and PopFactory().
DoPushFactory()
void CIccXformCreator::DoPushFactory (IIccXformFactory * pFactory) private
{
  factoryStack.push_front(pFactory);
}
References factoryStack.
Referenced by GetInstance(), and PushFactory().
GetInstance()
CIccXformCreator * CIccXformCreator::GetInstance () static private
Function: GetInstance() Private static function to access singleton CiccXformCreator Object.
Parameter(s): None
Returns the singleton CIccXformCreator object. It will allocate a new one and push a single CIccSpecXform Factory object onto the factory stack if the singleton has not been intialized.
{
  if (!theXformCreator.get()) {
    theXformCreator = CIccXformCreatorPtr(new CIccXformCreator);
    theXformCreator->DoPushFactory(new CIccBaseXformFactory);
  }
  return theXformCreator.get();
}
References DoPushFactory(), and theXformCreator.
Referenced by CreateXform(), PopFactory(), and PushFactory().
PopFactory()
static IIccXformFactory * CIccXformCreator::PopFactory () inline static
Function: PopFactory() Remove the top IIccXformFactory from the stack of xform factories tracked by the system.
Parameter(s): None
Returns the top IIccXformFactory from the stack of xform factories tracked by the system. The returned xform factory is no longer owned by the system and needs to be deleted to avoid memory leaks.
Note: The initial CIccSpecXformFactory cannot be popped off the stack.
      { return CIccXformCreator::GetInstance()->DoPopFactory(); }
References DoPopFactory(), and GetInstance().
PushFactory()
static void CIccXformCreator::PushFactory (IIccXformFactory * pFactory) inline static
Function: PushFactory(pFactory) Add an IIccXformFactory to the stack of xform factories tracked by the system.
Parameter(s): pFactory = pointer to an IIccXformFactory object to add to the system. The pFactory must be created with new, and will be owned CIccXformCreator until popped off the stack using PopFactory(). Any factories not popped off will be taken care of properly on application shutdown.
      { CIccXformCreator::GetInstance()->CIccXformCreator::DoPushFactory(pFactory); }
References DoPushFactory(), and GetInstance().
Field Documentation
factoryStack
CIccXformFactoryList CIccXformCreator::factoryStack private
Referenced by DoCreateXform(), DoPopFactory(), and DoPushFactory().
theXformCreator
std::unique_ptr< CIccXformCreator > CIccXformCreator::theXformCreator static private
Referenced by GetInstance().
The documentation for this class was generated from the following files:
IccProfLib/IccXformFactory.h
IccProfLib/IccXformFactory.cpp