iccDEV: IccProfLib/IccSignatureUtils.h File Reference
IccSignatureUtils.h File Reference
#include "IccDefs.h"
#include <cstdint>
#include <cstdio>
#include <cmath>
Data Structures
struct IccColorSpaceDescription
Macros
#define ICC_ASSERT(expr, desc) ((void)0)
#define ICC_LOG_DEBUG(...) do { fprintf(stderr, "ICC_DEBUG: [%s:%d] ", __FILE__, __LINE__); fprintf(stderr, __VA_ARGS__); fputc('\n', stderr); } while(0)
#define ICC_LOG_ERROR(...) do { fprintf(stderr, "ICC_ERROR: [%s:%d] ", __FILE__, __LINE__); fprintf(stderr, __VA_ARGS__); fputc('\n', stderr); } while(0)
#define ICC_LOG_FLOAT_BITS(val, label)
#define ICC_LOG_INFO(...) do { fprintf(stderr, "ICC_INFO: [%s:%d] ", __FILE__, __LINE__); fprintf(stderr, __VA_ARGS__); fputc('\n', stderr); } while(0)
#define ICC_LOG_SAFE_VAL(name, idx, basePtr, limit) ((void)0)
#define ICC_LOG_WARNING(...) do { fprintf(stderr, "ICC_WARN: [%s:%d] ", __FILE__, __LINE__); fprintf(stderr, __VA_ARGS__); fputc('\n', stderr); } while(0)
#define ICC_SAFE_FLOAT_LOG(label, val_expr) do { ICC_LOG_DEBUG(label, val_expr); } while(0)
#define ICC_SANITY_CHECK_SIGNATURE(sig, label)
#define ICC_SIGNATURE_UTILS_H
#define ICC_TRACE_NAN(val, label) ((void)0)
#define icSigSpectralPcsData ((icColorSpaceSignature)0x73706320)
#define TRACE_CALLER() ((void)0)
#define TRACE_LOG(msg, ...) ICC_LOG_WARNING(msg, ##__VA_ARGS__)
Functions
const char * ColorSpaceSignatureToStr (icUInt32Number sig)
void DebugColorSpaceMeta (icUInt32Number sig)
IccColorSpaceDescription DescribeColorSpaceSignature (icUInt32Number sig)
bool IsSpaceSpectralPCS (icColorSpaceSignature sig)
bool IsValidColorSpaceSignature (icUInt32Number sig)
bool IsValidTechnologySignature (icUInt32Number sig)
Detailed Description
File: IccSignatureUtils.h
Contains: Implementation of definitions and macros for ICC signature logging.
Version: V1
Copyright: (c) see ICC Software License
Definition in file IccSignatureUtils.h.
Data Structure Documentation
IccColorSpaceDescription
struct IccColorSpaceDescription
Data Fields
char bytes[5]
bool isKnown
const char * name
Macro Definition Documentation
ICC_ASSERT
#define ICC_ASSERT (expr, desc) ((void)0)
ICC_LOG_DEBUG
#define ICC_LOG_DEBUG (...) do { fprintf(stderr, "ICC_DEBUG: [%s:%d] ", __FILE__, __LINE__); fprintf(stderr, __VA_ARGS__); fputc('\n', stderr); } while(0)
       { fprintf(stderr, "ICC_DEBUG: [%s:%d] ", __FILE__, __LINE__); fprintf(stderr, __VA_ARGS__); fputc('\n', stderr); } while(0)
ICC_LOG_ERROR
#define ICC_LOG_ERROR (...) do { fprintf(stderr, "ICC_ERROR: [%s:%d] ", __FILE__, __LINE__); fprintf(stderr, __VA_ARGS__); fputc('\n', stderr); } while(0)
       { fprintf(stderr, "ICC_ERROR: [%s:%d] ", __FILE__, __LINE__); fprintf(stderr, __VA_ARGS__); fputc('\n', stderr); } while(0)
ICC_LOG_FLOAT_BITS
#define ICC_LOG_FLOAT_BITS (val, label)
Value:
  do { \
    union { float f; uint32_t u; } raw; \
    raw.f = static_cast<float>(val); \
    ICC_LOG_DEBUG("%s: float=%.8f bits=0x%08x", label, raw.f, raw.u); \
  } while(0)
     { \
    union { float f; uint32_t u; } raw; \
    raw.f = static_cast<float>(val); \
    ICC_LOG_DEBUG("%s: float=%.8f bits=0x%08x", label, raw.f, raw.u); \
  } while(0)
ICC_LOG_INFO
#define ICC_LOG_INFO (...) do { fprintf(stderr, "ICC_INFO: [%s:%d] ", __FILE__, __LINE__); fprintf(stderr, __VA_ARGS__); fputc('\n', stderr); } while(0)
       { fprintf(stderr, "ICC_INFO: [%s:%d] ", __FILE__, __LINE__); fprintf(stderr, __VA_ARGS__); fputc('\n', stderr); } while(0)
ICC_LOG_SAFE_VAL
#define ICC_LOG_SAFE_VAL (name, idx, basePtr, limit) ((void)0)
ICC_LOG_WARNING
#define ICC_LOG_WARNING (...) do { fprintf(stderr, "ICC_WARN: [%s:%d] ", __FILE__, __LINE__); fprintf(stderr, __VA_ARGS__); fputc('\n', stderr); } while(0)
       { fprintf(stderr, "ICC_WARN: [%s:%d] ", __FILE__, __LINE__); fprintf(stderr, __VA_ARGS__); fputc('\n', stderr); } while(0)
ICC_SAFE_FLOAT_LOG
#define ICC_SAFE_FLOAT_LOG (label, val_expr) do { ICC_LOG_DEBUG(label, val_expr); } while(0)
     { ICC_LOG_DEBUG(label, val_expr); } while(0)
ICC_SANITY_CHECK_SIGNATURE
#define ICC_SANITY_CHECK_SIGNATURE (sig, label)
Value:
  do { \
    if (((sig) & 0xFF000000) == 0x3F000000) { \
      ICC_LOG_WARNING("%s: suspicious signature 0x%08x", \
                      label, (uint32_t)(sig)); \
      assert(false && "Suspicious or uninitialized signature"); \
    } \
  } while(0)
     { \
    if (((sig) & 0xFF000000) == 0x3F000000) { \
      ICC_LOG_WARNING("%s: suspicious signature 0x%08x", \
                      label, (uint32_t)(sig)); \
      assert(false && "Suspicious or uninitialized signature"); \
    } \
  } while(0)
ICC_SIGNATURE_UTILS_H
#define ICC_SIGNATURE_UTILS_H
ICC_TRACE_NAN
#define ICC_TRACE_NAN (val, label) ((void)0)
icSigSpectralPcsData
#define icSigSpectralPcsData ((icColorSpaceSignature)0x73706320)
TRACE_CALLER
#define TRACE_CALLER () ((void)0)
TRACE_LOG
#define TRACE_LOG (msg, ...) ICC_LOG_WARNING(msg, ##__VA_ARGS__)
Function Documentation
ColorSpaceSignatureToStr()
const char * ColorSpaceSignatureToStr (icUInt32Number sig) inline
{
  switch (sig) {
    case (icUInt32Number)icSigXYZData:    return "XYZ";
    case (icUInt32Number)icSigLabData:    return "Lab";
    case (icUInt32Number)icSigRgbData:    return "RGB";
    case (icUInt32Number)icSigCmykData:   return "CMYK";
    case (icUInt32Number)icSigGrayData:   return "Gray";
    case (icUInt32Number)icSigNamedData:  return "Named";
    case (icUInt32Number)icSigMCH1Data:   return "MCH1";
    case (icUInt32Number)icSigMCH2Data:   return "MCH2";
    case (icUInt32Number)icSigMCH3Data:   return "MCH3";
    case (icUInt32Number)icSigMCH4Data:   return "MCH4";
    case (icUInt32Number)icSigMCH5Data:   return "MCH5";
    case (icUInt32Number)icSigMCH6Data:   return "MCH6";
    case (icUInt32Number)icSigMCH7Data:   return "MCH7";
    case (icUInt32Number)icSigMCH8Data:   return "MCH8";
    case (icUInt32Number)icSigMCH9Data:   return "MCH9";
    default:                              return "Unknown";
  }
}
References icSigCmykData, icSigGrayData, icSigLabData, icSigMCH1Data, icSigMCH2Data, icSigMCH3Data, icSigMCH4Data, icSigMCH5Data, icSigMCH6Data, icSigMCH7Data, icSigMCH8Data, icSigMCH9Data, icSigNamedData, icSigRgbData, and icSigXYZData.
Referenced by DescribeColorSpaceSignature(), and IsValidColorSpaceSignature().
DebugColorSpaceMeta()
void DebugColorSpaceMeta (icUInt32Number sig) inline
{
  IccColorSpaceDescription desc = DescribeColorSpaceSignature(sig);
  ICC_LOG_INFO("Signature 0x%08x [%s]: known=%d, bytes='%s'",
               sig, desc.name, desc.isKnown, desc.bytes);
}
References IccColorSpaceDescription::bytes, DescribeColorSpaceSignature(), IccColorSpaceDescription::isKnown, and IccColorSpaceDescription::name.
DescribeColorSpaceSignature()
IccColorSpaceDescription DescribeColorSpaceSignature (icUInt32Number sig) inline
{
  IccColorSpaceDescription desc;
  desc.name = ColorSpaceSignatureToStr(sig);
  desc.isKnown = IsValidColorSpaceSignature(sig);
  desc.bytes[0] = (sig >> 24) & 0xFF;
  desc.bytes[1] = (sig >> 16) & 0xFF;
  desc.bytes[2] = (sig >> 8) & 0xFF;
  desc.bytes[3] = sig & 0xFF;
  desc.bytes[4] = '\0';
  return desc;
}
References IccColorSpaceDescription::bytes, ColorSpaceSignatureToStr(), IccColorSpaceDescription::isKnown, IsValidColorSpaceSignature(), and IccColorSpaceDescription::name.
Referenced by DebugColorSpaceMeta().
IsSpaceSpectralPCS()
bool IsSpaceSpectralPCS (icColorSpaceSignature sig) inline
{
  return sig == icSigSpectralPcsData;
}
IsValidColorSpaceSignature()
bool IsValidColorSpaceSignature (icUInt32Number sig) inline
{
  // Log incoming value and its decoded name for debug traceability
  ICC_LOG_DEBUG("IsValidColorSpaceSignature(): input = 0x%08x (%s)", sig, ColorSpaceSignatureToStr(sig));
  switch (sig) {
    case (icUInt32Number)icSigXYZData:
    case (icUInt32Number)icSigLabData:
    case (icUInt32Number)icSigRgbData:
    case (icUInt32Number)icSigCmykData:
    case (icUInt32Number)icSigGrayData:
    case (icUInt32Number)icSigNamedData:
    case (icUInt32Number)icSigMCH1Data:
    case (icUInt32Number)icSigMCH2Data:
    case (icUInt32Number)icSigMCH3Data:
    case (icUInt32Number)icSigMCH4Data:
    case (icUInt32Number)icSigMCH5Data:
    case (icUInt32Number)icSigMCH6Data:
    case (icUInt32Number)icSigMCH7Data:
    case (icUInt32Number)icSigMCH8Data:
    case (icUInt32Number)icSigMCH9Data:
      return true;
    default:
      // Emit structured warning with signature details
      ICC_LOG_WARNING("IccSignatureUtils.h: ColorSpace signature: 0x%08x (%s)",
                      sig, ColorSpaceSignatureToStr(sig));
      return false;
  }
}
References ColorSpaceSignatureToStr(), icSigCmykData, icSigGrayData, icSigLabData, icSigMCH1Data, icSigMCH2Data, icSigMCH3Data, icSigMCH4Data, icSigMCH5Data, icSigMCH6Data, icSigMCH7Data, icSigMCH8Data, icSigMCH9Data, icSigNamedData, icSigRgbData, and icSigXYZData.
Referenced by DescribeColorSpaceSignature().
IsValidTechnologySignature()
bool IsValidTechnologySignature (icUInt32Number sig) inline
{
  ICC_LOG_DEBUG("IsValidTechnologySignature(): input = 0x%08x", sig);
  switch (sig) {
    case (icUInt32Number)icSigDigitalCamera:
    case (icUInt32Number)icSigFilmScanner:
    case (icUInt32Number)icSigReflectiveScanner:
    case (icUInt32Number)icSigInkJetPrinter:
    case (icUInt32Number)icSigThermalWaxPrinter:
    case (icUInt32Number)icSigElectrophotographicPrinter:
    case (icUInt32Number)icSigElectrostaticPrinter:
    case (icUInt32Number)icSigDyeSublimationPrinter:
    case (icUInt32Number)icSigPhotographicPaperPrinter:
    case (icUInt32Number)icSigFilmWriter:
    case (icUInt32Number)icSigVideoMonitor:
    case (icUInt32Number)icSigVideoCamera:
    case (icUInt32Number)icSigProjectionTelevision:
    case (icUInt32Number)icSigCRTDisplay:
    case (icUInt32Number)icSigPMDisplay:
    case (icUInt32Number)icSigAMDisplay:
    case (icUInt32Number)icSigPhotoCD:
    case (icUInt32Number)icSigPhotoImageSetter:
    case (icUInt32Number)icSigGravure:
    case (icUInt32Number)icSigOffsetLithography:
    case (icUInt32Number)icSigSilkscreen:
    case (icUInt32Number)icSigFlexography:
      return true;
    default:
      ICC_LOG_WARNING("IccSignatureUtils.h: Invalid Technology signature: 0x%08x", sig);
      return false;
  }
}
References icSigAMDisplay, icSigCRTDisplay, icSigDigitalCamera, icSigDyeSublimationPrinter, icSigElectrophotographicPrinter, icSigElectrostaticPrinter, icSigFilmScanner, icSigFilmWriter, icSigFlexography, icSigGravure, icSigInkJetPrinter, icSigOffsetLithography, icSigPhotoCD, icSigPhotographicPaperPrinter, icSigPhotoImageSetter, icSigPMDisplay, icSigProjectionTelevision, icSigReflectiveScanner, icSigSilkscreen, icSigThermalWaxPrinter, icSigVideoCamera, and icSigVideoMonitor.