iccDEV: CIccEvalCompare Class Reference
CIccEvalCompare Class Reference abstract
#include <IccEval.h>
Public Member Functions
virtual void Compare (icFloatNumber *pPixel, icFloatNumber *deviceLab, icFloatNumber *destLab1, icFloatNumber *destLab2)=0
icStatusCMM ICCPROFLIB_API EvaluateProfile (CIccProfile *pProfile, icUInt8Number nGran=0, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, bool buseMpeTags=true)
icStatusCMM ICCPROFLIB_API EvaluateProfile (const icChar *szProfilePath, icUInt8Number nGran=0, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, bool buseMpeTags=true)
Detailed Description
Member Function Documentation
Compare()
virtual void CIccEvalCompare::Compare (icFloatNumber * pPixel, icFloatNumber * deviceLab, icFloatNumber * destLab1, icFloatNumber * destLab2) pure virtual
Implemented in CIccMinMaxEval, and CIccMinMaxEval.
Referenced by EvaluateProfile().
EvaluateProfile() [1/2]
icStatusCMM CIccEvalCompare::EvaluateProfile (CIccProfile * pProfile, icUInt8Number nGran = 0, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, bool buseMpeTags = true)
{
  if (!pProfile)
  {
    return icCmmStatCantOpenProfile;
  }
  if (pProfile->m_Header.deviceClass!=icSigInputClass &&
    pProfile->m_Header.deviceClass!=icSigDisplayClass &&
    pProfile->m_Header.deviceClass!=icSigOutputClass &&
    pProfile->m_Header.deviceClass!=icSigColorSpaceClass)
  {
    return icCmmStatInvalidProfile;
  }
  CIccCmm dev2Lab(icSigUnknownData, icSigLabData);
  CIccCmm Lab2Dev2Lab(icSigLabData, icSigLabData, false);
  icStatusCMM result;
  result = dev2Lab.AddXform(*pProfile, nIntent, nInterp, NULL, icXformLutColorimetric, buseMpeTags);
  if (result!=icCmmStatOk) {
    return result;
  }
  result = dev2Lab.Begin();
  if (result != icCmmStatOk) {
    return result;
  }
  result = Lab2Dev2Lab.AddXform(*pProfile, nIntent, nInterp, NULL, icXformLutColorimetric, buseMpeTags);
  if (result != icCmmStatOk) {
    return result;
  }
  result = Lab2Dev2Lab.AddXform(*pProfile, nIntent, nInterp, NULL, icXformLutColorimetric, buseMpeTags);
  if (result != icCmmStatOk) {
    return result;
  }
  result = Lab2Dev2Lab.Begin();
  if (result != icCmmStatOk) {
    return result;
  }
  icFloatNumber sPixel[15];
  icFloatNumber devPcs[15], roundPcs1[15], roundPcs2[15];
  int ndim = icGetSpaceSamples(pProfile->m_Header.colorSpace);
  int ndim1 = ndim+1;
  // determine granularity
  if (!nGran)
  {
    CIccTagLutAtoB* pTag = (CIccTagLutAtoB*)pProfile->FindTag(icSigAToB0Tag+(nIntent==icAbsoluteColorimetric ? icRelativeColorimetric : nIntent));
    if (!pTag || ndim==3)
    {
      nGran = 33;
    }
    else {
      CIccCLUT* pClut = pTag->GetCLUT();
      if (pClut)
        nGran = pClut->GridPoints()+2;
      else
        nGran = 33;
    }
  }
  int i, j;
  icFloatNumber stepsize = (icFloatNumber)(1.0/(icFloatNumber)(nGran-1));
  icFloatNumber* steps = new icFloatNumber[ndim1];
  icFloatNumber nstart = 0.0;
  icFloatNumber nEnd = (icFloatNumber)(1.0+stepsize/2.0);
  for(j=0; j<ndim1; j++) {
    steps[j] = nstart;
  }
  while(steps[0]==nstart) {
    for(j=0; j<ndim; j++) {
      sPixel[j] = icMin(steps[j+1],1.0);
    }
    steps[ndim] = (steps[ndim]+stepsize);
    for(i=ndim; i>=0; i--) {
      if(steps[i]>nEnd) {
        steps[i] = nstart;
        steps[i-1] = (steps[i-1]+stepsize);
      }
      else break;
    }
    dev2Lab.Apply(devPcs, sPixel); //Convert device value to pcs from input table
    Lab2Dev2Lab.Apply(roundPcs1, devPcs);  //First round trip gets color into output gamut
    Lab2Dev2Lab.Apply(roundPcs2, roundPcs1);  //Second round trip find reproducibility error
    icLabFromPcs(devPcs);
    icLabFromPcs(roundPcs1);
    icLabFromPcs(roundPcs2);
    Compare(sPixel, devPcs, roundPcs1, roundPcs2);
  }
  delete[] steps;
  return icCmmStatOk;
}
References icHeader::colorSpace, Compare(), icHeader::deviceClass, CIccMBB::GetCLUT(), CIccCLUT::GridPoints(), icAbsoluteColorimetric, icCmmStatCantOpenProfile, icCmmStatInvalidProfile, icCmmStatOk, icGetSpaceSamples(), icLabFromPcs(), icMin(), icRelativeColorimetric, icSigAToB0Tag, icSigColorSpaceClass, icSigDisplayClass, icSigInputClass, icSigLabData, icSigOutputClass, and icXformLutColorimetric.
Referenced by EvaluateProfile().
EvaluateProfile() [2/2]
icStatusCMM CIccEvalCompare::EvaluateProfile (const icChar * szProfilePath, icUInt8Number nGran = 0, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, bool buseMpeTags = true)
{
  CIccProfile *pProfile = ReadIccProfile(szProfilePath);
  if (!pProfile)
    return icCmmStatCantOpenProfile;
  icStatusCMM result = EvaluateProfile(pProfile, nGrid, nIntent, nInterp, buseMpeTags);
  delete pProfile;
  return result;
}
References CIccProfile, EvaluateProfile(), icCmmStatCantOpenProfile, and ReadIccProfile().
Referenced by main().
The documentation for this class was generated from the following files:
IccProfLib/IccEval.h
IccProfLib/IccEval.cpp