iccDEV: CIccPixelBuf Class Reference
CIccPixelBuf Class Reference
#include <IccUtil.h>
Public Member Functions
CIccPixelBuf (int nChan=icDefaultPixelBufSize)
~CIccPixelBuf ()
icFloatNumber * get ()
operator icFloatNumber * ()
operator void * ()
icFloatNumber & operator[] (int nPos)
Protected Attributes
icFloatNumber m_buf [icDefaultPixelBufSize]
icFloatNumber * m_pixel
Detailed Description
Constructor & Destructor Documentation
CIccPixelBuf()
CIccPixelBuf::CIccPixelBuf (int nChan = icDefaultPixelBufSize)
                                     : m_buf{}
{
  if (nChan>icDefaultPixelBufSize) {
    m_pixel = new icFloatNumber[nChan];
  }
  else {
    m_pixel = m_buf;
  }
}
References m_buf.
Referenced by CIccCfgColorData::fromLegacy(), main(), and main().
~CIccPixelBuf()
CIccPixelBuf::~CIccPixelBuf ()
{
  if (m_pixel && m_pixel!=m_buf)
    delete [] m_pixel;
}
References m_buf, and m_pixel.
Member Function Documentation
get()
icFloatNumber * CIccPixelBuf::get () inline
{ return m_pixel;}
References m_pixel.
Referenced by main().
operator icFloatNumber *()
CIccPixelBuf::operator icFloatNumber * () inline
{ return m_pixel; }
References m_pixel.
operator void *()
CIccPixelBuf::operator void * () inline
{ return m_pixel; }
References m_pixel.
operator[]()
icFloatNumber & CIccPixelBuf::operator[] (int nPos) inline
{ return m_pixel[nPos]; }
References m_pixel.
Referenced by CIccCfgColorData::fromLegacy(), and main().
Field Documentation
m_buf
icFloatNumber CIccPixelBuf::m_buf[icDefaultPixelBufSize] protected
Referenced by CIccPixelBuf(), and ~CIccPixelBuf().
m_pixel
icFloatNumber* CIccPixelBuf::m_pixel protected
Referenced by ~CIccPixelBuf(), get(), operator icFloatNumber *(), operator void *(), and operator[]().
The documentation for this class was generated from the following files:
IccProfLib/IccUtil.h
IccProfLib/IccUtil.cpp