iccDEV: Tools/CmdLine/IccApplyToLink/iccApplyToLink.cpp File Reference
iccApplyToLink.cpp File Reference
#include <stdio.h>
#include <string>
#include "IccCmm.h"
#include "IccUtil.h"
#include "IccDefs.h"
#include "IccApplyBPC.h"
#include "IccEnvVar.h"
#include "IccProfLibVer.h"
#include "IccProfile.h"
#include "IccTagBasic.h"
#include "IccTagLut.h"
#include "IccTagMPE.h"
#include "IccMpeBasic.h"
Data Structures
class CCubeWriter
class CDevLinkWriter
class ILinkWriter
Typedefs
typedef std::list< CIccProfile * > IccProfilePtrList
typedef std::shared_ptr< ILinkWriter > LinkWriterPtr
Functions
int main (int argc, icChar *argv[])
void Usage ()
Typedef Documentation
IccProfilePtrList
typedef std::list<CIccProfile*> IccProfilePtrList
LinkWriterPtr
typedef std::shared_ptr<ILinkWriter> LinkWriterPtr
Function Documentation
main()
int main (int argc, icChar * argv[])
{
  int minargs = 10; // minimum number of arguments
  if(argc<minargs) {
    Usage();
    return -1;
  }
  int nNumProfiles, temp;
  temp = argc - minargs;
  //remaining arguments must be in pairs
  if(temp%2 != 0) {
    printf("\nMissing arguments!\n");
    Usage();
    return -1;
  }
  nNumProfiles = temp/2;
  ILinkWriter* pLinkWriter;
  if (atoi(argv[2])) {
    pLinkWriter = new CCubeWriter();
  }
  else {
    pLinkWriter = new CDevLinkWriter();
  }
  if (!pLinkWriter) {
    printf("Unable to allocate writer\n");
    return -1;
  }
  LinkWriterPtr pWriter(pLinkWriter);
  pWriter->setFile(argv[1]);
  int nLutSize = atoi(argv[3]);
  pWriter->setLutSize(nLutSize);
  pWriter->setOption(atoi(argv[4]));
  pWriter->setTitle(argv[5]);
  icFloatNumber loRange = (icFloatNumber)atof(argv[6]);
  icFloatNumber hiRange = (icFloatNumber)atof(argv[7]);
  icFloatNumber sizeRange = hiRange - loRange;
  pWriter->setInputRange(loRange, hiRange);
  //Retrieve command line arguments
  bool bFirstTransform = atoi(argv[8]) != 0;
  icXformInterp nInterp = (icXformInterp)atoi(argv[9]);
  int nIntent, nType, nLuminance;
  //Allocate a CIccCmm to use to apply profiles.
  //Let profiles determine starting and ending color spaces.
  //Third argument indicates that Input transform from first profile should be used.
  CIccCmm theCmm(icSigUnknownData, icSigUnknownData, bFirstTransform);
  //PCC profiles need to stay around until the CMM has been completely initialized to apply transforms.
  //TheCmm doesn't own them so keep a list so they can be released when they aren't needed any more.
  IccProfilePtrList pccList;
  int i, nCount;
  bool bUseD2BxB2DxTags;
  icStatusCMM stat;       //status variable for CMM operations
  icCmmEnvSigMap sigMap;  //Keep track of CMM Environment for each profile
  bool bUseSubProfile;
  //Remaining arguments define a sequence of profiles to be applied.
  //Add them to theCmm one at a time providing CMM environment variables and PCC overrides as provided.
  for(i = 0, nCount=minargs; i<nNumProfiles; i++, nCount+=2) {
#if defined(_WIN32) || defined(_WIN64)
    if (!strnicmp(argv[nCount], "-ENV:", 5)) {  //check for -ENV: to allow for CMM Environment variables to be defined for next transform
#else
    if (!strncasecmp(argv[nCount], "-ENV:", 5)) {
#endif
      icSignature sig = icGetSigVal(argv[nCount]+5);
      icFloatNumber val = (icFloatNumber)atof(argv[nCount+1]);
      sigMap[sig]=val;
    }
    else if (stricmp(argv[nCount], "-PCC")) { //Attach profile while ignoring -PCC (this are handled below as profiles are attached)
      bUseD2BxB2DxTags = true;
      nIntent = atoi(argv[nCount+1]);
      bUseSubProfile = (nIntent / 1000) > 0;
      nIntent = nIntent % 1000;
      nLuminance = nIntent / 100;
      nIntent = nIntent % 100;
      nType = abs(nIntent) / 10;
      nIntent = nIntent % 10;
      CIccProfile *pPccProfile = NULL;
      //Adjust type and hint information based on rendering intent
      CIccCreateXformHintManager Hint;
      switch(nType) {
      case 1:
        nType = 0;
        bUseD2BxB2DxTags = false;
        break;
      case 4:
        nType = 0;
        Hint.AddHint(new CIccApplyBPCHint());
        break;
      }
      if (nLuminance) {
        Hint.AddHint(new CIccLuminanceMatchingHint());
      }
      // Use of following -PCC arg allows for profile connection conditions to be defined
      if (i+1<nNumProfiles && !stricmp(argv[nCount+2], "-PCC")) {
        pPccProfile = OpenIccProfile(argv[nCount+3]);
        if (!pPccProfile) {
          printf("Unable to open Profile Connections Conditions from '%s'\n", argv[nCount+3]);
          return -1;
        }
        //Keep track of pPccProfile for until after cmm.Begin is called
        pccList.push_back(pPccProfile);
      }
      //CMM Environment variables are passed in as a Hint to the Xform associated with the profile
      if (sigMap.size()>0) {
        Hint.AddHint(new CIccCmmEnvVarHint(sigMap));
      }
      //Read profile from path and add it to theCmm
      CIccProfile* pXformProfile = ReadIccProfile(argv[nCount], bUseSubProfile); //We need all tags in profile for providing information to link
      stat = theCmm.AddXform(pXformProfile, nIntent<0 ? icUnknownIntent : (icRenderingIntent)nIntent, nInterp, pPccProfile,
                              (icXformLutType)nType, bUseD2BxB2DxTags, &Hint);
      if (stat) {
        printf("Invalid Profile(%d):  %s\n", stat, argv[nCount]);
        return -1;
      }
      sigMap.clear();
    }
  }
  //All profiles have been added to CMM.  Tell CMM that we are ready to begin applying colors/pixels
  if((stat=theCmm.Begin())) {
    printf("Error %d - Unable to begin profile application - Possibly invalid or incompatible profiles\n", stat);
    return -1;
  }
  pWriter->setCmm(&theCmm);
  //Now we can release the pccProfile nodes.
  IccProfilePtrList::iterator pcc;
  for (pcc=pccList.begin(); pcc!=pccList.end(); pcc++) {
    CIccProfile *pPccProfile = *pcc;
    delete pPccProfile;
  }
  pccList.clear();
  if (!pWriter->begin(theCmm.GetSourceSpace(), theCmm.GetDestSpace())) {
    printf("Unable to begin writing LUT\n");
      return -1;
  }
  //Get and validate the source color space from the Cmm.
  icColorSpaceSignature SrcspaceSig = theCmm.GetSourceSpace();
  int nSrcSamples = icGetSpaceSamples(SrcspaceSig);
  //Get and validate the destination color space from theCmm.
  icColorSpaceSignature DestspaceSig = theCmm.GetDestSpace();
  int nDestSamples = icGetSpaceSamples(DestspaceSig);
  int* idx = new int[nSrcSamples];
  icFloatNumber* srcPixel = new icFloatNumber[nSrcSamples];
  icFloatNumber* dstPixel = new icFloatNumber[nDestSamples];
  icUInt32Number maxLut = nLutSize - 1;
  int curPer, lastPer = -1;
  //init idx;
  int lutCount = 1;
  for (auto i = 0; i < nSrcSamples; i++) {
    idx[i] = 0;
    lutCount *= nLutSize;
  }
  int j = 0;
  for (int c = 0; j >= 0; c++) {
    for (auto i = 0; i < nSrcSamples; i++) {
      srcPixel[i] = sizeRange * (icFloatNumber)idx[i] / maxLut + loRange;
    }
    //Use CMM to convert SrcPixel to DestPixel
    theCmm.Apply(dstPixel, srcPixel);
    pWriter->setNextNode(dstPixel);
    for (j = nSrcSamples - 1; j >= 0;) {
      idx[j]++;
      if (idx[j] >= nLutSize) {
        idx[j] = 0;
        j--;
      }
      else
        break;
    }
    //Display status of how much we have accomplished
    curPer = (int)((float)(c + 1) * 100.0f / (float)lutCount);
    if (curPer != lastPer) {
      printf("\r%d%%", curPer);
      lastPer = curPer;
    }
  }
  delete[] dstPixel;
  delete[] srcPixel;
  delete[] idx;
  if (pWriter->finish()) {
    printf("\nLUT successfully written to '%s'\n", argv[1]);
  }
  else {
    printf("\nUnable to write LUT to '%s'\n", argv[1]);
  }
  return 0;
}
References CCubeWriter::CCubeWriter(), CDevLinkWriter::CDevLinkWriter(), CIccCmmEnvVarHint::CIccCmmEnvVarHint(), ILinkWriter::begin(), CIccProfile, ILinkWriter::finish(), icGetSigVal(), icGetSpaceSamples(), OpenIccProfile(), ReadIccProfile(), ILinkWriter::setCmm(), ILinkWriter::setFile(), ILinkWriter::setInputRange(), ILinkWriter::setLutSize(), ILinkWriter::setNextNode(), ILinkWriter::setOption(), ILinkWriter::setTitle(), and Usage().
Usage()
void Usage ()
{
  printf("iccApplyToLink built with IccProfLib version " ICCPROFLIBVER "\n\n");
  printf("Usage: iccApplyToLink dst_link_file link_type lut_size option title range_min range_max first_transform interp {{-ENV:sig value} profile_file_path rendering_intent {-PCC connection_conditions_path}}\n\n");
  printf("  dst_link_file is path of file to create\n\n");
  printf("  For link_type:\n");
  printf("    0 - Device Link\n");
  printf("    1 - .cube text file\n\n");
  printf("  Where lut_size represents the number of grid entries for each lut dimension.\n\n");
  printf("  For option when link_type is 0:\n");
  printf("    option represents the digits of precision for lut for .cube files\n");
  printf("  For option when link_type is 1:\n");
  printf("    0 - version 4 profile with 16-bit table\n");
  printf("    1 - version 5 profile\n\n");
  printf("  title is the title/description for the dest_link_file\n\n");
  printf("  range_min specifies the minimum input value (usually 0.0)\n");
  printf("  range_max specifies the maximum input value (usually 1.0)\n\n");
  printf("  For first_transform:\n");
  printf("    0 - use source transform from first profile\n");
  printf("    1 - use destination transform from first profile\n\n");
  printf("  For interp:\n");
  printf("    0 - linear interpolation\n");
  printf("    1 - tetrahedral interpolation\n\n");
  printf("  For rendering_intent:\n");
  printf("    0 - Perceptual\n");
  printf("    1 - Relative\n");
  printf("    2 - Saturation\n");
  printf("    3 - Absolute\n");
  printf("    10 - Perceptual without D2Bx/B2Dx\n");
  printf("    11 - Relative without D2Bx/B2Dx\n");
  printf("    12 - Saturation without D2Bx/B2Dx\n");
  printf("    13 - Absolute without D2Bx/B2Dx\n");
  printf("    20 - Preview Perceptual\n");
  printf("    21 - Preview Relative\n");
  printf("    22 - Preview Saturation\n");
  printf("    23 - Preview Absolute\n");
  printf("    30 - Gamut\n");
  printf("    33 - Gamut Absolute\n");
  printf("    40 - Perceptual with BPC\n");
  printf("    41 - Relative Colorimetric with BPC\n");
  printf("    42 - Saturation with BPC\n");
  printf("    50 - BDRF Parameters\n");
  printf("    60 - BDRF Direct\n");
  printf("    70 - BDRF MCS Parameters\n");
  printf("    80 - MCS connection\n");
  printf("  +100 - Use Luminance based PCS adjustment\n");
  printf(" +1000 - Use V5 sub-profile if present\n");
}