iccDEV: CIccToneMapFunc Class Reference
CIccToneMapFunc Class Reference
#include <IccMpeBasic.h>
Public Member Functions
CIccToneMapFunc ()
virtual ~CIccToneMapFunc ()
icFloatNumber Apply (icFloatNumber lumValue, icFloatNumber pixelValue) const
bool Begin ()
void Describe (std::string &sDescription, int nVerboseness=0)
virtual const char * GetClassName () const
virtual icToneFunctionSignature GetType () const
virtual CIccToneMapFunc * NewCopy () const
CIccToneMapFunc & operator= (const CIccToneMapFunc &toneMap)
bool Read (icUInt32Number size, CIccIO *pIO)
bool SetFunction (icUInt16Number nFunc, icUInt8Number, icFloatNumber *pParams)
icValidateStatus Validate (std::string &sFuncReport, int nVerboseness=0) const
bool Write (CIccIO *pIO)
Protected Member Functions
int NumArgs () const
Protected Attributes
icUInt16Number m_nFunctionType
icUInt8Number m_nParameters
icUInt32Number m_nReserved
icUInt16Number m_nReserved2
icFloatNumber * m_params
Detailed Description
Class: CIccToneMapFunc
Purpose: The parametric function to apply a tone map based on mapped luminance and channel value
Constructor & Destructor Documentation
CIccToneMapFunc()
CIccToneMapFunc::CIccToneMapFunc ()
{
  m_nFunctionType = 0;
  m_nParameters = 0;
  m_params = NULL;
  m_nReserved = 0;
  m_nReserved2 = 0;
}
References m_nFunctionType, m_nParameters, m_nReserved, m_nReserved2, and m_params.
Referenced by NewCopy(), and CIccMpeToneMap::NewToneMapFunc().
~CIccToneMapFunc()
CIccToneMapFunc::~CIccToneMapFunc () virtual
{
  if (m_params)
    free(m_params);
}
References m_params.
Member Function Documentation
Apply()
icFloatNumber CIccToneMapFunc::Apply (icFloatNumber lumValue, icFloatNumber pixelValue) const
{
  if (!m_nFunctionType && m_params) {
    return m_params[0] * lumValue * (pixelValue + m_params[1]) + m_params[2];
  }
  return 0;
}
References m_nFunctionType, and m_params.
Referenced by CIccMpeToneMap::Apply().
Begin()
bool CIccToneMapFunc::Begin ()
{
  if (m_nFunctionType != 0x0000)
    return false;
  if (m_nParameters < NumArgs() || !m_params)
    return false;
  return true;
}
References m_nFunctionType, m_nParameters, m_params, and NumArgs().
Referenced by CIccMpeToneMap::Begin().
Describe()
void CIccToneMapFunc::Describe (std::string & sDescription, int nVerboseness = 0)
{
  icChar buf[128];
  sprintf(buf, "ToneFunctionType: %04Xh\n", m_nFunctionType);
  sDescription += buf;
  switch (m_nFunctionType) {
  case 0x0000:
    sprintf(buf, "Y = %.8f * M * ( X + %.8f) + %.8f\n\n", m_params[0], m_params[1], m_params[2]);
    sDescription += buf;
    return;
  default:
    int i;
    sprintf(buf, "Unknown Function with %d parameters:\n\n", m_nParameters);
    sDescription += buf;
    for (i = 0; i < m_nParameters; i++) {
      sprintf(buf, "Param[%d] = %.8lf\n\n", i, m_params[i]);
      sDescription += buf;
    }
  }
}
References m_nFunctionType, m_nParameters, and m_params.
Referenced by CIccMpeToneMap::Describe().
GetClassName()
virtual const char * CIccToneMapFunc::GetClassName () const inline virtual
Reimplemented in CIccXmlToneMapFunc.
{ return "CIccToneMapFunc"; }
Referenced by CIccMpeXmlToneMap::ToXml().
GetType()
virtual icToneFunctionSignature CIccToneMapFunc::GetType () const inline virtual
{ return icSigToneMapFunction; }
References icSigToneMapFunction.
Referenced by Write().
NewCopy()
CIccToneMapFunc * CIccToneMapFunc::NewCopy () const virtual
{
  CIccToneMapFunc* rv = new CIccToneMapFunc();
  if (rv)
    *rv = *this;
  return rv;
}
References CIccToneMapFunc(), and operator=().
Referenced by CIccMpeToneMap::CopyToneFuncs().
NumArgs()
int CIccToneMapFunc::NumArgs () const protected
{
  if (m_nFunctionType == 0)
    return 3;
  return 0;
}
References m_nFunctionType.
Referenced by Begin(), SetFunction(), and Write().
operator=()
CIccToneMapFunc & CIccToneMapFunc::operator= (const CIccToneMapFunc & toneMap)
{
  if (&toneMapFunc == this)
    return *this;
  m_nFunctionType = toneMapFunc.m_nFunctionType;
  m_nParameters = toneMapFunc.m_nParameters;
  if (m_params)
    free(m_params);
  if (toneMapFunc.m_nParameters && toneMapFunc.m_params) {
    m_params = (icFloatNumber*)malloc(m_nParameters * sizeof(icFloatNumber));
    if (m_params)
      memcpy(m_params, toneMapFunc.m_params, m_nParameters * sizeof(icFloatNumber));
  }
  else
    m_params = NULL;
  m_nReserved = toneMapFunc.m_nReserved;
  m_nReserved2 = toneMapFunc.m_nReserved2;
  return *this;
}
References m_nFunctionType, m_nParameters, m_nReserved, m_nReserved2, and m_params.
Referenced by CIccXmlToneMapFunc::NewCopy(), and NewCopy().
Read()
bool CIccToneMapFunc::Read (icUInt32Number size, CIccIO * pIO)
{
  icCurveSegSignature sig;
  icUInt32Number headerSize = sizeof(icTagTypeSignature) +
    sizeof(icUInt32Number) +
    sizeof(icUInt16Number) +
    sizeof(icUInt16Number);
  if (headerSize > size)
    return false;
  if (!pIO) {
    return false;
  }
  if (!pIO->Read32(&sig))
    return false;
  if (sig != icSigToneMapFunction)
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  if (!pIO->Read16(&m_nFunctionType))
    return false;
  if (!pIO->Read16(&m_nReserved2))
    return false;
  if (m_params) {
    free(m_params);
  }
  m_nParameters = (icUInt8Number)((size - headerSize)/sizeof(icFloatNumber));
  if (m_nParameters) {
    m_params = (icFloatNumber*)malloc(m_nParameters * sizeof(icFloatNumber));
    if (!m_params)
      return false;
    if (pIO->ReadFloat32Float(m_params, m_nParameters) != m_nParameters) {
      return false;
    }
  }
  else
    m_params = NULL;
  return true;
}
References icSigToneMapFunction, m_nFunctionType, m_nParameters, m_nReserved, m_nReserved2, m_params, CIccIO::Read16(), CIccIO::Read32(), and CIccIO::ReadFloat32Float().
Referenced by CIccMpeToneMap::Read().
SetFunction()
bool CIccToneMapFunc::SetFunction (icUInt16Number nFunc, icUInt8Number nParams, icFloatNumber * pParams)
{
  m_nFunctionType = nFunc;
  if (m_params)
    free(m_params);
  int nArgs = NumArgs();
  m_nParameters = (icUInt8Number)icIntMin(nParams, NumArgs());
  if (nArgs && pParams) {
    m_params = (icFloatNumber*)calloc(nArgs, sizeof(icFloatNumber));
    if (m_params)
      memcpy(m_params, pParams, icIntMin(nArgs, nParams) * sizeof(icFloatNumber));
  }
  return nParams == NumArgs();
}
References icIntMin(), m_nFunctionType, m_nParameters, m_params, and NumArgs().
Validate()
icValidateStatus CIccToneMapFunc::Validate (std::string & sFuncReport, int nVerboseness = 0) const
{
  CIccInfo Info;
  icValidateStatus rv = icValidateOK;
  if (m_nReserved || m_nReserved2) {
    sReport += icMsgValidateWarning;
    sReport += " formula curve has non zero reserved data.\n";
    rv = icMaxStatus(rv, icValidateWarning);
  }
  switch (m_nFunctionType) {
    case 0x0000:
      if (!m_params || m_nParameters < 3) {
        sReport += icMsgValidateCriticalError;
        sReport += " Tone mapping function has invalid parameters.\n";
        rv = icMaxStatus(rv, icValidateCriticalError);
      }
      else if (m_nParameters > 3) {
        sReport += icMsgValidateWarning;
        sReport += " tone mapping function has too many formulaCurveSegment parameters.\n";
        rv = icMaxStatus(rv, icValidateWarning);
      }
      break;
    default:
    {
      icChar buf[128];
      sReport += icMsgValidateCriticalError;
      sprintf(buf, " tone mapping function uses unknown function type %d\n", m_nFunctionType);
      sReport += buf;
      rv = icMaxStatus(rv, icValidateCriticalError);
    }
  }
  return rv;
}
References icMaxStatus(), icMsgValidateCriticalError, icMsgValidateWarning, icValidateCriticalError, icValidateOK, icValidateWarning, m_nFunctionType, m_nParameters, m_nReserved, m_nReserved2, and m_params.
Referenced by CIccMpeToneMap::Validate().
Write()
bool CIccToneMapFunc::Write (CIccIO * pIO)
{
  icToneFunctionSignature sig = GetType();
  if (!pIO)
    return false;
  if (!pIO->Write32(&sig))
    return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  if (!pIO->Write16(&m_nFunctionType))
    return false;
  if (!pIO->Write16(&m_nReserved2))
    return false;
  if (m_nParameters != NumArgs())
    return false;
  if (m_nParameters) {
    if (pIO->WriteFloat32Float(m_params, m_nParameters) != m_nParameters)
      return false;
  }
  return true;
}
References GetType(), m_nFunctionType, m_nParameters, m_nReserved, m_nReserved2, m_params, NumArgs(), CIccIO::Write16(), CIccIO::Write32(), and CIccIO::WriteFloat32Float().
Referenced by CIccMpeToneMap::Write().
Field Documentation
m_nFunctionType
icUInt16Number CIccToneMapFunc::m_nFunctionType protected
Referenced by CIccToneMapFunc(), Apply(), Begin(), Describe(), NumArgs(), operator=(), CIccXmlToneMapFunc::ParseXml(), Read(), SetFunction(), CIccXmlToneMapFunc::ToXml(), Validate(), and Write().
m_nParameters
icUInt8Number CIccToneMapFunc::m_nParameters protected
Referenced by CIccToneMapFunc(), Begin(), Describe(), operator=(), CIccXmlToneMapFunc::ParseXml(), Read(), SetFunction(), CIccXmlToneMapFunc::ToXml(), Validate(), and Write().
m_nReserved
icUInt32Number CIccToneMapFunc::m_nReserved protected
Referenced by CIccToneMapFunc(), operator=(), Read(), CIccXmlToneMapFunc::ToXml(), Validate(), and Write().
m_nReserved2
icUInt16Number CIccToneMapFunc::m_nReserved2 protected
Referenced by CIccToneMapFunc(), operator=(), CIccXmlToneMapFunc::ParseXml(), Read(), CIccXmlToneMapFunc::ToXml(), Validate(), and Write().
m_params
icFloatNumber* CIccToneMapFunc::m_params protected
Referenced by CIccToneMapFunc(), ~CIccToneMapFunc(), Apply(), Begin(), Describe(), operator=(), CIccXmlToneMapFunc::ParseXml(), Read(), SetFunction(), CIccXmlToneMapFunc::ToXml(), Validate(), and Write().
The documentation for this class was generated from the following files:
IccProfLib/IccMpeBasic.h
IccProfLib/IccMpeBasic.cpp