iccDEV: CIccSampledCurveSegmentXml Class Reference
CIccSampledCurveSegmentXml Class Reference
Public Member Functions
CIccSampledCurveSegmentXml (icFloatNumber start, icFloatNumber end)
virtual icFloatNumber Apply (icFloatNumber v) const
virtual bool Begin (CIccCurveSegment *pPrevSeg)
virtual void Describe (std::string &sDescription, int nVerboseness)
icFloatNumber EndPoint ()
virtual const icChar * GetClassName () const
virtual icFloatNumber * GetSamples ()
virtual icUInt32Number GetSize ()
virtual icCurveSegSignature GetType () const
virtual CIccCurveSegment * NewCopy () const
bool ParseXml (xmlNode *pNode, std::string &parseStr)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool SetSize (icUInt32Number nSize, bool bZeroAlloc=true)
icFloatNumber StartPoint ()
bool ToXml (std::string &xml, std::string blanks)
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccTagMultiProcessElement *pMPE=NULL, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccCurveSegment * Create (icCurveSegSignature sig, icFloatNumber start, icFloatNumber end)
Protected Attributes
icFloatNumber m_endPoint
icFloatNumber m_last
icUInt32Number m_nCount
icUInt32Number m_nReserved
icFloatNumber * m_pSamples
icFloatNumber m_range
icFloatNumber m_startPoint
Detailed Description
Constructor & Destructor Documentation
CIccSampledCurveSegmentXml()
CIccSampledCurveSegmentXml::CIccSampledCurveSegmentXml (icFloatNumber start, icFloatNumber end) inline
: CIccSampledCurveSegment(start, end) {}
References CIccSampledCurveSegment::CIccSampledCurveSegment().
Referenced by CIccSegmentedCurveXml::ParseXml().
Member Function Documentation
Apply()
icFloatNumber CIccSampledCurveSegment::Apply (icFloatNumber v) const virtual inherited
Name: CIccSampledCurveSegment::Apply
Purpose:
Args:
Return:
Implements CIccCurveSegment.
{
  if (v<m_startPoint)
    v=m_startPoint;
  else if (v>m_endPoint)
    v=m_endPoint;
  icFloatNumber pos = (v-m_startPoint)/m_range * m_last;
  icUInt32Number index = (icUInt32Number) pos;
  icFloatNumber remainder = pos - (icFloatNumber)index;
  if (remainder==0.0)
    return m_pSamples[index];
  return (icFloatNumber)((1.0-remainder)*m_pSamples[index] + remainder*m_pSamples[index+1]);
}
References CIccCurveSegment::m_endPoint, CIccSampledCurveSegment::m_last, CIccSampledCurveSegment::m_pSamples, CIccSampledCurveSegment::m_range, and CIccCurveSegment::m_startPoint.
Begin()
bool CIccSampledCurveSegment::Begin (CIccCurveSegment * pPrevSeg = NULL) virtual inherited
Name: CIccSampledCurveSegment::Begin
Purpose:
Args:
Return:
Implements CIccCurveSegment.
{
  if (m_nCount<2)
    return false;
  m_range = m_endPoint - m_startPoint;
  m_last = (icFloatNumber)(m_nCount - 1);
  if (m_endPoint-m_startPoint == 0.0)
    return false;
  if (!pPrevSeg)
    return false;
  //Set up interpolation from Application of last segment
  m_pSamples[0] = pPrevSeg->Apply(m_startPoint);
  return true;
}
References CIccCurveSegment::Apply(), CIccCurveSegment::m_endPoint, CIccSampledCurveSegment::m_last, CIccSampledCurveSegment::m_nCount, CIccSampledCurveSegment::m_pSamples, CIccSampledCurveSegment::m_range, and CIccCurveSegment::m_startPoint.
Create()
CIccCurveSegment * CIccCurveSegment::Create (icCurveSegSignature sig, icFloatNumber start, icFloatNumber end) static inherited
Name: CIccCurveSegment::Create
Purpose:
Args:
Return:
{
  switch(sig) {
  case icSigFormulaCurveSeg:
    return new CIccFormulaCurveSegment(start, end);
  case icSigSampledCurveSeg:
    return new CIccSampledCurveSegment(start, end);
  default:
    return NULL;
  }
}
References CIccFormulaCurveSegment::CIccFormulaCurveSegment(), CIccSampledCurveSegment::CIccSampledCurveSegment(), icSigFormulaCurveSeg, and icSigSampledCurveSeg.
Referenced by CIccSegmentedCurve::Read().
Describe()
void CIccSampledCurveSegment::Describe (std::string & sDescription, int nVerboseness) virtual inherited
Name: CIccSampledCurveSegment::Describe
Purpose:
Args:
Return:
Implements CIccCurveSegment.
{
  icChar buf[128];
  if (m_nCount<2) {
    sDescription += "Empty Segment [";
    if (m_startPoint==icMinFloat32Number)
      sDescription += "-Infinity, ";
    else {
    sprintf(buf, "%.8f, ", m_startPoint);
    sDescription += buf;
    }
    if (m_endPoint==icMaxFloat32Number)
      sDescription += "+Infinity";
    else {
    sprintf(buf, "%.8f", m_endPoint);
    sDescription += buf;
    }
    sprintf(buf, "]\n");
    sDescription += buf;
  }
  else {
    sDescription += "Sampled Segment [";
    if (m_startPoint==icMinFloat32Number)
      sDescription += "-Infinity, ";
    else {
    sprintf(buf, "%.8f, ", m_startPoint);
    sDescription += buf;
    }
    if (m_endPoint==icMaxFloat32Number)
      sDescription += "+Infinity";
    else {
    sprintf(buf, "%.8f", m_endPoint);
    sDescription += buf;
    }
    sprintf(buf, "]\n");
    sDescription += buf;
    sDescription += "IN  OUT\n";
    icUInt32Number i;
    icFloatNumber range = m_endPoint - m_startPoint;
    icFloatNumber last = (icFloatNumber)(m_nCount-1);
    for (i=1; i<m_nCount; i++) {
      sprintf(buf, "%.8f %.8f\n", m_startPoint + (icFloatNumber)i*range/last, m_pSamples[i]);
      sDescription += buf;
    }
  }
  sDescription += "\n";
}
References CIccCurveSegment::m_endPoint, CIccSampledCurveSegment::m_nCount, CIccSampledCurveSegment::m_pSamples, and CIccCurveSegment::m_startPoint.
EndPoint()
icFloatNumber CIccCurveSegment::EndPoint () inline inherited
{ return m_endPoint;}
References CIccCurveSegment::m_endPoint.
Referenced by CIccSegmentedCurve::Apply(), and CIccSegmentedCurve::Insert().
GetClassName()
virtual const icChar * CIccSampledCurveSegment::GetClassName () const inline virtual inherited
Implements CIccCurveSegment.
{ return "CIccSampledCurveSegment"; }
GetSamples()
virtual icFloatNumber * CIccSampledCurveSegment::GetSamples () inline virtual inherited
{ return m_pSamples; }
References CIccSampledCurveSegment::m_pSamples.
GetSize()
virtual icUInt32Number CIccSampledCurveSegment::GetSize () inline virtual inherited
{ return m_nCount; }
References CIccSampledCurveSegment::m_nCount.
GetType()
virtual icCurveSegSignature CIccSampledCurveSegment::GetType () const inline virtual inherited
Implements CIccCurveSegment.
{ return icSigSampledCurveSeg; }
References icSigSampledCurveSeg.
Referenced by CIccSampledCurveSegment::Write().
NewCopy()
virtual CIccCurveSegment * CIccSampledCurveSegment::NewCopy () const inline virtual inherited
Implements CIccCurveSegment.
{ return new CIccSampledCurveSegment(*this);}
References CIccSampledCurveSegment::CIccSampledCurveSegment().
ParseXml()
bool CIccSampledCurveSegmentXml::ParseXml (xmlNode * pNode, std::string & parseStr)
{
  const char *filename = icXmlAttrValue(pNode, "Filename");
  // file exists
  if (filename[0]) {
    CIccIO *file = IccOpenFileIO(filename, "rb");
    if (!file){
      parseStr += "Error! - File '";
      parseStr += filename;
      parseStr +="' not found.\n";
      delete file;
      return false;
    }
    const char *format = icXmlAttrValue(pNode, "Format");
    // format is text
    if (!strcmp(format, "text")) {
      icUInt32Number num = file->GetLength();
      char *buf = new char[num];
      if (!buf) {
        perror("Memory Error");
        parseStr += "'";
        parseStr += filename;
        parseStr += "' may not be a valid text file.\n";
        delete file;
        return false;
      }
      if (file->Read8(buf, num) !=num) {
        perror("Read-File Error");
        parseStr += "'";
        parseStr += filename;
        parseStr += "' may not be a valid text file.\n";
        delete[] buf;
        delete file;
        return false;
      }
      CIccFloatArray data;
      //if (!data.ParseTextArray(buf)) {
      if (!data.ParseTextArrayNum(buf, num, parseStr)){
        parseStr += "File '";
        parseStr += filename;
        parseStr += "' is not a valid text file.\n";
        SetSize(0);
        delete[] buf;
        delete file;
        return false;
      }
      else {
        SetSize(data.GetSize());
        icFloatNumber *src = data.GetBuf();
        icFloatNumber *dst = m_pSamples;
        icUInt32Number i;
        for (i=0; i<data.GetSize(); i++) {
          *dst = *src;
          dst++;
          src++;
        }
      }
      delete[] buf;
      delete file;
      return true;
    }
    // format is binary
    else if (!strcmp(format, "binary")) {
      const char *order = icXmlAttrValue(pNode, "Endian");
      bool little_endian = !strcmp(order, "little");
      icUInt16Number storageType = icValueTypeFloat32;
      xmlAttr *attr = icXmlFindAttr(pNode, "StorageType");
      if (attr) {
       storageType = (icUInt16Number)atoi(icXmlAttrValue(attr));
      }
      if (storageType == icValueTypeUInt8){
        icUInt32Number num = file->GetLength();
        icUInt8Number value;
        SetSize(num);
        icFloatNumber *dst =  m_pSamples;
        icUInt32Number i;
        for (i=0; i<num; i++) {
          if (!file->Read8(&value)) {
            perror("Read-File Error");
            parseStr += "'";
            parseStr += filename;
            parseStr += "' may not be a valid binary file.\n";
            delete file;
            return false;
          }
          *dst++ = (icFloatNumber)value / 255.0f;
        }
        delete file;
        return true;
      }
      else if (storageType == icValueTypeUInt16){
        icUInt32Number num = file->GetLength() / sizeof(icUInt16Number);
        icUInt16Number value;
        icUInt8Number *m_ptr = (icUInt8Number*)&value;
        SetSize(num);
        icFloatNumber *dst = m_pSamples;
        icUInt32Number i;
        for (i=0; i<num; i++) {
          if (!file->Read16(&value)) {  //assumes data is big endian
            perror("Read-File Error");
            parseStr += "'";
            parseStr += filename;
            parseStr += "' may not be a valid binary file.\n";
            delete file;
            return false;
          }
#ifdef ICC_BYTE_ORDER_LITTLE_ENDIAN
          if (little_endian) {
#else
          if (!little_endian) {
#endif
            icUInt8Number t = m_ptr[0];
            m_ptr[0] = m_ptr[1];
            m_ptr[1] = t;
          }
          *dst++ = (icFloatNumber)value / 65535.0f;
        }
        delete file;
        return true;
      }
      else if (storageType == icValueTypeFloat16){
        icUInt32Number num = file->GetLength() / sizeof(icFloat16Number);
        icFloat16Number value;
        icUInt8Number *m_ptr = (icUInt8Number*)&value;
        SetSize(num);
        icFloatNumber *dst = m_pSamples;
        icUInt32Number i;
        for (i=0; i<num; i++) {
          if (!file->Read16(&value)) { //assumes data is big endian
            perror("Read-File Error");
            parseStr += "'";
            parseStr += filename;
            parseStr += "' may not be a valid binary file.\n";
            delete file;
            return false;
          }
#ifdef ICC_BYTE_ORDER_LITTLE_ENDIAN
          if (little_endian) {
#else
          if (!little_endian) {
#endif
            icUInt8Number t = m_ptr[0];
            m_ptr[0] = m_ptr[1];
            m_ptr[1] = t;
          }
          *dst++ = icF16toF(value);
        }
        delete file;
        return true;
      }
      else if (storageType == icValueTypeFloat32) {
        icUInt32Number num = file->GetLength()/sizeof(icFloat32Number);
        icFloat32Number value;
        icUInt8Number *m_ptr = (icUInt8Number*)&value;
        SetSize(num);
        icFloatNumber *dst = m_pSamples;
        icUInt32Number i;
        for (i=0; i<num; i++) {
          if (!file->ReadFloat32Float(&value)) {  //assumes data is big endian
            perror("Read-File Error");
            parseStr += "'";
            parseStr += filename;
            parseStr += "' may not be a valid binary file.\n";
            delete file;
            return false;
          }
#ifdef ICC_BYTE_ORDER_LITTLE_ENDIAN
          if (little_endian) {
#else
          if (!little_endian) {
#endif
            icUInt8Number tmp;
            tmp = m_ptr[0]; m_ptr[0] = m_ptr[3]; m_ptr[3] = tmp;
            tmp = m_ptr[1]; m_ptr[1] = m_ptr[2]; m_ptr[2] = tmp;
          }
          *dst++ = value;
        }
        delete file;
        return true;
      }
      else { //not 8bit/16bit/float
        delete file;
        return false;
      }
    }
  }
  else {
    CIccFloatArray samples;
    if (!samples.ParseArray(pNode->children)) {
      return false;
    }
    if (!SetSize(samples.GetSize())) {
      return false;
    }
    memcpy(m_pSamples, samples.GetBuf(), samples.GetSize() * sizeof(icFloatNumber));
  }
  return true;
}
References CIccXmlArrayType< T, Tsig >::GetBuf(), CIccIO::GetLength(), CIccXmlArrayType< T, Tsig >::GetSize(), IccOpenFileIO(), icF16toF(), icValueTypeFloat16, icValueTypeFloat32, icValueTypeUInt16, icValueTypeUInt8, icXmlAttrValue(), icXmlAttrValue(), icXmlFindAttr(), CIccSampledCurveSegment::m_pSamples, CIccXmlArrayType< T, Tsig >::ParseArray(), CIccXmlArrayType< T, Tsig >::ParseTextArrayNum(), CIccIO::Read16(), CIccIO::Read8(), CIccIO::ReadFloat32Float(), and CIccSampledCurveSegment::SetSize().
Referenced by CIccSegmentedCurveXml::ParseXml().
Read()
bool CIccSampledCurveSegment::Read (icUInt32Number size, CIccIO * pIO) virtual inherited
Name: CIccSampledCurveSegment::Read
Purpose:
Args:
Return:
Implements CIccCurveSegment.
{
  icCurveSegSignature sig;
  icUInt32Number headerSize = sizeof(icTagTypeSignature) +
    sizeof(icUInt32Number) +
    sizeof(icUInt32Number);
  if (headerSize > size)
    return false;
  if (!pIO) {
    return false;
  }
  if (!pIO->Read32(&sig))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  if (!pIO->Read32(&m_nCount))
    return false;
  if (m_nCount > size - headerSize || m_nCount * sizeof(icFloat32Number) > size - headerSize)
    return false;
  //Reserve room for first point who's value comes from previous segment
  m_nCount++;
  if (!SetSize(m_nCount, false))
    return false;
  if (m_nCount) {
    if (pIO->ReadFloat32Float(m_pSamples+1, m_nCount-1)!=(icInt32Number)(m_nCount-1))
      return false;
  }
  //Initialize first point with zero.  Properly initialized during Begin()
  m_pSamples[0] = 0;
  return true;
}
References CIccSampledCurveSegment::m_nCount, CIccCurveSegment::m_nReserved, CIccSampledCurveSegment::m_pSamples, CIccIO::Read32(), CIccIO::ReadFloat32Float(), and CIccSampledCurveSegment::SetSize().
SetSize()
bool CIccSampledCurveSegment::SetSize (icUInt32Number nCount, bool bZeroAlloc = true) virtual inherited
Name: CIccSampledCurveSegment::SetSize
Purpose: Sets size of sampled lookup table. Previous data (if exists) is lost.
Args: nCount = number of elements in lut (must be >= 2). Note: the m_pSample[0] is initialized from the the previous segment. It is not saved as part of Write(), or loaded as part of Read(). It will be initialized during the call to Begin(), The actual count of elements written to the file will be nCount-1 bZeroAlloc = flag to decide if memory should be set to zero.
Return: true if allocation successful.
{
  if (!nCount) {
    if (m_pSamples)
      free(m_pSamples);
    m_pSamples = NULL;
    m_nCount = nCount;
    return true;
  }
  if (m_pSamples) {
    free(m_pSamples);
  }
  if (bZeroAlloc)
    m_pSamples = (icFloatNumber*)calloc(nCount, sizeof(icFloatNumber));
  else
    m_pSamples = (icFloatNumber*)malloc(nCount * sizeof(icFloatNumber));
  if (m_pSamples)
    m_nCount = nCount;
  else
    m_nCount = 0;
  return (m_pSamples != NULL);
}
References CIccSampledCurveSegment::m_nCount, and CIccSampledCurveSegment::m_pSamples.
Referenced by ParseXml(), and CIccSampledCurveSegment::Read().
StartPoint()
icFloatNumber CIccCurveSegment::StartPoint () inline inherited
{ return m_startPoint; }
References CIccCurveSegment::m_startPoint.
Referenced by CIccSegmentedCurve::Insert(), and CIccSegmentedCurve::Write().
ToXml()
bool CIccSampledCurveSegmentXml::ToXml (std::string & xml, std::string blanks)
{
  char buf[256];
  char line[256];
  sprintf(line, "<SampledSegment Start=\"%s\"", icSegPos(buf, m_startPoint));
  xml += blanks + line;
  sprintf(line, " End=\"%s\">\n",icSegPos(buf, m_endPoint));
  xml += line;
  CIccFloatArray::DumpArray(xml, blanks+"  ", m_pSamples, m_nCount, icConvertFloat, 8);
  xml += blanks + "</SampledSegment>\n";
  return true;
}
References CIccXmlArrayType< T, Tsig >::DumpArray(), icConvertFloat, icSegPos(), CIccCurveSegment::m_endPoint, CIccSampledCurveSegment::m_nCount, CIccSampledCurveSegment::m_pSamples, and CIccCurveSegment::m_startPoint.
Referenced by CIccSegmentedCurveXml::ToXml().
Validate()
icValidateStatus CIccSampledCurveSegment::Validate (std::string sigPath, std::string & sReport, const CIccTagMultiProcessElement * pMPE = NULL, const CIccProfile * pProfile = NULL) const virtual inherited
Name: CIccSampledCurveSegment::Validate
Purpose:
Args:
Return:
Implements CIccCurveSegment.
{
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  icValidateStatus rv = icValidateOK;
  if (m_nReserved) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " sampled curve has non zero reserved data.\n";
    rv = icValidateWarning;
  }
  if (m_nCount<1) {
    sReport += icMsgValidateCriticalError;
    sReport += sSigPathName;
    sReport += " sampled curve has too few sample points.\n";
    rv = icMaxStatus(rv, icValidateCriticalError);
  }
  else if (m_endPoint-m_startPoint == 0.0) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " sampled curve has a range of zero.\n";
    rv = icMaxStatus(rv, icValidateWarning);
  }
  return rv;
}
References CIccInfo::GetSigPathName(), icMaxStatus(), icMsgValidateCriticalError, icMsgValidateWarning, icValidateCriticalError, icValidateOK, icValidateWarning, CIccCurveSegment::m_endPoint, CIccSampledCurveSegment::m_nCount, CIccCurveSegment::m_nReserved, and CIccCurveSegment::m_startPoint.
Write()
bool CIccSampledCurveSegment::Write (CIccIO * pIO) virtual inherited
Name: CIccSampledCurveSegment::Write
Purpose:
Args:
Return:
Implements CIccCurveSegment.
{
  icCurveSegSignature sig = GetType();
  if (!pIO)
    return false;
  if (!pIO->Write32(&sig))
    return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  icUInt32Number nCount;
  if (m_nCount)
    nCount = m_nCount -1;
  else
    nCount = 0;
  if (!pIO->Write32(&nCount))
    return false;
  //First point in samples is ONLY for interpolation (not saved)
  if (nCount) {
    if (pIO->WriteFloat32Float(m_pSamples+1, nCount)!=(icInt32Number)nCount)
      return false;
  }
  return true;
}
References CIccSampledCurveSegment::GetType(), CIccSampledCurveSegment::m_nCount, CIccCurveSegment::m_nReserved, CIccSampledCurveSegment::m_pSamples, CIccIO::Write32(), and CIccIO::WriteFloat32Float().
Field Documentation
m_endPoint
icFloatNumber CIccCurveSegment::m_endPoint protected inherited
Referenced by CIccFormulaCurveSegment::CIccFormulaCurveSegment(), CIccFormulaCurveSegment::CIccFormulaCurveSegment(), CIccSampledCurveSegment::CIccSampledCurveSegment(), CIccSampledCurveSegment::CIccSampledCurveSegment(), CIccSampledCurveSegment::Apply(), CIccSampledCurveSegment::Begin(), CIccFormulaCurveSegment::Describe(), CIccSampledCurveSegment::Describe(), CIccCurveSegment::EndPoint(), CIccFormulaCurveSegment::operator=(), CIccSampledCurveSegment::operator=(), CIccFormulaCurveSegmentXml::ToXml(), ToXml(), and CIccSampledCurveSegment::Validate().
m_last
icFloatNumber CIccSampledCurveSegment::m_last protected inherited
Referenced by CIccSampledCurveSegment::CIccSampledCurveSegment(), CIccSampledCurveSegment::CIccSampledCurveSegment(), CIccSampledCurveSegment::Apply(), and CIccSampledCurveSegment::Begin().
m_nCount
icUInt32Number CIccSampledCurveSegment::m_nCount protected inherited
Referenced by CIccSampledCurveSegment::CIccSampledCurveSegment(), CIccSampledCurveSegment::CIccSampledCurveSegment(), CIccSampledCurveSegment::Begin(), CIccSampledCurveSegment::Describe(), CIccSampledCurveSegment::GetSize(), CIccSampledCurveSegment::operator=(), CIccSampledCurveSegment::Read(), CIccSampledCurveSegment::SetSize(), ToXml(), CIccSampledCurveSegment::Validate(), and CIccSampledCurveSegment::Write().
m_nReserved
icUInt32Number CIccCurveSegment::m_nReserved protected inherited
Referenced by CIccFormulaCurveSegment::CIccFormulaCurveSegment(), CIccFormulaCurveSegment::CIccFormulaCurveSegment(), CIccSampledCurveSegment::CIccSampledCurveSegment(), CIccSampledCurveSegment::CIccSampledCurveSegment(), CIccFormulaCurveSegment::operator=(), CIccSampledCurveSegment::operator=(), CIccFormulaCurveSegment::Read(), CIccSampledCurveSegment::Read(), CIccFormulaCurveSegmentXml::ToXml(), CIccFormulaCurveSegment::Validate(), CIccSampledCurveSegment::Validate(), CIccFormulaCurveSegment::Write(), and CIccSampledCurveSegment::Write().
m_pSamples
icFloatNumber* CIccSampledCurveSegment::m_pSamples protected inherited
Referenced by CIccSampledCurveSegment::CIccSampledCurveSegment(), CIccSampledCurveSegment::CIccSampledCurveSegment(), CIccSampledCurveSegment::~CIccSampledCurveSegment(), CIccSampledCurveSegment::Apply(), CIccSampledCurveSegment::Begin(), CIccSampledCurveSegment::Describe(), CIccSampledCurveSegment::GetSamples(), CIccSampledCurveSegment::operator=(), ParseXml(), CIccSampledCurveSegment::Read(), CIccSampledCurveSegment::SetSize(), ToXml(), and CIccSampledCurveSegment::Write().
m_range
icFloatNumber CIccSampledCurveSegment::m_range protected inherited
Referenced by CIccSampledCurveSegment::CIccSampledCurveSegment(), CIccSampledCurveSegment::CIccSampledCurveSegment(), CIccSampledCurveSegment::Apply(), and CIccSampledCurveSegment::Begin().
m_startPoint
icFloatNumber CIccCurveSegment::m_startPoint protected inherited
Referenced by CIccFormulaCurveSegment::CIccFormulaCurveSegment(), CIccFormulaCurveSegment::CIccFormulaCurveSegment(), CIccSampledCurveSegment::CIccSampledCurveSegment(), CIccSampledCurveSegment::CIccSampledCurveSegment(), CIccSampledCurveSegment::Apply(), CIccSampledCurveSegment::Begin(), CIccFormulaCurveSegment::Describe(), CIccSampledCurveSegment::Describe(), CIccFormulaCurveSegment::operator=(), CIccSampledCurveSegment::operator=(), CIccCurveSegment::StartPoint(), CIccFormulaCurveSegmentXml::ToXml(), ToXml(), and CIccSampledCurveSegment::Validate().
The documentation for this class was generated from the following file:
IccXML/IccLibXML/IccMpeXml.cpp