iccDEV: CIccOpDefVectorOr Class Reference
CIccOpDefVectorOr Class Reference
Public Member Functions
virtual int ArgsPushed (CIccMpeCalculator *pCalc, SIccCalcOp &op)
virtual int ArgsUsed (CIccMpeCalculator *pCalc, SIccCalcOp &op)
virtual void Describe (SIccCalcOp &op, std::string &desc, int nVerboseness)
virtual bool Exec (SIccCalcOp *op, SIccOpState &os)
virtual bool IsValid (CIccMpeCalculator *pCalc, SIccCalcOp &op)
Detailed Description
Member Function Documentation
ArgsPushed()
virtual int IIccOpDef::ArgsPushed (CIccMpeCalculator * pCalc, SIccCalcOp & op) inline virtual inherited
{ return op.ArgsPushed(pCalc);}
References SIccCalcOp::ArgsPushed().
ArgsUsed()
virtual int IIccOpDef::ArgsUsed (CIccMpeCalculator * pCalc, SIccCalcOp & op) inline virtual inherited
{ return op.ArgsUsed(pCalc);}
References SIccCalcOp::ArgsUsed().
Describe()
virtual void IIccOpDef::Describe (SIccCalcOp & op, std::string & desc, int nVerboseness) inline virtual inherited
{op.Describe(desc, nVerboseness);}
References SIccCalcOp::Describe().
Exec()
virtual bool CIccOpDefVectorOr::Exec (SIccCalcOp * op, SIccOpState & os) inline virtual
Reimplemented from IIccOpDef.
  {
    int j, n = op->data.select.v1+1;
    int tn = n*2;
    size_t ss = os.pStack->size();
    if (tn>(int)ss)
      return false;
    icFloatNumber *s = &(*os.pStack)[ss-tn];
    for (j=0; j<n; j++) {
      s[j] = (s[j]>=0.5f || s[j+n]>=0.5) ? 1.0f : 0.0f;
    }
    OsShrinkArgs(n);
    return true;
  }
References SIccOpState::pStack.
IsValid()
virtual bool IIccOpDef::IsValid (CIccMpeCalculator * pCalc, SIccCalcOp & op) inline virtual inherited
Reimplemented in CIccOpDefInvalid.
{ return op.IsValidOp(pCalc); }
References SIccCalcOp::IsValidOp().
The documentation for this class was generated from the following file:
IccProfLib/IccMpeCalc.cpp