iccDEV: CIccUTF16String Class Reference
CIccUTF16String Class Reference
#include <IccUtilXml.h>
Public Member Functions
CIccUTF16String ()
CIccUTF16String (const char *szStr)
CIccUTF16String (const CIccUTF16String &str)
CIccUTF16String (const icUInt16Number *uzStr)
virtual ~CIccUTF16String ()
const icUInt16Number * c_str ()
void Clear ()
bool FromUtf8 (const char *szStr, size_t sizeSrc=0)
CIccUTF16String & operator= (const char *szStr)
CIccUTF16String & operator= (const CIccUTF16String &wstr)
CIccUTF16String & operator= (const icUInt16Number *uzStr)
icUInt16Number operator[] (size_t m_nIndex)
bool Resize (size_t len)
size_t Size ()
const char * ToUtf8 (std::string &buf)
const wchar_t * ToWString (std::wstring &buf)
Static Public Member Functions
static size_t WStrlen (const icUInt16Number *uzStr)
Static Protected Member Functions
static size_t AllocSize (size_t n)
Protected Attributes
size_t m_alloc
size_t m_len
icUInt16Number * m_str
Detailed Description
Constructor & Destructor Documentation
CIccUTF16String() [1/4]
CIccUTF16String::CIccUTF16String ()
{
  m_alloc=64;
  m_len = 0;
  m_str = (icUInt16Number*)calloc(m_alloc, sizeof(icUInt16Number));
}
References m_alloc, m_len, and m_str.
CIccUTF16String() [2/4]
CIccUTF16String::CIccUTF16String (const icUInt16Number * uzStr)
{
  m_len = WStrlen(uzStr);
  m_alloc = AllocSize(m_len);
  m_str = (icUInt16Number *)malloc(m_alloc*sizeof(icUInt16Number));
  memcpy(m_str, uzStr, m_len+1*sizeof(icUInt16Number));
}
References AllocSize(), m_alloc, m_len, m_str, and WStrlen().
CIccUTF16String() [3/4]
CIccUTF16String::CIccUTF16String (const char * szStr)
{
  size_t sizeSrc = strlen(szStr);
  if (sizeSrc) {
    m_alloc = AllocSize(sizeSrc*2);
    m_str = (UTF16 *)calloc(m_alloc, sizeof(icUInt16Number)); //overallocate to allow for up to 4 bytes per character
    UTF16 *szDest = m_str;
    icConvertUTF8toUTF16((const UTF8 **)&szStr, (const UTF8 *)&szStr[sizeSrc], &szDest, &szDest[m_alloc], lenientConversion);
    if (m_str[0]==0xfeff) {
      size_t i;
      for (i=1; m_str[i]; i++)
        m_str[i-1] = m_str[i];
      m_str[i-1] = 0;
    }
    m_len = WStrlen(m_str);
  }
  else {
    m_alloc = 64;
    m_len = 0;
    m_str = (icUInt16Number*)calloc(m_alloc, sizeof(icUInt16Number));
  }
}
References AllocSize(), icConvertUTF8toUTF16(), lenientConversion, m_alloc, m_len, m_str, and WStrlen().
Referenced by CIccTagXmlTextDescription::ParseXml(), CIccTagXmlMultiLocalizedUnicode::ParseXml(), CIccTagXmlProfileSequenceId::ParseXml(), and CIccTagXmlDict::ParseXml().
CIccUTF16String() [4/4]
CIccUTF16String::CIccUTF16String (const CIccUTF16String & str)
{
  m_alloc = str.m_alloc;
  m_len = str.m_len;
  m_str = (icUInt16Number*)malloc(m_alloc*sizeof(icUInt16Number));
  memcpy(m_str, str.m_str, (m_alloc)*sizeof(icUInt16Number));
}
References m_alloc, m_len, and m_str.
~CIccUTF16String()
CIccUTF16String::~CIccUTF16String () virtual
{
  free(m_str);
}
References m_str.
Member Function Documentation
AllocSize()
static size_t CIccUTF16String::AllocSize (size_t n) inline static protected
{ return (((n+64)/64)*64); }
Referenced by CIccUTF16String(), CIccUTF16String(), FromUtf8(), operator=(), and Resize().
c_str()
const icUInt16Number * CIccUTF16String::c_str () inline
{ return m_str; }
References m_str.
Referenced by icUtf8ToUtf16(), CIccTagXmlMultiLocalizedUnicode::ParseXml(), CIccTagXmlProfileSequenceId::ParseXml(), and CIccTagXmlDict::ParseXml().
Clear()
void CIccUTF16String::Clear ()
{
  m_len = 0;
  m_str[0] = 0;
}
References m_len, and m_str.
FromUtf8()
bool CIccUTF16String::FromUtf8 (const char * szStr, size_t sizeSrc = 0)
{
  if (!sizeSrc)
    sizeSrc = strlen(szStr);
  if (sizeSrc) {
    size_t nAlloc = AllocSize(sizeSrc*2);
    if (m_alloc<=nAlloc) {
      m_str = (icUInt16Number*)icRealloc(m_str, nAlloc *sizeof(icUInt16Number));
      m_alloc = nAlloc;
    }
    if (m_str) {
      memset(m_str, 0, m_alloc * sizeof(icUInt16Number));
      UTF16 *szDest = m_str;
      icConvertUTF8toUTF16((const UTF8 **)&szStr, (const UTF8 *)&szStr[sizeSrc], &szDest, &szDest[m_alloc], lenientConversion);
      if (m_str[0]==0xfeff) {
        size_t i;
        for (i=1; m_str[i]; i++)
          m_str[i-1] = m_str[i];
        m_str[i-1] = 0;
      }
      m_len = WStrlen(m_str);
    }
    else {
      m_len =0;
      return false;
    }
  }
  else {
    m_len = 0;
    m_str[0] = 0;
  }
  return true;
}
References AllocSize(), icConvertUTF8toUTF16(), icRealloc(), lenientConversion, m_alloc, m_len, m_str, and WStrlen().
Referenced by icUtf8ToUtf16(), and operator=().
operator=() [1/3]
CIccUTF16String & CIccUTF16String::operator= (const char * szStr)
{
  FromUtf8(szStr, 0);
  return *this;
}
References FromUtf8().
Referenced by CIccTagXmlDict::ParseXml().
operator=() [2/3]
CIccUTF16String & CIccUTF16String::operator= (const CIccUTF16String & wstr)
{
  if (m_alloc<=wstr.m_alloc) {
    m_str = (icUInt16Number*)icRealloc(m_str, wstr.m_alloc *sizeof(icUInt16Number));
    if (m_str)
      m_alloc = wstr.m_alloc;
    else
      m_alloc = 0;
  }
  if (m_str) {
    m_len = wstr.m_len;
    memcpy(m_str, wstr.m_str, (m_len+1)*sizeof(icUInt16Number));
  }
  else {
    m_len = 0;
  }
  return *this;
}
References icRealloc(), m_alloc, m_len, and m_str.
operator=() [3/3]
CIccUTF16String & CIccUTF16String::operator= (const icUInt16Number * uzStr)
{
  size_t n = WStrlen(uzStr);
  size_t nAlloc = AllocSize(n);
  if (m_alloc<=nAlloc) {
    m_str = (icUInt16Number*)icRealloc(m_str, nAlloc*sizeof(icUInt16Number));
    if (m_str)
      m_alloc = nAlloc;
    else
      m_alloc = 0;
  }
  if (m_str) {
    m_len = n;
    memcpy(m_str, uzStr, (m_len+1)*sizeof(icUInt16Number));
  }
  else {
    m_len = 0;
  }
  return *this;
}
References AllocSize(), icRealloc(), m_alloc, m_len, m_str, and WStrlen().
operator[]()
icUInt16Number CIccUTF16String::operator[] (size_t m_nIndex) inline
{ return m_str[m_nIndex]; }
References m_str.
Referenced by CIccTagXmlTextDescription::ParseXml().
Resize()
bool CIccUTF16String::Resize (size_t len)
{
  if (len>m_alloc) {
    size_t nAlloc = AllocSize(len);
    m_str = (icUInt16Number*)icRealloc(m_str, nAlloc*sizeof(icUInt16Number));
    if (!m_str) {
      m_len = 0;
      return false;
    }
    m_alloc = nAlloc;
  }
  if (len>m_len) {
    memset(&m_str[m_len], 0x0020, (len-m_len)*sizeof(icUInt16Number));
  }
  m_len = len;
  m_str[m_len] = 0;
  return true;
}
References AllocSize(), icRealloc(), m_alloc, m_len, and m_str.
Size()
size_t CIccUTF16String::Size () inline
{ return m_len; }
References m_len.
Referenced by CIccTagXmlTextDescription::ParseXml().
ToUtf8()
const char * CIccUTF16String::ToUtf8 (std::string & buf)
{
  return icUtf16ToUtf8(buf, m_str, (int)m_len);
}
References icUtf16ToUtf8(), m_len, and m_str.
ToWString()
const wchar_t * CIccUTF16String::ToWString (std::wstring & buf)
{
  size_t i;
  buf.clear();
  for (i=0; i<m_len; i++) {
    buf += (wchar_t)m_str[i];
  }
  return buf.c_str();
}
References m_len, and m_str.
Referenced by CIccTagXmlDict::ParseXml().
WStrlen()
size_t CIccUTF16String::WStrlen (const icUInt16Number * uzStr) static
{
  size_t n=0;
  while(uzStr[n]) n++;
  return n;
}
Referenced by CIccUTF16String(), CIccUTF16String(), FromUtf8(), icUtf16ToUtf8(), and operator=().
Field Documentation
m_alloc
size_t CIccUTF16String::m_alloc protected
Referenced by CIccUTF16String(), CIccUTF16String(), CIccUTF16String(), CIccUTF16String(), FromUtf8(), operator=(), operator=(), and Resize().
m_len
size_t CIccUTF16String::m_len protected
Referenced by CIccUTF16String(), CIccUTF16String(), CIccUTF16String(), CIccUTF16String(), Clear(), FromUtf8(), operator=(), operator=(), Resize(), Size(), ToUtf8(), and ToWString().
m_str
icUInt16Number* CIccUTF16String::m_str protected
Referenced by CIccUTF16String(), CIccUTF16String(), CIccUTF16String(), CIccUTF16String(), ~CIccUTF16String(), c_str(), Clear(), FromUtf8(), operator=(), operator=(), operator[](), Resize(), ToUtf8(), and ToWString().
The documentation for this class was generated from the following files:
IccXML/IccLibXML/IccUtilXml.h
IccXML/IccLibXML/IccUtilXml.cpp