iccDEV: CIccDefaultEncProfileCacheHandler Class Reference
CIccDefaultEncProfileCacheHandler Class Reference
Public Member Functions
CIccDefaultEncProfileCacheHandler ()
virtual CIccProfile * GetEncodingProfile (const icUChar *szColorSpaceName)
Static Public Member Functions
static IIccEncProfileCacheHandler * GetHandler ()
static void SetEncCacheHandler (IIccEncProfileCacheHandler *pHandler)
Detailed Description
Constructor & Destructor Documentation
CIccDefaultEncProfileCacheHandler()
CIccDefaultEncProfileCacheHandler::CIccDefaultEncProfileCacheHandler () inline
{}
Referenced by IIccEncProfileCacheHandler::GetHandler().
Member Function Documentation
GetEncodingProfile()
virtual CIccProfile * CIccDefaultEncProfileCacheHandler::GetEncodingProfile (const icUChar * szColorSpaceName) inline virtual
Implements IIccEncProfileCacheHandler.
  {
    std::string file = "ISO22028-Encoded-";
    file += (char*)szColorSpaceName;
    file += ".icc";
    return OpenIccProfile(file.c_str());
  }
References OpenIccProfile().
GetHandler()
IIccEncProfileCacheHandler * IIccEncProfileCacheHandler::GetHandler () static inherited
{
  if (!g_pEncProfileCacheHandler) {
    g_pEncProfileCacheHandler = new CIccDefaultEncProfileCacheHandler();
  }
  return g_pEncProfileCacheHandler;
}
References CIccDefaultEncProfileCacheHandler(), and g_pEncProfileCacheHandler.
Referenced by icConvertEncodingProfile().
SetEncCacheHandler()
void IIccEncProfileCacheHandler::SetEncCacheHandler (IIccEncProfileCacheHandler * pHandler) static inherited
{
  if (pHandler) {
    if (g_pEncProfileCacheHandler) {
      delete g_pEncProfileCacheHandler;
    }
    g_pEncProfileCacheHandler = pHandler;
  }
}
References g_pEncProfileCacheHandler.
The documentation for this class was generated from the following file:
IccProfLib/IccEncoding.cpp