iccDEV: CIccSegmentedCurve Class Reference
CIccSegmentedCurve Class Reference
#include <IccMpeBasic.h>
Public Member Functions
CIccSegmentedCurve ()
CIccSegmentedCurve (const CIccSegmentedCurve &ITPC)
virtual ~CIccSegmentedCurve ()
virtual icFloatNumber Apply (icFloatNumber v) const
virtual bool Begin (icElemInterp nInterp, CIccTagMultiProcessElement *pMPE)
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual const icChar * GetClassName () const
virtual icCurveElemSignature GetType () const
bool Insert (CIccCurveSegment *pCurveSegment)
virtual CIccCurveSetCurve * NewCopy () const
CIccSegmentedCurve & operator= (const CIccSegmentedCurve &ParamCurveTag)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
void Reset ()
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccTagMultiProcessElement *pMPE=NULL, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccCurveSetCurve * Create (icCurveElemSignature sig)
Protected Attributes
CIccCurveSegmentList * m_list
icUInt32Number m_nReserved1
icUInt32Number m_nReserved2
Detailed Description
Class: CIccSegmentedCurve
Purpose: The Curve Set Segmented Curve Type
Constructor & Destructor Documentation
CIccSegmentedCurve() [1/2]
CIccSegmentedCurve::CIccSegmentedCurve ()
Name: CIccSegmentedCurve::CIccSegmentedCurve
Purpose:
Args:
Return:
{
  m_list = new CIccCurveSegmentList();
  m_nReserved1 = 0;
  m_nReserved2 = 0;
}
References m_list, m_nReserved1, and m_nReserved2.
Referenced by CIccCurveSetCurve::Create(), and CIccTagSegmentedCurve::Read().
CIccSegmentedCurve() [2/2]
CIccSegmentedCurve::CIccSegmentedCurve (const CIccSegmentedCurve & curve)
Name: CIccSegmentedCurve::CIccSegmentedCurve
Purpose:
Args:
Return:
{
  CIccCurveSegmentList::iterator i;
  m_list = new CIccCurveSegmentList();
  for (i=curve.m_list->begin(); i!=curve.m_list->end(); i++) {
    m_list->push_back((*i)->NewCopy());
  }
  m_nReserved1 = curve.m_nReserved1;
  m_nReserved2 = curve.m_nReserved2;
}
References m_list, m_nReserved1, m_nReserved2, and CIccCurveSegment::NewCopy().
Referenced by NewCopy().
~CIccSegmentedCurve()
CIccSegmentedCurve::~CIccSegmentedCurve () virtual
Name: CIccSegmentedCurve::~CIccSegmentedCurve
Purpose:
Args:
Return:
{
  Reset();
  delete m_list;
}
References m_list, and Reset().
Member Function Documentation
Apply()
icFloatNumber CIccSegmentedCurve::Apply (icFloatNumber v) const virtual
Name: CIccSegmentedCurve::Apply
Purpose:
Args:
Return:
Implements CIccCurveSetCurve.
{
 CIccCurveSegmentList::iterator i;
  for (i=m_list->begin(); i!=m_list->end(); i++) {
    if (v <= (*i)->EndPoint())
      return (*i)->Apply(v);
  }
  return v;
}
References CIccCurveSegment::Apply(), CIccCurveSegment::EndPoint(), and m_list.
Referenced by CIccTagSegmentedCurve::Apply().
Begin()
bool CIccSegmentedCurve::Begin (icElemInterp nInterp, CIccTagMultiProcessElement * pMPE) virtual
Name: CIccSegmentedCurve::Begin
Purpose:
Args:
Return:
Implements CIccCurveSetCurve.
{
  if (m_list->size()==0)
    return false;
 CIccCurveSegmentList::iterator i;
 CIccCurveSegment *pLast = NULL;
  for (i=m_list->begin(); i!=m_list->end(); i++) {
    if (!(*i)->Begin(pLast))
      return false;
    pLast = *i;
  }
  return true;
}
References CIccCurveSegment::Begin(), and m_list.
Referenced by CIccTagSegmentedCurve::Begin().
Create()
CIccCurveSetCurve * CIccCurveSetCurve::Create (icCurveElemSignature sig) static inherited
Name: CIccCurveSetCurve::Create
Purpose:
Args:
Return:
{
  switch (sig) {
  case icSigSegmentedCurve:
    return new CIccSegmentedCurve();
  case icSigSingleSampledCurve:
    return new CIccSingleSampledCurve();
  case icSigSampledCalculatorCurve:
    return new CIccSampledCalculatorCurve();
  default:
    return NULL;
  }
}
References CIccSampledCalculatorCurve::CIccSampledCalculatorCurve(), CIccSegmentedCurve(), CIccSingleSampledCurve::CIccSingleSampledCurve(), icSigSampledCalculatorCurve, icSigSegmentedCurve, and icSigSingleSampledCurve.
Referenced by CIccMpeCurveSet::Read(), and CIccMpeToneMap::Read().
Describe()
void CIccSegmentedCurve::Describe (std::string & sDescription, int nVerboseness) virtual
Name: CIccSegmentedCurve::Describe
Purpose:
Args:
Return:
Implements CIccCurveSetCurve.
{
  CIccCurveSegmentList::iterator i;
  sDescription += "BEGIN_CURVE\n";
  for (i=m_list->begin(); i!=m_list->end(); i++) {
    (*i)->Describe(sDescription, nVerboseness);
  }
}
References CIccCurveSegment::Describe(), and m_list.
Referenced by CIccTagSegmentedCurve::Describe().
GetClassName()
virtual const icChar * CIccSegmentedCurve::GetClassName () const inline virtual
Implements CIccCurveSetCurve.
{ return "CIccSegmentedCurve"; }
GetType()
virtual icCurveElemSignature CIccSegmentedCurve::GetType () const inline virtual
Implements CIccCurveSetCurve.
{ return icSigSegmentedCurve; }
References icSigSegmentedCurve.
Referenced by Read(), Validate(), and Write().
Insert()
bool CIccSegmentedCurve::Insert (CIccCurveSegment * pCurveSegment)
Name: CIccSegmentedCurve::Insert
Purpose:
Args:
Return:
{
  CIccCurveSegmentList::reverse_iterator last = m_list->rbegin();
  if (last!=m_list->rend()) {
    if (pCurveSegment->StartPoint() == (*last)->EndPoint()) {
      m_list->push_back(pCurveSegment);
      return true;
    }
  }
  else {
    m_list->push_back(pCurveSegment);
    return true;
  }
  return false;
}
References CIccCurveSegment::EndPoint(), m_list, and CIccCurveSegment::StartPoint().
NewCopy()
virtual CIccCurveSetCurve * CIccSegmentedCurve::NewCopy () const inline virtual
Implements CIccCurveSetCurve.
{ return new CIccSegmentedCurve(*this);}
References CIccSegmentedCurve().
Referenced by CIccTagSegmentedCurve::CIccTagSegmentedCurve(), CIccDefaultEncProfileConverter::ConvertFromParams(), and CIccTagSegmentedCurve::operator=().
operator=()
CIccSegmentedCurve & CIccSegmentedCurve::operator= (const CIccSegmentedCurve & curve)
Name: &CIccSegmentedCurve::operator=
Purpose:
Args:
Return:
{
  Reset();
  CIccCurveSegmentList::iterator i;
  for (i=curve.m_list->begin(); i!=curve.m_list->end(); i++) {
    m_list->push_back((*i)->NewCopy());
  }
  m_nReserved1 = curve.m_nReserved1;
  m_nReserved2 = curve.m_nReserved2;
  return (*this);
}
References m_list, m_nReserved1, m_nReserved2, CIccCurveSegment::NewCopy(), and Reset().
Read()
bool CIccSegmentedCurve::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccSegmentedCurve::Read
Purpose:
Args:
Return:
Implements CIccCurveSetCurve.
{
  icCurveElemSignature sig;
  icUInt32Number startPos = pIO->Tell();
  icUInt32Number headerSize = sizeof(icCurveElemSignature) +
    sizeof(icUInt32Number) +
    sizeof(icUInt16Number) +
    sizeof(icUInt16Number);
  if (headerSize > size)
    return false;
  if (!pIO) {
    return false;
  }
  if (!pIO->Read32(&sig))
    return false;
  if (sig!=GetType())
    return false;
  if (!pIO->Read32(&m_nReserved1))
    return false;
  icUInt16Number nSegments;
  if (!pIO->Read16(&nSegments))
    return false;
  if (!pIO->Read16(&m_nReserved2))
    return false;
  Reset();
  icUInt32Number pos = pIO->Tell();
  icCurveSegSignature segSig;
  CIccCurveSegment *pSeg;
  if (nSegments==1) {
    if (sizeof(segSig) > size - headerSize)
      return false;
    if (!pIO->Read32(&segSig))
      return false;
    pSeg = CIccCurveSegment::Create(segSig, icMinFloat32Number, icMaxFloat32Number);
    if (!pSeg)
      return false;
    pIO->Seek(pos, icSeekSet);
    if (!pSeg->Read(size-(pos-startPos), pIO)) {
      delete pSeg;
      return false;
    }
    m_list->push_back(pSeg);
  }
  else if (nSegments) {
    if (nSegments > size - headerSize)
      return false;
    icFloatNumber *breakpoints=(icFloatNumber*)calloc(nSegments-1, sizeof(icFloatNumber));
    if (!breakpoints)
      return false;
    if (pIO->ReadFloat32Float(breakpoints, nSegments-1)!=nSegments-1) {
      free(breakpoints);
      return false;
    }
    int i;
    for (i=0; i<nSegments; i++) {
      pos = pIO->Tell();
      if (!pIO->Read32(&segSig)) {
        free(breakpoints);
        return false;
      }
      if (pIO->Seek(pos, icSeekSet)!=(icInt32Number)pos)
        return false;;
      if (!i)
        pSeg = CIccCurveSegment::Create(segSig, icMinFloat32Number, breakpoints[i]);
      else if (i==nSegments-1)
        pSeg = CIccCurveSegment::Create(segSig, breakpoints[i-1], icMaxFloat32Number);
      else
        pSeg = CIccCurveSegment::Create(segSig, breakpoints[i-1], breakpoints[i]);
      if (!pSeg) {
        free(breakpoints);
        return false;
      }
      if (!pSeg->Read(size-(pos-startPos), pIO)) {
        delete pSeg;
        free(breakpoints);
        return false;
      }
      m_list->push_back(pSeg);
    }
    free(breakpoints);
  }
  return true;
}
References CIccCurveSegment::Create(), GetType(), icSeekSet, m_list, m_nReserved1, m_nReserved2, CIccCurveSegment::Read(), CIccIO::Read16(), CIccIO::Read32(), CIccIO::ReadFloat32Float(), Reset(), CIccIO::Seek(), and CIccIO::Tell().
Referenced by CIccTagSegmentedCurve::Read().
Reset()
void CIccSegmentedCurve::Reset ()
Name: CIccSegmentedCurve::Reset
Purpose:
Args:
Return:
{
  CIccCurveSegmentList::iterator i;
  for (i=m_list->begin(); i!=m_list->end(); i++) {
    delete (*i);
  }
  m_list->clear();
}
References m_list.
Referenced by ~CIccSegmentedCurve(), operator=(), and Read().
Validate()
icValidateStatus CIccSegmentedCurve::Validate (std::string sigPath, std::string & sReport, const CIccTagMultiProcessElement * pMPE = NULL, const CIccProfile * pProfile = NULL) const virtual
Name: CIccSegmentedCurve::Validate
Purpose:
Args:
Return:
Implements CIccCurveSetCurve.
{
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  icValidateStatus rv = icValidateOK;
  if (m_nReserved1 || m_nReserved2) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " Segmented curve has non zero reserved data.\n";
    rv = icValidateWarning;
  }
  if (m_list->size()==0) {
    sReport += icMsgValidateCriticalError;
    sReport += sSigPathName;
    sReport += " Has Empty CurveSegment!\n";
    return icMaxStatus(rv, icValidateCriticalError);
  }
  CIccCurveSegmentList::iterator i;
  for (i=m_list->begin(); i!=m_list->end(); i++) {
    rv = icMaxStatus(rv, (*i)->Validate(sigPath+icGetSigPath(GetType()), sReport, pMPE, pProfile));
  }
  return rv;
}
References CIccInfo::GetSigPathName(), GetType(), icGetSigPath(), icMaxStatus(), icMsgValidateCriticalError, icMsgValidateWarning, icValidateCriticalError, icValidateOK, icValidateWarning, m_list, m_nReserved1, m_nReserved2, and CIccCurveSegment::Validate().
Referenced by CIccTagSegmentedCurve::Validate().
Write()
bool CIccSegmentedCurve::Write (CIccIO * pIO) virtual
Name: CIccSegmentedCurve::Write
Purpose:
Args:
Return:
Implements CIccCurveSetCurve.
{
  icCurveElemSignature sig = GetType();
  if (!pIO)
    return false;
  if (!pIO->Write32(&sig))
    return false;
  if (!pIO->Write32(&m_nReserved1))
    return false;
  icUInt16Number nSegments = (icUInt16Number)m_list->size();
  if (!pIO->Write16(&nSegments))
    return false;
  if (!pIO->Write16(&m_nReserved2))
    return false;
  CIccCurveSegmentList::iterator i;
  if (nSegments>1) {
    icFloatNumber breakpoint;
    i=m_list->begin();
    for (i++; i!=m_list->end(); i++) {
      breakpoint = (*i)->StartPoint();
      if (!pIO->WriteFloat32Float(&breakpoint))
        return false;
    }
  }
  for (i=m_list->begin(); i!=m_list->end(); i++) {
    if (!(*i)->Write(pIO))
      return false;
  }
  return true;
}
References GetType(), m_list, m_nReserved1, m_nReserved2, CIccCurveSegment::StartPoint(), CIccCurveSegment::Write(), CIccIO::Write16(), CIccIO::Write32(), and CIccIO::WriteFloat32Float().
Referenced by CIccTagSegmentedCurve::Write().
Field Documentation
m_list
CIccCurveSegmentList* CIccSegmentedCurve::m_list protected
Referenced by CIccSegmentedCurve(), CIccSegmentedCurve(), ~CIccSegmentedCurve(), Apply(), Begin(), Describe(), Insert(), operator=(), CIccSegmentedCurveXml::ParseXml(), Read(), Reset(), CIccSegmentedCurveXml::ToXml(), Validate(), and Write().
m_nReserved1
icUInt32Number CIccSegmentedCurve::m_nReserved1 protected
Referenced by CIccSegmentedCurve(), CIccSegmentedCurve(), operator=(), Read(), Validate(), and Write().
m_nReserved2
icUInt32Number CIccSegmentedCurve::m_nReserved2 protected
Referenced by CIccSegmentedCurve(), CIccSegmentedCurve(), operator=(), Read(), Validate(), and Write().
The documentation for this class was generated from the following files:
IccProfLib/IccMpeBasic.h
IccProfLib/IccMpeBasic.cpp