iccDEV: IccProfLib/IccEncoding.h File Reference
IccEncoding.h File Reference
#include "IccProfile.h"
Data Structures
class IIccEncProfileCacheHandler
class IIccEncProfileConverter
Enumerations
enum icStatusEncConvert {
icEncConvertOk = 0 , icEncConvertBadProfile , icEncConvertNoBaseProfile , icEncConvertBadBaseProfile ,
icEncConvertBadParams , icEncConvertMemoryError
}
Functions
icStatusEncConvert ICCPROFLIB_API icConvertEncodingProfile (CIccProfilePtr &newIcc, CIccProfile *pEncodeIcc)
Detailed Description
File: IccEncode.h
Contains: Header for implementation of Encoded profile class utiltities
Version: V1
Copyright: (c) see ICC Software License
Definition in file IccEncoding.h.
Enumeration Type Documentation
icStatusEncConvert
enum icStatusEncConvert
Enumerator
icEncConvertOk
icEncConvertBadProfile
icEncConvertNoBaseProfile
icEncConvertBadBaseProfile
icEncConvertBadParams
icEncConvertMemoryError
             {
  icEncConvertOk = 0,
  icEncConvertBadProfile,
  icEncConvertNoBaseProfile,
  icEncConvertBadBaseProfile,
  icEncConvertBadParams,
  icEncConvertMemoryError,
} icStatusEncConvert;
Function Documentation
icConvertEncodingProfile()
icStatusEncConvert ICCPROFLIB_API icConvertEncodingProfile (CIccProfilePtr & newIcc, CIccProfile * pEncodeIcc)
{
  newIcc = NULL;
  if (!pEncodeIcc || pEncodeIcc->m_Header.deviceClass!=icSigColorEncodingClass)
    return icEncConvertBadProfile;
  CIccTag *pTag;
  CIccTagStruct *pParams=NULL;
  pTag = pEncodeIcc->FindTagOfType(icSigReferenceNameTag, icSigUtf8TextType);
  if (pTag) {
    CIccTagUtf8Text *pText = (CIccTagUtf8Text*)pTag;
    const icUChar *szRefName = pText->GetText();
    if (!strcmp((const char*)szRefName, "ISO 22028-1")) {
      pTag = pEncodeIcc->FindTagOfType(icSigColorEncodingParamsTag, icSigTagStructType);
      if (pTag)
        pParams = (CIccTagStruct*)pTag->NewCopy();
    }
    else {
      CIccTag *pNameTag = pEncodeIcc->FindTagOfType(icSigColorSpaceNameTag, icSigUtf8TextType);
      if (pNameTag) {
        pText = (CIccTagUtf8Text *)pNameTag;
        const icUChar *szName = pText->GetText();
        CIccProfile *pBaseIcc = IIccEncProfileCacheHandler::GetHandler()->GetEncodingProfile(szName);
        if (!pBaseIcc) {
          return icEncConvertNoBaseProfile;
        }
        pTag = pBaseIcc->FindTagOfType(icSigColorEncodingParamsTag, icSigTagStructType);
        if (!pTag) {
           delete pBaseIcc;
           return icEncConvertBadBaseProfile;
        }
        pParams = (CIccTagStruct*)pTag->NewCopy();
        delete pBaseIcc;
        //Now Copy Overrides into pParams (if they exist in pEncodeIcc
        CIccTag *pOverridesTag = pEncodeIcc->FindTagOfType(icSigColorEncodingParamsTag, icSigTagStructType);
        if (pOverridesTag) {
          CIccTagStruct *pStruct = (CIccTagStruct*)pOverridesTag;
          TagEntryList *pTags = pStruct->GetElemList();
          if (pTags) {
            TagEntryList::iterator entry;
            for (entry=pTags->begin(); entry!=pTags->end(); entry++) {
              if (entry->pTag) {
                pStruct->DeleteElem(entry->TagInfo.sig);
                pStruct->AttachElem(entry->TagInfo.sig, entry->pTag->NewCopy());
              }
            }
          }
        }
      }
    }
  }
  if (!pParams) {
    return icEncConvertBadProfile;
  }
  //Create and initialize new profile from pEncodeIcc and pParams
  icStatusEncConvert stat = IIccEncProfileConverter::GetHandler()->ConvertFromParams(newIcc, pParams, &pEncodeIcc->m_Header);
  delete pParams;
  return stat;
}
References CIccTagStruct::AttachElem(), CIccProfile, IIccEncProfileConverter::ConvertFromParams(), CIccTagStruct::DeleteElem(), icHeader::deviceClass, CIccTagStruct::GetElemList(), IIccEncProfileCacheHandler::GetEncodingProfile(), IIccEncProfileCacheHandler::GetHandler(), IIccEncProfileConverter::GetHandler(), CIccTagUtf8Text::GetText(), icEncConvertBadBaseProfile, icEncConvertBadProfile, icEncConvertNoBaseProfile, icSigColorEncodingClass, icSigColorEncodingParamsTag, icSigColorSpaceNameTag, icSigReferenceNameTag, icSigTagStructType, icSigUtf8TextType, CIccTag::NewCopy(), and icTag::sig.