iccDEV: CIccTagProfileSequenceId Class Reference
CIccTagProfileSequenceId Class Reference
#include <IccTagProfSeqId.h>
Public Member Functions
CIccTagProfileSequenceId ()
CIccTagProfileSequenceId (const CIccTagProfileSequenceId &lut)
virtual ~CIccTagProfileSequenceId ()
bool AddProfileDescription (CIccProfile &profile)
bool AddProfileDescription (const CIccProfileIdDesc &profileDesc)
CIccProfileIdDescList::iterator begin ()
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
CIccProfileIdDescList::iterator end ()
virtual const icChar * GetClassName () const
virtual IIccExtensionTag * GetExtension ()
CIccProfileIdDesc * GetFirst ()
CIccProfileIdDesc * GetLast ()
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
CIccTagProfileSequenceId & operator= (const CIccTagProfileSequenceId &lut)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
static CIccTagProfileSequenceId * ParseMem (icUInt8Number *pMem, icUInt32Number size)
Data Fields
icUInt32Number m_nReserved
Protected Member Functions
void Cleanup ()
Protected Attributes
CIccProfileIdDescList * m_list
Detailed Description
Class: CIccTagProfileSequenceId
Purpose: The ProfileSequenceId tag
Constructor & Destructor Documentation
CIccTagProfileSequenceId() [1/2]
CIccTagProfileSequenceId::CIccTagProfileSequenceId ()
Name: CIccTagProfileSequenceId::CIccTagProfileSequenceId
Purpose:
Args:
Return:
{
  m_list = new CIccProfileIdDescList();
}
References m_list.
CIccTagProfileSequenceId() [2/2]
CIccTagProfileSequenceId::CIccTagProfileSequenceId (const CIccTagProfileSequenceId & psi)
Name: CIccTagProfileSequenceId::CIccTagProfileSequenceId
Purpose:
Args:
Return:
{
  m_list = new CIccProfileIdDescList();
  *m_list = *psi.m_list;
}
References m_list.
Referenced by NewCopy().
~CIccTagProfileSequenceId()
CIccTagProfileSequenceId::~CIccTagProfileSequenceId () virtual
Name: CIccTagProfileSequenceId::~CIccTagProfileSequenceId
Purpose:
Args:
Return:
{
  delete m_list;
}
References m_list.
Member Function Documentation
AddProfileDescription() [1/2]
bool CIccTagProfileSequenceId::AddProfileDescription (CIccProfile & profile) inline
{ return AddProfileDescription(CIccProfileIdDesc(profile)); }
References CIccProfileIdDesc::CIccProfileIdDesc(), and AddProfileDescription().
AddProfileDescription() [2/2]
bool CIccTagProfileSequenceId::AddProfileDescription (const CIccProfileIdDesc & profileDesc)
Name: sampleICC::CIccTagProfileSequenceId::AddProfileDescription
Purpose:
Args: CIccProfileIdDesc &profileDesc
Return: bool
{
  m_list->push_back(profileDesc);
  return true;
}
References m_list.
Referenced by AddProfileDescription().
begin()
CIccProfileIdDescList::iterator CIccTagProfileSequenceId::begin () inline
{ return m_list->begin(); }
References m_list.
Cleanup()
void CIccTagProfileSequenceId::Cleanup () protected
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagProfileSequenceId::Describe (std::string & sDescription, int nVerboseness) virtual
Name: CIccTagProfileSequenceId::Describe
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icChar buf[128];
  sprintf(buf, "BEGIN ProfileSequenceIdentification_TAG\n");
  sDescription += buf;
  sDescription += "\n";
  int i;
  CIccProfileIdDescList::iterator j;
  for (i=0, j=m_list->begin(); j!=m_list->end(); i++, j++) {
    sprintf(buf, "ProfileDescription_%d:\n", i+1);
    sDescription += buf;
    j->Describe(sDescription, nVerboseness);
  }
  sprintf(buf, "END ProfileSequenceIdentification_TAG\n");
  sDescription += buf;
  sDescription += "\n";
}
References CIccProfileIdDesc::Describe(), and m_list.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
end()
CIccProfileIdDescList::iterator CIccTagProfileSequenceId::end () inline
{ return m_list->end(); }
References m_list.
GetClassName()
virtual const icChar * CIccTagProfileSequenceId::GetClassName () const inline virtual
Reimplemented from CIccTag.
Reimplemented in CIccTagXmlProfileSequenceId.
{ return "CIccTagProfileSequenceId"; }
GetExtension()
virtual IIccExtensionTag * CIccTag::GetExtension () inline virtual inherited
Reimplemented in CIccTagXmlUnknown, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, CIccTagXmlSignature, CIccTagXmlNamedColor2, CIccTagXmlXYZ, CIccTagXmlChromaticity, CIccTagXmlCicp, CIccTagXmlSparseMatrixArray, CIccTagXmlFixedNum< T, Tsig >, CIccTagXmlNum< T, A, Tsig >, CIccTagXmlFloatNum< T, A, Tsig >, CIccTagXmlMeasurement, CIccTagXmlMultiLocalizedUnicode, CIccTagXmlTagData, CIccTagXmlDateTime, CIccTagXmlColorantOrder, CIccTagXmlColorantTable, CIccTagXmlViewingConditions, CIccTagXmlSpectralDataInfo, CIccTagXmlSpectralViewingConditions, CIccTagXmlProfileSeqDesc, CIccTagXmlResponseCurveSet16, CIccTagXmlCurve, CIccTagXmlParametricCurve, CIccTagXmlSegmentedCurve, CIccTagXmlLutAtoB, CIccTagXmlLutBtoA, CIccTagXmlLut8, CIccTagXmlLut16, CIccTagXmlMultiProcessElement, CIccTagXmlProfileSequenceId, CIccTagXmlDict, CIccTagXmlStruct, CIccTagXmlArray, CIccTagXmlGamutBoundaryDesc, CIccTagXmlEmbeddedHeightImage, CIccTagXmlEmbeddedNormalImage, and CIccTagXmlEmbeddedProfile.
{return NULL;}
Referenced by icCurvesFromXml(), icCurvesToXml(), icProfDescToXml(), icXmlParseProfDesc(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeXmlTintArray::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
GetFirst()
CIccProfileIdDesc * CIccTagProfileSequenceId::GetFirst ()
Name: sampleICC::CIccTagProfileSequenceId::GetFirst
Purpose:
Args:
Return: CIccProfileIdDesc *
{
  if (m_list->size())
    return &(*(m_list->begin()));
  return NULL;
}
References m_list.
GetLast()
CIccProfileIdDesc * CIccTagProfileSequenceId::GetLast ()
Name: sampleICC::CIccTagProfileSequenceId::GetLast
Purpose:
Args:
Return: CIccProfileIdDesc *
{
  if (m_list->size())
    return &(*(m_list->rbegin()));
  return NULL;
}
References m_list.
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagProfileSequenceId::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigProfileSequceIdType; }
References icSigProfileSequceIdType.
Referenced by Validate(), and Write().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
virtual CIccTag * CIccTagProfileSequenceId::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
{ return new CIccTagProfileSequenceId(*this);}
References CIccTagProfileSequenceId().
operator=()
CIccTagProfileSequenceId & CIccTagProfileSequenceId::operator= (const CIccTagProfileSequenceId & psi)
Name: &operator=
Purpose:
Args:
Return:
{
  if (&psi == this)
    return *this;
  *m_list = *psi.m_list;
  return *this;
}
References m_list.
ParseMem()
CIccTagProfileSequenceId * CIccTagProfileSequenceId::ParseMem (icUInt8Number * pMem, icUInt32Number size) static
Name: CIccTagProfileSequenceId::ParseMem
Purpose:
Args:
Return:
{
  CIccMemIO IO;
  if (!IO.Attach(pMem, size))
    return NULL;
  CIccTagProfileSequenceId *pProSeqId = new CIccTagProfileSequenceId;
  if (!pProSeqId->Read(size, &IO)) {
    delete pProSeqId;
    return NULL;
  }
  return pProSeqId;
}
References CIccMemIO::Attach(), and Read().
Read() [1/2]
bool CIccTagProfileSequenceId::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagProfileSequenceId::Read
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icUInt32Number headerSize = sizeof(icTagTypeSignature) +
    sizeof(icUInt32Number) +
    sizeof(icUInt32Number);
  if (headerSize > size)
    return false;
  if (!pIO) {
    return false;
  }
  m_list->clear();
  icUInt32Number sig;
  icUInt32Number tagStart = pIO->Tell();
  if (!pIO->Read32(&sig))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  icUInt32Number count, i;
  if (!pIO->Read32(&count))
    return false;
  if (headerSize + (icUInt64Number)count*sizeof(icUInt32Number)*2 > size)
    return false;
  if (!count) {
    return true;
  }
  icPositionNumber *pos = new icPositionNumber[count];
  if (!pos)
    return false;
  //Read TagDir
  for (i=0; i<count; i++) {
    if (!pIO->Read32(&pos[i].offset) ||
        !pIO->Read32(&pos[i].size)) {
      delete [] pos;
      return false;
    }
  }
  CIccProfileIdDesc pid;
  for (i=0; i<count; i++) {
    if (pos[i].offset + pos[i].size > size) {
      delete [] pos;
      return false;
    }
    pIO->Seek(tagStart + pos[i].offset, icSeekSet);
    if (!pid.Read(pos[i].size, pIO)) {
      delete [] pos;
      return false;
    }
    m_list->push_back(pid);
  }
  delete [] pos;
  return true;
}
References icSeekSet, m_list, CIccTag::m_nReserved, icPositionNumber::offset, CIccProfileIdDesc::Read(), CIccIO::Read32(), CIccIO::Seek(), icPositionNumber::size, and CIccIO::Tell().
Referenced by ParseMem().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
Validate()
icValidateStatus CIccTagProfileSequenceId::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagProfileSequenceId::Validate
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigName = Info.GetSigPathName(sigPath);
  CIccProfileIdDescList::iterator i;
  for (i=m_list->begin(); i!=m_list->end(); i++) {
    rv = icMaxStatus(rv, i->Validate(sigPath+icGetSigPath(GetType()), sReport, pProfile));
  }
  return rv;
}
References CIccInfo::GetSigPathName(), GetType(), icGetSigPath(), icMaxStatus(), m_list, CIccTag::Validate(), and CIccProfileIdDesc::Validate().
Write()
bool CIccTagProfileSequenceId::Write (CIccIO * pIO) virtual
Name: CIccTagProfileSequenceId::Write
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  if (!pIO)
    return false;
  icUInt32Number tagStart = pIO->Tell();
  if (!pIO->Write32(&sig))
    return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  icUInt32Number i, count = (icUInt32Number)m_list->size();
  pIO->Write32(&count);
  icPositionNumber *pos = new icPositionNumber[count];
  if (!pos)
    return false;
  icUInt32Number dirpos = pIO->Tell();
  //Write Unintialized TagDir
  for (i=0; i<count; i++) {
    pos[i].offset = 0;
    pos[i].size = 0;
    pIO->Write32(&pos[i].offset);
    pIO->Write32(&pos[i].size);
  }
  CIccProfileIdDescList::iterator j;
  //Write Tags
  for (i=0, j=m_list->begin(); j!= m_list->end(); i++, j++) {
    pos[i].offset = pIO->Tell();
    j->Write(pIO);
    pos[i].size = pIO->Tell() - pos[i].offset;
    pos[i].offset -= tagStart;
    pIO->Align32();
  }
  icUInt32Number endpos = pIO->Tell();
  pIO->Seek(dirpos, icSeekSet);
  //Write TagDir with offsets and sizes
  for (i=0; i<count; i++) {
    pIO->Write32(&pos[i].offset);
    pIO->Write32(&pos[i].size);
  }
  pIO->Seek(endpos, icSeekSet);
  return true;
}
References CIccIO::Align32(), GetType(), icSeekSet, m_list, CIccTag::m_nReserved, icPositionNumber::offset, CIccIO::Seek(), icPositionNumber::size, CIccIO::Tell(), CIccProfileIdDesc::Write(), and CIccIO::Write32().
Field Documentation
m_list
CIccProfileIdDescList* CIccTagProfileSequenceId::m_list protected
Referenced by CIccTagProfileSequenceId(), CIccTagProfileSequenceId(), ~CIccTagProfileSequenceId(), AddProfileDescription(), begin(), Describe(), end(), GetFirst(), GetLast(), operator=(), CIccTagXmlProfileSequenceId::ParseXml(), Read(), CIccTagXmlProfileSequenceId::ToXml(), Validate(), and Write().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and Write().
The documentation for this class was generated from the following files:
IccProfLib/IccTagProfSeqId.h
IccProfLib/IccTagProfSeqId.cpp