iccDEV: IccProfLib/IccEncoding.cpp File Reference
IccEncoding.cpp File Reference
#include "IccEncoding.h"
#include "IccProfile.h"
#include "IccTag.h"
#include "IccTagMPE.h"
#include "IccMpeBasic.h"
#include "IccCAM.h"
#include "IccUtil.h"
#include <string>
#include <time.h>
#include <cstring>
Data Structures
class CIccDefaultEncProfileCacheHandler
class CIccDefaultEncProfileConverter
Functions
icStatusEncConvert icConvertEncodingProfile (CIccProfilePtr &newIcc, CIccProfile *pEncodeIcc)
static icFloatNumber icGetParamFloatNum (CIccTagStruct *pParams, icColorEncodingParamsMemberSignature sig, icFloatNumber defaultValue=0)
static void icYxy2XYZVector (icFloatNumber *XYZ, icFloatNumber Y, icFloatNumber *xy, icUInt8Number idxOffset=1)
Variables
static IIccEncProfileCacheHandler * g_pEncProfileCacheHandler = NULL
static IIccEncProfileConverter * g_pEncProfileConverter = NULL
Function Documentation
icConvertEncodingProfile()
icStatusEncConvert icConvertEncodingProfile (CIccProfilePtr & newIcc, CIccProfile * pEncodeIcc)
{
  newIcc = NULL;
  if (!pEncodeIcc || pEncodeIcc->m_Header.deviceClass!=icSigColorEncodingClass)
    return icEncConvertBadProfile;
  CIccTag *pTag;
  CIccTagStruct *pParams=NULL;
  pTag = pEncodeIcc->FindTagOfType(icSigReferenceNameTag, icSigUtf8TextType);
  if (pTag) {
    CIccTagUtf8Text *pText = (CIccTagUtf8Text*)pTag;
    const icUChar *szRefName = pText->GetText();
    if (!strcmp((const char*)szRefName, "ISO 22028-1")) {
      pTag = pEncodeIcc->FindTagOfType(icSigColorEncodingParamsTag, icSigTagStructType);
      if (pTag)
        pParams = (CIccTagStruct*)pTag->NewCopy();
    }
    else {
      CIccTag *pNameTag = pEncodeIcc->FindTagOfType(icSigColorSpaceNameTag, icSigUtf8TextType);
      if (pNameTag) {
        pText = (CIccTagUtf8Text *)pNameTag;
        const icUChar *szName = pText->GetText();
        CIccProfile *pBaseIcc = IIccEncProfileCacheHandler::GetHandler()->GetEncodingProfile(szName);
        if (!pBaseIcc) {
          return icEncConvertNoBaseProfile;
        }
        pTag = pBaseIcc->FindTagOfType(icSigColorEncodingParamsTag, icSigTagStructType);
        if (!pTag) {
           delete pBaseIcc;
           return icEncConvertBadBaseProfile;
        }
        pParams = (CIccTagStruct*)pTag->NewCopy();
        delete pBaseIcc;
        //Now Copy Overrides into pParams (if they exist in pEncodeIcc
        CIccTag *pOverridesTag = pEncodeIcc->FindTagOfType(icSigColorEncodingParamsTag, icSigTagStructType);
        if (pOverridesTag) {
          CIccTagStruct *pStruct = (CIccTagStruct*)pOverridesTag;
          TagEntryList *pTags = pStruct->GetElemList();
          if (pTags) {
            TagEntryList::iterator entry;
            for (entry=pTags->begin(); entry!=pTags->end(); entry++) {
              if (entry->pTag) {
                pStruct->DeleteElem(entry->TagInfo.sig);
                pStruct->AttachElem(entry->TagInfo.sig, entry->pTag->NewCopy());
              }
            }
          }
        }
      }
    }
  }
  if (!pParams) {
    return icEncConvertBadProfile;
  }
  //Create and initialize new profile from pEncodeIcc and pParams
  icStatusEncConvert stat = IIccEncProfileConverter::GetHandler()->ConvertFromParams(newIcc, pParams, &pEncodeIcc->m_Header);
  delete pParams;
  return stat;
}
References CIccTagStruct::AttachElem(), CIccProfile, IIccEncProfileConverter::ConvertFromParams(), CIccTagStruct::DeleteElem(), icHeader::deviceClass, CIccTagStruct::GetElemList(), IIccEncProfileCacheHandler::GetEncodingProfile(), IIccEncProfileCacheHandler::GetHandler(), IIccEncProfileConverter::GetHandler(), CIccTagUtf8Text::GetText(), icEncConvertBadBaseProfile, icEncConvertBadProfile, icEncConvertNoBaseProfile, icSigColorEncodingClass, icSigColorEncodingParamsTag, icSigColorSpaceNameTag, icSigReferenceNameTag, icSigTagStructType, icSigUtf8TextType, CIccTag::NewCopy(), and icTag::sig.
icGetParamFloatNum()
static icFloatNumber icGetParamFloatNum (CIccTagStruct * pParams, icColorEncodingParamsMemberSignature sig, icFloatNumber defaultValue = 0) static
{
  CIccTagFloat32 *pTag = (CIccTagFloat32*)pParams->FindElemOfType(sig, icSigFloat32ArrayType);
  if (!pTag || pTag->GetSize()<1)
    return defaultValue;
  return (*pTag)[0];
}
References CIccTagStruct::FindElemOfType(), CIccTagFloatNum< T, Tsig >::GetSize(), icSigFloat32ArrayType, and CIccTagFloatNum< T, Tsig >::operator[]().
icYxy2XYZVector()
static void icYxy2XYZVector (icFloatNumber * XYZ, icFloatNumber Y, icFloatNumber * xy, icUInt8Number idxOffset = 1) static
{
  XYZ[0] = Y*xy[0] / xy[1];
  XYZ[idxOffset] = Y;
  XYZ[idxOffset<<1] = Y*(1.0f-xy[0]-xy[1]) / xy[1];
}
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams().
Variable Documentation
g_pEncProfileCacheHandler
IIccEncProfileCacheHandler* g_pEncProfileCacheHandler = NULL static
Referenced by IIccEncProfileCacheHandler::GetHandler(), and IIccEncProfileCacheHandler::SetEncCacheHandler().
g_pEncProfileConverter
IIccEncProfileConverter* g_pEncProfileConverter = NULL static
Referenced by IIccEncProfileConverter::GetHandler(), and IIccEncProfileConverter::SetEncProfileConverter().