iccDEV: IccXML/IccLibXML/IccUtilXml.h File Reference
IccUtilXml.h File Reference
#include "IccUtil.h"
#include "IccTag.h"
#include "IccXmlConfig.h"
#include "libxml/parser.h"
#include <vector>
#include <string>
Data Structures
class CIccUTF16String
class CIccXmlArrayType< T, Tsig >
Macros
#define icSigFloatArrayType ((icTagTypeSignature)0x66637420) /* 'flt ' */
#define icXmlStrCmp(x, y) strcmp((const char *)(x), (const char*)(y))
Typedefs
typedef CIccXmlArrayType< icFloat32Number, icSigFloat32ArrayType > CIccFloat32Array
typedef CIccXmlArrayType< icFloat64Number, icSigFloat64ArrayType > CIccFloat64Array
typedef CIccXmlArrayType< icFloatNumber, icSigFloatArrayType > CIccFloatArray
typedef CIccXmlArrayType< icUInt16Number, icSigUInt16ArrayType > CIccUInt16Array
typedef CIccXmlArrayType< icUInt32Number, icSigUInt32ArrayType > CIccUInt32Array
typedef CIccXmlArrayType< icUInt64Number, icSigUInt64ArrayType > CIccUInt64Array
typedef CIccXmlArrayType< icUInt8Number, icSigUInt8ArrayType > CIccUInt8Array
Functions
const char * icAnsiToUtf8 (std::string &buf, const char *szSrc)
bool icCLUTDataToXml (std::string &xml, CIccCLUT *pCLUT, icConvertType nType, std::string blanks, bool bSaveGridPoints=false)
bool icCLUTToXml (std::string &xml, CIccCLUT *pCLUT, icConvertType nType, std::string blanks, bool bSaveGridPoints=false, const char *szExtraAttrs="", const char *szName="CLUT")
const char * icFixXml (char *szDest, const char *szStr)
const char * icFixXml (std::string &buf, const char *szStr)
icMeasurementGeometry icGeNamedtMeasurementGeometryValue (const icChar *str)
icColorantEncoding icGetColorantValue (const icChar *str)
icDateTimeNumber icGetDateTimeValue (const icChar *str)
const std::string icGetDeviceAttrName (icUInt64Number devAttr)
icUInt64Number icGetDeviceAttrValue (xmlNode *pNode)
const std::string icGetHeaderFlagsName (icUInt32Number flags, bool bUsesMCS=false)
icIlluminant icGetIlluminantValue (const icChar *str)
icMeasurementUnitSig icGetMeasurementValue (const icChar *str)
icMeasurementFlare icGetNamedMeasurementFlareValue (const icChar *str)
icStandardObserver icGetNamedStandardObserverValue (const icChar *str)
const std::string icGetPadSpace (double value)
icRenderingIntent icGetRenderingIntentValue (const icChar *szRenderingIntent)
const icChar * icGetStandardObserverName (icStandardObserver str)
icTagSignature icGetTagNameSig (const icChar *szTagName)
const icChar * icGetTagSigName (icTagSignature tagSig)
const icChar * icGetTagSigTypeName (icTagTypeSignature tagTypeSig)
icTagTypeSignature icGetTypeNameTagSig (const icChar *szTagType)
const char * icUtf16ToUtf8 (std::string &buf, const icUInt16Number *szSrc, int sizeSrc=0)
const char * icUtf8ToAnsi (std::string &buf, const char *szSrc)
const unsigned short * icUtf8ToUtf16 (CIccUTF16String &buf, const char *szSrc, int sizeSrc=0)
const char * icXmlAttrValue (xmlAttr *attr, const char *szDefault="")
const char * icXmlAttrValue (xmlNode *pNode, const char *szName, const char *szDefault="")
icUInt32Number icXmlDumpHexData (std::string &xml, std::string blanks, void *pBuf, icUInt32Number nBufSize)
xmlAttr * icXmlFindAttr (xmlNode *pNode, const char *szAttrName)
xmlNode * icXmlFindNode (xmlNode *pNode, const char *szNodeName)
icUInt32Number icXmlGetChildSigVal (xmlNode *pNode)
icUInt32Number icXmlGetHexData (void *pBuf, const char *szText, icUInt32Number nBufSize)
icUInt32Number icXmlGetHexDataSize (const char *szText)
icUInt32Number icXmlNodeCount (xmlNode *pNode, const char *szNodeName)
icUInt32Number icXmlNodeCount2 (xmlNode *pNode, const char *szNodeName1, const char *szNodeName2)
icUInt32Number icXmlNodeCount3 (xmlNode *pNode, const char *szNodeName1, const char *szNodeName2, const char *szNodeName3)
icFloatNumber icXmlStrToFloat (const xmlChar *szStr)
icSignature icXmlStrToSig (const char *szStr)
Detailed Description
File: IccUtilXml.cpp
Contains: Implementation of Utilities used for ICC/XML processing
Version: V1
Copyright: (c) see ICC Software License
Definition in file IccUtilXml.h.
Macro Definition Documentation
icSigFloatArrayType
#define icSigFloatArrayType ((icTagTypeSignature)0x66637420) /* 'flt ' */
icXmlStrCmp
#define icXmlStrCmp (x, y) strcmp((const char *)(x), (const char*)(y))
Typedef Documentation
CIccFloat32Array
typedef CIccXmlArrayType<icFloat32Number, icSigFloat32ArrayType> CIccFloat32Array
CIccFloat64Array
typedef CIccXmlArrayType<icFloat64Number, icSigFloat64ArrayType> CIccFloat64Array
CIccFloatArray
typedef CIccXmlArrayType<icFloatNumber, icSigFloatArrayType> CIccFloatArray
CIccUInt16Array
typedef CIccXmlArrayType<icUInt16Number, icSigUInt16ArrayType> CIccUInt16Array
CIccUInt32Array
typedef CIccXmlArrayType<icUInt32Number, icSigUInt32ArrayType> CIccUInt32Array
CIccUInt64Array
typedef CIccXmlArrayType<icUInt64Number, icSigUInt64ArrayType> CIccUInt64Array
CIccUInt8Array
typedef CIccXmlArrayType<icUInt8Number, icSigUInt8ArrayType> CIccUInt8Array
Function Documentation
icAnsiToUtf8()
const char * icAnsiToUtf8 (std::string & buf, const char * szSrc)
{
#ifdef WIN32
  size_t len = strlen(szSrc)+1;
  wchar_t *szUnicodeBuf = (wchar_t*)malloc(len*sizeof(icUInt16Number)*2);
  char *szBuf = (char*)malloc(len*2);
  size_t n;
  n=MultiByteToWideChar(CP_ACP, 0, szSrc, (int)len-1, szUnicodeBuf, (int)len*2);
  szUnicodeBuf[n] = '\0';
  n = WideCharToMultiByte(CP_UTF8, 0, (const wchar_t*)szUnicodeBuf, (int)n, szBuf, (int)len*2, 0, NULL);
  szBuf[n] = '\0';
  buf = szBuf;
  free(szBuf);
  free(szUnicodeBuf);
#else
  buf = szSrc;
#endif
  return buf.c_str();
}
Referenced by icXmlDumpTextData(), CIccTagXmlNamedColor2::ToXml(), and CIccTagXmlColorantTable::ToXml().
icCLUTDataToXml()
bool icCLUTDataToXml (std::string & xml, CIccCLUT * pCLUT, icConvertType nType, std::string blanks, bool bSaveGridPoints = false)
{
  char buf[128];
  int nStartType = nType;
  if (nType == icConvertVariable) {
    nType = pCLUT->GetPrecision()==1 ? icConvert8Bit : icConvert16Bit;
  }
  if (bSaveGridPoints) {
    xml += blanks + "  <GridPoints>";
    int i;
    for (i=0; i<pCLUT->GetInputDim(); i++) {
      if (i)
        sprintf(buf, " %d", pCLUT->GridPoint(i));
      else
        sprintf(buf, "%d", pCLUT->GridPoint(i));
      xml += buf;
    }
    xml += "</GridPoints>\n";
  }
  int nPixelsPerRow = pCLUT->GridPoint(0);
  // if the CLUT has no GridPoints, profile is invalid
  if (nPixelsPerRow == 0) {
    printf("\nError! - CLUT Table not found.\n");
    return false;
  }
  CIccDumpXmlCLUT dumper(&xml, nType, blanks + "   ", pCLUT->GetOutputChannels(), nPixelsPerRow);
  xml += blanks + "  <TableData";
  if (nStartType == icConvertVariable && nType == icConvert8Bit) {
    sprintf(buf, " Precision=\"1\"");
    xml += buf;
  }
  xml += ">\n";
  pCLUT->Iterate(&dumper);
  dumper.Finish();
  xml += blanks + "  </TableData>\n";
  return true;
}
References CIccDumpXmlCLUT::CIccDumpXmlCLUT(), CIccDumpXmlCLUT::Finish(), CIccCLUT::GetInputDim(), CIccCLUT::GetOutputChannels(), CIccCLUT::GetPrecision(), CIccCLUT::GridPoint(), icConvert16Bit, icConvert8Bit, icConvertVariable, and CIccCLUT::Iterate().
Referenced by icCLUTToXml(), CIccMpeXmlEmissionCLUT::ToXml(), and CIccMpeXmlReflectanceCLUT::ToXml().
icCLUTToXml()
bool icCLUTToXml (std::string & xml, CIccCLUT * pCLUT, icConvertType nType, std::string blanks, bool bSaveGridPoints = false, const char * szExtraAttrs = "", const char * szName = "CLUT")
{
  char buf[128];
  xml += blanks + "<" + szName;
  if (!bSaveGridPoints) {
    sprintf(buf, " GridGranularity=\"%d\"", pCLUT->GridPoint(0));
    xml += buf;
  }
   if (szExtraAttrs && *szExtraAttrs) {
    xml += szExtraAttrs;
  }
  xml += ">\n";
  icCLUTDataToXml(xml, pCLUT, nType, blanks, bSaveGridPoints);
  xml += blanks + "</" + szName + ">\n";
  return true;
}
References CIccCLUT::GridPoint(), and icCLUTDataToXml().
Referenced by icMBBToXml(), CIccMpeXmlCLUT::ToXml(), and CIccMpeXmlExtCLUT::ToXml().
icFixXml() [1/2]
const char * icFixXml (char * szDest, const char * szStr)
{
  char *m_ptr = szDest;
  while (*szStr) {
    switch (*szStr) {
    case '\'':
      strcpy(m_ptr, "&apos;");
      m_ptr += 6;
      break;
    case '&':
      strcpy(m_ptr, "&amp;");
      m_ptr += 5;
      break;
    case '\"':
      strcpy(m_ptr, "&quot;");
      m_ptr += 6;
      break;
    case '<':
      strcpy(m_ptr, "&lt;");
      m_ptr += 4;
      break;
    case '>':
      strcpy(m_ptr, "&gt;");
      m_ptr += 4;
      break;
    default:
      *m_ptr++ = *szStr;
    }
    szStr++;
  }
  *m_ptr = '\0';
  return szDest;
}
Referenced by icProfDescToXml(), CIccMpeXmlUnknown::ToXml(), CIccMpeXmlBAcs::ToXml(), CIccMpeXmlEAcs::ToXml(), CIccTagXmlSignature::ToXml(), CIccTagXmlNamedColor2::ToXml(), CIccTagXmlColorantTable::ToXml(), CIccTagXmlSpectralDataInfo::ToXml(), CIccTagXmlProfileSequenceId::ToXml(), CIccTagXmlDict::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
icFixXml() [2/2]
const char * icFixXml (std::string & buf, const char * szStr)
{
  buf = "";
  while (*szStr) {
    switch (*szStr) {
    case '\'':
      buf += "&apos;";
      break;
    case '&':
      buf += "&amp;";
      break;
    case '\"':
      buf += "&quot;";
      break;
    case '<':
      buf += "&lt;";
      break;
    case '>':
      buf += "&gt;";
      break;
    default:
      buf += *szStr;
    }
    szStr++;
  }
  return buf.c_str();
}
Referenced by CIccTagXmlTextDescription::ToXml(), and CIccTagXmlMultiLocalizedUnicode::ToXml().
icGeNamedtMeasurementGeometryValue()
icMeasurementGeometry icGeNamedtMeasurementGeometryValue (const icChar * str)
{
  if (!strcmp(str, "Geometry Unknown"))
    return icGeometryUnknown;
  if (!strcmp(str, "Geometry 0-45 or 45-0"))
      return icGeometry045or450;
  if (!strcmp(str, "Geometry 0-d or d-0"))
      return icGeometry0dord0;
  if (!strcmp(str, "Max Geometry"))
      return icMaxEnumGeometry;
  return icGeometryUnknown;
}
References icGeometry045or450, icGeometry0dord0, and icGeometryUnknown.
Referenced by CIccTagXmlMeasurement::ParseXml().
icGetColorantValue()
icColorantEncoding icGetColorantValue (const icChar * str)
{
    if (!strcmp(str, "ITU-R BT.709"))
        return icColorantITU;
    if (!strcmp(str, "SMPTE RP145-1994"))
        return icColorantSMPTE;
    if (!strcmp(str, "EBU Tech.3213-E"))
        return icColorantEBU;
    if (!strcmp(str, "P22"))
        return icColorantP22;
  return icColorantUnknown;
}
References icColorantEBU, icColorantITU, icColorantP22, icColorantSMPTE, and icColorantUnknown.
Referenced by CIccTagXmlChromaticity::ParseXml().
icGetDateTimeValue()
icDateTimeNumber icGetDateTimeValue (const icChar * str)
{
    unsigned int day=0, month=0, year=0, hours=0, minutes=0, seconds=0;
    icDateTimeNumber dateTime = {};
  if (!stricmp(str, "now")) {
    time_t rawtime;
    struct tm * timeinfo;
    time ( &rawtime );
    timeinfo = localtime ( &rawtime );
    year = timeinfo->tm_year+1900;
    month = timeinfo->tm_mon+1;
    day = timeinfo->tm_mday;
    hours = timeinfo->tm_hour;
    minutes = timeinfo->tm_min;
    seconds = timeinfo->tm_sec;
  }
  else {
    sscanf(str, "%d-%02d-%02dT%02d:%02d:%02d", &year, &month, &day, &hours, &minutes, &seconds);
  }
    dateTime.year = year;
    dateTime.month = month;
    dateTime.day = day;
    dateTime.hours = hours;
    dateTime.minutes = minutes;
    dateTime.seconds = seconds;
    return dateTime;
}
References icDateTimeNumber::day, icDateTimeNumber::hours, icDateTimeNumber::minutes, icDateTimeNumber::month, icDateTimeNumber::seconds, and icDateTimeNumber::year.
Referenced by CIccProfileXml::ParseBasic(), and CIccTagXmlDateTime::ParseXml().
icGetDeviceAttrName()
const std::string icGetDeviceAttrName (icUInt64Number devAttr)
{
    char line[256];
    std::string xml;
    if (devAttr & icTransparency)
        sprintf(line, "<DeviceAttributes ReflectiveOrTransparency=\"transparency\"");
    else
        sprintf(line, "<DeviceAttributes ReflectiveOrTransparency=\"reflective\"");
    xml += line;
    if (devAttr & icMatte)
        sprintf(line, " GlossyOrMatte=\"matte\"");
    else
        sprintf(line, " GlossyOrMatte=\"glossy\"");
    xml += line;
    if (devAttr & icMediaNegative)
        sprintf(line, " MediaPolarity=\"negative\"");
    else
        sprintf(line, " MediaPolarity=\"positive\"");
    xml += line;
    if (devAttr & icMediaBlackAndWhite)
        sprintf(line, " MediaColour=\"blackAndwhite\"");
    else
        sprintf(line, " MediaColour=\"colour\"");
    xml += line;
  icUInt64Number otherAttr = ~((icUInt64Number)icTransparency|icMatte|icMediaNegative|icMediaBlackAndWhite);
  if (devAttr & otherAttr) {
    sprintf(line, " VendorSpecific=\"%016llx\"", devAttr & otherAttr);
    xml += line;
  }
  xml += "/>\n";
    return xml;
}
Referenced by icProfDescToXml(), and CIccProfileXml::ToXmlWithBlanks().
icGetDeviceAttrValue()
icUInt64Number icGetDeviceAttrValue (xmlNode * pNode)
{
    icUInt64Number devAttr = 0;
    xmlAttr *attr = icXmlFindAttr(pNode, "ReflectiveOrTransparency");
  if (attr && !strcmp(icXmlAttrValue(attr), "transparency")) {
    devAttr |= icTransparency;
  }
    attr = icXmlFindAttr(pNode, "GlossyOrMatte");
  if (attr && !strcmp(icXmlAttrValue(attr), "matte")) {
    devAttr |= icMatte;
    }
    attr = icXmlFindAttr(pNode, "MediaPolarity");
  if (attr && !strcmp(icXmlAttrValue(attr), "negative")) {
    devAttr |= icMediaNegative;
  }
    attr = icXmlFindAttr(pNode, "MediaColour");
  if (attr && !strcmp(icXmlAttrValue(attr), "blackAndWhite")) {
        devAttr |= icMediaBlackAndWhite;
    }
  attr = icXmlFindAttr(pNode, "VendorSpecific");
  if (attr) {
    icUInt64Number vendor;
    sscanf(icXmlAttrValue(attr), "%llx", &vendor);
    devAttr |= vendor;
  }
    return devAttr;
}
References icXmlAttrValue(), and icXmlFindAttr().
Referenced by icXmlParseProfDesc(), and CIccProfileXml::ParseBasic().
icGetHeaderFlagsName()
const std::string icGetHeaderFlagsName (icUInt32Number flags, bool bUsesMCS = false)
{
    char line[256];
    std::string xml;
  if (flags & icEmbeddedProfileTrue)
        sprintf(line, "<ProfileFlags EmbeddedInFile=\"true\"");
    else
      sprintf(line, "<ProfileFlags EmbeddedInFile=\"false\"");
    xml += line;
  if (flags & icUseWithEmbeddedDataOnly)
        sprintf(line, " UseWithEmbeddedDataOnly=\"true\"");
    else
        sprintf(line, " UseWithEmbeddedDataOnly=\"false\"");
    xml += line;
  if (flags & icExtendedRangePCS) {
    sprintf(line, " ExtendedRangePCS=\"true\"");
    xml += line;
  }
  icUInt32Number otherFlags = ~(icEmbeddedProfileTrue | icUseWithEmbeddedDataOnly | icExtendedRangePCS);
  if (bUsesMCS) {
    if (flags & icMCSNeedsSubsetTrue)
      sprintf(line, " MCSNeedsSubset=\"true\"");
    else
      sprintf(line, " MCSNeedsSubset=\"false\"");
    xml += line;
    otherFlags &= ~icMCSNeedsSubsetTrue;
  }
  if (flags & otherFlags) {
    sprintf(line, " VendorFlags=\"%08x\"", flags & otherFlags);
    xml += line;
  }
  xml += "/>\n";
  return xml;
}
Referenced by CIccProfileXml::ToXmlWithBlanks().
icGetIlluminantValue()
icIlluminant icGetIlluminantValue (const icChar * str)
{
  if (!strcmp(str, "Illuminant Unknown"))
      return icIlluminantUnknown;
  if (!strcmp(str, "Illuminant D50") || !strcmp(str, "D50"))
      return icIlluminantD50;
  if (!strcmp(str, "Illuminant D65") || !strcmp(str, "D65"))
      return icIlluminantD65;
  if (!strcmp(str, "Illuminant D93") || !strcmp(str, "D93"))
      return icIlluminantD93;
  if (!strcmp(str, "Illuminant F2") || !strcmp(str, "F2"))
      return icIlluminantF2;
  if (!strcmp(str, "Illuminant D55") || !strcmp(str, "D55"))
      return icIlluminantD55;
  if (!strcmp(str, "Illuminant A") || !strcmp(str, "A"))
      return icIlluminantA;
  if (!strcmp(str, "Illuminant EquiPowerE") || !strcmp(str, "Illuminant E") || !strcmp(str, "E"))
      return icIlluminantEquiPowerE;
  if (!strcmp(str, "Illuminant F8") || !strcmp(str, "F8"))
      return icIlluminantF8;
  if (!strcmp(str, "Illuminant Black Body") || !strcmp(str, "Black Body"))
    return icIlluminantBlackBody;
  if (!strcmp(str, "Illuminant Daylight") || !strcmp(str, "Daylight"))
    return icIlluminantDaylight;
  if (!strcmp(str, "Illuminant B") || !strcmp(str, "B"))
    return icIlluminantB;
  if (!strcmp(str, "Illuminant C") || !strcmp(str, "C"))
    return icIlluminantC;
  if (!strcmp(str, "Illuminant F1") || !strcmp(str, "F1"))
    return icIlluminantF1;
  if (!strcmp(str, "Illuminant F3") || !strcmp(str, "F3"))
    return icIlluminantF3;
  if (!strcmp(str, "Illuminant F4") || !strcmp(str, "F4"))
    return icIlluminantF4;
  if (!strcmp(str, "Illuminant F5") || !strcmp(str, "F5"))
    return icIlluminantF5;
  if (!strcmp(str, "Illuminant F6") || !strcmp(str, "F6"))
    return icIlluminantF6;
  if (!strcmp(str, "Illuminant F7") || !strcmp(str, "F7"))
    return icIlluminantF7;
  if (!strcmp(str, "Illuminant F9") || !strcmp(str, "F9"))
    return icIlluminantF9;
  if (!strcmp(str, "Illuminant F10") || !strcmp(str, "F10"))
    return icIlluminantF10;
  if (!strcmp(str, "Illuminant F11") || !strcmp(str, "F11"))
    return icIlluminantF11;
  if (!strcmp(str, "Illuminant F12") || !strcmp(str, "F12"))
    return icIlluminantF12;
  return icIlluminantCustom;
}
References icIlluminantA, icIlluminantB, icIlluminantBlackBody, icIlluminantC, icIlluminantD50, icIlluminantD55, icIlluminantD65, icIlluminantD93, icIlluminantDaylight, icIlluminantEquiPowerE, icIlluminantF1, icIlluminantF10, icIlluminantF11, icIlluminantF12, icIlluminantF2, icIlluminantF3, icIlluminantF4, icIlluminantF5, icIlluminantF6, icIlluminantF7, icIlluminantF8, icIlluminantF9, and icIlluminantUnknown.
Referenced by CIccTagXmlMeasurement::ParseXml(), CIccTagXmlViewingConditions::ParseXml(), and CIccTagXmlSpectralViewingConditions::ParseXml().
icGetMeasurementValue()
icMeasurementUnitSig icGetMeasurementValue (const icChar * str)
{
    if (!strcmp(str, "Status A"))
        return icSigStatusA;
    if (!strcmp(str, "Status E"))
        return icSigStatusE;
    if (!strcmp(str, "Status I"))
        return icSigStatusI;
    if (!strcmp(str, "Status T"))
        return icSigStatusT;
    if (!strcmp(str, "Status M"))
        return icSigStatusM;
    if (!strcmp(str, "DIN with no polarizing filter"))
        return icSigDN;
    if (!strcmp(str, "DIN with polarizing filter"))
        return icSigDNP;
    if (!strcmp(str, "Narrow band DIN with no polarizing filter"))
        return icSigDNN;
    if (!strcmp(str, "Narrow band DIN with polarizing filter"))
        return icSigDNNP;
  return icSigStatusA;
}
References icSigDN, icSigDNN, icSigDNNP, icSigDNP, icSigStatusA, icSigStatusE, icSigStatusI, icSigStatusM, and icSigStatusT.
Referenced by CIccTagXmlResponseCurveSet16::ParseXml().
icGetNamedMeasurementFlareValue()
icMeasurementFlare icGetNamedMeasurementFlareValue (const icChar * str)
{
  if (!strcmp(str, "Flare 0"))
      return icFlare0;
  if (!strcmp(str, "Flare 100"))
      return icFlare100;
  if (!strcmp(str, "Max Flare"))
      return icMaxEnumFlare;
  return icFlare0;
}
References icFlare0, and icFlare100.
Referenced by CIccTagXmlMeasurement::ParseXml().
icGetNamedStandardObserverValue()
icStandardObserver icGetNamedStandardObserverValue (const icChar * str)
{
  if (!strcmp(str, "Unknown observer"))
      return icStdObsUnknown;
  if (!strcmp(str, "CIE 1931 (two degree) standard observer"))
      return icStdObs1931TwoDegrees;
  if (!strcmp(str, "CIE 1964 (ten degree) standard observer"))
      return icStdObs1964TenDegrees;
  return icStdObsCustom;
}
References icStdObs1931TwoDegrees, icStdObs1964TenDegrees, and icStdObsUnknown.
Referenced by CIccTagXmlMeasurement::ParseXml(), and CIccTagXmlSpectralViewingConditions::ParseXml().
icGetPadSpace()
const std::string icGetPadSpace (double value)
{
  std::string space = "";
  if ( value >=0 && value < 10)
    space = "    ";
  if ( value >=10 && value < 100)
    space = "   ";
   if ( value >=100 && value < 1000 )
    space = "  ";
   return space;
}
icGetRenderingIntentValue()
icRenderingIntent icGetRenderingIntentValue (const icChar * szRenderingIntent)
{
  if (!strcmp(szRenderingIntent, "Perceptual"))
      return icPerceptual;
  else if (!strcmp(szRenderingIntent, "Media-relative colorimetric"))
      return icRelativeColorimetric;
  else if (!strcmp(szRenderingIntent, "Saturation"))
      return icSaturation;
  else if (!strcmp(szRenderingIntent, "ICC-absolute colorimetric"))
      return icAbsoluteColorimetric;
  return icPerceptual;
}
References icAbsoluteColorimetric, icPerceptual, icRelativeColorimetric, and icSaturation.
icGetStandardObserverName()
const icChar * icGetStandardObserverName (icStandardObserver str)
{
  switch (str) {
  case icStdObsUnknown:
    return "Unknown Observer";
  case icStdObs1931TwoDegrees:
    return "CIE 1931 standard colorimetric observer";
  case icStdObs1964TenDegrees:
    return "CIE 1964 standard colorimetric observer";
  default:
    return "Unknown Observer";
  }
}
References icStdObs1931TwoDegrees, icStdObs1964TenDegrees, and icStdObsUnknown.
Referenced by CIccTagXmlMeasurement::ToXml().
icGetTagNameSig()
icTagSignature icGetTagNameSig (const icChar * szTagName)
{
  return CIccTagCreator::GetTagNameSig(szName);
}
References CIccTagCreator::GetTagNameSig().
Referenced by CIccProfileXml::ParseTag(), and CIccTagXmlStruct::ParseTag().
icGetTagSigName()
const icChar * icGetTagSigName (icTagSignature tagSig)
{
  const icChar *rv = CIccTagCreator::GetTagSigName(tagTypeSig);
  // if  the tag signature is not found, it is a custom type.
  if (!rv)
    return "PrivateTag";
  return rv;
}
References CIccTagCreator::GetTagSigName().
icGetTagSigTypeName()
const icChar * icGetTagSigTypeName (icTagTypeSignature tagTypeSig)
{
  const icChar *rv = CIccTagCreator::GetTagTypeSigName(tagTypeSig);
  // if  the tag signature is not found, it is a custom type.
  if (!rv)
    return "PrivateType";
  return rv;
}
References CIccTagCreator::GetTagTypeSigName().
Referenced by icProfDescToXml(), CIccMpeXmlTintArray::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
icGetTypeNameTagSig()
icTagTypeSignature icGetTypeNameTagSig (const icChar * szTagType)
{
  return CIccTagCreator::GetTagTypeNameSig(szTagType);
}
References CIccTagCreator::GetTagTypeNameSig().
Referenced by icXmlParseProfDesc(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), and CIccTagXmlArray::ParseXml().
icUtf16ToUtf8()
const char * icUtf16ToUtf8 (std::string & buf, const icUInt16Number * szSrc, int sizeSrc = 0)
{
  if (!sizeSrc) {
    sizeSrc = (int)CIccUTF16String::WStrlen(szSrc);
  }
  int n = sizeSrc*4;
  if (n) {
    char *szBuf = (char *)malloc(n+1);
    char *szDest = szBuf;
    icConvertUTF16toUTF8(&szSrc, &szSrc[sizeSrc], (UTF8**)&szDest, (UTF8*)&szDest[n+1], lenientConversion);
    *szDest= '\0';
    buf = szBuf;
    free(szBuf);
  }
  else {
    buf.clear();
  }
  return buf.c_str();
}
References icConvertUTF16toUTF8(), lenientConversion, and CIccUTF16String::WStrlen().
Referenced by CIccUTF16String::ToUtf8(), CIccTagXmlTextDescription::ToXml(), CIccTagXmlMultiLocalizedUnicode::ToXml(), CIccTagXmlProfileSequenceId::ToXml(), and CIccTagXmlDict::ToXml().
icUtf8ToAnsi()
const char * icUtf8ToAnsi (std::string & buf, const char * szSrc)
{
#ifdef WIN32
  size_t len = strlen(szSrc)+1;
  wchar_t *szUnicodeBuf = (wchar_t*)malloc(len*sizeof(icUInt16Number)*2);
  char *szBuf = (char*)malloc(len*2);
  size_t n;
  n=MultiByteToWideChar(CP_UTF8, 0, szSrc, (int)len, szUnicodeBuf, (int)len*2);
  szUnicodeBuf[n] = '\0';
  n = WideCharToMultiByte(CP_ACP, 0, (const wchar_t*)szUnicodeBuf, (int)n, szBuf, (int)len*2, "?", NULL);
  szBuf[n] = '\0';
  buf = szBuf;
  free(szBuf);
  free(szUnicodeBuf);
#else
  buf = szSrc;
#endif
  return buf.c_str();
}
Referenced by icXmlParseTextString(), CIccTagXmlTextDescription::ParseXml(), CIccTagXmlNamedColor2::ParseXml(), and CIccTagXmlColorantTable::ParseXml().
icUtf8ToUtf16()
const unsigned short * icUtf8ToUtf16 (CIccUTF16String & buf, const char * szSrc, int sizeSrc = 0)
{
  buf.FromUtf8(szSrc, sizeSrc);
  return buf.c_str();
}
References CIccUTF16String::c_str(), and CIccUTF16String::FromUtf8().
icXmlAttrValue() [1/2]
const char * icXmlAttrValue (xmlAttr * attr, const char * szDefault = "")
{
  if (attr && attr->children && attr->children->type == XML_TEXT_NODE && attr->children->content)
    return (const char*)attr->children->content;
  return szDefault;
}
Referenced by icCLutFromXml(), icGetDeviceAttrValue(), icMatrixFromXml(), icMBBFromXml(), icXmlAttrValue(), icXmlParseColorAppearanceParams(), CIccProfileXml::ParseBasic(), CIccTagXmlMultiProcessElement::ParseElement(), CIccMpeXmlCalculator::ParseImport(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccFormulaCurveSegmentXml::ParseXml(), CIccSampledCurveSegmentXml::ParseXml(), CIccSampledCalculatorCurveXml::ParseXml(), CIccSinglSampledeCurveXml::ParseXml(), CIccMpeXmlTintArray::ParseXml(), CIccXmlToneMapFunc::ParseXml(), CIccTagXmlNamedColor2::ParseXml(), CIccTagXmlXYZ::ParseXml(), CIccTagXmlChromaticity::ParseXml(), CIccTagXmlCicp::ParseXml(), CIccTagXmlSparseMatrixArray::ParseXml(), CIccTagXmlMeasurement::ParseXml(), CIccTagXmlMultiLocalizedUnicode::ParseXml(), CIccTagXmlColorantTable::ParseXml(), CIccTagXmlViewingConditions::ParseXml(), CIccTagXmlSpectralViewingConditions::ParseXml(), CIccTagXmlParametricCurve::ParseXml(), CIccTagXmlMultiProcessElement::ParseXml(), CIccTagXmlProfileSequenceId::ParseXml(), CIccTagXmlDict::ParseXml(), and CIccTagXmlArray::ParseXml().
icXmlAttrValue() [2/2]
const char * icXmlAttrValue (xmlNode * pNode, const char * szName, const char * szDefault = "")
{
  xmlAttr *attr = icXmlFindAttr(pNode, szName);
  if (attr) {
    return icXmlAttrValue(attr, szDefault);
  }
  return szDefault;
}
References icXmlAttrValue(), and icXmlFindAttr().
Referenced by icCLutFromXml(), icXmlParseTextString(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccTagXmlCurve::ParseXml(), CIccFormulaCurveSegmentXml::ParseXml(), CIccSampledCurveSegmentXml::ParseXml(), CIccSinglSampledeCurveXml::ParseXml(), CIccMpeXmlUnknown::ParseXml(), CIccSegmentedCurveXml::ParseXml(), CIccMpeXmlCurveSet::ParseXml(), CIccMpeXmlTintArray::ParseXml(), CIccXmlToneMapFunc::ParseXml(), CIccMpeXmlToneMap::ParseXml(), CIccMpeXmlMatrix::ParseXml(), CIccMpeXmlCLUT::ParseXml(), CIccMpeXmlExtCLUT::ParseXml(), CIccMpeXmlBAcs::ParseXml(), CIccMpeXmlEAcs::ParseXml(), CIccMpeXmlJabToXYZ::ParseXml(), CIccMpeXmlXYZToJab::ParseXml(), CIccMpeXmlCalculator::ParseXml(), CIccMpeXmlEmissionMatrix::ParseXml(), CIccMpeXmlInvEmissionMatrix::ParseXml(), CIccMpeXmlEmissionCLUT::ParseXml(), CIccMpeXmlReflectanceCLUT::ParseXml(), CIccMpeXmlEmissionObserver::ParseXml(), CIccMpeXmlReflectanceObserver::ParseXml(), CIccTagXmlUnknown::ParseXml(), CIccTagXmlTextDescription::ParseXml(), CIccTagXmlNamedColor2::ParseXml(), CIccTagXmlFloatNum< T, A, Tsig >::ParseXml(), CIccTagXmlTagData::ParseXml(), CIccTagXmlColorantTable::ParseXml(), CIccTagXmlSpectralDataInfo::ParseXml(), CIccTagXmlResponseCurveSet16::ParseXml(), CIccTagXmlParametricCurve::ParseXml(), CIccTagXmlProfileSequenceId::ParseXml(), CIccTagXmlDict::ParseXml(), CIccTagXmlGamutBoundaryDesc::ParseXml(), CIccTagXmlEmbeddedHeightImage::ParseXml(), and CIccTagXmlEmbeddedNormalImage::ParseXml().
icXmlDumpHexData()
icUInt32Number icXmlDumpHexData (std::string & xml, std::string blanks, void * pBuf, icUInt32Number nBufSize)
{
  icUInt8Number *m_ptr = (icUInt8Number *)pBuf;
  char buf[15];
  icUInt32Number i;
  for (i=0; i<nBufSize; i++, m_ptr++) {
    if (!(i%32)) {
      if (i)
        xml += "\n";
      xml += blanks;
    }
    sprintf(buf, "%02x", *m_ptr);
    xml += buf;
  }
  if (i) {
    xml += "\n";
  }
  return i;
}
Referenced by icXmlDumpTextData(), CIccMpeXmlUnknown::ToXml(), CIccMpeXmlBAcs::ToXml(), CIccMpeXmlEAcs::ToXml(), CIccTagXmlUnknown::ToXml(), CIccTagXmlZipUtf8Text::ToXml(), CIccTagXmlZipXml::ToXml(), CIccTagXmlTagData::ToXml(), CIccTagXmlEmbeddedHeightImage::ToXml(), and CIccTagXmlEmbeddedNormalImage::ToXml().
icXmlFindAttr()
xmlAttr * icXmlFindAttr (xmlNode * pNode, const char * szAttrName)
{
  if (!pNode) return NULL;
  xmlAttr *attr;
  for (attr = pNode->properties; attr; attr = attr->next) {
    if (attr->type != XML_ATTRIBUTE_NODE)
      continue;
    if (!icXmlStrCmp(attr->name, szAttrName)) {
      return attr;
    }
  }
  return NULL;
}
Referenced by icCLutFromXml(), icGetDeviceAttrValue(), icMatrixFromXml(), icMBBFromXml(), icXmlAttrValue(), icXmlParseColorAppearanceParams(), CIccProfileXml::ParseBasic(), CIccTagXmlMultiProcessElement::ParseElement(), CIccMpeXmlCalculator::ParseImport(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccFormulaCurveSegmentXml::ParseXml(), CIccSampledCurveSegmentXml::ParseXml(), CIccSampledCalculatorCurveXml::ParseXml(), CIccSinglSampledeCurveXml::ParseXml(), CIccMpeXmlTintArray::ParseXml(), CIccXmlToneMapFunc::ParseXml(), CIccTagXmlNamedColor2::ParseXml(), CIccTagXmlXYZ::ParseXml(), CIccTagXmlChromaticity::ParseXml(), CIccTagXmlCicp::ParseXml(), CIccTagXmlSparseMatrixArray::ParseXml(), CIccTagXmlMeasurement::ParseXml(), CIccTagXmlMultiLocalizedUnicode::ParseXml(), CIccTagXmlColorantTable::ParseXml(), CIccTagXmlViewingConditions::ParseXml(), CIccTagXmlSpectralViewingConditions::ParseXml(), CIccTagXmlParametricCurve::ParseXml(), CIccTagXmlMultiProcessElement::ParseXml(), CIccTagXmlProfileSequenceId::ParseXml(), CIccTagXmlDict::ParseXml(), and CIccTagXmlArray::ParseXml().
icXmlFindNode()
xmlNode * icXmlFindNode (xmlNode * pNode, const char * szNodeName)
{
  if (!pNode) return NULL;
  for (; pNode; pNode = pNode->next) {
    if (pNode->type != XML_ELEMENT_NODE)
      continue;
    if (!icXmlStrCmp(pNode->name, szNodeName)) {
      return pNode;
    }
  }
  return NULL;
}
Referenced by icCLutFromXml(), icMBBFromXml(), icXmlParseColorAppearanceParams(), icXmlParseProfDesc(), CIccProfileXml::ParseBasic(), CIccMpeXmlCalculator::ParseImport(), CIccTagXmlCurve::ParseXml(), CIccSampledCalculatorCurveXml::ParseXml(), CIccMpeXmlToneMap::ParseXml(), CIccMpeXmlMatrix::ParseXml(), CIccMpeXmlJabToXYZ::ParseXml(), CIccMpeXmlXYZToJab::ParseXml(), CIccMpeXmlCalculator::ParseXml(), CIccMpeXmlEmissionMatrix::ParseXml(), CIccMpeXmlInvEmissionMatrix::ParseXml(), CIccMpeXmlEmissionCLUT::ParseXml(), CIccMpeXmlReflectanceCLUT::ParseXml(), CIccMpeXmlEmissionObserver::ParseXml(), CIccMpeXmlReflectanceObserver::ParseXml(), CIccProfileXml::ParseXml(), CIccTagXmlUnknown::ParseXml(), CIccTagXmlTextDescription::ParseXml(), CIccTagXmlSignature::ParseXml(), CIccTagXmlNamedColor2::ParseXml(), CIccTagXmlChromaticity::ParseXml(), CIccTagXmlCicp::ParseXml(), CIccTagXmlSparseMatrixArray::ParseXml(), CIccTagXmlFixedNum< T, Tsig >::ParseXml(), CIccTagXmlNum< T, A, Tsig >::ParseXml(), CIccTagXmlFloatNum< T, A, Tsig >::ParseXml(), CIccTagXmlMeasurement::ParseXml(), CIccTagXmlMultiLocalizedUnicode::ParseXml(), CIccTagXmlTagData::ParseXml(), CIccTagXmlDateTime::ParseXml(), CIccTagXmlColorantOrder::ParseXml(), CIccTagXmlColorantTable::ParseXml(), CIccTagXmlViewingConditions::ParseXml(), CIccTagXmlSpectralDataInfo::ParseXml(), CIccTagXmlSpectralViewingConditions::ParseXml(), CIccTagXmlProfileSeqDesc::ParseXml(), CIccTagXmlResponseCurveSet16::ParseXml(), CIccTagXmlParametricCurve::ParseXml(), CIccTagXmlSegmentedCurve::ParseXml(), CIccTagXmlMultiProcessElement::ParseXml(), CIccTagXmlProfileSequenceId::ParseXml(), CIccTagXmlDict::ParseXml(), CIccTagXmlStruct::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagXmlGamutBoundaryDesc::ParseXml(), CIccTagXmlEmbeddedHeightImage::ParseXml(), CIccTagXmlEmbeddedNormalImage::ParseXml(), and CIccTagXmlEmbeddedProfile::ParseXml().
icXmlGetChildSigVal()
icUInt32Number icXmlGetChildSigVal (xmlNode * pNode)
{
  if (!pNode || !pNode->children || !pNode->children->content)
    return 0;
  return icGetSigVal((const char*)pNode->children->content);
}
References icGetSigVal().
Referenced by CIccProfileXml::ParseBasic().
icXmlGetHexData()
icUInt32Number icXmlGetHexData (void * pBuf, const char * szText, icUInt32Number nBufSize)
{
  unsigned char *pDest = (unsigned char*)pBuf;
  icUInt32Number rv =0;
  while(*szText && rv<nBufSize) {
    int c1=hexValue(szText[0]);
    int c2=hexValue(szText[1]);
    if (c1>=0 && c2>=0) {
      *pDest = c1*16+ c2;
      pDest++;
      szText +=2;
      rv++;
    }
    else {
      szText++;
    }
  }
  return rv;
}
References hexValue().
Referenced by icXmlParseTextString(), CIccProfileXml::ParseBasic(), CIccMpeXmlUnknown::ParseXml(), CIccMpeXmlBAcs::ParseXml(), CIccMpeXmlEAcs::ParseXml(), CIccTagXmlUnknown::ParseXml(), CIccTagXmlZipUtf8Text::ParseXml(), CIccTagXmlZipXml::ParseXml(), CIccTagXmlTextDescription::ParseXml(), CIccTagXmlTagData::ParseXml(), CIccTagXmlProfileSequenceId::ParseXml(), CIccTagXmlEmbeddedHeightImage::ParseXml(), and CIccTagXmlEmbeddedNormalImage::ParseXml().
icXmlGetHexDataSize()
icUInt32Number icXmlGetHexDataSize (const char * szText)
{
  icUInt32Number rv =0;
  while(*szText) {
    int c1=hexValue(szText[0]);
    int c2=hexValue(szText[1]);
    if (c1>=0 && c2>=0) {
      szText +=2;
      rv++;
    }
    else {
      szText++;
    }
  }
  return rv;
}
References hexValue().
Referenced by icXmlParseTextString(), CIccMpeXmlUnknown::ParseXml(), CIccMpeXmlBAcs::ParseXml(), CIccMpeXmlEAcs::ParseXml(), CIccTagXmlUnknown::ParseXml(), CIccTagXmlZipUtf8Text::ParseXml(), CIccTagXmlZipXml::ParseXml(), CIccTagXmlTagData::ParseXml(), CIccTagXmlEmbeddedHeightImage::ParseXml(), and CIccTagXmlEmbeddedNormalImage::ParseXml().
icXmlNodeCount()
icUInt32Number icXmlNodeCount (xmlNode * pNode, const char * szNodeName)
{
  icUInt32Number rv = 0;
  for (; pNode; pNode = pNode->next) {
    if (pNode->type == XML_ELEMENT_NODE &&
        !icXmlStrCmp(pNode->name, szNodeName)) {
      rv++;
    }
  }
  return rv;
}
Referenced by CIccXmlArrayType< T, Tsig >::ParseArray(), CIccXmlArrayType< T, Tsig >::ParseArray(), CIccTagXmlXYZ::ParseXml(), CIccTagXmlChromaticity::ParseXml(), CIccTagXmlColorantOrder::ParseXml(), CIccTagXmlColorantTable::ParseXml(), and CIccTagXmlResponseCurveSet16::ParseXml().
icXmlNodeCount2()
icUInt32Number icXmlNodeCount2 (xmlNode * pNode, const char * szNodeName1, const char * szNodeName2)
{
  icUInt32Number rv = 0;
  for (; pNode; pNode = pNode->next) {
    if (pNode->type == XML_ELEMENT_NODE &&
      (!icXmlStrCmp(pNode->name, szNodeName1) || !icXmlStrCmp(pNode->name, szNodeName2))) {
      rv++;
    }
  }
  return rv;
}
icXmlNodeCount3()
icUInt32Number icXmlNodeCount3 (xmlNode * pNode, const char * szNodeName1, const char * szNodeName2, const char * szNodeName3)
{
  icUInt32Number rv = 0;
  for (; pNode; pNode = pNode->next) {
    if (pNode->type == XML_ELEMENT_NODE &&
      (!icXmlStrCmp(pNode->name, szNodeName1) || !icXmlStrCmp(pNode->name, szNodeName2) || !icXmlStrCmp(pNode->name, szNodeName3))) {
      rv++;
    }
  }
  return rv;
}
Referenced by CIccTagXmlNamedColor2::ParseXml().
icXmlStrToFloat()
icFloatNumber icXmlStrToFloat (const xmlChar * szStr)
{
  float f=0.0;
  sscanf((const char*)szStr, "%f", &f);
  return (icFloatNumber)f;
}
icXmlStrToSig()
icSignature icXmlStrToSig (const char * szStr)
{
  return icGetSigVal(szStr);
}
References icGetSigVal().
Referenced by icXmlParseProfDesc(), CIccMpeXmlUnknown::ParseXml(), CIccMpeXmlBAcs::ParseXml(), and CIccMpeXmlEAcs::ParseXml().