iccDEV: Tools/CmdLine/IccCommon/IccCmmConfig.cpp File Reference
IccCmmConfig.cpp File Reference
#include "IccCmmConfig.h"
#include <stdio.h>
#include <fstream>
#include <string.h>
Data Structures
class CIccIndexValue
class CIccIt8Parser
Typedefs
typedef std::pair< int, std::string > icIndexName
typedef std::vector< CIccIndexValue > icValueVector
Functions
const char * icGetJsonColorEncoding (icFloatColorEncoding v)
const char * icGetJsonFileEncoding (icFloatColorEncoding v)
static const icChar * icGetJsonFloatColorEncoding (icFloatColorEncoding val)
static bool icGetJsonRenderingIntent (const json &j, int &v)
icFloatColorEncoding icSetJsonColorEncoding (const char *szEncode)
icFloatColorEncoding icSetJsonFileEncoding (const char *szEncode)
static bool jsonFromEnvMap (json &j, const icCmmEnvSigMap &map)
void jsonSetValue (json &j, const char *szName, icCfgDataType v)
bool jsonToValue (const json &j, icCfgDataType &v)
bool jsonToValue (const json &j, icCmmEnvSigMap &v)
bool jsonToValue (const json &j, icDstBool &v)
bool jsonToValue (const json &j, icFloatColorEncoding &v)
static bool ParseName (icChar *pName, icChar *pString)
static bool ParseNextNumber (icFloatNumber &num, icChar **text)
static bool ParseNumbers (icFloatNumber *pData, icChar *pString, icUInt32Number nSamples)
static void setDstBool (json &j, const char *szName, icDstBool v)
static void setSampleIndex (std::vector< icValueVector > &samples, int index, const char *szFmt, const char **szChannels)
Variables
static const char * clrEncNames []
static icFloatColorEncoding clrEncValues []
static const char * fileEncNames [] = { "8Bit", "16Bit", "float", "sameAsSource", nullptr}
static icFloatColorEncoding fileEncValues [] = { icEncode8Bit, icEncode16Bit, icEncodeFloat, icEncodeUnknown, icEncode8Bit }
static const char * icInterpNames [] = { "linear", "tetrahedral", nullptr }
static icXformInterp icInterpValues [] = { icInterpLinear, icInterpTetrahedral, icInterpTetrahedral }
static const char * icTranNames []
static icXformLutType icTranValues []
Typedef Documentation
icIndexName
typedef std::pair<int, std::string> icIndexName
icValueVector
typedef std::vector<CIccIndexValue> icValueVector
Function Documentation
icGetJsonColorEncoding()
const char * icGetJsonColorEncoding (icFloatColorEncoding v)
{
  int i;
  for (i = 0; clrEncNames[i]; i++) {
    if (v==clrEncValues[i])
      break;
  }
  return clrEncNames[i] ? clrEncNames[i] : clrEncNames[0];
}
References clrEncNames, and clrEncValues.
Referenced by CIccCfgDataApply::toJson().
icGetJsonFileEncoding()
const char * icGetJsonFileEncoding (icFloatColorEncoding v)
{
  int i;
  for (i = 0; fileEncNames[i]; i++) {
    if (v == fileEncValues[i])
      break;
  }
  return fileEncNames[i] ? fileEncNames[i] : clrEncNames[0];
}
References clrEncNames, fileEncNames, and fileEncValues.
Referenced by CIccCfgImageApply::toJson().
icGetJsonFloatColorEncoding()
static const icChar * icGetJsonFloatColorEncoding (icFloatColorEncoding val) static
{
  switch (val) {
  case icEncodeValue:
    return "value";
  case icEncodeFloat:
    return "float";
  case icEncodeUnitFloat:
    return "unitFloat";
  case icEncodePercent:
    return "percent";
  case icEncode8Bit:
    return "8Bit";
  case icEncode16Bit:
    return "16Bit";
  case icEncode16BitV2:
    return "16BitV2";
  default:
    return "unknown";
  }
}
Referenced by CIccCfgColorData::toJson().
icGetJsonRenderingIntent()
static bool icGetJsonRenderingIntent (const json & j, int & v) static
{
  if (j.is_string()) {
    std::string str = j.get<std::string>();
    if (str == "perceptual")
      v = icPerceptual;
    else if (str == "relative")
      v = icRelative;
    else if (str == "saturation")
      v = icSaturation;
    else if (str == "absolute")
      v = icAbsolute;
    else
      v = icUnknownIntent;
  }
  else if (j.is_number_integer()) {
    v = j.get<int>();
  }
  else
    return false;
  return true;
}
References icAbsolute, icPerceptual, icRelative, and icSaturation.
Referenced by CIccCfgProfile::fromJson().
icSetJsonColorEncoding()
icFloatColorEncoding icSetJsonColorEncoding (const char * szEncode)
{
  int i;
  for (i = 0; clrEncNames[i]; i++) {
    if (!stricmp(szEncode, clrEncNames[i]))
      break;
  }
  return clrEncValues[i];
}
References clrEncNames, and clrEncValues.
Referenced by CIccCfgColorData::fromJson(), and jsonToValue().
icSetJsonFileEncoding()
icFloatColorEncoding icSetJsonFileEncoding (const char * szEncode)
{
  int i;
  for (i = 0; fileEncNames[i]; i++) {
    if (!stricmp(szEncode, fileEncNames[i]))
      break;
  }
  return fileEncValues[i];
}
References fileEncNames, and fileEncValues.
Referenced by CIccCfgImageApply::fromJson().
jsonFromEnvMap()
static bool jsonFromEnvMap (json & j, const icCmmEnvSigMap & map) static
{
  char buf[30];
  j.clear();
  for (auto e = map.begin(); e != map.end(); e++) {
    json var;
    var["name"] = icGetSigStr(buf, e->first);
    var["value"] = e->second;
    j.push_back(var);
  }
  return j.is_array() && j.size() > 0;
}
References icGetSigStr().
Referenced by CIccCfgProfile::toJson().
jsonSetValue()
void jsonSetValue (json & j, const char * szName, icCfgDataType v)
{
  if (v == icCfgColorData)
    j[szName] = "colorData";
  else if (v == icCfgLegacy)
    j[szName] = "legacy";
  else if (v == icCfgIt8)
    j[szName] = "it8";
}
References icCfgColorData, icCfgIt8, and icCfgLegacy.
Referenced by CIccCfgDataApply::toJson().
jsonToValue() [1/4]
bool jsonToValue (const json & j, icCfgDataType & v)
{
  std::string str;
  if (jsonToValue(j, str)) {
    if (str == "colorData")
      v = icCfgColorData;
    else if (str == "legacy")
      v = icCfgLegacy;
    else if (str == "it8")
      v = icCfgIt8;
    else
      return false;
  }
  else
    return false;
  return true;
}
References icCfgColorData, icCfgIt8, icCfgLegacy, and jsonToValue().
Referenced by CIccCfgDataApply::fromJson().
jsonToValue() [2/4]
bool jsonToValue (const json & j, icCmmEnvSigMap & v)
{
  if (!j.is_array())
    return false;
  for (auto e = j.begin(); e != j.end(); e++) {
    if (e->is_object()) {
      std::string name;
      icFloatNumber value;
      if (jsonToValue((*e)["name"], name) && jsonToValue((*e)["value"], value)) {
        icColorSpaceSignature sig = (icColorSpaceSignature)icGetSigVal(name.c_str());
        v[sig]=value;
      }
    }
  }
  return true;
}
References icGetSigVal(), and jsonToValue().
Referenced by CIccCfgProfile::fromJson().
jsonToValue() [3/4]
bool jsonToValue (const json & j, icDstBool & v)
{
  if (j.is_boolean())
    v = j.get<bool>() ? icDstBoolTrue : icDstBoolFalse;
  else if (j.is_string()) {
    std::string str = j.get<std::string>();
    if (str == "true")
      v = icDstBoolTrue;
    else if (str == "false")
      v = icDstBoolFalse;
    else if (str == "sameAsSource")
      v = icDstBoolFromSrc;
    else
      return false;
  }
  else
    return false;
  return true;
}
References icDstBoolFalse, icDstBoolFromSrc, and icDstBoolTrue.
Referenced by CIccCfgImageApply::fromJson().
jsonToValue() [4/4]
bool jsonToValue (const json & j, icFloatColorEncoding & v)
{
  std::string str;
  if (jsonToValue(j, str)) {
    v = icSetJsonColorEncoding(str.c_str());
    return true;
  }
  return false;
}
References icSetJsonColorEncoding(), and jsonToValue().
Referenced by CIccCfgDataApply::fromJson().
ParseName()
static bool ParseName (icChar * pName, icChar * pString) static
{
  if (strncmp(pString, "{ \"", 3))
    return false;
  icChar* ptr = strstr(pString, "\" }");
  if (!ptr)
    return false;
  icUInt32Number nNameLen = (icUInt32Number)(ptr - (pString + 3));
  if (!nNameLen)
    return false;
  strncpy(pName, pString + 3, nNameLen);
  pName[nNameLen] = '\0';
  return true;
}
Referenced by CIccCfgColorData::fromLegacy().
ParseNextNumber()
static bool ParseNextNumber (icFloatNumber & num, icChar ** text) static
{
  if (!text)
    return false;
  icChar* ptr = *text;
  while (*ptr == ' ') ptr++;
  if ((*ptr >= '0' && *ptr <= '9') || *ptr == '.') {
    num = (icFloatNumber)atof(ptr);
    while (*ptr && *ptr != ' ') ptr++;
    *text = ptr;
    return true;
  }
  return false;
}
Referenced by CIccCfgColorData::fromLegacy().
ParseNumbers()
static bool ParseNumbers (icFloatNumber * pData, icChar * pString, icUInt32Number nSamples) static
{
  icUInt32Number nNumbersRead = 0;
  icChar* ptr = pString;
  while (*ptr && nNumbersRead < nSamples) {
    while (*ptr == ' ' || *ptr == '\t' || *ptr == '\n' || *ptr == '\r')
      ptr++;
    if (sscanf(ptr, ICFLOATFMT, &pData[nNumbersRead]) == 1)
      nNumbersRead++;
    else
      break;
    while (*ptr && *ptr != ' ' && *ptr != '\t' && *ptr != 'n' && *ptr != '\r')
      ptr++;
  }
  if (nNumbersRead != nSamples) {
    return false;
  }
  return true;
}
Referenced by CIccCfgColorData::fromLegacy().
setDstBool()
static void setDstBool (json & j, const char * szName, icDstBool v) static
{
  if (v == icDstBoolTrue)
    j[szName] = true;
  else if (v == icDstBoolFalse)
    j[szName] = false;
  else if (v == icDstBoolFromSrc) // Compare, don't assign
    j[szName] = "sameAsSource";
  else
    j[szName] = nullptr; //  handle unexpected values
}
References icDstBoolFalse, icDstBoolFromSrc, and icDstBoolTrue.
Referenced by CIccCfgImageApply::toJson().
setSampleIndex()
static void setSampleIndex (std::vector< icValueVector > & samples, int index, const char * szFmt, const char ** szChannels) static
{
  size_t nPos = samples.size() - 1;
  for (int i = 0; i < samples[nPos].size(); i++) {
    if (!strcmp(szFmt, szChannels[i])) {
      samples[nPos][i].nIndex = index;
    }
  }
}
References CIccIndexValue::nIndex.
Referenced by CIccCfgColorData::fromIt8().
Variable Documentation
clrEncNames
const char* clrEncNames[] static
Initial value:
= { "value", "float", "unitFloat", "percent",
                                     "8Bit", "16Bit", "16BitV2", nullptr }
                                   { "value", "float", "unitFloat", "percent",
                                     "8Bit", "16Bit", "16BitV2", nullptr };
Referenced by icGetJsonColorEncoding(), icGetJsonFileEncoding(), and icSetJsonColorEncoding().
clrEncValues
icFloatColorEncoding clrEncValues[] static
Initial value:
= { icEncodeValue, icEncodeFloat, icEncodeUnitFloat, icEncodePercent,
                                               icEncode8Bit, icEncode16Bit, icEncode16BitV2, icEncodeUnknown }
                                             { icEncodeValue, icEncodeFloat, icEncodeUnitFloat, icEncodePercent,
                                               icEncode8Bit, icEncode16Bit, icEncode16BitV2, icEncodeUnknown };
Referenced by icGetJsonColorEncoding(), and icSetJsonColorEncoding().
fileEncNames
const char* fileEncNames[] = { "8Bit", "16Bit", "float", "sameAsSource", nullptr} static
{ "8Bit", "16Bit", "float", "sameAsSource", nullptr};
Referenced by icGetJsonFileEncoding(), and icSetJsonFileEncoding().
fileEncValues
icFloatColorEncoding fileEncValues[] = { icEncode8Bit, icEncode16Bit, icEncodeFloat, icEncodeUnknown, icEncode8Bit } static
{ icEncode8Bit, icEncode16Bit, icEncodeFloat, icEncodeUnknown, icEncode8Bit };
Referenced by icGetJsonFileEncoding(), and icSetJsonFileEncoding().
icInterpNames
const char* icInterpNames[] = { "linear", "tetrahedral", nullptr } static
{ "linear", "tetrahedral", nullptr };
Referenced by CIccCfgProfile::fromJson(), and CIccCfgProfile::toJson().
icInterpValues
icXformInterp icInterpValues[] = { icInterpLinear, icInterpTetrahedral, icInterpTetrahedral } static
{ icInterpLinear, icInterpTetrahedral, icInterpTetrahedral };
Referenced by CIccCfgProfile::fromJson(), and CIccCfgProfile::toJson().
icTranNames
const char* icTranNames[] static
Initial value:
= { "default", "named", "colorimetric", "spectral",
                                     "MCS", "preview", "gamut", "brdfParam",
                                     "brdfDirect", "brdfMcsParam" , nullptr }
                                   { "default", "named", "colorimetric", "spectral",
                                     "MCS", "preview", "gamut", "brdfParam",
                                     "brdfDirect", "brdfMcsParam" , nullptr };
Referenced by CIccCfgProfile::fromJson().
icTranValues
icXformLutType icTranValues[] static
Initial value:
= { icXformLutColor, icXformLutNamedColor, icXformLutColorimetric, icXformLutSpectral,
                                         icXformLutMCS, icXformLutPreview, icXformLutGamut, icXformLutBRDFParam,
                                         icXformLutBRDFDirect, icXformLutBRDFMcsParam, icXformLutColor }
                                       { icXformLutColor, icXformLutNamedColor, icXformLutColorimetric, icXformLutSpectral,
                                         icXformLutMCS, icXformLutPreview, icXformLutGamut, icXformLutBRDFParam,
                                         icXformLutBRDFDirect, icXformLutBRDFMcsParam, icXformLutColor };
Referenced by CIccCfgProfile::fromJson().