iccDEV: CIccArrayCreator Class Reference
CIccArrayCreator Class Reference
#include <IccArrayFactory.h>
Public Member Functions
~CIccArrayCreator ()
Static Public Member Functions
static IIccArray * CreateArray (icArraySignature arrayTypeSig, CIccTagArray *pTagArray=NULL)
static icArraySignature GetArraySig (const icChar *arrayName)
static bool GetArraySigName (std::string &arrayName, icArraySignature arrayTypeSig, bool bFillUnknown=true)
static IIccArrayFactory * PopFactory ()
static void PushFactory (IIccArrayFactory *pFactory)
Private Member Functions
CIccArrayCreator ()
IIccArray * DoCreateArray (icArraySignature arrayTypeSig, CIccTagArray *pArray)
icArraySignature DoGetArraySig (const icChar *arrayName)
bool DoGetArraySigName (std::string &arrayName, icArraySignature arrayTypeSig, bool bFillUnknown=true)
IIccArrayFactory * DoPopFactory (bool bAll=false)
void DoPushFactory (IIccArrayFactory *pFactory)
Static Private Member Functions
static CIccArrayCreator * GetInstance ()
Private Attributes
CIccArrayFactoryList factoryStack
Static Private Attributes
static CIccArrayCreatorPtr theArrayCreator
Detailed Description
Class: CIccArrayCreator
Purpose: CIccArrayCreator uses a singleton pattern to provide dynamically upgradeable IIccArrayObject derived object creation based on element signature.
Constructor & Destructor Documentation
~CIccArrayCreator()
CIccArrayCreator::~CIccArrayCreator ()
{
  IIccArrayFactory *pFactory = DoPopFactory(true);
  while (pFactory) {
    delete pFactory;
    pFactory = DoPopFactory(true);
  }
}
References DoPopFactory().
CIccArrayCreator()
CIccArrayCreator::CIccArrayCreator () inline private
Only GetInstance() can create the singleton
{ }
Member Function Documentation
CreateArray()
static IIccArray * CIccArrayCreator::CreateArray (icArraySignature arrayTypeSig, CIccTagArray * pTagArray = NULL) inline static
Function: CreateArray(structTypeSig) Create a element of type structTypeSig.
Parameter(s): structTypeSig = signature of the ICC element type for the element to be created
Returns a new CIccProcessArray object of the given signature type. Each factory in the factoryStack is used until a factory supports the signature type.
      { return CIccArrayCreator::GetInstance()->DoCreateArray(arrayTypeSig, pTagArray); }
References DoCreateArray(), and GetInstance().
Referenced by CIccTagArray::GetArrayHandler(), and CIccTagArray::SetTagArrayType().
DoCreateArray()
IIccArray * CIccArrayCreator::DoCreateArray (icArraySignature arrayTypeSig, CIccTagArray * pArray) private
{
  CIccArrayFactoryList::iterator i;
  IIccArray *rv = NULL;
  for (i=factoryStack.begin(); i!=factoryStack.end(); i++) {
    rv = (*i)->CreateArray(arrayTypeSig, pTagArray);
    if (rv)
      break;
  }
  return rv;
}
References IIccArrayFactory::CreateArray(), and factoryStack.
Referenced by CreateArray().
DoGetArraySig()
icArraySignature CIccArrayCreator::DoGetArraySig (const icChar * arrayName) private
{
  CIccArrayFactoryList::iterator i;
  for (i = factoryStack.begin(); i != factoryStack.end(); i++) {
    icArraySignature rv = (*i)->GetArraySig(structName);
    if (rv)
      return rv;
  }
  return (icArraySignature)0;
}
References factoryStack, and IIccArrayFactory::GetArraySig().
Referenced by GetArraySig().
DoGetArraySigName()
bool CIccArrayCreator::DoGetArraySigName (std::string & arrayName, icArraySignature arrayTypeSig, bool bFillUnknown = true) private
{
  CIccArrayFactoryList::iterator i;
  for (i=factoryStack.begin(); i!=factoryStack.end(); i++) {
    if ((*i)->GetArraySigName(arrayName, arrayTypeSig, bFillUnknown))
      return true;
  }
  return false;
}
References factoryStack, and IIccArrayFactory::GetArraySigName().
Referenced by GetArraySigName().
DoPopFactory()
IIccArrayFactory * CIccArrayCreator::DoPopFactory (bool bAll = false) private
{
  if (factoryStack.size()>0) {
    CIccArrayFactoryList::iterator i=factoryStack.begin();
    IIccArrayFactory* rv = (*i);
    factoryStack.pop_front();
    return rv;
  }
  return NULL;
}
References factoryStack.
Referenced by ~CIccArrayCreator(), and PopFactory().
DoPushFactory()
void CIccArrayCreator::DoPushFactory (IIccArrayFactory * pFactory) private
{
  factoryStack.push_front(pFactory);
}
References factoryStack.
Referenced by GetInstance(), and PushFactory().
GetArraySig()
static icArraySignature CIccArrayCreator::GetArraySig (const icChar * arrayName) inline static
Function: GetArraySig(arrayName) Get signature associate with display name arrayName handler
Parameter(s): arrayName = string to find signature for
Returns array signuture if arrayName arrays are recognized by any factory, 0 if all factories do not create arrayName arrays.
    { return CIccArrayCreator::GetInstance()->DoGetArraySig(arrayName); }
References DoGetArraySig(), and GetInstance().
Referenced by CIccTagXmlArray::ParseXml().
GetArraySigName()
static bool CIccArrayCreator::GetArraySigName (std::string & arrayName, icArraySignature arrayTypeSig, bool bFillUnknown = true) inline static
Function: GetArraySigName(structTypeSig) Get display name of structTypeSig.
Parameter(s): arrayName = string to put struct name into arrayTypeSig = signature of the ICC struct type to get a name for bFillUnknown = flag to fill in arrayName if arryTypeSig is unknown
Returns true if struct type is recognized by any factory, false if all factories do not create arrayTypeSig arrays. If arrayTypeSig is not recognized by any factories a suitable display name will be placed in arrayName if bFindUnkown is true (otherwise arrayName will be empty).
      { return CIccArrayCreator::GetInstance()->DoGetArraySigName(arrayName, arrayTypeSig, bFillUnknown); }
References DoGetArraySigName(), and GetInstance().
Referenced by CIccTagArray::Describe(), CIccInfo::GetArraySigName(), and CIccTagXmlArray::ToXml().
GetInstance()
CIccArrayCreator * CIccArrayCreator::GetInstance () static private
Function: GetInstance() Private static function to access singleton CiccArrayCreator Object.
Parameter(s): None
Returns the singleton CIccArrayCreator object. It will allocate a new one and push a single CIccSpecArray Factory object onto the factory stack if the singleton has not been initialized.
{
  if (!theArrayCreator.get()) {
    theArrayCreator = CIccArrayCreatorPtr(new CIccArrayCreator);
    theArrayCreator->DoPushFactory(new CIccBasicArrayFactory);
  }
  return theArrayCreator.get();
}
References DoPushFactory(), and theArrayCreator.
Referenced by CreateArray(), GetArraySig(), GetArraySigName(), PopFactory(), and PushFactory().
PopFactory()
static IIccArrayFactory * CIccArrayCreator::PopFactory () inline static
Function: PopFactory() Remove the top IIccArrayFactory from the stack of element factories tracked by the system.
Parameter(s): None
Returns the top IIccArrayFactory from the stack of element factories tracked by the system. The returned element factory is no longer owned by the system and needs to be deleted to avoid memory leaks.
Note: The initial CIccBasicElemFactory cannot be popped off the stack.
      { return CIccArrayCreator::GetInstance()->DoPopFactory(); }
References DoPopFactory(), and GetInstance().
PushFactory()
static void CIccArrayCreator::PushFactory (IIccArrayFactory * pFactory) inline static
Function: PushFactory(pFactory) Add an IIccArrayFactory to the stack of element factories tracked by the system.
Parameter(s): pFactory = pointer to an IIccArrayFactory object to add to the system. The pFactory must be created with new, and will be owned CIccArrayCreator until popped off the stack using PopFactory(). Any factories not popped off will be taken care of properly on application shutdown.
      { CIccArrayCreator::GetInstance()->CIccArrayCreator::DoPushFactory(pFactory); }
References DoPushFactory(), and GetInstance().
Field Documentation
factoryStack
CIccArrayFactoryList CIccArrayCreator::factoryStack private
Referenced by DoCreateArray(), DoGetArraySig(), DoGetArraySigName(), DoPopFactory(), and DoPushFactory().
theArrayCreator
std::unique_ptr< CIccArrayCreator > CIccArrayCreator::theArrayCreator static private
Referenced by GetInstance().
The documentation for this class was generated from the following files:
IccProfLib/IccArrayFactory.h
IccProfLib/IccArrayFactory.cpp