iccDEV: CIccTagXmlTextDescription Class Reference
CIccTagXmlTextDescription Class Reference
#include <IccTagXml.h>
Public Member Functions
CIccTagXmlTextDescription ()
CIccTagXmlTextDescription (const CIccTagXmlTextDescription &ITTD)
virtual ~CIccTagXmlTextDescription ()
icUInt32Number Capacity () const
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
icChar * GetBuffer (icUInt32Number nSize)
virtual const char * GetClassName () const
virtual const char * GetExtClassName () const
virtual const char * GetExtDerivedClassName () const
virtual IIccExtensionTag * GetExtension ()
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
const icChar * GetText () const
virtual icTagTypeSignature GetType () const
icUInt16Number * GetUnicodeBuffer (icUInt32Number nSize)
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
virtual bool ParseXml (xmlNode *pNode, std::string &parseStr)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
void Release ()
void ReleaseUnicode ()
void SetText (const icChar *szText)
virtual bool ToXml (std::string &xml, std::string blanks="")
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
Protected Attributes
bool m_bInvalidScript
icUInt32Number m_nASCIISize
icUInt16Number m_nScriptCode
icUInt8Number m_nScriptSize
icUInt32Number m_nUnicodeLanguageCode
icUInt32Number m_nUnicodeSize
icUInt8Number m_szScriptText [67]
icChar * m_szText
icUInt16Number * m_uzUnicodeText
Detailed Description
Constructor & Destructor Documentation
CIccTagXmlTextDescription() [1/2]
CIccTagXmlTextDescription::CIccTagXmlTextDescription () inline
: CIccTagTextDescription() {}
References CIccTagTextDescription::CIccTagTextDescription().
CIccTagXmlTextDescription() [2/2]
CIccTagXmlTextDescription::CIccTagXmlTextDescription (const CIccTagXmlTextDescription & ITTD) inline
: CIccTagTextDescription(ITTD) {}
References CIccTagTextDescription::CIccTagTextDescription().
Referenced by NewCopy().
~CIccTagXmlTextDescription()
virtual CIccTagXmlTextDescription::~CIccTagXmlTextDescription () inline virtual
{}
Member Function Documentation
Capacity()
icUInt32Number CIccTagTextDescription::Capacity () const inline inherited
{ return m_nASCIISize; }
References CIccTagTextDescription::m_nASCIISize.
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagTextDescription::Describe (std::string & sDescription, int nVerboseness) virtual inherited
Name: CIccTagTextDescription::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  sDescription += "TextDescription Length = ";
  if (m_szText && *m_szText) {
    char buf[40];
    sprintf(buf, "%zu bytes\n", strlen(m_szText));
    sDescription += buf;
  }
  else
    sDescription += "0 (NULL)";
  if (nVerboseness > 25) {
    sDescription += "\"";
    if (m_szText && *m_szText) {
      if ((nVerboseness > 50) || (strlen(m_szText) < BRIEF_STRING_SIZE)) {
        // output entire string if short or doing verbose
         sDescription += m_szText;
      }
      else {
        // copy just first part of string to keep nVerboseness under control
        char buf[BRIEF_STRING_SIZE+1];
        strncpy(buf, m_szText, BRIEF_STRING_SIZE);
        buf[BRIEF_STRING_SIZE] = '\0'; // ensure NULL termination
        sDescription += buf;
        sDescription += "\n... <!truncated!>";
      }
    }
    sDescription += "\"\n";
  }
}
References CIccTagTextDescription::m_szText.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
GetBuffer()
icChar * CIccTagTextDescription::GetBuffer (icUInt32Number nSize) inherited
Name: CIccTagTextDescription::GetBuffer
Purpose: This function allocates room and returns pointer to data buffer to put string into
Args: nSize = Requested size of data buffer.
Return:
{
  if (m_nASCIISize < nSize) {
    m_szText = (icChar*)icRealloc(m_szText, nSize+1);
    m_szText[nSize] = '\0';
    m_nASCIISize = nSize;
  }
  return m_szText;
}
References icRealloc(), CIccTagTextDescription::m_nASCIISize, and CIccTagTextDescription::m_szText.
Referenced by ParseXml(), CIccTagTextDescription::Read(), and CIccTagTextDescription::SetText().
GetClassName()
virtual const char * CIccTagXmlTextDescription::GetClassName () const inline virtual
Reimplemented from CIccTagTextDescription.
{return "CIccTagXmlTextDescription"; }
GetExtClassName()
virtual const char * CIccTagXml::GetExtClassName () const inline virtual inherited
Implements IIccExtensionTag.
{ return "CIccTagXml"; }
Referenced by icProfDescToXml(), and icXmlParseProfDesc().
GetExtDerivedClassName()
virtual const char * CIccTagXml::GetExtDerivedClassName () const inline virtual inherited
Implements IIccExtensionTag.
Reimplemented in CIccCurveXml.
{ return ""; }
GetExtension()
virtual IIccExtensionTag * CIccTagXmlTextDescription::GetExtension () inline virtual
Reimplemented from CIccTag.
{return this; }
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetText()
const icChar * CIccTagTextDescription::GetText () const inline inherited
{ return m_szText; }
References CIccTagTextDescription::m_szText.
Referenced by CIccProfileIdDesc::CIccProfileIdDesc(), icGetTagText(), and main().
GetType()
virtual icTagTypeSignature CIccTagTextDescription::GetType () const inline virtual inherited
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigTextDescriptionType; }
References icSigTextDescriptionType.
Referenced by CIccTagTextDescription::Write().
GetUnicodeBuffer()
icUInt16Number * CIccTagTextDescription::GetUnicodeBuffer (icUInt32Number nSize) inherited
Name: CIccTagTextDescription::GetUnicodeBuffer
Purpose: This function allocates room and returns pointer to data buffer to put string into
Args: nSize = Requested size of data buffer.
Return:
{
  if (m_nUnicodeSize < nSize) {
    m_uzUnicodeText = (icUInt16Number*)icRealloc(m_uzUnicodeText, (nSize+1)*sizeof(icUInt16Number));
    m_uzUnicodeText[nSize] = 0;
    m_nUnicodeSize = nSize;
  }
  return m_uzUnicodeText;
}
References icRealloc(), CIccTagTextDescription::m_nUnicodeSize, and CIccTagTextDescription::m_uzUnicodeText.
Referenced by ParseXml(), and CIccTagTextDescription::Read().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
virtual CIccTag * CIccTagXmlTextDescription::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTagTextDescription.
{return new CIccTagXmlTextDescription(*this);}
References CIccTagXmlTextDescription().
ParseXml()
bool CIccTagXmlTextDescription::ParseXml (xmlNode * pNode, std::string & parseStr) virtual
Implements CIccTagXml.
{
  pNode = icXmlFindNode(pNode, "TextData");
  // support for reading desc, dmmd, and dmnd tags from file.
  // if (!pNode || !pNode->children)
  if (!pNode)
    return false;
  // search for "file" attribute in <TextDescription/> tag
  const icChar *filename = icXmlAttrValue(pNode, "File");
  // file exists
  if (filename[0]) {
    CIccIO *file = IccOpenFileIO(filename, "rb");
    if (!file){
      parseStr += "Error! - File '";
      parseStr += filename;
      parseStr +="' not found.\n";
      delete file;
      return false;
    }
    icUInt32Number fileLength = file->GetLength();
    char *buf = (char *)malloc(fileLength);
    if (!buf) {
      perror("Memory Error");
      parseStr += "'";
      parseStr += filename;
      parseStr += "' may not be a valid text file.\n";
      delete file;
      return false;
    }
    if (file->ReadLine(buf, fileLength)!=fileLength) {
      parseStr += "Error while reading file '";
      parseStr += filename;
      parseStr += "'. Size read is not equal to file length. File may not be a valid text file.\n";
      free(buf);
      delete file;
      return false;
    }
    // set ANSII string
    std::string ansiStr;
    icUtf8ToAnsi(ansiStr, buf);
    icUInt32Number nStrSize = (icUInt32Number)ansiStr.size();
    GetBuffer(nStrSize);
    if (nStrSize) {
      memcpy(m_szText, ansiStr.c_str(), nStrSize);
      m_nASCIISize = nStrSize + 1;
    }
    else
      m_szText[0] = '\0';
    // set Unicode String
    CIccUTF16String wstr(buf);
    nStrSize = (icUInt32Number)wstr.Size();
    m_uzUnicodeText = GetUnicodeBuffer(nStrSize);
    if (nStrSize) {
      // assign each entry in wstr to m_uzUnicodeText
      for (int i=0; i < (int) nStrSize; i++) {
        m_uzUnicodeText[i] = wstr[i];
      }
      // include the null termintor in the string size.
      m_nUnicodeSize = nStrSize + 1;
    }
    else
      m_uzUnicodeText[0] = 0;
    // Set ScriptCode
    m_nScriptCode=0;
    m_nScriptSize = (icUInt8Number) fileLength + 1;
    memcpy(m_szScriptText, buf, 67);
    delete file;
  }
  // file does not exist
  else {
    std::string str = icXmlParseTextString(pNode, parseStr);
    icUInt32Number nSize = (icUInt32Number)str.size();
    icChar *pBuf = GetBuffer(nSize);
    if (nSize) {
      memcpy(m_szText, str.c_str(), nSize);
      // include the null termintor in the string size.
      m_nASCIISize = nSize + 1;
    }
    else
      m_szText[0] = '\0';
    Release();
    // support for automatically generating unicode and scriptcode tags if these do not
    // exist in the XML file.
    bool unicodeExists = false;
    bool scriptcodeExists = false;
    for (;pNode; pNode = pNode->next) {
      if (pNode->type==XML_ELEMENT_NODE) {
        if (!icXmlStrCmp(pNode->name, "Unicode")) {
          const icChar *pRegion = icXmlAttrValue(pNode, "LanguageCode");
          // *pRegion may not have value.
          if (pRegion && /* *pRegion && */pNode->children && pNode->children->content) {
            CIccUTF16String wstr((const char*)pNode->children->content);
            nSize = (icUInt32Number)wstr.Size();
            // set size of m_uzUnicodeText
            m_uzUnicodeText = GetUnicodeBuffer(nSize);
            if (nSize) {
              // assign each entry in wstr to m_uzUnicodeText
              for (int i=0; i < (int) nSize; i++) {
                m_uzUnicodeText[i] = wstr[i];
              }
              // include the null termintor in the string size.
              m_nUnicodeSize = nSize + 1;
              unicodeExists = true;
            }
            else
              m_uzUnicodeText[0] = 0;
          }
        }
        else if (!icXmlStrCmp(pNode->name, "MacScript")) {
          const icChar *pScript = icXmlAttrValue(pNode, "ScriptCode");
          if (pScript && *pScript) {
            icUInt32Number nCode=0;
            sscanf(pScript, "%x", &nCode);
            m_nScriptCode = (icUInt16Number)nCode;
            if (pNode->children && pNode->children->content) {
              // set m_nScriptSize as receiver the return value of icXmlGetHexData
              // no need to add 1 since the return value is already exact.
              m_nScriptSize = (icUInt8Number) icXmlGetHexData(m_szScriptText, (const char*)pNode->children->content, sizeof(m_szScriptText));
              scriptcodeExists = true;
            }
            else
              m_szScriptText[0] = 0;
          }
        }
      }
    }
#if 0
    // automatically generate unicode tag in the profile if it does not exist
    if (!unicodeExists){
      m_uzUnicodeText = GetUnicodeBuffer(nSize);
      if (nSize) {
        // assign each entry in wstr to m_uzUnicodeText
        for (int i=0; i < (int) nSize; i++) {
          m_uzUnicodeText[i] = str[i];
        }
        // include the null termintor in the string size.
        m_nUnicodeSize = nSize + 1;
      }
      else
        m_uzUnicodeText[0] = 0;
    }
    // automatically generate scriptcode tag in the profile if it does not exist
    if (!scriptcodeExists){
      m_nScriptCode=0;
      m_nScriptSize = (icUInt8Number)m_nASCIISize;
      memcpy(m_szScriptText, m_szText, 67);
    }
#endif
  }
  return true;
}
References CIccUTF16String::CIccUTF16String(), CIccTagTextDescription::GetBuffer(), CIccIO::GetLength(), CIccTagTextDescription::GetUnicodeBuffer(), IccOpenFileIO(), icUtf8ToAnsi(), icXmlAttrValue(), icXmlFindNode(), icXmlGetHexData(), icXmlParseTextString(), CIccTagTextDescription::m_nASCIISize, CIccTagTextDescription::m_nScriptCode, CIccTagTextDescription::m_nScriptSize, CIccTagTextDescription::m_nUnicodeSize, CIccTagTextDescription::m_szScriptText, CIccTagTextDescription::m_szText, CIccTagTextDescription::m_uzUnicodeText, CIccUTF16String::operator[](), CIccIO::ReadLine(), CIccTagTextDescription::Release(), and CIccUTF16String::Size().
Read() [1/2]
bool CIccTagTextDescription::Read (icUInt32Number size, CIccIO * pIO) virtual inherited
Name: CIccTagTextDescription::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  icUInt32Number nEnd;
  m_szText[0] = '\0';
  nEnd = pIO->Tell() + size;
  if (size<3*sizeof(icUInt32Number) || !pIO)
    return false;
  icUInt32Number nSize;
  if (!pIO->Read32(&sig) ||
      !pIO->Read32(&m_nReserved) ||
      !pIO->Read32(&nSize))
    return false;
  if (3*sizeof(icUInt32Number) + nSize > size)
    return false;
  icChar *pBuf = GetBuffer(nSize);
  if (nSize) {
    if (pIO->Read8(pBuf, nSize) != (icInt32Number)nSize) {
      return false;
    }
  }
  else
    m_szText[0] = '\0';
  Release();
  if (pIO->Tell() + 2 * sizeof(icUInt32Number) > nEnd)
    return false;
  if (!pIO->Read32(&m_nUnicodeLanguageCode) ||
      !pIO->Read32(&nSize))
    return false;
  // Calculations in GetUnicodeBuffer() can cause wrap-around error
  if (nSize == 0xFFFFFFFF)
    return false;
  icUInt16Number *pBuf16 = GetUnicodeBuffer(nSize);
  if (nSize) {
    if (pIO->Read16(pBuf16, nSize) != (icInt32Number)nSize) {
      return false;
    }
  }
  else
    pBuf16[0] = 0;
  ReleaseUnicode();
  if (pIO->Tell()+3 > (icInt32Number)nEnd)
    return false;
  if (!pIO->Read16(&m_nScriptCode) ||
      !pIO->Read8(&m_nScriptSize))
     return false;
  if (pIO->Tell() + m_nScriptSize> (icInt32Number)nEnd ||
      m_nScriptSize > sizeof(m_szScriptText))
    return false;
  int nScriptLen = pIO->Read8(m_szScriptText, 67);
  if (!nScriptLen)
    return false;
  if (nScriptLen<67) {
    memset(&m_szScriptText[0], 0, 67-nScriptLen);
    m_bInvalidScript = true;
  }
  return true;
}
References CIccTagTextDescription::GetBuffer(), CIccTagTextDescription::GetUnicodeBuffer(), CIccTagTextDescription::m_bInvalidScript, CIccTag::m_nReserved, CIccTagTextDescription::m_nScriptCode, CIccTagTextDescription::m_nScriptSize, CIccTagTextDescription::m_nUnicodeLanguageCode, CIccTagTextDescription::m_szScriptText, CIccTagTextDescription::m_szText, CIccIO::Read16(), CIccIO::Read32(), CIccIO::Read8(), CIccTagTextDescription::Release(), CIccTagTextDescription::ReleaseUnicode(), and CIccIO::Tell().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
Release()
void CIccTagTextDescription::Release () inherited
Name: CIccTagTextDescription::Release
Purpose: This will resize the buffer to fit the zero terminated string in the buffer.
{
  icUInt32Number nSize = (icUInt32Number)strlen(m_szText);
  if (nSize < m_nASCIISize-1) {
    m_szText=(icChar*)icRealloc(m_szText, nSize+1);
    m_nASCIISize = nSize+1;
  }
}
References icRealloc(), CIccTagTextDescription::m_nASCIISize, and CIccTagTextDescription::m_szText.
Referenced by ParseXml(), CIccTagTextDescription::Read(), and CIccTagTextDescription::SetText().
ReleaseUnicode()
void CIccTagTextDescription::ReleaseUnicode () inherited
Name: CIccTagTextDescription::ReleaseUnicode
Purpose: This will resize the buffer to fit the zero terminated string in the buffer.
{
  int i;
  for (i=0; m_uzUnicodeText[i]; i++);
  icUInt32Number nSize = i+1;
  if (nSize < m_nUnicodeSize-1) {
    m_uzUnicodeText=(icUInt16Number*)icRealloc(m_uzUnicodeText, (nSize+1)*sizeof(icUInt16Number));
    m_nUnicodeSize = nSize+1;
  }
}
References icRealloc(), CIccTagTextDescription::m_nUnicodeSize, and CIccTagTextDescription::m_uzUnicodeText.
Referenced by CIccTagTextDescription::Read().
SetText()
void CIccTagTextDescription::SetText (const icChar * szText) inherited
Name: CIccTagTextDescription::SetText
Purpose: Allows text data associated with the tag to be set.
Args: szText - zero terminated string to put in tag
{
  m_bInvalidScript = false;
  if (!szText) {
    SetText("");
    return;
  }
  icUInt32Number len=(icUInt32Number)strlen(szText) + 1;
  icChar *szBuf = GetBuffer(len);
  strcpy(szBuf, szText);
  Release();
}
References CIccTagTextDescription::GetBuffer(), CIccTagTextDescription::m_bInvalidScript, CIccTagTextDescription::Release(), and CIccTagTextDescription::SetText().
Referenced by CIccTagTextDescription::operator=(), and CIccTagTextDescription::SetText().
ToXml()
bool CIccTagXmlTextDescription::ToXml (std::string & xml, std::string blanks = "") virtual
Implements CIccTagXml.
{
    std::string fix;
    std::string buf;
    char data[256];  // Adjust the size as needed
    std::string datastr;
    icXmlDumpTextData(xml, blanks, m_szText);
    // Added support for <![CData[Insert Text here]]> for Unicode
    if (m_uzUnicodeText[0]) {
        if (m_nUnicodeLanguageCode == 0)
            buf = "<Unicode>";
        else {
            icGetSigStr(data, m_nUnicodeLanguageCode);
            icFixXml(fix, data);
            buf = "<Unicode LanguageCode=\"" + fix + "\">";
        }
        xml += blanks + buf;
        icUtf16ToUtf8(datastr, m_uzUnicodeText);
        icFixXml(fix, datastr.c_str());
        buf = "<![CDATA[" + fix + "]]></Unicode>\n";
        xml += buf;
    }
    if (m_nScriptSize) {
        buf = "<MacScript ScriptCode=\"" + std::to_string(m_nScriptCode) + "\">";
        xml += blanks + buf;
        std::stringstream ss;
        for (int i = 0; i < m_nScriptSize; i++) {
            ss << std::hex << std::uppercase << std::setw(2) << std::setfill('0')
               << static_cast<int>(static_cast<unsigned char>(m_szScriptText[i]));
        }
        buf = ss.str();
        xml += buf;
        xml += "</MacScript>\n";
    }
    return true;
}
References icFixXml(), icGetSigStr(), icUtf16ToUtf8(), icXmlDumpTextData(), CIccTagTextDescription::m_nScriptCode, CIccTagTextDescription::m_nScriptSize, CIccTagTextDescription::m_nUnicodeLanguageCode, CIccTagTextDescription::m_szScriptText, CIccTagTextDescription::m_szText, and CIccTagTextDescription::m_uzUnicodeText.
Validate()
icValidateStatus CIccTagTextDescription::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual inherited
Name: CIccTagTextDescription::Validate
Purpose: Check tag data validity.
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  if (m_nScriptSize>67) {
    sReport += icMsgValidateNonCompliant;
    sReport += sSigPathName;
    sReport += " - ScriptCode count must not be greater than 67.\n";
    rv =icMaxStatus(rv, icValidateNonCompliant);
  }
  if (m_bInvalidScript) {
    sReport += icMsgValidateNonCompliant;
    sReport += sSigPathName;
    sReport += " - ScriptCode must contain 67 bytes.\n";
    rv =icMaxStatus(rv, icValidateNonCompliant);
  }
  return rv;
}
References CIccInfo::GetSigPathName(), icMaxStatus(), icMsgValidateNonCompliant, icValidateNonCompliant, CIccTagTextDescription::m_bInvalidScript, CIccTagTextDescription::m_nScriptSize, and CIccTag::Validate().
Write()
bool CIccTagTextDescription::Write (CIccIO * pIO) virtual inherited
Name: CIccTagTextDescription::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  icUInt32Number zero = 0;
  if (!pIO)
   return false;
  if (!pIO->Write32(&sig) ||
      !pIO->Write32(&m_nReserved) ||
      !pIO->Write32(&m_nASCIISize))
    return false;
  if (m_nASCIISize) {
    if (pIO->Write8(m_szText, m_nASCIISize) != (icInt32Number)m_nASCIISize)
      return false;
  }
  if (!pIO->Write32(&m_nUnicodeLanguageCode))
    return false;
  if (m_nUnicodeSize > 1) {
    if (!pIO->Write32(&m_nUnicodeSize) ||
        pIO->Write16(m_uzUnicodeText, m_nUnicodeSize) != (icInt32Number)m_nUnicodeSize)
      return false;
  }
  else {
    if (!pIO->Write32(&zero))
      return false;
  }
  if (!pIO->Write16(&m_nScriptCode) ||
      !pIO->Write8(&m_nScriptSize) ||
      pIO->Write8(m_szScriptText, 67)!= 67)
    return false;
  m_bInvalidScript = false;
  return true;
}
References CIccTagTextDescription::GetType(), CIccTagTextDescription::m_bInvalidScript, CIccTagTextDescription::m_nASCIISize, CIccTag::m_nReserved, CIccTagTextDescription::m_nScriptCode, CIccTagTextDescription::m_nScriptSize, CIccTagTextDescription::m_nUnicodeLanguageCode, CIccTagTextDescription::m_nUnicodeSize, CIccTagTextDescription::m_szScriptText, CIccTagTextDescription::m_szText, CIccTagTextDescription::m_uzUnicodeText, CIccIO::Write16(), CIccIO::Write32(), and CIccIO::Write8().
Field Documentation
m_bInvalidScript
bool CIccTagTextDescription::m_bInvalidScript protected inherited
Referenced by CIccTagTextDescription::CIccTagTextDescription(), CIccTagTextDescription::CIccTagTextDescription(), CIccTagTextDescription::operator=(), CIccTagTextDescription::Read(), CIccTagTextDescription::SetText(), CIccTagTextDescription::Validate(), and CIccTagTextDescription::Write().
m_nASCIISize
icUInt32Number CIccTagTextDescription::m_nASCIISize protected inherited
Referenced by CIccTagTextDescription::CIccTagTextDescription(), CIccTagTextDescription::CIccTagTextDescription(), CIccTagTextDescription::Capacity(), CIccTagTextDescription::GetBuffer(), CIccTagTextDescription::operator=(), ParseXml(), CIccTagTextDescription::Release(), and CIccTagTextDescription::Write().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_nScriptCode
icUInt16Number CIccTagTextDescription::m_nScriptCode protected inherited
Referenced by CIccTagTextDescription::CIccTagTextDescription(), CIccTagTextDescription::CIccTagTextDescription(), CIccTagTextDescription::operator=(), ParseXml(), CIccTagTextDescription::Read(), ToXml(), and CIccTagTextDescription::Write().
m_nScriptSize
icUInt8Number CIccTagTextDescription::m_nScriptSize protected inherited
Referenced by CIccTagTextDescription::CIccTagTextDescription(), CIccTagTextDescription::CIccTagTextDescription(), CIccTagTextDescription::operator=(), ParseXml(), CIccTagTextDescription::Read(), ToXml(), CIccTagTextDescription::Validate(), and CIccTagTextDescription::Write().
m_nUnicodeLanguageCode
icUInt32Number CIccTagTextDescription::m_nUnicodeLanguageCode protected inherited
Referenced by CIccTagTextDescription::CIccTagTextDescription(), CIccTagTextDescription::CIccTagTextDescription(), CIccTagTextDescription::operator=(), CIccTagTextDescription::Read(), ToXml(), and CIccTagTextDescription::Write().
m_nUnicodeSize
icUInt32Number CIccTagTextDescription::m_nUnicodeSize protected inherited
Referenced by CIccTagTextDescription::CIccTagTextDescription(), CIccTagTextDescription::CIccTagTextDescription(), CIccTagTextDescription::GetUnicodeBuffer(), CIccTagTextDescription::operator=(), ParseXml(), CIccTagTextDescription::ReleaseUnicode(), and CIccTagTextDescription::Write().
m_szScriptText
icUInt8Number CIccTagTextDescription::m_szScriptText[67] protected inherited
Referenced by CIccTagTextDescription::CIccTagTextDescription(), CIccTagTextDescription::CIccTagTextDescription(), CIccTagTextDescription::operator=(), ParseXml(), CIccTagTextDescription::Read(), ToXml(), and CIccTagTextDescription::Write().
m_szText
icChar* CIccTagTextDescription::m_szText protected inherited
Referenced by CIccTagTextDescription::CIccTagTextDescription(), CIccTagTextDescription::CIccTagTextDescription(), CIccTagTextDescription::~CIccTagTextDescription(), CIccTagTextDescription::Describe(), CIccTagTextDescription::GetBuffer(), CIccTagTextDescription::GetText(), CIccTagTextDescription::operator=(), CIccTagTextDescription::operator=(), ParseXml(), CIccTagTextDescription::Read(), CIccTagTextDescription::Release(), ToXml(), and CIccTagTextDescription::Write().
m_uzUnicodeText
icUInt16Number* CIccTagTextDescription::m_uzUnicodeText protected inherited
Referenced by CIccTagTextDescription::CIccTagTextDescription(), CIccTagTextDescription::CIccTagTextDescription(), CIccTagTextDescription::~CIccTagTextDescription(), CIccTagTextDescription::GetUnicodeBuffer(), CIccTagTextDescription::operator=(), ParseXml(), CIccTagTextDescription::ReleaseUnicode(), ToXml(), and CIccTagTextDescription::Write().
The documentation for this class was generated from the following files:
IccXML/IccLibXML/IccTagXml.h
IccXML/IccLibXML/IccTagXml.cpp