iccDEV: MyTagDialog Class Reference
MyTagDialog Class Reference
#include <wxProfileDump.h>
Inherits wxDialog.
Public Member Functions
MyTagDialog (wxWindow *pParent, CIccProfile *pIcc, icTagSignature sig, CIccTag *pTag)
Data Fields
wxFont m_FixedFont
CIccProfile * m_pIcc
CIccTag * m_pTag
icTagSignature m_sigTag
Detailed Description
Constructor & Destructor Documentation
MyTagDialog()
MyTagDialog::MyTagDialog (wxWindow * pParent, CIccProfile * pIcc, icTagSignature sig, CIccTag * pTag)
                                                                                                     :
wxDialog(pParent, wxID_ANY, _T("View Tag"), wxDefaultPosition, wxDefaultSize, wxDEFAULT_DIALOG_STYLE | wxRESIZE_BORDER)
{
    m_pIcc = pIcc;
    m_sigTag = sig;
    m_pTag = pTag;
    CIccInfo Fmt;
    wxString sTagSignature = Fmt.GetTagSigName(sig);
    wxString sTagType;
    std::string desc;
    if (pTag) {
        if (pTag->IsArrayType()) {
            sTagType = _T("Array of ");
        }
        else {
            sTagType.Empty();
        }
        sTagType += Fmt.GetTagTypeSigName(pTag->GetType());
        wxBeginBusyCursor();
        pTag->Describe(desc, 100);
        wxEndBusyCursor();
    }
    else if (pIcc) {
        CIccMemIO *pIO = pIcc->GetTagIO(sig);
        sTagType = "***Invalid Tag!***";
        if (pIO) {
            std::string dump;
            icMemDump(dump, pIO->GetData(), pIO->GetLength());
            delete pIO;
            desc = "Data contents of tag:\n\n";
            desc += dump;
        }
        else {
            desc = "Invalid Tag Directory Entry!\n";
        }
    }
    else {
        desc = "Invalid Tag Entry!\n";
        sTagType = "***Invalid Tag***";
    }
    wxSizer *sizer = new wxBoxSizer(wxVERTICAL);
    wxSizer *sizerRow1 = new wxBoxSizer(wxHORIZONTAL);
    wxSize winSize = wxDefaultSize;
    winSize.SetWidth(100);
    wxStaticText *labelSig = new wxStaticText(this, wxID_ANY, _T("Tag Signature:"), wxDefaultPosition, winSize, wxALIGN_RIGHT);
    winSize.SetWidth(400);
    wxStaticText *textSig = new wxStaticText(this, wxID_ANY, sTagSignature, wxDefaultPosition, winSize, wxSTATIC_BORDER|wxTE_RIGHT);
    sizerRow1->Add(labelSig, 0, wxALL | wxALIGN_CENTRE_VERTICAL, 5);
    sizerRow1->Add(textSig, 1, wxALL | wxALIGN_CENTRE_VERTICAL, 5);
    sizer->Add(sizerRow1, wxSizerFlags().Expand());
    wxSizer *sizerRow2 = new wxBoxSizer(wxHORIZONTAL);
    winSize = wxDefaultSize;
    winSize.SetWidth(100);
    wxStaticText *labelType = new wxStaticText(this, wxID_ANY, _T("Tag Type:"), wxDefaultPosition, winSize, wxALIGN_RIGHT);
    winSize.SetWidth(400);
    wxStaticText *textType = new wxStaticText(this, wxID_ANY, sTagType, wxDefaultPosition, winSize, wxSTATIC_BORDER|wxTE_RIGHT);
    sizerRow2->Add(labelType, 0, wxALL | wxALIGN_CENTRE_VERTICAL, 5);
    sizerRow2->Add(textType, 1, wxALL | wxALIGN_CENTRE_VERTICAL, 5);
    sizer->Add(sizerRow2, wxSizerFlags().Expand());
    winSize = wxSize(500, 400);
    wxTextCtrl *textReport = new wxTextCtrl(this, wxID_ANY, wxString(desc.c_str()), wxDefaultPosition, winSize,
        wxTE_MULTILINE |wxTE_READONLY | wxTE_RICH| wxTE_DONTWRAP);
    sizer->Add(textReport, wxSizerFlags(1).Expand());
    SetSizer(sizer);
    sizer->Fit(this);
}
References MyTagDialog(), CIccTag::Describe(), CIccMemIO::GetData(), CIccMemIO::GetLength(), CIccInfo::GetTagTypeSigName(), CIccTag::GetType(), icMemDump(), CIccTag::IsArrayType(), m_pIcc, m_pTag, and m_sigTag.
Referenced by MyTagDialog().
Field Documentation
m_FixedFont
wxFont MyTagDialog::m_FixedFont
m_pIcc
CIccProfile* MyTagDialog::m_pIcc
Referenced by MyTagDialog().
m_pTag
CIccTag* MyTagDialog::m_pTag
Referenced by MyTagDialog().
m_sigTag
icTagSignature MyTagDialog::m_sigTag
Referenced by MyTagDialog().
The documentation for this class was generated from the following files:
Tools/wxWidget/wxProfileDump/wxProfileDump.h
Tools/wxWidget/wxProfileDump/wxProfileDump.cpp