iccDEV: CIccMpeCreator Class Reference
CIccMpeCreator Class Reference
#include <IccMpeFactory.h>
Public Member Functions
~CIccMpeCreator ()
Static Public Member Functions
static CIccMultiProcessElement * CreateElement (icElemTypeSignature elemTypeSig)
static bool GetElementSigName (std::string &elemName, icElemTypeSignature elemTypeSig)
static IIccMpeFactory * PopFactory ()
static void PushFactory (IIccMpeFactory *pFactory)
Private Member Functions
CIccMpeCreator ()
CIccMultiProcessElement * DoCreateElement (icElemTypeSignature elemTypeSig)
bool DoGetElementSigName (std::string &elemName, icElemTypeSignature elemTypeSig)
IIccMpeFactory * DoPopFactory (bool bAll=false)
void DoPushFactory (IIccMpeFactory *pFactory)
Static Private Member Functions
static CIccMpeCreator * GetInstance ()
Private Attributes
CIccMpeFactoryList factoryStack
Static Private Attributes
static CIccMpeCreatorPtr theElementCreator
Detailed Description
Class: CIccMpeCreator
Purpose: CIccMpeCreator uses a singleton pattern to provide dynamically upgradeable CIccProcessElement derived object creation based on element signature.
Constructor & Destructor Documentation
~CIccMpeCreator()
CIccMpeCreator::~CIccMpeCreator ()
{
  IIccMpeFactory *pFactory = DoPopFactory(true);
  while (pFactory) {
    delete pFactory;
    pFactory = DoPopFactory(true);
  }
}
References DoPopFactory().
CIccMpeCreator()
CIccMpeCreator::CIccMpeCreator () inline private
Only GetInstance() can create the singleton
{ }
Member Function Documentation
CreateElement()
static CIccMultiProcessElement * CIccMpeCreator::CreateElement (icElemTypeSignature elemTypeSig) inline static
Function: CreateElement(elemTypeSig) Create a element of type elemTypeSig.
Parameter(s): elemTypeSig = signature of the ICC element type for the element to be created
Returns a new CIccProcessElement object of the given signature type. Each factory in the factoryStack is used until a factory supports the signature type.
      { return CIccMpeCreator::GetInstance()->DoCreateElement(elemTypeSig); }
References DoCreateElement(), and GetInstance().
Referenced by CIccMultiProcessElement::Create().
DoCreateElement()
CIccMultiProcessElement * CIccMpeCreator::DoCreateElement (icElemTypeSignature elemTypeSig) private
{
  CIccMpeFactoryList::iterator i;
  CIccMultiProcessElement *rv = NULL;
  for (i=factoryStack.begin(); i!=factoryStack.end(); i++) {
    rv = (*i)->CreateElement(elemTypeSig);
    if (rv)
      break;
  }
  return rv;
}
References IIccMpeFactory::CreateElement(), and factoryStack.
Referenced by CreateElement().
DoGetElementSigName()
bool CIccMpeCreator::DoGetElementSigName (std::string & elemName, icElemTypeSignature elemTypeSig) private
{
  CIccMpeFactoryList::iterator i;
  for (i=factoryStack.begin(); i!=factoryStack.end(); i++) {
    if ((*i)->GetElementSigName(elemName, elemTypeSig))
      return true;
  }
  return false;
}
References factoryStack, and IIccMpeFactory::GetElementSigName().
Referenced by GetElementSigName().
DoPopFactory()
IIccMpeFactory * CIccMpeCreator::DoPopFactory (bool bAll = false) private
{
  if (factoryStack.size()>0) {
    CIccMpeFactoryList::iterator i=factoryStack.begin();
    IIccMpeFactory* rv = (*i);
    factoryStack.pop_front();
    return rv;
  }
  return NULL;
}
References factoryStack.
Referenced by ~CIccMpeCreator(), and PopFactory().
DoPushFactory()
void CIccMpeCreator::DoPushFactory (IIccMpeFactory * pFactory) private
{
  factoryStack.push_front(pFactory);
}
References factoryStack.
Referenced by GetInstance(), and PushFactory().
GetElementSigName()
static bool CIccMpeCreator::GetElementSigName (std::string & elemName, icElemTypeSignature elemTypeSig) inline static
Function: GetElementSigName(elemTypeSig) Get display name of elemTypeSig.
Parameter(s): elemName = string to put element name into elemTypeSig = signature of the ICC element type to get a name for
Returns true if element type is recognized by any factory, false if all factories do not create elemTypeSig elements. If element type is not recognized by any factories a suitable display name will be placed in elemName.
      { return CIccMpeCreator::GetInstance()->DoGetElementSigName(elemName, elemTypeSig); }
References DoGetElementSigName(), and GetInstance().
Referenced by CIccInfo::GetElementTypeSigName().
GetInstance()
CIccMpeCreator * CIccMpeCreator::GetInstance () static private
Function: GetInstance() Private static function to access singleton CiccElementCreator Object.
Parameter(s): None
Returns the singleton CIccMpeCreator object. It will allocate a new one and push a single CIccSpecElement Factory object onto the factory stack if the singleton has not been intialized.
{
  if (!theElementCreator.get()) {
    theElementCreator = CIccMpeCreatorPtr(new CIccMpeCreator);
    theElementCreator->DoPushFactory(new CIccBasicMpeFactory);
  }
  return theElementCreator.get();
}
References DoPushFactory(), and theElementCreator.
Referenced by CreateElement(), GetElementSigName(), PopFactory(), and PushFactory().
PopFactory()
static IIccMpeFactory * CIccMpeCreator::PopFactory () inline static
Function: PopFactory() Remove the top IIccMpeFactory from the stack of element factories tracked by the system.
Parameter(s): None
Returns the top IIccMpeFactory from the stack of element factories tracked by the system. The returned element factory is no longer owned by the system and needs to be deleted to avoid memory leaks.
Note: The initial CIccBasicElemFactory cannot be popped off the stack.
      { return CIccMpeCreator::GetInstance()->DoPopFactory(); }
References DoPopFactory(), and GetInstance().
PushFactory()
static void CIccMpeCreator::PushFactory (IIccMpeFactory * pFactory) inline static
Function: PushFactory(pFactory) Add an IIccMpeFactory to the stack of element factories tracked by the system.
Parameter(s): pFactory = pointer to an IIccMpeFactory object to add to the system. The pFactory must be created with new, and will be owned CIccMpeCreator until popped off the stack using PopFactory(). Any factories not popped off will be taken care of properly on application shutdown.
      { CIccMpeCreator::GetInstance()->CIccMpeCreator::DoPushFactory(pFactory); }
References DoPushFactory(), and GetInstance().
Referenced by main().
Field Documentation
factoryStack
CIccMpeFactoryList CIccMpeCreator::factoryStack private
Referenced by DoCreateElement(), DoGetElementSigName(), DoPopFactory(), and DoPushFactory().
theElementCreator
CIccMpeCreatorPtr CIccMpeCreator::theElementCreator static private
Referenced by GetInstance().
The documentation for this class was generated from the following files:
IccProfLib/IccMpeFactory.h
IccProfLib/IccMpeFactory.cpp