iccDEV: CIccTagFixedNum< T, Tsig > Class Template Reference
CIccTagFixedNum< T, Tsig > Class Template Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagFixedNum (const CIccTagFixedNum< T, Tsig > &ITFN)
CIccTagFixedNum (int nSize=1)
virtual ~CIccTagFixedNum ()
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
virtual const icChar * GetClassName () const
virtual IIccExtensionTag * GetExtension ()
virtual icUInt32Number GetNumValues () const
icUInt32Number GetSize () const
Returns the size of the data array.
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual bool GetValues (icFloatNumber *DstVector, icUInt32Number nStart=0, icUInt32Number nVectorSize=1) const
virtual bool Interpolate (icFloatNumber *DstVector, icFloatNumber val, icUInt32Number nVectorSize=1, icFloatNumber *zeroVals=NULL) const
virtual bool IsArrayType ()
virtual bool IsMatrixArray () const
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
CIccTagFixedNum & operator= (const CIccTagFixedNum< T, Tsig > &FixedNumTag)
T & operator[] (icUInt32Number index)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
bool SetSize (icUInt32Number nSize, bool bZeroNew=true)
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool ValuePos (icFloatNumber &DstPos, icFloatNumber val, bool &bNoZero) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
Protected Attributes
icUInt32Number m_nSize
T * m_Num
Detailed Description
template<class T, icTagTypeSignature Tsig>
class CIccTagFixedNum< T, Tsig >
Class: CIccTagFixedNum
Purpose: A template class for arrays of Fixed point numbers
Derived Tags: CIccTagS15Fixed16 and CIccTagU16Fixed16
Constructor & Destructor Documentation
CIccTagFixedNum() [1/2]
template<class T , icTagTypeSignature Tsig> CIccTagFixedNum< T, Tsig >::CIccTagFixedNum (int nSize = 1)
Name: CIccTagFixedNum::CIccTagFixedNum
Purpose: CIccTagFixedNumConstructor
Args: nSize = number of data entries
{
  m_nSize = nSize;
  if (m_nSize <1)
    m_nSize = 1;
  m_Num = (T*)calloc(nSize, sizeof(T));
}
References CIccTagFixedNum< T, Tsig >::m_nSize, and CIccTagFixedNum< T, Tsig >::m_Num.
Referenced by main().
CIccTagFixedNum() [2/2]
template<class T , icTagTypeSignature Tsig> CIccTagFixedNum< T, Tsig >::CIccTagFixedNum (const CIccTagFixedNum< T, Tsig > & ITFN)
Name: CIccTagFixedNum::CIccTagFixedNum
Purpose: Copy Constructor
Args: ITFN = The CIccTagFixedNum object to be copied
{
  m_nSize = ITFN.m_nSize;
  m_Num = (T*)calloc(m_nSize, sizeof(T));
  memcpy(m_Num, ITFN.m_Num, m_nSize*sizeof(T));
}
References CIccTagFixedNum< T, Tsig >::m_nSize, and CIccTagFixedNum< T, Tsig >::m_Num.
~CIccTagFixedNum()
template<class T , icTagTypeSignature Tsig> CIccTagFixedNum< T, Tsig >::~CIccTagFixedNum () virtual
Name: CIccTagFixedNum::~CIccTagFixedNum
Purpose: Destructor
{
  if (m_Num)
    free(m_Num);
}
References CIccTagFixedNum< T, Tsig >::m_Num.
Member Function Documentation
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
template<class T , icTagTypeSignature Tsig> void CIccTagFixedNum< T, Tsig >::Describe (std::string & sDescription, int nVerboseness) virtual
Name: CIccTagFixedNum::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  icChar buf[128] = { 0 };
  if (m_nSize == 1 ) {
    if (Tsig==icSigS15Fixed16ArrayType)
      sprintf(buf, "Value = %.4lf\n", icFtoD(m_Num[0]));
    else
      sprintf(buf, "Value = %.4lf\n", icUFtoD(m_Num[0]));
    sDescription += buf;
  }
  else {
    icUInt32Number i;
    if (Tsig==icSigS15Fixed16ArrayType && m_nSize==9) {
      sDescription += "Matrix Form:\n";
      icMatrixDump(sDescription, (icS15Fixed16Number*)m_Num);
      sDescription += "\nArrayForm:\n";
    }
    sDescription.reserve(sDescription.size() + m_nSize*79);
    for (i=0; i<m_nSize; i++) {
      if (Tsig==icSigS15Fixed16ArrayType)
        sprintf(buf, "Value[%u] = %8.4lf\n", i, icFtoD(m_Num[i]));
      else
        sprintf(buf, "Value[%u] = %8.4lf\n", i, icUFtoD(m_Num[i]));
      sDescription += buf;
    }
  }
}
References icMatrixDump(), icSigS15Fixed16ArrayType, CIccTagFixedNum< T, Tsig >::m_nSize, and CIccTagFixedNum< T, Tsig >::m_Num.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
GetClassName()
template<class T , icTagTypeSignature Tsig> const icChar * CIccTagFixedNum< T, Tsig >::GetClassName () const virtual
Name: CIccTagFixedNum::GetClassName
Purpose: Returns the tag type class name
Reimplemented from CIccTag.
Reimplemented in CIccTagXmlFixedNum< T, Tsig >.
{
  if (Tsig==icSigS15Fixed16ArrayType)
    return "CIccTagS15Fixed16";
  else
    return "CIccTagU16Fixed16";
}
References icSigS15Fixed16ArrayType.
GetExtension()
virtual IIccExtensionTag * CIccTag::GetExtension () inline virtual inherited
Reimplemented in CIccTagXmlUnknown, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, CIccTagXmlSignature, CIccTagXmlNamedColor2, CIccTagXmlXYZ, CIccTagXmlChromaticity, CIccTagXmlCicp, CIccTagXmlSparseMatrixArray, CIccTagXmlFixedNum< T, Tsig >, CIccTagXmlNum< T, A, Tsig >, CIccTagXmlFloatNum< T, A, Tsig >, CIccTagXmlMeasurement, CIccTagXmlMultiLocalizedUnicode, CIccTagXmlTagData, CIccTagXmlDateTime, CIccTagXmlColorantOrder, CIccTagXmlColorantTable, CIccTagXmlViewingConditions, CIccTagXmlSpectralDataInfo, CIccTagXmlSpectralViewingConditions, CIccTagXmlProfileSeqDesc, CIccTagXmlResponseCurveSet16, CIccTagXmlCurve, CIccTagXmlParametricCurve, CIccTagXmlSegmentedCurve, CIccTagXmlLutAtoB, CIccTagXmlLutBtoA, CIccTagXmlLut8, CIccTagXmlLut16, CIccTagXmlMultiProcessElement, CIccTagXmlProfileSequenceId, CIccTagXmlDict, CIccTagXmlStruct, CIccTagXmlArray, CIccTagXmlGamutBoundaryDesc, CIccTagXmlEmbeddedHeightImage, CIccTagXmlEmbeddedNormalImage, and CIccTagXmlEmbeddedProfile.
{return NULL;}
Referenced by icCurvesFromXml(), icCurvesToXml(), icProfDescToXml(), icXmlParseProfDesc(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeXmlTintArray::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
GetNumValues()
template<class T , icTagTypeSignature Tsig> virtual icUInt32Number CIccTagFixedNum< T, Tsig >::GetNumValues () const inline virtual
Implements CIccTagNumArray.
{ return GetSize(); }
References CIccTagFixedNum< T, Tsig >::GetSize().
GetSize()
template<class T , icTagTypeSignature Tsig> icUInt32Number CIccTagFixedNum< T, Tsig >::GetSize () const inline
Returns the size of the data array.
{ return m_nSize; }
References CIccTagFixedNum< T, Tsig >::m_nSize.
Referenced by CIccTagFixedNum< T, Tsig >::GetNumValues().
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
template<class T , icTagTypeSignature Tsig> virtual icTagTypeSignature CIccTagFixedNum< T, Tsig >::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return Tsig; }
Referenced by CIccTagFixedNum< T, Tsig >::Write().
GetValues()
template<class T , icTagTypeSignature Tsig> bool CIccTagFixedNum< T, Tsig >::GetValues (icFloatNumber * DstVector, icUInt32Number nStart = 0, icUInt32Number nVectorSize = 1) const virtual
Name: CIccTagFixedNum::GetValues
Purpose: Gets values from the num array tag as floating point numbers
Args: nSize - number of data entries, bZeroNew - flag to zero newly formed values
Implements CIccTagNumArray.
{
  if (nVectorSize+nStart >m_nSize)
    return false;
  icUInt32Number i;
  switch (Tsig) {
    case icSigS15Fixed16ArrayType:
      for (i=0; i<m_nSize; i++) {
        DstVector[i] = (icFloatNumber)icFtoD(m_Num[i+nStart]);
      }
      break;
    case icSigU16Fixed16ArrayType:
      for (i=0; i<m_nSize; i++) {
        DstVector[i] = (icFloatNumber)icUFtoD(m_Num[i+nStart]);
      }
      break;
    default:
      return false;
  }
  return true;
}
References icSigS15Fixed16ArrayType, icSigU16Fixed16ArrayType, CIccTagFixedNum< T, Tsig >::m_nSize, and CIccTagFixedNum< T, Tsig >::m_Num.
Interpolate()
template<class T , icTagTypeSignature Tsig> bool CIccTagFixedNum< T, Tsig >::Interpolate (icFloatNumber * DstVector, icFloatNumber pos, icUInt32Number nVectorSize = 1, icFloatNumber * zeroVals = NULL) const virtual
Name: CIccTagFixedNum::Interpolate
Purpose: Gets values from the num array tag as floating point numbers
Args: nSize - number of data entries, bZeroNew - flag to zero newly formed values
Implements CIccTagNumArray.
{
  icUInt32Number nVector = m_nSize / nVectorSize;
  if (!nVector)
    return false;
  if (zeroVals)
    nVector ++;
  else if (nVector<=1)
    return false;
  if (pos<0.0)
    pos=0.0;
  if (pos>1.0)
    pos=1.0;
  icFloatNumber fpos = (icFloatNumber)(nVector-1) * pos;
  icUInt32Number iPos = (icUInt32Number)fpos;
  icFloatNumber x = fpos - iPos;
  if (iPos == nVector-1) {
    iPos--;
    x = (icFloatNumber)1.0;
  }
  T *lo, *hi;
  if (zeroVals) {
    if (!iPos) {
      lo = NULL;
      hi = m_Num;
    }
    else {
      lo = &m_Num[(iPos-1)*nVectorSize];
      hi = &lo[nVectorSize];
    }
  }
  else {
    lo = &m_Num[iPos*nVectorSize];
    hi = &lo[nVectorSize];
  }
  icUInt32Number i;
  switch (Tsig) {
    case icSigS15Fixed16ArrayType:
      if (!lo) {
        if (zeroVals) {
          for (i = 0; i < m_nSize; i++) {
            DstVector[i] = (icFloatNumber)(zeroVals[i] * (1.0f - x) + icFtoD(hi[i]) * x);
          }
        }
        else {
          for (i = 0; i < m_nSize; i++) {
            DstVector[i] = (icFloatNumber)(icFtoD(hi[i]) * x);
          }
        }
      }
      else {
        for (i=0; i<m_nSize; i++) {
          DstVector[i] = (icFloatNumber)(icFtoD(lo[i])*(1.0-x) + icFtoD(hi[i])*x);
        }
      }
      break;
    case icSigU16Fixed16ArrayType:
      if (!lo) {
        if (zeroVals) {
          for (i = 0; i < m_nSize; i++) {
            DstVector[i] = (icFloatNumber)(zeroVals[i] * (1.0 - x) + icUFtoD(hi[i]) * x);
          }
        }
        else {
          for (i = 0; i < m_nSize; i++) {
            DstVector[i] = (icFloatNumber)(icUFtoD(hi[i]) * x);
          }
        }
      }
      else {
        for (i=0; i<m_nSize; i++) {
          DstVector[i] = (icFloatNumber)(icUFtoD(lo[i])*(1.0-x) + icUFtoD(hi[i])*x);
        }
      }
      break;
    default:
      return false;
  }
  return true;
}
References icSigS15Fixed16ArrayType, icSigU16Fixed16ArrayType, CIccTagFixedNum< T, Tsig >::m_nSize, and CIccTagFixedNum< T, Tsig >::m_Num.
IsArrayType()
template<class T , icTagTypeSignature Tsig> virtual bool CIccTagFixedNum< T, Tsig >::IsArrayType () inline virtual
Reimplemented from CIccTag.
{ return m_nSize > 1; }
References CIccTagFixedNum< T, Tsig >::m_nSize.
IsMatrixArray()
template<class T , icTagTypeSignature Tsig> virtual bool CIccTagFixedNum< T, Tsig >::IsMatrixArray () const inline virtual
Implements CIccTagNumArray.
{ return false; }
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
template<class T , icTagTypeSignature Tsig> virtual bool CIccTagFixedNum< T, Tsig >::IsNumArrayType () const inline virtual
Reimplemented from CIccTag.
{ return true; }
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
template<class T , icTagTypeSignature Tsig> virtual CIccTag * CIccTagFixedNum< T, Tsig >::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
{ return new CIccTagFixedNum<T, Tsig>(*this); }
operator=()
template<class T , icTagTypeSignature Tsig> CIccTagFixedNum< T, Tsig > & CIccTagFixedNum< T, Tsig >::operator= (const CIccTagFixedNum< T, Tsig > & ITFN)
Name: CIccTagFixedNum::operator=
Purpose: Copy Operator
Args: ITFN = The CIccTagFixedNum object to be copied
{
  if (&ITFN == this)
    return *this;
  m_nSize = ITFN.m_nSize;
  if (m_Num)
    free(m_Num);
  m_Num = (T*)calloc(m_nSize, sizeof(T));
  memcpy(m_Num, ITFN.m_Num, m_nSize*sizeof(T));
  return *this;
}
References CIccTagFixedNum< T, Tsig >::m_nSize, and CIccTagFixedNum< T, Tsig >::m_Num.
operator[]()
template<class T , icTagTypeSignature Tsig> T & CIccTagFixedNum< T, Tsig >::operator[] (icUInt32Number index) inline
{return m_Num[index];}
References CIccTagFixedNum< T, Tsig >::m_Num.
Referenced by main().
Read() [1/2]
template<class T , icTagTypeSignature Tsig> bool CIccTagFixedNum< T, Tsig >::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagFixedNum::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  if (sizeof(icTagTypeSignature) +
      sizeof(icUInt32Number) +
      sizeof(T) > size)
    return false;
  if (!pIO) {
    return false;
  }
  if (!pIO->Read32(&sig))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  icUInt32Number nSize=((size-2*sizeof(icUInt32Number)) / sizeof(T));
  if (!SetSize(nSize))
    return false;
  if (pIO->Read32(m_Num, nSize) != (icInt32Number)nSize )
    return false;
  return true;
}
References CIccTag::m_nReserved, CIccTagFixedNum< T, Tsig >::m_Num, CIccIO::Read32(), and CIccTagFixedNum< T, Tsig >::SetSize().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
SetSize()
template<class T , icTagTypeSignature Tsig> bool CIccTagFixedNum< T, Tsig >::SetSize (icUInt32Number nSize, bool bZeroNew = true)
Name: CIccTagFixedNum::SetSize
Purpose: Sets the size of the data array.
Args: nSize - number of data entries, bZeroNew - flag to zero newly formed values
{
  if (nSize==m_nSize)
    return true;
  m_Num = (T*)icRealloc(m_Num, nSize*sizeof(T));
  if (!m_Num) {
    m_nSize = 0;
    return false;
  }
  if (bZeroNew && m_nSize < nSize) {
    memset(&m_Num[m_nSize], 0, (nSize-m_nSize)*sizeof(T));
  }
  m_nSize = nSize;
  return true;
}
References CIccTagFixedNum< T, Tsig >::m_nSize, and CIccTagFixedNum< T, Tsig >::m_Num.
Referenced by CIccTagFixedNum< T, Tsig >::Read().
Validate()
icValidateStatus CIccTag::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual inherited
Function: Validate Each derived tag will implement it's own IsValid() function
Parameter(s): sig - signature of tag being validated, sDescription - A string to put tag validation report.
Name: CIccTag::Validate
Purpose: Check tag data validity. In base class we only look at the tag's reserved data value
Args: sig = signature of tag being validated, sReport = String to add report information to
Return: icValidateStatusOK if valid, or other error status.
Reimplemented in CIccTagGamutBoundaryDesc, CIccTagText, CIccTagUtf8Text, CIccTagZipUtf8Text, CIccTagUtf16Text, CIccTagTextDescription, CIccTagSignature, CIccTagNamedColor2, CIccTagXYZ, CIccTagChromaticity, CIccTagCicp, CIccTagSparseMatrixArray, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, CIccTagMeasurement, CIccTagMultiLocalizedUnicode, CIccTagData, CIccTagDateTime, CIccTagColorantOrder, CIccTagColorantTable, CIccTagViewingConditions, CIccTagProfileSeqDesc, CIccTagResponseCurveSet16, CIccTagSpectralDataInfo, CIccTagSpectralViewingConditions, CIccTagEmbeddedHeightImage, CIccTagEmbeddedNormalImage, CIccTagStruct, CIccTagArray, CIccTagDict, CIccTagEmbeddedProfile, CIccTagCurve, CIccTagParametricCurve, CIccTagSegmentedCurve, CIccTagMultiProcessElement, and CIccTagProfileSequenceId.
{
  icValidateStatus rv = icValidateOK;
  if (m_nReserved != 0) {
    CIccInfo Info;
    sReport += icMsgValidateNonCompliant;
    sReport += Info.GetSigPathName(sigPath);
    sReport += " - Reserved Value must be zero.\n";
    rv = icValidateNonCompliant;
  }
  return rv;
}
References CIccInfo::GetSigPathName(), icMsgValidateNonCompliant, icValidateNonCompliant, icValidateOK, and CIccTag::m_nReserved.
Referenced by CIccTagGamutBoundaryDesc::Validate(), CIccMBB::Validate(), CIccTagLutAtoB::Validate(), CIccTagLutBtoA::Validate(), CIccTagLut8::Validate(), CIccTagLut16::Validate(), CIccArrayUnknown::Validate(), CIccArrayColorantInfo::Validate(), CIccArrayNamedColor::Validate(), CIccStructUnknown::Validate(), CIccTagText::Validate(), CIccTagUtf8Text::Validate(), CIccTagZipUtf8Text::Validate(), CIccTagUtf16Text::Validate(), CIccTagTextDescription::Validate(), CIccTagSignature::Validate(), CIccTagNamedColor2::Validate(), CIccTagXYZ::Validate(), CIccTagChromaticity::Validate(), CIccTagCicp::Validate(), CIccTagNum< T, Tsig >::Validate(), CIccTagFloatNum< T, Tsig >::Validate(), CIccTagMeasurement::Validate(), CIccTagMultiLocalizedUnicode::Validate(), CIccTagData::Validate(), CIccTagDateTime::Validate(), CIccTagColorantOrder::Validate(), CIccTagColorantTable::Validate(), CIccTagViewingConditions::Validate(), CIccTagProfileSeqDesc::Validate(), CIccTagResponseCurveSet16::Validate(), CIccTagSpectralDataInfo::Validate(), CIccTagSpectralViewingConditions::Validate(), CIccTagEmbeddedHeightImage::Validate(), CIccTagEmbeddedNormalImage::Validate(), CIccTagStruct::Validate(), CIccTagArray::Validate(), CIccTagDict::Validate(), CIccTagEmbeddedProfile::Validate(), CIccTagCurve::Validate(), CIccTagParametricCurve::Validate(), and CIccTagProfileSequenceId::Validate().
ValuePos()
template<class T , icTagTypeSignature Tsig> bool CIccTagFixedNum< T, Tsig >::ValuePos (icFloatNumber & DstPos, icFloatNumber val, bool & bNoZero) const virtual
Name: CIccTagFixedNum::ValuePos
Purpose: Gets position of a value int the num array tag
Args: DstPos - position of val in array val - value to look for in array. bNoZero - flag indicating whether first entry is zero
Implements CIccTagNumArray.
{
  if(val<0.0)
    return false;
  icFloatNumber nv = 0.0;
  icFloatNumber lv = 0.0;
  switch (Tsig) {
    case icSigS15Fixed16ArrayType:
      lv = icFtoD(m_Num[0]);
      break;
    case icSigU16Fixed16ArrayType:
      lv = icUFtoD(m_Num[0]);
      break;
    default:
      return false;
  }
  bNoZero = (lv!=0.0);
  if (val<lv) {
    DstPos = val/lv - 1.0f;
    return true;
  }
  icUInt32Number i;
  for (i=1; i<m_nSize; i++, lv=nv) {
    switch (Tsig) {
      case icSigS15Fixed16ArrayType:
        nv = icFtoD(m_Num[i]);
        break;
      case icSigU16Fixed16ArrayType:
        nv = icUFtoD(m_Num[i]);
        break;
      default:
        return false;
    }
    if (val<=nv) {
      DstPos = (val-lv)/(nv-lv) + i - 1.0f;
      return true;
    }
  }
  return false;
}
References icSigS15Fixed16ArrayType, icSigU16Fixed16ArrayType, CIccTagFixedNum< T, Tsig >::m_nSize, and CIccTagFixedNum< T, Tsig >::m_Num.
Write()
template<class T , icTagTypeSignature Tsig> bool CIccTagFixedNum< T, Tsig >::Write (CIccIO * pIO) virtual
Name: CIccTagFixedNum::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  if (!pIO)
   return false;
  if (!pIO->Write32(&sig))
   return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  if (pIO->Write32(m_Num, m_nSize) != (icInt32Number)m_nSize)
    return false;
  return true;
}
References CIccTagFixedNum< T, Tsig >::GetType(), CIccTag::m_nReserved, CIccTagFixedNum< T, Tsig >::m_nSize, CIccTagFixedNum< T, Tsig >::m_Num, and CIccIO::Write32().
Field Documentation
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_nSize
template<class T , icTagTypeSignature Tsig> icUInt32Number CIccTagFixedNum< T, Tsig >::m_nSize protected
Referenced by CIccTagFixedNum< T, Tsig >::CIccTagFixedNum(), CIccTagFixedNum< T, Tsig >::CIccTagFixedNum(), CIccTagFixedNum< T, Tsig >::Describe(), CIccTagFixedNum< T, Tsig >::GetSize(), CIccTagFixedNum< T, Tsig >::GetValues(), CIccTagFixedNum< T, Tsig >::Interpolate(), CIccTagFixedNum< T, Tsig >::IsArrayType(), CIccTagFixedNum< T, Tsig >::operator=(), CIccTagFixedNum< T, Tsig >::SetSize(), CIccTagFixedNum< T, Tsig >::ValuePos(), and CIccTagFixedNum< T, Tsig >::Write().
m_Num
template<class T , icTagTypeSignature Tsig> T* CIccTagFixedNum< T, Tsig >::m_Num protected
Referenced by CIccTagFixedNum< T, Tsig >::CIccTagFixedNum(), CIccTagFixedNum< T, Tsig >::CIccTagFixedNum(), CIccTagFixedNum< T, Tsig >::~CIccTagFixedNum(), CIccTagFixedNum< T, Tsig >::Describe(), CIccTagFixedNum< T, Tsig >::GetValues(), CIccTagFixedNum< T, Tsig >::Interpolate(), CIccTagFixedNum< T, Tsig >::operator=(), CIccTagFixedNum< T, Tsig >::operator[](), CIccTagFixedNum< T, Tsig >::Read(), CIccTagFixedNum< T, Tsig >::SetSize(), CIccTagFixedNum< T, Tsig >::ValuePos(), and CIccTagFixedNum< T, Tsig >::Write().
The documentation for this class was generated from the following files:
IccProfLib/IccTagBasic.h
IccProfLib/IccTagBasic.cpp