iccDEV: CIccSparseMatrixEntry< T > Class Template Reference
CIccSparseMatrixEntry< T > Class Template Reference abstract
#include <IccSparseMatrix.h>
Public Member Functions
CIccSparseMatrixEntry ()
virtual icFloatNumber get (int index) const =0
virtual icUInt8Number * getPtr (int index) const
void init (void *pData)
virtual void set (int index, icFloatNumber value)=0
virtual icUInt8Number size () const
Protected Attributes
T * m_pData
Detailed Description
template<class T>
class CIccSparseMatrixEntry< T >
Constructor & Destructor Documentation
CIccSparseMatrixEntry()
template<class T > CIccSparseMatrixEntry< T >::CIccSparseMatrixEntry () inline
{m_pData = 0;}
Member Function Documentation
get()
virtual icFloatNumber IIccSparseMatrixEntry::get (int index) const pure virtual inherited
Implemented in CIccSparseMatrixUInt8, CIccSparseMatrixUInt16, CIccSparseMatrixFloat16, CIccSparseMatrixFloat32, and CIccSparseMatrixFloatNum.
Referenced by CIccSparseMatrix::Copy(), CIccTagSparseMatrixArray::Describe(), CIccSparseMatrix::Interp(), and CIccSparseMatrix::MultiplyVector().
getPtr()
template<class T > virtual icUInt8Number * CIccSparseMatrixEntry< T >::getPtr (int index) const inline virtual
Implements IIccSparseMatrixEntry.
{return (icUInt8Number*)(&m_pData[index]); }
References CIccSparseMatrixEntry< T >::m_pData.
init()
template<class T > void CIccSparseMatrixEntry< T >::init (void * pData) inline virtual
Implements IIccSparseMatrixEntry.
{m_pData = (T*)pData;}
References CIccSparseMatrixEntry< T >::m_pData.
set()
virtual void IIccSparseMatrixEntry::set (int index, icFloatNumber value) pure virtual inherited
Implemented in CIccSparseMatrixUInt8, CIccSparseMatrixUInt16, CIccSparseMatrixFloat16, CIccSparseMatrixFloat32, and CIccSparseMatrixFloatNum.
Referenced by CIccSparseMatrix::Copy(), CIccSparseMatrix::FillFromFullMatrix(), CIccSparseMatrix::Interp(), and CIccSparseMatrix::Union().
size()
template<class T > virtual icUInt8Number CIccSparseMatrixEntry< T >::size () const inline virtual
Implements IIccSparseMatrixEntry.
{ return sizeof(T); }
Field Documentation
m_pData
template<class T > T* CIccSparseMatrixEntry< T >::m_pData protected
Referenced by CIccSparseMatrixEntry< T >::getPtr(), and CIccSparseMatrixEntry< T >::init().
The documentation for this class was generated from the following file:
IccProfLib/IccSparseMatrix.h