iccDEV: CIccConsoleDebugger Class Reference
CIccConsoleDebugger Class Reference
Public Member Functions
virtual ~CIccConsoleDebugger ()
virtual bool AfterOp (SIccCalcOp *op, SIccOpState &os, SIccCalcOp *ops)
virtual bool BeforeOp (SIccCalcOp *op, SIccOpState &os, SIccCalcOp *ops)
virtual void BeginApply ()
virtual void EndApply ()
virtual void Error (const char *szMsg)
Static Public Member Functions
static void SetDebugger (IIccCalcDebugger *pDebugger)
Detailed Description
Constructor & Destructor Documentation
~CIccConsoleDebugger()
virtual CIccConsoleDebugger::~CIccConsoleDebugger () inline virtual
{}
Member Function Documentation
AfterOp()
virtual bool CIccConsoleDebugger::AfterOp (SIccCalcOp * op, SIccOpState & os, SIccCalcOp * ops) inline virtual
Implements IIccCalcDebugger.
  {
    if (op->sig == icSigDataOp) {
      printf("%9s\t", "data");
    }
    else {
      if (op->sig == icSigIfOp || op->sig == icSigSelectOp) {
        printf("End:");
      }
      std::string opDesc;
      op->Describe(opDesc, 100); // TODO - propogate nVerboseness
      printf("%9s\t", opDesc.c_str());
    }
    for (int j = 0; j < (int)os.pStack->size(); j++)
      printf(" %.4f", (*os.pStack)[j]);
    printf("\n");
    if (op->sig==icSigIfOp || op->sig==icSigSelectOp)
      printf("\n");
    fflush(stdout);
    return false;
  }
References SIccCalcOp::Describe(), icSigDataOp, icSigIfOp, icSigSelectOp, SIccOpState::pStack, and SIccCalcOp::sig.
BeforeOp()
virtual bool CIccConsoleDebugger::BeforeOp (SIccCalcOp * op, SIccOpState & os, SIccCalcOp * ops) inline virtual
Implements IIccCalcDebugger.
  {
    if (op->sig == icSigIfOp || op->sig == icSigSelectOp) {
      printf("Start:");
        std::string opDesc;
      op->Describe(opDesc, 100); // TODO - propogate nVerboseness
      printf("%9s\t", opDesc.c_str());
      for (int j = 0; j < (int)os.pStack->size(); j++)
        printf(" %.4f", (*os.pStack)[j]);
      printf("\n");
    }
    return false;
  }
References SIccCalcOp::Describe(), icSigIfOp, icSigSelectOp, SIccOpState::pStack, and SIccCalcOp::sig.
BeginApply()
virtual void CIccConsoleDebugger::BeginApply () inline virtual
Implements IIccCalcDebugger.
  {
    printf("\nBegin Calc Apply\n");
  }
EndApply()
virtual void CIccConsoleDebugger::EndApply () inline virtual
Implements IIccCalcDebugger.
  {
    printf("End Calculator Apply\n\n");
    fflush(stdout);
  }
Error()
virtual void CIccConsoleDebugger::Error (const char * szMsg) inline virtual
Implements IIccCalcDebugger.
  {
    printf("%s\n", szMsg);
  }
SetDebugger()
void IIccCalcDebugger::SetDebugger (IIccCalcDebugger * pDebugger) static inherited
{
  if (pDebugger == icCalcDebuggerConsole)
    g_pDebugger = &g_ConsoleDebugger;
  else
    g_pDebugger = pDebugger;
}
References g_ConsoleDebugger, and g_pDebugger.
Referenced by main().
The documentation for this class was generated from the following file:
IccProfLib/IccMpeCalc.cpp