iccDEV: CIccTagXmlDict Class Reference
CIccTagXmlDict Class Reference
#include <IccTagXml.h>
Public Member Functions
virtual ~CIccTagXmlDict ()
bool AreNamesNonzero () const
bool AreNamesUnique () const
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
CIccDictEntry * Get (const char *szName) const
CIccDictEntry * Get (const icUInt16Number *szName) const
CIccDictEntry * Get (std::wstring sName) const
virtual const char * GetClassName () const
virtual const char * GetExtClassName () const
virtual const char * GetExtDerivedClassName () const
virtual IIccExtensionTag * GetExtension ()
CIccTagMultiLocalizedUnicode * GetNameLocalized (const char *szName) const
CIccTagMultiLocalizedUnicode * GetNameLocalized (const icUnicodeChar *szName) const
CIccTagMultiLocalizedUnicode * GetNameLocalized (std::wstring sName) const
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
std::wstring GetValue (const char *szName, bool *bIsSet=NULL) const
std::wstring GetValue (const icUnicodeChar *szName, bool *bIsSet=NULL) const
std::wstring GetValue (std::wstring sName, bool *bIsSet=NULL) const
CIccTagMultiLocalizedUnicode * GetValueLocalized (const char *szName) const
CIccTagMultiLocalizedUnicode * GetValueLocalized (const icUnicodeChar *szName) const
CIccTagMultiLocalizedUnicode * GetValueLocalized (std::wstring sName) const
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
virtual bool ParseXml (xmlNode *pNode, std::string &parseStr)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
bool Remove (const char *szName)
bool Remove (const icUnicodeChar *szName)
bool Remove (std::wstring sName)
bool Set (const char *szName, const char *szValue=NULL)
bool Set (const icUnicodeChar *szName, const icUnicodeChar *szValue=NULL)
bool Set (std::wstring sName, std::wstring sValue, bool bUnSet=false)
bool SetNameLocalized (const char *szName, CIccTagMultiLocalizedUnicode *pTag)
bool SetNameLocalized (const icUnicodeChar *szName, CIccTagMultiLocalizedUnicode *pTag)
bool SetNameLocalized (std::wstring sName, CIccTagMultiLocalizedUnicode *pTag)
bool SetValueLocalized (const char *szName, CIccTagMultiLocalizedUnicode *pTag)
bool SetValueLocalized (const icUnicodeChar *szName, CIccTagMultiLocalizedUnicode *pTag)
bool SetValueLocalized (std::wstring sName, CIccTagMultiLocalizedUnicode *pTag)
virtual bool ToXml (std::string &xml, std::string blanks="")
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
CIccNameValueDict * m_Dict
icUInt32Number m_nReserved
Protected Member Functions
void Cleanup ()
icUInt32Number MaxPosRecSize ()
Protected Attributes
bool m_bBadAlignment
icUInt32Number m_tagSize
icUInt32Number m_tagStart
Detailed Description
Constructor & Destructor Documentation
~CIccTagXmlDict()
virtual CIccTagXmlDict::~CIccTagXmlDict () inline virtual
{}
Member Function Documentation
AreNamesNonzero()
bool CIccTagDict::AreNamesNonzero () const inherited
Name: CIccTagDict::AreNamesNonzero
Purpose: For each tag it checks to see if any other tags have the same signature.
Return: true if all tags have unique signatures, or false if there are duplicate tag signatures.
{
  CIccNameValueDict::const_iterator i, j;
  for (i=m_Dict->begin(); i!=m_Dict->end(); i++) {
    if (i->ptr->GetName().empty())
      return false;
  }
return true;
}
References CIccDictEntry::GetName(), CIccTagDict::m_Dict, and CIccDictEntryPtr::ptr.
Referenced by CIccTagDict::Validate().
AreNamesUnique()
bool CIccTagDict::AreNamesUnique () const inherited
Name: CIccTagDict::AreNamesUnique
Purpose: For each tag it checks to see if any other tags have the same signature.
Return: true if all tags have unique signatures, or false if there are duplicate tag signatures.
{
  CIccNameValueDict::const_iterator i, j;
  for (i=m_Dict->begin(); i!=m_Dict->end(); i++) {
    j=i;
    for (j++; j!= m_Dict->end(); j++) {
      if (i->ptr->GetName() == j->ptr->GetName())
        return false;
    }
  }
  return true;
}
References CIccDictEntry::GetName(), CIccTagDict::m_Dict, and CIccDictEntryPtr::ptr.
Referenced by CIccTagDict::Validate().
Cleanup()
void CIccTagDict::Cleanup () protected inherited
Name: CIccTagDict::Cleanup
Purpose: Detach from a pending IO object
{
  CIccNameValueDict::iterator i;
  for (i=m_Dict->begin(); i!=m_Dict->end(); i++) {
    if (i->ptr)
      delete i->ptr;
  }
  m_Dict->clear();
}
References CIccTagDict::m_Dict, and CIccDictEntryPtr::ptr.
Referenced by CIccTagDict::~CIccTagDict(), CIccTagDict::operator=(), and CIccTagDict::Read().
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
void CIccTagDict::Describe (std::string & sDescription, int nVerboseness) virtual inherited
Name: CIccTagDict::Describe
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icChar buf[128];
  sprintf(buf, "BEGIN DICT_TAG\n");
  sDescription += buf;
  CIccNameValueDict::iterator i;
  for (i=m_Dict->begin(); i!=m_Dict->end(); i++) {
    sDescription += "\n";
    i->ptr->Describe(sDescription, nVerboseness);
  }
  sprintf(buf, "\nEND DICT_TAG\n");
  sDescription += buf;
}
References CIccDictEntry::Describe(), CIccTagDict::m_Dict, and CIccDictEntryPtr::ptr.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
Get() [1/3]
CIccDictEntry * CIccTagDict::Get (const char * szName) const inherited
Name: CIccTagDict::Get
Purpose: Get a dictionary entry with a given name
Args: sName - name to find in dictionary
Return: Pointer to desired dictionary entry, or NULL if not found.
{
  std::wstring sName(szName, szName+strlen(szName));
  return Get(sName);
}
References CIccTagDict::Get().
Get() [2/3]
CIccDictEntry * CIccTagDict::Get (const icUInt16Number * szName) const inherited
Name: CIccTagDict::Get
Purpose: Get a dictionary entry with a given name
Args: sName - name to find in dictionary
Return: Pointer to desired dictionary entry, or NULL if not found.
{
  std::wstring sName;
  while(*szName)
    sName += *szName;
  return Get(sName);
}
References CIccTagDict::Get().
Get() [3/3]
CIccDictEntry * CIccTagDict::Get (std::wstring sName) const inherited
Name: CIccTagDict::Get
Purpose: Get a dictionary entry with a given name
Args: sName - name to find in dictionary
Return: Pointer to desired dictionary entry, or NULL if not found.
{
  CIccNameValueDict::const_iterator i;
  for (i=m_Dict->begin(); i!=m_Dict->end(); i++) {
    if (i->ptr->GetName() == sName)
      return i->ptr;
  }
  return NULL;
}
References CIccDictEntry::GetName(), CIccTagDict::m_Dict, and CIccDictEntryPtr::ptr.
Referenced by CIccTagDict::Get(), CIccTagDict::Get(), CIccTagDict::GetNameLocalized(), CIccTagDict::GetValue(), CIccTagDict::GetValueLocalized(), CIccTagDict::Set(), CIccTagDict::SetNameLocalized(), and CIccTagDict::SetValueLocalized().
GetClassName()
virtual const char * CIccTagXmlDict::GetClassName () const inline virtual
Reimplemented from CIccTagDict.
{return "CIccTagXmlDict"; }
GetExtClassName()
virtual const char * CIccTagXml::GetExtClassName () const inline virtual inherited
Implements IIccExtensionTag.
{ return "CIccTagXml"; }
Referenced by icProfDescToXml(), and icXmlParseProfDesc().
GetExtDerivedClassName()
virtual const char * CIccTagXml::GetExtDerivedClassName () const inline virtual inherited
Implements IIccExtensionTag.
Reimplemented in CIccCurveXml.
{ return ""; }
GetExtension()
virtual IIccExtensionTag * CIccTagXmlDict::GetExtension () inline virtual
Reimplemented from CIccTag.
{return this; }
GetNameLocalized() [1/3]
CIccTagMultiLocalizedUnicode * CIccTagDict::GetNameLocalized (const char * szName) const inherited
Name: CIccTagDict::GetNameLocalized
Purpose: Get a localized name information associated with a given name
Args: sName - name to find in dictionary
Return: localized information for name
{
  std::wstring sName(szName, szName+strlen(szName));
  return GetNameLocalized(sName);
}
References CIccTagDict::GetNameLocalized().
GetNameLocalized() [2/3]
CIccTagMultiLocalizedUnicode * CIccTagDict::GetNameLocalized (const icUnicodeChar * szName) const inherited
Name: CIccTagDict::GetNameLocalized
Purpose: Get a localized name information associated with a given name
Args: sName - name to find in dictionary
Return: localized information for name
{
  std::wstring sName;
  while(*szName)
    sName += *szName;
  return GetNameLocalized(sName);
}
References CIccTagDict::GetNameLocalized().
GetNameLocalized() [3/3]
CIccTagMultiLocalizedUnicode * CIccTagDict::GetNameLocalized (std::wstring sName) const inherited
Name: CIccTagDict::GetNameLocalized
Purpose: Get a localized name information associated with a given name
Args: sName - name to find in dictionary
Return: localized information for name
{
  CIccDictEntry *de = Get(sName);
  if (de)
    return de->GetNameLocalized();
  return NULL;
}
References CIccTagDict::Get(), and CIccDictEntry::GetNameLocalized().
Referenced by CIccTagDict::GetNameLocalized(), and CIccTagDict::GetNameLocalized().
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagDict::GetType () const inline virtual inherited
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigDictType; }
References icSigDictType.
Referenced by CIccTagDict::Write().
GetValue() [1/3]
std::wstring CIccTagDict::GetValue (const char * szName, bool * bIsSet = NULL) const inherited
Name: CIccTagDict::GetValue
Purpose: Get a value associated with a given name
Args: szName - name to find in dictionary
Return: Pointer to desired dictionary entry, or NULL if not found.
{
  std::wstring sName(szName, szName+strlen(szName));
  return GetValue(sName, bIsSet);
}
References CIccTagDict::GetValue().
GetValue() [2/3]
std::wstring CIccTagDict::GetValue (const icUnicodeChar * szName, bool * bIsSet = NULL) const inherited
Name: CIccTagDict::GetValue
Purpose: Get a value associated with a given name
Args: szName - name to find in dictionary
Return: Pointer to desired dictionary entry, or NULL if not found.
{
  std::wstring sName;
  while(*szName)
    sName += *szName;
  return GetValue(sName, bIsSet);
}
References CIccTagDict::GetValue().
GetValue() [3/3]
std::wstring CIccTagDict::GetValue (std::wstring sName, bool * bIsSet = NULL) const inherited
Name: CIccTagDict::GetValue
Purpose: Get a value associated with a given name
Args: sName - name to find in dictionary
Return: Pointer to desired dictionary entry, or NULL if not found.
{
  CIccDictEntry *de = Get(sName);
  if (de) {
    if (bIsSet)
      *bIsSet = de->IsValueSet();
    return de->GetValue();
  }
  if (bIsSet)
    *bIsSet = false;
  std::wstring str;
  return str;
}
References CIccTagDict::Get(), CIccDictEntry::GetValue(), and CIccDictEntry::IsValueSet().
Referenced by CIccTagDict::GetValue(), and CIccTagDict::GetValue().
GetValueLocalized() [1/3]
CIccTagMultiLocalizedUnicode * CIccTagDict::GetValueLocalized (const char * szName) const inherited
Name: CIccTagDict::GetValueLocalized
Purpose: Get a localized name information for value associated with a given name
Args: sName - name to find in dictionary
Return: localized information for name's value
{
  std::wstring sName(szName, szName+strlen(szName));
  return GetValueLocalized(sName);
}
References CIccTagDict::GetValueLocalized().
GetValueLocalized() [2/3]
CIccTagMultiLocalizedUnicode * CIccTagDict::GetValueLocalized (const icUnicodeChar * szName) const inherited
Name: CIccTagDict::GetValueLocalized
Purpose: Get a localized name information for value associated with a given name
Args: sName - name to find in dictionary
Return: localized information for name's value
{
  std::wstring sName;
  while(*szName)
    sName += *szName;
  return GetValueLocalized(sName);
}
References CIccTagDict::GetValueLocalized().
GetValueLocalized() [3/3]
CIccTagMultiLocalizedUnicode * CIccTagDict::GetValueLocalized (std::wstring sName) const inherited
Name: CIccTagDict::GetValueLocalized
Purpose: Get a localized name information for value associated with a given name
Args: sName - name to find in dictionary
Return: localized information for name's value
{
  CIccDictEntry *de = Get(sName);
  if (de)
    return de->GetValueLocalized();
  return NULL;
}
References CIccTagDict::Get(), and CIccDictEntry::GetValueLocalized().
Referenced by CIccTagDict::GetValueLocalized(), and CIccTagDict::GetValueLocalized().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccTagStruct::GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
MaxPosRecSize()
icUInt32Number CIccTagDict::MaxPosRecSize () protected inherited
Name: CIccTagDict::MaxPosRecSize;
Purpose:
Args:
Return:
{
  icUInt32Number rv = 16;
  CIccNameValueDict::iterator i;
  CIccDictEntry ptr;
  for (i=m_Dict->begin(); i!=m_Dict->end(); i++) {
    if (i->ptr->PosRecSize() > rv)
      rv = i->ptr->PosRecSize();
  }
  return rv;
}
References CIccTagDict::m_Dict, CIccDictEntry::PosRecSize(), and CIccDictEntryPtr::ptr.
Referenced by CIccTagDict::Write().
NewCopy()
virtual CIccTag * CIccTagDict::NewCopy () const inline virtual inherited
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
{ return new CIccTagDict(*this);}
References CIccTagDict::CIccTagDict().
ParseXml()
bool CIccTagXmlDict::ParseXml (xmlNode * pNode, std::string & parseStr) virtual
Implements CIccTagXml.
{
  m_Dict->clear();
  for (pNode = icXmlFindNode(pNode, "DictEntry"); pNode; pNode = icXmlFindNode(pNode->next, "DictEntry")) {
    CIccDictEntryPtr ptr;
    CIccDictEntry *pDesc = new CIccDictEntry();
    xmlAttr *pAttr;
    CIccUTF16String str;
    if (!pDesc)
      return false;
    ptr.ptr = pDesc;
    str = icXmlAttrValue(pNode, "Name", "");
    str.ToWString(pDesc->GetName());
    pAttr = icXmlFindAttr(pNode, "Value");
    if (pAttr) {
      std::wstring wstr;
      str = icXmlAttrValue(pAttr, "");
      str.ToWString(wstr);
      pDesc->SetValue(wstr);
    }
    xmlNode *pChild;
    for (pChild = pNode->children; pChild; pChild = pChild->next) {
      if (pChild->type == XML_ELEMENT_NODE && !icXmlStrCmp(pChild->name, "LocalizedName")) {
        CIccTagMultiLocalizedUnicode *pTag = pDesc->GetNameLocalized();
        if (!pTag) {
          pTag = new CIccTagMultiLocalizedUnicode();
          pDesc->SetNameLocalized(pTag);
        }
        if ((pAttr = icXmlFindAttr(pChild, "LanguageCountry")) && pChild->children) {
          xmlNode *pText;
          icUInt32Number lc = icGetSigVal(icXmlAttrValue(pAttr));
          for (pText = pChild->children; pText && pText->type != XML_TEXT_NODE && pText->type != XML_CDATA_SECTION_NODE; pText = pText->next);
          if (pText) {
            CIccUTF16String str((const char*)pText->content);
            pTag->SetText(str.c_str(), (icLanguageCode)(lc>>16), (icCountryCode)(lc & 0xffff));
          }
          else {
            pTag->SetText("");
          }
        }
      }
      else if (pChild->type == XML_ELEMENT_NODE && !icXmlStrCmp(pChild->name, "LocalizedValue")) {
        CIccTagMultiLocalizedUnicode *pTag = pDesc->GetValueLocalized();
        if (!pTag) {
          pTag = new CIccTagMultiLocalizedUnicode();
          pDesc->SetValueLocalized(pTag);
        }
        if ((pAttr = icXmlFindAttr(pChild, "LanguageCountry")) && pChild->children) {
          xmlNode *pText;
          icUInt32Number lc = icGetSigVal(icXmlAttrValue(pAttr));
          for (pText = pChild->children; pText && pText->type != XML_TEXT_NODE && pText->type != XML_CDATA_SECTION_NODE; pText = pText->next);
          if (pText) {
            CIccUTF16String str((const char*)pText->content);
            pTag->SetText(str.c_str(), (icLanguageCode)(lc>>16), (icCountryCode)(lc & 0xffff));
          }
          else {
            pTag->SetText("");
          }
        }
      }
    }
    m_Dict->push_back(ptr);
  }
  return true;
}
References CIccDictEntry::CIccDictEntry(), CIccTagMultiLocalizedUnicode::CIccTagMultiLocalizedUnicode(), CIccUTF16String::CIccUTF16String(), CIccUTF16String::c_str(), CIccDictEntry::GetName(), CIccDictEntry::GetNameLocalized(), CIccDictEntry::GetValueLocalized(), icGetSigVal(), icXmlAttrValue(), icXmlAttrValue(), icXmlFindAttr(), icXmlFindNode(), CIccTagDict::m_Dict, CIccUTF16String::operator=(), CIccDictEntryPtr::ptr, CIccDictEntry::SetNameLocalized(), CIccTagMultiLocalizedUnicode::SetText(), CIccTagMultiLocalizedUnicode::SetText(), CIccDictEntry::SetValue(), CIccDictEntry::SetValueLocalized(), and CIccUTF16String::ToWString().
Read() [1/2]
bool CIccTagDict::Read (icUInt32Number size, CIccIO * pIO) virtual inherited
Name: CIccTagDict::Read
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  m_tagSize = size;
  icUInt32Number headerSize = sizeof(icTagTypeSignature) +
    sizeof(icUInt32Number) +
    sizeof(icUInt32Number) +
    sizeof(icUInt32Number);
  if (headerSize > size)
    return false;
  if (!pIO) {
    return false;
  }
  Cleanup();
  m_tagStart = pIO->Tell();
  if (!pIO->Read32(&sig))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  icUInt32Number count, reclen, i;
  if (!pIO->Read32(&count))
    return false;
  if (!pIO->Read32(&reclen))
    return false;
  if (reclen!=16 && reclen!=24 && reclen!=32)
    return false;
  if (headerSize + count*reclen > size)
    return false;
  icDictRecordPos *pos = (icDictRecordPos*)calloc(count, sizeof(icDictRecordPos));
  if (!pos)
    return false;
  //Read TagDir
  for (i=0; i<count; i++) {
    if (!pIO->Read32(&pos[i].posName.offset) ||
        !pIO->Read32(&pos[i].posName.size) ||
        !pIO->Read32(&pos[i].posValue.offset) ||
        !pIO->Read32(&pos[i].posValue.size)) {
      free(pos);
      return false;
    }
    if (reclen>=24) {
      if (!pIO->Read32(&pos[i].posNameLocalized.offset) ||
          !pIO->Read32(&pos[i].posNameLocalized.size)) {
        free(pos);
        return false;
      }
      if (reclen>=32) {
        if (!pIO->Read32(&pos[i].posValueLocalized.offset) ||
            !pIO->Read32(&pos[i].posValueLocalized.size)) {
          free(pos);
          return false;
        }
      }
    }
    if ((pos[i].posName.offset & 0x3) ||
        (pos[i].posValue.offset & 0x3) ||
        (pos[i].posNameLocalized.offset & 0x3) ||
        (pos[i].posValueLocalized.offset & 0x3))
      m_bBadAlignment = true;
  }
  icUInt32Number bufsize = 128, num;
  icUnicodeChar *buf = (icUnicodeChar*)malloc(bufsize);
  CIccDictEntryPtr ptr = {};
  std::wstring str;
  for (i=0; i<count; i++) {
    ptr.ptr = new CIccDictEntry();
    if (!ptr.ptr)
      return false;
    //GetName
    if (pos[i].posName.offset) {
      if (!pos[i].posName.size) {
        str.clear();
        ptr.ptr->SetValue(str);
      }
      else {
        if (pos[i].posName.offset + pos[i].posName.size >size ||
            !pos[i].posName.size) {
          free(pos);
          free(buf);
          delete ptr.ptr;
          return false;
        }
        //Make sure we have buf large enough for the string
        if (bufsize < pos[i].posName.size) {
          bufsize = pos[i].posName.size;
          buf = (icUnicodeChar*)icRealloc(buf, bufsize);
          if (!buf) {
            free(pos);
            delete ptr.ptr;
            return false;
          }
        }
        if (pIO->Seek(m_tagStart+pos[i].posName.offset, icSeekSet)<0) {
          free(pos);
          free(buf);
          delete ptr.ptr;
          return false;
        }
        num = pos[i].posName.size / sizeof(icUnicodeChar);
        if (pIO->Read16(buf, num)!=(icInt32Number)num) {
          free(pos);
          free(buf);
          delete ptr.ptr;
          return false;
        }
        str.assign(&buf[0], &buf[num]);
        ptr.ptr->GetName() = str;
      }
    }
    //GetValue
    if (pos[i].posValue.offset) {
      if (!pos[i].posValue.size) {
        str.clear();
        ptr.ptr->SetValue(str);
      }
      else {
        if (pos[i].posValue.offset + pos[i].posValue.size >size ||
            (pos[i].posValue.size&1)) {
            free(pos);
            free(buf);
            delete ptr.ptr;
            return false;
        }
        //Make sure we have buf large enough for the string
        if (bufsize < pos[i].posValue.size) {
          bufsize = pos[i].posValue.size;
          buf = (icUnicodeChar*)icRealloc(buf, bufsize);
          if (!buf) {
            free(pos);
            delete ptr.ptr;
            return false;
          }
        }
        if (pIO->Seek(m_tagStart+pos[i].posValue.offset, icSeekSet)<0) {
          free(pos);
          free(buf);
          delete ptr.ptr;
          return false;
        }
        num = pos[i].posValue.size / sizeof(icUnicodeChar);
        if (pIO->Read16(buf, num)!=(icInt32Number)num) {
          free(pos);
          free(buf);
          delete ptr.ptr;
          return false;
        }
        str.assign(&buf[0], &buf[num]);
        ptr.ptr->SetValue(str);
      }
    }
    //Get NameLocalized
    if (pos[i].posNameLocalized.offset) {
      if (pos[i].posNameLocalized.offset + pos[i].posNameLocalized.size > size ||
          pos[i].posNameLocalized.size < sizeof(icSignature)) {
        free(pos);
        free(buf);
        delete ptr.ptr;
        return false;
      }
      if (pIO->Seek(m_tagStart+pos[i].posNameLocalized.offset, icSeekSet)<0) {
        free(pos);
        free(buf);
        delete ptr.ptr;
        return false;
      }
      icTagTypeSignature textSig = (icTagTypeSignature)0;
      if (!pIO->Read32(&textSig, 1)) {
        free(pos);
        free(buf);
        delete ptr.ptr;
        return false;
      }
      if (textSig != icSigMultiLocalizedUnicodeType) {
        free(pos);
        free(buf);
        delete ptr.ptr;
        return false;
      }
      if (pIO->Seek(m_tagStart+pos[i].posNameLocalized.offset, icSeekSet)<0) {
        free(pos);
        free(buf);
        delete ptr.ptr;
        return false;
      }
      CIccTagMultiLocalizedUnicode *pTag = new CIccTagMultiLocalizedUnicode();
      if (!pTag || !pTag->Read(pos[i].posNameLocalized.size, pIO)) {
        free(pos);
        free(buf);
        delete ptr.ptr;
        return false;
      }
      ptr.ptr->SetNameLocalized(pTag);
    }
    //Get ValueLocalized
    if (pos[i].posValueLocalized.offset) {
      if (pos[i].posValueLocalized.offset + pos[i].posValueLocalized.size > size ||
        pos[i].posValueLocalized.size < sizeof(icSignature)) {
          free(pos);
          free(buf);
          delete ptr.ptr;
          return false;
      }
      if (pIO->Seek(m_tagStart+pos[i].posValueLocalized.offset, icSeekSet)<0) {
        free(pos);
        free(buf);
        delete ptr.ptr;
        return false;
      }
      icTagTypeSignature textSig = (icTagTypeSignature)0;
      if (!pIO->Read32(&textSig, 1)) {
        free(pos);
        free(buf);
        delete ptr.ptr;
        return false;
      }
      if (textSig != icSigMultiLocalizedUnicodeType) {
        free(pos);
        free(buf);
        delete ptr.ptr;
        return false;
      }
      if (pIO->Seek(m_tagStart+pos[i].posValueLocalized.offset, icSeekSet)<0) {
        free(pos);
        free(buf);
        delete ptr.ptr;
        return false;
      }
      CIccTagMultiLocalizedUnicode *pTag = new CIccTagMultiLocalizedUnicode();
      if (!pTag || !pTag->Read(pos[i].posValueLocalized.size, pIO)) {
        free(pos);
        free(buf);
        delete ptr.ptr;
        return false;
      }
      ptr.ptr->SetValueLocalized(pTag);
    }
    m_Dict->push_back(ptr);
  }
  free(pos);
  free(buf);
  return true;
}
References CIccDictEntry::CIccDictEntry(), CIccTagMultiLocalizedUnicode::CIccTagMultiLocalizedUnicode(), CIccTagDict::Cleanup(), CIccDictEntry::GetName(), icRealloc(), icSeekSet, icSigMultiLocalizedUnicodeType, CIccTagDict::m_bBadAlignment, CIccTagDict::m_Dict, CIccTag::m_nReserved, CIccTagDict::m_tagSize, CIccTagDict::m_tagStart, icPositionNumber::offset, icDictRecordPos::posName, icDictRecordPos::posNameLocalized, icDictRecordPos::posValue, icDictRecordPos::posValueLocalized, CIccDictEntryPtr::ptr, CIccTagMultiLocalizedUnicode::Read(), CIccIO::Read16(), CIccIO::Read32(), CIccIO::Seek(), CIccDictEntry::SetNameLocalized(), CIccDictEntry::SetValue(), CIccDictEntry::SetValueLocalized(), icPositionNumber::size, and CIccIO::Tell().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
Remove() [1/3]
bool CIccTagDict::Remove (const char * szName) inherited
Name: CIccTagDict::Remove
Purpose: Remove a name value pair from the dictionary
Args: sName = the name to look for in the dictionary
Return: true if sName exists and was remove , or false otherwise
{
  std::wstring sName(szName, szName+strlen(szName));
  return Remove(sName);
}
References CIccTagDict::Remove().
Remove() [2/3]
bool CIccTagDict::Remove (const icUnicodeChar * szName) inherited
Name: CIccTagDict::Remove
Purpose: Remove a name value pair from the dictionary
Args: sName = the name to look for in the dictionary
Return: true if sName exists and was remove , or false otherwise
{
  std::wstring sName;
  while(*szName)
    sName += *szName;
  return Remove(sName);
}
References CIccTagDict::Remove().
Remove() [3/3]
bool CIccTagDict::Remove (std::wstring sName) inherited
Name: CIccTagDict::Remove
Purpose: Remove a name value pair from the dictionary
Args: sName = the name to look for in the dictionary
Return: true if sName exists and was removed, or false otherwise
{
  CIccNameValueDict::iterator i;
  for (i=m_Dict->begin(); i!=m_Dict->end(); i++) {
    if (i->ptr->GetName() == sName) {
      delete i->ptr;
      m_Dict->erase(i);
      return true;
    }
  }
  return false;
}
References CIccDictEntry::GetName(), CIccTagDict::m_Dict, and CIccDictEntryPtr::ptr.
Referenced by CIccTagDict::Remove(), and CIccTagDict::Remove().
Set() [1/3]
bool CIccTagDict::Set (const char * szName, const char * szValue = NULL) inherited
{
  std::wstring sName(szName, szName+strlen(szName));
  std::wstring sValue;
  if (szValue) {
    sValue.assign(szValue, szValue+strlen(szValue));
    return Set(sName, sValue, false);
  }
  return Set(sName, sValue, true);
}
References CIccTagDict::Set().
Set() [2/3]
bool CIccTagDict::Set (const icUnicodeChar * szName, const icUnicodeChar * szValue = NULL) inherited
{
  std::wstring sName;
  while(*szName)
    sName += *szName;
  std::wstring sValue;
  if (szValue) {
    while(*szValue)
      sValue += *szValue;
    return Set(sName, sValue, false);
  }
  return Set(sName, sValue, true);
}
References CIccTagDict::Set().
Set() [3/3]
bool CIccTagDict::Set (std::wstring sName, std::wstring sValue, bool bUnSet = false) inherited
Name: CIccTagDict::Set
Purpose: Associate a value with a name in the dictionary
Args: sName = the name to look for in the dictionary sValue = value to associate with sName bUnset = flag to indicate that value has not been set (no data for value in tag)
Return: true if value associate with sName was changed, or false if no change
{
  CIccDictEntry *de = Get(sName);
  if (de) {
    if (de->GetValue()==sValue && de->IsValueSet() && !bUnSet)
      return false;
  }
  else {
    de = new CIccDictEntry;
    de->GetName() = sName;
    CIccDictEntryPtr ptr = {};
    ptr.ptr = de;
    m_Dict->push_back(ptr);
  }
  if (sValue.empty() && bUnSet)
    de->UnsetValue();
  else
    de->SetValue(sValue);
  return true;
}
References CIccTagDict::Get(), CIccDictEntry::GetName(), CIccDictEntry::GetValue(), CIccDictEntry::IsValueSet(), CIccTagDict::m_Dict, CIccDictEntryPtr::ptr, CIccDictEntry::SetValue(), and CIccDictEntry::UnsetValue().
Referenced by CIccTagDict::Set(), and CIccTagDict::Set().
SetNameLocalized() [1/3]
bool CIccTagDict::SetNameLocalized (const char * szName, CIccTagMultiLocalizedUnicode * pTag) inherited
{
  std::wstring sName;
  while(*szName)
    sName += *szName++;
  return SetNameLocalized(sName, pTag);
}
References CIccTagDict::SetNameLocalized().
SetNameLocalized() [2/3]
bool CIccTagDict::SetNameLocalized (const icUnicodeChar * szName, CIccTagMultiLocalizedUnicode * pTag) inherited
{
  std::wstring sName;
  while(*szName)
    sName += *szName++;
  return SetNameLocalized(sName, pTag);
}
References CIccTagDict::SetNameLocalized().
SetNameLocalized() [3/3]
bool CIccTagDict::SetNameLocalized (std::wstring sName, CIccTagMultiLocalizedUnicode * pTag) inherited
{
  CIccDictEntry *de = Get(sName);
  if (!de) {
    de = new CIccDictEntry;
    de->GetName() = sName;
    CIccDictEntryPtr ptr = {};
    ptr.ptr = de;
    m_Dict->push_back(ptr);
  }
  return de->SetNameLocalized(pTag);
}
References CIccTagDict::Get(), CIccDictEntry::GetName(), CIccTagDict::m_Dict, CIccDictEntryPtr::ptr, and CIccDictEntry::SetNameLocalized().
Referenced by CIccTagDict::SetNameLocalized(), and CIccTagDict::SetNameLocalized().
SetValueLocalized() [1/3]
bool CIccTagDict::SetValueLocalized (const char * szName, CIccTagMultiLocalizedUnicode * pTag) inherited
{
  std::wstring sName(szName, szName+strlen(szName));
  return SetValueLocalized(sName, pTag);
}
References CIccTagDict::SetValueLocalized().
SetValueLocalized() [2/3]
bool CIccTagDict::SetValueLocalized (const icUnicodeChar * szName, CIccTagMultiLocalizedUnicode * pTag) inherited
{
  std::wstring sName;
  while(*szName)
    sName += *szName++;
  return SetValueLocalized(sName, pTag);
}
References CIccTagDict::SetValueLocalized().
SetValueLocalized() [3/3]
bool CIccTagDict::SetValueLocalized (std::wstring sName, CIccTagMultiLocalizedUnicode * pTag) inherited
{
  CIccDictEntry *de = Get(sName);
  if (!de) {
    de = new CIccDictEntry;
    de->GetName() = sName;
    CIccDictEntryPtr ptr = {};
    ptr.ptr = de;
    m_Dict->push_back(ptr);
  }
  return de->SetValueLocalized(pTag);
}
References CIccTagDict::Get(), CIccDictEntry::GetName(), CIccTagDict::m_Dict, CIccDictEntryPtr::ptr, and CIccDictEntry::SetValueLocalized().
Referenced by CIccTagDict::SetValueLocalized(), and CIccTagDict::SetValueLocalized().
ToXml()
bool CIccTagXmlDict::ToXml (std::string & xml, std::string blanks = "") virtual
Implements CIccTagXml.
{
  std::string info;
  CIccNameValueDict::iterator nvp;
  for (nvp=m_Dict->begin(); nvp!=m_Dict->end(); nvp++) {
    CIccDictEntry *nv = nvp->ptr;
    if (!nv)
      continue;
    char buf[256];
    char data[256];
    char fix[256];
    std::string bufstr;
    xml += blanks + " <DictEntry Name=\"";
    xml += icFixXml(fix, icUtf16ToUtf8(bufstr, (icUInt16Number*)nv->GetName().c_str(), (int)nv->GetName().size()));
    xml += "\"";
    if (nv->IsValueSet()) {
      xml += " Value=\"";
      xml += icFixXml(fix, icUtf16ToUtf8(bufstr, (icUInt16Number*)nv->GetValue().c_str(), (int)nv->GetValue().size()));
      xml += "\"";
    }
    if (!nv->GetNameLocalized() && !nv->GetValueLocalized()) {
      xml += "/>\n";
    }
    else {
      xml += ">\n";
      if (nv->GetNameLocalized()) {
        CIccMultiLocalizedUnicode::iterator i;
        for (i=nv->GetNameLocalized()->m_Strings->begin(); i!=nv->GetNameLocalized()->m_Strings->end(); i++) {
          sprintf(buf, "  <LocalizedName LanguageCountry=\"%s\"", icFixXml(fix, icGetSigStr(data, (i->m_nLanguageCode<<16) + i->m_nCountryCode)));
          xml += blanks + buf;
          sprintf(buf, "><![CDATA[%s]]></LocalizedName>\n", icFixXml(fix, icUtf16ToUtf8(bufstr, i->GetBuf(), i->GetLength())));
          xml += buf;
        }
      }
      if (nv->GetValueLocalized()) {
        CIccMultiLocalizedUnicode::iterator i;
        for (i=nv->GetValueLocalized()->m_Strings->begin(); i!=nv->GetValueLocalized()->m_Strings->end(); i++) {
          sprintf(buf, "  <LocalizedValue LanguageCountry=\"%s\"", icFixXml(fix, icGetSigStr(data, (i->m_nLanguageCode<<16) + i->m_nCountryCode)));
          xml += blanks + buf;
          sprintf(buf, "><![CDATA[%s]]></LocalizedValue>\n", icFixXml(fix, icUtf16ToUtf8(bufstr, i->GetBuf(), i->GetLength())));
          xml += buf;
        }
      }
      xml += blanks + " </DictEntry>\n";
    }
  }
  return true;
}
References CIccLocalizedUnicode::GetBuf(), CIccLocalizedUnicode::GetLength(), CIccDictEntry::GetName(), CIccDictEntry::GetNameLocalized(), CIccDictEntry::GetValue(), CIccDictEntry::GetValueLocalized(), icFixXml(), icGetSigStr(), icUtf16ToUtf8(), CIccDictEntry::IsValueSet(), CIccTagDict::m_Dict, CIccLocalizedUnicode::m_nCountryCode, CIccLocalizedUnicode::m_nLanguageCode, CIccTagMultiLocalizedUnicode::m_Strings, and CIccDictEntryPtr::ptr.
Validate()
icValidateStatus CIccTagDict::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual inherited
Name: CIccTagDict::Validate
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  // Check for duplicate tags
  if (!AreNamesUnique()) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " - There are duplicate names.\n";
    rv =icMaxStatus(rv, icValidateWarning);
  }
  if (!AreNamesNonzero()) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " - There zero-length names.\n";
    rv =icMaxStatus(rv, icValidateWarning);
  }
  // Check for duplicate tags
  if (m_bBadAlignment) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " - Some Data elements are not aligned correctly\n";
    rv =icMaxStatus(rv, icValidateWarning);
  }
  return rv;
}
References CIccTagDict::AreNamesNonzero(), CIccTagDict::AreNamesUnique(), CIccInfo::GetSigPathName(), icMaxStatus(), icMsgValidateWarning, icValidateWarning, CIccTagDict::m_bBadAlignment, and CIccTag::Validate().
Write()
bool CIccTagDict::Write (CIccIO * pIO) virtual inherited
Name: CIccTagDict::Write
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  if (!pIO)
    return false;
  m_tagStart = pIO->Tell();
  if (!pIO->Write32(&sig))
    return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  CIccNameValueDict::iterator i, j;
  icUInt32Number count;
  icUInt8Number zbuf[32];
  memset(zbuf, 0, 32);
  for (count=0, i=m_Dict->begin(); i!= m_Dict->end(); i++) {
    if (i->ptr)
      count++;
  }
  pIO->Write32(&count);
  icUInt32Number recSize = MaxPosRecSize();
  pIO->Write32(&recSize);
  icDictRecordPos *pos = (icDictRecordPos*)calloc(count, sizeof(icDictRecordPos));
  if (!pos)
    return false;
  icUInt32Number n, dirpos = pIO->Tell();
  //Write Unintialized Dict rec offset array
  for (i=m_Dict->begin(); i!= m_Dict->end(); i++) {
    if (i->ptr) {
      pIO->Write8(zbuf, recSize);
    }
  }
  icUnicodeChar c;
  std::wstring::const_iterator chrptr;
  //Write Dict records
  for (n=0, i=m_Dict->begin(); i!= m_Dict->end(); i++) {
    if (i->ptr) {
      pos[n].posName.offset = pIO->Tell()-m_tagStart;
      for(chrptr = i->ptr->GetName().begin(); chrptr!=i->ptr->GetName().end(); chrptr++) {
        c=(icUnicodeChar)*chrptr;
        pIO->Write16(&c, 1);
      }
      pos[n].posName.size = pIO->Tell()-m_tagStart - pos[n].posName.offset;
      pIO->Align32();
      if (i->ptr->IsValueSet()) {
        pos[n].posValue.offset = pIO->Tell()-m_tagStart;
        for(chrptr = i->ptr->ValueBegin(); chrptr!=i->ptr->ValueEnd(); chrptr++) {
          c=(icUnicodeChar)*chrptr;
          pIO->Write16(&c, 1);
        }
        pos[n].posValue.size = pIO->Tell()-m_tagStart - pos[n].posValue.offset;
        pIO->Align32();
      }
      if (recSize>16 && i->ptr->GetNameLocalized()) {
        pos[n].posNameLocalized.offset = pIO->Tell()-m_tagStart;
        i->ptr->GetNameLocalized()->Write(pIO);
        pos[n].posNameLocalized.size = pIO->Tell()-m_tagStart - pos[n].posNameLocalized.offset;
        pIO->Align32();
      }
      if (recSize>24 && i->ptr->GetValueLocalized()) {
        pos[n].posValueLocalized.offset = pIO->Tell()-m_tagStart;
        i->ptr->GetValueLocalized()->Write(pIO);
        pos[n].posValueLocalized.size = pIO->Tell()-m_tagStart - pos[n].posValueLocalized.offset;
        pIO->Align32();
      }
      n++;
    }
  }
  icUInt32Number endpos = pIO->Tell();
  pIO->Seek(dirpos, icSeekSet);
  //Write TagDir with offsets and sizes
  for (n=0, i=m_Dict->begin(); i!= m_Dict->end(); i++) {
    if (i->ptr) {
      pIO->Write32(&pos[n].posName.offset);
      pIO->Write32(&pos[n].posName.size);
      pIO->Write32(&pos[n].posValue.offset);
      pIO->Write32(&pos[n].posValue.size);
      if (recSize>16) {
        pIO->Write32(&pos[n].posNameLocalized.offset);
        pIO->Write32(&pos[n].posNameLocalized.size);
        if (recSize>24) {
          pIO->Write32(&pos[n].posValueLocalized.offset);
          pIO->Write32(&pos[n].posValueLocalized.size);
        }
      }
    }
    n++;
  }
  pIO->Seek(endpos, icSeekSet);
  free(pos);
  return true;
}
References CIccIO::Align32(), CIccDictEntry::GetName(), CIccDictEntry::GetNameLocalized(), CIccTagDict::GetType(), CIccDictEntry::GetValueLocalized(), icSeekSet, CIccDictEntry::IsValueSet(), CIccTagDict::m_Dict, CIccTag::m_nReserved, CIccTagDict::m_tagStart, CIccTagDict::MaxPosRecSize(), icPositionNumber::offset, icDictRecordPos::posName, icDictRecordPos::posNameLocalized, icDictRecordPos::posValue, icDictRecordPos::posValueLocalized, CIccDictEntryPtr::ptr, CIccIO::Seek(), icPositionNumber::size, CIccIO::Tell(), CIccDictEntry::ValueBegin(), CIccDictEntry::ValueEnd(), CIccTagMultiLocalizedUnicode::Write(), CIccIO::Write16(), CIccIO::Write32(), and CIccIO::Write8().
Field Documentation
m_bBadAlignment
bool CIccTagDict::m_bBadAlignment protected inherited
Referenced by CIccTagDict::CIccTagDict(), CIccTagDict::CIccTagDict(), CIccTagDict::Read(), and CIccTagDict::Validate().
m_Dict
CIccNameValueDict* CIccTagDict::m_Dict inherited
Referenced by CIccTagDict::CIccTagDict(), CIccTagDict::CIccTagDict(), CIccTagDict::~CIccTagDict(), CIccTagDict::AreNamesNonzero(), CIccTagDict::AreNamesUnique(), CIccTagDict::Cleanup(), CIccTagDict::Describe(), CIccTagDict::Get(), CIccTagDict::MaxPosRecSize(), CIccTagDict::operator=(), ParseXml(), CIccTagDict::Read(), CIccTagDict::Remove(), CIccTagDict::Set(), CIccTagDict::SetNameLocalized(), CIccTagDict::SetValueLocalized(), ToXml(), and CIccTagDict::Write().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_tagSize
icUInt32Number CIccTagDict::m_tagSize protected inherited
Referenced by CIccTagDict::CIccTagDict(), CIccTagDict::CIccTagDict(), and CIccTagDict::Read().
m_tagStart
icUInt32Number CIccTagDict::m_tagStart protected inherited
Referenced by CIccTagDict::CIccTagDict(), CIccTagDict::CIccTagDict(), CIccTagDict::Read(), and CIccTagDict::Write().
The documentation for this class was generated from the following files:
IccXML/IccLibXML/IccTagXml.h
IccXML/IccLibXML/IccTagXml.cpp