iccDEV: CIccLocalizedUnicode Class Reference
CIccLocalizedUnicode Class Reference
#include <IccTagBasic.h>
Public Member Functions
CIccLocalizedUnicode ()
CIccLocalizedUnicode (const CIccLocalizedUnicode &ILU)
virtual ~CIccLocalizedUnicode ()
icUInt16Number * GetBuf () const
icUInt32Number GetLength () const
bool GetText (std::string &text)
const icChar * GetUtf8 (icChar *szBuf, icUInt32Number nBufSize)
icUInt32Number GetUtf8Size ()
CIccLocalizedUnicode & operator= (const CIccLocalizedUnicode &UnicodeText)
const icChar * operator= (const icChar *szText)
const icUInt16Number * operator= (const icUInt16Number *sszText)
const icUInt32Number * operator= (const icUInt32Number *sszText)
bool SetSize (icUInt32Number)
bool SetText (const icChar *szText, icLanguageCode nLanguageCode=icLanguageCodeEnglish, icCountryCode nRegionCode=icCountryCodeUSA)
bool SetText (const icUInt16Number *sszUnicode16Text, icLanguageCode nLanguageCode=icLanguageCodeEnglish, icCountryCode nRegionCode=icCountryCodeUSA)
bool SetText (const icUInt32Number *sszUnicode32Text, icLanguageCode nLanguageCode=icLanguageCodeEnglish, icCountryCode nRegionCode=icCountryCodeUSA)
Data Fields
icCountryCode m_nCountryCode
icLanguageCode m_nLanguageCode
Protected Attributes
icUInt32Number m_nLength
icUInt16Number * m_pBuf
Detailed Description
Data Class: CIccLocalizedUnicode
Purpose: Implementation of a unicode string with language and region identifiers.
Constructor & Destructor Documentation
CIccLocalizedUnicode() [1/2]
CIccLocalizedUnicode::CIccLocalizedUnicode ()
Name: CIccLocalizedUnicode::CIccLocalizedUnicode
Purpose: Constructor
{
  m_pBuf = (icUInt16Number*)malloc(1*sizeof(icUInt16Number));
  *m_pBuf = 0;
  m_nLength = 0;
}
References m_nLength, and m_pBuf.
CIccLocalizedUnicode() [2/2]
CIccLocalizedUnicode::CIccLocalizedUnicode (const CIccLocalizedUnicode & ILU)
Name: CIccLocalizedUnicode::CIccLocalizedUnicode
Purpose: Copy Constructor
Args: ILU = The CIccLocalizedUnicode object to be copied
{
  m_nLength = ILU.GetLength();
  m_pBuf = (icUInt16Number*)malloc((m_nLength+1) * sizeof(icUInt16Number));
  if (m_nLength)
    memcpy(m_pBuf, ILU.GetBuf(), m_nLength*sizeof(icUInt16Number));
  m_pBuf[m_nLength] = 0;
  m_nLanguageCode = ILU.m_nLanguageCode;
  m_nCountryCode = ILU.m_nCountryCode;
}
References GetBuf(), GetLength(), m_nCountryCode, m_nLanguageCode, m_nLength, and m_pBuf.
~CIccLocalizedUnicode()
CIccLocalizedUnicode::~CIccLocalizedUnicode () virtual
Name: CIccLocalizedUnicode::~CIccLocalizedUnicode
Purpose: Destructor
{
  if (m_pBuf)
    free(m_pBuf);
}
References m_pBuf.
Member Function Documentation
GetBuf()
icUInt16Number * CIccLocalizedUnicode::GetBuf () const inline
{ return m_pBuf; }
References m_pBuf.
Referenced by CIccLocalizedUnicode(), operator=(), CIccTagMultiLocalizedUnicode::Read(), CIccTagXmlMultiLocalizedUnicode::ToXml(), CIccTagXmlProfileSequenceId::ToXml(), CIccTagXmlDict::ToXml(), and CIccTagMultiLocalizedUnicode::Write().
GetLength()
icUInt32Number CIccLocalizedUnicode::GetLength () const inline
{ return m_nLength; }
References m_nLength.
Referenced by CIccLocalizedUnicode(), operator=(), CIccTagXmlMultiLocalizedUnicode::ToXml(), CIccTagXmlProfileSequenceId::ToXml(), CIccTagXmlDict::ToXml(), and CIccTagMultiLocalizedUnicode::Write().
GetText()
bool CIccLocalizedUnicode::GetText (std::string & sText)
Name: CIccLocalizedUnicode::GetText
Purpose: Gets text as a UTF-8 string
Args: sText - string to put results in
{
  sText.clear();
  icUInt16Number* str = m_pBuf;
  while (*str) {
    icUInt32Number code32 = 0x0;
    //UTF-16 to UTF-32
    if (*str <= 0xD7FF) {
      code32 = *str;
      str++;
    }
    else if (*str <= 0xDBFF) {
      icUInt16Number high = (*str - 0xD800) * 0x400;
      icUInt16Number low = *(str + 1) - 0xDC00;
      code32 = (low | high) + 0x10000;
      str += 2;
    }
    //UTF-32 to UTF-8 -------
    if (code32 <= 0x007F) {
      sText += (unsigned char)code32;
    }
    else if (code32 <= 0x07FF) {
      sText += (unsigned char)(((code32 >> 6) & 0x1F) | 0xC0);
      sText += (unsigned char)((code32 & 0x3F) | 0x80);
    }
    else if (code32 <= 0xFFFF) {
      sText += (unsigned char)(((code32 >> 12) & 0x0F) | 0xE0);
      sText += (unsigned char)(((code32 >> 6) & 0x3F) | 0x80);
      sText += (unsigned char)(((code32) & 0x3F) | 0x80);
    }
    else if (code32 <= 0x10FFFF) {
      sText += (unsigned char)(((code32 >> 18) & 0x07) | 0xF0);
      sText += (unsigned char)(((code32 >> 12) & 0x3F) | 0x80);
      sText += (unsigned char)(((code32 >> 6) & 0x3F) | 0x80);
      sText += (unsigned char)(((code32) & 0x3F) | 0x80);
    }
  }
  return true;
}
References m_pBuf.
Referenced by CIccTagMultiLocalizedUnicode::Describe(), GetUtf8(), GetUtf8Size(), icGetTagText(), and main().
GetUtf8()
const icChar * CIccLocalizedUnicode::GetUtf8 (icChar * szBuf, icUInt32Number nBufSize)
Name: CIccLocalizedUnicode::GetUtf8
Purpose: Extracts the ANSI data buffer (from UTF-16BE)
Args: szBuf = pointer where the returned string buffer is to be stored nBufSize = size of the buffer to be extracted
Return: Pointer to the ANSI data string
{
  if (!szBuf || !nBufSize)
    return NULL;
  std::string str;
  GetText(str);
  if (nBufSize - 1 < str.size()) {
    memcpy(szBuf, str.c_str(), nBufSize - 1);
    szBuf[nBufSize] = 0;
  }
  else {
    strcpy(szBuf, str.c_str());
  }
  return szBuf;
}
References GetText().
GetUtf8Size()
icUInt32Number CIccLocalizedUnicode::GetUtf8Size ()
Name: CIccLocalizedUnicode::GetUtf8Size
Purpose: Returns the size of the ANSI data buffer
{
  std::string str;
  GetText(str);
  return (icUInt32Number)str.size()+1;
}
References GetText().
operator=() [1/4]
CIccLocalizedUnicode & CIccLocalizedUnicode::operator= (const CIccLocalizedUnicode & UnicodeText)
Name: CIccLocalizedUnicode::operator=
Purpose: Copy Operator
Args: UnicodeText = The CIccLocalizedUnicode object to be copied
{
  if (&UnicodeText == this)
    return *this;
  if (SetSize(UnicodeText.GetLength())) {
    memcpy(m_pBuf, UnicodeText.GetBuf(), m_nLength*sizeof(icUInt16Number));
  }
  m_nLanguageCode = UnicodeText.m_nLanguageCode;
  m_nCountryCode = UnicodeText.m_nCountryCode;
  return *this;
}
References GetBuf(), GetLength(), m_nCountryCode, m_nLanguageCode, m_nLength, m_pBuf, and SetSize().
operator=() [2/4]
const icChar * CIccLocalizedUnicode::operator= (const icChar * szText) inline
{ SetText(szText); return szText; }
References SetText().
operator=() [3/4]
const icUInt16Number * CIccLocalizedUnicode::operator= (const icUInt16Number * sszText) inline
{ SetText(sszText); return sszText; }
References SetText().
operator=() [4/4]
const icUInt32Number * CIccLocalizedUnicode::operator= (const icUInt32Number * sszText) inline
{ SetText(sszText); return sszText; }
References SetText().
SetSize()
bool CIccLocalizedUnicode::SetSize (icUInt32Number nSize)
Name: CIccLocalizedUnicode::SetSize
Purpose: Sets the size of the string buffer.
Args: nSize - length of the string
{
  if (nSize == m_nLength)
    return true;
  m_pBuf = (icUInt16Number*)icRealloc(m_pBuf, (nSize+1)*sizeof(icUInt16Number));
  if (!m_pBuf) {
    m_nLength = 0;
    return false;
  }
  m_nLength = nSize;
  m_pBuf[nSize]=0;
  return true;
}
References icRealloc(), m_nLength, and m_pBuf.
Referenced by operator=(), CIccTagMultiLocalizedUnicode::Read(), SetText(), SetText(), and SetText().
SetText() [1/3]
bool CIccLocalizedUnicode::SetText (const icChar * szText, icLanguageCode nLanguageCode = icLanguageCodeEnglish, icCountryCode nRegionCode = icCountryCodeUSA)
Name: CIccLocalizedUnicode::SetText
Purpose: Allows text data associated with the tag to be set.
Args: szText = zero terminated utf8 string to put in tag, nLanguageCode = the language code type as defined by icLanguageCode, nRegionCode = the region code type as defined by icCountryCode
{
  if (!szText)
    szText = "";
  //first convert utf8 to unicode
  std::vector<unsigned long> unicode;
  size_t i = 0;
  while (szText[i])
  {
    unsigned long uni;
    size_t todo;
    bool error = false;
    unsigned char ch = szText[i++];
    if (ch <= 0x7F)
    {
      uni = ch;
      todo = 0;
    }
    else if (ch <= 0xBF)
    {
      //not a UTF-8 string so use question mark
      uni = '?';
      todo = 0;
    }
    else if (ch <= 0xDF)
    {
      uni = ch & 0x1F;
      todo = 1;
    }
    else if (ch <= 0xEF)
    {
      uni = ch & 0x0F;
      todo = 2;
    }
    else if (ch <= 0xF7)
    {
      uni = ch & 0x07;
      todo = 3;
    }
    else
    {
      //not a UTF-8 string so use question mark
      uni = '?';
      todo = 0;;
    }
    for (size_t j = 0; j < todo; ++j)
    {
      if (!szText[i]) {
        uni = '?';
        break;
      }
      else {
        unsigned char ch = szText[i];
        if (ch < 0x80 || ch > 0xBF) {
          //not a UTF-8 string so use question mark
          uni = '?';
          break;
        }
        else {
          uni <<= 6;
          uni += ch & 0x3F;
        }
      }
    }
    if (uni >= 0xD800 && uni <= 0xDFFF) {
      //not a UTF-8 string so use question mark
      uni = '?';
    }
    else if (uni > 0x10FFFF) {
      //not a UTF-8 string so use question mark
      uni = '?';
    }
    unicode.push_back(uni);
  }
  //now convert unicode to utf16
  std::vector<unsigned short> utf16;
  for (i = 0; i < unicode.size(); ++i)
  {
    unsigned long uni = unicode[i];
    if (uni <= 0xFFFF)
    {
      utf16.push_back((unsigned short)uni);
    }
    else
    {
      uni -= 0x10000;
      utf16.push_back((unsigned short)((uni >> 10) + 0xD800));
      utf16.push_back((unsigned short)((uni & 0x3FF) + 0xDC00));
    }
  }
  icUInt16Number *pBuf;
  size_t len = utf16.size();
  if (!SetSize((icUInt32Number)len+1))
    return false;
  pBuf = m_pBuf;
  for (i=0; i<len; i++) {
    *pBuf++ = utf16[i];
  }
  *pBuf = 0;
  m_nLanguageCode = nLanguageCode;
  m_nCountryCode = nRegionCode;
  return true;
}
References m_nCountryCode, m_nLanguageCode, m_pBuf, and SetSize().
Referenced by operator=(), and CIccTagMultiLocalizedUnicode::SetText().
SetText() [2/3]
bool CIccLocalizedUnicode::SetText (const icUInt16Number * sszUnicode16Text, icLanguageCode nLanguageCode = icLanguageCodeEnglish, icCountryCode nRegionCode = icCountryCodeUSA)
Name: CIccLocalizedUnicode::SetText
Purpose: Allows text data associated with the tag to be set.
Args: sszUnicode16Text = Unicode16 text to be set, nLanguageCode = the language code type as defined by icLanguageCode, nRegionCode = the region code type as defined by icCountryCode
{
  icUInt16Number empty[1] = { 0 };
  if (!sszUnicode16Text)
    sszUnicode16Text = &empty[0];
  const icUInt16Number *pBuf=sszUnicode16Text;
  int len;
  for (len=0; *pBuf; len++, pBuf++);
  if (!SetSize(len))
    return false;
  memcpy(m_pBuf, sszUnicode16Text, (len+1)*sizeof(icUInt16Number));
  m_nLanguageCode = nLanguageCode;
  m_nCountryCode = nRegionCode;
  return true;
}
References m_nCountryCode, m_nLanguageCode, m_pBuf, and SetSize().
Referenced by operator=(), and CIccTagMultiLocalizedUnicode::SetText().
SetText() [3/3]
bool CIccLocalizedUnicode::SetText (const icUInt32Number * sszUnicode32Text, icLanguageCode nLanguageCode = icLanguageCodeEnglish, icCountryCode nRegionCode = icCountryCodeUSA)
Name: CIccLocalizedUnicode::SetText
Purpose: Allows text data associated with the tag to be set.
Args: sszUnicode32Text = Unicode32 text to be set, nLanguageCode = the language code type as defined by icLanguageCode, nRegionCode = the region code type as defined by icCountryCode
{
  const icUInt32Number empty[1] = { 0 };
  if (!sszUnicode32Text)
    sszUnicode32Text = &empty[0];
  const icUInt32Number *pBuf=sszUnicode32Text;
  int len;
  for (len=0; *pBuf; len++, pBuf++);
  if (*pBuf)
    pBuf--;
  if (!SetSize(len*2))
    return false;
  const icUInt32Number *srcStart = sszUnicode32Text;
  icUInt16Number *dstStart = m_pBuf;
  icConvertUTF32toUTF16(&srcStart, &srcStart[len], &dstStart, &dstStart[len*2], lenientConversion);
  *dstStart=0;
  if (!SetSize((icUInt32Number)(dstStart - m_pBuf)))
    return false;
  m_nLanguageCode = nLanguageCode;
  m_nCountryCode = nRegionCode;
  return true;
}
References icConvertUTF32toUTF16(), lenientConversion, m_nCountryCode, m_nLanguageCode, m_pBuf, and SetSize().
Referenced by operator=(), and CIccTagMultiLocalizedUnicode::SetText().
Field Documentation
m_nCountryCode
icCountryCode CIccLocalizedUnicode::m_nCountryCode
Referenced by CIccLocalizedUnicode(), CIccTagMultiLocalizedUnicode::Describe(), CIccTagMultiLocalizedUnicode::Find(), operator=(), CIccTagMultiLocalizedUnicode::Read(), SetText(), SetText(), SetText(), CIccTagXmlMultiLocalizedUnicode::ToXml(), CIccTagXmlProfileSequenceId::ToXml(), CIccTagXmlDict::ToXml(), and CIccTagMultiLocalizedUnicode::Write().
m_nLanguageCode
icLanguageCode CIccLocalizedUnicode::m_nLanguageCode
Referenced by CIccLocalizedUnicode(), CIccTagMultiLocalizedUnicode::Describe(), CIccTagMultiLocalizedUnicode::Find(), operator=(), CIccTagMultiLocalizedUnicode::Read(), SetText(), SetText(), SetText(), CIccTagXmlMultiLocalizedUnicode::ToXml(), CIccTagXmlProfileSequenceId::ToXml(), CIccTagXmlDict::ToXml(), and CIccTagMultiLocalizedUnicode::Write().
m_nLength
icUInt32Number CIccLocalizedUnicode::m_nLength protected
Referenced by CIccLocalizedUnicode(), CIccLocalizedUnicode(), GetLength(), operator=(), and SetSize().
m_pBuf
icUInt16Number* CIccLocalizedUnicode::m_pBuf protected
Referenced by CIccLocalizedUnicode(), CIccLocalizedUnicode(), ~CIccLocalizedUnicode(), GetBuf(), GetText(), operator=(), SetSize(), SetText(), SetText(), and SetText().
The documentation for this class was generated from the following files:
IccProfLib/IccTagBasic.h
IccProfLib/IccTagBasic.cpp