iccDEV: CIccTagFloatNum< T, Tsig > Class Template Reference
CIccTagFloatNum< T, Tsig > Class Template Reference
#include <IccTagBasic.h>
Public Member Functions
CIccTagFloatNum (const CIccTagFloatNum< T, Tsig > &ITNum)
CIccTagFloatNum (int nSize=1)
virtual ~CIccTagFloatNum ()
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
virtual const icChar * GetClassName () const
virtual IIccExtensionTag * GetExtension ()
virtual icUInt32Number GetNumValues () const
icUInt32Number GetSize () const
Returns the size of the data array.
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual bool GetValues (icFloatNumber *DstVector, icUInt32Number nStart=0, icUInt32Number nVectorSize=1) const
virtual bool Interpolate (icFloatNumber *DstVector, icFloatNumber val, icUInt32Number nVectorSize=1, icFloatNumber *zeroVals=NULL) const
virtual bool IsArrayType ()
virtual bool IsMatrixArray () const
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
CIccTagFloatNum & operator= (const CIccTagFloatNum< T, Tsig > &NumTag)
T & operator[] (icUInt32Number index)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
bool SetSize (icUInt32Number nSize, bool bZeroNew=true)
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool ValuePos (icFloatNumber &DstPos, icFloatNumber val, bool &bNoZero) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
Data Fields
icUInt32Number m_nReserved
Protected Attributes
icUInt32Number m_nSize
T * m_Num
Detailed Description
template<class T, icTagTypeSignature Tsig>
class CIccTagFloatNum< T, Tsig >
Class: CIccTagFloatNum
Purpose: A template class for arrays of floating point numbers
Derived Tags: CIccTagFloat32 and CIccTagFloat64
Constructor & Destructor Documentation
CIccTagFloatNum() [1/2]
template<class T , icTagTypeSignature Tsig> CIccTagFloatNum< T, Tsig >::CIccTagFloatNum (int nSize = 1)
Name: CIccTagFloatNum::CIccTagFloatNum
Purpose: Constructor
Args: nSize = number of data entries
{
  m_nSize = nSize;
  if (m_nSize <1)
    m_nSize = 1;
  m_Num = (T*)calloc(nSize, sizeof(T));
}
References CIccTagFloatNum< T, Tsig >::m_nSize, and CIccTagFloatNum< T, Tsig >::m_Num.
CIccTagFloatNum() [2/2]
template<class T , icTagTypeSignature Tsig> CIccTagFloatNum< T, Tsig >::CIccTagFloatNum (const CIccTagFloatNum< T, Tsig > & ITNum)
Name: CIccTagFloatNum::CIccTagFloatNum
Purpose: Copy Constructor
Args: ITNum = The CIccTagNum object to be copied
{
  m_nSize = ITNum.m_nSize;
  m_Num = (T*)calloc(m_nSize, sizeof(T));
  memcpy(m_Num, ITNum.m_Num, m_nSize * sizeof(T));
}
References CIccTagFloatNum< T, Tsig >::m_nSize, and CIccTagFloatNum< T, Tsig >::m_Num.
~CIccTagFloatNum()
template<class T , icTagTypeSignature Tsig> CIccTagFloatNum< T, Tsig >::~CIccTagFloatNum () virtual
Name: CIccTagFloatNum::~CIccTagFloatNum
Purpose: Destructor
{
  if (m_Num)
    free(m_Num);
}
References CIccTagFloatNum< T, Tsig >::m_Num.
Member Function Documentation
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagStruct::LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
Describe()
template<class T , icTagTypeSignature Tsig> void CIccTagFloatNum< T, Tsig >::Describe (std::string & sDescription, int nVerboseness) virtual
Name: CIccTagFloatNum::Describe
Purpose: Dump data associated with the tag to a string
Args: sDescription - string to concatenate tag dump to
Reimplemented from CIccTag.
{
  icChar buf[128] = {0};
  if (m_nSize == 1 ) {
    switch (sizeof(T)) {
      case 4:
        sprintf(buf, "Value = %.8f\n", m_Num[0]);
        break;
      case 8:
        sprintf(buf, "Value = %.16f\n", m_Num[0]);
        break;
      default:
        sprintf(buf, "Value = %.f\n", m_Num[0]);
        break;
    }
    sDescription += buf;
  }
  else {
    icUInt32Number i, n;
    sDescription.reserve(sDescription.size() + m_nSize*79);
    sprintf(buf, "Begin_Value_Array[%d]\n", m_nSize);
    sDescription += buf;
    if (sizeof(T)!=8)
      n=8;
    else
      n=4;
    for (i=0; i<m_nSize; i++) {
      if (i&& !(i%n))
        sDescription += "\n";
      switch (sizeof(T)) {
      case 4:
        sprintf(buf, " %.8f", m_Num[i]);
        break;
      case 8:
        sprintf(buf, " %.16f", m_Num[i]);
        break;
      default:
        sprintf(buf, " %f", m_Num[i]);
      }
      sDescription += buf;
    }
    if ((i%n)!=1)
      sDescription += "\n";
    sDescription += "End_Value_Array\n";
  }
}
References CIccTagFloatNum< T, Tsig >::m_nSize, and CIccTagFloatNum< T, Tsig >::m_Num.
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
GetClassName()
template<class T , icTagTypeSignature Tsig> const icChar * CIccTagFloatNum< T, Tsig >::GetClassName () const virtual
Name: CIccTagFloatNum::GetClassName
Purpose: Returns the tag type class name
Reimplemented from CIccTag.
Reimplemented in CIccTagXmlFloatNum< T, A, Tsig >.
{
  if (Tsig==icSigFloat16ArrayType)
    return "CIccFlaot16";
  if (Tsig==icSigFloat32ArrayType)
    return "CIccFloat32";
  else if (Tsig==icSigFloat64ArrayType)
    return "CIccFloat64";
  else
    return "CIccTagFloatNum<>";
}
References icSigFloat16ArrayType, icSigFloat32ArrayType, and icSigFloat64ArrayType.
GetExtension()
virtual IIccExtensionTag * CIccTag::GetExtension () inline virtual inherited
Reimplemented in CIccTagXmlUnknown, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, CIccTagXmlSignature, CIccTagXmlNamedColor2, CIccTagXmlXYZ, CIccTagXmlChromaticity, CIccTagXmlCicp, CIccTagXmlSparseMatrixArray, CIccTagXmlFixedNum< T, Tsig >, CIccTagXmlNum< T, A, Tsig >, CIccTagXmlFloatNum< T, A, Tsig >, CIccTagXmlMeasurement, CIccTagXmlMultiLocalizedUnicode, CIccTagXmlTagData, CIccTagXmlDateTime, CIccTagXmlColorantOrder, CIccTagXmlColorantTable, CIccTagXmlViewingConditions, CIccTagXmlSpectralDataInfo, CIccTagXmlSpectralViewingConditions, CIccTagXmlProfileSeqDesc, CIccTagXmlResponseCurveSet16, CIccTagXmlCurve, CIccTagXmlParametricCurve, CIccTagXmlSegmentedCurve, CIccTagXmlLutAtoB, CIccTagXmlLutBtoA, CIccTagXmlLut8, CIccTagXmlLut16, CIccTagXmlMultiProcessElement, CIccTagXmlProfileSequenceId, CIccTagXmlDict, CIccTagXmlStruct, CIccTagXmlArray, CIccTagXmlGamutBoundaryDesc, CIccTagXmlEmbeddedHeightImage, CIccTagXmlEmbeddedNormalImage, and CIccTagXmlEmbeddedProfile.
{return NULL;}
Referenced by icCurvesFromXml(), icCurvesToXml(), icProfDescToXml(), icXmlParseProfDesc(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeXmlTintArray::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
GetNumValues()
template<class T , icTagTypeSignature Tsig> virtual icUInt32Number CIccTagFloatNum< T, Tsig >::GetNumValues () const inline virtual
Implements CIccTagNumArray.
{ return GetSize(); }
References CIccTagFloatNum< T, Tsig >::GetSize().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams().
GetSize()
template<class T , icTagTypeSignature Tsig> icUInt32Number CIccTagFloatNum< T, Tsig >::GetSize () const inline
Returns the size of the data array.
{ return m_nSize; }
References CIccTagFloatNum< T, Tsig >::m_nSize.
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), CIccTagFloatNum< T, Tsig >::GetNumValues(), and icGetParamFloatNum().
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTag::GetTagStructType () const inline virtual inherited
Reimplemented in CIccTagStruct.
{ return icSigUndefinedStruct; }
References icSigUndefinedStruct.
Referenced by icGetTagStructHandlerOfType(), CIccArrayColorantInfo::Validate(), and CIccArrayNamedColor::Validate().
GetType()
template<class T , icTagTypeSignature Tsig> virtual icTagTypeSignature CIccTagFloatNum< T, Tsig >::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return Tsig; }
Referenced by CIccTagFloatNum< T, Tsig >::Write().
GetValues()
template<class T , icTagTypeSignature Tsig> bool CIccTagFloatNum< T, Tsig >::GetValues (icFloatNumber * DstVector, icUInt32Number nStart = 0, icUInt32Number nVectorSize = 1) const virtual
Name: CIccTagFloatNum::GetValues
Purpose: Gets values from the num array tag as floating point numbers
Args: nSize - number of data entries, bZeroNew - flag to zero newly formed values
Implements CIccTagNumArray.
{
  if (nVectorSize >m_nSize)
    return false;
  icUInt32Number i;
  for (i=0; i<m_nSize; i++) {
    DstVector[i] = (icFloatNumber)m_Num[i+nStart];
  }
  return true;
}
References CIccTagFloatNum< T, Tsig >::m_nSize, and CIccTagFloatNum< T, Tsig >::m_Num.
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams().
Interpolate()
template<class T , icTagTypeSignature Tsig> bool CIccTagFloatNum< T, Tsig >::Interpolate (icFloatNumber * DstVector, icFloatNumber pos, icUInt32Number nVectorSize = 1, icFloatNumber * zeroVals = NULL) const virtual
Name: CIccTagFloatNum::Interpolate
Purpose: Gets values from the num array tag as floating point numbers
Args: nSize - number of data entries, bZeroNew - flag to zero newly formed values
Implements CIccTagNumArray.
{
  icUInt32Number nVector = m_nSize / nVectorSize;
  if (!nVector)
    return false;
  if (zeroVals)
    nVector ++;
  else if (nVector<=1)
    return false;
  if (pos<0.0)
    pos=0.0;
  if (pos>1.0)
    pos=1.0;
  icFloatNumber fpos = (icFloatNumber)(nVector-1) * pos;
  icUInt32Number iPos = (icUInt32Number)fpos;
  icFloatNumber x = fpos - iPos;
  icFloatNumber invx = (1.0f - x);
  if (iPos == nVector-1) {
    iPos--;
    x = (icFloatNumber)1.0f;
    invx = (icFloatNumber)0.0f;
  }
  T *lo, *hi;
  if (zeroVals) {
    if (!iPos) {
      lo = NULL;
      hi = m_Num;
    }
    else {
      lo = &m_Num[(iPos-1)*nVectorSize];
      hi = &lo[nVectorSize];
    }
  }
  else {
    lo = &m_Num[iPos*nVectorSize];
    hi = &lo[nVectorSize];
  }
  icUInt32Number i;
  if (!lo) {
    if (zeroVals) {
      for (i = 0; i < nVectorSize; i++) {
        DstVector[i] = (icFloatNumber)(zeroVals[i] * invx + hi[i] * x);
      }
    }
    else {
      for (i = 0; i < nVectorSize; i++) {
        DstVector[i] = (icFloatNumber)(hi[i] * x);
      }
    }
  }
  else {
    for (i=0; i<nVectorSize; i++) {
      DstVector[i] = (icFloatNumber)(lo[i]*invx + hi[i]*x);
    }
  }
  return true;
}
References CIccTagFloatNum< T, Tsig >::m_nSize, and CIccTagFloatNum< T, Tsig >::m_Num.
IsArrayType()
template<class T , icTagTypeSignature Tsig> virtual bool CIccTagFloatNum< T, Tsig >::IsArrayType () inline virtual
Reimplemented from CIccTag.
{ return m_nSize > 1; }
References CIccTagFloatNum< T, Tsig >::m_nSize.
IsMatrixArray()
template<class T , icTagTypeSignature Tsig> virtual bool CIccTagFloatNum< T, Tsig >::IsMatrixArray () const inline virtual
Implements CIccTagNumArray.
{ return false; }
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
template<class T , icTagTypeSignature Tsig> virtual bool CIccTagFloatNum< T, Tsig >::IsNumArrayType () const inline virtual
Reimplemented from CIccTag.
{ return true; }
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
NewCopy()
template<class T , icTagTypeSignature Tsig> virtual CIccTag * CIccTagFloatNum< T, Tsig >::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
{ return new CIccTagFloatNum<T, Tsig>(*this); }
operator=()
template<class T , icTagTypeSignature Tsig> CIccTagFloatNum< T, Tsig > & CIccTagFloatNum< T, Tsig >::operator= (const CIccTagFloatNum< T, Tsig > & ITNum)
Name: CIccTagFloatNum::operator=
Purpose: Copy Operator
Args: ITNum = The CIccTagNum object to be copied
{
  if (&ITNum == this)
    return *this;
  m_nSize = ITNum.m_nSize;
  m_Num = (T*)calloc(m_nSize, sizeof(T));
  memcpy(m_Num, ITNum.m_Num, m_nSize * sizeof(T));
  return *this;
}
References CIccTagFloatNum< T, Tsig >::m_nSize, and CIccTagFloatNum< T, Tsig >::m_Num.
operator[]()
template<class T , icTagTypeSignature Tsig> T & CIccTagFloatNum< T, Tsig >::operator[] (icUInt32Number index) inline
{return m_Num[index];}
References CIccTagFloatNum< T, Tsig >::m_Num.
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), and icGetParamFloatNum().
Read() [1/2]
template<class T , icTagTypeSignature Tsig> bool CIccTagFloatNum< T, Tsig >::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagFloatNum::Read
Purpose: Read in the tag contents into a data block
Args: size - # of bytes in tag, pIO - IO object to read tag from
Return: true = successful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  if (Tsig==icSigFloat16ArrayType) {
    if (sizeof(icTagTypeSignature) +
        sizeof(icUInt32Number) +
        sizeof(icFloat16Number) > size)
      return false;
  }
  else {
    if (sizeof(icTagTypeSignature) +
        sizeof(icUInt32Number) +
        sizeof(T) > size)
      return false;
  }
  if (!pIO) {
    return false;
  }
  if (!pIO->Read32(&sig))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  if (Tsig==icSigFloat16ArrayType) {
    icUInt32Number nSize=((size-2*sizeof(icUInt32Number)) / sizeof(icFloat16Number));
    if (!SetSize(nSize))
      return false;
    if (pIO->ReadFloat16Float(&m_Num[0], nSize) != (icInt32Number)nSize)
      return false;
  }
  else if (Tsig==icSigFloat32ArrayType) {
    icUInt32Number nSize=((size-2*sizeof(icUInt32Number)) / sizeof(icFloat32Number));
    if (!SetSize(nSize))
      return false;
    if (pIO->Read32(m_Num, nSize) != (icInt32Number)nSize )
      return false;
  }
  else if (Tsig==icSigFloat64ArrayType) {
    icUInt32Number nSize=((size-2*sizeof(icUInt32Number)) / sizeof(icFloat64Number));
    if (!SetSize(nSize))
      return false;
    if (pIO->Read64(m_Num, nSize) != (icInt32Number)nSize )
      return false;
  }
  else
    return false;
  return true;
}
References icSigFloat16ArrayType, icSigFloat32ArrayType, icSigFloat64ArrayType, CIccTag::m_nReserved, CIccTagFloatNum< T, Tsig >::m_Num, CIccIO::Read32(), CIccIO::Read64(), CIccIO::ReadFloat16Float(), and CIccTagFloatNum< T, Tsig >::SetSize().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
SetSize()
template<class T , icTagTypeSignature Tsig> bool CIccTagFloatNum< T, Tsig >::SetSize (icUInt32Number nSize, bool bZeroNew = true)
Name: CIccTagFloatNum::SetSize
Purpose: Sets the size of the data array.
Args: nSize - number of data entries, bZeroNew - flag to zero newly formed values
{
  if (nSize==m_nSize)
    return true;
  m_Num = (T*)icRealloc(m_Num, nSize*sizeof(T));
  if (!m_Num) {
    m_nSize = 0;
    return false;
  }
  if (bZeroNew && m_nSize < nSize) {
    memset(&m_Num[m_nSize], 0, (nSize-m_nSize)*sizeof(T));
  }
  m_nSize = nSize;
  return true;
}
References CIccTagFloatNum< T, Tsig >::m_nSize, and CIccTagFloatNum< T, Tsig >::m_Num.
Referenced by CIccTagFloatNum< T, Tsig >::Read().
Validate()
template<class T , icTagTypeSignature Tsig> icValidateStatus CIccTagFloatNum< T, Tsig >::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagFloatNum::Interpolate
Purpose: Gets values from the num array tag as floating point numbers
Args: nSize - number of data entries, bZeroNew - flag to zero newly formed values
Reimplemented from CIccTag.
{
  icValidateStatus rv = icValidateOK;
  //Check # of channels
  if (icGetFirstSigPathSig(sigPath) == icSigMaterialDefaultValuesTag &&
    pProfile &&
    m_nSize != icGetMaterialColorSpaceSamples(pProfile->m_Header.mcs)) {
      CIccInfo Info;
      std::string sSigPathName = Info.GetSigPathName(sigPath);
      sReport += icMsgValidateCriticalError;
      sReport += sSigPathName;
      sReport += " - Number of material default values does not match MCS in header.\n";
      rv = icMaxStatus(rv, icValidateCriticalError);
  }
  rv = icMaxStatus(rv, CIccTagNumArray::Validate(sigPath, sReport, pProfile));
  return rv;
}
References CIccInfo::GetSigPathName(), icGetFirstSigPathSig(), icGetMaterialColorSpaceSamples(), icMaxStatus(), icMsgValidateCriticalError, icSigMaterialDefaultValuesTag, icValidateCriticalError, icValidateOK, CIccTagFloatNum< T, Tsig >::m_nSize, icHeader::mcs, and CIccTag::Validate().
ValuePos()
template<class T , icTagTypeSignature Tsig> bool CIccTagFloatNum< T, Tsig >::ValuePos (icFloatNumber & DstPos, icFloatNumber val, bool & bNoZero) const virtual
Name: CIccTagFloatNum::ValuePos
Purpose: Gets position of a value int the num array tag
Args: DstPos - position of val in array val - value to look for in array. bNoZero - flag indicating whether first entry is zero
Implements CIccTagNumArray.
{
  if(val<0.0)
    return false;
  icFloatNumber nv = 0.0;
  icFloatNumber lv = 0.0;
  lv = (icFloatNumber)m_Num[0];
  bNoZero = (lv!=0.0);
  if (val<lv) {
    DstPos = val/lv - 1.0f;
    return true;
  }
  icUInt32Number i;
  for (i=1; i<m_nSize; i++, lv=nv) {
    nv = (icFloatNumber)m_Num[i];
    if (val<=nv) {
      DstPos = (val-lv)/(nv-lv) + i - 1.0f;
      return true;
    }
  }
  return false;
}
References CIccTagFloatNum< T, Tsig >::m_nSize, and CIccTagFloatNum< T, Tsig >::m_Num.
Write()
template<class T , icTagTypeSignature Tsig> bool CIccTagFloatNum< T, Tsig >::Write (CIccIO * pIO) virtual
Name: CIccTagFloatNum::Write
Purpose: Write the tag to a file
Args: pIO - The IO object to write tag to.
Return: true = succesful, false = failure
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  if (!pIO)
   return false;
  if (!pIO->Write32(&sig))
   return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  if (Tsig==icSigFloat16ArrayType) {
    if (pIO->WriteFloat16Float(m_Num, m_nSize) != (icInt32Number)m_nSize)
      return false;
  }
  else if (Tsig == icSigFloat32ArrayType) {
    if (pIO->Write32(m_Num, m_nSize) != (icInt32Number)m_nSize)
      return false;
  }
  else if (Tsig == icSigFloat64ArrayType) {
    if (pIO->Write64(m_Num, m_nSize) != (icInt32Number)m_nSize)
      return false;
  }
  else
    return false;
  return true;
}
References CIccTagFloatNum< T, Tsig >::GetType(), icSigFloat16ArrayType, icSigFloat32ArrayType, icSigFloat64ArrayType, CIccTag::m_nReserved, CIccTagFloatNum< T, Tsig >::m_nSize, CIccTagFloatNum< T, Tsig >::m_Num, CIccIO::Write32(), CIccIO::Write64(), and CIccIO::WriteFloat16Float().
Field Documentation
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), CIccTagStruct::Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), CIccTagStruct::Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_nSize
template<class T , icTagTypeSignature Tsig> icUInt32Number CIccTagFloatNum< T, Tsig >::m_nSize protected
Referenced by CIccTagFloatNum< T, Tsig >::CIccTagFloatNum(), CIccTagFloatNum< T, Tsig >::CIccTagFloatNum(), CIccTagFloatNum< T, Tsig >::Describe(), CIccTagFloatNum< T, Tsig >::GetSize(), CIccTagFloatNum< T, Tsig >::GetValues(), CIccTagFloatNum< T, Tsig >::Interpolate(), CIccTagFloatNum< T, Tsig >::IsArrayType(), CIccTagFloatNum< T, Tsig >::operator=(), CIccTagFloatNum< T, Tsig >::SetSize(), CIccTagFloatNum< T, Tsig >::Validate(), CIccTagFloatNum< T, Tsig >::ValuePos(), and CIccTagFloatNum< T, Tsig >::Write().
m_Num
template<class T , icTagTypeSignature Tsig> T* CIccTagFloatNum< T, Tsig >::m_Num protected
Referenced by CIccTagFloatNum< T, Tsig >::CIccTagFloatNum(), CIccTagFloatNum< T, Tsig >::CIccTagFloatNum(), CIccTagFloatNum< T, Tsig >::~CIccTagFloatNum(), CIccTagFloatNum< T, Tsig >::Describe(), CIccTagFloatNum< T, Tsig >::GetValues(), CIccTagFloatNum< T, Tsig >::Interpolate(), CIccTagFloatNum< T, Tsig >::operator=(), CIccTagFloatNum< T, Tsig >::operator[](), CIccTagFloatNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::SetSize(), CIccTagFloatNum< T, Tsig >::ValuePos(), and CIccTagFloatNum< T, Tsig >::Write().
The documentation for this class was generated from the following files:
IccProfLib/IccTagBasic.h
IccProfLib/IccTagBasic.cpp