iccDEV: IccProfLib/IccMD5.h File Reference
IccMD5.h File Reference
#include "IccProfLibConf.h"
Data Structures
struct MD5_CTX
Typedefs
typedef unsigned char * POINTER
typedef unsigned short int UINT2
typedef ICCUINT32 UINT4
Functions
void ICCPROFLIB_API icMD5Final (unsigned char *, MD5_CTX *)
void ICCPROFLIB_API icMD5Init (MD5_CTX *)
void ICCPROFLIB_API icMD5Update (MD5_CTX *, unsigned char *, unsigned int)
Detailed Description
IccMD5.H - header file for IccMD5.cpp
Copyright (C) 1991-2, RSA Data Security, Inc. Created 1991. All rights reserved.
License to copy and use this software is granted provided that it is identified as the "RSA Data Security, Inc. MD5 Message-Digest Algorithm" in all material mentioning or referencing this software or this function.
License is also granted to make and use derivative works provided that such works are identified as "derived from the RSA Data Security, Inc. MD5 Message-Digest Algorithm" in all material mentioning or referencing the derived work.
RSA Data Security, Inc. makes no representations concerning either the merchantability of this software or the suitability of this software for any particular purpose. It is provided "as is" without express or implied warranty of any kind.
These notices must be retained in any copies of any part of this documentation and/or software.
Definition in file IccMD5.h.
Data Structure Documentation
MD5_CTX
struct MD5_CTX
MD5 context.
Data Fields
unsigned char buffer[64]
UINT4 count[2]
UINT4 state[4]
Typedef Documentation
POINTER
typedef unsigned char* POINTER
POINTER defines a generic pointer type
UINT2
typedef unsigned short int UINT2
UINT2 defines a two byte word
UINT4
typedef ICCUINT32 UINT4
UINT4 defines a four byte word
Function Documentation
icMD5Final()
void ICCPROFLIB_API icMD5Final (unsigned char * digest, MD5_CTX * context)
MD5 finalization. Ends an MD5 message-digest operation, writing the the message digest and zeroizing the context.
{
  unsigned char bits[8];
  unsigned int index, padLen;
  /* Save number of bits */
  Encode (bits, context->count, 8);
  /* Pad out to 56 mod 64.
*/
  index = (unsigned int)((context->count[0] >> 3) & 0x3f);
  padLen = (index < 56) ? (56 - index) : (120 - index);
  icMD5Update (context, PADDING, padLen);
  /* Append length (before padding) */
  icMD5Update (context, bits, 8);
  /* Store state in digest */
  Encode (digest, context->state, 16);
  /* Zeroize sensitive information.
*/
  memset((POINTER)context, 0, sizeof (*context));
}
References MD5_CTX::count, Encode(), icMD5Update(), PADDING, and MD5_CTX::state.
Referenced by CalcProfileID().
icMD5Init()
void ICCPROFLIB_API icMD5Init (MD5_CTX * context)
MD5 initialization. Begins an MD5 operation, writing a new context.
{
  context->count[0] = context->count[1] = 0;
  /* Load magic initialization constants.
*/
  context->state[0] = 0x67452301;
  context->state[1] = 0xefcdab89;
  context->state[2] = 0x98badcfe;
  context->state[3] = 0x10325476;
}
References MD5_CTX::count, and MD5_CTX::state.
Referenced by CalcProfileID().
icMD5Update()
void ICCPROFLIB_API icMD5Update (MD5_CTX * context, unsigned char * input, unsigned int inputLen)
MD5 block update operation. Continues an MD5 message-digest operation, processing another message block, and updating the context.
{
  unsigned int i, index, partLen;
  /* Compute number of bytes mod 64 */
  index = (unsigned int)((context->count[0] >> 3) & 0x3F);
  /* Update number of bits */
  if ((context->count[0] += ((UINT4)inputLen << 3))
    < ((UINT4)inputLen << 3))
    context->count[1]++;
  context->count[1] += ((UINT4)inputLen >> 29);
  partLen = 64 - index;
  /* Transform as many times as possible.
  */
  if (inputLen >= partLen) {
    memcpy((POINTER)&context->buffer[index], (POINTER)input, partLen);
    MD5Transform (context->state, context->buffer);
    for (i = partLen; i + 63 < inputLen; i += 64)
      MD5Transform (context->state, &input[i]);
    index = 0;
  }
  else
    i = 0;
  /* Buffer remaining input */
  memcpy((POINTER)&context->buffer[index], (POINTER)&input[i],inputLen-i);
}
References MD5_CTX::buffer, MD5_CTX::count, MD5Transform(), and MD5_CTX::state.
Referenced by CalcProfileID(), and icMD5Final().