iccDEV: CIccPRMG Class Reference
CIccPRMG Class Reference
#include <IccPrmg.h>
Public Member Functions
CIccPRMG ()
icStatusCMM EvaluateProfile (CIccProfile *pProfile, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, bool buseMpeTags=true)
icStatusCMM EvaluateProfile (const icChar *szProfilePath, icRenderingIntent nIntent=icUnknownIntent, icXformInterp nInterp=icInterpLinear, bool buseMpeTags=true)
icFloatNumber GetChroma (icFloatNumber L, icFloatNumber h)
bool InGamut (icFloatNumber *Lab)
bool InGamut (icFloatNumber L, icFloatNumber c, icFloatNumber h)
Data Fields
bool m_bPrmgImplied
icUInt32Number m_nDE1
icUInt32Number m_nDE10
icUInt32Number m_nDE2
icUInt32Number m_nDE3
icUInt32Number m_nDE5
icUInt32Number m_nTotal
Detailed Description
Constructor & Destructor Documentation
CIccPRMG()
CIccPRMG::CIccPRMG ()
{
  m_nTotal = m_nDE1 = m_nDE2 = m_nDE3 = m_nDE5 = m_nDE10 = 0;
  m_bPrmgImplied = false;
}
References m_bPrmgImplied, m_nDE1, m_nDE10, m_nDE2, m_nDE3, m_nDE5, and m_nTotal.
Member Function Documentation
EvaluateProfile() [1/2]
icStatusCMM CIccPRMG::EvaluateProfile (CIccProfile * pProfile, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, bool buseMpeTags = true)
{
  if (!pProfile)
  {
    return icCmmStatCantOpenProfile;
  }
  if (pProfile->m_Header.deviceClass!=icSigInputClass &&
    pProfile->m_Header.deviceClass!=icSigDisplayClass &&
    pProfile->m_Header.deviceClass!=icSigOutputClass &&
    pProfile->m_Header.deviceClass!=icSigColorSpaceClass)
  {
    return icCmmStatInvalidProfile;
  }
  m_bPrmgImplied = false;
  if (nIntent==icPerceptual || nIntent==icSaturation) {
    icTagSignature rigSig = (icTagSignature)(icSigPerceptualRenderingIntentGamutTag + ((icUInt32Number)nIntent)%4);
    CIccTag *pSigTag = pProfile->FindTag(rigSig);
    if (pSigTag && pSigTag->GetType()==icSigSignatureType) {
      CIccTagSignature *pSig = (CIccTagSignature*)pSigTag;
      if (pSig->GetValue()==icSigPerceptualReferenceMediumGamut)
        m_bPrmgImplied = true;
    }
  }
  CIccCmm Lab2Dev2Lab(icSigLabData, icSigLabData, false);
  icStatusCMM result = Lab2Dev2Lab.AddXform(*pProfile, nIntent, nInterp, NULL, icXformLutColorimetric, buseMpeTags);
  if (result != icCmmStatOk) {
    return result;
  }
  result = Lab2Dev2Lab.AddXform(*pProfile, nIntent, nInterp, NULL, icXformLutColorimetric, buseMpeTags);
  if (result != icCmmStatOk) {
    return result;
  }
  result = Lab2Dev2Lab.Begin();
  if (result != icCmmStatOk) {
    return result;
  }
  icFloatNumber pcs[3], Lab1[3], Lab2[3], dE;
  m_nTotal = m_nDE1 = m_nDE2 = m_nDE3 = m_nDE5 = m_nDE10 = 0;
  for (pcs[0]=0.0; pcs[0]<=1.0; pcs[0] += (icFloatNumber)0.01) {
    for (pcs[1]=0.0; pcs[1]<=1.0; pcs[1] += (icFloatNumber)0.01) {
      for (pcs[2]=0.0; pcs[2]<=1.0; pcs[2] += (icFloatNumber)0.01) {
        memcpy(Lab1, pcs, 3*sizeof(icFloatNumber));
        icLabFromPcs(Lab1);
        if (InGamut(Lab1)) {
          Lab2Dev2Lab.Apply(Lab2, pcs);
          icLabFromPcs(Lab2);
          dE = icDeltaE(Lab1, Lab2);
          m_nTotal++;
          if (dE<=1.0) {
            m_nDE1++;
            m_nDE2++;
            m_nDE3++;
            m_nDE5++;
            m_nDE10++;
          }
          else if (dE<=2.0) {
            m_nDE2++;
            m_nDE3++;
            m_nDE5++;
            m_nDE10++;
          }
          else if (dE<=3.0) {
            m_nDE3++;
            m_nDE5++;
            m_nDE10++;
          }
          else if (dE<=5.0) {
            m_nDE5++;
            m_nDE10++;
          }
          else if (dE<=10.0) {
            m_nDE10++;
          }
        }
      }
    }
  }
  return icCmmStatOk;
}
References icHeader::deviceClass, CIccTag::GetType(), CIccTagSignature::GetValue(), icCmmStatCantOpenProfile, icCmmStatInvalidProfile, icCmmStatOk, icDeltaE(), icLabFromPcs(), icPerceptual, icSaturation, icSigColorSpaceClass, icSigDisplayClass, icSigInputClass, icSigLabData, icSigOutputClass, icSigPerceptualReferenceMediumGamut, icSigPerceptualRenderingIntentGamutTag, icSigSignatureType, icXformLutColorimetric, InGamut(), m_bPrmgImplied, m_nDE1, m_nDE10, m_nDE2, m_nDE3, m_nDE5, and m_nTotal.
Referenced by EvaluateProfile().
EvaluateProfile() [2/2]
icStatusCMM CIccPRMG::EvaluateProfile (const icChar * szProfilePath, icRenderingIntent nIntent = icUnknownIntent, icXformInterp nInterp = icInterpLinear, bool buseMpeTags = true)
{
  CIccProfile *pProfile = ReadIccProfile(szProfilePath);
  if (!pProfile)
    return icCmmStatCantOpenProfile;
  icStatusCMM result = EvaluateProfile(pProfile, nIntent, nInterp, buseMpeTags);
  delete pProfile;
  return result;
}
References CIccProfile, EvaluateProfile(), icCmmStatCantOpenProfile, and ReadIccProfile().
Referenced by AnalyzeRoundTrip(), and main().
GetChroma()
icFloatNumber CIccPRMG::GetChroma (icFloatNumber L, icFloatNumber h)
{
  if (L < 3.5 || L > 100.0)
    return -1;
  int nHIndex, nLIndex;
  icFloatNumber dHFraction, dLFraction;
  // Normalize h to the range [0, 360)
  while (h < 0.0)
    h += 360.0;
  while (h >= 360.0)
    h -= 360.0;
  nHIndex = (int)(h / 10.0);
  dHFraction = (h - nHIndex * 10.0f) / 10.0f;
  if (L < 5) {
    nLIndex = 0;
    dLFraction = (L - 3.5f) / (5.0f - 3.5f);
  } else if (L == 100.0) {
    nLIndex = 19; // Assuming 19 is a safe index, adapt if necessary
    dLFraction = 1.0;
  } else {
    nLIndex = (int)((L - 5.0) / 5.0) + 1;
    dLFraction = (L - nLIndex * 5.0f) / 5.0f;
  }
  // Determine the bounds of the icPRMG_Chroma array (replace with actual bounds)
  const int maxHIndex = sizeof(icPRMG_Chroma) / sizeof(icPRMG_Chroma[0]) - 1;
  const int maxLIndex = sizeof(icPRMG_Chroma[0]) / sizeof(icPRMG_Chroma[0][0]) - 1;
    // Clamp indices to prevent out-of-bounds access
  nHIndex = icClamp(nHIndex, 0, maxHIndex - 1);
  nLIndex = icClamp(nLIndex, 0, maxLIndex - 1);
  icFloatNumber dInvLFraction = 1.0f - dLFraction;
  // Interpolate chroma values safely
  icFloatNumber ch1 = icPRMG_Chroma[nHIndex][nLIndex] * dInvLFraction
                    + icPRMG_Chroma[nHIndex][nLIndex+1] * dLFraction;
  icFloatNumber ch2 = icPRMG_Chroma[nHIndex+1][nLIndex] * dInvLFraction
                    + icPRMG_Chroma[nHIndex+1][nLIndex+1] * dLFraction;
  return ch1 * (1.0f - dHFraction) + ch2 * dHFraction;
}
References icClamp(), and icPRMG_Chroma.
Referenced by InGamut().
InGamut() [1/2]
bool CIccPRMG::InGamut (icFloatNumber * Lab)
{
  icFloatNumber Lch[3];
  icLab2Lch(Lch, Lab);
  return InGamut(Lch[0], Lch[1], Lch[2]);
}
References icLab2Lch(), and InGamut().
Referenced by EvaluateProfile().
InGamut() [2/2]
bool CIccPRMG::InGamut (icFloatNumber L, icFloatNumber c, icFloatNumber h)
{
  icFloatNumber dChroma = GetChroma(L, h);
  if (dChroma<0.0 || c>dChroma)
    return false;
  return true;
}
References GetChroma().
Referenced by InGamut().
Field Documentation
m_bPrmgImplied
bool CIccPRMG::m_bPrmgImplied
Referenced by CIccPRMG(), EvaluateProfile(), and main().
m_nDE1
icUInt32Number CIccPRMG::m_nDE1
Referenced by CIccPRMG(), EvaluateProfile(), and main().
m_nDE10
icUInt32Number CIccPRMG::m_nDE10
Referenced by CIccPRMG(), EvaluateProfile(), and main().
m_nDE2
icUInt32Number CIccPRMG::m_nDE2
Referenced by CIccPRMG(), EvaluateProfile(), and main().
m_nDE3
icUInt32Number CIccPRMG::m_nDE3
Referenced by CIccPRMG(), EvaluateProfile(), and main().
m_nDE5
icUInt32Number CIccPRMG::m_nDE5
Referenced by CIccPRMG(), EvaluateProfile(), and main().
m_nTotal
icUInt32Number CIccPRMG::m_nTotal
Referenced by CIccPRMG(), AnalyzeRoundTrip(), EvaluateProfile(), and main().
The documentation for this class was generated from the following files:
IccProfLib/IccPrmg.h
IccProfLib/IccPrmg.cpp