iccDEV: IIccOpDef Class Reference
IIccOpDef Class Reference
#include <IccMpeCalc.h>
Inherited by CIccOpDefAbsoluteVal, CIccOpDefAdd, CIccOpDefAnd, CIccOpDefArcCosine, CIccOpDefArcSine, CIccOpDefArcTan2, CIccOpDefArcTangent, CIccOpDefCartesianToPolar, CIccOpDefCeiling, CIccOpDefCopy, CIccOpDefCosine, CIccOpDefCube, CIccOpDefCubeRoot, CIccOpDefData, CIccOpDefDivide, CIccOpDefEnvVar, CIccOpDefEqual, CIccOpDefExp, CIccOpDefFlip, CIccOpDefFloor, CIccOpDefFromLab, CIccOpDefGamma, CIccOpDefGreaterThan, CIccOpDefGreaterThanEqual, CIccOpDefInputChan, CIccOpDefInvalid, CIccOpDefLessThan, CIccOpDefLessThanEqual, CIccOpDefLogrithm, CIccOpDefMaximum, CIccOpDefMinimum, CIccOpDefModulus, CIccOpDefMultiply, CIccOpDefNaturalLog, CIccOpDefNear, CIccOpDefNeg, CIccOpDefNegInfinity, CIccOpDefNot, CIccOpDefNotANumber, CIccOpDefNotEqual, CIccOpDefOr, CIccOpDefOutputChan, CIccOpDefPi, CIccOpDefPolarToCartesian, CIccOpDefPop, CIccOpDefPosInfinity, CIccOpDefPositionDup, CIccOpDefPow, CIccOpDefProduct, CIccOpDefRealNumber, CIccOpDefRotateLeft, CIccOpDefRotateRight, CIccOpDefRound, CIccOpDefScalarAdd, CIccOpDefScalarDivide, CIccOpDefScalarMultiply, CIccOpDefScalarSubtract, CIccOpDefSign, CIccOpDefSine, CIccOpDefSolve, CIccOpDefSquare, CIccOpDefSquareRoot, CIccOpDefSubElement, CIccOpDefSubtract, CIccOpDefSum, CIccOpDefTangent, CIccOpDefTempGetChan, CIccOpDefTempPutChan, CIccOpDefTempSaveChan, CIccOpDefToLab, CIccOpDefTranspose, CIccOpDefTruncate, CIccOpDefVectorAnd, CIccOpDefVectorMaximum, CIccOpDefVectorMinimum, and CIccOpDefVectorOr.
Public Member Functions
IIccOpDef ()
virtual ~IIccOpDef ()
virtual int ArgsPushed (CIccMpeCalculator *pCalc, SIccCalcOp &op)
virtual int ArgsUsed (CIccMpeCalculator *pCalc, SIccCalcOp &op)
virtual void Describe (SIccCalcOp &op, std::string &desc, int nVerboseness)
virtual bool Exec (SIccCalcOp *op, SIccOpState &s)
virtual bool IsValid (CIccMpeCalculator *pCalc, SIccCalcOp &op)
Detailed Description
Interface: IIccOpDef
Purpose: A structure to keep track of channel operations
Constructor & Destructor Documentation
IIccOpDef()
IIccOpDef::IIccOpDef () inline
{}
~IIccOpDef()
virtual IIccOpDef::~IIccOpDef () inline virtual
{}
Member Function Documentation
ArgsPushed()
virtual int IIccOpDef::ArgsPushed (CIccMpeCalculator * pCalc, SIccCalcOp & op) inline virtual
{ return op.ArgsPushed(pCalc);}
References SIccCalcOp::ArgsPushed().
ArgsUsed()
virtual int IIccOpDef::ArgsUsed (CIccMpeCalculator * pCalc, SIccCalcOp & op) inline virtual
{ return op.ArgsUsed(pCalc);}
References SIccCalcOp::ArgsUsed().
Describe()
virtual void IIccOpDef::Describe (SIccCalcOp & op, std::string & desc, int nVerboseness) inline virtual
{op.Describe(desc, nVerboseness);}
References SIccCalcOp::Describe().
Exec()
virtual bool IIccOpDef::Exec (SIccCalcOp * op, SIccOpState & s) inline virtual
Reimplemented in CIccOpDefInvalid, CIccOpDefData, CIccOpDefPop, CIccOpDefOutputChan, CIccOpDefInputChan, CIccOpDefTempGetChan, CIccOpDefTempPutChan, CIccOpDefTempSaveChan, CIccOpDefEnvVar, CIccOpDefSubElement, CIccOpDefCopy, CIccOpDefPositionDup, CIccOpDefFlip, CIccOpDefRotateLeft, CIccOpDefRotateRight, CIccOpDefTranspose, CIccOpDefSolve, CIccOpDefPi, CIccOpDefPosInfinity, CIccOpDefNegInfinity, CIccOpDefNotANumber, CIccOpDefSum, CIccOpDefProduct, CIccOpDefMinimum, CIccOpDefMaximum, CIccOpDefAnd, CIccOpDefOr, CIccOpDefVectorMinimum, CIccOpDefVectorMaximum, CIccOpDefVectorAnd, CIccOpDefVectorOr, CIccOpDefAdd, CIccOpDefSubtract, CIccOpDefMultiply, CIccOpDefDivide, CIccOpDefModulus, CIccOpDefGamma, CIccOpDefScalarAdd, CIccOpDefScalarSubtract, CIccOpDefScalarMultiply, CIccOpDefScalarDivide, CIccOpDefPow, CIccOpDefSquare, CIccOpDefSquareRoot, CIccOpDefCube, CIccOpDefCubeRoot, CIccOpDefSign, CIccOpDefAbsoluteVal, CIccOpDefTruncate, CIccOpDefFloor, CIccOpDefCeiling, CIccOpDefRound, CIccOpDefExp, CIccOpDefLogrithm, CIccOpDefNaturalLog, CIccOpDefSine, CIccOpDefCosine, CIccOpDefTangent, CIccOpDefArcSine, CIccOpDefArcCosine, CIccOpDefArcTangent, CIccOpDefArcTan2, CIccOpDefCartesianToPolar, CIccOpDefPolarToCartesian, CIccOpDefLessThan, CIccOpDefRealNumber, CIccOpDefLessThanEqual, CIccOpDefEqual, CIccOpDefNotEqual, CIccOpDefNear, CIccOpDefGreaterThanEqual, CIccOpDefGreaterThan, CIccOpDefNot, CIccOpDefNeg, CIccOpDefToLab, and CIccOpDefFromLab.
{return false;}
Referenced by CIccCalculatorFunc::ApplySequence().
IsValid()
virtual bool IIccOpDef::IsValid (CIccMpeCalculator * pCalc, SIccCalcOp & op) inline virtual
Reimplemented in CIccOpDefInvalid.
{ return op.IsValidOp(pCalc); }
References SIccCalcOp::IsValidOp().
The documentation for this class was generated from the following file:
IccProfLib/IccMpeCalc.h