iccDEV: CIccSubCalcApply Class Reference
CIccSubCalcApply Class Reference
#include <IccMpeCalc.h>
Public Member Functions
CIccSubCalcApply (CIccApplyMpe *pApplyMpe)
~CIccSubCalcApply ()
void Apply (icFloatNumber *pDestPixel, const icFloatNumber *pSrcPixel)
icUInt16Number NumInputChannels ()
icUInt16Number NumOutputChannels ()
Protected Attributes
CIccApplyMpe * m_pApply
Detailed Description
Constructor & Destructor Documentation
CIccSubCalcApply()
CIccSubCalcApply::CIccSubCalcApply (CIccApplyMpe * pApplyMpe) inline
{ m_pApply = pApplyMpe; }
References m_pApply.
Referenced by CIccMpeCalculator::GetNewApply().
~CIccSubCalcApply()
CIccSubCalcApply::~CIccSubCalcApply () inline
{ if (m_pApply) delete m_pApply; }
References m_pApply.
Member Function Documentation
Apply()
void CIccSubCalcApply::Apply (icFloatNumber * pDestPixel, const icFloatNumber * pSrcPixel) inline
{ if (m_pApply) m_pApply->Apply(pDestPixel, pSrcPixel); }
References CIccApplyMpe::Apply(), and m_pApply.
Referenced by CIccOpDefSubElement::Exec().
NumInputChannels()
icUInt16Number CIccSubCalcApply::NumInputChannels () inline
{ return m_pApply->GetElem()->NumInputChannels(); }
References CIccApplyMpe::GetElem(), m_pApply, and CIccMultiProcessElement::NumInputChannels().
Referenced by CIccOpDefSubElement::Exec().
NumOutputChannels()
icUInt16Number CIccSubCalcApply::NumOutputChannels () inline
{ return m_pApply->GetElem()->NumOutputChannels(); }
References CIccApplyMpe::GetElem(), m_pApply, and CIccMultiProcessElement::NumOutputChannels().
Referenced by CIccOpDefSubElement::Exec().
Field Documentation
m_pApply
CIccApplyMpe* CIccSubCalcApply::m_pApply protected
Referenced by CIccSubCalcApply(), ~CIccSubCalcApply(), Apply(), NumInputChannels(), and NumOutputChannels().
The documentation for this class was generated from the following file:
IccProfLib/IccMpeCalc.h