iccDEV: CIccTagStruct Class Reference
CIccTagStruct Class Reference
#include <IccTagComposite.h>
Public Member Functions
CIccTagStruct ()
CIccTagStruct (const CIccTagStruct &lut)
virtual ~CIccTagStruct ()
bool AreElemsUnique () const
bool AttachElem (icSignature sig, CIccTag *pTag)
bool DeleteElem (icSignature sig)
virtual void Describe (std::string &sDescription, int nVerboseness)
virtual void DetachIO ()
CIccTag * FindElem (icSignature sig)
CIccTag * FindElemOfType (icSignature sig, icTagTypeSignature sigType)
virtual const icChar * GetClassName () const
TagEntryList * GetElemList ()
icFloatNumber GetElemNumberValue (icSignature sig, icFloatNumber defaultValue=0)
virtual IIccExtensionTag * GetExtension ()
IIccStruct * GetStructHandler ()
virtual icArraySignature GetTagArrayType () const
virtual icStructSignature GetTagStructType () const
virtual icTagTypeSignature GetType () const
virtual bool IsArrayType ()
virtual bool IsMBBType ()
virtual bool IsNumArrayType () const
virtual bool IsSupported ()
virtual CIccTag * NewCopy () const
CIccTagStruct & operator= (const CIccTagStruct &lut)
virtual bool Read (icUInt32Number size, CIccIO *pIO)
virtual bool Read (icUInt32Number size, CIccIO *pIO, CIccProfile *pProfile)
virtual bool ReadAll ()
virtual bool SetTagStructType (icStructSignature sig)
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
virtual bool Write (CIccIO *pIO)
Static Public Member Functions
static CIccTag * Create (icTagTypeSignature sig)
static std::string GetElemName (icTagSignature sig, icStructSignature sigThis)
static CIccTagStruct * ParseMem (icUInt8Number *pMem, icUInt32Number size)
Data Fields
icUInt32Number m_nReserved
Protected Member Functions
void Cleanup ()
bool DetachElem (CIccTag *pTag)
IccTagEntry * GetElem (CIccTag *pTag) const
IccTagEntry * GetElem (icSignature sig) const
bool LoadElem (IccTagEntry *pTagEntry, CIccIO *pIO)
Protected Attributes
TagEntryList * m_ElemEntries
TagPtrList * m_ElemVals
IIccStruct * m_pStruct
icStructSignature m_sigStructType
icUInt32Number m_tagSize
icUInt32Number m_tagStart
Detailed Description
Class: CIccTagStruct
Purpose: The general purpose Tag Struct type tag
Constructor & Destructor Documentation
CIccTagStruct() [1/2]
CIccTagStruct::CIccTagStruct ()
Name: CIccTagStruct::CIccTagStruct
Purpose:
Args:
Return:
{
  m_ElemEntries = new(TagEntryList);
  m_ElemVals = new(TagPtrList);
  m_pStruct = NULL;
}
References m_ElemEntries, m_ElemVals, and m_pStruct.
CIccTagStruct() [2/2]
CIccTagStruct::CIccTagStruct (const CIccTagStruct & subTags)
Name: CIccTagStruct::CIccTagStruct
Purpose:
Args:
Return:
{
  m_sigStructType = subTags.m_sigStructType;
  m_ElemEntries = new(TagEntryList);
  m_ElemVals = new(TagPtrList);
  if (!subTags.m_ElemEntries->empty()) {
    TagEntryList::const_iterator i;
    IccTagEntry entry;
    for (i=subTags.m_ElemEntries->begin(); i!=subTags.m_ElemEntries->end(); i++) {
      entry.pTag = i->pTag->NewCopy();
      memcpy(&entry.TagInfo, &i->TagInfo, sizeof(icTag));
      m_ElemEntries->push_back(entry);
    }
  }
  if (!subTags.m_ElemVals->empty()) {
    TagPtrList::const_iterator i;
    IccTagPtr tagptr;
    for (i=subTags.m_ElemVals->begin(); i!=subTags.m_ElemVals->end(); i++) {
      tagptr.ptr = i->ptr->NewCopy();
      m_ElemVals->push_back(tagptr);
    }
  }
  if (subTags.m_pStruct) {
    m_pStruct = subTags.m_pStruct->NewCopy(this);
  }
  else {
    m_pStruct = NULL;
  }
}
References m_ElemEntries, m_ElemVals, m_pStruct, m_sigStructType, CIccTag::NewCopy(), and IIccStruct::NewCopy().
Referenced by NewCopy().
~CIccTagStruct()
CIccTagStruct::~CIccTagStruct () virtual
Name: CIccTagStruct::~CIccTagStruct
Purpose:
Args:
Return:
{
  Cleanup();
  delete m_ElemEntries;
  delete m_ElemVals;
  if (m_pStruct)
    delete m_pStruct;
}
References Cleanup(), m_ElemEntries, m_ElemVals, and m_pStruct.
Member Function Documentation
AreElemsUnique()
bool CIccTagStruct::AreElemsUnique () const
Name: CIccTagStruct::AreElemsUnique
Purpose: For each tag it checks to see if any other tags have the same signature.
Return: true if all tags have unique signatures, or false if there are duplicate tag signatures.
{
  TagEntryList::const_iterator i, j;
  for (i=m_ElemEntries->begin(); i!=m_ElemEntries->end(); i++) {
    j=i;
    for (j++; j!= m_ElemEntries->end(); j++) {
      if (i->TagInfo.sig == j->TagInfo.sig)
        return false;
    }
  }
  return true;
}
References m_ElemEntries, and icTag::sig.
Referenced by Validate().
AttachElem()
bool CIccTagStruct::AttachElem (icSignature sig, CIccTag * pTag)
Name: CIccTagStruct::AttachTag
Purpose: Assign a tag object to a directory entry in the profile. This will assume ownership of the tag object.
Args: sig - signature of tag 'name' to use to assign tag object with, pTag - pointer to tag object to attach to profile.
Return: true = tag assigned to profile, false - tag not assigned to profile (tag already exists).
{
  IccTagEntry *pEntry = GetElem(sig);
  if (pEntry) {
    if (pEntry->pTag == pTag)
      return true;
    return false;
  }
  IccTagEntry Entry;
  Entry.TagInfo.sig = (icTagSignature)sig;
  Entry.TagInfo.offset = 0;
  Entry.TagInfo.size = 0;
  Entry.pTag = pTag;
  m_ElemEntries->push_back(Entry);
  TagPtrList::iterator i;
  for (i=m_ElemVals->begin(); i!=m_ElemVals->end(); i++)
    if (i->ptr == pTag)
      break;
  if (i==m_ElemVals->end()) {
    IccTagPtr TagPtr;
    TagPtr.ptr = pTag;
    m_ElemVals->push_back(TagPtr);
  }
  return true;
}
References GetElem(), m_ElemEntries, m_ElemVals, icTag::offset, icTag::sig, and icTag::size.
Referenced by icConvertEncodingProfile(), and CIccTagXmlStruct::ParseTag().
Cleanup()
void CIccTagStruct::Cleanup () protected
Name: CIccTagStruct::Cleanup
Purpose: Detach from a pending IO object
{
  TagPtrList::iterator i;
  for (i=m_ElemVals->begin(); i!=m_ElemVals->end(); i++) {
    if (i->ptr)
      delete i->ptr;
  }
  m_ElemEntries->clear();
  m_ElemVals->clear();
  if (m_pStruct)
    delete m_pStruct;
  m_pStruct = NULL;
  m_sigStructType = icSigUndefinedStruct;
}
References icSigUndefinedStruct, m_ElemEntries, m_ElemVals, m_pStruct, and m_sigStructType.
Referenced by ~CIccTagStruct(), operator=(), and Read().
Create()
CIccTag * CIccTag::Create (icTagTypeSignature sig) static inherited
Name: CIccTag::Create
Purpose: This is a static tag creator based upon tag signature type
Args: sig = tag type signature
Return: Pointer to Allocated tag
{
  return CIccTagCreator::CreateTag(sig);
}
References CIccTagCreator::CreateTag().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), LoadElem(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeTintArray::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagLut8::SetColorSpaces(), CIccTagLut16::SetColorSpaces(), and CIccProfileDescText::SetType().
DeleteElem()
bool CIccTagStruct::DeleteElem (icSignature sig)
Name: CIccTagStruct::DeleteSubTag
Purpose: Delete tag directory entry with given signature. If no other tag directory entries use the tag object, the tag object will also be deleted.
Args: sig - signature of tag directory entry to remove
Return: true - desired tag directory entry was found and deleted, false - desired tag directory entry was not found
{
  TagEntryList::iterator i;
  for (i=m_ElemEntries->begin(); i!=m_ElemEntries->end(); i++) {
    if (i->TagInfo.sig==sig)
      break;
  }
  if (i!=m_ElemEntries->end()) {
    CIccTag *pTag = i->pTag;
    m_ElemEntries->erase(i);
    if (!GetElem(pTag)) {
      DetachElem(pTag);
      delete pTag;
    }
    return true;
  }
  return false;
}
References DetachElem(), GetElem(), m_ElemEntries, and icTag::sig.
Referenced by icConvertEncodingProfile().
Describe()
void CIccTagStruct::Describe (std::string & sDescription, int nVerboseness) virtual
Name: CIccTagStruct::Describe
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  std::string name;
  CIccStructCreator::GetStructSigName(name, m_sigStructType);
  sDescription += "BEGIN STRUCT \"";
  sDescription += name + "\"\n";
  if (m_pStruct) {
    m_pStruct->Describe(sDescription, nVerboseness);
  }
  else {
    IIccStruct *pStruct = CIccStructCreator::CreateStruct(m_sigStructType, this);
    if (pStruct) {
      pStruct->Describe(sDescription, nVerboseness);
      delete pStruct;
    }
    else {
      CIccStructUnknown structHandler(this);
      structHandler.Describe(sDescription, nVerboseness);
    }
  }
  sDescription += "END STRUCT \"";
  sDescription += name + "\"\n";
}
References CIccStructUnknown::CIccStructUnknown(), CIccStructCreator::CreateStruct(), CIccStructUnknown::Describe(), IIccStruct::Describe(), CIccStructCreator::GetStructSigName(), m_pStruct, and m_sigStructType.
DetachElem()
bool CIccTagStruct::DetachElem (CIccTag * pTag) protected
Name: CIccTagStruct::DetachSubTag
Purpose: Remove association of a tag object from all tag directory entries. Associated tag directory entries will be removed from the tag directory. The tag object is NOT deleted from memory, but is considered to be no longer associated with the CIccTagStruct object. The caller assumes ownership of the tag object.
Args: pTag - pointer to tag object unassociated with the profile object
Return: true - tag object found and unassociated with profile object, false - tag object not found
{
  if (!pTag)
    return false;
  TagPtrList::iterator i;
  for (i=m_ElemVals->begin(); i!=m_ElemVals->end(); i++) {
    if (i->ptr == pTag)
      break;
  }
  if (i==m_ElemVals->end())
    return false;
  m_ElemVals->erase(i);
  TagEntryList::iterator j;
  for (j=m_ElemEntries->begin(); j!=m_ElemEntries->end();) {
    if (j->pTag == pTag) {
      j=m_ElemEntries->erase(j);
    }
    else
      j++;
  }
  return true;
}
References m_ElemEntries, and m_ElemVals.
Referenced by DeleteElem().
DetachIO()
virtual void CIccTag::DetachIO () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
{}
FindElem()
CIccTag * CIccTagStruct::FindElem (icSignature sig)
Name: CIccTagStruct::FindElem
Purpose: Finds the tag object associated with the struct entry with the given signature.
Args: sig - element signature to find
Return: The desired tag object, or NULL if unable to find in the struct
{
  IccTagEntry *pEntry = GetElem(sig);
  if (pEntry) {
    return pEntry->pTag;
  }
  return NULL;
}
References GetElem().
Referenced by CIccStructUnknown::GetElem(), GetElemNumberValue(), CIccStructNamedColor::getName(), CIccTagXmlStruct::ParseTag(), CIccTagXmlStruct::ToXml(), CIccStructNamedColor::Validate(), CIccStructBRDF::Validate(), and CIccStructColorantInfo::Validate().
FindElemOfType()
CIccTag * CIccTagStruct::FindElemOfType (icSignature sig, icTagTypeSignature sigType)
Name: CIccTagStruct::FindElemOfType
Purpose: Finds the tag object associated with the struct entry with the given signature that has a specific tag type.
Args: sig - element signature to find sigType - signature of desired tag type
Return: The desired tag object, or NULL if unable to find in the struct
{
  IccTagEntry *pEntry = GetElem(sig);
  if (pEntry && pEntry->pTag && pEntry->pTag->GetType()==sigType) {
    return pEntry->pTag;
  }
  return NULL;
}
References GetElem(), and CIccTag::GetType().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), and icGetParamFloatNum().
GetClassName()
virtual const icChar * CIccTagStruct::GetClassName () const inline virtual
Reimplemented from CIccTag.
Reimplemented in CIccTagXmlStruct.
{ return "CIccTagStruct"; }
GetElem() [1/2]
IccTagEntry * CIccTagStruct::GetElem (CIccTag * pTag) const protected
Name: CIccTagStruct::GetElem
Purpose: Finds the first tag entry that points to the indicated tag object
Args: pTag - pointer to tag object desired to be found
Return: pointer to first tag struct entry that points to the desired tag object, or NULL if tag object is not pointed to by any tag struct entries.
{
  TagEntryList::const_iterator i;
  for (i=m_ElemEntries->begin(); i!=m_ElemEntries->end(); i++) {
    if (i->pTag==pTag)
      return (IccTagEntry*)&(i->TagInfo);
  }
  return NULL;
}
References m_ElemEntries.
Referenced by DeleteElem().
GetElem() [2/2]
IccTagEntry * CIccTagStruct::GetElem (icSignature sig) const protected
Name: CIccTagStruct::GetElem
Purpose: Get a tag entry with a given signature
Args: sig - signature id to find in tag structure
Return: Pointer to desired tag struct entry, or NULL if not found.
{
  TagEntryList::const_iterator i;
  for (i=m_ElemEntries->begin(); i!=m_ElemEntries->end(); i++) {
    if (i->TagInfo.sig==sig)
      return (IccTagEntry*)&(i->TagInfo);
  }
  return NULL;
}
References m_ElemEntries, and icTag::sig.
Referenced by AttachElem(), FindElem(), and FindElemOfType().
GetElemList()
TagEntryList * CIccTagStruct::GetElemList () inline
{ return m_ElemEntries; }
References m_ElemEntries.
Referenced by CIccStructUnknown::Describe(), IIccStruct::Describe(), and icConvertEncodingProfile().
GetElemName()
static std::string CIccTagStruct::GetElemName (icTagSignature sig, icStructSignature sigThis) static
GetElemNumberValue()
icFloatNumber CIccTagStruct::GetElemNumberValue (icSignature sig, icFloatNumber defaultValue = 0)
Name: CIccTagStruct::GetElemNumberValue
Purpose: Returns the number value associated with the first entry of a CIccTagNumberArray based tag with the given signature.
Args: sig - subtag signature to find defaultValue - value to use if the tag cannot be found, or is not a number tag
Return: The tags value or defaultValue if unable to find subtag in the struct or if the subtag is not a CIccTagNumberArray based tag.
{
  CIccTag *pTag = FindElem(sig);
  if (!pTag || !pTag->IsNumArrayType())
    return defaultValue;
  CIccTagNumArray *pNumArray = (CIccTagNumArray*)pTag;
  icFloatNumber rv = defaultValue;
  pNumArray->GetValues(&rv, 0, 1);
  return rv;
}
References FindElem(), CIccTagNumArray::GetValues(), and CIccTag::IsNumArrayType().
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams().
GetExtension()
virtual IIccExtensionTag * CIccTag::GetExtension () inline virtual inherited
Reimplemented in CIccTagXmlUnknown, CIccTagXmlText, CIccTagXmlUtf8Text, CIccTagXmlZipUtf8Text, CIccTagXmlZipXml, CIccTagXmlUtf16Text, CIccTagXmlTextDescription, CIccTagXmlSignature, CIccTagXmlNamedColor2, CIccTagXmlXYZ, CIccTagXmlChromaticity, CIccTagXmlCicp, CIccTagXmlSparseMatrixArray, CIccTagXmlFixedNum< T, Tsig >, CIccTagXmlNum< T, A, Tsig >, CIccTagXmlFloatNum< T, A, Tsig >, CIccTagXmlMeasurement, CIccTagXmlMultiLocalizedUnicode, CIccTagXmlTagData, CIccTagXmlDateTime, CIccTagXmlColorantOrder, CIccTagXmlColorantTable, CIccTagXmlViewingConditions, CIccTagXmlSpectralDataInfo, CIccTagXmlSpectralViewingConditions, CIccTagXmlProfileSeqDesc, CIccTagXmlResponseCurveSet16, CIccTagXmlCurve, CIccTagXmlParametricCurve, CIccTagXmlSegmentedCurve, CIccTagXmlLutAtoB, CIccTagXmlLutBtoA, CIccTagXmlLut8, CIccTagXmlLut16, CIccTagXmlMultiProcessElement, CIccTagXmlProfileSequenceId, CIccTagXmlDict, CIccTagXmlStruct, CIccTagXmlArray, CIccTagXmlGamutBoundaryDesc, CIccTagXmlEmbeddedHeightImage, CIccTagXmlEmbeddedNormalImage, and CIccTagXmlEmbeddedProfile.
{return NULL;}
Referenced by icCurvesFromXml(), icCurvesToXml(), icProfDescToXml(), icXmlParseProfDesc(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccMpeXmlTintArray::ToXml(), CIccTagXmlStruct::ToXml(), CIccTagXmlArray::ToXml(), and CIccProfileXml::ToXmlWithBlanks().
GetStructHandler()
IIccStruct * CIccTagStruct::GetStructHandler ()
Name: CIccTagStruct::GetStructHandler
Purpose: Get struct object handler
Args:
Return: Pointer to a IIccStruct object handler for the associated struct type
{
  if (!m_pStruct) {
    m_pStruct = CIccStructCreator::CreateStruct(m_sigStructType, this);
  }
  return m_pStruct;
}
References CIccStructCreator::CreateStruct(), m_pStruct, and m_sigStructType.
Referenced by icGetTagStructHandler(), CIccTagXmlStruct::ToXml(), and CIccArrayNamedColor::Validate().
GetTagArrayType()
virtual icArraySignature CIccTag::GetTagArrayType () const inline virtual inherited
Reimplemented in CIccTagArray.
{ return icSigUndefinedArray; }
References icSigUndefinedArray.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
GetTagStructType()
virtual icStructSignature CIccTagStruct::GetTagStructType () const inline virtual
Reimplemented from CIccTag.
{ return m_sigStructType; }
References m_sigStructType.
Referenced by CIccDefaultEncProfileConverter::ConvertFromParams(), IIccStruct::Describe(), and CIccStructNamedColor::Validate().
GetType()
virtual icTagTypeSignature CIccTagStruct::GetType () const inline virtual
Function: GetType()
Purpose: Get Tag Type. Each derived tag will implement it's own GetType() function.
Reimplemented from CIccTag.
{ return icSigTagStructType; }
References icSigTagStructType.
Referenced by Write().
IsArrayType()
virtual bool CIccTag::IsArrayType () inline virtual inherited
Reimplemented in CIccTagXYZ, CIccTagChromaticity, CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, CIccTagFloatNum< T, Tsig >, and CIccTagData.
{ return false; }
Referenced by MyTagDialog::MyTagDialog(), and DumpTag().
IsMBBType()
virtual bool CIccTag::IsMBBType () inline virtual inherited
Reimplemented in CIccMBB.
{ return false; } //If true then CIccTag can be cast as an CIccMBB
Referenced by CIccProfileXml::ParseTag().
IsNumArrayType()
virtual bool CIccTag::IsNumArrayType () const inline virtual inherited
Reimplemented in CIccTagSparseMatrixArray, CIccTagFixedNum< T, Tsig >, CIccTagNum< T, Tsig >, and CIccTagFloatNum< T, Tsig >.
{ return false;} //If true then CIccTag can be cast as a CIccTagNumArray
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), GetElemNumberValue(), CIccStructNamedColor::GetNumArray(), CIccMpeXmlTintArray::ParseXml(), and CIccMpeTintArray::Read().
IsSupported()
virtual bool CIccTag::IsSupported () inline virtual inherited
Function: IsSupported(size, pIO) - Check if tag fully supported for apply purposes. By Default inherited classes are supported. Unknown tag types are not supported.
Returns true if tag type is supported.
Reimplemented in CIccTagUnknown, CIccTagEmbeddedProfile, and CIccTagMultiProcessElement.
{ return true; }
LoadElem()
bool CIccTagStruct::LoadElem (IccTagEntry * pTagEntry, CIccIO * pIO) protected
Name: CIccTagStruct::LoadSubTag
Purpose: This will load from the indicated IO object and associate a tag object to a tag directory entry. Nothing happens if tag directory entry is associated with a tag object.
Args: pTagEntry - pointer to tag directory entry, pIO - pointer to IO object to read tag object data from
Return: true - tag directory object associated with tag directory entry, false - failure
{
  if (!pTagEntry)
    return false;
  if (pTagEntry->pTag)
    return true;
  icUInt32Number headerSize = sizeof(icTagTypeSignature) +
    sizeof(icUInt32Number) +
    sizeof(icUInt32Number);
  if (pTagEntry->TagInfo.offset<headerSize ||
      !pTagEntry->TagInfo.size ||
      pTagEntry->TagInfo.offset+pTagEntry->TagInfo.size > m_tagSize) {
    return false;
  }
  icTagTypeSignature sigType;
  icUInt32Number offset = pTagEntry->TagInfo.offset + m_tagStart;
  //First we need to get the tag type to create the right kind of tag
  if (pIO->Seek(offset, icSeekSet)!=offset)
    return false;
  if (!pIO->Read32(&sigType))
    return false;
  CIccTag *pTag = CIccTag::Create(sigType);
  if (!pTag)
    return false;
  //Now seek back to where the tag starts so the created tag object can read
  //in its data.
  //First we need to get the tag type to create the right kind of tag
  if (pIO->Seek(offset, icSeekSet)!=offset) {
    delete pTag;
    return false;
  }
  if (!pTag->Read(pTagEntry->TagInfo.size, pIO)) {
    delete pTag;
    return false;
  }
  pTagEntry->pTag = pTag;
  IccTagPtr TagPtr;
  TagPtr.ptr = pTag;
  m_ElemVals->push_back(TagPtr);
  TagEntryList::iterator i;
  for (i=m_ElemEntries->begin(); i!= m_ElemEntries->end(); i++) {
    if (i->TagInfo.offset == pTagEntry->TagInfo.offset &&
        i->pTag != pTag)
      i->pTag = pTag;
  }
  return true;
}
References CIccTag::Create(), icSeekSet, m_ElemEntries, m_ElemVals, m_tagSize, m_tagStart, icTag::offset, CIccTag::Read(), CIccIO::Read32(), CIccIO::Seek(), and icTag::size.
Referenced by Read().
NewCopy()
virtual CIccTag * CIccTagStruct::NewCopy () const inline virtual
Function: NewCopy(sDescription) Each derived tag will implement it's own NewCopy() function.
Parameter(s): none
Returns a new CIccTag object that is a copy of this object.
Reimplemented from CIccTag.
{ return new CIccTagStruct(*this);}
References CIccTagStruct().
operator=()
CIccTagStruct & CIccTagStruct::operator= (const CIccTagStruct & subTags)
Name: &operator=
Purpose:
Args:
Return:
{
  if (&subTags == this)
    return *this;
  Cleanup();
  m_sigStructType = subTags.m_sigStructType;
  if (!subTags.m_ElemEntries->empty()) {
    m_ElemEntries->clear();
    TagEntryList::const_iterator i;
    IccTagEntry entry;
    for (i=subTags.m_ElemEntries->begin(); i!=subTags.m_ElemEntries->end(); i++) {
      entry.pTag = i->pTag->NewCopy();
      memcpy(&entry.TagInfo, &i->TagInfo, sizeof(icTag));
      m_ElemEntries->push_back(entry);
    }
  }
  if (!subTags.m_ElemVals->empty()) {
    m_ElemVals->clear();
    TagPtrList::const_iterator i;
    IccTagPtr tagptr;
    for (i=subTags.m_ElemVals->begin(); i!=subTags.m_ElemVals->end(); i++) {
      tagptr.ptr = i->ptr->NewCopy();
      m_ElemVals->push_back(tagptr);
    }
  }
  if (subTags.m_pStruct)
    m_pStruct = subTags.m_pStruct->NewCopy(this);
  else
    m_pStruct = NULL;
  return *this;
}
References Cleanup(), m_ElemEntries, m_ElemVals, m_pStruct, m_sigStructType, CIccTag::NewCopy(), and IIccStruct::NewCopy().
ParseMem()
CIccTagStruct * CIccTagStruct::ParseMem (icUInt8Number * pMem, icUInt32Number size) static
Name: CIccTagStruct::ParseMem
Purpose:
Args:
Return:
{
  CIccMemIO IO;
  if (!IO.Attach(pMem, size))
    return NULL;
  CIccTagStruct *pTags = new CIccTagStruct;
  if (!pTags->Read(size, &IO)) {
    delete pTags;
    return NULL;
  }
  return pTags;
}
References CIccMemIO::Attach(), and Read().
Read() [1/2]
bool CIccTagStruct::Read (icUInt32Number size, CIccIO * pIO) virtual
Name: CIccTagStruct::Read
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icTagTypeSignature sig;
  m_tagSize = size;
  icUInt32Number headerSize = sizeof(icTagTypeSignature) +
    sizeof(icUInt32Number) +
    sizeof(icStructSignature) +
    sizeof(icUInt32Number);
  if (headerSize > size)
    return false;
  if (!pIO) {
    return false;
  }
  Cleanup();
  m_tagStart = pIO->Tell();
  if (!pIO->Read32(&sig))
    return false;
  if (!pIO->Read32(&m_nReserved))
    return false;
  icStructSignature sigStructType;
  if (!pIO->Read32(&sigStructType))
    return false;
  SetTagStructType(sigStructType);
  icUInt32Number count, i;
  IccTagEntry TagEntry;
  TagEntry.pTag = NULL;
  if (!pIO->Read32(&count))
    return false;
  if (headerSize + (icUInt64Number)count*sizeof(icUInt32Number)*3 > size)
    return false;
  //Read TagDir
  for (i=0; i<count; i++) {
    if (!pIO->Read32(&TagEntry.TagInfo.sig) ||
        !pIO->Read32(&TagEntry.TagInfo.offset) ||
        !pIO->Read32(&TagEntry.TagInfo.size)) {
      return false;
    }
    m_ElemEntries->push_back(TagEntry);
  }
  TagEntryList::iterator entry;
  for (entry=m_ElemEntries->begin(); entry!=m_ElemEntries->end(); entry++) {
    if (!LoadElem((IccTagEntry*)&(entry->TagInfo), pIO)) {
      Cleanup();
      return false;
    }
  }
  return true;
}
References Cleanup(), LoadElem(), m_ElemEntries, CIccTag::m_nReserved, m_tagSize, m_tagStart, icTag::offset, CIccIO::Read32(), SetTagStructType(), icTag::sig, icTag::size, and CIccIO::Tell().
Referenced by ParseMem().
Read() [2/2]
virtual bool CIccTag::Read (icUInt32Number size, CIccIO * pIO, CIccProfile * pProfile) inline virtual inherited
Function: Read(size, pIO) - Read tag from file. Each derived tag will implement it's own Read() function.
Parameter(s): size - number of bytes in tag including the type signature. pIO - IO object used to read in tag. The IO object should already be initialized to point to the begining of the tag.
Returns true if Read is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return Read(size, pIO); }
References CIccTag::Read().
ReadAll()
virtual bool CIccTag::ReadAll () inline virtual inherited
Function: ReadAll() - Read All sub data for tag from file. Called by CIccProfile::ReadAll() to read all sub data for tag
Returns true if ReadAll is successful.
Reimplemented in CIccTagEmbeddedProfile.
{ return true; }
SetTagStructType()
bool CIccTagStruct::SetTagStructType (icStructSignature sig) virtual
Name: CIccTagStruct::SetTagStructType
Purpose:
Args:
Return:
{
  if (m_pStruct)
    delete m_pStruct;
  m_sigStructType = sig;
  m_pStruct = CIccStructCreator::CreateStruct(m_sigStructType, this);
  return m_pStruct != NULL;
}
References CIccStructCreator::CreateStruct(), m_pStruct, and m_sigStructType.
Referenced by CIccTagXmlStruct::ParseXml(), and Read().
Validate()
icValidateStatus CIccTagStruct::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual
Name: CIccTagStruct::Validate
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icValidateStatus rv = CIccTag::Validate(sigPath, sReport, pProfile);
  CIccInfo Info;
  std::string sSigPathName = Info.GetSigPathName(sigPath);
  // Check for duplicate tags
  if (!AreElemsUnique()) {
    sReport += icMsgValidateWarning;
    sReport += sSigPathName;
    sReport += " - There are duplicate elements.\n";
    rv =icMaxStatus(rv, icValidateWarning);
  }
  if (m_pStruct) {  //Should call GetStructHandler before validate to get
    rv = icMaxStatus(rv, m_pStruct->Validate(sigPath, sReport, pProfile));
  }
  else {
    sReport += "Unknown tag struct type - Validating struct sub-tags\n";
    rv = icMaxStatus(rv, icValidateWarning);
    // Per Tag tests
    TagEntryList::iterator i;
    for (i = m_ElemEntries->begin(); i != m_ElemEntries->end(); i++) {
      rv = icMaxStatus(rv, i->pTag->Validate(sigPath + icGetSigPath(i->TagInfo.sig), sReport, pProfile));
    }
  }
  return rv;
}
References AreElemsUnique(), CIccInfo::GetSigPathName(), icGetSigPath(), icMaxStatus(), icMsgValidateWarning, icValidateWarning, m_ElemEntries, m_pStruct, icTag::sig, CIccTag::Validate(), and IIccStruct::Validate().
Write()
bool CIccTagStruct::Write (CIccIO * pIO) virtual
Name: CIccTagStruct::Write
Purpose:
Args:
Return:
Reimplemented from CIccTag.
{
  icTagTypeSignature sig = GetType();
  if (!pIO)
    return false;
  m_tagStart = pIO->Tell();
  if (!pIO->Write32(&sig))
    return false;
  if (!pIO->Write32(&m_nReserved))
    return false;
  if (!pIO->Write32(&m_sigStructType))
    return false;
  TagEntryList::iterator i, j;
  icUInt32Number count;
  for (count=0, i=m_ElemEntries->begin(); i!= m_ElemEntries->end(); i++) {
    if (i->pTag)
      count++;
  }
  pIO->Write32(&count);
  icUInt32Number dirpos = pIO->Tell();
  //Write Unintialized TagDir
  for (i=m_ElemEntries->begin(); i!= m_ElemEntries->end(); i++) {
    if (i->pTag) {
      i->TagInfo.offset = 0;
      i->TagInfo.size = 0;
      pIO->Write32(&i->TagInfo.sig);
      pIO->Write32(&i->TagInfo.offset);
      pIO->Write32(&i->TagInfo.size);
    }
  }
  //Write Tags
  for (i=m_ElemEntries->begin(); i!= m_ElemEntries->end(); i++) {
    if (i->pTag) {
      for (j=m_ElemEntries->begin(); j!=i; j++) {
        if (i->pTag == j->pTag)
          break;
      }
      if (i==j) {
        i->TagInfo.offset = pIO->GetLength();
        i->pTag->Write(pIO);
        i->TagInfo.size = pIO->GetLength() - i->TagInfo.offset;
        i->TagInfo.offset -= m_tagStart;
        pIO->Align32();
      }
      else {
        i->TagInfo.offset = j->TagInfo.offset;
        i->TagInfo.size = j->TagInfo.size;
      }
    }
  }
  icUInt32Number epos = pIO->Tell();
  pIO->Seek(dirpos, icSeekSet);
  //Write TagDir with offsets and sizes
  for (i=m_ElemEntries->begin(); i!= m_ElemEntries->end(); i++) {
    if (i->pTag) {
      pIO->Write32(&i->TagInfo.sig);
      pIO->Write32(&i->TagInfo.offset);
      pIO->Write32(&i->TagInfo.size);
    }
  }
  pIO->Seek(epos, icSeekSet);
  return true;
}
References CIccIO::Align32(), CIccIO::GetLength(), GetType(), icSeekSet, m_ElemEntries, CIccTag::m_nReserved, m_sigStructType, m_tagStart, icTag::offset, CIccIO::Seek(), icTag::sig, icTag::size, CIccIO::Tell(), CIccTag::Write(), and CIccIO::Write32().
Field Documentation
m_ElemEntries
TagEntryList* CIccTagStruct::m_ElemEntries protected
Referenced by CIccTagStruct(), CIccTagStruct(), ~CIccTagStruct(), AreElemsUnique(), AttachElem(), Cleanup(), DeleteElem(), DetachElem(), GetElem(), GetElem(), GetElemList(), IIccStruct::getTagEntries(), LoadElem(), operator=(), Read(), CIccTagXmlStruct::ToXml(), Validate(), and Write().
m_ElemVals
TagPtrList* CIccTagStruct::m_ElemVals protected
Referenced by CIccTagStruct(), CIccTagStruct(), ~CIccTagStruct(), AttachElem(), Cleanup(), DetachElem(), LoadElem(), and operator=().
m_nReserved
icUInt32Number CIccTag::m_nReserved inherited
Referenced by CIccTag::CIccTag(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::CIccTagMultiProcessElement(), CIccTagMultiProcessElement::operator=(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), CIccTagText::Read(), CIccTagUtf8Text::Read(), CIccTagZipUtf8Text::Read(), CIccTagUtf16Text::Read(), CIccTagTextDescription::Read(), CIccTagSignature::Read(), CIccTagNamedColor2::Read(), CIccTagXYZ::Read(), CIccTagChromaticity::Read(), CIccTagCicp::Read(), CIccTagSparseMatrixArray::Read(), CIccTagFixedNum< T, Tsig >::Read(), CIccTagNum< T, Tsig >::Read(), CIccTagFloatNum< T, Tsig >::Read(), CIccTagMeasurement::Read(), CIccTagMultiLocalizedUnicode::Read(), CIccTagData::Read(), CIccTagDateTime::Read(), CIccTagColorantOrder::Read(), CIccTagColorantTable::Read(), CIccTagViewingConditions::Read(), CIccTagProfileSeqDesc::Read(), CIccTagResponseCurveSet16::Read(), CIccTagSpectralDataInfo::Read(), CIccTagSpectralViewingConditions::Read(), CIccTagEmbeddedHeightImage::Read(), CIccTagEmbeddedNormalImage::Read(), Read(), CIccTagArray::Read(), CIccTagDict::Read(), CIccTagCurve::Read(), CIccTagParametricCurve::Read(), CIccTagLutAtoB::Read(), CIccTagLut8::Read(), CIccTagLut16::Read(), CIccTagGamutBoundaryDesc::Read(), CIccTagMultiProcessElement::Read(), CIccTagProfileSequenceId::Read(), CIccTagEmbeddedProfile::Read(), CIccTag::Validate(), CIccTagText::Write(), CIccTagUtf8Text::Write(), CIccTagZipUtf8Text::Write(), CIccTagUtf16Text::Write(), CIccTagTextDescription::Write(), CIccTagSignature::Write(), CIccTagNamedColor2::Write(), CIccTagXYZ::Write(), CIccTagChromaticity::Write(), CIccTagCicp::Write(), CIccTagSparseMatrixArray::Write(), CIccTagFixedNum< T, Tsig >::Write(), CIccTagNum< T, Tsig >::Write(), CIccTagFloatNum< T, Tsig >::Write(), CIccTagMeasurement::Write(), CIccTagMultiLocalizedUnicode::Write(), CIccTagData::Write(), CIccTagDateTime::Write(), CIccTagColorantOrder::Write(), CIccTagColorantTable::Write(), CIccTagViewingConditions::Write(), CIccTagProfileSeqDesc::Write(), CIccTagResponseCurveSet16::Write(), CIccTagSpectralDataInfo::Write(), CIccTagSpectralViewingConditions::Write(), CIccTagEmbeddedHeightImage::Write(), CIccTagEmbeddedNormalImage::Write(), Write(), CIccTagArray::Write(), CIccTagDict::Write(), CIccTagEmbeddedProfile::Write(), CIccTagCurve::Write(), CIccTagParametricCurve::Write(), CIccTagLutAtoB::Write(), CIccTagLut8::Write(), CIccTagLut16::Write(), CIccTagGamutBoundaryDesc::Write(), CIccTagMultiProcessElement::Write(), and CIccTagProfileSequenceId::Write().
m_pStruct
IIccStruct* CIccTagStruct::m_pStruct protected
Referenced by CIccTagStruct(), CIccTagStruct(), ~CIccTagStruct(), Cleanup(), Describe(), GetStructHandler(), operator=(), CIccTagXmlStruct::ParseTag(), SetTagStructType(), and Validate().
m_sigStructType
icStructSignature CIccTagStruct::m_sigStructType protected
Referenced by CIccTagStruct(), Cleanup(), Describe(), GetStructHandler(), GetTagStructType(), operator=(), SetTagStructType(), CIccTagXmlStruct::ToXml(), and Write().
m_tagSize
icUInt32Number CIccTagStruct::m_tagSize protected
Referenced by LoadElem(), and Read().
m_tagStart
icUInt32Number CIccTagStruct::m_tagStart protected
Referenced by LoadElem(), Read(), and Write().
The documentation for this class was generated from the following files:
IccProfLib/IccTagComposite.h
IccProfLib/IccTagComposite.cpp