iccDEV: IIccExtensionTag Class Reference
IIccExtensionTag Class Reference abstract
#include <IccTagBasic.h>
Public Member Functions
virtual const char * GetExtClassName () const =0
virtual const char * GetExtDerivedClassName () const =0
Detailed Description
Member Function Documentation
GetExtClassName()
virtual const char * IIccExtensionTag::GetExtClassName () const pure virtual
Implemented in CIccTagXml.
Referenced by icCurvesFromXml(), CIccProfileXml::ParseTag(), CIccTagXmlStruct::ParseTag(), CIccMpeXmlTintArray::ParseXml(), CIccTagXmlArray::ParseXml(), and CIccMpeXmlTintArray::ToXml().
GetExtDerivedClassName()
virtual const char * IIccExtensionTag::GetExtDerivedClassName () const pure virtual
Implemented in CIccTagXml, and CIccCurveXml.
Referenced by icCurvesFromXml(), and icCurvesToXml().
The documentation for this class was generated from the following file:
IccProfLib/IccTagBasic.h