iccDEV: CIccCmmEnvVarWrapperHint Class Reference
CIccCmmEnvVarWrapperHint Class Reference
Inherits CIccCreateCmmEnvVarXformHint.
Public Member Functions
CIccCmmEnvVarWrapperHint (SIccCmmEnvVars *pVars)
virtual IIccCmmEnvVarLookup * GetNewCmmEnvVarLookup () const
Protected Attributes
SIccCmmEnvVars * m_pVars
Detailed Description
Constructor & Destructor Documentation
CIccCmmEnvVarWrapperHint()
CIccCmmEnvVarWrapperHint::CIccCmmEnvVarWrapperHint (SIccCmmEnvVars * pVars) inline
{ m_pVars = pVars; }
References m_pVars.
Referenced by IccCmmAttachProfileFile(), and IccCmmAttachProfileHandle().
Member Function Documentation
GetNewCmmEnvVarLookup()
virtual IIccCmmEnvVarLookup * CIccCmmEnvVarWrapperHint::GetNewCmmEnvVarLookup () const inline virtual
{ return new CIccCmmEnvVarsWrapper(m_pVars); }
References CIccCmmEnvVarsWrapper::CIccCmmEnvVarsWrapper(), and m_pVars.
Field Documentation
m_pVars
SIccCmmEnvVars* CIccCmmEnvVarWrapperHint::m_pVars protected
Referenced by CIccCmmEnvVarWrapperHint(), and GetNewCmmEnvVarLookup().
The documentation for this class was generated from the following file:
IccProfLib/IccWrapper.cpp