iccDEV: CIccStructMeasurementInfo Class Reference
CIccStructMeasurementInfo Class Reference
#include <IccStructBasic.h>
Public Member Functions
CIccStructMeasurementInfo (CIccTagStruct *pTagStruct=NULL)
virtual ~CIccStructMeasurementInfo ()
virtual void Describe (std::string &sDescription, int nVerboseness) const
virtual const icChar * GetClassName () const
virtual const icChar * GetDisplayName () const
CIccTag * GetElem (icSignature sigElem) const
virtual std::string GetElemName (icSignature sigElem) const
virtual icSignature GetElemSig (const icChar *szElemName) const
CIccTagStruct * GetTagStruct ()
virtual IIccStruct * NewCopy (CIccTagStruct *pNewTagStruct) const
virtual icValidateStatus Validate (std::string sigPath, std::string &sReport, const CIccProfile *pProfile=NULL) const
Protected Member Functions
TagEntryList * getTagEntries () const
Protected Attributes
SIccElemNameSig * m_pElemNameSigTable
CIccTagStruct * m_pTagStruct
Detailed Description
Class: CIccStructMeasurementInfo
Purpose: The Named Color struct handler
Constructor & Destructor Documentation
CIccStructMeasurementInfo()
CIccStructMeasurementInfo::CIccStructMeasurementInfo (CIccTagStruct * pTagStruct = NULL)
{
  m_pTagStruct= pTagStruct;
  m_pElemNameSigTable = g_IccStructMeasurementInfoElemTable;
}
References g_IccStructMeasurementInfoElemTable, CIccStructUnknown::m_pElemNameSigTable, and IIccStruct::m_pTagStruct.
Referenced by CIccBasicStructFactory::CreateStruct(), and NewCopy().
~CIccStructMeasurementInfo()
CIccStructMeasurementInfo::~CIccStructMeasurementInfo () virtual
{
}
Member Function Documentation
Describe()
void CIccStructUnknown::Describe (std::string & sDescription, int nVerboseness) const virtual inherited
Reimplemented from IIccStruct.
{
  char buf[256];
  CIccInfo info;
  int n;
  if (m_pTagStruct) {
    TagEntryList *entries = m_pTagStruct->GetElemList();
    TagEntryList::iterator i;
    for (n=0, i=entries->begin(); i!=entries->end(); n++, i++) {
      if (i->pTag) {
        if (n)
          sDescription += "\n";
        sprintf(buf, "Begin SubTag(%s)\n", GetElemName(i->TagInfo.sig).c_str());
        sDescription += buf;
        i->pTag->Describe(sDescription, nVerboseness);
        sprintf(buf, "End SubTag(%s)\n", GetElemName(i->TagInfo.sig).c_str());
        sDescription += buf;
      }
    }
  }
}
References CIccTag::Describe(), CIccTagStruct::GetElemList(), CIccStructUnknown::GetElemName(), IIccStruct::m_pTagStruct, and icTag::sig.
Referenced by CIccTagStruct::Describe().
GetClassName()
virtual const icChar * CIccStructMeasurementInfo::GetClassName () const inline virtual
Reimplemented from CIccStructUnknown.
{ return "CIccStructMeasurementInfo"; }
GetDisplayName()
virtual const icChar * CIccStructMeasurementInfo::GetDisplayName () const inline virtual
Reimplemented from CIccStructUnknown.
{ return "measurementInfoStructure"; }
GetElem()
CIccTag * CIccStructUnknown::GetElem (icSignature sigElem) const inherited
{
  if (!m_pTagStruct)
    return NULL;
  return m_pTagStruct->FindElem(sigElem);
}
References CIccTagStruct::FindElem(), and IIccStruct::m_pTagStruct.
Referenced by CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), CIccArrayNamedColor::FindSpectralColor(), CIccStructBRDF::GetBRDFFunction(), CIccStructBRDF::GetBRDFType(), and CIccStructNamedColor::GetNumArray().
GetElemName()
std::string CIccStructUnknown::GetElemName (icSignature sigElem) const virtual inherited
Implements IIccStruct.
{
  if (m_pElemNameSigTable) {
    int i;
    for (i = 0; m_pElemNameSigTable[i].szName; i++) {
      if (m_pElemNameSigTable[i].nSig == sigElem)
        return m_pElemNameSigTable[i].szName;
    }
  }
  CIccInfo info;
  std::string str;
  str = "PrivateSubTag";
  //str += info.GetSigName(sigElem);
  return str;
}
References CIccStructUnknown::m_pElemNameSigTable, SIccElemNameSig::nSig, and SIccElemNameSig::szName.
Referenced by CIccStructUnknown::Describe().
GetElemSig()
icSignature CIccStructUnknown::GetElemSig (const icChar * szElemName) const virtual inherited
Implements IIccStruct.
{
  if (m_pElemNameSigTable) {
    int i;
    for (i = 0; m_pElemNameSigTable[i].szName; i++) {
      if (!strcmp(m_pElemNameSigTable[i].szName, szElemName))
        return m_pElemNameSigTable[i].nSig;
    }
  }
  return (icSignature)0;
}
References CIccStructUnknown::m_pElemNameSigTable, SIccElemNameSig::nSig, and SIccElemNameSig::szName.
getTagEntries()
TagEntryList * IIccStruct::getTagEntries () const protected inherited
{
  if (m_pTagStruct)
    return m_pTagStruct->m_ElemEntries;
  return NULL;
}
References CIccTagStruct::m_ElemEntries, and IIccStruct::m_pTagStruct.
Referenced by CIccStructUnknown::Validate().
GetTagStruct()
CIccTagStruct * IIccStruct::GetTagStruct () inline inherited
{ return m_pTagStruct; }
References IIccStruct::m_pTagStruct.
NewCopy()
IIccStruct * CIccStructMeasurementInfo::NewCopy (CIccTagStruct * pNewTagStruct) const virtual
Reimplemented from CIccStructUnknown.
{
  CIccStructMeasurementInfo *rv = new CIccStructMeasurementInfo(pTagStruct);
  return rv;
}
References CIccStructMeasurementInfo().
Validate()
icValidateStatus CIccStructUnknown::Validate (std::string sigPath, std::string & sReport, const CIccProfile * pProfile = NULL) const virtual inherited
Implements IIccStruct.
Reimplemented in CIccStructNamedColor, CIccStructBRDF, and CIccStructColorantInfo.
{
  icValidateStatus rv = icValidateOK;
  TagEntryList *pList = getTagEntries();
  if (pList) {
    // Per Tag tests
    TagEntryList::iterator i;
    for (i = pList->begin(); i != pList->end(); i++) {
      if (i->pTag)
        rv = icMaxStatus(rv, i->pTag->Validate(sigPath + icGetSigPath(i->TagInfo.sig), sReport, pProfile));
    }
  }
  else {
    sReport += "Struct Handler not connected to CIccTagStruct object with valid sub-tags!";
    rv = icValidateWarning;
  }
  return rv;
}
References IIccStruct::getTagEntries(), icGetSigPath(), icMaxStatus(), icValidateOK, icValidateWarning, icTag::sig, and CIccTag::Validate().
Referenced by CIccStructNamedColor::Validate(), CIccStructBRDF::Validate(), and CIccStructColorantInfo::Validate().
Field Documentation
m_pElemNameSigTable
SIccElemNameSig* CIccStructUnknown::m_pElemNameSigTable protected inherited
Referenced by CIccStructBRDF::CIccStructBRDF(), CIccStructColorantInfo::CIccStructColorantInfo(), CIccStructColorEncodingParams::CIccStructColorEncodingParams(), CIccStructMeasurementInfo(), CIccStructNamedColor::CIccStructNamedColor(), CIccStructProfileInfo::CIccStructProfileInfo(), CIccStructTintZero::CIccStructTintZero(), CIccStructUnknown::CIccStructUnknown(), CIccStructUnknown::GetElemName(), and CIccStructUnknown::GetElemSig().
m_pTagStruct
CIccTagStruct* IIccStruct::m_pTagStruct protected inherited
Referenced by CIccStructBRDF::CIccStructBRDF(), CIccStructColorantInfo::CIccStructColorantInfo(), CIccStructColorEncodingParams::CIccStructColorEncodingParams(), CIccStructMeasurementInfo(), CIccStructNamedColor::CIccStructNamedColor(), CIccStructProfileInfo::CIccStructProfileInfo(), CIccStructTintZero::CIccStructTintZero(), CIccStructUnknown::CIccStructUnknown(), CIccStructUnknown::Describe(), IIccStruct::Describe(), CIccStructUnknown::GetElem(), CIccStructNamedColor::getName(), IIccStruct::getTagEntries(), IIccStruct::GetTagStruct(), CIccStructNamedColor::Validate(), CIccStructBRDF::Validate(), and CIccStructColorantInfo::Validate().
The documentation for this class was generated from the following files:
IccProfLib/IccStructBasic.h
IccProfLib/IccStructBasic.cpp