iccDEV: IccProfLib/IccTagComposite.cpp File Reference
IccTagComposite.cpp File Reference
#include <stdio.h>
#include <math.h>
#include <string.h>
#include <stdlib.h>
#include "IccTagComposite.h"
#include "IccStructBasic.h"
#include "IccUtil.h"
#include "IccIO.h"
#include "IccStructFactory.h"
#include "IccArrayFactory.h"
Functions
IIccArray * icGetTagArrayHandler (CIccTag *pTag)
IIccArray * icGetTagArrayHandlerOfType (CIccTag *pTag, icArraySignature sig)
IIccStruct * icGetTagStructHandler (CIccTag *pTag)
IIccStruct * icGetTagStructHandlerOfType (CIccTag *pTag, icStructSignature sig)
Detailed Description
File: IccTagComposite.cpp
Contains: Implementation of Struct and Array Tags
Version: V1
Copyright: (c) see ICC Software License
Definition in file IccTagComposite.cpp.
Function Documentation
icGetTagArrayHandler()
IIccArray * icGetTagArrayHandler (CIccTag * pTag)
{
  if (!pTag)
    return NULL;
  if (pTag->GetType()!=icSigTagArrayType)
    return NULL;
  CIccTagArray *pArray = (CIccTagArray*)pTag;
  return pArray->GetArrayHandler();
}
References CIccTagArray::GetArrayHandler(), CIccTag::GetType(), and icSigTagArrayType.
Referenced by icGetTagArrayHandlerOfType(), and CIccProfileXml::ParseTag().
icGetTagArrayHandlerOfType()
IIccArray * icGetTagArrayHandlerOfType (CIccTag * pTag, icArraySignature sig)
{
  if (pTag->GetTagArrayType()==sig)
    return icGetTagArrayHandler(pTag);
  return NULL;
}
References CIccTag::GetTagArrayType(), and icGetTagArrayHandler().
icGetTagStructHandler()
IIccStruct * icGetTagStructHandler (CIccTag * pTag)
{
  if (!pTag)
    return NULL;
  if (pTag->GetType()!=icSigTagStructType)
    return NULL;
  CIccTagStruct *pStruct = (CIccTagStruct*)pTag;
  return pStruct->GetStructHandler();
}
References CIccTagStruct::GetStructHandler(), CIccTag::GetType(), and icSigTagStructType.
Referenced by icGetTagStructHandlerOfType().
icGetTagStructHandlerOfType()
IIccStruct * icGetTagStructHandlerOfType (CIccTag * pTag, icStructSignature sig)
{
  if (pTag->GetTagStructType()==sig)
    return icGetTagStructHandler(pTag);
  return NULL;
}
References CIccTag::GetTagStructType(), and icGetTagStructHandler().
Referenced by CIccArrayNamedColor::Begin(), CIccArrayNamedColor::FindDeviceColor(), CIccArrayNamedColor::FindPcsColor(), and CIccArrayNamedColor::FindSpectralColor().