iccDEV: CIccCfgColorData Class Reference
CIccCfgColorData Class Reference
#include <IccCmmConfig.h>
Public Member Functions
CIccCfgColorData ()
virtual ~CIccCfgColorData ()
bool fromIt8 (const char *filename, bool bReset=false)
bool fromJson (json obj, bool bReset=false)
bool fromLegacy (const char *filename, bool bReset=false)
void reset ()
bool toIt8 (const char *filename, icUInt8Number nDigits, icUInt8Number nPrecision)
void toJson (json &obj) const
bool toLegacy (const char *filename, CIccCfgProfileSequence *pProfiles, icUInt8Number nDigits, icUInt8Number nPrecision, bool bShowDebug=false)
Data Fields
CIccCfgDataEntryList m_data
icFloatColorEncoding m_encoding
icColorSpaceSignature m_space
icFloatColorEncoding m_srcEncoding
icColorSpaceSignature m_srcSpace
Protected Member Functions
void addFields (std::string &dataFormat, int &nFields, int &nSamples, icColorSpaceSignature sig, std::string prefix)
std::string spaceName (icColorSpaceSignature sig)
Detailed Description
Constructor & Destructor Documentation
CIccCfgColorData()
CIccCfgColorData::CIccCfgColorData ()
{
  reset();
}
References reset().
~CIccCfgColorData()
virtual CIccCfgColorData::~CIccCfgColorData () inline virtual
{}
Member Function Documentation
addFields()
void CIccCfgColorData::addFields (std::string & dataFormat, int & nFields, int & nSamples, icColorSpaceSignature sig, std::string prefix) protected
{
  std::string tabStr = "\t";
  char buf[32];
  switch (sig) {
    case icSigRgbData:
      nSamples = 3;
      if (nFields) dataFormat += tabStr;
      dataFormat += prefix + "RGB_R";
      dataFormat += tabStr + prefix + "RGB_G";
      dataFormat += tabStr + prefix + "RGB_B";
      nFields += nSamples;
      return;
    case icSigCmyData:
      nSamples = 3;
      if (nFields) dataFormat += tabStr;
      dataFormat += prefix + "CMY_C";
      dataFormat += tabStr + prefix + "CMY_M";
      dataFormat += tabStr + prefix + "CMY_Y";
      nFields += nSamples;
      return;
    case icSigCmykData:
      nSamples = 4;
      if (nFields) dataFormat += tabStr;
      dataFormat += prefix + "CMYK_C";
      dataFormat += tabStr + prefix + "CMYK_M";
      dataFormat += tabStr + prefix + "CMYK_Y";
      dataFormat += tabStr + prefix + "CMYK_K";
      nFields += nSamples;
      return;
    case icSigDevLabData:
    case icSigLabData:
      nSamples += 3;
      if (nFields) dataFormat += tabStr;
      dataFormat += prefix + "LAB_L";
      dataFormat += tabStr + prefix + "LAB_A";
      dataFormat += tabStr + prefix + "LAB_B";
      nFields += nSamples;
      return;
    case icSigDevXYZData:
    case icSigXYZData:
      nSamples += 3;
      if (nFields) dataFormat += tabStr;
      dataFormat += prefix + "XYZ_X";
      dataFormat += tabStr + prefix + "XYZ_Y";
      dataFormat += tabStr + prefix + "XYZ_Z";
      nFields += 3;
      return;
    case icSigNamedData:
      nSamples += 1;
      if (nFields) dataFormat += tabStr;
      dataFormat += prefix + "TINT";
      nFields += nSamples;
      return;
    default:
      nSamples = icGetSpaceSamples(sig);
      if (nFields) dataFormat += tabStr;
      for (int i = 0; i < nSamples; i++) {
        sprintf(buf, "%dCOLOR_%d", nSamples, i + 1);
        if (i)
          dataFormat += tabStr;
        dataFormat += buf;
      }
      nFields += nSamples;
      return;
  }
}
References icGetSpaceSamples(), icSigCmyData, icSigCmykData, icSigLabData, icSigNamedData, icSigRgbData, and icSigXYZData.
Referenced by toIt8().
fromIt8()
bool CIccCfgColorData::fromIt8 (const char * filename, bool bReset = false)
{
  if (bReset)
    reset();
  CIccIt8Parser f;
  if (!f.open(filename))
    return false;
  std::vector<std::string> line;
  if (!f.findTokenLine(line, "CGATS.17"))
    return false;
  if (!f.findTokenLine(line, "NUBER_OF_FIELDS"))
    return false;
  int nFields = 0;
  if (line.size() >= 2) {
    nFields = atoi(line[1].c_str());
  }
  if (!f.findTokenLine(line, "BEGIN_DATA_FORMAT"))
    return false;
  if (!f.parseNextLine(line)) {
    return false;
  }
  if (line.size() != nFields)
    return false;
  std::string lastSpace;
  std::vector<icValueVector> samples;
  std::vector<std::string> spaces;
  std::vector<icIndexName> names;
  int nSpace = 0;
  int nName = 0;
  int nId = -1;
  int nLabel = -1;
  int index = 0;
  for (auto fmt = line.begin(); fmt != line.end(); fmt++, index++) {
    if (*fmt == "SAMPLE_ID") {
      nId = index;
    }
    else if (*fmt == "SAMPLE_NAME") {
      nLabel = index;
    }
    else {
      std::string space;
      const char* szFmt = fmt->c_str();
      if (!strncmp(szFmt, "SRC_", 4)) {
        space += "SRC_";
        szFmt += 4;
      }
      if (!strcmp(szFmt, "NAME")) {
        space += "NAME";
        names.push_back(icIndexName(index, space));
      }
      else if (!strncmp(szFmt, "TINT", 4)) {
        space += "TINT";
        if (space != lastSpace) {
          icValueVector val(1);
          val[0].nIndex = index;
          val[0].space = icSigNamedData;
          samples.push_back(val);
          lastSpace = "";
        }
      }
      else if (!strncmp(szFmt, "RGB_", 4)) {
        space += "RGB";
        szFmt += 4;
        if (space != lastSpace) {
          lastSpace = space;
          icValueVector val(3);
          val[0].space = icSigRgbData;
          samples.push_back(val);
          spaces.push_back(space);
        }
        const char* szChannels[] = { "R", "G", "B" };
        setSampleIndex(samples, index, szFmt, &szChannels[0]);
      }
      else if (!strncmp(szFmt, "CMYK_", 5)) {
        space += "CMYK";
        szFmt += 5;
        if (space != lastSpace) {
          lastSpace = space;
          icValueVector val(4);
          val[0].space = icSigCmykData;
          spaces.push_back(space);
        }
        const char* szChannels[] = { "C", "M", "Y", "K" };
        setSampleIndex(samples, index, szFmt, &szChannels[0]);
      }
      else if (!strncmp(szFmt, "LAB_", 4)) {
      space += "LAB";
      szFmt += 4;
      if (space != lastSpace) {
        lastSpace = space;
        icValueVector val(4);
        val[0].space = icSigLabData;
        samples.push_back(val);
        spaces.push_back(space);
      }
      const char* szChannels[] = { "L", "A", "B" };
      setSampleIndex(samples, index, szFmt, &szChannels[0]);
      }
      else if (!strncmp(szFmt, "XYZ_", 4)) {
      space += "XYZ";
      szFmt += 4;
      if (space != lastSpace) {
        lastSpace = space;
        icValueVector val(4);
        val[0].space = icSigXYZData;
        samples.push_back(val);
        spaces.push_back(space);
      }
      const char* szChannels[] = { "X", "Y", "Z" };
      setSampleIndex(samples, index, szFmt, &szChannels[0]);
      }
      else {
      int nColor = -1;
      if (sscanf(szFmt, "%uCOLOR_", &nColor) && nColor >= 1) {
        char buf[30];
        sprintf(buf, "%uCOLOR", nColor);
        space += buf;
        if (space != lastSpace) {
          lastSpace = space;
          icValueVector val(nColor);
          val[0].space = (icColorSpaceSignature)(icSigNChannelData + (nColor & 0xffff));
          samples.push_back(val);
          spaces.push_back(space);
        }
        szFmt = strchr(szFmt, '_');
        if (szFmt) {
          szFmt++;
          int nChannel = atoi(szFmt);
          size_t last = samples.size() - 1;
          if (nChannel > 0 && samples[last].size() >= nChannel) {
            samples[samples.size() - 1][nChannel - 1].nIndex = index;
          }
        }
      }
      }
    }
  }
  if (!f.findTokenLine(line, "END_DATA_FORMAT"))
    return false;
  if (!f.findTokenLine(line, "NUMBER_OF_SETS"))
    return false;
  int nSets = 0;
  if (line.size() > 1) {
    nSets = atoi(line[1].c_str());
  }
  if (!f.findTokenLine(line, "BEGIN_DATA"))
    return false;
  do {
    if (!f.parseNextLine(line) || line[0] == "END_DATA")
      break;
    CIccCfgDataEntryPtr pData(new CIccCfgDataEntry);
    if (nId >= 0 && nId < line.size()) {
      pData->m_index = atoi(line[nId].c_str());
    }
    else if (nLabel >= 0 && nLabel < line.size()) {
      pData->m_label = line[nLabel];
    }
    if (names.size() > 0) {
      if (names[0].second == "NAME") {
        if (names[0].first >= 0)
          pData->m_name = line[names[0].first];
        if (names.size() > 1) {
          if (names[1].first >= 0)
            pData->m_srcName = line[names[1].first];
        }
      }
      else if (names[0].second == "SRC_NAME") {
        if (names[0].first >= 0)
          pData->m_srcName = line[names[0].first];
        if (names.size() > 1) {
          if (names[1].first >= 0)
            pData->m_name = line[names[1].first];
        }
      }
    }
    int nValueIdx;
    for (nValueIdx = 0; nValueIdx < samples.size(); nValueIdx++) {
      if (samples[nValueIdx][0].space == m_space)
        break;
    }
    if (nValueIdx != samples.size()) {
      for (int i = 0; i < samples[nValueIdx].size(); i++) {
        int nPos = samples[nValueIdx][i].nIndex;
        if (nPos < line.size()) {
          pData->m_values.push_back((icFloatNumber)atof(line[nPos].c_str()));
        }
      }
    }
    else {
      for (nValueIdx = 0; nValueIdx < spaces.size(); nValueIdx++) {
        if (strncmp(spaces[nValueIdx].c_str(), "SRC_", 4))
          break;
      }
      if (nValueIdx != spaces.size() && nValueIdx < samples.size()) {
        m_space = samples[nValueIdx][0].space;
        for (int j = 0; j < samples[nValueIdx].size(); j++) {
          int nPos = samples[nValueIdx][j].nIndex;
          if (nPos < line.size()) {
            pData->m_values.push_back((icFloatNumber)atof(line[nPos].c_str()));
          }
        }
      }
    }
    int nSrcIndex;
    for (nSrcIndex = 0; nSrcIndex < samples.size(); nSrcIndex++) {
      if (samples[nSrcIndex][0].space == m_srcSpace)
        break;
    }
    if (nSrcIndex != samples.size() && nSrcIndex != nValueIdx) {
      for (int i = 0; i < samples[nSrcIndex].size(); i++) {
        int nPos = samples[nSrcIndex][i].nIndex;
        if (nPos < line.size()) {
          pData->m_values.push_back((icFloatNumber)atof(line[nPos].c_str()));
        }
      }
    }
    else {
      for (nSrcIndex = 0; nSrcIndex < spaces.size(); nSrcIndex++) {
        if (!strncmp(spaces[nValueIdx].c_str(), "SRC_", 4))
          break;
      }
      if (nSrcIndex != spaces.size() && nSrcIndex < samples.size()) {
        m_srcSpace = samples[nSrcIndex][0].space;
        for (int j = 0; j < samples[nValueIdx].size(); j++) {
          int nPos = samples[nValueIdx][j].nIndex;
          if (nPos < line.size()) {
            pData->m_srcValues.push_back((icFloatNumber)atof(line[nPos].c_str()));
          }
        }
      }
      else {
        for (nSrcIndex = 0; nSrcIndex < samples.size(); nSrcIndex++) {
          if (nSrcIndex != nValueIdx)
            break;
        }
        if (nSrcIndex < samples.size()) {
          m_srcSpace = samples[nSrcIndex][0].space;
          for (int j = 0; j < samples[nValueIdx].size(); j++) {
            int nPos = samples[nValueIdx][j].nIndex;
            if (nPos < line.size()) {
              pData->m_srcValues.push_back((icFloatNumber)atof(line[nPos].c_str()));
            }
          }
        }
      }
    }
    if (pData->m_values.size() || pData->m_srcValues.size() || pData->m_name.size() || pData->m_srcName.size())
      m_data.push_back(pData);
    else
      pData.reset();
  } while (!f.isEOF());
  return m_data.size() == nSets;
}
References CIccIt8Parser::findTokenLine(), icSigCmykData, icSigLabData, icSigNamedData, icSigNChannelData, icSigRgbData, icSigXYZData, CIccIt8Parser::isEOF(), m_data, CIccCfgDataEntry::m_index, CIccCfgDataEntry::m_label, CIccCfgDataEntry::m_name, m_space, CIccCfgDataEntry::m_srcName, m_srcSpace, CIccCfgDataEntry::m_srcValues, CIccCfgDataEntry::m_values, CIccIndexValue::nIndex, CIccIt8Parser::open(), CIccIt8Parser::parseNextLine(), reset(), setSampleIndex(), and CIccIndexValue::space.
fromJson()
bool CIccCfgColorData::fromJson (json obj, bool bReset = false)
{
  if (!j.is_object())
    return false;
  if (bReset)
    reset();
  std::string str;
  jsonToColorSpace(j["space"], m_space);
  if (jsonToValue(j["encoding"], str))
    m_encoding = icSetJsonColorEncoding(str.c_str());
  jsonToColorSpace(j["srcSpace"], m_srcSpace);
  if (jsonToValue(j["srcEncoding"], str))
    m_srcEncoding = icSetJsonColorEncoding(str.c_str());
  if (j.find("data")!=j.end()) {
    json data = j["data"];
    if (data.is_array()) {
      for (auto d = data.begin(); d != data.end(); d++) {
        if (d->is_object()) {
          CIccCfgDataEntryPtr entry(new CIccCfgDataEntry);
          if (entry->fromJson(*d)) {
            m_data.push_back(entry);
          }
          else
            entry.reset();
        }
      }
    }
  }
  return true;
}
References CIccCfgDataEntry::fromJson(), icSetJsonColorEncoding(), jsonToColorSpace(), jsonToValue(), m_data, m_encoding, m_space, m_srcEncoding, m_srcSpace, and reset().
Referenced by main().
fromLegacy()
bool CIccCfgColorData::fromLegacy (const char * filename, bool bReset = false)
{
  if (bReset)
    reset();
  std::ifstream InputData(filename);
  if (!InputData) {
    return false;
  }
  int tempBufSize = 20000;
  icChar ColorSig[7], *tempBuf = new icChar[tempBufSize];
  if (!tempBuf)
    return false;
  InputData.getline(tempBuf, tempBufSize);
  int i;
  for (i = 0; (i < 4 || tempBuf[i + 1] != '\'') && i < 6; i++) {
    ColorSig[i] = tempBuf[i + 1];
  }
  for (; i < 7; i++)
    ColorSig[i] = '\0';
  //Init source number of samples from color signature is source data file
  m_srcSpace = (icColorSpaceSignature)icGetSigVal(ColorSig);
  int nSamples = icGetSpaceSamples(m_srcSpace);
  if (m_srcSpace != icSigNamedData) {
    if (!nSamples) {
      delete[] tempBuf;
      return false;
    }
  }
  InputData.getline(tempBuf, tempBufSize);
  sscanf(tempBuf, "%s", tempBuf);
  //Setup source encoding
  m_encoding = CIccCmm::GetFloatColorEncoding(tempBuf);
  if (m_encoding == icEncodeUnknown) {
    delete[] tempBuf;
    return false;
  }
  char SrcNameBuf[256];
  int nSrcSamples = icGetSpaceSamples(m_srcSpace);
  CIccPixelBuf Pixel(nSrcSamples + 16);
  while (!InputData.eof()) {
    CIccCfgDataEntryPtr data(new CIccCfgDataEntry());
    //Are names coming is as an input?
    if (m_srcSpace == icSigNamedData) {
      InputData.getline(tempBuf, tempBufSize);
      if (!ParseName(SrcNameBuf, tempBuf))
        continue;
      data->m_name = SrcNameBuf;
      icChar* numptr = strstr(tempBuf, "\" }");
      if (numptr)
        numptr += 3;
      icFloatNumber tint;
      if (!ParseNextNumber(tint, &numptr))
        tint = 1.0;
      data->m_values.push_back(tint);
    }
    else { //pixel sample data coming in as input
      InputData.getline(tempBuf, tempBufSize);
      if (!ParseNumbers(Pixel, tempBuf, nSamples))
        continue;
      for (int n = 0; n < nSamples; n++) {
        data->m_values.push_back(Pixel[n]);
      }
    }
    m_data.push_back(data);
  }
  delete[] tempBuf;
  return true;
}
References CIccCfgDataEntry::CIccCfgDataEntry(), CIccPixelBuf::CIccPixelBuf(), icGetSigVal(), icGetSpaceSamples(), icSigNamedData, m_data, m_encoding, CIccCfgDataEntry::m_name, m_srcSpace, CIccCfgDataEntry::m_values, CIccPixelBuf::operator[](), ParseName(), ParseNextNumber(), ParseNumbers(), and reset().
Referenced by main().
reset()
void CIccCfgColorData::reset ()
{
  m_space = icSigUnknownData;
  m_encoding = icEncodeValue;
  m_srcSpace = icSigUnknownData;
  m_srcEncoding = icEncodeValue;
  m_data.clear();
}
References m_data, m_encoding, m_space, m_srcEncoding, and m_srcSpace.
Referenced by CIccCfgColorData(), fromIt8(), fromJson(), and fromLegacy().
spaceName()
std::string CIccCfgColorData::spaceName (icColorSpaceSignature sig) protected
{
  switch (sig) {
    case icSigRgbData:
      return "RGB";
    case icSigCmyData:
      return "CMY";
    case icSigCmykData:
      return "CMYK";
    case icSigDevXYZData:
    case icSigXYZData:
      return "XYZ";
    case icSigDevLabData:
    case icSigLabData:
      return "LAB";
    case icSigNamedData:
      return "TINT";
    default:
    {
      int nSamples = icGetSpaceSamples(sig);
      char buf[32];
      sprintf(buf, "%dCOLOR", nSamples);
      return buf;
    }
  }
}
References icGetSpaceSamples(), icSigCmyData, icSigCmykData, icSigLabData, icSigNamedData, icSigRgbData, and icSigXYZData.
Referenced by toIt8().
toIt8()
bool CIccCfgColorData::toIt8 (const char * filename, icUInt8Number nDigits, icUInt8Number nPrecision)
{
  if (!m_data.size())
    return false;
  FILE* f;
  char fmt[64];
  if (!nDigits)
    sprintf(fmt, " %%.%df", nPrecision);
  else
    sprintf(fmt, " %%%d.%df", nDigits, nPrecision);
  auto first = m_data.begin();
  CIccCfgDataEntry* pEntry = first->get();
  std::string dataFormat;
  int nFields = 0;
  bool bShowIndex = false;
  bool bShowLabel = false;
  bool bShowSrcName = false;
  bool bShowSrcValues = false;
  bool bShowName = false;
  bool bShowValues = false;
  int nSrcSamples = 0, nDstSamples = 0;
  if (pEntry->m_index >= 0) {
    dataFormat = "INDEX";
    nFields = 1;
    bShowIndex = true;
  }
  if (pEntry->m_label.size()) {
    if (nFields) dataFormat+="\t";
    dataFormat += "SAMPLE_ID";
    nFields++;
    bShowLabel = true;
  }
  bool bSameSpace = spaceName(m_space) == spaceName(m_srcSpace);
  if (pEntry->m_name.size()) {
    if (nFields) dataFormat += "\t";
    dataFormat += "NAME";
    nFields++;
    bShowName = true;
  }
  if (m_space != icSigUnknownData) {
    addFields(dataFormat, nFields, nDstSamples, m_space, "");
    if (nDstSamples)
      bShowValues = true;
  }
  if (pEntry->m_srcName.size()) {
    if (nFields) dataFormat += "\t";
    if (bSameSpace)
      dataFormat += "SRC_";
    dataFormat += "NAME";
    nFields++;
    bShowSrcName = true;
  }
  if (m_srcSpace != icSigUnknownData) {
    addFields(dataFormat, nFields, nSrcSamples, m_srcSpace, bSameSpace ? "SRC_" : "");
    if (nSrcSamples)
      bShowSrcValues = true;
  }
  if (!nFields)
    return false;
  if (!filename || !filename[0])
    f = stdout;
  else
    f = fopen(filename, "wt");
  if (!f)
    return false;
  fprintf(f, "CGATS.17\n");
  fprintf(f, "ORIGINATOR\t\"DemoIccMAX\"\n");
  fprintf(f, "FILE_DESCRIPTOR\t\"Color Data\"\n");
  fprintf(f, "NUMBER_OF_FIELDS\t%d\n", nFields);
  fprintf(f, "BEGIN_DATA_FORMAT\n");
  fprintf(f, "%s\n", dataFormat.c_str());
  fprintf(f, "END_DATA_FORMAT\n");
  fprintf(f, "NUMBER_OF_SETS\t%u\n", (int)m_data.size());
  CIccCfgDataEntry blank;
  char buf[256];
  fprintf(f, "BEGIN_DATA\n");
  for (auto e = m_data.begin(); e != m_data.end(); e++) {
    std::string line;
    CIccCfgDataEntry* pEntry = e->get();
    if (!pEntry)
      pEntry = &blank;
    if (bShowIndex) {
      sprintf(buf, "%d", pEntry->m_index);
      line += buf;
    }
    if (bShowLabel) {
      if (line.size()) line += "\t";
      if (!pEntry->m_label.size())
        line += "\"\"";
      else
        line += pEntry->m_label;
    }
    if (bShowName) {
      if (line.size()) line += "\t";
      if (!pEntry->m_name.size())
        line += "\"\"";
      else
        line += pEntry->m_name;
    }
    if (bShowValues) {
      if (line.size()) line += "\t";
      for (int i = 0; i < nDstSamples; i++) {
        icFloatNumber v = i >= pEntry->m_values.size() ? 0 : pEntry->m_values[i];
        sprintf(buf, fmt, v);
        if (i)
          line += "\t";
        line += buf;
      }
    }
    if (bShowSrcName) {
      if (line.size()) line += "\t";
      if (!pEntry->m_srcName.size())
        line += "\"\"";
      else
        line += pEntry->m_srcName;
    }
    if (bShowSrcValues) {
      if (line.size()) line += "\t";
      for (int i = 0; i < nSrcSamples; i++) {
        icFloatNumber v = i >= pEntry->m_srcValues.size() ? 0 : pEntry->m_srcValues[i];
        sprintf(buf, fmt, v);
        if (i)
          line += "\t";
        line += buf;
      }
    }
    fprintf(f, "%s\n", line.c_str());
  }
  fprintf(f, "END_DATA\n");
  if (f != stdout)
    fclose(f);
  return true;
}
References addFields(), m_data, CIccCfgDataEntry::m_index, CIccCfgDataEntry::m_label, CIccCfgDataEntry::m_name, m_space, CIccCfgDataEntry::m_srcName, m_srcSpace, CIccCfgDataEntry::m_srcValues, CIccCfgDataEntry::m_values, and spaceName().
Referenced by main().
toJson()
void CIccCfgColorData::toJson (json & obj) const
{
  char buf[32];
  obj["space"] = icGetColorSigStr(buf, m_space);
  obj["encoding"] = icGetJsonFloatColorEncoding(m_encoding);
  obj["srcSpace"] = icGetColorSigStr(buf, m_srcSpace);
  obj["srcEncoding"] = icGetJsonFloatColorEncoding(m_srcEncoding);
  json data;
  for (auto e = m_data.begin(); e != m_data.end(); e++) {
    CIccCfgDataEntry *pData = e->get();
    if (!pData)
      continue;
    json entry;
    pData->toJson(entry);
    if (entry.is_object())
      data.push_back(entry);
  }
  if (data.is_array() && data.size()) {
    obj["data"] = data;
  }
}
References icGetColorSigStr(), icGetJsonFloatColorEncoding(), m_data, m_encoding, m_space, m_srcEncoding, m_srcSpace, and CIccCfgDataEntry::toJson().
Referenced by main().
toLegacy()
bool CIccCfgColorData::toLegacy (const char * filename, CIccCfgProfileSequence * pProfiles, icUInt8Number nDigits, icUInt8Number nPrecision, bool bShowDebug = false)
{
  FILE* f;
  char tempBuf[256];
  char fmt[20];
  if (!nDigits)
    sprintf(fmt, " %%.%df", nPrecision);
  else
    sprintf(fmt, " %%%d.%df", nDigits, nPrecision);
  if (!filename || !filename[0])
    f = stdout;
  else
    f = fopen(filename, "wt");
  if (!f)
    return false;
  std::string out;
  sprintf(tempBuf, "%s\t; ", icGetColorSig(tempBuf, m_space, false));
  out = tempBuf;
  out += "Data Format\n";
  fwrite(out.c_str(), out.size(), 1, f);
  sprintf(tempBuf, "%s\t; ", CIccCmm::GetFloatColorEncoding(m_encoding));
  out = tempBuf;
  out += "Encoding\n\n";
  fwrite(out.c_str(), out.size(), 1, f);
  out = ";Source Data Format: ";
  sprintf(tempBuf, "%s\n", icGetColorSig(tempBuf, m_srcSpace, false));
  out += tempBuf;
  fwrite(out.c_str(), out.size(), 1, f);
  out = ";Source Data Encoding: ";
  sprintf(tempBuf, "%s\n", CIccCmm::GetFloatColorEncoding(m_srcEncoding));
  out += tempBuf;
  fwrite(out.c_str(), out.size(), 1, f);
  fprintf(f, ";Source data is after semicolon\n");
  if (pProfiles) {
    fprintf(f, "\n;Profiles applied\n");
    for (auto pIter = pProfiles->m_profiles.begin(); pIter != pProfiles->m_profiles.end(); pIter++) {
      CIccCfgProfile* pProf = pIter->get();
      if (!pProf)
        continue;
      if (pProf->m_pccFile.size()) {
        fprintf(f, "; %s -PCC %s\n", pProf->m_iccFile.c_str(), pProf->m_pccFile.c_str());
      }
      else {
        fprintf(f, "; %s\n", pProf->m_iccFile.c_str());
      }
    }
  }
  fprintf(f, "\n");
  for (auto dIter = m_data.begin(); dIter != m_data.end(); dIter++) {
    CIccCfgDataEntry* pData = dIter->get();
    if (!pData)
      continue;
    if (bShowDebug && pData->m_debugInfo.size()) {
      for (auto l = pData->m_debugInfo.begin(); l != pData->m_debugInfo.end(); l++) {
        fprintf(f, "; %s\n", l->c_str());
      }
    }
    if (pData->m_name.size()) {
      fprintf(f, "{ \"%s\" }\t;", pData->m_name.c_str());
    }
    else {
      for (int i = 0; i < pData->m_values.size(); i++) {
        fprintf(f, fmt, pData->m_values[i]);
      }
      fprintf(f, "\t;");
    }
    if (pData->m_srcName.size()) {
      fprintf(f,"{ \"%s\" }", pData->m_srcName.c_str());
      if (pData->m_srcValues.size() && pData->m_srcValues[0] != 1.0) {
        fprintf(f, fmt, pData->m_srcValues[0]);
      }
    }
    else {
      for (int i = 0; i < pData->m_srcValues.size(); i++) {
        fprintf(f, fmt, pData->m_srcValues[i]);
      }
    }
    fprintf(f, "\n");
  }
  if (f != stdout)
    fclose(f);
  return true;
}
References icGetColorSig(), m_data, CIccCfgDataEntry::m_debugInfo, m_encoding, CIccCfgProfile::m_iccFile, CIccCfgDataEntry::m_name, CIccCfgProfile::m_pccFile, CIccCfgProfileSequence::m_profiles, m_space, m_srcEncoding, CIccCfgDataEntry::m_srcName, m_srcSpace, CIccCfgDataEntry::m_srcValues, and CIccCfgDataEntry::m_values.
Referenced by main().
Field Documentation
m_data
CIccCfgDataEntryList CIccCfgColorData::m_data
Referenced by fromIt8(), fromJson(), fromLegacy(), main(), reset(), toIt8(), toJson(), and toLegacy().
m_encoding
icFloatColorEncoding CIccCfgColorData::m_encoding
Referenced by fromJson(), fromLegacy(), main(), reset(), toJson(), and toLegacy().
m_space
icColorSpaceSignature CIccCfgColorData::m_space
Referenced by fromIt8(), fromJson(), main(), reset(), toIt8(), toJson(), and toLegacy().
m_srcEncoding
icFloatColorEncoding CIccCfgColorData::m_srcEncoding
Referenced by fromJson(), main(), reset(), toJson(), and toLegacy().
m_srcSpace
icColorSpaceSignature CIccCfgColorData::m_srcSpace
Referenced by fromIt8(), fromJson(), fromLegacy(), main(), reset(), toIt8(), toJson(), and toLegacy().
The documentation for this class was generated from the following files:
Tools/CmdLine/IccCommon/IccCmmConfig.h
Tools/CmdLine/IccCommon/IccCmmConfig.cpp